### ISSUE TITLE
Steam sync fails with 429

### ISSUE THREAD

**Issue by colecash122** [JosefNemec/Playnite#1003]
Just opened Playnite and Steam is refusing to update my library and returns error code 429 in [notifications](https://imgur.com/a/aSr90kt).

**Comment by JosefNemec** [comment]
Does it work if you wait a while? There's a limit on how many call can be made to Steam API and we probably reached it. You can also provide your own API key in settings to go around the shared limit.

**Comment by JosefNemec** [comment]
Closing, no response from original reporter.
