### ISSUE TITLE
“Export Library” doesn’t put Epic in CSV

### ISSUE THREAD

**Issue by jamesgecko** [JosefNemec/Playnite#1009]
When using the “Export Library” extension in a library linked to the Epic game store, the resulting CSV does not include “Epic” in the store column. Instead, rows for games from Epic contain a blank field in the store column.

Here’s an example with Shadow Complex:

```
"Amnesia: The Dark Descent","Steam","9/8/2010 12:00:00 AM","0","False"
"Shadow Complex Remastered",,"3/16/2016 12:00:00 AM","0","False"
"Grey Goo","Steam",,"0","False"
"Astebreed: Definitive Edition","Steam","5/30/2014 12:00:00 AM","1080","False"
"Mass Effect: Andromeda","Origin","3/22/2017 7:00:00 PM","0","True"
```

**Comment by psychonic** [comment]
Looks like a simple fix. I created PR #1010 for it, but I think it may only affect future games imported from the Epic Games Launcher.

**Comment by jamesgecko** [comment]
Awesome. Thank you!

**Comment by JosefNemec** [comment]
Yes it won't be applied retrospectively to already imported games, but you can always edit the Source manually for games that are missing it.
