### ISSUE TITLE
Keeps downloading images and gamedetails

### ISSUE THREAD

**Issue by Binkie88** [JosefNemec/Playnite#101]
I have tried this program since the 1.0 release. Ever since i have it keeps downloading images and gamedetails. It stops after a time but when i reopen Playnite it starts again. 
As far as i can see it is not adding any new data at this point but i still have quite a few missing details and images.

https://pastebin.com/uRkU9muM This is a partial of the playnite.log

**Comment by JosefNemec** [comment]
Fix released in version 1.3
