### ISSUE TITLE
Adding additional actions as buttons under "Play"

### ISSUE THREAD

**Issue by kpd328** [JosefNemec/Playnite#1021]
Currently extra actions are only found under the "more" or context menu. I personally use the extra actions to merge multiple instances of a single game (for instance, and N64 rom and it's Wii Virtual Console port or different translations of a rom), so the ability to essentially have more than one "play" button would help streamline this scenario.

**Comment by NoShotz** [comment]
Yeah, I do something similar when a game has multiple modes, but each are a separate executable For example Crackdown 3 Campaign and Crackdown 3 Wrecking Zone, I added wrecking zone as a secondary action, but due to this it does not track play time for it.

**Comment by JosefNemec** [comment]
Will be done as part of #272
