### ISSUE TITLE
Issues with certains itch.io games

### ISSUE THREAD

**Issue by ClearStrelok** [JosefNemec/Playnite#1022]
Diag package:

74a3b759-4f3b-41c2-88a5-298b6f37fa10

When launching the itch.io version of ZeroRanger trough Playnite, the window is not minimized as it should and Play Time is not recorded properly. The Game Monitoring seems to get stuck at launch and doesn't detect that the game has been closed. Trying to close the monitoring manually also freezes Playnite, but I've noticed that killing the itch.io helper process beforehand prevents that.

This happen regardless of whether the itch.io client is already running or not, but other games (Shattered Realms in my case) are fine so it doesn't seem to affect everything.

**Comment by JosefNemec** [comment]
I don't own the game so I can't test it myself, but can look if there's `.itch.toml` file inside game's installation folder and attach it here? Thank you

**Comment by ClearStrelok** [comment]
Unfortunately there doesn't seem to be anything other than the game executable, a readme and this archive : 
[receipt.json.gz](https://github.com/JosefNemec/Playnite/files/2894909/receipt.json.gz)

**Comment by JosefNemec** [comment]
I've tried demo version and it seems to work properly, I'm not sure what's different in full version that could cause this.

**Comment by ClearStrelok** [comment]
I did a few more tests with the full game after reimporting it and the launch process does seem to be monitored properly on a completely random basis. It works perfectly once (generally after a fresh boot of the computer) and breaks at every subsequent launch attempt.

At least I'm pretty much sure that the issue seems to come from the itch.io butler (as killing its process at least prevents a crash when attempting to cancel the monitoring).

**Comment by JosefNemec** [comment]
Can you please retest it with the demo version to see if the issue applies to it as well? If the issue is in butler then in theory the official Itch app should show similar symptoms, unless issue is in out integration of butler.

**Comment by ClearStrelok** [comment]
There seem to be no issues with the demo.

**Comment by ClearStrelok** [comment]
Just had similar issues with the freeware Roguelight : 
https://managore.itch.io/roguelight

I've also noticed that Shattered Realms, which is so far the only game in my library that works with no issues, has this notification under the "manage" tab :

![sans titre-2](https://user-images.githubusercontent.com/38838369/53302955-df8dad80-3864-11e9-85f2-97d68e33df9e.jpg)

Which is absent from both ZeroRanger and Roguelight. I'm not sure this is even remotely related, but that's something they have in common.

**Comment by JosefNemec** [comment]
I can't reproduce it with Roguelight (both Roguelight and Roguelight (SPOOKY)). I'm not sure what "Powered by butler" means exactly, but other games that don't have it work for me as well (Afterlife for example).

**Comment by ClearStrelok** [comment]
The issue has ceased as of 4.74 but I have no idea how that's possible given that this update didn't appear to change anything related to the itch.io app. 

My guess is that a problematic file on my end has been replaced, but I've reinstalled Playnite and the Itch app a couple of times and to no avail before opening that issue, so I'm not sure what is up with that.

**Comment by ClearStrelok** [comment]
I'm re-opening this as the issue has show up again in several occasions. At some point that I have yet to pinpoint, the handling of the monitoring process basically becomes broken. Re-installing the Itch.io application temporarily fix the issue and games are properly monitored again, but this starts again eventually.
