### ISSUE TITLE
Playnite window offscreen if monitor disconnected

### ISSUE THREAD

**Issue by bburky** [JosefNemec/Playnite#1024]
The Playnite window doesn't appear if the program was exited while the window was on a second monitor that is no longer connected. The window is offscreen and inaccessible.

Steps to reproduce:

1. Have two monitors connected
2. Exit Playnite while the window on the second screen.
3. Disconnect second monitor
4. Relaunch Playnite

It looks like you deliberately [don't call `CheckWindowBounds()`](https://github.com/JosefNemec/Playnite/blob/0d188678d556f4a976f7646c46438e47e6b0462b/source/PlayniteUI/WindowPositionHandler.cs#L34-L38) if the window is present in the config data. The problem is that the maximum screen size may no longer be the same.

**Comment by JosefNemec** [comment]
Done in 6.0
