### ISSUE TITLE
Adjustment to the application and GOG clearance

### ISSUE THREAD

**Issue by Crowley99hy** [JosefNemec/Playnite#1025]
Hello
I started testing the Playnite application just as soon as I tested it, it looks very promising. But there is one option that I didn't find when I made the adjustment. On GOG, I want the Galaxy application to start automatically and the game that is on this platform. I was able to successfully set up the Galaxy application for which automatically starts, but I can't do this action for the game on this platform.

At the moment the game in question has to start it manually. I turned to this Playnite application to centralize, but play and automate my GOG games with the Galaxy application

**Comment by JosefNemec** [comment]
To start game via GOG this must be true:
- Game is imported automatically (it won't work for manually added)
- `Play` action has `Managed by library plugin` option enabled
- `Start games using Galaxy client` option in "Settings-Libraies-GOG" is enabled
