### ISSUE TITLE
Option to open save folder

### ISSUE THREAD

**Issue by chocolatechipcats** [JosefNemec/Playnite#1027]
Would be nice if there was an option (similar to "open installation location") to input a game's save folder to add to the menu for easy access. This can already be done by adding a new URL action, but it seems to be a sensible addition.

Thanks in advance, and I understand if you decide against the idea.

**Comment by JosefNemec** [comment]
This is really cool idea. We could also pull automatically what the save path is from PCGamingWiki.

I'm also linking #124 to this since both need ability to specify what the save path is for each game.

**Comment by ArtexJay** [comment]
YES please! that would be amazing, would it be possible to make like a database where users would be able to add directories to the save location if PCGamingWiki does not have it? Cause i noticed they have a lot of save locations for Steam but not for anything else and a bit for locally downloaded games without steam.

**Comment by JosefNemec** [comment]
Closing for same reasons as #124. Too many issues making this reliable, mainly in terms of getting correct save folder.
