### ISSUE TITLE
"Abandoned" option for Completion Status for when you decide to never come back to a game. 

### ISSUE THREAD

**Issue by PsychoFoxOne** [JosefNemec/Playnite#1028]
Please use search first to see if the issue is already opened. Thank you

**Comment by darklinkpower** [comment]
May I suggest a few more to add?
* Playing
* On-hold (Useful if you won't abandon the game but want to stop playing for a while)
* Plan to Play

I think with the current ones and the ones suggested here should suffice for all scenarios.

**Comment by CriticalComposer** [comment]
Might I add one more: Endless or Null. Lots of retro games were designed without an end state and that concept is making a huge resurgence in the Games as a Service design.

**Comment by darklinkpower** [comment]
I don't know about everyone else, but in my opinion it would clutter the UI with so many options and while I agree there are "endless" games, the "playing" status would work in that case and you could simply switch between that and On-Hold.

**Comment by JosefNemec** [comment]
Done in 6.0
