### ISSUE TITLE
Battle.Net Game fail to login

### ISSUE THREAD

**Issue by Pycorax** [JosefNemec/Playnite#1030]
Battle.Net games fail to login after the game is launched with PlayNite. It seems that it is only able work if launched by the Battle.Net app itself.

Tested on Overwatch and Black Ops 4.

**Comment by JosefNemec** [comment]
Blizzard probably once again changed how games should be started outside of the launcher, I'll look into it.

**Comment by JosefNemec** [comment]
I'm unable to reproduce it if the game was automatically imported using Battle.net plugin. Did you add game manually or was it automatically imported?

**Comment by Pycorax** [comment]
So sorry, you're right, I had initially imported the game manually as the plugin didn't work when I first installed it. I tried it again and removed the manually added entries and it works now. Thanks!
