### ISSUE TITLE
Add online profile with our library

### ISSUE THREAD

**Issue by Bigaston** [JosefNemec/Playnite#1040]
Hello!
I want to know if it's possible to add a user profile to share our library. Something like https://playnite.link/u/Bigaston

Thanks!

**Comment by JosefNemec** [comment]
This won't probably get implemented using our backend solution, but instead there are plans to add option to link IGDB accounts and sync your library there. See #594

**Comment by Bigaston** [comment]
Okay! It can be very usefull! Thanks for this tool ! ^^

**Comment by vinguan** [comment]
This is a great suggestion, this could be very good for reviewers because they would be able to aggregate all their reviewed games into one plataform.

**Comment by JosefNemec** [comment]
I'm closing this since the feature will be added via #594

**Comment by cristianmtr** [comment]
Any plan on adding something like this to any other online platform? https://howlongtobeat.com/ or https://rawg.io/ ?

**Comment by Lacro59** [comment]
For HowLongToBeat, you can use a plugin: https://playnite.link/forum/thread-309.html
