### ISSUE TITLE
Mass-Tagging & Mass-Untagging

### ISSUE THREAD

**Issue by whismerhill** [JosefNemec/Playnite#1045]
hi,
so as the title says : 
I'm unaware if there's the ability to do some Tagging & Untagging of games in batch/group

for example one thing I'd like to do is remove tags I will never want to filter my games list on, such as :
"Steam Trading Cards", "Steam Cloud"  ....

Mostly to sanitize the amount of tags and/or add new tags quickly instead of doing your whole library of games 1 by 1

Thank you.

**Comment by JosefNemec** [comment]
This will be part of 5.0, I have the feature almost finished already.

**Comment by JosefNemec** [comment]
Done in 5.0
