### ISSUE TITLE
Metadata for manually added games (the 'Playnite library') can only be updated one by one in the edit window

### ISSUE THREAD

**Issue by Stuntaneous** [JosefNemec/Playnite#1047]
I need to go Edit > Download Metadata for every new manually imported game individually. Tools > Download Metadata doesn't work for these games. 

Somewhat related: Tools > Download Metadata doesn't save my preferences of metadata sources.

**Comment by JosefNemec** [comment]
Can you got `About` menu and create diag. package for me please? Thank you

**Comment by Stuntaneous** [comment]
efb1b6de-3be3-4e91-ae36-a6a4dea7f5e1

**Comment by JosefNemec** [comment]
Sadly I'm unable to reproduce it and there's nothing in your logs that would indicate some issue. Maybe you have games named in a way that Playnite is unable to link them to corresponding IGDB records (the game's name is used for database lookup). That's just about the only thing that could cause issues.

**Comment by Stuntaneous** [comment]
I've cleaned names to remove version numbers and version dates and some are picked up while some aren't. Some that aren't only have one, correct, exact option when done manually.

**Comment by JosefNemec** [comment]
I will need exact game names that are causing issues.

**Comment by JosefNemec** [comment]
Closing since requested names were not provided.
