### ISSUE TITLE
"Added" column is accurate only down to the day

### ISSUE THREAD

**Issue by Stuntaneous** [JosefNemec/Playnite#1048]
Would much appreciate greater accuracy.

**Comment by JosefNemec** [comment]
Is that really useful? Where would you actually use information that the game was added at 1 am or 2 pm etc.?

**Comment by Stuntaneous** [comment]
It helps to have sorting by time appear the same way between Windows Explorer and Playnite, in terms of my ability to organise and change metadata, especially when I'm often adding a number of games at a time.

**Comment by JosefNemec** [comment]
Done in Playnite 8.
