### ISSUE TITLE
Suppress connectivity error messages when no internet access

### ISSUE THREAD

**Issue by berserkwarwolf** [JosefNemec/Playnite#105]
DIAG PKG
[bug_when_no_internet.zip](https://github.com/JosefNemec/Playnite/files/1283056/bug_when_no_internet.zip)

What happens:
Playnite starts spewing all kinds of errors about not connected to Steam, GOG, whatever. And ultimately proposes submitting a bug report.

Expected Behaviour:
Let Playnite act just as Steam Offline mode. Notify the user about the lack of connectivity, and just use what is cached.

**Comment by JosefNemec** [comment]
For now you can disable "Download 3rd party library updates on startup" option in settings, but some kind of offline detection should be implemented.

**Comment by JosefNemec** [comment]
Was added in P10. Library update is completely skipped on startup if no internet connection is detected.
