### ISSUE TITLE
Playnite preventing game process from being terminated

### ISSUE THREAD

**Issue by Stuntaneous** [JosefNemec/Playnite#1054]
This happened with Metro Exodus. I ran the game, moments later I ended the process (in this case by sloppily clicking a lot and freaking Windows out enough to pop up the 'not responding' dialog), and then after the process was not ending I tried but was unable to kill the process through either Task Manager or with elevated command prompt and taskkill /F. "Access denied". Closing Playnite caused the game process to disappear.

**Comment by Stuntaneous** [comment]
102b2cb6-168e-4eca-9a74-da33d98bb3b3

**Comment by Stuntaneous** [comment]
This also occurs when a game crashes. The process only finally exits when I close Playnite.

**Comment by JosefNemec** [comment]
I don't have Metro Exodus to test this and I can't reproduce this with any other game I tried (from different launchers).

**Comment by JosefNemec** [comment]
I tried to reproduce this with Xbox App version of Metro Exodus and it worked for me properly.

**Comment by JosefNemec** [comment]
Is this still an issue with the latest Playnite version?

**Comment by falcorr** [comment]
#2184
