### ISSUE TITLE
Plugins development

### ISSUE THREAD

**Issue by NaolShow** [JosefNemec/Playnite#1055]
Hey, first thanks for your software!
Its very very usefull and I love it !

So, do you know if there is a way to retrieve the platform path of a game ?
I'm trying to retrieve the platform installation path (platform = origin,steam...) when the player close his game.

So I found that: 
game.PlatformId

But that is not what I want, there is a want to convert it to the platform name ?
Or there is a function to get platform installation path ? 
Thanks !

**Comment by bburky** [comment]
I think you're looking for the [`Source` property](https://playnite.link/docs/api/Playnite.SDK.Models.Game.html#Playnite_SDK_Models_Game_Source) on `Game` objects, it's a human readable string like "Steam" or "Origin". Do note that it may be empty, games added manually (not from a library plugin) will have it unset.

I'm not sure what you're asking about by platform installation path. Something like `C:\Program Files\Steam (x86)\` for Steam? Currently that's not a public API. If you're just looking for the path to the game's files that's the [`InstallDirectory` property](https://playnite.link/docs/api/Playnite.SDK.Models.Game.html#Playnite_SDK_Models_Game_InstallDirectory).

**Comment by JosefNemec** [comment]
There's currently no way how to get installation path of appropriate game launcher.

**Comment by NaolShow** [comment]
Thanks ! game.Source is good!

Thanks again for Playnite ;)
