### ISSUE TITLE
Battle.net sync rework

### ISSUE THREAD

**Issue by JosefNemec** [JosefNemec/Playnite#1057]
We currently use data provided by Blizzard's [account website](https://account.blizzard.com/overview), which has unfortunate side effect in login session not lasting very long and user is prompted to re-authenticate after some time (more info in #234).

We should ideally use API used by Battle.net launcher instead of Blizzard website for more robust solution.

**Comment by PiiSmith** [comment]
I think that a very similar issue is happening with Origin. Also there the session is not permanent/long living, but you have to login every time you start Playnite in order to update the library.

**Comment by JosefNemec** [comment]
For Origin there's a "Remember me" checkbox that you need to check. Anyways it should have been opened as separate issue since it has nothing to do with Battle.net.

**Comment by johnny5wd** [comment]
Perhaps a quick peek at https://github.com/FriendsOfGalaxy/galaxy-integration-battlenet could be helpful. The new GoG Galaxy client is open source, on GitHub and I don't experience the Battle.Net issue on that platform.

At the same time, perhaps you could contribute to GoG Galaxy's itch.io integration, as that one doesn't work reliably (Playnite's does but Playnite has the Battle.Net issue).

With the Activision takeover, presumably, Battle.Net releases might increase in frequency.

**Comment by JosefNemec** [comment]
I don't think this is critical to fix given the frequency new games are being released on Battle.net. You can disable import of uninstalled games after first sync to get rid of the error messages.

I don't plan to contribute to Galaxy project.

**Comment by johnny5wd** [comment]
Fair enough.

To be honest I don't think of it as critical at all (it is an annoyance however). I was just trying to be helpful and constructive by coming up with something other than criticism or rejected ideas, so I  thought since both projects are open source it could potentially help fix the issue / annoyance some time in the future / e.g. it wouldn't hurt to have a look at their Battle.Net plugin and how it's implemented - and thinking in terms of a fair exchange, that's all.

Don't worry, I'm aware of the history of this thread and the pushy response by some on that other thread and I totally agree with you credentials should NOT be stored by an application such as Playnite.

Like I said, was just trying to offer a possibly different (and positive/constructive) approach. I absolutely understand this project is already eating up waaay too much of your valuable time and appreciate the amazing work you're doing.

**Comment by darklinkpower** [comment]
@johnny5wd Playnite doesn't store credentials. Quoting the webpage and github page:

"**Privacy Statement**

Playnite doesn't store any user information and you don't need to provide any information to import installed games. Account connection process is usually done via official login web forms and only the web session cookies or tokens are stored, the same way when you login to those services via the web browser."

**Comment by johnny5wd** [comment]
@darklinkpower  Yes, absolutely I know that, and I completely agree with that. I was refering to the discussion [here](https://github.com/JosefNemec/Playnite/issues/234) where someone suggested storing could be a solution. I disagree with that solution but instead hinted to have a look at another project which doesn't seem to suffer from the same timeout issues (and it connects in a similar way as Playnite, as far as I know) for a possible solution in the future.

The session timeout problems discussed there are not present in that project, hence my suggestion to have a look. However I do understand it is extremely low priority and the workaround is simple (sync installed games only). No worries :)

**Comment by PoooMukkel** [comment]
Every time I open Playnite I have to login to Battle.net. May be you are able to fix this issue?

**Comment by JosefNemec** [comment]
@PoooMukkel I can't do anything about it right now. I recommend disabling import of uninstalled games, which shouldn't be an issue since new games are added to Bnet very rarely.

**Comment by SolomonCM** [comment]
i have followed the suggestion of unchecking import of uninstalled games for the battle.net plug-in, but at every start-up of play-nite, I still am getting the authentication error. only option selected for plugin is connect account. should i unselect this too?

**Comment by JosefNemec** [comment]
Yes, disable account connection as well.

**Comment by JosefNemec** [comment]
Done in `devel8`.
