### ISSUE TITLE
Support for removable devices with dynamic drive letter

### ISSUE THREAD

**Issue by Kvaell** [JosefNemec/Playnite#1065]
Hello,

Some of emulator's rom aren't synchronized anymore with playnite, playnite still list them, the roms are still in the same folder, but when launched through playnite, the rom cannot be launched, each emulator saying an error occurred while reading/loading it.

If launched from the emulator itself, no problem occurs but it doesn't work frol Playnite. 

When synchronize the rom with the emulator on playnite again, the roms appears twice as if it wasn't already synchronized. 
![error](https://user-images.githubusercontent.com/27021339/53898836-2c2d7180-4039-11e9-9152-009c0a02abf0.png)

Those roms are stored on a SD card. 

It happens mainly to emulator that I don't launch often.

**Comment by JosefNemec** [comment]
This apparently happens when games are stored on removable device (like SD Cards).

**Comment by JosefNemec** [comment]
Is the SD card being mounted always with the same drive letter? My guess is that this happens because the game was originally imported when SD card was mounted a `G:` and later it was mounted as something else. Is that the case?

**Comment by Kvaell** [comment]
I can confirm the letter doesn't change since Redream emulator doesn't have the issue, maybe for this emulator playnite make the emulator launch the roms straight away.

**Comment by Kvaell** [comment]
You are right, that's exactly what happening, but I don't know how Redream emulator is still working properly, as if the letter didn't changed.

**Comment by JosefNemec** [comment]
They must have built in mechanism to check other drives if the originally passed path doesn't exists. We could in theory do the same check before passing the value to an emulator and replace the path if necessary.

**Comment by Kvaell** [comment]
That would be great! Normally on the worst case only the drive changes, the folder stay the same so it should be quite fast for playnite to find on which drive it is.

**Comment by plug313** [comment]
I've been having lots of problems with this. I have tons of games installed on an external hard drive and every time the drive number changes I have to manually alter their installation directory/path all over again, and one at a time which is sort of painful! would love to see a solution.

**Comment by JosefNemec** [comment]
Can you check if there's a way to force Windows to mount specific devices under the same drive letter? I get your frustration, but if you tell some application to use certain folder path, and then that folder path changes, it's IMHO not really a job of that application to go and look where the folder was moved.

I'll try to add some lookup for drive letter change into post Playnite 8 update release, but I don't promise anything.

**Comment by plug313** [comment]
> Can you check if there's a way to force Windows to mount specific devices under the same drive letter? I get your frustration, but if you tell some application to use certain folder path, and then that folder path changes, it's IMHO not really a job of that application to go and look where the folder was moved.
> 
> I'll try to add some lookup for drive letter change into post Playnite 8 update release, but I don't promise anything.

thank you for your reply. I did some research and I don't think it's possible, but I found a sort of temporary solution, if I change the drive letter to a letter that isn't used very often like X or Z then it may not change too much. 
I understand and I agree that it's not really the program's job to find the games if they change location, but it would be a nice QOL feature, I'm thankful for you even considering it. I love your work.

**Comment by JosefNemec** [comment]
@MopsiMauser You can take a look at this. If you have additional questions then message me on Playnite's Discord server.

**Comment by MopsiMauser** [comment]
@JosefNemec ok. On which branch shall I work, devel?

**Comment by MopsiMauser** [comment]
@plug313 are you talking about games for specific emulators or about games for 3rd party clients like Steam, GOG,.... and so on?

**Comment by JosefNemec** [comment]
This should only apply to manually added games and emulated ones. Games from 3rd party launchers must keep using paths that those original clients report.

**Comment by Bluscream** [comment]
Couldnt you use drive id paths like `\\?\{uid}\path\to\file` ?

**Comment by JosefNemec** [comment]
That's just over-complicating it, we are going to enumerate through all connected drives and check if the path exists on one of them.

**Comment by JosefNemec** [comment]
Done in `devel`.
