### ISSUE TITLE
Can't find Steam library

### ISSUE THREAD

**Issue by OmegaER** [JosefNemec/Playnite#1066]
Hello, I tried to use both **Authenticated User** and **Account URL Name** for updating my library, but I always get the notification: "_No games found on specific Steam account_" for the first case and the "_404_" error for the second, if I put my entire URL. I didn't try the **Private Account** option, but I don't have any API key nor I don't know how to take it. Am I missing something? Can you help me with this, please?
Thank you in advance!

**Comment by JosefNemec** [comment]
See https://github.com/JosefNemec/Playnite/wiki/How-to-get-Steam-account-name

**Comment by OmegaER** [comment]
Sorry, I'm very stupid, apparently I was having restriction because of my profile privacy. I'll close the isse. Sorry again.
