### ISSUE TITLE
Option to start Epic games without the launcher

### ISSUE THREAD

**Issue by JosefNemec** [JosefNemec/Playnite#1068]
Apparently launching games from Epic Games launcher with the `-EpicPortal` argument makes it possible to launch the games without having the Epic Games client running.

**Comment by DennoCoil** [comment]
Turns out there's some games on the Epic store that is DRM-Free and you just launch the executable to the game directly.  The downside is you would have to test each game you download individually to see if it launches or not without Epic running.

**Comment by JosefNemec** [comment]
Done in `devel7`.
