### ISSUE TITLE
import games from itch.io

### ISSUE THREAD

**Issue by roney33** [JosefNemec/Playnite#107]
i wanna play games from itch.io too

**Comment by drewbitt** [comment]
so add them yourself as a custom game. itch.io doesn't keep track of what games you have downloaded, where you put them on your computer etc. so you just need to add them all as custom games. Put them all in a single folder and import the folder. Done.

**Comment by Snorrp** [comment]
Status?

**Comment by JosefNemec** [comment]
@Snorrp I didn't even look if this is technically possible, probably won't make it into 4.0

**Comment by notnsane** [comment]
Just wanted to show my support for this. If you need more help I'm sure you can contact any itch admins like leaf or fasterthanlime.

**Comment by fasterthanlime** [comment]
Quick update: Josef and I are in touch!

**Comment by lukakostic** [comment]
Sooo....

**Comment by JosefNemec** [comment]
> Sooo....

@lukakostic So what? Please only comment if you have anything to say about this specific issue. Your comment doesn't bring anything to the table. itch.io support is in progress with no ETA.

**Comment by TroudhuK** [comment]
"Butler executable not found."
![image](https://user-images.githubusercontent.com/11449740/52479752-f87e3980-2ba9-11e9-95f0-1a4e19c7dcc3.png)
My butler.exe is in %appdata%\itch\bin\ .

**Comment by JosefNemec** [comment]
@TroudhuK What itch client version do you have? The path Playnite uses is path recommend to me by itch.io developers and it should work with version 25 and newer.

**Comment by TroudhuK** [comment]
Ok, my version is up to date, v23.6.3, so I have to wait for the v25 deployment.

**Comment by JosefNemec** [comment]
I just installed the latest version and it's 25.4.0, maybe try manually reinstalling it.

**Comment by TroudhuK** [comment]
Yes, I downloaded the setup and overwrite my installation. This last version isn't accessible from itch update. It should be better. Thanks!

**Comment by lbacud** [comment]
I'm getting an error whenever I try to import games from itch, which reads "Failed to import games from itch.io. JSON integer 3355307335 is too large or small for an Int32. Path 'result.items[0].installInfo.installedSize', line 1, position 1017

**Comment by JosefNemec** [comment]
@lbacud reported separately in #982

**Comment by fasterthanlime** [comment]
> Ok, my version is up to date, v23.6.3, so I have to wait for the v25 deployment.

@TroudhuK that one's on me, sorry. The install/update system changed completely between v23 and v25. There is a banner that shows up in v23 that says to install v25 manually, but it might only show up on the itch frontpage. I might work on something better now that we're confident v25 works for most people.

**Comment by TroudhuK** [comment]
@fasterthanlime ok no problem. Is there any "how to" for the 23 => 25 upgrade? I had to re-import games, reinstall some of them (because the folder name is not the same, ex: "ONE SHOT" => "one-shot")...

**Comment by fasterthanlime** [comment]
> ok no problem. Is there any "how to" for the 23 => 25 upgrade? I had to re-import games, reinstall some of them (because the folder name is not the same, ex: "ONE SHOT" => "one-shot")...

Well, this isn't really the right thread for this, but: v25 imports game install from v23 (on startup, and you can request it explicitly in install locations). The install folder name doesn't matter. It will not import entries where the game or the upload has been deleted since (or you somehow lost access to them). There's an open issue at https://github.com/itchio/itch/issues/2238 for that.
