### ISSUE TITLE
Be able to manually create new Libraries for Rom categories

### ISSUE THREAD

**Issue by Onionhorse** [JosefNemec/Playnite#1072]
I don't have issues with adding one by one of my old roms, but it seems like everything gets added into the Playnite folder and it would be cool if i could separate them into Folders under the name of NES, SNES or Playstation, unless its there and i am not seeing it

**Comment by JosefNemec** [comment]
You can use `Platforms` field for that purpose.

**Comment by JosefNemec** [comment]
I'm closing this for now since filtering/grouping using `Platform` field should serve the same purpose. If it's not what you were looking for then please describe in more detail your requirement.
