### ISSUE TITLE
Close all 3rd party launchers when closing Playnite or when game exits

### ISSUE THREAD

**Issue by MagnavoxTG** [JosefNemec/Playnite#1073]
So basically it would be nice if all the 3rd party launchers like Steam, Origin, etc... that are synced with Playnite would be closed once Playnite is closed so you dont have to close them all manually once you are finished with your gaming session.

**Comment by MohandL3G** [comment]
Or atleast close it when you close the game, I used lutris on Ubutnu and it had this great feature

**Comment by JosefNemec** [comment]
Linking #833 to this.

The problem I see with this is finding a proper way how to gracefully shutdown the client. My guess is that most of them probably don't have built-in way how to shutdown them externally. Force killing them could cause various issues, for example if the client is in the middle of uploading cloud saves.

Overall I agree that this would be really helpful primarily for low power/memory devices.

**Comment by MagnavoxTG** [comment]
@MohandL3G Well its not exactly the same because sometimes you want launchers to stay open. For example Steam for the chat or because you want to be able to get invited to games by friends. Closing the launcher right after the game closes is not the same just want to make the distinction clear so that this doesnt get linked to something thats similar but not the same.

**Comment by MagnavoxTG** [comment]
@JosefNemec Ohh I see so the problem lies with the 3rd party launcher because they do not provide an easy way to shut them down. Well lets hope there is a way around that because that would just be a really nice quality of life feature and help make it feel more like an all in one launcher.

**Comment by daniel-j** [comment]
Steam has a `-shutdown` cli flag. `Steam.exe -shutdown` starts a graceful shutdown of Steam (same as choosing exit in Steam's menu.)

**Comment by MohandL3G** [comment]
@MagnavoxTG Yea, so what if you need the chat even after closing Playnite and Playnite close steam?
you can simply run steam again.
or we might need to exits:
1. Exit
2. Exit and Close Clients
or in the options where we can enable or disable it.
also when you first install and run Playnite it ask you if you want to enable/disable it.

**Comment by JosefNemec** [comment]
@daniel-j Thanks, that's a really useful information. If we could get some solution for all currently supported launchers that would be great.

@MohandL3G If we add this, then it would be configurable on per library/launcher basis. So you could technically set it up in a way that it would close all known launchers but Steam.

**Comment by Dasnap** [comment]
@JosefNemec I'm at work at the moment so I can't check, but I'll say what I remember from my own testing/investigating anyway. 

With Uplay specifically, it seems to run multiple different services/programs while active. One of them is called UbisoftGameLauncher.exe. From my testing, **this only runs when a game is running or is cloud syncing.** This could possibly be used as a trigger for when to force-shutdown the client. 

Personally, I use it as a trigger for DisplayFusion so it knows to de-minimize Uplay after a Steam bought Uplay game closes, thus reminding me to close the client. 

I'm sure you can give it some testing also. I might be wrong about the cloud-sync part, but Uplay only seems to pop up for me after the cloud sync window disappears. 

Keep it up man, you're doing God's work.

**Comment by JosefNemec** [comment]
Playnite now supports auto-closing of 3rd party launchers since version 7. If you need additional apps closed then you can write a script extension for it.
