### ISSUE TITLE
Battle.net authentication not working

### ISSUE THREAD

**Issue by JosefNemec** [JosefNemec/Playnite#1075]
Something probably changed on Blizzard's website. Login button currently doens't do anything in Playnite.

**Comment by vinguan** [comment]
I was going to report this. It works the first time but it does not save the authentication. Is there a fix yet?

**Comment by JosefNemec** [comment]
If the login works first time then it's a different issue, see #1057

**Comment by JosefNemec** [comment]
Not an issue anymore.
