### ISSUE TITLE
Feature Request: Import from a simple text list of game titles.

### ISSUE THREAD

**Issue by Hashnoob** [JosefNemec/Playnite#1076]
Hey Josef,

I just found playnite it's pretty amazing, so thank you for you work on it. I think it would be a great addition to PN to be able to import a list of games from a .txt file.

Is there anyway to accomplish this task at this moment that I may have missed?

Example.txt
- 1: Title Title 1
- 2: Title Title 2
- ...
- 1000: Title Title etc

**Comment by JosefNemec** [comment]
There's no built-in functionality for something like this since the text file format could be different from one person to another depending on their use case. However you can write a [simple script](https://playnite.link/docs/) to import games from whatever file format you want.

**Comment by Hashnoob** [comment]
Thanks for the reply, I finally figured out how to do it in something that's not ahk. It worked out out great got about 900 out of around 1100 titles right.

For anyone else who needs a quick script here you go.

```python
def TextImport():
	path = PlayniteApi.Dialogs.SelectFile("TXT|*.txt")
	file = open(path)
	line = file.readline()
	while line:
	    new_game = Game(line)
	    PlayniteApi.Database.AddGame(new_game)
	    line = file.readline()
	file.close()
```

**Comment by JosefNemec** [comment]
Thanks for the code snippet. I'm going to close this issue since I don't think we could add this as native functionality because of how many formats people can store their lists in.
