### ISSUE TITLE
Name labels in fullscreen mode

### ISSUE THREAD

**Issue by ichimitch** [JosefNemec/Playnite#1078]
I'm a long time Launchbox user and just tried Playnite out of curiosity. It's almost as good as Launchbox and it's free! I'm telling my friends about it. 

Just a couple of small requests.. Do you think you might be able to add the ability to change the size of the font in desktop mode? And the ability to have text labels at all in fullscreen mode? (without switching to Details mode)

**Comment by JosefNemec** [comment]
The font change will be possible via custom themes once #510 is done.

**Comment by ichimitch** [comment]
Noice!

**Comment by ichimitch** [comment]
You really should start charging for some premium features. I know my peers may not want to hear such suggestions  :P but it's your hard work and life going into the project and if people value it as much as I think they do, they should be happy to support the work that goes into it.

**Comment by JosefNemec** [comment]
I personally don't want to go "premium features" way and there are also logistical problems with that. Given that the whole application is open source, I would have to close some parts for the code and I don't want to do that. If you want to support Playnite monetarily then you can do so via [Patreon](https://www.patreon.com/playnite).

**Comment by ichimitch** [comment]
Nobel of you. And I will do, this pay day. Thanks for all you've put into it.

**Comment by JosefNemec** [comment]
Done in 5.0
