### ISSUE TITLE
Default theme suggestions

### ISSUE THREAD

**Issue by PurpleAzurite** [JosefNemec/Playnite#1079]
Bring back the way the old skin handles displaying information in the List View mode. Information was displayed neater, the background was more visible, and the tags were on display.

1. Bring back the 'boxes' which displayed information in list view.
2. Display links/tags in list view.

**Comment by JosefNemec** [comment]
What do you mean by "old"? There was no change to official skins for a while now.

**Comment by PurpleAzurite** [comment]
> What do you mean by "old"? There was no change to official skins for a while now.

I'm talking about the way the Classic skin handles displaying information versus the modern skin. In general, I prefer the modern skin's look, but i think the classic skin displays information much neater since they are confined to boxes. Also the information is displayed in the top of the screen instead of middle which is a better use of space since it begins at the eye level. 

Other than that, the side box the classic skin uses to display information is much more practical since it displays the tags, and also the links. It eliminates the need to switch to Details view mode to see tags, or two extra mouse click to access links.

I like the way the filters tab is displayed on the left side of the window as opposed to right side of the screen in classic mode. 

I also don't like way the modern skin blurs/darkens the background images. The way images fit to the screen if you have the right resolution works better in the classic skin.

So in general i think the following changes brought from the Classic skin will greatly improve the modern skin:

1. Bring back the old way of displaying information in List View (semi-transparent boxes).
2. Display tags and URLS in the main display instead of having to switch to Details view (for tags) or click More>Links (for URLS). 
3. Bring back quick switching between List, Covers, and Details by shortcuts on the bottom of the screen instead of having to click on "...".
4. Addition of covers display in List View of the modern skin is a welcome one, so keep that.

I know this might seem like my own preferences, but I think these changes will greatly improve the usability of the modern skin, and also looks better.

Thanks for the great app. I only wish for it to improve.

**Comment by JosefNemec** [comment]
I'm closing this since themes (default and others) were completely reworked in Playnite 5.
