### ISSUE TITLE
Add .smc extension to Snes9X profile

### ISSUE THREAD

**Issue by hunterdestroy** [JosefNemec/Playnite#1081]
Please use search first to see if the issue is already opened. Thank you
I was able to import all my gba roms but its not picking up my snes roms. It has detected the emulator I'm using (snes9x). The snes roms have a .smc extension.

**Comment by JosefNemec** [comment]
For some reason we don't list `.smc` as supported extension for Snes9X, I'll fix that. Until then you can add that extension manually via "Tools -> Platforms and Emulators" menu.

**Comment by hunterdestroy** [comment]
Thanks for the quick response, it's working now.

**Comment by JosefNemec** [comment]
Done in 5.0
