### ISSUE TITLE
Suggestion: changing background image

### ISSUE THREAD

**Issue by elalam** [JosefNemec/Playnite#1087]
Hello! Thanks so much for this great work!!!!

Would be possible to - instead of choosing a single image to be used as the background (in Media part of edit) - choosing a folder filled with images. And each time the game is clicked to be viewed the background image is chosen randomly from the set of images (similar to how that of steam works). 

(can be on click or based on a timer like 1 min or something, which ever is easier to implement).

(I tried searching for the topic to see if it has been suggested before or answered, couldn't find anything. If it has sry </3)

**Comment by JosefNemec** [comment]
Duplicate to #552
