### ISSUE TITLE
When i open it give me error 0xc0000135

### ISSUE THREAD

**Issue by ronen1n** [JosefNemec/Playnite#1088]
Please use search first to see if the issue is already opened. Thank you

**Comment by JosefNemec** [comment]
According to error code it probably means that .NET installation on your PC is not in correct state. Could you try reinstalling it from [this link](https://www.microsoft.com/en-us/download/details.aspx?id=53344) to see if it helps?

**Comment by ronen1n** [comment]
Yes i guess i have problem with the .net or something in my os 
When i get in to "Windows Features" i can see only the "Internet explorer 11" and i can't see the .net and other stuff like windows media player

**Comment by JosefNemec** [comment]
What Windows version do you have? Is it one of the stripped down "S" versions by any chance?

**Comment by ronen1n** [comment]
No i have standart windows 10 pro 1809
Maybe some tweak software did it or the ssd lost some important windows file that cause this
I did try sfc/scannow and it found some problems and then i run it again and it didnt find anything and it wasn't fix it so i think i just reinstall windows to fix it
