### ISSUE TITLE
Citra games not detected as closed

### ISSUE THREAD

**Issue by PhonixeOreo** [JosefNemec/Playnite#1089]
Whenever I close citra, Paynite shows "Running". I noticed this issue only comes up when a game is run in the citra emulator, if I just open the emulator then close it without running any game, it properly detects played time and shows "Play".
I'm using the latest citra nighty build (this happened with the latest canary also)
the citra profile settings are the default ones from the import emluators function

**Comment by JosefNemec** [comment]
No response, closing.
