### ISSUE TITLE
Playstation Now integration

### ISSUE THREAD

**Issue by janforster** [JosefNemec/Playnite#109]
Hi,

I think this will be an impossible request, but I thought it might still be worth to mention.

It would be really cool to be able to import, organise and launch the games from PS Now (https://www.playstation.com/en-gb/explore/playstation-now/ps-now-on-pc/) among the rest of the Playnite games.

Cheers

**Comment by JosefNemec** [comment]
So I had a look at it and it's not very possible. For one you actually don't have any library to import since it's  subscription based, plus there's no API to link the account. I'm closing this for now until Sony opens the platform more (unlikely in my opinion).

**Comment by janforster** [comment]
Thanks for looking into it. I was thinking about it from the other point of view: since it's a subscription based basically the whole thing IS part of your library. Pity about the API, I was hoping that maybe there would be some possibility which I have missed when reasearching it.

What I was thinking about is that scraping the whole list of games into playnite library would be possible, but the annoying thing is that there is no way how to launch a specific game from outside of the service with a shortcut or anything.
