### ISSUE TITLE
Turn Off Play Time

### ISSUE THREAD

**Issue by Serdyera** [JosefNemec/Playnite#1090]
It would be great if I had the option to turn off play time stats.

**Comment by Serdyera** [comment]
> It would be great if I had the option to turn off play time stats.

**Comment by JosefNemec** [comment]
Are you talking about hiding the information in UI or disabling the play time counter completely (which I can't see a point of doing)?

**Comment by Serdyera** [comment]
I was talking about hiding the info in UI. I think it would be a good aesthetic option to let people choose whether or not they wanted to directly see their play time.

**Comment by JosefNemec** [comment]
Done in 5.0
