### ISSUE TITLE
Open 3rd Party Client, within game page/summary

### ISSUE THREAD

**Issue by MrAltF4** [JosefNemec/Playnite#1091]
Apologies if this is not where suggestions go.

I'm loving your hard work on Playnite! Well done mate!

**The Suggestion**
When I search for titles, I find myself wanting to launch the chosen 3rd party client first, before launching the game itself. [Rough suggestion of what I'm talking about ](https://i.imgur.com/ndvlorV.png)

**known paths**
*path 1*
[I'm aware I'm able to right-click the icon in the taskbar menu](https://i.imgur.com/ZOdatcY.png) I'm assuming that this feature is [this post ](https://github.com/JosefNemec/Playnite/issues/65) right? . However, putting on my limited UX designer hat I find this a rather disconnecting pathway. 
e.g. User path:
Search for game > right-click on taskbar icon > find the right client for the game you've just found (this is harder if you don't have your library sorted by a client)

*path 2*
Open the client the old fashioned way.
This isn't really great either as the idea behind Playnite, is "This is the ONE app to rule them all", right?

*Path 3* (not possible and is the suggestion in more detail)
This is the path that I feel Playnite needs. If it can't be like the [Rough suggestion above](https://i.imgur.com/ndvlorV.png) then maybe it could be found in the "More" button (which is where I keep searching but then remember I've searched there already 500 times haha).

If you need more detail I'm happy to explain in more details :)

Cheers
And keep up the great work!!!

**Comment by JosefNemec** [comment]
Adding this to game's context menu (and under More button), should be fairly easy and makes sense to me.

**Comment by MrAltF4** [comment]
sounds great :)

**Comment by ArtexJay** [comment]
You could put the words of the 3rd party launcher above the name of the Game Title, and we would just like on that to open steam, epic etc.

**Comment by AIRyndon** [comment]
I would like to work on this one if no one is doing it already :)

**Comment by JosefNemec** [comment]
Should be made as part of integration plugins where this is actually possible, not all clients allow this.
