### ISSUE TITLE
Playnite installs in an odd path

### ISSUE THREAD

**Issue by benblo** [JosefNemec/Playnite#1093]
Playnite doesn't want to install in %Program Files like any regular program, but in AppData\Local... is it expected or a bug?
I'm using Window 10
![image](https://user-images.githubusercontent.com/574187/55176663-d6ed0780-5181-11e9-8801-6624ba7a866f.png)

**Comment by JosefNemec** [comment]
This is by design, %ProgramFiles% would require elevated rights, which is unnecessary since Playnite itself doesn't modify any system settings and runs with user rights without any issues.

**Comment by benblo** [comment]
Aaah, good to know thanks!
