### ISSUE TITLE
Ignore uninstallers when importing executables

### ISSUE THREAD

**Issue by benblo** [JosefNemec/Playnite#1094]
I scanned my "non-Steam non-GoG" games folder, and Playnite found all exes, and offered to add uninstallers to my collection :/ !
![image](https://user-images.githubusercontent.com/574187/55177625-ef5e2180-5183-11e9-8370-235e250ee413.png)
Luckily I noticed, but if I hadn't I launched one of those "games", I might uninstall it by mistake? How about filtering out "uninstall.exe" and some common exe names?

**Comment by JosefNemec** [comment]
Done in `devel7` branch (future Playnite 7).
