### ISSUE TITLE
Lint build scripts with PSScriptAnalyzer

### ISSUE THREAD

**Issue by tylerszabo** [JosefNemec/Playnite#1095]
Running PSScriptAnalyzer `Invoke-ScriptAnalyzer -Path build` lists a number of warnings with default rules.

Maintainability:
- **PSAvoidGlobalVars** - (fixed by using `.` dot-sourcing instead of `&` call)
- **PSAvoidUsingCmdletAliases** - swap `Where` for `Where-Object` and `ForEach` for `ForEach-Object` (this is especially important for `ForEach` which could be either a statement or the `ForEach-Object` function).
- **PSPossibleIncorrectComparisonWithNull**
- **PSUseDeclaredVarsMoreThanAssignment** - There are some unused variables that appear to be legacy.

Style:
- **PSAvoidTrailingWhitespace**, **PSUseConsistentWhitespace**

Should likely be suppressed:
- **PSAvoidUsingWriteHost** - Write-Host is used a lot in the build scripts; while moving to `Write-Verbose` or `Write-Information` or a custom `Write-Log` might be handy, this would be a sufficiently significant effort to coordinate with how `stdout` is currently handled so warrant handling as a separate issue.

Below is an invocation example with a proposed ruleset that enforces current style:

```powershell
Invoke-ScriptAnalyzer -Path . -Recurse -Settings @{
   IncludeRules = @( '*' )
   ExcludeRules = @( 'PSAvoidUsingWriteHost' )
   Rules = @{
     PSPlaceOpenBrace = @{ Enable = $true; OnSameLine = $false }
     PSPlaceCloseBrace = @{ Enable = $true; NoEmptyLineBefore = $true }
     PSUseConsistentIndentation = @{ Enable = $true; Kind = 'space'; IndentationSize = 4 }
     PSUseConsistentWhitespace = @{ Enable = $true; CheckOpenBrace = $false }
   }
 }
```

**Comment by JosefNemec** [comment]
I'm closing this. It would bring basically no value, since I'm the only one maintaining build scripts and the only one actually making builds.
