### ISSUE TITLE
German installation of battle.net not recognized, thus games cannot start

### ISSUE THREAD

**Issue by Retr0Pixel** [JosefNemec/Playnite#1097]
Hi, i have the problem using a german installation where the path to battle.net is called "C:\Program Files (x86)\Battle.net"
It works fine on its own and Games get detected.
This is the diagnostics package code: 8c369246-bf96-474b-911a-bc2228f6b562

**Comment by JosefNemec** [comment]
Is this still an issue in Playnite 5? I fixed it for some other language there so it probably fixed german as well.

**Comment by Retr0Pixel** [comment]
Hi, sadly it still does not work. battle.net in Playnite keeps getting logged every time i restart Playnite and even when logged on i cannot start or install battle.net Games, stating battle.net Launcher was not installed properly.

Created new diagnostics package: 71ca92e6-4374-4d9c-8f5b-fefaed5b0982

**Comment by JosefNemec** [comment]
According to diag. package it looks like some issue with your battle.net client installation (it doesn't show up in list of installed apps). Can you try to reinstall it?

**Comment by Retr0Pixel** [comment]
Hi, indeed, after removing the old installation and reinstalling battle.net, the error is gone and it doesnt log off anymore. Tried restarting battle.net and Playnite and even the Computer, error is gone.

This is solved. Thank you :)
