### ISSUE TITLE
Fix website description

### ISSUE THREAD

**Issue by chocolatechipcats** [JosefNemec/Playnite#1100]
At present it's this:

`<meta name="description" content="Source code generated using layoutit.com">`

When a link to the site is pasted into Discord, the rich embedding shows this message. Suggest changing it to this:

> Playnite is an open source video game library manager with one simple goal: To provide a unified interface for all of your games.

**Comment by JosefNemec** [comment]
Fixed (Discord may still show the old description due to caching).
