### ISSUE TITLE
Reddit link wrong label

### ISSUE THREAD

**Issue by Magi1053** [JosefNemec/Playnite#1103]
When downloading links from sources, the label for Reddit is set to "14"

![image](https://user-images.githubusercontent.com/1045179/55429410-0d939b00-5551-11e9-9ff2-f1f2d9b48bae.png)

**Comment by AIRyndon** [comment]
Hello @JosefNemec , I would like to work on this issue if possible, seems low_priority enough for a beginner like me :). Is there someone working on this? Thanks!
