### ISSUE TITLE
Catalan translation

### ISSUE THREAD

**Issue by amagraphics** [JosefNemec/Playnite#1104]
TRADUCCIÓ AL CATALÀ DE PLAYNITE

1.0 - Catalan translation added

Si trobes algun error o creus que s'hauria de canviar alguna frase, fes-m'ho saber!

[catalan.zip](https://github.com/JosefNemec/Playnite/files/3045327/catalan.zip)

**Comment by JosefNemec** [comment]
Localization have been completely move to Crowdin: https://crowdin.com/project/playnite

Please join the project there to submit updates.
