### ISSUE TITLE
IGDB

### ISSUE THREAD

**Issue by mrcturner** [JosefNemec/Playnite#1105]
Hi

Just a bit of positive feedback. Playnite has now been my games library/launcher for a few months now. It's definitely what people have been looking for and I recommend it to all PC gaming users I know.

However, one possible suggestion, could you apply the IGDB rating API at the bottom of the individual game information? Just a suggestion.....

https://igdb.github.io/api/

Best

**Comment by JosefNemec** [comment]
Will be done as part of #594
