### ISSUE TITLE
Support for ISO files and installers for pc games

### ISSUE THREAD

**Issue by gitHarvest** [JosefNemec/Playnite#1108]
i have a lot of old pc game cds which i've recently backed up into iso files and also some installers from old free games or gog.

i think it would be great if there's a way to add these to my playnite library and show these games as uninstalled in the library and to let it start the installers or mount the iso files when prompted.

**Comment by DennoCoil** [comment]
I've been thinking about this too.  Loose ISO's and loose installers are much different from the regular EXE files that Playnite handles.  How Playnite handles the Play\Install feature is it executes the EXE once and tracks how long it's alive.

But you don't want that for an Installer or loose ISO.  Playnite needs to keep the location of the original installer (or better yet, copy\move it for you), while using a separate spawned exe from the installer\ISO as the real program to launch.

Perhaps have a toggle button in the Installation tab on the Game Edit menu that changes the behavior of some parts of the menu.  Mainly adding a new Play Action underneath everything to add a separate Install button.
![2019-04-13 01_37_06-Edit Game Details](https://user-images.githubusercontent.com/21137176/56075234-37d52c00-5d8d-11e9-9bf2-1a1d8ed5f949.png)

**Comment by JosefNemec** [comment]
Duplicate to  #478

**Comment by sparxooo** [comment]
#797 references mounting ISO's
