### ISSUE TITLE
Launcher Shortcuts

### ISSUE THREAD

**Issue by berserkwarwolf** [JosefNemec/Playnite#111]
Near the Steam Friends icon / button, the one with two people in it, it would be nice if we could have the logo from each launcher and click it to open that launcher, in order to chat with our friends on that platform. There are gamers that use TeamSpeak, Mumble, and most of all Discord, so a custom shortcut option would be nice too.

**Comment by trymeouteh** [comment]
A mumble and teamspeak button will be cool!

**Comment by JosefNemec** [comment]
I'm duplicating this to #1463
