### ISSUE TITLE
Tray icon is not clickable after system startup

### ISSUE THREAD

**Issue by Pegoth** [JosefNemec/Playnite#1110]
After system start the Playnite tray icon doesn't bring up the menu when I click it.

If I start clicking it like a madman then it will crash. Everything works fine if I restart Playnite after the crash.

**Comment by Pegoth** [comment]
Added a custom task to start it delayed after user login (1 min later) and it fixed the problem.

**Comment by JosefNemec** [comment]
I can't reproduce this, does it still happen with Playnite 5?

**Comment by Pegoth** [comment]
> I can't reproduce this, does it still happen with Playnite 5?

Unfortunately I stopped using the software as I no longer needed it.
