### ISSUE TITLE
Allow multiple exe in one Play Action

### ISSUE THREAD

**Issue by ewauq** [JosefNemec/Playnite#1111]
It would be useful to allow multiple exe or linking Play Action together when you launch a specific Play Action, to launch tools with the game for example.

I like to play in borderless mode (with Borderless Gaming) but I don't want that the tool is launched all the time. I just need it when I launch the game.

So it would be nice to let us to launch another exe within a single Play Action.

The only solution I found is to make a Batch file, but it is not very handy.

**Comment by JosefNemec** [comment]
Will be supported via #113
