### ISSUE TITLE
After update it loses the library location and appearence settings. 

### ISSUE THREAD

**Issue by vinguan** [JosefNemec/Playnite#1114]
When the app updates it loses the library location and the settings for theme and appearance every time. Is there a way i can fix this?

**Comment by JosefNemec** [comment]
Can you go to `About` menu and create diagnostics package for me please?

**Comment by vinguan** [comment]
Sure. Here is the ID : 75714df7-9a9b-44ac-bedc-221be1e2b093

**Comment by JosefNemec** [comment]
Done in 5.0
