### ISSUE TITLE
Playnite crash after the installation

### ISSUE THREAD

**Issue by Alragan** [JosefNemec/Playnite#1116]
Hello,
I can't open Playnite
(rebboting windows have been done)
Diag package : 41f1c5ef-99db-436c-a68c-32f8bd9034f7

thanks !

**Comment by JosefNemec** [comment]
According to logs it looks like there's something wrong with fonts on your system.

Here are some suggestions how to fix it:
https://stackoverflow.com/questions/48206725/no-fontfamily-element-found-in-fontfamilycollection

**Comment by Alragan** [comment]
Thanks ! It worked ! 
Now i can't see any unistalled games on my steam librairie. I already have updated it on playnite's settings
what should i do ?

**Comment by JosefNemec** [comment]
See https://github.com/JosefNemec/Playnite/wiki/Account-sync-troubleshooting
