### ISSUE TITLE
Playnite crashed after downloading metadata to manually added game

### ISSUE THREAD

**Issue by Rawra** [JosefNemec/Playnite#1117]
I added the Kenshi demo to Playnite manually and it crashed after attempting to download the metadata.
Playnite provided the following crash code 09bdbfce-450e-4e48-b39c-9dd41eb1be8c

Upon restating Playnite, I received a "Failed to start. Close all running instances" error. Restarting once more worked.

**Comment by JosefNemec** [comment]
I made some changes in Playnite 5 to metadata downloads. Does this still happen in latest versions as well?

**Comment by Rawra** [comment]
Completely forgot to respond to this. No, the issue appears to have been fixed. Haven't had a crash happen since the update.
