### ISSUE TITLE
Not detecting uninstalled Steam games

### ISSUE THREAD

**Issue by ThePamplemoussian** [JosefNemec/Playnite#1120]
After importing all of my games, I found out ones I hadn't installed from Steam weren't detected (even though I had the box checked). I tried it the next day, but it still gave the same error (no games found on specified Steam account), even though there are definitely ones I don't have installed. Also, not sure if this is related, but it didn't import any of my playtimes either.

By the way, I'm not sure if this extends to other libraries. All of my games from Blizzard, Epic, and Origin are installed.

![image](https://user-images.githubusercontent.com/29361536/56537159-d865e180-652d-11e9-839a-3c5ae7c63b1b.png)
_Steam Library vs. Playnite library (filtered to only show steam games). As you can see, Poly Bridge, Portal 1 & 2, and Goat Simulator were not imported._

![image](https://user-images.githubusercontent.com/29361536/56537396-6c37ad80-652e-11e9-8c38-23089d955934.png)
_Filters I have set up, as well as the error message._

**Comment by JosefNemec** [comment]
It's because your account has Private account visibility (default state). You either have to set it to Public or provide your own API key if you want to keep it private.

https://github.com/JosefNemec/Playnite/wiki/Account-sync-troubleshooting

**Comment by ThePamplemoussian** [comment]
I'm dumb, I should've checked the wiki first. Thank you though!

**Comment by TacticalTurtleneck** [comment]
I have the exact same problem and my Steam account is Public. I don't have any filters enabled and I have already reinstalled Steam to rule out corruption. 

Any ideas?
