### ISSUE TITLE
Turkish Translation for Playnite

### ISSUE THREAD

**Issue by eycefchi** [JosefNemec/Playnite#1121]
Playnite Versiyon 7.47 Türkçe Çeviri
Playnite Version 7.47 Turkish Translation

[turkish.zip](https://github.com/JosefNemec/Playnite/files/3122366/turkish.zip)

**Comment by JosefNemec** [comment]
There was one already submitted in #1119, I'm not sure which one to integrate now :)

**Comment by JosefNemec** [comment]
Localization have been completely move to Crowdin: https://crowdin.com/project/playnite

Please join the project there to submit updates.
