### ISSUE TITLE
Playnite preventing computer shutdown

### ISSUE THREAD

**Issue by mario182** [JosefNemec/Playnite#1122]
(Probably unrelated to #866)

Diagnostic Package ID: 9d0a206c-beb1-4767-ada3-cd7180d7ce12

For reasons unknown to me, on random occasions when attempting to shut down my PC, Windows tells me that Playnite is preventing shutdown, and when I cancel, and return to desktop, I'm greeted with this "Closing Playnite..." bar that seemingly never completes.

![](https://puu.sh/Dl2lj.png)

**Comment by Stuntaneous** [comment]
Might be related to Playnite causing game executables to stay alive, i.e. try seeing if any games opened through Playnite have lingering executables in Task Manager and if so, kill them.

**Comment by JosefNemec** [comment]
According to screenshot it's because Battle.net import is still in progress (stuck on something) and Playnite tries to cancel it first, it's a deadlock situation. It's in fact duplicate to #859, I'll try to fix it for 5.0 since more people started reporting this.
