### ISSUE TITLE
Playnite does not start minimized on computer startup

### ISSUE THREAD

**Issue by Marotheit** [JosefNemec/Playnite#1123]
Playnite seems to start minimized if I launch the application normally, but does not start minimized on computer startup.

I don't see other users with this problem, so it may be just me.

My diagnostic code is abfac147-f8e2-466a-b8b3-5bcaf5241b56 in case it matters.

**Comment by rejas** [comment]
Got the same problem too @Marotheit so you are not alone.

**Comment by M0rr1s0n** [comment]
Wanted to ask the same, I'm on Windows 10 Build 1903 and Playnite isn't started minimized on boot even though the checkmark is checked in settings.

**Comment by JosefNemec** [comment]
This should be fixed in Playnite 5, can somebody verify please?

**Comment by Marotheit** [comment]
I can confirm that this has been fixed as of version 5.5.

Wonderful work! Thank you!
