### ISSUE TITLE
Migrating game directory to another drive

### ISSUE THREAD

**Issue by Pink-Devil** [JosefNemec/Playnite#1124]
I have over a hundred games in the same directory, using Playnite for these and I am about to move these hundreds of games to another larger hard drive, from drive "D:" to Drive "E:". Is there a way to make Playnite change all its Installation Directory and Actions Path from D to E automatically or would I have to manually do all of them one by one?

**Comment by JosefNemec** [comment]
If they are games that are automatically imported from 3rd party library (like Steam, GOG etc.) then installation paths will be updated automatically next time you start Playnite. For manually added games there's currently no option to edit installation path for multiple games at once.

**Comment by Barina** [comment]
> For manually added games there's currently no option to edit installation path for multiple games at once.
Do we have a "game install migration" for single game? can't find any..

**Comment by jackyliu16** [comment]
I just see this, maybe it will help you 
https://github.com/dragonmc77/MoveGame

**Comment by xenlata** [comment]
[Path](playnite://playnite/installaddon/PathReplacer) Replacer 
This extension will find-and-replace the start of game/emulator/auto-scan configuration file paths. Its main use is for when you've moved folders around.
