### ISSUE TITLE
Origin Issue

### ISSUE THREAD

**Issue by backpack5689** [JosefNemec/Playnite#1126]
I currently have the issue of being unable to run games that are from origins. All other launchers are working fine, and the games from origins are importing, they are just not launching after I press the run button.

**Comment by JosefNemec** [comment]
Do you get some error message or anything? Also please go to "About" menu and create diagnostics package for me.

**Comment by backpack5689** [comment]
I didn’t get an error. However, after messing around with it, having origins open while pressing the play button worked to start the game. My origins doesn’t start on launch, but I set it to now and no longer get any errors. Here is the code for the diag. a89ccfab-0710-4801-b1cf-864cbe1fc391

--Aaron Thompson
Missouri Military Academy Graduate
Lipscomb University CCT Student
Information Security Major

Have a great day!

________________________________

**Comment by JosefNemec** [comment]
Is this still an issue with Playnite 5?

**Comment by backpack5689** [comment]
No, this last update fixed it. Thanks

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
