### ISSUE TITLE
Add "Abandoned" completion status

### ISSUE THREAD

**Issue by JosefNemec** [JosefNemec/Playnite#1127]
https://www.reddit.com/r/playnite/comments/bkiczn/any_way_to_add_a_new_completion_status_option/

**Comment by Mates1500** [comment]
I could take a look at this if you're not already working on it.

**Comment by JosefNemec** [comment]
Sure that a look at it, there was also request to add "Stuck" or "On hold". Maybe ask people on Discord what would they prefer as complete list of states to make sure we are not adding them one by one.

Also please base your work `devel` in this case since completion status enum was moved around.

**Comment by JosefNemec** [comment]
Duplicate to #1028
