### ISSUE TITLE
[Feature Request] Wishlist import/export

### ISSUE THREAD

**Issue by SonOfDiablo** [JosefNemec/Playnite#1129]
I was wondering if it would be possible to have a feature to import wishlists from all the different places.

Maybe have a view where you can see the prices from different places? (Could probably get the prices from isthereanydeal.com)

Also the option to export the concatenated whishlist to a text document for easy sharing.

**Comment by JosefNemec** [comment]
I think this should be done as part of #278. Implementing our own price comparison system is something we don't have manpower for and isthereanydeal does a very good job. Adding some good integration with isthereanydeal makes more sense to me.
