### ISSUE TITLE
Pre/post script actions

### ISSUE THREAD

**Issue by AntoinevdHorst** [JosefNemec/Playnite#113]
Hey,

When I want to play a game on battle net or origin I usually launch it via playnite but that usually only starts origin/battle.net . This could be resolved by having the ability to issue a wait command for additional actions.
So then it would look like this:

Launch Battle.net
Wait 5 seconds
Launch World of warcraft
Wait 5 seconds
Launch twitch(for addons)
Wait 5 seconds
Launch Tukui(for addons)

Would this be possible?

**Comment by JosefNemec** [comment]
Yes, I'm planning to add additional launch settings including pre and post sections and custom scripted actions.

**Comment by JosefNemec** [comment]
Done in 6.0

**Comment by molnizzle** [comment]
Was it removed then? I'm not seeing how to do this with Hearthstone and Hearthstone Deck Tracker.

**Comment by JosefNemec** [comment]
No it was not removed, the option is still there while editing the game or in application settings for global scripts.
