### ISSUE TITLE
Notify if 3rd party launcher or game has updates available

### ISSUE THREAD

**Issue by SonOfDiablo** [JosefNemec/Playnite#1130]
I was wondering if it would be possible to have Playnite notify the user if one of the installed launchers has an update pending?

I like how I don't have to have my launchers running to browse my games thanks to Playnite, but if I have to update my launchers when I install a game or want to play a game through the launcher, then it takes away some of the ease that Playnite brings. So if Playnite could have a notification for launcher updates and maybe let the user update through Playnite (I don't know how possible that would be) that would be a tremendous quality of life improvement!

**Comment by JosefNemec** [comment]
I think this will be very complicated to do. I would have to check for each launcher, but the biggest issue will be to find a reliable way how to detect if update is available.

**Comment by backtolinux** [comment]
Hi,
Excuse for intrusion, but I have similar error :
I have game installed on samba share.
Steam is connected to playnite (thanks !).
Ark evolved has to be updated in steam.
In playnite, game is marked playable.
When I clic on play, playnite crashed.
This is the number for error details : 5a6d66f1-8560-461f-a466-c54a5eb7d893.
Let me know if new post needed.
Kind regards.

**Comment by JosefNemec** [comment]
Please open that crash as separate issue.

**Comment by backtolinux** [comment]
done :-)

**Comment by JosefNemec** [comment]
Duplicate to #432
