### ISSUE TITLE
Sea of Thieves not found

### ISSUE THREAD

**Issue by eproxus** [JosefNemec/Playnite#1136]
Sea of Thieves cannot be added from _Add Game_ -> _Scan Automatically..._ -> _Detect Installed_. I have both Forza Horizon 4 and Sea of Thieves installed from the Microsoft Store (via Xbox Game Pass), but only Forza shows up.

**Comment by JosefNemec** [comment]
I'm not sure what might be causing this. Is Forza installed on the same drive as Sea of Thieves?

**Comment by eproxus** [comment]
@JosefNemec Yes, both are installed on `D:`. Seems a bit broken in the Store itself, if I look at installed apps both Forza and SoT sometimes shows up, sometimes not. They are always in the start menu though and in the uninstall list of Apps & Features.

**Comment by JosefNemec** [comment]
If even the Store itself fails to recognize if the game is installed then I'm not sure we can do anything about this. I would maybe try to completely uninstall and reinstall the game.

**Comment by eproxus** [comment]
Now that I check, the Store does finds Sea of Thieves reliably. But it still doesn't show up in Playnite.

**Comment by plxjammerplx** [comment]
Solution: Look for the game manually. (Option is there, stop being lazy)

**Comment by JosefNemec** [comment]
@plxjammerplx Maybe read the issue description first. It's not about being lazy, the only option Playnite currently provides to properly import Windows Store games doesn't detect it.

**Comment by eproxus** [comment]
@plxjammerplx I already tried this. The problem is, Windows Store applications are installed in a folder which the user doesn't have access to. So maybe ask before you judge (option is there, stop being rude).

**Comment by eproxus** [comment]
Just installed Astroneer and Bridge Constructor Portal via Xbox Games Pass for PC. Bridge Constructor was found by Playnite, but not Astroneer. Sea of Thieves is still not found. All games are listed correctly in the start menu and in Microsoft Store as installed.

**Comment by JosefNemec** [comment]
I just checked it with Astroneer and the game is listed, but not under normal name, but its ID `SystemEraSoftworks.29415440E1269`. I'll see what I can do about it.

**Comment by JosefNemec** [comment]
Done in 5.0
