### ISSUE TITLE
Hitting enter when only having one search result should launch that game

### ISSUE THREAD

**Issue by ChildishGiant** [JosefNemec/Playnite#1138]
Just a lil request, hopefully fairly simple to implement if agreed to

**Comment by JosefNemec** [comment]
I'm not sure I agree with this. Having different behavior depending on how many search results are returned, seems not very user friendly to me.

**Comment by ChildishGiant** [comment]
I do see where you're coming from. I think I'm just used to steam and being able to type in a game's name and hit enter. Maybe making enter not move the focus to the filters, but to the games list would help? That way it's two enter taps to launch a game? I always assume tab will change focus and enter will open what's focused. I guess this is a question of what does opening the search bar mean?

**Comment by JosefNemec** [comment]
This will be done as part of #1413
