### ISSUE TITLE
Few ideas and one bug

### ISSUE THREAD

**Issue by SziserTrue** [JosefNemec/Playnite#1139]
Hello, got a few ideas:
-Start random game
-Automaticly load UPlay games which are not downloaded
-Maybe some Razer Chroma like features
-Choosing size of covers in BPM
-Handling messeges and contacts from diffrent launchers
-Facebook,discord and other media shortcuts and functions
-Playnite friend system
-Achievments (maybe even something like social achievments ,so even achivmentless games could get one)
-Maybe possible mod list for game ,imported from apis like nexus or moddb

And one bug:
-Battle.net after every launch of playnite is logged of from playnite ,even if told to not.

**Comment by SziserTrue** [comment]
and got one more idea :) Handling DLC's :) 
BTW thanks for your work :) Now we can play games freely and stop thinking about thousands launchers :)

**Comment by JosefNemec** [comment]
> -Start random game

#121

> -Automaticly load UPlay games which are not downloaded

#196

> -Maybe some Razer Chroma like features

What would actually Playnite do with that?

> -Choosing size of covers in BPM

What's BPM?

> -Handling messeges and contacts from diffrent launchers

Probably not going to happen in foreseeable future until those launchers provide official API for it. Some sort integration for Discord might be in theory possible #194

> -Facebook,discord and other media shortcuts and functions

Probably #197 if I understand correctly what you are looking for.

> -Playnite friend system

There's already so many services that provide ability to chat with friends that implementing another custom solution makes no sense to me at the moment. Partnering with existing service is more probable in future.

> -Achievments (maybe even something like social achievments ,so even achivmentless games could get one)

#146

> -Maybe possible mod list for game ,imported from apis like nexus or moddb

Do they have APIs for 3rd parties to get their data?

> And one bug:
> -Battle.net after every launch of playnite is logged of from playnite ,even if told to not.

#1057

> and got one more idea :) Handling DLC's :)

#367

**Comment by kpd328** [comment]
> > -Choosing size of covers in BPM
> What's BPM?
I think he means Big Picture Mode (what steam calls fullscreen)

**Comment by JosefNemec** [comment]
Closing, no response to my questions from original reporter.
