### ISSUE TITLE
Playnite dosen't start

### ISSUE THREAD

**Issue by Lunchb0ne** [JosefNemec/Playnite#114]
I just installed it and it dosen't open

[ERR.zip](https://github.com/JosefNemec/Playnite/files/1336884/ERR.zip)

**Comment by JosefNemec** [comment]
Can you try if portable version works? It looks like that either the installation is damaged for some reason or there might be some fonts missing on your PC. I can't say exactly, this is the first time this error showed up.

**Comment by Lunchb0ne** [comment]
I tried Portable version, same error

**Comment by JosefNemec** [comment]
Can you please try this Playnite version and tell if it works? Thanks
http://playnite.link/download/PlaynitePortable_HtmlFix.zip

**Comment by Lunchb0ne** [comment]
Works Flawlessly,
Thanks a lot!

**Comment by JosefNemec** [comment]
Great, I'll leave this issue open until fix gets released via standard update.

**Comment by JosefNemec** [comment]
Released in 2.0
