### ISSUE TITLE
Time/Last Played isn't imported from the origin launcher

### ISSUE THREAD

**Issue by ChildishGiant** [JosefNemec/Playnite#1140]
There are several similar issues but not any that are the same as this. Basically when importing games from origin, both time played and last played aren't imported. I know this is intended but this is basically a feature request

![image](https://user-images.githubusercontent.com/13716824/57327333-9d0b0b80-7106-11e9-8e3f-c604162bffb6.png)
![image](https://user-images.githubusercontent.com/13716824/57327420-cfb50400-7106-11e9-8ddb-fabec6fab089.png)

**Comment by JosefNemec** [comment]
Play time import is currently only supported for Steam and GOG games: https://github.com/JosefNemec/Playnite/wiki/Feature-table-based-on-library-provider

**Comment by tylerszabo** [comment]
I think I can implement this; from looking at the website Origin has a way to query playtime / last played metadata. I'm not sure how stable the API is, though. @JosefNemec would you rather wait for official support or is this something I should take a crack at?

**Comment by JosefNemec** [comment]
Feel free to look at it, I'm not planning to implement it myself any time soon.
