### ISSUE TITLE
Playnite always goes to top element

### ISSUE THREAD

**Issue by soDedInside** [JosefNemec/Playnite#1146]
No matter on what menu i am, playnite always goes to the top element.

https://gyazo.com/2874c253e14196c5a7a7dddcb504c13a

**Comment by JosefNemec** [comment]
Do you have controller attached? There's currently no way to disable controller support in Desktop mode (it will be possible in 5.0) and it looks like that there's some that resends input to move the game selection back.

**Comment by soDedInside** [comment]
No... I have a controller but it wasn't attached when the bug happened.

Now that i'm thinking of it, I believe this started happening when i installed the sony remote control app on the system.

May be it? It required the use of the DS4 for validating (even though, again, it wasn't pluged in when the bug happened).

**Comment by JosefNemec** [comment]
It's definitely something re-sending arrow keys or XInput inputs in loop.

**Comment by soDedInside** [comment]
Yep, confirmed.

Once i uninstalled the aplication it worked flawlessly. For keeping the record, was this software:

https://remoteplay.dl.playstation.net/remoteplay/lang/en/index.html
