### ISSUE TITLE
Uninstalled Steam games aren´t showing up

### ISSUE THREAD

**Issue by shutakku** [JosefNemec/Playnite#1147]
I searched the Wiki and the existing issues, couldnt find anything that helped me. 

Account, inventory, everything is set to public. Although I still tried to use a Steam API key. Restarting the program, the computer. Nothing helped.

**Comment by JosefNemec** [comment]
Do you get some error notification? Also make sure that you don't have a filter enabled that would only show installed games.

**Comment by shiitake** [comment]
I've had the same issue as @shutakku 

I was only able to resolve this generating an API key on the steam website.

**Comment by DaRochaRomain** [comment]
I've had the same issue too. Only the API key was able to show my uninstalled game.

**Comment by JosefNemec** [comment]
You only need to set API key if your Steam account is using private account visibility. Public accounts should work without it.
