### ISSUE TITLE
Favorites in fullscreen mode

### ISSUE THREAD

**Issue by brickcatena** [JosefNemec/Playnite#1149]
Some nice to have features:
- Filter by favorites in fullscreen mode
- Set a default filter for fullscreen mode
 or
- last used filter persist between fullscreen sessions

**Comment by JosefNemec** [comment]
Duplicate to #520

**Comment by brickcatena** [comment]
In 520, you seem to have stated: "also split this to separate issues"

**Comment by brickcatena** [comment]
Please pardon my misinterpretation.
