### ISSUE TITLE
(Visual?) bug when deselecting a game amongst multiple selections (List view)

### ISSUE THREAD

**Issue by unrealed** [JosefNemec/Playnite#1152]
When in List view, using Ctrl to deselect a game from the list won't actually visually deselect that game until you select/deselect another game. It should deselect the game immediately.

**Comment by JosefNemec** [comment]
Yes this is just visual, the game is in fact not selected anymore, just the visual focus stays there for some reason.

**Comment by JosefNemec** [comment]
Fixed in 5.7
