### ISSUE TITLE
Multi-view

### ISSUE THREAD

**Issue by unrealed** [JosefNemec/Playnite#1153]
Would be nice to have the ability 2 (or more?) "viewports" where we could filter games as we want to compare things between games. Maybe it would be comparing libraries, ratings, whatever. This is very high in complexity, probably very low in demand, so definitely very low priority.

**Comment by JosefNemec** [comment]
This is in "very complicated, nearly impossible" category due to multiple reasons like theme support, performance etc. I'm closing this for that reason.
