### ISSUE TITLE
Entering text in the top bar's search field and clicking "clear filters" resets the filters but does not clear the field

### ISSUE THREAD

**Issue by wmassingham** [JosefNemec/Playnite#1154]
Playnite 4.74. "Clear filters" doesn't clear the text from the top bar, even though it does remove filters from the list. That button should clear both the filter panel and the top bar's field.

Reproduce:
1. Expand the filter panel
2. Enter text in the top search field (observe the same text filled into the left "name" field)
3. Click "clear filters"
4. Filter fields on left are cleared and the list is no longer filtered, but the top bar still has your text in it

**Comment by T-0pel** [comment]
I could pick this up if no one else did yet.

**Comment by T-0pel** [comment]
@JosefNemec I think this issue can be closed, as it was resolved in 5.0.
