### ISSUE TITLE
Grouping by installation state

### ISSUE THREAD

**Issue by Darkenend** [JosefNemec/Playnite#1161]
The sorting method that I want to suggest is basically showing first the installed games, and then the uninstalled games, this way you can have your installed games in an easy way to access them, and you have also the uninstalled games so you would just have to scroll down a bit to install a game you want.

Uplay does something similar, but it shows all games. (And also has favorite games on top)

![image](https://user-images.githubusercontent.com/34766606/58018588-851e8900-7b03-11e9-9ed2-a4e07972ac96.png)

**Comment by JosefNemec** [comment]
Done in 7.1.
