### ISSUE TITLE
"Yes/no" is not translated in Details view

### ISSUE THREAD

**Issue by ClearStrelok** [JosefNemec/Playnite#1164]
![Sans titre-3](https://user-images.githubusercontent.com/38838369/58126979-9905e000-7c14-11e9-9b95-6470d8ceec0c.jpg)

**Comment by T-0pel** [comment]
@JosefNemec I would like to start contributing to this project and this seems like a good initial issue. I could take a look at it if no one else picked it up yet.

**Comment by JosefNemec** [comment]
I already fixed this some time ago, sorry.

**Comment by JosefNemec** [comment]
Done in 5.0
