### ISSUE TITLE
Some Authentication Issues With Twitch and Battle.net

### ISSUE THREAD

**Issue by SageMastah** [JosefNemec/Playnite#1166]
I'm having minor issues with the Twitch and Battle.net integrations. For Twitch, after doing everything recommended from both here and on Reddit to fix this issue, I can't seem to get my account authenticated. There's nothing wrong with my Twitch account, since I can log into it just fine elsewhere, especially since this wasn't an issue before today. 

For Battle.net, I have to log in every time I launch the app. It's manageable, especially since I don't use Battle.net often, but it's still a mild annoyance at this point.

Feel free to take your time with this, as I'm sure this has been a recurring issue for a few months now and I'm in no particular need to have these fixed.

I'm using version 4.74 SDK 4.0.0 and my .diag ID is `f74fd25d-faa5-48c1-9379-3b62edcb7e8c`.

**Comment by JosefNemec** [comment]
Both of these are know issues, please use search next time before opening new issues: #1057 #991
