### ISSUE TITLE
Allow excluding generes/tags when filtering

### ISSUE THREAD

**Issue by azumukupoe** [JosefNemec/Playnite#1168]
Please use search first to see if the issue is already opened. Thank you

**Comment by Gerren** [comment]
Hello,

I would also use this feature.

I imagine this to have the checkboxes as a Tri-State:

- Empty: do not care
- Checked: game has to have this Tag/Feature/...
- Crossed: game shall not have this Tag/Feature/...

If you need an inspiration, see https://www.lorenzostanco.com/lab/steam/ 

There it is indicated as Grey/White/Red.

**Comment by Gerren** [comment]
Oh, this is basically #837

**Comment by JosefNemec** [comment]
Will be done in #837

**Comment by ccrowles** [comment]
> Will be done in #837

 I see that the issue is marked as closed and #837 is marked closed as well, but I'm on playnite 9 and I don't see any way to exclude games with certain tags when filtering. Am I just not seeing the obvious or...?

**Comment by JosefNemec** [comment]
Up to date issue #2538
