### ISSUE TITLE
Store column in Details view

### ISSUE THREAD

**Issue by MessuKilkain** [JosefNemec/Playnite#117]
The title is pretty straightforward but I will explain a bit.
They are currently 3 types of view: List, Cover and Details.
On Details display, we can choose the column we want to display. I would like to be able to display a column with the store (Steam,GOG,Origin,Uplay,Custom).
My naive guess is that it is really not that hard to do (and if I one day learn how to edit the project correctly with Visual Studio, I may even fix this issue myself but no time today).
By the way, thanks a lot for this project (finally a software that let me use and compare my own Steam and GOG libraries... and cherry on the cake, it's open source; man I love you).

**Comment by JosefNemec** [comment]
Yeah it will be easy to add. However it will not make 2.0 release, which is going out today. I will put in into one of 2.x releases.

**Comment by MessuKilkain** [comment]
Thank you a lot. I just updated the soft and fully understand why it was not possible/desirable to make the change for that version.
By the way, congratulation for release of v2.

**Comment by JosefNemec** [comment]
Released in 2.1
