### ISSUE TITLE
Links do not open in Firefox if it already open

### ISSUE THREAD

**Issue by Purplemage0** [JosefNemec/Playnite#1171]
When I click on a link in Playnite, and I have Firefox already open I get an error that says
"Firefox is already running, but is not responding. The old Firefox process must be closed to open a new window."
If firefox is closed it does open a new window, but I have to restore my session for other tabs I had open.
I am using stored sessions in firefox, as I always have the same few tabs open, could it be a sessions error, that it is resetting?

**Comment by JosefNemec** [comment]
I don't think we can change this behavior, we only say to Windows to open some URL (we don't manually start browser process to open it). What happens next is outside of our control.

**Comment by Purplemage0** [comment]
I have been experimenting and I think it's the latest update to firefox that is broken not your links, sorry, I should have tested more to begin with
