### ISSUE TITLE
Crash when opening tga image for metadata

### ISSUE THREAD

**Issue by kpd328** [JosefNemec/Playnite#1172]
I experienced a crash today while trying to use a tga file as an icon for a wii u game, it worked in the past, but now Playnite immediately crashes, and after a restart crashed again under the same conditions.
Diagnostic Package ID: d402d02c-11d9-443c-94e5-4c2c0557b5f6

Edit: As a workaround I've just converted the tga to a png with photoshop but a crash is still a crash.

**Comment by JosefNemec** [comment]
Can you please attach tga image causing the crash?

**Comment by kpd328** [comment]
sorry, the edit window for github was acting up, it won't let me attach directly, but here's a onedrive link https://1drv.ms/u/s!AoUNLus_xI3TlJpf2-xHjzxjth4GvQ

**Comment by JosefNemec** [comment]
Done in 5.0
