### ISSUE TITLE
Playnite fails to import games from Itch.io

### ISSUE THREAD

**Issue by D4KD4WG** [JosefNemec/Playnite#1173]
The same that happened in #984 but for version 4.74 when i try to import games from Itch.io
![jr2ga6cKaV](https://user-images.githubusercontent.com/48488232/58698644-ef54ea80-839b-11e9-8e48-17d64ccb96fc.png)

**Comment by JosefNemec** [comment]
Is this still an issue with Playnite 5?

**Comment by D4KD4WG** [comment]
Sorry for this late response but yes it does

**Comment by JosefNemec** [comment]
Can you go to "About Playnite" menu and create diagnostics package for me please?

**Comment by D4KD4WG** [comment]
I think i did it here's there ID 020db0e4-db2d-46d8-ab56-799c7e859feb

**Comment by JosefNemec** [comment]
Fixed in 5.7
