### ISSUE TITLE
Mass aply emulators and profiels to titles 

### ISSUE THREAD

**Issue by kernaldave** [JosefNemec/Playnite#1175]
HI, I use Retroarch  emulators, I wast trying to add a new profile (core), but it would not auto load it in on my already created Emulator. I was hoping that I could just create a new emulator and delete the old one and since the paths would be similar the new one would just take over. But that wasn't the case, now I have over a thousand titles with no emulator attach.  I do not want to delete them manually and re add  them, tried it with sega and I but my mouse (left click) and delete key through a gauntlet, of over 900 button presses, could really use a shortcut here.  any help would be really appreciated,  Don't really want to delete my SNES and N64 either, as i have manually spent hours changing custom cover art and meta data.

**Comment by JosefNemec** [comment]
Duplicate to #547. I'll try to squeeze at least editing of Play actions into 5.0 release since this is coming up as issue more and more lately.
