### ISSUE TITLE
Hidden games bug?

### ISSUE THREAD

**Issue by janforster** [JosefNemec/Playnite#118]
Hi,

It seems to me that the (since 2.0) "hidden" category is bugged (or the functionality changed?)... I cannot manage to ever have games in this category hidden:
- if the "hidden" selector is off I can see hidden games in my library (among rest of my games)
- if the "hidden" selector is on I can see only my hidden games

Could be that I am missing some 2.0 feature.

Cheers

**Comment by JosefNemec** [comment]
Yes that's a bug, it should work as prior to 2.0 Thanks for reporting it.

**Comment by JosefNemec** [comment]
Released in 2.1
