### ISSUE TITLE
Playnite crashed when downloading wallpaper from URL

### ISSUE THREAD

**Issue by deepbhattacharya** [JosefNemec/Playnite#1180]
Crash code --> e8dbc1dc-28e1-42db-ab87-fcce5836d87c

Repeated crashes when trying to manually set the background image URL (to: https://wallpapercave.com/wp/3U55bWo.jpg) and restarting via the 'Restart PlayNite' button.

Exiting PlayNite and opening the app again fixed it.

**Comment by deepbhattacharya** [comment]
This happened again today. The same (exit, start) fixed it.

I've been downloading hundreds of background images via PlayNite in the last couple days, and this happened each time after a long time spent (2+ hours I think) doing that, that might have something to do with it.

I've also noticed a few times the image does not actually download from the URL. But the same image I can download from browser and set as file. Not sure if related to this issue.

**Comment by JosefNemec** [comment]
Fixed in 5.0
