### ISSUE TITLE
Crash when adding game

### ISSUE THREAD

**Issue by Grawler** [JosefNemec/Playnite#1182]
When I'm trying to add a game, the app crashes. Tried with administrative rights, but that didn't change it.

I'm trying to add a game that was installed from the Windows Store (Vampyr). Last night I did the same with Forza Horizon 4 and that wasn't a problem.

Crash ID b06f6b41-55fd-46a9-b33b-29e01204b56c.

e: Uninstalled and re-installed the game to no avail. Also took ownership of the folder and gave everyone permission to use it.

e2: Just installed a random game from the Windows Store (Crosscode) and that can be added without a problem as well.

**Comment by delurfangs** [comment]
I also get a crash when trying to add vamprye while other windows store games (crackdown 3) worked just fine.

**Comment by jakewp11** [comment]
Same for me, but with Into the Breach on Windows Store.

Hellblade Senua's Sacrifice worked fine.

e4c58e44-735f-463c-afcb-305c33afff78

**Comment by JosefNemec** [comment]
It's fixed in `devel` and 5.0 beta.

**Comment by jakewp11** [comment]
Awesome, good to know. Thank you!

**Comment by Enderpanda** [comment]
Into the Breach crashes when trying to add from the Windows Store by 'detecting installed - I don't think there is a way to add it manually.

8c6191f6-463b-43a2-a8ba-5486051252e7

Note:  ABZU, Battle Chasers Nightwar, Hellblade Senua's Sacrifice, Hollow Knight, Ori and the Blind Forest Definitive Edition, Rise of the Tomb Raider, Ruiner, The Messenger, Undertale, and Wasteland 2 Director's Cut were all added without issue.

Also, I know they are known issues already, but I also get errors when trying to scan for non-installed games from Blizzard and Twitch.  Love the app, keep up the great work, thanks!

**Comment by JosefNemec** [comment]
Done in 5.0

**Comment by Enderpanda** [comment]
Fantastic, thanks!
