### ISSUE TITLE
New icon for Filter pannel

### ISSUE THREAD

**Issue by ClearStrelok** [JosefNemec/Playnite#1183]
The Xbox App is now out and I've noticed that it used the same type of icon as Battle.net for its game pannel Show/Hide toggle. The icon reverse itself depending on wether the panel is currently shown or collapsed.

![Sans titre-4](https://user-images.githubusercontent.com/38838369/59231294-772ec600-8be0-11e9-8028-d0634b253a4a.jpg)
![Sans titre-2](https://user-images.githubusercontent.com/38838369/59231295-772ec600-8be0-11e9-98f7-d1e5a3196070.jpg)

Any interest in using the same kind of icon for the filter panel ?

**Comment by ClearStrelok** [comment]
Quick and dirty preview of how it would like : 

![Sans titre-8](https://user-images.githubusercontent.com/38838369/59231591-8c582480-8be1-11e9-9708-81f31b7ea235.jpg)
![Sans titre-6](https://user-images.githubusercontent.com/38838369/59231592-8c582480-8be1-11e9-98ab-13102c036674.jpg)
![Sans titre-7](https://user-images.githubusercontent.com/38838369/59231593-8c582480-8be1-11e9-948c-0ee2f4579738.jpg)

**Comment by JosefNemec** [comment]
I don't think that properly represents a filter, rather some generic panel.
