### ISSUE TITLE
[Suggestion] Reminder for free games

### ISSUE THREAD

**Issue by leobenkel** [JosefNemec/Playnite#1185]
That would be great to have reminders for free games:

* Epic game has free game every 2 weeks
* Steam discounts
* Twitch has games once a month
* etc... 

Thanks for this awesome app !

**Comment by JosefNemec** [comment]
This will be done via http://www.isthereanydeal.com integration #278

**Comment by leobenkel** [comment]
Awesome thanks ! Can't wait for it !
