### ISSUE TITLE
Prevent launching games multiple times

### ISSUE THREAD

**Issue by XJIOP** [JosefNemec/Playnite#1191]
The problem is that my children always double-click on the game label and launch two game instances. Same problem for a long time in Steam launcher. I would like to enable such an option in the settings of Playnite that would prevent the launch of several copies of the game simultaneously.

**Comment by JosefNemec** [comment]
Is this still an issue with the latest version of Playnite? I can't reproduce it myself, but I'm not sure what you mean by "game label". What part of the application they use to launch the game specifically (and from what view)?

**Comment by XJIOP** [comment]
it was with version 4 and below, in the latest version I do not find this problem.
