### ISSUE TITLE
Playtime tracking broken for some Microsoft Store games (Possibly due to Title Update ?)

### ISSUE THREAD

**Issue by ClearStrelok** [JosefNemec/Playnite#1193]
So I've had Sea of Thieves added to Playnite for some time, now. However, I've only reinstalled it recently and noticed on both a first and second launch that Playnite, while able to launch the game, is unable to keep track of the process. 

I've re-imported the .exe of the game and the issue was caused by the installation folder now having a different ID. 

Former folder :
C:\Program Files\WindowsApps\Microsoft.SeaofThieves_2.75.7351.2_x64__8wekyb3d8bbwe

New folder:
C:\Program Files\WindowsApps\Microsoft.SeaofThieves_2.83.6356.2_x64__8wekyb3d8bbwe

Renaming the target folder in the game's details has fixed the issue, but I'm not sure if the change was caused by the way this particular game handles title updates or if it's anything else. Metal Slug 2 was also added some time ago and the process is still tracked with no issue, but this could be due to it not having been updated since.

**Comment by JosefNemec** [comment]
Yeah they changed something that prevents Playnite to access game's installation folder (permission issue). Especially if you install game using Xbox App, then it's completely busted.

**Comment by JosefNemec** [comment]
Already fixed in `devel`.

**Comment by JosefNemec** [comment]
Fixed in 5.1
