### ISSUE TITLE
Failure in plugin settings load crashed the whole application

### ISSUE THREAD

**Issue by Dnomyar96** [JosefNemec/Playnite#1196]
I wanted to try the classic theme, so I selected it and restarted Playnite. However, I really don't like it, so now I want to switch back. But whenever I try opening the settings, the application crashes.

Diagnostic package id: acea7346-b636-42d0-bf14-d22483783d57

**Comment by JosefNemec** [comment]
It crashes because you have some custom plugin installed (called `CustomPlugin`) and it fails to load its settings.

**Comment by Dnomyar96** [comment]
Thanks! Removing the plugin worked. Do you happen to know why it fails to load the settings? I made it according to the docs and it worked fine before switching the theme (it doesn't work anymore though, even after switching back). Does it throw some kind of exception or anything?

**Comment by JosefNemec** [comment]
You can find stack trace in `%AppData%\Playnite\playnite.log`. I don't know why it crashes (I didn't have time to investigate it more deeply), but my guess is that you are not passing correct parameters into `LoadPluginSettings` method.

**Comment by Dnomyar96** [comment]
Ah, thanks! The parameters are fine it seems. It throws a NullReferenceException, so somewhere I use an object that's not initialized. Those logs are pretty usefull actually! Thanks again!

**Comment by JosefNemec** [comment]
Done in 6.0
