### ISSUE TITLE
playnite crashes when game has to be updated in steam

### ISSUE THREAD

**Issue by backtolinux** [JosefNemec/Playnite#1197]
playnite crashed when game has to be updated in steam
Games resided on samba share.
Games was marked playable.
Clicking on button play made playnite to crash with this number for error details : 5a6d66f1-8560-461f-a466-c54a5eb7d893

**Comment by backtolinux** [comment]
It seems all games on samba share made playnite to crash.
But, when game is really playable, playnite crashed and game is launched.

**Comment by JosefNemec** [comment]
There are multiple know issues with games located on network shares, we currently don't support it until #950 is finished.
