### ISSUE TITLE
Playnite have issue grouping

### ISSUE THREAD

**Issue by fr4nk1sh** [JosefNemec/Playnite#1198]
Please use search first to see if the issue is already opened. Thank you
Playnite don't recognize Starcraft 2 as a blizzard game and can not start it or group in the in app.

**Comment by JosefNemec** [comment]
Only automatically imported games will show under Battle.net library. Did you add it manually?

**Comment by fr4nk1sh** [comment]
Oh yes, I believe I did.. but I did it cause it would not find it automatically.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by JosefNemec** [comment]
If it didn't detect it automatically then try repairing Starcraft 2 installation from Battle.net client, that usually fixes it.

**Comment by fr4nk1sh** [comment]
Just to let you know, you were spot on. It sure did solve the “issue”. Thanks!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
