### ISSUE TITLE
Count and display playtime

### ISSUE THREAD

**Issue by JosefNemec** [JosefNemec/Playnite#120]

**Comment by Snorrp** [comment]
This would be top notch

**Comment by Snorrp** [comment]
Update?

**Comment by Elias-gg** [comment]
Is this still in progress? Would I be able to take a swing at implementing it?

**Comment by JosefNemec** [comment]
Yes it's in progress, I'm currently working on it.

**Comment by MattGTX** [comment]
It Will be very nice to see this feature implemented in the next version :D Keep up the good work Josef!!!

**Comment by JosefNemec** [comment]
Released in 4.0
