### ISSUE TITLE
Authentication screen improvement

### ISSUE THREAD

**Issue by DennoCoil** [JosefNemec/Playnite#1200]
When trying to authenticate uninstalled games, if the firewall or something else is blocking the internet connection of Playnite, the popup to authenticate your account just shows a black browser screen.

There needs to be a check on the popup to see if Internet or the remote login is working or it throws an error “Could not communicate with server.”  Add a “Retry?” and "Close" button.

**Comment by JosefNemec** [comment]
This is not possible, each library integration plugin uses different process to authenticate and Playnite itself has no idea about what's happening during the authentication process.
