### ISSUE TITLE
option to add shortcuts instead of .exe files

### ISSUE THREAD

**Issue by boynet** [JosefNemec/Playnite#1201]
it will allow us to solve some stuff like https://github.com/JosefNemec/Playnite/issues/1193 and others by allowing us in the file browser to choose shortcuts instead of .exe files.

for example microsoft store games have shorcuts, but they dont point to any file.

here example for uwp gears of war game shortcut(see how the target dosent point to anything:
![Untitled](https://user-images.githubusercontent.com/1615629/59668752-b0a79880-91c1-11e9-8e58-92317f13d6a3.jpg)

**Comment by JosefNemec** [comment]
You can already set any executable file in any action, including shortcuts.

**Comment by boynet** [comment]
I know its not support here, but when trying to add shortcuts to uwp app it says "Catastrophic failure"
testes with multiple games like:

- gears of war
- orh and the blind forest
- rise of the tomb raider

tried adding them manually or by dragging them into the app, both options fail
