### ISSUE TITLE
Server-Client System

### ISSUE THREAD

**Issue by delfino434** [JosefNemec/Playnite#1204]
Can we write the program in the form of server and client and record game progress

**Comment by JosefNemec** [comment]
I have no ideas what you mean by this. What do you mean by "record game progress" and what does is have to do with Server-Client architecture?

**Comment by delfino434** [comment]
http://www.ucgenoyunarsivi.com/  buna bir bak

**Comment by JosefNemec** [comment]
I'm sorry but I don't speak Turkish and the web page doesn't have English version. Please specify what are your functionality requirements in English.

**Comment by delfino434** [comment]
can you add admin login system

**Comment by ChildishGiant** [comment]
From looking at the [Google translate version](https://translate.google.com/translate?sl=auto&tl=en&u=http%3A%2F%2Fwww.ucgenoyunarsivi.com%2F) it seems to be software licensed to Turkish internet cafés so users can keep their progress across different visits or potentially different cafés. This seems entirely out of scope for this project to me.

**Comment by JosefNemec** [comment]
Honestly when I looked at translated version it didn't really clear things up for me, I was not sure if it backs up user data or the whole games. Anyways I agree that it's completely out of scope for Playnite and it's also a very niche feature that would not benefit the overall Playnite community (given how much resources it would take to implement it).
