### ISSUE TITLE
Homonyms can get wrong metadata (e.g. The Witness)

### ISSUE THREAD

**Issue by lapo-luchini** [JosefNemec/Playnite#1207]
**The Witness** in Epic Store and Playnite:
![image](https://user-images.githubusercontent.com/420454/59964663-bd025d00-9503-11e9-8931-49be4ded56af.png)

**Comment by JosefNemec** [comment]
There's nothing we can do about this because we don't get a release date from Epic store to match games better. Sorry

**Comment by lapo-luchini** [comment]
Maybe a text file with a map of exceptions? (title → id, or epic id → id)
(would be a hassle to keep updated, but maybe the community could help with that)

**Comment by JosefNemec** [comment]
That's not realistic because it's not going to be maintainable in long term. What would be an actual solution is if IGDB would allow to assign game ids from Epic store (and other stores as well, right now they only do it for Steam and GOG as far as I know).

**Comment by lapo-luchini** [comment]
I suggested it and IGDB support told me support for Epic and other stores is already on this year's road-map.
