### ISSUE TITLE
Spectabis compability?

### ISSUE THREAD

**Issue by vannessqn** [JosefNemec/Playnite#1208]
Can I use Playnite with Spectabis (PCSX2 front end with per game configuration) ?

**Comment by JosefNemec** [comment]
There's no support for Spectabis and it doesn't make sense to me to include it (being custom launcher as Playnite). The per game configuration should be now possible if you pass PCSX2 config file to additional arguments in Playnite's Play action.

Some advanced GUI for emulator settings (like what Spectabis offers) will be possible once we improve our emulator support with #653
