### ISSUE TITLE
Option to randomly pick a game to play

### ISSUE THREAD

**Issue by JosefNemec** [JosefNemec/Playnite#121]
You know, sometimes there's just too many options to choose from...

**Comment by ChildishGiant** [comment]
![image](https://user-images.githubusercontent.com/13716824/57333849-ef075d80-7115-11e9-92c6-2d271e0a0436.png)
It could function similarly to the one on steamdb where it'd offer you random games or you can launch a random game

**Comment by darklinkpower** [comment]
Just wondering which implementation you'll make. Will it choose from every installed game randomly or the games that are showing after applying filters?

**Comment by JosefNemec** [comment]
Current plan is to add checkbox that would limit selection only to currently applied filter. That way you would be able to fine tune the selection to your liking (for example only choosing from games that you never played before).

**Comment by JosefNemec** [comment]
Done in 6.0

**Comment by sushicw** [comment]
Aw yiss. 🎉

**Comment by HunterXd2904** [comment]
Hey, I just downloaded  Playnite (very cool program btw) and i trying to figure out how to ramdomly run a game. In resume there's the button with a dice that shows me a ramdom game acording to the current filter. I want to click the dice and a random game just start to run. There is some way to do it?

**Comment by JosefNemec** [comment]
There is no way to immediately run random game, not sure that's a good idea from UX perspective. You either select random game from the list or open random game picker dialog.

You could for sure make this as a plugin though.

**Comment by HunterXd2904** [comment]
I'm trying to make a plugin right now actually lol. But to be honest i think i guetting nowhere, since i basically have 0 experience with programing in general im using chat GBT to help me, but looks like he canot to it too. I managed to do a code that can list all the games in my library but i dont get how to run a random game from that, GPT keeps saying that the games need to have an action called "PlayAction" , but i just dont understand what this means. Anyway i think gonna keep searching until i get somewhere.

**Comment by JosefNemec** [comment]
Don't ask GPT or any other LLM for help, they will not be able to generate working code for Playnite. Playnite is way too niche for any LLM to generate working stuff. Many people tried before you and failed. I recommend joining our Discord server and asking in extension development channel for specific help.

**Comment by HunterXd2904** [comment]
Thanks for the tip. Gonna do that.

**Comment by darklinkpower** [comment]
> I'm trying to make a plugin right now actually lol. But to be honest i think i guetting nowhere, since i basically have 0 experience

@HunterXd2904  I know how difficult it can be when I was new to making extensions with zero knowledge. Here are some pointers:

1. Method to find and launch a game.
- First you need to get your list of games, if you prefer all games in your database use [PlayniteApi.Database.Games](https://api.playnite.link/docs/api/Playnite.SDK.IGameDatabase.html#Playnite_SDK_IGameDatabase_Games). If you prefer the ones in view, use [PlayniteApi.MainView.FilteredGames](https://api.playnite.link/docs/api/Playnite.SDK.IMainViewAPI.html#Playnite_SDK_IMainViewAPI_FilteredGames)
- Of course you must filter by IsInstalled, as uninstalled games can't be played.
- Use [Random](https://learn.microsoft.com/en-us/dotnet/api/system.random?view=net-8.0) to pick a random game from your games list. To relate with the previous conversation, this is general specific knowledge outside of Playnite so LLMs like ChatGPT will easily guide you if you have issues.
- Use [PlayniteApi.StartGame](https://api.playnite.link/docs/api/Playnite.SDK.IPlayniteAPI.html#Playnite_SDK_IPlayniteAPI_StartGame_System_Guid_) method to start the game using the game Id.

2. Create your sidebar or top panel icon that calls the method you created, where Activated calls the method you created: https://api.playnite.link/docs/tutorials/extensions/ui.html?tabs=csharp#top-panel


I think this could be a good learning experience but if you get stuck let me know and I can create the extension for you.
