### ISSUE TITLE
Added a finished game indicator.

### ISSUE THREAD

**Issue by SubActif** [JosefNemec/Playnite#1210]
It would be nice to have a field or box that is easily accessible (right click for example) to indicate if the game is finished.

If you tick or activate the box it will display a small icon next to the name to immediately see that you have marked this game as finished.

It would be useful for big accounts that have a lot of games including a lot of independent games and that sometimes we have more in mind if we finished them or not and it will avoid having to load the game.

**Comment by ArtexJay** [comment]
It would be cool if you could connect Playnite to IGDB to mark/keep track of games you are playing, finished or wanting to play.

**Comment by JosefNemec** [comment]
Ability to link IGDB accounts is planned in  #594

**Comment by JosefNemec** [comment]
Playnite 5 now displays completion status on game's page. Is that enough that I can close this?

**Comment by JosefNemec** [comment]
Closing since there's no response to my last question.
