### ISSUE TITLE
Add a field where is backup folder (and maybe more)

### ISSUE THREAD

**Issue by SubActif** [JosefNemec/Playnite#1211]
It would be nice to have a field to indicate the location of backups.

I don't know if there is a database or site that could be parsed to take the values automatically but otherwise just leave the field blank that could be clicked to select the folder and that it would allow with a button to open the backup folder directly.

See more extended function to allow you to save these backups in Zip to a playnite folder.

See if playnite can't do it or doesn't want to be able to connect it to the "GameSave Manager" software that does it.

This will make a very interesting addition to a library management so we could check that we have made a backup before deleting the game.

**Comment by JosefNemec** [comment]
Duplicate to #124
