### ISSUE TITLE
KeePass use with library authentications keeps entering text in the main Playnite Window.

### ISSUE THREAD

**Issue by WolvenSpectre** [JosefNemec/Playnite#1213]
When reauthenticating my library authentications using the KeePass Password Vault instead of entering credentials in the Account Name and Password fields it goes back to the primary Playnite Window and types the info in the search box.

Normal behavior has the user go from the window with the fields for credentials and then to KeePass to find them and fill them out for you.

**Comment by tylerszabo** [comment]
Playnite's `WebViewWindow` has no title, so KeePass can't detect which window to match for auto-fill. It looks like the `TitleChanged` event from `CefSharp.Wpf.ChromiumWebBrowser` could be passed through to change the window title. Appending " - Playnite" would make it appear like other web browser windows and should work for KeePass.

**Comment by tylerszabo** [comment]
I'll take a crack at this.

**Comment by JosefNemec** [comment]
`ChromiumWebBrowser` doesn't control window's title. You need to modify `WebView` class and change it though `window` field. The best solution would be to extend `IWebView` and allow plugin users to set custom title if they want to.

**Comment by JosefNemec** [comment]
Scratch what I said in my previous comment, I haven't though it though :)

**Comment by JosefNemec** [comment]
Done in 5.0
