### ISSUE TITLE
Fullscreen stretches to all monitors

### ISSUE THREAD

**Issue by tomblind** [JosefNemec/Playnite#1216]
version 4.74

I have 3 screens: one 4k (175% scaling), and two 1080s (100% scaling). When I run in full screen mode, everything is stretched across all three monitors. I tried turning on "Disable DPI Scaling" as was mentioned in #785, but it made no difference.

![Untitled](https://user-images.githubusercontent.com/26638278/60140035-6f892880-976d-11e9-8f06-98fbd6291e89.jpg)

**Comment by tomblind** [comment]
It does seem to be DPI related. If I change my primary monitor to 100% scaling, it works correctly. Any other value causes the stretching.

**Comment by tomblind** [comment]
I found an interesting workaround: Setting "High DPI scaling override" to "System" in PlayniteUI.exe's properties allows it work correctly (regardless of whether Playnite's "Disable DPI Scaling" is set or not). I would hazard a guess that the setting isn't being applied, but the windows override has the same effect.

**Comment by JosefNemec** [comment]
Duplicate to #739

**Comment by tomblind** [comment]
This is still a problem on version 5.3. Fullscreen mode tries to stretch to all monitors. If I try to change to target display in fullscreen settings, Playnite won't display anything at all. "Disable DPI Scaling" still has no effect. The only way for fullscreen to be usable is setting the Windows High DPI scaling override to "System", but then everything is blurry.

![Untitled](https://user-images.githubusercontent.com/26638278/61995363-c7ed6780-b044-11e9-8a8d-4514b19903cc.jpg)

**Comment by JosefNemec** [comment]
Do you have Windows 10 1903? Because 1903 broke the way we handle DPI settings and I was unable to find the fix so far.

**Comment by tomblind** [comment]
This may be related to #1282?

**Comment by tomblind** [comment]
Ah yes - I'm on 1903

**Comment by tomblind** [comment]
Just to confirm - v5.4 fixed this. Thanks!
