### ISSUE TITLE
Descriptions text appears blurry (when scrolling down)

### ISSUE THREAD

**Issue by ClearStrelok** [JosefNemec/Playnite#1217]
I'll swear there used to be a similar issue, but I can't find in both closed and open categories. When switching from one game to the next, the text in the description often appears soft and unfocused, like so :

![Sans titre-18](https://user-images.githubusercontent.com/38838369/59803095-c8c70700-92ea-11e9-9bf4-5edf35c504ef.jpg)

This happened in 4.74 too and generally occurs when the previous game description was scrolled down. Simply clicking on the text temporarily fixes the issue : (but scrolling down again generally brings it back) 

![Sans titre-19](https://user-images.githubusercontent.com/38838369/59803096-c8c70700-92ea-11e9-98bd-043ded632c9e.jpg)

**Comment by JosefNemec** [comment]
I also remember this being an issue in past, but I was also unable to find the issue or commit for it :(

**Comment by JosefNemec** [comment]
Fixed in 5.7
