### ISSUE TITLE
Ideas for playnite

### ISSUE THREAD

**Issue by Kroelbeertje** [JosefNemec/Playnite#1221]
Ideas / Improvements: 

- Being able to import covers and icons from links like here: [https://imgur.com/a/gYOZTdb](url)

- Automatic look for a background on the internet [https://imgur.com/a/2x7yGI2](url) So if there is no background look the title up and put a blur on it instead of nothing.

-  Using The updated Reddit logo 

- Epic store Games pulling icons from the web instead of using the epic logo

- Having a home screen with a rss feed like discord for example [https://imgur.com/a/6HWGrBA](url)

**Comment by JosefNemec** [comment]
All of these are already opened as separate issues. Also please don't bundle more feature requestes into one issue in future, thank you.
