### ISSUE TITLE
Play time not being counter properly for Dark Souls 3 when launcher via mod launcher

### ISSUE THREAD

**Issue by TrueCP6** [JosefNemec/Playnite#1228]
Having a checkbox in each game's settings for whether to force sync play time for only that game would be a really great feature.

**Comment by JosefNemec** [comment]
Why would you want to sync play time only for specific games and not others?

**Comment by TrueCP6** [comment]
I launch Dark Souls 3 through a mod launcher shortcut through Playnite so Playnite doesn't recognize my playtime correctly. I would turn on force sync for all but a lot of my hours in some games are offline and it wouldn't show my actual playtime. For now I can just update them manually every now and then.

Great program btw

**Comment by JosefNemec** [comment]
I think the correct way to approach this would be fixing the issue of Playnite not tracking time with your setup. Did you actually edit game's Play action to start the mod launcher? If you disable "Managed by library plugin" option and set it to `Executable` type with launchers exe set in `Path` property, then Playnite should count the play time properly.

**Comment by TrueCP6** [comment]
It has to launch a shortcut file which is probably why the issue is happening.

**Comment by tylerszabo** [comment]
I think this feature would be handy; but in thinking bout why I came to believe it's an aspect of a more complex idea.

My use case is as follows: I often (but not always) use launch the game through the store launcher to take advantage of playtime tracking there as it will accumulate regardless of which machine I'm using. I sometimes play a game on my laptop and want to resync just that game's time (this is especially true if there's a game that I don't use the store launcher for and syncing will force me to manually restore it).

In thinking about my problem I came to realize I was trying to work around a more complex issue in that a "game" as PlayNite sees it doesn't match how I see it. PlayNite considers a Title, Store-SKU, Installation, as a single "Game" object (both conceptually and structurally) and I think that has limitations.

It might make sense to normalize Game schema slightly; I'm not sure a "game" and a "library item" are necessarily the same thing all the time. Different data in a game have different loci:

----

### Title (Global)
Information that doesn't depend on editions or vendor
 - Critic score, time to beat, description, additional resources (wiki, Forum), etc.

### Store-SKU (Global)
A particular SKU in a particular game store
- Examples: Wasteland 2 (Steam), Wasteland 2: Directors Cut (Steam), Wasteland 2: Director's Cut (GoG) are all distinct store-SKUs despite all potentially being considered the same game "Wasteland 2".
- Specific Title, Platform, Publisher, etc.

### Installation (Personal)
There may be more than one on a single machine (multiple copies of a game with different configs), may exist on multiple machines, may not exist at all (uninstalled everywhere)
- Install directory, Launch Actions, Installed/Running states, etc.

### "Concept" (Personal)
A personal concept of a particular "game". It's possible any particular person would want to think of a game in terms of its particular Store-SKU or Title, or Installation. It may even be a cross-platform idea - one might want to be able to count how much time was spent playing Minecraft regardless of whether they played it on a console or on their PC.
- Play time, last played, play count

----

Each library is inherently personal but the "Global" information can be initially populated from shared databases (such is IGDB or the stores) and conceptually lives globally.

Given this, I think it would also make sense to consider this part of a larger idea where things like play time are shown potentially as aggregations (local counter + game store A's counter + game store B's counter).

**Comment by JosefNemec** [comment]
@tylerszabo Please open that as separate issue.

**Comment by JosefNemec** [comment]
Will be done as part of #1348
