### ISSUE TITLE
[ REQUEST] New Launchers support

### ISSUE THREAD

**Issue by pcwizard7** [JosefNemec/Playnite#1238]
hey i don't if this isn't even been worked on anymore but shame cause its best third party manager i ve seen so i like to know whats up

if you are still development the app could you add support for new launchers that popup and we can't have that ?

Bethesda
Epic Games

**Comment by JosefNemec** [comment]
Epic is already supported and full support for Bethesda is being tracked in #303 (only installed games are being imported right now).
