### ISSUE TITLE
Ability to backup game save file (cloud sync)

### ISSUE THREAD

**Issue by ryantheleach** [JosefNemec/Playnite#124]
This is likely out of scope, but if Playnite takes off, having a unified cloud save / manual backup feature of some kind would be amazing for game saves.

Too often are the save files on PC games neglected or not backed up, due to being strewn across so many god damned directories.

**Comment by JosefNemec** [comment]
I would like to eventually do something like this. Basically what GameSave Manager does, but well integrated and with some cloud sync support.

**Comment by Astuceman** [comment]
hmm yeah that would be a great idea even if I think it's hard to get developed

**Comment by JosefNemec** [comment]
I thought about it and it's not going to be that hard. The hardest part is to detect where the save files for specific game are located. I guess we will have to let use specify that, because I have no idea how to detect  save location reliably.

**Comment by Astuceman** [comment]
I have found that PCGamingWiki have save data location for every game
https://pcgamingwiki.com/wiki/Don%27t_Starve

**Comment by bburky** [comment]
[GameSave Manager](https://www.gamesave-manager.com/)'s database of save game locations is downloadable as a sqlite database: https://www.gamesave-manager.com/?s=download&f=db_update_direct&a=dl

Note, that application is freeware not open source. I'm not sure if the developer would be happy with us using their database though.

**Comment by aabeba** [comment]
This would be great, especially for emulated games. The ability to pick up where you left off on different physical platforms (PC, Switch, GPD XD...) would be a life-changer for me.

**Comment by mtkennerly** [comment]
Hi! I just released a [Playnite plugin](https://github.com/mtkennerly/ludusavi-playnite) for automated save backups that could be helpful here (although it doesn't have direct cloud integration [yet](https://github.com/mtkennerly/ludusavi/issues/13)). It uses [Ludusavi](https://github.com/mtkennerly/ludusavi) and ultimately sources data from [PCGamingWiki](https://www.pcgamingwiki.com/wiki/Home) so that everyone can help to add/improve the data.

**Comment by RiseT** [comment]
Tried Ludusavi (currently without the Playnite plugin), and pleasantly surprised how well it works. Some saves weren't backed up due to currently incorrect PCGamingWiki entries, though (e. g. Totally Accurate Battle Simulator on Epic).

Now, my primary point: In order to find out which installed games have no cloud backup (so I have to backup them manually), I've (unsuccessfully) tried to filter in Playnite for "installed" + "no cloud saves". It's possible to filter for "installed" + "cloud saves", though. Any possibility to filter in Playnite for "no cloud saves"?

**Comment by darklinkpower** [comment]
@RiseT There's no exclude filter in Playnite. You could add a "No Cloud saves" feature via an extension and filter them. This should work:

```
function GetMainMenuItems
{
    param(
        $menuArgs
    )

    $menuItem1 = New-Object Playnite.SDK.Plugins.ScriptMainMenuItem
    $menuItem1.Description = "Add `"No Cloud`" feature"
    $menuItem1.FunctionName = "Add-Feature"
    $menuItem1.MenuSection = "@No Cloud"
    
    return $menuItem1
}

function Add-Feature
{
    # Create Feature
    $featureName = "No Cloud Saves"
    $feature = $PlayniteApi.Database.Features.Add($featureName)
    
    # Set GameDatabase
    $GameDatabase = $PlayniteApi.MainView.SelectedGames | Where-Object {$_.Platform.Name -eq "PC"}
    
    # Set counters
    $FeatureAdded = 0
    
    # Start Execution for each game in the database
    foreach ($game in $GameDatabase) {
        if (($game.Features.name -contains "Cloud Saves") -and ($game.Features.name -notcontains $featureName))
        {
            # Add feature to game
            if ($game.FeatureIds) 
            {
                $game.FeatureIds += $feature.Id
            } 
            else
            {
                # Fix in case game has null FeatureIds
                $game.FeatureIds = $feature.Id
            }
            
            # Update game in database
            $PlayniteApi.Database.Games.Update($game)
            $FeatureAdded++
            $__logger.Info("Added `"$featureName`" feature to `"$($game.name)`".")
        }
    }
    
    # Show finish dialogue
    $PlayniteApi.Dialogs.ShowMessage("Added `"$featureName`" feature to $FeatureAdded games.","Steam Mini");
}
```

**Comment by RiseT** [comment]
Hey, great! Thank you very much for your (unexpected) effort, will definitely try this!

**Comment by RiseT** [comment]
@darklinkpower Hallo again, I've just tried your script and I'm always getting "Added "No Cloud Saves" feature to 0 games."

Any idea what's going wrong, i. e. is the fault on my side - which is very possible since I've never dabbled with a Playnite extensions before and have virtually no PS knowledge (only some Python)? Thanks in advance for your efforts.

**Comment by darklinkpower** [comment]
@RiseT I just tried it and it works correctly. Make sure to select the games that you want to add the feature before using the function. If you want to search in all games in your playnite database, change 
` $GameDatabase = $PlayniteApi.MainView.SelectedGames | Where-Object {$_.Platform.Name -eq "PC"}`
for
` $GameDatabase = $PlayniteApi.Database.Games | Where-Object {$_.Platform.Name -eq "PC"}`

**Comment by RiseT** [comment]
@darklinkpower Dumb me - I indeed hadn't selected any games as I expected it to work on all games in the database. Works like a charm now - many, many thanks for your efforts & help!

**Comment by darklinkpower** [comment]
@RiseT The "Cloud Saves" feature gets added depending on your configured Metadata settings in `Settings` -> `Metadata`. As far as I know, only the built-in steam metadata provider and the Universal Steam Metadata metadata extension have that feature in them and add it to the games. If you have games with the "Cloud Saves" feature, it was almost surely added by them.

**Comment by darklinkpower** [comment]
@RiseT Now that I remember, I made an extension to check if your selected games are in the list of games with missing save info in Ludusavi. You can use it and cross information with the "No cloud saves" extension https://playnite.link/forum/thread-343-post-1361.html#pid1361

**Comment by RiseT** [comment]
> The "Cloud Saves" feature gets added depending on your configured Metadata settings in `Settings` -> `Metadata`.

Oh, I see, Ludusavi gets its data from PCGamingWiki, not Playnite - I mixed that up.

Just checked the "Lego Marvel Super Heroes 2" (Steam) example - the features info on Steam's store page indeed doesn't mention the cloud save feature, although it's definitely implemented in that game. So it's Steam's oversight.

> Now that I remember, I made an extension to check if your selected games are in the list of games with missing save info in Ludusavi.

Will check that out. Thx!

**Comment by CRAWLER-V** [comment]
Sorry, i've just try now Ludusavi, but when i run it from inside the Playnite, a notification say: "Unable to run Ludusavi" what could it be?

**Comment by JosefNemec** [comment]
You need to ask developer of that plugin for support, this is place is for issues with Playnite only.

**Comment by mtkennerly** [comment]
@CRAWLER-V You can open a ticket for the plugin here if you need help: https://github.com/mtkennerly/ludusavi-playnite/issues . You may just need to configure it to point to the location of your ludusavi.exe: https://github.com/mtkennerly/ludusavi-playnite#Setup

**Comment by JosefNemec** [comment]
Closing this. I can't see myself doing this as a built-in feature since there's a lot of potential issues with this, therefore high maintenance/implementation cost (detecting saves path, backend implementation etc.). It's imo more fit to be done as an extension, like Ludusavi.
