### ISSUE TITLE
[5.0] info icon in grid view

### ISSUE THREAD

**Issue by By6r9** [JosefNemec/Playnite#1242]
![pldetailspanel](https://user-images.githubusercontent.com/32620314/61068548-95b7f500-a40a-11e9-8175-e5ff5a31d894.png)

In `Grid view` there is `i` icon. Normal behavior:  shows detail panel.
But: 
If you close detail panel, select some game, then press `i` icon, detail panel will open, but with message as on screenshot.

**Comment by JosefNemec** [comment]
Fixed in 5.1
