### ISSUE TITLE
5.0+ Full Screen UI UX Issues

### ISSUE THREAD

**Issue by LordFren** [JosefNemec/Playnite#1244]
Align top navigation items and bottom prompts to the pre-defined sage edges. Issue can be seen here: http://pics.frenlabs.com/xRBDIEyora.jpg

In the details page the text scrolling section should move up with some animation to allow larger surface area to read on and not limit the user to a tiny area to read on. http://pics.frenlabs.com/303VQiPXXt.jpg

**Comment by JosefNemec** [comment]
I don't think I can align the bottom menu. There won't be enough space for progress notification and search/filter indicator.

**Comment by JosefNemec** [comment]
Fixed in 5.1
