### ISSUE TITLE
Doesn't restore column size

### ISSUE THREAD

**Issue by MGMehdi** [JosefNemec/Playnite#1245]
Hi 
each time Playnite open for the first time it doesn't save the size of column so it's cropped 

After resize columns 
![Capture1](https://user-images.githubusercontent.com/48625769/61113407-837f9a80-a48e-11e9-8116-43f22deb12e3.PNG)

After first start of Playnite
![Capture](https://user-images.githubusercontent.com/48625769/61113331-57641980-a48e-11e9-87a6-24da537f9b84.PNG)

**Comment by JosefNemec** [comment]
Duplicate to #976
