### ISSUE TITLE
Crash while scrolling playnite after exiting game or app.

### ISSUE THREAD

**Issue by gamdes** [JosefNemec/Playnite#1246]
hello,

im using playnite 5 installed on version 4.7.

it crashed after exiting the game and scrolling the list of available games.

I've added Apps from the windows store, Kodi and Netflix it might have something to do with this. 

it also crashes when i launch netflix and when i exit kodi. and when exiting emulator like dosbox games. 

it didn't happen in the previous version.

thank you.

crash report

441341a1-b5f2-4185-a956-0862482f7b2c

**Comment by JosefNemec** [comment]
Fixed in 5.1
