### ISSUE TITLE
Track Playtime and add it to recently played list when opening game via another Play action

### ISSUE THREAD

**Issue by darklinkpower** [JosefNemec/Playnite#1247]
**Describe the solution you'd like**
When launching a game with another play action, Playnite doesn't track playtime.

Another issue is it doesn't add said game to the list of recent played games. 

Generally, play actions are used for configuration tools and manuals but some games actually run the game with another configuration, and it also helps if you add another play action for some other purpose yourself. A possible solution to cater both needs would be to implement an option in each play action that when checked, tells Playnite to track time and add it to the recent list when running with that specific Play action.

**Screenshots**

Example of game with Play actions automatically added by Playnite when it was added that runs the game with another configuration:
![imagen](https://user-images.githubusercontent.com/1389286/61174687-37edef00-a569-11e9-9065-0ac4094259d2.png)

Example of custom added play action for other purposes:
![imagen](https://user-images.githubusercontent.com/1389286/61174734-e5610280-a569-11e9-8481-1d2bd389f222.png)

**Comment by JosefNemec** [comment]
Will be done as part of #272
