### ISSUE TITLE
Unable to track Play Time (Diablo II LOD - Battle.net) 

### ISSUE THREAD

**Issue by ClearStrelok** [JosefNemec/Playnite#1250]
By default, Playnite launches both Diablo II and its expansion using _Diablo II.exe_. This is fine with Diablo II alone, but with the Lord of Destruction expansion it switches to _game.exe_ immediately, which breaks Play Time tracking.

**Comment by JosefNemec** [comment]
Both are started exactly the same by Playnite, there can't be any difference in time tracking (unless you modified the Play action settings). Something else must be affecting time tracking for an expansion.

**Comment by JosefNemec** [comment]
I was able to reproduce it. It doesn't make any sense, but I'll see what can be done about it.

**Comment by JosefNemec** [comment]
Fixed in 5.1
