### ISSUE TITLE
[Bug]Icons dissapear when scrolling too fast

### ISSUE THREAD

**Issue by develoqqer** [JosefNemec/Playnite#1255]
When scrolling to fast the icons will dissapear and become pitch black

**To Reproduce**
Scroll very fast, doesn't matter mouse wheel or the slider

![bug1](https://user-images.githubusercontent.com/52682107/61596011-d3f3a800-abb2-11e9-84a2-1bc6055b0a6d.png)
![bug2](https://user-images.githubusercontent.com/52682107/61596012-d3f3a800-abb2-11e9-8f29-1b99e7de4870.png)

**Comment by JosefNemec** [comment]
Do you have async image loading enabled? It's a bit buggy at the moment.

**Comment by develoqqer** [comment]
Where can I find that

**Comment by JosefNemec** [comment]
Settings -> Advanced

**Comment by develoqqer** [comment]
It's on

**Comment by JosefNemec** [comment]
Fixed in 5.7
