### ISSUE TITLE
InvalidOperation: (:) [Start-Process], InvalidOperationException

### ISSUE THREAD

**Issue by NuLz0** [JosefNemec/Playnite#1256]
While trying to compile the scripts in PowerShell with the help of the build.ps1, I get the following error: 
```
Start-Process : This command cannot be run due to the error: The system cannot find the file specified.
At C:\Users\*user*\OneDrive\Documents\Playnite-master\build\common.ps1:17 char:17
+         $proc = Start-Process $Path $Arguments -PassThru -NoNewWindow
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand
```
The line specified in the error which is contained in common.ps1 is the following:
```
{ 
        $proc = Start-Process $Path $Arguments -PassThru -NoNewWindow
    }
```
View of the error itself
![image](https://user-images.githubusercontent.com/25515334/61650824-8e061500-ac82-11e9-9d38-4e717eda828b.png)
View of the common.ps1 file
![image](https://user-images.githubusercontent.com/25515334/61650872-b2fa8800-ac82-11e9-9302-3565ca5cca9d.png)
View of the folder containing the scripts
![image](https://user-images.githubusercontent.com/25515334/61650892-be4db380-ac82-11e9-9a29-b652357099b6.png)

I will be more reachable on Discord: BootyLicker420#8007
Feel free to DM me. Thanks in advance :)

**Comment by JosefNemec** [comment]
Fixed
