### ISSUE TITLE
Option to scale the info panel

### ISSUE THREAD

**Issue by ChildishGiant** [JosefNemec/Playnite#1260]
![image](https://user-images.githubusercontent.com/13716824/61972933-b1aac180-afda-11e9-8048-4edad456c4f1.png)
Preferably with one of these thingys 
![image](https://user-images.githubusercontent.com/13716824/61973216-7f4d9400-afdb-11e9-9c63-9e4438513212.png)

**Comment by JosefNemec** [comment]
Settings option added in 5.4

**Comment by ChildishGiant** [comment]
Is there supposed to be a thingy for me to change the width with? I'm on 5.5 so I should have an option, right? or is it only available to themes?

https://gfycat.com/creativehospitablekronosaurus
![](https://thumbs.gfycat.com/CreativeHospitableKronosaurus-size_restricted.gif)

**Comment by JosefNemec** [comment]
You can't resize it by dragging it. There's only option to set the size in settings under `Layout` section.

**Comment by KaceCottam** [comment]
Sorry for reopening this issue after a long time; I would like to ask if there is any support planned for resizing the details menu by dragging? If you point me to the right files for where the panes in this view are set up/laid out, I would be interested in working on a pull request to do this. It seems like there is already a dynamic layout given that we can resize it at all-- so it should be somewhat simple!

**Comment by JosefNemec** [comment]
This is not a simple change because of how current layout works with ability to move panels to different sides. If you want, open different issue for drag support, this one was about ability to change the size in the first place.
