### ISSUE TITLE
Add plugin for Beamdog client

### ISSUE THREAD

**Issue by T-0pel** [JosefNemec/Playnite#1268]
[Beamdog](https://www.beamdog.com/) has their own client that is used for a few of their [enhanced edition games](https://www.beamdog.com/games/). It would be nice to add it as an option for people who bought the games before they were available on other platforms so that they unify their library.

Import of uninstalled games should be possible via the profile details on their website, i.e. https://store.beamdog.com/users/t-opel/, or contact them whether there is a public API method that could be used. Import of installed games only should be possible as well, but I will have to take a look at ways to identify that the game was installed via Beamdog. 

I could pick this task up if it is approved.

**Comment by JosefNemec** [comment]
I'm kind of split on an idea of adding support for launcher that has only 7 games on it (I know Battle.net...), since you could easily add those manually.

**Comment by T-0pel** [comment]
True, I did not realize it can be easily added manually and including downloaded metadata. With Battle.net you can argue that it is a much more high profile client and that the games cannot be obtained legally any other way, whereas Beamdog games you can buy them on many other clients.
