### ISSUE TITLE
Version 5 covers in details mode in seemingly incorrect place/scale

### ISSUE THREAD

**Issue by rmccullagh99** [JosefNemec/Playnite#1269]
The bug appears to be that the Cover icon for any game in the new version in the Details mode has moved from the left to a section in the right and is scaled down to the point where it doesn't seem like the intended choice. See the uploaded image for an example.
If it helps to know, I'm using a dual monitor setup with my primary monitor's resolution of 4k and secondary monitor with a 1080p resolution. I use Playnite on my primary monitor.
Screenshot:
![playnite bug](https://user-images.githubusercontent.com/42370113/61987858-46560380-b05d-11e9-9f77-5cebfcac5bba.JPG)

**Comment by darklinkpower** [comment]
The cover being to the right is perfectly normal, that's where it's placed in the current version. The only thing you can add (without modifying the theme itself) is the game icon by going to options and game details.
![imagen](https://user-images.githubusercontent.com/1389286/61990081-1bd55d80-afff-11e9-90d0-216ba038314a.png)

But I agree that the scaling looks off, maybe try check your DPI scaling settings in Playnite and Windows.
![imagen](https://user-images.githubusercontent.com/1389286/61990095-53440a00-afff-11e9-8dd9-80375a54a9da.png)

I hope this helps, if not Crow will have to step in.

**Comment by JosefNemec** [comment]
This is because the image there has set height for consistency. I agree that it looks weird when vertical style cover image is used, but there's way to make it look consistent for both banners and DVD covers without setting either width or height to a static value.

Probably the only solution would be to make the height configurable in settings.

**Comment by JosefNemec** [comment]
I forgot to also mention that the new placement is intentional since previous solution didn't work very well on smaller screens.

**Comment by rmccullagh99** [comment]
Ah, I see. I was simply worried it wasn't intentional, as due to vertical covers and my 4k monitor the spacing looks kinda eh. Thanks though

**Comment by JosefNemec** [comment]
You can now change height of the image in 5.7 via application settings.
