### ISSUE TITLE
Fullscreen mode: Views use descending sorting option by default instead of ascending, which is more natural

### ISSUE THREAD

**Issue by darklinkpower** [JosefNemec/Playnite#1273]
I found the following issues:

**All view:**  uses Descending sorting option by default, which is not optimal
![imagen](https://user-images.githubusercontent.com/1389286/61989441-04917280-aff5-11e9-8c7f-735adc2d48e8.png)

**Favorites view:** uses Descending sorting option by default too
![imagen](https://user-images.githubusercontent.com/1389286/61989484-ba5cc100-aff5-11e9-8782-77fa578d2a18.png)

**Comment by JosefNemec** [comment]
Fixed in 5.4
