### ISSUE TITLE
Fullscreen mode: Switching between Horizontal and vertical scrolling bugs the views.

### ISSUE THREAD

**Issue by darklinkpower** [JosefNemec/Playnite#1274]
**Switching form Horizontal scrolling to vertical scrolling:** 

Depending on how far to the right you scrolled you will see less covers when switching back to vertical scrolling. There's no way to fix the view other than switching to horizontal and then vertical again without moving.
![imagen](https://user-images.githubusercontent.com/1389286/61989655-76b78680-aff8-11e9-98d8-f8db75e2d4ac.png)
![imagen](https://user-images.githubusercontent.com/1389286/61989698-e594df80-aff8-11e9-9c71-f3ca8fcfc9f8.png)
![2019-07-26_22-53-20](https://user-images.githubusercontent.com/1389286/61989875-432a2b80-affb-11e9-8f15-28ef6b9035ed.gif)

**Switching form Vertical scrolling to horizontal scrolling:** 

Depending on how far down you scrolled you will see less covers when switching back to horizontal scrolling. Fixable by moving around.
![imagen](https://user-images.githubusercontent.com/1389286/61989792-f2fe9980-aff9-11e9-87be-fb403f356e01.png)

![2019-07-26_23-03-44](https://user-images.githubusercontent.com/1389286/61989824-6e604b00-affa-11e9-82d6-3a0d01467f14.gif)

edit: sorry for all the name changing in my opened issues, I put desktop mode instead of fullscreen mode at first, I was just a little tired.

**Comment by JosefNemec** [comment]
I can no longer reproduce it with Playnite 7. Can you confirm that this is still an issue for you with Playnite 7?

**Comment by JosefNemec** [comment]
Closing based on conversation on Discord.
