### ISSUE TITLE
Fullscreen mode suggestion: Possibly change a button term and add one missing

### ISSUE THREAD

**Issue by darklinkpower** [JosefNemec/Playnite#1275]
Currently pressing the xbox one start button opens the specific game options, which in my opinion is not too clear. My suggestion is changing said term to "Game Options".

Also pressing the xbox one controller back button (or whatever it's called) opens Playnite's option menu but currently there is no button that indicates that that button opens said menu, so my suggestion is adding one below.

![imagen](https://user-images.githubusercontent.com/1389286/61989961-27278980-affd-11e9-91e4-edc6acc4ca02.png)

If the term is changed, it would be neccesary to modify it in the game details screen.

![imagen](https://user-images.githubusercontent.com/1389286/61990001-b896fb80-affd-11e9-8599-74e810b9bbdf.png)

**Comment by JosefNemec** [comment]
I agree with renaming the button to Game Options, but adding another one to the bottom panel is no go. There's already very little space there if filter is enabled and then some progress shows up.

However we could probably add the button indicator next to the menu icon on top right which activates menu as well.

**Comment by JosefNemec** [comment]
@LordFren What do you think?

**Comment by JosefNemec** [comment]
Renaming from Options to Game Options is done already and we won't be adding extra Options button, because there's not enough room for it (once the filter/search is enabled or progress is shown).
