### ISSUE TITLE
Sort alphabetically ignoring "the"

### ISSUE THREAD

**Issue by jobbogamer** [JosefNemec/Playnite#1279]
When sorting alphabetically, all the games starting with "The" appear together under T. In general most applications tend to ignore "The" when sorting, so for instance "The Messenger" appears under M and "The Witness" appears under W.

Strangely, I notice that *some* games starting with "The" are sorted as I expect, but not all. For example in the screenshot below, The Talos Principle is shown where I expect, but there are a lot of other games which are all grouped by "The".

![image](https://user-images.githubusercontent.com/661493/61993743-2d9f1b00-b068-11e9-9cf3-024ed41a2da6.png)

**Comment by JosefNemec** [comment]
There's a separate field you can set for any game called `Sorting Name`, that's used for exactly that purpose. We do usually populate it, but there might be scenarios where you need to set it manually.
