### ISSUE TITLE
"Completion status" filter doesn't behave properly

### ISSUE THREAD

**Issue by ClearStrelok** [JosefNemec/Playnite#1281]
See screenshot : 

![Sans titre-4](https://user-images.githubusercontent.com/38838369/61994277-4401a280-b079-11e9-8708-54da1a3f20d1.jpg)

Checking "Played" in the _Completion status_ filter will bring up "Less than an hour" in the _Time Played_ filter and so on. This cannot be reversed.

**Comment by JosefNemec** [comment]
Fixed in 5.4
