### ISSUE TITLE
Fullscreen mode doesn't render properly when using non-100% DPI scaling

### ISSUE THREAD

**Issue by Revolt64** [JosefNemec/Playnite#1282]
**Describe the bug**

They say a picture is worth a thousand words: 

![playnite_bug](https://user-images.githubusercontent.com/42483196/61995106-b70c1880-b07b-11e9-9fda-095196cab5d0.jpg)

This is a screenshot of the full screen. You can see it's zoomed in and missing a lot of visual elements, the most important of which, the menu.

**Info**

I'm running at 4k resolution (3840x2160) on Windows 10. My systems display scaling setting is at 150%. 

**To Reproduce**

Set windows 10's display scaling to 150% (presumably happens at other scales too). If you change the scale to 100%, the bug goes away. This is an unacceptable workaround though, as it makes visual elements on the desktop too small to use.

I'm using the latest version of playnite that just released, v5.3 in a clean installation. I haven't used playnite before on this system.

Thank you

**Comment by JosefNemec** [comment]
This got broken thanks to 1903 Windows update. I will try to find some workaround.

**Comment by Revolt64** [comment]
> This got broken thanks to 1903 Windows update. I will try to find some workaround.

Excellent. Thank you

**Comment by JosefNemec** [comment]
Fixed in 5.4

**Comment by Revolt64** [comment]
I can confirm this fixed the issue. Thanks! @JosefNemec
