### ISSUE TITLE
Force application restart when changing library location

### ISSUE THREAD

**Issue by NULUSIOS** [JosefNemec/Playnite#1283]
(the description below, also is the process to possibly duplicate the issue)

OK so I tried 5.2 (now 5.3) on my gaming PC (no emulation software there), to use it just for the existing game libraries I use (Steam etc.).

I started from scratch and I used install (which I rarely do, I prefer portable installs).
That said, I installed it in a folder E:\Various\Playnite (not in Program Files). I have other software there working fine.
It seemed to work ok, saw my games (didn't check if they were all) and started to bring metadata.
I checked the settings, made a few tiny changes, but decided to use another path for the game library. So I changed it.
I didn't physically change anything (move folders).
I had to quit it later and then tried to import metadata again "only for missing". While it seemed to progress (counter) I didn't notice any real new metadata and felt something is wrong.
Today I noticed that "library" folder in AppData is big, while "library" folder where I put it in the settings is small (which is in a folder "library" within Playnite folder i.e. E:\Various\Playnite\library).
Also saw some other folders and files in AppData, that I didn't touch, although I would prefer they could be moved where I want them (for a more portable install). But this is another issue.
So I manually moved just the "library" folder.
Well this made things worse.
Now my game list has DOUBLE entries. One entry has metadata, one doesn't have.
(also there is no method to cleanup the database)
Even in library manager, platform, type, company, tag, source are mostly double! (some entries are not double not sure why)

So... what do I do now?

**Comment by JosefNemec** [comment]
Based on what you are describing you probably copied one library folder into another during the whole process, which is what causes the duplication. You can't do that since every time new library folder is generated, everything in database will have new IDs (everything is stored in files under new names).

Playnite doesn't move any library files when changing library location. It does two things after the change: If the target location is empty it creates new library (and populates it with items under new IDs). If the target location contains existing library files it just reuses those and doesn't generate anything.

Sadly I don't think there's a way how to de-duplicate your scenario.

We should probably add some message to make it clear what is happening when user decides to change the library location.

**Comment by tylerszabo** [comment]
I'd suggest to manually recover you could (first, make a backup) then remove all files with a "created" time after the move. That would eliminate the new files and hopefully leave the old ones.

**Comment by NULUSIOS** [comment]
The library is not that huge.
How can I delete all entries without deleting my settings?

I didn't "copy" anything. Initially I did no file move (just changed the setting), then when I discovered that things already did not work ok (I mean the old path was getting populated, not the new - this is already a bug), I moved from old location, just the library folder (which was a few MB), over the new one which was virtually empty (didn't exactly check what was in it, but the folder contents size was tiny, some Kb).
Then I got the double entries. There is no "library" in the original path. So there is just one database.

So, can I just delete the contents of the folder and let the database rebuild and get the metadata again? Or should I delete other files as well?

**Comment by JosefNemec** [comment]
Deleting contents of library folder is enough, you don't need to delete anything else. Application settings are store separately.

I still don't understand how this issue could have happened. Did you restart Playnite immidietely after the first database location change or did you kept using it and restarted later? I can there being possible issue if user doesn't restart immediately, I'll have to look into that.

**Comment by NULUSIOS** [comment]
I think I kept using it (actually not using it, just letting it run)... as I THINK (not sure any more) metadata were still downloading.
I think the system should prevent some possible user actions when some tasks are conflicting. OR schedule the actions for after the tasks.

Will delete library contents. Thanks.

**Comment by JosefNemec** [comment]
This was done in 5.7 by adding warning dialog about how the location change works.
