### ISSUE TITLE
Can't launch steam via Playnite

### ISSUE THREAD

**Issue by Quayyy** [JosefNemec/Playnite#1284]
Whenever I try to launch steam through Playnite, it gives me the "fatal error: failed to load steamui.dll" and nothing happens. This happens on any action that would launch steam, eg. starting an already installed game, installing a new game, or trying to open the steam friends panel.

But if steam is already running in the background, it works just fine.

Tried to delete the steamui.dll file, so steam would redownload it, but it didnt help.

**Comment by JosefNemec** [comment]
That's really weird, have you tried re-installation of Steam? This looks like some issue with Steam install to me. I don't think there's anything we can do about it from our side since we just open `steam://` url based on what game action is being invoked.

**Comment by Quayyy** [comment]
Thanks, reinstalling steam did the trick!

**Comment by therealmrbob** [comment]
I have the same issue.
I can open steam just fine using steam://
But it does not work in playnite.
Reinstalling didn't make a difference.

I also thought it may have been related to beta so I installed prod steam and still have the same issue.

**Comment by JosefNemec** [comment]
You need to uninstall and then do a clean install of Steam. Not just reinstall over existing installation.

**Comment by therealmrbob** [comment]
Interesting, I didn't do a full uninstall but after 6.2 I no longer have this issue.
