### ISSUE TITLE
Option to automatically download metadata for multiple games

### ISSUE THREAD

**Issue by XenSide** [JosefNemec/Playnite#129]
It would be very helpful to have an option to just automatically parse info from one of those two sources for every game without having to go one by one (mainly for custom imported games since you get metadata from the stores from games that come from them)

**Comment by jsphonorio** [comment]
I second this, everything else has been great for me so far and this is the only thing  from my library being good to go right off the bat

**Comment by JosefNemec** [comment]
Released in 3.0

**Comment by JosefNemec** [comment]
Main menu -> Library -> Download metadata
