### ISSUE TITLE
Desktop mode: Modifying a game Sorting Name and deleting it later, doesn't return the game to the previous position until restart.

### ISSUE THREAD

**Issue by darklinkpower** [JosefNemec/Playnite#1292]
In this case, I modified the game sorting name and it lists as expected, but when I deleted the sorting name, it doesn't return to where it was previously. Restarting Playnite lists the game where it should be again.

![2019-07-27_17-41-28](https://user-images.githubusercontent.com/1389286/62000181-4faf9200-b096-11e9-8a15-ebc329e04938.gif)

**Comment by JosefNemec** [comment]
Fixed in 5.4
