### ISSUE TITLE
Add option to show amount of items in a group

### ISSUE THREAD

**Issue by HoLLy-HaCKeR** [JosefNemec/Playnite#1293]
When grouping games (by eg. categories), it would be very convenient if it showed the amount of games in that category, especially when collapsed. Preferably, this would be a toggle in the settings, since many people may not want this behavior.

Example:
In the following screenshot, the category names (such as "Arcade", "FPS") would be appended with the amount of games in the category, making "Arcade (12)" and "FPS (29)".
![group example](https://i.imgur.com/bmxbekq.png)

**Comment by ClearStrelok** [comment]
The _show item count on group descriptions_ option already does that :

![Sans titre-4](https://user-images.githubusercontent.com/38838369/62000589-747a2880-b0db-11e9-8c04-f9da32de26f6.jpg)

**Comment by JosefNemec** [comment]
Closing, see ClearStrelok's comment.

**Comment by HoLLy-HaCKeR** [comment]
Not sure how I missed that, my bad.
