### ISSUE TITLE
Feature request: remember the size and position the 'Assign category' window

### ISSUE THREAD

**Issue by bettafo** [JosefNemec/Playnite#1294]
It would be nice if the size and position the 'Assign category' window (opened by right-clicking a game and choosing 'Set Category...') could be remembered by Playnite. With about 20 categories, I find myself spending more time having to resize or to scroll the window up and down each time I assign categories to games than actually selecting the relevant categories for the games.

Thank you for your great work!
Cheers

**Comment by JosefNemec** [comment]
Fixed in 5.4
