### ISSUE TITLE
Import Categories Steam Still Broken

### ISSUE THREAD

**Issue by xchaolingx** [JosefNemec/Playnite#1295]
It Add Games Not Existing In My Custom Category
I never play some of these games (print), I checked.They don't exist in my library and some aren't even in the store (eg Tiger Knight empire war)
It is shuffling games from other categories, games from category 1 are also being imported to category 2 for example.
![EAf0XGvWwAAzKfm](https://user-images.githubusercontent.com/53383844/62000390-33b6eb00-b0ac-11e9-9402-15cefa0779f5.jpg)

**Comment by darklinkpower** [comment]
My guess is you have them grouped by library, not by category, Try changing it. 
![imagen](https://user-images.githubusercontent.com/1389286/62003266-24e72d00-b0da-11e9-9d11-030c3b0a7a27.png)

**Comment by xchaolingx** [comment]
same result is filtered by category only
![image](https://user-images.githubusercontent.com/53383844/62009019-52f75c00-b130-11e9-93e5-8c09a4f889d2.png)

**Comment by JosefNemec** [comment]
I don't think there's anything we can do about this. We use Steam's API to fetch list of your games and if that API says that they are in your library then I don't think we can do anything about it. For now you have to hide them (from right-click game menu), proper support for ignore list [is coming in future](https://github.com/JosefNemec/Playnite/issues/565).

Just to make sure, if you use [SteamDB's calculator](https://steamdb.info/calculator/) do you see those game there as well (they use the same API AFAIK)?

**Comment by xchaolingx** [comment]
I my SteamDB's calculator  show this!
![image](https://user-images.githubusercontent.com/53383844/62329444-45253c00-b48c-11e9-8597-ec503f6cb119.png)
really!
Total Bug this API, this game (Tiger Knight: Empire War) I never play, never buy, it never be free.
And yet appear in my library when using API

**Comment by xchaolingx** [comment]
But if it helps,
Import Categories Steam hits 97% accuracy

**Comment by JosefNemec** [comment]
I'm going to close this then. I don't know why Steam API reports it, but I can do nothing about it. For now you can hide it in your library (via right-click game menu).
