### ISSUE TITLE
Multiple import issues with some GOG games

### ISSUE THREAD

**Issue by ClearStrelok** [JosefNemec/Playnite#1296]
A lot of games currently have troubles importing metadatas from GOG. Some games can still import most datas (but only on fields that have been emptied) while others cannot import anything outside of links and medias.

Do note that my library has been converted from previous versions of Playnite. I'll try importing my entire GOG library on a fresh portable installation to see if this is what's causing the issue.

**Comment by JosefNemec** [comment]
Can you give examples of games you are having issues with? Also are we talking about manual metadata update while editing game or mass download via "Download metadata..." menu? The fact that it works for fields that are empty would suggest the latter in case you didn't disable "Only download metadata for games missing them" option (which would be correct behavior).

**Comment by ClearStrelok** [comment]
About half of my GOG library is still able to import most or all informations properly using the mass metadatas query. The only issue for these is that the download metadata button now only replace fields that I usually left empty (whereas it previously replaced everything, unless I'm mistaken).

The other group of game, however, is completely broken. Few or no metadatas at all can be downloaded regardless of the query method and the backgrounds are randomly replaced with outdated versions on Playnite's startup. Store links are also broken.

Affected games include : The Witcher 3, Hellblade, Arma 2 (delisted), Assault on Dark Athena (delisted) and every Bethesda/Id software games.

**Comment by JosefNemec** [comment]
> backgrounds are randomly replaced with outdated versions on Playnite's startup

I can't see how that's possible, Playnite doesn't download or change metadata on startup if the game was already imported.

**Comment by ClearStrelok** [comment]
That surprised me as well. I thought it was simply an issue with my cache folder or something else on my end, but I've manually changed Quake/Quake 3 to their current store background since making this issue : 

https://images.gog.com/7a2aae78299a8202e892122664582c22c633c0af75e581d083fdd48a68cefca9_bg_crop_1920x655.jpg

Only to see them having been rolled back with the outdated versions when launching Playnite today : 

http://images-1.gog.com/0d02a21fe7d67f970501d2869d67c6024a14ad01700cac145696f0c7b4f76ce4.jpg

I'm probably mistaken on those having been changed on startup, but I didn't do any metadata query prior to seeing that a dozen of my GOG games backgrounds had been replaced, so I'll have to find out how this happened. If you can't reproduce these import issues I'll probably roll back to my pre-5.0 library on a fresh install.

**Comment by ClearStrelok** [comment]
> It looks to me like something went wrong on my end at some point.

Scratch that. I've imported my library anew on a portable installation of Playnite 5.4 and the same games are affected by the same issues. I don't think the app has anything to do with this either, as no library other than GOG is plagued by those issues. 

The backgrounds issue, however, appears to have been mostly a cache issue. I can't figure out why some of them have been replaced twice, but that's probably on my end. 

As a reminder, I already reported a much smaller issue with GOG import a month ago, (#1184) although I'm not sure this is related.

**Comment by JosefNemec** [comment]
> games are affected by the same issues

What do you mean specifically by "the same issue"? If you mean that some games have old style background then that's a GOG thing. They didn't update every game, mostly unlisted ones or games with newer editions available. For example Witcher 3 has old style background, but GOTY edition has updated one. The same goes for old Fallout games, Classic editions don't have updated backgrounds or covers.

**Comment by ClearStrelok** [comment]
I'm talking about the following issues : 

- Limited or no metadatas available at all 
- Broken Store link 
- Links import issue mentionned in #1184

IGDB will be able to pick up when games are recognized by name, but others won't be imported correctly. The first two issues also didn't happen when I first imported most of these games (some of them quite recently).

The issue with the backgrounds was that they were being replaced with their older version even though I had already changed them manually, but I think this simply was an unidentified cache issue on my end so you can ignore that.

**Comment by ClearStrelok** [comment]
I'm closing the issue for now. There's a couple of other games acting up in various ways when importing metadatas, but it all seems to be due to the store informations being messed up with and breaking things on our end. (either when importing the game for the first time or trying to update it) Much like with the backgrounds not being updated, I don't think you can do anything about it.
