### ISSUE TITLE
Crash when clicking empty link

### ISSUE THREAD

**Issue by artur-ag** [JosefNemec/Playnite#1298]
**Check for existing issue**
Similar to https://github.com/JosefNemec/Playnite/issues/468, but not the same, it seems.

**Describe the bug**
Unrecoverable error when clicking in a link of a game, if the link's URL is empty. The link already came empty from importing the game metadata from IGDB.

**To Reproduce**
* Add game with empty link from IGDB (e.g. Dead or Alive Paradise (PSP)
* Click the link
* Playnite will crash

Note that, if you manually create a link and leave the URL empty, Playnite will _not_ crash when you try to open the link. It has to be imported from IGDB.

**Screenshots**
![image](https://user-images.githubusercontent.com/9512554/62002706-01a59780-b145-11e9-8ebe-5e159b429b22.png)

**Diagnostics ID**
c3274a46-bb57-44f8-aa49-ecef6f91b4d8

**Comment by JosefNemec** [comment]
Fixed in 5.4
