### ISSUE TITLE
AutoClose in Fullscreen mode

### ISSUE THREAD

**Issue by ZerotakerZX** [JosefNemec/Playnite#1299]
After update to V5 one of the features and found handy was gone.

It is to CLOSE app after game is launched. It still works on desktop mode, but not fullscreen mode. I remember same issue was a thing long ago, then was fixed, but it's here again.

Currently in fullscreen mode the app only gets minimized (and opens again after I'm done with the game). It's a very minor gripe in a great app, just want to see it resolved. Cheers!

**Comment by JosefNemec** [comment]
Fixed in 5.4
