### ISSUE TITLE
[Request] Scrollbar Removal

### ISSUE THREAD

**Issue by VeganHentai** [JosefNemec/Playnite#130]
Would it be possible to add an option in the settings to remove or hide the scroll bars?

**Comment by JosefNemec** [comment]
What scrollbars are you talking about? Can you make a screenshot?

**Comment by VeganHentai** [comment]
The scrollbars on the right of the game information.

![abxzae](https://user-images.githubusercontent.com/25962087/31315018-8e4ce55a-abdc-11e7-98c7-13c9d6b44316.png)

**Comment by JosefNemec** [comment]
Well the text would not fit otherwise, I'm not sure what to do about it if I remove scrollbar.

**Comment by VeganHentai** [comment]
I was just wondering. Like being able to scroll, but it be hidden. I didn't know if it's actually possible to do something like that. Thank you for taking the time though. Playnite is great.

**Comment by JosefNemec** [comment]
Well technically it's not a problem to hide it, I just don't think it would be very user friendly since scrollbars usually indicate that there's more content out of screen. However in 3.0 you will be able to completely customize the skin and you will be able to remove it by editing the skin.

**Comment by VeganHentai** [comment]
Awesome. Thanks for the information.

**Comment by JosefNemec** [comment]
I'm going to close this, since it will be dependent on selected theme after 3.0 releases.

**Comment by sickalot** [comment]
I know, this is an old topic. But I cannot figure out how to hide the scrollbar.
I cannot find anything in the settings. Was this implemented?

**Comment by JosefNemec** [comment]
You need to make custom theme.

**Comment by sickalot** [comment]
You mean a theme from scratch?
