### ISSUE TITLE
Hide unassigned items in the Explorer/Filter panels

### ISSUE THREAD

**Issue by ivanmestre** [JosefNemec/Playnite#1301]
**Check for existing issue**
No issue found

**Describe the solution you'd like**
Hide empty filters in the Explorer Panel. Example, on the platforms view, only show the platforms that contain games. If I imported PC games and SNES games, only show PC and SNES in the platforms. Same with the other filters like Categories, Genres, etc.

**Screenshots**
I've only imported PC games, yet all the platforms are showing

![image](https://user-images.githubusercontent.com/6786286/62008324-ea5ab000-b12c-11e9-9c38-883830364130.png)

**Comment by JosiasElias** [comment]
also on fullscreen please!
oh, today I want to play some ps1 game and..oh my god do I have to scroll down on this?I only have like 5 consoles

![Screenshot (26)](https://user-images.githubusercontent.com/28114069/62254589-1ea1cb00-b3d0-11e9-8e80-8f30ad300095.png)

**Comment by JosefNemec** [comment]
Done in `devel8.

**Comment by RagnarokAeon** [comment]
Oof, my bad. I didn't see this when I was looking. Messing around with the program a little more, I serendipitously found the options to remove the extra platforms under the Manage Library option. If anything, the help / manual could probably be updated to include the Manage Library option.
