### ISSUE TITLE
Shortcut icon missing after upgrade

### ISSUE THREAD

**Issue by as232** [JosefNemec/Playnite#1302]
**Check for existing issue**
Please use issue search in the repository if the bug is something really obvious there's a high change it was already reported.

**Describe the bug**
After upgrading from 5.2 to 5.3, the application shortcut icon is missing. The EXE icon in the program directory appears to be there, but within the Start menu the icon is a blank piece of paper icon (Windows10 v1803)

**To Reproduce**
Upgrade

**Comment by JosefNemec** [comment]
Main application executable changed, see [changelog](https://github.com/JosefNemec/Playnite/wiki/Playnite-5-changelog) for more details. You need to create new shortcut.

**Comment by as232** [comment]
I did create the new shortcut, but it only had the default Windows icon. I work in IT so I know how to manually change the icon, but u thought you'd want to know that other people may be experiencing this too.

BTW a big THANK YOU for developing Playnite, it is an awesome application!
