### ISSUE TITLE
Full screen mode offset horizontally

### ISSUE THREAD

**Issue by maxwellainatchi** [JosefNemec/Playnite#1303]
**Check for existing issue**
Please use issue search in the repository if the bug is something really obvious there's a high change it was already reported.

**Describe the bug**
The full screen mode is offset by a large vertical white bar that makes a large portion of the screen unusable (since the 5.0 update)

**To Reproduce**
Launch in full screen mode

**Screenshots**
![image](https://user-images.githubusercontent.com/4398327/62010148-e92d8100-b134-11e9-97fd-c7289edad57f.png)

**Diagnostics ID**
If this is a crash report please include string ID you receive after using "Create diag. package` on crash dialog.

**Comment by JosefNemec** [comment]
Same issue as #1282
