### ISSUE TITLE
Playnite Theme Settings

### ISSUE THREAD

**Issue by ArtexJay** [JosefNemec/Playnite#1304]
Would it be at all possible to have Playnite switch themes from Dark to Light (I know there isn't a light theme atm) depending on the system's theme? 

If this is achievable then Playnite could also change it's monochrome icon depending on system's theme so if users are using white theme in windows, Playnite would use the black monochrome icon, and vice versa.

If the above is achieved then we could try to separate the color highlighting to be a separate option in the settings. So the user would select if they want dark/light them then select if they want blue, red, green etc highlighting.

And then as another separate option can have a drop down or something to select a custom theme to override the default theme. And it could be optional for the custom themes to also have a light/dark theme as well.

**Comment by JosefNemec** [comment]
Is this really useful? How often do you change the Windows theme? Plus any change depending on Windows theme would require Playnite restart, which is not very user friendly.

**Comment by ArtexJay** [comment]
I personally have it set with a 3rd party app that changes the Windows theme from light to dark theme depending on the time of the day by extension all of my apps/browsers change as well.  So that i can actually see what im doing on my screen during the day and save my eyes in way from the bright white glare at night. 

I personally think it would be useful for people who have dimmer screens when in sunny areas as it dark mode makes it near impossible to be seen. Also if people like monochrome icons and alternate between dark and white theme, it would also be nice if the monochrome icon would adjust automatically without user intervention.

Dark Themes are great when in darker rooms or time of the day. White themes are great when it's bright and sunny. That my opinion though.

I do agree that Playnite needing to restart to change themes isn't really user friendly. One way would be to have Playnite or a seperate part of  Playnite simply monitor the setting of Windows in the background and swap out the theme when Playnite itself is in the background (closed to taskbar) or when its opened again after being closed normally.

**Comment by JosefNemec** [comment]
I'm closing this. There's no way we can make this work in some user friendly way because theme change requires Playnite restart.

I could technically make it so we reload the theme without process restart (it is WPF's supported feature), but themes can affect a lot of things (not just visual stuff), so it's way safer to require restart.
