### ISSUE TITLE
Unrecoverable Error when adding games manually

### ISSUE THREAD

**Issue by CMDRLucienn** [JosefNemec/Playnite#1308]
When manually adding a game, Playnite 5.3 crashes.

I've been able to reproduce this repeatedly; simply adding any game and downloading Metadata, then once Save is clicked, PlayNite crashes. Game is still successfully added.

Database was upgraded from latest 4.X release prior to 5.0 release.

Possibly related to Issue #522 ?

Diagnostics ID: 650c636c-249b-446d-85bf-9450268a72fe

**Comment by JosefNemec** [comment]
Fixed in 5.4
