### ISSUE TITLE
Feature request: random sorting order

### ISSUE THREAD

**Issue by MemeTroubadour** [JosefNemec/Playnite#1309]
There's already an issue for a random game button, but I was thinking a random sorting order might be a good alternative. More random games per screen, your library would look different for every boot and might be easier to fit the feature in since there wouldn't be a need for an all-new UI element.

**Comment by JosefNemec** [comment]
This would require complete rework of how we do sorting right now, which is IMHO not worth it.

**Comment by poisonborz** [comment]
Please consider doing this. It would enhance the browsing experience big time - in a lot of cases (eg. a large  collection of games, party games) a user just wants to play something new, where random ordering would help a lot. Having different games pop up is nice for looks and would make discoverability of games better.

**Comment by mjd4219** [comment]
Appreciate this would take a lot of work but I think this would be a really great feature. It would keep the library fresh seeing new content on each boot and integrate more nicely with fullscreen themes when browsing. Thanks for the awesome app & all your work :)

**Comment by mjd4219** [comment]
I wrote a small add-on that assigns random numbers as Tags or Categories to allow lists to be sorted in a random order. It is only a workaround but seems to work for my usecase. [RandomSorting](https://github.com/mjd4219/RandomSorting_playnite/releases/download/1.2/RandomSorting_a6af1255-7acc-4b6d-99f1-661065beb1b9_1_2.pext)
