### ISSUE TITLE
Playnite starting on the wrong monitor

### ISSUE THREAD

**Issue by DidyZ** [JosefNemec/Playnite#1311]
Hi,

I have two monitors and I use Playnite on the left one.
When I start the app, it always starts on the main monitor not the one it was previously on (the left one). It does this every launch.

You can reproduce this bug by moving the app on any other secondary monitor and when you will restart the app it will always starts on the main monitor

(french here sorry for my english)

**Comment by develoqqer** [comment]
which monitor is your main monitor in windows

**Comment by DidyZ** [comment]
In Windows my main monitor is the "2" and I want playnite to stay on the "1". Also i'm using extend desktop mode for dual screen.

**Comment by TrueCP6** [comment]
This is not an issue with Playnite this is an issue with windows itself. Change this to an enhancement to add the feature to be able to set which monitor Playnite starts on.

**Comment by JosefNemec** [comment]
It is an issue in Playnite. Playnite won't open on proper location if saved location has negative coordinates, which are correct values in case the second monitor is located on the left side to the main one.

**Comment by Highlander1536** [comment]
Yea I have 3 Monitors, Middle one is my main screen and my right one is in Portrait and it will Fullscreen on the Portrait one sadly

**Comment by JosefNemec** [comment]
Fixed in 5.7

**Comment by Wibbbs** [comment]
This seems to be happening again. I have a portrait oriented second monitor on the left of my main monitor. I would like for playnite to open maximized there when windows starts up. I have it set to open with windows which works fine. But it always opens on my main monitor. Even when I have it maximized on my second monitor and I restart it when installing a plugin or changing themes, it moves over to my main monitor when it restarts.

Should I open a new issue?

**Comment by JosefNemec** [comment]
> Should I open a new issue?
Yes
