### ISSUE TITLE
[Details view] panel window opacity option

### ISSUE THREAD

**Issue by ClearStrelok** [JosefNemec/Playnite#1313]
The windows are currently transparent but they had a fixed opacity in the 5.0 beta : 

![Sans titre-2](https://user-images.githubusercontent.com/38838369/62065723-e6fc1d00-b22f-11e9-9612-25620ab2f44c.jpg)

While full transparency works just fine by default, (due to the background picture doubling/darkening functionally replacing the old opacity factor) it can lead to some visibility issues depending on the way you're setting up your theme : 

![Sans titre-5](https://user-images.githubusercontent.com/38838369/62066333-4e669c80-b231-11e9-9834-1c8ddc824390.jpg)

I think adding a "fixed window opacity/darkening" toggle would be useful for those that want to use a single fullscreen background picture (this could also be added as a third slider below _LOCSettingsShowBackgroundWindowImage_).

I personally use the default look, but being able to tweak the darkening of the fullscreen background pictures and the opacity of the windows separately would also be useful for my case.

**Comment by JosefNemec** [comment]
There's no way how to do it currently because of the way we implemented the blurring option. Sadly this is a result of need to support Windows 7 and 8. We are actually not changing the opacity of panels but the background image itself.

Once we drop Windows 7/8 support I can rework this to something where we can adjust the panels them self.

**Comment by bettafo** [comment]
OMG. Don't you ever drop win7 support :/ pleeeeeaaaaaase

**Comment by JosefNemec** [comment]
I've added option to change the darkening intensity in of the 5.x versions, can't remember which one. Closing
