### ISSUE TITLE
Attempting to log in on Battle.net freezes Playnite

### ISSUE THREAD

**Issue by ClearStrelok** [JosefNemec/Playnite#1314]
Could be related to #1075 ? 

As the title says, attempting to log in your credentials on Battle.net freezes Playnite, leaving no choice but to kill the process. This happened consistently on both a regular and portable installation.

**Diagnostics ID**
af5fefc3-7b7b-49a4-a239-5bd081ecbeca

**Comment by JosefNemec** [comment]
This is really weird, it did work for me yesterday :(

**Comment by JosefNemec** [comment]
Fixed in 5.5
