### ISSUE TITLE
Merge Existing Games

### ISSUE THREAD

**Issue by TheOneWayTruth** [JosefNemec/Playnite#1318]
Some Games i have twice, for example i have Subnautica on Steam and on Epic Games. 
![image](https://user-images.githubusercontent.com/12105754/62132550-8fb48600-b2dd-11e9-8297-a95c659f8569.png)
It should be merged into one. with like 2 play buttons -> Play on Steam, Play on Epic
something like that.

**Comment by JosefNemec** [comment]
Duplicate to #408
