### ISSUE TITLE
Missing Icons on Twitch Games

### ISSUE THREAD

**Issue by TheOneWayTruth** [JosefNemec/Playnite#1319]
![image](https://user-images.githubusercontent.com/12105754/62132845-22552500-b2de-11e9-83f3-407c80ba32e9.png)

Missing Icons on Twitch Games

**Comment by JosefNemec** [comment]
We only pull icons for installed Twitch games, there's no way how to get icons for uninstalled ones.

https://github.com/JosefNemec/Playnite/wiki/Feature-table-based-on-library-provider
