### ISSUE TITLE
Add support for Epic Games Launcher?

### ISSUE THREAD

**Issue by SoupOrJuice** [JosefNemec/Playnite#132]
No clue how feasible this is, but Epic Games' launcher supports a few titles now so it'd be worth looking at at least. At least to automatically import installed games, as they're a pain to find the Binaries for. (Only have that idea because you mentioned it might be possible for Blizzard's Battle.net - which I'd also look forward to.)

**Comment by nichols-356** [comment]
+1 for Epic Games launcher support.

I did a little bit of poking around, and I did find some kind of API for the Epic Games Launcher, but I have no idea what the underlying structure is.

https://launcher-public-service-prod06.ol.epicgames.com/launcher/

You can see this URL is pointing to an API, but it is returning "not found" error. Not sure if there some some documentation on this API somewhere.

**Comment by JosefNemec** [comment]
Added in #845
