### ISSUE TITLE
ScummVM importer script - 'GetEmulators' method fails

### ISSUE THREAD

**Issue by Zebrazilla** [JosefNemec/Playnite#1320]
Can not get the ScummVM import script to work. Using the latest version (https://github.com/JosefNemec/Playnite/tree/master/scripts/Extensions/ScummVMImporter) the following issue appears:

> Failed to execute extensions function.
>
> Method invocation failed because [Playnite.API.DatabaseAPI] does not contain method named 'GetEmulators'.

**Comment by JosefNemec** [comment]
Fixed
