### ISSUE TITLE
Custom Quick Filters

### ISSUE THREAD

**Issue by pulse4J** [JosefNemec/Playnite#1321]
It would be great if you could select custom filters in the upper right.  There are already quick filters for "Installed" "Uninstalled" "Hidden" and "Favorite"....  Why not be able to put custom filters... like "VR Supported", from Category field underneath?

Clicking on the checkbox for that quick filter would be the same as selecting that tag in the drop down menu.  There's good reason for this feature as some of the tags are difficult to navigate.

**Comment by pulse4J** [comment]
I'm going to try and get this working... I'll let you know. :)

**Comment by JosefNemec** [comment]
This is IMHO duplicate to #590

**Comment by pulse4J** [comment]
Gotcha, didn't see that one.  I'll close this issue.
