### ISSUE TITLE
Playnite doesn't detect that an emulated game was closed.

### ISSUE THREAD

**Issue by PhonixeOreo** [JosefNemec/Playnite#1322]
This problem happens sometimes with cemu and dolphin, but always happens with Citra.
After I close the emulator, I don't get brought back to Playnite automatically. And when I open it manually I find that the game is set to "Running".
I added these games with the Add Game > Emulated Game option.

**Comment by JosefNemec** [comment]
Duplicate to #1089, also opened by you :)
