### ISSUE TITLE
Better mouse and keyboard support for Fullscreen Mode

### ISSUE THREAD

**Issue by notNSANE** [JosefNemec/Playnite#1323]
**Describe the bug**
You can select stuff with the mouse but can't go back since there isn't a back button or a way to go back.

**To Reproduce**
Click on settings or a game.

**Note**
I simply suggest mapping the "Esc" keyboard functionality with the Right Click, if the Right Click isn't used anywhere else on Fullscreen Mode.

**Comment by JosefNemec** [comment]
I changed the title because we need to generally overhaul navigation with mouse and keyboard in Fullscreen mode.

**Comment by JosefNemec** [comment]
Will be done via #1344
