### ISSUE TITLE
Playnite renderer is incompatible with Steam's Big Picture Mode (BPM) Overlay

### ISSUE THREAD

**Issue by notNSANE** [JosefNemec/Playnite#1324]
**Describe the bug**
While the core support of Playnite works (you can use a controller via Steam Input), the Overlay doesn't play nice at all on top of Playnite. It completely freezes the screen (the Steam Overlay can be heard if you use the left stick or the buttons).

**To Reproduce**
1. Add Playnite.FullscreenApp.exe as a Non-Steam Shortcut in Steam
2. Start it
3. Press the "Guide" button on your controller to call the Steam Overlay

**Note**
You can regain back control of the UI if you alt tab, then focus Playnite again.

**Comment by JosefNemec** [comment]
This is not supported scenario. The whole point of Playnite is to start Steam games though it, not the other way around. Also there's nothing I can do about this. Playnite is not a game, you can't expect game related features like overlay to work on it.

Also if Steam fails to attach overlay process to Playnite properly then it's a Steam issue, not Playnite one. We don't have any protection in place to prevent other processes injecting stuff into Playnite.
