### ISSUE TITLE
Untranslated fields in 5.5

### ISSUE THREAD

**Issue by ClearStrelok** [JosefNemec/Playnite#1325]
The following fields are currently left untranslated : 

_Details view_
_Grid view_
_List view_

_Width_
_Details game list position_
_Draw background_

This also concerns other strings not yet in use that have been recently added to Crowdin but aren't in the translation files.

**Comment by JosefNemec** [comment]
I can see then on Crowdin, you even translated them :)

**Comment by ClearStrelok** [comment]
I've looked further and only _LOCSettingsGridItemDrawBackground_ along with _LOCSettingsDetailsGameListPosition_ seem to be missing from the translation files. The other strings are actually acounted for are just currently empty, like so : 

    <sys:String x:Key="LOCListViewLabel"></sys:String>
    <sys:String x:Key="LOCGridViewLabel"></sys:String>
    <sys:String x:Key="LOCDetailsViewLabel"></sys:String>

    <sys:String x:Key="LOCWidth"></sys:String>
    <sys:String x:Key="LOCHeight"></sys:String>
    <sys:String x:Key="LOCSize"></sys:String>

    <sys:String x:Key="LOCGeneralExtensionInstallTitle"></sys:String>

Other translations files are also affected by this to a lesser degree. This is weird, because these strings have actually been commited before both 5.4 and 5.5 went online : https://github.com/JosefNemec/Playnite/pull/1310/commits/e62910a04b808ed0aeda591c99c0e540ba315bbc

**Comment by JosefNemec** [comment]
That's because I didn't push updates from crowdin to github yet https://github.com/JosefNemec/Playnite/pull/1310
