### ISSUE TITLE
Switch to other instance as early as possible

### ISSUE THREAD

**Issue by tylerszabo** [JosefNemec/Playnite#1326]
In the case where Playnite is already running and minimized to tray and is launched it will take a few seconds and a display of the splash screen before the original instance is brought to front and the new instance terminates.

I mostly notice this when pinned to taskbar and minimized to tray (rather than just minimized).

Related to #1285.

**Comment by JosefNemec** [comment]
We no longer show splashscreen when switching to already running instance as of 5.8.
