### ISSUE TITLE
Scrollbar in details view causes horizontal shift of information

### ISSUE THREAD

**Issue by sjdawson** [JosefNemec/Playnite#1327]
When clicking through games in your list in "Details view", depending on the length of the content, the main window's scrollbar will hide when it's short enough. This causes the main content to shift horizontally left and right.

![vTyYERZE0b](https://user-images.githubusercontent.com/1701603/62225784-08384700-b3b1-11e9-985e-bffac89c6b01.gif)

**Comment by JosefNemec** [comment]
Fixed in 5.7
