### ISSUE TITLE
Custom Uninstall Action for manually installed games.

### ISSUE THREAD

**Issue by Dread-Pony** [JosefNemec/Playnite#1328]
I am hoping for this so the manually installed games can fit more seamlessly with the automatically installed games. It is already possible to add an Uninstall Action, but it gets put right below the Play Action like all other actions. This can cause someone to accidentally uninstall the game when they were actually wanting to play it. I was originally thinking of this for games with an uninstall.exe, but it might also help to add the option to delete specific files (mainly for roms) or to delete a folder (for portable games that don't include an uninstall.exe.

**Comment by JosefNemec** [comment]
Extensions can now provide custom uninstall actions but somebody needs to make one which supports games without launchers. I'm not planning to support this via some built-in feature because there's too many ways games can implement uninstall feature.
