### ISSUE TITLE
[5.5] Scripting issues

### ISSUE THREAD

**Issue by Belgabor** [JosefNemec/Playnite#1329]
After the much appreciated release of 5.X I'm trying to update the python script I wrote to manage categories. So far I've come across two issues that weren't there (or could be worked around) in 4.x

1. Reload Scripts doesn't work. The log claims the scripts are reloaded, but factually they are not.
2. I am now unable to add a Category to a Game that has none since in that case Game.Categories is of NoneType and read only. In the old version it wan't read only, so I could assign an empty List object to it, but that no longer works.

1 is more of a small annoyance, but since my script is all about handling categories and sorting in freshly added games 2 is a major deal breaker.

**Comment by JosefNemec** [comment]
You need to add a category to database's `Categories` collection and then assigns category ids into game's `CategoryIds` field.

I'll look into that reload issue.

**Comment by Belgabor** [comment]
Ahh! Got it working that way, thanks.
