### ISSUE TITLE
Failed to Import Origin Games

### ISSUE THREAD

**Issue by virginsofcool** [JosefNemec/Playnite#133]
"Failed to import installed Origin games: The remote server returned an error: (404) Not Found."

I verified my account was authenticated and I also tried it with and without the separate Origin client open.

**Comment by JosefNemec** [comment]
Please go to main menu, "About Playnite..." and then click "Create diag. package" and upload created file. Thanks a lot.

**Comment by virginsofcool** [comment]
No problem!

[virginsofcool diag 10-8-17.zip](https://github.com/JosefNemec/Playnite/files/1366893/virginsofcool.diag.10-8-17.zip)

**Comment by JosefNemec** [comment]
Thanks, that really helped me to find where the problem is. You can use [this build](playnite.link/download/PlayniteInstallerOriginFix.exe) until patch gets out via standard update.

**Comment by virginsofcool** [comment]
It says "Not Found" when I click that link.  It's cool though if it's too much work, I can wait for the standard update.

**Comment by JosefNemec** [comment]
Was missing http :) here you go [http:/playnite.link/download/PlayniteInstallerOriginFix.exe](http:/playnite.link/download/PlayniteInstallerOriginFix.exe)

**Comment by virginsofcool** [comment]
Perfect, that did it.  All of my games were imported correctly now. :-)

**Comment by JosefNemec** [comment]
Released in 2.3
