### ISSUE TITLE
48 errors when building

### ISSUE THREAD

**Issue by NHurstNeumont** [JosefNemec/Playnite#1331]
**Describe the bug**
When building the solution in VS 2017 Enterprise, there are 48 build errors I can't seem to fix

**To Reproduce**
Clone Repo
Open \Playnite\source\Playnite.sln
Download missing Nuget Packages
Build Solution

[errors.txt](https://github.com/JosefNemec/Playnite/files/3459227/errors.txt)

**Comment by JosefNemec** [comment]
Can check if you are building under `x86` solution config, not `AnyCPU`?

**Comment by NHurstNeumont** [comment]
Some projects are set to do x86, others are set to anycpu
![image](https://user-images.githubusercontent.com/25715845/62383102-52820b00-b50c-11e9-9eef-0c9012ae68bd.png)

**Comment by JosefNemec** [comment]
I'm talking about active global solution config, you need to set it to `x86`:
![image](https://user-images.githubusercontent.com/3874087/62384596-145c0a00-b553-11e9-93a1-c5ebe8469379.png)

**Comment by NHurstNeumont** [comment]
Already set
![image](https://user-images.githubusercontent.com/25715845/62384809-a0007700-b510-11e9-9a2b-da2312400291.png)
Just wanted to make sure about the individual projects

**Comment by bugthug** [comment]
Same issue here, unable to compile the project

**Comment by JosefNemec** [comment]
I have no idea why it's not working with Enterprise edition and I can't reproduce it on any of my PCs.

**Comment by NHurstNeumont** [comment]
Well I'm working in a group and none of us could get it to build, but to just make sure we're not all doing it wrong

Clone the repo
Open the Playnite.csproj file in VS2017
Go to Nuget package manager
Download all of the missing packages
It should work (?)

**Comment by JosefNemec** [comment]
No that's not correct. You don't open `Playnite.csproj`, you need to open Playnite's solution `Playnite.sln`.

Also you are missing "Switch to x86 solution configuration". But other then that, yes, that's enough. As long as you have .NET 4.6.2 installed (which VS should ask for automatically). Also maybe try restarting VS after restoring nugets and then just explicitly build desktop or fullscreen project.

I really don't have a way to test it with Enterprise edition and I also can't think of reason why the VS edition would have an effect on project build. Also maybe check if you have some VS extension installed that affects building (mainly priorities), if that's not the issue.

**Comment by NHurstNeumont** [comment]
Huh... 
I meant sln, not csproj, but I reverted all my changes, opened the sln file, restored packages, triple checked I was on the right config, and then restarted VS and it built just fine, maybe it's just another weird VS bug, thanks for the help anyways
