### ISSUE TITLE
Client bugged after pressing 

### ISSUE THREAD

**Issue by bugthug** [JosefNemec/Playnite#1333]
**Check for existing issue**
I have not found the bug anywhere else

**Describe the bug**
When pressing on the developer/publisher link in at least one game, the client bugs out and only shows that game

**To Reproduce**
The game in question is Freddy Fazbears' Pizzeria Simulator. It's free so there shouldn't be a problem

**Screenshots**
![image](https://user-images.githubusercontent.com/48732230/62362208-2f178a00-b525-11e9-9a4a-acb8d87880a7.png)

**Comment by bugthug** [comment]
Nevermind I'm dumb, didn't understand how filters work

**Comment by JosefNemec** [comment]
Did the filter panel open after clicking on developer? It should have. If it didn't then it's a bug and I can see how that could be confusing.
