### ISSUE TITLE
Add sounds to Fullscreen mode

### ISSUE THREAD

**Issue by JosefNemec** [JosefNemec/Playnite#1335]
We should add sounds to Fullscreen mode to improve navigation feedback. Also possibly background music to make it less depressingly quiet.

**Comment by kllr007** [comment]
Yes I would love that.

**Comment by MaximusX800** [comment]
This would be a great feature addition, full customization allowed.

**Comment by slymeasy** [comment]
How do you vote for this? This is pretty much the only thing that Playnite is missing.

**Comment by JosefNemec** [comment]
Voting takes place on Patreon after each major version is released, the next one will be after Playnite 8 release.

**Comment by slymeasy** [comment]
Ok, thanks.

**Comment by SargeantWoods** [comment]
Yes this would be awesome, definetly the only thing that Playnite is missing.

**Comment by KultGrazer** [comment]
Sound-Effects - For me, the last missing piece to be the best gaming-hub out there!

**Comment by JosefNemec** [comment]
Done in devel9.
