### ISSUE TITLE
Playnite freezes and crashes after importing games or if hitting cancel during import

### ISSUE THREAD

**Issue by cristi1990an** [JosefNemec/Playnite#1337]
**Describe the bug**
Pretty much crashes no matter what. See videos.

https://youtu.be/W8bsk4t6zkk

https://youtu.be/rQy4ngYFc4M

**Comment by JosefNemec** [comment]
Can you send me your `%AppData%\Playnite` folder?

**Comment by JosefNemec** [comment]
Also, does it recover if you just wait a while without force killing it?

**Comment by cristi1990an** [comment]
Yes, it was the server issue you talked about on Discord. It works now
