### ISSUE TITLE
Controller Improvements

### ISSUE THREAD

**Issue by jessetandor** [JosefNemec/Playnite#1338]
**Check for existing issue**
A) Two clicks currently are required to leave big picture mode..
B) Cant use Controller to navigate in Desktop mode

**Describe the solution you'd like**
A) Button B or O on controllers isn't used in Big picture mode. Add functionality where pressing this button exits back to normal mode. Simple back button.
B) Enable controller in desktop mode. Pressing options on controller can bring up settings for example. So we're not so reliant on mouse/keyboard.

**Screenshots**
If applicable, add screenshots to help explain requested changes.

**Comment by JosefNemec** [comment]
A) I don't think that's a good idea because B is used to get back or cancel from other dialogs. Getting back to desktop by simply pressing B would be a bad UX.

B) I currently don't plan to add support for Desktop mode because it would be a nightmare to make it work properly.
