### ISSUE TITLE
Client crashes when attempting to grab exe file's icon

### ISSUE THREAD

**Issue by starpotion** [JosefNemec/Playnite#134]

**Comment by JosefNemec** [comment]
Please go to main menu, "About Playnite..." and then click "Create diag. package" and upload created file. Thanks a lot.

**Comment by starpotion** [comment]
No problem 
[Diag.zip](https://github.com/JosefNemec/Playnite/files/1367232/Diag.zip)

**Comment by JosefNemec** [comment]
Released in 2.4
