### ISSUE TITLE
Not detecting non Blizzard games installed with battle.net

### ISSUE THREAD

**Issue by snits** [JosefNemec/Playnite#1341]
**Describe the bug**
For games in the battle.net launcher that are not from blizzard it appears that perhaps they aren't detected as installed. I've seen this with Call of Duty: Black Ops 4 specifically, but I'm guessing the same will happen with Destiny 2, and Modern Warfare when it is finally released.

The game import does detect them as existing in the library though.

**To Reproduce**
1. Install Black Ops 4.
2. Update Game Library in playnite.
3. Check Black Ops 4 to see whether it shows as installed or not in playnite.

**Screenshots**

https://imgur.com/2HrtRkT

**Comment by JosefNemec** [comment]
Did you actually install Back Ops 4 or just imported existing installation into Battle.net? There's a known issue where some games might not be detected if you just import them, you will need to run repair installation in Battle.net client for Playnite to detect install state properly.

**Comment by snits** [comment]
It was previously installed with battle.net. I'm running the scan and repair to verify that clears it up. I will update here, and then you can close it.

**Comment by snits** [comment]
Verified that the scan & repair solved it. Closing the issue.
