### ISSUE TITLE
Ignore filters when searching

### ISSUE THREAD

**Issue by Rinma** [JosefNemec/Playnite#1342]
There should be an option to activate/deactivate the actual set filters when searching.

Means when I filter to see only my favorites and then search I want that the filter is ignored and the search is performed about my whole library of games.
Because I think some do like it how it actually is this should be an optional setting.

**Comment by JosefNemec** [comment]
I think this would be super confusing since we don't have separate view for filtered and "searched" games. It would not be immediately clear what are currently displayed games filtered/search by.

**Comment by Rinma** [comment]
That's why I suggest this to be optional like an option in the settings that says "Ignore filters when search []" that is off by default but could be activated.
 
I always only display my favorite games and when I search that is not in this filter I first have to open the filters, deactivate favorites, search and afterward I have to activate the filter for favorites again.

I understand your point and a search is nothing different than a filter on a specific name but I don't think that it would be more confusing like now when you search for a game and forgot that you have set a filter previously.

**Comment by rnd256** [comment]
I think https://github.com/JosefNemec/Playnite/issues/1413 achieves a similar goal in a better way.

**Comment by JosefNemec** [comment]
Will be done via #1413
