### ISSUE TITLE
Option to add description to crash dialog

### ISSUE THREAD

**Issue by JosefNemec** [JosefNemec/Playnite#1349]
Have text field to allow users to add simple description about what actions where taken before the crash occurred.

**Comment by T-0pel** [comment]
Is this being worked on? If not, I could take a look at it.

**Comment by JosefNemec** [comment]
I'm not working on it, feel free to look at it.

**Comment by T-0pel** [comment]
I am starting to look into this and I have a couple of questions to make sure we are on the same page: 

- the idea is to add a textbox to the crash dialog and then export this text as part of the diagnostics package?
- I assume this should not influence the create diagnostics package in the About window?

**Comment by JosefNemec** [comment]
Yes, exactly.

**Comment by JosefNemec** [comment]
Done in 6.1
