### ISSUE TITLE
Playnite crash

### ISSUE THREAD

**Issue by ListenToTheRain** [JosefNemec/Playnite#1350]
**Describe the bug**
Playnite crashed when I tried to download and then save metadata from official store (steam) for Sunrider Academy specifically.

**Screenshots**
![Безымянный](https://user-images.githubusercontent.com/53796634/62493950-ff91a780-b7da-11e9-98a2-08e7712f77fd.jpg)

**Diagnostics ID**
8ced1e28-10d7-40bb-91e1-fdd6a84b69a2

**Comment by JosefNemec** [comment]
What did you do before it crashed?

**Comment by ListenToTheRain** [comment]
Nothing, it multiply crashed when I tried to download and save metadata for this game even after reloading playnite right after previous crash.

**Comment by JosefNemec** [comment]
Fixed in 5.6

**Comment by JosefNemec** [comment]
Fixed in 5.7
