### ISSUE TITLE
Blizzard client freezes

### ISSUE THREAD

**Issue by xchaolingx** [JosefNemec/Playnite#1351]
Blizzard client freezes if opened with Playnite, open by itself does not freeze,only when games are open

**Comment by JosefNemec** [comment]
I can't reproduce it. Also I don't think this is caused by Playnite since we just start the executable, we don't do any additional interaction with Battle.net application.

**Comment by JosefNemec** [comment]
Closing since it can't be caused by Playnite, at least I don't see how it could be and I failed to reproduce it on any of my machiens. If you have exact steps how to reproduce it reliably, let me know.
