### ISSUE TITLE
Additional game actions are not available in Fullscreen mode

### ISSUE THREAD

**Issue by kristheb** [JosefNemec/Playnite#1353]
**Check for existing issue**
Please use issue search in the repository if your feature request is something really obvious there's a high change it was already requested.

**Describe the solution you'd like**

**Screenshots**
If applicable, add screenshots to help explain requested changes.

**Comment by kristheb** [comment]
when adding additional play actions, they are not visible or executable in fullscreen mode. they could be placed under options.

**Comment by CatEyedLink** [comment]
Yes, Please add this

**Comment by JosefNemec** [comment]
Fixed in 8.4
