### ISSUE TITLE
Backdrop image issue

### ISSUE THREAD

**Issue by RadicalGlitch** [JosefNemec/Playnite#1356]
There is a little shifting of background image when there is a long description about the game...

Basically when the right slider pops in, it moves the background image to the left... So when I am browsing my games (clicking them one after the other to watch beautiful backgrounds) there is a slight glitch effect that does not look good... 

Here is the video that i recorded : https://youtu.be/-4C228SODzc

Thank You.

**Comment by JosefNemec** [comment]
Duplicate to #1327
