### ISSUE TITLE
Connecting to itch.io account with 0 games gives error

### ISSUE THREAD

**Issue by grnassar** [JosefNemec/Playnite#1357]
I have an itch.io account, but I don't have any games in the account yet.

Expected behavior:
Linking empty itch.io account in Playnite syncs 0 games, gives no error.

Actual behavior:
Linking empty itch.io account in Playnite gives the following error on every sync process: "Failed to import games from itch.io. Object reference not set to an instance of an object."

**Comment by JosefNemec** [comment]
Can you go to "About Playnite" menu and create diag. package for me please? Thanks

**Comment by grnassar** [comment]
ID: 666a2212-8d49-4cad-a921-8662fd7181ec

**Comment by JosefNemec** [comment]
Duplicate to #1173
