### ISSUE TITLE
Add a "Default Game Background Image" option

### ISSUE THREAD

**Issue by DennoCoil** [JosefNemec/Playnite#1358]
In Settings -> Appearance -> Advanced
![2019-08-10 09_08_25-](https://user-images.githubusercontent.com/21137176/62822244-cc3e7800-bb4e-11e9-976e-b5f1ec708f4e.png)
There's options for Missing game icons and covers to have a potential default they can revert back to.  There's no option for potential default backgrounds that can be used, whether by a plugin, the library platform manager (which doesn't have an option for a default background either), or Playnite's currently selected color themes.
![2019-08-10 09_10_26-Library Manager](https://user-images.githubusercontent.com/21137176/62822252-e24c3880-bb4e-11e9-8dc8-56f2613f657d.png)

**Comment by darklinkpower** [comment]
I was about to suggest exactly this, glad to see I'm not the only one thinking this feature is needed.

**Comment by JosefNemec** [comment]
Done in 6.0
