### ISSUE TITLE
"Supported File types" Field auto-inserts spaces.

### ISSUE THREAD

**Issue by JosiasElias** [JosefNemec/Playnite#1360]
**Describe the bug**
Spaces are added all over the place in the "supported file types" field in "cunfigure emulators"

**To Reproduce**
Library>configure emulators>select emulator(retroarch)>profile(Dolphin)>Supported file types
tried typing the extensions, even just backspace(lol) and spaces are added like everywhere.
This also seems to mess with the scanning of games, it cant find any games like this

**Screenshots**
![Screenshot (34)](https://user-images.githubusercontent.com/28114069/62828315-8074e880-bbb9-11e9-9cbb-26dc622989ac.png)

**Comment by Stuntaneous** [comment]
And more importantly, all extensions other than the first are not picked up when adding a folder of emulated games.

**Comment by JosefNemec** [comment]
Fixed in 5.7
