### ISSUE TITLE
Drag categories on explore panel to games

### ISSUE THREAD

**Issue by MrJoeSchmo** [JosefNemec/Playnite#1367]
**Check for existing issue**
No similar issue created

**Describe the solution you'd like**
Dragging category names out from the Explorer Panel and dropping them onto a game should add that category to that game. It takes several clicks just to get to the field to add a category at the moment. If the Explorer Panel shouldn't be used in this way then I feel there should be someway to add categories more efficiently.

**Screenshots**
Dragging this "Party" category to Move Or Die could add it to the game.
![image](https://user-images.githubusercontent.com/17410781/62994205-b7046a80-be28-11e9-8fd1-6874edaf598d.png)

**Comment by JosefNemec** [comment]
Will be done via  #1894
