### ISSUE TITLE
Cannot see Origin Uninstalled Game in library

### ISSUE THREAD

**Issue by ScimmiaSpaziale** [JosefNemec/Playnite#1368]
**Describe the bug**
Even Tho I'm authenticated into Origin via Playnite, I cannot find in my library the only uninstalled game I own (Sims 4).
I already tried updating Origin library and all library and rebooting playnite.

**Screenshots**
![image](https://user-images.githubusercontent.com/15640234/63007257-9831c280-be80-11e9-9423-460f6b0eae64.png)
![image](https://user-images.githubusercontent.com/15640234/63007290-a7b10b80-be80-11e9-9920-c978fadfd2c0.png)

**Comment by JosefNemec** [comment]
Can you please go to `About Playnite` menu and create diag. package for me?

**Comment by ScimmiaSpaziale** [comment]
322a1468-0011-4b8c-8cd7-2979f2846b33

**Comment by JosefNemec** [comment]
I can see that Sims 4 was imported according to logs. You even started the game from Playnite at least once. I'm not sure what the issue is then. Can you clarify?

**Comment by ScimmiaSpaziale** [comment]
I used to play with it via playnite when it was installed.

The bug is that now that I've uninstalled it, it's not visible in the library even tho I chose to see uninstalled games from origin.

![image](https://user-images.githubusercontent.com/15640234/63157466-50916f00-c017-11e9-8c50-be6b029df1bf.png)

**Comment by ScimmiaSpaziale** [comment]
![image](https://user-images.githubusercontent.com/15640234/63157520-6acb4d00-c017-11e9-91d4-d6978c4273b7.png)

**Comment by JosefNemec** [comment]
That's weird. Can you upload `%appdata%\Playnite\library` folder for me please? Thanks

**Comment by ScimmiaSpaziale** [comment]
[library.zip](https://github.com/JosefNemec/Playnite/files/3509146/library.zip)

**Comment by JosefNemec** [comment]
Can you please try it with [this build](https://playnite.link/download/OriginDebug.exe)? After you reproduce the issue please create new diag. package for me, thank you.

**Comment by ScimmiaSpaziale** [comment]
Here it is: 98d2c3a5-2ad2-46da-afe8-10645eb1b7d6
(The game is yet not visible in this build)

**Comment by ScimmiaSpaziale** [comment]
Sorry, I forgot to respond:
I checked and actually log out and log in again in origin both via playnite and via origin browser (I think I already was, but)

**Comment by JosefNemec** [comment]
Can you please check if this is still an issue with latest 5.7 update?

**Comment by ScimmiaSpaziale** [comment]
Updated to 5,8 but still the issue remain
4f6fa6d2-96b4-44cc-9e4d-870e53c71435

**Comment by JosefNemec** [comment]
Is this still an issue in latest Playnite version? There was multiple updates to Origin integration since 5.8.

**Comment by JosefNemec** [comment]
Closing, no response.
