### ISSUE TITLE
Option to disable the Desctiption panel in the Covers view mode.

### ISSUE THREAD

**Issue by outlawzgosu** [JosefNemec/Playnite#137]
The information in the description panel is the game description, genre, ect. This information may be useful once or twice, but seeing it popup every time is kind of annoying. When you click in a gray area on the game's list, the description box disappears, rearranging the game order. Then when you click on a game , it appears again, rearranging the games again.

**Comment by JosefNemec** [comment]
You will be able to remove it in 3.0. For now you can double-click on game and it will start it without opening the panel.

**Comment by evgdovg1996** [comment]
@JosefNemec I please you to add an reverse option where the description will always be opened(user can't close it) and it opened when the program starts, with the position that user was selected in last time.
It's very useful for those,who like full description of games

**Comment by JosefNemec** [comment]
Added in Playnite 4.
