### ISSUE TITLE
Minor suggestions to the theme (Align elements)

### ISSUE THREAD

**Issue by darklinkpower** [JosefNemec/Playnite#1374]
Currently the different elements in the details view don't align. Making them align would give a cleaner, more organized and better look.

The main things I notice is on the left side, where the play button and icon don't align with the details. Maybe it was thought as an indent but in my opinion it would be better having them aligned.

On the right side, the cover and horizontal separation line don't align with the description content.

In the middle all the elements are aligned differently but the main thing is the "Description" label and it's content. In this case, it's inconsistent with what is happening on the details and it's content, where it's correctly aligned vertically.

I attach an image showing what I'm describing and with a color on the lines I think should be aligned.
**Screenshots**

![JPEGView_2019-08-15_14-19-30_proc](https://user-images.githubusercontent.com/1389286/63120392-d7870e80-bf67-11e9-8a10-2d0f1f29b645.jpg)

**Comment by JosefNemec** [comment]
Fixed in 5.7
