### ISSUE TITLE
Twitch background image pulling wrong image

### ISSUE THREAD

**Issue by sjdawson** [JosefNemec/Playnite#1376]
**Describe the bug**
When importing games from Twitch, the background image that's applied is one from "Getting Over It with Bennet Foddy", even when that's not the game in question. It picks up this URL:

https://images-na.ssl-images-amazon.com/images/I/A1VAra5JJvL.jpg

**To Reproduce**
Import games from Twitch. Notably this has happened with:
* Cultist Simulator
* For the King
* Hyper Light Drifter
* Joggernauts
* Keep in Mind
* Mable and the Wood
* Majesty 2 Collection
* Majesty Gold HD
* Pikuniku
* Pumped BMX Pro
* Republique
* Snake Pass
* Star Vikings Forever
* The King's Bird
* Yooka-Laylee

**Comment by Danyelalejandro** [comment]
I had the same issue as well but forgot to report it.

**Comment by JosefNemec** [comment]
I checked it and for some reason if the game publisher didn't set background they return Getting Over It background instead in their API. I'll add check for it and ignore it if it's set.

**Comment by JosefNemec** [comment]
Fixed in 5.7
