### ISSUE TITLE
Steamworks Common Redistributables listed as a game

### ISSUE THREAD

**Issue by droz36** [JosefNemec/Playnite#1377]
**Check for existing issue**
I did not see an open bug for this issue

**Describe the bug**
The "Steamworks Common Redistributables" are listed as a game with Steam games

**To Reproduce**
I have steam installed with PlayNite and it just appeared.

**Screenshots**

![2019-08-17](https://user-images.githubusercontent.com/17975920/63215219-8acf3f00-c0f1-11e9-8f78-06adece7df93.png)

**Comment by JosefNemec** [comment]
This was already fixed in 5.4 update. But if redist. was imported already from previous versions then you need to remove it manually. It shouldn't come back next time you update the library.

Also it's Playnite not PlayNite :)
