### ISSUE TITLE
Crash when switching from Fullscreen mode to Desktop mode

### ISSUE THREAD

**Issue by Kilroy5150** [JosefNemec/Playnite#1378]
It crashed when going to Desktop mode, that's all i know and that's what i'm reporting.

Sorry but i'm not going to school myself on this software (that i just started using) just to report a bug. Most serious software has it's own code built in and it's own report and you just push the button.

I think, perhaps, you should write and perfect the "bug report" first and foremost.

**Comment by JosefNemec** [comment]
Can you make a screenshot of the crash and also upload `%appdata%\Playnite\playnite.log` file? We do have automated reporting implemented, but if you didn't see it then the app crashed due to something outside of our control.

**Comment by Kilroy5150** [comment]
[playnite.log](https://github.com/JosefNemec/Playnite/files/3512403/playnite.log)


There you go...but it, literally, happens every time i switch to desktop mode.

**Comment by JosefNemec** [comment]
Can you try to rename Playnite's folder from `V:\! Playnite !\` to just `V:\Playnite\` to see if it fixes the issue?

**Comment by JosefNemec** [comment]
Fixed in 5.7
