### ISSUE TITLE
Not calculating game time if game runs in compatibility mode

### ISSUE THREAD

**Issue by Bobsans** [JosefNemec/Playnite#1385]
If application runs in compatibility mode, game time not calculating. In same cases Playnite behaves like if game closed (window minimize and now maximize).

Reproduce:
1. Right-click on .exe file.
2. Go to compatibility tab.
3. Set "Run in compatibility mode" checkbox and select "Window XP" or other.
4. Add .exe to Playnite.
5. Click Run button.

**Comment by JosefNemec** [comment]
My guess is that's because it forces the game to run with elevated privileges, which prevents Playnite from interacting with process properly.

**Comment by JosefNemec** [comment]
I can't reproduce it with latest version of Playnite. Can you confirm that this is still an issue? If so, please specify what games have this issue, including the game version (retain, Steam, GOG, etc.).
