### ISSUE TITLE
Screensaver option

### ISSUE THREAD

**Issue by MaximusX800** [JosefNemec/Playnite#1386]
Please add a screensaver option to Fullscreen mode.

Something simple like gradient default color scheme that flows diagonally.

**Comment by JosefNemec** [comment]
Why not just use screensaver that comes with Windows? Seems a bit unnecessary to implement something that's integrated in Windows.

**Comment by MaximusX800** [comment]
Two reasons, 1 wasn't sure how PlayNite's fullscreen mode was handled, borderless or not, to even allow windows screen saver to over-take.  And 2nd, due to personal preference, I disabled windows display off and screensaver options.

**Comment by JosefNemec** [comment]
I'm closing this, it find it unnecessary to implement feature that comes with Windows already.

**Comment by cnapolit** [comment]
@JosefNemec I have a handful of ideas that could be interesting with this concept. Would this be possible as extension? If so, I may try this sometime in the future.

**Comment by JosefNemec** [comment]
You can implement it as completely separate app. You can do it as a plugin, but I don't see a reason to go that route.

**Comment by cnapolit** [comment]
To anyone who's looking for something like this, I created a plugin for it: https://github.com/cnapolit/ScreenSaver .

**Comment by chinedooo** [comment]
A screensaver would be nice in the app because i have an OLED TV and only want the screensaver on the fullscreen OLED not my monitors
