### ISSUE TITLE
Detect uninstalled Steam Learning games

### ISSUE THREAD

**Issue by MaximeElbac** [JosefNemec/Playnite#1387]
First of all, sorry if it was already asked, and sorry if my English is broken.

For now, Playnite doesn't detect Steam Learning games (also called profile features limited games).
These are the kind of games where Steam isn't sure if it's "a true game", or a game made only for achievements and/or Steam cards, and lock these features until it looks legit enough.
Consequently, this somehow makes these games and its licenses harder to detect.
If you need an exemple, here's a free game that Steam is Learning : [Frostbite: Deadly Climate](https://store.steampowered.com/app/890880/FROSTBITE_Deadly_Climate/)
The only way for Playnite to detect them for now is to install them, and then run the detection for Steam games.
DLCs can also be in this "learning mode", but i don't think this will be useful for Playnite.

Can you do something about it ?
Thanks in advance.

**Comment by JosefNemec** [comment]
We can only import games that Steam API reports as part of your library. If Steam stem excludes those games from the API then there's nothing we can do about it.

**Comment by JosefNemec** [comment]
I'm closing this based on my previous comment. If some uninstalled games are imported and others are not then it's an issue in Steam API not reporting those games as part of your library.
