### ISSUE TITLE
Running a game and putting your PC to sleep keeps counting time for Time Played

### ISSUE THREAD

**Issue by darklinkpower** [JosefNemec/Playnite#1389]
**Describe the bug**
Running a game and putting your PC to sleep keeps counting time for Time Played. 

**To Reproduce**
For example, if you start a game, play 1 minute and don't close, then put your pc to sleep for 1 hour, it will count as 1h1m when you wake your PC anc close the game. It happens with manually added games or from any library

**Screenshots**
![imagen](https://user-images.githubusercontent.com/1389286/63550658-b6d72f80-c4f8-11e9-8efe-c9c3d45b4a3f.png)

This can not be a huge issue with steam since it corrects the time if enabled, but for every other platform, emulators or manually added games it would screw the playtime permanently.

**Comment by JosefNemec** [comment]
I'm not sure I can fix it without changing the way we count the time to less efficient (more CPU intensive) way. I'm not sure it's worth it since this looks like a very rare scenario.

**Comment by darklinkpower** [comment]
If there's not a way to "fix" this without compromising performance, I agree in ignoring this issue since as you say it's a very rare case scenario.

**Comment by kvdrrrrr** [comment]
How about using [this (MSDN).](https://docs.microsoft.com/en-us/dotnet/api/microsoft.win32.systemevents.powermodechanged?redirectedfrom=MSDN&view=netframework-4.8) Suspended state should indicate (among other suspended states) sleep state.

**Comment by JosefNemec** [comment]
I'm closing this. We would have to completely rework how play time counting works and I don't think it's worth it just for this rare scenario.

**Comment by sysmoon14** [comment]
I know that this has been closed for 3 years now, but for what it's worth I think this is much more important with the rise of Windows handhelds and the Steam Deck. I will suspend my Deck with games running all the time which basically renders the play time count useless.

**Comment by xdpirate** [comment]
Adding that this also applies to hibernation as well as sleep, from #3702.

**Comment by journeym** [comment]
Is this going to be fixed?
It's not a rare scenario, for games that use videocard on full it's common to put pc to sleep to save power. It's basically the same thing as a console sleep.

**Comment by xdpirate** [comment]
> Is this going to be fixed? It's not a rare scenario, for games that use videocard on full it's common to put pc to sleep to save power. It's basically the same thing as a console sleep.

It's only gonna get more and more common with x64-based handhelds like ROG Ally, Steam Deck, etc. becoming more and more common. Whenever I play games on my Ally, I always hibernate while in game because it's quick and saves battery, and most games work fine after waking from hibernation.

**Comment by JosefNemec** [comment]
Fixed in 10.33
