### ISSUE TITLE
Move the project homepage over to HTTPS

### ISSUE THREAD

**Issue by Hermanio** [JosefNemec/Playnite#139]

**Comment by nichols-356** [comment]
Just curious, any specific reason you're asking for this? I see no problem with the project homepage being on HTTP, seeing as it has no form fields to fill out, therefore nothing insecure to transmit.

**Comment by Hermanio** [comment]
Yes, it is a static page, but it would still be good practice to enable HTTPS. I could help with this if nobody else has the time to do this.

**Comment by JosefNemec** [comment]
I'm not sure it's worth the price of SSL certificate.

**Comment by Hermanio** [comment]
No need to even pay anything with LetsEncrypt: https://letsencrypt.org/

I have set it up on my personal site and it works very well. There are plenty of guides on doing this, for example these:

https://www.digitalocean.com/community/tutorials/how-to-secure-apache-with-let-s-encrypt-on-debian-8
https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-debian-8

**Comment by C0rn3j** [comment]
Any progress on this?

You link to binaries you expect people to run on the page, TLS is very important in this case.

**Comment by JosefNemec** [comment]
DV SSL is up: https://playnite.link

**Comment by C0rn3j** [comment]
http://playnite.link/

HTTP doesn't redirect to HTTPS.

You may also want set HSTS header and getting into the HSTS preload list - https://hstspreload.org/

**Comment by JosefNemec** [comment]
It redirects for me in Chrome and IE, what browser do you use?

**Comment by C0rn3j** [comment]
Chromium and Firefox.

No redirect using either browser.

**Comment by JosefNemec** [comment]
It should now properly redirect, please let me know if it works for you.

**Comment by C0rn3j** [comment]
Works great!

Though you can still get bonus points for getting on the preload list ^^ 

https://hstspreload.org/
