### ISSUE TITLE
Selecting favorites in grid mode uses different spacing than when not selected

### ISSUE THREAD

**Issue by darklinkpower** [JosefNemec/Playnite#1391]
**Describe the bug**
Selecting favorites in grid mode uses different spacing/number of columns than when not selected

**To Reproduce**
Move the slider just exact amount to show one more column with favorites selected. If you unselect favorites, the number of columns will decrease by one.

**Screenshots**
![2019-08-25_13-48-18](https://user-images.githubusercontent.com/1389286/63654436-ddd37280-c73f-11e9-8175-94f5162b67d5.gif)

**Comment by JosefNemec** [comment]
It's because the scrollbar shows up, taking up some space. IMHO not worth "fixing".

**Comment by darklinkpower** [comment]
Then it's basically the same thing that is happening in #1327 ? I was thinking this could be fixed for consistency but not a big thing if you decide to not fix it, more so if it's a difficult task.

**Comment by JosefNemec** [comment]
Yes it's the same thing, but I can't apply the same fix here because the layout code has no idea how big the scrollbar is (to reserve extra space for it), because it's being set by theme.

**Comment by JosefNemec** [comment]
I'm going to close this since it's not fixable in any reasonable way.
