### ISSUE TITLE
Unexpected crash

### ISSUE THREAD

**Issue by thiagoAciely** [JosefNemec/Playnite#1394]
**Check for existing issue**
Please use issue search in the repository if the bug is something really obvious there's a high change it was already reported.

**Describe the bug**

**To Reproduce**
If it's not clear from the description how to reproduce the issue please add clear steps to reproduce the behavior.

**Screenshots**

**Diagnostics ID**
If this is a crash report please include string ID you receive after using "Create diag. package` on crash dialog.
61c851ca-f977-4a0d-ac11-35d2759680b8

**Comment by JosefNemec** [comment]
Fixed in 5.7
