### ISSUE TITLE
Playnite categories not being removed after removing games under them

### ISSUE THREAD

**Issue by PopeRigby** [JosefNemec/Playnite#1395]
**Describe the bug**
Categories are still staying in the category list, even after all the games that have been assigned that category have been removed. I tried sorting by categories but none of my games were under the categories that were still there.

**Screenshots**
![Screenshot (55)](https://user-images.githubusercontent.com/20866468/63901133-32812280-c9b8-11e9-8ece-753f8a6de9cd.png)

**Comment by darklinkpower** [comment]
Not a bug, you need to remove the category in the library manager (ctrl+w)

**Comment by PopeRigby** [comment]
Oh. In #507, @JosefNemec said that you needed to remove all your games from under that category. I didn't even know the library manager existed.
