### ISSUE TITLE
Suggestion to change link descriptions and add possibly add a new one

### ISSUE THREAD

**Issue by darklinkpower** [JosefNemec/Playnite#1396]
**Describe the solution you'd like**
Change the following terms
Forums -> Community Hub (Correct term to where the current link gets you)
Wiki -> PCGW (Current term is too ambiguous, I thought at first it was a link to the respective Wikipedia page and since there are multiple wiki websites, it could be confusing)

As another suggestion, maybe adding a link called "Discussions" (term used for the steam forums) would be a good idea, preferably between Community Hub (if it gets changed) and News since it would make more sense to place it there.

**Screenshots**
![imagen](https://user-images.githubusercontent.com/1389286/64067313-57f67200-cbec-11e9-8f83-ab481e0da20a.png)

to:

![imagen](https://user-images.githubusercontent.com/1389286/64067311-4f9e3700-cbec-11e9-86d7-9a945c192091.png)

**Comment by JosefNemec** [comment]
Just a note for anybody fixing this:
Links are set by the library plugins, so this should fixed on per library basis. For example `Community Hub` only makes sense for Steam, since GOG only has forums. Also we already changed `Wiki` to `PCGW` in some library plugins, it's a case of unifying this in other plugins.

**Comment by darklinkpower** [comment]
I made a pull request with the following changes: #1417 

I changed the Following ones:
`Forums` -> `Community Hub`
`Discussions` (I added this one)
`Store` -> `Store Page` (Current term is not too clear where it takes you and Store Page is the correct name Steam itself uses in it's webpage to refer to that link)
![imagen](https://user-images.githubusercontent.com/1389286/64916556-f0d8d180-d744-11e9-9a7b-befa7e9a1d72.png)

`Wiki` -> `PCGamingWiki` (I decided to use the whole name for consistency since a lot of software and websites refer to it as PCGamingWiki, not as PCGW. For example, the Augmented steam extension)
![imagen](https://user-images.githubusercontent.com/1389286/64916535-7b6d0100-d744-11e9-8df2-d73464e703ce.png)


Created a Pull request for the steam library.

**Comment by JosefNemec** [comment]
Released in 5.7
