### ISSUE TITLE
In Details View, when you scroll all the way to the bottom of the list, minimize the window and return to it, the list will be scrolled up very slightly.

### ISSUE THREAD

**Issue by crobblackley** [JosefNemec/Playnite#1397]
**Describe the bug**
In Details View, when you scroll all the way to the bottom of the list, minimize the window and return to it, the list will be scrolled up very slightly.

**To Reproduce**
Scroll to the bottom of the games list in Details View. Minimize window. Open window. See results.

**Screenshots**
![Playnite Issue 1](https://user-images.githubusercontent.com/54752955/64068886-da0b8880-cc36-11e9-9fac-23e877ebb711.png)
![Playnite Issue 2](https://user-images.githubusercontent.com/54752955/64068887-da0b8880-cc36-11e9-9195-9287625b6164.png)

**Comment by JosefNemec** [comment]
This is some issue in WPF, I can't fix it, sadly.
