### ISSUE TITLE
Download grids instead of covers

### ISSUE THREAD

**Issue by denisidoro** [JosefNemec/Playnite#1399]
Grids (let's define it as width > height) play nicer than covers (height > width).

Covers, when in fullscreen mode, are scaled and cropped.

The metadata downloader could use https://www.steamgriddb.com, for example. It even has some APIs.

**Comment by JosefNemec** [comment]
Support for additional metadata providers will be done in #417. People from Discord are already planning to implement them after #417 is done (especially steam grid ones), therefore I'm closing this.
