### ISSUE TITLE
Latest version doesn't recognize Vortex Minecraft Launcher

### ISSUE THREAD

**Issue by MohandL3G** [JosefNemec/Playnite#1401]
So in previous version of Playnite (I tried 4.74) it worked it recognized it, and the Play button changed to Running, but in the latest version (5.6) it doesn't.

here is a picture for the 4.74 version:
![4 74](https://user-images.githubusercontent.com/31743237/64275606-41328100-cf46-11e9-8348-d72d68a048ff.jpg)

and here is a picture for the 5.6 version:
![5 6](https://user-images.githubusercontent.com/31743237/64275395-bbaed100-cf45-11e9-99d9-adf121eb485e.jpg)

Can you please fix this, and thanks.

**Comment by JosefNemec** [comment]
Nothing changed in 5.x in regards to play time detection. Did you change Play action's settings by any chance?

**Comment by MohandL3G** [comment]
Nope, sorry, but I haven't changed anything.

**Comment by MohandL3G** [comment]
I have fixed it, I tried to disable hardware acceleration, and it worked, I don't know why?
now even if I enable hardware acceleration it works.

**Comment by JosefNemec** [comment]
That must be something else, hardware acceleration can't have any effect on it. It's more likely some random issue that only occurs sometimes.

**Comment by MohandL3G** [comment]
Yea, I though so I don't know from the problem came, I just tried to install it on my brother PC, and it worked, so I don't know, I tried to restart the app and run it as admin, I also tried to restart my PC, so I don't know why it didn't work at first, anyway now it just work.

thanks for the support.

**Comment by JosefNemec** [comment]
If you find a way how to reproduce it on demand let me know.
