### ISSUE TITLE
Clear logo support

### ISSUE THREAD

**Issue by sjdawson** [JosefNemec/Playnite#1402]
Addition of a new field on the media tab for "clear logo", that is the to show the logo of the game/application that can be displayed on a background.

Although this image is from the new Steam library screenshots, this shows how the feature could benefit Playnite:

![image](https://user-images.githubusercontent.com/1701603/64324117-a70e1f80-cfbd-11e9-845d-543ab4bf018d.png)

**Comment by develoqqer** [comment]
very good idea from steam

**Comment by JosefNemec** [comment]
This will be done via #358. I don't think it makes sense to add it as built-in media type since only Steam and Epic provides those.

**Comment by sjdawson** [comment]
Ah, yes. This is a duplicate of #358 - apologies. I searched for "clear logo" before making this issue, but didn't find that one as that issue didn't mention it by this name. 

I was under the impression that IGDB had them, but on second looking, that doesn't seem to be the case. :disappointed:
