### ISSUE TITLE
Controller support in desktop mode doesn't work

### ISSUE THREAD

**Issue by ooa113y** [JosefNemec/Playnite#1403]
**Describe the bug**
My controller works with Playnite in fullscreen mode, but not in desktop mode. This is a regular XBox One controller, nothing special about it. It's connected wirelessly if that matters, but I don't see how it would. The "Enable controller support in Desktop mode" option is enabled.

**Diagnostics ID**
4c0d52dd-591b-4841-a6e3-14b69dd4dbc7

**Comment by JosefNemec** [comment]
Controller is not supported in desktop mode. The only function that's supported is Guide button which should open Fullscreen mode. The description of the option is misleading and will be fixed.

**Comment by ooa113y** [comment]
As a matter of fact, the guide button does not do anything either (the option to enable it is also checked however)

**Comment by JosefNemec** [comment]
Does it work after you manually select some input element (like game list for example)? It's probably connected to #701 issue.

**Comment by ooa113y** [comment]
It appears to work after minimizing and restoring the Playnite window.
