### ISSUE TITLE
Suggestion to add option to change colors used inside settings

### ISSUE THREAD

**Issue by darklinkpower** [JosefNemec/Playnite#1406]
**Describe the solution you'd like**
Adding it as an option would be better since there would be no need to edit theme files to change colors and it would eliminate the problems when the default theme is updated since it would need to be updated again. With this and the option to change the font, you would only need to edit the theme files if you want to make some "heavy" modifications to the theme

**Comment by JosefNemec** [comment]
I don't think we can implement this in some reasonable way. A lot of things in themes are defined with brushes, not just colors.

**Comment by JosefNemec** [comment]
I'm closing this since there's now [extension](https://playnite.link/forum/thread-388.html) for it.
