### ISSUE TITLE
Dead cells Microsoft store not showing

### ISSUE THREAD

**Issue by gamdes** [JosefNemec/Playnite#1410]
Hello,

i've downloaded Dead Cells from microsoft store, the Xbox (beta) app, and it doesn't show in installed games.

when im doing add microsoft store or xbox app game, nor when i use detect installed.

Thank you.

**Comment by darklinkpower** [comment]
It shows as this name, not as Dead Cells
![imagen](https://user-images.githubusercontent.com/1389286/64477751-ee82e000-d164-11e9-83ee-1ee12f661e48.png)
