### ISSUE TITLE
Please add a {System} emulator CLI argument

### ISSUE THREAD

**Issue by djvj1** [JosefNemec/Playnite#1411]
I'm requesting one additional argument be added to your list of parameters that can be passed to the emulator executable.

So for example, if the user has a list of Sega Genesis games in Playnite, "Sega Genesis" would be the system name. Adding an argument like {System} so that can be passed onto the executable would allow my app (RocketLauncher) to work correctly with Playnite.

**Comment by JosefNemec** [comment]
Added in 5.7. It's called `{Platform}` to make it consistent with what the field is named in the application. Full list of variables is available [here](https://github.com/JosefNemec/Playnite/wiki/Adding-new-emulator#dynamic-variables) (I've added more of them).

**Comment by djvj1** [comment]
Great! Can't wait to try it. Thank you.
