### ISSUE TITLE
Global search rework

### ISSUE THREAD

**Issue by JosefNemec** [JosefNemec/Playnite#1413]
The idea is to have global search to work as general game and command search. Similarly to how VS Code's [command palette](https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette) works.

You open the search/command bar (for example with CTRL-F) and start typing. Playnite will list both games and commands that fit the search term and instead of filtering list of visible games it will allow user to immediately invoke the action (start the game, start game installation, invoke Playnite command etc.)

For example if you type "add" you would get list of all games with "add" string in them, but all commands like "Add Emulated Game", "Add Game Manually" etc.

Additional:
- we should also expose this to Playnite's SDK and allow extensions to provide custom commands.
- if possible we should also make this working when Playnite is not focused, by having an option to assign system shortcut that would open search on general desktop.

**Comment by bluddy** [comment]
It would also be nice to include all content from the library manager in the search. This would be an easier way, for example, to open up to a specific genre or a specific category than the Explorer Panel.

**Comment by darklinkpower** [comment]
This is a good idea. I moved to keyboard based launcher for my PC a long time a ago and they are pretty good. I think implementing a command based system too would help a lot since a general one can get clunky results. Similar to how keyboard launcher work by using a letter or command + space + search. A few ideas:

**For game status:**
i Gamename (limits search to installed games and Searchs using "Gamename")
u Gamename (limits search to unninstalled games and Searchs using "Gamename")
f Gamename (limits search to favorited games and Searchs using "Gamename")
h Gamename (limits search to hidden games and Searchs using "Gamename")

**You could also limit the search by library or platform using commands**
epic Gamename
Steam Gamename
snes Gamename
etc...

**For Playnite commands:**
cmd Add
cmd update
etc...

**Comment by JosefNemec** [comment]
You should not have to write cmd, i, u or any other keywords. It should automatically list all options grouped based on what they are (commands, games etc.), with an option to choose priorities.

**Comment by darklinkpower** [comment]
Yes I get that, it's just that in my experience with keyboard launchers, they sometimes don't give you what you want and you have sometimes almost have to write the full word to give you what you want. Commands limit the search and are more precise and get you to the result you want faster, but it's fine to have a general search too, just was throwing an idea.

**Comment by Flomkato** [comment]
I am missing an exclude option in the filters.
A optional keyword would come in handy.
e.g.:
#g(enre) Action && #t(ag) --gore

**Comment by TRoehrman** [comment]
Suggestion for associated feature: (When searching, press down to move to the list and hit enter to launch the game.) Lessens reliance on the mouse.

**Comment by tynansdtm** [comment]
I also want to suggest a feature. A new field for game details, specifically for search aliases. For example, searching GTA could find Grand Theft Auto games in my library. If there's only one, I wouldn't want to use the Series field. Maybe future extensions could automatically add acronyms to this search alias field.

**Comment by Bluscream** [comment]
^ 100% this, thanks for suggesting it

**Comment by Bluscream** [comment]
^ 100% this, thanks for suggesting it

**Comment by felixkmh** [comment]
I tried my hand at an extension (before I knew this issue existed) that checks most of the boxes in the initial proposal, so I thought I might as well share it here. Forum post for the extension: https://playnite.link/forum/thread-677.html . Problems it has of course, are that it has limited access to Playnite's commands outside of the ones bound to shortcuts in the main window and that adding commands from other extension requires these extension to reference an additional assembly.

**Comment by JosefNemec** [comment]
Done in devel.
