### ISSUE TITLE
Parental Controls or Lock Changes

### ISSUE THREAD

**Issue by japzone1** [JosefNemec/Playnite#1415]
I'm interested in creating a pseudo game console using Playnite and its Fullscreen mode. The only issue is that Fullscreen mode still allows making changes to the library(like removing titles) and changing some settings, plus it has a menu option to switch back to the desktop mode where even more could be done. I can't leave kids alone with this if they could accidentally delete things or screw up some setting. If there was a way to launch Playnite Fullscreen without these options, or a parental lock of some kind, that would be nice. I can handle making sure Windows itself can't be messed with, but I need a way to protect Playnite. 

Maybe a launch flag that would hide the settings and Desktop mode? I could work with that.

**Comment by JosefNemec** [comment]
Duplicate to #1252 and #1102.

**Comment by admiralzeech** [comment]
Try looking at the bottom of my issue #1252 - If you use version 4.74, and comment out / delete the block for the escape menu, and only have gamepad games (and thus no mouse/keyboard), then I think you're pretty covered for locking down playnite.  (to exit playnite, you plug in a keyboard and kill playnite using Ctrl+Alt+Del and task manager.)

You might also consider installing software like Deepfreeze or Rollback Rx, so you can undo any mishaps with just a reboot.
