### ISSUE TITLE
Views (like Galaxy bookmarks)

### ISSUE THREAD

**Issue by bluddy** [JosefNemec/Playnite#1418]
It'd be nice to have something like Galaxy's bookmarks, as they provide rapid access to specific list -- faster than working through the Explorer Panel's intricate interface.

Effectively, a view would save a combination of filters and view settings (e.g. grid/list/details) and would have easy access via a view bar of some sort. One default view could be your favorites, making them really easy to get to.

The views would also integrate well with the global search feature. A quick search for 'favorites' (with auto-completion) would take you to your favorites, with default grid view (though you could modify the view to have a list view). (I realize the over-usage of 'view'. Might need a different name.)

**Comment by darklinkpower** [comment]
Duplicate to #590

**Comment by bluddy** [comment]
Fair enough. Not an exact duplicate since I'd like these things to save the current view settings as well, and also be very easy to access.

**Comment by darklinkpower** [comment]
I think you should post your ideas in that issue and not in a separate one since it's related, but it's up to @JosefNemec how he wants to organize things here

**Comment by JosefNemec** [comment]
I'm going to close this since the majority of this will be done in #590. We can discuss other changes after that's done, however we won't be able to replicate Galaxy's system exactly anyways because we have different approach to UX.
