### ISSUE TITLE
UI Enhancement: collapse / expand all

### ISSUE THREAD

**Issue by nichols-356** [JosefNemec/Playnite#142]
When viewing your library grouped by category, by default it has all categories expanded. I have a lot of categories, so it becomes a tad difficult to scroll through and find the category of game I want to play. I'd like the ability to collapse all categories with a few clicks. Maybe it can be done in a right click menu over the category itself, with options such as:
* Collapse
* Collapse all
* Expand
* Expand all

**Comment by JosefNemec** [comment]
Thanks for a suggestion, there's already issue #54 for it, so I'm going to close this as duplicate.
