### ISSUE TITLE
Playnite doesn't download metadata for newly added games

### ISSUE THREAD

**Issue by cristi1990an** [JosefNemec/Playnite#1424]
Only downloading the metadata manually and unchecking the "download only for games missing metadata" checkbox makes the metadata download.

**Comment by JosefNemec** [comment]
Can you check that you have "Download metadata after importing games" option enabled in the settings?

**Comment by cristi1990an** [comment]
Yes, it's checked

În mar., 17 sept. 2019 la 13:04, Josef Nemec <notifications@github.com> a
scris:

**Comment by JosefNemec** [comment]
Are these manually/emulated games or games from some 3rd party library?

**Comment by JosefNemec** [comment]
Also please add some examples of game names causing the issue or ideally exact steps how to reproduce this. And please generate diag. package from "About Playnite" menu. Thanks

**Comment by cristi1990an** [comment]
Normal 3rd party library. They get added at start-up, but the metadata
never downloads.

În mar., 17 sept. 2019 la 13:28, Josef Nemec <notifications@github.com> a
scris:

**Comment by JosefNemec** [comment]
Is this still an issues? Can you provide diag. package I asked for in my previous comments?

**Comment by cristi1990an** [comment]
Ah, sorry. I didn't see your second reply. Here's the
ID: 20737e8f-2282-40a8-bcce-6665bf5eb840. Yes, I still seem to have the
issue. But I don't have any games right now missing the metadata since
manually downloading it still fixes the issue and I've been doing that ever
since.

În joi, 7 nov. 2019 la 18:48, Josef Nemec <notifications@github.com> a
scris:
