### ISSUE TITLE
[fresh install] Not working for Battle.net, GOG and Origin (OK for Steam and Epic)

### ISSUE THREAD

**Issue by simkin** [JosefNemec/Playnite#1427]
**Describe the bug**
Fresh installation, ran through authentication wizard for Steam, Origin, Battlenet, Uplay and GOG. Only Steam and Epic store games are imported. For the others a "not logged in" notification is displayed

**To Reproduce**
n.a.

**Screenshots**
![image](https://user-images.githubusercontent.com/958263/65145752-8a8cd100-da1a-11e9-8186-99e0874c71ad.png)

**Workaround**
Settings-> Libraries --> Re-autheticate --> Update Library

**Comment by JosefNemec** [comment]
Please see this: https://github.com/JosefNemec/Playnite/wiki/Account-sync-troubleshooting

**Comment by JosefNemec** [comment]
You can also repeat the authentication process in the Settings -> Libraries menu.

**Comment by JosefNemec** [comment]
Closing, please open new issue for specific library if you still have login issues.
