### ISSUE TITLE
Selected install for a game installed already, Playnite crashes and won't start up anymore

### ISSUE THREAD

**Issue by bbottema** [JosefNemec/Playnite#1428]
**Describe the bug**
Selected install for the already installed game "Alcyone_ The Last City" (itch). This game is known to have naming issues as well I think due to a character not allowed in Windows file/folder names. I remember having it installed manually and not through Itch, while Playnite might thing it was installed through Itch.

**Diagnostics ID**
1b86fe97-cc3d-4cd9-b2ce-ba6fbfb35aba

**Comment by JosefNemec** [comment]
Could you please upload your library folder for me? Some media file is causing OutOfMemory crash. It's a `%appdata%\Playnite\library` folder. Thanks

**Comment by JosefNemec** [comment]
Fixed in [5.8 update](https://github.com/JosefNemec/Playnite/releases/tag/5.8).
