### ISSUE TITLE
Settings lost

### ISSUE THREAD

**Issue by Skarafaz** [JosefNemec/Playnite#1432]
Hi!

Sometimes Playnite resets my custom settings (just settings, the db is ok) to default. It happened a couple of times during last ten days, so I think it could be a bug.

**Comment by JosefNemec** [comment]
Please go to `About Playnite` menu and create diagnostics package for me. Thank you

Also do you know what settings got reset?

**Comment by Skarafaz** [comment]
Ok, I will sed you the package asap.

All settings I think.

**Comment by Skarafaz** [comment]
I've uploaded the diagnostic package! Here is the id: 59197c6e-e117-4e73-b1bd-32fa2ab5162d

**Comment by JosefNemec** [comment]
Thanks for the diag. package. I don't see any errors related to settings in those logs. Do you remember by any chance what settings are being reset exactly? I'll add some additional diagnostics messages to Playnite 6, so please create new diag. package for me once Playnite 6 is available if issue still persists. Thank you

**Comment by Skarafaz** [comment]
_All_ settings has been reset. I'll send you the v6 package! Thanks.

**Comment by Skarafaz** [comment]
It just happened again.

**Comment by JosefNemec** [comment]
Please generate new diag. package. Thanks

**Comment by Skarafaz** [comment]
Here is the id: b2ab54cf-2356-4f7c-b187-a58a9cb919a8

(Sorry for the late answer)

**Comment by JosefNemec** [comment]
Thanks for diag. package. I'm afraid I probably won't be able to help you. There is no information in logs that settings are being reset, I'm not sure what's going on.

**Comment by Skarafaz** [comment]
Ok, no problem! I've just installed the latest version, I will report here if it will happen again. Thanks.
