### ISSUE TITLE
Copying Categories

### ISSUE THREAD

**Issue by haseebxhekh** [JosefNemec/Playnite#1437]
In the previous versions of playnite, I was able to edit the game and copy/paste all the custom categories that I had made up until that point. Now after adding a game, I have to manually select the categories and it's taking too long. Please bring that ability back! PLEASE!!!

**Comment by JosefNemec** [comment]
You can bulk edit categories for multiple games, just select multiple games and edit the details.

**Comment by JosefNemec** [comment]
Closing per my last comment, you don't have to edit categories one game at a time, you can bulk edit them.
