### ISSUE TITLE
Error on Startup - Sort by Name?

### ISSUE THREAD

**Issue by SoupOrJuice** [JosefNemec/Playnite#144]
Not exactly sure what caused this error. I've been trying to get the Library to search for the Name of a game, but it hadn't been working (when I would type and press Enter, the entire list would still be there). So I tried a couple things. I tried opening the Filter tab and closing it again, which would just make all the games disappear from the list (even though I know a game exists with that exact name), I could get them back by clearing the Filters. But then I tried the Name + Filtering by Platform (in this case Origin), and got this error.
[Here's the Diagnostic file.](https://github.com/JosefNemec/Playnite/files/1366966/Issue.Diagnostic.zip) Can't do anything currently, the error comes up on each restart.  

Also, if there's a way to reset the filter outside of Playnite (in a config somewhere), that'd be nice because it's currently unusable :(

**Comment by JosefNemec** [comment]
Interesting error you have here. Could you please try it [with this debug build](http://playnite.link/download/PlayniteInstallerDebug.exe) and send me a new diag. package? Thanks in advance

**Comment by JosefNemec** [comment]
Btw to reset settings just delete `%appdata%\playnite\config.json` file.

**Comment by SoupOrJuice** [comment]
I get [this](https://user-images.githubusercontent.com/20274390/31318474-5de2b508-ac21-11e7-8c91-af99e3e238b3.PNG) when I try to launch the debug build. I deleted that file and re-imported just Steam/Origin/UPlay, but when it brings up the list of games it just freezes/goes unresponsive.

**Comment by JosefNemec** [comment]
Please try it again, I've re-uploaded new version, which should not freeze. Sorry for the issues and thanks again.

**Comment by SoupOrJuice** [comment]
[Here's](https://user-images.githubusercontent.com/20274390/31318656-d3b23e46-ac23-11e7-9dd3-9b3bbc509bb9.png) part of my list. [This](https://user-images.githubusercontent.com/20274390/31318662-e900f44a-ac23-11e7-8ff3-8ffa0d9471df.png) is my list with a Name filter. No more error, even when filtering with Origin, Steam, UPlay, etc. I've tried all combinations. But the Name search still doesn't work. (You can see a game named exactly "20XX" in the first screenshot, doesn't appear in the 2nd.)

**Comment by JosefNemec** [comment]
Can you attach diag. package please?

**Comment by SoupOrJuice** [comment]
Oh, yes sorry - 
[Fixed.zip](https://github.com/JosefNemec/Playnite/files/1367023/Fixed.zip)

**Comment by SoupOrJuice** [comment]
And this is the diag package from the Debug build.
[Debug.zip](https://github.com/JosefNemec/Playnite/files/1367025/Debug.zip)

**Comment by SoupOrJuice** [comment]
Sorry for spam. 
[This](https://github.com/JosefNemec/Playnite/files/1367029/Debug.zip) is the Debug diagnostic package.

**Comment by JosefNemec** [comment]
OK one more thing, can you upload your database file? If you open settings you'll see its location there. Thanks

**Comment by SoupOrJuice** [comment]
[games.zip](https://github.com/JosefNemec/Playnite/files/1367037/games.zip)

**Comment by JosefNemec** [comment]
It looks like it's an empty zip file I'm afraid.

**Comment by SoupOrJuice** [comment]
Whoops, sorry about that. [Here it is.](https://www.dropbox.com/s/l2juckoxlh3bjgy/games.zip?dl=0)

**Comment by JosefNemec** [comment]
Thanks a lot helping me with this. I've fixed the issue and you can use [this build](http:/playnite.link/download/PlayniteInstallerSteamFix.exe) until the patch gets released with normal updates.

**Comment by SoupOrJuice** [comment]
Hey, thanks so much for the help. And for Playnite!! So useful.

**Comment by JosefNemec** [comment]
Released in 2.3
