### ISSUE TITLE
Fullscreen mode bugs view when exiting game

### ISSUE THREAD

**Issue by rmccullagh99** [JosefNemec/Playnite#1445]
After I exit a game in fullscreen mode, the view is bugged as seen below.

I can't seem to get it to work EVERY time, but the most consistent way is to launch a game in playnite fullscreen, exit it and scroll my game list. If it helps I have two monitors, main being 4k and secondary being 2k.

![bugreport](https://user-images.githubusercontent.com/42370113/65389238-46415e00-dd97-11e9-9f24-9e84a37075b7.png)

**Comment by JosefNemec** [comment]
Done in `devel`.
