### ISSUE TITLE
Main window blackout stops working when Playnite isn't the active window

### ISSUE THREAD

**Issue by sjdawson** [JosefNemec/Playnite#1447]
If you open a popup window, say to edit details of a game, the main window of Playnite gets a nice blackout over it, to put focus on the new popup. However, if you make it so Playnite isn't the "active" window, that blackout disappears. Making Playnite active again will restore the blackout.

**To Reproduce**
* Open the "Edit game details" window for any game.
* Open another window (file manager, or click on your desktop).

**Comment by JosefNemec** [comment]
Done in 6.1
