### ISSUE TITLE
Add an accent color setting

### ISSUE THREAD

**Issue by RubeensVinicius** [JosefNemec/Playnite#1449]
With the addition of the settings allowing us to change the size and indentation of objects on the UI without having to make a new theme, how about an option to select an accent color, like the one on the Windows 10 settings? This could be used on the default theme to replace the blue with another color, making the "Default Red", "Classic Blue" and "Classic Green" themes unnecessary and letting us choose our favorite color.

**Comment by JosefNemec** [comment]
Duplicate to  #1406
