### ISSUE TITLE
Cover view

### ISSUE THREAD

**Issue by dephunk** [JosefNemec/Playnite#145]
Any chance of having an option to have a cover view without the launcher icon below, I added a game manually and it doesn't have this & 100% looks cleaner imo. Thanks

**Comment by dephunk** [comment]
Also it scanned my uPlay games fine but didn't automatically scan & download metadata for them?

**Comment by JosefNemec** [comment]
Covers are being reworked as part of #36 Also there's no automatic metadata download for UPlay games currently.
