### ISSUE TITLE
Double game entries using "Last Played"

### ISSUE THREAD

**Issue by JosefNemec** [JosefNemec/Playnite#1451]
https://www.reddit.com/r/playnite/comments/d6644n/double_game_entries_using_last_played/

> I have a very large library so I tend to use the "Last Played" filter option. I noticed that every time I leave a game, it will not always reflect in "Last Played" and almost always will instead show a duplicate cover of the previously played game. If you select one of the duplicate entries, it will show "No game is selected". I can reproduce this every time I leave a game and look at the top of the list. The only way to fix it is to either A) change the filter to something else and then back or B) scroll the list down a ways and let it sort itself out when I scroll back.

**Comment by rohanrichards** [comment]
Just adding to this as per my comments on the Discord (Noom) as it was indicated my issue is related to this.
I have many duplicate entries when in Grid View, plus grouping by genre.
[imgur link to image of duplication](https://imgur.com/E5zJN7L)

**Comment by JosefNemec** [comment]
Done in `devel7`.
