### ISSUE TITLE
Support for new Steam metadata and client

### ISSUE THREAD

**Issue by IrritatedGoat** [JosefNemec/Playnite#1455]
When getting Official Store metadata from a Steam library game, it is still grabbing the old grid style banner. 

Games tried:
Hyper dimension Neptunia Rebirth 1,2
Hyper dimension Neptunia U 
Higurashi When They Cry (any part)
Mega dimension Neptunia V II R
Muv Luv Alternative

**Comment by JosefNemec** [comment]
We don't support new metadata or new Steam beta client yet.

**Comment by JosefNemec** [comment]
Done in Playnite 6.
