### ISSUE TITLE
[Epic Games connexion] pollingID is invalid

### ISSUE THREAD

**Issue by MagicaNexus** [JosefNemec/Playnite#1459]
When I want to connect to Epic Games, I have this error :

**Screenshots**
![image](https://user-images.githubusercontent.com/33450776/65721975-84969000-e0ab-11e9-9388-9bf3e047cd8a.png)

Thanks

**Comment by MagicaNexus** [comment]
I had this issue because I am using Google Auth.
To resolve this issue, I symply go to the epic games store on my browser and added a new password. Then connect without using Google Auth. Et voilà !

**Comment by JosefNemec** [comment]
Duplicate to #1416
