### ISSUE TITLE
Icon for games from Epic Store

### ISSUE THREAD

**Issue by leobenkel** [JosefNemec/Playnite#1460]
**Check for existing issue**
I havent seen something similar when I searched: https://github.com/JosefNemec/Playnite/issues?utf8=%E2%9C%93&q=epic+icon

**Describe the solution you'd like**
When the meta data are downloaded from Steam or other provider, the icon of the game in the list change.
However, the one coming from epic store dont. They have a default icon. I even tried to manually download from IGDB or wiki but the icon was not added.
I get that if the `exe` don't have an icon, that will be tricky. But maybe when several media are downloaded, pick the one that is square and smallest or the available ones ? That would probably end up better than the default most of the time ?

**Comment by JosefNemec** [comment]
There's no metadata source that would provide game icons, we have no way where to download them.

**Comment by leobenkel** [comment]
What about what I suggested ? From the exe file, extract the icon. Or from the other sources, take the first media which is a square and smallest resolution ?

**Comment by JosefNemec** [comment]
We don't know what the actual executable is. We could guess, but it wouldn't be accurate.

**Comment by JosefNemec** [comment]
Ignore my last comment, I forgot that we actually already set icon if the game is installed. You just need to manually re-download metadata if the game goes from uninstalled to installed state (we only update metadata automatically when the game is imported).

**Comment by leobenkel** [comment]
ah ok, after re-downloading, the icon show up. Maybe the feature should be updated then. 

Maybe when the game switch from uninstalled to installed, you can resync ?
