### ISSUE TITLE
Renaming a string in the Library Manager produces error "An item with the same name already exists" if only capitalization is changed

### ISSUE THREAD

**Issue by ethansshaw** [JosefNemec/Playnite#1461]
To reproduce:

Press ctrl+w to open the Library Manager. Select any string from any category, e.g under "Source", choose "Battle.net", and rename to the same string but with capitalization changed, e.g "BATTLE.NET", and the error is returned "An item with the same name already exists" despite the strings being technically different. This is significant primarily for aesthetic reasons.

**Comment by JosefNemec** [comment]
Done in 6.0
