### ISSUE TITLE
Close Fullscreen mode with F11

### ISSUE THREAD

**Issue by MohandL3G** [JosefNemec/Playnite#1464]
I like to use keyboard shortcuts more than using my mouse, even on Playnite I always use F3 to edit game info and F11 to change to Fullscreen mode.

So can you add the keyboard shortcut F11 in Fullscreen mode, so that it close Fullscreen mode and return to desktop mode.

**Comment by bsinky** [comment]
Has anyone started implementing this yet? It sounds useful, and I'm interested in trying my hand at a PR if no one's started work on this yet.

**Comment by JosefNemec** [comment]
I don't think anybody is working on this atm.
