### ISSUE TITLE
I want to be able to override the play button

### ISSUE THREAD

**Issue by lupus590** [JosefNemec/Playnite#1471]
Related? #113

**Describe the solution you'd like**
I would like to be able to replace the default play button added by the library plugin. For example, I have Fallout 4 with its default play button from Steam, I also have F4SE installed and would like to have it that when I click on Fallout 4 to play it Playnite would launch the F4SE exe, not the Steam URL.

**Screenshots**
Some kind of button on this screen to set the custom Other Action as the default for the play button would do nicely.
![image](https://user-images.githubusercontent.com/9790321/65831514-58992b80-e2b2-11e9-993e-e76332386139.png)

**Comment by JosefNemec** [comment]
Uncheck `Managed by library plugin` checkbox and change the Play action settings to whatever you want (in you case change it to `Executable` type and set F4SE's exe as the path to launch.
