### ISSUE TITLE
"Force sync play time" doesn't seem to apply to the GOG library anymore

### ISSUE THREAD

**Issue by ClearStrelok** [JosefNemec/Playnite#1474]
I thought this could be an issue on my end, but I've had no issue syncing with Steam.

**Comment by JosefNemec** [comment]
We don't distinguish between libraries when deciding whether to download time or not. It must mean that we are not getting play time from GOG at all. Is play time downloaded for a game if you set it to 0?

**Comment by ClearStrelok** [comment]
It doesn't, but I will reinstall Galaxy and try again to make sure I'm not causing this.

**Comment by JosefNemec** [comment]
How do you link the GOG account? Via account name or by authenticating? Account name sync has been quite buggy (on the GOG's side) and I will be removing it in Playnite 6.

**Comment by ClearStrelok** [comment]
I'm using the account authentication. Right now, syncing is still broken after reinstalling GOG Galaxy and purging the web cache so I'm guessing this is an API issue. Could this be related to the ongoing beta of Galaxy 2.0 ?

**Comment by JosefNemec** [comment]
Galaxy installation will have no impact on this. We get the info from GOG's web API.

**Comment by JosefNemec** [comment]
I'm afraid I have to close this without a fix because I had to switch to a different API to get list of games (it's more reliable) and sadly that API doesn't provide play time information.
