### ISSUE TITLE
New games not appearing

### ISSUE THREAD

**Issue by ChildishGiant** [JosefNemec/Playnite#1476]
Whenever I add a new game, it doesn't show up in any of the views. This happens when manually choosing the EXE or when scanning automatically. This has happened with all games I've tried to add.

https://gfycat.com/wholeinfamousachillestang
![wholeinfamousachillestang](https://thumbs.gfycat.com/WholeInfamousAchillestang-size_restricted.gif)

**Diagnostics ID**
I don't think it's applicable but here it is anyway: 7fe453d2-0e87-4a50-bd2c-61fc4de26019

**Comment by JosefNemec** [comment]
I can see that you have a filter enabled, probably preventing those games from showing up. Click on the funnel icon on the main bar to see what filter is being applied.

**Comment by ChildishGiant** [comment]
![image](https://user-images.githubusercontent.com/13716824/65956476-5ebe1200-e442-11e9-9761-b0f56f904030.png)

Right you are. Sorry for the hassle
