### ISSUE TITLE
Support for Steam description metadata in other languages

### ISSUE THREAD

**Issue by darklinkpower** [JosefNemec/Playnite#1479]
**Describe the solution you'd like**
Currently, Steam grabs metadata in english language only even if you use Playnite in any other language. 

From what I see, Playnite currently pulls metadata via the Store API without any language in specific in `SteamLibrary/Services/WebApiClient.cs` this way:

`https://store.steampowered.com/api/appdetails?appids={appId}`

**Adding the `l` parameter, outputs the description in the target language:**
`https://store.steampowered.com/api/appdetails?appids={appId}&l={SteamApiLangCode}`

**For example:**
[https://store.steampowered.com/api/appdetails?appids=460790&l=japanese](https://store.steampowered.com/api/appdetails?appids=460790&l=japanese)

Perhaps the code could be changed to `https://store.steampowered.com/api/appdetails?appids={appId}&l=` and just add the target language via a localization string per language.

The Codes used by the API can be looked here (third column): 
[https://partner.steamgames.com/doc/store/localization](https://partner.steamgames.com/doc/store/localization)

The data in the description language is still in english when the game doesn't have a description in the requested language.

**Comment by JosefNemec** [comment]
This is actually duplicate to #136
