### ISSUE TITLE
Starts with the top 3rd out of the top of my screen. 

### ISSUE THREAD

**Issue by SoaringSpoon** [JosefNemec/Playnite#148]
Every time I launch PlayNite it starts out with the top 3rd of the screen off the top of my display. I have to resize it every time.

**Comment by JosefNemec** [comment]
Can you go to "About Playnite..." menu and create diag. package for me? Thanks

**Comment by SoaringSpoon** [comment]
Thanks Sure here you go 
[PlayNite.zip](https://github.com/JosefNemec/Playnite/files/1367312/PlayNite.zip)

**Comment by JosefNemec** [comment]
Do you have multiple monitors by any chance? What are their resolutions and which one is primary?

**Comment by JosefNemec** [comment]
Released in 2.4
