### ISSUE TITLE
Steam: Downloaded metadata description is in Russian

### ISSUE THREAD

**Issue by darklinkpower** [JosefNemec/Playnite#1480]
**Describe the bug**
For some games, the pulled game description is in Russian, for example: [I am not a Monster: Complete Edition](https://store.steampowered.com/app/826600/I_am_not_a_Monster_Complete_Edition/)

It might be related to #1479 but I'm not sure, since neither the store or the Steam API contain what Playnite gets for the description in any language:

Steam Store english: https://store.steampowered.com/app/826600/I_am_not_a_Monster_Complete_Edition/
Steam API English: https://store.steampowered.com/api/appdetails?appids=826600

Russian Store Page: https://store.steampowered.com/app/826600/I_am_not_a_Monster_Complete_Edition/?l=russian
Steam API Russian: https://store.steampowered.com/api/appdetails?appids=826600&l=russian

Pulled Description: https://pastebin.com/98YiPhwW

According to the log, Playnite gets info from a cache, can that be the different for the currently live store version? Maybe it's pulling outdated info, because not even the images are the same in the store pages and what playnite is getting.

**Screenshots**
![Playnite DesktopApp_2019-10-02_00-28-59](https://user-images.githubusercontent.com/1389286/66020144-b5ac0180-e4ab-11e9-9219-be6be12b7296.png)
![Playnite DesktopApp_2019-10-02_00-29-14](https://user-images.githubusercontent.com/1389286/66020149-ba70b580-e4ab-11e9-802c-675c0bd9a048.jpg)
![Playnite DesktopApp_2019-10-02_00-29-21](https://user-images.githubusercontent.com/1389286/66020153-bd6ba600-e4ab-11e9-8ade-1c65bf27883c.jpg)

**edit:** there's something very weird with this game. The game has changed it's name, adding complete edition. I completely deleted the game from Playnite and added it again and it's still getting the old name. The only thing that is updating is the new cover image.

![Playnite DesktopApp_2019-10-02_01-42-44](https://user-images.githubusercontent.com/1389286/66023167-f6107d00-e4b5-11e9-900f-adedf396ff51.png)

diag.package: a5b06066-d3e0-49ac-9f46-85947373960f

**Comment by Exemplifire** [comment]
I have this issue with DOOM.

![Capture](https://user-images.githubusercontent.com/51807274/68055076-ddb29e80-fcbd-11e9-8e59-c03b5f402afc.PNG)

**Comment by Exemplifire** [comment]
At least as far as the Russian/Cyrillic text is concerned.

**Comment by darklinkpower** [comment]
![Playnite DesktopApp_2019-11-03_22-59-30](https://user-images.githubusercontent.com/1389286/68100440-adb9f580-fe8d-11e9-9c26-d5dc1ccf0c68.jpg)

Yeah I can confirm it happens with Doom too.

**Comment by JosefNemec** [comment]
Done in 6.1

**Comment by Korb** [comment]
@JosefNemec, same problem.

The interface language of store.steampowered.com is set to

- Primary Language: English
- Secondary languages: Russian

Playnite language: English

**Diagnostics ID**

Playnite 10.34
SDK: 6.11.0
Theme API: 2.6.0
Portable installation

`948b05f2-1131-4edb-bcb4-65907d5a93a1`

Microsoft Windows 10.0.19045.4957
