### ISSUE TITLE
Start minimized

### ISSUE THREAD

**Issue by XJIOP** [JosefNemec/Playnite#1482]
In version 5.8 after windows startup Playnite is minimized only in taskbar, previous versions was minimized to tray. Please add an option to settings for choise, minimize to taskbar and minimize to tray.

these are my current settings
![Аннотация 2019-10-03 160426](https://user-images.githubusercontent.com/1385503/66133756-81ddf280-e5f7-11e9-8af0-f2b80d6ca548.png)

**Comment by JosefNemec** [comment]
You have to enable "Minimize to tray" option. That's how it always worked, even prior to Playnite 5.

**Comment by JosefNemec** [comment]
I can't reproduce it. If I enable `Start Minimized` and `Minimize to tray` options then Playnite starts properly minimized in tray. Also there was no change to this functionality since Playnite 4, so I'm not sure why it doesn't work for you. Please make sure you have both of those options enabled.

**Comment by XJIOP** [comment]
I restarted pc right now
![Аннотация 2019-10-03 173810](https://user-images.githubusercontent.com/1385503/66141896-cb810a00-e604-11e9-8684-8bdae49a897c.png)

what could it be? it wasn’t before ... settings I showed in my first post.

**Comment by XJIOP** [comment]
Where is option Minimize to tray? I see only Start Mminized

**Comment by JosefNemec** [comment]
Appearance -> General

**Comment by XJIOP** [comment]
Sorry, now I have found and it has been disabled. Thanks!
