### ISSUE TITLE
Darken covers for uninstalled games in Grid/Fullscreen view.

### ISSUE THREAD

**Issue by rmccullagh99** [JosefNemec/Playnite#1484]
Hey, would just like to make a suggestion that if a game isn't installed locally, then when its cover shows up on grid view it could be lightly darkened so that it's immediately apparent what games are and aren't installed. Also changing the play button icon to a download icon would be nice to help with this.

**Comment by darklinkpower** [comment]
Nice idea. Related to this, I think it would be also great if currently hovered or selected game would increase brightness similar to what Galaxy 2.0 or the new Steam UI does

**Comment by PurpleAzurite** [comment]
I hope this is an optional feature. I would not like it myself. I like too look at my game covers without the darkening.

**Comment by JosefNemec** [comment]
Yes, there will be an option to toggle this behavior.

**Comment by JosefNemec** [comment]
Done in devel7 branch (future Playnite 7).
