### ISSUE TITLE
Improve layout of List View game details

### ISSUE THREAD

**Issue by bundito** [JosefNemec/Playnite#1485]
From a purely user interface perspective, there's a lot of wasted space on the list view's game details page. See the attached screenshot for what I mean. The current layout almost looks like something's missing at the top half of the screen.

I realize we don't want to over-clutter the screen, but I'd think this would be a nice update that would give Playnite some additional professional polish.

(If I could figure out the code, I'd try doing it myself...)

![playnite](https://user-images.githubusercontent.com/1828240/66350031-d945d080-e91f-11e9-898a-2316e6836275.png)

**Comment by darklinkpower** [comment]
I replied to you hours ago on discord. This is configurable in settings.

**Comment by JosefNemec** [comment]
The "wasted space" is there to show the artwork. As darklinkpower mentioned you can disable/adjust it via settings. Closing
