### ISSUE TITLE
support alternative controller

### ISSUE THREAD

**Issue by Kmoshiro** [JosefNemec/Playnite#1488]
**Check for existing issue**
I would like to provide support for alternative controls.

**Describe the solution you'd like**
there is a program called "x360ce" which manages to emulate the alternative controller as xbox 360 controller, but the program does not work with the playnite

![Captura](https://user-images.githubusercontent.com/56491484/66708546-50b49f00-ed28-11e9-8286-ffe14e5a5b0a.PNG)
![Uploading Captura.PNG…]()

sorry for my bad inglish

**Comment by darklinkpower** [comment]
I think Xbox360CE makes your controller use dinput and Playnite currenly only supports xinput controllers. This is a duplicate to #1113

You can try any software that translates dinput to xinput and see if it works, I found this with a quick google search https://github.com/csutorasa/XOutput

**Comment by JosefNemec** [comment]
You are showing Desktop mode on your screenshot, we don't support controller input on Desktop mode. Does it work in Fullscreen?

**Comment by Kmoshiro** [comment]
@JosefNemec 
doesn't work in any of the ways

**Comment by Kmoshiro** [comment]
@darklinkpower oh I hadn't noticed, I'll try

**Comment by JosefNemec** [comment]
Make sure that the controller is configured to works as XInput one, otherwise it wont work. Support for direct intput will be done in #684
