### ISSUE TITLE
Make use of the features provided by enhanced steam for game information

### ISSUE THREAD

**Issue by trillex** [JosefNemec/Playnite#149]
Making it possible to pull out information, like what Enhanced Steam (http://www.enhancedsteam.com/) does could provide a lot of interesting information on the game pages. 

Quickly seeing sales numbers, players currently playing, news feed from Steam could be glorious. :)

**Comment by JosefNemec** [comment]
Would be possible via #138, therefore I'm closing this a duplicate.
