### ISSUE TITLE
Sorting Name doesn't recongise numbers higher than 9. 10 will be sorted next to 1

### ISSUE THREAD

**Issue by jameskchapman-github** [JosefNemec/Playnite#1490]
**Check for existing issue**
Not to my knowledge 

**Describe the bug**
When entering a sorting name any digit past 9 is not registered as being greater than 9. e.g 10 will be next to 1 as it is reading it as 1, 0, not the numerical value Ten

**To Reproduce**
I was sorting Tomb Raider Games
>Edit>Sorting Name>'Tomb Raider 1'
Repeat with Tomb Raider 2, 3, 4, 5, 6, 7, 8, 9
The first in the reboot games is Tomb Raider 10 and this appears between Tomb Raider 1 and Tomb Raider 2.

![Capture](https://user-images.githubusercontent.com/53371449/66767648-cd6e8700-eea8-11e9-8884-2a943e53bb9f.PNG)

To temporarily fix this I have listed it as Tomb Raider 91

**Comment by JosefNemec** [comment]
This is called natural sorting and we don't support it at the moment, it will be implemented in #671. For now you have to use 01, 02 etc.
