### ISSUE TITLE
IndieGala Library Integration

### ISSUE THREAD

**Issue by doublah** [JosefNemec/Playnite#1492]
IndieGala has a growing number of available DRM-free games downloaded from the user's profile page, but they don't have an API for it, so probably have to parse the page at https://www.indiegala.com/profile for logged in users.

**Comment by leobenkel** [comment]
That would be awesome !

**Comment by shakeyourbunny** [comment]
Note that the downloads of these free games regularily vanish, the developers/publisher retain the download entry but you get empty zips or an error message.

This is not a Playnite problem but IndieGala itself.

**Comment by mfujita47** [comment]
A GOG Galaxy integration plugin for **IndieGala** has been released just recently.
- https://github.com/burnhamup/galaxy-integration-indiegala/

I have given the plugin a try and found it working well. It would be nice if someone could implement the similar function to **Playnite**.

**Comment by JosefNemec** [comment]
Done by a community member as extension https://playnite.link/forum/thread-344.html
