### ISSUE TITLE
'Pinned' or 'Home' Tabs that are user-customisable.

### ISSUE THREAD

**Issue by rmccullagh99** [JosefNemec/Playnite#1495]
Recently tried out GOG 2.0, and they've had a great idea where users can pin current pages to a main sidebar, for easy clicking between user-created presets such as certain filters, genres, or libraries. 
Would reccomend thinking about implementing this for Playnite, to allow for a really seamless use for users that add their own pins.

**Comment by darklinkpower** [comment]
duplicate to #590 but maybe throw your idea on how it should work in that issue.

**Comment by JosefNemec** [comment]
Closing as this is duplicate to #590
