### ISSUE TITLE
Search keyboard shortcut (Ctrl/Control+F) doesn't work

### ISSUE THREAD

**Issue by user00101010** [JosefNemec/Playnite#1498]
**Describe the bug**
"Control + F" doesn't activate the search box.

**To Reproduce and other details**
Pressing "Control + F" never works. This does not seem related to #701

**Comment by bluddy** [comment]
In addition, Ctrl+G also doesn't work (show/hide filters).

**Comment by JosefNemec** [comment]
Done in `devel7`.
