### ISSUE TITLE
Provide OnGameSelected event for scripting

### ISSUE THREAD

**Issue by lutewise** [JosefNemec/Playnite#1499]
Provide a new event (OnGameSelected/on_game_selected) that is triggered when the user selects one game on the list, passing a Game. 

In the case more than one game is selected, pass just the last one.

If possible, event processing should be asynchronous.

This could be used in various integrations as shown in the following use cases:

- Use case 1: Remote control Steam (or other game library) to change the page to the selected game's page.

- Use case 2: Remote control a browser for it to make some actions with the selected game (for example, to show Mobygames page).

- Use case 3: Play a video related to the selected game.

- Use case 4: Count clicks on each game, as an indirect indicator of interest.

**Comment by JosefNemec** [comment]
As far as sync vs async processing, I will be adding separate async handlers for all events. So in this case you will have OnGameSelected and OnGameSelectedAsync.

**Comment by lutewise** [comment]
> As far as sync vs async processing, I will be adding separate async handlers for all events. So in this case you will have OnGameSelected and OnGameSelectedAsync.

Better yet!!! Thanks!

**Comment by JosefNemec** [comment]
Done in `devel7` branch (future Playnite 7).
