### ISSUE TITLE
 Customising EGS store plugin launch options

### ISSUE THREAD

**Issue by Driek123** [JosefNemec/Playnite#1502]
Is it possible to import a bunch of games from my EGS library but choose to launch from the executable instead in bulk?

Main reason for this being that EGS' games (after downloading) can be run from the .exe without first launching the launcher (at least that seems to be the case for most games I've tried, although there's some exceptions like What Remains of Edith Finch - I'll come to this later). 

It's basically like GOG's with the .exe being drm-free. And I noticed GOG's store plugin has the option to not launch GOG Galaxy in it, but not EGS. So it felt like the functionality was already possibly there, but haven't been extended to other plugins. 

Since it's not possible to bulk edit all the games' play action from a particular library, I thought modifying the library plugin would be a possible solution to this. It's a lot more elegant compared to modifying the play action of each game & for every time a new one gets added (or whenever I need to reimport them for whatever reason when things go wrong...). 

It would be nice to extend this to the rest of the plugins as well, which is a more systemic change which probably isn't possible at this point. Stores that force the store launcher to start up with their exe will have it embedded in their exe (at least that's my understanding regarding steam), so there isn't really a need for playnite to first launch the store launcher then actually launch the game. It probably messes with some fundamental way in which playnite does its launching though. 

Extra: I posted this to the /r/playnite subreddit and got some more input which I'll list below. 

- Since the launcher isn't lauched, features like cloud saves wouldn't work. Adding a line below the checkbox when deselecting the launcher's launch could get around this issue of people complaining about their cloud saves later on. Already can be implemented under GOG's library setting's checkbox about not using the Galaxy Client, with the deselected state triggering a line like "Please note that launcher features like cloud saves would not work" or something 

- Edith. So what happens is that the game will crash if you try to launch it from the exe directly, then force the EGS launcher to launch before relaunching again. However, adding "-EpicPortal" to a shortcut targeting the exe allows the game to launch normally without causing the launcher to launch (for now). This seems to be the "Arguments" field in the Play Action section, so this workaround could probably be automated. 

- In general you can't just deselect "managed by library plugin" in bulk for a bunch of games. Perhaps if things can't be implemented within the plugin, probably implementing a way to bulk "disable library plugin management for play action" could be a solution. It'll automatically go straight to launching the exe anyway in that case and do what I intended anyway. 

This project has been incredibly promising so far, hope to see it improve more & more in the future.

**Comment by JosefNemec** [comment]
Duplicate to #1068 and #547
