### ISSUE TITLE
[API] Adding new game

### ISSUE THREAD

**Issue by By6r9** [JosefNemec/Playnite#1505]
**Describe the bug**
`ERROR:Unhandled exception occured.Microsoft.Scripting.ArgumentTypeException: expected str, got GameInfo`

**To Reproduce**

```
def addnewgame():
    new_game = GameInfo()
    new_game.Name = "New Game"
    PlayniteApi.Database.Games.Add(new_game)```

**Comment by JosefNemec** [comment]
I'm sorry, the documentation is wrong. You should be creating `Game` object, not `GameInfo`.

**Comment by By6r9** [comment]
That makes some sense.
djd4ws0n reported another bug/strange behavior, pasting so it doesn't get lost.    
"If I run the following in an extension, the BackgroundImage doesn't work. CoverImage downloads fine."
```
                    games.Add(new GameInfo()
                    {
                        Name = "Game Name",
                        BackgroundImage = @"url-to-bg",
                        CoverImage = @"url-to-cover",
                    });

**Comment by JosefNemec** [comment]
You need to add the game first, then add the file and then assign it to a game.
https://playnite.link/docs/tutorials/scripts/scriptingDatabase.html#changing-cover-image

I'll expose possibility of adding games via `GameInfo` in future (functionality is there, but it's not exposed).

**Comment by JosefNemec** [comment]
Done in `devel7`. Database API now has `ImportGame` method that accepts `GameInfo` object.
