### ISSUE TITLE
Custom Library Tags for "Playnite" Library

### ISSUE THREAD

**Issue by kpd328** [JosefNemec/Playnite#1506]
I was just thinking that there should be a simple box available in games not imported from a library provider, such as Windows Store Games or games that came from a disc, to mark them as part of a custom library (like marking Windows Store games as something like "Windows Store" or "Xbox Game Pass") so that when grouped by library games from say Xbox Game Pass are separate from games that I need to put in a disc for.

**Comment by JosefNemec** [comment]
There's already game field for that called `Source`.
