### ISSUE TITLE
Update Twitch logo

### ISSUE THREAD

**Issue by superusercode** [JosefNemec/Playnite#1507]
The current logo has been altered as part of their design refresh. Currently, we have this: 
![image](https://user-images.githubusercontent.com/23001825/67624067-5d41f880-f7fa-11e9-8762-ba61ec766966.png)

Now it looks like this: 
![image](https://user-images.githubusercontent.com/23001825/67624099-9b3f1c80-f7fa-11e9-9648-974ad4f535e0.png)

**Comment by darklinkpower** [comment]
Sent a pull request to update it in the `devel branch` in #1508

Old logo:
 ![twitchicon1](https://user-images.githubusercontent.com/1389286/67625178-19ea8880-f800-11e9-82cf-dd2ad562b156.png)

New logo: 
![twitchicon](https://user-images.githubusercontent.com/1389286/67625182-2838a480-f800-11e9-81fd-dfcf90e18ce0.png)

**Comment by JosefNemec** [comment]
Done in 6.0
