### ISSUE TITLE
Call of Duty Modern Warfare (2019) doesn't get imported from Battle.net

### ISSUE THREAD

**Issue by iSnackyCracky** [JosefNemec/Playnite#1509]
**Describe the bug**
After installing the new Call of Duty: Modern Warfare via the Blizzard Battle.net launcher, the Game does not get imported to Playnite. (I checked authentication, did a "scan and repair" in the Battle.net launcher but without any luck).

**To Reproduce**
Install Call of Duty: Modern Warfare in the Battle.net launcher, authenticate Battle.net in Playnite and hit F5 (or just refresh Battle.net)

**Screenshots**
![image](https://user-images.githubusercontent.com/20481463/67634494-0bae7200-f8bd-11e9-80b1-64d06421c220.png)

**Comment by JosefNemec** [comment]
Already implemented via a264733a64b29ca4e555bbe395b862e0a2f1e1bb. It will be released in next update.

**Comment by JosefNemec** [comment]
Done in 6.0
