### ISSUE TITLE
LaunchBox data import

### ISSUE THREAD

**Issue by By6r9** [JosefNemec/Playnite#151]
- import (or, preferably, link to) images, music, manuals from LaunchBox directory 
- import data from already made LaunchBox platform xml files. Example:

`<?xml version="1.0" standalone="yes"?>
<LaunchBox>
  <Game>
    <ApplicationPath>..\SNK Neo Geo Pocket\Neo Cherry Master - Real Casino Series (Japan, Europe) (En,Ja).ngp</ApplicationPath>
    <CommandLine />
    <Completed>false</Completed>
    <ConfigurationCommandLine />
    <ConfigurationPath />
    <DateAdded>2016-12-10T18:21:04.3606947+01:00</DateAdded>
    <DateModified>2016-12-10T18:21:04.3606947+01:00</DateModified>
    <Developer>DYNA</Developer>
    <DosBoxConfigurationPath />
    <Emulator>f0ef6559-789d-4832-aa24-a65c95e3bf38</Emulator>
    <Favorite>false</Favorite>
    <ID>fba6b693-bfc8-4b21-b10a-59bd0d326612</ID>
    <ManualPath />
    <MusicPath />
    <Notes>Neo Cherry Master (or Real Casino Series: Neo Cherry Master) is a fruit machine/"one-armed bandit" simulator. Simple - spin the reels and wait for luck - identical fruits in the row. Controls are simple: player push A button to spin the reels and the B button to increase "credits". No real gambling – player can't lose real money.</Notes>
    <Platform>SNK Neo Geo Pocket</Platform>
    <Publisher>SNK</Publisher>
    <ReleaseDate>1998-12-25T09:00:00+01:00</ReleaseDate>
    <RootFolder />
    <ScummVMAspectCorrection>false</ScummVMAspectCorrection>
    <ScummVMFullscreen>false</ScummVMFullscreen>
    <ScummVMGameDataFolderPath />
    <ScummVMGameType />
    <SortTitle />
    <Source />
    <StarRating>0</StarRating>
    <Status>Imported ROM</Status>
    <DatabaseID>27870</DatabaseID>
    <Title>Neo Cherry Master: Real Casino Series</Title>
    <UseDosBox>false</UseDosBox>
    <UseScummVM>false</UseScummVM>
    <Version />
    <Series />
    <PlayMode>Single Player</PlayMode>
    <Region>Europe, Japan</Region>
    <PlayCount>0</PlayCount>
    <Portable>false</Portable>
    <VideoPath />
    <Hide>false</Hide>
    <Broken>false</Broken>
    <Genre>Casino</Genre>
  </Game>
</LaunchBox>`

Hard part - additional roms versions (roms released in different countries but also second CD or floppy squashed into one entry) are stored in: 
`  <AdditionalApplication>
    <Id>a07fd9f3-bbf6-4d71-ba7d-b7be09036b8c</Id>
    <PlayCount>0</PlayCount>
    <GameID>fda8f1cc-e094-4260-bac6-60f2717780f5</GameID>
    <ApplicationPath>..\Sega Genesis\nointro\Fighting Masters (USA).md</ApplicationPath>
    <AutoRunAfter>false</AutoRunAfter>
    <AutoRunBefore>false</AutoRunBefore>
    <Name>Play (USA) Version...</Name>
    <UseDosBox>false</UseDosBox>
    <UseEmulator>true</UseEmulator>
    <WaitForExit>false</WaitForExit>
    <ReleaseDate>1992-08-17T09:00:00+02:00</ReleaseDate>
    <Developer>Almanic</Developer>
    <Publisher>Treco</Publisher>
    <Region>North America</Region>
    <Version>(USA)</Version>
    <Status>Imported ROM</Status>
    <EmulatorId>f0ef6559-789d-4832-aa24-a65c95e3bf38</EmulatorId>
    <SideA>false</SideA>
    <SideB>false</SideB>
    <Priority>1</Priority>
  </AdditionalApplication>`

**Comment by Tenome** [comment]
Bumping in case this wasn't implemented yet. I'm still deciding between Launchbox and Playnite, but I'm learning towards LB because of their database (their client itself is slower and clunkier on my computer).

**Comment by JosefNemec** [comment]
I don't think I'll be adding this as built-in feature into Playnite in near future. I think this is a prime example of something that could be done as an user extension (our SDK already supports everything needed for this to be implemented).

As far as LB database, @spektor56 is already working on metadata plugin that will fetch game info from there.

**Comment by spektor56** [comment]
Yes I'm working on LB and emumovies integration for metadata providers but it won't be done for a bit.  Been busy with Christmas stuff, house stuff, and taking care of a newborn.  Yes it's easy to do I just don't have much free time unfortunately

**Comment by JosefNemec** [comment]
I'm closing this, since I can't see myself implementing this due to niche nature of this feature. As I mentioned in my previous comment, this can be easily implemented as a 3rd party extension by a community member.
