### ISSUE TITLE
Update Libraries Option in Full Screen Mode

### ISSUE THREAD

**Issue by bverkron** [JosefNemec/Playnite#1511]
**Check for existing issue**
Searched for "refresh" under all issues (not just open). Could not find one matching this request. I also browsed through the menus to see if there was an auto-refresh interval or other option that would cover this one.

**Describe the solution you'd like**
Addition of a feature to refresh the game libraries from Full Screen mode.  Seemingly, at the moment, in order to refresh the libraries you need to manually switch to Desktop mode and run Update Game Library from the main menu.  This breaks the console-like experience if new games were added to one of the libraries and you want to be able to come to your Playnite UI later and have it available for install or play as it requires several manual steps with a mouse and keyboard.

**Screenshots**
N/A

**Comment by JosefNemec** [comment]
Done in devel7 branch (future Playnite 7).
