### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by Rastem88** [JosefNemec/Playnite#1513]
**Check for existing issue**
I did not see this issue reported elsewhere.
**Describe the bug**
Upon launching playnite I was told to update from a very old version(I think 4.74 according to the log file in appdata/roaming/) . After doing so I received an error message stating an "unrecoverable error occurred". I then closed and reopened the program a few times to the same result. I uninstalled playnite then reinstalled using the 5.8 installer and received the same result. My libraries appears to be loading in the background, but I am not allowed to interact with them due to the error message. 

**To Reproduce**
Crash on starting the program. 

**Diagnostics ID**
151a539a-647e-454e-be9b-aa087b5183d3

**Comment by JosefNemec** [comment]
For some reason it crashes when trying to initialize tray icon. For now you can disable tray manually by editing `%appdata%\playnite\config.json` file and changing `EnableTray` to `false`.

**Comment by Rastem88** [comment]
That appears to have solved the crashing. Thanks.

**Comment by JosefNemec** [comment]
Done in 6.0
