### ISSUE TITLE
Twitch import not working since the client redesign

### ISSUE THREAD

**Issue by rogersachan** [JosefNemec/Playnite#1517]
**Describe the bug**
The offline game importer opens the client but does not ask for authentication in any way. This has been occurring ever since they rolled out the redesign.

**To Reproduce**
Clean install twitch and playnite and then attempt to authenticate twitch when importing.

**Comment by JosefNemec** [comment]
I can't reproduce it. Please go to "About Playnite" menu and create diagnostics package, thanks.

**Comment by JosefNemec** [comment]
Closing since there's no response from reporter and I can't reproduce it myself.
