### ISSUE TITLE
Turn Off Game Background but still use it for Window Background?

### ISSUE THREAD

**Issue by Exemplifire** [JosefNemec/Playnite#1520]
I primarily use Grid View, but I find it easier to organize and modify in Details View.

In the previous Beta version of Playnite I had been using the Game Background and Window background must have been the same thing. But now when I use my custom backgrounds for how they look in Grid View, I get a double vision in Details View.

Here's my Grid view:

![Capture2](https://user-images.githubusercontent.com/51807274/68091436-36f90a00-fe45-11e9-9bc9-6a24d42e91b0.PNG)

I love it. It looks great. But here's the Details View:

![Capture](https://user-images.githubusercontent.com/51807274/68091446-598b2300-fe45-11e9-8ea3-9f14846cd66f.PNG)

I'm not sure what the best solution is for this. I don't want to blur the Window Background image because that's the one I'll see in Grid View.

So, would it be possible to toggle the Game Background image off in Details View and still see that background image as the Window Background image. Or possibly isolate the Background Blur to Details View only? To be honest I'd prefer for it be the Window Background in all cases, so turning off the use of that loaded background image for the Game Background in Details View would be my preferred solution.

**Comment by Exemplifire** [comment]
Maybe an option to select a different background for the Window and the Game? That way you can leave the Game background blank, if you want? Or even add another transparent image over the Window background/ Sorry, I'm a graphic designer.

**Comment by JosefNemec** [comment]
You can already disable it in Settings -> Appearance -> Details View, uncheck Background Image.

**Comment by Exemplifire** [comment]
Ah! Great! Thanks!

Separate images would be cool, though, likely not a priority.

Thanks for the instructions!
