### ISSUE TITLE
Fullscreen Mode - Change "Enter" key to go to "Details" Instead of Launching

### ISSUE THREAD

**Issue by BGrym** [JosefNemec/Playnite#1521]
Changing the enter key to open up game details rather than immediately launching the game would align it better with the "A" button on a controller.

This would be useful for situations where you need to bind a button to a key to use in fullscreen mode when an xinput option is not available, like with the steam controller. If bound to the "Enter" key now, you would have two buttons to directly launch the game, and none to go to a details view. If bound to the "A" button, it can't be used for the Filter control, or for search text entry.

It may also prevent erroneously launching the game.

**Comment by JosefNemec** [comment]
Will be done via #1344
