### ISSUE TITLE
Option for Xbox / Guide controller button to restore Fullscreen mode

### ISSUE THREAD

**Issue by JosefNemec** [JosefNemec/Playnite#1527]
Apparently Playnite sometimes doesn't restore itself properly after game exits in Fullscreen mode (which is definitely an issue in Playnite). Having option to press Guide button on controller could be used to restore Playnite in case such scenario occurs. I can also see this being usefully if user minimizes Playnite for some reason and wants a quick way to get back to it with controller.

**Comment by xCONFLiCTiONx** [comment]
Was going to make an issue but came across this one. I would love to see xbox controller support. The ability to go through the collection of games in the UI using the dpad or thumbstick and then the guide button to open it. You could also set it to open when you plug in your xbox controller.

The following is code I used in my lame attempt to make a game launcher that uses the Guide button on the xbox controller.

C#
[https://github.com/xCONFLiCTiONx/GHelper/blob/master/XBOX_GUIDE_BUTTON/GuideButton.cs](https://github.com/xCONFLiCTiONx/GHelper/blob/master/XBOX_GUIDE_BUTTON/GuideButton.cs)

**Comment by Bluscream** [comment]
That would be nice indeed

**Comment by WilliamLeGod** [comment]
Any1 updates on this?

**Comment by JosefNemec** [comment]
It's planned for Playnite 10 (you can check what milestone it's assigned to).

**Comment by JosefNemec** [comment]
Done in devel.

**Comment by Newer1107** [comment]
Hello, is this feature implemented yet?

**Comment by JosefNemec** [comment]
yes

**Comment by Newer1107** [comment]
Hello Josef, I was looking for a feature that brings on the full screen mode upon pressing the xbox button and I'm afraid I've opened the wrong thread.

**Comment by JosefNemec** [comment]
This specific issues was about refocusing Playnite while it's already running. Playnite obviously can't launch itself when you press controller button if Playnite is not already running. For that you need to use some other app that will run Playnite exe on button press.
