### ISSUE TITLE
Install button do not work for game manually created

### ISSUE THREAD

**Issue by Neothom2404** [JosefNemec/Playnite#1531]
Hi, 

I have some softwares not installed, I created them manually with filled Directory and Path
![image](https://user-images.githubusercontent.com/57912044/69074913-3b6a1900-0a28-11ea-9677-e5548b98ee06.png)

It seem I can't click on Install button and when I try, it is not doing anything
![image](https://user-images.githubusercontent.com/57912044/69075011-6fddd500-0a28-11ea-98a7-c78f5b9054a1.png)

I did not found anything about this, any Idea?

**Comment by JosefNemec** [comment]
Duplicate to #478
