### ISSUE TITLE
Option to pull metadata (i.e. covers/genres.) from the Twitch database/directory

### ISSUE THREAD

**Issue by rogersachan** [JosefNemec/Playnite#1533]
https://www.twitch.tv/directory/ 

As of right now, publishers are still required to directly contact Twitch and update info through Giantbomb to update cover art (rather than into IGDB - although this will hopefully be the case soon). There are also some old games that have a higher quality cover on Twitch than IGDB sometimes.

**Comment by rogersachan** [comment]
I should also note that twitch has begun to store genre info, which might be useful for filling gaps in some situations.

**Comment by JosefNemec** [comment]
Twitch recently bought IGDB and they will start using theirs data so it doesn't make sense to add support for Twitch since we already support IGDB.
