### ISSUE TITLE
Option to pull metadata (i.e. covers/descriptions) from the youtube database/directory

### ISSUE THREAD

**Issue by ghost** [JosefNemec/Playnite#1534]
i.e. https://www.youtube.com/channel/UCAzEd39C-UI5ynpeAJtM4JQ

Youtube somehow manages covers without watermarks for old games - to an extent larger than Twitch does. It's not clear where they get the covers from since open source games have covers that developers have no idea originated from (i.e. Rigs of Rods). To find a way to grab these covers programmatically would be a boon to my workflow rather than collecting these covers one by one.

**Comment by rogersachan** [comment]
I should note that youtube also has descriptions for games, but they extract these from wikipedia.

**Comment by rogersachan** [comment]
`https://yt3.ggpht.com/SOQFGMNgg07Yun2Z9Sjop4yubIIy092CKPxVjofyFeEm-BNr1nGXKrrkmN2VwaOFdGrIaN2jIA=w600-h800-nd` when you right click the image from the game page the url needs to be edited so you get the full resolution - simply removing the size tag gives you the smallest version of the image.

**Comment by JosefNemec** [comment]
I'm closing this because I don't have resources to support another built-in metadata source. This can be implemented as a user plugin if anybody wants to take a stab at it.
