### ISSUE TITLE
Missing some installed games from Uplay

### ISSUE THREAD

**Issue by trockenasche** [JosefNemec/Playnite#1538]
**Describe the bug**
I just installed Playnite 6.2 and check the new Uplay integration, now I can see also uninstalled games from Uplay, except two installed.

I can remember that I bought South Park via Steam but I still need Uplay for it and it got added via Steam to Uplay. Maybe the same happened with Anno.

**Screenshots**
![Uplay-Playnite](https://user-images.githubusercontent.com/2905450/69459947-32a07c80-0d73-11ea-9481-b34e8b987cbb.png)
![Uplay-Uplay](https://user-images.githubusercontent.com/2905450/69459960-38965d80-0d73-11ea-9898-39f8c4808533.png)

I added my configuration file from Uplay.
[configurations](https://github.com/JosefNemec/Playnite/files/3881423/configurations.txt)

Diagnostic Id is `206303e8-d5f1-46c9-833b-1f7cf4af49e0`

**Comment by JosefNemec** [comment]
Uplay games bought from other stores are ignored during import to prevent duplicates. Also starting the game from Uplay launches it via Steam, so it really doesn't make sense to import them as part of your Uplay library.
