### ISSUE TITLE
Sort games alphabetically while ignoring "The" at the start of titles.

### ISSUE THREAD

**Issue by MEGAtheguy** [JosefNemec/Playnite#154]
As the subject title says, really. The Binding of Isaac and other games with "The" preceding the rest of the title sorts alphabetically with other games that start with T. I would like it if, for example again, The Binding of Isaac sorted with game titles starting with B

**Comment by JosefNemec** [comment]
Will be possible once #84 is done.

**Comment by JosefNemec** [comment]
Released in 3.4
