### ISSUE TITLE
Reset scrolling when switching to another game (Details view)

### ISSUE THREAD

**Issue by ClearStrelok** [JosefNemec/Playnite#1545]
When the user scrolls down the description of a game in Details view, the scrolling position is kept and the next selected game will be scrolled down as far as possible, provided that its description is also long enough to have scrolling enabled.

Since most users want to see the essential informations right away when selecting a game, I think it would be preferable to have the scrolling position reset to the top of the page everytime a new game is selected.

If the behavior is changed, it should also apply to the description box in Grid View.

**Comment by JosefNemec** [comment]
Fixed in devel by 46a403af6adb30ae6722c63dc281f2334da782d4
