### ISSUE TITLE
Option to disable background cover transition animation when using blur

### ISSUE THREAD

**Issue by darklinkpower** [JosefNemec/Playnite#1546]
**Describe the solution you'd like**
Using blur in some intel gpus results in noticeable lag/slowdown during the transition animation. Adding an option to disable the animation could mitigate this.

**Screenshots**
Video example of slowdown: https://cdn.discordapp.com/attachments/365863064010227723/647758111570001942/2019-11-23_05-16-08.mp4

**Comment by JosefNemec** [comment]
Done in 6.3
