### ISSUE TITLE
Random Game picker: Make "Limit selection to current filter" default and perhaps make it configurable

### ISSUE THREAD

**Issue by darklinkpower** [JosefNemec/Playnite#1548]
**Describe the solution you'd like**
It makes more sense to me to limit to current applied filters since that's basically what you are wanting to play and it's weird to me that it's selecting games that are not even currently installed by default. Another option is to make the default criteria configurable, with installed, limit to filters, etc. as options to modify.

**Comment by JosefNemec** [comment]
I think it makes sense to have that option enabled by default.

**Comment by JosefNemec** [comment]
Done in 6.3
