### ISSUE TITLE
Empty Steam library gives an error on start-up

### ISSUE THREAD

**Issue by VinzNL** [JosefNemec/Playnite#155]
When you have multiple Steam libraries and one of them is empty you get the following error on start-up:

`Failed to import installed Steam games: Could not find a part of the path 'Z:\games\SteamLibrary\steamapps'.`

The Z: drive is a mounted samba share from a Linux fileserver in this case, not sure if that matters. After I close the error Playnite works just as expected, it got all my games from the other Steam libraries.

**Comment by JosefNemec** [comment]
Released in 2.4
