### ISSUE TITLE
Change term "Scripts" to "Global Scripts" in the main settings window.

### ISSUE THREAD

**Issue by darklinkpower** [JosefNemec/Playnite#1550]
**Describe the solution you'd like**
`Global Scripts` makes more sense to be more clear that the scripts written in here will apply to every game.

**Screenshots**
Proposed change:
![imagen](https://user-images.githubusercontent.com/1389286/69488178-78208080-0e2b-11ea-81ac-1430bef409f5.png)

**Comment by JosefNemec** [comment]
I would rather add some description to the settings view then change this string, I'll do it for 6.3.
