### ISSUE TITLE
Settings: "[UNUSED]"

### ISSUE THREAD

**Issue by RiseT** [JosefNemec/Playnite#1553]
**Describe the bug**
See attached screenshot. Is it intended that "[UNUSED]" is being displayed? If it is, there seems to be no string for translation on Crowdin.

**To Reproduce**
Using v6.2, just open the settings.

**Screenshots**
![Playnite_issue](https://user-images.githubusercontent.com/12624674/69495253-36441880-0ec5-11ea-9ef4-103f1f8c44f2.PNG)

**Diagnostics ID**
n/a

**Comment by JosefNemec** [comment]
That's a bug in the localization file, it has to be changed on Crowdin. It's a `LOCScripts` string, I can see it on Crowdin just fine, you should be able to translate it properly.

**Comment by RiseT** [comment]
Ah, I see. Hard to search for something if you don't know what you're searching for.

Just one other question:

For the notification
"Failed to import games from Epic. User is not authenticated.",

i can find the first part on Crowdin (key: LOCLibraryImportError), but for the life of me, I cannot find the second one ("User is not authenticated.") via Crowdin's search function - neither in English nor in its current German translation (interestingly, there IS a current German translation in the app itself).

Could you help me out here?

**Comment by JosefNemec** [comment]
"User is not authenticated" is not translatable, it's an exception string from Epic plugin itself. I'll make it translatable in future.

**Comment by RiseT** [comment]
Thanks. That's interesting. A couple of Playnite restarts (because of switching languages), a translation for that string had been displayed (I'm 100% sure, as I've searched for it on Crowdin), but now it's in English.
Perhaps that translation came from the Epic plugin? Strange that is has changed know.
