### ISSUE TITLE
Remember the size of the Playnite window

### ISSUE THREAD

**Issue by unrealed** [JosefNemec/Playnite#1554]
It would be really useful if Playnite could remember the size of its window. It always goes back to being too narrow, cropping the images in the game's description. This could be a Windows issue on my end or something, but if not it would be a nice addition

**Comment by JosefNemec** [comment]
This is already implement and working according to my tests. Must be some issue on your side.

**Comment by darklinkpower** [comment]
It's saving the position and window size to me too between restarts with no issues.

**Comment by Stuntaneous** [comment]
This pairs well with the forgotten #976

**Comment by JosefNemec** [comment]
I have made some fixes to position saving in Playnite 7. If you still have some issues with this, then please open new issue. Thanks
