### ISSUE TITLE
[pedantic] Wording of adding games manually and scanning automatically

### ISSUE THREAD

**Issue by Stuntaneous** [JosefNemec/Playnite#1558]
**Describe the issue**
I manually add all of my games. I find it's best done by 'scanning automatically' as opposed to adding 'manually'. This was very counterintuitive as a new user to the application. After adding games this way, I then right click on their name and edit their details. 'Scanning automatically' ends up being a very manual task.

**Suggestion for remedy**
Clearer language regarding these two options.

**Comment by JosefNemec** [comment]
The actual process of import the game and finding executable is still being automated. We already have a menu for adding games "manually". I think that having two different ways of adding game "manually" would be confusing.
