### ISSUE TITLE
Selecting executables via scan automatically's browse option inconveniently outputs unchecked results

### ISSUE THREAD

**Issue by Stuntaneous** [JosefNemec/Playnite#1559]
**Describe the solution you'd like**
As it was in the past, I'd much prefer if games selected via 'scan automatically' > 'browse' were checked by default. Being unchecked slows down the process unnecessarily.

**Comment by JosefNemec** [comment]
I don't agree. Lets say we detect 100 executables there, but you want to import only 2. Now you have to uncheck all of those.

This will be solved by #768, which should add "select/unselect all" options to all selectable lists in Playnite.
