### ISSUE TITLE
Custom/Multiple Steam File Path(s)

### ISSUE THREAD

**Issue by WiFilter** [JosefNemec/Playnite#156]
I have an error occurring where Playnite says my Steam directory is somewhere where it isn't.

![image](https://user-images.githubusercontent.com/5510718/31322748-ec0f8b8e-ace0-11e7-9ce0-a56abe12e364.png)

I would like to be able to set a custom file path and multiple files paths to automatically scan at startup.

**Comment by JosefNemec** [comment]
Playnite automatically detects Steam library paths and it seems that Steam left this one in its configuration files for some reason. I will make it so these nonexistent paths are ignored.

**Comment by JosefNemec** [comment]
Released in 2.4

**Comment by Halolink109** [comment]
Is there anyway to make a custom path? I'm still getting this same error

**Comment by JosefNemec** [comment]
I'm not sure what you mean by "custom path", but can you please go to "About Playnite..." and create diagnostics package for me? Thanks

**Comment by Halolink109** [comment]
[playnitediag.zip](https://github.com/JosefNemec/Playnite/files/1385318/playnitediag.zip)

I'm getting the same error as he was, I wanted to know if there was a way to tell the program where the install locations of my steam games are, instead of it doing it automatically.

**Comment by JosefNemec** [comment]
For some reason Playnite thinks that you have Steam installed in this folder `C:\Games\Middle-Earth - Shadow of War\x64\Steam\`, which doesn't seem right. You may need to reinstall Steam to fix this issue. The value is taken from registry key created by Steam itself, so something had to "corrupt" that value.

**Comment by WiFilter** [comment]
Custom path refers to being able to manually locate where the Steam directory is located.
