### ISSUE TITLE
Updating from Playnite 5 to 6 re-enabled extensions that were previously disabled

### ISSUE THREAD

**Issue by Stuntaneous** [JosefNemec/Playnite#1561]
**Describe the bug**
Title.

Would be good to at least have a warning in the update dialog.

**Comment by JosefNemec** [comment]
Please create diagnostics package from "About Playnite" menu. There was no change to extension handling and they should stay disabled.

**Comment by JosefNemec** [comment]
Closing, no response in 24 days.
