### ISSUE TITLE
Crash during first time configuration wizard

### ISSUE THREAD

**Issue by spektor56** [JosefNemec/Playnite#1564]
**Describe the bug**

Went through the wizard, when i got to the screen where i can check to open the emulator config wizard and finish i instead clicked back, was sent to a blank "Settings..." page.  Clicked next and then playnite crashed.

**Diagnostics ID**
If this is a crash report please include string ID you receive after using "Create diag. package` on crash dialog.

4ab173f4-1f9e-4082-aa85-79268ff74eb2

**Comment by JosefNemec** [comment]
Fixed in 6.4
