### ISSUE TITLE
Covers become blurry when scrolling in Grid view (6.3)

### ISSUE THREAD

**Issue by ClearStrelok** [JosefNemec/Playnite#1567]
The issue is of a similar fashion to the one that's been fixed in #1539, except for the fact that the bluriness occurs on the vertical level and is unaffected by the zoom level. Instead, scrolling a list at specific parts will bring the issue: 

![2](https://user-images.githubusercontent.com/38838369/69765065-c65aba00-1172-11ea-947a-5509cd0bf0d8.png)

And the next scrolling will make it disappear:

![1](https://user-images.githubusercontent.com/38838369/69765116-f99d4900-1172-11ea-97f1-02133a9224fd.png)

**Comment by JosefNemec** [comment]
The image gets shifted by 1px as it did in that previous issue, just in different direction. I'm not really sure why is it happening.

**Comment by JosefNemec** [comment]
Closing, this is basically duplicate to #1539
