### ISSUE TITLE
Can't import Epic library

### ISSUE THREAD

**Issue by leftos** [JosefNemec/Playnite#1568]
Playnite 6.3, fresh installation. Epic import fails with "Object reference not set to an instance of an object" error.

Diagnostic package generated: c94001a7-41eb-42c8-aa53-084cc573821e

**Comment by JosefNemec** [comment]
Can you try reinstalling Epic client? It looks like the installation may be damaged somehow, according to logs.

**Comment by leftos** [comment]
That appears to have fixed whatever the issue was. Thank you.
