### ISSUE TITLE
Playnite 6.3 doesn't import playtime from GOG

### ISSUE THREAD

**Issue by qquq** [JosefNemec/Playnite#1570]
I've tried re-connect platform several times, but playtime from GOG never imports, although this function is listed in the feature table. See screenshots.

![image](https://user-images.githubusercontent.com/33117021/69861788-5eeb5a00-1299-11ea-91f5-d908743491a8.png)
![image](https://user-images.githubusercontent.com/33117021/69861950-b8538900-1299-11ea-84fd-4dcd4f0a4251.png)
![image](https://user-images.githubusercontent.com/33117021/69861965-bbe71000-1299-11ea-9b81-38f09124da45.png)
![image](https://user-images.githubusercontent.com/33117021/69861981-c2758780-1299-11ea-95fa-1a7380d46d0b.png)

**Comment by JosefNemec** [comment]
This is no longer supported for GOG, I just forgot to update feature table. Sorry about that
