### ISSUE TITLE
The Sims 4 Digital Deluxe can not be launched

### ISSUE THREAD

**Issue by NoZomIBK** [JosefNemec/Playnite#1571]
When I try to start The Sims 4 Digital Deluxe via Playnite i get an error message "cannot start game: Der Angegebenen Datei ist keine Anwendung zugeordnet" (playnite is set to english, but gives german error message. translated would be something like "The file is not linked to any application"

I can start other games of Origin
Origin is connected and authenticated
Game is automatically added
i can launche the game via Origin
no other game is running
there is no difference whether i have origin open or closed

**Diagnostics ID**
ab68bf57-867a-4adf-983c-78ab6c5d5894

**Comment by JosefNemec** [comment]
If you edit the game, go to "Actions" tab and uncheck "Managed by library plugin", what is set in `Path` and `Working Directory` fields?

**Comment by NoZomIBK** [comment]
Path: `ClientFullBuild0.package` (which seems wrong)
Working Directory: `{InstallDir}`

When i change the Path to `D:\Games\Origin\The Sims 4\Game\Bin\TS4_x64.exe` it works, so one workaround for this problem for now

**Comment by JosefNemec** [comment]
Fixed in 6.4
