### ISSUE TITLE
Generic plugins have no settings in the menu

### ISSUE THREAD

**Issue by MatDaniel** [JosefNemec/Playnite#1573]
**Description**
Generic plugins have no settings in the menu, instead another plugin gets additional settings in the menu.

**How To Reproduce**
Simply create a generic plugin. It doesn't even have to override the GetSettings() and GetSettingsView() methods.

**Screenshots**
![image](https://user-images.githubusercontent.com/29778928/69901346-9d0f7900-1380-11ea-9cf2-208c75ddad60.PNG)

**Comment by MatDaniel** [comment]
![Unbenannt](https://user-images.githubusercontent.com/29778928/69915053-0a87dc00-144b-11ea-9c6d-5647dd1ccfcd.PNG)

Thank You.

**Comment by JosefNemec** [comment]
Fixed in 6.4
