### ISSUE TITLE
Group by Name (Letter)

### ISSUE THREAD

**Issue by heidefinnsichen** [JosefNemec/Playnite#1575]
I think it would be great if there was an option to group your library by Name (actually by Letter).
Currently I am using the Category function to do this:

![Anmerkung 2019-12-03 190634](https://user-images.githubusercontent.com/58484745/70078217-942dda00-1602-11ea-88e7-93e7bad65727.png)

**Comment by JosefNemec** [comment]
Great idea! This seems so obvious that I have no idea why I didn't implement this in first version :)

**Comment by JosefNemec** [comment]
Done in `devel8`.
