### ISSUE TITLE
Detection game instal

### ISSUE THREAD

**Issue by Kaouran** [JosefNemec/Playnite#1576]
Overwatch is instal but no in list, detect in no instal .

but Starcraft is detect

![Overwatch no detect 2](https://user-images.githubusercontent.com/58531220/70179229-f3ace800-16dd-11ea-93ed-71c0bd74c6cf.PNG)
![Overwatch no detect](https://user-images.githubusercontent.com/58531220/70179230-f4457e80-16dd-11ea-94a7-05ef72b8583d.PNG)

**Comment by JosefNemec** [comment]
See [this page](https://github.com/JosefNemec/Playnite/wiki/Battlenet-troubleshooting#games-not-reported-as-installed) and let me know if it fixes the issue for you.

**Comment by JosefNemec** [comment]
Closing because of no response.
