### ISSUE TITLE
Description format wrong for EGS games.

### ISSUE THREAD

**Issue by darklinkpower** [JosefNemec/Playnite#1578]
**Describe the bug**
Descriptions are not properly formatted to a format that Playnite could display correctly.
This is the game that is shown in the screenshot: [Jotun Valhalla Edition](https://www.epicgames.com/store/en-US/product/jotun/home)

**Screenshots**
![imagen](https://user-images.githubusercontent.com/1389286/70278423-dd546a00-1779-11ea-94ee-25888aa51f29.png)

![imagen](https://user-images.githubusercontent.com/1389286/70278387-c7df4000-1779-11ea-82e8-b4f870eb599f.png) (Also, for some reason the text gets cut horizontally in the last line)

**Comment by JosefNemec** [comment]
Done in `devel8`.
