### ISSUE TITLE
Controller buttons too sensitive

### ISSUE THREAD

**Issue by Michoko92** [JosefNemec/Playnite#1579]
Hi,

Thank you for Playnite, this is very nice software! I just have one issue though: I use it in full screen mode, with an Xbox 360 controller, and the buttons sensitivity is too high. If you keep a button pressed for too long, several actions are triggered.
For example, if I press the A button on a game, sometimes it will just open the game details, and other times it will open the game details AND launch the game. Another example: if I press SELECT, it brings up the right menu, but if I press it for a half second too long, the right menu shows up and disappears immediately. It is pretty annoying, and you just have to tap the buttons quickly to avoid this behavior.
Could you just make sure that once a button is pressed, it has to be released first before sending another "pressed" signal, to avoid buttons repeating?
Thank you!

**Comment by JosefNemec** [comment]
Done in `devel`.

**Comment by Michoko92** [comment]
I tested the latest version (7.2), and despite the changelog, I still see the issue. Way to reproduce:
- launch the fullscreen mode
- hold the "SELECT" button on the gamepad, for example
- the menu will keep opening and closing as long as the button is pressed

Same thing for all controller buttons. Normally, pressing a button should trigger an action once, then we should have to release the same button and press it again to trigger the action again. Here the action is repeated many times while the button is kept pressed, which leads to many unwanted effects.

**Comment by JosefNemec** [comment]
I can't reproduce it with 7.2 (I can with 6.5). This might be a controller issue, I'm using original Xbox 360 controller.

**Comment by Michoko92** [comment]
OK I think I found the issue: it happens when several controllers are connected at the same time.

First, I could see the repeating buttons issue when using Nvidia Gamestream (which by default, always adds at least one additional controller, the Nvidia Shield one, when the session starts). Then when using my Xbox 360 wireless Controller while gamestreaming, the repeating buttons issue happened.

So basically:
- If I connect only one Xbox 360 controller to my PC, the buttons presses don't repeat, as expected.
- If I gamesteam with both 1 Xbox 360 controller and 1 Nvidia Shield controller, the buttons keep being repeated
- If I DON'T gamestream, but I connect 2 wireless Xbox 360 wirelss controllers, the buttons repeat too.

So it is clear now that the issue comes from the fact that several controllers are connected at the same time. I hope it helps. :)

**Comment by JosefNemec** [comment]
Done in `devel`.
