### ISSUE TITLE
Import GOG games by the start menu shortcut to enable Galaxy features

### ISSUE THREAD

**Issue by billybruiser** [JosefNemec/Playnite#158]
If the games are launched by the start menu shortcut that is created when they are installed by Galaxy, then you will have the cloud saving, time tracking, achievements, and other client features.  If the game is just launched via the exe, then you will have no client features.  For example, this is the target of the shortcut for my installation of Age of Decadence.  

"C:\Program Files (x86)\GOG Galaxy\GalaxyClient.exe" /command=runGame /gameId=1440152251 /path="D:\GOG Games\The Age of Decadence"

**Comment by JosefNemec** [comment]
There's already option for that in settings, under GOG section called "Start games via Galaxy client".

**Comment by billybruiser** [comment]
It does not appear to be working correctly then.  When I have that option checked, it starts Galaxy and loads the screen for that game, and then I have to click the Play button within Galaxy for it to start.

What I'm talking about would load the game immediately through Galaxy without having to press the Play button within Galaxy.  It's a much smoother way of starting.  

I tried messing around with the shortcut paths within Playnite to get it to function the way I'm talking about, but couldn't figure it out.  I can tell you what Launchbox does is just load that Start Menu shortcut, which has the correct arguments. When I start it in Launchbox, it starts via Galaxy automatically.   

For example, this is what the path within Launchbox looks like that it uses to launch the game.
..\..\ProgramData\Microsoft\Windows\Start Menu\Programs\Baseball Stars 2 [GOG.com]\Baseball Stars 2.lnk

And this is what that shortcut link has as it's loading properties.
Target "C:\Program Files (x86)\GOG Galaxy\GalaxyClient.exe" /command=runGame /gameId=2020914910 /path="D:\Games\GOG Games\Baseball Stars 2"
Start in "C:\Program Files (x86)\GOG Galaxy"

And this is what Playnite uses to launch the game.
Path  D:/Games/GOG Games/Baseball Stars 2\bstars2.exe
Working Directory  D:/Games/GOG Games/Baseball Stars 2

So the way Playnite responds if I don't have the option to launch through Galaxy checked is it simply loads the game straight away.  If I do have that option checked, it loads Galaxy and goes to the game's page, but then waits for me to click play.

**Comment by JosefNemec** [comment]
Problem is that Playnite uses `/command=launch` instead of `/command=runGame`, thanks for pointing out correct parameter. Fix will be in next version.

**Comment by JosefNemec** [comment]
Released in 2.4
