### ISSUE TITLE
Support for new steam game logos and background assets

### ISSUE THREAD

**Issue by darklinkpower** [JosefNemec/Playnite#1583]
**Describe the solution you'd like**
Support for new covers was added in #1455 but the new logos and background remain to be added. The Logos would require a new media asset to be added to Playnite.

**The URLs are:**

Game Page Background: `https://steamcdn-a.akamaihd.net/steam/apps/APP_ID/library_hero.jpg`

Game Logo (transparent): `https://steamcdn-a.akamaihd.net/steam/apps/APP_ID/logo.png
`

The new assets would be a great addition considering they are higher res and there is already a theme based on the new Steam UI that would benefit from this: https://playnite.link/forum/thread-58-post-130.html

**Comment by JosefNemec** [comment]
Done in Playnite 7
