### ISSUE TITLE
Sorting by name doesn't behave properly when using numbers

### ISSUE THREAD

**Issue by ClearStrelok** [JosefNemec/Playnite#1585]
See screenshot: 

![Sorting](https://user-images.githubusercontent.com/38838369/70526263-810e9300-1b49-11ea-8de9-ecf19081dc56.jpg)

1.5 and 2 respectively seem to be recognised as 15 and 20 when it comes to sorting. This may be problematic when trying to sort series with several entries and extensions in proper order of release.

**Comment by JosefNemec** [comment]
Same issue as #671
