### ISSUE TITLE
Text brush loaded with StaticResource instead of DynamicResource

### ISSUE THREAD

**Issue by Bigfootmech** [JosefNemec/Playnite#1586]
I found that in the themes, some of the files Have StaticResource declared for the text brush, instead of DynamicResource

Best case scenario: User has to change the variable type to Dynamic when changing brush name (but there's nothing to indicate this easily for someone just starting)
Worst case scenaro: User's brush colour isn't applied if there is a pre-existing static brush?

Classic: 
DerivedStyles\DetailsViewItemStyle.xaml(24):
DerivedStyles\DetailsViewItemStyle.xaml(27):

Default:
DerivedStyles\DetailsViewItemStyle.xaml(23):
DerivedStyles\DetailsViewItemStyle.xaml(26): 
<potentially also line 34 in the generated one, but not sure>
Views\DetailsViewGameOverview.xaml(53):
Views\GridViewGameOverview.xaml(64):
Views\MainPanel.xaml(44):

Steps to reproduce:
Create a new theme (either with Toolbox, or by copypasting an existing theme)
Make sure that one of these files esists
Rename TextBrush in the target file, 
Either add a brush in Constants file with the same name, or rename TextBrush in the whole project

Result:
Theme fails to load with no explanation

(I managed to resolve it by going to "about playnite" ->  Create diag. package -> it failed to upload -> I could look at the log file -> fiddling with the rest)

Attached files:
I've attached a zip with the diag. package, and a sample theme where this happens

[combo.zip](https://github.com/JosefNemec/Playnite/files/3951687/combo.zip)

**Comment by JosefNemec** [comment]
Done in `devel`.

I changed those references to dynamic. I also may have found a way how to load those static references, but it would require changes to the theme load mechanism and I'm not sure it's safe.

I will probably implement it after some more indepth testing in later versions.
