### ISSUE TITLE
Support for games with multiple discs

### ISSUE THREAD

**Issue by jk1984** [JosefNemec/Playnite#159]
For emulation of PSX and Gamecube games, the iso's I have are split, it would be great if I could group them together, so rather than have 7 separate files of 1 particular game, it would be 1 listing.

Besides that, Playnite is fantastic, really great work.

**Comment by JosefNemec** [comment]
Linking #653 to this, we might need to do those together.

**Comment by MAC293** [comment]
FFVII has 3 discs and is repeated 3 times. How can I link those 3 to a 1 cover of the game?.

**Comment by JosefNemec** [comment]
You can't currently, that's what this issue is about, add support for it.

**Comment by MAC293** [comment]
> 
> 
> You can't currently, that's what this issue is about, add support for it.

I know. I only gave another description of the issue. Thank you.

**Comment by git-steve-git** [comment]
This may not work for all emulators, but for Dolphin (GC) I was able to make multi-disc games show as one entry by setting up a playlist file (.m3u) for the game, and telling Playnite that m3u was a recognized extension.  The same should work for other emulators as long as they support .m3u

(The m3u won't appear in Dolphin itself, but the program still understands how to run them when you pass the playlist file in by command line.)

For those who may not know, an m3u is just a text file with a different extension, and each line in the text file is the path to a disc for the game:
c:\path\to\game (disc 1).iso
c:\path\to\game (disc 2).iso
etc.

**Comment by zurdwango** [comment]
.m3u works for PSX as well. I can speak from personal experience.
Really, you can just add the .m3u file as the file that gets loaded by Playnite and discs will automatically be loaded for any multi-disc game (correct me if I am wrong).

**Comment by DennoCoil** [comment]
m3u files are very dependent on the emulators involved.  Stand alone emulators might not have it, but Retroarch with the appropriate cores do.  It's hit or miss and you really need to see which ones work.

**Comment by GinoMan** [comment]
The most popular PSX emulators support the pbp filetype. There's a tool that will convert a multi-disk game into a single pbp game. 

There's a full guide at this link: https://www.reddit.com/r/miniSNESmods/comments/7nx6z3/guide_how_to_convert_psx_multiple_discs_game_in/

**Comment by JosefNemec** [comment]
Done in devel9.

**Comment by JazzJohannes** [comment]
I request to re-open, since it does in fact not work for Commodore Amiga at all, no matter which filename configuration is used.
