### ISSUE TITLE
Themes not installing

### ISSUE THREAD

**Issue by Nilot352** [JosefNemec/Playnite#1591]
Dragging the .pthm file over playnite desktop main window is not possible at this moment.

**Comment by JosefNemec** [comment]
I can't reproduce it, it works for me. What specifically happens when you drop the file?

Also if you are running Playnite as admin then you won't be to drop files to it unless the source of drag operation is from application also running as admin (it's a Windows security feature).

**Comment by JosefNemec** [comment]
Closing because of no response.
