### ISSUE TITLE
Alternative name for easier searching

### ISSUE THREAD

**Issue by CorvoJavidan** [JosefNemec/Playnite#1592]
Would be nice to have an alternative name entry option so the user can choose which way to search for.

In the game detail page they can add acronyms such as eso/wow/kotor to search for that instead of elder scrolls online/world of warcraft/knights of the old republic. Or ignoring punctuation by searching for "fear" or "asura vengeance" instead of "F.E.A.R." and "Asura: Vengeance"

**Comment by JosefNemec** [comment]
Acronym search is already supported and support for full alternative names is tracked in #3190, closing.
