### ISSUE TITLE
When I launch a game, the full screen mode screen is minimized

### ISSUE THREAD

**Issue by R3N69** [JosefNemec/Playnite#1593]
I am trying to make my PC similar to a console, and I find this launcher fantastic, I have already started the automatic startup when I start windows, but when I start a game the screen is minimized by showing the desktop, how can I not minimize it?

P.S. sorry for my english, my language is italian.

**Comment by JosefNemec** [comment]
This is intentional to prevent issues where the game will not get proper input focus (some games have issues with it).
