### ISSUE TITLE
"Import Steam Categories" doesn't set favorites, but makes category. 

### ISSUE THREAD

**Issue by Bigfootmech** [JosefNemec/Playnite#1596]
Assuming this changed how it works at some point during development.

Settings -> Libraries -> Steam -> Import Steam Categories

Imports Steam categories, but creates a "favorites" category that's not special in Playnite.

There's also a Playnite flag for favorited games, and this is not triggered.

This seems like a bug.

**Comment by JosefNemec** [comment]
Done in `devel`.
