### ISSUE TITLE
expose cookies of webview

### ISSUE THREAD

**Issue by Schippi** [JosefNemec/Playnite#1598]
for various plugin modules it would be adventageous to expose the cookies of the supplied webview/browser to get session ids for example.
in `source/playnite/WebView/WebView.cs` there are already functions to set and delete cookies, but not to easily retrieve them.
i suggest a method there that relays to `Cef.GetGlobalCookieManager().GetCookie(...)` similar to the setCookie function, so you dont need to supply another version of the cef library yourself alongside the plugin

**Comment by JosefNemec** [comment]
Done in `devel8`.
