### ISSUE TITLE
"Failed to import games from Origin. User is not logged in."

### ISSUE THREAD

**Issue by bverkron** [JosefNemec/Playnite#1599]
**Check for existing issue**
Searched for "User is not logged in" and other pieces of the error. Couldn't find a match

**Describe the bug**
Any time I try to update the Origin library I get the following error.
"Failed to import games from Origin. User is not logged in."

**To Reproduce**
Try to update Origin, though if nobody else has reported then it may be something obscure.

I have tried rebooting, closing and reopening both Playnite and Origin. Signing out of Origin and back in, etc. Same error.

**Screenshots**

**Diagnostics ID**
No crash

**Comment by JosefNemec** [comment]
Are you checking `Remember me` option when logging into Origin?

**Comment by bverkron** [comment]
As far as I recall yes, but I will have to double check when I get home. Does this effect how it behaves in the background? Because I can have Origin open and logged in and I still get this error.

**Comment by JosefNemec** [comment]
Login in Origin client itself has no effect on Playnite's Origin integration, it's a separate thing.

**Comment by bverkron** [comment]
Then I guess in this case it shouldn't matter if Remember Me is checked or not?

**Comment by JosefNemec** [comment]
Of course it matters, Playnite works the same way as any browser in this case. If you don't select remember me option then the session expires and you have to authenticate again.

**Comment by bverkron** [comment]
> Of course it matters, Playnite works the same way as any browser in this case. If you don't select remember me option then the session expires and you have to authenticate again.

Sounds contradictory to your last statement are you talking about a `remember me` option in Origin or in Playnite?

**Comment by JosefNemec** [comment]
In Playnite, your login in Origin client doesn't affect Playnite. Logging in Playnite is the same as logging to Origin via Chrome or Firefox, it's a separate login session that has nothing to do with Origin desktop client.

**Comment by bverkron** [comment]
> In Playnite, your login in Origin client doesn't affect Playnite. Logging in Playnite is the same as logging to Origin via Chrome or Firefox, it's a separate login session that has nothing to do with Origin desktop client.

Makes more sense. It's been a while since I setup Playnite and haven't had to look at the logins since. For various reasons I was getting the impression it was handle in the background after logging in via the official Origin client on the same machine, though now I vaguely recall getting prompted by Playnite for some logins during initial setup.

I'll try to re-authenticate through Playnite when I get home. That will mostly likely solve it.

**Comment by bverkron** [comment]
Settings > Libraries > Origin. Authenticated again. Fixed.

Thanks and apologies for mis-understanding how that worked.
