### ISSUE TITLE
EmuMovies Support

### ISSUE THREAD

**Issue by LuckyLukeArio** [JosefNemec/Playnite#160]
Add EmuMovies sync support to Playnite. As requested on the Playnite subreddit. [https://www.reddit.com/r/playnite/comments/755a4d/emumovies_support/](url)

**Comment by LuckyLukeArio** [comment]
https://www.reddit.com/r/playnite/comments/755a4d/emumovies_support/ Link works now, sorry!

**Comment by JosefNemec** [comment]
Support for custom metadata providers was added in Playnite 6. You should be able to create custom plugin for this now, without any addition support from Playnite required.

**Comment by JosefNemec** [comment]
Closing since this is now [being worked on](https://playnite.link/forum/thread-112.html) by a community member as a separate metadata plugin.

**Comment by JosefNemec** [comment]
Ask in plugin's repo, not here.
