### ISSUE TITLE
Add user defined launch script presets that  can be easily reapplied to different games.

### ISSUE THREAD

**Issue by Someone65** [JosefNemec/Playnite#1600]
I'd like to request the ability to save and load presets for the scripts tab of each game. The idea is that you will have scripts that you want to apply to a lot of games but you don't want it for ALL games so using the global script feature is out of the question.

The issue with doing it manually is that you have to copy paste 2 boxes of scripts and this can be slow and annoying. The solution would be to allow saving and naming sets of scripts that you can easily apply with 2 clicks (click 1: click dropdown menu, click 2: click desired preset).

Example: I need to use Borderless Gaming for some games and DXWnd for others as these may or may not function with certain games and I have to pick one or the other depending on the game. What I would do is save a script preset for each, go through each game I want to apply them to, click the dropdown menu and click my named script for each and proceed to do this for every game I want to apply one of them to. This removes the need to open up a notepad or something to keep 2 clipboard or more clipboard items in to do this manually.

**Comment by JosefNemec** [comment]
I don't think we need to add this as a feature, you can already achieve this by doing this (PowerShell example):

- save you script to a .ps1 file
- set game script to `& "file.ps1"`

**Comment by JosefNemec** [comment]
Closed based on my previous comment.
