### ISSUE TITLE
Created Categories appear multiple times in filter list 

### ISSUE THREAD

**Issue by RocketBun** [JosefNemec/Playnite#1602]
I was going through to create categories for easier filtering, and the first category was created fine. However, the second two list themselves multiple times in the dropdown menu. When adding them to a game they are only listed once, though. All of the "extra" categories seem to be identical, filter wise, and I can't find a way to get rid of them. 
![Playnite DesktopApp_2019-12-20_17-53-35](https://user-images.githubusercontent.com/24851266/71297510-bc7f3d80-2351-11ea-93ad-e20ddd57a1f2.png)

![2019-12-20_17-52-12](https://user-images.githubusercontent.com/24851266/71297432-88a41800-2351-11ea-8d42-2f25d6672b8d.png)

**Comment by JosefNemec** [comment]
What Playnite version do you use?

**Comment by RocketBun** [comment]
I'm using 6.4.

**Comment by RocketBun** [comment]
It seems to only occur for freshly created categories -- after creating a new one, the bug appeared on the new one and then stopped happening for the old.

**Comment by JosefNemec** [comment]
Fixed in Playnite 7.
