### ISSUE TITLE
Add Option to Use Cover/Banner Art for details view.

### ISSUE THREAD

**Issue by ddengel93** [JosefNemec/Playnite#1603]
As the title says add Option to Use Cover/Banner Art for details view instead of the icon. The Icon is too low res and is super stretched out when using custom themes and layouts. If possible also add an easy way to set the size of the art in details view.

![image](https://user-images.githubusercontent.com/29446346/71314500-81dfd880-2417-11ea-9997-6002bd3e4f5a.png)

![image](https://user-images.githubusercontent.com/29446346/71314539-06325b80-2418-11ea-9228-78d97430442a.png)

**Comment by JosefNemec** [comment]
If you are using custom theme then it should be up to the theme itself to show cover art there instead of icon. We don't need to make any changes in Playnite for that, you just need to ask theme author to change it.
