### ISSUE TITLE
[Fullscreen] Missing dark "shadow" when a game uses its cover as a background

### ISSUE THREAD

**Issue by kryptot7** [JosefNemec/Playnite#1604]
First of all, thanks for this app, it's super useful and beautiful! ✨ 
I have my library set to use the cover image as a background if a game has no background image provided. This works in Fullscreen, but when you click on a game's details, the dark "five-o-clock shadow" that the other games have is missing. That causes the UI elements to clash.

Here's the bug. This game was added manually:
![Playnite - BG missing dark shade](https://user-images.githubusercontent.com/30781325/71317227-eae14380-244b-11ea-9f09-f779ab90f2c1.png)

This game was added from itch.io:
![image](https://user-images.githubusercontent.com/30781325/71317270-604d1400-244c-11ea-93cb-98c0b1232ea3.png)

Here's an example of a game that looks right:
![image](https://user-images.githubusercontent.com/30781325/71317222-dbfa9100-244b-11ea-8312-58c3c3577ebd.png)

**Comment by JosefNemec** [comment]
Done in `devel7`.
