### ISSUE TITLE
Could the maxJsonLength setting be increased 

### ISSUE THREAD

**Issue by Shawson** [JosefNemec/Playnite#1606]
The Oculus library plugin fails because the maxJsonLength is too small on the Playnite app- some of the oculus manigest files can be aroujnd 5mb!

Would be great if you could increase the maxJsonLength to 10mb, just to be safe?

**Comment by JosefNemec** [comment]
I'm not sure this is Playnite issue. Can't you just change settings of `JavaScriptSerializer` you are using?

Playnite libraries/plugins use Newtonsoft.Json library and I don't remember it having such limit, maybe try using that one instead.

**Comment by Shawson** [comment]
I'll give it a bash!  cheers

**Comment by JosefNemec** [comment]
Closing since this should be handled in the specific plugin, it's not a Playnite issue.
