### ISSUE TITLE
Failed to open library database

### ISSUE THREAD

**Issue by PunishedDante** [JosefNemec/Playnite#1613]
Upon startup, I get this error. It seems to fix it when I run as administrator but gets rid of any setting changes I may make. Playnite already has full authorization so I am unsure what running admin changes. I know there is a DbTools.exe but I've tried running it multiple times in multiple different locations but it doesn't seem to work for me.
![Screenshot (128)](https://user-images.githubusercontent.com/59376583/71603747-028f8a80-2b24-11ea-909c-349a18dd64bf.png)

**Comment by JosefNemec** [comment]
Did you run Playnite's setup as admin? That's the only way I can think of this happening.

You'll have to fix access rights to that folder (`%appdata%\Playnite`) manually now or remove it completely and reinstall Playnite as standard user (the user you are trying to run it as, without elevated rights).

**Comment by PunishedDante** [comment]
> Did you run Playnite's setup as admin? That's the only way I can think of this happening.
> 
> You'll have to fix access rights to that folder (`%appdata%\Playnite`) manually now or remove it completely and reinstall Playnite as standard user (the user you are trying to run it as, without elevated rights).
> 
> Also DbTools.exe is obsolete.

No, I had installed it a standard user and it worked for a while but some time ago it developed tghis problem. I'll try reinstalling it and see if that works.

**Comment by PunishedDante** [comment]
I attempted to reinstall, same issue. Also, I forgot to mention that when I close the "Failed to open library database" I get a second error that says "Database is not opened." probably doesn't help but figured I would mention it.

**Comment by JosefNemec** [comment]
You need to delete that appdata folder (or repair its permissions) before reinstalling.

**Comment by PunishedDante** [comment]
Alright reinstalling worked. Thank you!
