### ISSUE TITLE
XB1 controller turns off when focusing on Full Screen window

### ISSUE THREAD

**Issue by PhilippeCadieux** [JosefNemec/Playnite#1618]
When using an official Xbox 1 controller with the official Microsoft USB Dongle to connect it wirelessly to the PC. The first time I click on the Playnite fullscreen window to put it in focus after turning the controller on, the controller will automatically turn off. I can then turn it back on and it will function normally. I am able to reproduce the issue by simply removing the battery from the controller to force it off and then turning it back on and clicking on the Playnite window again.

Steps to reproduce:
1-Turn on the XB1 Wireless Controller
2-Click on an already opened Fullscreen window of Playnite to put it in focus
3-Notice that the controller turns off

[diag.zip](https://github.com/JosefNemec/Playnite/files/4020446/diag.zip)

**Comment by JosefNemec** [comment]
I'm not sure how that's possible, we don't do anything with controller's power state.

I don't own XB1 controller so I won't be able to debug this, but I'll test with 360 wireless one next week.

**Comment by PhilippeCadieux** [comment]
Yeah it's a weird one for sure and not a deal breaker by any means obviously. It could be so many things causing this and it is the first time I've seen this happening (and I have actually been working in game QA for over a decade haha!).

Let me know if there's anything else I can do on my end to help track it down.

**Comment by JosefNemec** [comment]
This might be similar issue: https://www.reddit.com/r/playnite/comments/f6d73l/bug_full_screen_ui_wont_respond_to_left_stick/

**Comment by Super1337Boy** [comment]
This is probably the same issue as this one: https://www.reddit.com/r/playnite/comments/luyoul/controller_shutting_off_when_game_closes/

**Comment by WilliamLeGod** [comment]
Any1 is working on this issue?

**Comment by JosefNemec** [comment]
Removing from P10, will have to wait for #684 with reworked input handling support.

**Comment by JosefNemec** [comment]
Closing as we now switched to completely different input handling library which shouldn't have this issues (at least I wasn't able to find anybody reporting it).
