### ISSUE TITLE
Uniform cover size

### ISSUE THREAD

**Issue by Menna39** [JosefNemec/Playnite#162]
Can it be made so all covers have the same size, picture as reference.

I choose my own covers with pictures I found on google, but they're not the same size, can the covers all be made the same size disregarding the images I pick?

![cover_size](https://user-images.githubusercontent.com/8777847/31339098-0cd4c5c0-ad02-11e7-9608-dc3467b5b254.png)

**Comment by JosefNemec** [comment]
You can also try using IGDB as cover source, they have somewhat consistent sizes so it can help until this issue is solved (you can download cover from IGDB via "Download metadata" button while editing game).

**Comment by JosefNemec** [comment]
Since 3.0 this is controller by selected theme, by default all covers are set to have the same aspect ratio.

**Comment by JanPokorny** [comment]
@JosefNemec Are there currently any themes that support this? It doesn't seem like that the default theme does, the covers are all different sizes.

**Comment by JosefNemec** [comment]
@JanPokorny The area to render the image is the same for all covers no matter what theme you are using. The sizes are not the same because images are not stretched to fit that area, it would look ugly. There's no way how to solve it other then to download images with the same size and there are currently no sources that would offer covers in uniform form factor. Every store/database offer different dimensions.

**Comment by JanPokorny** [comment]
@JosefNemec I was thinking about a solution similar to how portrait videos are "converted" to landscape: essentially by filling the void with a larger, blurry version (https://www.youtube.com/watch?v=CgZsDLfzrTs)

**Comment by JosefNemec** [comment]
I'm not sure how that would look like, but you can open new issue for it.

**Comment by JanPokorny** [comment]
@JosefNemec OK, I'll try to do a mockup to see how it looks.

**Comment by JanPokorny** [comment]
@JosefNemec I somehow finally got to making a mock-up of blurred covers.

Before:

![obrazek](https://user-images.githubusercontent.com/4580066/39880002-b26a69f0-547c-11e8-8dce-c7fa3187f879.png)

After applying the cover, stretched (with aspect ratio preserved), centered, cropped and gauss-blurred as a background:

![obrazek](https://user-images.githubusercontent.com/4580066/39879985-aad02f36-547c-11e8-9032-653a94b5527c.png)

I'm not sure if it helps much, visually... But it may be a backup solution if there is no way to download uniform covers.

**Comment by JanPokorny** [comment]
@JosefNemec OK, made #580
