### ISSUE TITLE
Automatically recognize if it's in the Playnite folder/subfolder

### ISSUE THREAD

**Issue by Cyberavater** [JosefNemec/Playnite#1622]
When I choose; 
Action>Path>Browse then locate the executable .exe
Rather than setting path as;
`D:\Playnite64\Games\Deadpool\Binaries\DP.exe`
It would be wise to check if it's in the Playnite folder; if it is, then the path should be set as;
`{PlayniteDir}\Games\Deadpool\Binaries\DP.exe`

A very tiny feature but useful none the less, thanks!

**Comment by JosefNemec** [comment]
Duplicate to  #412
