### ISSUE TITLE
Add D3DOverrider in Playnite

### ISSUE THREAD

**Issue by Cyberavater** [JosefNemec/Playnite#1624]
Sometimes, for Vsync and speed issues, D3DOverrider is a must. 
So it would be wise to add it built-in. So that if I tick an option in Playnite for a game, D3DOverrider features will be used for that game when I run it through Playnite.

**Comment by JosefNemec** [comment]
This can be already achieved via custom game script. I don't really want to integrate such niche app natively, especially since it doesn't provide any official API.
