### ISSUE TITLE
Built-in option to use per game backgrounds in fullscreen mode 

### ISSUE THREAD

**Issue by Enkak** [JosefNemec/Playnite#1626]
Similar to how Desktop mode works visually, an option to use per game backgrounds in fullscreen mode.

**Comment by JosefNemec** [comment]
Are you talking about option to assign different background specifically for Fullscreen mode? Because we already display background image in Fullscreen mode.

**Comment by Enkak** [comment]
I'm talking about an option to have per game backgrounds when we scroll the game list in Fullscreen mode instead of them appearing in details only. Like this attached image:

![playnite_fullscreen](https://user-images.githubusercontent.com/11450342/75386945-6fcc5b80-58da-11ea-8cbb-8d00c5408031.jpg)

**Comment by JosefNemec** [comment]
Done in `devel`.

**Comment by Enkak** [comment]
Thank you so much!
