### ISSUE TITLE
UI Bug: Configure Emulators (Batch changes broken)

### ISSUE THREAD

**Issue by teconmoon** [JosefNemec/Playnite#1628]
When configuring emulators with Playnite, if I select an emulator and choose an alternate profile, I can view and make changes just fine. However, if I switch to another emulator in my list, it does not show the profile and information for that emulator, it shows what was previously being worked on.

For example, if I am working on mGBA looking at profiles and I switch to Dolphin, in the form fields most of the mGBA information will be displayed.

Going on to select a 3rd emulator will finally load the form fields, and I can then go back to what I was working on. So there is a workaround, just hard to get the hang of.

Another by-product of this issue is that if I try to select an emulator and remove multiple profiles, I can only successfully remove the first. The rest will not be removed, or even properly select. I have to select two other emulators before re-selecting what I was working on and continuing deletion.

[Video demonstrating](https://drive.google.com/file/d/1P7yyZOScUt7-aXyb5e_Kae-xQIn8XsnV/view?usp=sharing). Had a hard time figuring out how I was going to sufficiently explain this issue.

I am testing using clean installs of Playnite 6.4, tested on multiple machines.

**Comment by JosefNemec** [comment]
Done in `devel7`.
