### ISSUE TITLE
Redusing Similar Developer/Publisher Names

### ISSUE THREAD

**Issue by Rawra** [JosefNemec/Playnite#1634]
In some cases when downloading metadata about a title, developer or publisher information will be listed slightly differently. For example, across the F.E.A.R. series Monolith is entered as "Monolith", "Monolith Productions" and "Monolith Productions, Inc." It'd be great to have an automated method of marking all of these as the same so it will make it easier to filter titles developed or published by a specific studio easier.

**Comment by JosefNemec** [comment]
I don't think there's a way to implement this in some reliable way. There will be an option added in future that will allow merging of metadata fields via #1270

**Comment by Rawra** [comment]
That sounds like a more versatile feature, I certainly would like to see that.
