### ISSUE TITLE
Add Sizer

### ISSUE THREAD

**Issue by Cyberavater** [JosefNemec/Playnite#1636]
It'd be nice if it had, built-in <a href="http://www.brianapps.net/sizer4/">Sizer</a>

**Comment by JosefNemec** [comment]
How would that integration actually work from UX perspective?

**Comment by JosefNemec** [comment]
Also if Sizer works from cmdline then you can already integrate it, by starting it via game script before the game is started (when editing the game, via [Scripts tab](https://github.com/JosefNemec/Playnite/wiki/Frequently-Asked-Questions#how-do-i-start-additional-applications-before-game-starts-and-kill-it-after-game-exits)).

**Comment by Cyberavater** [comment]
> Also if Sizer works from cmdline then you can already integrate it, by starting it via game script before the game is started (when editing the game, via Scripts tab).

No, it doesn't support CLI. And this feature is best used in GUI.

> How would that integration actually work from UX perspective?
See here;  #1637
Thanks.

**Comment by JosefNemec** [comment]
If it doesn't support CLI then there's no way of integrating it (I don't see any mention of them having API available).

I also thing that this should be done as a custom plugin and not a built-in feature since it's a really rare use case.

I'll close this and leave #1637, to make it easier to develop this kinds of plugins.

**Comment by Cyberavater** [comment]
I didn't suggest to add the software literally!
I'm just suggesting to the software's feature (that's why I added built-in).

**Comment by JosefNemec** [comment]
I see, I'm sorry for misunderstanding. However my comment about this being niche feature stands and it should be done as a custom plugin.

Alternatively I would suggest contacting Sizer's author and ask them to add some CLI support if you want to integrate it using current scripting interface.
