### ISSUE TITLE
Add option to choose between launching Rainbow Six Siege in DirectX 11 or Vulkan mode. 

### ISSUE THREAD

**Issue by cristi1990an** [JosefNemec/Playnite#1638]
It defaults to DirectX11 and doesn't allow you to change it.

**Comment by JosefNemec** [comment]
Duplicate to #1107

For now you can manually edit game's Play action and change it to start game in Vulkan mode (RainbowSix_Vulkan.exe executable according to pcgamingwiki).

**Comment by ShovelKnight11** [comment]
Sorry for the necro, but changing the play action causes a secondary dialogue to open up in steam asking if I want to allow the game to launch.

**Comment by JosefNemec** [comment]
We can't force Steam to launch different executable than the default one without additional security dialogs, Steam simply doesn't support it. Launching exe directly is the only way you can do it, and if that doesn't work properly, there's nothing you can do, it's an issue on Steam's side.

**Comment by ShovelKnight11** [comment]
Thanks! Good to know.
