### ISSUE TITLE
problem background Incomplete Can be seen

### ISSUE THREAD

**Issue by Amir-799** [JosefNemec/Playnite#1639]
hi.thank for the amazing program.
my problem background
When I save background
 Incomplete Can be seen
How to solve the problem?
picture down problem

why down picture remove ?

**Comment by Amir-799** [comment]
https://ibb.co/VqPp056 
https://ibb.co/M6vDq5c background full

**Comment by JosefNemec** [comment]
That's how the default theme works, it creates gradient between the window background (or another blurred background image stretched to the whole windows if you have that enabled in settings) and the background image.

You either have to use some [custom theme](https://playnite.link/forum/forum-8.html) or [create a new one](https://playnite.link/docs/) that displays the background imaged differently.

**Comment by Amir-799** [comment]
Can you explain more accurately

**Comment by Amir-799** [comment]
It can't be adjusted with the settings?

**Comment by JosefNemec** [comment]
It can't be adjusted via settings, it's controlled by selected theme and that's just how it looks with the default one.

Your only options right now are either create your own theme that doesn't use the gradient or use existing custom theme that looks similar to what you are looking for.
