### ISSUE TITLE
Amazon Games launcher support

### ISSUE THREAD

**Issue by JosefNemec** [JosefNemec/Playnite#1640]
https://www.reddit.com/r/playnite/comments/exfdv2/new_amazon_games_launcher/

**Comment by BitGrub** [comment]
+1 to this because I found out I picked up 128 games from Twitch so far, and some of them are actually really good! 

FURI PogChamp

**Comment by JosefNemec** [comment]
If they are games from twitch then just use Twitch client, which is already supported.

**Comment by unrealed** [comment]
So, for me, launching a Twitch game now launches the Twitch app. Slight problem tho: all the games I had are now on the Amazon Games app... So basically the whole Twitch library on Playnite is unusable right now. I don't know how recently this became a problem but it's definitely a big one now

**Comment by darklinkpower** [comment]
@unrealed Twitch games are DRM free so you can launch them without the client. [Crow already implemented the option to launch the games that way](https://github.com/JosefNemec/Playnite/commit/9ed9da5b6e92f02ec193757b401ea97a0d866b24) and will be released in a future version.

**Comment by JosefNemec** [comment]
@unrealed Support for Amazon Games launcher will be added in 7.3.

**Comment by JosefNemec** [comment]
Done in 7.3
