### ISSUE TITLE
Crash when launching DesktopApp "System.NullReferenceException"

### ISSUE THREAD

**Issue by Le-Barbu** [JosefNemec/Playnite#1646]
I have a similar issue to #1609 (I thought it was the same issue but the errorcode is different)
both playnite and several library plugins are throwing "System.NullReferenceException: La reference d'objet n'est pas definie a une instance d'un objet."

I tried uninstalling, removing the settings folder and reinstalling different versions (6.5, 5.8, 5.6, 4.74) they all crash at launch
It is weird because I have been using Playnite for months now
The crash window crashes too except the first time playnite is launched on a fresh install :  buttons are responsive but clicking the "Create diag. package" button opens a window saying "Failed to create diagnostics package."

FullscreenApp works fine with an existing library

this is the log from playnite portable 6.5

[playnite.log](https://github.com/JosefNemec/Playnite/files/4175590/playnite.log)

**Comment by JosefNemec** [comment]
After the diag. package creation filed the Explorer window will open pointing to a zip file. Please attach that file, thank you.

**Comment by Le-Barbu** [comment]
It didn't, I'm sorry I have no idea where that file is

**Comment by JosefNemec** [comment]
That's weird, I checked the log file you attached and there's something wrong with access to a system registry. All library plugins failed to load completely. That should not be causing the crash though.

Can you please try it again with [this build](playnite.link/download/6_5_debug.zip) and send me new `playnite.log`? Thanks in advance

**Comment by Le-Barbu** [comment]
[playnite.log](https://github.com/JosefNemec/Playnite/files/4176644/playnite.log)

**Comment by JosefNemec** [comment]
Thanks for the log file, can you try it with [this build](https://github.com/JosefNemec/Playnite/issues/playnite.link/download/1646.zip)? It should be working now.

**Comment by Le-Barbu** [comment]
It works like a charm! Everything works as if nothing bad happened, thanks a lot!
