### ISSUE TITLE
RAWG Videogames Database metadata plugin

### ISSUE THREAD

**Issue by darklinkpower** [JosefNemec/Playnite#1647]
**Describe the solution you'd like**
Make a plugin that uses RAWG Videogames Database. API available here: https://rawg.io/apidocs

A thing to consider is that this db has a limitation. Quoting: 

> Free for commercial use for startups and hobby projects with not more than 100,000 monthly active users or 500,000 page views per month. If your project is larger than that, email us at api@rawg.io for commercial terms.

**Comment by spektor56** [comment]
I started on this
