### ISSUE TITLE
Add a button for all installed games in full-screen-mode

### ISSUE THREAD

**Issue by Rioluuu** [JosefNemec/Playnite#1648]
Adding a button that shows all installed games in full-screen-mode would be very nice, because when you have lots of games that arn't installed on to your system it's better to find your titles.

It could look like this:
![grafik](https://user-images.githubusercontent.com/43097559/74104113-ff8baf00-4b51-11ea-803a-d135fe3bb99f.png)

**Comment by JosefNemec** [comment]
Will be done via #590. For now you can enable display of only installed games in the Fullscreen mode settings.
