### ISSUE TITLE
Update for all games that has more then 1 disc

### ISSUE THREAD

**Issue by Swat842** [JosefNemec/Playnite#1650]
**Check for existing issue**
N/A

**Describe the solution you'd like**
I would like to see an update for all games that has more then 1 disc to be able to pull the info of that game like for exp " Legend of Dragoon it has 4 Disc's for that game, Metal Gear Solid Subsistence it has 3 Disc's etc.." we shouldn't have to load 1 game at a time an find the right info or have to input the right info for more then 1 disc an also if we can combine them to 1 game like for exp " Legend of Dragoon Disc 1 / 4 in 1 file should still keep track of how long that game is played for each disc not just for Disc 1 only but for all disc's"

**Screenshots**
If applicable, add screenshots to help explain requested changes.
![image](https://user-images.githubusercontent.com/59518236/74355978-9a230280-4d8b-11ea-82ec-75bf0832594a.png)

**Comment by JosefNemec** [comment]
Duplicate to #159
