### ISSUE TITLE
"Client shutdown grace period" and "Don't close after games sessions shorter" value can't be more than 100

### ISSUE THREAD

**Issue by darklinkpower** [JosefNemec/Playnite#1652]
**Describe the bug**
Attempting to input more than 100 will revert it to previous value. For "Don't close after games sessions shorter" I can see people (like me) wanting to use more than 100 seconds for that feature.

I've made a pull request to increase maximum value of "Don't close after games sessions shorter" to 9,999. I think it makes sense to have a higher value to allow even 10 or 20 minutes sessions because probably if someone plays for that relatively short time, chances are he will still want to play another game in the same client.

**Comment by JosefNemec** [comment]
Done in 7.1
