### ISSUE TITLE
Games not being sorted by group in grid view.

### ISSUE THREAD

**Issue by darklinkpower** [JosefNemec/Playnite#1654]
**Describe the bug**
Behavior in previous Playnite versions was sorting first by group and then by name in grid view. Now it's only sorting by name without considering selected group option and losing all organization in the process.

**Screenshots**
![imagen](https://user-images.githubusercontent.com/1389286/74510282-1111e580-4ec9-11ea-9ceb-75411ab670e1.png)

**Comment by JosefNemec** [comment]
Fixed in `devel8` by 736f4f9896c4bed90ec6db65e43989633c644ad9 revert.
