### ISSUE TITLE
Option to disable the import of Steam Soundtracks

### ISSUE THREAD

**Issue by sjdawson** [JosefNemec/Playnite#1655]
An option in the Steam importer that will allow soundtracks to be ignored during game import.

With Steam moving Soundtracks to a first party library member, instead of just DLC, Playnite now imports them as a game - but only if it's installed. Not sure on the logistics of it being possible, but if there could be an option to disable importing soundtracks during Steam import, that would stop them showing up in Playnite, that would be awesome.

**Comment by darklinkpower** [comment]
I don't know if it's related but I bought this game today and it imported the DLC for some reason as a separate game entry.

https://store.steampowered.com/app/229660/Sonic_and_AllStars_Racing_Transformed_Metal_Sonic__Outrun_DLC/

![imagen](https://user-images.githubusercontent.com/1389286/74578740-ff2d5280-4f5b-11ea-86ab-511bec2348ec.png)

**Comment by JosefNemec** [comment]
Done in `devel`. Playnite will ignore soundtracks completely, there's no option to import them (there are complications in starting them and in general having them imported as a game).

@darklinkpower It's not related. Steam API sometimes decides to report DLC as a separate game, nothing I can do about it that right now. You'll have to hide it for now (there will be ignore import feature added in Playnite 8).
