### ISSUE TITLE
Uplay on "open third party clients" window

### ISSUE THREAD

**Issue by Alelucci** [JosefNemec/Playnite#1656]
Maybe it just me but i don't see the Uplay client on the "open third parts clients" window. If its not just me coud you add it ?
Sorry if the screenshot is in Italian.

![Playnite Uplay](https://user-images.githubusercontent.com/43417615/74560298-91d2ef00-4f66-11ea-8b9f-88efb3939a0f.jpg)

**Comment by JosefNemec** [comment]
Try re-installing Uplay client. It's shown there on all my systems.

**Comment by Alelucci** [comment]
I did it as u said and it worked, thank you for your time. :)
