### ISSUE TITLE
Improvements and recomendations

### ISSUE THREAD

**Issue by JMPMX** [JosefNemec/Playnite#1659]
If I may, I would like to suggest some improvements to this wonderful frontend:

1) Implement another APIs to scrapping metada like: www.mobygames.com,  https://thegamesdb.net/ or https://screenscraper.fr/ (personally, actually the best)., because sometimes the base scrapper dont get all metadata or get incomplete.

2) Zip support for emulators that dont natively support it and are better than retroarch libretto. (Example: Snes9x or Kega Fusion) and then Goodmerge 7-Zip support to choose rom inside like others frontends (EmulatorsOrganizer, Emucenter2...) or emulator BizHawk, because old consoles or computers collections are romerged (Example: GoodSnes or GoodGen) with all versions of the game (Usa-Europe-Japan) plus Hack versions and (this is the most important) translated versions, and is important to choose what file you want to send to emulator to run. (attached video https://streamable.com/ulfrw)

Best regarts,

JMPM.

**Comment by JosefNemec** [comment]
1) There are separate issues opened already for other metadata providers. I personally do not plan to add and maintain any new ones, but some people already [created some](https://playnite.link/forum/forum-17.html).

2) Already opened as #271
