### ISSUE TITLE
GameDatabase isn't thread safe

### ISSUE THREAD

**Issue by jcanady20** [JosefNemec/Playnite#166]
1: GameDatabase uses a filelock object to protect against multiple threads executing the same code sections.
FileLock is a private member and not a static member of the class.

GameDatabase initialization isn't thread safe:
 
Multiple threads can initialize the Instance of GameDatabase.
Use lock to prevent race conditions when creating the Single instance of GameDatabase

https://msdn.microsoft.com/en-us/library/ff650316.aspx

please review the section on Multi Threaded Singleton

**Comment by JosefNemec** [comment]
Singletons are no longer being used in 3.0

**Comment by JosefNemec** [comment]
Released in 3.0
