### ISSUE TITLE
Somebody selling Playnite on Steam

### ISSUE THREAD

**Issue by shakeyourbunny** [JosefNemec/Playnite#1665]
**Describe the bug**
Someone called "loongjinlong" is selling Playnite for profit. I doubt he has permission.

See https://store.steampowered.com/app/1236280/loongs_utilities_Playnite/

**Comment by JosefNemec** [comment]
Already reported on several places including in #1664, my response is [here](https://playnite.link/forum/thread-144.html). Please use search next time to see if the issue was already reported, as issue template says.
