### ISSUE TITLE
Ability to sort games by install size

### ISSUE THREAD

**Issue by imkrut** [JosefNemec/Playnite#167]
1) Select game at random (for when you don't know what to play/feel like getting a suggestion) extra filters like (not played, etc could be used) 
Currently this site does it (https://servc.eu/rsg/)

2) Sort games by install size (great for Steam, when you want to play something new, but don't want to wait for a huge download size)

Currently this site gives that info apparently (http://www.mysteamgauge.com)

**Comment by JosefNemec** [comment]
Thanks for suggestions. No.1 has been already requested in #121 so I'm going to rename this issue to take care of no.2

**Comment by GreetingsEarthling** [comment]
I agree that this would be very helpful. It would also be great to see size of games that are not installed (I know Steam API can provide size, not sure about other games).

**Comment by ChildishGiant** [comment]
Is there any chance this'll be added for 5.0?

**Comment by JosefNemec** [comment]
No there isn't, this was not planned to be in 5.0.

**Comment by HunterZ** [comment]
Playnite already knows where games are installed. Just reporting the size of the file tree under that folder would probably be good. It looks like there are a lot of examples around of how to do this in C#. The only issue I can think of is it's probably a slow operation, so maybe default to caching the sizes and give the user an option to recalculate?

**Comment by bverkron** [comment]
> it's probably a slow operation, so maybe default to caching the sizes and give the user an option to recalculate?

This is a good suggestion. I had a similar thought. Maybe a warning / note somewhere too that enabling the feature could introduce slowness.

**Comment by bburky** [comment]
Not a perfect solution (only works for installed games, and it's a spreadsheet export not built in) but be this extension I wrote is a partial solution if you're trying to find your largest installed games:

[Calculate Sizes of All Installed Games](https://playnite.link/forum/thread-277.html)  
> This extension calculates the sizes of the `InstallDirectory` of all installed games, creates a CSV spreadsheet and opens it in Excel

**Comment by Gerren** [comment]
Hello there,

I decided I'd make an Extension for it. It utilizes Age rating, and you can use it in the library to filter and sort.

Forum
https://playnite.link/forum/thread-280.html

GitHub:
https://github.com/Gerren/SizeCalculator

**Comment by JosefNemec** [comment]
Done in Playnite 10
