### ISSUE TITLE
Navigation by System

### ISSUE THREAD

**Issue by monfor1** [JosefNemec/Playnite#1670]
One of the most need updates of Playnite is his usability and navigation. Playnite can be the most used launcher, if a gamer can navigate correctly by games only with a gamepad.

One of the most needed options is navigate by systems/platforms only with a button. 

I think that the app works so nice, and it's time to improve usability, configuration and new visual themes. The most important, navigate by systems with a key, perhaps a trigger from xbox gamepad.

![system](https://user-images.githubusercontent.com/61489759/75316215-f8a8b000-5864-11ea-925e-ce44e5c42f2d.jpg)

Another interesting options are visual themes, metro launcher from Xbox is so nice, like banner and etc, but another visual options are so nice.

![1080-ViewsCitrisKeibertzPoster(20160925)](https://user-images.githubusercontent.com/61489759/75316266-23930400-5865-11ea-9223-482c498893b1.jpg)

![UntitledSeries3](https://user-images.githubusercontent.com/61489759/75316264-2261d700-5865-11ea-943b-2443bb44586a.jpg)

![1080p-ViewsCitrisExplorerRedux(20161113)](https://user-images.githubusercontent.com/61489759/75316260-20981380-5865-11ea-94a2-61e6242bc6b7.jpg)

**Comment by JosefNemec** [comment]
This will be added via #1278

**Comment by mattmaiorana** [comment]
Love those mockups @monfor1 - are they from an existing frontend/theme?

**Comment by shakeyourbunny** [comment]
Looks like an EmulationStation skin.
