### ISSUE TITLE
save load game for offline games

### ISSUE THREAD

**Issue by delfino434** [JosefNemec/Playnite#1673]
**Check for existing issue**
Please use issue search in the repository if your feature request is something really obvious there's a high change it was already requested.

**Describe the solution you'd like**

**Screenshots**
If applicable, add screenshots to help explain requested changes.

**Comment by JosefNemec** [comment]
I have no idea what are you asking for. `A clear and concise description of what you want to happen.` is there for a reason, please clarify.
