### ISSUE TITLE
Option to search by specific image resolution when searching images via Google and add presets support

### ISSUE THREAD

**Issue by darklinkpower** [JosefNemec/Playnite#1674]
**Describe the solution you'd like**
Currently results are not filtered in any way when searching for images via Google for metadata artwork. This brings a lot of unwanted results since most results tend to be of very low quality for the purpose, for example:

![imagen](https://user-images.githubusercontent.com/1389286/75467148-dd1ad380-5950-11ea-93e1-a6bea2779d27.png)

I have some ideas to address this.

![imagen](https://user-images.githubusercontent.com/1389286/75468925-ab573c00-5953-11ea-8b8e-abd510dc7bcf.png)

Having an option to search by specific sizes would be useful. It would make use of `imagesize:{width}x{height}` that can be added when using google images to search for images of an specific resolution, but ideally this string should be hidden from the user and only added internally in the search to show the desired results.

![imagen](https://user-images.githubusercontent.com/1389286/75469427-95964680-5954-11ea-899b-a677d4b22702.png)

Different presets could be made for covers, icons and Background images. Thinking of covers it would be a good option until #805 is added, because it would allow to quickly get covers for specific sizes.

**Comment by JosefNemec** [comment]
Done in devel
