### ISSUE TITLE
Add New Features.

### ISSUE THREAD

**Issue by kareem007g** [JosefNemec/Playnite#1680]
Hi Mr.Josef Namec
First of all thank you for your Amazing Project that you made !!
I have small suggestions which make your Playnite project more epic , And I hope you add it in your future updates.
first suggestion is to add support playing videos background for each game (like short snap video or trailer) and show the video when the mouse arrow hover on the game banner or add an icon beside play and details icons to show the trailer video as a customizble  popup window or when we show the game details as will as with full screen mode.
Second , On the full screen mode let us launch the game by click the game banner by Mouse not just the controller or keyboard.
Thanks allot.

**Comment by JosefNemec** [comment]
Hi, will be done via  #405 and #1323.
