### ISSUE TITLE
Xbox Games and Games for Windows

### ISSUE THREAD

**Issue by aserrallerios** [JosefNemec/Playnite#1685]
Games for windows games appear under Xbox library, but the "Platform" is wrong, it shows "MS Xbox 360", so they are indistinguishable from true Xbox360 games.

**Comment by JosefNemec** [comment]
See [this page](https://github.com/JosefNemec/Playnite/wiki/Xbox-Library-troubleshooting#gfwl-pc-games-are-imported-as-360-games). Xbox Live API reports all GFWL as 360 games, nothing I can do about it sadly. However you can change the platform manually to correct one.
