### ISSUE TITLE
Minecraft Microsoft Store

### ISSUE THREAD

**Issue by MohandL3G** [JosefNemec/Playnite#1687]
**Describe the bug:**
A clear and concise description of what the bug is.I have Minecraft (Bedrock) Installed on my PC but I can't add it to Playnite, when I click on **"Add Game > Microsoft Store or Xbox App Game..."** I can't see Minecraft listed even when I click on **Detect Installed** it doesn't show up.
I've had to create a bat file with these commands:
```
@echo off
explorer.exe shell:appsFolder\Microsoft.MinecraftUWP_8wekyb3d8bbwe!App
pause
```
and when I exit the Game I have to exit the cmd window.

**To Reproduce:**
Install Minecraft (Bedrock).
Run Playnite and click **"Add Game > Microsoft Store or Xbox App Game..."**.
Now I can't find the game.
Optional: Click on **Detect Installed** and I still can't find it.

**Screenshots:**
Minecraft is shown on Start Menu.
![Screenshot_1](https://user-images.githubusercontent.com/31743237/75626648-e8c8fd00-5bd1-11ea-83e6-709ffbfd5872.jpg)

Minecraft is shown under Installed Apps.
![Screenshot_2](https://user-images.githubusercontent.com/31743237/75626670-0a29e900-5bd2-11ea-9fcf-477b9094788b.jpg)

Minecraft is not available on **Microsoft Store or Xbox App Game** menu on Playnite.
![Screenshot_3](https://user-images.githubusercontent.com/31743237/75626674-157d1480-5bd2-11ea-8ccd-bc5567eddbd6.JPG)

**Comment by JosefNemec** [comment]
Was the game installed from Microsoft Store or side loaded somehow? Also try using new Xbox integration that comes with Playnite 7, it will import all MS Store games automatically.

However if the game doesn't show up in that list it means that it's somehow not installed properly. You may need to try and reinstall it.

**Comment by MohandL3G** [comment]
Yeah the game was sideloaded, I forgot to mention that.
I used xatoner Patch from cs.rin, So this means that the Game is cracked.
I tried reinstalling it but, it was the same.
But the Game is Installed under Installed Apps.

So does that means that Playnite can't add sideloaded Games?

**Comment by JosefNemec** [comment]
We don't support side loaded games. We use official Windows API that doesn't report side loaded apps and I have personally zero interest in officially supporting cracked games.

You can technically set it up by adding the game manually and setting up its Play action to use `explorer.exe` with arguments you mentioned.

**Comment by MohandL3G** [comment]
Alright, I'll try to use some method, especially that I want Playnite to count Play Time.

Thanks for your reply.
