### ISSUE TITLE
Arcade rom names

### ISSUE THREAD

**Issue by DoctorGoat** [JosefNemec/Playnite#1689]
When you import roms, you get names like samsh5sp and sf2yyc that are not exactly good looking. If Mame is installed, it can output a list of roms by zip name and actual name. It would be nice if it was possible to add this and have it automatically fix CPS1/2/3, Neo Geo, and MAME lists. If this is done, it should also greatly improve metadata searching.

Attached is an example output of -listtxt from Mame64 with my rom folders. 
[exported.txt](https://github.com/JosefNemec/Playnite/files/4277824/exported.txt)

**Comment by JosefNemec** [comment]
This will be solved by #653
