### ISSUE TITLE
Steam Game "Covers" have icon, Orign (and others) do not.

### ISSUE THREAD

**Issue by brendonlamb** [JosefNemec/Playnite#169]
![image](https://user-images.githubusercontent.com/1816511/31362229-5eb88750-ad25-11e7-93e9-cd11116a88d2.png)

Personally I like the "full" cover look, no "Steam" or "Origin" icons would be great or at least give us the option to toggle those icons.

Simple example, in my image compare "Sim City" with "Elite Dangerous"

Fantastic work work man, keep it up!

**Comment by JosefNemec** [comment]
Cover view will be completely redone in 3.0, in issue #36
