### ISSUE TITLE
Change default monitor and audio output when in fullscreen

### ISSUE THREAD

**Issue by superusercode** [JosefNemec/Playnite#1691]
**Describe the solution you'd like**
When I'm using big picture mode on my TV, which is connected via HDMI, I need to switch default video and audio output, so it would be more convenient to have it done automatically whenever I enable and disable the big picture mode. This is already done by steam.

Based on https://www.reddit.com/r/emulation/comments/fayqyb/playnite_7_released_open_source_videogame_library/fj1qp1y

**Comment by leonardoRC** [comment]
1 more with this problem, I'm using the steam big picture for this.
The big picture permit selects the monitor that you ain't to use, to open the selected game.
When you open this game steam sets the screen selected as a system default.

**Comment by JosefNemec** [comment]
Somebody made an extension for this: https://playnite.link/forum/thread-265.html

**Comment by leonardoRC** [comment]
Yes, this extension is exactly the solution. I think have a lot of users who use playnite as a console emulator for tv =)
I tried this extension like other users but it's not workling
we Tring to solve that here https://github.com/konnogatto/SwitchDisplay/issues/1#issuecomment-655038936

Should be nice have this extension default.
