### ISSUE TITLE
Minimize Button in Fullscreen

### ISSUE THREAD

**Issue by CriticalComposer** [JosefNemec/Playnite#1695]
I know Fullscreen enhancements are coming soon (so maybe this is already on the table) but I'd like to be able to minimize Playnite while in Fullscreen mode. I used to just close it when I was done playing a game but with the addition of auto-closing clients I now have to keep Playnite open after playing. 

For the time being I'll simply alt+tab to something else but the minimize feature is already baked into the software (it does it when a game is launched) so I don't see why it shouldn't be added in to manually invoke the minimize command.

**Comment by JosefNemec** [comment]
Done in master.
