### ISSUE TITLE
"No games found for specified search/filter criteria" displayed prematurely/incorrectly

### ISSUE THREAD

**Issue by RiseT** [JosefNemec/Playnite#1700]
**Describe the bug**
On several occassions (e. g. launching Playnite, switching to fullscreen mode), the string "_No games found for specified search/filter criteria_" (LOCNoGamesFound) is getting displayed prematurely (and incorrectly), i. e. while Playnite is still in its launching process. As an example, when launching Playnite, the mentioned string **and** the string "Loading game library…" are getting displayed **simultaneously** for several seconds (which makes no sense). Don't know if this is due to my rather large game library, but even then this shouldn't happen imho.

Additionally, that string is not properly horizontally centered.

PS: It isn't necessary to have any filters applied for this to happen.

**To Reproduce**
Launch Playnite (don't know if a large game database is necessary).

**Screenshots**
Will try to take one if necessary.

**Diagnostics ID**
n/a

**Comment by JosefNemec** [comment]
Yeah this will happen if it takes longer then usual to initialize the library. I could probably fix it somehow, but it's IMHO low priority.

**Comment by RiseT** [comment]
Right, low priority imo as well, but wanted to point it out in an issue.

**Comment by kremuwakarz** [comment]
This happens on my setup too with 3 games and running on SSD, annoying, its need to be fixed.
@JosefNemec  perhaps you could extend app start time a bit to hide this message somehow...

**Comment by JosefNemec** [comment]
I changed how to message is displayed in Playnite 8 (for default theme that is).
