### ISSUE TITLE
Window Size & Position Resetting

### ISSUE THREAD

**Issue by SirR0BN** [JosefNemec/Playnite#1701]
Recently the Playnite window is not saving size and position. There was an update that prevented the window from being resized "too small" which is when the issue started.

This occurs after:  Windows shutdown and startup, Windows restart, Playnite exit application and application start.

Below is a screenshot of how the Playnite window starts up across my two monitors.

![ISSUE](https://user-images.githubusercontent.com/62158912/76661151-09d60a00-6551-11ea-88c4-a04684937156.jpg)

Below is also a screenshot of how I typically exit the application or shutdown Windows.

![TYPICAL](https://user-images.githubusercontent.com/62158912/76661575-2757a380-6552-11ea-82e2-d220e2d312cd.jpg)

**Comment by JosefNemec** [comment]
Should be an easy fix. The workaround for now is to set the window width at least one pixel larger then minimal allowed size.

**Comment by SirR0BN** [comment]
I can confirm that increasing the width slightly does cause the window to remember size and position.

**Comment by SirR0BN** [comment]
> Should be an easy fix. The workaround for now is to resize the window width at least one pixel larger then minimal allowed size.

I can confirm that increasing the width slightly does cause the window to remember size and position.

**Comment by JosefNemec** [comment]
Fixed in `devel8`.
