### ISSUE TITLE
Option for extensions to supply UI elements to game view

### ISSUE THREAD

**Issue by Deide** [JosefNemec/Playnite#1702]
Is it possible to supplant dynamic variables in a game's description entry? I'm thinking of having an extension parse the description when it comes into view (when the information view is opened). A quick look over the API, and there are events for "selected game", and ways to update metadata, but I do not want to make database changes, only visual changes.

For example, if we imagined a game containing the following as its description entry:

> {DynamicDescription}
> This game is... (carry on with regular descriptive stuff)

Then the `{DynamicDescription}` is visually replaced with some extension's output, like the other dynamic variables elsewhere. It could be used for all sorts, like getting the last achievement you got, showing a random screenshot, or displaying current lobby data, etc.

Perhaps this isn't the best way to achieve what I'm looking for though. Is there a better route towards this kind of extensibility and computed customisation?

**Comment by JosefNemec** [comment]
I do plan to add an option for extensions to provide custom UI elements that will be placeable on game's view. It definitely won't be done via Description field, that's just HTML rendered for that text.

**Comment by Deide** [comment]
Excellent. Beats doing hacky things with the Description field for sure.

**Comment by JosefNemec** [comment]
Done in devel9.
