### ISSUE TITLE
Global script execution override

### ISSUE THREAD

**Issue by IFD3** [JosefNemec/Playnite#1708]
At the moment there are global scripts executed at start and stop of a game 
and you can also set scripts for games themselfes.
Now I have the Problem that the global script should not start when there is a start/stop script for a specific game.

Would be awesome, if there where an option to disable or override the default/global script via checkbox with the game specific one in the game preferences.

thanks, best regards

**Comment by JosefNemec** [comment]
Done in `devel8`.
