### ISSUE TITLE
Error during shutdown of Windows

### ISSUE THREAD

**Issue by InPhoenity** [JosefNemec/Playnite#1711]
Hello,

New user to Playnite, it seems to work fine and it is already my primary launcher.
I just have one issue described below.

**Check for existing issue**
The issue already exist but was closed. So it is a potential regression : https://github.com/JosefNemec/Playnite/issues/866

**Describe the bug**
When shutting down or restart the computer, a Windows error message appear.

**To Reproduce**
Shutdown the computer by letting Playnite running in tray.

**Screenshots**
![66102034-3d2f6880-e5b1-11e9-9073-f9057778ac40](https://user-images.githubusercontent.com/3192429/77106740-dfd48a00-6a1f-11ea-8bf1-87603b6564e4.jpg)

**Diagnostics ID**
9eb08723-ebe6-428d-b754-23d82d061ea3

**Comment by JosefNemec** [comment]
I don't think it's a regression, the shutdown code didn't change since then, the original fix is still in place. 

I can't reproduce it myself on any of my systems, which makes it basically impossible for me to fix it.

**Comment by InPhoenity** [comment]
If it may help, I have noticed the error doesn't occure if I am running Playnite as administrator. I will do different kind of experimentation to try to isolate the origin of the problem. Some preliminary researches mention this error can be related to Nvidia Control Panel config.

**Comment by InPhoenity** [comment]
Ok. I have identified the origin of the problem.
On my configuration, the error is related to https://maxto.net/ (to split screen in regions).
If I first quit MaxTo, and then shutdown my computer, no error anymore from Playnite.
