### ISSUE TITLE
Ability to import Windows shortcuts (*.lnk)

### ISSUE THREAD

**Issue by rubin55** [JosefNemec/Playnite#1715]
**Describe the solution you'd like**
When using "Add Game" -> "Scan Automatically" -> "Scan Folder" and selecting a folder that contains a large collection of meticulously created custom Windows shortcuts for various DOSbox games, zero games are detected.

Please make it so that *.lnk files can be added, just as .exe's can be today.

**Comment by JosefNemec** [comment]
Duplicate to #815
