### ISSUE TITLE
Certain Steam Games Not Importing

### ISSUE THREAD

**Issue by shangles** [JosefNemec/Playnite#1717]
Lots of games are being released for free on Steam due to COVID-19.  I've been grabbing them and adding them to my library (but NOT installing) for a later date.

After adding to my Steam library, I update Playnite Steam library and it doesn't always import the games.

Two games I've noticed so far are:

**Uni**
https://store.steampowered.com/app/1011300/UNI/

**Between Two Castles - Digital Edition**
https://store.steampowered.com/app/1158500/Between_Two_Castles__Digital_Edition/

**Comment by JosefNemec** [comment]
Duplicate to #910
