### ISSUE TITLE
Collate name search E.g. Pokemon/Pokémon

### ISSUE THREAD

**Issue by cbpassingham** [JosefNemec/Playnite#1719]
I added a number of Pokémon games to my library and downloaded metadata from IGDB. When I search for "pokemon", none of them show up.

Could an option be added to match accented names when using non-accented search strings?

**Comment by JosefNemec** [comment]
Sadly, this is an issue with IGDB's API search. I'll try to add some workaround, but it will not work 100% correctly until this is fixed on IGDB's side.

**Comment by JosefNemec** [comment]
I've done some workarounds in Playnite 8, but it still doesn't work reliably. It simply has to be fixed on IGDB's side.

**Comment by robclouth** [comment]
@JosefNemec Filtering by name works better than search. E.g.
```request.where(`name ~ *"${query}"*`);```

**Comment by JosefNemec** [comment]
We already do that.

**Comment by robclouth** [comment]
Ok. I know nothing about your project sorry. I just thought it might be
useful. (it wasn't lol)
