### ISSUE TITLE
Ignore previously imported ROMs when importing for emulators

### ISSUE THREAD

**Issue by JeromeDane** [JosefNemec/Playnite#172]
It would be great if the import emulated games functionality looked to see if each valid game in an import folder was already present in the library and either did not include them in the import list or included them unchecked. This could probably be accomplished by checking to see if there is already a game in the library with a value for `Image/ISO Path` that matches the path of the ROM file that would be imported.

Alternately, being able to "un-check all" in the import list then re-check just the newly added roms would be a good start.

Thanks for a GREAT program. <3

**Comment by JeromeDane** [comment]
I take it ignoring previously imported ROM files didn't make the cut for v3.0? No problem, as we're all excited for any and all updates, and I understand if there are more important things to focus on at the moment. Just hoping this stays on your radar for a future update.  Keep up the good work! <3

**Comment by JosefNemec** [comment]
I wasn't planning on adding it into 3.0, but I agree that it's really annoying if you store ROMs in single folder. I might squeeze it into 3.0.

**Comment by JosefNemec** [comment]
Released in 3.0
