### ISSUE TITLE
add android games to playnite launcher

### ISSUE THREAD

**Issue by Kmoshiro** [JosefNemec/Playnite#1720]
hi, i set out to add android games to the launcher.

I have managed to add the games so that the emulator starts correctly and then starts the game,all this from the launcher.
(the emulator I used on this occasion was bluestacks)

i'm a bit new when it comes to programming, well let's get to the point.

-install your game on bluestack

-after installing the game you can see a shortcut of the game on your desktop, which you must open properties.

-now in playnite, you need to add a new game manual

-you go to the installation tab and click installed

-go to the actions tab:
You must first locate the executable "HD-RunApp.exe" usually this in "C: \ Program Files \ BlueStacks \"
then you must locate the argument of the game which is in the destination in the properties window that we previously opened.
for example:
on this occasion I added minecraft pocket edition
his destiny is "C:\Program Files\BlueStacks\HD-RunApp.exe" -json "{\"app_icon_url\":\"\",\"app_name\":\"Minecraft\",\"app_url\":\"\",\"app_pkg\":\"com.mojang.minecraftpe\"}"
what interests us is everything that is outside the first pair of double quotes

in this case it would be: -json "{\"app_icon_url\":\"\",\"app_name\":\"Minecraft\",\"app_url\":\"\",\"app_pkg\":\"com.mojang.minecraftpe\"}
this is the argument that we will use

I will leave in photos step by step what I did because I know it is a bit complex to explain

![foto 1](https://user-images.githubusercontent.com/56491484/77840606-baeac000-715f-11ea-9fd9-59893dd6d9a6.PNG)
![foto 2](https://user-images.githubusercontent.com/56491484/77840612-c1793780-715f-11ea-80e9-49fe12b13ac4.PNG)
![foto 3](https://user-images.githubusercontent.com/56491484/77840618-ce962680-715f-11ea-89ac-aac9bef3f09c.PNG)
![foto 4](https://user-images.githubusercontent.com/56491484/77840619-d3f37100-715f-11ea-9b41-ac3fab0c08eb.PNG)
![foto 5](https://user-images.githubusercontent.com/56491484/77840620-d655cb00-715f-11ea-9e5b-fa34caa96839.PNG)
![foto 6](https://user-images.githubusercontent.com/56491484/77840622-db1a7f00-715f-11ea-8f3a-b3de1581946d.PNG)
![foto 7](https://user-images.githubusercontent.com/56491484/77840624-df469c80-715f-11ea-8321-3fc7f77a1cd8.PNG)
![foto 8](https://user-images.githubusercontent.com/56491484/77840627-e2da2380-715f-11ea-8063-fb4d985978af.PNG)
![foto 9](https://user-images.githubusercontent.com/56491484/77840628-e66daa80-715f-11ea-865f-f094af6c5950.PNG)
![foto 10](https://user-images.githubusercontent.com/56491484/77840632-ecfc2200-715f-11ea-9258-613037c2543b.PNG)
![foto 11](https://user-images.githubusercontent.com/56491484/77840637-f5545d00-715f-11ea-94fb-295d9a47669c.png)

I hope it works for all of you

**Comment by JosefNemec** [comment]
Please post tutorials and other helpful information on our [forums](https://playnite.link/forum/). GitHub issue tracker is only for tracking of new features and bugs in the application.

Also there's far easier way how to set this up. Just drag and drop game's desktop shortcut, that BlueStacks creates, into Playnite's main window and Playnite will set the game up automatically.
