### ISSUE TITLE
Blank IGDB image prompt leads to Playnite freeze

### ISSUE THREAD

**Issue by RealityExit** [JosefNemec/Playnite#1721]
- Download metadata for The Witcher 2: Assassins of Kings (non-Enhanced Edition) from IGDB 

- Choose background image prompt is only populated with blank entries

- Make a choice, cancel, or close window

- Playnite is frozen

Closing Playnite with task manager while in this state doesn't seem to take and I have to kill it via command line.

I'm not sure if there's something weird going on with that specific IGDB page.

`a8e40173-7278-48a3-a8de-266753495b85`

**Comment by JosefNemec** [comment]
It's probably slow IGDB server that serves images (it happened in past multiple times). I'll need to make download run in different thread with an option to cancel it.

**Comment by JosefNemec** [comment]
Done in `devel8`.
