### ISSUE TITLE
Itch client version 25 or newer is not installed

### ISSUE THREAD

**Issue by Twombs** [JosefNemec/Playnite#1722]
I have installed Playnite for the first time, and when I click on Authenticate for Itch.io I get the following error message.
Itch client version 25 or newer is not installed.

**Comment by JosefNemec** [comment]
Try reinstalling itch client.

**Comment by Twombs** [comment]
Not sure I know how to do that, but will have another look.

**Comment by JosefNemec** [comment]
https://itch.io/app

**Comment by Twombs** [comment]
Thanks

**Comment by Twombs** [comment]
All solved, importing now.

**Comment by forenta** [comment]
Today I am in the same situation. Import ok for Xbox, Steam, GOG, Epic & Ubisoft Connect, but even though I re-installed the app, Playnite says that I'm >25.0.
Diagnostic ID 48374431-1bf2-4dac-8605-5ff1cb12326d.
![qr](https://user-images.githubusercontent.com/2451238/125163761-fbbceb80-e18e-11eb-9fbb-fa3a4842e3f8.png)

**Comment by JosefNemec** [comment]
Try reinstalling itch client. Registry keys we use to detect it are missing on your system for some reason.

**Comment by forenta** [comment]
A multiple reinstallation did not lead to the success, but I was able to track down the cause in the end: I use my Windows account without administration rights and only perform installations with administration rights, so the applications and games can be installed in C:\Program Files\[Name].

Playnite can't seem to do anything with the installation in C:\Program Files\itch. After an installation WITHOUT administrator rights - in C:\Users\[user]\AppData\Local\itch the scan and integration in Playnite worked without problems.

Maybe the registry entry ends up somewhere else and it can be a basis to solve the problem for third parties.

**Comment by PescheHelfer** [comment]
If you install it with an admin account but run playnite with your normal user, it won't detect it. Playnite looks for the uninstall entry to get the install location of itch. If installed with admin, the uninstall entry in the registry is in the admin account, so Playnite won't find it. As a workaround, you can export the following registry folder:
`Computer\HKEY_USERS\<admin>\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\itch`

open the exported file in an editor to replace the admin key with the user key, and then import the modified registry entry. You should now have: 
`Computer\HKEY_USERS\<user>\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\itch`

which can be detected by Playnite.

To get your admin and user keys, see here:
https://stackoverflow.com/questions/2919286/getting-the-username-from-the-hkey-users-values
