### ISSUE TITLE
Import Microsoft Store games library

### ISSUE THREAD

**Issue by Twombs** [JosefNemec/Playnite#1723]
The main reason I grabbed and installed Playnite, was the hope it would show me my games from the Microsoft Store library, as I have been unable to find a way of doing that in Windows 7.
Please can you support this?
P.S. I fully realize I cannot install those games to Windows 7, but as I often browse and buy while using Windows 7, it would be nice to be able to see a list of what I already have.
Cheers, and thanks for the impressive work that is Playnite.

**Comment by JosefNemec** [comment]
This is already supported via Xbox plugin.

**Comment by Twombs** [comment]
Is this a separate download (i.e. Unity plugin) or the builtin option I already tried with email and password?

**Comment by JosefNemec** [comment]
Built-in, if you disabled it during first time startup then you need to enabled it in Settings -> Extensions.

**Comment by JosefNemec** [comment]
I forgot to mention that it won't import any games on Windows 7, only Windows 10 is supported.

**Comment by Twombs** [comment]
ok. thanks. Is there any way to get a listing on Windows 7 ... any app you know of?

Would be a great feature to have.
