### ISSUE TITLE
While in game set Steam away status regardless if playing a Steam game or not.

### ISSUE THREAD

**Issue by rye-74** [JosefNemec/Playnite#1726]
I don't know if this is possible but I would love to see Playnite set the Steam 'away status' to whatever activity you are doing in playnite. For example If i launched SMB from playnite a non steam game, the playnite application sets the Steam 'away status' to something like "...playing SMB with Playnite". Of course being able to remove/reset status when your done with the game SMB would be needed as well.

**Comment by JosefNemec** [comment]
We could only change profile status (away, offline etc.), not set any specific message.

**Comment by JosefNemec** [comment]
Also this is such a specific scenario that I'm not sure it makes sense to add it as built-in feature into Playnite. I don't want to hard code any store specific features if it's possible. It should be already possible to create plugin that does the trick.

**Comment by rye-74** [comment]
Yeah I was thinking it could be done by a script but I can't code myself
out of a paper bag....soo no chance I could do this.

Also just wanted you to know that work is appreciated out here on the
internets. I spent the last two days organizing my collection just as I
wanted. Thanks for the great work.

**Comment by Bluscream** [comment]
https://partner.steamgames.com/doc/features/enhancedrichpresence

What about this? i mean worst case you could offer playnite through steam and get access to RPC from there :P

**Comment by JosefNemec** [comment]
Closing, this is not possible without serious hackery or Playnite being actually published on Steam.
