### ISSUE TITLE
Search from System Tray by Right-Click

### ISSUE THREAD

**Issue by zahroc** [JosefNemec/Playnite#1731]
I apologize if I  missed this already but a quick search did not turn anything up.

It would be nice to have the ability to search from the system tray by a right-click / search.
When looking at game sales, it would be beneficial to quickly search and see if I have that game already.

**Comment by ATNewHope** [comment]
Now that we have FlowLauncherExporter and QuickSearch, quick search is fully supported with a hotkey, I guess it's even quicker than click on system tray to search.
I guess you could close this issue If you're satisfied with the one of the two extensions above.
Also, if you're looking for game sales, try out IsThereAnyDeal extension.

**Comment by JosefNemec** [comment]
Playnite 10 added system wide [keyboard launcher](https://api.playnite.link/docs/manual/features/keyboardLauncher.html) so this is covered by that now.
