### ISSUE TITLE
Move translation effort to Weblate

### ISSUE THREAD

**Issue by comradekingu** [JosefNemec/Playnite#1733]
With how much targeted advertisement and tracking of users [Crowdin does](https://support.crowdin.com/cookies/). Having to be 18 to use it is also a deterrent. With Crowdin being closed source, and their blatant disregard for GDPR, I would much rather see Playnite on Weblate, or any service or platform that compares to it. I can contribute upstream, and translate it to nb_NO, I can also help administer it on Weblate.

Playtime qualifies for gratis hosting here https://weblate.org/hosting/ and the equivalent on Crowdin would require contribution to closed translation memory, and for the Playnite project to be non-commercial. Setting up a self-hosted instance with Weblate is also an option, but I think benefiting from the larger community, TM, and bigger pool and variety of projects on Hosted Weblate would do nicely.

This avoids #1730

**Comment by JosefNemec** [comment]
Closing, I currently don't see a good reason why to move to a different platform.
