### ISSUE TITLE
Support .pext properly as file extension

### ISSUE THREAD

**Issue by Bluscream** [JosefNemec/Playnite#1734]
- [ ] Implement required launch argument`Playnite.DesktopApp.exe "path/to/extension.pext"`
- [ ] Make required changes to registry on Installation/First Update with this change (https://stackoverflow.com/questions/2681878)

**Comment by JosefNemec** [comment]
Duplicate to #1584

**Comment by Bluscream** [comment]
Oh, yeah sorry
