### ISSUE TITLE
Desktop mode window opens "minimized" at first

### ISSUE THREAD

**Issue by fdutheil** [JosefNemec/Playnite#1737]
**Describe the bug**
After starting Playnite when you open it for the first time, its window "opens" but is not visible as it is still a normal minimized window: it only shows up in the taskbar.

**To Reproduce**
- Have Playnite 7.5 installed (7.4 is not affected)
- Settings: 
  - start minimized is **enabled**
  - run when computer starts is **enabled**
  - minimize to systray is **enabled**
  - close to systray is **enabled**
- close playnite if it's running
- start playnite
- open playnite (doubleclick or right-click -> *open playnite* on its systray icon)
- it only shows the window in taskbar, not on the desktop (as if the window is minimized but not to systray).
- click on taskbar to get the playnite window to finally show up (un-minimize)

**Comment by JosefNemec** [comment]
Fixed by 7713b4f347ce19fc8bc60da5bb7a6b54e7fc8478 in `devel8`.
