### ISSUE TITLE
Crash when trying to set categories to multiple games over categories when selecting with Shift

### ISSUE THREAD

**Issue by Arattor** [JosefNemec/Playnite#174]
When selecting multiple games over multiple categories using Shift like below:
![like here](https://user-images.githubusercontent.com/15693467/31403987-14cff53e-adfb-11e7-877c-ec3595ac35bd.png)

and trying to add them to a category, Playnite crashes. I'm guessing it's thinking of the category itself as a game entry and trying to add it as well. Diag package below:

[diag package.zip](https://github.com/JosefNemec/Playnite/files/1373012/diag.package.zip)

**Comment by JosefNemec** [comment]
Released in 2.5
