### ISSUE TITLE
Origin game, Dragon Age II, doesn't launch game, missing DLL

### ISSUE THREAD

**Issue by sengtsan** [JosefNemec/Playnite#1742]
When I try to launch origin game Dragon Age II from playnite, I get the following message:

"missing required file ssleay32.dll"

I had a look to see if it was there. I found it in:

M:\Games\Origin\Dragon Age II\bin_ship\Core

The drive is a dedicated SSD for games and not the boot drive. 

Dxdiag: 

36f8970c-760a-46fc-9dae-ac5d2d2fa3d7

I don't know if this is relevant but I will mention it anyway. I previously played this game on origin access. I then purchased the game outright. As the game didn't work I remove and re-added the entry from Playnite in the hope that would fix the issue. 

I removed the game and readded it via the update library option but it didn't fix the issue. 
![errorscreen](https://user-images.githubusercontent.com/63714826/79326026-12cc4980-7f0a-11ea-9a60-a189cdd1c064.jpg)

(So far, I am impressed with the launcher)

**Comment by JosefNemec** [comment]
So while you had the game only via Origin Access, it did start properly from Playnite? And then it started failing to launch once you purchased it?

**Comment by sengtsan** [comment]
It was some time ago since i was subscribed, but I don't believe I ever
tried to launch dragon age II through Playnite while I has access; however
the game was added to the playnite library for the first time during that
time.

Other games which were on origin access worked fine (e.g. Ghost of a tale,
dragon age inquisition)

**Comment by JosefNemec** [comment]
I managed to replicate it on my system.
Until the patch is released, this is how you fix it:
- edit the game
- go to Actions tab and uncheck "managed by library plugin"
- change Path to `DragonAge2.exe` and Working Directory to `{InstallDir}\bin_ship`
- check "managed by library plugin" and save changes

**Comment by sengtsan** [comment]
That did it. Thank you. Great program. Appreciate the fast resolution.

The best launcher on PC that I've tried (i.e. better than GOG and
launchbox), and deserves more support in the PC space

**Comment by JosefNemec** [comment]
Fixed in 7.6

**Comment by sengtsan** [comment]
Thank you kindly. Do i need to undo the manual amend, or can i just leave
it?

**Comment by JosefNemec** [comment]
No you don't, you can leave it as is.

**Comment by RikudouSage** [comment]
@JosefNemec How can I do this in the latest version? I'm facing the same issue (except it's the EA app).
