### ISSUE TITLE
Fullscreen not returning to complete fullscreen after exiting game

### ISSUE THREAD

**Issue by shaikio** [JosefNemec/Playnite#1743]
I've been using this in fullscreen and I noticed if I exit a game I'm playing that when Playnite pops back up it's not quite fullscreen. The taskbar ends up over tpp of the bottom of the app and and it doesn't quite reach the top of the screen anymore. The only way to fix it is to restart Playnite or to switch to desktop view and back to fullscreen.

**Comment by JosefNemec** [comment]
Are you using 7.5 version? This was specifically fixed there.

**Comment by shaikio** [comment]
Yes I am using 7.5.
  

  
  

  
  
>

**Comment by JosefNemec** [comment]
Can you please make a video of the behavior? Also go to Desktop mode and generate diagnostics package for me from "About Playnite" menu. Thank you

**Comment by JosefNemec** [comment]
Requested information not provided => closed.
