### ISSUE TITLE
No-intro, Redump and the like as metadata source and ability to name games.

### ISSUE THREAD

**Issue by genova447** [JosefNemec/Playnite#1744]
I need to give an example of what I have in mind, I think, to explain the latter part of my request.

Just today I bought Atari Vault and its DLC on steam, and added those games to Retroarch/MAME, first running them through some DAT files with the help of ClrMamePro.

However some of the games in that bundle are arcade games, and unlike home-consoles games, the naming convention for Arcade game seems a bit more 'ugly', ending up with names such as "montecar" for the game Monte Carlo, as an example.

However, importing these games named thusly into Retroarch, made the name appear in Retroarch properly, as "Monte Carlo" - in spite the file name is "montecar".

I assume this is because of the database they have, in-Retroarch, make sure to contain data to define a 'pretty name'.

So I was wondering if Playnite could perhaps implement this functionality too - as currently said game was imported as 'montecar', as is the filename.
 
some of the databases that Retroarch specifically uses are listed here: https://github.com/libretro/libretro-database/blob/master/README.md

---

Please, whoever knows more about this, and understand better what I'm trying to say, or how to properly implement it - please do correct and clarify (assuming it's of interested to you as well of course) : o

**Comment by JosefNemec** [comment]
This will be done as part of #653
