### ISSUE TITLE
Cover UI Elements Scaling Improperly

### ISSUE THREAD

**Issue by MrMendelli** [JosefNemec/Playnite#1745]
As discussed on the Discord server, the play and info buttons in grid mode display very pixelated. This happens regardless of the following:

- Desktop resolution
- DPI scaling
- Library zoom

My desktop resolution is 1920x1080 @ 125% DPI scaling. Adjusting to 100% scaling bears little to no difference.

Diagnostic package ID: `df6aab7d-ae86-4149-a1ca-c8dfa1705eae`

**Comment by JosefNemec** [comment]
As we discussed this on Discord, I don't think this is an issue in Playnite. I can't replicate this on any of my systems and other users don't seem to be having this issue either. If I manage to replicate it somehow then I'll look into it, but at this point I don't think there's anything I can do about it.

**Comment by MrMendelli** [comment]
No problem, this was more for the purpose of your request and to document the event.

**Comment by JosefNemec** [comment]
After some additional investigation on Discord, we've found that it was caused by incorrect text formatting setting in Playnite. Switching to default fixed it.
