### ISSUE TITLE
Uninstalled Cover Darken Not Working

### ISSUE THREAD

**Issue by MrMendelli** [JosefNemec/Playnite#1746]
I have enabled the `Darken uninstalled games` option for my library, the covers for uninstalled games appear no darker or brighter than covers for installed titles.

![Untitled-1](https://user-images.githubusercontent.com/47702158/79438375-af392f00-7f90-11ea-86bc-4153af172c93.png)
_(Seen left: BioShock 2 is uninstalled, but is not noticeably darker than BioShock 2: Remastered)_

Diagnostic package ID: `df6aab7d-ae86-4149-a1ca-c8dfa1705eae`

**Comment by JosefNemec** [comment]
Can't reproduce. Are you using custom theme?

**Comment by JosefNemec** [comment]
Never mind, I checked the diag. package and you are using SteamNite theme. This means that the theme doesn't respect the config value and that theme must be fixed.

**Comment by MrMendelli** [comment]
Well, why aren't themes overwritten for this feature? It's a global Playnite setting, so the theme being different shouldn't matter.

**Comment by JosefNemec** [comment]
We just can't inject new elements to unknown themes to enforce new features. Views can be completely reworked by the theme and we could break it. 

I always put together list of changes that need to be made when new feature is added and it requires theme file update. Then it's up to theme creators if they update it or not, I can't force to do so.

**Comment by JosefNemec** [comment]
I also forgot to mention. If theme doesn't change affected file (in this example Grid item style files) and is also properly packaged via Toolbox tool (not just manually by dumping all xaml files into archive), then those new features are inherited and will work.

**Comment by MrMendelli** [comment]
Interesting, I assumed that control of the UI was more restrictive with themes. I will take this into consideration going forward, thank you for the insight on the matter.

**Comment by sjgold** [comment]
Hi I am having a similar issue where the grid view in the default desktop view is not darkening when the item is uninstalled on steam.
https://imgur.com/a/rTYiRky

**Comment by JosefNemec** [comment]
@sjgold Do you have the feature enabled in application settings? It 100% works with default theme.

**Comment by sjgold** [comment]
I believe so...
[https://imgur.com/a/cvaSTgs](url)

**Comment by sjgold** [comment]
Ok this is weird maybe I don't understand whats going on or there is a deeper issue check this out. Its showing I have 0 games uninstalled but thats not the case i just uninstalled a bunch of games from steam. 
https://imgur.com/a/t23fv39

**Comment by JosefNemec** [comment]
You need to have import of uninstalled games enabled, otherwise install state won't be synced properly (or you have to initiate uninstallation from Playnite, not Steam).
