### ISSUE TITLE
API calls doesn't work properly

### ISSUE THREAD

**Issue by Skyline404** [JosefNemec/Playnite#1747]
```
$wshell = New-Object -ComObject Wscript.Shell
function global:OnGameStarted()
{
    param(
        $game
    )

    $wshell.Popup("Game started",0,"Done",0x1)
}

function global:OnGameStopped()
{
    param(
        $game,
        $elapsedSeconds
    )

    $wshell.Popup("Game closed",0,"Done",0x1)
}
```
Want: pop-up window on start / close events.
Have: nothing.

> Script for all games on pre-start.
> I did reload playnite.

**Comment by JosefNemec** [comment]
Works for me. What OS and PowerShell version do you have? What error message are you getting?

You can also use Playnite's built-in [dialog API](https://playnite.link/docs/api/Playnite.SDK.IDialogsFactory.html). For example:
`$PlayniteApi.Dialogs.ShowMessage("test")`

**Comment by Skyline404** [comment]
> Works for me. What OS and PowerShell version do you have? What error message are you getting?
> 
> You can also use Playnite's built-in [dialog API](https://playnite.link/docs/api/Playnite.SDK.IDialogsFactory.html). For example:
> `$PlayniteApi.Dialogs.ShowMessage("test")`

Windows 1903
PowerShell v5

**Comment by JosefNemec** [comment]
You don't paste this to global scripts. If you want to use `OnGameStarted` and other game events, you actually have to create script extension (with extension manifest and everything).

If you use game scripts then just add following to pre/post sections:
```
$wshell = New-Object -ComObject Wscript.Shell
$wshell.Popup("Game started",0,"Done",0x1)
```

**Comment by Skyline404** [comment]
> You don't paste this to global scripts. If you want to use `OnGameStarted` and other game events, you actually have to create script extension (with extension manifest and everything).
> 
> If you use game scripts then just add following to pre/post sections:
> 
> ```
> $wshell = New-Object -ComObject Wscript.Shell
> $wshell.Popup("Game started",0,"Done",0x1)
> ```

Ok, thx, will try
