### ISSUE TITLE
Custom Cursor Support In Themes

### ISSUE THREAD

**Issue by xyifer12** [JosefNemec/Playnite#1749]
**Describe the solution you'd like**
I would like for themes to be able to use a custom .cur file so that custom cursors can be set in the theme. 

Blend has a selection box with a list of cursors from PresentationCore.dll, ideally this list would include cursors from the theme files as well.

**Comment by MrMendelli** [comment]
Using a true cursor format may be a bad idea in my opinion, making them properly is like making icons properly. In order for them to scale correctly they need to be made into a cursor group. It may be more ideal to use a network graphic _(.png)_ and choose a static minimum size then downscale based on settings.

**Comment by JosefNemec** [comment]
Using anything but .cur or .ani would be a bit problematic. However, I think I can add a system that would internally convert png to cur if the theme uses png.

**Comment by xyifer12** [comment]
Cursor files have a set hotspot, this is where the pointer is selecting. Hotspots are represented with X and Y values. Image files are not a valid replacement for .cur files and cannot just be converted.

**Comment by JosefNemec** [comment]
We can just set hotspot for image cursors to center of the image and theme author has to take that into account. CUR format should still be preferred format, but I don't see why we couldn't add png as fallback format with some limitations.

**Comment by xyifer12** [comment]
The hotspot is defined as the distance from the top left corner. Treating the center of a PNG as the hotspot does not work because the resolution is variable.

**Comment by JosefNemec** [comment]
That's easy to calculate based on size of the image.

**Comment by JosefNemec** [comment]
Done in P9.
