### ISSUE TITLE
Playnite Fullscreen gamepad problem

### ISSUE THREAD

**Issue by GreenRabbits** [JosefNemec/Playnite#1754]
When I launch some games through Playnite Fullscreen, Playnite remains controllable during the gameplay, whereas it is minimised. I already accidentally ran another game while I was playing the first, because Playnite Fullscreen was running in background, taking into account the gamepad buttons.

**Comment by JosefNemec** [comment]
I can't reproduce it. Can you provide exacts steps how to make this happen? Does this happen with all games or just some (which exactly if that's the case)?

**Comment by GreenRabbits** [comment]
I think that Antimicro software (that I use to assign the guide button on my gamepad to launch playnite fullscreen) intereferes with Playnite Fullscreen. When I press it accidentallly during a gameplay, it opens Playnite Fullscreen in bakground.The problem is that Playnite remains still controllable in background (for example, when I press X button in a game, it launches the game selected in Playnite, in background.

**Comment by JosefNemec** [comment]
If you focus Playnite using 3rd party software, while playing the game, then I don't think there's anything I can do about it. This is IMHO problem with your setup.

**Comment by GreenRabbits** [comment]
ok

**Comment by JosefNemec** [comment]
I'm closing this since it's caused by 3rd party and I have no idea how would I even "fix" this. If some app forces Playnite to open, then it will open and take focus.
