### ISSUE TITLE
Windowed Borderless mode is extremely necessary.

### ISSUE THREAD

**Issue by kremuwakarz** [JosefNemec/Playnite#1757]
Because seeing ugly desktop every time when launching a game is atrocious. Its due to Playnite minimizing during game launch.
Good behavior example is: Steam bigpicture mode, Launchbox/Bigbox

**Comment by JosefNemec** [comment]
Playnite already runs in borderless window mode. The minimizing is done to prevent issues where games are not getting input focus after we launch them (I think MS Store games were especially affected by it).

We can't change it for compatibility reasons. If you don't want to see desktop, then hide your desktop icons and remove wallpaper.
