### ISSUE TITLE
Allow Themes To Buttonize Menu Options

### ISSUE THREAD

**Issue by xyifer12** [JosefNemec/Playnite#1758]
**Describe the solution you'd like**
Make all context menu options from the main menu available to theme creators as stand-alone buttons.

See this Settings button example.
![WIP](https://user-images.githubusercontent.com/33806276/79641517-9cc02080-815d-11ea-9af9-0be4664caf25.png)

**Comment by JosefNemec** [comment]
Sort of same as #1463

**Comment by JosefNemec** [comment]
Will be done via #1759
