### ISSUE TITLE
Pick a random game - go to library page

### ISSUE THREAD

**Issue by Gerren** [JosefNemec/Playnite#1762]
Hi there,

I love the feature to Pick a random game. But I would like to select the rolled game in the library, so I can edit, check wheter it is installed, what library it is in, or such.

I personally do not see need to add a special button. Either change "Play" to "Go to", or simply link the cover image as a link to the game. Potentially a "..." button. I saw no button, so I naturally clicked the image in anticipation of selecting it in the library. No luck.

Only edge case is, when there is a "Limit selection to current filter" unchecked, and the random game is not included in the mentioned current filter.

Cheers,
Vašek

**Comment by trillex** [comment]
I am seconding this, not sure if you like these "bumps", Crow or how you want to gauge interest.

**Comment by JosefNemec** [comment]
Done in devel via 11e6c8ff0cc0044ea3e4592f5f44a127d7377184
