### ISSUE TITLE
Humble Account Authentication Issue

### ISSUE THREAD

**Issue by MrMendelli** [JosefNemec/Playnite#1763]
Whenever Playnite opens I get an authentication problem with my Humble Bundle account. I verified this account with the library import wizard and it is the only account I have this problem with. Seen in the clip below, I get the notification but upon checking the issue Playnite changes the account authorization upon viewing the import dialog for Humble. I have re-installed Playnite and connected and imported my Humble account as well and the problem persists.

![clip](https://user-images.githubusercontent.com/47702158/79814291-19f4bc80-833b-11ea-9b62-d73e30c7cc48.gif)

Diagnostic ID: `294392bc-0c95-4ce7-a0ac-580f4a1c9b0b`

**Comment by Bluscream** [comment]
![image](https://user-images.githubusercontent.com/3318223/79842856-b3fb4a00-83b9-11ea-8b90-d12da9d645fb.png)

I have the same problem with BattleNet but i think it's something with my network/firewall/adblocker/dns so i won't report it

**Comment by JosefNemec** [comment]
For battle.net [see this](https://github.com/JosefNemec/Playnite/wiki/Battlenet-troubleshooting#authentication-being-lost-after-some-time).

**Comment by JosefNemec** [comment]
Can you please reproduce it again with [this version](https://github.com/JosefNemec/Playnite/files/4509037/HumbleDebug.zip) of Humble plugin and generate new diag. package?

**Comment by MrMendelli** [comment]
I was able to, here is my diagnostic ID: `a31010c5-5618-4f1f-9892-76c9aedc673e`.

**Comment by JosefNemec** [comment]
I'm getting some weird messages in logs, do you actually have any games in library or just subscription? Does [this page](https://www.humblebundle.com/home/library?hmb_source=navbar) show any games on `Library` tab when opened via browser?

**Comment by solsticesurfer** [comment]
Sorry to post this here and create noise but GitHub doesn't provide a way to DM someone. @MrMendelli, would you mind sharing the name of the program that you used to create the animated screenshot?

**Comment by MrMendelli** [comment]
> 
> 
> I'm getting some weird messages in logs, do you actually have any games in library or just subscription? Does [this page](https://www.humblebundle.com/home/library?hmb_source=navbar) show any games on `Library` tab when opened via browser?
I do not have any games purchased through my account yet. This would explain the errors you are getting. Apologies, I would have mentioned this if I knew it might have been a cause for account authentication problems.



> 
> 
> Sorry to post this here and create noise but GitHub doesn't provide a way to DM someone. @MrMendelli, would you mind sharing the name of the program that you used to create the animated screenshot? That would be very helpful to have when filing bug reports. Thanks!

I use [ScreenToGif](https://www.screentogif.com/) @solsticesurfer.

**Comment by Bluscream** [comment]
I can also suggest ShareX

**Comment by JosefNemec** [comment]
@MrMendelli That explains it then, thanks for clarification.

**Comment by solsticesurfer** [comment]
Thank you!

**Comment by JosefNemec** [comment]
Done in `devel8`.
