### ISSUE TITLE
Ability for plugins to intercept game starts

### ISSUE THREAD

**Issue by Bluscream** [JosefNemec/Playnite#1765]
**Describe the solution you'd like**

Either by changing the OnGameStarting event's return type to boolean and letting the plugin handle it completely like this:
![](https://cdn.discordapp.com/attachments/699577276571975760/702066459026784366/image.png)

Or by letting the plugin modify the Game instance and then starting that modified instance:
![](https://cdn.discordapp.com/attachments/699577276571975760/702066801240178719/image.png)

**Comment by JosefNemec** [comment]
Will be done via #1852
