### ISSUE TITLE
Export library in various 'formats' (ex. import into Nvidia Shield/GameStream)

### ISSUE THREAD

**Issue by genova447** [JosefNemec/Playnite#1769]
Initially I had in mind that it could be neat if I could quickly, export my whole Playnite library, with games from places like Steam and games-booting-in-emulators both.

In the case given in the title, Nvidia Shield/GameStream/whatever-it-be-called has a folder in "C:\Users\[UserName]\AppData\Local\NVIDIA Corporation\Shield Apps" where you simply put shortcuts/.ink-files, and it will work with the likes of Moonlight (https://github.com/moonlight-stream) - that is, rather than going through the GeForce Experience interface to add files one-by-one.

I do believe there is an AMD equivalent of all that - but I have no idea if it works similarly, in the case of how to add games to their system

Of course, this specifically would be unnecessary in case one day #883 might happen.

And of course, it might be unwanted to bloat Playnite with too many niche in-built functions, so maybe this is more a thing that should be added as a plugin if someone knows how to do that.

Additionally: For me personally, I'd like those 'exportable' files to by default use the Playnite 'URI'/API/thingymajing.

(Sorry for spamming 'feature requests')

---

This could maybe also be a thing to directly 'interface' with programs (or their unique way of keeping a database) that have their own way to import games, such as Steam.
There is Steam Rom Manager (https://github.com/doZennn/steam-rom-manager) - but it doesn't quite do everything Playnite can do - so it could be cool if Playnite could 'export' all non-steam games back into Steam, in the manner that Steam Rom Manager does.
I know there is a plugin that can technically do this already, even batch export everything (https://github.com/bburky/playnite-non-steam-shortcuts) but it also changed the default play action to play through Steam, while what I would propose, is really just the functionality of Steam Rom Manager, but with the added 'ability' of Playnite - Not at all touching anything in Playnite, just exporting - but perhaps this is rather something I should request from the one who made that plugin?

Mind you, I get the impression that anything akin to Steam Rom Manager is always a bit 'risky' in that it isn't per se meant to be tampered with, but people found a way to do it - I don't know if it can be assured that Valve wouldn't suddenly change how their system works, breaking such an implementation, and/or perhaps ruining peoples' libraries in Steam. (They already changed the system once before which interfered with SRM if I recall correctly)

There was talks of some of this in #760 as well, but I don't think it's covering exactly the same things.

**Comment by JosefNemec** [comment]
This should be done (and can already be done) as a plugin. There are way to many different formats and it's not really possible to support all of them (or even fraction of them) given how limited development resources on Playnite are. I'm closing this because of that (this repository should track features being built natively into Playnite).

 Feel free to open thread on discord or forums asking if somebody is interesting in making this.

**Comment by darklinkpower** [comment]
Done as an extension, you can check it here: https://playnite.link/forum/thread-252.html
