### ISSUE TITLE
Sort by installed lists uninstalled first

### ISSUE THREAD

**Issue by CaptainCow95** [JosefNemec/Playnite#177]
Sorting games by installed ascending makes it so that the games are listed in alphabetical order, but the uninstalled games come before the installed games, making me have to scroll to the bottom to see what games I have installed. By switching the order to descending, I get what I would expect from that sort, with installed games coming first, in reverse alphabetical order. With sorting by installed, I would always expect the installed games to be listed first, or at least have an option to make that happen, with the actually sort happening on the installed and uninstalled lists independently.

**Comment by JosefNemec** [comment]
Released in 2.5
