### ISSUE TITLE
Twitch not in sync

### ISSUE THREAD

**Issue by leobenkel** [JosefNemec/Playnite#1770]
**Describe the bug**
When the library synchronize with Twitch it does not add any of the new games anymore. I am not sure when it started but recently, I just claimed new free games on Twitch but they did not get added to Playnite after sync. 
No error and it is marked as authenticated in the settings. 

**To Reproduce**
Claim a game on Twitch, update libraries in playnite, the game is not there..

**Comment by JosefNemec** [comment]
Do you get some error or anything? Is the game detected if you install it? Please also go "About Playnite" menu and generate diagnostics package for me.

**Comment by JosefNemec** [comment]
No response => closing.
