### ISSUE TITLE
Xbox One controller doesn't work in fullscreen mode on Windows 10 LTSC 2019

### ISSUE THREAD

**Issue by samiscool51** [JosefNemec/Playnite#1771]
**Playnite Version**
7.6

**Check for existing issue**
checked, no-one else is having this issue (to be fair it's a very special issue)

**Describe the bug**
my Xbox One Controller (either via bluetooth or USB and is Xinput compatible) does not work with playnite in fullscreen mode. i know it's not the controller or the OS as other applications and games work fine and can detect and use it as if nothing is wrong.
it's playnite that has the issue. i also tried an Xinput emulation application to try and see if it could see that but no luck.
i have verified that it works on my main desktop running windows 10 pro (both with USB and bluetooth).
i don't know why other applications and games work fine but playnite doesn't, i've done all that i can trying to fix the issue but it looks like playnite is refusing to play ball. (HA! i'm very funny...)
since there is no way of knowing the status of connected controllers (note: this should probbly be added into full screen mode to help diagnose future issues like this but thats not important right now), i don't know what is going on, even the log won't tell me anything about connected controllers.

**To Reproduce**
1. have a system with Windows 10 LTSC 2019
2. install playnite and setup it up for a super simple setup
3. connect controler
4. start fullscreen mode
5. fullscreen mode doesn't work with controler
6. lie down
7. try not to cry
8. cry
(note: steps 6-8 are not required and not recommended, don't ask me how i know)

**Screenshots**
N/A

**Diagnostics ID**
N/A

**Comment by JosefNemec** [comment]
Please go to "About Playnite" menu in Desktop mode and generate diagnostics package for me.

I don't have LTSC license so I can't test this on my own, but I don't even know if I would be able to fix it somehow. We just pull XInput interface for status of connected controllers.

**Comment by samiscool51** [comment]
09ea81a8-30aa-4bdd-8ac7-83d62401b4db
sorry for not adding it eairler, your bug report template lead me to believe that it was meant for crashes and really didn't tell me that i needed to do it within playnite

**Comment by samiscool51** [comment]
> I don't have LTSC license so I can't test this on my own,
microsoft allows you to download a trial here: https://www.microsoft.com/en-us/evalcenter/evaluate-windows-10-enterprise
just make sure you select the "ISO - LTSC" option as i haven't in the past and it's very annoying to find out that you downloaded and installed the wrong version! yay!

**Comment by JosefNemec** [comment]
Thanks for the link. I installed evaluation version and I can't reproduce the issue. I just installed Firefox and Playnite, and controller works properly in Fullscreen mode (wired 360 one, but that shouldn't matter since all MS controllers are native XInput compatible).

I don't see any errors in the logs related to input, I have no idea why it doesn't work for you.

**Comment by samiscool51** [comment]
i don't know either man, i'm gonna try and see if i can convert it to a pro system manually, thanks for your help
