### ISSUE TITLE
Error for Valorant

### ISSUE THREAD

**Issue by Kaouran** [JosefNemec/Playnite#1773]
For launch game is RiotClientServices.exe
Not auto detect, and imposible to launch with Playnite

Error launch game directly

![image](https://user-images.githubusercontent.com/58531220/80307826-cfa48d00-87cb-11ea-9dcc-52b6a2c812ca.png)

72334a1f-9f89-424f-b843-8a7277e81f90

**Comment by JosefNemec** [comment]
Drag and drop Valorant shortcut to Playite and it will configure the game properly:
https://www.reddit.com/r/playnite/comments/g4efmn/launching_valorant/fnznozz/
