### ISSUE TITLE
Icon for titles with controller support in fullscreen mode

### ISSUE THREAD

**Issue by Pixxel123** [JosefNemec/Playnite#1775]
Would be really handy to have an icon added to the boxart in fullscreen mode for games that have controller support.

(Realised we already have support for filters in fullscreen, edited)

**Comment by JosefNemec** [comment]
I don't think this is possible because controller support field can be named differently in everyone's library (it's just a string pulled from game store or named by an user). Plus user can easily rename it to their native language, which would break this further.

**Comment by Pixxel123** [comment]
Fair point! Will close this out!
