### ISSUE TITLE
RFE: Use external browser to sign in to external services

### ISSUE THREAD

**Issue by fowl2** [JosefNemec/Playnite#1776]
It would be great that if, instead using a a webview to handle sign in (eg. Epic, Xbox), my regular browser - where I'm already signed in - could be launched.

The allowed redirect urls for each oauth client registration would have to be augmented with localhost and/or protocol handler and then the corresponding protocol handler or loopback webserver implemented. A barebones inproc web server is probably the most self contained - eg.  start up a [WebListener](https://docs.microsoft.com/en-us/dotnet/api/microsoft.net.http.server.weblistener), wait for the token, then shut it down again.  

Could use Kestrel if you want to go more modern and you're ok pulling in half the ASP.NET universe.

**Comment by JosefNemec** [comment]
That would be way too complicated and less reliable compared to current implementation and I don't really see much benefit in it compared to the amount of implementation and maintenance effort it would require.

**Comment by fowl2** [comment]
Fair enough, I was actually really impressed by how compact and straight forward the existing code was.

The 5 sets of sign in dialogs during onboarding were a big enough barrier for me to give up so I thought if it was overwhelming for me, others would be missing out too.

(I then subsequently spend an hour reading the code and getting it to build - investigating the feasibility of what I wrote - funny how the brain works, huh?)

Thanks again for your time =)

**Comment by JosefNemec** [comment]
We could technically try and get tokens from browser cookies, but that would only work for some libraries.

The other limitation of your suggestion is that all library integrations are implemented as completely separate plugins. We would have to implement this for each and every single one separately.
