### ISSUE TITLE
Art Library Import

### ISSUE THREAD

**Issue by mike090682** [JosefNemec/Playnite#1777]
Would it be possible to have a function to import own cover/background art per game? 

The function would look in a specific folder for art work matching the title of the game and use that instead of downloaded artwork.

Thanks 

Mike

**Comment by JosefNemec** [comment]
You can already write a custom script extensions for it. I'm not sure it makes sense to have this as built-in feature since it's very specific use case.

**Comment by mike090682** [comment]
Hi, thanks for the speedy response. I have tried with your guides to make a script but I really dont have a clue :( . Could I please ask for your help in creating one? Any help would be appreciated as I have over 15000 retro games I want to use my own art work for.

Regards

Mike

**Comment by JosefNemec** [comment]
I currently don't have time to write code examples, but this is what you need to do:
- read file names of your covers
- find appropriate game in Playnite's library (based on the cover name)
- add cover file to library
- assign added file to a game
- update game in library

I recommend using PowerShell as it's IMHO easier for beginners. If you have additional questions then I recommend joining our Discord server, maybe somebody else would be able to help you more.
