### ISSUE TITLE
Request for Batch Download of Metadata

### ISSUE THREAD

**Issue by Ayaneko** [JosefNemec/Playnite#178]
After installing Playnite and having it pull all of the games and game images from steam, gog, uplay, and origin, I found several items without images, so I looked at each and found within the Edit option that there is an option to download metadata for a game. This feature works great and I was able to replace the missing images and info for the few games that did not gather it from steam for whatever reason. But I really like the images from IGDB much better as they fill the entire panel and look much nicer. Easier to identify, etc. 

I know that when you select IGDB it brings up a list of games and asks you to choose one, and that this may be why you have not already included a batch import of metadata, but in every instance it was the first game in the list, so it seems that 99% of the time it is able to locate the correct game info without actually needing input from the user.

My suggestion is to allow for batch import of game metadata from IGDB, and maybe during the process, if it does not find an exact match for the game title it is currently processing, it then pops up a list for the user to choose from, else it continues to pull in the info for your entire library.

If there is an issue with hitting IGDB repeatedly to gather this info, I am sure a brief pause can be coded into the import process and most users would be happy to wait, and have a much better display of their games, without having to manually update each one.

I may be a bit out of the ordinary with a library of 330 games and counting, but I am sure there are enough people out there like myself that would really enjoy having the option to mass import metadata for a much better game management experience.

EDIT: I see there is a request for scaling the cover image to fill the panel (Cover size #162), and you have it marked as "Scale Covers on Height". I should point out this is a bad idea, as scaling the image by height (while keeping the image proportions) to fill the panel is going to crop the image and look horrible. In most cases it will cut off the name of the game, etc. since their is no consistency in the placement of text in game banners. IGDB still seems to be the way to go. My two cents.

So far the app looks very promising. Thank you for your hard work!

**Comment by JosefNemec** [comment]
Already requested in #129
