### ISSUE TITLE
Hotkey for the "Сhoose Сategory" feature

### ISSUE THREAD

**Issue by nnbc** [JosefNemec/Playnite#1782]
Hello. Can you add a hotkey for "choose category" option? I very often use it and it's annoying to use right click button on the mouse every time. Screenshoot included.
![Безымянный](https://user-images.githubusercontent.com/64670053/80850891-7a370880-8c2f-11ea-807c-0feb8a029663.png)

Thx. Sorry for my bad English.

**Comment by JosefNemec** [comment]
Duplicate to #1594
