### ISSUE TITLE
pcgamingwiki metadata plugin

### ISSUE THREAD

**Issue by SeeDborg** [JosefNemec/Playnite#1784]
Would it be possible to add a field for the number of players for every game ?
It can be retrieved on pcgamingwiki, for example : https://www.pcgamingwiki.com/wiki/BattleBlock_Theater#Multiplayer_types

In my opinion we would need the 3 infos, for example a game could be played at 4 locally, 12 on LAN and 12 online. So... 3 fields ?

**Comment by JosefNemec** [comment]
I don't think we need another field for that. You can already assign those as tags or features.

**Comment by SeeDborg** [comment]
That's what I did but I have hundreds of game and have to do it one by one.

**Comment by JosefNemec** [comment]
Then what you want is basically pcgamingwiki metadata plugin. I currently don't have plans for adding any new metadata plugins myself, but maybe someone from community will create one.

**Comment by SeeDborg** [comment]
I just discovered thiswebsite and it seems more complete : https://playco-opgame.com
Maybe it's best to develop a plugin for this one?

**Comment by Bluscream** [comment]
https://playnite.link/forum/thread-238.html

**Comment by xxylem** [comment]
IGDB does seem to have this information, at least for some games, in a section called Multiplayer Modes. Look at for example, [the entry for Overcooked 2](https://www.igdb.com/games/overcooked-2):
![image](https://user-images.githubusercontent.com/35666594/84190095-405aec80-aa8e-11ea-84d2-d3273f7a778f.png)
[Here is the same section for Videoball, currently in a bad state](https://www.igdb.com/games/videoball):
![image](https://user-images.githubusercontent.com/35666594/84190226-8021d400-aa8e-11ea-87d4-6f514db4d0d4.png)

Not all games have this data, but for those that do, [this data seems to be accessible through IGDB's API.](https://api-docs.igdb.com/#multiplayer-mode) 

I agree that quickly being able to find games that support (e.g.) four players with controllers would be nice.

**Comment by JosefNemec** [comment]
Closing, I don't have resources to support another built-in metadata plugin. Can be created as a custom metadata plugin if anybody has time to do it.

**Comment by Clusters** [comment]
Wanted something similiar like the Author and stumbled over this issue.
I forked from @Bluscream and added local multiplayer tagging.

If someone is interested. Following tags are added, if the game supports local multiplayer:
Local Multiplayer
Local MP Mode: <Mode Name>
Local MP Playercount: <number of players>

https://github.com/Clusters/Playnite-PCGW/releases/tag/0.2

**Comment by Bluscream** [comment]
Sorry for my silly commit messages and thanks for picking up the project. I saw you removed my engine tagging (which might be a good thing because there's https://github.com/darklinkpower/PlayniteScriptExtensions/tree/master/Extensions/GameEngineChecker now. I would prefer this to be handled by a MetaDataprovider though so if you want you can create a setting page for it and just make the 3 new tags toggable instead of having to chose one.

**Comment by JosefNemec** [comment]
Please don't comment on closed issues, especially if it's not related to Playnite's built-in functionality. Use issue reporting for related extensions.

**Comment by SeeDborg** [comment]
> 
> 
> Wanted something similiar like the Author and stumbled over this issue.
> I forked from @Bluscream and added local multiplayer tagging.
> 
> If someone is interested. Following tags are added, if the game supports local multiplayer:
> Local Multiplayer
> Local MP Mode: {mode name}
> Local MP Playercount: {number of players}
> 
> https://github.com/Clusters/Playnite-PCGW/releases/tag/0.2

Thank you so much ! I'll test it today :)
