### ISSUE TITLE
Keep display settings for each category

### ISSUE THREAD

**Issue by SeeDborg** [JosefNemec/Playnite#1785]
It's a feature I like in GOG Galaxy 2.0 and I would love to see it in Playnite : when you create a category, and set display settings for it (covers size / how to sort), it keeps it so the next time you go in the same category you find those exacts settings again.

For example, I love to see a list sorted by name for my favorite games, but I prefer seeing a grid display sorted by last played for my "games of the moment" !

**Comment by JosefNemec** [comment]
Will be done via #590
