### ISSUE TITLE
Installing a theme that contains a point "." makes Playnite delete all other existing themes

### ISSUE THREAD

**Issue by darklinkpower** [JosefNemec/Playnite#1786]
**Describe the bug**
Installing a theme that contains a point "."  in the `name` in it's manifest makes Playnite delete all other existing themes or themes directory

**To Reproduce**
Install a theme that contains a `.` in the `name` in it's manifest. Example of manifest:
```
Name: SwitchNite 2.0
Author: Le Malgache
Version: 2.0
ThemeApiVersion: 1.4.1
Mode: Fullscreen
```

When installing a theme with that characteristic, this happens:

- Fullscreen mode theme: It deletes all other existing fullscreen themes and installs the fullscreen theme
- Desktop mode theme: it deletes the entire  `Playnite\Themes\Desktop` folder and doesn't install the theme

**Screenshots**
Video example of this issue: https://cdn.discordapp.com/attachments/699577276571975760/706303774376853546/2020-05-02_19-36-16.mp4

**Comment by JosefNemec** [comment]
Fixed in 7.7
