### ISSUE TITLE
Sea of Thieves stuck Launching (Microsoft Store App)

### ISSUE THREAD

**Issue by shangles** [JosefNemec/Playnite#1787]
I recently purchased Sea of Thieves from the Microsoft Store.  I manually added the game to Playnite
(Add game > Microsoft Store application)

When I click the Play button, it changes to "Launching" and never opens the game.

**Diagnostics ID**
d92b7e76-a4f1-480c-81e7-5714ee914790

**Comment by JosefNemec** [comment]
Can you try importing it using Xbox integration plugin instead? That's the main way MS Store games should be imported.

**Comment by shangles** [comment]
Yes I will.  I'm also going to reinstall the game.  I initially installed it and it put it on my C: drive when I wanted it on my D: drive.  I moved the game, but there were still some game remnants on the C: drive.  Sometimes the game wouldn't launch even natively through the Start menu, so this may not be a Playnite issue.

I'll report back in the morning once I have it reinstalled and imported into Playnite using your suggestion.

**Comment by shangles** [comment]
That did the trick.  Game launches from Playnite successfully now.  Thank you so much.  Also, thank you for informing me about the Xbox integration plug-in.  I found so many old Xbox 360 games that I own but forgot about.  This will make quarantine a little more entertaining.

I hope you're staying safe and healthy, and sane.

You make a wonderful product and it's miles ahead of any competitor.
