### ISSUE TITLE
Main menu stops working in Desktop Mode

### ISSUE THREAD

**Issue by bverkron** [JosefNemec/Playnite#1789]
**Check for existing issue**
None found

**Describe the bug**
The main menu in desktop mode stops working somethings. When I click it I can see a handful of light blue pixels appear to the bottom left of the menu button but the menu does not appear. I have to quite and reopen Playnite to get it working again.

**To Reproduce**
Unsure how to specifically reproduce. It just happens after a period of time. Unsure if it's tied to a certain event or not.

**Diagnostics ID**
f6ccc14d-b9ab-48da-ab16-90dd4dc13666

If it matters I'm running Windos 10 1909 Build 18363.778

**Comment by JosefNemec** [comment]
Please replace files in installation directory with these debug ones: https://playnite.link/download/MenuIssueDebug.zip

Once the issue happens again, please generate new diag. package from "About Playnite" menu (can be accessed with F1 hotkey).

**Comment by JosefNemec** [comment]
Never mind, I already reproduced it. Fix will be in 7.7

**Comment by JosefNemec** [comment]
Fixed in 7.7

**Comment by bverkron** [comment]
Amazing, thanks! Have to say I absolutely love Playnite and all the effort and quick responses! Do you have a one-time donation method or just Patreon subscriptions?

**Comment by JosefNemec** [comment]
I have [PayPal link](https://paypal.me/playnite). Thanks a lot for considering making a donation!

**Comment by bverkron** [comment]
PayPal seems to want to charge me unacceptable fees for a small donation so I opted to do a Patreon subscription for a period of time instead :) 
<img width="481" alt="Screen Shot 2020-05-04 at 12 13 39 PM" src="https://user-images.githubusercontent.com/19174503/81004226-e7e65e80-8e00-11ea-9a41-a83fd017e8a5.png">
