### ISSUE TITLE
Duplicate option "go to sleep mode" in Fullscreen

### ISSUE THREAD

**Issue by SeeDborg** [JosefNemec/Playnite#1790]
I don't see a post reporting that so I do : I have 2 buttons "go to sleep mode" when I'm in Fullscreen mode : 
![image](https://user-images.githubusercontent.com/7523821/80944836-b6fb2f00-8dea-11ea-844d-7707585be8b4.png)

The 2 buttons seems to do the same thing (there is no "normal sleep" and "deep sleep" for example). I use playnite in portable mode.

**Comment by JosefNemec** [comment]
This is localization issue, both "hibernate" (LOCMenuHibernateSystem) and "suspend" (LOCMenuSuspendSystem) options are translated to the same string. This needs to be fixed via [Crowding](https://crowdin.com/project/playnite) project, not github.

**Comment by SeeDborg** [comment]
I'll join the translation team then, thanks :)
Maybe an option to display just "Hibernate" or "Suspend" would be useful, I don't use both and I think I'm not the only one.
