### ISSUE TITLE
Warcraft III: Reforged and Call of Duty MW2 Campaign Remastered not appearing

### ISSUE THREAD

**Issue by troytc** [JosefNemec/Playnite#1791]
**Describe the bug**
The Call of Duty MW2: Campaign Remastered title does not appear in Playnite.  This is a non-Blizzard game and the same issue when Modern Warfare was released.

**To Reproduce**
Install Call of Duty MW2: Campaign Remastered, then update your Playnite library.  The game does not appear.

**Diagnostics ID**
66b466dc-c1b3-4461-bda4-b2c5a90525e2

**Comment by JosefNemec** [comment]
Done in `devel8`.
