### ISSUE TITLE
App goes on background when Steam BPM is launched

### ISSUE THREAD

**Issue by SeeDborg** [JosefNemec/Playnite#1792]
How to create the issue : launch Steam in Big Picture Mode on background, then launch Playnite in Fullscreen Mode.

Then you can launch a game and play it, but when you quit, Playnite relaunches and THEN Steam BPM goes above it.

This is a problem for a PC attached to a TV, I want to use it only with Playnite Fullscreen but I need to have Steam BPM in background so I can access the steam UI during game.

**Comment by JosefNemec** [comment]
There's nothing I can do about this. We have no control over Steam BPM.

**Comment by JosefNemec** [comment]
As a workaround you can try launching Playnite through BPM, that way it should never restore over Playnite because it will think that the "game" is always running.

**Comment by SeeDborg** [comment]
I'll try that. Another workaround I thought about would be to delay restoring Playnite after a game closes (if BPM mode is active), because this problem occurs only because Playnite is restored before BPM.
