### ISSUE TITLE
Darken uninstalled games in Fullscreen Mode

### ISSUE THREAD

**Issue by bverkron** [JosefNemec/Playnite#1793]
**Check for existing issue**
Found none

**Describe the solution you'd like**
Would be nice to have an option to "Darken uninstalled games" in full screen mode or piggy back off the current setting. I have it enabled under Settings > Appearance > Grid view but it does not seem to apply to full screen mode and I don't see a separate option (maybe I'm missing it)

**Comment by darklinkpower** [comment]
Enable it here.
![](https://i.imgur.com/qOv8nUD.png)

**Comment by bverkron** [comment]
Duh on my part. So used to most of the settings I need being under the Desktop mode that I haven’t been in the Fullscreen settings in a long time and forgot they were there. <facepalm>
