### ISSUE TITLE
Call Of Duty: Modern Warfare 2 Campaign Remaster import

### ISSUE THREAD

**Issue by ArthurHNL** [JosefNemec/Playnite#1795]
The remastered Modern Warfare 2 Campaign was released onto Battle.net recently. Playnite does not import this game. This is probably a small fix by adding an entry to [source/Plugins/BattleNetLibrary/BattleNetGames.cs](https://github.com/JosefNemec/Playnite/blob/master/source/Plugins/BattleNetLibrary/BattleNetGames.cs) for this game.

**Comment by JosefNemec** [comment]
Duplicate #1791
