### ISSUE TITLE
Importing some third party store games from Humble when set to ignore them

### ISSUE THREAD

**Issue by awbooze** [JosefNemec/Playnite#1797]
**Check for existing issue**
This was sparked by #1676 and is probably something to improve while you're working on it.

**Describe the bug**
I really appreciate Playnite and took advantage of the Humble integration to run the importer and bring more of my games together. To my surprise, even though I had the "Ignore third party store games" checkbox checked, the importer imported _Assault Android Cactus+_, _FRAMED Collection_, and _Into the Breach_, which I also have Steam keys for. To reproduce, own any of those games on Humble and import from Humble into Playnite with the "Ignore third party store games" setting enabled.

**Fix**
After mucking around in Humble's API response and the source code for a bit, it seems that each of these games has a separate problem. From reading it, it looks like HumbleLibrary.cs just checks if the store key's name is the same as the game's or has " Key" appended to the end. However, "Assault Android Cactus+" != "Assault Android Cactus", "FRAMED Collection" != "Framed Collection", and "Into the Breach" != "Into The Breach (Steam)", which are the differences between the titles of the downloadable application and the Steam key. We could fix the last two by comparing the strings case-insensitively and also checking if a "Steam" is appended to the end, but I'm not sure how to fix the first. I'd be willing to work on this before the 8.0 release, though.

**Diagnostics ID**
9666630c-382d-47a4-bc0e-808c4618efb8, if you need it.

**Comment by JosefNemec** [comment]
Should be fixed in Playnite 8, let me know if it still doesn't work.

**Comment by awbooze** [comment]
After updating to Playnite 8.1, I've confirmed that it works. Thanks!
