### ISSUE TITLE
Full Steam Library Import fails - possibly too many games?

### ISSUE THREAD

**Issue by TheMerricat** [JosefNemec/Playnite#180]
I'm assuming from the fact that it's indicated that the profile must be public that when the full library import from Steam is being done it's using the "All Games" link.

I haven't been able to get a full import to work yet, it keeps failing and I was wondering if it's a timeout issue with the number of games that need to be imported.

[http://steamcommunity.com/id/Merricat/games/?tab=all](http://steamcommunity.com/id/Merricat/games/?tab=all)

**Comment by JosefNemec** [comment]
Could you please attach diagnostics package, which can be created from "About Playnite..." menu? Thanks

(btw it's not using that link, but Steam API to get list of games)

**Comment by TheMerricat** [comment]
[Test.zip](https://github.com/JosefNemec/Playnite/files/1376146/Test.zip)

Was in the middle of creating one. :-)

**Comment by JosefNemec** [comment]
It looks like you have no connection to Playnite server, can you try [this link](http://185.28.100.135:8080/api/steam/library/Merricat) in your browser? It should return games in your library.

**Comment by JosefNemec** [comment]
Also please check if your firewall is not blocking Playnite from using port 8080 over http.

**Comment by TheMerricat** [comment]
That would be it then, for some reason I've never been able to get to playnite.link, had to get to you via github. Traceroutes pretend that they know the IP but timeout without getting a single response. 

The link you gave also timed out with a 'connection was reset' after a few minutes of waiting.

**Comment by JosefNemec** [comment]
Thanks for that info, I'm going to close this since it's not an issue in Playnite.
