### ISSUE TITLE
Humble library importer adding games not in my Humble library

### ISSUE THREAD

**Issue by kccricket** [JosefNemec/Playnite#1801]
Humble library integration is importing games that are not in my Humble library.

**Screenshots**
Multiple Humble games that are not in my Humble library.
![Playnite library](https://user-images.githubusercontent.com/2245729/81372200-c23eab00-90c7-11ea-8b38-ef5e867a16d0.PNG)

I searched for "divinoids" on my Humble library, and didn't find it. In fact, the game isn't released yet.
![Search on Humble](https://user-images.githubusercontent.com/2245729/81372196-c10d7e00-90c7-11ea-841e-cd61cc8bc2a4.PNG)

**Diagnostics ID**
47e13321-bdfa-4ee2-9d2f-3a7c273ae7b8

**Comment by JosefNemec** [comment]
Divinoids is currently in Humble Trove, do you have import of Trove games enabled?

**Comment by kccricket** [comment]
Fair enough. It was enabled. I was certain I checked the Humble importer settings for anything like that. Thank you.

Closing as user error.
