### ISSUE TITLE
Alternative search provider for image search

### ISSUE THREAD

**Issue by shakeyourbunny** [JosefNemec/Playnite#1805]
**Check for existing issue**
I could not find an issue for this.

**Describe the solution you'd like**
If you are editing game details, you can search manually with Google Image search for possible matching images by clicking on the respective "G" button in the section of the "Media" tab.

Please add / allow other image search sources, the "G" button should be configurable where it would search which should be configurable by a (fixed) dropdown list in the preferences.

Suggested alternative image sources:
**DuckDuckGo**
- icon: https://duckduckgo.com/?q={search term}+icon&iax=images&ia=images&iaf=layout%3ASquare%2Csize%3AMedium
- cover: https://duckduckgo.com/?q={search term}+cover&iar=images&iaf=layout%3ATall%2Csize%3ALarge&iax=images&ia=images
- wallpaper: https://duckduckgo.com/?q={search term}+wallpaper&t=palemoon&iar=images&iaf=layout%3AWide%2Csize%3ALarge&iax=images&ia=images

You can fine-tune the search with image orientation and form, I already did that for the requested searches above.

**Yandex**
- icon: https://yandex.com/images/search?text=section%208%20icon
- cover: https://yandex.com/images/search?text=section%208%20cover
- wallpaper: https://yandex.com/images/search?text=section%208%20cover

**Bing**
I would like to have it due its often on-spot findings, but unfortunately, most results are colored out due to heavy geo-filtering and censorship. If a result is not found on from a list of seemingly whitelisted websites (for example mobygames, wikipedia, pcgamingwiki, ebay, deviantart...) you get colored squares as image results.
http://www.bing.com/images/search?q=ultima+underworld+cover if you wanna try.

**Comment by ArtexJay** [comment]
I agree with going with DDG, I never had the colored squares issue with Bing... I can see the pics fine there

**Comment by shakeyourbunny** [comment]
With Bing, I mean this:
https://s1.imagebanana.com/file/200519/2ssJvaK4.PNG

Note that I'm using a computer with English localization, my Browser sends that it wants only English .... and I get geofenced by IP to German (and with its censorship) without the possibility to change  the language or anything on Bing.

**Comment by JosefNemec** [comment]
Will be done via #1766, the support has to be implemented as a metadata plugin.
