### ISSUE TITLE
Battle.net always needs to be authenticated

### ISSUE THREAD

**Issue by Russti** [JosefNemec/Playnite#1810]
**Check for existing issue**
Please use issue search in the repository if the bug is something really obvious there's a high change it was already reported.

**Describe the bug**

**To Reproduce**
If it's not clear from the description how to reproduce the issue please add clear steps to reproduce the behavior.

**Screenshots**

**Diagnostics ID**
Please generate diagnostics package from "About Playnite" menu and attach identifier you received. If the issue is a crash bug, you can generate diag. package directly from crash dialog.

**Comment by JosefNemec** [comment]
Duplicate to #1057, also see [this](https://github.com/JosefNemec/Playnite/wiki/Battlenet-troubleshooting#authentication-being-lost-after-some-time).

**Comment by JosefNemec** [comment]
Also, next time please read the issue template and provide requested information. Thank you
