### ISSUE TITLE
Not detecting Epic Installed games

### ISSUE THREAD

**Issue by Phalk** [JosefNemec/Playnite#1812]
I'm still having the same issue as listed in this closed issue: https://github.com/JosefNemec/Playnite/issues/1132

That is: Cannot identify installed epic games. I found out the reason tho.
I'm using a pt-br locale of Windows 10 and my "All Users" folder inside "Users" isn't named "All Users" but "Todos os Usuários".

I managed to band aid fix this by creating a symlink of the Epic folder inside "Todos os Usuários" inside a manually created "All Users" folder.

I guess you should be able to fix that @ the base code with this information!

**Comment by FlaipyTheHost** [comment]
Hi Phalk, I have the same problem, and I can't find the "All Users" or "Todos os Usuários" folder. If you have free time, could you help me? I would appreciate it very much, thank you!

Olá Phalk, eu passo pelo mesmo problema, e não consigo achar a pasta "All Users" ou "Todos os Usuários". Se tiver um tempo livre, poderia me ajudar? Agradeceria muito, obrigado!

![image](https://user-images.githubusercontent.com/36010065/83913228-97d32280-a745-11ea-9c51-208a31d77989.png)

**Comment by Phalk** [comment]
"Exibir -> Opções -> Modo de Exibição" then uncheck "Ocultar arquivos protegidos do sistema operacional (Recomendado)."

This should make the "Todos os Usuários" folder appear in your "Users" dir.

Then just make a symbiotic link (google it) that links the "Todos os Usuários" folder to a folder named "All Users" folder. This should band-aid fix this. At least it worked for me.

**Comment by JosefNemec** [comment]
Done in `devel8`.
