### ISSUE TITLE
Ubisoft UPlay versions of Brothers in Arms games not detected

### ISSUE THREAD

**Issue by adrianluff** [JosefNemec/Playnite#1816]
The Ubisoft UPlay store has versions of the Brothers in Arms trilogy available. At least two of the three are not detected by Playnite's UPlay library plugin. They do not appear in Playnite even if the game(s) are installed by the UPlay app.

Brothers in Arms - Hell's Highway
https://store.ubi.com/us/game/?lang=en_US&pid=56c4948388a7e300458b4714&dwvar_56c4948388a7e300458b4714_Platform=pcdl&edition=Standard&source=detail

Brothers in Arms - Earned in Blood
https://store.ubi.com/us/game/?lang=en_US&pid=575ffd92a3be1633568b4d28&dwvar_575ffd92a3be1633568b4d28_Platform=pcdl&edition=Standard&source=detail

**Comment by JosefNemec** [comment]
Please generate diagnostics package from "About Playnite" menu and attach identifier you received.

**Comment by adrianluff** [comment]
5a477436-c769-4e36-ad9f-366d8c77b6f5

**Comment by adrianluff** [comment]
I added the two games manually.

**Comment by JosefNemec** [comment]
Can you check if they are imported as "BiA EiB" and "BiAHH". That's how Uplay names them (for some reason) in registry entries we use to import installed games.

**Comment by adrianluff** [comment]
Ah, yes. They were.

https://gyazo.com/45df7e1ba66eac1ee38d35a69a0dc9d9/raw
