### ISSUE TITLE
Relative path support

### ISSUE THREAD

**Issue by planningall** [JosefNemec/Playnite#1817]
like this :
D:\GAME\manager\Playnite
D:\GAME\manager\Playnite\library
D:\GAME\FPS\DOOM
D:\GAME\STG\Ikaruga
D:\GAME\Emulator\MAME0.22
D:\GAME\MAME_ROMS

In library\games\*.json

"InstallDirectory":"D:\\GAME\\FPS\\DOOM"
"InstallDirectory":"D:\\GAME\\STG\\Ikaruga"

"InstallDirectory":"D:\\GAME\\MAME_ROMS"
"GameImagePath":"D:\\GAME\\MAME_ROMS\\kf2k2mp2.zip"

If I change the root dir name，for example : E:\GAME or D:\GAME_old or D:\BACK\GAME,Playnite  stop working.
If roms isn't in MAME root dir,Playnite stop working.

I hope Playnite can support :  .\  and  ..\

D:\GAME\manager\Playnite——.\
D:\GAME\manager\Playnite\library——..\library

In library\games\*.json

"InstallDirectory":"D:\\GAME\\FPS\\DOOM"——..\FPS\DOOM
"InstallDirectory":"D:\\GAME\\STG\\Ikaruga"——..\STG\Ikaruga

"InstallDirectory":"D:\\GAME\\MAME_ROMS"——..\MAME_ROMS
"GameImagePath":"D:\\GAME\\MAME_ROMS\\kf2k2mp2.zip"——..\MAME_ROMS\kf2k2mp2.zip

**Comment by JosefNemec** [comment]
#412
