### ISSUE TITLE
Authenticating Epic Account, login page cannot detect captcha completed

### ISSUE THREAD

**Issue by randomguyingithub** [JosefNemec/Playnite#1818]
Don't know if the problem belongs to Epic Game Store, this app or the browser. So I put report in Playnite Github to let dev knows.

**To Reproduce**
Uae latest Playnite.
Authenticate Epic Game Store Account.
Fill in relevant Email and Password.
Complete Captcha.
Press Sign in.
It shows  "You must complete Captcha", doesn't let you log in (as seen gif below)
Default Browser is Firefox 76.0.1 (64-bit) (with many plugins don't know if it's related)

**Screenshots**
https://i.imgur.com/3YxdL1I.gifv

(still happening with a real account)

**Diagnostics ID**
422b2601-f36e-4ac5-bbbb-7900f913d6f6

**Comment by JosefNemec** [comment]
I can't replicate it myself, I get completely different captcha system then what's on you video, but I will update web view component in Playnite 8. I'm not sure if it's going to help, but that' all I can do about it really.

**Comment by JosefNemec** [comment]
In theory fixed by 37aec5f3bb0706b139892a4911413ea0269b5853 (in `devel8` branch). Please retest once Playnite 8 is available.

**Comment by t3pfaffe** [comment]
Receiving this bug again in 8.11. Same conditions and outcome, Firefox 86.0.1.
