### ISSUE TITLE
Allow people to vote for the most anticipated features

### ISSUE THREAD

**Issue by SeeDborg** [JosefNemec/Playnite#1819]
It would be cool to have some place to vote for the features we want the most in the next releases of Playnite. Maybe along all the features tags as "enhancements" here in Github.

A system little bit like the GOG wishlist would be nice : https://www.gog.com/wishlist/site

**Comment by darklinkpower** [comment]
Playnite already has a poll that is opened for patreon supporters after a new major version is released where people can vote on what features they want in the next major release.
https://www.patreon.com/playnite
