### ISSUE TITLE
2.5 crashes when trying to import the library

### ISSUE THREAD

**Issue by Arattor** [JosefNemec/Playnite#182]
When starting up the 2.5 version of Playnite crashes during the importing of installed games. Tried it multiple times with four different errors, mostly related to an out of range index or array being too small. Diag packages from them are all below (5 is the latest one, and each one should have the earliest occurence of the specific type of crash at the bottom of the log)
[diag package 2.zip](https://github.com/JosefNemec/Playnite/files/1376680/diag.package.2.zip)
[diag package 3.zip](https://github.com/JosefNemec/Playnite/files/1376681/diag.package.3.zip)
[diag package 4.zip](https://github.com/JosefNemec/Playnite/files/1376682/diag.package.4.zip)
[diag package 5.zip](https://github.com/JosefNemec/Playnite/files/1376683/diag.package.5.zip)

**Comment by JosefNemec** [comment]
Duplicate to #181

**Comment by JosefNemec** [comment]
Please reinstall to 2.4 until this is fixed.
