### ISSUE TITLE
Group By -> Last Played = misleading

### ISSUE THREAD

**Issue by IFD3** [JosefNemec/Playnite#1820]
The usual groups are:
**Today:** Show Games played today (OK)
**Past week:** Shows Games played yesterday and "IN the last/past week" (the "IN" makes the difference or else it would be excactly 7 days in the past)
**Past Month:** Now it get's totally out of hand. Shows everything between 7 days from now back to 30 days so it seems. (again here would _IN_ the past/last month be more logical)
**Past Year:** Same as before
**More than a year ago:** totally fine!

Alternatively Today / This Week / This Month / This Year / More than a year ago
would be as short as it is right now but makes more sense to me.

**Comment by JosefNemec** [comment]
Would just renaming it to "In past week" be enough? "This week" would mean this specific week which would show different data, not just games played in last 7 days.

Or I could just rename it to "In past 7 days", "In past 31 days" which would be even more accurate.

**Comment by IFD3** [comment]
I like the "In past x Days" most, simple and easy to get, no thinking needed. Maybe It is even easier in translations to other languages.

**Comment by JosefNemec** [comment]
Done in devel9.
