### ISSUE TITLE
I have some ideas about game manager

### ISSUE THREAD

**Issue by planningall** [JosefNemec/Playnite#1821]
[game_manager.pdf](https://github.com/JosefNemec/Playnite/files/4639731/game_manager.pdf)

I have some ideas about game manager.

If necessary,i can made an english version document.

**Comment by JosefNemec** [comment]
1) PDFs are terrible for any kind of collaboration or commenting
2) English is mandatory

**Comment by JosefNemec** [comment]
No response => closing.
