### ISSUE TITLE
First char in 'Assign Category' menu is not shown

### ISSUE THREAD

**Issue by By6r9** [JosefNemec/Playnite#1822]
**Describe the bug**
In some cases first char (like `_` or ~emoji~) of 'category' is not shown in 'Assign Category' menu.
**To Reproduce**
Create '_Backlog' category.

**Screenshots**
![_](https://user-images.githubusercontent.com/32620314/82143661-c3997180-9845-11ea-99e8-84f71675a0d9.png)

**Comment by JosefNemec** [comment]
Fixed in Playnite 8.
