### ISSUE TITLE
Better handling of unavailable Google Images images

### ISSUE THREAD

**Issue by DillonWgithub** [JosefNemec/Playnite#1823]
**Describe the bug**
When editing any game (I have been doing this on emulated games), selecting a 252x252 icon from google will result in no changes to the icon.

**To Reproduce**
Simply edit any game (known issue on emulated games), click the g icon under choose an icon, select a 252x252 image and click save

**Screenshots**
![Edit Game Details 5_17_2020 4_22_15 PM](https://user-images.githubusercontent.com/32619267/82159195-a58a3c00-985a-11ea-8ec0-fc77dd4e713f.png)

**Diagnostics ID**
e8f2f37e-11c6-48cd-bfe2-a59948c40029

**Comment by DillonWgithub** [comment]
Interestingly enough, a 252x252 icon is not even shown as selectable on PC games.

**Comment by darklinkpower** [comment]
Images shown there are from google cache and the real image might not exist, it's not a problem with the resolution. Try with another image and you can add `imagesize: 252x252` to limit results to that resolution and see that it's an issue with that specific image.

**Comment by JosefNemec** [comment]
It's exactly how darklinkpower says. Google will index images that have source no longer available. There are two ways we could handle this:

- use cached thumbnail (might be ok for icons)
- display warning message that source image is no longer available.

We should maybe do both of those, download cached preview image and display warning that source is not available and lower quality version is downloaded.

**Comment by JosefNemec** [comment]
Done in `devel8`.
