### ISSUE TITLE
Add game titles with pictures

### ISSUE THREAD

**Issue by SeeDborg** [JosefNemec/Playnite#1824]
You could add a picture for game title in addition to game icons. And maybe display it.

Like this, creators of skins could use them to display too.

I'm currently using my games icons to do that, but I dont have game icons since ^^

This : https://i.imgur.com/xJR1dVy.jpg
Could look like this : https://i.imgur.com/CjtvJub.jpg

With my current skin (SteamNite), it looks like this : https://i.imgur.com/2dgcN9V.jpg
But could look like this with icon AND title : https://i.imgur.com/NAbOtYk.jpg

**Comment by JosefNemec** [comment]
Duplicate to  #1682
