### ISSUE TITLE
playnite.link has stopped working

### ISSUE THREAD

**Issue by kwilliams1987** [JosefNemec/Playnite#1827]
**Describe the bug**
When trying to download any version of the app, the playnite.link domain currently times out when accessed.

**To Reproduce**
1. Try accessing https://playnite.link

**Screenshots**
![image](https://user-images.githubusercontent.com/2725436/82349720-c12c4880-99fa-11ea-900d-3587fedaba3f.png)

**Comment by JosefNemec** [comment]
Works for me. I have no idea why it doesn't work for you.

**Comment by kwilliams1987** [comment]
I did some more tests and see that the connect is very unstable from home, but via my office VPN it works.

I'll try to find out what's wrong at my end, sorry for the inconvenience :)
