### ISSUE TITLE
New"Logo" field

### ISSUE THREAD

**Issue by Ohkami** [JosefNemec/Playnite#1828]
Could we add a "_logo_" field in addition to the "_icon_" field in the media? Some themes like _SteamNite_ (https://playnite.link/forum/thread-58.html) use the SteamGridDB logos which look good on the details view page, but not at all in games list.

![nHBHpgd](https://user-images.githubusercontent.com/55941477/82353303-8842a280-99ff-11ea-9a9c-082cc92f1d83.png)

**Comment by JosefNemec** [comment]
#1682
