### ISSUE TITLE
GOG "installer" button opens library (without Galaxy) / Offline Installer support

### ISSUE THREAD

**Issue by shakeyourbunny** [JosefNemec/Playnite#1829]
**Describe the bug**
I use GOG strictly only with offline installers and not with GOG.

So, if I click on a GOG game page the "install" button, I just get redirect to the standard GOG library page, which is a bit annoying.

**To Reproduce**
- remove GOG Galaxy if it is installed.
- import GOG games
- try to install game (click on "install").
- you are being redirected to https://www.gog.com/account and PlayNite is in some sort of installing mode.

**Proposed solution**
![image](https://user-images.githubusercontent.com/5352403/82367808-b088cc00-9a14-11ea-993f-7d88814e7698.png)
Save the GOG slug (see www.gogdb.org) alongside with the game and either provide a direct link to library page of GOG and/or have a configurable option where the offline installer are located and organized by folder which have a slug name for downloading in order to directly start the offline installer. 

Example below.
![image](https://user-images.githubusercontent.com/5352403/82368061-0fe6dc00-9a15-11ea-82fa-339b940de013.png)
results in
![image](https://user-images.githubusercontent.com/5352403/82368101-20975200-9a15-11ea-8f38-ba24bd78d6c3.png)

Playnite then could start setup_broken_sword_4_the_angel_of_death_1.1a_(24519).exe to run the installer. Note that the exact filename of  installer may change due to updates, so it would be better to scan for executables in the slug folder beginning with "setup..." and then present a choice if there are multiple found. GOG only provides offline installers beginning with "setup_".

**Comment by JosefNemec** [comment]
Will be done via #478
