### ISSUE TITLE
Playnite cannot find Uplay launcher

### ISSUE THREAD

**Issue by n30nwav** [JosefNemec/Playnite#1830]
It seems like Playnite is not able to find Uplay launcher if its installed in an alternate location. I am getting an error "The system cannot find the file specified". This also is impacting its ability to read the configuration file in order to view Uninstalled games

**Comment by JosefNemec** [comment]
Please generate diagnostics package from "About Playnite" menu and attach identifier you received. 

We take installation location from registry entries Uplay creates during installation. You may try repairing Uplay install to see if it fixes the issues.

**Comment by n30nwav** [comment]
and so it did. Yeah for some reason my Uplay launcher even though was working perfectly. Had some entries missing. I just re-installed it and everything works now. Thanks for your quick help
