### ISSUE TITLE
Possible support for grabbing metadata for japanese games from DLsite?

### ISSUE THREAD

**Issue by gin9980** [JosefNemec/Playnite#1836]
Having lots of games bought from DLsite manually having to input each metadata for every single game is time consuming. Is it possible to add metadata grabbing the release dates, tags, comments, cover, circle (developer), genre (catagories), series, age ratings and link?

**Comment by erri120** [comment]
I created a DLSite Metadata Provider Extension here: https://github.com/erri120/Playnite.Extensions

**Comment by JosefNemec** [comment]
Thanks, I'm closing this since there's an extension for it now.
