### ISSUE TITLE
Playnite settings access on plugins.

### ISSUE THREAD

**Issue by Lacro59** [JosefNemec/Playnite#1837]
In order to localize the plugin (for example), it's necessary to easy access to playnite settings.

**Comment by JosefNemec** [comment]
Done in `devel8`. I haven't exposed all application settings, only those I thought could be used by plugins. If you want to see something else exposed, open new issue for it.

**Comment by Lacro59** [comment]
It's great! It's more safe than load manually the configuration.
Thanks!!

**Comment by Bluscream** [comment]
Do you have a link for that part of the docs?

**Comment by JosefNemec** [comment]
It will be in new `IPlayniteSettings` interface, there are no docs, I make docs before the actual build release.

**Comment by Bluscream** [comment]
I see, thanks ^^
