### ISSUE TITLE
Quick filters/Dynamic collections

### ISSUE THREAD

**Issue by Gerren** [JosefNemec/Playnite#1839]
I love the filter options. I do have some favorite combinations of them, and when I want to set the other, I need to clear all, and set the other one.

In Steam client, this function is called "Dynamic collections".

One can create a collection of strategies, and when new game with this feature, it is automatically added to this collection.

There could also be count of matching games for each collection. #1838

**Comment by JosefNemec** [comment]
Duplicate to #590
