### ISSUE TITLE
Two requests, Vertically center game covers in Covers view / Extend the hitbox(?) of the game covers area to make it easier to select game with a short cover image.

### ISSUE THREAD

**Issue by outlawzgosu** [JosefNemec/Playnite#184]
Here's an example: 

Current alignment: https://imgur.com/16Xoq1D.jpg
Suggested alignment: https://imgur.com/L1m1vKm.jpg

Also, I don't know if I have to make a new Issue for each feature request, but if it's possible to make it so you can click anywhere in this area (https://imgur.com/WaIpLQP.jpg) to activate the game. Currently, you have to click on the game cover, which becomes a problem when there are very skinny covers for some games (https://imgur.com/HjhQt2i.jpg).

**Comment by JosefNemec** [comment]
Kind of duplicate to #162 , at this will be taken care of in #162
