### ISSUE TITLE
Will not connect any games that are not installed except for origin even though all the boxes to import uninstalled games are ticked

### ISSUE THREAD

**Issue by Roboticfuriosity** [JosefNemec/Playnite#1841]
**Check for existing issue**
Please use issue search in the repository if the bug is something really obvious there's a high change it was already reported.

**Describe the bug**

**To Reproduce**
If it's not clear from the description how to reproduce the issue please add clear steps to reproduce the behavior.

**Screenshots**

**Diagnostics ID**
Please generate diagnostics package from "About Playnite" menu and attach identifier you received. If the issue is a crash bug, you can generate diag. package directly from crash dialog.

**Comment by JosefNemec** [comment]
Could you please follow issue template instructions and provide requested information? Also, just checking uninstalled checkbox is not enough, you have to be authenticated with those services for import of uninstalled games to work.

**Comment by JosefNemec** [comment]
No response, closing.
