### ISSUE TITLE
It says my steam account is private even though it is public

### ISSUE THREAD

**Issue by Roboticfuriosity** [JosefNemec/Playnite#1842]
**Check for existing issue**
Please use issue search in the repository if the bug is something really obvious there's a high change it was already reported.

**Describe the bug**

**To Reproduce**
If it's not clear from the description how to reproduce the issue please add clear steps to reproduce the behavior.

**Screenshots**

**Diagnostics ID**
Please generate diagnostics package from "About Playnite" menu and attach identifier you received. If the issue is a crash bug, you can generate diag. package directly from crash dialog.

**Comment by JosefNemec** [comment]
Not only your profile, but also "Game details" section has to be set to public. If you are still having issues after settings "Game details" to public, then just obtain your own API key and use that.

**Comment by Roboticfuriosity** [comment]
> 
> 
> Not only your profile, but also "Game details" section has to be set to public. If you are still having issues after settings "Game details" to public, then just obtain your own API key and use that.

My game details are also set to public but wont work and the api code isnt working

**Comment by JosefNemec** [comment]
Can you provide diagnostics package requested in issue template?

**Comment by JosefNemec** [comment]
Also make sure that your AV/FW/VPN is not blocking traffic from Playnite processes.

**Comment by JosefNemec** [comment]
No response, closing.
