### ISSUE TITLE
"Unrecoverable Error"

### ISSUE THREAD

**Issue by Ethroptur1** [JosefNemec/Playnite#1845]
I recently found that Playnite refused to launch. After uninstalling, deleting all Playnite-associated files, and reinstalling, Playnite still refused to launch. I attempted to use the multi-instance build, however that version told me that an unrecoverable error occurred.

Diagnostics ID: 2b9088f7-e977-47b5-b58b-773527c73aa2

**Comment by JosefNemec** [comment]
What's the "multi-instance build"?

The version you are using is pretty old and this specific startup crash was fixed already in 7.x branch, please update to latest version.
