### ISSUE TITLE
Add an option to minimize to tray when opening a game

### ISSUE THREAD

**Issue by lordsilver-zz** [JosefNemec/Playnite#1847]
Right now there is only an option to minimize when opening the game, but there is no option to minimize it to tray (right side of start bar).

**Comment by JosefNemec** [comment]
Enable "minimize to tray" option.

**Comment by lordsilver-zz** [comment]
Yes, it works, not sure why I didn't think about this. A bit different that it changes minimize to tray even if you click minimize, but that's not a problem.
