### ISSUE TITLE
Playnite doesn't have an icon in the taskbar when set to start not minimized to tray

### ISSUE THREAD

**Issue by darklinkpower** [JosefNemec/Playnite#1849]
**Describe the bug**
Happens seemingly randomly when starting Playnite when set to start not minimized to tray on either fresh start or after restarting when changing a setting or installing an extension.

**To Reproduce**
At the moment I can't find a certain way to reproduce but it happens frequently when what was described happens.

**Screenshots**
![imagen](https://user-images.githubusercontent.com/1389286/83310497-d579fd80-a1d1-11ea-850f-ffd92acb70bc.png)

![imagen](https://user-images.githubusercontent.com/1389286/83310652-5fc26180-a1d2-11ea-8432-8f19cd30ec7c.png)

**Comment by JosefNemec** [comment]
This is another case of issue #354. I literary have no control over how that icon is rendered.
