### ISSUE TITLE
Cache search results from IGDB API

### ISSUE THREAD

**Issue by JosefNemec** [JosefNemec/Playnite#185]
Once #129 is implemented we might reach API call limit (at least for free account that is). We should cache more data then what we do right now and switch to paid account later if needed.

**Comment by krazyjakee** [comment]
Are you putting an API key in the release builds? If so, let me know the name that the Application is under at api.igdb.com as I couldn't find Playnite in our system. I can put you on the open source plan which bumps the limit up to 30k requests per month.
Doesn't fix this issue but it will help prolong the functionality. If limits become a problem again, please get in touch.

**Comment by JosefNemec** [comment]
I'm not distributing API keys to client installations. Everything goes via extra service, which accesses IGDB, caches data and then sends them to the clients.

I checked api.igdb.com and it looks completely different then when I was settings things up :) I'm currently going via RapidAPI (id playnite_59230283e4b0bba971febaaa), should I switch to api.igdb.com and set up new account there?

**Comment by krazyjakee** [comment]
@JosefNemec We'll look back at RapidAPI eventually but for now, if you could sign up at api.igdb.com I promise you a better experience :P

You just need to change the endpoint and set an HTTP header `user-key` with your new key. Everything should work just the same.

Sorry for further derailing this issue but we will also soon be an oauth provider where users can login, rate games and add to a their "want" list. We will expand this functionality but it seems like something that could be a nice little extra for those who want to rate their games. We also have game news (pulse) which could show up on game views as we have connected articles to games.

Just some ideas :)

**Comment by JosefNemec** [comment]
OK I've created `Playnite` app there. Wouldn't mind leaving RapidApi since their interface is slow as hell :) I'll will switch to new endpoint in next version.

Thanks for additional ideas, I'll be definitely looking into those (primarily news aggregation).

**Comment by JosefNemec** [comment]
Released in 3.0
