### ISSUE TITLE
Steam game not getting detected as running by Playnite

### ISSUE THREAD

**Issue by darklinkpower** [JosefNemec/Playnite#1850]
**Describe the bug**
----
Steam game not getting detected as running

**To Reproduce**
---
Run the steam game "[Raging loop](https://store.steampowered.com/app/648100/Raging_Loop/)"

**Screenshots**
----
Screenshot showing Steam is running the game but not getting detected by Playnite
![imagen](https://user-images.githubusercontent.com/1389286/83337084-2810f380-a27e-11ea-8b51-76b616b2a009.png)

Only particular things is that it's a Unity game (though others have worked fine) and that the directory name is in japanese. Folder name is `レイジングループ`
![imagen](https://user-images.githubusercontent.com/1389286/83337098-4676ef00-a27e-11ea-8ec9-31c753c05b6f.png)

Process is `ragingloop.exe`, subprocess is `レイジングループ`
![imagen](https://user-images.githubusercontent.com/1389286/83337090-3232f200-a27e-11ea-88d3-7ef8db360179.png)

![imagen](https://user-images.githubusercontent.com/1389286/83337209-1c71fc80-a27f-11ea-8d56-f0c5e1d06a1a.png)

**Comment by JosefNemec** [comment]
Fixed in `devel8`.
