### ISSUE TITLE
Allow plugins to inject global PlayActions

### ISSUE THREAD

**Issue by Bluscream** [JosefNemec/Playnite#1852]
This can be considered a alternative or enhancement of #1765!

**Comment by JosefNemec** [comment]
Plugins can already add/modify game actions. Game actions are just game properties that can be changed as any other game property.

**Comment by Bluscream** [comment]
Wouldn't they have to add it's action to each game individually?

**Comment by JosefNemec** [comment]
Yes, but that's true even for plugins that "own" the game.

**Comment by Bluscream** [comment]
That's what i'm requesting and therefor this request shouldn't be closed

**Comment by JosefNemec** [comment]
What's the use case for this?

**Comment by Bluscream** [comment]
Exactly what i mentioned in the referenced request

**Comment by JosefNemec** [comment]
Adding #272 dependency.

**Comment by JosefNemec** [comment]
Done in devel9.

**Comment by Bluscream** [comment]
Thanks :)
