### ISSUE TITLE
PCSX2: Lauch A Game With Fastboot

### ISSUE THREAD

**Issue by Jimmy2Times** [JosefNemec/Playnite#1854]
**Check for existing issue**
Please use issue search in the repository if your feature request is something really obvious there's a high change it was already requested.

**Describe the solution you'd like**

**Screenshots**
If applicable, add screenshots to help explain requested changes.

**Comment by JosefNemec** [comment]
You can already supply any custom arguments to any emulator profile that's automatically imported or manually added. You can also overwrite cmdline arguments for each when configuring play action.

**Comment by JosefNemec** [comment]
Remove `--fullboot` from emulator argument configuration.

**Comment by Jimmy2Times** [comment]
Thank you, that worked.
