### ISSUE TITLE
Possibility for windowed fullscreen by default

### ISSUE THREAD

**Issue by magalhas** [JosefNemec/Playnite#1857]
Cases like Steam Link and Nvidia Shield don't play well regaining focus on Fullscreen windows due to resolution changes. It would be awesome to be able to have Playnite fullscreen app be able to open as windowed by default. Windowed is already supported by using alt+enter when opened, so it should be no problem.

Alternatively we could also have a command line flag to enable this behaviour instead of a setting on the UI.

**Comment by JosefNemec** [comment]
Playnite is always windowed, exclusive fullscreen is not supported at all.
