### ISSUE TITLE
Scripted key inputs when an application is executed.

### ISSUE THREAD

**Issue by CreamyNobody** [JosefNemec/Playnite#1858]
So I have the PC port of Super Mario 64 and when it launches you must press alt+space to enter full-screen. Is there a way this can be done through the scripting function perhaps?

Apologies, I am new to github and only have a basic understanding of how these scripts work. 

Thanks.

**Comment by JosefNemec** [comment]
It will be possible once #1736 is implemented. I would also recommend contacting author of the game and ask them to add a parameter to start the game in fullscreen.

**Comment by CreamyNobody** [comment]
Thank you. 

Unfortunately, I don't know who the author of the game is. It's a community port that a friend happened to give me. Its pretty bare bones, it does have a fullscreen parameter in its config, but unfortunately it doesn't function.
