### ISSUE TITLE
Playnite fullscreen ignores desktop settings

### ISSUE THREAD

**Issue by Aleonz00** [JosefNemec/Playnite#1859]
I have "When game starts" set as "Do nothing" but with the fullscreen program, it still minimizes. I can't find the option in the fullscreen settings so I can't fix it.

Is there any reason why minimize is the default anyway? I don't want to see my web browser immediately after launching a game. Ruins the immersion of the "console" experience for me.

Thanks for the great program though.

**Comment by JosefNemec** [comment]
This is intentional functionality of Fullscreen mode. Since we don't have a full control over game startup (like original launchers), we have to minimize Playnite as soon as possible to prevent issues with games not getting input focus properly.

**Comment by Aleonz00** [comment]
Okay, I understand why it's default now. Why remove it completely though? It can't hurt to have the option for people who don't care about that issue. You could even add a warning or something to the setting if it's really that big of a deal (never had the issue you described with Steam Big Picture though, and I use Uplay, Origin, etc). Fullscreen looks so clean and professional but the minimizing makes me not want to use it anymore.

**Comment by mcay23** [comment]
Seconding this, would be nice if we could turn it on for all games and manually turn it off for problematic games.

**Comment by magnummer** [comment]
> Seconding this, would be nice if we could turn it on for all games and manually turn it off for problematic games.

That would be really useful indeed.

**Comment by JosefNemec** [comment]
Done in devel9, there's now separate option for Fullscreen mode to not minimize after starting a game.
