### ISSUE TITLE
VR Suggestion !

### ISSUE THREAD

**Issue by greatxerox** [JosefNemec/Playnite#186]
hiiiiiiii !

i have some suggestions
 - please add : VR  category (there are VR games on steam & Uplay)    :smile:
- Itch client
- and VR MOD category also for games which are non VR but with the possibilily to use VR using a MOD
(my vr modded games : [http://nsm07.casimages.com/img/2017/10/12//17101211390816744215316241.jpg](url)

thank you a lot !

Good thing for Battle.net client ;)

**Comment by JosefNemec** [comment]
You can already create VR category by yourself and filter it like Steam does. It that sufficient for you, or would you like some kind of different behavior?

**Comment by greatxerox** [comment]
thank you Josef.
i know i can create VR category by myself, but in the Steam library, VR category exists by default and it's useful. i have a bunch of VR titles, and usually, VR users has a lot of VR titles, a lot of little games, and it's difficult to remember each game, because there are tons of indie games, like on the usual Steam library.

**Comment by JosefNemec** [comment]
Thanks for clarification, I think it would be possible to do that once issues #152 and #153 are implemented.

**Comment by greatxerox** [comment]
that's great :)  thank you

**Comment by greatxerox** [comment]
since your last update, the login problem for Battle.net is solved, congratulations Josef :)

i hope you'll add Itch client

**Comment by JosefNemec** [comment]
I haven't changed anything in regards to battle.net so it must be a coincidence. Also please keep this comment section focused on original issue and create a new one if you some other stuff you need to solve. Thanks

**Comment by greatxerox** [comment]
👍

**Comment by JosefNemec** [comment]
Steam API doesn't provide information to automatically categorize the game as VR., You can now assign custom tags or categories so I'm going to close this.
