### ISSUE TITLE
RSPC3 Does Not Always Launch Games Through Playnite

### ISSUE THREAD

**Issue by SEGA99** [JosefNemec/Playnite#1860]
More often than not RSPC3 will not launch games than it actually working as intended. RSPC3 the program itself works and launches games just fine but when I've pointed Playnite to the PS3 games' EBOOT files in order to launch the games via my front-end launcher I get this error message pop up, 'This application failed to start because no qt platform plugin could be initialized. Reinstalling the application may fix this problem.'

RSPC3 works just fine but there is an issue if you or anyone else knows a fix I'll be greatly appreciative?

Thanks!!

**Comment by JosefNemec** [comment]
I don't think there's anything that can be done about this from Playnite's side. We just launch all RSPC3 games in  the same way (unless you manually change it). If it works for some games and not others,  then it's an RSPC3 issue.

**Comment by JosefNemec** [comment]
Also make sure you have emulator and the game properly imported:
https://github.com/JosefNemec/Playnite/wiki/Importing-Emulated-games

**Comment by JosefNemec** [comment]
Just to be sure, I just tried it and it works with latest RSPC3 (tested with Demon's Souls), using steps I linked in my previous comment.

**Comment by SEGA99** [comment]
> Just to be sure, I just tried it and it works with latest RSPC3 (tested with Demon's Souls), using steps I linked in my previous comment.

I figured it out, for some reason Playnite has two options to read game files and they are both called "Default". Once I changed from one of the options to the other that are both called "Default" to the other "Default" option it will work. This can be done by manually adding the emulated game or clicking "Edit" on a game and selecting the "Actions" tab and changing it from there. Very frustrating but your software works extremely well. Maybe just laballing tabs within the imported emulated profiles would help others.

**Comment by JosefNemec** [comment]
Can you post what's the emulator configuration of both of those "Default" profiles? Only one should be imported unless you have multiple RSPC3 executables in single folder.

**Comment by SEGA99** [comment]
I just checked my RSPC3 installation folder and I have a new folder called, "rpcs3_old" which I am assuming is simply after updating the program it keeps the old files as a rollback. I believe this is creating some kind of conflict within RSPC3 to launch games unless you choose the other "Default" option in the "Actions" tab. 

Let me just add that everything works fine I guess it's just a UI issue as it's not made clear which is which when in reality they both should be the same because they are the same executable files virtually.

**Comment by GinoMan** [comment]
So to close this issue, RSPC3 should look for the main executable in the regular folder not the "rpcs3_old" folder and also not create a second profile for the old installation?

**Comment by JosefNemec** [comment]
Done in devel9.
