### ISSUE TITLE
Error when importing GOG games "Unexpected character encountered while parsing value: E. Path[...]"

### ISSUE THREAD

**Issue by darklinkpower** [JosefNemec/Playnite#1862]
**Describe the bug**
Error when importing GOG games "Failed to import games from GOG. Unexpected character encountered while parsing value: E. Path[...]"

**To Reproduce**
Try to update your GOG library. I suspect the error trigerred because I had not updated my library in a long time and maybe I was not authenticated anymore. Upon checking in settings, it said that I was still authenticated. The error was fixed by pressing the "Authenticate" button, which opened  the login window that just asked for my password because it already had my username saved.

**Screenshots**
![imagen](https://user-images.githubusercontent.com/1389286/83918958-550e4c00-a73f-11ea-99f2-4acdae4a32c5.png)

![imagen](https://user-images.githubusercontent.com/1389286/83919287-e8478180-a73f-11ea-9905-7e6aacbda676.png)

**Diagnostics ID**
I'll paste the log when it happened

```
2020-06-05 15:03:37.5622|ERROR:Failed to import linked account GOG games details.Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: E. Path '', line 0, position 0.
   en Newtonsoft.Json.JsonTextReader.ParseValue()
   en Newtonsoft.Json.JsonTextReader.Read()
   en Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   en Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   en Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   en Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   en Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   en GogLibrary.Services.GogAccountClient.GetOwnedGames() en E:\Devel\Playnite\source\Plugins\GogLibrary\Services\GogAccountClient.cs:línea 133
   en GogLibrary.GogLibrary.GetLibraryGames() en E:\Devel\Playnite\source\Plugins\GogLibrary\GogLibrary.cs:línea 119
   en GogLibrary.GogLibrary.GetGames() en E:\Devel\Playnite\source\Plugins\GogLibrary\GogLibrary.cs:línea 224

**Comment by shangles** [comment]
I'm also having this error.  I tried to reconnect the GOG library and reauthenticate but I still get the error when updating all libraries.

**Comment by JosefNemec** [comment]
I think it's some issue on GOG side, I'm having issues signing in on their website.

**Comment by shangles** [comment]
I was able to login on their site.  Just tried updating Playnite again and it refreshed GOG without error.

**Comment by JosefNemec** [comment]
Is this reproducible on demand?

**Comment by darklinkpower** [comment]
No, it has only happened once to me and was fixed by login in again.
