### ISSUE TITLE
Steam library import no longer imports game icons

### ISSUE THREAD

**Issue by roalthomp** [JosefNemec/Playnite#1863]
**Check for existing issue**
Please use issue search in the repository if the bug is something really obvious there's a high change it was already reported.

**Describe the bug**
Game icons are no longer showing up for games imported from my Steam library.  This used to work, so must have broken in a recent update.  It seems to be related to the "Managed by library plugin" functionality.

**To Reproduce**
Import any game to Playnite by updating the Steam library.  The game icon will not load and the default "controller" icon will display.  If you attempt to force the icon to import in the Edit menu of the game, under the Media tab, you get the message "Cannot get icon if Play action is missing or is set to URL".  

The Play action is marked as "Managed by library plugin".  If I disable this checkbox, change the Type to "Executable", and the path to the game executable, then forcing the icon to import will work.

It seems the "Managed by library plugin" behavior needs to be modified to still look at the game executable for the icon, at least on initial import.

**Screenshots**
![image](https://user-images.githubusercontent.com/66508643/83937835-296e7e80-a79e-11ea-829d-3de03d246f4b.png)

![image](https://user-images.githubusercontent.com/66508643/83937838-38553100-a79e-11ea-8888-21dca3ffa0fd.png)

![image](https://user-images.githubusercontent.com/66508643/83937847-45722000-a79e-11ea-835a-796e50517f4a.png)

![image](https://user-images.githubusercontent.com/66508643/83937853-4dca5b00-a79e-11ea-9d79-39da9dfbc390.png)

![image](https://user-images.githubusercontent.com/66508643/83937859-5753c300-a79e-11ea-9043-a1329d84c172.png)

![image](https://user-images.githubusercontent.com/66508643/83937869-65a1df00-a79e-11ea-8aa9-2e60b296c019.png)

**Diagnostics ID**
Please generate diagnostics package from "About Playnite" menu and attach identifier you received. If the issue is a crash bug, you can generate diag. package directly from crash dialog.

75df5e09-5367-4c24-8da1-aa36a5ac7ff1

**Comment by JosefNemec** [comment]
Please add diagnostics ID.

It's definitely not related to game action configuration. Steam games pull icons from via Steam API.

**Comment by roalthomp** [comment]
Added the generated ID.

**Comment by JosefNemec** [comment]
I see a lot of timeout errors related to Steam metadata downloads, this looks a network issue to me. Also, those errors are week old, there are no newer errors then that.

If you want to re-download icons manually, then either do it via Download Metadata button while editing games or in bulk from main menu using Library -> Download Metadata.

**Comment by roalthomp** [comment]
"in bulk from main menu using Library -> Download Metadata"

I swear I tried this multiple times before and it didn't work, but it
worked this time.  Issue resolved, thanks for the help!
