### ISSUE TITLE
Cover Images of certain aspect ratios grow huge on desktop UI

### ISSUE THREAD

**Issue by Someone65** [JosefNemec/Playnite#1865]
As can be seen here:
![Playnite Screenshot](https://i.vgy.me/XXwiZl.png)
The image used for the cover grows so huge as to cover a bit of the UI to its left side.
I scaled down the image and it produces the same result (the screenshot is actually using the scaled down image).

Images tried are [this](https://zdoom.org/assets/images/logo/text_zdoom.png) and [this](https://i.vgy.me/YitIdL.png).

diag ID: e104e684-8d9a-4559-87bb-e4b1d51be099

**Comment by darklinkpower** [comment]
Playnite uses this setting to determine how big the image will be. Just keep in mind that it will apply to all images no matter the aspect ratio it uses. Change it to a value that fits what you are using, which should be a low number if you are using an horizontal image.

![imagen](https://user-images.githubusercontent.com/1389286/83989890-72911080-a90d-11ea-8806-363c6b7aa8c4.png)

**Comment by Someone65** [comment]
Ah, so it's not an issue after all. It's still strange that it can cause very flat cover images to extend far enough to cover UI elements. Closing issue. Sorry.
