### ISSUE TITLE
Unreal Engine plugins showing up in games list.

### ISSUE THREAD

**Issue by xanderVH** [JosefNemec/Playnite#1867]
**Describe the bug**

**To Reproduce**
Download a version of the Unreal Engine on the Epic Games store and create a project. Open the Unreal marketplace, buy the free plugin called "Auto Size Comments" and add it to your newly created project, you may have to enable the plugin in your project settings first.

**Screenshot**
![image](https://user-images.githubusercontent.com/51954292/84076346-dc74ed00-a9d5-11ea-962a-0eaf313ee93c.png) 
**Game ID**
f247bd5f-4c66-42e1-bda9-3c36beb9fda9

**Comment by JosefNemec** [comment]
Can you edit this entry, go to "Advanced" tab and post what `Game Id` value is? Thanks

**Comment by xanderVH** [comment]
> Can you edit this entry, go to "Advanced" tab and post what `Game Id` value is? Thanks

Should be added, thanks for the quick response.

**Comment by JosefNemec** [comment]
Fixed in Playnite 8.
