### ISSUE TITLE
Improper authication with Battlenet

### ISSUE THREAD

**Issue by Murkur** [JosefNemec/Playnite#1876]
The authentication window for battle net closes to early when 2 Factor authentication is enabled using the battle net authenticate app the authentication windows closes before you can enter a code invalidating the authentication

**Comment by JosefNemec** [comment]
For some reason I can't reproduce it, the window stays open and waits until I confirm authentication in mobile app. I'll have to prepare some debug build of battle.net extension for you, to figure out what's happening.

**Comment by Murkur** [comment]
thank you I only just installed playnite a few days ago after my steam forced updated itself and I refuse to use the library interface they released for now I just disabled syncing of uninstalled games and ill wait for the development build

**Comment by JosefNemec** [comment]
Please reproduce it again with this build of battle.net plugin:
[Bnetdebug.zip](https://github.com/JosefNemec/Playnite/files/4776373/Bnetdebug.zip)

You need to replace files in `%appdata%\Playnite\Extensions\BattleNetLibrary\` directory.
After the issue occurs, generate diagnostics package from "About Playnite" windows and attach ID you receive. Thank you

**Comment by Murkur** [comment]
did as told and I tried to sign in it said user is authenticated then it said I was no longer authenticated

`26e813ae-19c0-4a53-9faa-aca1e8aefdac`

**Comment by JosefNemec** [comment]
I don't see anything wrong in new logs. Can you make a video of the issue? According to logs, the window closes after the profile page is loaded, which is definitely after 2FA check.

**Comment by Murkur** [comment]
I think it may be an issue caused after first installation and not restarting after first install, since after I installed playnite I didn't restart my PC till now (3 days later) and it authenticates properly
