### ISSUE TITLE
Fail to import games when hdd is under heavy load (Browser is not yet initialized)

### ISSUE THREAD

**Issue by darklinkpower** [JosefNemec/Playnite#1877]
**Describe the bug**
Fail to import games when hdd is under heavy load (Error: Browser is not yet initialized)

**To Reproduce**
Fail to import games when hdd is under heavy load. Should be related too hdd being slow too.

**Screenshots**
![imagen](https://user-images.githubusercontent.com/1389286/84540061-403f3480-acba-11ea-9d4e-9d6c245d6103.png)

**Comment by JosefNemec** [comment]
Done in `devel8`.
