### ISSUE TITLE
'Enter' key doesn't work to press "OK" in dialogues created via SDK or in the game details edit window

### ISSUE THREAD

**Issue by darklinkpower** [JosefNemec/Playnite#1878]
**Describe the bug**
'Enter' key doesn't work to press enter in dialogues created via SDK. Doesn't work with any type of dialogue that has "OK"

edit: it happens with all dialogues, including the ones found in the edit window when creating a new element.

**To Reproduce**
Create a dialogue via SDK or open a dialogue window by trying to add a new element for any field in the game edit window and press the 'enter' key.

**Screenshots**

![imagen](https://user-images.githubusercontent.com/1389286/84546922-07a65780-acc8-11ea-9232-fe726f2a5bbb.png)

![imagen](https://user-images.githubusercontent.com/1389286/84563163-2126be00-ad1f-11ea-8ff9-f4500b2111ca.png)

**Comment by JosefNemec** [comment]
Done in `devel8`.
