### ISSUE TITLE
Cover View client logos

### ISSUE THREAD

**Issue by weissni** [JosefNemec/Playnite#188]
The format you chose for the covers seems to only really work with origin games. while they fill up the cover frames, the covers of games from every other client (especially steam) only take up a third of the frame while the rest is the client logo.

I get that these clients provide pictures in different formats, but wouldn't it be possible to solve this via a trade-off, like squared covers? Or since most people will have the majority of their collection on steam use their cover format generally?

PS: You've created a great piece of software there that i had wished existed a long time ago already

**Comment by JosefNemec** [comment]
See #36
