### ISSUE TITLE
Import icon from itch.io play action

### ISSUE THREAD

**Issue by MemeTroubadour** [JosefNemec/Playnite#1883]
Hello, thank you for your work on Playnite.

Currently, it seems that games imported from itch.io cannot get their icon from their default play action regardless of if they're installed or not, possibly because it's considered an URL.

I'm assuming the varying file types of itch.io games might make this harder to implement in comparison to Steam, but if it's possible, finding a solution to this would be nice for itch.io app users as the only alternative would be to set an unique play action for each game linking directly to its executable.

**Comment by JosefNemec** [comment]
You can manually point to game's executable to use it as icon source, you don't have to do it via Play action. Fetection from Play action is only for cases where the Play action points to an executable, there's really nothing I can do about this for itch games.
