### ISSUE TITLE
Crash on trying to run game

### ISSUE THREAD

**Issue by IrritatedGoat** [JosefNemec/Playnite#1884]
64e574db-348f-496c-9c36-4afb41035e69

This is a bit of a unique situation. I remoted into my PC from another PC and used the jumplist to start a game. I know it's fringe but I wanted to report it just in case.

**Comment by JosefNemec** [comment]
I don't see any crash happening according to logs. Do you have a screenshot or a video of the issue? Can you reproduce it on demand?

**Comment by IrritatedGoat** [comment]
I don't unfortunately. It doesn't happen often enough to be able to reproduce it consistently. You can close if you want. I don't think I have any way of making it happen more consistently.

**Comment by JosefNemec** [comment]
The problem is that according to logs, no crash happened. Do you see some crash dialog or something? Or does the app just closes?

**Comment by IrritatedGoat** [comment]
Full white screen for about 15 seconds then crash dialog.

**Comment by JosefNemec** [comment]
Can you make a video of the crash please?

**Comment by JosefNemec** [comment]
No response, closing.
