### ISSUE TITLE
Cursor is too sensitive in laptop. But if i connect mouse, it works fine. Only laptop track mouse is having issue

### ISSUE THREAD

**Issue by maharshi-b** [JosefNemec/Playnite#1885]
**Check for existing issue**
Please use issue search in the repository if the bug is something really obvious there's a high change it was already reported.

**Describe the bug**

**To Reproduce**
If it's not clear from the description how to reproduce the issue please add clear steps to reproduce the behavior.

**Screenshots**

**Diagnostics ID**
Please generate diagnostics package from "About Playnite" menu and attach identifier you received. If the issue is a crash bug, you can generate diag. package directly from crash dialog.

**Comment by JosefNemec** [comment]
We don't do anything with mouse sensitivity, you get the same sensitivity as with any other application. If your sensitivity is high then you need to adjust it on a system wide level.
