### ISSUE TITLE
Close Full Screen Menu On Hybernate and Sleep

### ISSUE THREAD

**Issue by Axbruce96** [JosefNemec/Playnite#1887]
I use playnite to turn my PC into a console and use a gamepad to wake from hybernate. When I do this  through full screen mode the menu is still open and the cursor remains on hybernate so when I attempt to pass the lock screen by pressing A the hybernate button is pressed again. I have tried to add the action of closing the settings menu before going into hybernation but I cannout figure out how to do that.

**Comment by JosefNemec** [comment]
Done in `devel8`.
