### ISSUE TITLE
Itch.io - Only installed games importing

### ISSUE THREAD

**Issue by gilorian** [JosefNemec/Playnite#1890]
Based on this reddit thread, I think Itch.io games that I have claimed as owned in my Itch.io library should appear in playnite as uninstalled games: https://www.reddit.com/r/playnite/comments/gz9ysd/possibility_to_add_itchio_bundles/

Like this reddit thread, I have purchased the racial equality bundle, but unlike the OP I have claimed all the games. So they appear in my 'Owned' library, and updated the Playnite game library; no games were added. I left it for a few days, and have found that only games I actually install in Itch.io are appearing in Playnite, as installed games, with source set to Itch.  

Am I doing something wrong?

Itch.io client; 25.4.0
Playnite; 7.7

**Comment by JosefNemec** [comment]
Do you have import of uninstalled games enabled? I can't reproduce it myself, all games I claimed from the bundle are being imported properly if import of uninstalled games is enabled.

**Comment by gilorian** [comment]
Thank you Josef!

I was not aware of Libraries > itch.io > Connect Account > Import
uninstalled games.

It's working now that I have enabled it.
