### ISSUE TITLE
clear filters button

### ISSUE THREAD

**Issue by SaltySamurai** [JosefNemec/Playnite#1892]
Add a clear filters button next to the Filters active button.
I don't want to have to open the filters pan and then move my mouse across the whole screen to click clear filters. It's not very efficient.

**Screenshots**
![image](https://user-images.githubusercontent.com/10049294/85224006-26d77000-b3bf-11ea-9be4-9054843b1b1d.png)

**Comment by spineduke** [comment]
Any chance of this happening ?

**Comment by JosefNemec** [comment]
I don't really like an idea of adding extra button for it. What about clearing filters when right-clicking on the existing filter button?

**Comment by spineduke** [comment]
Yes that would be an acceptable solution! One click on the top level menu is basically what we're asking for
