### ISSUE TITLE
Crash when trying to add some things from the Microsoft Store

### ISSUE THREAD

**Issue by DigitalNikki** [JosefNemec/Playnite#1896]
**Describe the bug**
An unrecoverable error occurred

**To Reproduce**
Start Playnite, open the menu, open the add game menu, pick Microsoft Store Application, try to add Forza Horizon 4, click add, and watch Playnite crash.

This only happens with some Microsoft Store Apps. So far for me it's caused by Forza, and Xbox related apps. My guess is it's related to the Xbox Game Pass for PC.

**Screenshots**

**Diagnostics ID**
19ec5810-fbb9-46af-81d1-eb54a7a94257
4a62b135-d922-4d00-b3d4-fa0937c1b7db

**Comment by JosefNemec** [comment]
The reason for this crash is really weird, but I should be able to fix. Anyways, Forza Horizon 4 should be imported via built-in Xbox plugin, you don't have to add it manually.

**Comment by DigitalNikki** [comment]
I thought it should be imported automatically, but for some reason it isn't getting imported so I tried to add it manually.

**Comment by JosefNemec** [comment]
The log shows that you are not authenticated with Xbox, you need to go to setting and authenticate.

**Comment by DigitalNikki** [comment]
I don't login using a MS account, but I am logged into to all the Xbox apps and the MS store. I don't think logging into Windows using a MS account should be required, just being logged in to the Xbox apps.

**Comment by JosefNemec** [comment]
You have to authenticate in Playnite if you want Xbox integration to work properly, there's no way around that.

**Comment by DigitalNikki** [comment]
Until this just now when it made to authenticate again, it has always looked like this on the settings page.
https://i.postimg.cc/fbPStzmR/xbox.png
Now that I've re-authenticated, it looks like the image again. However it's the same thing. Some games are not added, and trying to add them causes a crash.

28355380-4a5b-4470-ac72-32ce9563e819

**Comment by JosefNemec** [comment]
It looks like a file system issue to me. Is `D:\Programs\Playnite\` folder or the actual d: drive a standard drive or some mounted network thing? It crashes because Playnite fails to do some things in regards to access to the library folder.

I'm unable to reproduce this on any of my systems.

**Comment by DigitalNikki** [comment]
It's a 2TB internal HDD I use for some programs and documents. I have I have 5 storage volumes, one is RAID 0. I use the RAID (R drive) and a 2TB NVMe SSD (N Drive) for games.

Without knowing more specifics, I don't know what to try. I haven't seen any logs stored locally.

**Comment by JosefNemec** [comment]
Please reproduce again with [these files](https://github.com/JosefNemec/Playnite/files/4844542/WinStoreDebug.zip) (you need to place them into `%appdata%\playnite` folder) and then generate new diag. package, thank you.

**Comment by DigitalNikki** [comment]
I replaced folder library\files because Playnite refuses to not download images regardless of settings. I have them hidden because I don't want to see them, and I don't want them taking up drive space. I can allow it to make that folder, but there needs to be an option to prevent all image downloads that Playnite will use so I don't have to block it writing them. This is probably the cause, but I would rather not have the games in Playnite than see and waste space with the images because it doesn't use it's option to not have them.

I'm using the "portable" version so I don't have an %appdata%\playnite folder.

**Comment by JosefNemec** [comment]
That explains it. Please mention any 3rd party modifications to Playnite folders/files in future, it could have save me time debugging this.

You can disable image downloads completely in metadata settings. Just uncheck import for icons, covers and backgrounds.
