### ISSUE TITLE
Uplay games purchased in steam not showing up in Uplay Source/Library.

### ISSUE THREAD

**Issue by SaltySamurai** [JosefNemec/Playnite#1897]
I would like to have all my games from Uplay in the same space in Playnite. At the moment, as described in the title this is not possible because games are not being picked up.

**Comment by JosefNemec** [comment]
I'm closing this after the discussion we've had on Discord. We don't import Uplay games that require Steam. For some reason Uplay imports them, but Steam is always required to install and launch the game. It doesn't make much sense to import those under Uplay and Steam libraries to create duplicates.

Other 3rd party activated Uplay games (from Epic for example) are being imported properly.
