### ISSUE TITLE
Look into GOG based Linux "light" client

### ISSUE THREAD

**Issue by JosefNemec** [JosefNemec/Playnite#190]
Looks like official GOG Galaxy linux client is nowhere to be seen and community seems to really want it. We might be able to create some stripped down Playnite version with GOG only support for now.

This would be also helpful as a research into future fully fledged cross-platform version.

**Comment by GitRASQ** [comment]
I would love to see this! But is there any practical reason to remove Steam support? Steam's API should be the same on all platforms AFAIK.

**Comment by JosefNemec** [comment]
The reason is to not put much of the time to Linux support right now since I don't know if I'm going to fully commit to cross-platform yet.

**Comment by JosefNemec** [comment]
Adding reference to #59

**Comment by aaronfranke** [comment]
If you want to make a version for Linux, the first thing you should do is replace .NET functions that don't exist in .NET 4.0. The latest Mono roughly has feature parity with .NET 4.5, without WPF, WWF, and with limited WCF. Or, almost everything in .NET 4.0. Then you can switch to Mono, which is cross-platform.

**Comment by JosefNemec** [comment]
I'm closing this since any half-baked client would probably not get enough support. Any potential Linux support should be done as part of #59 as a fully featured client.
