### ISSUE TITLE
Button layout in Library Manager improvement

### ISSUE THREAD

**Issue by SaltySamurai** [JosefNemec/Playnite#1901]
**Describe the solution you'd like**
If it was Add, Rename ---SPACE--- <red> Remove and Remove unused <red>
That would make sure it's easy to read and you don't press the wrong button.

![image](https://user-images.githubusercontent.com/10049294/85843427-121d2280-b799-11ea-9301-10726eec00b6.png)

**Comment by JosefNemec** [comment]
Done in `devel9`.
