### ISSUE TITLE
SDK - Add event to interface is loaded

### ISSUE THREAD

**Issue by Lacro59** [JosefNemec/Playnite#1904]
The event "OnApplicationStarted" is returned when application is loaded but not the complete interface like different game view.
It's possible to have a event for this when it's loaded?

**Comment by JosefNemec** [comment]
What's the use case for this?

**Comment by Lacro59** [comment]
My plugins can communicate with theme.
In certain cases on application start, the plugin try to communicate with some UI elements not so loaded.
In consequent, the plugin must wait a another event that run after interface loaded. 

For example, the problem with interface integration of SuccessStory plugin.

**Comment by Lacro59** [comment]
With Playnite9, my demand is obsolete.
