### ISSUE TITLE
Use browser to authenticate account? 

### ISSUE THREAD

**Issue by lingsamuel** [JosefNemec/Playnite#1905]
**Describe the solution you'd like**
In settings library authenticate page, users have to input there account, password, 2FA code in built-in webview without URL. Users actually know nothing about this website, they will wonder if it is a phishing website.
Can Playnite get authenticated by browser like Firefox, Chrome or others?

**Comment by JosefNemec** [comment]
This is not possible due to technical limitations.

**Comment by ohadschn** [comment]
> Users actually know nothing about this website, they will wonder if it is a phishing website.

More practically, the system browser is typically already logged in to most of the services, so that can be a big time saver in terms of not digging up passwords, activating 2FA codes, etc...
