### ISSUE TITLE
Metadata download, broke after large library loading

### ISSUE THREAD

**Issue by achavazza** [JosefNemec/Playnite#1906]
Somewhat the temp broke after loading a large library, now updating don't load any missing data

There is a command to force redownload data and images for missing data?

**Comment by JosefNemec** [comment]
Main menu -> library -> download metadata.

What does "temp broke" mean?

**Comment by achavazza** [comment]
Thanks, that worked!

(I'm sorry, I thought you download every metadata to a temp folder, and when I was importing all my games that folder somewhat got corrupt)

Anyways, thank you, "download metadata" worked for me
