### ISSUE TITLE
Moving to different header in full screen mode clears filters

### ISSUE THREAD

**Issue by bverkron** [JosefNemec/Playnite#1909]
**Check for existing issue**
Did not find a match using "filter" or "filter full screen" in open issues.

**Describe the bug**
If filters are set under one of the headings (such as All, Most Played, etc) in full screen mode and you navigate to another heading the filters are cleared even under the original heading.

Unsure if this is intended functionality or a bug but seems odd to me that filters would be automatically removed when doing UI navigation like that and I thought the filters stayed in the past so submitting as a bug.

**To Reproduce**
Set a filter under one of the headings (ex: All) navigate to another heading (ex: Most Played) with the controller or the mouse. Filters will be cleared even when returning to original heading where they were set.

**Diagnostics ID**
ff6266a3-d949-4003-beaa-6b9eafc1bd67

**Comment by JosefNemec** [comment]
This is intended. Headers are basically filter presets, there will be an option to create custom ones in future.
