### ISSUE TITLE
Saving the position for right side (description) after exiting Playnite

### ISSUE THREAD

**Issue by Evene174** [JosefNemec/Playnite#191]
https://imgur.com/a/448TY

**Comment by evgdovg1996** [comment]
@JosefNemec Also,it will be very cool if playnite will have the option to run in mode:
on the left of the cover
on the right the descriptions,
without closing the right side

**Comment by JosefNemec** [comment]
Closing this since it will be completely reworked in 4.6 via new theming support and it will be up to the theme.
