### ISSUE TITLE
Why PES 2017 won't open through playnite?

### ISSUE THREAD

**Issue by mohaidar** [JosefNemec/Playnite#1912]
![Screenshot (4184)](https://user-images.githubusercontent.com/67690038/86238592-f4e8b980-bbc7-11ea-926a-1cc1030b09e8.png)

Why PES 2017 won't open through playnite launcher? I always get this message. When I do not open it through playnite, it works fine.

**Comment by JosefNemec** [comment]
We only tell Steam to launch the game, then it's up to Stem what it does with it, there's really nothing I can do about it. If you modified game's Play action to launch in a different way, then you probably misconfigured it.
