### ISSUE TITLE
Playnite don't find Epic Game on other drive

### ISSUE THREAD

**Issue by Raidez** [JosefNemec/Playnite#1913]
When I try to import games from Epic Game Store, Playnite don't find them.
I install all my games on my second drive (D:).
I think it the point, because all "Epic Game"'s games don't appair has installed game on Windows.

I still can import them manually but I can't change the library.

**Comment by JosefNemec** [comment]
I'm unable to reproduce this. Please try repairing Epic client installation.

**Comment by Raidez** [comment]
I found a way on follow that tutorial on [Reddit](https://www.reddit.com/r/playnite/comments/hcljw3/playnite_does_not_recognize_games_installed_from/fvfp3iw/) to change _EpicLibrary.dll_ and _EpicLibrary.pdb_ files.

I don't know why but it's working perfectly.

**Comment by JosefNemec** [comment]
If that build fixed it, then it means that Epic installation files are damaged, I just added workaround in 8f9fb509a7a1c7c24c3fd2a36801e25ee6b7b871 that ignores that corruption.
