### ISSUE TITLE
Steam Game Doesn't Import

### ISSUE THREAD

**Issue by networldsystems** [JosefNemec/Playnite#1914]
I'm not sure if it's an issue or not ...

Bought a few games in the Steam Summer Sale. All imported except one: Deathbloom. I've tried everything I could think of. There is no error or any clue that it is being skipped or why. It appears as if Playnite doesn't recognize that particular title as a game or at all- IDK. I imported another Steam game after - no issue with that.

I've never seen Playnite do that and thought it strange. It's no big deal to me, but I figured I should report it anyway.

Thanks!

**Comment by JosefNemec** [comment]
Duplicate to #910

**Comment by networldsystems** [comment]
Thanks. I searched using the game's title before posting. I was suspicious that it wasn't a bug, it seemed so odd. Sorry to waste your time on it.
Thanks again.



    On Saturday, July 4, 2020, 1:46:06 AM CDT, Josef Nemec <notifications@github.com> wrote:  
 
 


Duplicate to #910
