### ISSUE TITLE
Extensions with right click/context menue in game list

### ISSUE THREAD

**Issue by PeWa48** [JosefNemec/Playnite#1916]
**Check for existing issue**
Please use issue search in the repository if your feature request is something really obvious there's a high change it was already requested.

**Describe the solution you'd like**

**Screenshots**
If applicable, add screenshots to help explain requested changes.

**Comment by PeWa48** [comment]
it would be nice to access the extensions with context menue/right mouse click in the game list if i select a game.
Until now i must go to the main menue/extensions/chose the extension. I hope that is relativly easy to implement.

**Comment by JosefNemec** [comment]
Duplicate to #524
