### ISSUE TITLE
Wargaming.net Launcher

### ISSUE THREAD

**Issue by Warrender** [JosefNemec/Playnite#192]
Would it be possible to add the games in the Epic Launcher (https://www.epicgames.com/unrealtournament/download) and Wargaming.net Launcher?  Thanks.

**Comment by JosefNemec** [comment]
Epic already requested in #132

**Comment by JosefNemec** [comment]
I'm going to close this since I don't plan to work on it. The main reason being that they have only a small number of games there which you can add easily manually to Playnite.

The plugin support for libraries is there, so if anybody want to add this via plugin feel free to create one.

**Comment by ArtexJay** [comment]
This should be left open but with a new tag like "community plugin", which would allow people who want to create plugins such as this to view all the requests and make them. Having it closed feels like it will never be made or that it's already done.
