### ISSUE TITLE
Installed Steam games not being detected

### ISSUE THREAD

**Issue by r33int** [JosefNemec/Playnite#1921]
**Check for existing issue**

Did not find this issue elsewhere.

**Describe the bug**

I newly installed Playnite, and I am unable to get it to detect my installed Steam games. I enabled the Steam importer extension, but nothing happens. I also tried reinstalling Playnite from scratch

**To Reproduce**

- Install Playnite

- Run it

- Enable the Steam importer extensions

**Screenshots**

![image](https://user-images.githubusercontent.com/22567851/87221806-2bb09380-c36f-11ea-992b-5a268d5fb64a.png)

![image](https://user-images.githubusercontent.com/22567851/87221813-33703800-c36f-11ea-82ce-d461b85dd6b4.png)

![image](https://user-images.githubusercontent.com/22567851/87221815-379c5580-c36f-11ea-8df9-668064756a21.png)

**Diagnostics ID**

3ccd5ca2-30cf-4750-8177-bf09fd56ad50

**Comment by JosefNemec** [comment]
This usually happens if Steam installation is damaged somehow, please try reinstalling Steam client to see if it fixes the issue.

**Comment by r33int** [comment]
> This usually happens if Steam installation is damaged somehow, please try reinstalling Steam client to see if it fixes the issue.

Hello, thank you for your answer. I reinstalled Steam and it actually resolved the issue. Thankk you!
