### ISSUE TITLE
Scripting not finding commands

### ISSUE THREAD

**Issue by GiovaniGuizzo** [JosefNemec/Playnite#1922]
## Describe the bug

Basically the scripting module is not finding the `DisplaySwitch.exe` program (I am using Windows 10 v2004) when I try to run it as a script call before or after playing a game. The same error occurs for both PowerShell and Batch runtimes. More specifically, I am trying to run the following command to change my monitor projection:

```cmd
C:\Windows\System32\DisplaySwitch.exe /external
```

I have also tried to run the following in PowerShell mode, but it also doesn't work:

```PowerShell
Start-Process "C:\Windows\System32\DisplaySwitch.exe" -Args "/external"
```

I have tried to run in administrator mode as well, but the error persists. I also tried to put this command inside a .bat file and call the file from Playnite. In this case, it finds the batch file, but it still fails to run the command with the same error.

The weird thing is that this works perfectly fine when I try to run via PowerShell directly.

## To Reproduce

1. Copy `C:\Windows\System32\DisplaySwitch.exe /external` to the script input field of a game;
2. Try to run the game;
3. It will show the error message.

## Screenshots

A few screenshots of the error.

When I try to run with PowerShell type:

![image](https://user-images.githubusercontent.com/1986674/87223376-67019100-c374-11ea-9f70-75cd59756eab.png)

When I try to run with Batch type:

![image](https://user-images.githubusercontent.com/1986674/87223391-839dc900-c374-11ea-93e7-bce9844126f8.png)

My `$Path` variables:

![image](https://user-images.githubusercontent.com/1986674/87223437-d37c9000-c374-11ea-8f09-efb7c917d4ba.png)

## Diagnostics ID

35f0d40d-4009-4f19-9153-a361df6bc576

**Comment by JosefNemec** [comment]
Playnite is a 32-bit process, you need to address `SysWOW64` instead of `System32` if the executable is not in both paths.

**Comment by JosefNemec** [comment]
Ignore my previous comment, you need to use `sysnative` instead of `system32` because Playnite runs as 32-bit process:

`"C:\Windows\sysnative\DisplaySwitch.exe"`

**Comment by GiovaniGuizzo** [comment]
> Ignore my previous comment, you need to use `sysnative` instead of `system32` because Playnite runs as 32-bit process:
> 
> `"C:\Windows\sysnative\DisplaySwitch.exe"`

Perfect. Thanks for your reply. Now it works :)
