### ISSUE TITLE
Steam user reviews

### ISSUE THREAD

**Issue by noyouh** [JosefNemec/Playnite#1923]
Hi,

IGDB user scores are very scarce, most games only have a couple handful of reviews. Steam reviews, on the other hand, are very commonly used and are a pretty good way to tell how good a game is.

I believe this was requested before but back then there weren't any API calls to work with. They seem to exist now:
https://partner.steamgames.com/doc/store/getreviews

Sample API call for Assassin's Creed Origins: https://store.steampowered.com/appreviews/582160?json=1

**Comment by JosefNemec** [comment]
We should probably calculate rating using this since it provides better results: https://steamdb.info/blog/steamdb-rating/

**Comment by JosefNemec** [comment]
Done in `devel8`.

**Comment by Bluscream** [comment]
Can patreons get devel8 alpha access?

**Comment by JosefNemec** [comment]
You can try and build it yourself from code, but I don't consider it to be stable to distribute to people, even for testing, it's not finished yet.

**Comment by Bluscream** [comment]
Will patreons get rc1 when thats ready enough?
