### ISSUE TITLE
Let Windows handle text rendering setting

### ISSUE THREAD

**Issue by Aleonz00** [JosefNemec/Playnite#1927]
Please add a "None" option (or something similar) to the "text rendering mode" setting. I use a font renderer program called "MacType" which replaces Windows' font renderer. Since Playnite is handling fonts on its own, MacType can't inject into it like it can with every other program. I've tried every renderer combination in Playnite but everything still looks extremely pixelated no matter what.

Here's the difference between the default "auto : ideal" and MacType. (exact same font)

auto : ideal
https://i.ibb.co/cYMx75j/bioshock-infinite.png

MacType (Windows renderer)
https://i.ibb.co/RHmJSBP/biosh.png

**Comment by JosefNemec** [comment]
The currently available options are the only ones provided by WPF (UI toolkit we use).
