### ISSUE TITLE
Top of Playnite window defaults to a position above the screen, so it can't be moved

### ISSUE THREAD

**Issue by Pseudogenesis** [JosefNemec/Playnite#193]
When I first launched Playnite, the top of the window was outside of the space on my screen, so I couldn't move the client or view the top of the window. I'm on Windows 7 Home Premium x64, using a display resolution of 1366 x 768. 

I discovered a workaround (expanding the bottom of the window to the bottom of the screen, which "snaps" the window into a proper position) while writing this so unfortunately I can't provide an image or video for the sake of replication, but if it happens again later I'll update the ticket.

**Comment by JosefNemec** [comment]
Yeah the default size of main window doesn't with into 768px height, we may need to start maximized in case of such low resolution.

btw pro Windows tip: if you press Win key and use arrow keys then you can move any window around when it's get out of screen or into some weird position

**Comment by Pseudogenesis** [comment]
Oh good to know, thanks.

**Comment by Pseudogenesis** [comment]
I dunno if I should submit another issue for this, but I just encountered a bug. Here's a pastebin with the log: https://pastebin.com/PhRff6i8

Diagnostic package:
[Playnite Error.zip](https://github.com/JosefNemec/Playnite/files/1385438/Playnite.Error.zip)

**Comment by Pseudogenesis** [comment]
And another o_0

Pastebin: https://pastebin.com/WhDTCVrz

Package:
[Playnite Error 2.zip](https://github.com/JosefNemec/Playnite/files/1385444/Playnite.Error.2.zip)

**Comment by JosefNemec** [comment]
Released in 2.8
