### ISSUE TITLE
Remember filter in fullscreen mode

### ISSUE THREAD

**Issue by noyouh** [JosefNemec/Playnite#1930]
Currently when opening fullscreen or when switching tabs in fullscreen - the filter is cleared. It would be nice to have it remember your filter, like desktop mode. This also applies to "Sort By".

**Comment by teconmoon** [comment]
Hi there, I second this request. When in fullscreen mode viewing all my games, I like to sort them by custom categories I have created. However, if I switch to another tab and back (like Favorites), then this is reset and I have to re-select the filter.

**Comment by bverkron** [comment]
Yes please! Thought I read this was going to be added but I can't find the comment now. Something about being able to make other headers with filters set ahead of time?

Don't see this in the list of planned or poll features for v9. Bummer. One of the biggest missing features for me as I constantly have to re apply filters to get the list of games I want.

**Comment by bverkron** [comment]
Ah, I think this is it, which is included in the poll for v9.
https://github.com/JosefNemec/Playnite/issues/590

**Comment by noyouh** [comment]
Like bverkron said, this is happening with #590 😄 - closing this.
