### ISSUE TITLE
Only show "owned" platforms

### ISSUE THREAD

**Issue by noyouh** [JosefNemec/Playnite#1931]
When trying to filter by platforms I get a really big list of platforms that I have to go through to find the one I'm looking for. This is especially annoying when in fullscreen mode.

It would be nice to have some sort of toggle in settings to only show platforms that you actually have games for.

**Comment by Ryakna** [comment]
You can go to Menu > Library > Library manager  and in "Platforms" use the option to "Remove unused".
That way, only the platforms with associated games will stay.

**Comment by darklinkpower** [comment]
@Ryakna I don't think that's a good idea, it will be a mess to add every platform again afterwards. Crow has already implemented this in the upcoming Playnite 8 so it's a matter of waiting https://github.com/JosefNemec/Playnite/issues/1301

**Comment by JosefNemec** [comment]
Duplicate to #1301
