### ISSUE TITLE
Adding custom variables to "Installation" tab (like for defining romhacks, patches and texturepacks)

### ISSUE THREAD

**Issue by genova447** [JosefNemec/Playnite#1934]
Please excuse me in advance, this may already be an intended part of: https://github.com/JosefNemec/Playnite/issues/653 and/or https://github.com/JosefNemec/Playnite/issues/197
Though I thought that it might not be, so I went and took the liberty of making a new 'issue'.

Concisified explanation
-
Add the ability for users to be able to define their own additional variables, similar to {ImagePath} and the like.

Use case
-
Retroarch can use the the arguments **--ups**, **--ips** and **--bps** to call romhacks/patches to be applied to games at runtime, to take the example of one use case.
Currently in Playnite to most easily achieve and use that function of Retroarch, you would need to add an "Additional Emulator Argument", such as **--bps drive:/folder/folder/folder/patch.bps**
But with this idea implemented, one would have predefined the patch as **{Romhack#1Path}** and could write **--bps "{Romhack#1Path}"**.

An example of how the interface, to add the variables, could work, is provided further below.
(But, disclaimer: I don't assume that my 'idea' is a good way to implement the desired outcome, so naturally dismiss the 'suggestions' and do it differently if this is even a desired function at all.

**Below is my original post with more info and additional 'ideas' (leaving it here for now; as I'm really bad at both including all information, and being concise simultaneously), but you don't need to read any further to understand the idea of the feature I'm suggesting:**

---
---
Function and why it could be neat to have
-
I thought it could be pretty neat if we could define custom 'variables' in the Installation tab, that can be used for, well, whatever one might want to use it for.  In my specific case I had in mind; Retroarch can softpatch roms, for example, and by default you just need a ips, ups, or bps file that is named exactly the same as the rom [file] you're going to emulate.
However with the arguments --ips, --ups and --bps when starting Retroarch, you can manually define which romhack/patch you want to load with the rom. (and so have the patches/romhacks be in a different location, and be named differently as well)

It is of course already possible to do this in Playnite, by adding "Additional Emulator Arguments", but you would have to manually define the full path for the romhack/patch, and if you want to rearrange your 'Actions' you would have to copy-paste your lengthy arguments around.

I thought, those variables that would be created with using this function would then be usable in the same way as {InstallDir}, {InstallDirName}, {ImagePath}, {ImageName}, {ImageNameNoExt}, {PlayniteDir} and {Name} are currently.

So the idea would be that you could write **--bps "{Romhack#1Path}"** - in "Additional Emulator Arguments" as in the case of my example of Retroarch, and it would load in the romhack that would be present where-ever you would have defined the variable to be pointing to.

I made a little mockup of how it might look.

![PlayniteMockup](https://user-images.githubusercontent.com/36210357/88467475-92709980-cea5-11ea-8ca4-f6400bfdaa65.png)

And per my example, the new possible variables per new 'item' would be; **{Romhack#1Dir} {Romhack#1DirName} {Romhack#1Path} {Romhack#1Name}** and  **{Romhack#1NameNoExt}**.
**Edit**: Or maybe just making the singular variable itself, be the sole resulting variable, so it would just be **{Romhack#1}**.
And you could yourself define either folders or files that you want to have as available variables.

Concerns
-
Of course Playnite would have to disallow people name their variables in a way that would conflict with existing in-built variables

There can be made arguments against how this idea is not really 'less' work for an individual as such, since the path will have to be defined in the proposed new variables. I just thought it might be nice that you can manage all your romhacks in such a manner.

I have no idea how hard implementing dynamic variables like that would be (or what it would be called), nor how hard it might be to 'explain'/'convey' the function to users in-program without making an enormous help box (thinking of the box that pops up and explains {ImagePath} and all those), so I don't mean to impose this as "do it" - I just thought it might be neat, if anybody else might see a use for it as well.

something else?
-
Maybe an entirely different system to index romhacks, patches and the like, would be better - where you can seamlessly 'assign' romhacks to specific games through a per-game checkbox system, or something, rather than my proposed system where you add those romhacks, only to one given game at a time... though I wouldn't know where one might want to use the same patch for different games....

But, maybe with that... my example given here could be a "Local variables" only for that game... but maybe Playnite could have a "Global variables" as well, where the same variable could be used across various games, without having to define it for each and every game, I suppose might be even better. 

**Edit:** Or, perhaps have it be more like "per game variables", "per emulator variables" and finally "global variables",
So you can have variables that work and are definable for all games within the same emulator/system, as well as on only a per-game basis, or even a global, for-everything, system?
Of course my little mockup does not demonstrate how "emulator variables" and "global variables" could potentially be done...
Regardless though, I hope and I'm sure that someone else has a more 'optimized' idea of how one could do all that. (If anybody else would care for such a feature)

Anyway, it's just a silly little idea, if anything like that would be implemented, it naturally does not have to follow this idea here at all; usually others think of much better systems than I do xD

And I realize that in the case of some Romhacks that change games to essentially be another game entirely, some might prefer to rather have a system that add the game+romhack, as a entirely separate game in Playnite. - not sure how one would strike a balance between those two though; unless Playnite could specifically detect that certain filetypes are always romhacks, and would prompt the user to "add this as a romhack to existing game" or "add as separate game"

Additional functions that could go with this
-

Now, already as Playnite is, and much more so if this function would be implemented more or less as-is proposed here; it could perhaps be more 'user-friendly' if under 'Actions' you could somehow automatically "Paste Variable here"

For example you have: **-L ".\cores\mupen64plus_next_libretro.dll" "{ImagePath}"** in "Emulator Arguments"

Then in "Additional Emulator Arguments" you would type in: **--bps** and then you could right-click on the text box and have an option to **paste "{Romhack#1Path}"**  and you would end up with: **--bps "{Romhack#1Path}"** in the "Additional Emulator Arguments" field.

It would also be neat if Playnite could be set to 'track playtime' when games are started from "Other actions" in connection with this feature.

---

Sorry for my long ranty 'post'. -- I tried to organize it a bit so it's less painful to read.
I apologize if this is dumb.

**Comment by JosefNemec** [comment]
Will be done via #502
