### ISSUE TITLE
Steam integration - playnite not detecting when source mod games are running

### ISSUE THREAD

**Issue by CatEyedLink** [JosefNemec/Playnite#1936]
When launching a source mod playnite fails to look for the correct process thus playnite doesn't know when game starts or closes preventing things like knowing how long the game has been play for ,or running game closing scripts. 

**To Reproduce**
Add a source mod to steam then playnite (this is at least a issue with Source SDK Base 2013 Multiplayer) I used Open Fortress then launch the source mod from with in playnite the game status will not change from "Launching"

**Screenshots**
![Bug](https://user-images.githubusercontent.com/42761348/88615978-998bd900-d058-11ea-8b01-da5c6440331a.png)

**Diagnostics ID**
b84a9f8a-206c-4a60-95f8-4704c20cbd2e
don't know if this helpful but here it is

**Comment by psychonic** [comment]
This is fairly simple to work around for mods. I can submit a PR if desired.

Tangentially, some actual Steam games probably have a similar issue if they specify a non-default working directory or include a subfolder in their executable path, in their default launch option. The fix would for would have to involve reading the appinfo if/when available.

**Comment by JosefNemec** [comment]
Feel free to submit pull request for this.

**Comment by JosefNemec** [comment]
Fixed in Playnite 8.
