### ISSUE TITLE
Ability for plugin to detect active langauge

### ISSUE THREAD

**Issue by mtkennerly** [JosefNemec/Playnite#1937]
**Check for existing issue**
I looked for `language`, `translation`, and `localization` in the issues list and in the SDK documentation.

**Describe the solution you'd like**
I think it would be helpful for plugins to be able to detect Playnite's active language at runtime. I'm working on a plugin, and I'd like for it to support localization, which I would typically do by putting the strings into a `Translator` class that can encapsulate language-specific logic (plural rules, gender, etc). However, I couldn't find a way for it to detect the active language.

I do see `GetString` in `IResourceProvider` in the docs, but I'm not really sure how to use it. I'm guessing I would have to put the strings into XAML somehow, and I'd prefer not to do that since I doubt it can express the same level of logic. (For example, I expect that it would require having separate lookups for predefined language rules, like `BackedUpGames_Singular` for "game" vs `BackedUpGams_Plural` for "games", which doesn't naturally lend itself to the additional `BackedUpGames_Dual` translation that Arabic would need.)

**Comment by darklinkpower** [comment]
If I understand right, it's this and has already been implemented for Playnite 8

https://github.com/JosefNemec/Playnite/issues/1837

**Comment by mtkennerly** [comment]
Thanks! You're right, I see it [in the linked commit](https://github.com/JosefNemec/Playnite/commit/028a46fc6cde72fb334a2557e24581f41ecd7a42#diff-4fd4fddcbf36eaaa25229b18c66147a3R77). I'll go ahead and close this.
