### ISSUE TITLE
Add "DisplayName" for some elements from game information

### ISSUE THREAD

**Issue by Lacro59** [JosefNemec/Playnite#1940]
When we update the metadata of a game, the data of an element (genre, feature, ...) is linked by name.
Thereby, it's impossible to keep a personal naming for this elements like this:
![unknown](https://user-images.githubusercontent.com/124054/89053991-5c755e80-d358-11ea-89f4-19e1ea7d5286.png)

Is it possible to add a "DisplayName" in database for this elements?

For example:
{"Id":"08053a63-aa3e-4983-ad8e-261a9dcdb522","Name":"Full Controller Support","DisplayName":"🎮 - Full Controller Support"}

**Comment by JosefNemec** [comment]
Will be done via #1902.
