### ISSUE TITLE
Humble Plugin Returning (400) Bad Request (Playnite 7.7)

### ISSUE THREAD

**Issue by LeeThompson** [JosefNemec/Playnite#1945]
**Describe the bug**
When attempting to update Humble games using the plugin, after about two minutes the Playnite notification area reports "Failed to import games from Humble. The remote server returned an error: (400) Bad Request."

**To Reproduce**
Try to update Humble games with the plugin

**Screenshots**
None

**Diagnostics ID**
5bd6dbfa-5f65-4245-9b3f-b65e5de0995c

**Comment by JosefNemec** [comment]
Duplicate to #1944
