### ISSUE TITLE
When scanning for emulated games, don't automatically checkmark every file found

### ISSUE THREAD

**Issue by Aleonz00** [JosefNemec/Playnite#1946]
For example, when scanning for RPCS3, it found over 800 .bin files in the God of War Origins Collection USRDIR folder. I certainly couldn't simply uncheckmark every single one of them. So a workaround I thought of was to delete everything from that folder other than eboot.bin (then restore after adding to Playnite) but it would still be nice to fix.

Thank you for your time.

**Comment by JosefNemec** [comment]
Will be done via #653
