### ISSUE TITLE
Add possibilty to close Random Game Selection with Keyboard 

### ISSUE THREAD

**Issue by kristheb** [JosefNemec/Playnite#1947]
Today it's only possible to close the Random Search Window by using the mouse.

Adding a the Keyboard functionality - either ESC or via a Cancel Button.
![grafik](https://user-images.githubusercontent.com/28502250/89343923-56a7b200-d6a5-11ea-8385-b16600cfcc66.png)

**Comment by JosefNemec** [comment]
Done in Playnite 8.
