### ISSUE TITLE
Installation Error: Error writing to file locales/gu.pak

### ISSUE THREAD

**Issue by sogeking90** [JosefNemec/Playnite#195]
This keeps happening?

**Comment by JosefNemec** [comment]
What folder are you trying to install to? Does it happen when you install into different folder?

**Comment by sogeking90** [comment]
Hey I solved the issue by running as admin.

**Comment by JosefNemec** [comment]
That's weird, installer should ask for admin rights. Do you have UAC dialogs disabled?

**Comment by sogeking90** [comment]
It asks if I want to run it, and Windows Smartscreen suggested I don't run it.

I installed it to G: rather than C: because I've no room on C:

**Comment by JosefNemec** [comment]
That's a different dialog, after SmartScreen you should get another dialog from User Account Control service asking for admin permissions. If not then you have that disabled in "User Accounts" system settings.

**Comment by sogeking90** [comment]
Yeah sorry, UAC asked if I wanted to run the application and I said yes. Didn't know that also is meant to run as admin?
