### ISSUE TITLE
A Total War Saga: TROY doesn't launch from Playnite.

### ISSUE THREAD

**Issue by TehJumpingJawa** [JosefNemec/Playnite#1956]
Attempting to launch A Total War Saga: TROY from Playnite results in the game delivering the error dialog "Please use the Epic launcher to start the game. Connection to the Internet is required."

Steps to reproduce:

- buy game (it's still free on The Epic Games Store for the next ~1h45m!).
- install game. (has to be done through the Epic Games Launcher).
- attempt to launch game.

![image](https://user-images.githubusercontent.com/1738163/90243677-386d4f00-de27-11ea-94c4-c63d41aba23a.png)

**Diagnostics ID**

ce2b329f-28c2-450e-a3a4-8a1f0c01b497

**Comment by JosefNemec** [comment]
Do you have option to launch games without Epic client enabled?

https://github.com/JosefNemec/Playnite/wiki/Epic-Game-Store-troubleshooting#game-doesnt-start-properly

**Comment by TehJumpingJawa** [comment]
Cheers, that fixed it.
