### ISSUE TITLE
Add completion status for endless games (For Multiplayer, MMOs, Arcades, etc)

### ISSUE THREAD

**Issue by darklinkpower** [JosefNemec/Playnite#1958]
**Describe the solution you'd like**
Add a new completion status for endless games to be used aor multiplayer, MMOs, arcade and other type of games that can be played infinitely. While the "Playing" status exists, I think having a completion status for the mentioned kind of games would make it easier to manage the games and make a clear distinction between the play content of the games. 

As said [in this comment in another issue](https://github.com/JosefNemec/Playnite/issues/1951#issuecomment-674388704) by  @shakeyourbunny a suggested name for this completion status is "Recurrent Play", although I think maybe "Recurrent Playing" could also work.

**Comment by JosefNemec** [comment]
Will be done via #1388
