### ISSUE TITLE
Filter and sorting not saving in fullscreen mode

### ISSUE THREAD

**Issue by fehbari** [JosefNemec/Playnite#1959]
**Describe the solution you'd like**

Filter and sorting reset every time you switch tabs in fullscreen mode. It’s very tedious to re-apply the filter and sorting order whenever I switch back and forth between All and other tabs. Ideally, the app would save the active filter and sorting and keep it applied until I manually hit “Clear”. Strangely though, the filter is kept active between app restarts and when switching between fullscreen and desktop mode, but not when switching tabs.

**To Reproduce**

Enter fullscreen mode. Switch to All tab. Apply a filter and change the sorting order (e.g. installed state > descending to sort by installed first). Switch to a different tab (say, Favorites), then back to All. Your filter and sorting options are gone, and need to be re-applied manually.

**Comment by JosefNemec** [comment]
#1930
