### ISSUE TITLE
Nested Grouping in Details View

### ISSUE THREAD

**Issue by shakeyourbunny** [JosefNemec/Playnite#1961]
Would it possible to implement nested grouping in the Detail View.

I'd like to group by genre first, then in the groupings by itself by Tags, but this should be possible in any combination.

**Comment by JosefNemec** [comment]
I can't image how would that actually look, can you do some mockups?

**Comment by shakeyourbunny** [comment]
Well, you have a new sort option in the sort menu called "Secondary Group(ing) by" which has the same sorting options as "Group By", but is responsible for secondary sorting.

Example is a list of games, first sorted by genre, then publisher, but you should be able to mix and match like you want.
Dataset is:
- Spa Mania (Alawar)
- Spa Mania 2 (Alawar)
- Hearts' Medicine - Hospital Heat (Gamehouse)
- Hearts' Medicine - Time to Heal (Gamehouse)
- The Love Boat (Gamehouse)
- The Love Boat (Second Chances)  (Gamehouse)

This yields into:
+ Time Management
    + Alawar
        + Spa Mania
        + Spa Mania 2
    + Gamehouse
        + Hearts' Medicine - Hospital Heat
        + Hearts' Medicine - Time to Heal
        + The Love Boat
        + The Love Boat - Second Chances

First picture is standard sorting, in this example, by Genre.
![mockup-nested-folders-category](https://user-images.githubusercontent.com/5352403/90381651-f38f2580-e07d-11ea-83ee-fe4b5e7b13db.png)

Secondary sort is - after sorting by genre - sorting by publisher nested into each genre.
![mockup-nested-folders-2nd-category](https://user-images.githubusercontent.com/5352403/90381708-0a357c80-e07e-11ea-96ba-222799da061f.png)

This results in
![mockup-nested-folders](https://user-images.githubusercontent.com/5352403/90381733-1588a800-e07e-11ea-94e7-2daea8a5feee.png)

Why I would propose this?

Mainly you can nest this by genre and then by sub-genre or similar stuff and this makes browsing in the detail view much more efficent. Maybe a tertiary sorting option, but this is imho overkill.

**Comment by JosefNemec** [comment]
Will be done via  #2912
