### ISSUE TITLE
Emulation/Notes Area

### ISSUE THREAD

**Issue by MaximusX800** [JosefNemec/Playnite#1962]
I think it would be very useful to have another section added to entries for the purpose of notating Emulation settings, for console games.

Obviously, the large Description area can house any text data we need, but for organization purposes, I think it would work well if console entries, PS2, Wii, etc, had an area labeled Emulation settings.  Some emulators, like Dolphin and Cemu, require specific configs, that are not default, to get a game running smoothly.  In this area we can document what settings we use, that way in the future, we can refer back to this data to get back up an running quickly.

If needs to be for all entries, Notes would do just fine, that way we don't have to segregate PC games and Consoles game entries for this new section.

**Comment by MaximusX800** [comment]
This area would also be useful for old PC games that require extra files/mods/configs to get them to run under a modern OS.

**Comment by JosefNemec** [comment]
Duplicate to #766
