### ISSUE TITLE
Emulated games metadata downloading doesn't work with some games due to the No-Intro naming convention

### ISSUE THREAD

**Issue by DiegoLeocadio** [JosefNemec/Playnite#1964]
Some emulated games with titles with articles in the beginning can't download metadata. The article in the beginning, according to the No-Intro Naming Convention (and also TOSEC, Redump) goes to the position after the title.

Games I had problems with:
Title: A Bug's Life
No-Intro: Bug's Life, A
This one probably doesn't work right because of the "A" article

Title: The Legend of Zelda: Majora's Mask
No-Intro: Legend of Zelda, The - Majora's Mask
This one probably doesn't work because it has a subtitle. Maybe Playnite is putting the "The" after the whole name of the game, something like "Legend of Zelda - Majora's Mask, The"

Title: Der Langrisser
No-Intro: Langrisser, Der
This one has German article, so maybe it isn't accounted by Playnite as an article yet.

The games above are only examples, they weren't the only ones with this problem.

**Comment by JosefNemec** [comment]
Done in `devel8` via cf17c3ae8e3641e341c7ab3948221c7768d994c5

It will however only fix issues with specific articles like The, A, An and Der. I can't consider anything after `,` to be an article because of games like Warhammer 40,000.

**Comment by shakeyourbunny** [comment]
If you have added the German article, please also consider "Die" and "Das". Those two words complement the German "Der" article.
