### ISSUE TITLE
Toolbox.exe reported as Malware by Malwarebytes

### ISSUE THREAD

**Issue by kryptot7** [JosefNemec/Playnite#1968]
**Describe the bug**
Today, Malwarebytes Premium Trial detected Playnite's TOOLBOX.EXE file as malware during a scan.
The category is "Malware.AI", which means malware detected by artificial intelligence. Info on Malwarebytes' website: https://blog.malwarebytes.com/detections/malware-ai/

**Screenshots**
![image](https://user-images.githubusercontent.com/30781325/90827821-efc40300-e30a-11ea-96cc-1cf1f63830c5.png)

**Comment by JosefNemec** [comment]
Clearly a false positive, there's nothing in Toolbox utility that can be considered malicious. You should submit support ticket with Malwarebytes that the AV is falsely reporting Toolbox as a malware.

![image](https://user-images.githubusercontent.com/3874087/90860595-91d70000-e38a-11ea-8c43-bfee20d39c6a.png)
