### ISSUE TITLE
Install your program with my script.

### ISSUE THREAD

**Issue by dpertierra** [JosefNemec/Playnite#1969]
**Describe the solution you'd like**
I'm writing a powershell script that set up windows for gaming and I would like to offer the user to install Playnite with the script.
I'll be downloading playnite from the latest release in your github repository.
I'll give playnite's website link and project link in the Write-Output in the script and in the github readme,

You can check the github project at https://github.com/dpertierra/win10script 

Let me know if there's any problem with me doing this.

**Comment by JosefNemec** [comment]
I have no issue with it.
