### ISSUE TITLE
Metadata download priority doesn't work if a plugin fails

### ISSUE THREAD

**Issue by DeN-AlB** [JosefNemec/Playnite#1970]
Is it possible that Playnite has a general problem with downloading metadata with 3rd party metadata plugins automatically?

Actually I use the following metadata plugins:
https://playnite.link/forum/thread-194.html
https://playnite.link/forum/thread-291.html

In the metadata settings of Playnite I selected these plugins and moved them to the top of the lists. When selecting some games and only download metadata for these games nothing happens. But when manually downloading metadata with the help of F3 for each game and selecting each pluging manually then metadata will be downloaded.

Here are some screenshots to help you understand the problem with the help of "Age of Empires: Definitve Edition (Steam)".

Try to automatically download metadata:
![Metadata_1](https://user-images.githubusercontent.com/55697152/90878548-f489c500-e3a5-11ea-9255-d3c1494ec7b1.jpg)
![Metadata_2](https://user-images.githubusercontent.com/55697152/90878553-f5225b80-e3a5-11ea-8284-93be0b54b84f.jpg)
![Metadata_3](https://user-images.githubusercontent.com/55697152/90878554-f5225b80-e3a5-11ea-98a5-f49d1c7a0091.jpg)
![Metadata_4](https://user-images.githubusercontent.com/55697152/90878557-f5baf200-e3a5-11ea-8120-a80dd31a81ea.jpg)
![Metadata_5](https://user-images.githubusercontent.com/55697152/90878558-f5baf200-e3a5-11ea-8274-b8910c82fee0.jpg)

Manually download metadata:
![MetadataManual_1](https://user-images.githubusercontent.com/55697152/90878559-f5baf200-e3a5-11ea-91b8-7b3305e075f8.jpg)
![MetadataManual_2](https://user-images.githubusercontent.com/55697152/90878561-f6538880-e3a5-11ea-8e54-3eaddc267524.jpg)
![MetadataManual_3](https://user-images.githubusercontent.com/55697152/90878563-f6538880-e3a5-11ea-9157-531c75dfec1b.jpg)
![MetadataManual_4](https://user-images.githubusercontent.com/55697152/90878564-f6538880-e3a5-11ea-96cd-085621dec800.jpg)
![MetadataManual_5](https://user-images.githubusercontent.com/55697152/90878566-f6ec1f00-e3a5-11ea-900b-5dfefd14ec04.jpg)
![MetadataManual_6](https://user-images.githubusercontent.com/55697152/90878567-f6ec1f00-e3a5-11ea-814a-359fc3f673c9.jpg)
![MetadataManual_7](https://user-images.githubusercontent.com/55697152/90878568-f784b580-e3a5-11ea-8e9f-b72431d336e8.jpg)
![MetadataManual_8](https://user-images.githubusercontent.com/55697152/90878569-f784b580-e3a5-11ea-8552-818e4726cedb.jpg)
![MetadataManual_9](https://user-images.githubusercontent.com/55697152/90878571-f784b580-e3a5-11ea-8bab-ff665f98019f.jpg)

I thought that it could be a problem with the used plugins but it seems to be a problem of Playnite in general?

**Comment by JosefNemec** [comment]
Done in `devel8`.
