### ISSUE TITLE
Full Screen Mode doesn't display horizontal game covers correctly 

### ISSUE THREAD

**Issue by woutercools** [JosefNemec/Playnite#1972]
In Full Screen Mode Steam games are presented in horizontal bounding boxing while I choose not to download vertical cover images.

**To Reproduce**
Download metadata for Steam games while deselecting "Download vertical cover images".
Start Full Screen Mode 

**Screenshots**
![2020-08-23 17_41_20-Window](https://user-images.githubusercontent.com/16439116/90982738-6eb67700-e569-11ea-9694-ad943280ca58.jpg)

**Diagnostics ID**
d88e0cee-ba13-4fbe-a2b9-3491fb689d84

**Comment by woutercools** [comment]
Ok, sorry for this oversight...

Would it be possible to choose the amount of games presented on 1 line in the grid-size of the desktop and the full screen mode?

ex.
desktop mode: 8 games on 1 line
full screen mode: 6 games on 1 line

**Comment by JosefNemec** [comment]
Desktop: change zoom level
Fullscreen: can be changed in the Fullscreen settings

**Comment by woutercools** [comment]
Sorry again...

Thanks for your replies
