### ISSUE TITLE
Add option for show playtime in grid view

### ISSUE THREAD

**Issue by Lacro59** [JosefNemec/Playnite#1973]
![desktop](https://user-images.githubusercontent.com/124054/91032125-cdc7ca80-e601-11ea-859b-cfa49e9eca9a.jpg)
![fullscreen](https://user-images.githubusercontent.com/124054/91032137-d0c2bb00-e601-11ea-96b6-c1a64c1ef002.jpg)

**Comment by JosefNemec** [comment]
Duplicate to #1569 Also, this is already possible via custom theme.
