### ISSUE TITLE
SDK - Add datas what can be used in custom theme

### ISSUE THREAD

**Issue by Lacro59** [JosefNemec/Playnite#1974]
Allow to add datas for the plugins in List View and Grid View.
![list view](https://user-images.githubusercontent.com/124054/91038432-0a4bf400-e60b-11ea-8e01-436c814696f5.jpg)
![grdi view](https://user-images.githubusercontent.com/124054/91038681-775f8980-e60b-11ea-8dff-942dc8591748.jpg)

**Comment by JosefNemec** [comment]
Duplicate to #1702 and partially to #502
