### ISSUE TITLE
Playnite will not restore in window, can only see it in miminized state

### ISSUE THREAD

**Issue by Bboy486** [JosefNemec/Playnite#1979]
**Describe the bug**
When running playnite on Windows 10 it starts in a minimized state and I cannot restore or maximize. I have reinstalled the software but the issue persists. 

**To Reproduce**
Launch Playnite on Windows. Playnite is minimized and unable to go into a windowed mode 
**Screenshots**
https://prnt.sc/u94ufj

https://prnt.sc/u94v9d
**Diagnostics ID**
Please generate diagnostics package from "About Playnite" menu and attach identifier you received. If the issue is a crash bug, you can generate diag. package directly from crash dialog.

I cannot as I cannot get into the settings.

**Comment by JosefNemec** [comment]
Please attach `%appdata%\Playnite\windowPositions.json` file and then delete it to fix the issue (while Playnite is not running).

**Comment by Bboy486** [comment]
{
  "Positions": {
    "Main": {
      "Position": {
        "X": -8.0,
        "Y": -8.0
      },
      "Size": {
        "X": 640.0,
        "Y": 680.0
      },
      "State": 2
    }
  }
}

**Comment by Bboy486** [comment]
Following up as I still cant launch this app. I have uninstalled and reinstalled and it is the same issue as my first post. TY!

**Comment by JosefNemec** [comment]
Do you have some 3rd party app that would interact with application windows? Something like a window manager? I have no idea why would the window position itself in -32000 pixel offset.

You can try manually changing the values to positive pixel offset, but Playnite should be doing that on its own already. This looks like some issue caused by a 3rd party to me.

Also, what's you screen configuration (number of screens, resolution and position)?

**Comment by JosefNemec** [comment]
You can also try using winkey + arrow keys shortcut to try to reposition the window.

**Comment by Bboy486** [comment]
It is on a 4K TV. The resolution is set for 2560 x 1440.

I do not have any third-party app and this only affects playnite. This machine is lean. 

I have re-installed and same issue. I am not sure what else I can do. When I hover over the task bar icon I can see the window outline but no content. Are there any other configs I can delete to force an update?

**Comment by JosefNemec** [comment]
Can you also try setting TV to its native resolution to see if it fixes the issue (and also deleting `windowPositions.json`)?

**Comment by Bboy486** [comment]
It is fixed. It was an issue with RDP and the resolution when remoting into that computer.
