### ISSUE TITLE
Adding icons in the top bar next to Steam Friends

### ISSUE THREAD

**Issue by IngwiePhoenix** [JosefNemec/Playnite#1981]
**Describe the solution you'd like**
When working with emulated games, sometimes it is neccessary to enter those directly in order to change settings. One easy way would be to add the respective emulator icons in the top row (or as a default action to each game from a platform) and have that launch the emulator. For PCSX2, for instance, `pcsx2.exe --nodisc` launches the emulator without a loaded image, allowing you to change settings within the BIOS itself. Letting this run windowed, and not using `--nogui` would allow one to have the virtual PS2 be in it's bios and allow one to customize all the various options.

Right now, I just launch the emulator from outside. It'd be nice to have this just a little streamlined though. Hence, this is low-priority.

**Comment by darklinkpower** [comment]
Tools submenu section will be in Playnite 8 and will achieve the same purpose
https://github.com/JosefNemec/Playnite/issues/197

Icons might be difficult since it's limited to a certain number of icons and that area is already used when downloading metadata.

**Comment by IngwiePhoenix** [comment]
Well, the tools menu will have to do, then. Thanks!
