### ISSUE TITLE
Emulated games: Automatically look for new games

### ISSUE THREAD

**Issue by IngwiePhoenix** [JosefNemec/Playnite#1982]
**Describe the solution you'd like**
There is already a Steam, GoG and other launcher's synchronizer. Whilst those synchronize games from these other clients, I wonder why there is no such thing for emulated games?

I store my emulated games in a very basic folder structure: A folder for each platform. For instance:
```
.../ROMs/
| GB
| |- lsdj.gb
| PS2
| |- Crash TwinSanity.iso
```
Setting a platform-folder relation for automated scanning would be neat!

**Comment by darklinkpower** [comment]
Duplicate https://github.com/JosefNemec/Playnite/issues/653
