### ISSUE TITLE
Detail View: Visibly distance Favorites from other games

### ISSUE THREAD

**Issue by IngwiePhoenix** [JosefNemec/Playnite#1983]
**Describe the solution you'd like**
I have way over 100 titles in my library now (Steam, GOG, Emulated)... and so I picked up a few favorites and would like to see them not just at the top of the list (already possible with the "..." menu) but also visibly distanced. In Steam, a divider is drawn underneath the last favorite, making the list look segmented on purpose and splitting favorites off into their own little group.

**Comment by darklinkpower** [comment]
Duplicate https://github.com/JosefNemec/Playnite/issues/207
