### ISSUE TITLE
Discord Rich Presence

### ISSUE THREAD

**Issue by IngwiePhoenix** [JosefNemec/Playnite#1984]
**Describe the solution you'd like**
I personally like to make my friends aware of what I am doing - so that if they do bug me, I can at least tell them to check my status ;) . RetroArch and many other games already support Discord Rich Presence - but, not everything does.

I would like to propose a "fake presence". This should be a little checkbox in the game settings and upon launch, Playnite should just send a rich presence to Discord for the duration that the game is running, using the title and icon specified in the game settings itself and maybe custom information as given by the user.

I play on PCSX2 a lot and that one does not have Discord Rich Presence - so, adding a "fake presence" would help a lot.

**Comment by darklinkpower** [comment]
Duplicate and will be in Playnite 8 
https://github.com/JosefNemec/Playnite/issues/767

**Comment by IngwiePhoenix** [comment]
Alright, closing then! ETA for v8?
