### ISSUE TITLE
Razer Raiju Ultimate Controller not supported in fullscreen (BT, DirectInput + XInput)

### ISSUE THREAD

**Issue by IngwiePhoenix** [JosefNemec/Playnite#1985]
**Describe the bug**
When entering the fullscreen mode, my controller is not recognized. It is listed as a DirectInput and an XInput device - so I must be missing something or Playnite is. Therefore I'd like to report this as a bug, but also suggest a "Connected Controllers" window to see what controllers Playnite recognizes.

**To Reproduce**
- Turn on Razer Raiju Ultimate in PC mode
- Enter Fullscreen
- Try to navigate - it won't work.

**Diagnostics ID**
`11d81874-8e94-411d-b967-fe61ad66be16` via About menu

**Comment by darklinkpower** [comment]
XInput controllers are fully supported. Dinput will be done via https://github.com/JosefNemec/Playnite/issues/684

If your controller is not recognized, it probably is working in DInput and that's why it's not recognized.

**Comment by IngwiePhoenix** [comment]
What's a good way to check if the controller is DInput or XInput mode?

**Comment by JosefNemec** [comment]
Duplicate to #684
