### ISSUE TITLE
Redistributable Library entries

### ISSUE THREAD

**Issue by IngwiePhoenix** [JosefNemec/Playnite#1986]
**Describe the solution you'd like**
Games like "Pokemon Reborn" don't actually have an entry on the Game's database that could be looked up and used - and some other games have additional configuration programs that are not listed this way either.

That is why I would like to propose a redistributable library entry format. Or at least, start discussion about it. With a format like this, it'd be possible to "install" a game into Playnite whose metadata is not publicy available.

This could be a simple schemed zip file containing a JSON file holding the textual information, `cover.jpg`, `bg.jpg` and `icon.png` for the images. Upon installing, Playnite would ask the user where the install location is to set up actions.

This is just a very rough idea. But here is why this would be beneficial:
- Using Adobe Flash Projector, it's possible to add flash games to your library. Since Flash is to be EOLd soon, there are alternative flash player projects to play them. Now, there is no clear database of all these flash games, so a redistributable library enentry format would allow to have a proper screen for those games added.
- A couple of indie/fan games, "Pokémon Reborn" for instance, do not have listings that could be used for metadata scraping.

Let me know what you think :)

**Comment by JosefNemec** [comment]
You could just create an entry in IGDB's database and Playnite will be able to pull it without any explicit support on our end. They do accept fan games as well.

My main issue with this is that you will have to have some database/website that would store that user information, and then we would have to add support for that database and then you basically end up with something like IGDB anyways, if you want it to be user friendly (and make people to actually use it).

Also, what you describe can be already implemented as a custom metadata provider plugin, if you want to read metadata from custom format/source.

**Comment by IngwiePhoenix** [comment]
> You could just create an entry in IGDB's database and Playnite will be able to pull it without any explicit support on our end. They do accept fan games as well.
Oh they do? I thought only normal, regular games are supported. Good, in that case I will work something out that way then.


> My main issue with this is that you will have to have some database/website that would store that user information, and then we would have to add support for that database and then you basically end up with something like IGDB anyways, if you want it to be user friendly (and make people to actually use it).
Why not take a page out of [Homebrew](https://brew.sh/)'s page and use Github? But I guess since IGDB supports a vast variety of games - even fangames, which I hadn't known yet... - it would be pointless to make this I guess.
 
> Also, what you describe can be already implemented as a custom metadata provider plugin, if you want to read metadata from custom format/source.
But can a Metadata Plugin also accept files? For instance, would I be able to create a file/url handler that points at Playnite and triggers the plugin? That would mean I could write this feature on my own terms and it would be completely independent - and optional, too.

**Comment by JosefNemec** [comment]
> But can a Metadata Plugin also accept files?

You can make a metadata plugin that will take metadata from any place or file format you want. Playnite only cares about resulting data (image formats and string data), Playnite doesn't care how the plugin got the data.

**Comment by JosefNemec** [comment]
I'm going to close this. It's nearly impossible to have some general metadata import support, because everybody will have different requirements to file names, file formats etc. If you need to import metadata from custom source, then you will need to write an extension for it.
