### ISSUE TITLE
reset to default or default option

### ISSUE THREAD

**Issue by amir788** [JosefNemec/Playnite#1989]
hi
The program has no option (reset to default or default option)

It has many settings playnite
Such an option is necessary for playnite
Change settings incorrectly This is not an option to go back default
add In the new update
Thanks

**Comment by JosefNemec** [comment]
Duplicate to #1935

**Comment by amir788** [comment]
@JosefNemec
You can just delete library folder to reset game library.

I can not do this option because the game information and game time are also deleted

**Comment by amir788** [comment]
@JosefNemec
please help answer

**Comment by JosefNemec** [comment]
Delete:
%appdata%\playnite\fullscreenConfig.json
%appdata%\playnite\config.json
%appdata%\playnite\Backup\fullscreenConfig.json
%appdata%\playnite\Backup\config.json
