### ISSUE TITLE
{InstallDir} not respected in "Image, ROM or ISO Path" (Game details) and "Working Directory" (Emulator definition)

### ISSUE THREAD

**Issue by Lockszmith** [JosefNemec/Playnite#1993]
In an attempt to make my library metadata as portable as possible, I liked the idea of the special dir variables available in Playnite.
However, it seems it isn't working everywhere.

Specifically I found that {InstallDir} was not respected in the Emulator definition of 'Working Directory' and that it was passes as a string (instead of the reference value) in the "Image, ROM or ISO Path" of the game details.

I apologize if I misused the values, and this issue shouldn't have been opened, if that is the case, I would be happy to be educated. However, I believe I covered my tracks by reading whatever I could find about these value-expansions.

Below are screenshots showing how I tested this with powershell.
Emulator Details:
- Executable:
  > ``powershell.exe``
- Arguments:
  > ``-noexit -command "Write-Output ('[PWD] = '+$PWD),'InstallDir = {InstallDir}','ImagePath = {ImagePath}','PlayniteDir = {PlayniteDir}'"``
- Working Directory:
  > ``{InstallDir}``

Screenshot:
![Emulator details](https://user-images.githubusercontent.com/905716/92518916-23e26380-f1e7-11ea-850a-a604f0fabcca.png)

Game Details:
- Image, ROM or ISO Path:
  > ``{InstallDir}\filename.ext``

Screenshot:
![Game details](https://user-images.githubusercontent.com/905716/92518869-11682a00-f1e7-11ea-82ba-c7d64796ce22.png)

The output when executing from the 'PowerShell emulator':
  > [PWD] = C:\ # Incorrect location
  > InstallDir = <Install Dir from Game Details>
  > ImsagePath = {InstallDir}\filename.ext
  > PlayniteDir = <PlayniteDir>

Screenshot:
![Powershell called from Game](https://user-images.githubusercontent.com/905716/92518892-1cbb5580-f1e7-11ea-8fa8-1186c8941048.png)

Now, I thought about possible reasons this wouldn't be respected (in the case this was by choice):
- preventing 'loops' between 'Installation directory' and 'Image, ROM or ISO Path' in case InstallationPath references ImagePath and vice-a-versa. I get that, and an error would be enough to allow only one of the fields to contain the other, and not both.

**Comment by JosefNemec** [comment]
Done in devel9.

This could easily create infinite recursion so I only implemented fix for this specific use case for now.
