### ISSUE TITLE
File (extension) handlers

### ISSUE THREAD

**Issue by IngwiePhoenix** [JosefNemec/Playnite#1996]
**Describe the solution you'd like**
With custom file types - themes and extensions, mainly - it'd be nice to have Playnite register file handlers for those to just double-click and install. Dragging into the window works, but I use a screen magnifier that certainly doesn't play nice with dragging files across. Having just a file handler (`playnite.exe extention.pext`) would ve really nice.

Allowing plugins to register those would be nice for whatever they might do, but not the most required.

**Comment by darklinkpower** [comment]
Duplicate and implemented for Playnite 8 https://github.com/JosefNemec/Playnite/issues/1584

**Comment by JosefNemec** [comment]
Please use search next time, you have fairly high number of duplicate issues, thank you.
