### ISSUE TITLE
Borderlands 3 (Epic) No Longer Launches From Playlite

### ISSUE THREAD

**Issue by LeeThompson** [JosefNemec/Playnite#1999]
This appears to have  happened recently with the release of the new DLC but when I try to launch Borderlands 3 from Playnite I get a popup "Please use the Epic launcher to start the game. Connection to the Internet is required."

It launches fine from a desktop shortcut and from the Epic launcher.

(The desktop shortcut points to: `com.epicgames.launcher://apps/Catnip?action=launch&silent=true`)

![borderlands3error](https://user-images.githubusercontent.com/1982261/92988597-ddf4fc00-f481-11ea-9520-ce854f0c5c0c.jpg)

Playnite 7.9 (Windows 10 x64 1909 10.0.18363)
Diagnostic ID: `49b63ea5-d7a1-4fca-a0bc-c82a9db1689b`

**Comment by darklinkpower** [comment]
Do you have the option to launch Epic games without the client enabled?

**Comment by JosefNemec** [comment]
See https://github.com/JosefNemec/Playnite/wiki/Epic-Game-Store-troubleshooting

**Comment by LeeThompson** [comment]
Thanks that worked, but it was working before; I wonder what happened.  (in fact, I removed the checkmark by 'Managed by library plugin' and the URL was already there, I changed nothing but now it launches).

**Comment by darklinkpower** [comment]
That's because the game didn't require the Epic client to run before, but that must have changed with the update. Please remember to check first the settings for specific libraries and troubleshooting pages when you have issues.
