### ISSUE TITLE
Ability to launch any game from tray icon

### ISSUE THREAD

**Issue by JosefNemec** [JosefNemec/Playnite#200]
Originally requested on [reddit](https://www.reddit.com/r/playnite/comments/76joxr/small_feature_request/):

it would be cool that when you rightclick on the tray icon, you'll get a list of all your games, not just the ones you started recently. maybe have sort of a menu for recent, all, categories etc.
basically make it easier to launch games through the tray icon menu.

**Comment by evgdovg1996** [comment]
@JosefNemec It would be cool if there was an option to limit the number of games displayed

**Comment by drakenation** [comment]
Honestly, this seems out of scope for a tray icon. I have hundreds of games on steam, having them all show on a tray icon doesn't seem very helpful.

**Comment by JosefNemec** [comment]
I'm going to close this. It would really clutter the tray context menu and also use a lot of resources if you have large game library.

**Comment by Evene174** [comment]
@JosefNemec What do you think about my suggestion about choosing to limit the number of games in the context menu? Is it difficult to implement or do not you like it?

**Comment by JosefNemec** [comment]
Lets say you would set it to show 10 games, what 10 games should it display? What order from the whole library would be used? I would have to add options for that as well.

**Comment by Evene174** [comment]
I think it would be cool if:
1) It was possible to simply limit the number of recent games to an arbitrary value (for example, from 1 to 10)
2) If there was an opportunity to keep the position the necessary game in a separate tab of the context menu (for example, as "open the playlist" and "open a third-party client")
