### ISSUE TITLE
Some games from epic launcher are no longer reported as installed

### ISSUE THREAD

**Issue by AmahaShadow** [JosefNemec/Playnite#2002]
Some games from the epic launcher have their installed flag pseudo-randomly reset. One in particular, Satisfactory, is always reset, even though it's correctly installed. I tried forcing the play action to bypass it, but the import resets the installation directory and installed flag in the database, so I have to set those back every time.

might be related to this issue ?
https://github.com/JosefNemec/Playnite/issues/1132

but the file C:\ProgramData\Epic\UnrealEngineLauncher\LauncherInstalled.dat does exist, and the game (Satisfactory) is in the InstallationList 
			"InstallLocation": "F:\\Epic\\SatisfactoryEarlyAccess",
			"AppName": "CrabEA",
			"AppVersion": "125236"
a Manifest does exist for this game, with the correct installation parameters
[843608C744121FA6B45E5FA24D55C2DD.item.txt](https://github.com/JosefNemec/Playnite/files/5213863/843608C744121FA6B45E5FA24D55C2DD.item.txt)
Playnite's log does not reference any issue (checked UUID from playnite, "CrabEA", "Satisfactory","Epic" ... nothing)

Diag ID c91ef069-3484-4f42-a8e2-8fa3507eae0c

**Comment by AmahaShadow** [comment]
PS, I had that issue last year, and did a full clean install of windows since when I changed M/B
I still tried to reinstall Epic Launcher and Satisfactory but, no fix

**Comment by JosefNemec** [comment]
You have import of installed Epic games disabled. Please enable it and try again.

**Comment by AmahaShadow** [comment]
Doy, I must have disabled it during my tests.
Oops 

Sorry about that

**Comment by AmahaShadow** [comment]
Ps : my original issue was I think due to the fact I had a mixed language install, but when I reinstalled, I switch to full English, so it now works correctly.

Thank you for the awesome work.
