### ISSUE TITLE
Nothing shows up when searching for anything with "X-"

### ISSUE THREAD

**Issue by arnoldsecret** [JosefNemec/Playnite#2004]
**Describe the bug**
It seems that anything that has "X-" in the title makes the IGDB search not show up anything, thus breaking the scraper.

**To Reproduce**
Try searching for "X-Blades" or "X-Men Origins: Wolverine".

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/41223243/93088202-31f32100-f6cc-11ea-8180-a3bfa55b8ec6.png)
![Untitled1](https://user-images.githubusercontent.com/41223243/93088210-3586a800-f6cc-11ea-8e64-fbe60adb0e6b.png)

**Comment by JosefNemec** [comment]
This is an issue with IGDB's API search, nothing I can do about it.

https://twitch.uservoice.com/forums/929953-igdb/suggestions/40812964-api-searches-don-t-return-games-that-exist-on-the
