### ISSUE TITLE
Custom saved views

### ISSUE THREAD

**Issue by leobenkel** [JosefNemec/Playnite#2005]
**Describe the solution you'd like**

The use case is that there are two main search I do often:

* first one is unfiltered , sorted by date added , just to see everything available and what new I got to find a new game to play
* second is game installed, sorted by last date played, so I can continue one of my started game.

It would be great to be able to save those and switch back and forth quickly and easily.

Thank you for your work, it is amazing !

**Comment by JosefNemec** [comment]
Duplicate to #590
