### ISSUE TITLE
Possible stuttering on G-Sync and FreeSync (VRR) displays

### ISSUE THREAD

**Issue by ProjectInfinity** [JosefNemec/Playnite#201]
Moving the Playnite window on a g-sync enabled monitor causes massive system wide graphical lag.
Turning Gsync off solves the problem but is a deal breaker.

**Comment by JosefNemec** [comment]
There's an option in settings to disable GPU acceleration, it removes the stuttering.

**Comment by JosefNemec** [comment]
Also duplicate to #125

**Comment by JosefNemec** [comment]
Actually I'm going to leave this open, since we might implement opt-in workaround for people that don't want to disable acceleration (which currently doesn't do much btw).

**Comment by JosefNemec** [comment]
Plus if you don't want to disable GPU acceleration then just create nVidia profile for Playnite and set `Monitor Technology` to `Fixed Refresh`.

**Comment by JosefNemec** [comment]
Workaround I was planning is not safe from performance point of view. I opened official WPF issue for this, so lets hope they will fix it in next release.

https://github.com/dotnet/wpf/issues/2294

**Comment by JosefNemec** [comment]
Closing as this has to be fixed in the UI library we are using and sadly they don't seem to care about fixing it. Nothing I can do about it from our side.

https://github.com/dotnet/wpf/issues/2294

**Comment by cnapolit** [comment]
This seems to be fixed (at least in Win11). I used to be plagued with this stuttering issue, but I haven't seen it in nearly a year now.
