### ISSUE TITLE
Image Resizer for cover image

### ISSUE THREAD

**Issue by trymeouteh** [JosefNemec/Playnite#2017]
I been using this app for over a year and I love it! The only thing it is missing in my opinion is a basic image resizing tool for the cover image. To have one in the setting that van be ran to resize every image cover for every game to ensure image covers are not over a certain width and height in size while maintaining its aspect ratio would be handy indeed. If one finds their game library to load slow, they can go to the settings and easily resize all the image covers to not exceed a certain size.

**Comment by darklinkpower** [comment]
Related to https://github.com/JosefNemec/Playnite/issues/1831

There's a partial in-progress pull request by @erri120 for that issue https://github.com/JosefNemec/Playnite/pull/1950

That issue is to add methods for extensions to do what you say, so it depends on that being added first.

**Comment by trymeouteh** [comment]
Any progress on this feature?

**Comment by darklinkpower** [comment]
No. The related pull request was closed by its author.
In the meantime you can use this extension to manipulate in some ways including resizing https://playnite.link/forum/thread-565.html

**Comment by trymeouteh** [comment]
This is not needed. I tested this with the latest version of Playnite and I find fullscreen mode is not slow, nor is switching between display modes.
