### ISSUE TITLE
Integrate Windows Compact function

### ISSUE THREAD

**Issue by ziplock9000** [JosefNemec/Playnite#202]
Is seems Windows 10 has a new compact function that has dramatic results on most games and decompresses very fast.

Details here: https://www.reddit.com/r/Windows10/comments/76hj26/i_tested_25_games_against_the_windows_compact/

**Comment by JosefNemec** [comment]
Wow that looks almost too good to be true. It would be cool to have an option in Playnite that would compress game folder automatically after game import.

**Comment by evgdovg1996** [comment]
@JosefNemec 
It's really works.
For example fortnite compressed from 16.9 GB to 800MB, lol, insanity
It may takes little more times for loads in games and it has an impact in games where your CPU is bottlenecked,so user must choose a right level of decompression
So compact function would be very cool for Playnite

**Comment by evgdovg1996** [comment]
@JosefNemec Also, it will be very cool if the description of the game will have a column and display the actual size occupied by the game (after the compact for example) like PS4/XBOX One

**Comment by ArtexJay** [comment]
It's not a bad idea but the compact thing could potentially corrupt or create issues for the game, i have encountered a few, while trying it

**Comment by ziplock9000** [comment]
@ArtexJay That's strange considering the compact command is part of the actual operating system. Maybe send MS a bug report?

**Comment by JosefNemec** [comment]
Closing. This is out of scope right now (not enough dev resources) and could be made via a 3rd party extension.
