### ISSUE TITLE
Mass-edit: Change emulators used

### ISSUE THREAD

**Issue by IngwiePhoenix** [JosefNemec/Playnite#2023]
**Describe the solution you'd like**
In a recent PPSSPP libretro update, there seems to be issues with startup: https://github.com/hrydgard/ppsspp/issues/13471
This affects me a lot. I am someone who hops between games a lot and I have my entire physical (and digital) collection of PSP titles dumped, compressed and organized. Those are about >20 (with more to come as I dump more games as I aquired an old collection) titles. The regular PPSSPP release (1.10.x) works as expected and after some fiddling with `installed.txt`, it now works with my previously made save files. Unfortunately, now I have to edit every single entry in the library to switch from RetroArch and PPSSPP profile to plain PPSSPP with 64bit profile.

My request is to be able to change the emulator on all those titles at once by changing the emulator used and the profile. This might also become relevant later for other emulators and libretro cores.

**Screenshots**
Right now, when selecting multiple games, this is all that is seen in the edit window:
![image](https://user-images.githubusercontent.com/2893716/94363622-bc238800-00c3-11eb-9d36-947ffa066db6.png)
The "Actions" tab is missing. I'd love to be able to adjust the profiles used in here.

**Comment by JosefNemec** [comment]
Duplicate to #547
