### ISSUE TITLE
[Request] Fullscreen Mode

### ISSUE THREAD

**Issue by Eebrohim** [JosefNemec/Playnite#203]
Just the ability to go fullscreen by using F11 or making it so you can "open in fullscreen mode" in settings.
It would make it look better without the task bar and bar at the top. Also similar to Steams "Big Picture" In the way that if you are using this on a PC connected to a TV, it would be easier to navigate through games, whilst looking fresh.

Also want to just say that I have seen that you have been working on this regularly and listening to feed back from the community and I think you deserve massive props for it.

**Comment by JosefNemec** [comment]
Already requested in #56
