### ISSUE TITLE
Cannot download certain game images from Google Image Search

### ISSUE THREAD

**Issue by w568w** [JosefNemec/Playnite#2031]
**Describe the bug**
When using the google image search for game images, some of them are shown correctly but unable to be downloaded into the local folders.  

**To Reproduce**
1. Change the language to Chinese (unnecessary)
1. Use a relatively unstable Internet connection
2. Open a game's detail window
3. Goto the `Media` tab
4. Click `G` Button
5. Choose a picture to download

**Screenshots**
![Recorder](https://user-images.githubusercontent.com/8389787/95004899-d4475a00-0623-11eb-9c9f-aad993b9a47d.gif)

**Diagnostics ID**
978a91ae-f1b6-4373-9df7-05b91fcf1760

**Comment by darklinkpower** [comment]
Can you check if it's not this issue? https://github.com/JosefNemec/Playnite/issues/1823

The image in the selection list is from Google images cache, but the original icon source might be no longer available.

**Comment by w568w** [comment]
> 
> Can you check if it's not this issue? #1823
> 
Thanks! It seems to make sense.   
But the origin icon should be still available. The source url of the first one I selected in the screenshot is `https://pht.qoo-static.com/FR5U2L-pl_Od7uUgetBGo52Dhue8OLI7GTadrvY9kP1NzqE-0wv3PQZaTlU_GG8Kmt8N=w300`.  
And the third one is from `https://pht.qoo-static.com/xsrLVmvyWRafbzCdy4ci2SXUzgSZZ0Sf-LJzB1bVarL5vTUBIAFLabcwGsC0CjSnbg=w300`,  
and the second:`https://i3-ws.resource.ccplay.cn/media/images/topic/2020/09/27/1547-06-231/xsny.jpg-icon.xhuge`.  
  
All of them seem to be available. Only the second one could be loaded in Playnite, though.

**Comment by JosefNemec** [comment]
I'll look into it, but some files will simply not download properly because of websites using protections from scripts and scrappers that make it impossible to download them in Playnite.

**Comment by JosefNemec** [comment]
I've made some changes to this in Playnite 8 that should make image downloads more reliable. If it still doesn't work with some images, then there's nothing I can do about it. The issue is with Google indexing sources that no longer exist or that are not reachable in a way we have to use for downloads from Google to work in the first place.
