### ISSUE TITLE
Swap running Playnite instance to fullscreen if Playnite.FullscreenApp.exe is run

### ISSUE THREAD

**Issue by Xacorman** [JosefNemec/Playnite#2036]
Currently running Playnite through PlayniteUI.exe (Standalone install) and when I try to launch it fullscreen through Geforce Gamestream using Playnite.FullscreenApp.exe nothing happens. The only way that Playnite.FullscreenApp.exe works is if the existing Playnite instance is exited. Swapping the mode manually isn't an option through gamestream as it just launches executables.

**Comment by JosefNemec** [comment]
PlayniteUI.exe is only fallback executable for older versions and shouldn't be used anymore. You can force specific mode via cmdline in [Playnite 8](https://playnite.link/docs/playnite8/manual/cmdlineArguments.html).
