### ISSUE TITLE
Fullsceen mode launched during system startup doesn't have input focus

### ISSUE THREAD

**Issue by JosefNemec** [JosefNemec/Playnite#2038]
Don't know how to solve this to be honest. It sometimes happens if other apps start during boot process and Windows doesn't return focus back to Playnite or when some other app is displayed on top of Playnite.

**Comment by fehbari** [comment]
My personal workaround for this in my living room "console-like" PC is setting up a task in task scheduler for Playnite, with a login trigger delayed 30 seconds. Not ideal but allows everything else in my machine to start before Playnite, so there's no focus loss when it starts.
