### ISSUE TITLE
Random crash

### ISSUE THREAD

**Issue by jacksauciboie** [JosefNemec/Playnite#2046]
**Check for existing issue**
Please use issue search in the repository if the bug is something really obvious there's a high change it was already reported.

**Describe the bug**

**To Reproduce**
If it's not clear from the description how to reproduce the issue please add clear steps to reproduce the behavior.

**Screenshots**

**Diagnostics ID**
Please generate diagnostics package from "About Playnite" menu and attach identifier you received. If the issue is a crash bug, you can generate diag. package directly from crash dialog.
![Screenshot 2020-10-12 205747](https://user-images.githubusercontent.com/65568056/95785416-9bffe580-0ccd-11eb-8632-18c735e5f5f7.png)

**Comment by darklinkpower** [comment]
Please follow the issue template (Describe, Diagnostic ID, etc), otherwise there's no way of knowing what happened.

**Comment by JosefNemec** [comment]
Nothing I can do with report like this.
