### ISSUE TITLE
Launching games from Battle.net

### ISSUE THREAD

**Issue by Cyberdroid1** [JosefNemec/Playnite#2047]
I am not able to start any game from Battle.net via Playite. Linking play action to executable of game launches Battle.net but does not start game. Please guide me onto this.

**Comment by JosefNemec** [comment]
Battle.net client doesn't support startup of PTR versions externally, nothing I can do about that.

If the game is not being automatically detected as installed, then see [this link](https://github.com/JosefNemec/Playnite/wiki/Battlenet-troubleshooting#games-not-reported-as-installed).

**Comment by Cyberdroid1** [comment]
Thank you for informing this.

**Comment by Cyberdroid1** [comment]
Can you please add this somwhere in documentation or troubleshooting page for Battle.net?

**Comment by JosefNemec** [comment]
The link for troubleshooting is on the view where you configure battle.net settings and also links from "known issues" on wiki page there as well.
