### ISSUE TITLE
Untranslatable strings in Playnite 8.1

### ISSUE THREAD

**Issue by ClearStrelok** [JosefNemec/Playnite#2048]
The following strings appear to be currently unavailable for translation in Crowdin : 

- Left
- Top
- Right
- Bottom
- Discord Rich presence
- Global
- Filtered

**Comment by darklinkpower** [comment]
For reference:

Left, Top, Right, Bottom (Sidebar location)
![imagen](https://user-images.githubusercontent.com/1389286/96023272-c958aa80-0e17-11eb-9b80-5fffbf0d2492.png)

Global, Filtered (Statistics view panels)
![imagen](https://user-images.githubusercontent.com/1389286/96023369-f1480e00-0e17-11eb-991b-0259b742880d.png)

Discord Rich presence (Settings >> Advanced)
![imagen](https://user-images.githubusercontent.com/1389286/96023421-0624a180-0e18-11eb-9ae2-20f042c3d37d.png)

**Comment by ClearStrelok** [comment]
Two more in **Edit > Download Metadata**

- Current 
- New

![Untitled-2](https://user-images.githubusercontent.com/38838369/96046695-2bdf9400-0e74-11eb-8b9e-f0a145bd161b.jpg)

**Comment by JosefNemec** [comment]
I don't know if `Discord Rich presence` should be translatable. I don't even know how would I translate that into my native language.

**Comment by darklinkpower** [comment]
I don't see Left, Top, Right, Bottom in Crowdin, was that fixed in other way?

**Comment by JosefNemec** [comment]
They are already there `LOCDock*`.

**Comment by ClearStrelok** [comment]
The **Desktop** translation string also appears to be missing from Crowdin while the **Fullscreen** string is already translated but unassigned just like left/top/Bottom. I've opened issue #2062 for thoses.


![Untitled-2](https://user-images.githubusercontent.com/38838369/96348666-c45f5980-10aa-11eb-9584-1847292b3482.jpg)

**Comment by JosefNemec** [comment]
Desktop and Fullscreen strings on that screenshot shouldn't be translatable, since they are names of operation modes.

**Comment by Bluscream** [comment]
Most game settings also translate "Windowed", "Windowed Fullscreen" and "Fullscreen" into the selected language, so i don't see a reason for playnite to not do that

**Comment by JosefNemec** [comment]
`Fullscreen` is a proper noun in this case, it's name of the mode (like Steam's Big Picture). It's pretty generic name (because I couldn't think of anything better), but still. Also, it does in fact run in a window.

**Comment by JosefNemec** [comment]
Fixed in 8.2
