### ISSUE TITLE
PlayStation Library Import DLC Identification

### ISSUE THREAD

**Issue by adrianluff** [JosefNemec/Playnite#2049]
Sony has well structured identifiers for the type of content. The specifics vary by platform (PS3, PS4, PSVita) but are generally consistent otherwise. These identifiers are being stored by Playnite in the "Game Id" field. For example:
`#DLIST#UP1023-CUSA02159_00-ANEZ2DLCPL0003C1`

This can be identified as DLC from the identifier - and therefore should not be imported.

There are guides to these identifiers available from here:
https://www.psdevwiki.com/ps3/SKU_Regioning

**Comment by JosefNemec** [comment]
That link only mentions regions, not the whole format for those download list IDs and it doesn't look like they have it documented on that wiki.

**Comment by adrianluff** [comment]
Here is a direct link to the ID format:
https://www.psdevwiki.com/ps4/IDs_%2B_labels

I was mis-remembering apparently. At least for PS4 it does not explicitly define DLC.
