### ISSUE TITLE
Games languages and RegionS

### ISSUE THREAD

**Issue by TheDatadrainer** [JosefNemec/Playnite#2050]
**Check for existing issue**
Adding a "Languages" options in Edit Game Details and allow more than one region as a game can be available in different regions.

**Describe the solution you'd like**
1) In the "General" tab, please, add a combo box to choose the languages supported by a game like "Genres or Categories" and allow to sort on that.
2) In the "General" tab, make the + button of "Region" to add more than one region

Thank you

**Screenshots**
-

**Comment by JosefNemec** [comment]
I'll think about it. Right now this would be mostly useful for emulation, but you technically can't have one game that can launch different region variants, or have multiple game media assigned (for different regions). So it will at least have to wait until #653 is implemented.

**Comment by TheDatadrainer** [comment]
Thanks for your answer.

The most important thing for me would be the addition of a [Languages] field to set the languages supported by games. In Europe it is common to have the choice from multiple languages in games (recent or not). And be able to find easily which game support which languages would be great.

Now about the regions, you're right, that would be mostly useful for emulation. And that's why I wanted your advice. It would especially suitable for consoles games that are region locked. As some games uses the exact same ROM for different regions. Just need to set the emulator to the needed region and that's it. But among such games, some can read the region and change how they work, but most works exactly the same. And it is this last case that I found annoying, but your brings some enlightenment.
There is two possible ways to manage them:
- One is to create two shortcuts with one launcher for each game region.
- The other is to create a single shortcut with a launcher for each game region.

After thinking about it, it seems indeed that the first option is the correct one. Because setting two regions for a shortcut having two launchers, one for each region seems nice but it is not and should not be done as it brings more confusion than really helping to understand what is behind.

But please, consider adding the support for languages in later releases. Thanks again.

Have a nice day.

ps: I have another request about how to manage the library folder, but I'll talk about that later on the forum.

**Comment by TheDatadrainer** [comment]
Lacro59 is working hard to create a plugin managing games languages. The plugin supports to set user interface, audio and subtitles languages automatically and manually.
So as there is a powerful solution available, it is not important for Playnite to integrate natively such a functionality for now.

> The Lacro59 plugin description on the Playnite forum: [https://playnite.link/forum/thread-384.html](https://playnite.link/forum/thread-384.html)
> And the repo: [https://github.com/Lacro59/playnite-checklocalizations-plugin](https://github.com/Lacro59/playnite-checklocalizations-plugin)

Consequently I'm closing the issue.
