### ISSUE TITLE
--shutdown only works properly on Playnite.DesktopApp.exe

### ISSUE THREAD

**Issue by magalhas** [JosefNemec/Playnite#2051]
When trying to run Playnite.FullscreenApp.exe with the `--shutdown` flag the fullscreen gets closed instantly after the desktop app being closed.

**Comment by JosefNemec** [comment]
I'm not sure I understand what the issue is here, `--shutdown` is suppose to make sure that there are no running instances of Playnite. If you want to force specific operation more then you need to use `--startdesktop` or `--startfullscreen`.

**Comment by magalhas** [comment]
Playnite.FullscreenApp.exe --shutdown --startfullscreen does not work.

**Comment by JosefNemec** [comment]
Don't use shutdown if you are already using  --startfullscreen.

**Comment by magalhas** [comment]
Will it close any previously opened Playnite.DesktopApp.exe?

**Comment by JosefNemec** [comment]
Yes https://playnite.link/docs/manual/cmdlineArguments.html

**Comment by Bluscream** [comment]
Lmao

**Comment by JosefNemec** [comment]
@Bluscream How's your comment relevant to this issue?

**Comment by Bluscream** [comment]
it's just a comment. It does not need to have relevant substance (https://en.wikipedia.org/wiki/Topic_and_comment)
