### ISSUE TITLE
OnGameSelected in powershell script gets fired upon closing playnite

### ISSUE THREAD

**Issue by joyrider3774** [JosefNemec/Playnite#2053]
**Check for existing issue**
did not really find similar issue

**Describe the bug**
It seems in a powershell script that OnGameSelected event gets fired upon closing playnite. My guess is that when game details pane gets destroyed or hidden or set to nothing that it triggers the event. 

Edit: This only happens when library is being updated and you close the application while the updating is active and you answer yes to stopping the background task. So maybe not a bug after all ? 

**To Reproduce**
Create powershell script with following ongameselected event and provide hardcoded absolute path to a wav file, when selecting a game it should play the sound. However when pressing the close button from the window with me it seems to play the wav as well upon closing. 
```
function global:OnGameSelected()
{
    param(
        $args
    )
    
        $global:player = New-Object -TypeName System.Media.SoundPlayer
        $global:player.SoundLocation = "c:\Sound\GameSelected.wav"
        $global:player.Load()
        $global:player.Play()
}
```

Do watch out it's possible some extensions rely on the gameselected being triggerd when nothing gets shown (or so) but i'm not sure it matters upon closing the application

**Screenshots**
none

**Diagnostics ID**
698575e6-8d5e-4d5f-b5c9-0364b0b8d2e0

**Comment by JosefNemec** [comment]
Fixed in `devel`.
