### ISSUE TITLE
Black Ops Cold War support

### ISSUE THREAD

**Issue by fehbari** [JosefNemec/Playnite#2054]
**Check for existing issue**
Nothing similar

**Describe the bug**
Black Ops Cold War launches in a few weeks. Similar to previous years, it needs to be added manually to Playnite. As of today, owning the game in Battle.net doesn't import it to Playnite.

**Comment by JosefNemec** [comment]
We have to add support for each Battle.net game manually, that's why it's not being detected. I'm going to close this because I don't think it's worth the effort adding support for beta version which will be available only during one weekend.

**Comment by fehbari** [comment]
> adding support for beta version which will be available only during one weekend

I disagree with this. The Battle.net entry and game install paths for the beta are the same as the final version. You wouldn't be adding support for the beta, but for the entire game. There's no separate "beta" and "retail" version as you'd see in other launchers here.

**Comment by fehbari** [comment]
Also, I'd like to point the final game comes out in 3 weeks and there's no other ticket. It's work that will need to be done anyway so I don't understand closing the ticket. Do notice the title doesn't refer to the beta exclusively, but the game.

**Comment by JosefNemec** [comment]
No the entries are not the same, internal IDs for that game are all marked with "beta" string (zeusb and zeus_beta), so I would have to remove it and create new entry for final game.

**Comment by fehbari** [comment]
Fair enough. In that case I'll edit the description to be clearly about the final version in 3 weeks. Thank you

**Comment by JosefNemec** [comment]
Is the full game actually visible in battle.net client if you bought it already (as separate entry to beta one)? And also [here](https://account.blizzard.com/games)? I won't be able to fully add support for it unless it starts showing up as final game on that link.

**Comment by fehbari** [comment]
There's a single entry in Battle.net for the game. It appears ever since I pre-ordered. From my POV, all that changed with the beta released was the same UI entry now had the "Install/Play" button enabled. But I can't vouch for internal IDs as I'm not sure how you're seeing those.

Here's a screenshot of the games page you asked me to see:

<img width="902" alt="game-accounts" src="https://user-images.githubusercontent.com/3378355/96284268-b975cd80-0fb3-11eb-927b-2230b1f1186e.png">

I'll send you a message with the data returned by the API for that page. Let me know how I can help. If there's any useful info I can extract from my account or the launcher I'll be happy to do so.

**Comment by fehbari** [comment]
I see now where you get the internal IDs from. My (beta) client shows a single entry, the config file indeed lists it as `zeus_beta`

![Blizzard Battle net 16_10_2020 14_33_59](https://user-images.githubusercontent.com/3378355/96291062-f1820e00-0fbd-11eb-9f97-9e2d108f3f08.png)

```
{
   "zeus_beta":{
      "ServerUid":"zeus_beta",
      "LastActioned":"1602653681",
      "Resumable":"false",
      "LastPlayed":"1602803045"
   }
}
```

I'll update this thread as soon as I see the final game entry show up in my client.

**Comment by JosefNemec** [comment]
Done in 8.7
