### ISSUE TITLE
Minecraft Dungeons stuck in “Running” state after exit game

### ISSUE THREAD

**Issue by fehbari** [JosefNemec/Playnite#2055]
**Check for existing issue**
Nothing found

**Describe the bug**
Playnite is able to import and start Minecraft Dungeons from Xbox/Windows Store just fine. But after exiting the game, Playnite says it is still running. I have to manually click the button again and choose to revert to previous state. A consequence of that is play time is always at 0.

**To Reproduce**
Install Minecraft Dungeons from Game Pass or Microsoft Store. Import into Playnite. Launch the game. Exit the game. Playnite says the game is still running.

**Comment by JosefNemec** [comment]
It's an issue with the game, the game process sometimes takes longer to actually stop running (usually under a minute). The same issue can be seen with The Outer Worlds and some other games. Nothing I can do about it.
