### ISSUE TITLE
"Show only assigned fields" setting doesn't work

### ISSUE THREAD

**Issue by burnpsy** [JosefNemec/Playnite#2056]
**Describe the bug**
I have the new feature to not list unused fields in the Filter panel enabled. Even though none of my games have regions, it still shows in the filter panel.

I've also had similar issues with Version, User Score, Community Score, but only Region was left blank for the sake of this report and diagnostics package.

Far as I can tell, it just doesn't work.

**Screenshots**
![2020-10-15](https://user-images.githubusercontent.com/6007819/96183317-b7086a80-0f04-11eb-9894-b6c2cbb70d95.png)
![2020-10-15 (1)](https://user-images.githubusercontent.com/6007819/96183316-b66fd400-0f04-11eb-97e6-0b63cc256aa5.png)
![2020-10-15 (2)](https://user-images.githubusercontent.com/6007819/96183472-ea4af980-0f04-11eb-89fc-f705904545d8.png)

**Diagnostics ID**
50847dff-f4b0-492b-9a36-5778cf10c42a

**Comment by darklinkpower** [comment]
Oh, it seems there has been a misunderstanding regarding what this feature does.

What this feature does is hide the items inside the filter that don't have games assigned. For example, let's say you have in Regions:

![imagen](https://user-images.githubusercontent.com/1389286/96199061-2473c580-0f1c-11eb-9955-edd5c2c84ecb.png)

Let's say `Europe` is used by 0 games in your library. For each of the regions, Playnite will check if there are games that have that item assigned to it. If that is not the case, that specific item won't be show in the filters. In this case, `Europe` would be hidden.

![imagen](https://user-images.githubusercontent.com/1389286/96199243-af54c000-0f1c-11eb-8712-a6a71a1cb9a5.png)

---

The only way to hide those filters completely would be making a custom theme that modifies the filter panel to remove them

https://playnite.link/docs/tutorials/themes/introduction.html

**Comment by JosefNemec** [comment]
It's like darklinkpower describes, what you are asking for is #1423
