### ISSUE TITLE
Game Details Edit Button Disappears When Mousing Over Panel Borders Or Main Panel

### ISSUE THREAD

**Issue by xyifer12** [JosefNemec/Playnite#2057]
When the mouse is over or near a panel border, or over the main panel, the edit button in game details view disappears. This occurs even if the panel border is set to be hidden in the options menu. This causes the button to flicker when moving the mouse around.

I've included a comparison image with red dots representing the location of the mouse.

![adasd](https://user-images.githubusercontent.com/33806276/96224986-00cd7100-0f56-11eb-8007-1817758aeea8.png)

**Comment by JosefNemec** [comment]
This is completely handled by a theme. If you are using custom theme, then you need to report the issue to theme's author. We don't provide support for custom themes here.
