### ISSUE TITLE
Crash after IndieGala library import

### ISSUE THREAD

**Issue by ohadschn** [JosefNemec/Playnite#2059]
**Describe the bug**
Playnite crashed after I Imported my indiegala games via the community plugin downloaded from here: https://playnite.link/forum/thread-344-post-2090.html#pid2090

**Screenshots**
![image](https://user-images.githubusercontent.com/8555641/96261558-45debb00-0fc9-11eb-9317-48cb72f4ac05.png)

**Diagnostics ID**
0660b105-896f-4671-9ca8-c287b015b36e

**Comment by JosefNemec** [comment]
Please report issues related to 3rd party extensions to their author. We don't provide support for 3rd party extensions here.

**Comment by ohadschn** [comment]
Sure, opened https://github.com/Lacro59/playnite-indiegala-plugin/issues/7

@JosefNemec Could you share the diagnostics associated with the ID `0660b105-896f-4671-9ca8-c287b015b36e` so I can forward it to the extension's author?
