### ISSUE TITLE
Playstation integration adds DLCs and media apps as games

### ISSUE THREAD

**Issue by cristi1990an** [JosefNemec/Playnite#2061]
![2020-10-17_01h44_23](https://user-images.githubusercontent.com/23399600/96320207-62efaa00-101a-11eb-81c0-bd1dd07c87aa.png)

**Comment by JosefNemec** [comment]
I haven't found a way how to reliably detect DLCs. For now you'll have to remove then and add them to ignore list.

**Comment by JosefNemec** [comment]
I found a way how to filter those out (both apps and dlcs), I'll fix it in one of the upcoming updates.

**Comment by JosefNemec** [comment]
Closing because Sony completely removed download list source that we used to import this.
