### ISSUE TITLE
Unassigned translation strings in Playnite 8.1

### ISSUE THREAD

**Issue by ClearStrelok** [JosefNemec/Playnite#2062]
The following strings have been translated but are not currently being used in some places :

- Left
- Top
- Right
- Bottom
- Fullscreen

> 
> 
> For reference:
> 
> Left, Top, Right, Bottom (Sidebar location)
> ![imagen](https://user-images.githubusercontent.com/1389286/96023272-c958aa80-0e17-11eb-9b80-5fffbf0d2492.png)
> 
_Originally posted by @darklinkpower in https://github.com/JosefNemec/Playnite/issue_comments/708545938_

![Untitled-2](https://user-images.githubusercontent.com/38838369/96348771-78f97b00-10ab-11eb-9d81-15d1da0d111d.jpg)

**Comment by JosefNemec** [comment]
Desktop and Fullscreen strings on that screenshot shouldn't be translatable, since they are names of operation modes.

Dock strings are already on Crowdin.
