### ISSUE TITLE
Controller/Gamepad support for Desktop mode

### ISSUE THREAD

**Issue by notNSANE** [JosefNemec/Playnite#2066]
Since the Fullscreen mode lacks major features, I think a request is in order to add the most basic functionality for Desktop mode with a gamepad:

1. Move between games with Left Analog Stick/D-Pad
2. Press A/RT to emulate a click
3. Press Start to start a game
3. Emulate mouse with Right Analog Stick

**Comment by JosefNemec** [comment]
I'm really sorry, but I'm not adding controller support to Desktop mode. It's a nightmare to make it reliable, given how complex the UI is and it's made even worse once you start using custom themes. I did experiment with it in the past and it's just too much of a headache to deal with.

I recommend using some 3rd party app like JoyToKey to emulated keyboard and mouse if you want to use controller in desktop mode.

**Comment by JosefNemec** [comment]
I forgot to mentioned that I definitely plan to improve Fullscreen mode. I'm well aware of fact that there are features missing from it and I will improve it going forward.
