### ISSUE TITLE
Gamepad battery status (Fullscreen)

### ISSUE THREAD

**Issue by GreenRabbits** [JosefNemec/Playnite#2067]
Hello,

Is it possible to create a gamepad battery icon, in the header of Playnite Fullscreen, (next to the bell notification icon) ? Also, this requires an option in the parameters to enable/disable it.

**Comment by darklinkpower** [comment]
Duplicate

https://github.com/JosefNemec/Playnite/issues/1826

Remember to use the search function to see if something has already been suggested. If you have ideas you can share them in the existing issue if that is the case.
