### ISSUE TITLE
Release date showcased under the game title

### ISSUE THREAD

**Issue by PrynceAssassin** [JosefNemec/Playnite#2070]
Hi as shown in the picture, wouldn't it be possible later on to have the opportunity to show the release date of their expected games? I made 2 examples as in the picture

sorry for my bad english
![SharedScreenshot](https://user-images.githubusercontent.com/73237768/96729329-51f5be80-13b5-11eb-9c89-6d977911ae8d.jpg)
![SharedScreenshot1](https://user-images.githubusercontent.com/73237768/96729336-5326eb80-13b5-11eb-8a44-b042941ce247.jpg)

**Comment by JosefNemec** [comment]
Duplicate to #1569
