### ISSUE TITLE
Playnite 8.3 hangs after launching any Itch game

### ISSUE THREAD

**Issue by sinbad** [JosefNemec/Playnite#2074]
I’d noticed since either 8.2 or 8.3 that after finishing playing any Itch game, PlayNite doesn’t re-open and in fact is reported as “Not Responding” in Task Manager. I have to kill the process and restart it.

I play Itch games quite regularly and this is a new occurrence, it used to work fine. I’ve reproduced it with 3 different Itch games so it’s not specific to one game.

Thanks for PlayNite, it’s great 👍

**Comment by JosefNemec** [comment]
Please attach requested information from issue template (mainly diagnostics package).

**Comment by sinbad** [comment]
Sorry, when I raised this on my iPad yesterday it didn't prompt me for a template, I don't know why.

**To Reproduce**
Start an Itch game from Playnite, run it for a few seconds, then exit. Playnite will be stuck as "not responding" but all the associated processes report 0% CPU. The Itch app is perfectly resposive.

I'm using the latest Playnite and Itch app.

**Screenshots**
![image](https://user-images.githubusercontent.com/142735/97161903-53890300-1776-11eb-8dce-f6308745e881.png)

"Helper program for itch app" is not always showing as running, nor console host. Sometimes it's just the Playnite exe and one CefSharp process.

**Diagnostics ID**
35fe325d-ae9d-42ba-8daf-96ccdd2b0a7d

**Comment by sinbad** [comment]
I should clarify that running Steam and Epic games does not have this problem.

**Comment by MathWhiz** [comment]
I have also had this issue with Itch games, but not Steam or GOG games

**Comment by JosefNemec** [comment]
Fixed in 8.4

**Comment by sinbad** [comment]
Thanks for the quick fix!
