### ISSUE TITLE
Suggestion for itch.io Game icons downloads like on Steam

### ISSUE THREAD

**Issue by Slippy2k** [JosefNemec/Playnite#2077]
**Describe the solution you'd like**
Is there no way to download the icons like Steam? I've seen every game on itch.io has an icon. Here is an example from the HTML source code:
<!DOCTYPE HTML><html lang="en"><head><meta charset="UTF-8"/><meta content="#ffffff" name="theme-color"/><meta content="https://img.itch.zone/aW1nLzM1MDc1NzMuZ2lm/original/Yqwd1q.gif" property="og:image"/><link rel="icon" href="https://img.itch.zone/aW1nLzM1MDc1NzMuZ2lm/32x32%23m/22ywjR.gif" type="image/gif"/>

**Comment by JosefNemec** [comment]
Where's the example? Are you talking about favicon?

**Comment by Slippy2k** [comment]
Yes this is from HTML Sourcecode the Favicon:

`  | <!DOCTYPE HTML><html lang="en"><head><meta charset="UTF-8"/><meta content="#000000" name="theme-color"/><meta content="https://img.itch.zone/aW1nLzQzMzI4MzcuanBn/original/BHIkhB.jpg" property="og:image"/><link rel="icon" href="https://img.itch.zone/aW1nLzQzMzI4NTMuanBn/32x32%23/At5Llm.jpg" type="image/png"/>
-- | --


`

**Comment by JosefNemec** [comment]
I'm not sure if using favicon is a good idea. They look really bad. I tried only couple of them and they don't seem to exceed 32x32 resolution and even then they don't look good. Check this one from Pyre: https://img.itch.zone/aW1nLzE5ODYzODcucG5n/32x32%23/m13KG3.png

**Comment by Slippy2k** [comment]
I know that the icons are not that big but that was one of my thoughts better than no icons at all

**Comment by JosefNemec** [comment]
Closing, favicons are just not suitable for this.
