### ISSUE TITLE
UPlay Game Library Sync Issues After Upgrading to Ubisoft Connect

### ISSUE THREAD

**Issue by shangles** [JosefNemec/Playnite#2080]
**Check for existing issue**
Search for this issue provided no results

**Describe the bug**
I launched UPlay today (Windows 10 Pro 64-bit) and it upgraded to the new Ubisoft Connect platform.  Since upgrading the platform, performing an Update Game Library in Playnite fails with the error "Failed to import games from Uplay.  Uplay client was not initialized, please start the client at least once."

**To Reproduce**
Upgrade UPlay to Ubisoft Connect.  Update UPlay Game Library.

**Screenshots**

**Diagnostics ID**
42d308d3-60a9-41f5-a273-3736b8e93d1b

**Comment by JerwinModavi** [comment]
I'm having the same issue.

**Comment by darklinkpower** [comment]
Posted on the Discord earlier today
![imagen](https://user-images.githubusercontent.com/1389286/97397536-170cf280-18af-11eb-9955-261266651528.png)

**Comment by JosefNemec** [comment]
Done in 8.5
