### ISSUE TITLE
Extension "Library Exporter" failed to load properly

### ISSUE THREAD

**Issue by yarda** [JosefNemec/Playnite#2085]
I am running Playnite under Wine in Linux. It has been working flawlessly. Recently, the following error message started to appear under the "bell" icon: 'Extension "Library Exporter" failed to load properly.'. If I dismiss it, it re-appears upon next start of Playnite. It seems it doesn't affect the basic functionality of Playnite. This message started to appear one or two releases back IIRC (maybe more, but definitely not before the 8.x release). Currently, I am running Playnite 8.5. Is there any specific framework or DLL the "Library Exporter" requires? I guess it could be caused by some missing DLL in my Wine environment.

**Comment by darklinkpower** [comment]
https://github.com/JosefNemec/Playnite/wiki/Installing-scripts-and-plugins#if-you-are-windows-7-or-8-user-then-you-need-to-install-powershell-51-for-powershell-extensions-to-work

If you are Windows 7 or 8 user, then you need to install [PowerShell 5.1](https://www.microsoft.com/en-us/download/details.aspx?id=54616) for PowerShell extensions to work.

**Comment by JosefNemec** [comment]
As darklinkpower mentioned, 5.1 PS is required. Also, running Playnite under Wine is not supported. Please do not open issues that are not also reproducible on Windows, thank you.

**Comment by 0rkaM** [comment]
> https://github.com/JosefNemec/Playnite/wiki/Installing-scripts-and-plugins#if-you-are-windows-7-or-8-user-then-you-need-to-install-powershell-51-for-powershell-extensions-to-work
> 
> If you are Windows 7 or 8 user, then you need to install [PowerShell 5.1](https://www.microsoft.com/en-us/downloaddetails.aspx?id=54616) for PowerShell extensions to work.
> 
> Check if you need that too in your Wine enviroment.

OK... and How?
Can you contribute with either one of the following:

- another link, like a download link of PowerShell 5.1 install file for Windows 7 (or 8);
, or
- with (another link to) steps on how to obtain and install PowerShell 5;

Thanks.

P.S.: the [PowerShell 5.1](https://www.microsoft.com/en-us/downloaddetails.aspx?id=54616) you gave goes to a basically null-page.

**Comment by yarda** [comment]
FTR (maybe it can help others):
https://bugs.winehq.org/show_bug.cgi?id=40427

Just with the PowerShell 7.1.4 from the link bellow it doesn't work:
https://github.com/PowerShell/PowerShell/releases/

But it's minor problem, the plugin can be disabled in the menu and I don't need it. Other than that Playnite runs perfectly under wine.

I am going to open winedb record for the Playnite.

**Comment by JosefNemec** [comment]
As linked wiki page says, you need PowerShell 5.1, not 6 or 7.

**Comment by shakeyourbunny** [comment]
See also https://bugs.winehq.org/show_bug.cgi?id=40427#c9

**Comment by yarda** [comment]
FYI: wine appdb record:
https://appdb.winehq.org/objectManager.php?sClass=version&iId=40197

**Comment by JosefNemec** [comment]
Please use forums/reddit if you want to discuss unofficial ways of running Playnite on Linux. Use this repository only for talk related to officially supported platforms.
