### ISSUE TITLE
Searching metas on IGDB find different titles than website

### ISSUE THREAD

**Issue by lapo-luchini** [JosefNemec/Playnite#2086]
I bought Control on Epic, it shows up with wrong metadata (from an older game with the same title, I think).
No problem with that, I say: let's download metadata from IGDB; unfortunately, it doesn't show up.

**To Reproduce**
[Download Metadata…]

**Screenshots**
![image](https://user-images.githubusercontent.com/420454/97638029-06d64e00-1a3c-11eb-96cf-8dddef2c7b7e.png)
the game is not the first in the list, it's not even in the complete list

on the other hand, by [searching it on IGDB](https://www.igdb.com/search?type=1&q=control), I get these results:

- Control (2019)
- Star Control: Origins (2018)
- SUPERHOT: MIND CONTROL DELETE (2020)
- Chaos Control (2018)
- Ground Control II: Operation Exodus (2004)
- Duplicate Star Control II (1994)
- Baja: Edge of Control (2008)
- Balls Control
- Chaos Control (1995)
- (and others)

**Comment by JosefNemec** [comment]
The IGDB issue is caused by long standing issue on IGDB's side, the API search is simply broken, I can't fix that. I'll look into the Epic issue though.

**Comment by lapo-luchini** [comment]
Oh, I see.

BTW: if I do [Download Metadata…] → [Official store] I get this:
![image](https://user-images.githubusercontent.com/420454/97676609-2e0b3a80-1a91-11eb-98a2-88ddbc754f6a.png)

(originally all metadata auto-imported was that, including background image with a couple of flying dragons as far as I can remember)

**Comment by JosefNemec** [comment]
The Epic issue is now fixed in 8.6 update. I've also made some changed to IGDB integration and manual search should not return more results.

**Comment by lapo-luchini** [comment]
It works now great, in both Epic store (got all new links) and IGDB (the correct game shows up in position 4). 🎉
