### ISSUE TITLE
Fullscreen not loading and installation problem

### ISSUE THREAD

**Issue by Jon-PD** [JosefNemec/Playnite#2087]
Hey, I just updated to Playnite 8.5, and encountered a problem where it wouldn't let me boot to fullscreen using the PlayniteFullscreen.exe from the desktop - apparently the shortcut no longer existed.

I then tried to boot to fullscreen from within the desktop app, and Playnite simply shut down.  Then tried a reinstall, but it bumped on two specific files - CefSharp.BrowserSubProcess.exe and Playnite.FullscreenApp.exe - and threw up the error message "An error occurred while trying to replace the existing file: DeleteFile failed; code 5. Access is denied."

I love playnite and am happy to use it in desktop moment for now, but mostly use it fullscreen mode with a controller - let me know if I can share any extra information to help.

Thanks very much and keep up the great work!
Jon

**Comment by JosefNemec** [comment]
If you are using some AV software then make sure it's not blocking those files from being installed. Nothing I can do if the install fails to write files because of access issues. Or try different install location.

**Comment by Jon-PD** [comment]
Thanks so much! Adding an exception to the playnite folder in Avast solved it immediately. Not sure why it was blocked in the first place but good to know.
