### ISSUE TITLE
Program crashed after I searched for Borderlands

### ISSUE THREAD

**Issue by AdmiralMemo** [JosefNemec/Playnite#2089]
**Describe the bug**
Program crashed after I searched for Borderlands

**To Reproduce**
Search for Borderlands

**Diagnostics ID**
 e2a95d95-fbfb-4b34-bfbf-6de22ec28227

**Comment by JosefNemec** [comment]
I don't see any crash related to search in logs, only one that happened during application shutdown. Can you reproduce this on demand multiple times?

**Comment by AdmiralMemo** [comment]
No, it hasn't happened since I rebooted my PC. This was the first time the program crashed on me, so I just followed the instructions on the screen. I guess you can close this?
