### ISSUE TITLE
Launch fullscreen Playnite when desktop is running

### ISSUE THREAD

**Issue by jamie9090** [JosefNemec/Playnite#2091]
I would love to be able to launch a fullscreen version of Playnite even when desktop is running.

Basically, I like to have Playnite on all the time via desktop and in the tray. But when I switch to controller, I need to close it to get to full screen mode.

I would love to be able to just open a fullscreen shortcut to activate Playnite fullscreen.

**Comment by JosefNemec** [comment]
Use `--startfullscreen` argument when launching Fullscreen mode, it will close running instance of Desktop mode.

https://playnite.link/docs/manual/cmdlineArguments.html
