### ISSUE TITLE
Playnite preventing shutdown or reboot when Bandicam is running

### ISSUE THREAD

**Issue by KevinSauer** [JosefNemec/Playnite#2092]
After installing popular screen recorder Bandicam Playnite started preventing shutdown and reboot with the following error message:

> Playnite.DesktopApp.exe
> The instruction at _somememoryaddress_ referenced memory at _someothermemoryaddress_. The memory could not be written.

[Photo of this error message during reboot.](https://i.imgur.com/Zwj2O2U.jpg)

I have tried rebooting with and without Bandicam running several times. This error is only happening when Bandicam is running and the Playnite Window is open when rebooting.

[playnite.log](https://github.com/JosefNemec/Playnite/files/5470148/playnite.log)

**To Reproduce**

1. Install and start Bandicam
2. Open Playnite window
3. Reboot

**Diagnostics ID**
763daa8d-c5ce-4a3d-92e9-55ddc66c63ce

**Comment by KevinSauer** [comment]
I don't see a public Bandicam bug tracker. I've sent them an email with a bug description and a link to this issue.

**Comment by KevinSauer** [comment]
The issue disappears when the "Disable hardware acceleration" option is checked in Playnite's settings.

**Comment by KevinSauer** [comment]
> then this means that Bandicam is hooking into Playnite process (probably thinking that it's a game because it's a DX9 process)

Its FPS counter is present in Playnite as well.

> Nothing I can do about it.

Yeah, fair enough. Expected this as it smelled more like a Bandicam issue. Just wanted it on record.

**Comment by JosefNemec** [comment]
If disabling HW acceleration fixes the issue, then this means that Bandicam is hooking into Playnite process (probably thinking that it's a game because it's a DX9 process) and messing things up. Similar issue is caused by RivaTuner and its derivatives. Nothing I can do about it.
