### ISSUE TITLE
Show Title only when a game is selected

### ISSUE THREAD

**Issue by Rioluuu** [JosefNemec/Playnite#2094]
Add an option for fullscreen mode, that allows to only show the title of the currently selected game. Currently it is only possible to show the titles of all games.

Here's how I want it to look like:
![Unbenannt-1](https://user-images.githubusercontent.com/43097559/97810811-d0384780-1c76-11eb-9f6d-31776afc8a68.png)

**Comment by JosefNemec** [comment]
This can be done already via custom theme, if you don't want to wait for potential built-in support.
