### ISSUE TITLE
Feature Request: Screenshot Support

### ISSUE THREAD

**Issue by Devilion** [JosefNemec/Playnite#2095]
Hello. I was wondering if you could consider adding an option for screenshots? It'd be nice to be able to view some images of the games through Playnite, as the way I've been doing it messes with the title of the game. I've been basically just making really long images to compensate for the lack of such a feature. Thank you. 💜 

![screenshotex](https://user-images.githubusercontent.com/13909459/97956777-2a1c3880-1d6f-11eb-8676-6175af2bc153.png)

**Comment by JosefNemec** [comment]
#1453
