### ISSUE TITLE
Crash due to dialog result being set multiple times

### ISSUE THREAD

**Issue by GodSponge** [JosefNemec/Playnite#2096]
**Check for existing issue**
There was no error code for me to look for. It just gave me an unrecoverable error.

**Describe the bug**
I started my computer and Playnite showed a dialog that said there was an unrecoverable error. When I clicked on the restart Playnite, everything started fine as far as I can tell. 

**To Reproduce**
Since it started correctly now, I don't know if its reproducible. Just dropping this in since the app asked me to.

**Screenshots**
I didn't think to take a screenshot of the error, but it was very short. Something to the effect of: An unrecoverable error has occurred.

**Diagnostics ID**
cb1d409b-a5a9-41fa-b388-1fbb49ab90da

**Comment by JosefNemec** [comment]
This shows up in crash reports once in a while and I have no idea why it happens, it makes no sense to me. I'll just probably suppress the crash and hope that Playnite can keep working just fine.

**Comment by JosefNemec** [comment]
Done in devel9.
