### ISSUE TITLE
Ubisoft Connect issues

### ISSUE THREAD

**Issue by alien2003** [JosefNemec/Playnite#2097]
Some games are duplicated and some games are not detected (Watch Dogs Legion)

![image](https://user-images.githubusercontent.com/11610652/98137530-c3139680-1eca-11eb-93dd-906a88a58439.png)

f7010e15-f00c-47c5-bf19-cd2bb6f20b3a

**Comment by JosefNemec** [comment]
Duplicated games: Usually betas or other version, you need to manually remove them. There's no reliable way how to automatically remove those.
Not detected games: See this link: https://github.com/JosefNemec/Playnite/wiki/Uplay-troubleshooting

**Comment by alien2003** [comment]
@JosefNemec I fixed by complete reinstalling Playnite without preserving any data
