### ISSUE TITLE
Sorting by last activity

### ISSUE THREAD

**Issue by Bobbite** [JosefNemec/Playnite#210]
Hello,
I installed Playnite a few days ago and it's great but  I grouped the games by providers and sorted them by last activity (so that the last game I played should appear at the top of the list?) but it doesn't seem to work

**Comment by JosefNemec** [comment]
Are you sure you have Ascending/Descending order set correctly?

**Comment by Bobbite** [comment]
Oops I didn't notice that, sorry! Fixed!
