### ISSUE TITLE
Problem with maximized window while taskbar is in auto-hide mode

### ISSUE THREAD

**Issue by SatoHarn** [JosefNemec/Playnite#2100]
Taskbar completely disappears and becomes inaccessible while Playnite is maximized if taskbar is in auto-hide mode. Which isn't something intended probably, because taskbar becomes accessible with maximized window if auto-hide option is disabled. Normally taskbar should come out when mouse cursor touches to the bottom of the screen.

**Comment by JosefNemec** [comment]
Please use search next time #1106
