### ISSUE TITLE
Zoom slider Control in Grid View can't be changed

### ISSUE THREAD

**Issue by darklinkpower** [JosefNemec/Playnite#2101]
**Describe the bug**
Zoom slider Control in Grid View can't be changed. Changing the `width` only changes the position and not the width of the control.

**To Reproduce**
Change `width` of Zoom slider Control

**Screenshots**
![EGv580LMKY](https://user-images.githubusercontent.com/1389286/98340511-16710c00-1fd3-11eb-93a8-fad9017c9b2d.gif)

**Comment by JosefNemec** [comment]
Fixed in 8.7
