### ISSUE TITLE
Battle.net library imports games I don't own

### ISSUE THREAD

**Issue by imaspeer** [JosefNemec/Playnite#2104]
**Describe the bug**
On a fresh install, I connected my battle.net account and checked to import both installed and uninstalled games. In addition to properly importing my games, it also imported warcraft III and black ops 4, which I don't own.

**Diagnostics ID**
accd9ad2-e578-4237-af3b-dfa0c483b440

**Comment by JosefNemec** [comment]
Do you see those games [here](https://account.blizzard.com/games)? If so, then they are being imported properly.

**Comment by imaspeer** [comment]
Warcraft III was actually the legacy version (which I do own), and I do see black ops 4 on the page you linked. Guess the bug is on battle.net's side.
