### ISSUE TITLE
Uninstalling game from context menu causes Playnite to not recognize Steam.

### ISSUE THREAD

**Issue by xyifer12** [JosefNemec/Playnite#2105]
Uninstalling any PC game, regardless of which launcher it uses, causes Playnite to not recognize Steam. Manually opening Steam, then restarting Playnite, then closing Steam fixes the issue.

![sfsf](https://user-images.githubusercontent.com/33806276/98468003-2426bd00-219e-11eb-8771-a0d4cd883b0a.png)

**Comment by JosefNemec** [comment]
Pleas provide all requested information you were told in the issue template.

**Comment by xyifer12** [comment]
The only information I forgot was the diagnostic package submission. It is 2d50ee95-6fde-49a3-9f28-fa302fd1a65b.

**Comment by JosefNemec** [comment]
The log is full of messages from SuccessStory extension, making it useless to me. Please disable that extension, replicate the issue and then generate new diag. package, thanks.

**Comment by JosefNemec** [comment]
No response, closing.
