### ISSUE TITLE
Add String Formatting support to ThemeFile

### ISSUE THREAD

**Issue by joyrider3774** [JosefNemec/Playnite#2108]
**Check for existing issue**
none

**Describe the solution you'd like**
Add string formatting support to ThemeFile, so theme file locations can by variable / dynamic based on variables for example from Game objet.

Currently i use Source of image object in xaml and you have to use a datatrigger or some textblock workaround to be able to do string formatting on some other element and then assign to source so it can load variable files.

Other themes have just hardcoded conditions and you would need to add a condition for every possible value which is kinda counter productive.

Example of how i do it now, it would be a lot easier if we can just use ThemeFile with stringformatting
```
<TextBlock Name="ImagePath" Visibility="Collapsed">
	<TextBlock.Text>
		<MultiBinding StringFormat="{}{0}{1}{2}">
			<Binding Source="..\images\sources\" />
			<Binding Path="Game.Source"/>
			<Binding Source=".png"/>
		</MultiBinding>
	</TextBlock.Text>
</TextBlock>

<Image Height="75" Visibility="Visible" RenderOptions.BitmapScalingMode="Fant" StretchDirection="Both" Stretch="Fill"
	VerticalAlignment="Top" HorizontalAlignment="Stretch" Source="{Binding ElementName=ImagePath, Path=Text}" />
```

**Screenshots**
If applicable, add screenshots to help explain requested changes.

**Comment by JosefNemec** [comment]
Done in devel9. There's now new `ThemeFileBinding` markup extension.

```xml 
<Image Source="{ThemeFileBinding Game.Platform.Name, PathFormat='Platforms/{0}.jpg'}" />
```
