### ISSUE TITLE
Fullscreen zoom functionality

### ISSUE THREAD

**Issue by DoganM95** [JosefNemec/Playnite#2111]
**Describe the solution you'd like**

Would be great to have zoom in/out functionality in fullscreen-mode (also using controller).
One zoom slider for general UI (including text) and one zoom slider for game cover sizes.

**Comment by JosefNemec** [comment]
You can already adjust that in settings by choosing how many items should be displayed in a row/column. More granular zoom like in Desktop is not possible.
