### ISSUE TITLE
Library does not update on filename changes

### ISSUE THREAD

**Issue by DoganM95** [JosefNemec/Playnite#2112]
**Describe the bug**
Changing the filename of an already added game does not update in game libary. library shows old name, even when updating manually (F5).

**To Reproduce**
Create a file, e..g. `tekken 5 test.iso` and add it to the game library.
Then rename the local file to `tekken5.iso ` and check, if the game-name in the library changed.

The game will still be shown as `tekken 5 test` and starting that game gives an error about the game not being found.

**Comment by JosefNemec** [comment]
"Update library" only updates games which are imported via library plugin. What you are asking for is not possible because we would have to track file system changes (to detect that iso was renamed), which is virtually impossible to make reliable.

**Comment by DoganM95** [comment]
Have you tried using e.g. hashes?
You could create a hash for each imported file and store the games configuration in a file named `<fileHash>.yaml`, so even on a filename change, the settings would persist.
And to detect if a game name was changed, you could use simple polling, which is not really cpu demanding, if you do it e.g. every 10 seconds, or each time, F5 is pressed.

i don't know your current code base and if it would need a lot of changes in other parts of the application, just trying to give an idea.

**Comment by JosefNemec** [comment]
This is simply not practical to implement, especially considering that users don't generally rename game ROMs. I just don't see a value in adding this considering the effort needed to implement it in some reliable way.
