### ISSUE TITLE
Auto-Check already installed games in Importer

### ISSUE THREAD

**Issue by DoganM95** [JosefNemec/Playnite#2114]
**Describe the bug**
`Add Game -> Scan Automatically -> Scan Folder` works great, but it does not automatically check the executables already added to the game library. 

This leads to:
- Duplicate games in the library (exact same path and executable for two games)
- Confusion, as of which games were already added to the library previously

**To Reproduce**
`Add Game -> Scan Automatically -> Scan Folder` and add a game executable.
Repeat the process again. Each repetition causes a duplicate in the game library. 

**Screenshots**
after `Add Game -> Scan Automatically -> Scan Folder` the box is initially not checked:
![Capture](https://user-images.githubusercontent.com/38842553/99087028-934f4780-25ca-11eb-93a4-49fbbe4773f4.PNG)

Checking it by not knowing it is already in the library and clicking add games leads to another duplicate:
![Capture2](https://user-images.githubusercontent.com/38842553/99087208-ca255d80-25ca-11eb-8cdd-456bed7f7a98.PNG)

**Comment by JosefNemec** [comment]
#1050

**Comment by DoganM95** [comment]
Wasn't sure, if he meant the exact same thing. thanks :)
