### ISSUE TITLE
Can't add a LNK shortcut as an executable, neither use its target (a Google Chrome profile)

### ISSUE THREAD

**Issue by Romarain** [JosefNemec/Playnite#2115]
This doesn't work : 

![2020-11-14_16h54m46s_Playnite DesktopApp](https://user-images.githubusercontent.com/22033256/99151259-21463380-269a-11eb-828a-d6a7c8debbd4.jpg)

and adding the target of the link neither : 

![2020-11-14_16h32m01s_Playnite DesktopApp](https://user-images.githubusercontent.com/22033256/99151239-f956d000-2699-11eb-9aed-e31ab0792ab6.jpg)

This target is a Chrome app, meaning the opening of a URL in a dedicated window ("Create a shortcut" and "open in a new window" in Chrome's menu).

**Comment by JosefNemec** [comment]
To import lnk files: drag and drop lnk into Playnite's window.
As far as Chrome issue: remove quotes from those paths.
