### ISSUE TITLE
Support for individual theme styling of filter and other controls

### ISSUE THREAD

**Issue by darklinkpower** [JosefNemec/Playnite#2118]
**Describe the solution you'd like**
Currently certain controls inherit the style of the normal controls, which makes it difficult to style them and compromises have to be made.

Ideally they should have an style that can be edited individually.

**Screenshots**
1. Filters in Panel filter: Library, Release Year, Tags, etc.
![imagen](https://user-images.githubusercontent.com/1389286/99187521-b7bb3900-271c-11eb-9fcb-6fb40fde6f33.png)

2. Search textbox in MainPanel
![imagen](https://user-images.githubusercontent.com/1389286/99187533-c9044580-271c-11eb-8d0d-8e8ecf41848c.png)

3. Genres, Developers, Publishers, Categories, Features and Tags fields in the game edit window
![imagen](https://user-images.githubusercontent.com/1389286/99187550-e3d6ba00-271c-11eb-8cb0-19dc22f3a9d3.png)

**Comment by JosefNemec** [comment]
Done in devel9.

**Comment by darklinkpower** [comment]
Thanks a lot for this! (And everything else too of course)
