### ISSUE TITLE
SDK - Have the same AvailableFields system for Library Plugins that Metadata Plugins

### ISSUE THREAD

**Issue by Lacro59** [JosefNemec/Playnite#2120]
When a user update metadata (with CTRL+D for example), the selectable fields don't work when the provider is a Library Plugin.
By consequent, all fields is got with the plugin.

Is it possible to have the AvailableFields system in Library Plugins?

**Comment by JosefNemec** [comment]
I don't understand. Metadata from library plugin is always under "Official Store" option, which is always available for all fields.

**Comment by Lacro59** [comment]
When you use the Metadata Import, you can select the fields to import.
![image](https://user-images.githubusercontent.com/124054/99230094-2bc61180-27ef-11eb-8977-e65046b4451e.png)

This option don't work with a Library Plugin because, from what I understood, the selection use AvailableFields property, only usable for Metadata Plugin.

**Comment by JosefNemec** [comment]
"Official Store" option is the option for library plugin. It doesn't make sense to show every single library plugin as a source there (with an option to specify supported fields) because they only provide metadata for a specific library. You can't use them for games from other libraries.

**Comment by JosefNemec** [comment]
Closing based on my previous comment since there was no response.
