### ISSUE TITLE
Playnite fullscreen can send 2 gameselected events when going from "most played" to "Favorites" list in fullscreen app

### ISSUE THREAD

**Issue by joyrider3774** [JosefNemec/Playnite#2125]
**Check for existing issue**
none

**Describe the bug**
when going from "most played" to "Favorites" list in fullscreen app playnite is sending gameselected event twice, once either before filtering the list or sorting it (could not determine which is the case) and once after it has stopped sorting / fitering the list. The 2nd gameselected event is triggerd by the 1st entry in the list either being removed or be not the 1st item anymore in the list after sorting or filtering

It should only send a gameselected event once, after it has finished building the complete list and not while building the list and things happening during it

**To Reproduce**
create a prowershell extension and add a showmessage inside the gameselected like so :

```
function global:OnGameSelected()
{
	param(
		$arguments
	)
	if ($arguments.NewValue.Count -eq 1)
	{
		$PlayniteApi.Dialogs.ShowMessage("GameSelected:" + $arguments.NewValue[0].Name)
	}
}
```

make sure you have some favorited games, but not all of them only a couple. Start fullscreen app, on each game selected event it will show the name of the game. Goto most played tab, then goto favorites it will show 1st time a game and send game selected event, but then that 1st game is either removed or repositioned due to sorting or filtering and it send a second gameselected event for another game becomming the 1st one

**Screenshots**
see video here https://youtu.be/rVMtgXmisqo

**Diagnostics ID**
none

**Comment by JosefNemec** [comment]
Fixed in 8.9
