### ISSUE TITLE
Playnite display issues Chrome RDP/Unified

### ISSUE THREAD

**Issue by Bboy486** [JosefNemec/Playnite#2127]
**Check for existing issue**

**Describe the bug**
When launching playnite from a tablet or phone remotely (lan) playnite does not display. It is minimized and I cannot maximize or display.

**To Reproduce**
Use Chrome RDP or Unified on Android to remote to the computer with playnite and launch playnite.

**Screenshots**
Video
https://drive.google.com/file/d/11wmagHN4OA-RHn3f8U38ZY6yND7cn_uT/view?usp=drivesdk

**Comment by JosefNemec** [comment]
There's nothing I can do in terms of how the app works via RDP. You can try disabling hardware acceleration in the settings, to see if it helps, but that's about it.
