### ISSUE TITLE
Presence not working for Call of Duty: Black Ops Cold War

### ISSUE THREAD

**Issue by webtroter** [JosefNemec/Playnite#2128]
**Describe the bug**
I was playing Call of Duty: Black Ops Cold War, and the game isn't detected normally by discord to do the presence thing.

When I launched it via PlayNite, I had only "Playing Playnite" as my presence in Discord. I was expecting "Playing Call of Duty: Black Ops Cold War"

My other games works, but I'm not sure if its via the normal discord game detection or playnite.

**To Reproduce**
I think it is clear that you need to run Call of Duty: Black Ops Cold War via Playnite and see if the presence shows the game or only playnite. 

**Diagnostics ID**
44a41671-72cc-4a4e-95dd-c2eb6bad02db

**Comment by JosefNemec** [comment]
This is sadly limitation of Discord's API, nothing I can do about it.

**Comment by webtroter** [comment]
I'm sorry, but I must ask for more details.

What is the limitation?

**Comment by webtroter** [comment]
Well, I just looked harder and it's now obvious.

The presence show the program presence and the game is in the details.

I found the [code](https://github.com/JosefNemec/Playnite/blob/7dbe373ecfc4168eb69e4bb61466b58c65066b48/source/Playnite/DiscordManager.cs#L75) and it makes sense.
