### ISSUE TITLE
Add xenia to compatible emulators

### ISSUE THREAD

**Issue by greggameplayer** [JosefNemec/Playnite#2130]
**Check for existing issue**
Currently it's impossible to add Xbox 360 Games via the xenia emulator or whatever emulator because there isn't an Xbox 360 category.

**Describe the solution you'd like**
Add an Xbox 360 category and support the xenia emulator.

**Comment by JosefNemec** [comment]
Xenia has only `Default` profile because the emulator only supports one platform, and that profile has 360 properly set as supported platform.

https://github.com/JosefNemec/Playnite/blob/master/source/Playnite/Emulators/Xenia.yaml

**Comment by greggameplayer** [comment]
@JosefNemec Oh so it doesn't detect the canary version of xenia
