### ISSUE TITLE
Suggestion: Add separators to Actions

### ISSUE THREAD

**Issue by chocolatechipcats** [JosefNemec/Playnite#2133]
It would be helpful sometimes to add a separator/divider line between actions. 

Thank you.

**Comment by darklinkpower** [comment]
Just for info and after giving it thought I think it's this:

![imagen](https://user-images.githubusercontent.com/1389286/99925362-8259b100-2d03-11eb-8d28-f4d58cf6a96b.png)

Personally I don't agree with the change since separators are meant to separate sections, not sub items.

**Comment by JosefNemec** [comment]
I don't agree with this either. Separators are usually used to separate sections, not items in a section. I also don't think that it's a standard to have more then just a couple of actions, in which case it seems pointless to me to have them separated.

**Comment by JosefNemec** [comment]
Closing, this is imho not the way separator in the menu should be used.
