### ISSUE TITLE
Humble Bundle library not importing

### ISSUE THREAD

**Issue by AIRyndon** [JosefNemec/Playnite#2137]
**Describe the bug**
Using Playnite 8.8 - Importing the humble bundle library returns this error
![image](https://user-images.githubusercontent.com/8405286/100151622-46db0480-2f06-11eb-9758-11ee966b5cf1.png)

The user account is authenticated
![image](https://user-images.githubusercontent.com/8405286/100151716-6b36e100-2f06-11eb-89c6-24fcdd31ae53.png)

**Diagnostics ID**
Diag ID is - 59c6a851-2f05-4af0-9ccc-00ecd91b00a4

Thanks in advance!

**Comment by JosefNemec** [comment]
Can you please try it with [this version](https://github.com/JosefNemec/Playnite/files/5603284/HumbleDebug.zip) of Humble plugin? You need to replace those files in `%localappdata%\playnite\extensions\HumbleLibrary\` directory.

**Comment by AIRyndon** [comment]
Hello Josef

I have overwritten the two files in HumbleLibrary folder inside playnite's installation directory, it is installed on a different location (I'm guessing that shouldn't matter though). Still got the same error sadly. I disabled and reenabled the extension too.

I was trying to look for the place where the login credentials are saved - I'm thinking of logging in again just in case. Where is that btw? 😄 

Anyways, here is a diag thingy
973fd4cd-04ae-495c-bcb8-8fd5b3e4e920

Thanks again!

**Comment by JosefNemec** [comment]
Please reproduce it again with [this build](https://github.com/JosefNemec/Playnite/files/5607114/HumbleDebug2.zip) and generate new diag. package. It's still going to fail, but I added more information to logs. Thanks

**Comment by AIRyndon** [comment]
Hello Josef
Here is a new diag - 772e8cd6-415d-4f8a-bae5-a70518ebda27

The version you gave worked - I forgot if the VPN was running when it was failing, now that it was able to import the Trove games, the VPN is OFF.
I tried importing again with the VPN ON and it still works (I'm not sure if the games already existing there changes things - like does it still try to talk with Humble bundle when it sees the games there or not)

Anyways, thank you again. I hope the logs on your new DLL gives you more insight.
