### ISSUE TITLE
Rockstar Launcher support

### ISSUE THREAD

**Issue by D1Ck3n** [JosefNemec/Playnite#2138]
Hey!

To play RDR2 I unfortunately have to use the annoying Rockstar Game Launcher. It can't be started in the tray and always appears at every game start. A Rockstar Launcher support would be great! And if it's just a way to minimize the launcher automatically and start Playnite in fullscreen again. When I quit the game the launcher unfortunately blocks Playnite.

**Comment by JosefNemec** [comment]
https://github.com/JosefNemec/PlaynitePlugin-RockstarLibrary
