### ISSUE TITLE
CefSharp.BrowserSubprocess requesting firewall rule

### ISSUE THREAD

**Issue by kccricket** [JosefNemec/Playnite#2139]
**Describe the bug**
After Playnite upgrade from v8.7 to v8.8, the CefSharp.BrowserSubprocess executable is requesting inbound access to any TCP and UDP port.

This Stackoverflow post suggests this may be because it wants to do mDNS discovery on the network. I suspect that is not required for Playnite. https://stackoverflow.com/a/63887797/1460906

**Comment by JosefNemec** [comment]
I'm not sure how 8.7 -> 8.8 update could trigger this since CefSharp was not updated in that update, but I'll look into it.

**Comment by JosefNemec** [comment]
I've done some research and the only reliable way how to handle this would be creating FW rule. The problem with that is that it would require elevated rights, which would mean requiring elevated right for the whole installation process (and you would still get that prompt when using portable version). I don't think that's worth it.
