### ISSUE TITLE
Add MobyGames Database for Game Info Scraping

### ISSUE THREAD

**Issue by ohnozen** [JosefNemec/Playnite#214]
Adding [MobyGames](https://www.mobygames.com/) for info scraping might benefit people adding ROMs. I found some boxart for Genesis/MD games the other two databases didn't have.

**Comment by JosefNemec** [comment]
MobyGames do provide official API access, but they have very unrealistic limits for apps like Playnite. We would probably need to force people to get their own API key instead of using shared (and cached) access like for IGDB.

**Comment by JosefNemec** [comment]
Support for custom metadata providers was added in Playnite 6. You should be able to create custom plugin for this now, without any addition support from Playnite required.

**Comment by JosefNemec** [comment]
Closing based on my previous comment, can be done as a 3rd party extension. I can't reasonably provide built-in support for IGDB and MobyGames, I don't have resources for that.
