### ISSUE TITLE
Library Manager: Renaming entry to existing one should merge them

### ISSUE THREAD

**Issue by chocolatechipcats** [JosefNemec/Playnite#2141]
Currently, there's no clear way to easily merge similar entries of tags/genres/companies/etc in the Library Manager, aside from bulk-editing all the games and then deleting the unwanted entries. A bit of a mess with certain genres that have a zillion variations (RPG? Roleplaying Game? Role-Playing Game (RPG)?)

At the moment, trying to rename an entry to one that already exists just makes an error. Instead, I suggest that it merge the two entries together. Perhaps a dedicated Merge button would also be useful. 

Thank you.

**Comment by JosefNemec** [comment]
#1270
