### ISSUE TITLE
Suggestion: Support URLs for "Open Manual" field

### ISSUE THREAD

**Issue by chocolatechipcats** [JosefNemec/Playnite#2142]
There's two reasons for this:

1. Online manuals. Sadly common for the newer games. 
2. My personal reason: I keep all my PDF manuals in a Calibre library. I prefer to use calibre:// urls instead of linking directly to the files. I just add them as a custom URL action, but it'd be nice to be able to use the built-in feature for this.

Thank you.

**Comment by JosefNemec** [comment]
This is already supported.

**Comment by chocolatechipcats** [comment]
When I put in a calibre:// URL, I got this error:

"Failed to open manual: The given path's format is not supported." 😞

**Comment by JosefNemec** [comment]
I see, I checked and we check for http URIs only. I'll fix that.

**Comment by chocolatechipcats** [comment]
Thank you! 😸

**Comment by JosefNemec** [comment]
Fixed in 8.9
