### ISSUE TITLE
Missing game icons for Epic Store games

### ISSUE THREAD

**Issue by vladeck** [JosefNemec/Playnite#2143]
**Describe the bug**
Game icons are missing for all Epic Store games in either Details or List view.

**To Reproduce**
- Enable Epic Store Library Importer
- Check "Connect account", "Import not installed games"
- Authenticate and let Playnite sync everything
- Games are listed, but without icons (Backgrounds and Covers are present)

**Screenshots**
<img width="960" alt="Screenshot 2020-11-29 004553" src="https://user-images.githubusercontent.com/16443718/100528369-627f2d00-31dc-11eb-87b1-44d052bebb98.png">

**Comment by darklinkpower** [comment]
Icons only get added for games that are installed on your pc when updating your Epic library.

As an alternative, you can use this metadata plugin to get the icons from Steam: https://github.com/JosefNemec/PlaynitePlugin-SteamStoreMetadata

**Comment by vladeck** [comment]
I fell like dumb dumb. I glimpsed over metadata support on the Wiki, but I haven't noticed that icons are pulled only if the game is installed.

@darklinkpower Thank you, will try the plugin you mentioned.
