### ISSUE TITLE
Suggestion: Syntax highlighting in description editor

### ISSUE THREAD

**Issue by chocolatechipcats** [JosefNemec/Playnite#2144]
I'm going to guess that a WYSIWYG editor is a bit out of scope (or at least a long-term thing),, but having some basic optional syntax highlighting without having to copy to a dedicated editor would make cleaning up those walls-of-code a lot easier. Also being able to change the font in just the description box to a fixed-width font. 

Thank you.

**Comment by JosefNemec** [comment]
Even syntax highlight is out of scope, description field was not designed for people to put complex html constructs there. Also, we are planning to [switch to Markdown](https://github.com/JosefNemec/Playnite/issues/397) which has way simpler syntax.
