### ISSUE TITLE
Built in themes not working

### ISSUE THREAD

**Issue by indig0F10w** [JosefNemec/Playnite#2146]
Hi,

Not a single built in theme works. It always starts with default look.

I tried changing theme by going to Settings > Extensions > Themes > Desktop. Then select for example Classic Green, click Save, right click on system tray icon and then Exit.

Start Playnite again, nothing changes. I tried every theme listed.

OS: Windows 10 x64

Thanks.

**Comment by JosefNemec** [comment]
Can't reproduce, please attach all information requested in issue template.
https://github.com/JosefNemec/Playnite/issues/new/choose

**Comment by JosefNemec** [comment]
Never mind, I just read your message properly. That's not how you change the theme. There's a drop down in `Appearance` section used for changing theme.
