### ISSUE TITLE
GameSelected event gets fired multiple times during deletion of multiple selected games

### ISSUE THREAD

**Issue by joyrider3774** [JosefNemec/Playnite#2147]
**Check for existing issue**
none

**Describe the bug**
When deleting multiple games a gameselected event is fired after every single delete of a game. I think it should not fire a gameselected event during deletion of the games except perhaps at the end to select a new game after deletion

**To Reproduce**
Create powershell extension with this simple ongameselected event
```
function global:OnGameSelected()
{
	param(
		$arguments
	)
	
	$PlayniteApi.Dialogs.ShowMessage("OnGameSelected Fired", "")
}
```
Do a multiselect of games and then right click and choose delete. It will fire a game selected event after each delete of a game and you can see this due to the added showmessage blocking the next delete

**Screenshots**
See video here https://youtu.be/hH3iMy0DGOw

**Diagnostics ID**
none

**Comment by JosefNemec** [comment]
Can't be fixed now because this behavior is a workaround for WPF bug, see #796. I will be able to do something with it after switch to .NET5/6.

**Comment by JosefNemec** [comment]
Fixed in devel.
