### ISSUE TITLE
Xbox games have stopped importing completely, even after reinstall

### ISSUE THREAD

**Issue by ninnyjams** [JosefNemec/Playnite#2150]
**Check for existing issue**
Not seeing anything.

**Describe the bug**
Playnite has completely stopped pulling in Xbox library PC games. It just doesn't grab them anymore, and the bulk of the games don't appear when I select Microsoft Store games, either. Previously imported games from this library appear, but on 11/19, Playnite stopped importing new ones. I just uninstalled the app completely using Revo Uninstaller and reinstalled, and it still won't pull in any new Xbox games. Other libraries (including Steam, Itch, Epic, Battle.net, and Bethesda.net) are importing fine.

I am logged in and authenticated.

**To Reproduce**
Should be pretty clear!

**Screenshots**
N/A

**Diagnostics ID**
edc41906-ba82-49a6-a84a-34bd22f2a83a

**Comment by JosefNemec** [comment]
Looks like some issue on your system:
```
Failed to get list of installed UWP apps.
System.Exception: Fast Cache data not found. (Exception from HRESULT: 0x80071130)
```

**Comment by ninnyjams** [comment]
Ugh ... thanks, I have no idea where to even begin trying to figure out what that means. Lovely.

**Comment by JosefNemec** [comment]
I would try repairing/resetting Windows Store.
