### ISSUE TITLE
Android wireless controller 1up gc3 not working on full screen mode

### ISSUE THREAD

**Issue by JBIRO** [JosefNemec/Playnite#2152]
Hi guys as u read in title i have 1up gc3 controller that work fine with every game but have no access to Playnite !

**Comment by darklinkpower** [comment]
Only xinput controllers are supported, check if your controller is using it. Otherwise, you need to wait for https://github.com/JosefNemec/Playnite/issues/684 or use an xinput emulator like x360ce

**Comment by JosefNemec** [comment]
Duplicate to #684
