### ISSUE TITLE
In Advanced/Notes, please enable text wrapping

### ISSUE THREAD

**Issue by sengtsan** [JosefNemec/Playnite#2154]
At the moment, when entering text into the notes section, there is now text wrapping in the box. It would be a good quality of life improvement to enable text wrapping. Screenshot of the relevant section attached. 

![Untitled](https://user-images.githubusercontent.com/63714826/101019582-19750300-3565-11eb-807c-792f25d1f628.jpg)

**Comment by JosefNemec** [comment]
Done in `devel9`.

**Comment by sengtsan** [comment]
Fantastic. Happy new year!

**Comment by sengtsan** [comment]
Hi,
The text wrapping has gone as of 8.13. Is it best to report as new issue?

**Comment by JosefNemec** [comment]
This was never implemented in Playnite 8. The issue was closed because it's fixed in Playnite 9's branch (devel9).

**Comment by sengtsan** [comment]
Apologies. All the best,
