### ISSUE TITLE
The Battle.net integration does not import (nor launch) Warcraft 3 Reforged correctly.

### ISSUE THREAD

**Issue by argaton** [JosefNemec/Playnite#2157]
The Battle.net integration imports classic Warcraft 3 and it's expansion instead of Reforged. It also doesn't launch at all if the play action is managed by the plugin. A few things to note are that both classic and Reforged have the same product ID and the client for the OG game and the remaster is one and the same (much like StarCraft Remastered).

**Comment by JosefNemec** [comment]
Forgot to close this, Reforged support was added some time ago.
