### ISSUE TITLE
Automatic ignoring of articles when sorting such as "The, a, an" etc..

### ISSUE THREAD

**Issue by amandotzip** [JosefNemec/Playnite#2159]
**Describe the solution you'd like** 
With  [issue 84](https://github.com/JosefNemec/Playnite/issues/84) you can manually solve this problem by changing the sorting name field, but to be able to automatically do this at scale on an entire library would be fantastic. It was already noted that Steam and other popular library systems do this automatically for "the" at least.

**For example**

```
Mario Bros 2
The Jackbox Party Pack 7
The Legend of Korra

```
**Should be sorted as**

```
The Jackbox Party Pack 7
The Legend of Korra
Mario Bros 2
```

By the way thank you so much for this software, especially @JosefNemec  for supporting it so much. It's grown incredibly the past few years.

**Comment by grnassar** [comment]
Strangely, it seems like #154 was supposed to address this and create a sorting name without The/A/An, but for some reason it doesn't seem to be working -- seemingly all my imported games starting with "The" are sorting under T.  If that issue did address this, that would mean this should be categorized as a bug, not an enhancement, correct?
That said, an addition to this that would be nice would be to ignore non-alphanumeric leading characters, as well as The/A/An.  (Examples are the game Observer, which imports as ">observer_", or System.Hack, which imports as ">//:System.Hack".  Rather than sorting under "O" or "S" respectively, they sort at the very top of the list.)

**Comment by JosefNemec** [comment]
#154 was only about adding an option to manually specify sorting name. Not about automatically ignoring articles.

**Comment by grnassar** [comment]
I think #84 was to manually specify a sorting name, like the OP stated, wasn't it?  And #154 was to automatically set it for initial articles.  Here is the link to the commit associated with 154:

[New: Automatically set sorting name without "The" at the start of titles](https://github.com/JosefNemec/Playnite/commit/4bb5a8a33b2133b2c10d6815e72d8e4a4e456666)

Perhaps I'm misunderstanding the commit?

**Comment by JosefNemec** [comment]
The old issue/commit is about automatically adding sorting name without articles. Not about ignoring articles even if sorting name is not specified, which is what this issue is about.

**Comment by grnassar** [comment]
I'll let the original poster speak to that, I suppose -- that's not how I am understanding the issue he presents when I read it; the way I'm understanding it the problem he cites would be just as well solved by automatically adding a sorting name without the articles.  I think the issue may be agnostic to whether it's done via the sorting name field or via some "transparent" functionality, and the important thing isn't sorting name/no sorting name but is instead *automated* sort without articles, by whichever method is best. @amandotzip , what do you think?

**Comment by amandotzip** [comment]
I see what you're saying @grnassar , my request was I believe your idea of "transparent" functionality, as in title would automatically ignore the "the" article when being sorted. As in, without requiring the declaration of an added Sorting Name. That said, a hacky solution could be to strip the "The" when found and to put that reduced title as the added Sorting Name.

**Comment by grnassar** [comment]
Yes, I think that solution is what #154 had in mind. It's closed, but the feature doesn't seem to be active at the moment.

**Comment by Jeshibu** [comment]
Sort of solved with the automated sorting name, for game names at least.

**Comment by JosefNemec** [comment]
Closing as we are now setting sorting names on import that ignore articles.
