### ISSUE TITLE
Grouping by "Last Activity"

### ISSUE THREAD

**Issue by Nirilia** [JosefNemec/Playnite#216]
Please let me do this sorting so the more recent I have played a game the higher in the  list it is and it's also sorted showing, today, yesterday, etc (like steam, Library -> Recent).

It would be awesome, love you! :D

**Comment by Nirilia** [comment]
It now seems to sort by recently played, but I still would like to request the tags, to see when I played it.

**Comment by JosefNemec** [comment]
I'm not sure I understand this issue. Do want for last activity dates to change to "Today", "Yesterday" etc., instead of displaying date?

**Comment by Nirilia** [comment]
I wish it would automatically make "labels" in the game list on the left
that shows Today, Yesterday, This week, Last week, Last Month etc..

Just like how it is on steam recent tab for your games😊

Love the program, I am never going back.

Den ons 18 okt. 2017 20:51Josef Nemec <notifications@github.com> skrev:

**Comment by unrealed** [comment]
I was going to make this request as well. That's about the only thing I would want from Playnite, so I second this, even if it was requested a long time ago.

**Comment by JosefNemec** [comment]
Done in 5.0
