### ISSUE TITLE
Itch.io plugin does not import all games

### ISSUE THREAD

**Issue by reggert32** [JosefNemec/Playnite#2160]
I just activated the Itch.io plugin and noticed that not all games have been imported. The regular games are all there, but sometime ago there was a bundle for sale called "Bundle for Racial Justice and Equality" ( https://itch.io/b/520/bundle-for-racial-justice-and-equality ). There are 1741 items in this bundle. The problem is on the itch.io website ( not the client ) that the regular games are in the library, just as in the client, but this bundle is on a seperate page which is also not available in the Itch.io client, so playnite does not include this seperate page for the bundle. Is there a possible solution for this ?

**Comment by JosefNemec** [comment]
You need to claim games from the bundle first, they are not part of your library until then.
