### ISSUE TITLE
Filling in the install path for a game with only a space causes Playnite to crash when you then click on a link

### ISSUE THREAD

**Issue by SlipperyJim** [JosefNemec/Playnite#2161]
As per title and Discord discussion, filling in the install path with only a space (or spaces) causes Playnite to crash when you then click on a link for that particular game. Maybe other characters do too?

It would be nice to be able to have nothing in that field at all as it seems to want to put {installdir} in there when it has had something in there before, which then messes up sorting by the installation path in list view. Other imported but never installed games have nothing in the path after all, so it is not a requirement to have something there by the looks of it.

**Comment by JosefNemec** [comment]
Fixed in 8.11
