### ISSUE TITLE
Launching games from the "Recently Played" tab in full screen triggers visual bugs

### ISSUE THREAD

**Issue by leftweet** [JosefNemec/Playnite#2162]
**Describe the bug**
(For clarity, I'm defining the "first screen" as the screen that shows the first x number of covers depending on how many columns/or rows the user has selected. So, for instance, if I have 5 columns selected in horizontal view, the first screen would be the 5 covers of the most recently played games).

As a quick note, the bugs below seem to be present with both user-created themes and the default theme.

When starting a game within full screen's "Recently Played" tab that's not on the first screen and then exiting the game and returning to the "Recently Played" tab, I have experienced these visual bugs when "horizontal scrolling" is checked:

- If launching from the game's details view: A blank space where the game's cover originally was. See attached image: 
![Playnite 12_7_2020 1_34_29 PM](https://user-images.githubusercontent.com/4649456/101415130-37f83880-389c-11eb-8a18-5a63eaca75cd.jpg) No item will be focused within the viewport and the cover to the right of the blank space will change when focused on (when not focused, this spot will show the cover that should occupy the blank spot; when focused, it will show the correct cover for the spot to the right of the blank spot). In some cases, attempting to scroll right past the cover that changes when focused on is impossible.
- If launching directly from the "Recently Played tab": The game's cover simply won't update and remains in the spot it was in before launching.
- In both above cases, the "Recently Played" tab returns the viewport to the same spot it was at before launching the game instead of showing the most recently played game and focusing on the game's cover.
- If launching from the game's details view: The first spot is blank. No item will be focused within the viewport. The viewport updates properly to show the first screen, however. I am unsure how this bug is triggered differently from the first-mentioned details view bug.

When "horizontal scrolling" is unchecked, I have experienced these bugs when launching from the game details:

- The first two spots for covers are blank and no item is focused.
- A spot within the game's row will be blank and the game's cover won't be updated. When returning to the "Recently Played" tab, the viewport updates to the first screen.
- In some cases, Playnite will freeze and trigger a "not responding" warning. I have never had to force-quit Playnite, it just freezes for 5-10 seconds. (This has not occurred with "horizontal scrolling" checked). 

When starting a game within the "Recently Played" tab that is on the first screen and the exiting the game and returning to the "Recently Played" tab, I have experienced this visual bug both with "horizontal scrolling" checked and unchecked:

- The game's cover doesn't update to the first position and remains in the spot it was in before launching.

In all cases, navigating away from the visual bug and returning resolves the issue. In some cases, merely moving the joystick/arrow keys so that an item is focused also resolves the issue.

**To Reproduce**
Launch a game within the "Recently Played" tab while in full screen mode. The specific bugs either depend on which screen the game was launched from (ie the main screen or the details view) or otherwise appear to be random.

Edit: optimized image.

**Comment by JosefNemec** [comment]
Will be fixed via #1995
