### ISSUE TITLE
Differentiate between game logos and icons as sources for metadata

### ISSUE THREAD

**Issue by Jon-PD** [JosefNemec/Playnite#2164]
Hey everyone, I've got a small issue when trying to use the Steam Grid DB metadata extension.

I've begun using the '[Fullscreen Banner](https://playnite.link/forum/thread-456.html)' theme to get the look I'm going for when using Playnite fullscreen - but it needs to use the SteamGridDB metadata extension to pull icons to function effectively. 

However using this extension to source game icons then means the normal 'details view' shows icons that are far too big. 
![Playnite details icon](https://user-images.githubusercontent.com/73672723/101486612-d7790200-3954-11eb-8d30-aec95db05df2.png)

Would it be possible to a) set a hard limit for how big icons can be in details view, or b) add a metadata setting that would allow to download icons from SteamGrid DB *and* the game store, and for fullscreen to use one and the desktop mode to use the other?

Also just want to say I think this is a fantastic piece of software, and for now I'm happy to carry on with icons disabled in details view until a fix comes along.

Thanks very much,

Jon

**Comment by SlipperyJim** [comment]
I think the ability to have both icons and logos as seperate metadata items and be able to choose (via theming probably) which one to use where would be great.

**Comment by JosefNemec** [comment]
Native support for logo media type will be added via #1682. If you have some issues Steam Grid DB extension, then you need to contact its developer. Please do not open issues related to 3rd party extensions in this repository, thank you.
