### ISSUE TITLE
Images in the "Edit Game" window don't scale properly

### ISSUE THREAD

**Issue by spektor56** [JosefNemec/Playnite#2167]
**Describe the bug**

Vertical artwork looks like a square in the game edit window

**Screenshots**

https://media.discordapp.net/attachments/699578268373876756/787027989586116649/unknown.png?width=1026&height=630

Crow:
It's definitely set to uniform scale https://github.com/JosefNemec/Playnite/blob/master/source/Playnite.DesktopApp/Windows/GameEditWindow.xaml#L678
Never mind, we should be using uniform fill, please open github issue for it, thanks.

**Comment by JosefNemec** [comment]
Fixed in 8.11
