### ISSUE TITLE
Playnite stretch resolution when streaming from PC to TV

### ISSUE THREAD

**Issue by jtlimo** [JosefNemec/Playnite#2171]
Hi everyone. 

I'm using Playnite to stream my pc games at my TV on living room. I'm using moonlight with playnite. 
When I start a game by moonlight directly, the resolution it's ok, but when I start a game by playnite, the game doesn't fit my tv screen. 

**Screenshots**
![IMG_20201213_214937.jpg](https://user-images.githubusercontent.com/4023304/102029416-27106100-3d8d-11eb-9c48-2c8fa72a88b0.jpg)![IMG_20201213_214903.jpg](https://user-images.githubusercontent.com/4023304/102029419-2a0b5180-3d8d-11eb-855c-1999f4c22157.jpg)

**Comment by JosefNemec** [comment]
Must be an issue with Moonlight. Playnite doesn't change resolution or interact with the game process in any way. The process itself is also not running in real fullscreen mode so it's not changing output resolution at all.

**Comment by jtlimo** [comment]
> Must be an issue with Moonlight. Playnite doesn't change resolution or interact with the game process in any way. The process itself is also not running in real fullscreen mode so it's not changing output resolution at all.

It's possible. I'll open an issue in moonlight project.

Thanks for the answer!
