### ISSUE TITLE
game activity v1.2.1 plugin install error

### ISSUE THREAD

**Issue by sengtsan** [JosefNemec/Playnite#2172]
attempted to install game activity 1.2.1 after notification. on restart unrecoverable error arises. 

*4b20c1e1-e9fb-42cb-9b93-7293d0d40dac

**Comment by JosefNemec** [comment]
It's an issue with the plugin, you need to contact its author. You can manually delete it from `%appdata%\Playnite\Extensions\` directory or start Playnite in safe mode via `Safe Mode.bat` from install directory and disable/uninstall the plugin from UI.
