### ISSUE TITLE
Some of my Ubisoft Connect games aren't recognized, while others are.

### ISSUE THREAD

**Issue by woutercools** [JosefNemec/Playnite#2175]
1 game (Trials Fusion) in the My Games sections of Ubisoft Connect isn't recognized in Playnite.
2 games (Prince of Persia The Forgotten Sands & Tom Clancy's Rainbow Six Siege) are in my Playnite Ubisoft Connect library, but I don't own these games.

I've hidden the 2 latter games, but how can I add the missing game?

**Comment by JosefNemec** [comment]
https://github.com/JosefNemec/Playnite/wiki/Uplay-troubleshooting

**Comment by woutercools** [comment]
Trials Fusion is listed in my configurations file, yet it refuses to import in Playnite

  C:\Program Files (x86)\Ubisoft\Ubisoft Game Launcher\cache\configuration\configurations (33 hits)
	Line 1088:     thread: TrialsFusion
	Line 1140:     GAMENAME: Trials Fusion
	Line 1149:     RELATED_GAMENAME_671: 'Trials Fusion: Riders of the Rustlands'
	Line 1151:     RELATED_GAMENAME_713: 'Trials Fusion: Empire of the Sky'
	Line 1153:     RELATED_GAMENAME_714: 'Trials Fusion: Welcome to the Abyss'
	Line 1155:     RELATED_GAMENAME_715: 'Trials Fusion: Fire in the Deep'
	Line 1157:     RELATED_GAMENAME_716: 'Trials Fusion: Fault One Zero'
	Line 1159:     RELATED_GAMENAME_717: 'Trials Fusion: After The Incident'
	Line 1161:     RELATED_GAMENAME_719: 'Trials Fusion: Season Pass'
	Line 1163:     RELATED_GAMENAME_754: Trials Fusion - Cape Set
	Line 1165:     RELATED_GAMENAME_755: Trials Fusion - 4th Upgrade set for Tricky
	Line 1167:     RELATED_GAMENAME_756: Trials Fusion - 5th Upgrade set for Cheetah
	Line 1169:     RELATED_GAMENAME_757: Trials Fusion - Rhino Helmet
	Line 1171:     RELATED_GAMENAME_758: Trials Fusion - Full Rider Outfit
	Line 2875:   name: 'Trials Fusion: Riders of the Rustlands'
	Line 2882:   name: 'Trials Fusion: Empire of the Sky'
	Line 2889:   name: 'Trials Fusion: Welcome to the Abyss'
	Line 2896:   name: 'Trials Fusion: Fire in the Deep'
	Line 2903:   name: 'Trials Fusion: Fault One Zero'
	Line 2910:   name: 'Trials Fusion: After The Incident'
	Line 2921:   NAME: "Trials Fusion Season Pass" 
	Line 2925:   name: 'Trials Fusion: Season Pass'
	Line 3111:   name: Trials Fusion - Cape Set
	Line 3119:   name: Trials Fusion - 4th Upgrade set for Tricky
	Line 3127:   name: Trials Fusion - 5th Upgrade set for Cheetah
	Line 3135:   name: Trials Fusion - Rhino Helmet
	Line 3143:   name: Trials Fusion - Full Rider Outfit
	Line 3879:   NAME: "Trials Fusion" 
	Line 3888:   NAME: "Trials Fusion - Digital Standard" 
	Line 3893:   name: Trials Fusion - Season Pass
	Line 4147:   name: 'Trials Fusion: Awesome Level Max'
	Line 4154:   name: Trials Fusion - Awesome Level Max
	Line 5821:   name: Trials Fusion - Awesome Level Max

**Comment by JosefNemec** [comment]
Is it actually a game bought on Ubisoft's shop or did you bought it from Steam? Games bought from Steam that require Ubisoft Connect are not intentionally imported, because they would cause duplicates (since you also have Steam entry imported).

Also, please attach that configurations file with list of games that should be imported but aren't, thanks.

**Comment by woutercools** [comment]
Indeed, it's bought on Steam, but requires Ubisoft Connect to run the game.

I also have bought Trials Evolution & Trials Rising on Steam, but they are causing duplicates.
So that is because both Evolution and Rising were given away on Ubisoft Connect?

I think I got it now.

**Comment by JosefNemec** [comment]
If the game has a flag that it was bought from other store (like Steam), then we won't import it. Everything else should get imported.

**Comment by woutercools** [comment]
ok, got it.

Thanks.

**Comment by MindOfBlaze** [comment]
This is crazy that this game still wont launch for me years later WILD do they ever fix anything?
