### ISSUE TITLE
Xbox Plugin: Not installed games do not show even tough "Import not installed games" is enabled

### ISSUE THREAD

**Issue by verybadsoldier** [JosefNemec/Playnite#2176]
**Describe the bug**
The Xbox plugin does not import not installed games even tough the checkbox "Import not installed games" is enabled.
After doing a library refresh only installed games show up. Not installed games do not.

Am I doing anything wrong? Wrong expectations?

**Screenshots**
![image](https://user-images.githubusercontent.com/364469/102672970-ab4e5400-4192-11eb-9538-7b59ceda3b45.png)

EDIT:
Showing not installed games works fine for all other plugins you see in the screenshot.

**Comment by JosefNemec** [comment]
I can't reproduce it. Note that not installed games will be imported only if they were started at least once in the past.

Can you also please attach diag. package that was requested in the issue template?

**Comment by verybadsoldier** [comment]
Oh sorry, ok, that explains it. Works now after I installed them, started them once and uninstalled them.

The wiki mentions this behavior for installed games but it surely makes sense that it also applies for not installed games:
https://github.com/JosefNemec/Playnite/wiki/Xbox-Library-troubleshooting

Thank you!
