### ISSUE TITLE
Add the possibility to launch same game with two differents emulators

### ISSUE THREAD

**Issue by greggameplayer** [JosefNemec/Playnite#2177]
**Check for existing issue**
Currently you have to duplicate the game, let say you have ryujinx and yuzu, and  you want to setup a game to be able to run on both of those emulators, the game will be duplicated in your playnite library.

**Describe the solution you'd like**
Add the ability to add more than one launch action and the ability to choose which one you want to execute when launching the game.

**Comment by JosefNemec** [comment]
#272

**Comment by greggameplayer** [comment]
@JosefNemec Ok sorry haven't seen that issue.
