### ISSUE TITLE
dlc questions

### ISSUE THREAD

**Issue by urfausto** [JosefNemec/Playnite#2180]
1 - will available dlcs be fetched too in the game's page?

2 - will downloaded dlcs be shown in the game's page?

now (with latest version), i have 2 games (epic games) that actually show a double "samename - pack" (definitive edition games) and some more scattered dlcs listed in library as games

**Comment by JosefNemec** [comment]
DLCs are not being imported (unless Playnite fails to recognize that an item is a DLC) and Playnite doesn't show any DLC information. #367

Please do not use github issues to ask general questions. Only file feature requests and bugs here. If you have some questions, please post them on forums or Discord. Thanks

**Comment by urfausto** [comment]
> Only file feature requests and bugs here. If you have some questions, please post them on forums or Discord. Thanks

ok got it. but i have these dlcs from epic games that show up as games in my library... what should i do about them?

**Comment by urfausto** [comment]
is #367 a feature to be implemented? i'd like to have a more extensive description of that... in order to decide myself what's to do.
