### ISSUE TITLE
Games not updating on Playnite

### ISSUE THREAD

**Issue by MeHoyMinoy92** [JosefNemec/Playnite#2182]
Games not updating on Playnite when games get uninstalled. So far they get added fine but lately they haven't been updated after uninstalling games off of Steam, Xbox Game Pass and Ubisoft. I've tried to update it in the menu several times, both update all and from each launcher individually. 

**Check for existing issue**
Please use issue search in the repository if the bug is something really obvious there's a high change it was already reported.

**Describe the bug**

**To Reproduce**
If it's not clear from the description how to reproduce the issue please add clear steps to reproduce the behavior.

**Screenshots**

**Diagnostics ID**
Please generate diagnostics package from "About Playnite" menu and attach identifier you received. If the issue is a crash bug, you can generate diag. package directly from crash dialog.

**Comment by JosefNemec** [comment]
For Playnite to pick up that a game is uninstalled you either have to start uninstallation process from Playnite or enable import of not installed games for a specific library.

**Comment by MeHoyMinoy92** [comment]
Would have been good information to have available on Playnite. I never
bothered uninstalling from Playnite because it directs you to the launcher
to uninstall from there anyways. Nobody would think that clicking uninstall
on Playnite would be the only way to remove it. Then to remove the games I
have to press remove and add to exclusions list even though I don't want to
add it to that because I may play some games later on. If it detects a game
is installed why can't it detect if one is no longer in your system. I'll
just uninstall and reinstall but if that doesn't work and my stuff is still
a mess I'm not using it because it defeats the purpose of the app being a
place to organize games.

**Comment by MeHoyMinoy92** [comment]
Users shouldn't have to figure out some work around, devs should have it
user friendly and these things should be user friendly

**Comment by JosefNemec** [comment]
If you don't enable import of uninstalled games, then uninstalled state won't be imported. I think that's quite clear. You can also always change install state manually.
