### ISSUE TITLE
When app window maximized and windows taskbar set to autohide, mousing over the bottom of the screen doesn't show the taskbar.

### ISSUE THREAD

**Issue by Alterae** [JosefNemec/Playnite#2185]
**Check for existing issue**
Checked, did not find this issue.

**Describe the bug**
I am running Windows 10, with the taskbar set to automatically hide itself.  When I have Playnite open, focused, and maximized, moving the mouse to the bottom of the screen does not reveal the task bar, even though it should.

**To Reproduce**
1. In windows 10, set the taskbar to automatically hide in desktop mode.
2. Open Playnite.
3. Focus the Playnite application window and maximize it.
4. Move the mouse to the bottom of the screen.

**Screenshots**
Not really applicable.

**Diagnostics ID**
b2b83723-c296-4575-9496-545ea90aa7a8

**Comment by JosefNemec** [comment]
Duplicate #1106
