### ISSUE TITLE
Cannot launch steam via playnite (steamui.dll

### ISSUE THREAD

**Issue by dualhammers** [JosefNemec/Playnite#2189]
**Check for existing issue**
This was already reported but the bug was closed without a solution and it's not clear it was ever investigated.

**Describe the bug**
After importing my steam library I tried to launch the game via the playnite UI by pressing "Play" on an installed game. The "Checking for updates" steam window pops up and then I get this error: **Failed to Load steamui.dll**

I am using a fresh install of steam on a newly installed version of windows 10 (everything installed 2 weeks ago). All programs installed in the stock places.

**To Reproduce**
Run an installed game from your steam library

**Screenshots**
![image](https://user-images.githubusercontent.com/7495830/103060900-d35cff00-4566-11eb-8241-22aa3e0862ff.png)

**Diagnostics ID**
34dbe71d-a988-4b96-a9da-629af052bf2d

**Comment by JosefNemec** [comment]
You need to reinstall Steam client, it's a known issue with Steam where it will not launch games via `steam://` uri sometimes.

**Comment by dualhammers** [comment]
I reinstalled steam and it continued to do this

Dec 24, 2020 1:56:58 AM Josef Nemec <notifications@github.com>:

**Comment by JosefNemec** [comment]
You need to uninstall and install it. Just reinstall might not help. It's nothing I can fix from Playnite, we just open `steam://` URI to tell Steam to start a game and what happens next is out of our control.

**Comment by dualhammers** [comment]
That is what I did. I uninstalled and installed.

You might want to communicate with Steam to see if they can help you solve
the problem - I know the engineers there can be pretty helpful. I'd love to
recommend this software to friends but I cannot recommend it to anyone when
a fundamental element of the program is broken and requires a total
reinstall of steam (and all my software)

**Comment by JosefNemec** [comment]
It's not an issue with Playnite. It's an issue with your environment or Steam install. As I sad already, we just open `steam://` URI to launch a game and that's it, we don't control how the actual game startup works.

**Comment by JosefNemec** [comment]
Btw, this was already reported in the past in #1284 and Steam reinstall helped to two people reporting the issue.
