### ISSUE TITLE
Synchronization without internet

### ISSUE THREAD

**Issue by felipeyuuki** [JosefNemec/Playnite#2190]
Hello, I would like to suggest a small change in the synchronization of games with online libraries.
When we turn on "Playnite", he is looking for games on the servers to update our list, but without the internet he is also looking, but he cannot and does not present anything, he just looks. This is nothing, but for some people this search bar can be annoying ...
So my suggestion is that, when we turn on the program, it quickly checks whether or not it has internet (in the background) and if it has normal open, but, if not, it only issues a warning that there is no connection and will start in mode "Offline", so you won't check for updates on the net.
That's it, thanks for listening!

**Comment by chocolatechipcats** [comment]
I'd say that an offline mode isn't necessarily needed. Just a check for "is connection available?" before doing any sync, either the automatic startup one or a manual one.

**Comment by JosefNemec** [comment]
Done in Playnite 10
