### ISSUE TITLE
Add support for more attributes (SameSite, etc) to IWebView SetCookies

### ISSUE THREAD

**Issue by bburky** [JosefNemec/Playnite#2194]
Please consider adding more cookie attributes to `GetCookies()` (`HttpCookie`) and `SetCookies()`.  `Secure`, `SameSite` and `HttpOnly` appear to be missing from the current API.

Chrome (and CEF) recently changed their [default behavior for cookies that don't specify `SameSite`](https://www.chromium.org/updates/same-site/faq):

> Cookies that do not specify a `SameSite` attribute will be treated as if they specified `SameSite=Lax`, i.e. they will be restricted to first-party or same-site contexts by default.

This broke one of my extensions, but I managed a hacky work around for now.

Alternatively, you could provide an API to force sending cookies to a domain (regardless of any attributes).

**Comment by JosefNemec** [comment]
Done in devel9.
