### ISSUE TITLE
Inconsistent wording while grouping by Time Played

### ISSUE THREAD

**Issue by j-dec** [JosefNemec/Playnite#2199]
**Screenshot:**
![Playnite DesktopApp_I8E4QseI5h](https://user-images.githubusercontent.com/20731289/103379912-8f7a7480-4ae7-11eb-94eb-02e18ac9d56c.png)

**Description:**
Every single group's title verbally describes the group, except `1000+`. Note that several (but not all) languages have this issue.

**Comment by JosefNemec** [comment]
What would be expected wording here? `More than 1000 hours`?

**Comment by j-dec** [comment]
`Over 1000 hours`, in my opinion.

**Comment by j-dec** [comment]
Here's a list of non-empty localizations that also have this problem:

- https://github.com/JosefNemec/Playnite/blob/dbe013c0dc2d53c9e60938127fb441484542e0d2/source/Playnite/Localization/ca_ES.xaml
- https://github.com/JosefNemec/Playnite/blob/dbe013c0dc2d53c9e60938127fb441484542e0d2/source/Playnite/Localization/cs_CZ.xaml
- https://github.com/JosefNemec/Playnite/blob/dbe013c0dc2d53c9e60938127fb441484542e0d2/source/Playnite/Localization/da_DK.xaml
- https://github.com/JosefNemec/Playnite/blob/dbe013c0dc2d53c9e60938127fb441484542e0d2/source/Playnite/Localization/es_ES.xaml
- https://github.com/JosefNemec/Playnite/blob/dbe013c0dc2d53c9e60938127fb441484542e0d2/source/Playnite/Localization/et_EE.xaml
- https://github.com/JosefNemec/Playnite/blob/dbe013c0dc2d53c9e60938127fb441484542e0d2/source/Playnite/Localization/fa_IR.xaml
- https://github.com/JosefNemec/Playnite/blob/dbe013c0dc2d53c9e60938127fb441484542e0d2/source/Playnite/Localization/fi_FI.xaml
- https://github.com/JosefNemec/Playnite/blob/dbe013c0dc2d53c9e60938127fb441484542e0d2/source/Playnite/Localization/fr_FR.xaml
- https://github.com/JosefNemec/Playnite/blob/dbe013c0dc2d53c9e60938127fb441484542e0d2/source/Playnite/Localization/hr_HR.xaml
- https://github.com/JosefNemec/Playnite/blob/dbe013c0dc2d53c9e60938127fb441484542e0d2/source/Playnite/Localization/lt_LT.xaml
- https://github.com/JosefNemec/Playnite/blob/dbe013c0dc2d53c9e60938127fb441484542e0d2/source/Playnite/Localization/nl_NL.xaml
- https://github.com/JosefNemec/Playnite/blob/dbe013c0dc2d53c9e60938127fb441484542e0d2/source/Playnite/Localization/no_NO.xaml
- https://github.com/JosefNemec/Playnite/blob/dbe013c0dc2d53c9e60938127fb441484542e0d2/source/Playnite/Localization/pl_PL.xaml
- https://github.com/JosefNemec/Playnite/blob/dbe013c0dc2d53c9e60938127fb441484542e0d2/source/Playnite/Localization/pt_BR.xaml
- https://github.com/JosefNemec/Playnite/blob/dbe013c0dc2d53c9e60938127fb441484542e0d2/source/Playnite/Localization/pt_PT.xaml
- https://github.com/JosefNemec/Playnite/blob/dbe013c0dc2d53c9e60938127fb441484542e0d2/source/Playnite/Localization/ru_RU.xaml
- https://github.com/JosefNemec/Playnite/blob/dbe013c0dc2d53c9e60938127fb441484542e0d2/source/Playnite/Localization/sk_SK.xaml
- https://github.com/JosefNemec/Playnite/blob/dbe013c0dc2d53c9e60938127fb441484542e0d2/source/Playnite/Localization/sr_SP.xaml
- https://github.com/JosefNemec/Playnite/blob/dbe013c0dc2d53c9e60938127fb441484542e0d2/source/Playnite/Localization/sv_SE.xaml
- https://github.com/JosefNemec/Playnite/blob/dbe013c0dc2d53c9e60938127fb441484542e0d2/source/Playnite/Localization/uk_UA.xaml
- https://github.com/JosefNemec/Playnite/blob/dbe013c0dc2d53c9e60938127fb441484542e0d2/source/Playnite/Localization/zh_TW.xaml

**Comment by JosefNemec** [comment]
Localization is done on Crowdin, I don't control (specifically I can't because I don't speak those languages) how they decide to translate it once we make this change.

**Comment by JosefNemec** [comment]
Changed in devel9.
