### ISSUE TITLE
Endpoint not found exception

### ISSUE THREAD

**Issue by AntoinevdHorst** [JosefNemec/Playnite#220]
[errormsg.zip](https://github.com/JosefNemec/Playnite/files/1395628/errormsg.zip)

I started rocket league like this : https://imgur.com/a/mkzfU and proceeded to get that exception. Game still launched and playnite also launched just fine.
Also would be nice to get some visual feedback while creating a diagnostics package, although that is probably a really minor thing

**Comment by JosefNemec** [comment]
Released in 2.8
