### ISSUE TITLE
Initial scrollbar length in Details View is incorrect

### ISSUE THREAD

**Issue by j-dec** [JosefNemec/Playnite#2200]
**Description:**
Initially, the scrollbar length seems to be set to a certain constant default value upon entering Details View, rather than the appropriate length dependent on the number of games in the Library. At some point while scrolling towards the bottom of the list of games, the scrollbar is resized to the correct length. This occasionally makes it annoying to navigate Details View using the scrollbar with mouse.

**To reproduce:**

*Requirements:*
- set Playnite to Details View
- have enough games in your Library?

*Steps:*
1. (Re)initialize the scrollbar:
    1. (Re)launch Playnite.

    or
    1. Switch to a different View.
    2. Switch back to Details View.

    or
    1. Search by name.
    2. Clear the search box.

    (there might be more ways to perform this step).
2. Drag the scrollbar towards the bottom.

**Screenshots:**
| Initial scrollbar length            |  Correct scrollbar length |
:-------------------------:|:-------------------------:
![image](https://user-images.githubusercontent.com/20731289/103383977-fbafa500-4af4-11eb-92a6-8eadfd846698.png)| ![image](https://user-images.githubusercontent.com/20731289/103384537-0d924780-4af7-11eb-86ca-8485c8b7cae3.png)

**Comment by JosefNemec** [comment]
This is default behavior in WPF UI toolkit we use. Nothing I can do about it. It may be solved by WPF update once we switch to .NET 5 via #1141
