### ISSUE TITLE
Hidden games appear in notification area menu

### ISSUE THREAD

**Issue by chocolatechipcats** [JosefNemec/Playnite#2201]
Playnite 8,11

I have a copy of a duplicate game hidden.* However, despite it being hidden, it also appears in the notification area 'recently played games' list. 

If this is by design, can it please be made optional?

*This affects an Origin game launched via Steam. I guess the last-played date gets synced back from Origin. 

Thank you.

**Comment by darklinkpower** [comment]
Does it still happen if you disable this option?

![imagen](https://user-images.githubusercontent.com/1389286/103396336-3bc45700-4af8-11eb-9e96-173fbf147ab3.png)

**Comment by chocolatechipcats** [comment]
It's gone now. I didn't even see that option, though I was on that exact page. I think I was looking for some variant of system tray/notification area. 

Sorry.
