### ISSUE TITLE
XInput sends keys to app/game if the app was already running before Playnite

### ISSUE THREAD

**Issue by MartinAngelov** [JosefNemec/Playnite#2202]
If a game/app is already running and then start Playnite fullscreen, when I click a button on controller it will send the in game command to window and also Playnite mapped key. I assume that's becasue by defualt xinput is diabaled only when game is launched from inside Playnite.

**Comment by JosefNemec** [comment]
Probably similar issue to #2107

Playnite only processes XInput when window focus is active. I don't know how you are starting Playnite, but if something gives Playnite window focus, then input will be processed.

If you can reproduce this reliably on demand, please add detailed steps how to reproduce this.

**Comment by MartinAngelov** [comment]
Starting it with PowerShell Start-Process, and when I foucs on game or wathever app that supports xinput it is still happening.

**Comment by JosefNemec** [comment]
Then you have to adjust your custom way of starting Playnite. If it doesn't happen when the app is started normally, then there's nothing for me to fix.

**Comment by MartinAngelov** [comment]
> Then you have to adjust your custom way of starting Playnite. If it doesn't happen when the app is started normally, then there's nothing for me to fix.

When using PlayniteUI.exe default parameters  sounds like an bug in the way that it calls it. For me it is just fine to directly call the Fullscreen.exe

**Comment by JosefNemec** [comment]
The only thing that `PlayniteUI.exe` does is that it calls main exe. It's there only for backwards compatibility with application shortcuts created by Playnite 4 and older. It has no other functionality.

**Comment by MartinAngelov** [comment]
> The only thing that `PlayniteUI.exe` does is that it calls main exe. It's there only for backwards compatibility with application shortcuts created by Playnite 4 and older. It has no other functionality.

Great! Thanks!
