### ISSUE TITLE
plugins settings are partialy canceled

### ISSUE THREAD

**Issue by Lacro59** [JosefNemec/Playnite#2205]
When I undo a change to the plugin settings, the change is not saved but the changes are still visible in the plugin settings.

I checked with your Steam metadata plugin and I understood the problem.

Why don't you integrate the clone system with the default template?
https://github.com/JosefNemec/PlaynitePlugin-SteamStoreMetadata/blob/b79c28f5b2bcb6b3081cb86b581e4111170994b9/source/UniversalSteamMetadata/UniversalSteamMetadataSettings.cs#L44

**Comment by JosefNemec** [comment]
How is this an issue with Playnite? Canceling is implemented in each plugin separately.

I admit that current template implementation is not ideal and I actually reworked it devel9 already.
