### ISSUE TITLE
a specific manual game library update doesn't call OnLibraryUpdated()

### ISSUE THREAD

**Issue by Lacro59** [JosefNemec/Playnite#2207]
When you update a specific game library (steam, gog, ...), the OnLibraryUpdated() function isn't called.

No problem with the automatic update on Playnite start and the "Update All" from menu.

**Comment by JosefNemec** [comment]
I think it would make sense to actually remove this event, since you can listen to changes from `Games` database collection.

**Comment by Lacro59** [comment]
I saw two events for Games: ItemCollectionChanged & ItemUpdated.

The first is called when a game is add or delete from database.
The second is called when a game is updated.

During the game library update process, this two events are called many time.

The advantage of OnLibraryUpdated() is that it is called only once at the end of the update process.

**Comment by JosefNemec** [comment]
Fixed in devel9.
