### ISSUE TITLE
Issues loading Model 2 Emulator (http://nebula.emulatronia.com)

### ISSUE THREAD

**Issue by imkrut** [JosefNemec/Playnite#221]
Using the " "{ImagePath}" "  arguments (and other variants)
It loads the games into the launcher (would be cool if it would fetch the game names instead of the zip file names), and launches the emulator, but doesn't load the actual game.

Can't seem to make it work.

**Comment by By6r9** [comment]
`
emulator_multicpu.exe File
`
In LaunchBox there is special option for it: use file name only without extension or folder path
and second: don't use qoutes (around file name/path)

**Comment by JosefNemec** [comment]
Well that doesn't make much sense. But ok, I'll add option to insert file path without an extension.

**Comment by By6r9** [comment]
Arcade emulators are using predefined sets (vf2, sfexj, etc.) and for m2emulator you define rom path in emulator.ini. 
Same thing with MAME, but it is much smarter.

**Comment by JosefNemec** [comment]
But in his example (posted on Discord), he had zip file. So are you saying that it has to be unpacked first? Because passing zip file without file extension doesn't make any sense to me.

**Comment by By6r9** [comment]
For MAME vf2 set can mean: vf2.zip, vf2.7z, or folder named 'vf2'. MAME will check all those variants when started as 
`
mame vf2
`
in predefined ROM paths,  but also supports full path with full file name. M2emulator only supports name sets, I think.

**Comment by JosefNemec** [comment]
Fixed in 2.8, emulator import should import Nebula 2 with everything all set. If you want to set it up manually then use this as parameter string `{ImageNameNoExt}`. And remember that you have to set your ROM folder in Nebula itself, otherwise launching from cmdline won't work at all (in `emulator.ini` under `[RomDirs]`).

**Comment by imkrut** [comment]
Awesome, thanks!
