### ISSUE TITLE
itch.io library issue

### ISSUE THREAD

**Issue by WHiZSTA** [JosefNemec/Playnite#2211]
the itch.io library is assigning game 'features' to 'tags' unlike all other libraries. this poses an issue when trying to filter by say 'co-op' as a feature which shows all coop games from all other libraries, but to see them from itch, you have to clear the features filter and use a tag filter, meaning there is no way to see all co-op games from all libraries at once due to this misclassification/misassignment.

**Comment by JosefNemec** [comment]
Nothing I can do about that. Itch doesn't have dedicated "features" field, they put everything into tags.

**Comment by WHiZSTA** [comment]
could you just put the tags under features if the tagname matches a featurename?

**Comment by JosefNemec** [comment]
Matches what feature name? Itch doesn't have separate features, there's no reliable way how to detect if tag is actual feature or not.

**Comment by WHiZSTA** [comment]
no i mean, you clearly have a database or list of feature names that populate the feature dropdown for filter selection, im assuming gathered from different stores. if an itch.io title has say 'co-op' as a tag and 'co-op' is also in your feature database/list, add it for that title as a feature too. i noticed most of the tags have the exact equivalent features, others are clearly just unusable text that doesn't relate to other stores. but for those where the tag does match couldn't you just add the flag as a feature in the local db?
