### ISSUE TITLE
playnite insecure for linked google login

### ISSUE THREAD

**Issue by WHiZSTA** [JosefNemec/Playnite#2212]
when attempting to authenticate to connect to stores like epic games, indiegalla etc, if you have your acct with them via a google login (Login to those sites with a linked google account by clicking  'login with google', or the big G  as opposed to a local account with them where you just used your gmail address to make an account) after u put in your email address to go where you would enter your password you get an error page saying playnite's web browser is insecure and it won't let you continue to login.

![unknown](https://user-images.githubusercontent.com/18521070/103803800-12875780-501f-11eb-943a-d1ab8af93b21.png)

**Diagnostics ID**
ca575c12-63e9-4588-93cc-9da79c5a83df

**Comment by JosefNemec** [comment]
Same issue as #1416, see that issue for a workaround.

**Comment by Redherring32** [comment]
Issue #1416 is no longer present on this repository?
It is mentioned that this issue and a few others are duplicates to that, however it seems to not exist anymore, did it get deleted?

**Comment by JosefNemec** [comment]
It got moved to a different repository because authentication is handled by each integration plugin separately.
