### ISSUE TITLE
steam game tags not importing

### ISSUE THREAD

**Issue by WHiZSTA** [JosefNemec/Playnite#2213]
games are not importing the steam user-defined tags when they come from a steam store, even though the checkbox for metadata imports shows to get tags from the 'official store'.

![image](https://user-images.githubusercontent.com/18521070/103804503-38f9c280-5020-11eb-91cb-a32473f09281.png)

![image](https://user-images.githubusercontent.com/18521070/103804932-d5bc6000-5020-11eb-885d-fda516be3985.png)

![image](https://user-images.githubusercontent.com/18521070/103804995-f4225b80-5020-11eb-9312-14d716bce214.png)

i would think these popular tags for the games would be imported into the library for filtering purposes as they are with other libraries but they don't. Nor do ones you've added specifically seem to get synced over. I'd prefer the former functionality though.

**Comment by JosefNemec** [comment]
#605
