### ISSUE TITLE
Default page on Playnite to be Summary and Statistics.

### ISSUE THREAD

**Issue by sharazy** [JosefNemec/Playnite#2214]
Whenever we removed items or hide game (filter option or hide from context menu, the Playnite seems to be load empty page on "Details View". On startup, Playnite seems to load the first game on the list. 

My suggestion is to utilize statistic and summarize it along with recent games on prime page. The idea is like GOG Galaxy launcher that pack with the informative stuff, rather than boring empty space or the most top game on the list.

**Comment by JosefNemec** [comment]
will be done via  #1212
