### ISSUE TITLE
a control notch when ingame

### ISSUE THREAD

**Issue by christophe195** [JosefNemec/Playnite#2219]
Hello,

I have a computer that has only multiple bluetooth dongles, LAN, HDMI and power connected. When i play a steam game i can close it within the gamen, but when i use dolphin or ppsspp i can not close the game.

I'm a (web) devlopper, so i think it's possible to make a function weel that coms up in game when i press the psp or xbox button on the controller like the radget and clank weapon selector whith 4 options (volume +, volume -, close game, shut down system). I think that Playnite can get the pid id of the game when launching so it can close the game when requested.

is this something interesting?

![Quick_Select_from_R%26C_%282002%29](https://user-images.githubusercontent.com/22600069/104111311-b5222d80-52e0-11eb-8efd-c91d5da3663b.png)
![Quickselect_ACiT](https://user-images.githubusercontent.com/22600069/104111312-b6535a80-52e0-11eb-8e6d-52971ff72609.jpg)

**Comment by darklinkpower** [comment]
Playnite doesn't get the PID when executing the games, it only tells the original client to launch `x` game and what happens afterwards is outside of Playnite's control. To get the process ID you'll want to use something like `Get-Process` in Powershell in an  extension to track the game PID and do what you want.

**Comment by christophe195** [comment]
> Playnite doesn't get the PID when executing the games, it only tells the original client to launch `x` game and what happens afterwards is outside of Playnite's control. To get the process ID you'll want to use something like `Get-Process` in Powershell in an extension to track the game PID and do what you want.

Development of windows apps is out of my reatch for now, it was a idee.

**Comment by JosefNemec** [comment]
#1390

**Comment by blacklat** [comment]
> Playnite doesn't get the PID when executing the games, it only tells the original client to launch `x` game and what happens afterwards is outside of Playnite's control. To get the process ID you'll want to use something like `Get-Process` in Powershell in an extension to track the game PID and do what you want.

![Playnite DesktopApp_mH7oSpYeET](https://user-images.githubusercontent.com/56522998/147617138-449f60a7-87c5-4cf6-bc92-1938852baea1.png)

You're wrong, if it does monitoring by process, it's obvious that it has a way to know the PID.
