### ISSUE TITLE
Add support for Xbox library

### ISSUE THREAD

**Issue by dfocanti** [JosefNemec/Playnite#222]
For reference, sites like trueachievements and howlongtobeat are able to read those profiles so I believe it should be possible. For anyone with an Xbox Live profile, I believe this should also solve the issue of including Windows Store games, or at least the ones that have achievements.

**Comment by enfenix** [comment]
Could the API on https://xboxapi.com/ help?

**Comment by aserrallerios** [comment]
BTW, this integration is already working on GOG Galaxy 2.0, so it shouldn't be impossible.

**Comment by JosefNemec** [comment]
Done in `devel7`.
