### ISSUE TITLE
Import/Export Playnite Library

### ISSUE THREAD

**Issue by trymeouteh** [JosefNemec/Playnite#2220]
Please add a setting to import and export your playnite library into a compressed zip or 7z file which can be imported again. This compressed file will contain everything inside the playnite library folder such as the games, game covers, game background images, categories, platforms, game details, all of it.

This way Playnite will have an official import/export feature to allow for gamers to export their library and back it up now and then and then be able to import it to their new gaming computers with just a few clicks.

**Comment by JosefNemec** [comment]
#912
