### ISSUE TITLE
Background images loading time became much longer since update

### ISSUE THREAD

**Issue by lionnesquaer** [JosefNemec/Playnite#2221]
**Describe the bug**
Background images loading time became much longer since update 8.11. It is noticable and contnues few seconds.

**Diagnostics ID**
2f1d516c-6a9c-4e5f-aece-3e592a6c02d7

**Comment by JosefNemec** [comment]
I haven't changed how images are being loaded for several major versions now. I think last time I changed it was in 5.0. It must be some 3rd party causing it.

**Comment by lionnesquaer** [comment]
@JosefNemec Then i disable "Use game background image as window background" in appearence setting game detail and background image loads instantly. I dont now but i remember, maybe month ago, all load instantly with this option on.  I use background images from steamdb, i use playnite portable on SSD, i disable all background task and nothing changed

**Comment by lionnesquaer** [comment]
@JosefNemec Im fix this! Im disable Hardware Accelaration in Windows before. Lol!
sorry to bother you
