### ISSUE TITLE
Star Wars Battlefront II Not Syncing (Epic Games)

### ISSUE THREAD

**Issue by shangles** [JosefNemec/Playnite#2225]
**Describe the bug**
Star Wars Battlefront II Celebration Edition was just released as the free game on Epic Games Store today.  I added the game to my EGS library, but didn't install it (as I frequently do.)

I updated all game libraries in Playnite and it did not discover this game.

**To Reproduce**
Take advantage of the free game on EGS by adding it to your library.   Attempt to sync your game libraries in Playnite.

**Screenshots**
N/A

**Diagnostics ID**
94a69c5a-7c31-4aba-9cd2-3276659d15c2

**Comment by JosefNemec** [comment]
The game activates (the first time you install it), installs and runs via Origin. You need to use Origin integration for this game.
