### ISSUE TITLE
Google Media tab search term modification.

### ISSUE THREAD

**Issue by Haelikor** [JosefNemec/Playnite#2227]
eg Current setup is: "{Game Title} wallpaper"

A way to add words onto that would be a huge efficiency boost when going through a lot of content in one platform. (Example: being able to alter default search to "{Game Title} wallpaper imagesize:1920x1080 (platform)"

Currently this is hard coded but it would be great to see it as a customizable option in the client itself. 

I have some platforms with items in the 1000+ range, so CTRL+V'ing repeatedly becomes cumbersome. Thanks for considering looking into this and I hope it isn't a repeat though quick search doesn't appear to mention it.

**Comment by edwahu** [comment]
I was actually about to raise an issue to suggest changing the search term "Icon" to "Logo" when searching for Logos as the latter seems to give much better results, but it sounds like this would cover it anyway.

**Comment by cresource** [comment]
Is this still something that is planned? I am currently building out my games with Playnite, and I have roughly 400 games that I will have to manually go through and download logos for. Having a way to make Playnite search for logos instead of icons would cut the time necessary by a lot.

**Comment by JosefNemec** [comment]
I'll add it for Playnite 10 public release.

**Comment by JosefNemec** [comment]
Done in 10.1
