### ISSUE TITLE
Negative Filter

### ISSUE THREAD

**Issue by townkrier** [JosefNemec/Playnite#2230]
I think it would be extremely useful to have the ability to click a filter twice to filter out the selected field, possibly showing a minus/negative sign instead of the check for positive filter.

![image](https://user-images.githubusercontent.com/77748992/105220083-38cfeb80-5b25-11eb-9b44-d9be67d623ea.png)

**Comment by JosefNemec** [comment]
#837 #1895

**Comment by claudiombsilva** [comment]
I don't think issues #837 and #1895 solve this issue.
If they do, please explain how can I create a filter to include games that do NOT have a specific feature?
For example, I would like to create a filter for games that are NOT VR.

**Comment by JosefNemec** [comment]
Up to date issue is #2538
