### ISSUE TITLE
Star Wars Battlefront doesn't correctly get imported from Epic

### ISSUE THREAD

**Issue by cristi1990an** [JosefNemec/Playnite#2231]
What happens:
- game doesn't show up under Epic games
- game shows up 3 times under Origin games
- launching it from Origin tab opens Origin which tells you the game is not activated on you account

**Comment by JosefNemec** [comment]
Duplicate #2225

The game not starting via Origin integration is caused by the latest Origin update that broke it. See [this](https://playnite.link/forum/thread-563.html) for a workaround.
