### ISSUE TITLE
The 'Features' field is not available for filtering

### ISSUE THREAD

**Issue by bettafo** [JosefNemec/Playnite#2233]
**Check for existing issue**
-Not yet reported as far as I could see

**Describe the bug**
-The field 'Features' seems to have been omitted from the 'Filters' panel, rendering the field much less useful.

**To Reproduce**
-Open the 'Filters' panel and search for 'Features'. I checked again and again and could not see it

**Comment by JosefNemec** [comment]
Please post screenshot. It's there for me. If you are using custom theme, then it's probably an issue with the theme not being updated.

**Comment by bettafo** [comment]
OO Undeed I am using a slightly modified version of the Default theme that maximizes the space available to display my background images. I did not realize that it would mean missing on some of the updates. You can close this ticket, thank you.
