### ISSUE TITLE
Select which fields are avaialble in the Filters panel

### ISSUE THREAD

**Issue by bettafo** [JosefNemec/Playnite#2237]
**Check for existing issue**
No similar feature has been requested as far as I could see.

**Describe the solution you'd like**
The Filter panel currently proposes 23 fields for filtering and that number may still increase given that there exist a few requests for more fields. Consequently it is not rare to have to search and  scroll up and down to find the field(s) your are interested in when you use the filter panel. However most users only routinely use a subset of these fields and that subset may vary from one user to the other.

So it would be nice to have a section in the Settings where users could specify which fields should be inculded in the filter panel.

**Comment by JosefNemec** [comment]
#1423
