### ISSUE TITLE
Font Documentation/Wiki Link is Dead - Potentially Needs Revision

### ISSUE THREAD

**Issue by qwertycody** [JosefNemec/Playnite#2238]
See below steps - need alternative link or location for development ide setup:

https://github.com/JosefNemec/Playnite/wiki/Building#development-environment

![image](https://user-images.githubusercontent.com/4968312/105855664-52a28000-5fb6-11eb-8bf8-764ae33d7d7b.png)

![image](https://user-images.githubusercontent.com/4968312/105855553-369ede80-5fb6-11eb-88f8-0fecc8b2c982.png)

**Comment by qwertycody** [comment]
For now just copied fonts in folder and named to appropriate dependency name of "XBOX ONE" or "Playstation4"

**Comment by JosefNemec** [comment]
Nothing I can really do if the font is no longer available.

**Comment by JosefNemec** [comment]
Closing. I haven't found suitable free replacement and I think it's a waste to purchase different font when the current one still works just fine. I've made some changes to Playnite 9 branch, Fullscreen mode will compile even if the font is not available.
