### ISSUE TITLE
Filter game by cover and background image size

### ISSUE THREAD

**Issue by bettafo** [JosefNemec/Playnite#2240]
**Check for existing issue**
No similar proposal was made as far as I could see.

**Describe the solution you'd like**
Lately a feature was added to Playnite warning users about potentially too large game backgrounds or covers that could cause slow downs This is useful, but for users that had set up a large library before that feature was implemented or who downloaded metadata in bulk it can be hard to trace down games that have too large covers or backgrounds.

So for maintenance it would be useful to be able to filter gmaes per backgrounds or cover images sizes.

**Comment by JosefNemec** [comment]
Duplicate to #2240

**Comment by bettafo** [comment]
oO Duplicate to itself?

**Comment by JosefNemec** [comment]
Sorry, should have been #2236

**Comment by joyrider3774** [comment]
@bettafo checkout "game media tools" extension by darklingpower it can do what you want.. It can add tags for those images and you can filter on the games using those tags (optimazation tool)
