### ISSUE TITLE
Fullscreen filters do not persist when changing between "Recently Played/Most Played/All/etc"

### ISSUE THREAD

**Issue by Panthon13** [JosefNemec/Playnite#2241]
Changing between Recently Played, Favorites, All, etc causes any set filters to reset (specifically with Categories in my case), even though the filter still has checkmarks in the correct places.

1. To reproduce, start in Recently Played and set up a filter using categories
2. Change to Favorites
3. Return to Recently Played
4. Recently Played is no longer filtered, yet the categories are still selected in the filter. I have to uncheck and recheck one of the categories to get the filter to come back.

I'm not sure how this is intended, but in my opinion, it should work something along these lines:
- Set a filter on Recently Played, change to Favorites, return back to Recently Played, filter should persist. Each group (Recently Played, Favorites, etc) should have its own filter rules retained, rather than one filter shared across all of them.

**Comment by JosefNemec** [comment]
See #590
