### ISSUE TITLE
Add "help" commandline switch to toolbox.exe

### ISSUE THREAD

**Issue by joyrider3774** [JosefNemec/Playnite#2244]
**Check for existing issue**
none

**Describe the solution you'd like**
a lot of programs when you don't supply any parameter display a list of commandline parameters you can use with the program. Or by using "/?" "-h" "--help" or similar. Sometimes i want to use toolbox.exe but i can't remember the parameters and i always have to go and look on the tutorial page about toolbox.exe to know what they are. A simple commandline parameter to output the existing commandline parameters might help alliviate this as i can immediatly get it from the program.

**Screenshots**
![Screenshot](https://i.imgur.com/iKTuySh.png)

**Comment by JosefNemec** [comment]
Done in devel9.
