### ISSUE TITLE
Does not open games

### ISSUE THREAD

**Issue by MeHoyMinoy92** [JosefNemec/Playnite#2247]
**Check for existing issue**
Please use issue search in the repository if the bug is something really obvious there's a high change it was already reported.
Does not open games. I tried GTA, Hades, Apex, nothing works and I have to open the clients to do it. I give up I'm just going to use the clients.
**Describe the bug**

**To Reproduce**
If it's not clear from the description how to reproduce the issue please add clear steps to reproduce the behavior.

**Screenshots**

**Diagnostics ID**
Please generate diagnostics package from "About Playnite" menu and attach identifier you received. If the issue is a crash bug, you can generate diag. package directly from crash dialog.

**Comment by JosefNemec** [comment]
> A clear and concise description of what the bug is.

Where's the diag. package? What does "Does not open games" mean? What error do you get? What's the source client? Steam? EGS?

Reports like this make it nearly impossible to diagnose what's the issue.
