### ISSUE TITLE
Detect if game is already running

### ISSUE THREAD

**Issue by MartinAngelov** [JosefNemec/Playnite#2248]
**Check for existing issue**
Was not able to find such an option 

**Describe the solution you'd like**
At the moment I am using PowerShell extension to get the process for selected app an se the $game.IsRunning true which changes the state inside Playnite but it is not able to detect when process/app exits
Is there built in feature for that or those PlayniteApi exposes ProcessId somehow in order to be set via extension ?
Either built-in or api property will do just fine.

Code OnGameSelected:

```
    $GameName = $selection.NewValue[0].Name
    $GameProcess = Get-Process | Where-Object {$_.MainWindowTitle -like "*$GameName*"}
    $MyGame = $PlayniteApi.Database.Games[$selection.NewValue[0].Id]

    if ($GameProcess)
    {
           $MyGame.IsRunning = $true
    }
```

**Comment by JosefNemec** [comment]
There's no way how to get game's process using SDK. In a lot of cases, Playnite doesn't even know what game's process is, especially if the game was started by a library plugin.

Why are you modifying `IsRunning` via extension anyways? That should be already set if the game was started from Playnite.

**Comment by MartinAngelov** [comment]
> Why are you modifying `IsRunning` via extension anyways? That should be already set if the game was started from Playnite.

I am using virtual desktops and Playnite in fullscreen mode and sometimes game is minimized in other virtual desktop so when click on game and is sets it to running I can see there is already instance of it running.
