### ISSUE TITLE
Crash Relating to Rainbow Six Siege Imported Via Uplay

### ISSUE THREAD

**Issue by digitalmisanthrope** [JosefNemec/Playnite#225]
For some odd reason Rainbow Six Siege imported via Uplay causes the program to crash when the tile is interacted with. Resolved by deleting database, turning off uplay integration and re-importing library sans Rainbow Six.

Diag attached.
[diag1.zip](https://github.com/JosefNemec/Playnite/files/1400321/diag1.zip)

**Comment by JosefNemec** [comment]
Released in 2.8
