### ISSUE TITLE
I can't seem to authenticate Epic because I use a Google account for it. "This app may not be secure, use another browser."

### ISSUE THREAD

**Issue by NomadicVoxel** [JosefNemec/Playnite#2251]
I can't say what update introduced the bug, as I was able to do this before, but after moving to a new computer, I'm having issues authenticating my Epic account, which uses a Google ID. 
When I select to authenticate, and when I choose to use a Google ID, the popup window does take the Google username, but instead of then asking for a password, it shows the text shown below. 

![image](https://user-images.githubusercontent.com/36419454/107140179-32879080-68d5-11eb-9c2f-e0843ea3c39c.png)

Diagnostic id: 9eaeb657-4d52-4bc3-b593-73e11479a16a

// I did search for bugs related to google and didn't see anything that looked relevant, sorry if this is already known.

**Comment by JosefNemec** [comment]
Same issue as  #1416, see that for a workaround.

**Comment by NomadicVoxel** [comment]
Ah, alright. Thanks.
