### ISSUE TITLE
Error: Cannot perform operation because the wildcard path.

### ISSUE THREAD

**Issue by Josegg0** [JosefNemec/Playnite#2252]
Error: Cannot perform operation because the wildcard path.

This happens when there is a script with a game with an installation directory with [ ]. The game starts but the script not. Showing the error message in the pic. Tried to replicate this in another emulator and is the same error. If no script no error.

Installation Directory: C:\Users\JOSE\Documents\Emuladores\Wii U\Wii U Games\Captain_Toad_Treasure_Tracker_[AKBP0101]\code\

Rom path: C:\Users\JOSE\Documents\Emuladores\Wii U\Wii U Games SSD\Captain_Toad_Treasure_Tracker_[AKBP0101]\code\Kinopio.rpx

Script: Start-Process "C:\Users\JOSE\Documents\Portable\Playnite\Scripts\empty.txt"

The path does exist and works fine when launched straight from the emulator. Also if I remove [ ] from ROM folder playnite is then able to execute the rom and script.

I thinks there is a problem with powershell and the way it handles the installation directory, even if the script doesn't use this installation directory as shown in this case or if it doesn´t necessarily exist like the next situation:

If any character fom installation directory is removed (keeping original rom path with [ ]), playnite is then able to execute the rom and script.

Example of New Installation Directory (removed C from Captain): C:\Users\JOSE\Documents\Emuladores\Wii U\Wii U Games\aptain_Toad_Treasure_Tracker_[AKBP0101]\code\

Same old Rom path: C:\Users\JOSE\Documents\Emuladores\Wii U\Wii U Games SSD\Captain_Toad_Treasure_Tracker_[AKBP0101]\code\Kinopio.rpx

Log:

28-01 19:22:51.478|INFO|GamesEditor:Starting Captain Toad: Treasure Tracker, e290146d-291e-4daf-85ee-b478d2fb6352, 2859f867-facb-49a0-a2a9-06a30e56f8c2, 00000000-0000-0000-0000-000000000000
28-01 19:22:51.478|INFO|GamesEditor:Using generic controller start the game.
28-01 19:22:51.501|INFO|GameActionActivator:Activating game task Emulator: 0ca6e783-1d63-4da1-8327-08abe874a81b, 1176ab86-70d4-4f11-905a-3122bc589bee, False,
28-01 19:22:51.501|DEBUG|ProcessStarter:Starting process: C:\Users\JOSE\Documents\Emuladores\Wii U\cemu\Cemu.exe, -g "C:\Users\JOSE\Documents\Emuladores\Wii U\Wii U Games\Captain_Toad_Treasure_Tracker_[AKBP0101]\code\Kinopio.rpx" -f, C:\Users\JOSE\Documents\Emuladores\Wii U\cemu, False
28-01 19:22:51.510|INFO|GamesEditor:Started Captain Toad: Treasure Tracker game.
28-01 19:22:51.510|INFO|GamesEditor:Executing script action in PowerShell runtime.
28-01 19:22:51.542|ERROR|GamesEditor:Failed to execute game's game-started action.
Playnite.SDK.Exceptions.ScriptRuntimeException: Cannot perform operation because the wildcard path C:\Users\JOSE\Documents\Emuladores\Wii U\Wii U Games\Captain_Toad_Treasure_Tracker_[AKBP0101]\code did not resolve to a file.
at Playnite.Scripting.PowerShell.PowerShellRuntime.Execute(String script, Dictionary`2 variables, String workDir) in E:\Devel\Playnite\source\Playnite\Scripting\PowerShell\PowerShell.cs:line 86
at Playnite.Scripting.PowerShell.PowerShellRuntime.Execute(String script, String workDir) in E:\Devel\Playnite\source\Playnite\Scripting\PowerShell\PowerShell.cs:line 55
at Playnite.GamesEditor.ExecuteScriptAction(ScriptLanguage language, String script, Game game) in E:\Devel\Playnite\source\Playnite\GamesEditor.cs:line 1133
at Playnite.GamesEditor.Controllers_Started(Object sender, GameControllerEventArgs args) in E:\Devel\Playnite\source\Playnite\GamesEditor.cs:line 862
28-01 19:22:51.542|ERROR|GamesEditor:Start-Process "C:\Users\JOSE\Documents\Portable\Playnite\Scripts\empty.txt"
28-01 19:23:40.530|INFO|GamesEditor:Game Captain Toad: Treasure Tracker stopped after 49 seconds.

![Screenshot (312)](https://user-images.githubusercontent.com/67025623/107162393-c3f81080-6970-11eb-9bd6-4ba601fde542.png)

![106309337-f34fa480-622f-11eb-9f2c-880746d96e2e](https://user-images.githubusercontent.com/67025623/107162406-d4a88680-6970-11eb-9598-0202d81cf218.png)

![Screenshot (314)](https://user-images.githubusercontent.com/67025623/107162415-e0944880-6970-11eb-8ee8-7639c4d5b032.png)

[playnitesnoscriptscript.log](https://github.com/JosefNemec/Playnite/files/5940328/playnitesnoscriptscript.log)
[playnitechangeonlyonecharacterdirectory.log](https://github.com/JosefNemec/Playnite/files/5940333/playnitechangeonlyonecharacterdirectory.log)

**Comment by JosefNemec** [comment]
Sadly, this is a bug in `Start-Process` cmdlet, where it will fail when working directory contains some specific characters ([ and ] in this case). We can't update PowerShell runtime until #1141 is done, so there's nothing I can do about this.

To workaround this, you have to specify `-WorkingDirectory` when using `Start-Process`.

**Comment by rye-74** [comment]
im having this same issue. Looks like I need to rename some files.

**Comment by profucius** [comment]
Just had this issue, using -WorkingDirectory resolved it for me.

For anyone who might also be running into another related issue I had, where the global script also has certain symbols that Playnite isn't accepting, you can make a symbolic link of the folder in question (e.g. beside the original folder) and rename the symlink without the symbols, then use that path as the WorkingDirectory and it will work perfectly.

Looking forward to Playnite11 which may resolve all of this entirely.
