### ISSUE TITLE
fix ROM filenames based on metadata

### ISSUE THREAD

**Issue by gitzxcvb** [JosefNemec/Playnite#2253]
1. import metadata from a source (IGDB for example) and applying changes to the ROM files
2. button to fix name of file(s) based on the metadata imported

**Example:**
1. added ROMs for NES using emulator, one of them with filename "ff1.nes"
2. searched for metadata on IGDB and added correct data and name "Final Fantasy"
3. use new feature to fix filename: filename (and image path in Installation section) changes to "Final_Fantasy.nes"

**Comment by JosefNemec** [comment]
There's no way we can link names like `ff1.nes` with appropriate IGDB entry.

ROM import will be in general improved via #653

**Comment by gitzxcvb** [comment]
Hi, I guess I couldn't explain correctly.

The idea is not to link names to IGBD.

The idea is that once your data is clean and updated, you have a button to export the NAME of the game to the FILENAME.
Basically, the filename instead of being "ff.nes" would change to "Final_Fantasy.nes"

This functionality would organize all files easier. Would you consider it?

**Comment by JosefNemec** [comment]
That's should be imho done as an extension, since I don't see many people using this. SDK should already have everything needed for this.

**Comment by pcastela** [comment]
hey, so I have created an extension as you suggested. Thanks for the help and keep up the great work 👍 
https://playnite.link/forum/thread-583.html
