### ISSUE TITLE
Steam XBox Controller driver causes fullscreen d-pad to move two sqaures

### ISSUE THREAD

**Issue by TurboTim** [JosefNemec/Playnite#2254]
If I enable Steams XBox controller driver then in Playnite fullscreen the dpad moves two album covers for each press not one.  This issue goes away if I disable Steam controller driver.

**Comment by JosefNemec** [comment]
How is this an issue in Playnite if it's caused by 3rd party app? If you are simulating additional inputs with that driver, then you'll get duplicated inputs.

Playnite itself already handles XInput devices on it's own.

**Comment by TurboTim** [comment]
I am not simulated duplicating inputs using Steam at all, I am simply turning on their driver in replacement of the stock Windows driver for XBox pads.

**Comment by TurboTim** [comment]
![image](https://user-images.githubusercontent.com/2226767/107562842-3dde0300-6bd8-11eb-8dba-e680eec8934a.png)

I think Playnite's XInput handling somehow conflicts - I expect I am not the only one who wants to use Steam's driver and also Playnite full-screen.

**Comment by TurboTim** [comment]
Figured it out, apologies, I was unintentionally duplicating input as you suspected.  It actually turned outs that with Steam controller "Desktop Configuration" enabled it was simulating an arrow keyboard button press on the dpads (and joystick as mouse etc), so this along with the XInput handling in Playnite must account for the double input.  Disabling Steam controller "Desktop Configuration) fixed the issue so thats useful to know.
