### ISSUE TITLE
Minimal allowed width for List view columns

### ISSUE THREAD

**Issue by dohomin** [JosefNemec/Playnite#2257]
**Describe the bug**
I used to have this column. While adding games over several days, this column went missing. 
In this picture, you can see that the features column is selected yet nowhere to be seen: https://i.imgur.com/Phmm9Y1.png

**To Reproduce**
Sadly absolutely no clue. My uneducated guess would be that some game has had a faulty feature list imported that the program can't handle. Tried de-selecting and re-selecting the feature-column, starting playnite in safe-mode and launching with a different theme - all of which didn't help.

**Screenshots**
Same as above: https://i.imgur.com/Phmm9Y1.png

**Diagnostics ID**
7507c96f-1d33-4783-b272-1b53fe28ce2a

**Comment by dohomin** [comment]
Solved it completely by accident. Apparently you can lower the column-size by dragging to basically 0, essentially hiding it. 
Playnite: https://streamable.com/gwrryx
Excel: https://streamable.com/vhy2cj (column always visible even at size 0)

I guess this would be a feature-request now.

**Comment by JosefNemec** [comment]
Fixed in devel.
