### ISSUE TITLE
Requesting SNES emulator - ares

### ISSUE THREAD

**Issue by karehaqt** [JosefNemec/Playnite#2258]
Please could you add ares to Playnite if possible.  ares is made by Near aka byuu who is the creator of bsnes and higan, he has come out of retirement to work on emulation again.  ares is basically a fork of higan as the latter was given to the community by Near when he retired, but he wanted to work on it again and make a much easier to use emulator as higan is quite unweildy for some users.

https://ares.dev/

**Comment by JosefNemec** [comment]
If the emulator supports launching ROM files via cmdline, then you can already add it manually <https://github.com/JosefNemec/Playnite/wiki/Adding-new-emulator>

**Comment by JosefNemec** [comment]
Done in 10.10
