### ISSUE TITLE
"--start" only works if playnite is already running

### ISSUE THREAD

**Issue by tadly** [JosefNemec/Playnite#2259]
Using "--start <gameid>" does not work if playnite isn't already running.

I use homeassistant to automate the process of starting a game:
1. Turn on pc
2. Wait for pc to be online
3. Send command to start game with `Playnite.DesktopApp.exe --start <gameid>`

This currently requires me to monitor the system for running processes and verify that Playnite has successfully started through auto-start before sending the `--start` command.

If playnite were to start in case it isn't already running, it would smooth out the process big-time :)

**Comment by JosefNemec** [comment]
Weird, you can use `playnite://playnite/start/<gameid>` URI until this is fixed.

**Comment by tadly** [comment]
oh that's an option as well? Cool thanks :)

**Comment by JosefNemec** [comment]
Fixed in devel9.
