### ISSUE TITLE
Crash when typing then selecting category

### ISSUE THREAD

**Issue by KipThorne** [JosefNemec/Playnite#226]
Hey, first of all thanks for your amazing works Josef.

I just want to report a small bug : if I type something in the "Categories" field (in the "Edit Game Details" panel) and changing my mind by clicking on the three dot to select a saved category, Playnite crashes.

Zipped diag attached
[categoryIssue.zip](https://github.com/JosefNemec/Playnite/files/1402206/categoryIssue.zip)

**Comment by JosefNemec** [comment]
Released in 2.8
