### ISSUE TITLE
Can't find game on IGDB, although game is available on the website

### ISSUE THREAD

**Issue by poisonborz** [JosefNemec/Playnite#2260]
**Describe the bug**
Was trying to add a game, Flipon - https://www.igdb.com/games/flipon
When I was trying to download metadata, the search did not turn out any search results.

The game has no ratings on IGDB - it's maybe possible that the API doesn't list this game somehow?

**To Reproduce**
- Search for game "Flipon"
- No results, although game exists in IGDB.

**Comment by JosefNemec** [comment]
Fixed, it was a cache issue on backend.
