### ISSUE TITLE
Desktop Theme Selection Improvement

### ISSUE THREAD

**Issue by ricedaddy7** [JosefNemec/Playnite#2262]
Currently to change the desktop theme you open settings, and select appearance to show a theme selection menu. It would be quicker to, in desktop mode, change your theme in the topmost settings menu.
![theme](https://user-images.githubusercontent.com/32589145/108088570-9e40ca80-7046-11eb-9e9f-5a9fa4805fdf.png)

**Comment by JosefNemec** [comment]
I disagree. Theme change is not something that you do very often and therefore doesn't make much sense to have it there. Especially when main menu is getting really crowed already. Plus it also requires application restart.
