### ISSUE TITLE
Have to reinstall Playnite every time I want to open it

### ISSUE THREAD

**Issue by BenRobart** [JosefNemec/Playnite#2265]
**Describe the bug**
If I want to open Playnite I have to reinstall it - Otherwise, clicking the .exe shows it running briefly in task manager, then closing again. Nothing seems to get registered to logs.

**To Reproduce**
Attempt to open Playnite

**Screenshots**
N/A

**Diagnostics ID**
46712fbe-5fa2-48f9-94c5-a1f8ba9d0a8d

**Comment by JosefNemec** [comment]
Please delete `%appdata%\playnite\playnite.log`, reproduce the issue again and upload that file before re-installing. Thanks

The log in diag package rolled over and is only full of metadata download information, I need the log right after the issue happened.

**Comment by BenRobart** [comment]
No log is generated when the issue occurs - I run the .exe, the process shows in task manager briefly, then disappears again.

I'm not able to get a diag log from after it happens as the only way of getting into the menu for diagnostics is to reinstall, as I'm otherwise unable to open the client.

**Comment by JosefNemec** [comment]
If there's no log, then it's caused by some 3rd party. For example RivaTuner has been know to cause issue if you use older version: <https://github.com/JosefNemec/Playnite/wiki/Known-Issues#crash-on-startup>

**Comment by BenRobart** [comment]
I don't believe it's caused by a third party application - Reinstalling Playnite fixes it every time without fail (until I fully close it down again); it works for one launch then stops working again. I don't have RivaTuner installed, and I've tried disabling GPU acceleration. 

The bug has only started occurring since I updated to 8.11 a few days ago; previously I was on a version from around a year ago, and the bug never occurred until I updated.

**Comment by BenRobart** [comment]
I've managed to find these two logs in Event Viewer:

```
Faulting application name: PlayniteUI.exe, version: 4.64.0.18959, time stamp: 0x5c1a1010
Faulting module name: KERNELBASE.dll, version: 10.0.19041.804, time stamp: 0xb610d74d
Exception code: 0xe0434352
Fault offset: 0x0012a8b2
Faulting process id: 0xdbc
Faulting application start time: 0x01d70900978f0eb5
Faulting application path: C:\Users\Ben\AppData\Local\Playnite\PlayniteUI.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: fe358e9c-aa63-4d9c-af09-1069eed71695
Faulting package full name: 
Faulting package-relative application ID: 
```
and
```
Fault bucket 1769041328914916204, type 1
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: PlayniteUI.exe
P2: 4.64.0.18959
P3: 5c1a1010
P4: KERNELBASE.dll
P5: 10.0.19041.804
P6: b610d74d
P7: e0434352
P8: 0012a8b2
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERC28F.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERC2EE.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERC30E.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERC30E.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERC32F.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_PlayniteUI.exe_231b688c2dcb3d9b18f0dd1a7b7a5ce02bbd27b_21114931_df17e7bb-86ef-4f4b-ac42-0cb918de22a0

Analysis symbol: 
Rechecking for solution: 0
Report Id: fe358e9c-aa63-4d9c-af09-1069eed71695
Report Status: 268435456
Hashed bucket: 7235289343e777d4588ce5b742f5636c
Cab Guid: 0
```

**Comment by JosefNemec** [comment]
There's nothing in that update that could cause this. Also, don't use `PlayniteUI.exe`, but `Playnite.DesktopApp.exe`. `PlayniteUI.exe` is from very old version and it's not used anymore. It was kept in some updates for backwards compatibility reasons only.

**Comment by BenRobart** [comment]
Yep, was just in the middle of writing out a comment as you posted that! The shortcut I had leads to PlayniteUI.exe, but Playnite.DesktopApp.exe works with no issue.
