### ISSUE TITLE
Gameselection event not firing with F2 / F3 (LB / RB) in details view in fullscreen app

### ISSUE THREAD

**Issue by joyrider3774** [JosefNemec/Playnite#2268]
**Check for existing issue**
None

**Describe the bug**
When using F2 / F3 (or LB / RB on gamepad) to switch games in game details section in the fullscreen app (not main game selection) OnGameSelected never fires 

**To Reproduce**
Create simple plugin like this to show game name selected in ongameselected event, goto game details in fullscreen app and goto next previous game -> no gameselected will ever fire -> no messagebox is shown with this script
```
function global:OnGameSelected()
{
	param(
		$arguments
	)
	 if ($arguments.NewValue.Count -eq 1) 
     {
		foreach($game in $arguments.NewValue)
        {
			$PlayniteApi.Dialogs.ShowMessage("OnGameSelected Fired for " + $game.Name, "")
        }
	}
}
```

**Screenshots**
see video here :
https://youtu.be/IXFlBMx79f8

**Comment by JosefNemec** [comment]
Fixed in devel9.
