### ISSUE TITLE
Prioritize playtime for supported libraries option not working

### ISSUE THREAD

**Issue by loficat** [JosefNemec/Playnite#2269]
**Check for existing issue**
Please use issue search in the repository if the bug is something really obvious there's a high change it was already reported.

**Describe the bug**

**To Reproduce**
If it's not clear from the description how to reproduce the issue please add clear steps to reproduce the behavior.

**Screenshots**

**Diagnostics ID**
Please generate diagnostics package from "About Playnite" menu and attach identifier you received. If the issue is a crash bug, you can generate diag. package directly from crash dialog.

**Comment by darklinkpower** [comment]
Please provide the information mentioned in the template  and anything that might be useful. Issues like this with no information don't help to solve issues.

**Comment by loficat** [comment]
I apologize for not writing a more verbose description. Within Playtime settings on the General tab, selecting the "Prioritize play time for supported libraries" option doesn't work. I've checked titles I've played via multiple libraries (e.g., Epic, GOG, Humble, itch.io, Origin, Steam, Uplay, et al). The "Time Played" and "Last Played" fields are incorrect.  For some titles, the "Last Played" field will contain data corresponding to opening it from Playnite, but the "Time Played" field remains empty (displaying the "Not Played" value). Deselecting this option and restarting Playnite doesn't appear to impact the values. Thank you.

**Comment by JosefNemec** [comment]
Play time import is currently only supported for Steam and Origin libraries.

**Comment by PescheHelfer** [comment]
I can confirm this is not working correclty, also not for steam. Some titles are imported correctly, others (Steam titles) appear as "not played" unless you launch them from Playnite, but then only the time played from Playnite is shown.

**Comment by JosefNemec** [comment]
@PescheHelfer  Steam will not return play time via its API if certain parts of your profile as set to private, either make them public or provide API key of your account in Steam integration settings.

**Comment by PescheHelfer** [comment]
Thanks for your reply, but my Steam profile is full public. An example were the times are not being downloaded is mindustry. I have 89 hours in Steam, but 0 hours in Playnite:
![Screenshot](https://user-images.githubusercontent.com/8842081/164946535-61ef77d9-0494-4a82-ae4d-858a8e14a07b.png)
.
![Settings](https://user-images.githubusercontent.com/8842081/164946692-662ae0da-d3bf-43e2-a982-04d04202a7ed.png)

Could there be anything else I am doing wrong? I have also refreshed the library and downloaded the metadata multiple times.

Thanks for your help.

**Comment by darklinkpower** [comment]
@PescheHelfer You need to enable Private Account and enter an API key in the plugin settings. The method the plugin uses for for accounts without configuring the api key is different and it doesn't obtain Playtime that way.

**Comment by JosefNemec** [comment]
@darklinkpower That's false. We use the same method (and API) for accounts with or without API key. The only difference is what API key is used, for public accounts we use our own key.

**Comment by darklinkpower** [comment]
> @darklinkpower That's false. We use the same method (and API) for accounts with or without API key. The only difference is what API key is used, for public accounts we use our own key.

I don't know how the api used for public account works, I just checked how the plugin works internally:

1. If the account is not private, it uses the `ServicesClient.GetSteamLibrary` method: https://github.com/JosefNemec/PlayniteExtensions/blob/5120b0a988ffce0021b9612d053b86b2a4aeff27/source/Libraries/SteamLibrary/SteamLibrary.cs#L397-L404

2. Then a request is made to the api used for public accounts `http://.../.../steam/library/76561198025294991`: https://github.com/JosefNemec/PlayniteExtensions/blob/5120b0a988ffce0021b9612d053b86b2a4aeff27/source/Libraries/SteamLibrary/Services/SteamServicesClient.cs#L23-L29

The API returns the `Games` array from the `GetOwnedGames` steam web api endpoint, but the data is incomplete and missing playtime and other data:

![image](https://user-images.githubusercontent.com/1389286/165047977-547ecce7-053a-42ba-bd01-2dfcc826a6bb.png)

For comparison, here's the `GetOwnedGames` response, the same used when the api key has been configured

![image](https://user-images.githubusercontent.com/1389286/165048334-30fc72c7-1654-4dea-94d8-fe9eddf1e58c.png)

**Comment by JosefNemec** [comment]
It means you have some settings to set to private. I just tested it with multiple accounts and it works properly if the account is public. Keep in mind that even option like `Always keep my total playtime private even if users can see my game details.` has to be turned off, which it clearly isn't in @PescheHelfer 's case.

**Comment by darklinkpower** [comment]
Oh right. Then the issue is that the api only returns all the data, including playtime, if the api key owner is the same one as the account you are checking right? Sorry, I had seen that before but I totally forgot about that.

**Comment by JosefNemec** [comment]
All API key does in this case is give you access to private information, that's why it's necessary to use it for private accounts.

Our backend (used when not using your own API key) uses shared API key from my Playnite test account, which obviously can't access other people's private information.

**Comment by PescheHelfer** [comment]
> It means you have some settings to set to private. I just tested it with multiple accounts and it works properly if the account is public. Keep in mind that even option like `Always keep my total playtime private even if users can see my game details.` has to be turned off, which it clearly isn't in @PescheHelfer 's case.

Oh boy, how could I have been so blind! I haven't seen that checkbox, even not after I have taken the screenshot. Embarrassing,  like not seeing the bottle of milk in the fridge :( Well, anyway, that was it, after unchecking that option, playtime is synchronized perfectly fine, now, thanks a lot for pointing me in the right direction!
