### ISSUE TITLE
News feed support

### ISSUE THREAD

**Issue by ghost** [JosefNemec/Playnite#227]
Hey is it possible that you get some news about the game like in the steam client instead of the shop site?

**Comment by clintonbale** [comment]
Added a "News" link to the details panel (#231). A simple fix until a "Recent News" section can be added.

**Comment by JosefNemec** [comment]
We are most probably going to use news data provided by IGDB since we already integrate it in some fashion.

**Comment by JosefNemec** [comment]
I was planning to use IGDB to get aggregated news, but they no longer provide that feature (some issues with EU laws). And so far I was unable to find and alternative with API access.

So this is postponed indefinitely unless somebody comes up with source that we could take news from.

**Comment by Autus** [comment]
In regards to aggregated news for games, I've found that a lot of developers choose to release news on their products via their own network (company website, Twitter, Medium, etc). Steam does provide an RSS feed for titles it currently hosts, but anything outside of the Steam platform would most likely have to be manually added via a separate RSS feed. As such, I'd like to suggest the following:
- Add an RSS tab to the Edit Game Details screen. This would include an input box for the direct RSS feed url and a textarea form for JSON input to format the RSS contents.
- Setting for displaying the Description block, the RSS block, or both.
- Setting for default JSON formatting. Adding JSON to the Edit Game Details RSS tab would overwrite the default setting.

Other things that could potentially be useful/neat:
- Scrolling bar at top/bottom of screen that displays article titles with the game icon next to each scrolling title.
- Dedicated page for consolidating all news from RSS feeds, organized by published date.
---
Edit: After a bit of digging, I found this guy's code for finding the relevant RSS feeds for the games in your Steam library - https://github.com/bendodson/Steam-RSS. Could be a good reference or something.

**Comment by JosefNemec** [comment]
Removing from Playnite 9 milestone. I haven't found a good news source that would cover majority of people's libraries and I don't think it's worth implementing this if it will only work for games from a specific library (Steam specifically in this case). We would end up in a similar situation as with game icons, people complaining that not all (majority) games have news feeds.

I will reevaluate this in Playnite 10, most likely adding some plugin support for this to be supplied by 3rd party extensions rather then built-in feature. Unless we find some reliable news feed source.

**Comment by JosefNemec** [comment]
Closing per my previous comment. There's no reliable source with API access that we could use for this and cover most of games out there.
