### ISSUE TITLE
Can`t run custom script

### ISSUE THREAD

**Issue by ycodryn** [JosefNemec/Playnite#2272]
I`m trying to run a script that will change the freq of gpu for individual games but I have this error: the term C:\Program Files\NVIDIA Corporation\NVSMI\nvidia-smi.exe is not recognized, at <ScriptBlock>,<No file>: line 2

**Comment by darklinkpower** [comment]
What's the script? Can you share a screenshot?

**Comment by ycodryn** [comment]
Sure here it is for minimum clock: PowerShell
powercfg /s 381b4222-f694-41f0-9685-ff5bb260df2e
C:\Program Files\NVIDIA Corporation\NVSMI\nvidia-smi.exe -i 0 -pl 108

and when a game is started: 

powercfg /s 7f1988c7-5f9a-4eb8-b1ac-f1871ddb18ef
C:\Program Files\NVIDIA Corporation\NVSMI\nvidia-smi.exe -i 0 -pl 280

**Comment by JosefNemec** [comment]
Please read this page: <https://github.com/JosefNemec/Playnite/wiki/Game-scripts>
