### ISSUE TITLE
games do not appear on the view screen after adding them 

### ISSUE THREAD

**Issue by ilya-iqbal** [JosefNemec/Playnite#2274]
**Check for existing issue**
Please use issue search in the repository if the bug is something really obvious there's a high change it was already reported.
![Capture](https://user-images.githubusercontent.com/79708662/109316679-26e01780-784c-11eb-95a2-e0108cc0a7e4.PNG)
![Capture](https://user-images.githubusercontent.com/79708662/109316753-3a8b7e00-784c-11eb-9319-3d1b43051e17.PNG)

i have this issue where games do not appear in the view screen after adding them.
however the games appear to be recognized by the app and still listed in it's database.i would also like to mention that the games when added they seem to appear in the view screen when fullscreen mode is on!

**Comment by JosefNemec** [comment]
You have filters enabled preventing those games from showing up.
