### ISSUE TITLE
Can't automatically Import Xbox 360 XBLA games

### ISSUE THREAD

**Issue by Start-Cart** [JosefNemec/Playnite#2275]
When Importing Xenia Xbox 360 games by scanning automatically, Playnite doesn't show the games on the Import list. These files don't have file extensions which may affect this, but Launchbox doesn't have this issue.

The games relating to this issue are Xbox Live Arcade games (XBLA) such as 3D Ultra Mini Golf 2, 1942 Joint Strike, etc.

**Comment by Kaederoth** [comment]
I got add XBLA games using an space as compatible formats in compatible file types.
![image](https://user-images.githubusercontent.com/53636750/126369524-7995ecf0-b960-4bab-9979-5e25b3bc5f48.png)

Tested with NeoGeo Battle Coliseum and Daytona USA. All of them detected without issues.

**Comment by JosefNemec** [comment]
Done in devel9.
