### ISSUE TITLE
Fullscreen Mode with Second Monitor

### ISSUE THREAD

**Issue by Zaine6** [JosefNemec/Playnite#2281]
Fullscreen mode does not open on the primary monitor when having more then one monitor.

**Comment by JosefNemec** [comment]
You can change target display in the settings. Playnite 9 also adds option to always force to primary display.

**Comment by Zaine6** [comment]
@JosefNemec where can I find the option in settings, do not see it in the current release.

**Comment by JosefNemec** [comment]
![image](https://user-images.githubusercontent.com/3874087/110237772-0f84e680-7f3e-11eb-8dfe-d953402251ac.png)
