### ISSUE TITLE
Detailspane:Menu items missing when game cover imageheight is set too low

### ISSUE THREAD

**Issue by kristheb** [JosefNemec/Playnite#2283]
Issue in the details pane. depending on the settings set in "_Appearance, Details View, game cover image height_", not all menu items are displayed or accessible.

Menu on item in sidebar, all entries visible
![Screenshot (2)_LI](https://user-images.githubusercontent.com/28502250/110840957-a38be080-82a5-11eb-8c99-864fb27c614b.jpg)

Menu with missing entries in details pane
![Screenshot (3)_LI](https://user-images.githubusercontent.com/28502250/110841214-e948a900-82a5-11eb-81b6-522fa3060aad.jpg)

Shown here with default theme, happens in other themes too,

**Comment by JosefNemec** [comment]
Fixed in devel9.
