### ISSUE TITLE
Authentication webview is broken, only refreshes screen when window is resized

### ISSUE THREAD

**Issue by kryptot7** [JosefNemec/Playnite#2285]
**Describe the bug**
The webview window that is used to authenticate with third-party libraries is broken:
* It only refreshes its display when the window is resized. Interacting with the web interface works, but you must resize the window to see your changes.
* This often results in a black screen. Resize the window repeatedly to get something to show up.
* I tried this with Steam and Epic Games login and the bug happened with both.
* Also, the webview does not seem to be recognized as a secure environment. On the Epic Games page, Login with Google refuses to work (see #2212) and Epic Games login gives me a ridiculously long and difficult CAPTCHA which is near impossible to complete given the graphical glitches. 

**To Reproduce**
* Goto Playnite settings
* Libraries > Epic > Authenticate button
* You should see a login prompt, but instead you will likely see a black screen
* Resize it and the login prompt will show up but not be visually responsive

**Screenshots**
What you see when you open the authenticate window
![image](https://user-images.githubusercontent.com/30781325/111262762-2771ff80-85fb-11eb-9d01-933cfdb4b8c2.png)

What happens if you maximize the window...note that the duplicate buttons in the middle of the screen do not appear at first. They appear when I mouse over the area they are supposed to be located in. We see their "hover" sprites drawn in the correct place.
![image](https://user-images.githubusercontent.com/30781325/111262832-46709180-85fb-11eb-8ccd-817f0dea3c17.png)

Unmaximize and then maximize again...the window fixes itself this time. Notice how the buttons are in the middle of the screen, the same place that their clones erroneously appear in the last screenshot
![image](https://user-images.githubusercontent.com/30781325/111262977-833c8880-85fb-11eb-8d0d-42fdf9bee9aa.png)

User has to solve ten of these gosh darn puzzles in a row
![image](https://user-images.githubusercontent.com/30781325/111262467-b0d50200-85fa-11eb-8522-3b10a35bd39c.png)

NOTE: I have Bitdefender Antivirus Plus installed and running.

**Diagnostics ID**
Please generate diagnostics package from "About Playnite" menu and attach identifier you received. If the issue is a crash bug, you can generate diag. package directly from crash dialog.
3f4c1d8b-3df7-4d2c-a5c7-85809078d6ae

**Comment by JosefNemec** [comment]
Do you have Intel GPU? This has been know issue with bad Intel drivers.

**Comment by JosefNemec** [comment]
https://github.com/JosefNemec/Playnite/wiki/Known-Issues#integration-logins-dont-work-show-only-whiteblack-screen

**Comment by kryptot7** [comment]
Oh, that must be it. I have that exact graphics card! Thanks for the prompt response.

**Comment by JosefNemec** [comment]
Closing then, nothing I can do about it, Intel must fix in the drivers.

Disabling hardware acceleration in advanced settings will work around this issue, but may result in poor UI performance.

**Comment by SuperFurias** [comment]
I had the same issue. with an RTX 3060TI
i was literally unable to install the application because every time everything just.. freezes.
i was able to fix by disabling (with a lot of troubles) hardware acceleration. and now everything works perfectly fine, even if its a bit.. slow.
