### ISSUE TITLE
JavaScript Plugin support

### ISSUE THREAD

**Issue by Brendanp01** [JosefNemec/Playnite#2286]
I would like to start implementing JavaScript support for plugins. I plan on using Microsoft ClearScript to embed the V8 JavaScript engine into the app. Then create a plugin API (or modify existing API) to work with JavaScript.

**Comment by JosefNemec** [comment]
There are no plans adding additional scripting runtime. In fact, I'll be removing IronPython support when switching to new .NET runtime.

Support multiple scripting languages is way too much effort (code, documentation, support etc.) and it's imho not worth it. PowerShell will be the only supported scripting runtime going forward.
