### ISSUE TITLE
Failed to import games from Twitch

### ISSUE THREAD

**Issue by shangles** [JosefNemec/Playnite#2287]
**Check for existing issue**
No existing Open issue found

**Describe the bug**
This morning when trying to Update Game Libaries I received the following error message for the Twitch library:
Failed to import games from Twitch
The remote server returned an error: (400) Bad Request.

In Playnite I went to Settings > Libraries > Twitch and it shows "Requires authentication"
I clicked the Authenticate button and clicked OK to the window telling me that Twitch client would now open (I'm using the Windows 10 client available in the Microsoft Store)
It shows me already logged in, but I logged out and back in again.
In Playnite, there's a secondary window that says "Waiting for user to sign in, please close this when you're done..."   I clicked OK on that windows.
Playnite checks authentication status and it goes back to "Requires authentication"
Trying to update the Twitch Library in Playnite then shows the same 400 error.

Not sure if this is on Twitch's end or Playnite, but felt I should report here.

**To Reproduce**
Attempt to Update Game Library for Twitch

**Diagnostics ID**
47b7a1e2-2c04-4cf9-bc7f-fecfa0f8af8b

**Comment by JosefNemec** [comment]
Not sure it's worth fixing since Twitch itself is recommending users to migrate to Amazon Games client.

**Comment by shangles** [comment]
Good point.  I forgot about that.  I've disabled the Twitch library and kept my Amazon Games library intact, which is still working.  Sorry to bug you :)   I love this app!

**Comment by JosefNemec** [comment]
Closing, I will be removing Twitch plugin in Playnite 9. The source code will be still available, if somebody really needs to use it, they will have to fix it themself.
