### ISSUE TITLE
Authenticating Epic Account, login page cannot detect captcha completed 

### ISSUE THREAD

**Issue by t3pfaffe** [JosefNemec/Playnite#2288]
### **Reproduction Steps:**
- Use latest Playnite (8.11).
- Authenticate Epic Game Store Account.
- Fill in relevant Email and Password.
- Complete Captcha correctly.
- Press Sign in.
- **Observe response "You must complete Captcha", doesn't let you log-in**
### **Screenshots:**
![Demonstration from last occurrence](https://user-images.githubusercontent.com/16065962/111860971-29043600-8921-11eb-9b2b-dcebdd3280f5.gif)

### **Diagnostics ID:**
`9e80d175-3c5b-4fed-96d5-1b2d7fe46f34`
-------------------------

**Comment by JosefNemec** [comment]
The login form we use is just broken on Epic's side. I tried updating web view component in Playnite: it doesn't work. I tried login from a real browser: it doesn't work.

Not much I can do about it other then completely reworking sign-in process.

**Comment by JosefNemec** [comment]
Fixed in 8.12
