### ISSUE TITLE
Ability to add Custom filters as tabs or quick toggle

### ISSUE THREAD

**Issue by minifluff** [JosefNemec/Playnite#2289]
I'm hopping the ability will be added to be able to add Custom Filters to these two locations.
![Capture](https://user-images.githubusercontent.com/81107462/111915949-708cde00-8a57-11eb-8284-5850c5c5a0dc.PNG)
![Capture2](https://user-images.githubusercontent.com/81107462/111915951-74206500-8a57-11eb-9e7f-e462906c275f.PNG)

My main reasoning for this I use my game PC in multiple was one for play local games and another for playing Arcade game on my arcade. To be able to have a spot in both these locations to show just my arcade games would make things much easier as the arcade can't easily access the filter options.

**Comment by JosefNemec** [comment]
Duplicate to #590
