### ISSUE TITLE
Drop-down menu for custom categories

### ISSUE THREAD

**Issue by KipThorne** [JosefNemec/Playnite#229]
It is already possible to hide/show games by typing the custom category in the "Category" field. But with complex category name or with a lot of them, it's not very easy. I suggest a drop-down menu to click on categories we want to hide or show.

**Comment by JosefNemec** [comment]
Can you please add more detailed use case for this?

**Comment by KipThorne** [comment]
For example, I have more than 10 categories : "Reviewed : good", "Reviewed : bad", "Reviewed : average", "To review", etc. So I have to remember each one of them then type the correct name of categorie (because if I just write "Review", all categories will be displayed). I'm aware that I can click on categories in the game detail panel but before that, I need to find a game with the categorie I want.

It will be more easy to have a drop down menu to see all of categories and just click on it. There is same problem with Tag field.

**Comment by JosefNemec** [comment]
I see, it will be implemented in #135
