### ISSUE TITLE
Remember collapse/expand platform sections in details view

### ISSUE THREAD

**Issue by silverlays** [JosefNemec/Playnite#2290]
Hi,

before, a little of context: I'm using since the beginning the "details view" grouped by "platform".

Before the major update of the PlayNite core months ago, when I collapse a platform section (to hide his content), this was saved between sessions, but now, it don't save it anymore and at every launch, all sections are expanded by default.

Finally, my ask is pretty simple: Can you save again the collapse/expand state of each section just as it was before the major update please ?

Thank you in advance 😊

PS: I'm french user, sorry if i made grammatical mistakes.

**Comment by JosefNemec** [comment]
This seems to be working just fine for me. Please attach all information requested in issue report template.

**Comment by silverlays** [comment]
**Describe the bug**
Before the major update of the PlayNite core months ago, when I collapse a platform section (to hide his content), this was saved between sessions, but now, it don't save it anymore and at every launch, all sections are expanded by default.

**To Reproduce**
Launch PlayNite, click on a platform's section to collapse it. Close PlayNite and launch it again.

**Screenshots**
This is what I do on a session for example =>
![before](https://user-images.githubusercontent.com/17464661/112478881-ba860480-8d74-11eb-8705-52bc9673bfa1.jpg)

This is what it looks like after i completely close PlayNite and have it relaunched
![after relaunch](https://user-images.githubusercontent.com/17464661/112478874-b9ed6e00-8d74-11eb-8154-5b2d606c00bb.jpg)

**Diagnostics ID**
7b47b23f-3dfd-46ad-ad14-cbc41c13b0de


Thanks in advance and good luck 🤞

**Comment by JosefNemec** [comment]
It's because the theme you are using was not updated to support save state of game groups. You need to ask theme author to update it or use different theme.
