### ISSUE TITLE
Humble autentification

### ISSUE THREAD

**Issue by wigglywag** [JosefNemec/Playnite#2291]
The authentication to Humble with google is recognized as not secure. I might be too dumb to fix it myself idk, plz help

![Screenshot 2021-03-23 145057](https://user-images.githubusercontent.com/81259736/112202534-e031d300-8be7-11eb-8c3e-223ce4908586.png)

no crash report available sadly.

with love
Wigglywag <3

**Comment by JosefNemec** [comment]
Are you on 8.12? I updated web view component in that version.

**Comment by wigglywag** [comment]
> Are you on 8.12? I updated web view component in that version.

yes i am. Sorry, i should have specified first

**Comment by JosefNemec** [comment]
Fixed by 81f004f0aeedd4d241f23f9e7aee35de2d9bae5a
