### ISSUE TITLE
Enhancement Request: Add ToggleButtonEx for Fullscreen themes

### ISSUE THREAD

**Issue by davidkgriggs** [JosefNemec/Playnite#2292]
Like the ButtonEx already in place could there be a ToggleButtonEx added? I have been playing around with a theme and can turn things on and off with a Toggle Button using keyboard input, but there is a lack of Controller input support for the Toggle buttons. Adding this would allow more robust themes with options that could be turned on and off easily on the fly.
I can send you an example theme to show you what it could add feature wise. 
Thanks

**Comment by davidkgriggs** [comment]
To add to this there is also the option of adding the enter key as support for the ComboBoxEx. Currently it accepts a mouse click or A on xinput but not the keyboard enter key, is there a reason for this?

**Comment by JosefNemec** [comment]
Done in devel9_2
