### ISSUE TITLE
--startfullscreen argument is not switching a running instance of playnite desktop to full screen

### ISSUE THREAD

**Issue by maxwell-01** [JosefNemec/Playnite#2293]
**Describe the bug**
A command line argument '--startfullscreen' should switch a running desktop instance of the app to a full screen one as described in the docs here: https://playnite.link/docs/playnite8/manual/cmdlineArguments.html
This does not work for me. The shortcut will open playnite in full screen if it is not running, but it will not switch from desktop to full screen. I've also tried running as admin without any luck.

**To Reproduce**
Open playnite in desktop mode. Create a shortcut to the playnite exe and add '--startfullscreen' to the argument. Without playnite running it correctly opens full screen mode. With playnite in desktop mode it does nothing.

**Diagnostics ID**
95a1ae96-9850-4e65-bf9e-7114f285ef93

**Comment by JosefNemec** [comment]
You are using old version (8.8) which doesn't support this argument.

**Comment by maxwell-01** [comment]
That's embarrassing - sorry for the time waste.
