### ISSUE TITLE
GameContext not updated for custom UI in DetailsViewItem when scrolling

### ISSUE THREAD

**Issue by felixkmh** [JosefNemec/Playnite#2295]
**Description**
This is on the current devel9 branch commit 2b7f49e. The GameContextChanged() method for the custom ui integration does not appear to be called appropriately when objects are re-used in the Detail View List. I'm currently fiddling around with a custom ui element for my DuplicateHider plugin, but the GameContext property seems to be outdated (after some scrolling) when I try to integrate my element into the DetailsViewItemTemplate.

Edit:
I noticed that the DataContext is also changed while IsLoaded == false. Maybe in that case GameContextChanged() is not triggered and GameContext is not changed even though the DataContext is? If I subscribe to DataContextChanged event I get the behavior I want, but that is less than ideal because the type of the DataContext is not part of the SDK.

![grafik](https://user-images.githubusercontent.com/24227002/113210624-ba09d400-9274-11eb-867d-001291691c4e.png)

**Comment by JosefNemec** [comment]
Fixed in devel9_2.
