### ISSUE TITLE
[Epic authentication] after logging in, i end up on the account settings page, and not logged in.

### ISSUE THREAD

**Issue by cainy-a** [JosefNemec/Playnite#2296]
**Describe the bug**
When signing in via Epic Games, it does not authenticate correctly but instead just takes me to the epic account settings page.

**Screenshots**
![image](https://user-images.githubusercontent.com/19270622/113313804-83c76580-9303-11eb-85de-1eb6de4ef3c2.png)
![image](https://user-images.githubusercontent.com/19270622/113314928-adcd5780-9304-11eb-8b51-b3eec286c9d1.png)

**Diagnostics ID**
Please generate diagnostics package from "About Playnite" menu and attach identifier you received. If the issue is a crash bug, you can generate diag. package directly from crash dialog.
`f3ef777f-0316-4990-a3d0-d165a6f1514f`

**Comment by JosefNemec** [comment]
Update to latest 8.12 version.

**Comment by cainy-a** [comment]
oh ok thanks

**Comment by TurinTur** [comment]
Here it's a hint: maybe update the links here https://www.playnite.link/download.html !!

**Comment by SaiBork** [comment]
Download page still links to 8.11 even though we're on 8.13 now

**Comment by RSNTM3NT** [comment]
![Screenshot (60)](https://user-images.githubusercontent.com/59945382/158027926-bf259929-06ef-4f70-8368-21803c57ddac.png)
Already installed on the lastest version, but it fails. WTH?
