### ISSUE TITLE
It takes six clicks to sort my current view alphabetically. Would it be possible to save favourite configurations and put a quick toggle at the top of the UI? :)

### ISSUE THREAD

**Issue by citizenc204** [JosefNemec/Playnite#2297]
Hi!

I love PlayNite, and I'm hoping that this isn't too much of a request :)

With respect to the "Sort By" settings, I normally spend my time in two different configurations: "alphabetical list of everything installed", and "last played at the top".

At present it requires six clicks to transition between the two settings, and the menu is very small:

![playnite-sort-displayed-list-by-last-played-decending-order](https://user-images.githubusercontent.com/25515584/113410442-063e3c80-9379-11eb-9454-1f7432ab9871.png)

![playnite-sort-displayed-list-alphabetically-ascending-order](https://user-images.githubusercontent.com/25515584/113410444-06d6d300-9379-11eb-9691-445511811d1a.png)

Could we please have something like this?

![playnite-toggle-buttons-sort-by-favorites](https://user-images.githubusercontent.com/25515584/113410917-1e628b80-937a-11eb-8400-340819771653.png)

**Comment by JosefNemec** [comment]
Duplicate to  #590
