### ISSUE TITLE
Scan Library Folder Exclusions

### ISSUE THREAD

**Issue by oromis995** [JosefNemec/Playnite#2299]
When going to "Add Game>Scan Automatically..." and scanning a folder it'd be cool to be able to set parameters to exclude, such as config.exe files, or UnityCrashHandler.exe files.

Adding the ability to sort the results by the various columns should also be a feature.

I will attempt the upgrade, but I believe this is considerably beyond my capabilities, therefore assume I will not be completing this update.

**Comment by Eloren1** [comment]
Bump
