### ISSUE TITLE
Translations support

### ISSUE THREAD

**Issue by JosefNemec** [JosefNemec/Playnite#23]

**Comment by TheDarocker** [comment]
Highly recommend [OneSky](https://www.oneskyapp.com/) if you haven't found a good crowdsourced translation service yet. Completely free for public projects and works really easily once you get everything integrated into the code itself.

**Comment by JosefNemec** [comment]
Thanks for tip, I will definitively check it out once I get to this.

**Comment by XploitOcelot** [comment]
Any possibility to contribute with an european spanish translation?

**Comment by JosefNemec** [comment]
Once this issue is closed then it will be possible to contribute with translations. I haven't consolidated all texts into one place yet.

**Comment by L1cardo** [comment]
i can help with Chinese translation

**Comment by JosefNemec** [comment]
Released in 3.0
