### ISSUE TITLE
Game time tracking

### ISSUE THREAD

**Issue by trillex** [JosefNemec/Playnite#230]
Ever since Raptr reported it is closing down, the PC platform doesn't really have a decent way to record game time tracking, other than the ones inbuilt into Origin, Steam, GOG et all. 

It'd be super great if this was combined into one platform. I'm a sucker for those kind of stats and if it is possible to import from raptor and export in various formats, the data can be manipulated in a lot of fun ways, maybe even directly in playnite!

**Comment by JosefNemec** [comment]
Dupl. to #120
