### ISSUE TITLE
FS-UAE integration does not work 

### ISSUE THREAD

**Issue by uncleeddie** [JosefNemec/Playnite#2300]
**Integration issues**
If an issue is related to library integrations, use separate [extensions repository](https://github.com/JosefNemec/PlayniteExtensions) to file a report.

**Check for existing issue**
Please use issue search in the repository if the bug is something really obvious there's a high change it was already reported.

**Describe the bug**

**To Reproduce**
If it's not clear from the description how to reproduce the issue please add clear steps to reproduce the behavior.

**Screenshots**

**Diagnostics ID**
Please generate diagnostics package from "About Playnite" menu and attach identifier you received. If the issue is a crash bug, you can generate diag. package directly from crash dialog.

**Comment by uncleeddie** [comment]
I have reported this in the subreddit as well. Integration with the latest version of FS-UAE does not work. Playnite does not automatically recognize FS-UAE. When I manually add it, it has problems with autoscanning games. Also, launching non CD-32 games do not seem to work.

**Comment by JosefNemec** [comment]
Fixed in devel9.
