### ISSUE TITLE
AddCustomElementSupport() adds too many elements

### ISSUE THREAD

**Issue by felixkmh** [JosefNemec/Playnite#2301]
On the devel9 branch. This caused way too many instantiations of CustomElements, especially when the element list was long. Turns out that for each item in the ```ElementList``` in the ```AddCustomElementSupportArgs```, the whole ```ElementList``` is added to the ```CustomElementList```. This is caused by a loop in [ExtensionFactory.cs](https://github.com/JosefNemec/Playnite/blob/2b7f49ec7281f6e38fa29fec187ceec7d8bf930e/source/Playnite/Plugins/ExtensionFactory.cs#L726). Moving the instructions from inside the loop to the outside seems to do the trick.

**Comment by JosefNemec** [comment]
1) Thanks for the report, I'll look into it.
2) I recommend not using devel9 branch for anything until I officially announce that it's safe to use and test. I've already made some breaking changes in a different branch. Just a warning so you don't waste time implementing against something that will change.

**Comment by felixkmh** [comment]
I appreciate the warning. I just couldn't wait to try out the ideas that where floating around in my head for a while. Works pretty nicely so far, so I'll just have to hope not too much will break.

**Comment by JosefNemec** [comment]
Fixed in devel9_2.
