### ISSUE TITLE
Cannot Authenticate Epic Games Store

### ISSUE THREAD

**Issue by mattlokk** [JosefNemec/Playnite#2303]
The Authentication window opens, I enter my credentials and OTP, and then instead of the window auto-closing like it's supposed to it takes me to my account settings.  If I manually close the window at this point, PlayNite still shows "Requires authentication"

**Comment by JosefNemec** [comment]
Make sure you are on latest 8.12 update which fixes Epic auth issues (main menu -> help -> check for updates).

**Comment by mattlokk** [comment]
ok, thank you. I had just re-installed playnite on a new pc and was going through the initial setup wizard. 

might be a good idea to have the first step of the setup wizard be to check for updates.

in any case thank you for the speedy reply

**Comment by JosefNemec** [comment]
Playnite 9 will always download most recent version of integration plugins during first time startup.
