### ISSUE TITLE
Launch Fullscreen Button in Taskbar-Menu

### ISSUE THREAD

**Issue by Rioluuu** [JosefNemec/Playnite#2305]
Add a button to launch the Fullscreen-Mode of Playnite to the jumpmenu of the Taskbar. It could below the games.

![grafik](https://user-images.githubusercontent.com/43097559/114206020-30849100-995b-11eb-9ab5-e141f618238d.png)

**Comment by NoAccount1** [comment]
I think it's a great idea and I also saw a similar feature in GoG Galaxy

![2021-06-03_19h03_06](https://user-images.githubusercontent.com/74969657/120683821-5bdcb580-c49e-11eb-82ce-8ebc1978c426.png)
