### ISSUE TITLE
 fullscrem mode available for all dinput controls

### ISSUE THREAD

**Issue by dashjeep** [JosefNemec/Playnite#2306]
**Integration features**
If a feature request is related to library integrations, use separate [extensions repository](https://github.com/JosefNemec/PlayniteExtensions) to file a request.

**Check for existing issue**
Please use issue search in the repository if your feature request is something really obvious there's a high change it was already requested.

**Describe the solution you'd like**

**Screenshots**
If applicable, add screenshots to help explain requested changes.

**Comment by JosefNemec** [comment]
Duplicate
