### ISSUE TITLE
Failing to Update

### ISSUE THREAD

**Issue by Nannux96** [JosefNemec/Playnite#2307]
Hello, I'm on patch 8.9 and I'm trying to update to the latest one but I keep getting this error message:

![error](https://user-images.githubusercontent.com/82278162/114275721-dac7eb80-9a23-11eb-8d48-bab75e39342e.PNG)

The download bar fills all the way and then the error box instantly pops up, I've tried 4-5 times already with the same result.

Diagnostics ID: 61e05b7f-818d-49ad-8ebc-a7eec5a9ddb2

**Comment by JosefNemec** [comment]
You need to download latest installer manually. It's currently no longer possible to auto-update from 8.10 and older.
