### ISSUE TITLE
Group By Name - sorting

### ISSUE THREAD

**Issue by DE5VERGER** [JosefNemec/Playnite#2309]
Description:
When using the Group By Name option, titles are sorted by the 'Name' field, and ignores the 'Sorting Name' field, leading to them being placed under the wrong letter. Most noticeable with 'The'.

Note: It appears that the 'Sorting Name' parameter is applied _after_ the initial 'Name' sort, as demonstrated in the screenshot. 

To Reproduce:
Give a title a different name and sort name. Apply 'Group By Name' option.

Screenshots:

![Screenshot - 13_04_2021 , 9_09_34 AM](https://user-images.githubusercontent.com/74814999/114522051-e2151200-9c3a-11eb-83b1-17581278975f.png)

![Screenshot - 13_04_2021 , 9_10_06 AM](https://user-images.githubusercontent.com/74814999/114522062-e5100280-9c3a-11eb-864d-ec9df6cd9634.png)

**Comment by JosefNemec** [comment]
Done in devel9.
