### ISSUE TITLE
Epic Games authentication not working

### ISSUE THREAD

**Issue by Kevazy** [JosefNemec/Playnite#2310]
I login as I usually do using my Epic Games account, not through ex. Steam or Google, it takes me directly to the "General Settings" page and nothing happens.
I first had email authentication enabled, same issue occured so I tried switching to Google authentication which was the same.
Then disabled any form of authentication so my login consists of only an email address and password, and guess what? It's still the same.
I also made sure the launcher was updated.

**Comment by JosefNemec** [comment]
Duplicate, please use search next time. There's like 4 of these now...
