### ISSUE TITLE
Toolbar Introduction On Playnite

### ISSUE THREAD

**Issue by Harshit64** [JosefNemec/Playnite#2313]
Toolbar feature
It would be nice to have a toolbar in Playnite.
It would contain apps commonly used by gamers. To name a few to start with would be
Voice chat apps - Discord, Telegram, Teamspeak etc
Virtual LAN apps - Hamachi, Radmin VPN

I want to clear that I am not asking to use these apps without installing. These would be installed on system and can be detected by Playnite.

I think best position would be in the vertical right border of Playnite. It could be summoned between games by pressing maybe caps lock ( I thought this because I don't think any game uses caps lock as a control) and when summoned we could click on any app that is already added and a mini tab would silde from the toolbar where we can control the app. For eg - Connecting and disconnecting on voice chat, typing on telegram, changing settings of virtual LAN etc. This would solved the problem of programs taking all the space on screen and interrupting between games .  Also it would make Playnite one stop for all the gaming. 
Thank you

**Comment by JosefNemec** [comment]
This is what sidebar is for. You can't currently add items to it, but Playnite 9 will allow extensions to add items there and you will be also able to show items from Software Tools there.

**Comment by Harshit64** [comment]
Ok . Thank you for quick reply. Excited for the requested update.

**Comment by Harshit64** [comment]
Also along with the integrations mentioned above some more suggestions would be
Key mapping apps - Keytweak , Joy to key

**Comment by JosefNemec** [comment]
There's not going to be any specific app support. The implementation is generic enough that you can add any application you want.
