### ISSUE TITLE
Bug: Game wouldn't launch due to low disk space and then the game was removed from the library entirely after restarting Playnite via prompt.

### ISSUE THREAD

**Issue by ImaImagineer11** [JosefNemec/Playnite#2314]
As described in the title.  Haven't checked to see if it's reproducible however it is definitely a bug that resulted in loss of data (i.e. Time played).  Fortunately I was able to restore the game entry from a backup.  Great launcher otherwise!

**Comment by JosefNemec** [comment]
If you don't have space on drive where Playnite stores library info, then it will obviously fail since Playnite won't be able to write new library data. Nothing I can do about that.
