### ISSUE TITLE
"Additional filters" not clearing in Fullscreen UI after global "Clear" is pressed

### ISSUE THREAD

**Issue by ImaImagineer11** [JosefNemec/Playnite#2315]
Describe the bug

In Fullscreen mode, when "Additional filters" are applied and then cleared using the global "Clear" button, the menu UI does not update correctly.

To Reproduce

![Step1](https://user-images.githubusercontent.com/75451617/115284276-7808db00-a11a-11eb-8e81-3e4a32a4a3b1.png)

Beginning here, 6 games are correctly displayed with no filters applied.

![Step2](https://user-images.githubusercontent.com/75451617/115284265-75a68100-a11a-11eb-8ecf-bf81b51c0e88.png)

A tag filter is applied via the "Additional filters" --> "Tag" menu.  The filter is correctly applied.

![Step3](https://user-images.githubusercontent.com/75451617/115284268-763f1780-a11a-11eb-829f-098b55d0d563.png)

The global "Clear" button is pressed and the filter is correctly removed, returning to the original display of 6 games.  However, the "Additional filters" text remains red, despite not actually being applied.

![Step4](https://user-images.githubusercontent.com/75451617/115284271-77704480-a11a-11eb-99b7-926df7a6c389.png)

Navigating to the "Tag" menu once again shows the "Controller Preferred" box remains checked, yet it is not applied in the view.

I hope this one has not been previously reported.

Cheers Josef.

**Comment by JosefNemec** [comment]
Fixed in Devel9.
