### ISSUE TITLE
Wrong Button Prompts When Searching for Games in Fullscreen

### ISSUE THREAD

**Issue by coopermf** [JosefNemec/Playnite#2316]
When searching for games in fullscreen mode with Playstation prompts it gives the prompt to press the 'options' button when done but that doesn't do anything. Interestingly R1 seems to end the search but I'm also not clear about what the difference is between 'DONE' and 'Cancel' considering that cancel doesn't clear the search but only backs out of the keyboard input like I would expect when using 'DONE'.

**Comment by JosefNemec** [comment]
"DONE" should close the input and keep selected search string, "Cancel" should close the input and revert to original search string. I'll fix it.

**Comment by JosefNemec** [comment]
Fixed in devel9.
