### ISSUE TITLE
Installing Amazon just opens the Amazon Games Launcher

### ISSUE THREAD

**Issue by shakeyourbunny** [JosefNemec/Playnite#2321]
For reference, I used a stock user interface.

**Check for existing issue**
This specific problem was not found in this tracker.

**Describe the bug**
Clicking on 'install' on an Amazon Games game just opens the launcher and does not install the game nor selects the game in the launcher to install.

**To Reproduce**
Select a game from the Amazon games library, then click on 'install'.

**Screenshots**
![amazongames-install-fails](https://user-images.githubusercontent.com/5352403/115989550-80e02d80-a5ae-11eb-9430-c0cde6fac8d9.PNG)

My guess is that this is not possible with the Amazon Games Launcher?

This example is "The Adventures of Chris" and the game ID is "09fbe8c7-5f5b-4c23-88b7-09aeb2936c7a", but I don't know, if that is the Amazon game app id or not.

**Comment by JosefNemec** [comment]
That's how it works for most clients. Amazon has no support for directly opening game page from external sources.

Please also read issue template carefully, this is not correct repository for this issue.
