### ISSUE TITLE
Application Font Preview

### ISSUE THREAD

**Issue by felixkmh** [JosefNemec/Playnite#2323]
Render each font name using the corresponding font family in the "Application font" setting. This would make choosing a font much quicker, as you would not need to restart Playnite every time you want to see what a font would look like.
![grafik](https://user-images.githubusercontent.com/24227002/116395672-b1c99800-a824-11eb-8f22-0bf46b764891.png)

**Comment by mickaelxd** [comment]
But this way you will need to load every single font at least once, am I right? This feature doesn't decrease performance?

**Comment by felixkmh** [comment]
From what I experienced the fonts only seem to be loaded when opening the drop down menu of that specific combo box for the first time. So in that moment you notice some lag until it opens, yes. But I don't think it affects performance otherwise (except for the increased memory usage), and if you don't open that drop down, it should not make any difference. In my opinion that trade-off is worth it, considering that people won't open it that often anyway.
But maybe there is a way to only load those fonts that are actually in view, so that opening is a little bit faster.

**Comment by JosefNemec** [comment]
Done in devel.
