### ISSUE TITLE
Different versions of ResourceDictionaries used in different Views

### ISSUE THREAD

**Issue by felixkmh** [JosefNemec/Playnite#2328]
On Devel9_2 branch:
Reproduction:
- Make copy of Default Theme, change CheckBox.xaml in copy and in original so they look differently.
- Select copy of the Default Theme as the application Theme.

Example where I set background colors of the checkboxes to red (copy and active theme) and blue (original default theme):
![grafik](https://user-images.githubusercontent.com/24227002/117579681-4a4cfb80-b0f4-11eb-84f5-2900f87785c0.png)

I noticed similar problems with Constants.xaml, FilterEnumSelectionBox.xaml, FilterSelectionBox.xaml, FilterStringSelectionBox.xaml, SearchBox.xaml. Constants.xaml of the active Theme seems to not be available in the Game Edit View, while it is available in the Main View. FilterBoxes and SearchBox uses the Default files in the Main View.

**Comment by JosefNemec** [comment]
I'll be honest I have hard time parsing what's wrong. Please attach screenshots of views that don't inherit changes and also your custom theme.

**Comment by felixkmh** [comment]
One screenshot of that is already provided above. The dimmed part on the right is the main view that does not inherit the changes of the active theme that has red checkboxes. These checkboxes keep the color set in the default theme (blue). And the custom theme is just a copy of the default theme with the checkbox color changed.
[DefaultCopy.zip](https://github.com/JosefNemec/Playnite/files/6448033/DefaultCopy.zip)
Although I fixed some errors where ControlTemplates did not have a TargetType specified, which caused NotSupportedExceptions, but those where only in TopPanel.xaml and ImageHighlightButton.xaml.

**Comment by felixkmh** [comment]
Were you able to reproduce this issue or am I doing something wrong on my end?

**Comment by felixkmh** [comment]
The issues with the other files I noticed while working on this theme [Night-Theme.zip](https://github.com/JosefNemec/Playnite/files/6448117/Night-Theme.zip). If it is placed in the "Default" folder, it looks and works like expected, if placed in any other folder, some things are not working right. Trying to edit a game even crashes the application because a resource from Constants.xaml cannot be found if the theme is not placed in the default folder, while the resources are obviously available in the main view.

**Comment by JosefNemec** [comment]
Done in devel9.

**Comment by felixkmh** [comment]
The fix is merged into the devel branch, right? Because I still get the wrong behaviour in a very specific place: The CheckBox style from my theme [Night.zip](https://github.com/JosefNemec/Playnite/files/7093136/Night.zip) does seem to apply everywhere except for the four items at the top of the filter panel, see attached screenshot.
![grafik](https://user-images.githubusercontent.com/24227002/131714773-941148f1-1c4b-46b0-9d7d-ae3b104e8974.png)
