### ISSUE TITLE
Support for galaClient?

### ISSUE THREAD

**Issue by Razukin** [JosefNemec/Playnite#2331]
IndieGala just came out with a GalaClient for downloading DRM-free games. I don't know anything about the technical implementation, but if Playnite could integrate with it, perhaps much better IndieGala support would be better including installation? I'm not sure if this is an issue better suited for the IndieGala plugin.

**Comment by JosefNemec** [comment]
I'm not going to personally work on this. I already have to maintain quite a lot of these integrations. This is something that should be done as 3rd party extension.
