### ISSUE TITLE
Script doesn't execute before start epic game.

### ISSUE THREAD

**Issue by sunencheng** [JosefNemec/Playnite#2332]
I use this powershell script before starting a game .
`Start-Process "G:\Application\MSI Afterburner\MSIAfterburner.exe"`
But it doesn't execute when i start epic game.steam game is ok.

**Comment by JosefNemec** [comment]
These scripts are executed in the same way for every game, no matter the source library. If it works for Steam game, then it should work for Epic one as well. 

Also, attach requested information from the issue template.

**Comment by sunencheng** [comment]
Thanks.Borderlands 2 is OK,but pine is not ok.I guess this is my problem.
