### ISSUE TITLE
Add methods for MediaElement play(), stop(), and pause().

### ISSUE THREAD

**Issue by azuravian** [JosefNemec/Playnite#2334]
**Integration features**
If a feature request is related to library integrations, use separate [extensions repository](https://github.com/JosefNemec/PlayniteExtensions) to file a request.

**Check for existing issue**
Please use issue search in the repository if your feature request is something really obvious there's a high change it was already requested.

**Describe the solution you'd like**
Ability to add buttons with mouseclick methods that could call play, pause, or stop methods on a mediaelement.  Some example methods:

```
private void PlayButton_Click(object sender, RoutedEventArgs e)
{
    if (Media.Source != null)
        Media.Play();
}
 
private void PauseButton_Click(object sender, RoutedEventArgs e)
{
    if (Media.CanPause)
        Media.Pause();
}
 
private void StopButton_Click(object sender, RoutedEventArgs e)
{
    if (Media.Source != null)
        Media.Stop();
}
```

Alternatively, add support for the builtin MediaTransportControls.
https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.mediatransportcontrols?view=winrt-19041

**Screenshots**
If applicable, add screenshots to help explain requested changes.

**Comment by JosefNemec** [comment]
1) Playnite doesn't support any video game media files.
2) MediaTransportControls is UWP control, not WPF one.
3) Can be done in Playnite 9 with an extension.

In general, this will be done as part of #405.
