### ISSUE TITLE
Playnite fullscreen HDMI input loop & window remains focused even when opening game

### ISSUE THREAD

**Issue by jamie9090** [JosefNemec/Playnite#2336]
Using Ps5ish (although I don't know if it's related), full screen seems to occasionally get into an input loop with hdmi. I only have this issue in playnite, no other games or apps. 

See video: https://linksharing.samsungcloud.com/qOJSlGGlAsdv 

Maybe HDR related?  That's what the pop up on TV in top right corner says, "HDR". TV is LG CX.

Alongside this, opening up a game, I can still here Playnites background music. And ingame I get a double input issue, common when Playnite still has focus somehow in the background. I can fix this by going to desktop, opening playnite, minimising and then going back into game. I can't fix the input issue though. 

Makes me feel like perhaps there's an issue with how playnite is going full screen? Maybe it's a borderless window that's losing focus? 

Both issues seem related, in my opinion (an uneducated one 😂).

**Comment by JosefNemec** [comment]
Does it happen with default theme and all 3rd party extension disabled? If not, then you need to report it to theme/extension dev.

You also didn't attach information that's requested in issue template...

**Comment by jamie9090** [comment]
Sorry will get the Diag details shortly and test without extensions too!

**Comment by jamie9090** [comment]
Also, thank you Josef for an amazing project. Playnite makes a couch gaming dream a reality!

**Comment by jamie9090** [comment]
Just confirmed I'm only expereincing issue in PS5ish. Will re-open if I see this issue appear in Default.

Sorry!
