### ISSUE TITLE
GoG Games appear not installed. Sync fails. Clicking on install crashes playnite.

### ISSUE THREAD

**Issue by greendabre** [JosefNemec/Playnite#2338]
Sync error : Failed to import games from GOG. Unexpected character encountered while parsing value: . Path ", line 0,position 0.

Log attached. Generated after playnite crashed when clicking install.
[Playnite812.log](https://github.com/JosefNemec/Playnite/files/6526760/Playnite812.log)

**Comment by JosefNemec** [comment]
Please attach information request in issue template.

**Comment by greendabre** [comment]
What do you mean?

**Comment by greendabre** [comment]
Ah okay, I get it.

**Comment by greendabre** [comment]
Okay, I posted to the appropriate forum. Should I close this?
