### ISSUE TITLE
Need a Rockstar social club extension along with a facility of adding games like Genshin Impact  and Valorant.

### ISSUE THREAD

**Issue by Ax4Blood** [JosefNemec/Playnite#2341]
**Integration features**
If a feature request is related to library integrations, use separate [extensions repository](https://github.com/JosefNemec/PlayniteExtensions) to file a request.

**Check for existing issue**
Please use issue search in the repository if your feature request is something really obvious there's a high change it was already requested.

**Describe the solution you'd like**

**Screenshots**
If applicable, add screenshots to help explain requested changes.

**Comment by JosefNemec** [comment]
There already is Rockstar integration https://playnite.link/forum/forum-7.html

You can also add any game [manually](https://github.com/JosefNemec/Playnite/wiki/Adding-games-manually), which includes those two you mentioned.
