### ISSUE TITLE
Dialogue boxses don't work in full screen

### ISSUE THREAD

**Issue by zany130** [JosefNemec/Playnite#2342]
**Before creating bug report**
- Please use issue search in the repository first. If the bug is something really obvious there's a high change it was already reported.
- Make sure that the issue is not caused by custom theme or extension. You can restart Playnite in "safe mode" from help menu to quickly test it.
- Check list of known issues https://github.com/JosefNemec/Playnite/wiki/Known-Issues

**Integration issues**
If an issue is related to library integrations, use separate [extensions repository](https://github.com/JosefNemec/PlayniteExtensions) to file a report.

**Describe the bug**
extensions that use dialogue box are broken in full screen

**To Reproduce**
If it's not clear from the description how to reproduce the issue please add clear steps to reproduce the behavior.

Install how long to beat extension
**Screenshots**
https://u.pcloud.link/publink/show?code=XZ8xn9XZ53ByFALjBIuJrO8m7uXdULkcunsk

**Diagnostics ID**
Please generate diagnostics package from "About Playnite" menu and attach identifier you received. If the issue is a crash bug, you can generate diag. package directly from crash dialog.

0eb02716-1970-460b-ab90-db82744db0a2

**Comment by zany130** [comment]
I also opened a issue here https://github.com/Lacro59/playnite-howlongtobeat-plugin/issues/74 as I thought it might of been extension specific

**Comment by JosefNemec** [comment]
I have no idea what I'm suppose to see on that video. Whatever issue you are having, does it happen with default theme and with 3rd party extensions disabled?

**Comment by zany130** [comment]
Yes it happens regardless of themes as for extension of course it only happens with extensions that produce a dialogue box. If you look closely it just appears as a black speck on the tv i thought it might have been extension specific but @darklinkpower mentioned that this is a generic function from playnite so it's probably playnite fault and suggested i create this issues with that video

**Comment by JosefNemec** [comment]
What dialog API exactly is causing this?

**Comment by zany130** [comment]
I'm not sure exactly all i know it's that how long to beat and the ludusavi extensions show a pop-up after the game exits asking if the user wants to upload playtime (how long to beat) and if they want to back save data(ludusavi) and both of those pop-up show up as a black dot on the screen after the game ends when playnite is run in fullscreen. If playnite is in desktop mode the pop-ups work normally and are legible and usable

**Comment by darklinkpower** [comment]
> 
> 
> What dialog API exactly is causing this?

Ludusavi is using the `ShowMessage` method with a Yes/No message box.
https://github.com/mtkennerly/ludusavi-playnite/blob/master/src/LudusaviPlaynite.cs#L166

https://github.com/mtkennerly/ludusavi-playnite/blob/master/src/LudusaviPlaynite.cs#L317-L321

**Comment by JosefNemec** [comment]
`ShowMessage` 100% works, you can test that by trying to delete a game, it uses the same API.

**Comment by zany130** [comment]
> `ShowMessage` 100% works, you can test that by trying to delete a game, it uses the same API.
> 

You mean this pop-up? ![20210530_174608.jpg](https://user-images.githubusercontent.com/25832539/120120996-1a32ce80-c16f-11eb-9a68-4eb35f924a60.jpg)

Yeah that works but the pop-up ludusavi and how long to beat use just show up like a tiny dot like I showed in the video

**Comment by darklinkpower** [comment]
@zany130
As a suggestion, it's much better to share a screenshot to better appreciate what is going on in the screen. 

This website lists several ways to take one: https://www.take-a-screenshot.org/

After taking the screenshot, you can use `ctrl` + `v` here to share the screenshot. You can also upload mp4 videos here by draggin them to the write section.

**Comment by zany130** [comment]
here a screenshot of the dialogue box
![Screenshot 2021-05-31 015133](https://user-images.githubusercontent.com/25832539/120146359-f3968700-c1b2-11eb-9acc-4242ba470bd4.png)
and here it is blown up
![Screenshot 2021-05-31 015146](https://user-images.githubusercontent.com/25832539/120146436-14f77300-c1b3-11eb-9c2a-5a845b117486.png)

**Comment by JosefNemec** [comment]
Does this happen with all games? What's game's resolution? My guess is that the dialog is shown while the game is still running, which forces Playnite to think that desktop resolution is what the game currently uses and it scales dialog window based on that.

**Comment by zany130** [comment]
> Does this happen with all games? What's game's resolution? My guess is that the dialog is shown while the game is still running, which forces Playnite to think that desktop resolution is what the game currently uses and it scales dialog window based on that.


Yes this happens with all games and happens after i exit the game. Also i was running the game at 4k which is the same resolution playnite was running at on the tv.

**Comment by zany130** [comment]
tried connecting only my 4k tv and only my ultrawide 1080P monitor and same thing popup appears very tiny. This is in several games I have tried

**Comment by zany130** [comment]
Has anyone been able to reproduce this issue?

**Comment by JosefNemec** [comment]
I'm able to reproduce it, will be fixed in next update.

**Comment by JosefNemec** [comment]
Fixed in 8.13
