### ISSUE TITLE
Playnite Fullscreen crashes after waking up from hibernation on the GPD Win 3

### ISSUE THREAD

**Issue by Kavoriken** [JosefNemec/Playnite#2343]
I recently purchased and received a GPD Win 3 handheld gaming PC with an 1165G7 Tigerlake CPU. I do plan to use Playnite Fullscreen mode as the main game launcher for the device and i want to constantly have it running when putting the device to sleep and waking it up.

The Win 3 unfortunately comes with S0 (modern sleep) standby enabled, which works in weird ways and likes to randomly wake the device when it just sits on the table. Fortunately hibernation works so quickly, that using Windows standby is not really necessary.

Now my problem is, that when i am in the fullscreen mode of Playnite, let the device go into hibernation, wake it up and then unlock the device, i can see the playnite window for a second, but it always crashes. That does not happen when in playnite's desktop mode and it also does not happen on another device i own (GPD Win Max with an Ice Lake CPU).

As i am part of the GPD device's community on discord, i know that this seems to be reproducable on any GPD win 3 device, so it is not bound to my specific windows config. I do not know if this is a tigerlake specific problem, or if it is something about the Windows 10 version the Win 3 comes with.

If any crash logs or dumps are needed, just give me a word and i will upload them. Thanks for any help!

**Comment by JosefNemec** [comment]
Do you use any 3rd party extensions or themes? If so, try disabling them to see if they cause the crash. Also, if you don't get Playnite's crash dialog (which I assume you didn't, because you didn't attach crash ID), then the crash is not caused by our code, but most likely by some 3rd party (app installed on your system or an extension).

Lastly, there should be some crash info in Event Viewer, check there.

**Comment by Kavoriken** [comment]
> Do you use any 3rd party extensions or themes? If so, try disabling them to see if they cause the crash. Also, if you don't get Playnite's crash dialog (which I assume you didn't, because you didn't attach crash ID), then the crash is not caused by our code, but most likely by some 3rd party (app installed on your system or an extension).
> 
> Lastly, there should be some crash info in Event Viewer (built-in Windows app), check there.
