### ISSUE TITLE
PLaynite not detecting proper origin install state

### ISSUE THREAD

**Issue by p-engun** [JosefNemec/Playnite#2345]
When attempting to launch origin games (EA) the client only says, "install" and when I change the play action it works until I refresh the library or restart Playnite, at which point it reverts back to me having to press "install" and change the play actions again. I managed to fix this by unchecking everything except "Import installed games" in the Playnite Origin Library.
![image_2021-06-02_152225](https://user-images.githubusercontent.com/77411488/120497461-55730e80-c3b6-11eb-99ea-f64d7a1766d0.png)
![image_2021-06-02_151838](https://user-images.githubusercontent.com/77411488/120496830-ce259b00-c3b5-11eb-8be1-c107e9365e78.png)

**Comment by JosefNemec** [comment]
Provide information requested in issue template.
