### ISSUE TITLE
Wrong background image for selected game

### ISSUE THREAD

**Issue by philipjholm** [JosefNemec/Playnite#2348]
**Describe the bug**
In fullscreen mode, navigating in game list quickly by holding left arrow on keyboard most of the time results in wrong background image being shown for selected game.  See video. This happens also in safe mode but less frequently.

**To Reproduce**
Navigate far to the right in your game list and then hold down the left arrow key on your keyboard until you have navigated to the first item in the list.

**Video**
https://user-images.githubusercontent.com/37110163/120802648-f7bffd00-c542-11eb-8b3e-b8c1cb7e07e5.mp4

**Diagnostics ID**
Please generate diagnostics package from "About Playnite" menu and attach identifier you received. If the issue is a crash bug, you can generate diag. package directly from crash dialog.
d4ee7263-7e78-4a19-bd7d-99f64d39c77a

**Comment by JosefNemec** [comment]
Does it happen with default theme as well? If so, please make a video with default theme.

**Comment by philipjholm** [comment]
Yeah it does! A bit harder to see though, but as you can see on the first scroll, the Planet Coaster gets the Valheim background and then on the last scroll Tomb Raider gets the Fallout 4 background. Only happens when scrolling fast but a bit annoying as I often scroll quickly through my game library.

New video: 
https://user-images.githubusercontent.com/37110163/120809619-8f751980-c54a-11eb-86f3-f392aca13bf4.mp4

**Comment by JosefNemec** [comment]
Fixed in devel.
