### ISSUE TITLE
Handle Leak 

### ISSUE THREAD

**Issue by LeeThompson** [JosefNemec/Playnite#2352]
Over time, Playnite.DesktopApp.exe is leaking handles at the rate of about 200 per second.    I do have a rather large game library which may be a factor.   (As of this writing, it's at 9,876,892 handles and 38 threads.  The thread count is steady.)

I am running several extensions and a theme, so it may not be in PlayNite itself.  Hopefully the diagnostics package will have information that may be useful.   (This may be related to PlayNite eventually quietly terminating or perhaps not.)

(I just added the diagnostics ID below and the handle count is now at 9,891,548.)

**Diagnostics ID**
084e4363-c238-4b8a-99c0-1d4dc69c3bd7

**More information:**
This appears to occur when Playnite has launched a game, as soon as I exited the game, the handle count stopped rising, however, it did not release any handles.   The count is now 9,925,592.   This particular game is not part of any online library (Guild Wars 2), I don't know if that makes any difference.

**Comment by JosefNemec** [comment]
If you are running several extensions and a custom theme, then try disabling them to see if they are the issue. It's also what issue template says to do first before opening the issue...

**Comment by JosefNemec** [comment]
Never mind my last comment, I was able to reproduce it at last. It does only happen when game is being tracked by a process, not by a directory, so it mainly happens for manually imported games, not for most automatic ones (like Steam, GOG etc.).

**Comment by LeeThompson** [comment]
What might be something to add to Playnite is the ability to disable play time tracking and other monitoring on a game by game basis but that'd probably be a lot of work.

**Comment by JosefNemec** [comment]
Fixed in 8.13

**Comment by LeeThompson** [comment]
I've only been testing for a few minutes but it's looking a lot better, continuing testing but wanted to give you a quick early return.

**Comment by LeeThompson** [comment]
Still hasn't leaked any handles, I'm gonna call this one resolved!
