### ISSUE TITLE
Game Counter and making all copies of one game looking like one game, and you can choose from which launcher to launch the game.

### ISSUE THREAD

**Issue by Mite-Z-Ultra** [JosefNemec/Playnite#2354]
I want to request adding a counter for how much games do you have. Also can you make them like in GOG Galaxy - in GOG Galaxy all versions of a game are counted as one game and you can choose on which launcher to launch the game.

![Екранна снимка 2021-06-11 213727](https://user-images.githubusercontent.com/85761109/121734343-549c5400-cafd-11eb-9af8-61daad256f8d.png)

**Comment by JosefNemec** [comment]
Game grouping has been requested in multiple issues already.
