### ISSUE TITLE
platform included in library export.

### ISSUE THREAD

**Issue by X-4-N** [JosefNemec/Playnite#2355]
My Game Collection by Tuyware looks for a platform column when importing.  It would be really nice if the exported CSV from Playnite included the platform.

**Comment by JosefNemec** [comment]
You can change exported fields by modifying extension itself in `<playnite install dir>\Extensions\LibraryExporter\`

I have no plans developing library exporter extension any further.

**Comment by X-4-N** [comment]
np, changing the parameters for the built in extension was easy.  tyvm.
