### ISSUE TITLE
Downloading only covers using download metadata does not update game's modified time when a cover is found and downloaded

### ISSUE THREAD

**Issue by joyrider3774** [JosefNemec/Playnite#2356]
**Integration issues**
If an issue is related to library integrations, use separate [extensions repository](https://github.com/JosefNemec/PlayniteExtensions) to file a report.

I'm not sure if playnite or steam metadata provider is to blame

**Describe the bug**
when using download metadata on selected games (not using Edit screen) and deselecting only missing media and letting it update only cover images for games that already had a cover image, modified time of the game is not updated when a cover cover is downloaded

**To Reproduce**
Set PC Date one day in the past, modify a game where you know the metadata provider you will use has a cover for and modify the cover and save so that modified date is one day in the past. Set PC Date back to current day. Now use download metadata deselect "only missing data", in next screen deselect everything except covers and use steam as metadata data provider. Let it grab the cover. The cover will get update yet modified date of the game is still on yesterday so not updated.

**Screenshots**

https://user-images.githubusercontent.com/10714776/122203213-1bb60380-ce9e-11eb-9f7f-6a7d5f0b3aad.mp4

**Comment by JosefNemec** [comment]
Fixed in master.
