### ISSUE TITLE
Update Error - Failed to check for new version

### ISSUE THREAD

**Issue by shangles** [JosefNemec/Playnite#2357]
**Describe the bug**
I just updated Playnite to version 8.13.  If I manually check for updates (Help > Check for Updates) it fails with a pop-up Update Error window stating that it "Failed to check for new version."

**To Reproduce**

- Update Playnite to 8.13.
- Restart Playnite
- Manually check for updates via Help > Check for Updates menu.

**Screenshots**
![PrtScr capture_2](https://user-images.githubusercontent.com/9053908/122285324-6ab26780-cea3-11eb-86a2-7a73dd1aba31.jpg)

**Diagnostics ID**
32dfd463-70ac-48e9-ba15-65c1fbbe0a44

**Comment by JosefNemec** [comment]
Fixed on the server. Thanks for the report.
