### ISSUE TITLE
Some things to improve the Playnite.

### ISSUE THREAD

**Issue by SrAlexxYT** [JosefNemec/Playnite#2361]
1st Topic: Achievements

Why doesn't playnIte have an achievement system?
It didn't even need to appear in some corner of the screen, but at least when you enter a game you can see the game's achievements and which ones you've already achieved.

2nd Topic: Browser/Web

Why doesn't playnite have a browser system?
Like me, many people use Playnite to "transform" a pc in a console, because on pc there is a huge variety of games compared to consoles, but when i want to search i have to get out of Playnite's full screen mode, and it would be easier to just have a system of research in Playnite.

3rd Topic: Friends
Why isn't there a friend system in Playnite?
Because then you could see your friend and see what games he plays, regardless if it's from Steam or Epic Games or Ubisoft etc. And if you could play a game that you and your friend have in common it would be pretty top.

4th Topic and the last: Sound/Audio

Since there is no audio in Playnite when I use it, I think my headset is not working or I have muted it. At least one sound when clicking a game or moving the analog stick (selecting a game, for example).

NOTE: I know from constructive criticism that I seem to hate Playnite, but I just want to help you improve, as it is in the title of this "comment".

**Comment by SrAlexxYT** [comment]
> 1st Topic: Achievements
> 
> Why doesn't playnIte have an achievement system?
> It didn't even need to appear in some corner of the screen, but at least when you enter a game you can see the game's achievements and which ones you've already achieved.
> 
> 2nd Topic: Browser/Web
> 
> Why doesn't playnite have a browser system?
> Like me, many people use Playnite to "transform" a pc in a console, because on pc there is a huge variety of games compared to consoles, but when i want to search i have to get out of Playnite's full screen mode, and it would be easier to just have a system of research in Playnite.
> 
> 3rd Topic: Friends
> Why isn't there a friend system in Playnite?
> Because then you could see your friend and see what games he plays, regardless if it's from Steam or Epic Games or Ubisoft etc. And if you could play a game that you and your friend have in common it would be pretty top.
> 
> 4th Topic and the last: Sound/Audio
> 
> Since there is no audio in Playnite when I use it, I think my headset is not working or I have muted it. At least one sound when clicking a game or moving the analog stick (selecting a game, for example).
> 
> NOTE: I know from constructive criticism that I seem to hate Playnite, but I just want to help you improve, as it is in the title of this "comment".

**Comment by darklinkpower** [comment]
Not sure why you closed, maybe you saw that there are already requests for your ideas but linking them just in case.

1.
https://github.com/JosefNemec/Playnite/issues/146
https://github.com/JosefNemec/Playnite/issues/2041
Also a user extension already exists (SuccessStory)

2. https://github.com/JosefNemec/Playnite/issues/138
3. No open issue but would be technically difficult to develop and maintain. I guess you could ask the Playnite developer but I don't think it's feasible
4. Done for Playnite 9 in https://github.com/JosefNemec/Playnite/issues/1335 and also a user extension exists already (Playnite Sounds)

**Comment by SrAlexxYT** [comment]
> Not sure why you closed, maybe you saw that there are already requests for your ideas but linking them just in case.
> 
> 
> #146
> #2041
> Also a user extension already exists (SuccessStory)
> 
> 1. #138
> 2. No open issue but would be technically difficult to develop and maintain. I guess you could ask the Playnite developer but I don't think it's feasible
> 3. Done for Playnite 9 in #1335 and also a user extension exists already (Playnite Sounds)

I don't know if I screwed up, but I ended up closing it accidentally, im new in Github...

**Comment by darklinkpower** [comment]
I see. In any case, I suggest looking for existing issues as mentioned in the issue template to see if it already exists.
