### ISSUE TITLE
Cannot authenticate Playstation

### ISSUE THREAD

**Issue by NateIce31** [JosefNemec/Playnite#2363]
When I go to authenticate, I get "The sign-in ID (email address) or password is not correct."
Both of these are correct however. 
I've also tried generating a passcode as if I was logging in with a PS Vita/PS3 but no luck.

**Comment by JosefNemec** [comment]
Why did you open duplicate for this? You already reported this before.

https://github.com/JosefNemec/PlayniteExtensions/issues/26
