### ISSUE TITLE
Playnite reports an extension update is available, but to the same version number.

### ISSUE THREAD

**Issue by kwilliams1987** [JosefNemec/Playnite#2369]
**Before creating bug report**
- Please use issue search in the repository first. If the bug is something really obvious there's a high change it was already reported.
- Make sure that the issue is not caused by custom theme or extension. You can restart Playnite in "safe mode" from help menu to quickly test it.
- Check list of known issues https://github.com/JosefNemec/Playnite/wiki/Known-Issues

**Integration issues**
If an issue is related to library integrations, use separate [extensions repository](https://github.com/JosefNemec/PlayniteExtensions) to file a report.

**Describe the bug**
After installing the SuccessStory plugin I constantly get notified there is a new update to the same version.

Redownloading and installing the plugin didn't help.

**To Reproduce**
Simply downloaded and installed the addon using the shell integration.

**Screenshots**
![image](https://user-images.githubusercontent.com/2725436/124141850-06d69400-da8a-11eb-9a6e-5f7b564667bf.png)

**Diagnostics ID**
`09b9b7d0-cfff-4306-b110-02fa1900f75a`

**Comment by JosefNemec** [comment]
Playnite currently doesn't support extension updates, that notification is from a specific extension. You need to report the issue to its developer.
