### ISSUE TITLE
Improve "Features" of PN

### ISSUE THREAD

**Issue by msartiano** [JosefNemec/Playnite#2373]
**Problem**

**Integration features**
LB "Play mode" column displays information about games, such as "Single player", "Coop", "Multiplayer"
PN "Features" does the same as above as far as I can see
LB and EmuMovies by themselves have very rich and often matching "features" data, as shown when using LB, whereas IGDB has games that are supposed to be multiplayer not marked as multiplayer

**Describe the solution you'd like**
Here are 2 possible solutions:
1. Integrate "Play Mode" to be merged into "Features" from other databases, such as LB and EmuMovies.
2. Add a new "Play Mode(s)" property field in PN. (or..)

Any alternative is ok, the goal is to get a more detailed databases and LB/EmuMovies have rich DBs to be used as features/play mode.

**Screenshots**
Example: Features missing for 2020 Super Baseball
![immagine](https://user-images.githubusercontent.com/30049751/124789839-88269e80-df42-11eb-8f8b-4207841785d7.png)
And multiplayer info displayed on LB:
![immagine](https://user-images.githubusercontent.com/30049751/124790011-b1dfc580-df42-11eb-828a-d91f2099d7ba.png)

Example,: Multiplayer missing from 3 Ninjas Kick Back
![immagine](https://user-images.githubusercontent.com/30049751/124790093-c8861c80-df42-11eb-9f91-2b97766fadb5.png)
And Coop/Multiplayer shown on LB:
![immagine](https://user-images.githubusercontent.com/30049751/124790235-e81d4500-df42-11eb-97fa-b76418c7b4e1.png)

**Comment by JosefNemec** [comment]
You can already use Features, Tags, Categories and other fields for this. I don't see a point in adding another fields that basically duplicates existing functionality.

**Comment by msartiano** [comment]
Issue closed, as the best implementation for this problem is to update the extensions, which are proprietary and not related to the original PN Software, thanks.

**Comment by darklinkpower** [comment]
Leaving this here in case it's useful in the future. Automatically grabbed from a 1.4k library, should have all "Play Modes"

Steam category enums:

```
Id Value
-- -----
 1 Multi-player
 2 Single-player
 8 Valve Anti-Cheat enabled
 9 Co-op
10 Game demo
13 Captions available
14 Commentary available
15 Stats
16 Includes Source SDK
17 Includes level editor
18 Partial Controller Support
19 Mods
20 MMO
22 Steam Achievements
23 Steam Cloud
24 Shared/Split Screen
25 Steam Leaderboards
27 Cross-Platform Multiplayer
28 Full controller support
29 Steam Trading Cards
30 Steam Workshop
31 VR Support
32 Steam Turn Notifications
33 Native Steam Controller Support
35 In-App Purchases
36 Online PvP
37 Shared/Split Screen PvP
38 Online Co-op
39 Shared/Split Screen Co-op
41 Remote Play on Phone
42 Remote Play on Tablet
43 Remote Play on TV
44 Remote Play Together
47 LAN PvP
48 LAN Co-op
49 PvP
```
