### ISSUE TITLE
Origin-Plug In/EA Play: Games detected, but they do not start

### ISSUE THREAD

**Issue by forenta** [JosefNemec/Playnite#2379]
I use EA Play as an Xbox Game Pass Ultimate subscriber. Accordingly, Origin is replaced here by 'EA Play BETA'. The games are imported correctly - however, when trying to start a game via EA Play, only EA Play starts/appears in the foreground.
Maybe this can still be fixed?

Diagnostic ID: 85c352c7-5776-4760-acc8-8cd256cb70c6

**Comment by JosefNemec** [comment]
1) Wrong repository
2) EA Desktop is not currently supported https://github.com/JosefNemec/PlayniteExtensions/issues/13

**Comment by h107474** [comment]
Is it planned for support or is it impossible due to some technical limitation?
