### ISSUE TITLE
Netplay Support

### ISSUE THREAD

**Issue by FolfyBlue** [JosefNemec/Playnite#2380]
Hey, currently most popular/modern emulators all have a [Netplay ](https://emulation.gametechwiki.com/index.php/Netplay)feature (Retroarch, Dolphin, Mesen, Citra...)
But it seems impossible to launch these games in Netplay mode without creating a new Game profile with custom Emulator Arguments.
Could it be possible to implement a second Play button or an option in "More" to launch the current game in Netplay? 
The extra arguments required could be stored in the emulator's yaml file, and it could be great if we could even have a default Netplay IP/Port for all Emulators to use.

**Comment by JosefNemec** [comment]
Will be possible via #272 and #653 in Playnite 9.
