### ISSUE TITLE
Steam artwork doesn't get added when game was first added offline

### ISSUE THREAD

**Issue by rbits0** [JosefNemec/Playnite#2389]
**Describe the bug**
If I refresh the steam games in playnite while offline, the new games now have no artwork. If I then connect to the internet, they still have no artwork and I have to manually add the artwork individually from IGDB.

**To Reproduce**
Add new game to steam library
Disconnect from internet
Open playnite and refresh steam games

**Screenshots**
![image](https://user-images.githubusercontent.com/56014573/126100696-042f29cf-3cf5-404b-84df-a015c04a60c6.png)

**Comment by darklinkpower** [comment]
Playnite does not actively search for metadata when connecting/disconnecting from internet. If the automatic download process was not done on game import you need to download metadata manually from the edit window or in batch from MainMenu -> Library -> Download metadata

**Comment by JosefNemec** [comment]
Playnite doesn't re-download artwork automatically if the initial download was canceled or failed, that's by design.

**Comment by rbits0** [comment]
Ah, I didn't see the download metadata button in the playnite menu. Thanks!
