### ISSUE TITLE
PlayStation Library user authentication gives error after second login

### ISSUE THREAD

**Issue by TopHatHipster** [JosefNemec/Playnite#2390]
**Bug description**
The PlayStation Library recently mentioned that I am not authenticated anymore. Upon trying to re-authenticate, the first time logging in fails (stating the email address or password is incorrect, yet this is not correct as logging in with a regular web browser (using Brave/Chromium) works with one try)). Trying to login a second time and doing the human check causes an error. Clicking the error away shows on the homepage that I've been successfully logged into.

**How to reproduce**
1. Check the "Connect account" tick box and click the Authenticate button
2. Enter your email address and password/login as usual
3. Try logging in again by inputting the password
4. Follow the human verification test
5. Click the error away
6. Click on the sign in button on the PlayStation homepage

**Screenshots**
![image](https://user-images.githubusercontent.com/43381730/126164999-75b35bc8-9e74-46bc-915a-0bbaf0fcd311.png)
*First attempt logging in with correct credentials, email address censored.*
![image](https://user-images.githubusercontent.com/43381730/126165171-5aa59838-a45f-40e1-bccc-14d939e2d6d0.png)
*Human verification test after second login*
![image](https://user-images.githubusercontent.com/43381730/126165227-71c70bb8-a76b-4015-81d3-78dfbc4260c4.png)
*Error after trying to login with the correct credentials a second time*
![image](https://user-images.githubusercontent.com/43381730/126165388-2f452120-59e0-48ee-ba2d-8ef4db60f727.png)
*Correctly logged into account, after clicking the error away and clicking on the sign in button of the homepage*

**Diagnostics ID**
4fdfe697-20f1-474e-9696-29c903656e16

**Comment by JosefNemec** [comment]
1) Wrong repository
2) Already reported in correct one
