### ISSUE TITLE
Don't prevent wake events when suspending/hibernating Windows from Playnite

### ISSUE THREAD

**Issue by itsteddyyo** [JosefNemec/Playnite#2395]
**Describe the bug**
The problem is Playnites "Suspend/Hibernate System" actions in fullscreen mode are preventing Windows from waking up again at events. 
I am using a tool to update my games when i'm asleep and this tool works by creating a scheduled task in the Windows Task Scheduler. So when im done gaming i suspend the system and the task is supposed to wake the PC and work it's magic. 
But if i suspend from Playnite the PC only wakes at manual interaction (press power button, move mouse, etc.). If i send the system to sleep from Windows itself it works.
I think the reason is you call the SetSuspendState function with the parameter for wake events disabled.
https://github.com/JosefNemec/Playnite/blob/928e47926528f2f1c5555aebcad35b6ce2579ca9/source/Playnite.Common/InteropMethods.cs#L598
https://github.com/JosefNemec/Playnite/blob/928e47926528f2f1c5555aebcad35b6ce2579ca9/source/Playnite.Common/Computer.cs#L237-L245
Not even sure if bug is the right word from my problem. I just didn't find any information on why the wake events are disabled in general. If there's a reason and i just didn't see it i'm sorry.

**To Reproduce**
1. Create a scheduled task in the Windows Task Scheduler.
2. Use the "Suspend System" or "Hibernate System" actions in fullscreen mode. The system will not wake up.
3. Suspend the system from Windows itself. The system wakes up.

**Screenshots**
![image](https://user-images.githubusercontent.com/87882842/126852056-ec583640-e799-463f-80ea-8e3528a121de.png)

**Comment by JosefNemec** [comment]
I probably just didn't read properly what that argument does and just enabled it. I'll disable it in next version.

**Comment by JosefNemec** [comment]
Done in devel9.
