### ISSUE TITLE
updating game pass catalog at start adding all game pass games without active sub (but with linked account)

### ISSUE THREAD

**Issue by stoniemahonie** [JosefNemec/Playnite#2396]
Playnite just crashed while adding xbox gamepass games. The thing is, i dont have an active sub. I only have forza horizon 4 bought on game pass and installed like 3 games that i cant play bc of the inactive subscription. 

Just now when i started Playnite, the program has this routine to check on my linked accounts (steam, game pass etc.). It added like all game pass games to the library. But i did not change anything in regard to that. It happened out of nowhere. At first i thought playnite was stuck at "updating game pass catalog" but i could click inside this pop-up window notification with the right mouse button and could close it through the dialog.

I will now try to remove those games and unlink/deactivate the game pass functionality that comes with playnite for now. Maybe microsoft did something wrong and i can play all those games now, i will definitly check it out and report back if so.

**Comment by stoniemahonie** [comment]
seems like nothing was added at first sight. But the notification bell said 67 gamepass games got added before it crashed. i sorted the list by the filter date added and could not see something from there. Strange. Playnite works now as before. I will leave the game pass linking on and report back if it happens again and document it better.

**Comment by JosefNemec** [comment]
1) Integration related issues should go to a different repository as mentioned in issue template.
2) Xbox integration doesn't have any explicit Game Pass support, are you use you are not using some extension? Like this one: https://playnite.link/forum/thread-716.html

**Comment by stoniemahonie** [comment]
It ssems to be plugin related and this is the one. Thank you for clarification.

**Comment by JosefNemec** [comment]
Then you need to report the issue to its developer.
