### ISSUE TITLE
Download metadata error 

### ISSUE THREAD

**Issue by ageekhere** [JosefNemec/Playnite#2398]
**Describe the bug**
When downloading metadata i get the error "failed to download metadata unexpected character encountered while parsing value: <, path ", line 0, position 0."

**To Reproduce**
edit a game
Click download metadata
Click IGDB
Enter game name
Select game that is in the list

**Comment by JosefNemec** [comment]
Can't reproduce. What game (IGDB record) is it specifically? Also, attach all information requested in issue template.

**Comment by ageekhere** [comment]
Ah worked it out, it was my router blocking something.
Conclusion if you get this error your connection is getting blocked by your router.
