### ISSUE TITLE
Keeps re-downloading metadata

### ISSUE THREAD

**Issue by TheL0rd0fSpace** [JosefNemec/Playnite#240]
I noticed that when I open Playnite after restarting my pc, it needs to download images and game details again. So, if it isn't a thing already, then please let Playnite store those details without needing to redownload them multiple times.

Sincerely, a guy with 1k+ games.

**Comment by JosefNemec** [comment]
Please go to `About Playnite` menu and create diagnostics package for me. Thanks

**Comment by JosefNemec** [comment]
I'm going to close this for now since there's no additional information from original reporter and metadata download has been completely reworked in 3.0
