### ISSUE TITLE
Blurred label after hover

### ISSUE THREAD

**Issue by GitWatin** [JosefNemec/Playnite#2401]
**Describe the bug**
After hovering the mouse over the interface elements, they become "blurred" and impossible to read the content.
This happens mostly on labels
As can be seen on the pictures below

Graphic Driver was updated

**To Reproduce**
I don't know, just hover the interface label.
It's a clean install (with delete application cache and folder) 

**Screenshots**
![bug1](https://user-images.githubusercontent.com/28529151/128596376-0089b576-4b52-45c5-9d14-05a71de7edb3.png)
![bug4](https://user-images.githubusercontent.com/28529151/128596377-d1b55577-4475-41a9-8094-487f448ed9bc.png)
![bug3](https://user-images.githubusercontent.com/28529151/128596378-ce08217c-e13b-450d-a48d-399e78ce50dd.png)
![bug2](https://user-images.githubusercontent.com/28529151/128596380-e25fbd21-83e6-4630-b124-97a4bcfe4fd3.png)

**Diagnostics ID**
62797d0e-beb1-4097-ac67-fc1b583360a8

**Comment by darklinkpower** [comment]
Check if there's a third party app in your PC that might be causing it
https://github.com/JosefNemec/Playnite/wiki/Known-Issues#graphical-glitches-with-hardware-acceleration-enabled

**Comment by GitWatin** [comment]
> Check if there's a third party app in your PC that might be causing it
> https://github.com/JosefNemec/Playnite/wiki/Known-Issues#graphical-glitches-with-hardware-acceleration-enabled

I have already checked this kind of software. 
Can you maybe tell me what software could cause this? 

Regards

**Comment by JosefNemec** [comment]
Most people reporting this recently confirm that this is caused by `Nahimic Service`, but it might be some other app in your case. It is definitely caused by a third party and it's not an issue in Playnite.

**Comment by GitWatin** [comment]
Thanks you, 

I disable hardware acceleration in playnite options, and it's seems to be good

Regards

**Comment by darklinkpower** [comment]
Be aware that disabling hardware is more like a hacky workaround than a proper solution. Not using hardware acceleration will make Playnite slower.

Definitely try to investigate what app is causing this, you can try maybe running your PC in safe mode so it doesn't load some unneeded programs, try closing programs one by one, try checking in task manager if there is something running that could affect it, etc. Unforunately the program that is affecting you may be different for everyone so it should be investigated in a case per case basis individually to try to solve it.

**Comment by joyrider3774** [comment]
are you using MSI Afterburner and more specifically rivaturnerstatistics or something similar like thos apps? if so add exclusion for playnite in rivatunerstatistics.
