### ISSUE TITLE
Certain metadata plugins can add "NULL" weblinks causing playnite to crash if you try to remove such links

### ISSUE THREAD

**Issue by joyrider3774** [JosefNemec/Playnite#2402]
**Describe the bug**
Certain Metadata plugins are able to add NULL website links, for example the dslite metadata plugin did this for a few games. When you try to remove such links in playnite, playnite will crash. Either playnite should not allow such null links to be created when downloading metadata or it should handle this better when trying to delete such null weblinks. 

**To Reproduce**
1. install [DSLITE ](https://github.com/erri120/Playnite.Extensions/releases) metadata provider
2. acquire following 2 games on steam [Restrictr](https://store.steampowered.com/app/1170130/Restrictr/) or [Reality Blender](https://store.steampowered.com/app/844060/Reality_Blender/)
3. update steam library
4. edit game and download metadata using dslite it wll add a normal link as well as a NULL link
5. try to remove the NULL weblink and playnite will crash

Alternively i have included the 2 games json files of where the null links exists in 

[games.zip](https://github.com/JosefNemec/Playnite/files/6950544/games.zip)

**Screenshots**

https://user-images.githubusercontent.com/10714776/128629066-16022baa-790a-4301-89cb-eef1bf8f9c38.mp4

**Diagnostics ID**
6b69e97e-8d3e-46b7-baa1-d24bddb0542c

**Comment by JosefNemec** [comment]
Fixed in devel9.
