### ISSUE TITLE
A way to save/backup "User Score"

### ISSUE THREAD

**Issue by Amin52J** [JosefNemec/Playnite#2403]
I would like to see a feature to give us the ability to save or backup user scores in local device (or even online?). 

I recently had to re-install my Windows and after re-installing playnite I realized I had to score my 200+ games again to get the manual sort I wanted. Keep in mind that some of these games have been scored a few years back so I could not replicate the exact scores I once gave them. I think this would be a huge time saver. Thank you for this amazing software 🙌

**Comment by JosefNemec** [comment]
I don't think that option to backup only specific fields makes sense. You can already backup the complete library see [FAQ page](https://github.com/JosefNemec/Playnite/wiki/Frequently-Asked-Questions#how-do-i-backup-playnite-library-and-move-it-to-another-pc).

There are no plans plans to add native cloud account support in near future, see #108. But there are plans to add automated backup support, see #912
