### ISSUE TITLE
Launch Playnite minimized: only on startup

### ISSUE THREAD

**Issue by redactedscribe** [JosefNemec/Playnite#2408]
**Describe the solution you'd like**
An option to augment the "Launch Playnite minimized", so that it only starts minimized if "Launch Playnite when you start your computer" is enabled.

If launched via shortcut or other means, I'd like Playnite to appear on my screen, and not have to additionally go and restore it from the system tray.

Playnite v8.14

**Comment by 1ucay** [comment]
Yes please, also if I updating plugins or Playnite over GUI, it should be restore to window mode, not minimized.

**Comment by Progaros** [comment]
It should be possible by editing this file:
[CmdLineOptions.cs](https://github.com/JosefNemec/Playnite/blob/devel/source/Playnite/App/CmdLineOptions.cs)
```
[Option("startminimized")]
        public bool StartMinimized { get; set; }
```

**Comment by redactedscribe** [comment]
"Launch Playnite when you start your computer" > "Start closed to tray" option introduced in Playnite version 10, but doesn't appear to work currently: https://github.com/JosefNemec/Playnite/issues/3071

**Comment by JosefNemec** [comment]
Done in Playnite 10.
