### ISSUE TITLE
PowerShell 6/7 scripting support

### ISSUE THREAD

**Issue by shakeyourbunny** [JosefNemec/Playnite#2410]
**Check for existing issue**
Did not find any this regard.

**Describe the solution you'd like**
Add PowerShell 6 (aka 7/Core) scripting SDK support.

Although PowerShell 5.1 is well made, there should be some support for using PowerShell 6/7/Core if 5.1 is not available.

Perhaps already a planned feature for Playnite 9?

Thank you!

**Comment by shakeyourbunny** [comment]
Maybe duplicate of https://github.com/JosefNemec/Playnite/issues/823 ?

**Comment by JosefNemec** [comment]
Duplicate
