### ISSUE TITLE
Importing Games issue

### ISSUE THREAD

**Issue by CptVeg** [JosefNemec/Playnite#2412]
Getting a "failed to import games from X. The calling thread cannot access this object because a different thread owns it'" on most of my libraries when I try to import my games. Was all working fine until I upgraded my processor, 4790k>10700k 

![image](https://user-images.githubusercontent.com/64119101/130740916-c0f7eeab-87f4-426c-8476-693b9feefe6d.png)

**Comment by JosefNemec** [comment]
1) Where is all the information requested from issue template?
2) This is a known issue caused by some extension, try disabling 3rd party extensions you installed to found out which one is causing it.
