### ISSUE TITLE
Option to download images (or videos) from databases

### ISSUE THREAD

**Issue by KipThorne** [JosefNemec/Playnite#242]
IGDB (and other DB) sometimes provides images. Since Playnite already downloads metadatas, it will be great to add an option to donwload these images (and maybe trailers).

**Comment by v00d00m4n** [comment]
We need Wiki-like user-managed database for game arts of same size and standard and metadata, where all the information would be present.

**Comment by JosefNemec** [comment]
Related to #249 and #358

**Comment by JosefNemec** [comment]
Video support will be done in #405. Support for image download from IGDB (and other services via plugins) was done in Playnite 6.
