### ISSUE TITLE
PlayStation authentication process dont works with 2 FA Authentication Accounts

### ISSUE THREAD

**Issue by DustinDEV2more** [JosefNemec/Playnite#2422]
**Describe the bug**
If you try to link a playstation account with 2 factor authentication enabled, the Login promt response with the following promt: "The connection to the server timed out."

**To Reproduce**
Open the libraries window, go to the PlayStation section, click on Authenticate and try to login with a 2 Factor Authentication enabled Playstation Account

**Screenshots**
![promt image](https://i.ibb.co/QDqjGXP/Screenshot-2021-08-30-230135.png)

**Diagnostics ID**
2a9dff34-8f2f-417f-84f1-63c82f0815ba

**Comment by darklinkpower** [comment]
Incorrect repository as mentioned in the issue template. Login issues have been identified and there's an open issue: https://github.com/JosefNemec/PlayniteExtensions/issues/26
