### ISSUE TITLE
Keyboard searching in Tag field in Edit Game Details window

### ISSUE THREAD

**Issue by XenorPLxx** [JosefNemec/Playnite#2426]
**Integration features**
If a feature request is related to library integrations, use separate [extensions repository](https://github.com/JosefNemec/PlayniteExtensions) to file a request.

It's not.

**Check for existing issue**
Please use issue search in the repository if your feature request is something really obvious there's a high change it was already requested.

The closest I could find is https://github.com/JosefNemec/Playnite/issues/2264, but it is different.

**Describe the solution you'd like**

When you edit game details, you can use the keyboard to quickly search through options in some filed (e.g. Platform), but you can't use it for others (e.g. Tag). Would it be possible to add searching with keyboard to all fields (or at least Tag field?).

Extra: While making screenshots, I've found a possible bug. When you first click keyboard-searchable field (like Platform), and then open up non-searchable field and then press the same letter on the keyboard as before, search still works for the Platform field.
https://user-images.githubusercontent.com/6712823/131866545-ea317215-1c9c-48c5-b82f-a703b550e850.mp4

**Screenshots**
If applicable, add screenshots to help explain requested changes.

![image](https://user-images.githubusercontent.com/6712823/131865477-ad0d5a61-08d9-4c4d-8100-1b8fd2f4a763.png)

**Comment by SHiLLySiT** [comment]
This is very much needed when any of the metadata fields have 100s of entries.

**Comment by JosefNemec** [comment]
We already added search since this was opened.

**Comment by SHiLLySiT** [comment]
Ohhh sorry I just realized this ticket is for the edit game details window, not the filter view pane. I'll make a new one for this!
