### ISSUE TITLE
Export Prometheus compatible metrics

### ISSUE THREAD

**Issue by lapo-luchini** [JosefNemec/Playnite#2428]
Probably it's only me, but I'd find very nice if _Playnite_ exported (optionally) some usage metrics in Prometheus format (a single GET implemented on a local HTTP port) to export things such as:
- number of games in the library
- total play time
- play time per game (maybe?)
- access to external libraries / syncs done
- other stuff

Exporting Prometheus-like metrics should be fairly easy using this [Prometheus.Client](https://github.com/prom-client-net/prom-client).

If you'd like the idea I could try doing a PR, when I have some free time.

**Comment by JosefNemec** [comment]
This looks to me like a very niche feature and should be imho done as custom extension.

**Comment by JosefNemec** [comment]
Closing based on my previous comment.

**Comment by lapo-luchini** [comment]
I'm creating an extension for this:
https://github.com/lapo-luchini/PlayniteExporter
