### ISSUE TITLE
Extension Scripts load localization string of other extensions

### ISSUE THREAD

**Issue by darklinkpower** [JosefNemec/Playnite#2429]
**Describe the bug**
Extension Scripts load localization string of other extensions. This happens if the localization string key has the same name in more than one extension.

**To Reproduce**
Have multiple script extensions and create a localization dictionary containing a key with the same name. Then the extensions will use only the localization string of the latest extension loaded that has that string instead of their own one. I have not seen if it also happens with C# extensions.

**Screenshots**
Extension 1 (Correct)

![image](https://user-images.githubusercontent.com/1389286/132020048-6cb79b7c-07f6-474e-8a62-c06cd12f8f21.png)

![image](https://user-images.githubusercontent.com/1389286/132020153-05935c16-2c71-4986-8af5-bcb3a33bcc90.png)

![image](https://user-images.githubusercontent.com/1389286/132020235-9b7d0f4a-4d68-49aa-a1f9-a22b40de5fb4.png)

Extension 2 (Incorrect, uses string of extension 1)

![image](https://user-images.githubusercontent.com/1389286/132019679-d5ee2fc1-8a87-4f8d-981e-928c651fd7ba.png)

![image](https://user-images.githubusercontent.com/1389286/132019791-5aaf59dd-c215-46a3-a2dd-bcfda66197c7.png)

![image](https://user-images.githubusercontent.com/1389286/132019916-19c68620-695d-4856-b3a1-5779c8567abe.png)

**Diagnostics ID**
Please generate diagnostics package from "About Playnite" menu and attach identifier you received. If the issue is a crash bug, you can generate diag. package directly from crash dialog.

**Comment by JosefNemec** [comment]
Nothing I can do about that, you need to use different keys for different extensions.

**Comment by JosefNemec** [comment]
To clarify, I could technically add support for same keys from different extensions, but it would require completely rewriting localization support in Playnite, which is in my opinion not worth it.

**Comment by darklinkpower** [comment]
I see, don't worry if it's too much work then, I'll make them unique.
