### ISSUE TITLE
Details/Grid/List buttons should get a toggled state

### ISSUE THREAD

**Issue by SilverRoll** [JosefNemec/Playnite#2430]
The three buttons on the top bar that switch between view modes should get toggled states:
![image](https://user-images.githubusercontent.com/35656715/132048357-f1bc6177-65c9-48ce-9f39-5c29b66303f7.png)
There isn't much clarity over what view is currently in use. I thought the button is supposed to do something, but being on the details view, it didn't do much and I thought I had found a bug.

**Describe the solution you'd like**
Maybe a design like this could help:
![image](https://user-images.githubusercontent.com/35656715/132048784-7e634c45-2106-44ae-8b36-29bec8710c12.png)

**Comment by JosefNemec** [comment]
Fixed in devel.
