### ISSUE TITLE
Pressing F11 on Fullscreen mode does not return to desktop mode

### ISSUE THREAD

**Issue by WHITTYTOM95** [JosefNemec/Playnite#2433]
I can only return to desktop mode by navigating to the Playnite button and clicking it from there. Additionally, I can only access this Playnite button using the controller from the very right, top-most game, rather than being able to press up on the d-pad from any top-row game. I don't know if this is a bug, or intentional.

**Comment by SilverRoll** [comment]
As a theme designer, I found this incredibly useful. I'd like to see it back.

**Comment by JosefNemec** [comment]
Fixed in devel.
