### ISSUE TITLE
No "Select Sound" is played when selecting a game with the mouse in fullscreen application

### ISSUE THREAD

**Issue by joyrider3774** [JosefNemec/Playnite#2434]
**Describe the bug**
No "Select Sound" is played when selecting a game with the mouse in fullscreen application, only when using keyboard or gamecontroller a sound is played

**To Reproduce**
select games with the mouse in fullscreen mode

**Screenshots**
not applicable

**Diagnostics ID**
probably not applicable as well but b6865407-e0ba-46d3-b091-c8c78e22e06d

**Comment by JosefNemec** [comment]
Fixed in devel.
