### ISSUE TITLE
P9 Beta: Platform media is not migrated from playnite 8

### ISSUE THREAD

**Issue by joyrider3774** [JosefNemec/Playnite#2435]
**Describe the bug**
Platform media is not shown when icons are missing, it would seem platform media is not migrated from playnite 8

**To Reproduce**
Have games without certain media in playnite 8 for a certain platform, have platform media set in playnite 8 for this platform and in settings setup showing of missing media to platform. After p9 beta migration, platform media does not show up for that platform with games missing media while settings are still the same

**Diagnostics ID**
f337cf54-78dd-4fdb-aaf5-efd1e20a5ad3

**Comment by JosefNemec** [comment]
Fixed in devel.
