### ISSUE TITLE
Can't open any game trough the beta

### ISSUE THREAD

**Issue by Fancy2209** [JosefNemec/Playnite#2436]
**Describe the bug**
Sorry for the few information but this is everything I know
When I try to open a game from any plataform it says "It was not possible to start the game: Couldn't load file ou assemble 'System.Management.Automation, Version=3.0.0.0, Culuture=neutral, PublicKeyToken=31bf3856ad364e32' or one of the respective dependencies, File not found"
happens even with an custom play action.

**To Reproduce**
 Open any game trough playnite.
 
**Screenshots**
![image](https://user-images.githubusercontent.com/64917206/132067876-91baa1d9-8e7f-430c-a5a8-5a90cefec174.png)

**Diagnostics ID**
80fa89c5-fb11-4b6e-9b7c-3accc76470cc

**Comment by JosefNemec** [comment]
Do you have some game or global script set? Do you use Windows 7 (diag. package failed to gather system info for some reason).

**Comment by Fancy2209** [comment]
What do you mean about Global Script or game set?
Also yes I do use windows 7

**Comment by JosefNemec** [comment]
That error means that PowerShell script execution failed. You can assign scripts to be executed on various game events on global (in settings) and game (while editing game on Scripts tab) scopes.

Playnite by default doesn't execute any scripts so this leads me to believe that you have some script assigned somewhere.

Install this to see if it fixes the issue:
https://www.microsoft.com/en-us/download/details.aspx?id=54616

**Comment by Fancy2209** [comment]
I don't have any scripts assigned 
*That I remember* this happened on fresh P9 and P8 worked but let me try

**Comment by JosefNemec** [comment]
Fixed in devel.
