### ISSUE TITLE
You can add the same path in external extensions multiple times

### ISSUE THREAD

**Issue by darklinkpower** [JosefNemec/Playnite#2437]
**Describe the bug**
You can add the same path in external extensions multiple times. Ideally it shouldn't let you add it.

As a side note, it would be great if extensions would be sorted by path

**To Reproduce**
Click "Add" button and input the same path multiple times

**Screenshots**
![image](https://user-images.githubusercontent.com/1389286/132078024-381b6bbe-54c3-46fe-80b3-c6c8336e867d.png)

**Diagnostics ID**
Not applicable

**Comment by JosefNemec** [comment]
Fixed in devel.
