### ISSUE TITLE
P9 Beta: No "select box" for rom adding in the installation section.

### ISSUE THREAD

**Issue by Cr3ViL** [JosefNemec/Playnite#2439]
In the Installation section there is no button to select new roms; to add one, we must paste the link, but at version 8 there was a button to select.

![Untitled-2](https://user-images.githubusercontent.com/84658940/132093788-dc8f4c38-e20f-43aa-a8f0-597d585b1c95.jpg)

**Comment by JosefNemec** [comment]
Done in devel.
