### ISSUE TITLE
Failed to import installed Origin games.

### ISSUE THREAD

**Issue by hammersyko** [JosefNemec/Playnite#244]
Hey there,

For some reason my Playnite can't import my installed Origin games. I have no clue as to how or why :(
My Origin is logged in. It can import all my Origin games; it just doesn't recognize what is installed.
If I can provide more info, you've got to ask me, I have no idea what information would be relevant.

Notification: "Failed to import installed Origin games: Object reference not set to an instance of an object."
Diag. package: [Diag.zip](https://github.com/JosefNemec/Playnite/files/1422657/Debug.zip)

PS: Mandatory I love the software. Getting rid of 5 separate programs and launching one instead... Love it :D

**Comment by JosefNemec** [comment]
Thanks for a report. You can use [this build](http://playnite.link/download/PlayniteInstallerOriginFix.exe) until patch gets out via standard update.

**Comment by hammersyko** [comment]
That totally fixed it; awesome man :D

**Comment by JosefNemec** [comment]
I'll leave this open until it gets into public release.

**Comment by JosefNemec** [comment]
Released in 2.9
