### ISSUE TITLE
P9 Beta - Theme Creation - Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by xyifer12** [JosefNemec/Playnite#2440]
**Describe the bug**
Any themes opened in Blend will cause an "Object reference not set to instance of an object" error and Blend will refuse to render certain view files. LibraryDetailsView.xaml or LibraryGridView.xaml are the two I noticed. The theme seems to work fine in Playnite.

**To Reproduce**
Create a portable Playnite 9 beta installation. Create a new desktop theme using Toolbox. Open the theme's SLN file in Blend and attempt to edit LibraryDetailsView.xaml or LibraryGridView.xaml in visual editor mode.

**Screenshots**
![grid](https://user-images.githubusercontent.com/33806276/132094473-4ca6d531-77f2-482e-8f8e-2fdec31ddc3f.png)
![details](https://user-images.githubusercontent.com/33806276/132094475-bb5962f9-6789-4042-95f7-1d53c4f20e8a.png)

**Diagnostics ID**
6bbf655a-c794-40d6-b385-fd37cb8b1b1d

**Comment by JosefNemec** [comment]
Fixed in devel.
