### ISSUE TITLE
P9 Beta: Add-on update menu has inverted expand/contract symbols

### ISSUE THREAD

**Issue by Jeshibu** [JosefNemec/Playnite#2441]
**Describe the bug**
This concerns the add-on menu (F9), update section.

Usually, clickable things display what their action does, not what their current status is. This is what it's like now:
- Unexpanded: ^ or up symbol
- Expanded: v or down symbol

![image](https://user-images.githubusercontent.com/37979717/132108713-14393732-2ea5-4465-9073-931484a20f5b.png)

What I think it should be (representing what clicking it would do):
- Unexpanded: v or down symbol
- Expanded: ^ or up symbol

Also, the "Updates (2)" section entry on the left menu does not highlight (in blue on the default theme) on mouse-over or when it's selected.

**Comment by darklinkpower** [comment]
I personally think that `v` for expanded is correct. My suggestion is:

- Unexpanded: `>`
- Expanded: `v`

You can see an example of this in GOG Galaxy

Unexpanded:

![image](https://user-images.githubusercontent.com/1389286/132109442-292baeb5-2dfd-4252-ab3d-7f429f4e8f5b.png)

Expanded:

![image](https://user-images.githubusercontent.com/1389286/132109439-7d93f494-a638-4d37-b79b-2af237e8382f.png)

**Comment by Jeshibu** [comment]
That works too. The ^ just looked weird to me.

**Comment by JosefNemec** [comment]
Fixed in devel.
