### ISSUE TITLE
[Playnite 9 Beta] Custom Profile for emulator not scanning

### ISSUE THREAD

**Issue by Jhanlon95** [JosefNemec/Playnite#2442]
**Before creating bug report**
- Please use issue search in the repository first. If the bug is something really obvious there's a high change it was already reported. **Done**

- Make sure that the issue is not caused by custom theme or extension. You can restart Playnite in "safe mode" from help menu to quickly test it. **Done**
- Check list of known issues https://github.com/JosefNemec/Playnite/wiki/Known-Issues **Done**

**Integration issues**
If an issue is related to library integrations, use separate [extensions repository](https://github.com/JosefNemec/PlayniteExtensions) to file a report. **Not Applicable**

**Describe the bug**

There isn't in an in-built PCSX2 profile for RetroArch so wanted to add one as I prefer that emulator over others. When trying to scan for PS2 games by creating a custom profile under Retroarch for PCSX2 I am being given a "<!LOCEmulatedGameScanFailed Object reference not set to an instance of an object.!>

I do have PCSX2 core installed within RetroArch and was previously able to launch them from PlayNite 8

**To Reproduce**
If it's not clear from the description how to reproduce the issue please add clear steps to reproduce the behavior.

Go to "Library -> Configure Emulator -> Click on "RetroArch" under Emulators -> Click "Add" at the bottom of profiles -> set your retroarch executable, under arguments use "-L ".\cores\pcsx2_libretro.dll" "{ImagePath}", working directory to your retroarch folder and supported file types "iso,isz,cso,bin,elf,zip,7z". -> Click "Add Game" -> Add Scanner -> Select RetroArch and your custom profile -> Scan folder" 

**Screenshots**

My PCSX2 profile set up within PlayNite 8
![Playnite DesktopApp_01fvJgdHSm](https://user-images.githubusercontent.com/11045596/132115809-4fd66287-b7ce-4c61-b313-b3573c7d8bdd.png)

My PCSX2 profile set up within PlayNite 9 Beta
![Playnite DesktopApp_A4wwrG2yTk](https://user-images.githubusercontent.com/11045596/132115722-7c5c02c5-9db0-4b39-9425-988dae947798.png)

The error I'm getting when trying to scan
![Zzz1egLmyT](https://user-images.githubusercontent.com/11045596/132115728-c0146561-ed0e-4bd3-8a74-4727e0126e3b.png)

**Diagnostics ID**
Please generate diagnostics package from "About Playnite" menu and attach identifier you received. If the issue is a crash bug, you can generate diag. package directly from crash dialog.
**b5167916-3cfa-4eff-8422-780f33f9bd26**

**Comment by JosefNemec** [comment]
Fixed in devel.
