### ISSUE TITLE
P9 Beta: Error when assigning GameAction via plugin

### ISSUE THREAD

**Issue by darklinkpower** [JosefNemec/Playnite#2443]
**Describe the bug**
Error triggers when assigning GameAction to a game with an existing collection:
`This type of CollectionView does not admit changes to the SourceCollection of a subprocess other than the Dispatcher subprocess.`

**To Reproduce**
It's done with a plugin
Error: Game has a GameAction- > Delete it from Edit Window -> Try to add the GameAction with an extension -> Triggers the error

No error: Game has a GameAction -> Delete it from Edit Window -> Reboot Playnite -> Try to add the GameAction with extension -> Error doesn't trigger

Example of this is here with a woraround: https://github.com/darklinkpower/PlayniteExtensionsCollection/blob/master/source/Generic/NVIDIAGeForceNowEnabler/NVIDIAGeForceNowEnabler.cs#L164-L180

**Screenshots**
![image](https://user-images.githubusercontent.com/1389286/132122092-cba1b0a0-ea78-4833-820b-c2ae777e41f8.png)

**Diagnostics ID**
24e669e6-b721-4e9f-b42d-a4bbdb526a50

**Comment by JosefNemec** [comment]
Fixed in devel.
