### ISSUE TITLE
Playnite 9 Beta - Default Theme Text Boxes Too Small

### ISSUE THREAD

**Issue by xyifer12** [JosefNemec/Playnite#2446]
**Describe the bug**
Some text boxes are too small and only show 4 letters in Default theme.

**To Reproduce**
Install the Playnite 9 beta. Open desktop mode using Default theme. Open game settings, open Actions tab.

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/33806276/132122755-259d20b1-7f33-4e66-ba91-3b98f1ef5ba0.png)

**Diagnostics ID**
e8a79757-944b-448c-8bf1-1b4ce4f1c98a

**Comment by JosefNemec** [comment]
Fixed in devel.
