### ISSUE TITLE
Playnite 9 Addon browser improvements. 

### ISSUE THREAD

**Issue by SlipperyJim** [JosefNemec/Playnite#2447]
**Indicate somehow in the list which ones you already have installed** 
 
Currently in the P9 addon browser, it is only possible to see if you already have an add-on installed by clicking into each one and checking the installation status. It would be nice if there was some indication in the actual list as to whether you already had that add-on installed. Maybe have non-installed ones greyed-out slightly (or do the opposite and have installed ones greyed out)?

**Sort list alphabetically**

The list of addons is currently sorted by how recently they were added (I think). It makes more sense (imo) to have them sorted alphabetically.

**Search Automatically as you type**

It would be good if it searched automatically as you type the name in the search box, similar to how the game browser currently works

**Comment by JosefNemec** [comment]
Done in devel.
