### ISSUE TITLE
Desktop Version appearing very large after switching primary monitors

### ISSUE THREAD

**Issue by mainmango** [JosefNemec/Playnite#2448]
I've noticed the desktop version seems to scale all objects quite large after swapping from my 4k TV to my 1440p monitor. On my 4k TV I would have Playnite open displaying everything fine but when I switch to my 1440p monitor everything on my desktop version appears very large (text, game covers).

Exiting and re-launching desktop version fixes it.

This didn't happen on Playnite 8.

Thanks!

**Comment by JosefNemec** [comment]
Where's the information requested in issue template?
What does "switch to my 1440p monitor" mean? Moving Playnite window to that screen?
Btw there was no change to DPI handling in P9, so the issue must also appear in P8.

**Comment by mainmango** [comment]
**Describe the bug**
Desktop version visual scaling increases significantly after changing my primary monitor from 4k TV to 1440p monitor. Not sure if the resolution difference affects this.

**To Reproduce**
Use 4k tv as primary monitor then switch primary monitor to my 1440p monitor, turn off 4k tv, exit fullscreen playnite and launch desktop version of Playnite. Restarting playnite fixes the issue.

**Screenshots**
![screen1](https://user-images.githubusercontent.com/4985901/133293373-3ddcce42-c204-46f1-9749-6f544a0608d2.png)
![screen2](https://user-images.githubusercontent.com/4985901/133293430-44840fa8-e8f1-4b64-8951-82ea6758fe21.png)

Switch to my 1440p monitor = changing primary monitors

**Comment by mainmango** [comment]
Closing this for now as this might have been caused by DisplayFusion, a 3rd party app to increase multiple monitor functionality. Will re-open if I see if issues persists thanks!

**Comment by JazzJohannes** [comment]
Issue persists here, I do not have any third-party app regulating monitors or resolutions. My quicker fix is, simply re-arranging the monitor order, i.e. big screen swapped with small screen order, then resize on the edge of Playnite's window, then double-click the title bar, and swap back monitor order, and it was fixed.
