### ISSUE TITLE
P9 Beta: Addon browser still lists initial version and release date etc of addon after updating it

### ISSUE THREAD

**Issue by joyrider3774** [JosefNemec/Playnite#2449]
**Describe the bug**
I just updated my Game Speak plugin as it contained a bug. I added the new version to the manifest before the initial release one. P9 correctly detected the update and applied it. However the addon browser still seems to list the initial version i released instead of the latest.

![image](https://user-images.githubusercontent.com/10714776/132129651-d2868f5e-cfec-4978-a50a-8a4827b9df65.png)

https://github.com/joyrider3774/PlayniteGameSpeak/blob/main/GameSpeak.yaml
![image](https://user-images.githubusercontent.com/10714776/132129693-d1061627-bd34-4285-9ca1-51c10e301e87.png)

This also happens with the duplicate hider plugin

![image](https://user-images.githubusercontent.com/10714776/132129722-c93407a6-b17f-4cbc-b0c8-2f4c59b13209.png)
![image](https://user-images.githubusercontent.com/10714776/132129748-0449eea2-3591-4296-84be-e155c7eb471e.png)

**To Reproduce**
check addon browser, for mentioned addons

**Diagnostics ID**
9db7ea65-5c0c-4eba-a6ba-31ad3b1f7b85

**Comment by JosefNemec** [comment]
Fixed in devel.
