### ISSUE TITLE
P9 Beta: Search icon in SearchBox no longer shows after selecting it once

### ISSUE THREAD

**Issue by darklinkpower** [JosefNemec/Playnite#2450]
**Describe the bug**
Search icon in SearchBox no longer shows after selecting it once

**To Reproduce**
Select the Searchbox once. After deselecting it, the search icon will no longer show even if text was not entered.

Edit: Found a fix. You need to press enter, then click the delete button on the right side and the icon will show again.

**Screenshots**
Before selection:
![image](https://user-images.githubusercontent.com/1389286/132165324-88494007-86b2-4d7d-893d-e2461e120d79.png)

Selection:
![image](https://user-images.githubusercontent.com/1389286/132165353-3d229ea8-7599-480f-997c-b947ca035c8d.png)

No longer selected (Search icon doesn't show anymore)
![image](https://user-images.githubusercontent.com/1389286/132165371-f009f7f2-033a-44be-a45f-5fae787a7b4e.png)

As a side note, the name searchbox in the filters panel doesn't have a search icon at all but I don't know if it's intended
![image](https://user-images.githubusercontent.com/1389286/132165515-47d88f05-bd22-4bc7-95a6-94e1b3e9bc55.png)

**Diagnostics ID**
Not applicable.

**Comment by JosefNemec** [comment]
Fixed in devel.
