### ISSUE TITLE
P9 Beta: Don't allow filter presets with the same name and confirm if should be replaced

### ISSUE THREAD

**Issue by darklinkpower** [JosefNemec/Playnite#2452]
**Describe the solution you'd like**
Currently you can have multiple filters with the same name, which doesn't make sense because they can have different filters and you can't identify them.

Proposals:
- Don't allow for multiple filters with the same name
- If a filter with the given name already exists, ask user if wants to overwrite it

**Comment by JosefNemec** [comment]
Done in devel.
