### ISSUE TITLE
P9 Beta: Add button to load saved presets name in the filter presets save window

### ISSUE THREAD

**Issue by darklinkpower** [JosefNemec/Playnite#2453]
**Describe the solution you'd like**
Linked with #2452, would allow for easier and quicker modifying of existing filters.

Proposed:
- Add button to load saved presets name in the filter presets save window
- If there's a filter currently loaded in the Main View, have its name entered by default when opening the window.

**Screenshots**
![image](https://user-images.githubusercontent.com/1389286/132218403-50e26fcb-881c-4448-85cd-5f051a47781a.png)

**Comment by JosefNemec** [comment]
I don't like an idea of having additional button there to just load a string from existing preset, but I will fill in selected preset's name there.

**Comment by JosefNemec** [comment]
Actually, that doesn't make sense because there can't be any selected for this to appear.
