### ISSUE TITLE
P9 Beta: Performance issues when scrolling in Grid View when grouping is enabled

### ISSUE THREAD

**Issue by darklinkpower** [JosefNemec/Playnite#2454]
**Describe the bug**
Scrolling in Grid view over collapsed groups causes severe performance issues.

**To Reproduce**
- Set any grouping
- Switch to grid view
- Collapse all groups, open one and scroll over collapsed groups.

My guess is that Playnite is loading items that are inside the collapsed groups even when they are not viewable.

**Screenshots**
Scrolling like this would cause the mentioned issue
![image](https://user-images.githubusercontent.com/1389286/132218948-139a6954-8298-42ea-b12b-1234f9074252.png)

**Comment by JosefNemec** [comment]
I can't reproduce it. Are you sure it's not a theme issue?

**Comment by darklinkpower** [comment]
Default theme.

The video might not be clear enough because my PC is not capable to record at 60 fps and the stutters are worse than what can be seen in the video. The most noticeable slowdown/stutters is in the scroll at 0:54



https://user-images.githubusercontent.com/1389286/134331079-eabb2e68-649d-4805-aed7-5965fb819362.mp4

Some points:
- Notice the CPU usage. It around 10% at maximum when scrolling through already loaded items. When scrolling over collapsed groups, it jumps to around 30%.
- Notice how when going over the last group to the first group again, the items in the first group no longer have its cover images cacheed. I assume this is because the covers of the items in the collapsed groups are added to the cache during the scroll, the cache reached its limit and the covers of the items in the first group are the first to get removed and need to be cacheed back when returning to it.

**Comment by darklinkpower** [comment]
I just noticed that also the memory usage has drastic changes when scrolling through collapsed items.

**Comment by JosefNemec** [comment]
Will have to wait for  #2499

**Comment by darklinkpower** [comment]
Would it be possible to have a setting to completely disable grouping only in Grid View? Considering the performance issues, some people might prefer to not have grouping when using Grid View and having to change the selected group option each time the user switches to or from Grid View could be undesired.

**Comment by JosefNemec** [comment]
Workaround in devel, I hate it.

**Comment by darklinkpower** [comment]
*oh no*
