### ISSUE TITLE
P9 Beta: Platform media is not working / showing.

### ISSUE THREAD

**Issue by joyrider3774** [JosefNemec/Playnite#2457]
**Describe the bug**
Assigned platform media is not showing when you setup playnite 9 to display platform media in case of missing game media. 

**To Reproduce**
Setup playnite to show platform media for all missing media inside settings. Assign platform media to certain platform. Add new game assign this platform or edit a game using this platform and remove all game media. Check in details view when having playnite setup to show icons in the list or check the other media game details it won't show. At least nog with me

From what i saw when recompiling code & debugging Platform in GamesCollectionViewEntry remains empty / null

**Screenshots**
![image](https://user-images.githubusercontent.com/10714776/132328443-bc62e227-016f-42ee-924a-c07e9c5588fa.png)

![image](https://user-images.githubusercontent.com/10714776/132329680-1baf0c9e-f35c-46f6-ad1e-4d5d79db28dd.png)

**Diagnostics ID**
8f7bc237-0b94-40c4-b43d-2b308d20c7c0

**Comment by JosefNemec** [comment]
Fixed in devel.
