### ISSUE TITLE
P9 Beta: Updating a theme via the addon updater switches to it on restart

### ISSUE THREAD

**Issue by darklinkpower** [JosefNemec/Playnite#2459]
**Describe the bug**
P9 Beta: Updating a theme via the addon updater switches to it on restart, even if it's not the currently active theme.

**To Reproduce**
Install a theme, switch to another theme and wait for a push of an update. Alternatively, install an older version of a theme to be notified of the update.

**Screenshots**

**Diagnostics ID**

**Comment by JosefNemec** [comment]
Fixed in devel.
