### ISSUE TITLE
P9 Beta: "Save Changes" hint does not appear with all checkboxes in all tabs

### ISSUE THREAD

**Issue by joyrider3774** [JosefNemec/Playnite#2463]
**Describe the bug**
After having used download metadata, extra checkboxes appear to save changes or not. It would appear that some of these checkboxes have a tooltip hint "save changes" but they do not appear for all checkboxes in all tabs. For example from what i can see they do not appear with these checkboxes in media, general and advanced tab. Yet the checkboxes in installation, actions and scripts tab do show them.

**To Reproduce**
download metadata, hoover mouse over any of the checkboxes mentioned in the tabs above

**Screenshots**

https://user-images.githubusercontent.com/10714776/132423716-cfba77b1-9e87-4d82-a5e3-9f922d37c1ab.mp4

**Diagnostics ID**
Please generate diagnostics package from "About Playnite" menu and attach identifier you received. If the issue is a crash bug, you can generate diag. package directly from crash dialog.

**Comment by JosefNemec** [comment]
Fixed in devel.
