### ISSUE TITLE
P9 Beta: "Save changes" checkboxes behave differently for Score, playcount and playtime fields compared to other fields, like rechecking save changes checkbox on focus (lost) if data different

### ISSUE THREAD

**Issue by joyrider3774** [JosefNemec/Playnite#2464]
**Describe the bug**
The "Save changes" checkboxes behave differently for Score fields compared to other fields. For one normal string fields seem to immediatly check the checkbox on typing a first letter while score checkboxes don't do this, but this is normal i think as the value gets validated. However what may be unwanted behaviour is if we have a value in any score field that is different from original value and we disable the save changes checkbox it will automatically recheck itself just by having given the score fields focus. All other fields don't seem to do this even if data was changed. My guess is this could be related to the validation as well somehow but it might be unwanted behaviour as one could accidently recheck these save changes checkboxes after they loose focus overwriting users data when they did not want it (for example if they had accidently refocused the score field after disabling the checkbox and then going to a different tab, the user will not see that the save changes checkbox rechecked itself)

side note: playcount and playtime fields have same potential problem

**To Reproduce**
see (complete) video to see what i mean

**Screenshots**

https://user-images.githubusercontent.com/10714776/132425254-d3259d53-90ac-4451-9bf8-6ad18a83c8c7.mp4

The potential "dangerous" data overwrite problem
https://user-images.githubusercontent.com/10714776/132426892-d3437f56-26bb-4f0d-8e78-c93db485c12a.mp4

**Comment by JosefNemec** [comment]
Fixed in devel.
