### ISSUE TITLE
Playnite 9 Beta: Fullscreen 'Hidden' and 'Favorite' checkbox filters display wrong games

### ISSUE THREAD

**Issue by TheKersalMassive** [JosefNemec/Playnite#2469]
**Describe the bug**
When in Fullscreen and using the filter panel, the 'Hidden' and 'Favourite' checkboxes display each others games instead of the respective filter.

**To Reproduce**
In Desktop, select 'Hidden' checkbox in Filter Panel, which will display 'Hidden' games. Same for 'Favourites' checkbox which will display games marked as 'Favourite'. 
This works correctly as intended.

In Fullscreen (in default and custom themes) when 'Hidden' checkbox is checked, it shows 'Favourite' games instead.
Same for 'Favourites', it displays 'Hidden' games instead of 'Favourites'.

**Screenshots**
Screenshot 1: Shows list of games filtered as 'Favourite'

![Screenshot 1](https://user-images.githubusercontent.com/90322803/132503715-b1b45adf-5510-4a98-bb6a-926299665252.png)

Screenshot 2: Shows same list of games tagged as 'Favourite' but 'Hidden' is checked.

![Screenshot 2](https://user-images.githubusercontent.com/90322803/132503739-12cfe286-3d67-4bd3-aa7f-8185201b90e0.png)

**Comment by JosefNemec** [comment]
Fixed in devel.
