### ISSUE TITLE
Mobile Version

### ISSUE THREAD

**Issue by shanazzlowe** [JosefNemec/Playnite#247]
Just as an idea for far future, would if a mobile version of playnite was created. It would probably have to turn into it's own project where as mobile coding is very different from desktop.
It also would most likely have to be android because it is the most open platform. But i was thinking of possibly creating it as android launcher, to basically turn android devices into a handheld gaming system for on the go gaming. Maybe something like the psvita. It would also require that basic android launcher functionality to still exist in order to have the capability of removing it if desired

**Comment by shanazzlowe** [comment]
I apologize in advance if this has already been mentioned

**Comment by JosefNemec** [comment]
I think that's a completely different project with different target audience, different technological background and I'm personally not interested in developing for mobile.

**Comment by shanazzlowe** [comment]
Alright that's fine, just wanted to get the idea out there at most

**Comment by JosefNemec** [comment]
Will be done as part of #247

**Comment by JosefNemec** [comment]
I don't know why I closed this with reference to the same issue, sorry about that.

Anyways I thought about this again and I think it could be very useful at least as an emulation front end. I have no idea how the emulation ecosystem on mobile looks right now, so maybe this won't be needed because there is some super cool app available already.

**Comment by darklinkpower** [comment]
There's RetroX for android, although i'ts more like a mobile version of EmulationStation, it may not be as feature complete like Playnite for PC but I think it does the job pretty well for mobile devices
https://www.youtube.com/watch?v=25wR-S6Vhj0

There are other options too

**Comment by JosefNemec** [comment]
I'm marking this as duplicate to #323. I can't see myself doing proper mobile launcher for mobile, but companion app to desktop Playnite is realistic.
