### ISSUE TITLE
Playnite 9 Beta: No restart dialog when changing themes in Fullscreen mode

### ISSUE THREAD

**Issue by TheKersalMassive** [JosefNemec/Playnite#2470]
**Describe the bug**
When selecting a new theme in Fullscreen mode, there is no popup dialog to suggest a restart as there was previously in Playnite 8.
When a new theme is selected, nothing happens. You need to exit to desktop and return to fullscreen to see new theme.

This also applies to other options that require restart.

**Comment by JosefNemec** [comment]
Fixed in devel.
