### ISSUE TITLE
P9 Beta2: Failed to open library database

### ISSUE THREAD

**Issue by yrvn** [JosefNemec/Playnite#2471]
First run of beta2 on portable P8 and got this message. No games after pressing ok.

![image](https://user-images.githubusercontent.com/220171/132539799-004d8882-03fa-411e-ba5f-e51945e90899.png)

Closed and opened it again and I can see only the count of games I had installed/hidden but can't see any of them.

![image](https://user-images.githubusercontent.com/220171/132541419-5e9702d4-7a34-4a4e-94ea-a2b83b910be0.png)

Diagnostics ID: 463f1e70-1f4f-4f6e-b600-93244c8a0abf

**Comment by JosefNemec** [comment]
Try clearing filters, if the count shows games, then it means they were migrated correctly.

The error shown is from unrelated part of the app that I will fix, it didn't break anything in the library.

**Comment by yrvn** [comment]
I did press clear filters before posting and nothing happened. But now that you mentioned I restarted the app and now I see the games.

Thanks for the answer!

**Comment by JosefNemec** [comment]
Fixed in devel.
