### ISSUE TITLE
Anchor tags with an id attribute do not show up as links

### ISSUE THREAD

**Issue by azuravian** [JosefNemec/Playnite#2473]
**Describe the bug**
In the game description section, anchor tags that have an id attribute set are not clickable links.  They have the appropriate font color for links, but cannot be interacted with.  In many cases, description html downloaded from steam or other sources contains id attributes on links.  This effects both Playnite 8 and P9 Beta.

**To Reproduce**
Edit description of game with link.  Add id attribute with any unique name to the link.  Save changes.

**Screenshots**
![image](https://user-images.githubusercontent.com/7379812/132721909-636689db-a062-4c40-9e3b-1a4384630152.png)

**Comment by JosefNemec** [comment]
Sadly, won't fix. The control we use for descriptions is no longer being developed and I personally don't have time making fixes for 3rd party libraries. We are also planning to move from HTML to markdown descriptions in future.
