### ISSUE TITLE
P9 Beta 2: Error "The subprocess that makes the call can not get access to this object..."

### ISSUE THREAD

**Issue by darklinkpower** [JosefNemec/Playnite#2475]
**Describe the bug**
You get this error message on startup. The database appears to have not opened correctly because as seen in the screenshot, while the explorer panel listbox is populated, the combobox is not.

```
Failed to open library database.

The subprocess that makes the call can not get access to this object because the owner is another subprocess.
```

**To Reproduce**
Has happened when:
a) Restarting Playnite, by disabling extension, changing theme, etc.
b) When closing Playnite and starting it again.

I suspect it only happens when using a custom theme and possibly requires having the explorer panel open.

**Screenshots**
(Note: Colors are from a custom theme)
![image](https://user-images.githubusercontent.com/1389286/132800560-df2f22e8-d8f6-4ce1-8a85-318a541fbce2.png)

**Diagnostics ID**
20e1d690-e951-47d8-87f6-5faaa8d1d950

**Comment by JosefNemec** [comment]
Duplicate to #2471
