### ISSUE TITLE
Create separate constant for separation borders in certain windows

### ISSUE THREAD

**Issue by darklinkpower** [JosefNemec/Playnite#2476]
**Describe the bug**
There are certain windows that are not stylable in custom themes. I've identified some borders that use a brush that are in themes and to modify those borders, you have to modify this key, which affects all other things that also use the brush.

The proposal is to create a separate constant for just these inaccessible elements.

Currently they use `NormalBorderBrush`
**To Reproduce**
Not applicable.

**Screenshots**

![image](https://user-images.githubusercontent.com/1389286/132865823-9404c7d9-34e7-4a90-a36a-c13ccc7da2dd.png)

![image](https://user-images.githubusercontent.com/1389286/132865883-78e2193a-858f-4c52-a6c6-e2573538a7fe.png)

![image](https://user-images.githubusercontent.com/1389286/132865927-8c8abbf0-e43c-4559-954c-7edbd1947cd0.png)

**Comment by JosefNemec** [comment]
Done in devel.
