### ISSUE TITLE
Playnite 9 Beta: Focus follows highlighted game rather than skipping to first game in filter when navigating between quick filters in fullscreen

### ISSUE THREAD

**Issue by Super1337Boy** [JosefNemec/Playnite#2477]
**Describe the bug**
When navigating between quick filters in fullscreen, focus follows the game you had selected in the previous filter (provided it is present in the next one), instead of skipping to the first game in the next filter. This wasn't the case in Playnite 8, and it makes for a disorienting experience.

If it is intentional, maybe it would be possible to add an option to choose between behaviors.

**To Reproduce**
1. Make sure the same game is present in two different quick filters in fullscreen.
2. Highlight the game and switch between the filters with the bumper buttons or F2 and F3.

**Screenshots**
https://user-images.githubusercontent.com/6672819/132922958-86fe6a64-16cf-4c72-b779-eca04b70d171.mp4

**Comment by philipjholm** [comment]
It is especially weird when going from a filter for example platform "PC" games and then to jump to a filter for "Recently added". This results to me in a empty screen with no games. Only when I click on the left d-pad button it shows again.

**Comment by JosefNemec** [comment]
Fixed in devel.
