### ISSUE TITLE
Playnite 9 Beta: Not possible to navigate to the update button with a controller in fullscreen mode

### ISSUE THREAD

**Issue by Super1337Boy** [JosefNemec/Playnite#2478]
**Describe the bug**
In Playnite 9 you can no longer move selection hightlight up to the buttons in the top right corner. The Settings Pane can obviously be opened with the Select button instead, but as far as I can tell there is no way to hit the update button without using a mouse.

**Comment by JosefNemec** [comment]
Fixed in devel.
