### ISSUE TITLE
Ability to close the filter column by pressing the B button in fullscreen mode

### ISSUE THREAD

**Issue by Super1337Boy** [JosefNemec/Playnite#2479]
**Describe the solution you'd like**
A small suggestion for improving navigation in fullscreen mode: 

Adding the ability to close the Filter Column by pressing the B button in addition to the right stick.

Using B as a back button is the standard in most game interfaces, and I keep hitting it expecting the Filter Column to close. It would also be more consistent with how the Settings Pane is closed by hitting B instead of Select.

**Comment by JosefNemec** [comment]
Done in devel.
