### ISSUE TITLE
Manual sorting

### ISSUE THREAD

**Issue by evgdovg1996** [JosefNemec/Playnite#248]
It would be very cool to choose order of games on the list.
Is this possible?

**Comment by JosefNemec** [comment]
Yes, click on the `...` button on top panel.

**Comment by evgdovg1996** [comment]
@JosefNemec But.. where is it?) 
There's only in ascending and descending and others(not manual choosing), is not it?

**Comment by JosefNemec** [comment]
I don't understand what do you mean by "manual" then. You can sort by all fields that are available for each game, what else would you want?

**Comment by evgdovg1996** [comment]
@JosefNemec something like this 
https://imgur.com/JYxd9O6
Analog, something like : sort by name + release date

**Comment by JosefNemec** [comment]
I see, that will be possible after #84 is done.
