### ISSUE TITLE
Adding separate template styles for each button in Main, Game & Settings Menus

### ISSUE THREAD

**Issue by TheKersalMassive** [JosefNemec/Playnite#2481]
**Check for existing issue**
Playnite 9 (beta) removes the ability to customise and style Main Menu and Setting menu buttons such as PART_ButtonSettings, PART_ButtonUpdateLibrary, etc.
Previously in Playnite 8, you could customise these buttons to style individually and also add icons to each entry (as per screenshot below in the XBOX theme).
I believe other themes also took advantage of this such as the PS5'ish theme for example.

**Describe the solution you'd like**
- Add a separate template to style these buttons that appear in the menus for Main, Game & Settings menus.
- Ability to modify menu header text and icons/logos as per P8.

**Screenshots**
Example below for XBOX theme:
![3ezFzVn](https://user-images.githubusercontent.com/90322803/132946667-a225b9af-ff36-4d5d-aa3b-0b1cdc51f3eb.jpg)

**Comment by TheKersalMassive** [comment]
Just to add the same for the menu headers such as Notifications, where it would be good to customise the bell icon (html reference) as well as add those for settings header

**Comment by JosefNemec** [comment]
Done in devel.
