### ISSUE TITLE
Playnite 9 Beta: Image Rendering Scaler dropdown is disabled when 'Always use primary display' is checked

### ISSUE THREAD

**Issue by TheKersalMassive** [JosefNemec/Playnite#2483]
**Describe the bug**
When you check 'Always use primary display' which correctly disables the 'Target Display' dropdown, but also disables the 'Image Rendering Scaler' dropdown too. 
When you deselect the 'Always use primary display' , the image rendering scaler dropdown works as intended.

**To Reproduce**
Settings > General > check 'Always use primary display' and then try to change 'Image Rendering Scaler' option.

**Screenshots**
![unknown](https://user-images.githubusercontent.com/90322803/133094879-9404f7a0-4a3a-4896-830b-679c48813411.png)

**Comment by JosefNemec** [comment]
Fixed in devel.
