### ISSUE TITLE
P9 Beta: Active filters get reset to the selected filter preset after each restart

### ISSUE THREAD

**Issue by darklinkpower** [JosefNemec/Playnite#2484]
**Describe the bug**
Active Filters get set to the filters of the last selected filter preset in the combobox, even if active filters got changed after it last loaded. Can probably be linked to #2451

**To Reproduce**
1. Save any filter preset with any set of filters so there's a filter preset in the combobox
![image](https://user-images.githubusercontent.com/1389286/133129195-73796dc6-72c8-4ec4-b2e6-d1d5da6fed85.png)

2. Change active filters
![image](https://user-images.githubusercontent.com/1389286/133129305-b7466e87-00cb-4486-9b13-1636432b3bb0.png)

3. Restart Playnite. Upon reboot, you will see that the filters that were active before shutdown get loaded again while the library is loading, but will be set again to saved filters in the filter preset that is in the combobox

![image](https://user-images.githubusercontent.com/1389286/133130008-7575874d-4343-46c8-bf49-e72d6597e984.png)

**Screenshots**
Added in previous section

**Diagnostics ID**
d0ce1b29-4f25-4a22-ac58-082f1caf9d4c

**Comment by JosefNemec** [comment]
Caused by #2451
