### ISSUE TITLE
P9 Beta: Unrecoverable error on startup if you enter a file path in extensions dev path instance

### ISSUE THREAD

**Issue by darklinkpower** [JosefNemec/Playnite#2485]
**Describe the bug**
Unrecoverable error on startup if you enter a file path in extensions dev path instance instead of a directory path

My suggestion is:
- Verify that the entered path is not a file when adding
- Verify that the entered path is not a file when starting Playnite and skip if that is the case

**To Reproduce**
1. Add a path of a file in the extensions developer tab in settings
2. Restart Playnite

**Screenshots**
![image](https://user-images.githubusercontent.com/1389286/133242744-e226e9ff-c1b7-442d-9ee2-7b4d9e063c4b.png)

**Diagnostics ID**
ecf5f995-39f8-4572-a929-336104c97648

**Comment by JosefNemec** [comment]
Files are supported, you can put extension directories into a file (one per line) and then add that into Playnite. But we probably don't protect against unsupported formats.

**Comment by JosefNemec** [comment]
Fixed in devel.
