### ISSUE TITLE
P9 Beta 2: Creating a new PS extension with toolbox doesn't update manifest Id and Name properties with creation name

### ISSUE THREAD

**Issue by darklinkpower** [JosefNemec/Playnite#2486]
**Describe the bug**
Creating a new PS extension with toolbox doesn't update manifest Id and Name properties with creation name

**To Reproduce**
1. Create a PS extension as instructed in [the docs](https://playnite.link/docs/devel/tutorials/extensions/scripting.html#creating-script-extensions), changing the extension name
2. Verify content of the manifest. It's still using placeholder info and empty gui, while in previous releases it got correctly set

**Screenshots**

![image](https://user-images.githubusercontent.com/1389286/133244355-a85d660f-89ff-4f2e-ae9c-6074c40a3891.png)

![image](https://user-images.githubusercontent.com/1389286/133244450-4404c793-c3c8-441b-addd-59f5913e8465.png)

**Diagnostics ID**
Not applicable.

**Comment by JosefNemec** [comment]
Fixed in devel.
