### ISSUE TITLE
Playnite 9 Beta : Unable to use all sorting parameters 

### ISSUE THREAD

**Issue by NoAccount1** [JosefNemec/Playnite#2489]
**Describe the bug**
On small screens, some of the drop-down menu items are inaccessibles (this bug wasn't present on Playnite 8)
*PS : my screen is 1366x768*

**Screenshots**
![image](https://user-images.githubusercontent.com/74969657/133493256-532abf55-6ed3-4bf1-a452-5aa31b1df1d7.png)

**On small screens it is also not possible to see the wallpaper and the game buttons at the same time**

![image](https://user-images.githubusercontent.com/74969657/133493727-dd07cc8e-6a05-4fc7-8861-b4186b704057.png)
![image](https://user-images.githubusercontent.com/74969657/133493771-8dc2a3ba-6169-423f-b19f-8c516c8a9fd2.png)

**Comment by JosefNemec** [comment]
Duplicate to #2455
