### ISSUE TITLE
Potential Enhancements to PlayniteApi.MainView.SelectGame()

### ISSUE THREAD

**Issue by bburky** [JosefNemec/Playnite#2495]
When implementing my [Playlist extension](https://github.com/bburky/playnite-playlist), I didn't want to reimplement the entire Library UI. Instead, I added a "Show in Library" button that takes the selected games in the Playlist view and selects them in the Library. Then the user can see more information about the game or make batch modifications to multiple games.

There are some minor issues though:
* There's currently a bug that only the Details view correctly scrolls the selection into view. See #2493
* I can only select one game with this API, I might want to set the selection to multiple games
* The selected game might be excluded from the current set of filters.

I'm thinking an improvement might be to have `PlayniteApi.MainView.SelectGame()`:

1. Select the game like it does currently
2. Scroll the list to display the selected game (Fix [#2493](https://github.com/JosefNemec/Playnite/issues/2493))
3. If (and only if) the current filters exclude the selection, clear the filters

Not sure how to handle multiple games with that, maybe just use the first game in the list for step 2. And passing in a list is a breaking API change, whereas the rest of that isn't. (Multiple selection is probably a lower priority concern, I suppose the only use case is batch modification.)

I could try writing PR for the "clear filters if selection is excluded" bit if you want me to. Not sure where you would want that though, maybe the setter for `SelectedGame` in `DesktopAppViewModel`?

**Comment by JosefNemec** [comment]
I don't think I agree with the fact that game selection should be clearing filters.

**Comment by bburky** [comment]
Ok. It could be done through a separate API. The issue is I won't know if a game is visible due to the current set of filters or not. I wouldn't  want to clear filters unnecessarily.

I just thought it might be a good fit into the existing API. There's no APIs to query the filtered game list, so I'm not sure what a different implementation would look like.

**Comment by JosefNemec** [comment]
Closing, I've added new ways of selecting games and P10 has filters completely exposed in the SDK.
