### ISSUE TITLE
Gog metadata localized ro native language, need to force english

### ISSUE THREAD

**Issue by v00d00m4n** [JosefNemec/Playnite#250]
Gog metadata has localization for everything, even game names, I'm not sure how they detect that I'm in Russian when they give away metadata (probably by ip), but it has to be forced in English, otherwise it looks ugly and confusing. Some localized name makes game unrecognizable, they mess up sorting as well, and mixed language titles just look weird like "SOME TITLE: подназвание" instead of "SOME TITLE; Subtitle", Ведьмак 3 Дикая Охота instead of The Witcher 3 Wild Hunt

I suppose same happens to other non English speaking users.

**Comment by JosefNemec** [comment]
Can you please post content of [this link](http://api.gog.com/products/1207664643?expand=description) when you visit it via browser? Thanks

**Comment by JosefNemec** [comment]
Released in 3.0
