### ISSUE TITLE
PN8 & PN9B : can't change zoom level with keyboard arrows

### ISSUE THREAD

**Issue by SeeDborg** [JosefNemec/Playnite#2500]
Hello,
This is a little bug I noticed for a while on Playnite 8. It's still present on the beta of Playnite 9.

In grid mode, if we click on the zoom level then we push arrow keys on keyboard, the bar is moving but the icons don't get smaller or bigger.

For example, doing this, I can put the bar at maximum but have small icons : 
![image](https://user-images.githubusercontent.com/7523821/134467104-dce379b1-e129-4417-8259-032e4fa0af8c.png)

**Comment by JosefNemec** [comment]
Fixed in devel.
