### ISSUE TITLE
P9 Beta: Suggestion to show the description first in addon browser

### ISSUE THREAD

**Issue by darklinkpower** [JosefNemec/Playnite#2501]
**Describe the solution you'd like**
Move the description to above the screenshots in the addon browser. I think it makes more sense to have it first, otherwise you have to scroll all the way down if there are screenshots.

**Screenshots**
![image](https://user-images.githubusercontent.com/1389286/134512444-df399018-9ee0-404a-bd37-292027a1b86f.png)

**Comment by JosefNemec** [comment]
Done in devel.
