### ISSUE TITLE
Handle multiple plugin upgrades

### ISSUE THREAD

**Issue by Terrance** [JosefNemec/Playnite#2503]
## Describe the solution you'd like

Currently, plugins seems to have to be updated one at a time, either by opening or dragging/dropping a single .pext file, and Playnite requires a restart after each one (saying No to the restart cancels the installation).

It would be nicer to accept multiple dropped files, or to allow a delayed installation when Playnite exits.

## Screenshots

![Installation prompt](https://user-images.githubusercontent.com/4025899/134786567-fb66e0fd-1551-4c0c-8eed-4c92c33e99e0.png)
![Restart prompt](https://user-images.githubusercontent.com/4025899/134786576-2e19278d-3626-4781-a0ee-7eca1936ad72.png)

**Comment by JosefNemec** [comment]
Already done in Playnite 9 via new add-on manager.

**Comment by Terrance** [comment]
I've updated to Playnite 9 now, but it seems like installing from .pext files still requires a restart between each one?  (I have a couple of plugins from GitHub that aren't in the add-on browser.)
