### ISSUE TITLE
Plugin.OpenSettingsView() does not apply theme correctly on some elements

### ISSUE THREAD

**Issue by felixkmh** [JosefNemec/Playnite#2506]
**Describe the bug**
When opening a plugin's settings view using the OpenSettingsView() method, some elements don't get the theme applied correctly, like the color of the text of TextBlocks. This also happens with the Default theme.

**To Reproduce**
Open some settings view that contains TextBlocks by calling OpenSettingsView().

**Screenshots**
Example using SteamGridDB settings:
<details>
  <summary>Using Add-ons menu:</summary>

![grafik](https://user-images.githubusercontent.com/24227002/135090082-1f579552-0cda-40bf-8cd5-31b97ad13d90.png)

</details>
<details>
  <summary>Using OpenSettingsView():</summary>

![grafik](https://user-images.githubusercontent.com/24227002/135090068-cb064ea0-9511-4076-95ad-a0c5b3541db8.png)

</details>

**Comment by JosefNemec** [comment]
Fixed in master.
