### ISSUE TITLE
Export Data

### ISSUE THREAD

**Issue by shangles** [JosefNemec/Playnite#2513]
I was looking for a way to easily export data from a filtered list.

For example, I filtered my list of games to just show games from Amazon library.  I want to be able to select all the results and either copy those names or export them to a list quickly.

Is this possible to do now or in the future?

**Comment by dbuteau** [comment]
months ago i've done an extension which do that: 
https://github.com/dbuteau/multiplayer-exporter

long time i've not used it, don't know  if it stil compatible with last releases

**Comment by JosefNemec** [comment]
There's export extension (installed with Playnite by default) that's repetitively simple and you can modify it to your needs.

**Comment by shangles** [comment]
Ahh.. I knew I was probably missing something.  I found the Export Library option in the Extensions menu and exported to .csv where I can filter by Amazon.  You're the best!
