### ISSUE TITLE
Sorting by platform/age rating/completion status does not work

### ISSUE THREAD

**Issue by Jeshibu** [JosefNemec/Playnite#2515]
**Describe the bug**
Especially noticeable in list view; several columns don't respond to sorting by them. These are:
- Platform
- Age rating
- Completion status

The games look to be sorted by name instead, but I assume that's a fallback.

**Comment by joyrider3774** [comment]
Region has the same problem

**Comment by JosefNemec** [comment]
Completion status is working for me.

**Comment by Jeshibu** [comment]
Confirmed working for me too, don't know how that happened.

**Comment by JosefNemec** [comment]
Fixed in master.
