### ISSUE TITLE
On version 9.1, fullscreen mode doesn't properly update quick filter tabs with long lists

### ISSUE THREAD

**Issue by leftweet** [JosefNemec/Playnite#2516]
**Describe the bug**
When a quick filter tab on fullscreen mode has more than 10 games, launching a game in the 3rd position of the tab's list won't update the sorting of the quick filter. This is noticeable on quick filter tabs that are sorted by "recently played." 

Launching games in positions other than the 3rd position update the tab properly (at least with the first 7 games; I didn't try launching games past the 7th position). Also, if the quick filter tab has 10 games or fewer, the tab updates properly when launching a game in the 3rd position (as well as games in any other position).

**To Reproduce**
Have a quick filter tab with more than 10 games and sorted by recently played. Launch the game in 3rd position. When returning to Playnite, the tab won't have updated its list (so the game in 3rd position is still in 3rd position). If you switch to a different tab and then switch back to the recently played tab, the recently played tab becomes properly updated.

I found this on Playnite 9.1, and tested on my existing installation and a portable version. I also tried un-enabling all my extensions in the existing installation, as well as using the default theme. The portable version had no third-party extensions or themes installed. Also, I only tested with horizontal scrolling turned on.  

**Diagnostics ID**
7f4a6f1b-6951-498b-99ac-9f1b97863da6

**Comment by JosefNemec** [comment]
Duplicate to #1995. I had to revert I've made for it at the last minute because it was breaking other things. It's a bug in UI framework we are using and workarounds will cause issues in other places. It will have to wait for #2499
