### ISSUE TITLE
Filters Save in tab

### ISSUE THREAD

**Issue by dbuteau** [JosefNemec/Playnite#2517]
Could it be possible to implement the possibility to save our favorites filters under tabs presentation?
For example in this screen shot:
![image](https://user-images.githubusercontent.com/1951286/135745930-2517814d-2d07-4f91-a724-7047652d3c93.png)

when we wrote text into the textfield (the red rectangle on the screenshot) an click on the button ( the red square) it save the all filter options currently used and save it as tabs ( green rectangles ont the screenshot) with name we given previously

**Comment by JosefNemec** [comment]
Already implemented in Playnite 9.
