### ISSUE TITLE
GIFs in Game Description don't load

### ISSUE THREAD

**Issue by OsoaGitHub** [JosefNemec/Playnite#2519]
**Describe the bug**
When a game description have a .gif URL in it, it will display a black box instead of the correct gif.

**To Reproduce**
1. Make a new game called 'The Witcher Enhanced Edition'
2. Using [this](https://playnite.link/forum/thread-113.html) plugin, scrape the game with Steam
3. Look in the description to see the black screen gif.

**Screenshots**
![image](https://user-images.githubusercontent.com/33041004/135760207-93a26428-352b-440b-9564-4b292367c0c9.png)

**Diagnostics ID**
46f92ced-2009-4cb5-8853-34b88803ef30

**Comment by JosefNemec** [comment]
Only first frame will be shown, gif is not a supported format in control we use to render HTML descriptions.

**Comment by OsoaGitHub** [comment]
> 
> 
> Only first frame will be shown, gif is not a supported format in control we use to render HTML descriptions.

so, will it ever play properly?

**Comment by JosefNemec** [comment]
No, as I said, gif is not supported.
