### ISSUE TITLE
Allow display of filename for distinguishing duplicate roms

### ISSUE THREAD

**Issue by vgambier** [JosefNemec/Playnite#2522]
I'd like to request [a feature that was mentioned in the forums](https://www.playnite.link/forum/thread-469-post-5556.html): a way to be able to distinguish pseudo-duplicate roms within the library.

If you import many similar roms, you end up with "duplicate" games - some people want to hide the duplicates and there's already an extension for that, but I would like to keep all duplicates visible, while being able to distinguish them somehow.

![Roms you import](https://user-images.githubusercontent.com/38285114/135873176-e4aa997e-17ad-4f44-9d76-d961313b172b.png)
*Roms you import*

![Games in Playnite after import](https://user-images.githubusercontent.com/38285114/135873173-1138e00c-7fdb-42fb-8ecc-b8edb647a199.png)
*Games in Playnite after import*

There's several possible solutions to this problem, but my suggestion would be to add an optional column in the List view (and perhaps an optional field in the Details view as well) that would be called "Filename" and would display, for instance, "Mega Man 4 (USA) (Virtual Console)". It could be used either as a replacement to the main "Title" column, or simply as an additional column, depending on what the user wants their library to look like.

I'm more than willing to write a PR for this, but I would like to know a couple of things first:
* Is this a welcome feature?
* What solution do you think is best?

Cheers.

**Comment by JosefNemec** [comment]
Are you on Playnite 9? These would be merged under one entry in P9 with an option to choose which one to launch after starting the game.

**Comment by vgambier** [comment]
I am not on Playnite 9, I'm excited for the release! That sounds lovely and completely solves the issue. Thanks.
