### ISSUE TITLE
Crash at Startup

### ISSUE THREAD

**Issue by Dixon40** [JosefNemec/Playnite#2523]
Hello !!!!!
Playnite 9.1 Stable crashes at Startup also in safe mode

0a45d02d-49c9-4e7f-b5f1-03b5a3652ba3

Greetz

**Comment by JosefNemec** [comment]
That's really weird. Can you zip and upload your library folder for me? `library` folder in Playnite's installation directory, you can omit `files` folder to make it smaller. Thanks

**Comment by Dixon40** [comment]
After Start when automatic Library Import starts ... first is Origin *OK* then UbiSoft *Crash* ... Greetz

[library.zip](https://github.com/JosefNemec/Playnite/files/7280405/library.zip)

**Comment by JosefNemec** [comment]
It looks like there's incomplete ROM file assigned to Syndicate game causing the crash, I'll fix that. Did you add that manually by any change? I'm trying to figure out why is it there.

**Comment by JosefNemec** [comment]
Fixed in master.
