### ISSUE TITLE
playnite 9.1 Fullscreen : sound and xinput bug when launching a game

### ISSUE THREAD

**Issue by Alexis67330** [JosefNemec/Playnite#2526]
Hello

I have two problems with playnite 9.1 in fullscreen mode:

  *  the background music does not cut when I launch a game
  
  *  the controller behaves abnormally in the game, as if playnite still had an effect on it

these observations have been made for the moment with Dirt 4 (steam) and desktop mode, there is no problem.

If I deactivate the xinput in the playnite options, the controller works normally

The controller is a latest generation XBox controller to connect with the microsoft dongle

If you need more information do not hesitate to ask me

**Comment by Alexis67330** [comment]
Hello

I have two problems with playnite 9.1 in fullscreen mode:

* the background music does not cut when I launch a game
* the controller behaves abnormally in the game, as if playnite still had an effect on it

these observations have been made for the moment with Dirt 4 (steam) and desktop mode, there is no problem.

If I deactivate the xinput in the playnite options, the controller works normally

The controller is a latest generation XBox controller to connect with the microsoft dongle

If you need more information do not hesitate to ask me

**Comment by Alexis67330** [comment]
sorry I sent too quickly

**Comment by darklinkpower** [comment]
If you use the Splash Screen extension then this happens when you launch a game that is not borderless fullscreen. You must either disable the extension or disable music in Playnite until I fix the extension rewrite to fix the issue.

Also please don't delete the issue template, you need to provide all the requested information in the format, including the diagnostics id.

**Comment by Alexis67330** [comment]
thank you for your reply, indeed I am using the Splash Screen extension.

I tried by disabling the extension and to my surprise the two problems are solved, the sound and the controller in Dirt 4

I noticed that with the activate Dirt 4 extension this automatically puts in window even though I had put in full screen. Once the extension deactivates everything works normally, the full screen, the sound and the controller.

Still quite bizarre and surprising

Promised I would pay attention to the issue template. Playnite not being the problem, I think it's pointless to do more!

Do you think your future version of Splash Screen will solve all these problems? here it was on Dirt 4, but other games may have these issues.

Sorry for my bad english, this is a simple google translation.

**Comment by Alexis67330** [comment]
great, I'm waiting for the new version. For the moment I let this one deactivate

**Comment by JosefNemec** [comment]
Closing since this is not an issue in Playnite.
