### ISSUE TITLE
Game covers get misaligned in Grid View when grouping is enabled

### ISSUE THREAD

**Issue by darklinkpower** [JosefNemec/Playnite#2527]
**Describe the bug**
Game covers get misaligned in Grid View when grouping is enabled

**To Reproduce**
Enable grouping in Grid View. Scroll or collapse/expand groups and change zoom value until it happens. Happens in any theme.

**Screenshots**
![image](https://user-images.githubusercontent.com/1389286/135944296-610b3461-d0e8-4007-81b1-f23f871d85f6.png)

![image](https://user-images.githubusercontent.com/1389286/135945033-6880c9b1-6c47-4693-b704-40530b1f3f54.png)

https://user-images.githubusercontent.com/1389286/135944845-eaa8eaec-693f-4300-a30c-54e4da278950.mp4

**Diagnostics ID**
Not applicable.

**Comment by JosefNemec** [comment]
This is one of the reasons why we need to do #2499. I'll try some workarounds in the mean time...

**Comment by JosefNemec** [comment]
Done in devel.
