### ISSUE TITLE
Grid view is not grid-like when library update fills previously empty list

### ISSUE THREAD

**Issue by XenorPLxx** [JosefNemec/Playnite#2528]
**Describe the bug**
When filtering out games in grid view to have empty list and then updating that list by doing a library update that downloads new games, grid behaves like on a screenshot below. Changing view to list and back to grid fixes it.

**To Reproduce**
Filter out games list in grid view so the list is empty and then fire up library update that will add some games that match the filters selected.

**Screenshots**
![image](https://user-images.githubusercontent.com/6712823/136003174-9c38cbb7-c174-472d-a132-49d6a7d19b65.png)
https://user-images.githubusercontent.com/6712823/136003073-1e4561a4-de09-4893-a489-18e5d7b50368.mp4

**Diagnostics ID**
`22bc9ce5-dbe0-4ed4-990b-3ac04329ec85`

**Comment by JosefNemec** [comment]
Basically the same issue as #2527 that will most likely require #2499 to fix properly.

**Comment by JosefNemec** [comment]
I've looked into it and it's nothing like #2527, it's an issue with UI library we use. It simply decides to switch rendering panel in this one case so we are completely out of control in how those games are rendered.

So sadly this will have to wait for #1141. I will be able to switch to open source version of UI library we use and try to fix/workaround it then.
