### ISSUE TITLE
Adding filter preset to the sidebar

### ISSUE THREAD

**Issue by Vackz** [JosefNemec/Playnite#2543]
For quick access and cleaner look.

**Comment by JosefNemec** [comment]
Will be done via #2556

**Comment by vjadid** [comment]
I have made an example of how the Filter preset for "Platform" filter could look like in the sidebar, for quick access.
Logos I referenced from https://archive.org/details/console-logos-professionally-redrawn-plus-official-versions

![image](https://user-images.githubusercontent.com/29530546/209927512-efdf3a2b-384d-4ebe-a494-52e8b0f96ce9.png)
