### ISSUE TITLE
Add GiantBomb for Metadata source

### ISSUE THREAD

**Issue by ArtexJay** [JosefNemec/Playnite#255]
[Giantbomb](https://www.giantbomb.com) is similar to IGDB, it holds over 5000 games, more being added with every game release. I managed to find many games that IGDB did not have any summary of 
 or simply did not exist in it's database. Please consider adding it to the metadata scraping.

I feel that GiantBomb is more complete in terms of information and pictures of video games than IGDB.

**Comment by ArtexJay** [comment]
I found the[ api documentation for GiantBomb](https://www.giantbomb.com/api/documentation)

**Comment by JosefNemec** [comment]
Support for custom metadata providers was added in Playnite 6. You should be able to create custom plugin for this now, without any addition support from Playnite required.

**Comment by JosefNemec** [comment]
Closing based on my previous comment, can be done as a 3rd party extension. I can't reasonably provide built-in support for IGDB and GiantBomb, I don't have resources for that.
