### ISSUE TITLE
Use Source Url in manifest file in addon database as a weblink to the sources 

### ISSUE THREAD

**Issue by joyrider3774** [JosefNemec/Playnite#2551]
**Describe the solution you'd like**
Use Source Url in manifest file in addon database as a weblink to the sources ... we would not need to keep adding the weblinks ourselves in the links section of the manifest file and we would be able to tell people to check for it in addons browser to find the github of a person having created a plugin to report an issue
Basically i would add it as an extra or default weblinks

**Comment by JosefNemec** [comment]
Done in devel.
