### ISSUE TITLE
Add change Game ID and change Game library function

### ISSUE THREAD

**Issue by oureveryday** [JosefNemec/Playnite#2552]
I want to change Game ID and change Game library.
I have some game not on steam, but I want download game info from offical steam library.
Can you add change Game ID and change Game library function? Thanks!

**Comment by darklinkpower** [comment]
Please don't delete the template that is there when you start creating the issue. You are meant to read what it says and fill the requested information.

**Comment by darklinkpower** [comment]
And regarding the request, that will only cause issues and break a lot of things. If you want to download metadata from Steam, you can use the "Universal Steam Metadata" metadata plugin that is available in the addons browser.

**Comment by JosefNemec** [comment]
This will be no for me. People would just mess it up, game IDs have to have specific values. As darklinkpower said, there's an extension for general Steam metadata.
