### ISSUE TITLE
Steam-created shortcut to non-Steam game fails on selection as a Play path

### ISSUE THREAD

**Issue by falcorr** [JosefNemec/Playnite#2553]
Results in a dialog saying "catastrophic failure", without a crash. 

Can be bypassed by manually getting the shortcut's target link (e.g. steam://rungameid/15156570332099248228) and putting that in the Play path field. 

Should be pretty straight-forward to fix.

**Comment by darklinkpower** [comment]
Please don't delete the template that is there when you start creating the issue. You are meant to read what it says and fill the requested information.

**Comment by JosefNemec** [comment]
What are you actually settings as the Play action? You should be settings the shortcut URL in link type play action, not the actual shortcut file.

**Comment by JosefNemec** [comment]
Also if you drag and drop that shortcut file into Playnite, it will set it that way for you.
