### ISSUE TITLE
High framerate Playnite

### ISSUE THREAD

**Issue by unrealed** [JosefNemec/Playnite#2558]
I have a 144Hz monitor and whenever I start using Playnite (clicking on it to make it the active window) **the framerate of my cursor clearly moves as if I was using a 60HZ display**. If I click elsewhere, like on another window or on my desktop background, my refresh rate comes back to normal. It's like having Playnite active puts my computer on 60Hz mode, and it would be great if this was fixed.

It sounds like a pretty niche issue, but most of the time when this happens my monitor's brightness starts slightly flickering as it struggles to keep the brightness going at the new refresh rate, which is more than a little annoying. (a few other apps on my computer have the same symptoms btw, so I imagine this can be fixed)

**Comment by JosefNemec** [comment]
See https://github.com/JosefNemec/Playnite/wiki/Known-Issues#ui-stuttering-and-mouse-lag and #201
