### ISSUE TITLE
'Tracking folder' can be empty

### ISSUE THREAD

**Issue by XenorPLxx** [JosefNemec/Playnite#2565]
**Describe the bug**
When switching the tracking mode in game actions to 'Folder', the field 'Tracking folder' can be left empty.
It was blank for me by default since I didn't have 'Installation path' filled for the game.

**To Reproduce**
- Manually add a game
- make sure it's marked as installed without filling out installation path
- add an action and mark it as a 'play action'
- switch tracking mode to folder
- Playnite allows saving changes with empty 'tracking folder' field

**Screenshots**
Not applicable.

**Diagnostics ID**
Not applicable.

**Comment by JosefNemec** [comment]
Fixed in master.
