### ISSUE TITLE
Sync play time of two game entries

### ISSUE THREAD

**Issue by Chris1320** [JosefNemec/Playnite#2566]
I have two entries of the same game. I have the Epic Game Store version and the version from its official website. I wonder if I can sync the play time of the two entries because I uninstalled the EGS version and installed the other.

For now, I just manually copied the completion status, play time, and play count of the EGS version from the advanced tab to the Playnite entry of the official version.

**Describe the solution you'd like**

What I am proposing is some kind of a "sync game statistics" feature that will sync the following:

- Last Played
- Time Played
- Play Count
- Completion Status

So if I play the EGS version, the values of the other one also updates.

**Comment by JosefNemec** [comment]
Also, this could be made relatively easily as an extension.

**Comment by Chris1320** [comment]
Ahh okay, I understand. Thanks for the response.
