### ISSUE TITLE
Dolphin (and other emulators capable) should scan .m3u for playlist import of multi-disk games

### ISSUE THREAD

**Issue by Drumheld** [JosefNemec/Playnite#2570]
**Integration features**
.m3u scan ability

**Describe the solution you'd like**
Please allow support for the Dolphin emulator (and other emulators capable of reading multi-disk format) the ability to scan for .m3u files linking to multi-disk playlists.

**Screenshots**
![image](https://user-images.githubusercontent.com/49588295/137820032-2702b2ff-3830-4407-9085-5561795888a6.png)

**Comment by Spoopryme** [comment]
Mednafen uses m3u files for Playstation, TurboGrafix CD and Sega Saturn.

**Comment by JosefNemec** [comment]
Fixed in devel.
