### ISSUE TITLE
Removing a Software Tool currently set to Show on Sidebar isn't removed until relaunching 

### ISSUE THREAD

**Issue by bburky** [JosefNemec/Playnite#2571]
**Describe the bug**
Removing a "Software Tool" set to "Show on Sidebar" incorrectly leaves it behind until Playnite is restarted.

**To Reproduce**
1. Add a Software Tool and select "Show on Sidebar"
2. Remove the just created Software Tool
3. Observe that the item is not removed from the sidebar. Sometimes (but not always?) the icon is corrupted (removed?) and turns to an orange square. Clicking the sidebar item launches the deleted item.
4. Relaunch Playnite and the item will be fully removed.
   * Sometimes I saw the broken button not be removed after relaunching. Removing it again (maybe now with no icon) and relaunching again will remove it.

**Screenshots**
![image](https://user-images.githubusercontent.com/140526/137853126-66af5884-abf2-4454-9d3f-7e4ff773f843.png)

**Comment by TowardtheStars** [comment]
Same on version 9.18

**Comment by JosefNemec** [comment]
Fixed in devel.
