### ISSUE TITLE
Multidisk games don't import region, come in jumbled order.

### ISSUE THREAD

**Issue by kftX** [JosefNemec/Playnite#2573]
I've noticed that when trying to play a multidisc game in Playnite (thanks so much for the feature btw!) that it jumbles the order of the discs and doesn't append region, making it somewhat confusing.

The example I'm gonna give a screenshot of is the Sega Saturn version of Panzer Dragoon Saga for Sega Saturn, where when I click play, it prompts me for the disc but I don't know which region is which.

I've noticed that the same does not happen if we're dealing with a single disc game as well, but all my games use the same region nomenclature, screenshot attached as well. Games have the same region name in the filename.

**Screenshots**
![image](https://user-images.githubusercontent.com/47950410/137972348-e8fd6212-1cf0-47de-8282-63c7a42a9fdb.png)
![image](https://user-images.githubusercontent.com/47950410/137973246-f787c5b1-7320-4290-9f21-cee4832d7055.png)
![image](https://user-images.githubusercontent.com/47950410/137972596-a9681084-9b0b-4ecd-96be-7cb33df7e5b8.png)
![image](https://user-images.githubusercontent.com/47950410/137973184-e69c754d-8b1b-4bb1-8a9e-6f885111264c.png)

Am I doing something wrong or is this indeed an oversight on the side of the scanner?

**Comment by JosefNemec** [comment]
Fixed in devel.
