### ISSUE TITLE
Exclude subfolders when scanning for emulation games

### ISSUE THREAD

**Issue by kftX** [JosefNemec/Playnite#2574]
When adding emulation games to Playnite, it scans in subfolders for files with similar package names (which DLC and Patches can often be) and adds them to the library nonetheless.

I think good here would be a tickbox to enable or disable the scanning of subfolders to the process, since it's just sometimes convenient to have the DLC/Patches for games in the same folder as the games themselves to make it easier to activate them inside emulators and such.

Hopefully this is something that sounds like a good idea, since I love Playnite and want to use it for emulation too, since it's pretty much near-flawless in that regard since the version 9 update!

Thank you very much!

**Comment by mitch98** [comment]
I'm also experiencing this

**Comment by kftX** [comment]
> I don't know how to solve this without breaking it for other use cases where people have nested folders with full games in them.

While I don’t know the code underneath and how hard this would be to do, why not make it a tickable box on scan or something? That way users who want to scan subfolders can, users who don’t want can just untick the box.

**Comment by djvj1** [comment]
Please add the option to NOT scan subfolders. This is a basic that should have been in already.

**Comment by JosefNemec** [comment]
Done in devel.
