### ISSUE TITLE
Resolution switching issue

### ISSUE THREAD

**Issue by DrMasquerade** [JosefNemec/Playnite#2579]
When Playnite opens up it opens up with the primary monitor's resolution in mind (my 1080p main monitor) however it takes change the resolution when maximized on a non primary monitor (my 4k one) so the resolution of the covers is lower than it should look on the 4k display.  Could someone add the option to have your non main monitor be the resolution Playnite runs at? This is all in desktop mode by the way

**Comment by JosefNemec** [comment]
Fixed in master.
