### ISSUE TITLE
Add feature to run game pad emulator automatically with the game

### ISSUE THREAD

**Issue by moruya** [JosefNemec/Playnite#258]
Many people who own a gamepad not coming from Microsoft will like it because most game support Xbox controller and we have to use a gamepad emulator like x360ce to play the games smoothly with other gamepads, and it is very convenient if there is a feature to run that gamepad emulator automatically with the games, thank you.

**Comment by JosefNemec** [comment]
Depends on #113

**Comment by moruya** [comment]
Thank you for your respond, I hope you will soon find a solution for #113
issue and my issue also.

**Comment by JosefNemec** [comment]
Closing this since, it would have to be done on per game basis manually anyways and #113 will allow exactly that.
