### ISSUE TITLE
Weird nagivation issue when moving focus beyond what fits in the first view in fullscreen

### ISSUE THREAD

**Issue by Super1337Boy** [JosefNemec/Playnite#2583]
I'm sorry about the vague title, but I don't know exactly how to describe this issue.

**Describe the bug**
Something strange happens with navigation if focus is placed beyond the games that fit on the first "page" before switching presets. It looks like focus is lost, and you just land in a random place in the list. You have to move the left stick again to get focus back.

**To Reproduce**
Move focus to a game beyond the ones that fit in the first view, and then switch preset. 

How far you have to move focus, depends on your layout settings. I've tried different layout settings including both vertical and horisontal scrolling, and it happens either way. It also happens in safe mode.

**Screenshots**
https://user-images.githubusercontent.com/6672819/138349343-c90bc214-fab7-479c-9108-2c4c33ff0b5c.mp4

**Diagnostics ID**
352bbbce-2dcd-4d62-970e-0de8441a5783

**Comment by JosefNemec** [comment]
Fixed in devel.
