### ISSUE TITLE
In fullscreen a scrollbar is needed for the filter options on large fonts

### ISSUE THREAD

**Issue by C0D10X** [JosefNemec/Playnite#2588]
![Unbenannt.JPG](https://user-images.githubusercontent.com/92644280/138590603-91912d52-4875-4240-bb44-7c7676f59690.JPG)

Can't see some options on big font in fullscreen. They will be cut off on the bottom. 

A scrollbar would help here.

**Comment by JosefNemec** [comment]
Fixed in devel.
