### ISSUE TITLE
Dragging Desktop Shortcut to Interface Not working

### ISSUE THREAD

**Issue by WriterBobL** [JosefNemec/Playnite#2589]
With the update to Playnite 9.x (currently running running 9.6) on Windows 10 64 bit, when I drag a desktop shortcut for a newly installed game onto the Playnite interface, the Edit Game Details window that pops up no longer brings in the game's name,, installation path, or default Play action.

The only field that's populated is Name, taking as its value the name of the folder where the shortcut is located.

![image](https://user-images.githubusercontent.com/62488021/138597274-85f47570-1cec-4bb4-8eb2-3f25dd37e363.png)

Previously under 8.x, dragging a game's shortcut onto the interface would open the Edit Game Details window, populating the game's name (with the file name of the shortcut), the installation location and the executable from the shortcut.

**Comment by JosefNemec** [comment]
Fixed in master.
