### ISSUE TITLE
Default quick filters use English names despite having Crowdin translations

### ISSUE THREAD

**Issue by silver-volt4** [JosefNemec/Playnite#2590]
It's most noticeable in Fullscreen Mode.

Crowdin:
![image](https://user-images.githubusercontent.com/35656715/138606860-b65a3fcd-5a0f-4e7e-9599-d40e8a430004.png)
(All of these strings are translated)

Playnite:
![image](https://user-images.githubusercontent.com/35656715/138606875-d225d7f7-353e-4a0f-a065-f8b70c9fc166.png)
(This is what you can see in FS mode when using any language)

I believe the translations worked in Playnite 8, the transition to Playnite 9 and custom filter tabs probably caused this.
One solution would be to lock the default filters' names to thir respective translations, or to get rid of the translations when they aren't used.

**Comment by JosefNemec** [comment]
Filter presets are fully customizable (and can be renamed) so they are no longer being translated, the text is actually stored with the filter preset so localizing is no longer an option. Just edit those presets and rename them however you want.

**Comment by dbardelas** [comment]
Could you tell me how to do it? Should I edit a specif file (if so, where is located?) or I must modify the code inside the project?

**Comment by JosefNemec** [comment]
Open filter panel, then there are buttons at the top (in Desktop mode) or bottom (in Fullscreen mode) to change preset configuration.

**Comment by dbardelas** [comment]
Ok, thank you so much for your help and support, very appreciated 😊

**Comment by Silver-Volt4** [comment]
Ow my poor email inbox
