### ISSUE TITLE
Remove any hyphens in titles when using the Google Image button

### ISSUE THREAD

**Issue by burnpsy** [JosefNemec/Playnite#2595]
This is a very straightforward thing that's more an oversight than a bug.

There's a handy button that Googles the title of a game to find cover art or backgrounds. Love the feature.

Sadly, some games like to title themselves like **Title -Subtitle-**. The "-" in the title would exclude any search results containing **Subtitle**. As a side effect, this button would not show any relevant results until the user manually changes the search box to read **Title Subtitle**.

I know about this, but less knowledgeable users may end up confused, so I propose removing all hyphens for game titles auto-populated in the Google cover art search button.

**Comment by JosefNemec** [comment]
Fixed in master.
