### ISSUE TITLE
Expose ViewType setting via Playnite Api to extensions

### ISSUE THREAD

**Issue by darklinkpower** [JosefNemec/Playnite#2596]
**Describe the solution you'd like**
Expose [ViewType](https://github.com/JosefNemec/Playnite/blob/master/source/Playnite/Settings/ViewProperties.cs#L136-L144) setting from `ViewSettings`. This would allow the possibility to extensions controls to provide different settings or functionality depending on the active view.

**Comment by JosefNemec** [comment]
Done in master.
