### ISSUE TITLE
Clicking in the empty area of the zoom moves the bar but doesn't change zoom

### ISSUE THREAD

**Issue by nuckable** [JosefNemec/Playnite#2597]
Tested in version 9.6

When clicking in the empty area next to the bar of the zoom-scrollbar the bar will move towards where you clicked but the zoom doesn't update/change accordingly.
The only way to update the zoom is to click the bar itself.

Here's a screenshot of the bar almost all the way to the right while still having the smallest possible zoom.
<img width="594" alt="Playnite DesktopApp_AehRdcsgtb" src="https://user-images.githubusercontent.com/11585191/138852327-48eb430e-73fb-4afb-8957-1997354f8282.png">

**Comment by JosefNemec** [comment]
Fixed in devel.
