### ISSUE TITLE
Ability to define the Platform for saved scanners

### ISSUE THREAD

**Issue by nuckable** [JosefNemec/Playnite#2598]
It would be great to have an additional Drop Down to pre-select the Platform that scanned games will automatically receive from scans/saved scans.

Here's an example screenshot of what I'm envisioning
![image](https://user-images.githubusercontent.com/11585191/138855764-4df59772-3565-435d-bbc4-8dd4e234222d.png)

An example use case is when using the Mesen core for Retroarch it will automatically select NES & Famicom Disk System for all scanned games.

There's a similar issue #1557 but it's related to the default platform of "Scan automatically", but I think this is a different use case.

**Comment by JosefNemec** [comment]
So what should happen if platform is automatically detected and this is also set? Just overwrite automatic detection on all scanned games?

**Comment by JosefNemec** [comment]
Done in devel.
