### ISSUE TITLE
Support for Xemu

### ISSUE THREAD

**Issue by malcolmturnbull** [JosefNemec/Playnite#2601]
It would be great if Xemu was supported as an emulator profile - a search of the forums turned up this: [https://playnite.link/forum/thread-870.html?highlight=xemu](url), which says it has been supported for a while, but this does not seem to be the case! _Xenia_ for 360 is supported as is CxbxReloaded for Xbox. 

Running version 9.6. 

Thank!

**Comment by JosefNemec** [comment]
Done in master.
