### ISSUE TITLE
Playnite is hidden behind the above taskbar when opening.

### ISSUE THREAD

**Issue by ghost** [JosefNemec/Playnite#2602]
Never seen this issue on any program.
Windows 10.
No custom themes or programs on windows or playnite.
Resizing the playnite window brings it back on top.
diag package id: 362c8571-b366-462d-bd70-9eab9a949a05

![image](https://user-images.githubusercontent.com/20537257/139017522-15615d5f-2847-473b-8d94-bd2673f5448b.png)

**Comment by JosefNemec** [comment]
Is this still an issue? There have been some changes to window position saving since this was reported.
