### ISSUE TITLE
Playnite full screen shutdown command on Windows 11

### ISSUE THREAD

**Issue by C-Dub87** [JosefNemec/Playnite#2607]
This is a tricky one to describe but I will try my best. 

I use my PC nearly exclusively in fullscreen mode. I navigate to games using Playnite fullscreen and a controller. To start my system I use Wake on LAN magic packets as part of my home automation setup. 

The issue is when I shutdown my PC using the shutdown command in Playnite 9, Wake on LAN does not work. When I shutdown using the Start Menu in Windows 11, WOL works next time I want to switch my PC on. 

This wasn’t an issue in Windows 10, where I could shutdown with Playnite and have no problems starting the PC up again with the magic packet.

Not sure if it’s a Windows 11 bug or if MS have changed the way Windows 11 shuts down, but this is an issue I can reproduce by using Playnite. 

To reproduce:
1) Shut down PC from inside Playnite fullscreen. WOL does not work when you send magic packet to PC. 
2) Shut down PC from Windows 11 Start Menu. WOL now works when magic packet is sent. 
3) I have only observed this happening in Windows 11. 10 was fine. 

As I said, I don’t know if this is a Playnite bug per-se, but something unusual is definitely happening.

**Comment by JosefNemec** [comment]
Fixed in master.
