### ISSUE TITLE
Add "I have read the update notes" checkbox to Playnite update window

### ISSUE THREAD

**Issue by darklinkpower** [JosefNemec/Playnite#2608]
**Describe the solution you'd like**
Add a simple checkbox that says "I have read the update notes" to Playnite update window, with the purpose of minimizing the cases where people skip and don't read the update notes, which may contain important information.

The next button won't be enabled until this is checked. This could also be done for extensions but not sure if it's necessary.

**Comment by JosefNemec** [comment]
I'm closing it since I don't think this would help much, people just don't read. Plus it's really weird requiring people to confirm reading update notes. If you have some important info to show for an update, it should be handled by an extension itself.

**Comment by darklinkpower** [comment]
gotcha, although just to clarify this suggestion was for Playnite updates and not for extensions
