### ISSUE TITLE
Add option in Stats menu to filter by installed games

### ISSUE THREAD

**Issue by aherreracies** [JosefNemec/Playnite#2609]
Is there the possibility to add the option in the Stats menu to filter by installed, non installed, hidden and favourite games. Would be great to see the playtime of, for example, all of my installed games
![unknown](https://user-images.githubusercontent.com/67416451/139250180-47ac5141-14ed-4b39-b3c2-1952c4bd7981.png)

**Comment by JosefNemec** [comment]
Done in 10.30
