### ISSUE TITLE
Remove overlay from selected game in cover view

### ISSUE THREAD

**Issue by operamaniac** [JosefNemec/Playnite#261]
Or, show it only if the sidebar closed.
I think it's redundant to show the name on top of selected game because the info sidebar already had that. To make it standout and look like it been selected, we can try to increase the brightness a little or some icon instead dimming it with overlay.

Example : [Before](https://s2.postimg.org/k6e5pdjx5/image.png) | [After](https://s2.postimg.org/xnb48cp4p/image.png) | [Or something like this](https://s2.postimg.org/tkoomz2dl/222.png)

**Comment by evgdovg1996** [comment]
Also, simple bright frame without inscription looks very good:
https://i.imgur.com/mIStbe9.png

Would be very cool, if user could wiil choose color for it:)

**Comment by operamaniac** [comment]
@evgdovg1996 Yeah. I didn't mention that because it already there (with overlay) :D 
The color is a nice option too. I think it will be available when the skin support comes with 3.0.

**Comment by JosefNemec** [comment]
I will make some changes to cover view in 3.0. However it will be completely handled by skin, so you could change it however you like (there are too many opinions on how it should look like, and it's impossible to chose one).

**Comment by JosefNemec** [comment]
Done in 3.0
