### ISSUE TITLE
Adding Games from Executable

### ISSUE THREAD

**Issue by Alvin121** [JosefNemec/Playnite#2612]
Crash Bug

Crashes when clicking on Add Games Manually and Scan Automatically

I opened Playnite and then click Add Games Manually and Scan Automatically both gives the error

An unrecoverable error has occurred

* Tried in Restart in Safe Mode still has the problem

![Playnite_Error](https://user-images.githubusercontent.com/18336446/139346432-61ad9640-7104-49e0-a01b-1cc9118adab4.png)
![Playnite DesktopApp_AdxjGDlGBa](https://user-images.githubusercontent.com/18336446/139346439-13d6ce38-841c-4c7e-9f4c-0ed5b3aead62.png)
![Playnite](https://user-images.githubusercontent.com/18336446/139346442-cca5d2fb-d94c-45af-8cc6-b63acec9a257.png)

Diagnostics package - e5c07f64-9297-45bb-8933-6ee6aefe5abf

**Comment by JosefNemec** [comment]
Closing, no response.

**Comment by darklinkpower** [comment]
It's probable that it was this issue https://github.com/Lacro59/playnite-howlongtobeat-plugin/issues/88
