### ISSUE TITLE
Support for multiple accounts for the same integration service

### ISSUE THREAD

**Issue by Logerfo** [JosefNemec/Playnite#2624]
Today, users can only connect to one account for each integration service. I'd like to be able to connect to multiple accounts for the same service. For example: connect to 3 origin accounts.
I think that the main issue here would be the client integration, since only the current logged in account would be able to launch games. But maybe Playnite could specify that the said game is linked to another account than the current one, and which one (so users don't need to remember which account has each game).
Having multiple accounts on the same service can happen in some scenarios, like:
- Losing access and recovering it later, after creating another account.
- Getting temporarily banned.
- Region related matters.
- etc.

**Comment by darklinkpower** [comment]
This is the incorrect repository to report this. As mentioned in the issue template, reports for extensions must be made in this repository https://github.com/JosefNemec/PlayniteExtensions

This feature in particular needs to be handled individually for each library plugin and there's already an open issue for the steam library plugin but not other ones https://github.com/JosefNemec/PlayniteExtensions/issues/21

**Comment by Logerfo** [comment]
@darklinkpower I apologize. Thank you!
