### ISSUE TITLE
Windows 11 Snap Layout menu not appearing on hover

### ISSUE THREAD

**Issue by raygan** [JosefNemec/Playnite#2629]
Windows 11 has added a new popover menu that appears on hover when mousing over the maximize button. This doesn't appear for me on the Playnite desktop window using any theme I've tried.

![windows 11 snap layout popover](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/images/apply-design/snap-layout-menu.png)

Microsoft has some documentation about this here:

https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/apply-snap-layout-menu

It's a small thing, but it'd be nice to see this fixed! It's probably the new feature I'm enjoying most in Windows 11.

**Comment by BeerNecessities** [comment]
2024 and still not working.  I just got an app called "groupy" to group apps with tabs and playnite doesn't work well with it.  When my monitors wake up playnite within groupy doesn't remember position.  Just a heads up as I have it grouped with GFN app.

**Comment by JosefNemec** [comment]
Closing for the same reason as #3182. This is currently not supported properly by UI framework we are using and hacky workarounds I tried are not reliable. It's especially complicated since most themes use custom window decorations.
