### ISSUE TITLE
Hidden taskbar won't appear when Playnite is maximized

### ISSUE THREAD

**Issue by KROSSEYE** [JosefNemec/Playnite#2631]
**Describe the bug**
On windows 10 when the taskbar is set to auto-hide and Playnite is maximized the taskbar doesn't appear when hovering over the bottom of the screen. I've read that this can be caused by applications that draw their own boarders.

**To Reproduce**
Enable automatically hide taskbar in taskbar settigns

**Comment by JosefNemec** [comment]
Duplicate #1106
