### ISSUE TITLE
Raise OnGameStopped event after Playnite has already updated the new game state

### ISSUE THREAD

**Issue by darklinkpower** [JosefNemec/Playnite#2634]
**Describe the bug**
Currently Playnite raises the `OnGameStopped` before it updates the game to its new game state. This means that changes in `Play Count` and `Playtime` are not reflected. Ideally the event should happen after the game has been updated by Playnite to its new state.

**To Reproduce**
Happens during `OnGameStopped` event

**Screenshots**
These are the values during the start of the event. Current `Playtime` value is `2572`

![devenv_ap66dcafX7](https://user-images.githubusercontent.com/1389286/140492610-bd03a29e-d6dd-4727-85e2-e3c73576de97.png)

By using a task and a delay, it is confirmed that the value changes after the event to a different  `Playtime` value of `2596`

![devenv_ks3OmWkGv5](https://user-images.githubusercontent.com/1389286/140492823-5946e673-9b15-4bad-9ca0-01846eff5e97.png)

**Diagnostics ID**
Not applicable.

**Comment by JosefNemec** [comment]
Fixed in master.
