### ISSUE TITLE
Dolphin Gives Error: "Unknown entry type 6 in SYSCONF (IPL.TID@17f0)" when booted from Playnite.

### ISSUE THREAD

**Issue by Maleel** [JosefNemec/Playnite#2643]
**Describe the bug**
I recently reinstalled Playnite because I was having issues with it.
I imported my "library" folder to ensure I would keep all of the games I already put into Playnite.

The issues I had (slowness) were resolved and almost everything else works as it should, but a problem has cropped up when trying to boot dolphin where I keep getting an error prompt called; "Unknown entry type 6 in SYSCONF (IPL.TID@17f0)".
I can acknowledge the prompt and continue into the game, but on first loading it downscaled my resolution and probably reverted a bunch of other settings, and ultimately outputs no audio. The Dolphin window is also called Dolphin 5.0 rather than Dolphin 5.0-15465 like it should.
This issue does not happen on Dolphin on its own nor with Steam, only when booted up with Playnite.

I've already booted Playnite in safe mode, it makes no difference.

I've already tried doing a bunch of things with Dolphin. It happens on all versions, the only thing I can do to slightly change it is to delete the SYSCONF file, but all that does it get rid of the error prompt, Dolphin still won't output any audio and will skip past the BIOS.
I've gone into playnite, removed the games, removed the emulator config, and redid all of that and the issue persists.

**Diagnostics ID**
c019ceb3-a77e-4787-ac95-cd4773fa87c0

**Comment by darklinkpower** [comment]
Playnite just tells the emulator to launch the games via command line so this points it's an issue with the emulator. A simple search shows there are many people having the same issue

https://www.reddit.com/r/DolphinEmulator/comments/amij16/sysconf_error_when_starting_dolphin_50/
https://www.reddit.com/r/DolphinEmulator/comments/f2ksvc/how_to_fix_sysconf_error/

You need to ask for support in the emulators side to fix the issue.

**Comment by JosefNemec** [comment]
Closing based on darklinkpower's comment, not an issue in Playnite.

**Comment by Maleel** [comment]
I saw those when I searched up results for this issue.
The problem is that nothing changed with Dolphin that would cause this, it HAS to be an issue with Playnite.

All versions of Dolphin do this with my Playnite for whatever reason. Both my up to date one and earlier versions, as well as the custom ones I was using for Resident Evil 2 and 3 HD.
Dolphin works fine on its own. Steam launches Dolphin roms fine. It's just Playnite that causes this issue,  I see no reason why another frontend can launch Dolphin fine but another can't if they're both just launching the games via a command line.

I figure if I was going to be dismissed it would be because of the fact that I copied my old library folder over and that maybe you could tell me how that messes things up.

**Comment by JosefNemec** [comment]
I just tried it with 15467 Dolphin build and it launches properly for me, using built-in emulator profiles (emulator importer, not configured manually). If you set it up manually, then make sure you have everything configured properly, mainly arguments you are passing to Dolphin.

**Comment by Maleel** [comment]
I was actually using the built-in emulator profiles, but you mentioning that made me go back and create a manual profile and change the play action to use that one, I literally copied the argument from the built-in emulator.
Sure enough that worked.

I've got no clue how the built-in profiles choose which executable to boot up, so maybe it was choosing the wrong exe and that is the reason the built-in one doesn't work for me? I dunno. Regardless I got a workaround at least.

**Comment by JosefNemec** [comment]
What executables do you have in Dolphin's install directory?

**Comment by Maleel** [comment]
DSPtool.exe and Updater.exe are the only other ones, and neither open up a different version of Dolphin so maybe that theory is bunk. 
I have no clue why the built-in one causes the issue while the manual one using the exact same argument works.
