### ISSUE TITLE
Playnite desktop  keep crashing after i updated playnite-gameactivity-plugin  and another plugins this morning

### ISSUE THREAD

**Issue by sunencheng** [JosefNemec/Playnite#2647]
After that update,my playnite desktop mode can not start.But when i change config.json ,setting start with fullscreen mode,it works well.
Is there any possible solution for this issue?
This is my playnite.log.Thanks
[playnite.log](https://github.com/JosefNemec/Playnite/files/7524999/playnite.log)
I tried to reinstall playnite into the old folder,still crashing.

**Comment by sunencheng** [comment]
This is all the plugins i installed.
![image](https://user-images.githubusercontent.com/8297524/141412178-8c5e16db-e9a2-41f5-8cd9-87b95a45c354.png)

**Comment by sunencheng** [comment]
[User Data.zip](https://github.com/JosefNemec/Playnite/files/7525070/User.Data.zip)
This is the files in my \AppData\Local\Playnite\User Data

**Comment by JosefNemec** [comment]
Try running it in safe mode (via `Safe Mode.bat`).

I don't see any crash info logs, so I'm guessing it just closes with no crash dialog? If that's the case then it's 99% not caused by issue in Playnite and is caused by some 3rd party (app or installed extension/theme) or issue with the system.

**Comment by sunencheng** [comment]
> Try running it in safe mode (via `Safe Mode.bat`).
> 
> I don't see any crash info logs, so I'm guessing it just closes with no crash dialog? If that's the case then it's 99% not caused by issue in Playnite and is caused by some 3rd party (app or installed extension/theme) or issue with the system.

![image](https://user-images.githubusercontent.com/8297524/141436922-0b7c8be6-1834-4416-ad12-3aa5b75acfc0.png) 
It's this theme.
I forgot theme may cause crash too.
Thanks very much.

**Comment by sunencheng** [comment]
![image](https://user-images.githubusercontent.com/8297524/141437470-f1c92218-6ab0-4531-a8fb-bd5de5623164.png)
Update to fix this ,LOL.
