### ISSUE TITLE
Incorrect Dolphin emulator version is being used

### ISSUE THREAD

**Issue by 3mtee** [JosefNemec/Playnite#2651]
I have 2 versions of dolphin on my PC:

1. ["Installer" version](https://dolphin-emu.org/download/?ref=btn)
2. ["Portable" RE 3 Seamless HD Project](https://www.reshdp.com/re3/)

I have registered a portable emulator in the Playnite.
![image](https://user-images.githubusercontent.com/731529/141685270-3b44d95c-6b4f-4a3f-ba80-fc2f3b8bd570.png)

I have also associated a "resident evil 3" game with this "portable" dolphin.
![image](https://user-images.githubusercontent.com/731529/141684986-b2ed0774-428c-4aba-a4e9-2aafa4b1e4af.png)

Whenever I try to run the game using Playnite, it's being run on an "installer" version of a dolphin instead of a "portable" one.
![image](https://user-images.githubusercontent.com/731529/141685180-4638dbef-0080-411b-b6a2-d9ae24e0b60d.png)

If I uninstall an "installer" version then the game is correctly run on a "portable" dolphin
![image](https://user-images.githubusercontent.com/731529/141685256-6a1522c6-ccc1-49e8-a00d-c29013ec5ab5.png)

**Comment by JosefNemec** [comment]
You can't have both versions in the same folder. Specifically not in the directory that's set as emulator installation directory.  Playnite will search for emulator executable during game startup and will run first one it finds.

You should import those emulators as separate emulators or you need to assign them as custom profiles.

**Comment by 3mtee** [comment]
They're placed to different directories:
 installer
![image](https://user-images.githubusercontent.com/731529/141694957-9230d6e3-390b-456a-a957-04e8b5c2edf7.png)

portable
![image](https://user-images.githubusercontent.com/731529/141694986-da4b9a28-9136-4f9b-b745-177293d5b86a.png)


Custom profile did the trick.

Thank you so much
