### ISSUE TITLE
Game Library Integration Settings not showing up.

### ISSUE THREAD

**Issue by Creatiw89** [JosefNemec/Playnite#2653]
I'm trying to get to GOG's library integration settings, as evident from my last bug report, but the section where each Game-Library integrations' settings are supposed to be, is completely blank. I've tried checking for updates and restarting, but the problem persists.
![image_2021-11-15_180836](https://user-images.githubusercontent.com/90245340/141805244-66c1bb04-4323-427b-b5c5-4ed82ce803e1.png)

**Comment by JosefNemec** [comment]
You need to expand that "Libraries" item.
