### ISSUE TITLE
PS5

### ISSUE THREAD

**Issue by renaldyalirsyad** [JosefNemec/Playnite#2657]
**Integration features**
If a feature request is related to library integrations, use separate [extensions repository](https://github.com/JosefNemec/PlayniteExtensions) to file a request.

**Check for existing issue**
Please use issue search in the repository if your feature request is something really obvious there's a high change it was already requested.

**Describe the solution you'd like**

**Screenshots**
If applicable, add screenshots to help explain requested changes.

**Comment by darklinkpower** [comment]
what is this issue about? There isn't any information, other than the "PS5" title.
