### ISSUE TITLE
Scanners don't like relative paths

### ISSUE THREAD

**Issue by krank** [JosefNemec/Playnite#2659]
When defining a scanner:

- Using the {PlayniteDir} doesn't seem to work in scanners. For example: {PlayniteDir}\Games\WonderSwan. The Games directory is in the same directory as Playnite's exe.
- Using the usual .. and . solutions "work", but generate duplicates every time the scanner runs. For example: .\Games\WonderSwan.

Diagnostics ID: 31670782-6756-42dd-b96a-bbf94e23dc90

**Comment by JosefNemec** [comment]
Done in devel. The default scanner options will now use {PlayniteDir} and {EmulatorDir} variables in paths if possible during import.
