### ISSUE TITLE
Cursor position jumping around under specific conditions

### ISSUE THREAD

**Issue by KaeAlSa** [JosefNemec/Playnite#2663]
In full screen mode with the default themes. Using a controller. When I open a game description, where it gives you the option to launch or install, if I move down to the text description of the game and it has to be one that has a large enough description that it has the scroll bar.
When I back out to the main screen that has all the games, while I am scrolling around the selector will randomly jump from the games list to the top bar where the filters are
I can get it back to normal if I go into a game that has a short description and go down to that and then back out.

Diagnostics ID 0d24dcb1-b0a9-42ff-92ca-072faac60cfc

https://youtu.be/y451xsCCMx8

**Comment by JosefNemec** [comment]
Fixed in devel.
