### ISSUE TITLE
Crash when adding profile for RetroArch

### ISSUE THREAD

**Issue by Cerates** [JosefNemec/Playnite#2667]
**Describe the bug**
I added Sameboy profile to RetroArch in "Configure Emulators". I forgot to set a profile in the first place. I noticed that when I tried to add a second emulator as action on a game thats already present with standalone SameBoy as emulator.

My goal was that I can choose from multiple emulators.

**Diagnostics ID:** 
`33e964fb-2ced-4a89-8203-28cadc03f0`

**Screenshot:**
![Playnite DesktopApp_XnceO6Uia6](https://user-images.githubusercontent.com/31569889/143270971-b6fa1089-f3b3-4450-a893-ed0e4ade19eb.png)

**Comment by Cerates** [comment]
Oh I didn't close SameBoy maybe it crashed because I didn't shut down the emulator. Sorry.

**Comment by JosefNemec** [comment]
Can you reproduce this on demand? Did it happen only once?

**Comment by Cerates** [comment]
It happened once then I closed the emulator and then it worked with setting the profile and had no more crash. I could try to reproduce it.

**Comment by Cerates** [comment]
I just tried to reproduce but couldn't. I know tried with Gambatte instead of RetroArch. Could it be tht RetroArch is the culprit?

**Comment by JosefNemec** [comment]
It's not emulator related. I know where it crashes I just don't understand why or how to reproduce it to make sense of it.

**Comment by JosefNemec** [comment]
Fixed in devel.
