### ISSUE TITLE
RetroArch Cannot start game with using {PlayniteDir}

### ISSUE THREAD

**Issue by bulmust** [JosefNemec/Playnite#2669]
When I use {PlayniteDir} shortcut, RetroArch cannot start. In contrast, giving full path works. Same bug occurs when I use {PlayniteDir} for RetroArch roms. It is important to use Playnite as a portable game library.

Probably, it occurs due to the RetroArch path definition. The {PlayniteDir} path definition may include `\\`.

**Bug 1 Reproduce**
- Import RetroArch Emulator inside of Playnite Folder
- Change RetroArch Installation Folder C:\Playnite\RetroArch to {Playnite}\RetroArch
- Try to open a rom

**Bug 2 Reproduce**
- Import RetroArch Emulator inside of Playnite Folder
- Place a rom inside of {PlayniteDir}\rom
- Add a rom using "Emulated game (ctrl+q)"
- Change rom's installation Folder C:\Playnite\rom\ to {PlayniteDir}\rom\ 

**Diagnostics ID**
`563e0fed-335e-449a-a8ba-fd40461f7f21`

**Comment by JosefNemec** [comment]
Already done in master via cd2c3d536365b5cddbfb725b33e1bf973937f80c. Will be in next update.
