### ISSUE TITLE
Game library does not refresh after manually editing metadata

### ISSUE THREAD

**Issue by dotexe1337** [JosefNemec/Playnite#2671]
**Describe the bug**
When manually editing metadata for a game, the game library does not refresh after saving. This can cause issues such as games being temporarily sorted improperly (if editing the game's name or sort name) until the program is restarted.

**To Reproduce**
Manually edit the metadata for a game, save the metadata, and the library does not refresh on its own. The program must be restarted to refresh the game library.

**Diagnostics ID**
1e346ec2-80c5-47e1-808b-177b4ef0b471

**Comment by darklinkpower** [comment]
I can reliably reproduce it

1. Using the following game names
![image](https://user-images.githubusercontent.com/1389286/143536880-7d3ad58f-5480-4c4c-955c-4e1c84d8c26e.png)

2. Set sorting name of `Zup! 6` to `Zup! 2`. Game order is correct. (Naming to `Zup! 3` doesn't trigger the bug)
3. Delete the sorting name of the of this game. It doesn't return to where it should be with the name `Zup! 6`



https://user-images.githubusercontent.com/1389286/143536982-55f939e6-52a3-4f66-b2e3-fd26aeb30411.mp4

**Comment by JosefNemec** [comment]
Duplicate #1407
