### ISSUE TITLE
Xbox Game Pass games open microsoft store

### ISSUE THREAD

**Issue by Drumheld** [JosefNemec/Playnite#2672]
Xbox Game Pass games open the microsoft store despite having the "open xbox app" checkbox selected int he xbox configuration.

This may be an issue with the GamePass Extension integration and I will report the bug to them as well.

**Comment by JosefNemec** [comment]
1) Wrong repository, this is all handled by Xbox plugin.
2) Make sure Xbox app is properly installed, try reinstalling it.
