### ISSUE TITLE
Update file integrity check failed

### ISSUE THREAD

**Issue by pssandhu** [JosefNemec/Playnite#2673]
**Describe the bug**
I am attempting to update an old install from version to 8.1 to the current 9.6 version. After pressing "Download and install update", the update appears to download but then gives an error: "Update error: Failed to download and install updates. Update file integrity check failed".

**Diagnostics ID**
60584188-f0fc-4015-8abe-95a9faec451b

**Comment by JosefNemec** [comment]
You have to manually download installer and reinstall (you won't loose any data). Updates from such old versions are no longer possible.

**Comment by pssandhu** [comment]
I used the portable zip version. Can I just download the new zip and overwrite the files or might that cause issues?

**Comment by JosefNemec** [comment]
You can, it won't cause any issues.
