### ISSUE TITLE
[Feature Request] Add support for Playnite.SDK to share data among extensions

### ISSUE THREAD

**Issue by BanCrash** [JosefNemec/Playnite#2674]
**Describe the solution you'd like**
Hello, PlayState added a feature that allows you to pause the play time, and after the process is finished it will remove from the play time the paused time. However, other extensions (like [Game Activity](https://github.com/Lacro59/playnite-gameactivity-plugin)) doesn't have the updated play time since they can't communicate with the PlayState extension.

So adding support for extensions to share data will allow PlayState to share the real play time to GameActivity, and then you can see the real play time instead the play time + paused time.

References:
https://github.com/Lacro59/playnite-gameactivity-plugin/issues/55
https://github.com/darklinkpower/PlayniteExtensionsCollection/issues/122

**Comment by JosefNemec** [comment]
Duplicate #2039

**Comment by BanCrash** [comment]
Sorry, I've searched but didn't found it.
