### ISSUE TITLE
Darken the screen when the system is idle in Fullscreen mode.

### ISSUE THREAD

**Issue by grogfella** [JosefNemec/Playnite#2679]
So something that a lot of console systems dating back all the way to the Wii do is dim the screen when they notice that there hasn't been any input in a while. I would like to see the same kind thing implemented into Playnite as well when it is in Fullscreen mode, especially because I use Playnite with a CRT system where image retention is a big problem. Dimming the screen similarly to how the rest of the screen is dimmed when pulling up the Playnite Settings in Fullscreen should suffice.

In an ideal world it would be possible to launch a screensaver through Playnite the same way, but that's already been ruled out, so this is the next-best option.

**Comment by JosefNemec** [comment]
Duplicate #2362
