### ISSUE TITLE
Sort by price

### ISSUE THREAD

**Issue by BoltPow3r** [JosefNemec/Playnite#268]
I don't see any issues opened for this, so I am making one. 

I believe this is a needed feature.  For example, I have a friend who has [a lot ](https://imgur.com/viavTu8) of games. I would like to filter out all games below 4.99€ for example OR search for games that are above 30€.

**Comment by JosefNemec** [comment]
I don't think this is technically possible. The price changes a lot (on Steam primarily) and we would have to  update way too often, which we can't due to API call restrictions on Steam's side.

**Comment by epeternally** [comment]
What if the price was only updated in the initial metadata pull, rather than being constantly refreshed? Knowing the price of a game over time isn't needed, just having the initial MSRP would be enough to do a lot of helpful sorting.

**Comment by JosefNemec** [comment]
Technically we could do it, but I have some doubts about how helpful this would be. It's not going be price you payed for it or general price of that game because it could be on sale.
