### ISSUE TITLE
Github outage causes nonresponsiveness when retrieving addon information

### ISSUE THREAD

**Issue by chocolatechipcats** [JosefNemec/Playnite#2680]
Copied from https://playnite.link/forum/thread-992.html

> Currently, Github is down. Unfortunately, this means that when going to the Browse section and clicking on a plugin that's hosted on Github (and presumably fetches its information from there), Playnite becomes nonresponsive - cannot exit from the dialog and attempting to access the system tray menu fails. I waited some 7-10 minutes before terminating the Playnite process.
> 
> Clicking on the Updates section in the addons dialog was slow, but still allowed me to exit out of the dialog. 
> 
> I am also curious as to whether this could also be replicated with a lack of network access. 
> 
> Thank you.

**Comment by JosefNemec** [comment]
Fixed in master.
