### ISSUE TITLE
GOG Plugin not working anymore

### ISSUE THREAD

**Issue by marcistacks** [JosefNemec/Playnite#2681]
When clicking on "authenficate" nothing happens. Reinstalled newest version of Plugin, didnt help. 

![image](https://user-images.githubusercontent.com/87758617/143763537-baf227e5-366a-4c42-9fee-f07bbf9a4ec7.png)

**Comment by JosefNemec** [comment]
Wrong repository, report it in extension's repo.
Also I can't reproduce it.
