### ISSUE TITLE
Platrorm and Series tree structure

### ISSUE THREAD

**Issue by OMEGA-END** [JosefNemec/Playnite#2682]
Similar idea to request #2626
Option to display platforms and series in a tree structure would be fantastic. By tree structure i mean option to tag consoles with thier manufacturer and show them in a drop-down menu as pictured below:
https://imgur.com/rciDtAv
Also, a release year tag for platforms i order to sort them would be appreciated.

The same thing could be done with series by linking sub-series to parent franchise, for example
Mario
├Mario Bros.
├Super Mario
└Mario Kart

**Comment by JosefNemec** [comment]
Duplicate #1961
