### ISSUE TITLE
Date added field not functioning correctly

### ISSUE THREAD

**Issue by whoozwah** [JosefNemec/Playnite#2683]
The date added field doesn't appear to be working correctly. The time limits are not inclusive. I added several games at various points within the last 9 days. 1 game 9 days ago and 10 more today. I expected to be able to filter by last 31 days and see everything I've added in the last 31 days but it is only showing everything that I added that was added in-between the 7 and 31 day thresholds. I have to actually filter to "today" to see the games I've added today which is counter-intuitive given the labeling. The expectation is that you will see all games added in the last 31 days.

**Comment by redactedscribe** [comment]
I just noticed this behaviour too: filtering by "In past 31 days" doesn't show today's free game claimed from the Epic Games store. "Today" must also be checked.

**Comment by JosefNemec** [comment]
This is an unfortunate result of how I badly I designed date filters. It will be fixed by #1614
