### ISSUE TITLE
Unwieldly Company List Dropdown When Editing Games

### ISSUE THREAD

**Issue by burnpsy** [JosefNemec/Playnite#2687]
I would like to request a better way of filling in the company or tags when editing a game.

To elaborate, I have a very large library. As a result, I have several hundred developers, publishers, and tags that have been added over time. As a result, whenever I need to manually edit one of those fields, I am led to a very long dropdown list where I have to try and find the company I want to insert.

![image](https://user-images.githubusercontent.com/6007819/144292692-b826ebc3-a7fa-4913-aef3-3175da922a3a.png)

If I could suggest an idea, perhaps have a search box where I can type a few letters of a company name and the dropdown is filtered to only show these.

**Comment by JosefNemec** [comment]
9.7 already added search/filter there. You are just using a theme that overrides style for that dropdown and wasn't updated with 9.7 changes.

![image](https://user-images.githubusercontent.com/3874087/144296614-cbd46076-94ab-4444-b071-c0d9d6ad1bf9.png)
