### ISSUE TITLE
Sort by release date

### ISSUE THREAD

**Issue by BoltPow3r** [JosefNemec/Playnite#269]
As the title suggest. Nothing fancy.

**Comment by JosefNemec** [comment]
You can already do that

**Comment by BoltPow3r** [comment]
You can Ascend/Descend ?

**Comment by JosefNemec** [comment]
Yes, like with any other game property.

**Comment by BoltPow3r** [comment]
I'm dumb. Totally did not see that. I'm leaving for the moon.
