### ISSUE TITLE
Ignore list for emulation / ROM files

### ISSUE THREAD

**Issue by akumenon** [JosefNemec/Playnite#2691]
As helpful as the emulated games auto-scanner is, I believe its usefulness is quite heavily compromised by the inability to exclude specific ROMs.

This is important especially for emulated arcade games because their emulators usually demand that you have BIOS/drivers/other pre-requisite ROMs in the same directory. The scanner will pick up those files too, even though they can't be used/played by themselves most of the time. This feature would also be useful in situations where your disk/cartridge dumps are in 1 folder (per platform possibly) but not all games can be emulated or you simply do not want to emulate or add them to Playnite for whatever reason. For now, being able to exclude certain auto-scanners from bulk scans has proved very useful.

If I were to suggest a way to implement this, it would be to have a list of files to exclude in the auto-scanner settings or maybe extend Import Exclusion List to also process local files.

I hope you will consider adding this in future versions of Playnite.

Thank you very much.

**Comment by JosefNemec** [comment]
Done in devel.
