### ISSUE TITLE
FULLSCREEN Game Menu Options

### ISSUE THREAD

**Issue by Mobile313** [JosefNemec/Playnite#2699]
In full screen mode there is an overlay window (Game Menu).  The current options in the menu are Play, Add to Favorites, Hide This Game, Uninstall, and Remove.  I would like to propose an option in settings to toggle whether Hide, Remove, and Uninstall are displayed.

The rationale behind this is that my Playnite is used by more than just me, and I would like to make sure that when other people are using it that they can't have such easy access to those features.  For instance I'd rather not have to figure out what happened to Game X, because my nephew got click happy and accidentally removed a game from the library.  This feature would be a huge bonus for those of us who use the Desktop mode to manage our libraries, and the Fullscreen mode to play from.

**Comment by JosefNemec** [comment]
Duplicate #1252
