### ISSUE TITLE
Main search field to search filters via text

### ISSUE THREAD

**Issue by redactedscribe** [JosefNemec/Playnite#2700]
**Check for existing issue**
Similar to #1764.

**Describe the solution you'd like**
The main search field at the top-left is basically just the Name filter. I think it would be great if it could be used to search multiple filters via text. The feature needn't be as complex as the referenced issue, filter prefixes would be enough.

Example:
- `witcher 2: assassins library: steam, gog status: oh hold not_installed:: match: any`
- `preset: most played`

Breakdown:
- "name:" prefix would be the default and shouldn't need to be specified unless the name isn't specified first.
- Prefixes other than the ones _known_ to Playnite would be ignored, i.e. `2:` in the above's case shouldn't cause an error.
- Commas are used between filters that accept multiple values, but not needed between filter prefixes (`<known_filter>:` should be enough to handle knowing where multiple values stop and where a prefix begins).
- Filters that are checkboxes could be considered enabled via a double colon: `not_installed::` (and maybe `not_installed: [true|1]` if wanting to be verbose).
- Like the new match all filter in the filter sidebar, the entire match could be limited `match: any` or `all` filters.
- Valid filter values would be the strings used by the filter sidebar's drop-down menus.
- Search should all be case-insensitive.

Feature's main benefits:
- <kbd>Ctrl</kbd>+<kbd>F</kbd> becomes more useful, can search more than game names.
- No need for syntax that is too advanced.
- Filter sidebar can always remain closed: cleaner look, less screen space used.
- Potentially set filters more quickly than the UI (once you've memorised the prefixes).
- Search strings are shareable.

Cool, but unnecessary:
- After submitting a text search, all the valid values would appear in the filter sidebar's UI.
- After typing a known prefix, e.g. "features:", the Features drop-down would appear letting you choose the value without needing to type it (some are long).
- Typing a comma after a prefix and at least one value would show the drop-down again to insert another value.
- If multiple values are selected when this drop-down appears, insert the values separated by comma.

Thanks!

Playnite 9.11

**Comment by JosefNemec** [comment]
There are already existing issues for this. For example #1413 #135

**Comment by tetj** [comment]
still not implemented, I would re-open this one
