### ISSUE TITLE
Typing into filters with "Match all filters" doesn't work as expected

### ISSUE THREAD

**Issue by redactedscribe** [JosefNemec/Playnite#2701]
**Describe the bug**
Example: when _typing_ a tag name into the Tag filter field:
- Match all filters _off_: the tag is matched, the results are as expected.
- Match all filters _on_: the tag doesn't seem to be matched, as basically all games are returned. Only the Tag filter is set.

**To Reproduce**
- Add a unique tag to a game.
- Turn _on_ Match all filters.
- Search for the tag via text (not drop-down) in the Tag filter field.
- Should only be 1 result, but there are many.
- Repeat with Match all filters _off_, and notice only 1 result.

With Match all filters _on_, filtering for the unique tag works fine as long as it is done via the UI drop-down. Only when searched via text does it not work.

Thanks!

Playnite 9.11

**Comment by JosefNemec** [comment]
Fixed in devel.
