### ISSUE TITLE
Game History Affecting Executable/Game Settings

### ISSUE THREAD

**Issue by soapwad** [JosefNemec/Playnite#2702]
I was about to send in a bug, but trying to reproduce the bug rendered me in fixing it. I'm not sure if it's worth investigating, but still, I'm leaving what I wrote ten minutes ago in the following paragraphs below. Basically the problem was my game had a trouble looking for its master plugins when I had updated the 'Play' action executable. Creating a new game import of the executable fixed it. I wonder if it had anything to do with the previous game's settings, I'm just not sure how or why Playnite could affect something like that. 

<strike>644482c5-1bc6-4ec6-a4a4-eaf70a4b1633

I have installed a newer version of Skyrim that's modded, and so I also installed a newer version of an app (SKSE) needed to make it work. That file is the one that the "Play" action opens. It would run fine before the update. Like I could run my savegames well enough, but now, when I launch the app through Playnite, my savegames won't open, saying that Skyrim can't find its master plugins (Skyrim.esm & other esm/esps). I tried changing the app that would run in Playnite to either "Skyrim.exe" or "Launch Skyrim.exe" but the problem prevails. It isn't the game's problem because when I ran any of the three .exe files manually, the savegames open just fine. It only happens when I open the game through Playnite. 

The master plugins my game is looking for is in my "Program Files (x86)" folder. I tried to do one thing to remedy this problem. I heard somewhere that it's not recommended to place things in PFx86 that need to be read often, and so I made my game file open access through User Account Controls, but that did not fix the problem. I do not know how else to fix this.

I have never encountered this problem before. Before the update, the executable would run fine through Playnite with no errors, game errors notwithstanding. So I'm not sure why this is happening only in Playnite. 

Opening with Safe Mode on: Issue prevails

Reproducibility:

It's not a completely devastating bug. Like I said, everything works fine if I manually run the executable. But I'd really quite like it if I could open it through Playnite naturally, as I have been doing for some time now. Thank you for your help.</strike>

**Comment by JosefNemec** [comment]
You most likely missconfigured Play action, specifically working directory. Playnite only launches what you tell it to with arguments and working directory you set. If a game has issues with specific setup (again, most likely working directory), then it's an issue in the game or in a way you configured Play action.

**Comment by JosefNemec** [comment]
Forgot to mention: we don't interact with launched process in any way once it's started and Playnite uses standard .NET APIs to launch game processes. So there's IMO nothing to fix from Playnite's side.

**Comment by JosefNemec** [comment]
Closing based on my previous comments.

**Comment by soapwad** [comment]
Thank you!
