### ISSUE TITLE
Playnite Fullscreen Doesn't Launch When Playnite Desktop is Already Open

### ISSUE THREAD

**Issue by Blootrix** [JosefNemec/Playnite#2705]
Hey, I'm using it to launch the Playnite.FullscreenApp.exe using Controller Companion, but if Playnite Desktop is already open then Playnite, whether fullscreen, windowed, minimized to taskbar or minimized to tray, the desktop app opens instead and I need to full close Playnite in order for the Playnite.FullscreenApp.exe to work.

Using Windows 11 Pro: Version 10.0.22000

**Comment by JosefNemec** [comment]
This is intended behavior. You need to use [--startfullscreen](https://playnite.link/docs/master/manual/cmdlineArguments.html) argument if you want to force existing instance to Fullscreen mode.
