### ISSUE TITLE
Detect installed clients and suggest library plugins for new users

### ISSUE THREAD

**Issue by Jeshibu** [JosefNemec/Playnite#2706]
Allow plugin manifests to define collections of registry keys, which, if any are present, will result in new users being presented with the plugin being suggested.

How I imagine this:
- Right after initial install of Playnite:
- "We've detected GOG Galaxy 2, Steam, and Ubisoft Connect on your system. Install library plugins for them?"
- A checkbox list for what plugins to install.

I suggested collections of registry keys specifically for the EA Desktop/Origin situation. Maybe there should be a prompt too to warn users that the system is going to be scanned for game clients, in case it might feel invasive otherwise. Not sure how people generally feel about that.

**Comment by JosefNemec** [comment]
This seems to me like a lot of added complexity to spare users of doing couple extra clicks on first time startup dialog (where they can already select what integrations to install).
