### ISSUE TITLE
Playtime of library plugins is synced even when "Prioritize playtime" is disabled.

### ISSUE THREAD

**Issue by darklinkpower** [JosefNemec/Playnite#2708]
### Bug Description

Playtime of library plugins is synced even when "Prioritize playtime" is disabled.

### To Reproduce

1. Disable "Prioritize playtime..." option
2. Sync library plugin that supports playtime import (Like Steam or Epic)

### Diagnostics ID

750fb5af-c706-44a1-9847-81c2faac9d1d

### Screenshots

https://user-images.githubusercontent.com/1389286/145675752-d3d23160-936f-4df3-841c-cd1999b83e80.mp4

**Comment by JosefNemec** [comment]
Not a bug. That option only works on games that have some time recorded. If there's no time present, then Playnite has no idea of knowing if user set it to 0 or if no time was imported at all previously. Therefore this is intentional functionality.
