### ISSUE TITLE
Second Start Bar icon appears in Win 11 when Playnite is launched at startup

### ISSUE THREAD

**Issue by TreeFoxx** [JosefNemec/Playnite#2713]
### Bug Description

Currently running Windows 11 build 22000.376 (although this bug has been consistent across several builds). I have Playnite set to launch at start in a maximized window. When this happens, a second icon for Playnite appears in the start bar, next to the other Playnite icon. Closing and reopening Playnite resolves this.

It's a very minor bug, but I figured I would point it out. Thank you :-)

### Diagnostics ID

1df47c80-67bb-44d9-8b57-782902804458

**Comment by JosefNemec** [comment]
We have literally no control over this. Microsoft has to fix it.
