### ISSUE TITLE
Fulscreen mode and resolution switching issues

### ISSUE THREAD

**Issue by npaladin2000** [JosefNemec/Playnite#2714]
### Bug Description

I've noticed this with any condition that switches resolutions in Playnite fullscreen mode, both when docking and switching from an internal display to a TV, and when connecting via Remote Desktop, Playnite in fullscreen mode is unable to adjust to a new screen resolution and instead scales linerarly with a maintained aspect ratio (that is to say, it shows up the same as before but with black or white bars surrounding whatever edge is left over when the aspect ratio changes). 

### Diagnostics ID

bf12f26ab-3482-4896-b034-b8387299a60a

**Comment by JosefNemec** [comment]
Fixed in devel.
