### ISSUE TITLE
Play actions keep reappearing after being removed

### ISSUE THREAD

**Issue by adrian5683** [JosefNemec/Playnite#2718]
### Bug Description

Hi, it seems any play actions that are imported from an external library, like GOG, cannot be removed. They stay removed until the next time Playnite is restarted, then reappear in the same order they were initially imported.

### Diagnostics ID

7c01e9d1-c68c-4091-a23a-561cecd5a810

**Comment by JosefNemec** [comment]
To clarify, it's not Play actions, but other actions. Play actions are not permanently assigned to games since P9.

**Comment by adrian5683** [comment]
Yes, you are correct, stuff like opening a support page or manual. As far as I can tell it only happens for GOG imported games.

**Comment by JosefNemec** [comment]
Fixed in devel.
