### ISSUE TITLE
Numerical Sorting

### ISSUE THREAD

**Issue by godspeed-excelsior** [JosefNemec/Playnite#2720]
### Feature description

I've only recently downloaded Playnite and synced across my Steam collection to the Library. The main issue I'm having is that my Final Fantasy collection is not sorting properly.

It goes 1, 10, 12, 13, 13-2, 13 (Lightning Returns), 15, 2, 3, 4, 5, 6, 7, 8, 9. Clearly, the issue is that it is not counting 10 - 15 as a higher value than 2 and is only looking at the first numerical value.

**Comment by JosefNemec** [comment]
Duplicate #671

**Comment by godspeed-excelsior** [comment]
That was quick, thanks for the help.
