### ISSUE TITLE
Command line parameter to launch Playnite with certain extensions disabled

### ISSUE THREAD

**Issue by fernandofreije** [JosefNemec/Playnite#2721]
### Feature description

I'm not sure how possible this is, but certain extensions I use don't play well with, for example, Gamestream, like display switcher. There are other cases where I would love to launch playnite without certain extensions. Would it possible to add some kind of comand line parameter to disable some extensions on launch?

Thank you for your work!

**Comment by JosefNemec** [comment]
I don't know about this. This sounds like very niche feature that's basically a workaround for issues that should be fixed in those extensions.

**Comment by fernandofreije** [comment]
Noted! Thank you anyway!
