### ISSUE TITLE
Toolbox - generates invalid extension template (HRESULT: 0x80070002)

### ISSUE THREAD

**Issue by DrinkFromTheCup** [JosefNemec/Playnite#2722]
### Bug Description

Latest public Playnite version on Win10 x64 Home (RU)

For some reason, I can't make Toolbox-made extensions work.
Getting
23-12 00:24:23.847|ERROR|ExtensionFactory:Failed to load plugin: Paradox library
System.IO.FileNotFoundException: Не удается найти указанный файл. (Исключение из HRESULT: 0x80070002)
for both compiled and not compiled extensions.
Since I'm... eh... exceptionally bad at programming (and that's an underestimation), I can't even debug it properly.

### To Reproduce

toolbox.exe new LibraryPlugin "22" "C:\Users\%YOUR_USERNAME%\Documents\Playnite plugins\Generic_code_base\code"
then in Playnite's Settings > For Developers add extension's folder
C:\Users\%YOUR_USERNAME%\Documents\Playnite plugins\Generic_code_base\code\22
to the list of watched folders and restart.

Compiling it is successful - but compiled extension fails with same error as well.

### Diagnostics ID

31e83c01-daf1-4d0f-92ba-33a04627508c

**Comment by JosefNemec** [comment]
"For Developers" path has to point to build output with compiled plugin, not the path where source code is created by Toolbox. By default it should be `bin\Debug\` subfolder.

**Comment by DrinkFromTheCup** [comment]
Understood! It's sufficient for me to advance for now.
This one should probably be closed then, since documentation improvement for less-than-savy users like me is a completely different matter...
