### ISSUE TITLE
Crash after google image downloaded failed

### ISSUE THREAD

**Issue by darklinkpower** [JosefNemec/Playnite#2724]
### Bug Description

Attempted to download an image with the Google Images function. The image didn't download and after some time Playnite crashed and closed. No crash dialog.

### Diagnostics ID

5fe5981c-b81b-49ac-ac48-2c0f89ab507c

**Comment by JosefNemec** [comment]
No crash dialog means it's either some system issue or dependency issue. I can't replicate it myself.

**Comment by darklinkpower** [comment]
I couldn't reproduce it afterwards either. I tried immediately after rebooting Playnite and using the same image without luck. Now that I remember I was downloading something at the time and the internet stops working well for other programs when I'm downloading something so my guess is that this only happens in network limited scenarios.

I also saw this in the logs:

```
23-12 01:41:56.610|DEBUG|WindowFactory:Closing window Playnite.DesktopApp.Windows.GoogleImageDownloadWindowFactory, True.
23-12 01:43:36.654|ERROR|HttpDownloader:Failed to get HTTP response for https://www.hyperhype.es/wp-content/uploads/2020/12/Sakuna-Of-Rice-and-Ruin.jpg.
System.Threading.Tasks.TaskCanceledException: Se canceló una tarea.
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en Playnite.Common.Web.HttpDownloader.GetResponseCode(String url) en C:\projects\playnite\source\Playnite\Common\Web\HttpDownloader.cs:línea 79
23-12 01:43:36.888|WARN |GameEditViewModel:Original Google image request failed: ServiceUnavailable
```

I'll see if I can somehow trigger it again and see if the same happens

**Comment by JosefNemec** [comment]
Closing since I can't do anything about it because it doesn't crash in our code and it can't be replicated on demand to debug if it's some dependency doing it.
