### ISSUE TITLE
EmulatorDir variable is not expanded inside game action arguments

### ISSUE THREAD

**Issue by nannerdw** [JosefNemec/Playnite#2726]
### Bug Description

EmulatorDir variable is not expanded inside game action arguments

### To Reproduce

Use {EmulatorDir} in a game's installation folder path.
Use {InstallDir} in its ROM path.
Use {InstallDir} inside the emulator arguments.

### Diagnostics ID

Failed to create diagnostics package

**Comment by JosefNemec** [comment]
Done in devel.
