### ISSUE TITLE
support for metadata import for game demos

### ISSUE THREAD

**Issue by shakeyourbunny** [JosefNemec/Playnite#2728]
### Feature description

During metadata download, game demos (with "demo" or "(demo)" in title don't receive incomplete or no metadata at all.

Also, if a game demo is detected, it should also be automatically tagged or categorized as "demo" (not sure if tags or a category is more appropriate).

Go to Steam or GOG, add a game demo to your account and start metadata import.

Example games, which have a demo, but do not receive any metadata on scan:
- (Steam) Loop Hero demo
- (Steam) Wild life demo
- (Steam) Always Sometimes Monsters demo
- (Steam) Broforce Twitchcon demo
- (Steam) Fear Effect Sedna demo
- (GOG) Spindle demo
- (GOG) Trash Sailors demo
- (GOG) Project Warlock II demo
- (GOG) Sunblaze demo

Game demos, which DO receive metadata:
- (Steam) Puzzle Walker demo
- (Steam) Little Witch Nobeta demo
- (Steam) Erinye demo
- (Steam) Recourse demo

**Comment by JosefNemec** [comment]
This has to be handled in each metadata/library plugin independently.
