### ISSUE TITLE
Failed to Import Epic Games

### ISSUE THREAD

**Issue by shangles** [JosefNemec/Playnite#2730]
### Bug Description

I'm unsure if this is related to the current Epic Games issues or not (https://twitter.com/EpicGames/status/1476231639428739087) but figured it was worth posting.

I just updated Playnite to the latest version and re-authenticated my Epic account and tried to sync Epic Games after claiming today's free game and got this error message in Playnite:

`Failed to import games from Epic.  Unexpected character encountered while parsing value: <. Path ", line 0, position 0`

### To Reproduce

- Update Playnite
- Authenticate with Epic Games
- Update Epic library

### Diagnostics ID

f4f5f425-3832-4bdf-8f0c-6b5c0d6d5e50

**Comment by JosefNemec** [comment]
Wrong repository.

**Comment by shangles** [comment]
> 

Not sure what you mean by this.

**Comment by JosefNemec** [comment]
From the issue template:
> Integration issues
> If an issue is related to library integrations, use separate extensions repository to file a report.

**Comment by shangles** [comment]
Understood.  Sorry I missed this.  Recreating now in proper repository.
