### ISSUE TITLE
SDK: `Developer` and `Publisher` constructor with name do not call `base(name)`

### ISSUE THREAD

**Issue by erri120** [JosefNemec/Playnite#2731]
### Bug Description

https://github.com/JosefNemec/Playnite/blob/3e8b6222e194708152337191467ba7087f297a70/source/PlayniteSDK/Models/Company.cs#L52-L55

and

https://github.com/JosefNemec/Playnite/blob/3e8b6222e194708152337191467ba7087f297a70/source/PlayniteSDK/Models/Company.cs#L74-L77

both should call `base(name)` so the name can be set in `Company(string name)`. Currently calling either `Developer(string name)` or `Publisher(string name)` will result in `Company.Name` being `null`.

**Comment by JosefNemec** [comment]
Fixed in master.
