### ISSUE TITLE
"Edit Game Details" Window does not know about database updates

### ISSUE THREAD

**Issue by erri120** [JosefNemec/Playnite#2732]
### Bug Description

The database can be updated by a Metadata Provider:

When importing, Playnite shows the correct item:
![2021 12 30-12 26 47  7Y7QoLHd9R](https://user-images.githubusercontent.com/16577545/147748308-04e2d86d-b428-4873-9ccb-db2f79ccd397.png)

After importing the field is not set:
![2021 12 30-12 26 58  IQyn0Q1POe](https://user-images.githubusercontent.com/16577545/147748310-1da76b04-d66c-417f-83bc-0ab7b4d4a485.png)

The "Edit Game Details" does not know about the database update:
![image](https://user-images.githubusercontent.com/16577545/147748626-901246a8-05f0-4793-81da-480f47e66f4c.png)

Example:
```csharp
    public override IEnumerable<MetadataProperty> GetFeatures(GetMetadataFieldArgs args)
    {
        var feature = _playniteAPI.Database.Features.Add("Nice");
        return new[] { new MetadataIdProperty(feature.Id) };
    }
```

**Comment by JosefNemec** [comment]
You should not be adding fields to the database in metadata methods. `MetadataIdProperty` should be only used if you want to reference existing items.

**Comment by JosefNemec** [comment]
I'll explicitly mention this in the docs to make sure people don't misuse this. Metadata sources should just provide data to Playnite and then it should be left to Playnite how it actually stores that data since there is an additional layer of data handling on top of your plugin (to handle duplicates and other things).

**Comment by erri120** [comment]
So return `MetadataIdProperty` if the item already exists and `MetadataNameProperty` if it does not?

**Comment by JosefNemec** [comment]
Yes. You also don't have to explicitly check for existing items with the same name, Playnite will do that for you and will prevent duplicates to be created.
