### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by oOXenonTitareOo** [JosefNemec/Playnite#2734]
### Bug Description

The theme is missing quite a few translations (hungarian) and has some mistranslations too. I think I could translate it tho with some help.

### To Reproduce

Change playnite to hungarian and see the english texts in the theme...

### Diagnostics ID

c34e61da-7dfc-4a46-8ff0-e9ee0cb0c06f

**Comment by JosefNemec** [comment]
Bad translations has to be fixed on Crowdin: https://crowdin.com/project/playnite

If something is not translatable, add screenshot of what it is. You don't mention a single specific thing in your bug report.

**Comment by oOXenonTitareOo** [comment]
It's fixed by me. But there's one "bug". The theme adds "game" after launch. It is a problem because it should be "Játék Indítása" in hungarian. Currently, it feels like it's been half translated. 
![image](https://user-images.githubusercontent.com/43107574/147815356-f41baa52-f21f-4928-a229-7537da6809cd.png)

**Comment by JosefNemec** [comment]
You need to report that to theme's author.
