### ISSUE TITLE
Stops the autostart after an Playnite-update

### ISSUE THREAD

**Issue by forenta** [JosefNemec/Playnite#2735]
### Feature description

I am using my Windows-device without administrator privileges so that friends & guests can use it without breaking it. Whenever there's an update for Playnite, it asks to run it with administrator privilege. Fine so far, but afterwards it _always_ automatically starts the client in that privileged mode and asks _me_ not to do that as you can see it in the screenshot added.
I don't see how this behaviour does make any sense so it would be nice to at least be able to opt-out autostart after an update if it is not possible to run it _without_ admin privileges.

### Screenshots

![Playnite is running with elevated privileges (as an administator). This is not recommended sinc eit gives elevated privileges to all installed extensions and all games/apps started from Playnite!](https://user-images.githubusercontent.com/2451238/147828604-a4251886-43e4-48f6-bf67-a1169487989a.png)

**Comment by JosefNemec** [comment]
Playnite updates do not require admin privileges. I don't know what your setup is, but if you are using built-in auto-update, you should not be getting elevation dialog.

**Comment by JosefNemec** [comment]
Is the user account running Playnite standard account (I don't mean administrator account) or limited one? Is Playnite installed in the directory where that account has write access?

**Comment by forenta** [comment]
Without admin privileges it's not possible to get writing access to %ProgramFiles% at all. But this leads me to the idea to re-install it to the c:\-root and wait for the next turn if this already fixes it which it should this way.
Thanks for your support & answering!

**Comment by JosefNemec** [comment]
You should not be installing Playnite into Program Files in the first place. That place requires elevated privileges for write in general, that's why Playnite doesn't install there by default. Use location that doesn't require elevated privileges for write and you'll have no issues.

**Comment by JosefNemec** [comment]
Closing since this a side effect of where user chooses to install Playnite. Selecting location that requires elevated privileges for writing will simply cause issues.
