### ISSUE TITLE
PlayniteApi.MainView.SelectGame(Id) does not trigger OnGameSelected(args)

### ISSUE THREAD

**Issue by felixkmh** [JosefNemec/Playnite#2736]
### Bug Description

Calling PlayniteApi.MainView.SelectGame(Id) does not trigger OnGameSelected(args).

### To Reproduce

Selecting copies using DuplicateHider's theme integration calls PlayniteApi.MainView.SelectGame(Id) but the OnGameSelected() callback is not called for any plugin. 

### Diagnostics ID

n/a

**Comment by JosefNemec** [comment]
Can't reproduce. Please add sample code that reproduces the issue for you.

**Comment by felixkmh** [comment]
It seems that the event is only triggered if the game selected via SelectGame(Id) is matching the current filters. And DuplicateHider's source selector works by selecting games that are marked as hidden (while not having the hidden filter active), it does not trigger the event.

**Comment by JosefNemec** [comment]
Hmm I would almost say that's expected behavior since you can't technically select a game, as an user, which is not visible. I'll think about it.

**Comment by felixkmh** [comment]
Just so you know where this came up: a user noticed that the custom UI integration for the SuccessStory extension in the main view was not working properly when selecting a hidden duplicate using DuplicateHider. This is because SuccessStory's theme integration relies on some properties that are not bound to the current data context, but are part of the settings and rely on the OnGameSelected event. So any extension working that way would show unexpected behaviour in conjunction with DuplicateHider or any other extension selecting games that are not matched by the current filters.

**Comment by JosefNemec** [comment]
Done in devel via 4e82a31d564713d134eb1967049111d4df6b98fc
