### ISSUE TITLE
Fullscreen Scroll vs. Game Details Open/Close

### ISSUE THREAD

**Issue by zeroantix** [JosefNemec/Playnite#2739]
### Bug Description

Scrolling in Fullscreen Mode seems to lag/jolt upon closing Game Details View once opened.
Initially noticed via a Custom Theme, but can replicate within the Default Theme, but on a smaller noticeability scale. Attempts also in Safe Mode with ALL Image quality settings, the outcome the same or similar. 

### To Reproduce

In Fullscreen Mode:

1) Scroll as fast as possible, right to left a few times through a large list of Games.
2) Open Game Details
3) Close Game Details
4) Repeat Step 1

### Diagnostics ID

f0a14754-06c5-4f67-9693-c35ec4bf0885

### Screenshots

Video link included - https://youtu.be/j74S0Z5-sPc

**Comment by JosefNemec** [comment]
Fixed in devel.
