### ISSUE TITLE
Database update failed : Database must be migrated before opening

### ISSUE THREAD

**Issue by AlexandreJadin** [JosefNemec/Playnite#2744]
### Bug Description

Hello,

I recently updated Playnite to version 9.14

After the update, upon startup of the program I have the following error pop-ups

![image](https://user-images.githubusercontent.com/10000398/148103378-6ec9fb00-f273-441c-901e-05911205e834.png)

![image](https://user-images.githubusercontent.com/10000398/148103431-3937ff60-a23b-4f66-a146-7550b5cb1003.png)

Which can be translated to:

"database update failed"

"Unable to open library database
Database must be migrated before opening"

I have uninstalled and reboot the computer and  re-installed playnite without seeing improvements (even launching in safe mode)

I am also joining the playnite.log file it seems to contain errors related to the issue (line 27010)
[playnite.log](https://github.com/JosefNemec/Playnite/files/7809519/playnite.log)

Is there a way to fix this issue and re-open the database with minimal loss?
Which file would help?

Thank you in advance
```

04-01 18:59:50.637|ERROR|PlayniteApplication:Failed to migrate database to new version.
LiteDB.LiteException: Cannot insert duplicate key in unique index '_id'. The duplicate value is '{"$guid":"067765b0-94b4-4f5d-bb0d-b7db4f06f8a5"}'.
   Ã  LiteDB.IndexService.AddNode(CollectionIndex index, BsonValue key, Byte level, IndexNode last)
   Ã  LiteDB.IndexService.AddNode(CollectionIndex index, BsonValue key, IndexNode last)
   Ã  LiteDB.LiteEngine.InsertDocument(CollectionPage col, BsonDocument doc, BsonType autoId)
   Ã  LiteDB.LiteEngine.<>c__DisplayClass22_0.<Insert>b__0(CollectionPage col)
   Ã  LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func`2 action)
   Ã  LiteDB.LiteEngine.Insert(String collection, IEnumerable`1 docs, BsonType autoId)
   Ã  LiteDB.LiteEngine.Insert(String collection, BsonDocument doc, BsonType autoId)
   Ã  LiteDB.LiteCollection`1.Insert(T document)
   Ã  Playnite.Database.GameDatabase.<>c__DisplayClass280_0.<MigrateNewDatabaseFormat>g__convertList|3[TOld,TNew](String dir, Action`2 propertyMapper) dans C:\projects\playnite\source\Playnite\Database\GameDatabaseMigration.cs:ligne 221
   Ã  Playnite.Database.GameDatabase.MigrateNewDatabaseFormat(String databasePath) dans C:\projects\playnite\source\Playnite\Database\GameDatabaseMigration.cs:ligne 392
   Ã  Playnite.PlayniteApplication.<MigrateDatabase>b__133_0(GlobalProgressActionArgs _) dans C:\projects\playnite\source\Playnite\App\PlayniteApplication.cs:ligne 1105
   Ã  Playnite.ViewModels.ProgressViewViewModel.<ActivateProgress>b__31_0() dans C:\projects\playnite\source\Playnite\ViewModels\ProgressViewViewModel.cs:ligne 122
```

### Diagnostics ID

71786335-a947-4afe-bb36-85b6606956b6

**Comment by JosefNemec** [comment]
Did you modify database library files directly when on old version? Because this only happens if some changes to library files were made outside of Playnite.

Go to `C:\Users\Alexandre Jadin\AppData\Roaming\Playnite\`, zip and upload `library` folder, I'll try to repair it. You can exclude `files` subfolder, which could be large and I don't need it.

**Comment by AlexandreJadin** [comment]
Here it is

[library.zip](https://github.com/JosefNemec/Playnite/files/7809602/library.zip)

Never modified this manually outside the program though, 
I possibly had some extensions, will try to find which in a backup

**Comment by JosefNemec** [comment]
[Here's migrated library](https://github.com/JosefNemec/Playnite/files/7813011/library.zip). There were two games I had to remove because they had corrupted (duplicated) data. They were definitely modified by some 3rd party.

**Comment by AlexandreJadin** [comment]
Worked like a charm, thank you!
