### ISSUE TITLE
PlayStation Now plugin implementation

### ISSUE THREAD

**Issue by Gotcha007** [JosefNemec/Playnite#2745]
### Feature description

I'm currently trying to implement a plugin for the Playstation Now service based on the Geforce now existing plugin.
The goal here is to grab the list of available games on the PS Now platform and add a feature name PS Now

The list of games will be pulled from https://browse.prod.gaikai.com/apollo1/v1/np/US/en (for the US version). Other countries will also be implemented in the future.

For now there is now way to launch the game directly as Ps Now software does not allowed it. So when the user will play a game that is on PS Now it will simply open the application. It will be like that until Sony decide to open up their software like Geforce now is doing for example.

Not sure if this should be considered an extension or a library.

**Comment by JosefNemec** [comment]
I don't know why is this open as a feature request here. Make a plugin and publish it for other people to use. This repository is only for core Playnite features and this won't be accepted as a core feature. All integrations with other services have to be made as plugins.
