### ISSUE TITLE
metadata and library data randomly reset

### ISSUE THREAD

**Issue by zany130** [JosefNemec/Playnite#2746]
### Bug Description

metadata and library data randomly reset

### Diagnostics ID

b9fd5715-306f-496b-a505-6c6cbfe40607

**Comment by JosefNemec** [comment]
1) The bug description tells me basically nothing. Please specify what's actually happening.
2) Playnite never deletes metadata or games from the library on it's own, so it must be some 3rd party (extension or app) messing with that data.
3) There's a lot of errors in logs from various 3rd party extensions you have installed. Try disabling them to see if they cause the issue (like issue template recommends).

**Comment by zany130** [comment]
all library data and metadata are randomly getting deleted It seems to happen when I switch between desktop and fullscreen mode and it still happens even with all extensions disabled  here are more logs ffe237bf-3565-4dde-b3c6-96ca193494ed

**Comment by JosefNemec** [comment]
Make a video please, there's no error in the logs indicating any issue.

**Comment by JosefNemec** [comment]
Also switch to the default theme to make sure it's not a theme issue.

**Comment by zany130** [comment]
it's very difficult to get a video of since it happens randomly. basically, I will have my library with all its metadata downloaded and any custom play actions setup. ill switch modes  and all of the sudden my game library is empty and has to be populated again and all metadata redownloaded

**Comment by JosefNemec** [comment]
Then please try and make a diag. package right after the issue happens again. I just don't see any relevant errors in logs you posted so far.

Do you use some cloud sync tools to backup/sync Playnite's files? Like OneDrive, Google Drive etc.

**Comment by zany130** [comment]
well I do backup playnite  roaming files to Pcloud

**Comment by JosefNemec** [comment]
Library files are locked when Playnite is running so cloud sync app can't mess with them. But, they are briefly unlocked when modes are being switched (because Playnite is technically shutting down and starting new instance).

I don't know how Pcloud works, but one possible issue could happen if it tries to access library files during mode switch, leading to data corruption. But then again, I would see that in logs. I only see one error related to database opening, but that one would not lead to data being lost.

**Comment by zany130** [comment]
I haven't been able to reproduce the bug yet after disabling backup into pcloud  , but,  looking at old logs only errors I'm seeing are the occasional failed download which is fine, and this ```System.IO.IOException: The process cannot access the file 'C:\Users\Andres\AppData\Roaming\Playnite\library\platforms.db' because it is being used by another process.```
which I talked about on the discord and seems to happen when playnite try to exit (either to shut down or switch)  and some extensions are calling the ` OnLibraryUpdated method`  maybe in some cases, it seems to be causing corruption when pcloud syncs stuff when there double processes?

**Comment by gsabater** [comment]
Im having the same issue, closing and opening playnite again seems to reset all data, including imports, media must be downloaded again and any status for favorites, playing or anything is reset as well.
