### ISSUE TITLE
Download Metadata not working anymore

### ISSUE THREAD

**Issue by emperordaniel27** [JosefNemec/Playnite#2747]
### Bug Description

The button "Download Metadata" from "Edit Game Details" window is not showing anything, if i press nothing happens.
For me it's important to download because i have a large library and i don't want to enter manually all the details.

Thanks!

### To Reproduce

Add game manually->Download Metadata button.

### Diagnostics ID

7fb36dee-221c-4aef-a8f6-b0af690af802

### Screenshots

![Capture](https://user-images.githubusercontent.com/97333359/148636796-1205335b-2a5e-4e59-8782-101367971d3b.JPG)

**Comment by JosefNemec** [comment]
You don't have any metadata (or library) extensions installed, I don't know why that is, but all library integrations and metadata support are provided as plugins. If you upgraded from older Playnite versions then you need to also update those plugins from new "Add-ons" menu.

**Comment by emperordaniel27** [comment]
I installed them from "Add-ons" menu. It works
Thank you very much.
