### ISSUE TITLE
Clicking empty part of horizontal scrollbar moves window vertically (List View)

### ISSUE THREAD

**Issue by FolkSong** [JosefNemec/Playnite#2749]
### Bug Description

Note: this only applies to List view in windows mode.

Normally with a scrollbar there is the empty "track" running all the way along the window, and then the actual "bar" representing the viewable area (sorry if these aren't the standard terms). Normally to scroll the window you can either drag the bar along the track, or you can click the empty track on either side of the bar to make it jump in that direction.

In Playnite, the vertical scrollbar works as expected. However, the horizontal scrollbar does not. When clicking the empty track either to the left or the right of the bar, it makes the window scroll downwards! Exactly the same as if you clicked the empty track of the vertical scrollbar below the bar.

I confirmed that the problem is present even in safe mode. I have noticed this issue ever since I started using the program some months ago.

### Diagnostics ID

e4120f73-3b13-4b3e-b5c2-df03b7e9ff3a

**Comment by JosefNemec** [comment]
Fixed in devel.
