### ISSUE TITLE
Completion status Kanban

### ISSUE THREAD

**Issue by minifluff** [JosefNemec/Playnite#2753]
### Feature description

I was thinking of ways to better deal with games that I have completed and backlog. I came up with the idea that was sparked by a trello plugin that I believe you could impliment on the sidebar with library and stats. You could make a kanban style board to deal with games in backlog and diffetent statuses. You could then just drag a game through the catagorys as you get closer to completion which then would update the completion status.

**Comment by JosefNemec** [comment]
This sounds like something that should be probably made as a separate plugin. At least it would be very low on my list of priorities for foreseeable future as a built-in feature.

**Comment by JosefNemec** [comment]
Closing as this is very unlikely to be done as built-in feature due to its niche nature.
