### ISSUE TITLE
Official Riot Client support

### ISSUE THREAD

**Issue by m1karii** [JosefNemec/Playnite#2754]
### Feature description

It 'd be nice to have an official Riot Client support for Valorant, LoL players

**Comment by Jeshibu** [comment]
It's not official in any sense but one already exists: https://playnite.link/addons.html#Riot

**Comment by JosefNemec** [comment]
There already is 3rd party plugin for it as Jeshibu linked.

**Comment by JosefNemec** [comment]
> I'm aware of that, however i propose official support (directly in the client), since (among other) I'm concerned for the whole

All integrations are provided as 3rd party plugins. The only difference is that some of them are developed by me. Playnite treats all integrations the same way, no matter who wrote them.
