### ISSUE TITLE
Multiple Background Image + Shuffle +[BigPictureMode Compatibility]

### ISSUE THREAD

**Issue by NO84MADD** [JosefNemec/Playnite#2757]
### Since I now use this as my **Primary Library Manager**, It gets boring to see only _One Picture_ as a **Game's Background**, since _theme_ support is also available for this program. 

It would be **Great** and **Soothing** to see if we can add _Multiple Images_ for a **Game's Background** with the _ability_ to **shuffle** it. So it looks _**new & refreshing**_ every time we hover over, or tap on a game **[Like a Screen Saver]**

maybe even a small **AI** which automatically picks images from google and keeps updating it 😃 

But the **_ability_** to manually **_add, control images_** and **Big Picture** _Mode Compatibility_ is a must. 😶‍🌫️

**Comment by JosefNemec** [comment]
#552
