### ISSUE TITLE
IGDB Metadata Plugin - New games not showing

### ISSUE THREAD

**Issue by LerainL** [JosefNemec/Playnite#2759]
### Bug Description

Some of the newly created games in IGDB don't show inside Playnite using the IGDB plugin.

https://www.igdb.com/games/dynamite-duchess is a perfect example for that.

![image](https://user-images.githubusercontent.com/57292109/150102814-248b712a-bb29-4f16-84d0-96c198c75e72.png)

Last time I wrote on the Discord chat about this, someone from development told me that the IGDB API was crap, hence those problems occurring and it's not a problem from Playnite's side.

So I've contacted IGDB/Twitch about this, if they can test this internally. 
Through the whole process I've stumbled upon the IGDB API documentation and I tough - why not test it myself.

I did that and it seems the API is working as intended at least in the scope of Postman, while sending something like "search "Dynamite Duchess"; fields name;"

![image](https://user-images.githubusercontent.com/57292109/150102729-10f2adf2-0036-4541-bc6c-a3e717653b7c.png)

So it seems that this is a Playnite's problem after all. The IGDB Plugin source code was removed btw : https://github.com/JosefNemec/Playnite/tree/master/source/Plugins/IGDBMetadata - so i cannot see what is actually happening there.

I would be very glad if someone can take a look at that or at least provide the source code to the IGDB plugin so i can do try to do more investigation on the case.

Thank you

### To Reproduce

Try searching for "Dynamite Duchess" inside Playnite with active IGDB plugin integration. You wont get anything.

### Diagnostics ID

9bbe2f63-f642-495e-81ff-cd8fed12251a

### Screenshots

The screenshots are inside the  **Bug Description**  section

**Comment by JosefNemec** [comment]
Fixed.

**Comment by LerainL** [comment]
Indeed 

![image](https://user-images.githubusercontent.com/57292109/150105096-8261a098-742a-4909-aafd-e8367b9611a2.png)

Thank you
