### ISSUE TITLE
Grouping titles by services in fullscreen mode

### ISSUE THREAD

**Issue by SirBedwyr** [JosefNemec/Playnite#2761]
### Feature description

I did not find this in the outstanding issues afaict.

Currently in Fullscreen mode you can split games from different sources/libraries by sorting by library. It would be neat if doing that would display some kind of a labeled gap between the libraries that sets off which library you are on. Desktop mode already does this with a collapsible group label. Something similar in Fullscreen would make it easier to tell where you are whether it's a whole line break or just a blank spot with the name "GoG" or "XBox" or "Steam" to set things off.

**Comment by JosefNemec** [comment]
Duplicate #2145
