### ISSUE TITLE
IGDB metadata plugin: more options for downloading artwork

### ISSUE THREAD

**Issue by shakeyourbunny** [JosefNemec/Playnite#2763]
### Feature description

Currently, the IGDB metadata plugin only has the option "Use screenshots if artwork is not available".

Would it be possible to have this reworked, ie have a drop down to choose between these options?
- only download screenshots
- only download artwork
- download screenshots, fallback to artwork
- download artwork, fallback to screenshot

Also, if possible, the screenshots / covers should only stick for the platform, ie no Amiga screenshots for a black and white Game Boy game.

Would be really nice imho.

**Comment by darklinkpower** [comment]
Incorrect repository, should go in https://github.com/JosefNemec/PlayniteExtensions

**Comment by shakeyourbunny** [comment]
> Incorrect repository, should go in https://github.com/JosefNemec/PlayniteExtensions

The forum page for the IGDB links to this issue tracker.

**Comment by shakeyourbunny** [comment]
I recreated this issue over yonder.

**Comment by darklinkpower** [comment]
Crow must have forgotten to update it, it must get difficult to maintain things in many places but all extensions issues including igdb have been moved to that repo.

**Comment by shakeyourbunny** [comment]
no biggie, but thank you for pointing this out.
