### ISSUE TITLE
Folders with the words "setup/uninst" in its name are ignored from "Scan Automatically..."

### ISSUE THREAD

**Issue by LerainL** [JosefNemec/Playnite#2766]
### Bug Description

I've just found something interesting...

I'm using the "+ Add Game" > "Scan Automatically..." > "Scan Folder..." function.

Basically with this if i scan a folder (called "Test" in this example) that contains, lets say 5 EXE files, I would get a list of them inside Playnite.
And that works just fine (first picture).

![image](https://user-images.githubusercontent.com/57292109/150679850-a99b2556-2e54-4452-9f7e-7c9a72595f3d.png)

But if i add the word "Setup" on the folders name ("Test Setup" in my example) - Playnite will automatically skip this folder and won't find any EXE files remaining inside (second picture).

![image](https://user-images.githubusercontent.com/57292109/150679861-07f8f593-d1cd-4e19-8793-76e4c5a76040.png)

Way back I was asking for a way for Playnite to exclude specific folders from automatic scanning and no one told de about this, so i reckon it's quite unknown.

I've wrote this on Discords with Crow saying it's a bug and Jeshibu pointing to a cs code snippet here : https://github.com/JosefNemec/Playnite/blob/f97e5c8b77b0404807259bcd369512a27ec34967/source/Playnite/Common/Programs.cs

`private static readonly string[] uninstallerMasks = new string[]
        {
            "uninst",
            "setup",
            @"unins\d+"
        };`

### To Reproduce

Add the word "Setup" to any folder and it will be ignored.

It's also triggered by "uninst"

### Diagnostics ID

88ce13c4-f719-4bbe-915e-35706b6150d2

### Screenshots

already posted above

**Comment by JosefNemec** [comment]
Fixed in master.
