### ISSUE TITLE
Playnite crashed while creating and adding a new tag on multiple selected games.

### ISSUE THREAD

**Issue by Foshitz** [JosefNemec/Playnite#2767]
### Bug Description

Playnite crashed while creating and adding a new tag on multiple selected games.

### To Reproduce

1. Select multiple games
2. Right-click to edit game details
3. Click the + next to Tags to create and add a new tag.

### Diagnostics ID

7971107b-4937-4ee4-b887-7a1b5d0b9ce1

**Comment by JosefNemec** [comment]
Fixed in master by 1529482cee12c3604e3f0db27a7ab4bc43bece37
