### ISSUE TITLE
Auto-Update Program and Addons

### ISSUE THREAD

**Issue by FolkSong** [JosefNemec/Playnite#2770]
### Feature description

This would be a convenient option. Almost every time I start Playnite there's either a program update or some addon updates, which I have to spend time clicking through. I always just install them so there's no point asking me every time. I would like it to just go ahead and install them (or schedule them to be installed on the next restart).

Obviously there should be an option to disable it for people who don't like the idea.

Thanks for reading and for all your work on this great program!

**Comment by JosefNemec** [comment]
#2580
