### ISSUE TITLE
Ignore already imported EXEs when using "Scan Automatically..." 

### ISSUE THREAD

**Issue by LerainL** [JosefNemec/Playnite#2772]
### Feature description

I've made a bit of a retro games museum with my Playnite, manly from abandoned games and such that are very hard to find.
I have 461 games right now, planing to expand that even further.

What is really troubling for me is the state of "Scan Automatically..." that will always offer to import all of the EXEs in folder "Games" (for example), without caring that I have 99% of those EXEs already imported in my library.

Right now I need to add 30 more games to that collection that will be moved to the folder "Games", which means I have to hand pick them from the stack of 461 more EXEs (or 491 in total).

That doesn't seems very appealing.

Then I thought using something like a "Set" would totally do the job.
The keys can be the path to the EXEs with their names.
For example "H:\Collections\Games\Launchers\Playnite\Games\Engines\ECWolf\Spear of Destiny\Destiny.exe"

First we use the currently imported games to create that Set and populate it with keys to the corresponding EXE's paths.

Then we start using the "Scan Automatically..." functionality, applying it on the set.
Since no duplicates would be accepted, only new and unknown (not imported) EXEs would be added to the set.

Then we can show only the new entries of the set and offer them for importing, making the whole process a walk in the park.

In my case, I've actually made sure that I have only one valid EXE per game folder, so I wont see any useless old EXEs using this method - only the new ones and I can instantly import those 30 new games.

Isn't that marvelous?

The offered implementation may not be the best way, but this is what I thought. 

Thank you

### Screenshots

Example of the current state .. I have all those games already imported in my library, but still they appear on the "Select games to Import" box
![image](https://user-images.githubusercontent.com/57292109/151033936-130f460f-812c-4fec-a0b6-b1cf866033c1.png)

**Comment by JosefNemec** [comment]
Was added in Playnite 10
