### ISSUE TITLE
Multiple columns for multiple-value fields in grid mode detail view

### ISSUE THREAD

**Issue by Jeshibu** [JosefNemec/Playnite#2776]
### Feature description

Having lots of tags on a game takes up too much vertical space in grid mode detail view right now. Having multiple columns (preferably dynamic) would alleviate this.

### Screenshots

![image](https://user-images.githubusercontent.com/37979717/151168590-4ed650e2-464f-4186-99db-498accf86bc9.png)

**Comment by JosefNemec** [comment]
Will be done via #2594
