### ISSUE TITLE
Epic: "STAR WARS Jedi: Fallen Order" isn't shown in the library

### ISSUE THREAD

**Issue by yarda** [JosefNemec/Playnite#2782]
### Bug Description

Recently, I bought "STAR WARS Jedi: Fallen Order" on Epic [1]. But the game is not shown in the Playnite library. In the Epic client it is correctly shown and even on the Epic web store there appears "in library".

I had to click install in the Epic client. It installed Origin client and paired the game with the Origin. After it, when I synchronized Origin library in the Playnite, the game appeared under the Origin in the Playnite.

I think it should be shown from the beginning under the Epic and without the need of installation similarly as it is shown in the Epic client.

[1] https://www.epicgames.com/store/en-US/p/star-wars-jedi-fallen-order

### To Reproduce

Probable reproducer: buy "STAR WARS Jedi: Fallen Order" on Epic [1] or similar game (probably games requiring the Origin client).

Sync Epic library in the Playnite. The game is not shown in the Playnite library, but it is correctly shown in the Epic client.

[1] https://www.epicgames.com/store/en-US/p/star-wars-jedi-fallen-order

### Diagnostics ID

068b6d1b-cbc2-4e55-91bc-df08aa700903

**Comment by darklinkpower** [comment]
Wrong repository. As described in the issue template created when opening an issue, issues with extensions should go to this repository https://github.com/JosefNemec/PlayniteExtensions

This game needs to be imported by the Origin plugin as you mentioned since it doesn't get reported by the API used by the Epic plugin.

**Comment by JosefNemec** [comment]
As darklinkpower said, you need to import and start this game using Origin integration.
