### ISSUE TITLE
Allow adding shortcuts for third-party clients to the desktop mode sidebar, like with tools

### ISSUE THREAD

**Issue by Trobador** [JosefNemec/Playnite#2785]
### Feature description

Hi, thanks for your work on Playnite.

Just now, I learned Playnite now let you add shortcuts for software tools to the sidebar in desktop mode, which is awesome. Since this feature exists, I am wondering if it could be extended to allow third-party clients to be added to the sidebar as well ? It would personally be very helpful for me as I often use Playnite's existing task bar dropdown menu for third-party clients. 

While an easy solution would be to add the clients themselves as tools, it would mean bloating the tool list.

### Screenshots

![image](https://user-images.githubusercontent.com/35611827/151793452-ea3e90e4-4c2e-4672-bebe-2ec3d00794dc.png)

**Comment by JosefNemec** [comment]
Will be done via #2604

**Comment by Joackk** [comment]
Hello. How did you do that? I tried drag and drop and looked in Settings but couldn't find How to set this section
