### ISSUE TITLE
Improvements to play action selection window

### ISSUE THREAD

**Issue by akumenon** [JosefNemec/Playnite#2786]
### Feature description

Henlo,

I'd like to request the following improvements to the play action selection window in desktop mode:
1. Navigation via keyboard buttons (arrows to move, enter to select, escape to back out already works).
2. Scroll bar for when the number of play actions is high (e.g. when you use many different mods).

These are already available in full-screen mode, so desktop mode being at parity is desirable in my opinion.

Thank you for your hard work.
Best regards.

P.S. Probably related to #272

**Comment by V0idhead** [comment]
I'd like to implement this.
And also add the Number keys (1-9) to start the corresponding play action as a third point.

**Comment by JosefNemec** [comment]
Done in devel.
