### ISSUE TITLE
Fullscreen Xbox keyboard input fails

### ISSUE THREAD

**Issue by ShroudedBowman** [JosefNemec/Playnite#2800]
### Bug Description

Xbox chatpad setup to function on windows as a normal keyboard (works) is not recognized in playnite Fullscreen mode to type in the search bar.

### Diagnostics ID

N/A

**Comment by JosefNemec** [comment]
I don't own Chatpad so I have no idea how it works, but if it just sends keyboard inputs, then you need to move focus to textbox first.

**Comment by JosefNemec** [comment]
Most likely fixed by 0bbb056ff833d0418b9bd47c3b570b73ed7bcbce in devel. Feel free to reopen if it still doesn't once Playnite 10 is out.
