### ISSUE TITLE
Battle.net won't launch games, and requires logging in every time.

### ISSUE THREAD

**Issue by xCeeTee** [JosefNemec/Playnite#2803]
### Bug Description

Battle.net games do not load up with the rest of the games initially. I get a notification to say there was an issue and to verify my account again. When I go into addon settings to verify the account, it shows it's already logged in. At this point, the games then appear in my library.

So I press on the button to launch a game, such as Overwatch, and then after about 40 seconds Battle.net's client opens up, with a picture of the game I clicked on. However, it has my email address only and requires my password every single time. Once I enter the password the game still doesn't launch. The launcher just waits for me to hit play on any game I own. So every time it requires me to manually enter my password and then press play for the 2nd time. Also, Playnite then reports the game as "launching" until I manually reset it. However, if I don't launch through Playnite, it works perfectly. Steam can launch the games without any issues whatsoever.  Also, Playnite then reports the game as "launching" until I manually reset it.

### Diagnostics ID

bb8143f3-9c6b-453d-a612-fc7a846e26cd

**Comment by JosefNemec** [comment]
1) Wrong repository, please read issue template carefully next time.
2) Account login being desynchronized is a known issue already.
3) As far as game launch, that's not in our control. Battle.net integration just launches bnet launcher with an argument to start a specific game (for example `--exec="launch S2"` for StarCraft 2) and what happens next is up to the launcher, Playnite has no control over the actual start process once the launcher is started.
