### ISSUE TITLE
{InstallDir} not working when using UNC paths for network drives

### ISSUE THREAD

**Issue by Kartug01** [JosefNemec/Playnite#2806]
### Bug Description

When using `{InstallDir}` in a ROM path for an emulated game, and the Installation folder is on a network drive using UNC paths (for example `\\SomeServer\SomeFolder`), `{InstallDir}` doesn't convert to a proper network path. Instead of `\\` in the beginning of the path, we only get a single `\`, creating an invalid path. See attached screenshot.

When adding emulated games using a scanner, Playnite uses `{InstallDir}` in ROM paths by default. This means the added games are unplayable, since the paths are wrong. Another issue is when re-running the emulated game scanner, it doesn't recognize that the games have already been added, again since the paths are wrong, and adds a duplicate game every time the scanner is run. This is the reason for issue #2697.

### To Reproduce

1. Add Game > Emulated Game
2. Add scanner, and scan a ROM folder that's on a network drive (using UNC paths, so `\\SomeServer\SomeFolder`)
3. Import the found ROM
4. Edit the imported game > See that Installation folder says `\\SomeServer\SomeFolder` and ROM file says `{InstallDir}\SomeROM.extension`
5. Try to play the game, get error or crash

### Diagnostics ID

bfc5c536-62d6-411d-b3f5-cbbbb1fc19b4

### Screenshots

![Error](https://user-images.githubusercontent.com/78300679/153299849-2ed7be61-1740-41e3-a62a-14ea9eda1fb1.png)
An error I get from Dolphin Emulator. Notice that the beginning of the path only has a single `\`.

**Comment by JosefNemec** [comment]
Will be fixed as part of #950
