### ISSUE TITLE
Allow separate Emulator options for Fullscreen vs Windowed mode

### ISSUE THREAD

**Issue by anaisbetts** [JosefNemec/Playnite#2808]
### Feature description

When I run an emulated game via Playnite in normal mode, I want the emulated game to also be in a window, and when I run a game via Fullscreen mode, I want the game to be in Fullscreen mode as well. To do this, I need to be able to set command-line switches that are only applied when Playnite is in Fullscreen mode

### Screenshots

![image](https://user-images.githubusercontent.com/1396/153507418-c9a27b94-6868-450b-93cc-d49c6785e25a.png)

^^ An extra field: "Full-screen command line arguments" there would work great ✨

**Comment by JosefNemec** [comment]
Create separate emulator profiles with different arguments, that's what they are for.

**Comment by anaisbetts** [comment]
@JosefNemec That would result in every game being doubled, or?

**Comment by JosefNemec** [comment]
You always use only one specific profile for scanning. So you can have how many profiles you want and it won't result in duplicates.

**Comment by anaisbetts** [comment]
I'm still not following how this helps. So, I create a duplicate profile:

![image](https://user-images.githubusercontent.com/1396/153768381-33c506e8-38a8-46df-967b-d306c0a5bc1a.png)

However, there is no way to select which emulator profile to use in Fullscreen, it seems to still pick the first one:

![image](https://user-images.githubusercontent.com/1396/153768354-88f1a7c6-02c8-4958-8059-d76fe93e8e3d.png)

**Comment by JosefNemec** [comment]
- you need to change configuration of game's Play action from a specific profile to "Choose at startup"
- you will then get an option to choose which one to run after clicking Play from that game menu

**Comment by JosefNemec** [comment]
One of the issues I see here is that Playnite will always assign a profile used for scanning to the Play action. So we might need some option to force scanned games to use "Choose at startup" option instead of a specific profile that imported those games.

**Comment by anaisbetts** [comment]
If I wrote a PR to fix this would you take it? Asking people to do all of this work in order to get a behavior that should probably be built in (my SNES ROM collection has 800+ games, that's a lot of manual configuration changes!), _as well as_ making them choose a profile every time they launch a game, seems a bit Silly.

**Comment by JosefNemec** [comment]
PR for what specifically? If the root issue here is that RetroArch is not by default starting with --fullscreen argument, then the only change needed is to modify RA profiles: https://github.com/JosefNemec/Playnite/blob/master/source/Playnite/Emulation/Emulators/RetroArch/emulator.yaml

The change will get automatically applied to all imported/existing profiles/emulators.

**Comment by anaisbetts** [comment]
It would:

1. Add another field to Emulator profiles `FullscreenStartupArguments` that if set, override `StartupArguments` when launched via Playnite Fullscreen
2. Add the settings UI to be able to change this field
3. Change the launcher to prefer `FullscreenStartupArguments` if set, and Playnite is in Fullscreen mode
4. Update the default profiles to have an appropriate default `FullscreenStartupArguments` value

**Comment by JosefNemec** [comment]
I don't agree that we need FullscreenStartupArguments, I don't see a reason why we should have separate field for that. In 99% of cases you are always going to start an emulator only one way.

Most of the other emulators have profile that already defaults to running an emulator in fullscreen mode (if that emulator supports in via cmdline), so imo the only change here should be modifying built-in RA profiles to run in fullscreen by default.

**Comment by anaisbetts** [comment]
Hm, I might just use my own fork then. Thanks anyways!
