### ISSUE TITLE
Unable to open Playnite 9.x Add-ons Window

### ISSUE THREAD

**Issue by nils-hde** [JosefNemec/Playnite#2815]
### Bug Description

I am unable to open the add-ons page (see attached screenshot of how it simply greys out when I open the add-ons)

The window appears blank, and I cannot move it even using Windows + -> key. Settings windows etc. work fine.

Using Windows 11, 200% DPI scaling on a dual-monitor setup. I also use DisplayFusion to manage monitor setups but can confirm it is not causing the issue.

What I've tried:

- I checked safe mode to no avail
- deleting %appdata%\playnite\windowPositions.json file (while Playnite is not running) did not help
- Added both running binaries from Playnite (incl. browser instance) to the exclusion lists of RivaTuner and DisplayFusion to no avail. Also, turning off GPU acceleration did not do anything

### Diagnostics ID

7d0bcd75-ec7b-434c-860f-912f0586cf7e

### Screenshots

![Screenshot 2022-02-10 122411](https://user-images.githubusercontent.com/49347604/154251131-95e61e0d-9557-494a-b315-37d2202db216.png)

**Comment by JosefNemec** [comment]
Does switching to 100% DPI fix it? That window is not different to any other Playnite windows, so it's weird that other windows have no issues.

**Comment by nils-hde** [comment]
Thanks for the reminder!

I am not sure why I haven't tried that yet even though mentioning it. When setting both monitors to 100% I found that the window got positioned at the very bottom right corner, and was able to pull it back to the center. Now after setting DPI back to 200% everything works fine!

**Comment by JosefNemec** [comment]
That is very weird because deleting `windowPositions.json` should have lead to the same "fix".

**Comment by nils-hde** [comment]
True, I might have confused the installation directories (I just saw there was a 2nd old Playnite installation)
