### ISSUE TITLE
I have a suggestion

### ISSUE THREAD

**Issue by AniFacer** [JosefNemec/Playnite#2818]
### Feature description

1. Add a picture browsing control as shown in the figure

2. When there are multiple background pictures for selection during metadata download, you can select one as the background picture, and the other pictures can be added to the picture collection by the user

### Screenshots

![image](https://user-images.githubusercontent.com/44011463/155286259-431b2193-fd3d-477b-b675-8280783ff095.png)
![image](https://user-images.githubusercontent.com/44011463/155286537-15275640-a708-4521-8d6d-e842566f02bd.png)

**Comment by JosefNemec** [comment]
#552
