### ISSUE TITLE
"Completion Status" filter doesn't list all available options

### ISSUE THREAD

**Issue by jerrygreen** [JosefNemec/Playnite#2822]
Filter shows:

![image](https://user-images.githubusercontent.com/13215662/156285228-62bc6368-7234-4afd-8b12-353399a96503.png)

While the full list is:

![image](https://user-images.githubusercontent.com/13215662/156285708-36a82294-b334-4002-879c-8c2db1c20d72.png)

### Diagnostics ID

15a4b82e-9447-4460-9115-5bccf911d78d

**Comment by JosefNemec** [comment]
You have "Show only assigned fields on filter and explorer panels" option enabled.
