### ISSUE TITLE
Suggestion: Change how "Time Played" is calculated

### ISSUE THREAD

**Issue by jerrygreen** [JosefNemec/Playnite#2825]
Proposal: Exclude time intervals when the game is minimized. For non-fullscreen applications, exclude time intervals when the game loses focus.

Advanced (probably should be a separate issue): Exclude time intervals when user is afk >10 minutes.

**Comment by JosefNemec** [comment]
This was already proposed some time ago. There is no way how to properly detect if game is being played or no, there's too many edge cases which would not work properly.
