### ISSUE TITLE
Zoom level button moves but actual zoom level does not change when clicking on slider

### ISSUE THREAD

**Issue by ElfDestruct** [JosefNemec/Playnite#2831]
### Bug Description

When viewing library with grid view, using the Zoom control in the bottom bar only changes the size of thumbnails when dragging the button.   Clicking anywhere on the rest of the slider moves the button across the slider control, but this has no effect on the view.

### Diagnostics ID

f631dfff-97e3-4c9f-aea1-422d922220cd

### Screenshots

![Screenshot 2022-03-05 204124](https://user-images.githubusercontent.com/1841304/156909517-31e51357-59b6-42e0-948d-2a44cd9522d4.png)

**Comment by JosefNemec** [comment]
#2597
