### ISSUE TITLE
Dropdown menu: Focus text input on search

### ISSUE THREAD

**Issue by chocolatechipcats** [JosefNemec/Playnite#2833]
### Feature description

Currently, when opening the dropdown menu for certain fields (see pictured), the text input doesn't change focus. However, the user may expect it to and begin typing, resulting in whatever was being typed being lost to the void. A small change to have it automatically focus on the search box makes sense if it doesn't break anything else.

### Screenshots

![2022-03-08 06_35_00-Edit Game Details](https://user-images.githubusercontent.com/47759676/157220019-b47b7b78-47aa-4fff-a2ae-505568415929.png)

**Comment by JosefNemec** [comment]
Done in master via a275dd2882a6eef65477f58695e8b491182b1eca
