### ISSUE TITLE
Installed checkbox un-ticked when game is in a library integration, but a different version is installed.

### ISSUE THREAD

**Issue by rbits0** [JosefNemec/Playnite#2834]
### Bug Description

I have Celeste on Epic Games and as a DRM-free .exe. I do not have the epic games version installed, I have added the exe to playnite manually and checked the "installed" box. But every time I restart Playnite/click update game library, it becomes uninstalled again and I have to click edit and check the installed box again. This does not happen if I have Epic > Import installed games turned off.

### To Reproduce

Have a game in an account from a store, but do not install it. Link the play action to an exe not from that store. Tick the installed box. Restart Playnite. Now it shows as uninstalled

### Diagnostics ID

49118165-db8f-4529-b9d0-0371322d1d28

**Comment by JosefNemec** [comment]
The game is not installed via Epic client so Epic integration marks the game as not installed, this is intended behavior and correct behavior. You either have to import the game as a separate game, install it via Epic client (you can still launch it's exe directly) or disable import of uninstalled Epic games.
