### ISSUE TITLE
[Toolbox] Update toolbox to latest Playnite SDK

### ISSUE THREAD

**Issue by Jeshibu** [JosefNemec/Playnite#2836]
### Feature description

Currently, creating an extension template with toolbox.exe generates a project template for Playnite SDK 5.5.0.0. Updating the nuget package to 6.* and then removing the now invalid Playnite.SDK.Plugins.Plugin override methods is a minor annoyance that needn't be there.

**Comment by JosefNemec** [comment]
Current templates target `6.2.0`.

**Comment by JosefNemec** [comment]
https://github.com/JosefNemec/Playnite/blob/master/source/Tools/Playnite.Toolbox/Templates/Extensions/CustomMetadataPlugin/packages.config
https://github.com/JosefNemec/Playnite/blob/master/source/Tools/Playnite.Toolbox/Templates/Extensions/GenericPlugin/packages.config
https://github.com/JosefNemec/Playnite/blob/master/source/Tools/Playnite.Toolbox/Templates/Extensions/CustomLibraryPlugin/packages.config

**Comment by Jeshibu** [comment]
Odd, I just generated this from toolbox.exe in the Playnite (9.16) directory
![image](https://user-images.githubusercontent.com/37979717/157525832-d461af00-28e5-4c0d-9887-63eedb3281bf.png)

**Comment by JosefNemec** [comment]
That's definitely not from 9.16. Either your installation is messed up or you are running Toolbox from a different version.
