### ISSUE TITLE
Red Dead Redemption 2 is not automatically being picked up as an installed Steam game

### ISSUE THREAD

**Issue by vizionblind** [JosefNemec/Playnite#2838]
### Bug Description

all other Steam games show up in playnite in both desktop and full screen mode, but not red dead 2. It USED to, but not with recent Playnite versions.

### Diagnostics ID

5b9bce87-a6af-43d4-851f-41f81e307cc5

**Comment by JosefNemec** [comment]
This is all handled by Steam integration plugin, not Playnite itself. I recommend trying to reinstall the game or Steam.
