### ISSUE TITLE
Xcloud Games remaining in library

### ISSUE THREAD

**Issue by paultj** [JosefNemec/Playnite#2839]
### Bug Description

I installed the xcloud extension but then didn't like seeing all the games in my library. I deactivated the extension but the games remained. I then uninstalled the extension and the games remain. Do I need to go and manually uninstall all 400 games now?! It seems bugged as the games won't disappear, Playnite is updated 9.16

### Diagnostics ID

7815e0a1-7bac-4e14-ac7e-67186c91a6c7

**Comment by JosefNemec** [comment]
Playnite never automatically removes games, you need to remove them manually.

**Comment by JosefNemec** [comment]
Btw you can remove these games easily: reinstall the plugin, filter by library, select all games on the list and remove them.
