### ISSUE TITLE
Games are not sorted alphabetically after game is installed

### ISSUE THREAD

**Issue by deextercz** [JosefNemec/Playnite#284]
[alph.zip](https://github.com/JosefNemec/Playnite/files/1520699/alph.zip)
I have installed age of empires and it is in the end of list instead at the first place
![age1](https://user-images.githubusercontent.com/23039506/33471681-c76154fe-d66e-11e7-952b-afafc5c35439.PNG)
![age2](https://user-images.githubusercontent.com/23039506/33471682-c779f130-d66e-11e7-9627-36c3a77e02dd.PNG)
Even if I restart playnite results are still same.

**Comment by JosefNemec** [comment]
I checked the diag. package you didn't have sorting set by "Name", but by "Installation directory".
