### ISSUE TITLE
Not installed games show up as installed

### ISSUE THREAD

**Issue by CrazyEyesDave** [JosefNemec/Playnite#2840]
### Bug Description

I imported libraries from Amazon, Battle.net, Epic, GOG, Itch.io and Steam.

For Epic and Steam, multiple games appear as installed and with "Play" button, although they are not installed. They were never installed.

Note: The Epic and Steam libraries are quite large (almost 300 on Epic and 1300 on Steam).

### To Reproduce

- Sync Epic and Steam libraries
- check installed games in the lists
- notice different games appear as installed although they are not

### Diagnostics ID

ded6ad10-e072-44d1-bddf-429df439bb85

**Comment by JosefNemec** [comment]
1) Installation status is handled by each integration plugin separately
2) You have "nstallation Status Updater" extension installed that's been known to cause these issues, try disabling it
