### ISSUE TITLE
Games appear multiple times in games list

### ISSUE THREAD

**Issue by lapo-luchini** [JosefNemec/Playnite#2841]
### Bug Description

In by attempt at an OpenMetrics exporter I'm producing duplicate game data (issue lapo-luchini/PlayniteExporter#1).

I'd expect that for games in multiple libraries, but I only have "Unravel" and "Mass Effect Legendary Edition" in a single library, so I wonder why the games appear multiple times:

```
playnite_game_playtime_seconds{game="Unravel"} 1615
playnite_game_playtime_seconds{game="Unravel"} 9626
```
<img width="324" alt="image" src="https://user-images.githubusercontent.com/420454/157850127-b9e4fe3f-f59e-46d1-8fe7-eb1603ae3363.png">

```
playnite_game_playtime_seconds{game="Mass Effect Legendary Edition"} 7194
playnite_game_playtime_seconds{game="Mass Effect Legendary Edition"} 179834
```

<img width="326" alt="image" src="https://user-images.githubusercontent.com/420454/157850267-2e43f12a-007a-4b0f-aece-caba4585583a.png">

### To Reproduce

Can be checked also with the standard CVS export extension.

### Diagnostics ID

34f46509-5fd2-403a-b742-6df3a89b65a7

**Comment by JosefNemec** [comment]
Game imports are handled by each library plugin separately, it's not handled by Playnite itself. If you have multiple instances of the same game, it needs to be fixed in integration plugin that imported those games.

Since you mentioned these specific games, I'm guessing it's from Origin integration. Origin integration sometimes imports multiple versions of one game, some instances are trial version, EA Play sub versions etc. You need to manually remove those duplicates.

**Comment by lapo-luchini** [comment]
Yeah I can confirm the problem is Origin, I added "GameId" to my exporter.

```
playnite_game_playtime_seconds{gameId="1225560",game="Unravel"} 9626
playnite_game_playtime_seconds{gameId="Origin.OFR.50.0000823",game="Unravel"} 1615
```

But how can I remove them, if they don't show up in the game list?
<img width="147" alt="image" src="https://user-images.githubusercontent.com/420454/157854910-6305e714-1c38-4e37-83b1-0be9c316357b.png">

**Comment by JosefNemec** [comment]
That first instance of Unravel is from Steam, based on that [1225560](https://steamdb.info/app/1225560/) id. You definitely should see every game that's in your library, you most likely have a filter enabled or have those games hidden. Scripts and plugins can't export games that are not in your library and games that are in your library will always show in the UI (unless filter is applied).
