### ISSUE TITLE
Itch integration : start game in itch sandbox

### ISSUE THREAD

**Issue by goldmojo** [JosefNemec/Playnite#2842]
### Feature description

Default playnite start action starts itch games outside from itch sandbox.

It would be nice to start games inside itch integrated sandbox feature.

**Comment by Jeshibu** [comment]
This issue should go to where the itch.io extension repo is, and there's an issue for it there: https://github.com/JosefNemec/PlayniteExtensions/issues/98

**Comment by JosefNemec** [comment]
w
