### ISSUE TITLE
"Cannot start game: game installation not found"

### ISSUE THREAD

**Issue by ForAnAngel731** [JosefNemec/Playnite#2843]
### Bug Description

I have a game installed and have the installation folder set to where the exe is. The game loads when I run the exe manually. How can I launch the game through the playnite ui?

### Diagnostics ID

f021c7b7-6272-476d-b68f-7aaafebd5c66

### Screenshots

![image](https://user-images.githubusercontent.com/101476189/158031649-adf80838-82d3-453f-978a-ba13b0703b07.png)

**Comment by darklinkpower** [comment]
How does your Play Actions look in the Actions tab? Does it have a Play Action added that is pointing to that executable?

In case you added this game manually, you can add games by dragging the shortcut or executable to Playnite and it will configure things for you.

**Comment by ForAnAngel731** [comment]
It worked when I reinstalled the game through playnite.
