### ISSUE TITLE
Parental Controls or Child Lock function

### ISSUE THREAD

**Issue by carsonVibe** [JosefNemec/Playnite#2845]
### Feature description

Hi Team,

i having a few issue for full screen mode. My children are deleting many game also hide some game. 
kindly request a Parental Controls for the full screen mode for extension example:
-disable Shutdown
-disable Hibernate 
-disable delete game
-disable hide game

i also can suggest provide a pin code for host to avoid other user and children to sabotage the game.
guest can only play game and not allow to remove game or re adjust the setting in full screen mode only.

Kindly provide a update for this extension. 
Thank you .

**Comment by darklinkpower** [comment]
Duplicade of https://github.com/JosefNemec/Playnite/issues/1497
