### ISSUE TITLE
Nest Games With Multiplayer

### ISSUE THREAD

**Issue by guyinabush** [JosefNemec/Playnite#285]
For example:

I have Call of Duty: Modern Warfare 3 on Steam. It has several standalone launchers.

The core game and then Multiplayer.

The core game picks up the Steam Store Page information. But the multiplayer version does not. Since there is no Steam Store Page and IGDB does not have an independent page either.

I would like to see the game "nested" or at the very least duplicate the information from the Store Page of the core game into the standalone launchers.

Hope all of that makes sense.

Thanks for a great application!

Brian Dunaway

**Comment by JosefNemec** [comment]
You can do that manually by copying `Play action` settings from multiplayer version and adding then into `Other Actions` list in single player version. And then hiding multiplayer version of the game.

**Comment by berserkwarwolf** [comment]
How about a "merge" function for this ? if you select 2 games and click on "merge" it copies the play action over to the other game into Other Actions automatically ?

**Comment by JosefNemec** [comment]
Technically the same as #408, I'm going to close this since it will be implemented as part of that issue.
