### ISSUE TITLE
Cant authenticate my itch.io account.

### ISSUE THREAD

**Issue by RichardSmid** [JosefNemec/Playnite#2850]
### Bug Description

I have installed the itch.io addon, but can't authenticate because the addon tells me that I need version 2.5. I have tried reinstalling the addon, which didn't help.

### Diagnostics ID

68019da9-1e31-4d6a-907d-d0e04eed8593

### Screenshots

![image](https://user-images.githubusercontent.com/32524000/159153470-d18c224c-b5f4-419c-bc2e-8cc64b6fc5ca.png)

**Comment by JosefNemec** [comment]
Re-install itch.io client.

**Comment by RichardSmid** [comment]
Vsechno uz funguje spravne.
Diky moc.
