### ISSUE TITLE
Add physical games with code bar

### ISSUE THREAD

**Issue by YannD-Deltagon** [JosefNemec/Playnite#2855]
### Feature description

I use the [MyGamesCollection](https://play.google.com/store/apps/details?id=com.tuyware.mygamecollection&hl=fr&gl=US) app on android for my Physical old games (NES for example)
This app is cool, because, I have just to scan the code bar and verif

Any idea for import, or connect playnite with this app ?

Or, a android app "Playnite" :3

**Comment by darklinkpower** [comment]
In my opinion this sounds like a very niche/specific feature that would make more sense if someone made it as a separate extension and not as a built-in feature

For the second, there's already an open issue https://github.com/JosefNemec/Playnite/issues/323 and closed https://github.com/JosefNemec/Playnite/issues/247

**Comment by joyrider3774** [comment]
also you can export to csv in mygamescollection and then create a simple extension to import the games in playnite from that csv i know because i did that at one point but i don't think i still have the code need to look it up

**Comment by Jeshibu** [comment]
https://github.com/Jeshibu/PlayniteExtensions/releases/tag/barnite0.1

**Comment by JosefNemec** [comment]
Closing since Jeshibu's extension supports this.
