### ISSUE TITLE
Option to change and prioritize metadata search parameter

### ISSUE THREAD

**Issue by Bolthier** [JosefNemec/Playnite#2858]
### Feature description

Right now there seem to be two different behaviors even while using the same IGDB metadata addon.
1. While using the bulk editor "Library" > "Download Metadata" the application searches for the Source Name.
2. Using the "Edit" function directly for a game uses the Display Name of the game.

It would be great to have an option to change and prioritize the search parameter when downloading metadata. Both while editing a single game and bulk editing.

For example (sorted by my personal priority):

- IGDB ID
- Game ID (Source Game ID)
- Original Name
- Name (Display Name)
- Source Name

If a parameter is absent or not supported by the metadata addon it would use the next one.

IGDB ID
https://github.com/JosefNemec/Playnite/issues/595

Additional name fields (Original Name and Source Name)
https://github.com/JosefNemec/Playnite/issues/2814

### Screenshots

Screenshot
Bulk editing of metadata
![image](https://user-images.githubusercontent.com/42382626/159909844-5a01f75c-8823-4688-8a37-0de12be5a550.png)

Directly editing of metadata
![image](https://user-images.githubusercontent.com/42382626/159910070-973845cb-7519-4573-b352-0b9d761f7011.png)

**Comment by JosefNemec** [comment]
Playnite doesn't control this at all, it just tells specific metadata plugin: "give me metadata for this game" and then it's up to that plugin how it does it (and what fields it's using to match game records). So those changes you propose need to be made in [IGDB plugin](https://github.com/JosefNemec/PlayniteExtensions) (or in other metadata plugins you might be using).

**Comment by Bolthier** [comment]
Will do. Created the issue in the git for PlayniteExtensions.
https://github.com/JosefNemec/PlayniteExtensions/issues/157
