### ISSUE TITLE
Inconsistency between {InstallDir} and {InstallDirName}

### ISSUE THREAD

**Issue by the-conceptionist** [JosefNemec/Playnite#2860]
### Bug Description

When employing the use of {InstallDirName}, it returns with the name of the parent folder of the install directory. For example, if I were to have a game folder at `C:\Games\Game1`, {InstallDirName} would return with `Games`. However, when using {InstallDir}, it returns as `C:\Games\Game1`. Ideally, {InstallDirName} would return with `Game1` in this scenario.

### To Reproduce

1. Set a game's install directory.
2. For the game's start-up script, input `[System.Windows.Forms.Messagebox]::Show("{InstallDirName}")`
3. Launch the game and observe the output.
4. For the game's start-up script, replace `{InstallDirName}` with `{InstallDir}`.
5. Repeat step 3.

### Diagnostics ID

147fb84d-9bfd-4073-8a42-7cd1caefcafb

**Comment by JosefNemec** [comment]
Fixed in devel, temporary workaround is to end the part with `\`.
