### ISSUE TITLE
Window game background image is displayed when no game is selected or when it shouldn't on Grid View

### ISSUE THREAD

**Issue by darklinkpower** [JosefNemec/Playnite#2862]
### Bug Description

Window game background image is displayed when no game is selected or when it shouldn't on Grid View

### To Reproduce

It triggers by changing views, selecting game(s) and switching views back and forth and it can also cause to display the image on grid view even if it's disabled

It should be noted that it doesn't always happen for me. It sometimes starts happening and doesn't go away even on safe mode but then it can go away for no apparent reason randomly.

### Diagnostics ID

a9913195-7227-40f7-be19-99817f236d04

### Screenshots

https://user-images.githubusercontent.com/1389286/160286369-bcbbf060-3158-49e9-9bbf-94bfb5474118.mp4

Here the window game background image is disabled but the image still keeps being displayed:

https://user-images.githubusercontent.com/1389286/160286521-135ab0c0-19f9-42f1-8eb8-d6deeb585ad9.mp4

**Comment by JosefNemec** [comment]
Most likely fixed already by 2e911e99c7fed4f88b9ddd92b7b0087f30e44ead

**Comment by darklinkpower** [comment]
Can confirm that commit fixes this issue.
