### ISSUE TITLE
Can't create desktop shortcuts from Playnite

### ISSUE THREAD

**Issue by AgentSilentCat** [JosefNemec/Playnite#2864]
### Bug Description

Quite simply when I do the right click and click "Create desktop shortcut" nothing happens, whether I mass select the games, or select only one, it does not create the shortcut.

### Diagnostics ID

6adfcd61-fb70-43fb-9344-f5f454f9b45c

**Comment by JosefNemec** [comment]
There is no error in logs about shortcut creation so I have no idea what's happening. I can't reproduce it myself.

**Comment by JosefNemec** [comment]
Is this still reproducible with the latest version? If so, please generate new diagnostics package with that version, thank you.
