### ISSUE TITLE
Team Fortress 2 not showing up

### ISSUE THREAD

**Issue by Johnapolitan** [JosefNemec/Playnite#2865]
### Bug Description

Pretty much after installing and trying to update my game library, TF2 is still not showing up. Though it's not installed, every other game from my Steam library is there (no steam on my PC right now). 

### Diagnostics ID

c7ebd08a-ff70-4ed5-acae-dccb3f57a894

**Comment by darklinkpower** [comment]
Wrong repository, as indicated in text in the issue template it should go in https://github.com/JosefNemec/PlayniteExtensions

**Comment by JosefNemec** [comment]
1) Wrong repository
2) Enable "import generic free items" in Steam's integration settings
