### ISSUE TITLE
[Enhancement][Library Import] - Improved Library Import speed

### ISSUE THREAD

**Issue by fromage9747** [JosefNemec/Playnite#2866]
### Feature description

I have discovered Playnite and really like it when compared to other launchers available.

My one and only pain point is the Library import for Xbox360 iso imports as this is what I am using.

I have to leave my PC on overnight in order for it to go through 100 folders with a single iso in each one and its driving me nuts. 

My proposal is to first find out what on earth is causing it to take so long.  It should not take long to just scan the name of the folder, match it to IGDB and create the entry.  This should be done in a matter of seconds. If it can't match it, just create the entry in the Playnite DB and let the user manually find it with IGDB.

As you have to set the Emulator to scan with, is PlayNite trying to scan the entire iso using Xenia in order to obtain detail about the game?  If this is the case, it is not needed.  If the name does not match a title in IGDB, drop the scan and import the name.  It just needs the Attribute of the applicable emulator, which in this case is Xbox 360. 

Please please please can this get looked into?  I am not a .net, C++ or C# dev but as a Software Enginner I was looking at the code and I am sure I could figure it out myself.

It would also be great if there could be a prgress bar letting the user know how many titles left to scan.  Though if it can do all of this in seconds, the progress bar isn't really needed but just a cool UX feature.

**Comment by JosefNemec** [comment]
This is because Playnite reads checksum for these files to try to better identify what games they are. You can disable this in scanner's configuration by specifying what files should be excluded from checksum scan. The speed is affected by your CPU and IO (disk drive) speed.

**Comment by fromage9747** [comment]
@JosefNemec Hallelujah! Thank you.
