### ISSUE TITLE
Binding to settings property in ViewSettings not working in custom theme

### ISSUE THREAD

**Issue by darklinkpower** [JosefNemec/Playnite#2867]
### Bug Description

Binding in a DataTrigger in custom theme to settings property in ViewSettings not working.

Notifying the property change for the view settings like this does not fix it. The setter is not called when switching views

![image](https://user-images.githubusercontent.com/1389286/161086764-7db087e9-bde2-45e9-a182-3a9a8374ccf7.png)

### To Reproduce

Bind to a property in a control with a data trigger, either via int or enum as a string

```xml
<Style.Triggers>
    <DataTrigger Binding="{Settings ViewSettings.GamesViewType}" Value="1">
        <Setter Property="Background" Value="Green" />
    </DataTrigger>
    <DataTrigger Binding="{Settings ViewSettings.GamesViewType}" Value="Details">
        <Setter Property="Background" Value="Yellow" />
    </DataTrigger>
    <Trigger Property="IsMouseOver" Value="True">
        <Setter Property="Background" Value="Blue" />
    </Trigger>
</Style.Triggers>
```

Also can be reproducible with the Stardust theme, which includes a binding that is currently not working https://github.com/darklinkpower/Stardust/blob/master/source/DerivedStyles/WindowBarButton.xaml#L141-L143

### Diagnostics ID

Not applicable

### Screenshots

I think the issue is caused due to the ViewSettings not notifying of changes. Adding `OnPropertyChanged()` does not fix it because the setter is never called for some reason even on startup

https://user-images.githubusercontent.com/1389286/161089140-ab0002a2-76d7-43dc-aa7b-71005a241c45.mp4

**Comment by JosefNemec** [comment]
Closing after discussion on Discord, it's not an issue in Playnite.
