### ISSUE TITLE
Itch.io Library Plugin unsets installed status on manually configured entries

### ISSUE THREAD

**Issue by Mellified** [JosefNemec/Playnite#2869]
### Bug Description

Itch.io games create a somewhat unique problem in Playnite. It's possible to have free and purchased games from Itch which cannot be installed via the Itch client. These are larger games, which are hosted on third party sites. When manually installing these games the Playnite user has a couple of choices:
1. Add the game as a separate entry in Playnite. This means manually entering all the metadata, finding images, and tracking where the game was originally obtained.
2. Configure the existing Itch.io Playnite game entry manually to point to the installed game. This is accomplished by unchecking "Include library integration play actions" and setting the installation folder and marking the game as installed.

Many games on Itch only exist on Itch. Itch can't be referenced as a metadata source for games which didn't originate in Itch. There's little or no metadata available from Playnite's other sources. So using the Itch.io entry is the only automated way to get metadata for these games. As a result #2 is the preferred option for Itch.

Unfortunately when Playnite scans the Itch library it deletes the "installation directory" and marks these manually configured games as "not installed". _I believe this is a bug - not a feature - because it ignores the user's expressed intent to have the game installed._ It's probably not worth having Playnite track whether a plugin or the user marked a game as installed. Instead I propose that any game with manually defined Play actions have its installed state ignored by the library plugin.

### To Reproduce

1. Add a free game from Itch which requires downloading from a third party site to a collection.
2. Enable "Import free games from collections" setting in the Itch library plugin settings.
3. Select "Update Game Library -> Itch" to trigger Playnite to add the Itch game to Playnite.
4. Configure a play action and mark the game as installed.
5. Select "Update Game Library -> Itch" to trigger Playnite to add the Itch game to Playnite.
6. Observe the game is no longer installed.

### Diagnostics ID

N/A

**Comment by darklinkpower** [comment]
Incorrect repository. As indicated in the issue template text, this repository is not for addons

**Comment by JosefNemec** [comment]
Not an issue in Playnite, this is completely handled by itch integration plugin. In fact, installation status for all games imported by  plugins is handled by those plugins, Playnite doesn't control it.

**Comment by Mellified** [comment]
The forum post [here](https://playnite.link/forum/thread-42-post-89.html#pid89) points to a non-existent repository for the Itch.io library plugin. It also says that issues should be filed here.

Make up your mind.

**Comment by JosefNemec** [comment]
That forum post is obsolete (from before we separated integrations into external plugins), instructions in current issue template are up to date.
