### ISSUE TITLE
Media Action Type

### ISSUE THREAD

**Issue by By6r9** [JosefNemec/Playnite#287]
If user want link external manual or video to the game, there should be a predefined action type in selector - Media, Manual, Video, etc.

**Comment by JosefNemec** [comment]
How is this different to current solution where you can add either a new game link or custom action targeting URL?

**Comment by By6r9** [comment]
Just different label so user after clicking "type" knows that he can add media to actions. Renaming "URL" to "URL/Media files" could be another solution.

**Comment by ArtexJay** [comment]
May i ask what would the use for this in a game library? I find this feature to sound useless. I might not be understanding something lol

**Comment by By6r9** [comment]
For manuals, passwords, solutions, maps, etc. Good thing for more complex games.

![mediaaction](https://user-images.githubusercontent.com/32620314/33766134-6c1699d4-dc1c-11e7-9fb3-8ab3ced0b7bf.png)

**Comment by JosefNemec** [comment]
I think this is the same as #287, at least in regards to manuals, videos etc. Please correct me if I'm wrong about this.

**Comment by JosefNemec** [comment]
I'm stupid, I meant #286 not #287.
