### ISSUE TITLE
Game's Name an Disc ID Number's

### ISSUE THREAD

**Issue by Swat842** [JosefNemec/Playnite#2870]
### Feature description

I have notice the following game's isn't in it's own area at all an I had to manually had to add them to the right area so it wasn't by it's self or in the wrong area an the games is label as the Disc number an names but yet it keep's having them apart from the games name an ID the Legend of Dragoon, The (USA) is in it's own game folder an shows up as 1 now the Legend of Dragoon, The (Japan) doesn't show up as 1 nor dose Metal Gear Solid & Lunar - Silver Star Story Complete.

### Screenshots

Legend of Dragoon, The (Japan)
![image](https://user-images.githubusercontent.com/59518236/161401514-0d68a1ad-1414-468b-be42-e126813bfc7b.png)

Lunar - Silver Star Story Complete
![image](https://user-images.githubusercontent.com/59518236/161401560-d4238c4a-2f48-4bbb-96b8-e9a2b193ffd7.png)

Metal Gear Solid
![image](https://user-images.githubusercontent.com/59518236/161401606-c68cf2f3-9749-4727-8db5-c02da1bb97dd.png)

**Comment by JosefNemec** [comment]
Fixed in devel by ebef61373558d6a790113508262cce4a206b2059
