### ISSUE TITLE
PCSX2 nightly and dev support

### ISSUE THREAD

**Issue by tbmny** [JosefNemec/Playnite#2871]
### Feature description

Currently, playnite only recognizes **pcsx2.exe** as a valid executable for pcsx2. However, the nightly and dev builds don't use that filename. Aside from **pcsx2.exe**, other potential filenames include **pcsx2x64-avx2.exe**, **pcsx2x64-avx2.exe**, and **pcsx2-qtx64-avx2.exe**.

In addition, the launch arguments don't work on the Qt dev build (https://github.com/PCSX2/pcsx2/suites/5767252367/artifacts/191914197)

**Comment by JosefNemec** [comment]
Added in master.
