### ISSUE TITLE
Open Fullscreen mode with ps/guide button on controller

### ISSUE THREAD

**Issue by fewdji** [JosefNemec/Playnite#2876]
### Feature description

Is there way to open Playnite Fullscreen mode by pressing ps or guide button on gamepad (like in Steam it opens Big Picture Mode)? It would be very nice for TV gaming.

**Comment by JosefNemec** [comment]
From what state?

**Comment by fewdji** [comment]
When Playnite is running. Even when minimized. Just like Steam Big picture. It’s very useful when you can turn on pc and then just press ps/guide button to enter full screen mode and launch a game without touching mouse/keyboard.

**Comment by JosefNemec** [comment]
Already done in devel for Playnite 10: b0250bd7645428db03c7463b6a283f3136bbd135

**Comment by fewdji** [comment]
> Already done in devel for Playnite 10: [b0250bd](https://github.com/JosefNemec/Playnite/commit/b0250bd7645428db03c7463b6a283f3136bbd135)

Thank you! When it will be released?
