### ISSUE TITLE
BACKUP AND RESTORE SAVE DATA FILES

### ISSUE THREAD

**Issue by CRAWLER-V** [JosefNemec/Playnite#2877]
### Feature description

Hello, a cute thing you can add in this project is a function to BACKUP all the save game files.
The function have to find all the path and then backup all the save data with proper folders.
The backup function of course must have a restore function, for exaple, if i need to format my PC, this 2 functions make my "post-format" life very very very very better.

**Comment by darklinkpower** [comment]
Duplicate https://github.com/JosefNemec/Playnite/issues/124

Please read the instructions carefully, it mentions that you should search existing issues to make sure it's not a duplicate. Also don't use all caps for the title.

**Comment by darklinkpower** [comment]
There are also available extensions that do this https://playnite.link/addons.html#mtkennerly.ludusavi

**Comment by CRAWLER-V** [comment]
Super very thanks. Sorry for duplicate.
