### ISSUE TITLE
Platform Actions

### ISSUE THREAD

**Issue by By6r9** [JosefNemec/Playnite#288]
Ability to define actions for all items in defined platform, also for those imported after creating that action. 
Example: second emulator/profile in game context menu - now you must create new action for every game.

**Comment by JosefNemec** [comment]
Why would you have multiple emulator profiles assigned to a game? I don't see why would you run the same game with different profiles.

**Comment by ArtexJay** [comment]
I also find this idea not very useful, what would be the point of using different emulators for the same game.

**Comment by By6r9** [comment]
Some emulators have stable and nightly version. There is also sometimes RetroArch port. LaunchBox has a 'Launch with' auto-populated context menu with associated emulators.  
![3dscitra](https://user-images.githubusercontent.com/32620314/33766762-3f3659ba-dc1f-11e7-86e4-2712c7202602.png)

**Comment by JosefNemec** [comment]
Adding menu like shouldn't be a problem, we could list all emulators/profiles based on game's platform.

**Comment by JosefNemec** [comment]
Is this still valid for 3.0 where you can for example create "stable" and "nightly" emulator profiles and assign those on game to game basis? I personally don't know where you would use the feature on screenshot by 
@By6r9  (starting game each time with different emulator/profile).

**Comment by By6r9** [comment]
I think it is still valid request because:
a) you can't select 50 games and add action for all of them at once. 
b) adding new games means finding new entries and repeating assigning profiles, when platform-wide profiles are already created.

Reasons for using more than emulator: different versions, emulators with different features.

**Comment by JosefNemec** [comment]
> Reasons for using more than emulator: different versions, emulators with different features.

Well that doesn't answer my question, do you realistically run one with different emulators? I'm mean why would you run the game one day with Retroarch and another day with ePSXe? Wouldn't you just try what's the best one for that specific game and stick with it?

**Comment by By6r9** [comment]
Yes, I have 2-3 emulators per platform because they have different feature sets, WIMP/Big Box GUIs, etc. 
Sometimes I don't know which of them is the best one before I try them. For PSX, I have standalone mednafen, and 2 forks of it in Retroarch, and another fork of PCSX. Each of those forks has some quirks.

**Comment by By6r9** [comment]
Example from Metropolis Launcher:
https://metropolis-launcher.net/img/screenshots/06_Main-Context_Menu.png

**Comment by JosefNemec** [comment]
I'm closing this since it probably won't be compatible with planned emulation changes in #653. Support for similar functionality will be considered when implementing #653.
