### ISSUE TITLE
Playnite crashes when closing progress dialog manually

### ISSUE THREAD

**Issue by darklinkpower** [JosefNemec/Playnite#2883]
### Bug Description

Closing a Playnite api progress dialog manually with `Alt+F4 ` or with Right Click -> Close crashes Playnite

### To Reproduce

Close a progress dialog message with `Alt+F4 ` or with Right Click -> Close. It can be reproduced with the metadata download progress dialog but can also be reproduced with a progress dialog created with an extension.

`Dialogresult can only be set after having created Window and once shown as dialog box`

Error points points to this https://github.com/JosefNemec/Playnite/blob/87a8dfff816ebc528e0a99e11667db259f0ddbac/source/Playnite/Windows/WindowFactory.cs#L140-L150

### Diagnostics ID

230d4dce-e671-4ab7-bf8a-3386cb796cf3

### Screenshots

![image](https://user-images.githubusercontent.com/1389286/162353639-de98b548-c217-4088-ac44-d5c04c13bf54.png)

![image](https://user-images.githubusercontent.com/1389286/162353860-66396672-31bf-4116-9c67-4fdd69ff96cd.png)

**Comment by JosefNemec** [comment]
omg, if this is the reason for those dialog result crashes that's been happening for past 2 years...

**Comment by JosefNemec** [comment]
Fixed in master.
