### ISSUE TITLE
Tooltip for "Steam Friends" is generic

### ISSUE THREAD

**Issue by OLLI-S** [JosefNemec/Playnite#2889]
### Bug Description

The tooltip text (mouse-over) at the "Steam Friends" show a generic text.
See screen shot.

### Diagnostics ID

a309bf8c-2472-4d51-9f6e-57078c92c47d

### Screenshots

![image](https://user-images.githubusercontent.com/8037790/163649142-18499453-b40f-4bd0-880f-94fd3376858f.png)

**Comment by darklinkpower** [comment]
Hello, please read the instructions in the issue template more carefully in the future since it mentions that issues with extensions don't belong in this repository

![image](https://user-images.githubusercontent.com/1389286/163657244-1c839ac7-e9e7-4c66-b264-8a36f476556e.png)

**Comment by OLLI-S** [comment]
I have tread the text above, but I did not know, that this issue belongs to the extension....
Sorry.

**Comment by JosefNemec** [comment]
Already fixed in devel version of Steam plugin, will be out with next plugin update.
