### ISSUE TITLE
Exit game using a universal command

### ISSUE THREAD

**Issue by madieboyd** [JosefNemec/Playnite#289]
Wondering if somehow we would be able to bind a key to say a controller to exit out of a game/program

**Comment by JosefNemec** [comment]
I'm not sure what the use case for this is. Don't basically all games have menu with `Quit` option?

**Comment by madieboyd** [comment]
I was more thinking for emulators and the like that don't always have an easy way to map an exit key to a controller

**Comment by ArtexJay** [comment]
you can force quit any application/game with the combination of alt+f4

**Comment by madieboyd** [comment]
Yeah but id like to be able to close out of an emulator using my controller. Snes9x for example only accepts single buttons as the key for exiting a game. Ideally, id like to not even connect a keyboard/mouse to my emulator computer and just navigate playnite like a frontend

**Comment by JosefNemec** [comment]
Can't you use something like [keysticks](http://keysticks.net/site/) to map Alt-F4 globally to some button combination?

We could alternatively implement some action mapping system, but it's not an easy task.

**Comment by Evene174** [comment]
@JosefNemec 
To be honest, Josef, I think this is too complicated and unnecessary to implement.
All that the topic starter wants may easily done with the help of any third-party controller application that allows bind any combination of keys  to any button of the controller (For example, ControllerCompanion / Xpadder etc.)
I think implementing only one of all the functions of these applications will still not be enough, but developing an analog of such powerful programs is not included in your plans.

**Comment by madieboyd** [comment]
Those applications seem fine if I was using a PlayStation or Xbox controller, but I'm using a SNES controller to navigate and play everything. I don't believe it uses Xinput to control games and whatnot. If it is too difficult and not worth the time to do so, that's fine as it is an almost non-existent issue for most of your userbase.

**Comment by JosefNemec** [comment]
Well if it's not XInput then we can close this for sure because I'm not planning to add support for other input devices (it's not reasonable with limited resources Playnite development has and XInput is basically industry standard right now).

**Comment by JosefNemec** [comment]
I'm closing this since it's IMHO out of scope for Playnite. Plus there are 3rd party solution that could provide this functionality.
