### ISSUE TITLE
Statistics shows hidden games

### ISSUE THREAD

**Issue by Gerren** [JosefNemec/Playnite#2890]
### Bug Description

The statistics show hidden games by default. This should be optional at best.

### To Reproduce

Hide a game that has time played > 0. My top played "game" is SteamVR, which I have hidden.

### Diagnostics ID

9afccb2c-3f83-4a74-a5b5-8e8a35e95dc4

### Screenshots

![StatisticsHiddenGameDetail](https://user-images.githubusercontent.com/2953438/163810708-0616d02c-67ef-4519-ac64-e1b8ce9d4654.png)
![StatisticsHiddenGame](https://user-images.githubusercontent.com/2953438/163810712-5c7a670d-c839-41b7-b113-0647b9d4bd83.png)

**Comment by JosefNemec** [comment]
Done in devel. There's now an option to choose whether to include hidden games or not.

**Comment by Gerren** [comment]
Thanks!
V.
