### ISSUE TITLE
Custom Install Actions

### ISSUE THREAD

**Issue by Foroneus** [JosefNemec/Playnite#2893]
### Feature description

There should be a functionality to install games using local files through Playnite through the Install button; it could be at the bottom of the Installation section.

**Comment by Jeshibu** [comment]
Have a look at the "Install Button" extension

**Comment by JosefNemec** [comment]
Duplicate

**Comment by Foroneus** [comment]
> Have a look at the "Install Button" extension
I've seen it, and it does almost entirely what I asked for but at this time it uses a near-workaround by loading the installation executable as a ROM. But I'll probably go with that for now,
