### ISSUE TITLE
update extension tutorial URL

### ISSUE THREAD

**Issue by attemarkula** [JosefNemec/Playnite#2894]
### Bug Description

Steps to reproduce:
Open Playnite
Click main menu
Library
Configure interactions
Create new extension

Expected result:

- Open webpage to extension tutorial

Actual result: 

- Open webpage to 404 error page

Old URL:
https://playnite.link/docs/tutorials/intro.html was removed

My guess of new URL:
https://playnite.link/docs/tutorials/extensions/intro.html

### To Reproduce

Steps to reproduce:
Open Playnite
Click main menu
Library
Configure interactions
Create new extension

### Diagnostics ID

not needed

**Comment by JosefNemec** [comment]
There's no "Create new extension" link in Configure Integrations window. Please attach screenshot of what link you are talking about.

**Comment by attemarkula** [comment]
Correct on 9.x.
Note: Just noticed I was using ancient version 8.14.
I assume 8.x is not supported anymore, so no bug here. I'll upgrade later to 9.x when I have more time.

Sorry for the trouble.
