### ISSUE TITLE
Unrecoverable Error While Adding Game

### ISSUE THREAD

**Issue by ThyMrMan** [JosefNemec/Playnite#2895]
### Bug Description

Diagnostics ID: b130cc61-517c-4c57-ba93-0047286493c1

While attempting to add a game to Playnite, it suffers and unrecoverable error and crashes. Happens in safe mode as well. 
Happens with both Manual and Scan Automatically.

### Diagnostics ID

b130cc61-517c-4c57-ba93-0047286493c1

### Screenshots

<a href="https://imgur.com/rpw4zvU"><img src="https://i.imgur.com/rpw4zvU.png" title="source: imgur.com" /></a>
<a href="https://imgur.com/PsdMwu8"><img src="https://i.imgur.com/PsdMwu8.png" title="source: imgur.com" /></a>

**Comment by JosefNemec** [comment]
Your library files are damaged somehow, please attach `%AppData%\Playnite\games\games.db` file, I'll try to fix it.

**Comment by ThyMrMan** [comment]
Attached what I think is the correct file,

[games.zip](https://github.com/JosefNemec/Playnite/files/8540566/games.zip)

**Comment by JosefNemec** [comment]
Here's fixed file: [gamesfixed.zip](https://github.com/JosefNemec/Playnite/files/8541319/gamesfixed.zip)

**Comment by ThyMrMan** [comment]
That worked, Thanks. Any idea what would have caused the issue so I can avoid it in the future?

**Comment by JosefNemec** [comment]
No idea I'm afraid. This usually happens if you force close Playnite process while it's updating game library files.

We already have automatic recovery for some corruptions so I'll just cover this specific case as well if possible.

**Comment by ThyMrMan** [comment]
Well thanks for your help.
