### ISSUE TITLE
Playnite Fullscreen responds to controller input when game has focus

### ISSUE THREAD

**Issue by bverkron** [JosefNemec/Playnite#2897]
### Bug Description

When playing a game Playnite Full screen will continue to respond to controller input in the background. You can hear the navigation sounds of the Playnite grid in the background while navigating the game menus. Pressing buttons can continue to do things like open game info and potentially even launch games in the background. I typically just close Playnite to prevent that from happening.

In the clip you can hear Playnite grid being navigated even before the menu comes up. I alt-tab'd to another app and back again to try and force focus to the game but the issue continued and you can still hear Playnite grid navigating when in the game menu.

This does not always seem to happen in all games or all situations. I wonder if it might be due to games running in a windows or borderless mode vs true full screen mode but I have not tested that yet. In the case show here the game (God of War 2016) is running in borderless mode and there seems to be no full screen option for this game. In this case I launched the game manually from Steam. I don't recall if this happens when the game is launched from Playnite directly or not.

https://user-images.githubusercontent.com/19174503/164991182-9382e76e-d4db-4675-973f-52c045571e04.mp4

**Edit**: Video playback is being weird for me on github, missing the first portion, etc and it seems to have no audio.
Try this instead: https://vimeo.com/702608522

### To Reproduce

Steps to _possibly_ recreate it.

1. Launch Playnite full screen
2. Connect controller
3. Launch a game manually from Steam
4. Navigate around the game with the controller

Cannot guarantee this will reproduce the issue. Will try some other tests to narrow down the conditions.

### Diagnostics ID

950258fe-3cdc-4f44-ad0a-f677ad273442

**Comment by bverkron** [comment]
I'm having a hard time reproducing this intentionally. I have even tried things like starting the game manually via Steam and navigating back to Playnite full screen and moving around the grid with the controller while the game is launching. As soon as the game loading screen appears the focus shifts back to the game and I no longer hear the grid navigation sounds. I'm not even sure how Windows allows two programs to have focus from the controller at the same time.

**Comment by JosefNemec** [comment]
It means that something is setting focus to Playnite's window or not taking it back when you launch a game. Nothing we can do about it I'm afraid, it works correctly from Playnite's point of view. If Windows or something else sets Playnite's window as active/focused, Playnite will process controller inputs.

I tried to reproduce it multiple times but I couldn't (not with God of War since I don't own that game).

**Comment by bverkron** [comment]
Fair enough. I suppose if it were a widespread issue something could be done to ignore input if the launched game is the active window and return focus to Playnite once the game closes. Similar to the "When game starts: Minimize/Close" and "When game closes: Restore window" functionality. But of course, as you point out, this is not a Playnite issue and this seems like an edge case.

Thanks for the response. Closing.

**Comment by JosefNemec** [comment]
If you find a way how to reliably reproduce it, let me know, I'll look into more.

**Comment by SquiIIiam** [comment]
I know this is closed but FWIW this has been happening pretty often for me, but I'm also not sure how to consistently reproduce it. I've recently noticed it with Red Dead Redemption 2, which opens the Rockstar Launcher before the game starts, and with Crimson Desert, which has a startup splash screen and sometimes has some funky window focusing behavior
