### ISSUE TITLE
EA Play Games - Client Opens, Games Don't Launch

### ISSUE THREAD

**Issue by shangles** [JosefNemec/Playnite#2898]
### Bug Description

I have both the Origin Client installed as well as the EA Play beta client installed.  One game I have that's in EA Play but not Origin is Super Mega Baseball 3 (as it's part of the EA Play free subscription I have)  When I try to launch this game in Playnite, the EA Play client launches but the game itself never starts.  I can repeat this with other games as well (Madden NFL 2022)

A secondary question is:  Can I specify in Playnite which client a game should launch and open with?  ie:  Can I configure Madden NFL 2022 or Battlefield 2042, etc. to open with Origin and not EA Play?

### To Reproduce

Have both Origin and EA Play clients installed.  Launch the game from Playnite.

### Diagnostics ID

59864474-966f-4cac-a4f1-d03b66763ebf

**Comment by JosefNemec** [comment]
Wrong repository, please read issue template.

**Comment by JosefNemec** [comment]
Also forgot to mentioned that it's an issue with EA Desktop client, nothing we can do about it. It's still not finished and buggy.

**Comment by shangles** [comment]
I found some other info about it (and a workaround) in the other template for extension support.  Sorry to be a pest.
