### ISSUE TITLE
Norton 360 Data Protector warns from Playnite 9.17 updater.exe due to tried access of an protected PNF-File

### ISSUE THREAD

**Issue by Crwmy** [JosefNemec/Playnite#2900]
### Bug Description

While updating to 9.17, Norton 360's Data Protector component has logged a warning Playnite's Updater in %localappdata%\Temp\Playnite\update.exe because it tried to access an protected PNF-File (that is in my case related to the AMD Radeon Driver) in %SYSTEMROOT%\INF.  

First time this warning is logged in connection with Playnite. 

As far as I can tell, Playnite has updated without issues, only the access to the PNF has been blocked. As far as I can tell, this is no problem, but might lead some people think it's malicious.

I just wanted to let you know as I haven't found anything here or in the forum mentioning it :) 

### Diagnostics ID

not needed

**Comment by JosefNemec** [comment]
This has been an issue in the past with some other AVs as well, nothing I can do about it. I'm honestly tired dealing with it. It's issue with these crappy anti-malware apps and their heuristic detection...

Updater is completely safe, there's nothing wrong with it.
