### ISSUE TITLE
Playnite seems connecting to playnite.link via http instead of https

### ISSUE THREAD

**Issue by Crwmy** [JosefNemec/Playnite#2901]
### Bug Description

While scrolling through playnite.log, I noticed that all connections to playnite.link from the Playnite App are over http and not https. As all other connections seem to have https, I thought this might be unintended, especially since the App-Update Executables are downloaded from there too. 

Or is there an automatic upgrade/redirect to https after the initial contact and it is just not logged correctly?

### Diagnostics ID

fd0042d1-6196-4ef5-9593-0778446d71d0

### Screenshots

![Screenshot 2022-04-25 082429](https://user-images.githubusercontent.com/91319158/165032026-96516b13-acd7-4be9-999b-ae4d59329d66.png)

**Comment by JosefNemec** [comment]
I have no idea why you are getting http requests for update manifest and changelog, those should be accessed via https because base URLs are set to use https (and they actually are using https in my Playnite install). Can you please attach your `Common.config` file from Playnite's installation folder?

The only place that doesn't use https is the actual updater file URL, I'll fix that on the backend.

**Comment by JosefNemec** [comment]
Also attach diagnostics id that was requested in issue template.

**Comment by Crwmy** [comment]
Yes, sorry. ID: fd0042d1-6196-4ef5-9593-0778446d71d0

Common.config has http. 
Created: August 1, 2021
Modified: October 15, 2021

I did not make any changes. 

[Issue2901_CommonConfig.zip](https://github.com/JosefNemec/Playnite/files/8552858/Issue2901_CommonConfig.zip)

**Comment by JosefNemec** [comment]
That's definitely wrong, but I have no idea how it could have happened. Switch to https was done in 9.6 update, which should have updated that file. I'll look into it.

[Here's correct config file](https://github.com/JosefNemec/Playnite/files/8552984/Common.zip)

**Comment by Crwmy** [comment]
Thanks!

Works. Just as confirmation, just in case there could have been more places to look into, if it would not have worked.

![image](https://user-images.githubusercontent.com/91319158/165056411-1b94c0a5-032a-4aae-ada6-b2b4a6e90fa0.png)

Sadly, I have no clue either why it didn't update on my end.

Don't know if you can and/or have the capacity, but monitoring http requests from Playnite >= 9.6 could be a way to see if it's widespread or not and just something on my end went wrong and it is a individual, localized incident.

**Comment by JosefNemec** [comment]
Server itself redirects everything to https so it's not a big issues, but I will try to figure out how this happened.

**Comment by JosefNemec** [comment]
No idea how the original issue happened, all base URIs use https in current version so closing.
