### ISSUE TITLE
Add an option to hide “All” and “None” in the menu.

### ISSUE THREAD

**Issue by NiceGlassesDude** [JosefNemec/Playnite#2902]
### Feature description

This is very inconvenient, especially if you want to select only a certain grouping for the start.

The least I want is to mix up and see all my groupings altogether.

Please add an option to get rid of them.

### Screenshots

![image](https://user-images.githubusercontent.com/19506405/165250859-b47d369e-c4b5-4e98-9222-c6ded3e4e011.png)

**Comment by JosefNemec** [comment]
Duplicate #2124
