### ISSUE TITLE
Statistics page: Strings "Not played" and "Played" are displayed untranslated

### ISSUE THREAD

**Issue by RiseT** [JosefNemec/Playnite#2904]
### Bug Description

The two strings "Not played" and "Played" on Playnite's Statistics page are getting displayed untranslated. I've tried this in several languages and this is true for all of them (this is a long-standing issue btw).

### To Reproduce

1. Choose some language other than English
2. Open Statistics page

### Diagnostics ID

c98e3e99-2805-4fda-9ca1-1b88c7b47b43

### Screenshots

![playnite](https://user-images.githubusercontent.com/12624674/165291840-2311402c-6a63-46cc-ac36-c3f215332f88.PNG)

**Comment by JosefNemec** [comment]
Completion statuses are use configurable game fields and therefore are not translated (they won't change with Playnite's language). You can rename them in Library -> Library manager menu.

**Comment by RiseT** [comment]
Oh, I see, thanks. I'm not sure if this is ideal in its present form, though. The built-in default completion statuses that come with a Playnite installation should be translated imho. Which of course doesn't mean users shouldn't be able to edit them afterwards if they want to.
