### ISSUE TITLE
Update the "Get more themes" link

### ISSUE THREAD

**Issue by Jeshibu** [JosefNemec/Playnite#2906]
### Feature description

In Settings > Appearance, next to the theme selection dropdown, there is a "Get more themes" link. It takes you to the extensions forum section. I'd propose updating this to go to https://playnite.link/addons.html but with the Themes Desktop section opened (haven't found a way to do that via URL just yet though, might require a change there too).

**Comment by JosefNemec** [comment]
Done in devel.
