### ISSUE TITLE
No images 

### ISSUE THREAD

**Issue by Kratos20191920** [JosefNemec/Playnite#2907]
### Feature description

the apereas to be no images on the game covers both the themes the ps5 look no background image no nothing cant log in the PlayStation now 

### Screenshots

![Uploading ps5.jpg…]()

**Comment by JosefNemec** [comment]
- I have no idea what this issue is about
- I have no idea if this is related to some custom (PlayStation) theme or PlayStation integration
- I have no idea why is this opened as an "enhancement"
- Also there's no screenshot attached

Please try to rephrase what the issue, thanks.
