### ISSUE TITLE
Add-ons updates notification is not cleared inspite of completing it along with an unsupported extension

### ISSUE THREAD

**Issue by ykiran** [JosefNemec/Playnite#2916]
### Bug Description

The updates notifier badge shows as 2 updates available:

1. Add-ons updates for the Harmony and Stardust themes
2. An error message saying "Can't load Twitch Library Importer"

I've updated the themes sometime back, but still keep getting the update notification.
Not sure about the Twitch extension; this message started appearing only after I updated to the recent version of Playnite.

Screenshots for reference:

![image](https://user-images.githubusercontent.com/5526410/166743089-ae45758a-d018-4b73-b4ae-fe245704df13.png)

![image](https://user-images.githubusercontent.com/5526410/166742791-551ecab6-72cf-4c6b-9907-3525c8a17d8f.png)

![image](https://user-images.githubusercontent.com/5526410/166742827-743fac80-321e-4551-8932-a95b849eab1b.png)

### Diagnostics ID

261bbcd5-0696-41e4-a5bb-eec33e639e67

### Screenshots

Screenshots for reference:

![image](https://user-images.githubusercontent.com/5526410/166743089-ae45758a-d018-4b73-b4ae-fe245704df13.png)

![image](https://user-images.githubusercontent.com/5526410/166742791-551ecab6-72cf-4c6b-9907-3525c8a17d8f.png)

![image](https://user-images.githubusercontent.com/5526410/166742827-743fac80-321e-4551-8932-a95b849eab1b.png)

**Comment by JosefNemec** [comment]
Twitch plugin is no longer supported, use Amazon games one instead.

Don't know about those themes, but it's definitely not an issue in Playnite, try uninstalling and reinstalling them.

**Comment by ykiran** [comment]
It was the add-ons that were not updating and thus were showing the notification repeatedly. Was able to update to the latest version today. 
Also, I've disabled the Twitch extension,
Thanks for your time.
