### ISSUE TITLE
WindowsVersion detection is wrong

### ISSUE THREAD

**Issue by matthiakl** [JosefNemec/Playnite#2917]
### Bug Description

The WindowsVersion detection has invalid conditions. Instead of using `version.Major` it should probably be `version.Minor` for the second parts.

https://github.com/JosefNemec/Playnite/blob/0f5538cb325318014576188eee3b6c1236ea96f5/source/Playnite/Common/Computer.cs#L85-L89

I spotted this bug, because the shutdown command did not work on my Win7 (no `-hybrid` option) (re #2607)

**Comment by JosefNemec** [comment]
Fixed in devel.
