### ISSUE TITLE
Library scanner does not exclude most common unrelated executables

### ISSUE THREAD

**Issue by oromis995** [JosefNemec/Playnite#2919]
### Bug Description

When scanning a library, executables such as installers, unity crash handlers, C++ Redistributables, notification helpers, python executables, are not filtered.
List of executables that should be filtered:

- python.exe    #common in python games
- pythonw.exe    #common in python games
- UnityCrashHandler64.exe    #common in unity games
- UnityCrashHandler32.exe    #common in unity games
- vc_redist.x64.exe    #Microsoft redistributable C++
- vc_redist.x86.exe    #Microsoft redistributable C++
- Config.exe    #clearly a config
- zsync.exe    #updater that seems to be in all RPGM games? Maybe wolf, but still very common
- zsyncmake.exe     #updater that seems to be in all RPGM games? Maybe wolf, but still very common
- notification_helper.exe    #common in some nodejs programs

Screenshots not included for privacy purposes, however attention to case and precise spelling was paid when writing these executables.

### To Reproduce

Scan a folder to find the libraries.

### Diagnostics ID

edbeb8f2-95c3-4e1d-8fcc-a76d5e2b1a70

**Comment by JosefNemec** [comment]
Done via #2920
