### ISSUE TITLE
Grid View items dissapear before they are fully out of view while scrolling

### ISSUE THREAD

**Issue by darklinkpower** [JosefNemec/Playnite#2923]
### Bug Description

Grid View items disappear before they are fully out of view while scrolling when grouping is enabled. Doesn't happen to the first item in the row that is partially out of view.

### To Reproduce

1. Enable grouping
2. Scroll down

### Diagnostics ID

91d226d2-b440-4b06-9058-6a9a1434651b

### Screenshots

![Playnite DesktopApp_aE0BDbLGoj](https://user-images.githubusercontent.com/1389286/167513567-36200337-392c-4ac3-8d48-9fe9c0a659d0.png)

https://user-images.githubusercontent.com/1389286/167513573-dc554934-3029-44d7-a12c-f829afe2f0e2.mp4

**Comment by Jeshibu** [comment]
It doesn't happen to the first item in the grouping, unrelated to rows.

**Comment by JosefNemec** [comment]
Fixed in devel.
