### ISSUE TITLE
Add a timeout prompt or retry mechanism to the Play operation

### ISSUE THREAD

**Issue by sv158** [JosefNemec/Playnite#2924]
### Feature description

For example, if game executable didn't launch as expected, then try to relaunch the game one more time. 
If it still does not work properly, a timeout prompt window will pop up from Playnite or shows in system notification aera. 

----

The background is that recently I found an unexpected behavior on launching the game imported by Battle.net integration: 
The game (Heroes of the Storm) already running, but the status of Play button still shows `Launching` and will not become to `Running` at all. Even I exit the game and Battle.net launcher, the button still shows `Launching`.

It was not long before I found out that it wasn't all Playnite's fault, I remembered I've moved the game to a new location but forgot to update the game path info in Playnite entry. After I fixed the game path, the Play button works fine  as expected. 

P.S.  I have no way to checked or modified the game's default `Action` because it included via library integration. So in order to find out more details, I tried manually add a same game entry which uses old game path. 
This time the Play button didn't keep in `Launching` state, however after started the game, it just shows `Play` but not `Running`. 
Due to the inconsistent behavior of the two, I cannot conclude that this is a bug. That's the main reason why I chose open this issue as a feature request instead of bug report.

**Comment by JosefNemec** [comment]
This is up to each library plugin to handle it individually. Playnite itself has no idea how a game is launched or if its in fact running or not.
