### ISSUE TITLE
Backwards compatibility for themes.

### ISSUE THREAD

**Issue by digimancer** [JosefNemec/Playnite#2925]
### Feature description

Not liking the newer theses, don't want to downgrade to run older theme....

**Comment by darklinkpower** [comment]
That's not possible.

Your only option is to downgrade and use the theme you want or if the theme is updated to support the current version. You can ask the theme developer if they can update it or as a last resort update it yourself: https://playnite.link/docs/master/tutorials/themes/distributionAndUpdates.html#updating-themes

**Comment by JosefNemec** [comment]
It would require so much effort and time to maintain that it's just not worth it.
