### ISSUE TITLE
Fornite not showing up as installed

### ISSUE THREAD

**Issue by CreepyGiantz** [JosefNemec/Playnite#2926]
### Bug Description

Fortnite refuses to show up as installed. The two ways of making it show as installed are; clicking the install button which opens up Epic Games and sets it as installed. Second option is setting the install location manually and checking the "installed" box. Sadly both solutions reset when rebooting Playnite. Other games in the same directory as Fortnite don't have this issue.

### To Reproduce

I'm not sure how to reproduce this, I've tried reinstalling the Epic integration. Removing the game manually and letting my library update but these didn't change anything.

### Diagnostics ID

ebe90830-7647-4efd-a651-3438f038669a

**Comment by JosefNemec** [comment]
Wrong repository, this is handled by Epic plugin. Try reinstalling the game.
