### ISSUE TITLE
Better visual feedback when moving focus in fullscreen

### ISSUE THREAD

**Issue by Super1337Boy** [JosefNemec/Playnite#2927]
### Feature description

When navigating in fullscreen I notice a couple of issues that in my opinion make things unnecessarily disorienting.

1. When moving focus to the activated quick filter, there is no visual indication that focus is moved there. Shouldn't there be some kind of highlighting that is different from when a quickfilter is activated but not in focus?

2. At the same time there is no visual indication that focus is moved away from an activated game to the quick filters and back again. (except for the scrollbar) I think it would make more sense if the orange frame and zoom-in effect is removed when focus is moved to the quick filters.

### Screenshots

https://user-images.githubusercontent.com/6672819/168415756-0ca83921-80fe-430e-91be-ef603520c8f9.mp4

**Comment by JosefNemec** [comment]
Done in devel.
