### ISSUE TITLE
Request to have Fullscreen mode to switch filter location on RB / LB

### ISSUE THREAD

**Issue by Cath818** [JosefNemec/Playnite#2931]
### Feature description

So I've noticed that when I tap LB/RB on Fullscreen mode, it changes the filter you are actively viewing, but if you have a large number of filters that extended off the screen, Playnite has no way of focusing them to show what filter you're looking at. I've uploaded a video to show this problem. I'm using a theme but the same issue happens without any themes on the default setting.

Could this be somehow addressed? Or perhaps a solution to this specific issue proposed? Thank you!

### Screenshots

https://user-images.githubusercontent.com/105950745/169625293-df6b4f09-e830-4b55-b885-6fc621647c4c.mp4

**Comment by Cath818** [comment]
I realize this might have been explained very poorly, my apologies. I mean the top bar that shows the filters, it would be beneficial to have that bar scroll along once they get off screen as I press RB / LB.

**Comment by JosefNemec** [comment]
Fixed in devel.

**Comment by Cath818** [comment]
Thank you! I can't believe you added this in Playnite 10!!!! You rock!!!!
