### ISSUE TITLE
PCSX2 QT Launch arguments have changed/Missing built-in profile for 64-bit SSE4 Qt release

### ISSUE THREAD

**Issue by TheGershon** [JosefNemec/Playnite#2934]
### Bug Description

The newly publicly released Qt version of PCSX2 has changed it's commandline arguments which broke integration with Playnite, causing games to fail launching when using a Qt build.

According to running `pcsx2-qtx64-avx2.exe -help` via commandline:
![PCSX2 cmd](https://user-images.githubusercontent.com/6880780/169921996-a287d733-f2ac-41c5-ba4d-7afc0564bfe1.png)
To get as similar of a result as the wx versions, the arguments must change from `"{ImagePath}" --nogui --fullboot --fullscreen` to `-fullscreen -slowboot -- {ImagePath}`. `--nogui` seems to have no equivalent for now.

While on the subject of PCSX2 profiles, I've noticed there's no Playnite profile for the 64-bit SSE4 Qt nightly release. Along with including this, I'd recommend renaming the profiles from "Default 32/64-bit" to avoid confusion.

### Diagnostics ID

04cbfef0-e2bd-4f16-8946-fa2e5d1bba1e

**Comment by TsukikoChan** [comment]
To add to this, please add an equivalent for the Cfgpath=  parameter as it's needed for game specific controller/gpu/savefile loads from steam/playnite.

For myself, this particular parameter breaks loading games from steam. I can load some games from steam using imagepath without cfgpath, but once cfgpath is added it doesn't load.
But, it does load correctly for the latest wxwidget build.

**Comment by JosefNemec** [comment]
Fixed in devel.

**Comment by ToMattBan** [comment]
Using the latest Nightly version (v1.7.4322) the executable also changed the name. 
Now is just pcsx2-qt.exe
