### ISSUE TITLE
[Request] Changing the font and size for games in the list view.

### ISSUE THREAD

**Issue by FancyPenguin** [JosefNemec/Playnite#294]
Title pretty much sums it up. This is nowhere an important request, but I'd like if it was possible to modify the font and size (pictures and size of the font) in the list view or all the view. 

I'm used to "Steam" and I currently find that the list doesn't display enough games. Although I could switch to use the "details" view, I find it less attractive since it doesn't give the same info as the "list" view does showing the gamepage and quick summary.

Like I said, this isn't an important feature, just something I'd like.

Thanks.

**Comment by JosefNemec** [comment]
Will be possible via custom themes #71
