### ISSUE TITLE
Ability to manage categories from fullscreen

### ISSUE THREAD

**Issue by Sylvaeseel** [JosefNemec/Playnite#2945]
### Feature description

The ability to manage/change categories from fullscreen view, for example, add Halo MCC to a category named "x", categories don't need to be defined in fullscreen, it'd be kind of hard to do so with a controller, but there's no reason to not be able to assign a predefined category to a game. On top of that, being able to define the playing state of the game in fullscreen, like currently playing, completed, etc.

**Comment by JosefNemec** [comment]
#2935
