### ISSUE TITLE
Playnite keeps claiming that an installed game is not installed.

### ISSUE THREAD

**Issue by Foshitz** [JosefNemec/Playnite#2946]
### Bug Description

Every time I restart my computer, Playnite says that some games from the Epic Games Store are not installed.
The games are installed, and as soon as I click the "Install"-button in Playnite, both of them updates to the "Installed" status right away.
All games from Epic Games are installed on the same hard drive.

### Diagnostics ID

102ce769-9142-45ad-90ca-0083d0380566

**Comment by Foshitz** [comment]
Games affected by this:
- A Plague Tale: Innocence
- Bridge Constructor: The Walking Dead
- Cosmic Express
- Crashlands
- Creature in the Well
- Frostpunk
- Hob
- Idle Champions of the Forgotten Realms
- Journey
- Lifeless Planet
- My Time At Portia
- Obduction
- Pine
- Remnant: From the Ashes
- RUINER
- Satisfactory
- Shadow Tactics: Blades of the Shogun
- Snowrunner
- Sonic Mania
- Space Punks
- Tacoma
- The Colonists
- The Fall
- The Spectrum Retreat
- The Stanley Parable
- Train Sim World 2
- Tyranny - Gold Edition
- Wargame: Red Dragon

**Comment by JosefNemec** [comment]
1) This is all  handled by Epic plugin, so wrong repository.
2) https://github.com/JosefNemec/PlayniteExtensions/wiki/Epic-Game-Store-troubleshooting
3) Make sure that install state is not being changed by some other installed extension. If clicking Install sets proper state immediately, then it means that Epic plugin itself is detecting the state properly.

**Comment by JosefNemec** [comment]
I checked the logs and it's full of these errors:
`Epic game A Plague Tale: Innocence installation directory T:\EpicGames\APlagueTale not detected.`

So Epic's config files are pointing games to folders that don't exists, see troubleshooting link I posted in my previous message.
