### ISSUE TITLE
Import Emulator - Cemu Error

### ISSUE THREAD

**Issue by Sourenics** [JosefNemec/Playnite#2947]
### Bug Description

Playnite does not configure **Cemu** emulator.

I was told to go to Library > Configure emulators... > Import > Choose the folder where Cemu is installed.

However a bar appears like it's searching for something, but then it does nothing. 3 or 4 minutes later it closes like you did nothing.

### To Reproduce

Just go to the Menu > Library > Configure emulators... > Import > And choose the installation folder for the emulator.

### Diagnostics ID

b67ad5d8-0ec8-473c-bdc3-b481ade13af6

### Screenshots

![playnite](https://user-images.githubusercontent.com/47475710/172003765-8a9e85d5-1b6c-426c-a6bd-2b7aa431199a.jpg)

**Comment by JosefNemec** [comment]
Test with the latest nightly build of Citra and the latest Playnite, Citra is properly detected and imported so most likely fixed by some update since this issue was created.
