### ISSUE TITLE
Instant "stopped working" window on launch ever since a Windows 10 update

### ISSUE THREAD

**Issue by slaugaus** [JosefNemec/Playnite#295]
This one:
![untitled2](https://user-images.githubusercontent.com/23143819/34075128-d7041d7e-e271-11e7-8a49-ebf6b1c60df3.png)

- This has happened in both 2.9 and 3.0 for me.
- I have tried both reinstalling and deleting the folder in AppData\Roaming, but neither have helped.
- This happens before any useful logs can be created in said folder.
- It appears to be caused by [update KB4054517](https://support.microsoft.com/en-us/help/4054517/windows-10-update-kb4054517) judging by when I got it.

![untitled](https://user-images.githubusercontent.com/23143819/34075129-e24ca49e-e271-11e7-9b62-abd63702521d.png)

**Comment by JosefNemec** [comment]
Does it still happen if you disable Windows Defender?

**Comment by ArtexJay** [comment]
Check to see that your AV hasn't deleted anything or some program might interfere. I am up to date on Win10 and havent encountered such issue

**Comment by JosefNemec** [comment]
Also can you try to run Playnite as administrator to see if it helps?

**Comment by slaugaus** [comment]
Turned off real-time protection and ran as admin, still does the same thing. Defender doesn't say that it's removed anything.

**Comment by slaugaus** [comment]
OK, apparently it's caused by MSI Afterburner. Exited it and Playnite launched again.

**Comment by JosefNemec** [comment]
OK, thanks for the info. You can also disable GPU acceleration in settings menu, that should fix it as well.
