### ISSUE TITLE
Visual Bug When Grouping by Last Played and Midnight Passes

### ISSUE THREAD

**Issue by burnpsy** [JosefNemec/Playnite#2950]
### Bug Description

I have my library in grid view, sorted by Name and grouped by Last Played.

Normally, this works perfectly, with games moving between groups as I play them or not. However, the groupings do not update as a day rolls over. If I play a game at, say, 12:01 AM, the game is added to the "Today" group, but at the front of the list (ignoring the name sorting). The games that were played the previous day remain in the "Today" group instead of moving to the "Yesterday" group. Overall, none of the groupings update to reflect that it is a different day unless I change my filters or restart Playnite.

### To Reproduce

With the library setup the way I described (grid view, sort by name, group by last played), play a few games. Then leave Playnite open and wait until after midnight without touching your filters, and play any game.

The issue is more immediately apparent if the game played is either one of the ones you did not play the previous day, or if it is one of those games but it is not the first one alphabetically.

### Diagnostics ID

4f4166a8-65bc-49c6-a416-685ff1774875

### Screenshots

I have been unable to prepare a screenshot, mostly because I only get one opportunity per 24 hours and reflexively change my filters to fix it. My apologies.

**Comment by JosefNemec** [comment]
Same issue as #1995
