### ISSUE TITLE
all games in menu 

### ISSUE THREAD

**Issue by AhmedAbdElNaSsSer** [JosefNemec/Playnite#2951]
### Feature description

Hello,
First of all, thanks for this theme ( ps5 ish ) put i want some features if it could .. i want to see all games in menu not in ( all games section ),
And in notification section no logo for ps5 like ( xbox ish theme ),
And when i move in between games the theme get a bit laggy and moving randomly,
And if it could make us to put like logo or pics like steam or any launcher put my logo my name etc .. 

Thanks for helping and for all of ur works <3 

### Screenshots

![image](https://user-images.githubusercontent.com/97300429/172854608-bf57c7e0-ba9d-431a-8794-b3b44f7625e2.png)

**Comment by JosefNemec** [comment]
This repository is for issues and feature requestes related only to built-in functionality. You need to report this in ps5ish's repository (or wherever its dev wants feedback to be reported).
