### ISSUE TITLE
Can't download add-ons

### ISSUE THREAD

**Issue by 244671360** [JosefNemec/Playnite#2952]
### Bug Description

It shows "Failed to download add-on installation manifest. I reinstall the playnite but it still can't download.

### Diagnostics ID

c785c462-f0b5-4d38-b935-e74af3ab4756

### Screenshots

![Snipaste_2022-06-11_14-35-36](https://user-images.githubusercontent.com/36124979/173176520-572cc1e4-f0da-4540-80a0-29d7b8c2956b.png)

**Comment by JosefNemec** [comment]
Playnite is unable to reach `raw.githubusercontent.com` in this case. So either network issue or you have your AV/Firewall blocking Playnite process from accessing it.
