### ISSUE TITLE
Allow for more space between game covers in Fullscreen mode

### ISSUE THREAD

**Issue by C-Dub87** [JosefNemec/Playnite#2958]
### Feature description

I recently got a Steam Deck and one thing that struck me was how much space between game covers the library view has.

I tried to put that amount of spacing in on Fullscreen mode but it seems to max out at 40. In the desktop version I can go up to 999, which allowed me to space game covers in desktop mode to how I'd like them, but 40 is just not enough in Fullscreen mode.

I've attached a screenshot of the Steam Deck library view just to give you an idea of what I'd like to have on Playnite Fullscreen mode in terms of cover spacing.

Perhaps allowing us to space our Fullscreen library more than 40 is something that could be implemented in a future version of Playnite? I think it'd go a long way to making the Fullscreen mode look less cramped.

### Screenshots

**Steam Deck UI**
![Steam Deck UI](https://user-images.githubusercontent.com/12431105/174475630-b2d63e6d-3168-4123-a27c-0ce74d5aaebe.jpg)

**Comment by JosefNemec** [comment]
Done in devel.
