### ISSUE TITLE
Background Wallpaper in Modern mode

### ISSUE THREAD

**Issue by ArtexJay** [JosefNemec/Playnite#297]
I think that playnite would look a lot better if we got ride of the solid color in the description of the game (which i have circled in the screenshot) and instead replace it with a slightly darker transparent box or completely transparent.
![capture](https://user-images.githubusercontent.com/32932497/34075524-52b8d296-e297-11e7-8353-f4f208f74a1d.PNG)

Also if we could download the background image from the database if they provide any other images for the game.

**Comment by JosefNemec** [comment]
Yeah this is a bit tricky. It depends on what the background image is. If I make it completely transparent then the text wouldn't be readable if the image is very bright. But changing the tone color to more generic black-ish transparent might be a better option.

**Comment by JosefNemec** [comment]
Scratch that, it's a bug. I just found that the correct theme didn't get pushed with new release. This is how it should look like:

![image](https://user-images.githubusercontent.com/3874087/34077781-107ce18a-e30d-11e7-8baa-8919b4e3a384.png)

**Comment by JosefNemec** [comment]
I've updated 3.0 binaries, you have to re-download 3.0 manually (auto-update will not patch it).

**Comment by ArtexJay** [comment]
Thank you~ it's great now XD, also i forgot to mention that the red theme did not work, but it does now :D
