### ISSUE TITLE
Turn Off System / Shutdown option not working in Windows 7

### ISSUE THREAD

**Issue by gotbletu** [JosefNemec/Playnite#2971]
### Bug Description

Turn Off System aka shutdown not working.

im on windows 7 64bit with Playnite on Fullscreen Mode
Restart and Hibernate works but Shutdown never works.
I see a cmd screen popup then disappears really quick but after it execute, nothing happens.

### To Reproduce

Playnite (Fullscreen Mode) > Turn Off System

### Diagnostics ID

ffcc206f-d04c-4ec3-9a1c-f486e7fb4c2f

**Comment by JosefNemec** [comment]
Was fixed in Playnite 10.
