### ISSUE TITLE
Cycling through preset filters using LB/RB issue

### ISSUE THREAD

**Issue by stanejera** [JosefNemec/Playnite#2973]
### Bug Description

> I have this one issue where when I'm cycling through the preset filters using the LB/RB shortcuts, the top icons do not "scroll through" when reaching the end of the visible list. I have a relatively long list so not all icons are shown at the top. The listed games in the main frame do change but you don't know which filters are applied since the highlighted icons at the top are no longer visible.
> 
> Scrolling on the top icons/filters with D-Pad/LS + A works as intended but LB/RB just feels more intuitive and faster.
> 
> Hope my explanation makes sense but I've attached a GIF just in case. I'm not sure if this is a bug on my end or an overall playnite limitation.

I actually initially posted this on the [ReskinPS5 github page](https://github.com/TheKersalMassive/ReskinPS5/issues/37). The developer noted that the issue was present even in the default theme and suggested that I post it here instead. 

Love all the work you do with playnite, btw! 

### To Reproduce

Add a bunch of preset filters (that are shown as quick filters in fullscreen mode) such that the list becomes longer than the visible space available. Cycle through the filters using LB/RB. 

### Diagnostics ID

56da1098-45d3-4d5b-a670-f9202a51ffca

### Screenshots

![cycling](https://user-images.githubusercontent.com/108636612/177890874-ecd072e4-e607-4ba7-b19f-73c7dda0020b.gif)

**Comment by JosefNemec** [comment]
#2931
