### ISSUE TITLE
Themes and plugins gallery - Playnite integration

### ISSUE THREAD

**Issue by ArtexJay** [JosefNemec/Playnite#298]
Specification:
- List all currently installed themes / extensions
  - List author, versions and link to the gallery
- Options to disable and uninstall extension / theme
- Gallery browser with ability to install extensions / themes
  - Basically integrate web view with stuff from #593 

Origin request:
I'm sure you've already thought about this :P but just in case it would be cool to have on your website or some place on the web, where we can submit themes to share with others, view them other people's themes and download them.

**Comment by JosefNemec** [comment]
That would be great, I was thinking about creating some community website. With forums, skin gallery and extension gallery. Everything integrated into single site, with ability to push theme updates, which can be then downloaded automatically by Playnite without need for new program update.

**Comment by ArtexJay** [comment]
sounds great!

**Comment by JosefNemec** [comment]
I've temporarily created [theme list on reddit](https://www.reddit.com/r/playnite/comments/7o2bd2/custom_themes_database/)

**Comment by ArtexJay** [comment]
awesome!

**Comment by JosefNemec** [comment]
Rough specification:
- Users should be able to submit themes and plugins once they created account
- They should be submit updates to existing records
- Each record must have minimum required Playnite version
- Playnite will be able to search, download and update themes/plugins directly (like VS extension gallery for example)
- Users will be able to download themes/plugin via web gallery
- Ratings and comment will probably integrate via #430

**Comment by JosefNemec** [comment]
I have split this between general gallery that should be available on the web #593 and integration in Playnite that would allow to use that gallery for installation and updates (this issue).

**Comment by simeonradivoev** [comment]
Why not use NuGet? They are basically just zipped files like the current plugin packages files. The only issue is how to sync their spec file and the extension YAML file.

There are multiple ways to go about it:
One is to use the [NuGet command-line interface](https://docs.microsoft.com/en-us/nuget/reference/nuget-exe-cli-reference). It can search for packages, add them and remove them.

The other is to just use the [Rest API ](https://docs.microsoft.com/en-us/nuget/api/overview) to search, fetch and download the packages and they can straight up just be extracted using the existing system. Github packages also work with NuGet so the API should be the same.

**Comment by JosefNemec** [comment]
This is already done in Playnite 9, I forgot to close it.

**Comment by simeonradivoev** [comment]
What does it use?

**Comment by JosefNemec** [comment]
Custom solution.
