### ISSUE TITLE
Wikis have good Covers

### ISSUE THREAD

**Issue by Klemci** [JosefNemec/Playnite#2980]
### Feature description

I found that Wikis have good quality covers (PCG, Dolphin, Pcsx2... ...). And i often find some rare things (e.g: Sega Ages).

That's all for today ;)

**Comment by JosefNemec** [comment]
Has to be done as metadata plugins for each wiki individually. I personally don't have any time to develop or maintain additional plugins, so somebody from the community would have to create them.

**Comment by Klemci** [comment]
I understand, some covers are not good, others are better, and also there is some rare images (cover) in good quality, that's the advantage, it's time consuming to search custom images, after 200 games i used wikis a lot for console emus and a few times for PC (15 approximatively)...

Bon week-end.

**Comment by Klemci** [comment]
A reminder could be added telling that wikis can habe some good covers but there is no DB at this time , somewhre in the app, as a tooltip or other !
