### ISSUE TITLE
Games started via URL trigger InvokeOnStarted two times

### ISSUE THREAD

**Issue by darklinkpower** [JosefNemec/Playnite#2988]
### Bug Description

Games started via URL trigger InvokeOnStarted two times. I was made aware of the issue in https://github.com/darklinkpower/PlayniteExtensionsCollection/issues/280

This also causes `OnGameStarted` to be called twice in plugins

I've identified that it is triggered in these two places
https://github.com/JosefNemec/Playnite/blob/4e17416f866c38e6892408ffa0fec9983368a125/source/Playnite/Controllers/GenericGameController.cs#L484-L490

https://github.com/JosefNemec/Playnite/blob/4e17416f866c38e6892408ffa0fec9983368a125/source/Playnite/Controllers/GenericGameController.cs#L558-L561

### To Reproduce

Add a game action with Link type and enabled Play action checkbox using one of the two following URIs (with GTA V as an example game) leads to the mentioned crash:

- Default launch URI: steam://launch/271590/
- Non-default launch URI: steam://launch/271590/Option1

Playnite.log

```
16-07 00:36:14.547|INFO |GamesEditor:Starting Grand Theft Auto V, 32461062-cf2f-4b77-9310-c5252880cb93, 271590, cb91dfc9-b977-43bf-8e70-55f46e410fab
16-07 00:36:14.900|DEBUG|GamesEditor:Using generic controller start a game.
16-07 00:36:14.942|DEBUG|ProcessStarter:Opening URL: steam://launch/271590/Option1
16-07 00:36:15.042|INFO |GamesEditor:Started Grand Theft Auto V game.
16-07 00:36:15.042|DEBUG|ProcessMonitor:Watching dir processes E:\Spiele\Steam\steamapps\common\Grand Theft Auto V, False, False
16-07 00:36:17.075|INFO |GamesEditor:Started Grand Theft Auto V game.
```

### Diagnostics ID

😶

### Screenshots

![image](https://user-images.githubusercontent.com/1389286/179335587-fc95aec5-eea5-4c76-800b-f7e9530936f7.png)

**Comment by JosefNemec** [comment]
Fixed in devel.
