### ISSUE TITLE
Simplified Chinese Translation for Playnite

### ISSUE THREAD

**Issue by L1cardo** [JosefNemec/Playnite#299]
The latest Simplified Chinese localization updated for Plyanite 4.5
-------2018.9.9
更新了适用于Plyanite 4.5的最新简体中文版本
-------2018.9.9

Download the file below and extract it into "Localization" folder , you can find the folder here  \Playnite\Localization

下载下面的文件并将其解压缩到“Localization”文件夹中，您可以在这里找到文件夹
\Playnite \Localization

[中文.zip](https://github.com/JosefNemec/Playnite/files/2364145/default.zip)

**Comment by JosefNemec** [comment]
Thanks, released in updated 3.0 release.

**Comment by L1cardo** [comment]
![image](https://user-images.githubusercontent.com/33802186/34078180-2bd22de4-e350-11e7-8f5c-a9c1c6ebb6e8.png)
some cannot be translated，can you fix this in the next version？

**Comment by evgdovg1996** [comment]
Also waiting for fix, and I will do the Russian version

**Comment by JosefNemec** [comment]
3.2 update added new string for localization:
https://github.com/JosefNemec/Playnite/commit/ad9500c54713b53cf6e8bab1df4f0ee9fbf0be1a#diff-fc6eaa727d5578c3ac3d59652659d9e2
https://github.com/JosefNemec/Playnite/commit/b122a110cce6735adca31c3a5caadd0ab6451f91#diff-fc6eaa727d5578c3ac3d59652659d9e2

**Comment by L1cardo** [comment]
The latest Simplified Chinese localization updated for Plyanite 3.2
-------2017.12.20
[simplified chinese.zip](https://github.com/JosefNemec/Playnite/files/1574942/simplified.chinese.zip)

But there are still to fix in 3.2


![1](https://user-images.githubusercontent.com/33802186/34200699-fa79b21c-e5ac-11e7-9865-bd6b6843824e.png)

**Comment by L1cardo** [comment]
The latest Simplified Chinese localization updated for Plyanite 3.3
-------2017.12.22




[simplified.chinese.zip](https://github.com/JosefNemec/Playnite/files/1582105/simplified.chinese.zip)

**Comment by JosefNemec** [comment]
I won't be posting updates to original English files in every separate localization issue anymore. Please subscribe to new [localization updates](https://github.com/JosefNemec/Playnite/issues/385) issue to be notified when new stuff needs translation. But please keep posting your updated files in appropriate language issues. Thanks

**Comment by JosefNemec** [comment]
Please keep the name of the file as it was `中文.xaml` originally. I can't rename it in application itself because it would break for people using this language.

**Comment by L1cardo** [comment]
I just want to be sync with other guys.I think it is not good that others use english and i use chinese for the file name. Please rename it into **simplified chinese.xaml** instead of **中文.xaml**. but i can rename it if you insist.

**Comment by JosefNemec** [comment]
File name is used in settings as indicator what language user uses, if I rename it it will crash the application at startup #587. And honestly it really doesn't matter that it's not english file name.

**Comment by L1cardo** [comment]
ok then. I have remaned it into `中文.xaml`

**Comment by JosefNemec** [comment]
Localization have been completely move to Crowdin: https://crowdin.com/project/playnite

Please join the project there to submit updates.
