### ISSUE TITLE
Won't import some free Steam games

### ISSUE THREAD

**Issue by HoratioSvetlana** [JosefNemec/Playnite#2990]
### Bug Description

Playnite won't import some free Steam games, and won't import any demos.

It imported Princess Remedy but not Gravity Bone.

I have "Import generic free items" checked, and whether my Steam account is private or public doesn't effect it.

As an aside, GOG Galaxy will import all free games but not demos.

### Diagnostics ID

faccfeb0-6865-423b-814a-c35d092c75a6

**Comment by darklinkpower** [comment]
As indicated in the issue template extension issues should not be opened in this repository

![image](https://user-images.githubusercontent.com/1389286/179433720-ab3222a9-e8dd-40ec-a2aa-bfbfc2a9c87a.png)

**Comment by JosefNemec** [comment]
What darklinkpower says. Also copy of my response from reddit:

If you have that enabled, but your games are still not being imported then:
1) You might have a filter enabled which prevents those games from showing up.
2) It's an issue on Steam's side. We use Steam's API to get list of games from your library. If their API doesn't report a game in that list, we can't import it.
3) You already imported those games in the past and then removed them and added them to the import exclusion list (you can check in settings -> import exclusion list).
