### ISSUE TITLE
Emulated games not importing

### ISSUE THREAD

**Issue by Wilted** [JosefNemec/Playnite#2994]
### Bug Description

When I try to import emulated Dolphin games for the Wii profile, they are not showing up. The correct folder to search in is selected and the games are in there, yet nothing shows when it searches.

### To Reproduce

1. Go to `Add Game -> Emulated Game`
2. Select Dolphin with Wii profile
3. Select the folder Wii games are in
4. `Start Scan`

### Diagnostics ID

92de7e43-bef6-47c9-926f-9256c1c37155

### Screenshots

![image](https://user-images.githubusercontent.com/32426008/180581165-13cccf17-b1e4-4b88-8ff1-b9252a126b94.png)

**Comment by JosefNemec** [comment]
Please post screenshots of emulator profile and emulator scanner you are using.

**Comment by Wilted** [comment]
![image](https://user-images.githubusercontent.com/32426008/180618767-5131d5cf-b3df-4a52-86de-cd64d3c20033.png)
![image](https://user-images.githubusercontent.com/32426008/180618790-889cecf4-4acd-4ee6-a2ab-3bf16e606867.png)
![image](https://user-images.githubusercontent.com/32426008/180618811-9585a7a9-6458-4d71-ab5a-aca0dbadaf7a.png)

**Comment by Wilted** [comment]
![image](https://user-images.githubusercontent.com/32426008/180618822-ca3f53c2-22a6-4f75-9292-e33a5f04dae4.png)

**Comment by JosefNemec** [comment]
Can you check if you don't have those games imported already? You maybe have some view filter enabled that's not showing them. Emulation scanner skips ROM files that are already imported in Playnite.

**Comment by Wilted** [comment]
I checked, and those games are not available in my library. There are no active filters; when I search for them specifically, they do not appear.
