### ISSUE TITLE
Choppy/missed inputs when multiple controllers are connected

### ISSUE THREAD

**Issue by WyntrHeart** [JosefNemec/Playnite#2995]
### Bug Description

When multiple controllers are connected Playnite Fullscreen starts missing inputs, so pressing buttons is sometimes randomly ignored. I checked with other applications and games to make sure it wasn't wireless interference or something else, and only Playnite had this issue. Removing all but one controller causes the inputs to return to normal responsiveness. Each additional controller makes the issue worse, with 4 controllers being extremely choppy and unresponsive.

### To Reproduce

Run Playnite in fullscreen mode with more than one controller connected

### Diagnostics ID

0ac43e52-98b8-457e-8ad9-70d2767dc0ea

**Comment by WyntrHeart** [comment]
I tested on two different PC's and had the same issue. All controllers are Xbox 360 controllers and both PCs are running Windows 10

**Comment by JosefNemec** [comment]
Fixed in devel.
