### ISSUE TITLE
Failed to open library database after new update

### ISSUE THREAD

**Issue by deextercz** [JosefNemec/Playnite#300]
Proceed to update and after it is finished there is and database error.
![capture1](https://user-images.githubusercontent.com/23039506/34078360-05d0e36a-e319-11e7-905b-c28e5c634883.PNG)
[diag.zip](https://github.com/JosefNemec/Playnite/files/1565492/diag.zip)

I am also able to reproduce when trying to import from accounts

[games.zip](https://github.com/JosefNemec/Playnite/files/1565501/games.zip)

**Comment by JosefNemec** [comment]
Can you please upload you database file?

**Comment by deextercz** [comment]
Uploaded

**Comment by JosefNemec** [comment]
For some reason your db file has wrong version, did you open it by any chance with some development builds?

Anyway here's repaired file:
[games.zip](https://github.com/JosefNemec/Playnite/files/1565503/games.zip)

**Comment by deextercz** [comment]
Thanks, now it works.
