### ISSUE TITLE
login to epic always failed.

### ISSUE THREAD

**Issue by zero617** [JosefNemec/Playnite#3003]
### Bug Description

can't login to epic!!!

### Diagnostics ID

88a831d4-9d51-4f46-8637-985fd6d030b9

### Screenshots

![image](https://user-images.githubusercontent.com/67105838/181297762-6002293f-6e33-4c77-b237-5f1558862cec.png)

**Comment by JosefNemec** [comment]
wrong repository, please read issue template.
