### ISSUE TITLE
HeroicGamesLauncher play action

### ISSUE THREAD

**Issue by zachvlat** [JosefNemec/Playnite#3005]
### Feature description

I know that you can download the game from Heroic and then make a custom play action to launch the game through Playnite, but it would be more useful if (somehow) Playnite read the games that were installed with heroic and either launch them directly, or through Heroic launcher.

**Comment by JosefNemec** [comment]
There are no plans for adding support for 3rd party implementations of existing launchers. I myself already have to maintain a lot of integrations that use official launchers and this is just out of scope for me. Somebody from the community would have to create a plugin that works specifically with Heroic.
