### ISSUE TITLE
Emulated game variables incorrect

### ISSUE THREAD

**Issue by xunkar** [JosefNemec/Playnite#3006]
### Bug Description

`{ImagePath}`, `{ImageName}` and other derivatives always point to the first-configured ROM image

### To Reproduce

An emulated game is configured as such 
![image](https://user-images.githubusercontent.com/329857/181812906-7d32d78a-dbed-4e54-94e1-2b34f3b2e6e6.png)

In the emulator profile configuration, I've set "execute before starting emulator" script to `import.ps1 "{ImagePath}"`
The import script simply writes in a log file the value of the parameter

    param([string] $imagePath)
    $file = new-object io.streamWriter "log.txt"
    $file.writeLine("$($imagePath)")
    $file.close()

Upon starting the game using the Play action, no matter which image is selected, `{ImagePath}`, `{ImageName}` and other derivatives always point to the first-configured ROM image (in this case, `PS-FINAL8-U.m3u` no matter which version I try to boot.)

### Diagnostics ID

c25ae2ac-c194-450a-8ab0-5f29d80a5ee9

**Comment by JosefNemec** [comment]
You need to use `$SelectedRomFile` 
https://playnite.link/docs/master/manual/gameScripts.html

**Comment by xunkar** [comment]
I see. I was basing my research on this list https://playnite.link/docs/master/manual/gameVariables.html it might be useful to note this variable on this page too.

**Comment by xunkar** [comment]
Wait,  `$file.writeLine($SelectedRomFile)` from the PS script should work right? But I'm only getting an empty string.

**Comment by JosefNemec** [comment]
It only works from game scripts, not emulator scripts, will be fixed in next version.
