### ISSUE TITLE
Running a random game in fullscreen mode shows cover of last game seelcted.

### ISSUE THREAD

**Issue by akumenon** [JosefNemec/Playnite#3008]
### Bug Description

In fullscreen mode, if you select "Pick a random game" via the Playnite menu and launch anything, the screen that shows what game is launching shows the covert art of the game previously selcted/highlighted outside of the random picker window.

### Diagnostics ID

b9d510ed-2dc6-4dab-867b-f3ce95711b43

### Screenshots

Previously selected game "Bulk Slash" shows up as cover art when "Blood: Fresh Supply" is randomly selected and launched.

https://user-images.githubusercontent.com/6745915/182610050-0be1e1c1-86cb-464d-9d65-e7c85b625003.mp4

**Comment by JosefNemec** [comment]
#2723
