### ISSUE TITLE
Cannot import VisualBoyAdvance-M emulator

### ISSUE THREAD

**Issue by batistarasta** [JosefNemec/Playnite#3016]
### Bug Description

Playnite is unable to Import visualboyadvance. I tried manually adding the directory in but when trying to load a ROM, it says "cannot start game, emulator executable not found.

### Diagnostics ID

???????

**Comment by JosefNemec** [comment]
Attach diagnostics ID that was requested in issue template, thanks.

**Comment by batistarasta** [comment]
> Attach diagnostics ID that was requested in issue template, thanks.

#3016, is this the ID?

**Comment by batistarasta** [comment]
> Attach diagnostics ID that was requested in issue template, thanks.

Sorry I'm new here, I realised that was probably not the diagnostic ID but where can I generate one?

**Comment by JosefNemec** [comment]
> Please generate diagnostics package from "About Playnite" menu and attach identifier you received. If the issue is a crash bug, you can generate diag. package directly from crash dialog.
