### ISSUE TITLE
playnitemodernUI filter icons reset to plain

### ISSUE THREAD

**Issue by batistarasta** [JosefNemec/Playnite#3018]
### Bug Description

![image](https://user-images.githubusercontent.com/111014658/184126726-6fec0d89-35ed-4d08-ab43-8347f7a3f952.png)

All filter icons keep resetting to the plain "book" icon. The only solution I have found is to reset defaults using the DKGthememodifier which makes the normal aesthetic icons appear in fullscreen mode. However after closing playnite down and opening another session, the filter icons are lost again and the plain "book" icons appears for all filters even the all, most played, recent played.

### To Reproduce

I am not sure how this happened.... I can't find this problem reported anywhere else.

### Diagnostics ID

?????

### Screenshots

![image](https://user-images.githubusercontent.com/111014658/184127351-8676388a-6e6c-4511-b958-141d0560369d.png)

**Comment by batistarasta** [comment]
ID is #3018

**Comment by JosefNemec** [comment]
Issues with custom themes need to be reported to their devs, this repository is only for issues related to built-in functionality.
