### ISSUE TITLE
ares support to emulator config

### ISSUE THREAD

**Issue by DrMasquerade** [JosefNemec/Playnite#3022]
### Feature description

ares can be added manually, but I would like for it to be added as a default import option since it's not too difficult I don't think and would be useful. I have an example I made that could be improved

### Screenshots

![2022-08-17 12_09_43-Configure Emulators](https://user-images.githubusercontent.com/43123409/185189421-732c160a-b4a9-426a-90f8-fedab41ee3d5.png)

**Comment by JosefNemec** [comment]
Done in 10.10
