### ISSUE TITLE
Automatically display multiple images and videos, as needed, about each game

### ISSUE THREAD

**Issue by Gareth4321** [JosefNemec/Playnite#3025]
### Feature description

GOG Galaxy provides rich media in metadata which is downloaded as needed. This enables me to quickly evaluate the game's themes and style using visual media. This is much more efficient than text alone. This feature request includes:

1. Media downloaded as needed from an online source; NOT bulk downloaded for the entire library.
2. Media includes multiple videos AND images, NOT embedded in existing Description field.

See screenshot for preferred UX.

### Screenshots

![image](https://user-images.githubusercontent.com/72940366/185654791-d760e356-29dd-48ed-a0f6-d2c9fcabb8bf.png)

**Comment by JosefNemec** [comment]
There are already multiple issues related to additional metadata like videos and trailers, including an issue related to fetching these on demand.
