### ISSUE TITLE
Version text filtering appears to be case sensitive

### ISSUE THREAD

**Issue by 0-Hex** [JosefNemec/Playnite#3026]
### Bug Description

Version text filtering appears to be case sensitive, where I imagine it is supposed to be case insensitive like display name text filtering.

### To Reproduce

Example: 
Titles marked Undub will not show up if undub is used as filter but will if Undub is used.

### Diagnostics ID

b837c3b9-c4a4-428c-9e7f-e13b2af29268

### Screenshots

![with Undub capitalized](https://user-images.githubusercontent.com/111504845/185754915-b09d9623-451a-495f-acca-4c4f5b7a9f95.png)
![with undub not capitalized](https://user-images.githubusercontent.com/111504845/185754922-e187bcb5-7ffd-4356-ab41-044b6a96750f.png)

**Comment by JosefNemec** [comment]
Done in devel.
