### ISSUE TITLE
Custom organizing

### ISSUE THREAD

**Issue by Swagenator** [JosefNemec/Playnite#3033]
### Feature description

I have an idea, i want to be able to add my own groups and custom group names. Like right clicking on the grid and a option will appear like "create group" then i can click and drag the games to the group and it will be added. I also want an option to rename groups. Like if there is a group named "none" then i can right click it, select re-name and change it to something like "shooter". If you could make this a feature than that would be amazing. Thanks in advance!

**Comment by Jeshibu** [comment]
Categories work like this, don't they?

**Comment by JosefNemec** [comment]
What you describe can be done using categories or other game fields (tags, features etc.). You need to enable list grouping for these groups to be actually visible in the game list (via a button on the top panel).
