### ISSUE TITLE
Hope can support WeGame Library

### ISSUE THREAD

**Issue by JohnnyWoong** [JosefNemec/Playnite#3034]
### Feature description

New game platform [WeGame](https://www.wegame.com.cn)

**Comment by JosefNemec** [comment]
Personally, I have no plans adding any new integrations, I already have a lot of them to maintain. Somebody from the community will have to make it as 3rd party addon (like it already happened with many other libraries).

**Comment by JohnnyWoong** [comment]
> Personally, I have no plans adding any new integrations, I already have a lot of them to maintain. Somebody from the community will have to make it as 3rd party addon (like it already happened with many other libraries).

Alright, thanks :)
