### ISSUE TITLE
Loading all views if only one is open

### ISSUE THREAD

**Issue by Kosnix** [JosefNemec/Playnite#3035]
### Bug Description

while working on my theme, I realized that when I loaded the Gamedetail.xaml with Playnite full screen, the windows seem to load as soon as you switch to a new game without clicking on it and without unloading the ram. It would not be possible to load it only if we click on it? the whole is unloaded if you change category.

### To Reproduce

Use a resource-heavy full-screen theme with a lot of game to realize this easily with the task manager.
- Launch playnite in full screen
- Load the Gamedetail of a game
- Go back to games list
- Note what playnite consumes in ram with the task manager
- Scroll the list of games on all games
- compare the ram usage with the first measurement

### Diagnostics ID

78b5867f-ae3d-43bb-854c-0a28cedacb35

**Comment by JosefNemec** [comment]
Duplicate #2739
