### ISSUE TITLE
not possible to authentificate epic account

### ISSUE THREAD

**Issue by noyse27** [JosefNemec/Playnite#3036]
### Bug Description

hi 
im not able to authentificate my epic account. after insert the TFA the window is closing and an error occur that the user cannot be authentificate. im using Playnite 9.19 and no updates are available

BR Jens

### Diagnostics ID

55d1d64d-8422-4497-a4cc-660dfef2c2c9

**Comment by JosefNemec** [comment]
wrong repository

**Comment by Jeshibu** [comment]
To clarify, extension issues belong to the repository they are from. In this case; https://github.com/JosefNemec/PlayniteExtensions, where this issue has already been reported: https://github.com/JosefNemec/PlayniteExtensions/issues/207

**Comment by noyse27** [comment]
Sorry for any inconvenience. I will pay more attention in the future Am 31.08.2022 20:32 schrieb Jeshibu ***@***.***>:
To clarify, extension issues belong to the repository they are from. In this case; https://github.com/JosefNemec/PlayniteExtensions, where this issue has already been reported: JosefNemec/PlayniteExtensions#207
