### ISSUE TITLE
Epic Library fails after passing captcha test and two-factor sign in code, displays message "Failed to authenticate user"

### ISSUE THREAD

**Issue by johnobrien** [JosefNemec/Playnite#3038]
### Bug Description

Playnite does not import Epic games

### To Reproduce

1. Navigate to Addons->Browse->Libraries
2. Install Epic Store library integration
3. Restart Playnite
4. Navigate to Library->Configure Integrations->Epic
5. Enable "Import installed games", "Connect Account", "Import not installed games".
6. Click the "Authenticate Button"
7. Enter your username and password.
8. Pass the Captcha
9. Navigate to your email
10. Copy/Paste two factor sign-in-code to login screen.

Observed Behavior: System displays message "Failed to Authenticate user"
Expected Behavior: User is authenticated.

### Diagnostics ID

4e4e45c5-8257-486c-b392-0796823d4dfd

**Comment by JosefNemec** [comment]
#3036
