### ISSUE TITLE
Epic Library 2.11 is not connecting

### ISSUE THREAD

**Issue by paulocampoy** [JosefNemec/Playnite#3039]
### Bug Description

When start Playnite the Epic Store not connects... 

### To Reproduce

- Open Playnite using Epic Library 2.11
- Will not connect, try to connect using the library
- Enter with your user and password or you may try to connect using Google sing on.
- Will send a warning advice that was not connected
- Games of Epic Store will not be showed on Playnite 9.19

### Diagnostics ID

c6ce62ea-9699-41aa-a6d8-abe398a57e4d

**Comment by paulocampoy** [comment]
I could see that there was CAPTCHAS to sing on EPIC now...

**Comment by JosefNemec** [comment]
#3036
