### ISSUE TITLE
Support for Oculus Store

### ISSUE THREAD

**Issue by quakertroy** [JosefNemec/Playnite#304]
Would love to have integration with the Oculus storefront so I could launch my VR games from this program!

**Comment by JosefNemec** [comment]
Do you know if I can use Oculus store even if I don't own their VR hardware (at least to buy and install games)?

**Comment by quakertroy** [comment]
Doesn't hurt to try. You can download the client [here](https://www.oculus.com/setup/), and I think you can skip the HMD setup when you launch it. Might be able to claim some free games and see if they install.

**Comment by XN1TE** [comment]
I would like to add to this that you can get a list of your games from their website.

If you login to the oculus website and when you go to the My Rift page, you can see all of your owned games under the My Experiences section: https://secure.oculus.com/my/rift

This could be another vector for importing the Oculus library.

**Comment by Moby2kBug** [comment]
Is this still in development, since #523 has been implemented already?

**Comment by janforster** [comment]
Related to this one, it would also be nice to support management of games from other oculus platforms (Gear VR/Go/Quest) for purposes similar as #549 .

**Comment by sawfear** [comment]
Sorry to ask, but did anyone yet create an Oculus library importer? Would love to also integrate this store in Playnite

**Comment by Kilroy5150** [comment]
> Would love to have integration with the Oculus storefront so I could launch my VR games from this program!

I own Oculus and i use HTC Vive's and it would be outstanding to access those.

**Comment by Kilroy5150** [comment]
> Do you know if I can use Oculus store even if I don't own their VR hardware (at least to buy and install games)?

Yeah, you can fake your way past the setup like i did with HTC Vive. Basically, on most of them, you can "skip" the setup if you like and muddle your way through.

**Comment by JosefNemec** [comment]
I'm closing this since it's being developed as a user plugin in [separate repository](https://github.com/Shawson/Playnite-OculusLibrary).

**Comment by FolfyBlue** [comment]
Could you reconsider opening this, as the user plugin no longer works and the repo doesn't seem to be maintained?

**Comment by FolfyBlue** [comment]
Would you reconsider as of today, considering the user plugin is discontinued? I cannot get it to work on recent Playnite versions.

**Comment by JosefNemec** [comment]
You need to ask in plugin's repository.
