### ISSUE TITLE
Next/Previous buttons when editing game

### ISSUE THREAD

**Issue by ariesps** [JosefNemec/Playnite#3040]
### Feature description

When editing game details would be useful to have next/previous buttons, to be able to edit next/previous game, without the need to save, select the new game and select again Edit.

When selecting next or previous, the changes made should be saved.

These buttons could be placed, at bottom when editing game details, in between Download Metadata and Save / Cancel. Or maybe two flag buttons at top right.

### Screenshots

A quick screen idea.

![image](https://user-images.githubusercontent.com/7125095/188294362-ff230615-91b4-4ead-bdde-9094638ab6c6.png)

**Comment by JosefNemec** [comment]
#2243
