### ISSUE TITLE
Main menu item added by an extension gets duplicated if menu is opened multiple times

### ISSUE THREAD

**Issue by XenorPLxx** [JosefNemec/Playnite#3041]
### Bug Description

After installing an extension that adds a new main menu item, this menu item gets duplicated when the menu is opened multiple times in a _relatively_ short period of time, without any other actions being taken in the middle.

Specific extension that's causing the issue: https://github.com/sharenite/playnite-sharenite/blob/ef220da11b5c4a47913f3fd949dbf2673d0c4bb5/Sharenite.cs#L46

### To Reproduce

* Install Sharenite
* Try opening menu like on the video

### Diagnostics ID

61d61258-412f-4e8a-b7be-f929f18884ee

### Screenshots

https://user-images.githubusercontent.com/6712823/188317187-4c28930e-ecdf-4f53-8f87-6cd71c78fdde.mp4

**Comment by JosefNemec** [comment]
Fixed in devel.
