### ISSUE TITLE
Minimize to tray when opening a game

### ISSUE THREAD

**Issue by hyoretsu** [JosefNemec/Playnite#3044]
### Feature description

Title, pretty simple. I don't want an extra window for Playnite open 24/7, but I also don't want to have the delay of Playnite opening every time.

**Comment by JosefNemec** [comment]
Set "when game starts" option to "minimize" and enable minimizing to tray.

**Comment by hyoretsu** [comment]
Well, it's definitely not intuitive, being in Appearance and all. Also not enabled by default.
