### ISSUE TITLE
StarCraft Remastered consider as not installed at every import scan

### ISSUE THREAD

**Issue by VirgileVILE** [JosefNemec/Playnite#3045]
### Bug Description

I don't know why but every time I scan all the game platforms, battle.net removes StarCraft Remastered from the installed games when it's not, and I have to go back and show it the directory manually every time. I don't know why Playnite does this with this game and it's very annoying.

### Diagnostics ID

76b2b724-0218-460b-b37e-ab2f9fab8b18

**Comment by JosefNemec** [comment]
1) Wrong repository since this is handled by battle.net plugin.
2) Try repairing game installation in battle.net client. https://github.com/JosefNemec/PlayniteExtensions/wiki/Battle.net-troubleshooting#games-not-reported-as-installed

**Comment by VirgileVILE** [comment]
Who do you think you are to talk to me like a common moron? I don't give a fuck that you are designed all this, without people like us to use your mess you are nobody, so respect the human being who does his job by pointing out what he sees!
Thanks.
