### ISSUE TITLE
It would be possible to implement a menu for viewing achievements within the page of each loaded game

### ISSUE THREAD

**Issue by ShellAndPython** [JosefNemec/Playnite#3046]
### Feature description

I think it would be interesting to have a visualization of our achievements within the page of each game loaded, or a kind of Menu where we can go through our achievements obtained and available. I think of having this in 2 possible ways.

1 - A new menu called "Achievements", this menu will have the same layout as the total games menu, but the difference is that when we click on a specific game, it will show all our achievements in relation to that specific game.

2 - Within the game selector menu, when clicking on a game to play, information about the achievements for that specific game will appear

**Comment by JosefNemec** [comment]
Generalized support for achievements will be added by #2041, however there's also a community made plugin for it https://playnite.link/addons.html#playnite-successstory-plugin
