### ISSUE TITLE
Quick acess behaving differently in taskbar and system tray

### ISSUE THREAD

**Issue by flipperyikes** [JosefNemec/Playnite#3047]
### Bug Description

Some icons that show up in the when I right click playnite in the system tray, don't show up in the taskbar (even after restart) and also, when I make a change to an icon I have to restart playnite for it to update on the taskbar but it instantly changes in the system tray, but this might be intended behavior, I'm not sure.

I'm not sure what causes the icons to break in the first place in the taskbar but I can tell that every icon that is broken was changed with steamGridDB and that when they match the steam icon, even if downloaded from SteamGridDB it works

### Steps to Reproduce
1) Download icon from steamGridDB that doesn't match steam icon
2) It shows up in the system tray quick access menu but not on the taskbar's menu.

### Diagnostics ID

4a5c488a-a306-44ce-86f0-f0d453734f83

### Screenshots

![image](https://user-images.githubusercontent.com/76697414/189287481-becf8dcc-df8a-4105-821d-142b61998851.png)
![image](https://user-images.githubusercontent.com/76697414/189287510-a7df6dda-a327-4e76-91d9-8884af30778a.png)

**Comment by JosefNemec** [comment]
This is Windows limitation not supporting any icon format other than .ico. So only games with .ico icons will have icons in the task bar.
