### ISSUE TITLE
New search in Playnite 10 (Patreon build) shows Sorting Name instead of Game Title

### ISSUE THREAD

**Issue by NatParable** [JosefNemec/Playnite#3049]
### Bug Description

When using the new CTRL+F search in the Patreon build of Playnite 10, the games listed show their Sorting Names instead of their Game Titles.

In this example below, I have used unique sorting names to ensure that the various Tomb Raider games I own are correctly sorted by continuity (the original Core Design games, the Legend trilogy, and the Survivor trilogy). For example, Tomb Raider Chronicles has the sorting name of Tomb Raider Core 5, as it was the fifth game in the original Core Design games, and Tomb Raider Anniversary has the sorting title of Tomb Raider Legend 2, as it was the second game in the Legend trilogy by Crystal Dynamics.

![image](https://user-images.githubusercontent.com/47304926/189510089-5d9b6809-c475-4dad-ad27-36bc1ff92a2b.png)

At first I assumed this was intended behaviour, and that I was simply missing a setting to switch to the Game Titles rather than the Sorting Names, but it was suggested this might be a bug and that I should report it here.

### Diagnostics ID

6f0148d1-e361-4b35-ac82-179ea2e57d88

**Comment by JosefNemec** [comment]
Fixed in 10.1
