### ISSUE TITLE
Trailers Large with no Sound

### ISSUE THREAD

**Issue by RosellaCamella** [JosefNemec/Playnite#3055]
### Bug Description

After updating The DKG Theme Modifier to v2.8.1, video trailers are now the span of the screen behind the background image and do not have any sound even when hitting the Play Video Audio button. The only way you can get sound currently is going in the Settings of Extra Metadata Loader and unchecking Play Videos Initially Without Sound. However in doing so, you cannot mute the videos. Hitting mute with this option unchecked will let the Playnite background music and video audio play at the same time. I have tried turning off and on different settings and hitting Apply and have also restarted my system.

### Diagnostics ID

be7d40f2-009d-4989-afd8-66969730779b

### Screenshots

![Trailers](https://user-images.githubusercontent.com/107732413/190926603-11338c99-9455-4dc3-b8f1-9eb5066a209b.JPG)

**Comment by JosefNemec** [comment]
You need to report this to developers of that theme and extension you are using.

**Comment by RosellaCamella** [comment]
> After updating The DKG Theme Modifier to v2.8.1, video trailers are now the span of the screen behind the background image and do not have any sound even when hitting the Play Video Audio button. The only way you can get sound currently is going in the Settings of Extra Metadata Loader and unchecking Play Videos Initially Without Sound. However in doing so, you cannot mute the videos. Hitting mute with this option unchecked will let the Playnite background music and video audio play at the same time. I have tried turning off and on different settings and hitting Apply and have also restarted my system.

Apologies, I got anxious and didn't check where the "Report Feedback" button took me. I thought I was on the Theme creators report.
