### ISSUE TITLE
Authentication Issues - Multiple Extensions

### ISSUE THREAD

**Issue by Byron1c** [JosefNemec/Playnite#3056]
### Bug Description

Windows 11, Nord VPN Installed but not running, latest Portable installation

1. Epic Authentication fails. Confirmed it works in my browser, but after getting through the verification, and the Authentication code (seemingly successfully), Playnite reports Authentication Failure. 
2. Authenticate button for Amazon and Xbox do not work. Click the button and nothing happens (no dialog box)

### To Reproduce

1. Try authenticating with Epic
2. Try pressing the Authenticate buttons for Amazon and Xbox

### Diagnostics ID

294591be-26fa-4efb-afd5-277311b91809

**Comment by JosefNemec** [comment]
Authentication is handled completely by each individual library extension, therefore any issues have to be reported in their repositories.

**Comment by Byron1c** [comment]
cbf
