### ISSUE TITLE
Adding an executable in a game's Other Actions doesn't actually start it.

### ISSUE THREAD

**Issue by CantyCanadian** [JosefNemec/Playnite#306]
I tried to get my Dark Souls Connectivity Mod to be started at the same time as the game itself by adding it to the Other Actions list, but it just doesn't start it. Unless that menu is for other things. If that's so, then having the option of opening extra softwares on the side would be nice.

![image](https://user-images.githubusercontent.com/7960042/34081866-6d7d91e4-e322-11e7-864e-4f029c1eef8f.png)

**Comment by JosefNemec** [comment]
That's not how "Other actions" are meant to work. They are separate actions you can invoke via game context menu, they are no linked to Play action.

What you want to do has been requested in issue #113. For now you will probably need to create .bat script that will run the game and mod at the same time. Then set that .bat file as executable action for your Play action.
