### ISSUE TITLE
Could not detect game install size: Path not found - PlayNite 10

### ISSUE THREAD

**Issue by Terael76** [JosefNemec/Playnite#3067]
### Bug Description

Try to scan install size for crusader kings. Then a error apears.
![grafik](https://user-images.githubusercontent.com/68641824/191750246-8c0cca2e-c979-4ecf-9f55-ef1edfe1e9c1.png)

### To Reproduce

Right Click CKIII -> Calculate Install Size

### Diagnostics ID

4d95e3ce-ec94-4777-892b-adb1f16602a1

**Comment by darklinkpower** [comment]
Can you please share screenshots of the `Installation` and `Actions` tab from right click -> Edit?

**Comment by Terael76** [comment]
If u need these setting.

![grafik](https://user-images.githubusercontent.com/68641824/191828218-d7324784-dd7d-4dde-91e1-c9e2ed17dc66.png)
![grafik](https://user-images.githubusercontent.com/68641824/191828247-a849e426-307a-4613-b785-3968a1e76bf6.png)
