### ISSUE TITLE
Spanish Translation for Playnite

### ISSUE THREAD

**Issue by darklinkpower** [JosefNemec/Playnite#307]
And here it is. 

[spanish.zip](https://github.com/JosefNemec/Playnite/files/1565895/spanish.zip)

**Comment by JosefNemec** [comment]
3.2 update added new string for localization:
https://github.com/JosefNemec/Playnite/commit/ad9500c54713b53cf6e8bab1df4f0ee9fbf0be1a#diff-fc6eaa727d5578c3ac3d59652659d9e2
https://github.com/JosefNemec/Playnite/commit/b122a110cce6735adca31c3a5caadd0ab6451f91#diff-fc6eaa727d5578c3ac3d59652659d9e2

**Comment by darklinkpower** [comment]
[spanish.zip](https://github.com/JosefNemec/Playnite/files/1572729/spanish.zip)

Spanish translation updated with 3.2 added strings.

**Comment by adelpozoman** [comment]
¿Ya lo has hecho entero? Me gustaría ayudar, traducí gran parte de DuckDuckGo

**Comment by JosefNemec** [comment]
3.3 update added new string for localization:
https://github.com/JosefNemec/Playnite/commit/ec65168e6fb0f6dc207404c78f7647913441e956#diff-fc6eaa727d5578c3ac3d59652659d9e2

**Comment by JosefNemec** [comment]
I won't be posting updates to original English files in every separate localization issue anymore. Please subscribe to new [localization updates](https://github.com/JosefNemec/Playnite/issues/385) issue to be notified when new stuff needs translation. But please keep posting your updated files in appropriate language issues. Thanks

**Comment by JosefNemec** [comment]
Report from reddit:

in the Spanish translation of the setting menus, the English term "Remove" has been translated as "Remover", being more correct "Borrar", since using "Remover" is an anglisism. It's silly, but the correct translation of the term "Remove" is "Borrar".

**Comment by JosefNemec** [comment]
Localization have been completely move to Crowdin: https://crowdin.com/project/playnite

Please join the project there to submit updates.
