### ISSUE TITLE
"Launch playnite minimized" does not work

### ISSUE THREAD

**Issue by redactedscribe** [JosefNemec/Playnite#3071]
### Bug Description

It appears that Playnite's option "Launch playnite minimized" has stopped working since the introduction of version 10. Same issue in Safe mode.

**Edit:** Same problem for "Launch Playnite when you start your computer" > "Start closed to tray" (launches on startup in a restored state).

Playnite 10.1

### To Reproduce

Enable "Launch playnite minimized", exit Playnite, run Playnite. Window is displayed in the centre of the screen, not minimized.

### Diagnostics ID

-

### Screenshots

![pn](https://user-images.githubusercontent.com/25013746/191818485-0a09e834-36c0-4b6f-9f27-eb8d7aad12ec.png)

**Comment by Tetriser** [comment]
This bug is a little annoying honestly, I wish this can be fixed as soon as possible

**Comment by JosefNemec** [comment]
Fixed in master

**Comment by Rofii** [comment]
> 

I'm on 10.9 and it's still not working for me.

**Comment by Sohail-XD** [comment]
Same issue in 10.19
