### ISSUE TITLE
Ctrl+F to open global search doesn't work immediately after clicking away to main Playnite window

### ISSUE THREAD

**Issue by redactedscribe** [JosefNemec/Playnite#3072]
### Bug Description

Pretty much what the title says. If you close the global search with Esc, Ctrl+F has no issue immediately working again.

Playnite 10.1

### To Reproduce

- Press Ctrl+F
- Click on the main Playnite window (closes global search)
- Press Ctrl+F, and nothing
- Click the main Playnite window _again_
- Press Ctrl+F, global search now appears

### Diagnostics ID

-

**Comment by JosefNemec** [comment]
Fixed in master
