### ISSUE TITLE
Off screen add-ons

### ISSUE THREAD

**Issue by Kdog88** [JosefNemec/Playnite#3073]
### Bug Description

When right clicking on a title in the library not all extension are accessible and if you have a ton of add-ons some go off screen and arent available to access. 

### Diagnostics ID

9f3efbf9-d7f6-42ea-9b93-3d64d15d15e7

### Screenshots

![IMG_9816](https://user-images.githubusercontent.com/49170700/191832248-18e324b9-70bb-4c00-8502-4a6dbbf03928.JPG)

**Comment by JosefNemec** [comment]
Fixed in master.
