### ISSUE TITLE
Install size is not automatically calculated for games added via "Add game" menu

### ISSUE THREAD

**Issue by JosefNemec** [JosefNemec/Playnite#3077]
### Bug Description

For games imported via folder scan, MS Store games and game emulation import.

### Diagnostics ID

-

**Comment by darklinkpower** [comment]
I can't reproduce it. These Microsoft Store got their install size automatically scanned during library update

![image](https://user-images.githubusercontent.com/1389286/191878765-4e8521ad-30c7-4686-be2b-fe94c714601d.png)

**Comment by darklinkpower** [comment]
Same for these emulated games on library update

![image](https://user-images.githubusercontent.com/1389286/191878976-4e860a91-3edc-4c3e-9ad9-aacc1b482dc7.png)

**Comment by JosefNemec** [comment]
The size is scanned during library update, but it should be imo scanned directly after the initial import. Similar to how metadata are immediately downloaded after the import.
