### ISSUE TITLE
"Scan folder using Emulator" not detecting games

### ISSUE THREAD

**Issue by Yndaaa** [JosefNemec/Playnite#308]
Using the "Scan folder using Emulator" button when importing emulated games doesn't detect the supported file types. 
Tested with PCSX2, PPSSPP, ePSXe and Snes9X using default profiles.
Diag. package included.
[Diag.zip](https://github.com/JosefNemec/Playnite/files/1566023/Diag.zip)

**Comment by JosefNemec** [comment]
Can you please share content of some folders you are having issues importing? I'm mainly interested in how your ROM files are named.

**Comment by Yndaaa** [comment]
Paths are simple "This PC/Storage (E:)/Games/Final Fantasy XII/" type structure with the "Final Fantasy XII" folder containing few files, this one just containing "Final Fantasy XII (USA).iso" and "Final Fantasy XII.jpg" for the games custom cover.
This structure and these files didn't present the issue before 3.0 was released

**Comment by JosefNemec** [comment]
I'm still unable to reproduce it, can you try this with empty game database (move current .db file somewhere else and Playnite will create empty one next time you start it)?

**Comment by Yndaaa** [comment]
That fixed it. I guess my database is really messed up

**Comment by JosefNemec** [comment]
Thanks for the info, I saw some database migration errors in the logs so I thought it may help.
