### ISSUE TITLE
.cue/.gdi install size not properly detected (emulated games)

### ISSUE THREAD

**Issue by ppvnf** [JosefNemec/Playnite#3082]
### Bug Description

The new install size feature in version 10.1 is pretty cool. I had just 1 small problem though. The install size of my PS1 emulated games (currently using duckstation for emulation) with the .cue file selected as rom weren't detected automatically (nor using the right click option "Calculate install size"). As a workaround I am using the .bin and .ecm files as rom instead and then clicking the option "Calculate install size". Tbh I've already done this with all my games, but maybe fixing this will help other people.

Oddly enough, not all my PS1 games had this problem. I've seen a few games that had 1 or even 2 .bin files and a .cue file where the file size was measured out of the box and other games with the exact same file setup that I had to use the workaround. The game size/location is also similar in both cases. Thankfully duckstation magically allows playing .bin files even when there are more than 1.

### Diagnostics ID

5085d262-dbfa-4175-93cb-f1da5dcd6b1b

**Comment by ppvnf** [comment]
Oddly enough, not all my PS1 games had this problem. I've seen a few games that had 1 or even 2 .bin files and a .cue file where the file size was measured out of the box and other games with the exactly same file setup that I had to use the workaround. The game size/location is also similar in both cases. Thankfully duckstation magically allows playing .bin files even when there are more than 1.

**Comment by darklinkpower** [comment]
Can you share the content of one of the cue files?

Also a screenshot of the directory it is in.

**Comment by ppvnf** [comment]
> Can you share the content of one of the cue files?
> 
> Also a screenshot of the directory it is in.

Not detecting install size:
D:\Games\Emuladores\PS1\Adventures of Lomax [NTSC-U] [SCUS-94906]
D:\Games\Emuladores\PS1\Panzer Bandit (Japan)
D:\Games\Emuladores\PS1\Philosoma [U] [SCUS-94403]
D:\Games\Emuladores\PS1\Arkanoid R 2000 (Japan)
D:\Games\Emuladores\PS1\Zanac X Zanac (Japan)

[images.zip](https://github.com/JosefNemec/Playnite/files/9636408/images.zip)

[cue files.zip](https://github.com/JosefNemec/Playnite/files/9636386/cue.files.zip)

**Comment by darklinkpower** [comment]
Thanks. Your cue files are invalid or are pointing to files that don't exist:

Adventures of Lomax [NTSC-U] [SCUS-94906].cue:
- Point to: `Adventures of Lomax [NTSC-U] [SCUS-94906].bin`
- File in your directory: `Adventures of Lomax [NTSC-U] [SCUS-94906].bin.ecm`

Arkanoid R 2000 (Japan).cue:
- Point to: `Arkanoid R 2000 (Japan) [SLPM-86262].bin`
- File in your directory: `Arkanoid R 2000 (Japan).bin`

etc. The name of the file in the cue needs to match the name of the file you have in your directory.

How did you generate those cue files? Or perhaps you renamed the files? In any case, you can fix it by editing the cue files with any text editor

**Comment by ppvnf** [comment]
> Thanks. Your cue files are invalid or are pointing to files that don't exist:
> 
> Adventures of Lomax [NTSC-U] [SCUS-94906].cue:
> 
>     * Point to: `Adventures of Lomax [NTSC-U] [SCUS-94906].bin`
> 
>     * File in your directory: `Adventures of Lomax [NTSC-U] [SCUS-94906].bin.ecm`
> 
> 
> Arkanoid R 2000 (Japan).cue:
> 
>     * Point to: `Arkanoid R 2000 (Japan) [SLPM-86262].bin`
> 
>     * File in your directory: `Arkanoid R 2000 (Japan).bin`
> 
> 
> etc. The name of the file in the cue needs to match the name of the file you have in your directory.
> 
> How did you generate those cue files? Or perhaps you renamed the files? In any case, you can fix it by editing the cue files with any text editor

Thanks for figuring it out. Those files are quite old. I don't remember how I generated them. I guess I replaced the .bin files without editing the .cue file. In any case, I tested the ".cue" files in duckstation and somehow all of them (except Adventures of Lomax [NTSC-U] [SCUS-94906].cue) played without any problem. I don't understand how a .cue pointing to a non existing file is a problem to playnite but duckstation can "guess" the correct .bin file.

**Comment by darklinkpower** [comment]
The emulator must have a mechanism to still try to guess the game files even when it is invalid in these cases, like checking if a file of the same name as the cue file exists in the directory. Still I don't think we should be doing that in Playnite because it's not something that will work reliably, would make the processing slower and in my opinion the cue is invalid so Playnite shouldn't be doing the "patch" work.

**Comment by darklinkpower** [comment]
Lets wait @JosefNemec 's opinion about if we should take care of these cases or not.

**Comment by ppvnf** [comment]
I am also having a similar problem with Dreamcast games in .GDI file format. I guess the principle is the same as .CUE files. However, I don't think there's anything wrong with the files this time as the emulator Flycast could play the game. Converting it to CHD made Playnite able to recognize the game size. I have already converted most of my GDI files to CHD using CHDMAN and they are also playable after the conversion.

[Mars Matrix.zip](https://github.com/JosefNemec/Playnite/files/9651154/Mars.Matrix.zip)


![Captura de tela 2022-09-27 000705](https://user-images.githubusercontent.com/73800734/192424010-ec19ca82-c45e-4a01-95b2-9bfec5bfe416.png)

**Comment by ppvnf** [comment]
Probably related to https://github.com/JosefNemec/Playnite/issues/3093

**Comment by JosefNemec** [comment]
Sorry it took me so long to respond, I somehow missed this conversation.

I'm definitely not a fan of trying to guess what's the correct bin file. If playlist file (cue) points to a wrong file name, it's an issue in the cue file and it needs to be fixed there.

As far as that .gdi Dreamcast issue, we would need to add support gdi file parsing, I'll look into it.

Based on all of that, closing. If you encounter other size scanning issues, open new issue for them.
