### ISSUE TITLE
Install Size Scan Error after updating to 10.1

### ISSUE THREAD

**Issue by ykiran** [JosefNemec/Playnite#3083]
### Bug Description

Updated  Playnite to 10.1 today. After restarting this is the error I'm seeing:
![image](https://user-images.githubusercontent.com/5526410/192017104-f3e698c8-08cc-4149-b090-c38b7d367105.png)

Nothing has changed in these games folders.

Here is the diagnostics package id: 3d8a34c0-f2c5-4ebb-887e-732241794111

### To Reproduce

Update to the latest Playnite version (10.1) and restart.

### Diagnostics ID

3d8a34c0-f2c5-4ebb-887e-732241794111

### Screenshots

![image](https://user-images.githubusercontent.com/5526410/192017783-5b1f9aa1-77ac-42ab-9c5b-a003676b5b0a.png)

**Comment by darklinkpower** [comment]
Do the `c:\program files (x86)\steam\steamapps\common\motoRKDdash` and `c:\program files (x86)\steam\steamapps\common\Galaxy Control 3D Strategy` directories exist in your system? If so, can you share a screenshot of their contents please?

**Comment by ykiran** [comment]
This is how those look like (shortcut links) but they point to invalid directories:

![image](https://user-images.githubusercontent.com/5526410/192107330-1af5dcd9-a7b5-4410-bcab-767148b7bd22.png)


- C:\Steam\Galaxy Control 3D Strategy
- C:\Steam\motoRKDdash

Not sure why they're that way.

**Comment by darklinkpower** [comment]
Can you save those two directories to a zip file and upload them here please?

**Comment by darklinkpower** [comment]
Also, are you getting a dialog like this one when trying to open them? `Location not available`

![image](https://user-images.githubusercontent.com/1389286/192115119-0f05e8ae-0cb9-45b7-a8c3-f2c0cc03ee50.png)

**Comment by ykiran** [comment]
[common.zip](https://github.com/JosefNemec/Playnite/files/9641188/common.zip)

Here are the error messages I'm seeing when trying to open them:

![image](https://user-images.githubusercontent.com/5526410/192153282-9a629b1a-48ce-4ae0-9261-1882162c169d.png)
![image](https://user-images.githubusercontent.com/5526410/192153295-9144c728-f732-4c65-9a72-b37661b1a331.png)

**Comment by darklinkpower** [comment]
Thanks. I've identified the issue, the issue is that they are symbolic links that point to invalid target directories that don't exist. You can safely delete them to remove the issue for you as they are not valid anymore anyway. The third error is already fixed and will be included in a future update.

**Comment by ykiran** [comment]
>The third error is already fixed and will be included in a future update.
Thanks @darklinkpower this issue has been fixed. I updated to 10.3 and the error is not showing now.
I'm closing this issue now.
