### ISSUE TITLE
"Edit Fields" in Full Screen Confirm Button Does Nothing

### ISSUE THREAD

**Issue by MultiversalTraveler** [JosefNemec/Playnite#3087]
### Bug Description

When I go to edit a field in full screen (nice new desired feature), I can select any value (by hitting the A button on game pad) or all (by hitting the Y button), but hitting the button to confirm (the hamburger menu symbol or Start button) has no effect.  This is in sections that require it, like Category or Tags.  I am forced to hit B to go back, and when I reenter the fields have not changed.

### Diagnostics ID

bb8b4c4c-9a2d-4837-9614-b6ed16468722

**Comment by JosefNemec** [comment]
Fixed in master
