### ISSUE TITLE
Windows 11 Fullscreen

### ISSUE THREAD

**Issue by MauzRL** [JosefNemec/Playnite#3090]
### Bug Description

I have a 4k resolution, and 300% zoom, but when its displayed in the screen, it pixelates(the images and the texts and icons). I know this function was solved for w10, but I am wonder if you can do it for w11. Thanks!

### Diagnostics ID

Fullscreen scale

### Screenshots

![image](https://user-images.githubusercontent.com/90777531/192121523-f430d5b8-c31e-4d72-9968-61074364d147.png)

**Comment by JosefNemec** [comment]
Make sure you **don't** have any of these DPI settings enabled, this is how it should look like:
![image](https://user-images.githubusercontent.com/3874087/192135672-77ebed9e-55f4-4969-88cb-cc0a1e0d75d1.png)

**Comment by MauzRL** [comment]
Hi, I solved doing this:
![image](https://user-images.githubusercontent.com/90777531/192152893-bbaba9ed-fb2c-490a-810e-c6e837bc316c.png)
But i didn't know that  configuration exists, thanks a lot!
