### ISSUE TITLE
Missing translation strings in Playnite 10.2

### ISSUE THREAD

**Issue by ClearStrelok** [JosefNemec/Playnite#3092]
The following strings do not appear to have been added to Crowdin and cannot be translated at the moment: 

- getting add-on informations
- updated

The following string exists but doesn't appear to be used:

- updated (LOCExtensionVersion)

Those are found in the "add-ons" manager.

**Comment by JosefNemec** [comment]
Can you post screenshot for "update" string? I can't find it anywhere.

**Comment by ClearStrelok** [comment]
The missing strings are displayed in the add-ons description box. In fact it seems that "version" is also untranslated (it should use LOCExtensionVersion but here it doesn't appear to do so).

![Untitled-3](https://user-images.githubusercontent.com/38838369/192566055-be55c80b-55ac-4a1b-977c-e9985103accc.jpg)

**Comment by JosefNemec** [comment]
Fixed in master (strings pushed to Crowding).
