### ISSUE TITLE
"month-year" release dates ignore custom formatting

### ISSUE THREAD

**Issue by DomiDextrus** [JosefNemec/Playnite#3094]
### Bug Description

Full day-month-year release dates are formatted perfectly fine, but not if a game's release date doesn't signify a specific day of the month (e.g. with future game releases, or very old games where there's no clear information on the exact release date).

### Diagnostics ID

e810d833-0d68-4d77-88ac-c2774a7b80bf

### Screenshots

![playnite](https://user-images.githubusercontent.com/35101055/192139950-f512ce09-2a49-431f-b717-8f912ca4773b.png)

**Comment by JosefNemec** [comment]
Done in master, there's now an option to specify separate format for partial release date.
