### ISSUE TITLE
Daily automatic backups not triggering when they should

### ISSUE THREAD

**Issue by lordscales91** [JosefNemec/Playnite#3096]
### Bug Description

Hi there! 
I have enabled the automatic backups, I've configured it to trigger "Once a day". However, it seems that it's not really triggering every day, rather it's triggered every 24h.

Example: I startup Playnite at 07:00 PM. Next day I launch it at 05:00 PM. I would expect the backup to trigger, but it doesn't, probably because there has passed less than 24h since the last backup. Therefore, the schedule is not really once a day, but every 24h+ since last backup.

### Diagnostics ID

53d55526-8702-43e5-915b-4dd353f32c34

**Comment by JosefNemec** [comment]
Fixed in master
