### ISSUE TITLE
Social button missing

### ISSUE THREAD

**Issue by Neoakb** [JosefNemec/Playnite#310]
There used to be a chat/social button in the bottom right (classic theme), but it's gone in the latest version.

**Comment by ArtexJay** [comment]
From what i read on reddit from the author he took it away temporarily since it was causing some issue with the modern theme https://www.reddit.com/r/playnite/comments/7kcqdp/big_30_update_released/ 
In the comments it is discussed

**Comment by JosefNemec** [comment]
Released in 3.2
