### ISSUE TITLE
Issues when restoring from data backup

### ISSUE THREAD

**Issue by MagicalBlob** [JosefNemec/Playnite#3101]
### Bug Description

I used to backup Playnite using Google Drive for Desktop until I kept getting issues with it and stopped doing that, so I was glad to see the new backup option in Playnite 10.

To try it out, I started by making a safe working copy of the Playnite folder `C:\Users\Root\Playnite` (I have been using it as Portable since I used to be syncing with Google Drive) in order to restore at any time if the backup/restore process wasn't fully ironed out yet.

I then opened up Playnite as per usual and used the "Library > Backup Library Data" option with all data options selected:
![Backup Options](https://user-images.githubusercontent.com/6509486/192154400-062b2155-1a26-4b08-b37c-f988c69d0308.png)

Since my plan was to test how the backup restore worked, after the backup was complete, I removed Playnite, proceeded to do a clean install as the regular version (to the default AppData folders) and also as portable (to `C:\Users\Root\Playnite` like the original install) and used the "Library > Restore Data Backup" option (also with all options selected) to import the backed up data:
![image](https://user-images.githubusercontent.com/6509486/192154599-4f2c13a0-8610-4675-b8ed-20c23fa8e66e.png)

For both cases, after Playnite was done restoring the data, it opened up and showed up like this:
![Playnite After](https://user-images.githubusercontent.com/6509486/192153935-118293c5-46f9-4e0f-a2fe-6c98a71c2976.png)

For reference, this is how it looked on the original install:
![Playnite Before](https://user-images.githubusercontent.com/6509486/192154355-951bfb81-f563-46df-9b89-7489f334f4e4.png)

&nbsp;

The main issue is the absence of the games cover images and icons (obviously not visible in the screenshot, but they didn't show up in the Details/List views or the tray icon context menu), despite appearing to be present inside the ZIP archive that Playnite generated.

&nbsp;

Other issues that I've noticed are smaller things like:
* The restored version uses the default behaviour of Minimize Playnite to system tray when the application window is closed, when I had turned that off so it just closes Playnite completely (only minimize to system tray if the actual Minimize button is clicked or a game starts)
* Cover Art aspect ratio; Show game names on Grid view setting wasn't kept/restored

&nbsp;

Finally, and *only* when installed as the regular version (to AppData), and possibly because the data backup was made from a Portable version, the following error appeared (for `C:\Users\Root\AppData\Roaming\Playnite\Themes\Desktop` and `C:\Users\Root\AppData\Roaming\Playnite\Themes\Fullscreen`), but when I created those folders before restoring from backup, no error occurred:
![Failed to restore theme](https://user-images.githubusercontent.com/6509486/192155422-3aabd58c-c1f5-41bb-a8bc-8adbea1eacb0.png)

&nbsp;

I should mention the Diagnostics ID was generated from the original portable Playnite install that generated the backup (which is my regular install again), since all the issues were from restoring the backup on clean installs of Playnite 10.2.

If it's useful to test/reproduce I can also share the backup ZIP archive that Playnite created (should warn that it's ~2GB).

### Diagnostics ID

6f10a5f7-e6ce-4331-8c30-52a232c15ecd

**Comment by JosefNemec** [comment]
So you backed up from installed version and then tried to restore that backup in portable instance and then issues happened? Am I understanding it correctly?

**Comment by MagicalBlob** [comment]
Sorry if I made it a bit confusing. I backed up from a portable instance (which is located at `C:\Users\Root\Playnite`). After the backup was created, I removed that instance temporarily to an external drive.

Then I used the installer from the website to create a new Playnite install to try to restore the backup, which had these issues. I uninstalled Playnite again, and used the installer to create a clean Portable instance, but the same issues popped up (except for the themes folder issue which only occured on the regular install).

**Comment by MagicalBlob** [comment]
Here's the backup archive, in case it helps: https://drive.proton.me/urls/RS2Y2DR9ZC#EixTii7f6ZO7

**Comment by lordscales91** [comment]
I just did a test installing Playnite on a [Windows 10 Sandbox](https://learn.microsoft.com/en-gb/windows/security/threat-protection/windows-sandbox/windows-sandbox-overview) and restoring a backup. From what I could see the library media files are not imported, even if all options are checked. Manually extracting the files from the `libraryfiles` folder inside the ZIP file to `%AppData%\Playnite\library\files` restores all the thumbnails.

**Comment by IchinichiQ** [comment]
I encounter the same problem

**Comment by JosefNemec** [comment]
Fixed in master.
