### ISSUE TITLE
Epic games are always detected as not installed

### ISSUE THREAD

**Issue by TripleA160** [JosefNemec/Playnite#3104]
### Bug Description

As the title says Playnite always detects Epic games as not installed and when I press the install button it detects it as installed but when Playnite updates the Epic library (which happens on startup) it detects the games as not installed and I need to press the install button again.

### Diagnostics ID

cd159954-7a4a-49cc-8aa0-b3917233d9f0

**Comment by Jeshibu** [comment]
This should go in https://github.com/JosefNemec/PlayniteExtensions/
But do you have "Import installed games" checked in the Epic plugin settings? (main menu > Add-ons > Extension settings > Libraries > Epic)

**Comment by TripleA160** [comment]
Yes, and also "Import not installed games" is checked

**Comment by TripleA160** [comment]
Well I fixed this, I went to C:\ProgramData\Epic\EpicGamesLauncher\Data\Manifests and opened each file with Notepad to see which file belongs to the game and modified the path in it to the current game path
