### ISSUE TITLE
Hide filter applied notification in fullscreen mode

### ISSUE THREAD

**Issue by fewdji** [JosefNemec/Playnite#3105]
### Feature description

Hi!
Please add option to hide this notification. I have predefined tabs like All games, Multiplayer, Favourites.. And with this message it doesn't look clean :(

### Screenshots

![filter_notification](https://user-images.githubusercontent.com/13124598/192556332-2a5ada00-f871-4017-9dac-7e65de2111d0.png)

**Comment by cnapolit** [comment]
Very similar to an already solved (but not released) issue: https://github.com/JosefNemec/Playnite/issues/3113

**Comment by JosefNemec** [comment]
#3113
