### ISSUE TITLE
Game Install Size Calculation Failing On Long File Paths

### ISSUE THREAD

**Issue by Hassiopeia** [JosefNemec/Playnite#3107]
### Bug Description

The new file size calculation introduced in Playnite 10 is failing for long file paths. This produces an error and stops the processing of my game libraries. 

The attached error is even truncating the filepath; there's more to the path than it's even showing. 

### To Reproduce

Create a long file path and attempt to scan it with the install size calculator functions of Playnite.

### Diagnostics ID

1010fd53-74ce-4465-9f95-0ed9a925f087

### Screenshots

![image](https://user-images.githubusercontent.com/46950645/192621735-b5012c2b-0333-4060-887a-65a419a660a2.png)

**Comment by ppvnf** [comment]
Updating to 10.3 should solve this

**Comment by JosefNemec** [comment]
They are already on 10.3

**Comment by ppvnf** [comment]
> They are already on 10.3

My bad. I was searching the issue list and thought this one was the same as in https://github.com/JosefNemec/Playnite/issues/3067, but looking closer the error message is slightly different

**Comment by JosefNemec** [comment]
This functionality has nothing to do with any addon. Do you actually get that error dialog during library update? That should definitely not happen, failures during library update should be silent.

You can disable size calculations during library update in general settings.

**Comment by Hassiopeia** [comment]
Thanks, I didn't know it was able to be turned off, I'll do that. I realize it's not an addon in Plyanite 10, but I thought darklinkpower's size calculation addon from Playnite 9 had been integrated into 10. I'm sorry if I misunderstood that. 

I'm getting the error during the size calculation, but I'm noticing that newly purchased games aren't' being imported, and I assumed it was this error that was stopping the import process.

**Comment by darklinkpower** [comment]
Can you extract this test build (Separate from your normal Playnite install), create two games with the same Installation Directory as those games and check if the error happens in Edit -> Installation -> Calculate

https://drive.google.com/file/d/11RabLpmhcl8ZMYf1XC4iHPnaRBtRWWtj/view?usp=sharing 

If there is an error please upload your playnite.log file

**Comment by complex-hub** [comment]
Tried the build on my machine, since I'm having the same error with Need For Speed: Heat, but sadly it still seems to happen. I attached my playnite.log below.

![image](https://user-images.githubusercontent.com/53913349/196050355-9da31054-d088-4c50-a3b8-caa4296fe96e.png)

[playnite.log](https://github.com/JosefNemec/Playnite/files/9795332/playnite.log)
