### ISSUE TITLE
Updating CompletionStatus shows data change on Advanced tab

### ISSUE THREAD

**Issue by darklinkpower** [JosefNemec/Playnite#3110]
### Bug Description

Updating CompletionStatus shows data change on Advanced tab

### To Reproduce

1. Select multiple games and open edit window
2. Change the Completion Status

### Diagnostics ID

😺

### Screenshots

![image](https://user-images.githubusercontent.com/1389286/192686798-0aaf3b8a-416d-4f8e-8622-5a02c24377db.png)

**Comment by JosefNemec** [comment]
Fixed by some 10.x update
