### ISSUE TITLE
[Feature request] Option to backup without pictures

### ISSUE THREAD

**Issue by Gerren** [JosefNemec/Playnite#3112]
### Feature description

I love the newly added option to backup the library. Unfortunately, my library backup takes over 50 seconds to do and results in 1,5 GB backup (singular).

IMO, the library itself is ridiculously small in comparison, but the images take the bulk of it. And the images are mostly replaceable (from store, metadata, …)

I'd love an option to select "Backup without images". I'd argue, that this should be the default option.

FYI, I do backup for a long time. I had a BIG oopsie once, was glad I had the backup.

Cheers,

Vašek

**Comment by JosefNemec** [comment]
There already is an option for it, disable "Game library media" on backup dialog.

![image](https://user-images.githubusercontent.com/3874087/192758473-ade855ca-0ab2-42be-877e-1ee4474e00e8.png)

**Comment by Gerren** [comment]
Hi, then I'm sorry for bothering you :) A tooltip maybe? :)
