### ISSUE TITLE
'Additional Filter' label should match filter state

### ISSUE THREAD

**Issue by cnapolit** [JosefNemec/Playnite#3113]
### Feature description

In Fullscreen mode when any filter settings are applied, the 'Additional Filter' label is visible. Since Fullscreen is primarily used via filter presets, this results in the message pretty much always displaying.

Instead, this label should only display when filter settings are applied on top of/in addition to the active filter preset.

### Screenshots
![Label in question](https://user-images.githubusercontent.com/94765074/193114396-46395790-ac49-4584-9dcc-f9992cedbd4c.png)

**Comment by JosefNemec** [comment]
Fixed in master.
