### ISSUE TITLE
Taskbar doesn't show up on Windows 11 with Desktop Application.

### ISSUE THREAD

**Issue by Kidaore** [JosefNemec/Playnite#3116]
### Bug Description

I have "automatically hide the taskbar" enabled on Windows 11, so it's always hidden unless I drag the cursor to the very bottom of the screen. Whenever I'm using the Desktop app for Playnite, the taskbar doesn't show up that way until I minimize the window.

### Diagnostics ID

64fa8351-fc2b-4626-8adc-4e70c53e44c3

**Comment by 0-Hex** [comment]
crow is gonna close this #1106
but just thought id mention since your on Win 11 this issue is resolved/mitigated by taskbar changes introduced in Windows 11 recent 22h2 update

**Comment by JosefNemec** [comment]
#1106
