### ISSUE TITLE
Windows blue «death» screen

### ISSUE THREAD

**Issue by jerrygreen** [JosefNemec/Playnite#3118]
### Bug Description

Within last couple days, I have encountered this infamous blue screen, while trying to open Playnite, TWICE. The last one was just now.

In overall, I must add, Playnite is very «overall buggy», - it simply takes so much time to open. While often it takes a couple seconds to start, sometimes it takes whole MINUTES.

The last time, after a few minutes of inability to start Playnite, I tried to end task via Task Manager, then tried to start it again: almost immediately, after a few sec, I got this blue screen.

### To Reproduce

I don't know how to reproduce it. I can only describe my overall use of Playnite:

- I have 111 games. 26 installed, 85 not installed
- I have 5 integrations: Steam, Epic, Ubisoft, BattleNET, Battlestate Games
- Among other custom add-ons, I have only installed one called «Ludusavi», to backup saves
- As a directory where to place my game saves, I chose iCloud Drive... On Windows, yes. I think there are chances it might be related, because I noticed that iCloud folder in explorer is sometimes messy and buggy, too. Might be unrelated though.

Well, that's basically all that might be beyond a standard use of Playnite. I don't use any sneaky themes or anything, everything is quite standard as much as it can be.

### Diagnostics ID

a3c8be7a-9ac5-4002-9a39-e9fd637bbc87

### Screenshots

![image](https://user-images.githubusercontent.com/13215662/193419998-b3585ac7-cedd-4481-aa84-ad4ad6fea4c8.png)

**Comment by JosefNemec** [comment]
There's nothing we do in Playnite that could possibly cause blue screens. So it's either some 3rd party app causing the issue or issue with your system.

I'm sorry if it sounds too blunt and straight forward, but Playnite simple doesn't operate in a way that could crash the whole system if the system itself is healthy.

**Comment by darklinkpower** [comment]
> In overall, I must add, Playnite is very «overall buggy», - it simply takes so much time to open. While often it takes a couple seconds to start, sometimes it takes whole MINUTES.

This is also specially weird, specially with a library THIS small.  It doesn't make sense that it sometimes takes seconds and sometimes minutes as Playnite doesn't randomly change how it loads, it's always the same so there can't be a BIG difference, even with Windows Caching considered. Also it should be considered that this is the ONLY case that anyone has reported this specific issue in all Playnite history and no one has described an issue with their library taking this long to open so I think this indicates it's an issue in your system. A quick Google search indicates that it could be a drivers issue/borked Windows installation.

**Comment by jerrygreen** [comment]
Well, if it's something in my system, I would probably get blue screens from a various reasons, by using other programs. The last time I got blue screen is when I had running Chrome with a couple services like iCloud+GoogleDrive, - and started Playnite.

I kinda suspect that it can be related to integration with iCloud, but can not know for sure. Also, I'm not really sure IN WHAT CASE Playnite takes minutes to start.

> Playnite doesn't randomly change how it loads, it's always the same so there can't be a BIG difference

Yes, but there's always area for unexpected bugs, right? Right.

I specifically didn't open the issue the first time when I got blue screen, but after second time I kinda sure that was because of Playnite:

> The last time, after a few minutes of inability to start Playnite, I tried to end task via Task Manager, then tried to start it again: almost immediately, after a few sec, I got this blue screen.

The first time was quite similar, though not that obvious, because as you said: it well might be because of whole variety of reasons, system problems etc., so I wasn't suspecting Playnite as hugely.

All I can suggest here is to wait a few week/months, until I get third and maybe fourth-fifth blue screens. To tell that it's not just obvious but statistically repetitive, to further increase the confidence that it is Playnite's doing.

**Comment by cnapolit** [comment]
Only a plugin dev & app user, but I have a 2k+ library with many plugins & themes installed.

During both plugin development (which has certainly caused chaos) and general use, load times have always completed within a couple seconds and I've never encountered a blue screen I could attribute to Playnite.

I agree with the others that this is very abnormal behavior.

**Comment by Tofuraven** [comment]
> All I can suggest here is to wait a few week/months, until I get third and maybe fourth-fifth blue screens. To tell that it's not just obvious but statistically repetitive, to further increase the confidence that it is Playnite's doing.

There's a difference between indirectly causing an error and being at fault for said error.
Even if the driver issue hinted at by the BSOD happens during the process of starting Playnite, chances are it's still an issue of your system itself rather than a bug in this application.
Statistical repetition without changing up anything just means that it's some part of your current setup (which should already be pretty clear) rather than Playnite, specifically. Narrowing down any differences in resource usage between Playnite and other applications you use - like instances of concurrent cloud access, or something - should help identifying the actual cause.

(One lead might in fact be said usage of iCloud, wouldn't be the first time it's connected to Blue Screens. You could try relocating your library - either to another cloud provider that's not Google Drive, or to a local drive - and see if another BSOD occurs at some point in the future.)

**Comment by jerrygreen** [comment]
> One lead might in fact be said usage of iCloud, wouldn't be the first time it's connected to Blue Screens

Yeah, that's what I suspect the most (and basically it's the only thing). Unfortunately it's not as easily reproducible, as most of the times Playnite takes ~5 sec from cold start (say, after system restart), and normally this bug doesn't appear.

I don't say it's only related to Playnite and nothing but Playnite. No. It's definitely on the verge of several systems/programs interacting with each other. An edge-case. 98% confidence it's iCloud, when Playnite's plugin trying to access game saves or something. Not quite reproducible, unfortunatelly. Happened to me 2-3 times this year, when starting Playnite. Never in the other cases from the moment I've installed my system (~2 years ago). I will post more details if I find something.

I guess I will close it as «not reproducible» for now. I will share details if I will find some more useful intel. Thanks for feedback.

**Comment by jerrygreen** [comment]
Happened to me again. It seems it only happens when I end process via Ctrl+Shift+Esc menu. Each time all the same:

1. Start Playnite
2. The process appears in Task Manager, but does not appear in taskbar
3. Wait a min or so, → see the program doesn't appear still (even logo)
4. Press <kbd>Ctrl+Shift+Esc</kbd> → end process `Playnite Desktop Application (32 bit)`
5. Start Playnite again
6. Looks like normal start at first, it knows it crashed so asks me if you wanna start with extension disabled or not
7. Choose extensions enabled
8. Wait roughly 20 sec, → it doesn't start
9. BSOD happens

![image](https://user-images.githubusercontent.com/13215662/206879018-3550c859-6bd2-4205-948c-078e6288a8ef.png)

It only happens when I start Playnite, cannot be any other reason why I'm getting BSOD. That's 100% certainty now.

How it does not start sometimes, and sometimes start without problems, → I don't know.

After BSOD, Playnite started without problems in under 2-3 sec, as normal.

From this time, I will try start Playnite with extensions disabled each time, to tell you if it's problems with extensions, like ludusavi, or just Playnite itself.

**Comment by JosefNemec** [comment]
`nvlddmkm.sys` driver that caused BSOD is nvidia's driver, so most likely GPU or GPU driver issue. As I mentioned before, there's basically nothing we can do from Playnite's code to cause GPU related BSOD, we don't have that kind of low level access. It just means that Playnite uses some rendering features that are not working properly on your system. I can't tell you what those would be specifically, since the actual image rendering is obfuscated from us via WPF (UI library we use), we have only very high level control over how GPU is actually used.
