### ISSUE TITLE
Crash on adding game

### ISSUE THREAD

**Issue by Marmourjmh1** [JosefNemec/Playnite#3119]
### Bug Description

Playnite will crash everytime I add a new game.

### To Reproduce

Automatically adding any game exe will cause a crash everytime.

### Diagnostics ID

545e02b5-5d4d-401d-a8a8-df008c48dce6

**Comment by JosefNemec** [comment]
Your library files are somehow corrupted. Please go to `%AppData%\Playnite\library` (put this exactly as is into file explorer) and attach .db files you find there, I'll try to repair them.

**Comment by Marmourjmh1** [comment]
Here is a zip file of what you requested!

I just want to say that I love your program and it is the only way I use my
steam deck! I truly appreciate you taking the time to troubleshoot!

-Joseph Fahmy

**Comment by JosefNemec** [comment]
I don't see any zip file attached to the post or link to it.

**Comment by JosefNemec** [comment]
Here's fixed file [games.zip](https://github.com/JosefNemec/Playnite/files/9698534/games.zip)

**Comment by Marmourjmh1** [comment]
Do I just replace my files or do I use restore library function?Also how do I prevent this from happening again.You are truly so kind for fixing this, I will be donating to your efforts!On Oct 3, 2022, at 10:53 AM, Josef Nemec ***@***.***> wrote:﻿
Here's fixed file games.zip

**Comment by JosefNemec** [comment]
Just manually replace that one file I uploaded.

I have no idea how that corruption happen so no idea how to prevent it in future I'm afraid.
