### ISSUE TITLE
LaunchBox as metadata provider

### ISSUE THREAD

**Issue by By6r9** [JosefNemec/Playnite#312]
Parse Metadata.xml in LaunchBox folder or:
http://gamesdb.launchbox-app.com/Metadata.zip (updated once a day)

**Comment by JosefNemec** [comment]
I don't think it's worth using. They don't share cover art images, which is one the main reasons you would use external metadata provider.

**Comment by JosefNemec** [comment]
I'm going to close this. They don't provide any media for games so it's not worth the effort.

If somebody would really like this then they will be able to create custom plugin once that's supported.
