### ISSUE TITLE
SDK method to retrieve games based on a cached filter without modifying the main view

### ISSUE THREAD

**Issue by cnapolit** [JosefNemec/Playnite#3122]
### Feature description

Currently, the only way to retrieve filtered games of a cached filter via the SDK generally follows the form of:
```C#
var someCachedFilter = GetCachedFilter();
var activeFilter = _playniteApi.MainView.GetCurrentFilterSettings();

 _playniteApi.MainView.ApplyFilterPreset(someCachedFilter);
var filteredGames = _playniteApi.MainView.FilteredGames;

_playniteApi.MainView.ApplyFilterPreset(new FilterPreset { Settings = activeFilter });
```
Retrieving filtered games this way has two side effects:
- The main view rapidly snaps between the two filters, causing unnecessary performance hiccups
- The selected game is set to the front of the list

Ideally, a method would exist that allowed plugins to retrieve this data without these side effects:
```C#
var someCachedFilter = GetCachedFilter();

var filteredGames = _playniteApi.Database.GetFilteredGames(someCachedFilter);
```

**Comment by cnapolit** [comment]
Thanks for the quick response!

The only difference between the old approach in the description and the new API method is sorting.
The old method respected the filter order while the API method returns titles in no particular order.

I realize I left out this desired outcome in my initial description, so I understand why that wasn't addressed.
I also peaked at the implementation of sorting, and it looks like the 'ListCollectionView' class handles the sorting behavior for the application, so obtaining filtered games through the database in order would be more complicated than adding a few calls.

The main reason I wanted to rely on the app for filtering/sorting when possible, aside from not re-inventing the wheel, was to maintain parity. If Playnite ever changes how it sorts or filters, then plugins can inherit that change instead of needing to change themselves to match.

If sorting seems out of scope, feel free to leave this closed.

**Comment by cnapolit** [comment]
@JosefNemec ping for visibility

**Comment by JosefNemec** [comment]
I'll look into it for P11.
