### ISSUE TITLE
Playnite not getting input focuse back after Game/Emulator was quit

### ISSUE THREAD

**Issue by Solitair69** [JosefNemec/Playnite#3124]
### Bug Description

not fully reproducable,
it seems like after certain emulators i think its especially when
the emulator takes more time to fully quit or something like that
Playnite pobs back up but doenst have input focus.

### Diagnostics ID

e6da7ce3-4429-4ced-a402-fd31de84feb7

**Comment by JosefNemec** [comment]
Should be fixed by a workaround in one of the 10.x updates (I forgot which one). Somebody confirmed on Discord that it's no longer happening.
