### ISSUE TITLE
In-Game Playnite Overlay

### ISSUE THREAD

**Issue by ZazaMastro** [JosefNemec/Playnite#3130]
### Feature description

It would be great to have an in-game overlay through which you can view the information of the current game, have access to the basic options of quit, pause/resume, shutdown/restart/suspend the system. It would be very interesting if it could have themes and if it could be compatible with extensions so that it could be enriched and improved with time thanks to users. It would be the definitive consecration and completion of Playnite as a platform for gaming with gamepad.

**Comment by JosefNemec** [comment]
#1390

**Comment by ZazaMastro** [comment]
Why the request was closed already?

**Comment by JosefNemec** [comment]
duplicate

**Comment by ZazaMastro** [comment]
Oh sorry, I didn't noticed that! 😅
