### ISSUE TITLE
我无法同步我的游戏平台

### ISSUE THREAD

**Issue by xiaomaimai21** [JosefNemec/Playnite#3134]
### Bug Description

第一次进入时勾选了平台  但我未收到任何登录请求  进入后发现里面没有任何游戏  但我的有些有些未下载所以无法手动同步

### To Reproduce

下载  playnite  安装playnite   勾选游戏平台  进入playnite   没有任何游戏

### Diagnostics ID

no

**Comment by JosefNemec** [comment]
Please use English only, I don't speak Chinese.
