### ISSUE TITLE
Consistent "Install size scan error" messages

### ISSUE THREAD

**Issue by Mellified** [JosefNemec/Playnite#3135]
### Bug Description

After updating the game libraries, Playnite 10 shows a notification of an install size error. It's not clear why, as Explorer can navigate to the path successfully. Best guess it is related to the path length, which is over 256 characters. Since Windows 10 the path limit can be disabled via the registry, which I have done.

### To Reproduce

Install a game with a very long path length (?)

### Diagnostics ID

0

### Screenshots

![image](https://user-images.githubusercontent.com/81110968/195910809-ad89a445-a157-4839-a58d-291d6255156d.png)

**Comment by JosefNemec** [comment]
Attach diagnostics ID that was requested in issue template.

**Comment by Mellified** [comment]
Unfortunately Playnite is consistently failing to upload the diag package, which is why the ID is not included.

**Comment by Mellified** [comment]
Diag package and log attached.
[diag.zip](https://github.com/JosefNemec/Playnite/files/9789060/diag.zip)
[playnite.log](https://github.com/JosefNemec/Playnite/files/9789063/playnite.log)
