### ISSUE TITLE
Incomplete setup now I can't open Playnite

### ISSUE THREAD

**Issue by jjwhitfield** [JosefNemec/Playnite#3139]
### Bug Description

Hi,

So, I accidentally shut down my system in the middle of setting up Playnite and now I can't restart the process from the beginning or open the software - safe mode or otherwise. I just get the same message every time:

> "Playnite closed unexpectedly while starting. This is usually caused by 3rd party theme or extension. Do you want to start in safe mode with all 3rd party add-ons disabled?"

I've tried uninstalling and reinstalling several times, running as an admin, running in fullscreen, deleting temp files, editing my registry but the problem persists.

I've added my Playnite log below as well as some screenshots in case that's helpful.

[playnite.log](https://github.com/JosefNemec/Playnite/files/9816472/playnite.log)

### Diagnostics ID

Playnite closed unexpectedly while starting.

### Screenshots

![Screenshot 2022-10-18 231606](https://user-images.githubusercontent.com/20615332/196589492-9ab9c7f4-a098-40b4-a729-5e64ee92f664.png)
![Screenshot 2022-10-18 231745](https://user-images.githubusercontent.com/20615332/196589508-3cc2d063-7550-46e1-9d7e-37532b095e4b.png)

**Comment by JosefNemec** [comment]
Try deleting `%appdata%\playnite\` folder (put it into file explorer exactly as written).

**Comment by jjwhitfield** [comment]
No luck. Still having the same problem.

**Comment by JosefNemec** [comment]
Install portable instance to a different folder and try that. But if deleting that appdata folder didn't help, then it's most likely not an issue in Playnite.

**Comment by JosefNemec** [comment]
I tried to replicate this somehow and I can get startup error once after killing first time startup wizard, but then Playnite continues to work properly. So no idea what to do about this.

**Comment by JosefNemec** [comment]
Can't replicate so closing for now. If you find a way how to reliably reproduce it, let me know.
