### ISSUE TITLE
Origin being phased out in favour of 'EA App'

### ISSUE THREAD

**Issue by chocolatechipcats** [JosefNemec/Playnite#3140]
### Feature description

On PC at least, Origin is now being deprecated in favour of the EA App. Hopefully it won't break anything.

https://www.ea.com/news/ea-app

**Comment by darklinkpower** [comment]
Incorrect repository as indicated in the issue template

![image](https://user-images.githubusercontent.com/1389286/196815838-50d73d09-c267-4874-8d0d-fb403e4de106.png)

An update that supports that new app was released today https://github.com/JosefNemec/PlayniteExtensions/issues/13#issuecomment-1284001169

**Comment by chocolatechipcats** [comment]
Ok thanks. I just saw that update now. :)
