### ISSUE TITLE
Add M64Py or mupen64plus (it's not m64p bc it's not working)

### ISSUE THREAD

**Issue by IamNotHeree** [JosefNemec/Playnite#3143]
### Feature description

I want the m64py emulator to be added, it's not the same as m64p because when I choose m64p and select the m64py installation directory and save. When I want to turn on the n64 game I can not. M64p emulator is already transformed into simple64.

**Comment by JosefNemec** [comment]
From the looks of it M64Py is a frontend for mupen64plus. I don't think it makes sense adding *emulator* profile support a frontend. You will have to import and configure it [manually](https://playnite.link/docs/master/manual/emulators.html).

**Comment by JosefNemec** [comment]
Done in master.
