### ISSUE TITLE
Playnite keeps deleting EBOOT.BIN when I boot PS3 game

### ISSUE THREAD

**Issue by Stickend** [JosefNemec/Playnite#3144]
### Bug Description

Hello, this started to happen yesterday out of no reason.

I was playing Silent Hill: Downpour pretty good these days, but when I was going to check it last time, it says there's no EBOOT.BIN file to start with. I looked at it and saw it was true, so I copied again the same EBOOT.BIN.

Since then, every time I open the game through Playnite, it deletes the archive, preventing me from playing it again (unless I Copy again the archive and then it happens the same again, and again, and again...)

I didn't do anything out of the ordinary to make this happen, it just happened out of nothing.

I checked with other games which never gave me problems, like Tekken Tag Tournament 2, and it's now suffering exactly from the same fate.

What it's happening here? What's the solution to this?

Also, these two games are in Disc Format. I have another game, Sly Trilogy in Disc Format, but this game perfectly runs fine without Playnite deleting its EBOOT.BIN, which makes things even weirder.

### Diagnostics ID

61b2f5ce-a2fc-4b7b-a5f0-0df9f2699270

**Comment by JosefNemec** [comment]
Playnite never deletes any game files, there simply isn't any code that could do it. It's either the emulator itself or some other app doing it.

**Comment by Stickend** [comment]
But if I open the game through the emulator, it does it fine, and the EBOOT.BIN doesn't dissapears.

What I don't understand it's why this happened just suddenly, because I really didn't touch anything there.

What can I do to fix it?

**Comment by Stickend** [comment]
I made a video so you can see by yourself.

[https://drive.google.com/file/d/1wJFprz8M3_dh_NearbOj6i9_REWdfYhr/view?usp=sharing](url)

**Comment by JosefNemec** [comment]
I honestly have no idea. It's especially weird if you say that it only happens with one game, but I'm pretty sure it's not Playnite itself doing it. At least not any default functionality, I don't know if you have some custom scripts/extensions set somewhere.

As far as "it doesn't happen when launcher from the emulator", it might be a bug in RPCS3's cmdline support, see https://playnite.link/docs/master/manual/emulators.html#game-runs-properly-when-launched-manually-from-an-emulator-but-not-from-playnite

You can also try running Process Monitor to see what process deletes the file https://learn.microsoft.com/en-us/sysinternals/downloads/procmon

**Comment by Stickend** [comment]
Have you checked the video? 

I don't have any script/extension installed more than was already there.

I read the article you sent, and it says "If the issue is in built-in emulator profile using wrong arguments, please open [new issue](https://github.com/JosefNemec/Playnite/issues/) in Playnite's repository for the profile to be updated", so that's why I'm here.

And I've never tried Process Monitor before, I ill see if i can get it to work.

**Comment by JosefNemec** [comment]
I can't check the video, it's not accessible.

Please read the entire topic on cmdline startup issues. Try running `rpcs3.exe` manually from cmdline with `"D:\Juegos PS3\Emulador RPCS3\rpcs3-v0.0.22-13821-7842812e_win64\dev_hdd0\disc\BLES01446 - Silent Hill Downpour\PS3_GAME\USRDIR\EBOOT.BIN"` argument to see if it happens as well. If it does, it's an issue with the emulator.

**Comment by JosefNemec** [comment]
Also as far as `"If the issue is in built-in emulator profile using wrong arguments, please open [new issue](https://github.com/JosefNemec/Playnite/issues/) in Playnite's repository for the profile to be updated"` the important part is: `using wrong arguments`, which imo isn't this case.

**Comment by Stickend** [comment]
I uploaded the video to Mega: https://mega.nz/file/luAQQara#vL-ykvVq8_g1ybXBdM6IV0V8u9UaeyRm58hpF-Yq5WA

And I'm afraid I'm not sure how to run rpcs3.exe from a cmdline :(

**Comment by JosefNemec** [comment]
The documentation page I linked links to a website that shows how to use them: https://www.bleepingcomputer.com/tutorials/understanding-command-line-arguments-and-how-to-use-them/

**Comment by JosefNemec** [comment]
I checked the video an it shows the file being deleted after Playnite started emulator process, which imo points to the issues being really RPCS 3 (or some other app on your system, maybe antivirus or something). Once Playnite starts the emulator, it doesn't do anything with game files, it just tracks emulator process to check if a game is still running or not.

**Comment by Stickend** [comment]
I checked with cmdline and still it happens the same. So this is an emulator problem, then? What should I do? Just reinstall emulator?

**Comment by JosefNemec** [comment]
Yes it's either emulator or some other app on your system. I recommend contacting emulator's developers.

**Comment by Stickend** [comment]
Okay, thank you for your help and patience!
