### ISSUE TITLE
UriHandler doesn't parse arguments properly

### ISSUE THREAD

**Issue by HerrKnarz** [JosefNemec/Playnite#3153]
### Bug Description

I already reported it on discord some days ago, but figured I add it here as well so it won't get lost.

I tried to use the UriHandler in my extension, but it seems the arguments aren't parsed like they should (as already checked by crow).

I wanted to use the following link:

playnite://linkutilities/AddLink/https%3A%2F%2Fxyz.de%2Fabc/Test

That should be parsed into three arguments: "AddLink", "https%3A%2F%2Fxyz.de%2Fabc" and "Test". Unfortunately it's seems to decode the url in the second argument and I get "AddLink", "https:", "xyz.de", "abc" and "Test".

I also tried it this way with the same result:

playnite://linkutilities/AddLink/https###xyz.de###abc/Test

The funny thing is, that I still get "http:" as a second argument, although I left out the colon in the link.

### Diagnostics ID

c8cc838f-942e-43ae-a158-949f7d6704a3

**Comment by JosefNemec** [comment]
Already fixed in master via 6d18d14995096df4d4a4e57e2d07609f5daa94eam will be in 10.4 update.
