### ISSUE TITLE
delete pre-existing profile in playnite

### ISSUE THREAD

**Issue by AAide** [JosefNemec/Playnite#3159]
### Feature description

How did it? it is easy to add pre-existing profiles, to facilitate the import of games by emulator, but I find nowhere where I could delete pre-existing profiles

**Comment by JosefNemec** [comment]
You can delete assigned built-in profiles the same way as custom ones:
![image](https://user-images.githubusercontent.com/3874087/202895976-97c2966c-1a07-4bdc-a59a-d5fdec2d94f7.png)
