### ISSUE TITLE
Cannot search through library?

### ISSUE THREAD

**Issue by N0keya** [JosefNemec/Playnite#316]
Why am I not able to search through my library, like I type something and click enter and just nothing happens, I dont know if im missing something but I dont know how to.

**Comment by JosefNemec** [comment]
Do you mean by using filter panel or main search bar? It should automatically search after you stop writing.

**Comment by N0keya** [comment]
The main search bar, I type something in and I have waited, and even clicked enter but nothing is appearing, as in the game I am searching for doesnt come up.

**Comment by JosefNemec** [comment]
Can you please go to "About" menu, create diagnostics package and attach it here? Thank you

**Comment by N0keya** [comment]
[diagnostics package.zip](https://github.com/JosefNemec/Playnite/files/1569159/diagnostics.package.zip)

**Comment by JosefNemec** [comment]
I see some errors in your logs, I'll look into it. In the mean time just restarting Playnite should fix it (you may have to close the tray icon otherwise it will just get minimized when closing main window).

**Comment by N0keya** [comment]
ah yes that did fix it. I had tried closing it beforehand but it was still open like you said, but I literally just installed it not long ago so I didn't expect some issues. Thanks for the help!

**Comment by JosefNemec** [comment]
Released in 3.2
