### ISSUE TITLE
gta game

### ISSUE THREAD

**Issue by MoChadli96** [JosefNemec/Playnite#3160]
### Feature description

How to add games to custom menus in filters. For example, several multiplayer games will appear if I select the multiplayer option in the filter. I choose a single player and several single-player games appeared. I wish I could customize the categories to give the game a good menu. How do you do it?
![2](https://user-images.githubusercontent.com/118173306/201633800-3b694ab4-648e-4030-a5bd-ac1e4b90a7ab.png)
![1](https://user-images.githubusercontent.com/118173306/201633846-15eb8699-a98a-4c12-8abe-4f2513c78fd2.png)

### Screenshots

![2](https://user-images.githubusercontent.com/118173306/201633505-4d8ea7d6-a9ef-4ef0-9d48-fd32b7f2c444.png)
![1](https://user-images.githubusercontent.com/118173306/201633518-15edbf08-86d8-41eb-90f0-ecb41a585d1b.png)

**Comment by JosefNemec** [comment]
You don't add games to filter presets. Filter presets only hold and set filter panel settings, so set up you filters and game fields in a way that it shows only desired games and then save filter preset.

For example, if you want filter preset for multiplayer games, set filter to show only multiplayer games (based on tag, feature or whatever field you are using for that) and that make sure multiplayer games have multiplayer fields set, then save filter preset.
