### ISSUE TITLE
Expanding string with {EmulatorDir} variable removes it without expanding it

### ISSUE THREAD

**Issue by darklinkpower** [JosefNemec/Playnite#3161]
### Bug Description

Expanding string with {EmulatorDir} variable removes it without expanding it

In my opinion there are two options:

- Leave the string as is without modifying not expanded variable
- Preferably, allow to give an emulator Id and expand the variable in the method, as it's currently not possible

### To Reproduce

Expand string with `ExpandGameVariables` Api method

### Diagnostics ID

😶

### Screenshots

Before expanding:

![image](https://user-images.githubusercontent.com/1389286/201803182-ed31dc2d-fd8b-4c6d-814c-93ce92229cdd.png)

After expanding:

![image](https://user-images.githubusercontent.com/1389286/201803230-468c5a89-a826-4b78-ba77-8680d50ca709.png)

**Comment by JosefNemec** [comment]
I added function overload that takes extra argument for expanding that variable.
