### ISSUE TITLE
Menu Desync during Remote Streaming

### ISSUE THREAD

**Issue by allhailshake** [JosefNemec/Playnite#3163]
### Bug Description

Any interaction with the either the top menu, game options menu, or main Playnite menu through remote play causes a desynchronization by exactly one input. This resolves after returning to the library and never occurs while scrolling through the library. This also does not occur when using the Playnite menu at the host pc. 

Using Moonlight client on Samsung S20 FE to stream Playnite Fullscreen app via Sunshine Gamestream host.  

### Diagnostics ID

ba729658-8eff-4199-a3f3-b669467129ed

**Comment by JosefNemec** [comment]
We have virtually zero control over graphics rendering and input processing while Playnite is being streamed. It's either an issue in WPF (UI library we use, which is now more or less in a maintenance mode) or issue with Moonlight. There's nothing I can do about this.

**Comment by allhailshake** [comment]
I just noticed that this does not occur while the library is updating, either when Playnite is launched or when done manually.
