### ISSUE TITLE
Unselect filter preset in explorer panel if filtering parameters no longer match the filter preset

### ISSUE THREAD

**Issue by XenorPLxx** [JosefNemec/Playnite#3165]
### Feature description

When there's a filter preset selected in the explorer panel, and then sorting/grouping/filtering changes (so it doesn't match the filter preset anymore), is it possible to unselect the filter preset (in the explorer panel), so it can be re-applied just by clicking it? 

Currently, the user needs to click a different filter preset and then click the one originally selected to reset the filtering (and grouping/sorting) parameters if applied.

Could go a bit further and automatically mark a different preset if filtering parameters match, but IMO that's not required.

My use case:
I have an 'All' filter preset that I use the most, and often I filter the game list by extra parameters using 'All' as a starting point. Then to quickly reset to my 'All' filter preset, I need to choose a different preset in explorer panel and then click back 'All' preset.

**Comment by JosefNemec** [comment]
#2712
