### ISSUE TITLE
Save the dimensions of the settings dialogs

### ISSUE THREAD

**Issue by HerrKnarz** [JosefNemec/Playnite#3167]
### Feature description

I often resize the settings dialogs (both standard and add-on settings), so I don't have to scroll through some of the tabs. Unfortunately after closing and reopening the dialogs, they are back to their default dimensions. It would be great, if the dimensions could automatically be saved after resizing and loaded again on opening the dialogs. Should hopefully be simple to accomplish and would be a huge gain in comfort.

**Comment by JosefNemec** [comment]
Done in 10.30

**Comment by HerrKnarz** [comment]
Unfortunately the fix only works for the position of the settings/addon-dialogs, but the dimensions are still back to default after reopening them. I just tested it in version 10.31.
