### ISSUE TITLE
Playnite is not restoring original Display Resolution upon exit

### ISSUE THREAD

**Issue by GingerBobRoss** [JosefNemec/Playnite#3168]
### Bug Description

Using Playnite 10.7 |Moonlight | Windows 10
I tried searching for this issue and i appologize if i missed seeing this within open/closed results.

I am having an issue when closing playnite, my desktop resolution does not go back to its default (3440x1440)
I checked gamestream_playnite.ini and everything looks correct.
The python windows running in the background reports the below when Playnite is active:
Switching resolution to 1280x800
Minimizing windows
Starting game launcher
Focusing Playnite
Watching for launcher window to close

But when i quite my game and exit playnite through both Moonlight and just native on the desktop without any remote app  running, Playnite will close along with the python script running through CMD, but the resolution will not restore.

### To Reproduce

Launch playnite through one of the gamestream configure bat files.
close out of playnite

### Diagnostics ID

e7892db6-959f-4951-8df6-22b28c932d7a

**Comment by JosefNemec** [comment]
It's some issue with your resolution switching setup, Playnite doesn't interact with display resolution at all, it always runs in windowed mode only and doesn't change display resolution.

**Comment by GingerBobRoss** [comment]
I made a mistake, I thought i posted this on gamestream_launchpad git
