### ISSUE TITLE
"Open Installation Location" will open a same name shortcut in the parent directory.

### ISSUE THREAD

**Issue by AmeliaZ** [JosefNemec/Playnite#3169]
### Bug Description

"Open Installation Location" will open a same name shortcut in the parent directory.
Click "Installation Location" in the game details also do this.

Manually add `\` after the "Installation Folder" in "Edit Game Details" will resolve the issue.

### To Reproduce

Create a shortcut in the parent directory of InstallDir, rename it to the same name as the InstallDir.

### Diagnostics ID

f9362525-4512-417e-8af7-20c87ed0b253

**Comment by JosefNemec** [comment]
Fixed in 10.8 update
