### ISSUE TITLE
Wii U game name by folder- instead of filename

### ISSUE THREAD

**Issue by lixxbox** [JosefNemec/Playnite#317]
Would it be possible to use the folder name containing the „\code\*.rpx“ file for recognizing game names while importing them? The filename of the rpx files aren‘t useful for that, because they are pretty random.

Popular Tool "Wii U USB Helper" saves games like this: "\THE LEGEND OF ZELDA The Wind Waker HD [BCZP01]\code\cking.rpx" including the GameID BCZP01.
Playnite suggests "cking" as name, instead of "THE LEGEND OF ZELDA The Wind Waker HD".

**Comment by JosefNemec** [comment]
This will have to be done by specific emulator plugin once #653 is implemented, it won't be supported by Playnite directly.
