### ISSUE TITLE
Launching from GOG Galaxy sometimes doesn't focus on game screen

### ISSUE THREAD

**Issue by cutecycle** [JosefNemec/Playnite#3176]
### Bug Description

Not sure if this is the right place, but:

often when launching GOG games from Playnite, the game won't focus.

### To Reproduce

* Enable GOG integration.
* Enable "Launch from GOG Galaxy".
* Launch a game:
* In this example, it's happened with (will update over time):
  * Gamedec
  * Star Renegades
  * Clustertruck (understandably; this has the old school Unity thing of popping up a graphics settings dialog on startup)

The game will be behind the launcher and you'll have to click the icon in the taskbar to switch to it.

I imagine this may be a hard problem given all the caveats about forking and what the "main" process of a game even is, but I'm wondering if it's something that makes sense to attempt to resolve.

### Diagnostics ID

4a06425f-3070-4e17-98cd-00fa1e571664

**Comment by JosefNemec** [comment]
Nothing we can do about it, Galaxy is fully in control of how a game is started. The only interaction Playnite (GOG plugin specifically) is doing with a game is checking if game's process is still running for play time tracking purposes.

**Comment by cutecycle** [comment]
What if the the plugin were to traverse the process tree/WMI objects to find what `GalaxyClient` started, and switch focus to its window handel?

![image](https://user-images.githubusercontent.com/12169942/203870634-9d3f3ea9-841f-4aa0-8691-ac1adab894a4.png)
![image](https://user-images.githubusercontent.com/12169942/203870715-a9471a1b-e066-4a98-a4c6-1c93cefb131e.png)

**Comment by cutecycle** [comment]
if we can reference the win32 assemblies, we could do the C# equivalent of:


```powershell
 Add-Type @"
    using System;
    using System.Runtime.InteropServices;
    public class WinAp {
      [DllImport("user32.dll")]
      [return: MarshalAs(UnmanagedType.Bool)]
      public static extern bool SetForegroundWindow(IntPtr hWnd);

      [DllImport("user32.dll")]
      [return: MarshalAs(UnmanagedType.Bool)]
      public static extern bool ShowWindow(IntPtr hWnd, int nCmdShow);
    }
"@
 $ys=(get-process | where {$_.Parent -match "galaxyclient" -and $_.ProcessName -notmatch "galaxy"}).MainWindowHandle
[WinAp]::SetForegroundWindow($ys)
[WinAp]::ShowWindow($ys,3)
```


(taken from https://stackoverflow.com/questions/42566799/how-to-bring-focus-to-window-by-process-name)

**Comment by JosefNemec** [comment]
I'm not comfortable with interacting with game's window, because we have no idea what's actually happening with the game and it could potentially lead to other issues. If the issue happens only to some games for you, then I recommend using game script on those specific games to refocus them.

**Comment by cutecycle** [comment]
understandable.

though for clarification, I want to say:


* This isn't "specific games", it's most games; the specific ones are recent examples, and the solution is highly generalizable
* it's not "for me"; it's for anyone who is trying to use a controller-only setup with Galaxy.
* It's not interacting with the window; just making an attempt to focus it.

**Comment by JosefNemec** [comment]
Can  you check if you don't have some other app on your system that might be causing the issue? I tried to reproduce it with couple random GOG games (different ones to what you mentioned since I don't own those) and they all started in foreground for me. I don't really know what app might be causing it, maybe some window manager?
