### ISSUE TITLE
Disabling Updating Metadata on games???

### ISSUE THREAD

**Issue by trymeouteh** [JosefNemec/Playnite#3179]
### Feature description

Not a feature request. I do not have discord and do not use discord for privacy reasons.

Not sure if Playnite will download/update metadata such as images and other info on a game in my library automatically. If this is the case, how do I disable this?

I like to manually add images and metadata info to my games, I like to manually add each game and set the images and metadata to my liking, and not have it automated.

Is there a setting I need to change? Is there a setting I DO NOT want to turn on?

Thanks

**Comment by Jeshibu** [comment]
Uncheck everything under main menu > Settings > Metadata

**Comment by trymeouteh** [comment]
What about the settings under main menu > Settings > Updates

**Comment by JosefNemec** [comment]
settings - general - download metadata after importing games
