### ISSUE TITLE
More Groups

### ISSUE THREAD

**Issue by iagocanalejas** [JosefNemec/Playnite#318]
Allow Grouping by Genre or Developed by

**Comment by JosefNemec** [comment]
Related to #305

**Comment by Evene174** [comment]
It would be cool if the user could choose a sequence of genres.
For example, someone most often plays in RPG, but in the alphabet "r" is closer to the end of the list.

**Comment by kkjdroid** [comment]
Per series would also be helpful.

**Comment by JosefNemec** [comment]
Done in 5.0
