### ISSUE TITLE
Rounded Corners Missing on Windows 11

### ISSUE THREAD

**Issue by pbinspanish** [JosefNemec/Playnite#3182]
### Bug Description

On Windows 11, rounded corners are missing from the Playnite window. Microsoft documentation for rounded corners: https://learn.microsoft.com/en-us/windows/apps/desktop/modernize/apply-rounded-corners

### Diagnostics ID

4c62a962-1eec-4887-8560-bd701d845976

### Screenshots

![Playnite Rounded Corners Missing](https://user-images.githubusercontent.com/27387436/204071245-af39b58e-9ae2-4d1a-a562-12b50d49fee5.png)

**Comment by Teemsploit2** [comment]
i think thats intentional

**Comment by JosefNemec** [comment]
It's not intentional. UI library we currently use doesn't support Mika borders if you have custom window decorations in use, unless you take some extra steps, which break some other things at the moment (in relation to child windows).

The same goes for snap layout support.

**Comment by JosefNemec** [comment]
Closing as this is currently not properly supported by UI framework we are using (they are working on it but no EA). It would have to be faked by a theme.
