### ISSUE TITLE
Restore backup without overwritting current library data

### ISSUE THREAD

**Issue by trymeouteh** [JosefNemec/Playnite#3185]
### Feature description

The backup and restore feature is incredible, thank you

When you have content in your library and you go to restore your library with another backup, it will delete all of the content in your library and add the content from the backup your restoring.

I would like to suggest adding a feature which will import a backup but this backup will not overwrite any content in the library that the backup includes. For example if your library has the following games...

```
Call Of Duty: Modern Warfare 2
Skyrim
```

And this backup you want to import includes the following games...

```
Call Of Duty: Modern Warfare 3
Skyrim
```

Once you import this backup, this will be the games in your library

```
Call Of Duty: Modern Warfare 2
Call Of Duty: Modern Warfare 3
Skyrim
```

Skyrim will not be overwritten, whatever data the game ID for Skyrim has in the backup will not be imported since the library already contained Skyrim.

This would be useful for merging two backups into your library.

**Comment by JosefNemec** [comment]
I'm afraid that goes against how backups should work in general in any app, in my opinion. They should restore to exact state that was created during the backup.

**Comment by trymeouteh** [comment]
Closing since I found a way to achieve what I wanted without this feature.
