### ISSUE TITLE
Trailer videos small instead of fullscreen

### ISSUE THREAD

**Issue by DiegoMCHB** [JosefNemec/Playnite#3186]
### Feature description

Hello Josef

First of all, let me just personally thank you for creating such a cool, immersive, seamless and amazing theme for Playnite, it really is my go-to-choice above every other, and I find it absolutely mesmerizing. your work truly deserves recognition, if there is a Patreon page or any way I can buy you a coffee or something, please do let me know and count me in! such amazing work should not go unrewarded.

I don´t know if this counts as a new feature or if it´s just a matter of tweaking the code or something (spoiler: I have absolutely zero experience, lol) but I did find a video of your amazing theme (https://www.youtube.com/watch?v=DFMn2Fxm9Aw Stamp: 0:16) where a little trailer video could be seen playing on the top corner of the screen whenever you chose a game on the Fullscreen version of the theme. I found that really cool, however I have no idea how to implement such a feature on my version of your theme, a trailer does start if you enable such feature, but it hogs the whole screen and it´s not as cool and elegant as a small video playing, kinda like the Xbox Store does it, and my top wish is to copy that style and implement it on my own.

I wish this suggestion finds you in the mood to educate such an entry level user user like me on how to implement such a cool feature on my version of the theme, and please, if you find the time, don´t forget to reply to this with a link to your Patreon or anything similar where I can thank you properly for your amazing work.

Best in all your future endeavours!

Diego Cabrera, writing you from Mexico!

**Comment by JosefNemec** [comment]
Hi, I personally don't have any idea how specific themes implement it. I recommend downloading them and checking in their xaml files. You will most likely also need some extra plugin like Extra Metadata Loader.

I also recommend joining our Discord server, because that's where most of the discussion about theme development happens. The person that made the theme you linked can be found there as well.
