### ISSUE TITLE
BUG!!??

### ISSUE THREAD

**Issue by Arquivista** [JosefNemec/Playnite#3191]
### Bug Description

Hello, with the last update if you try to open the game location when the folder does not exist it simply opens the documents, before the update it did not open anything.
Is this normal or is this unexpected behavior?

### Diagnostics ID

666666666

### Screenshots

https://user-images.githubusercontent.com/30628523/205405706-75c028ab-a2a3-4eb2-84c7-15f2495290a5.mp4

**Comment by Arquivista** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/30628523/205406625-517b2927-558e-4281-a9d6-1334d3f870eb.jpg)

**Comment by JosefNemec** [comment]
Expected behavior, we now just tell explorer to open specific folder and then it's up to explorer what it does about non-existent folders.
