### ISSUE TITLE
Unable To Install Metadata Source

### ISSUE THREAD

**Issue by ayush-dbl** [JosefNemec/Playnite#3194]
### Bug Description

Updated to the latest version but unable to install metadata sources.
The same issue occurs while downloading the metadata from the website.

### Diagnostics ID

e151968f-92b0-4094-8bfe-538f73ac9103

### Screenshots

![image](https://user-images.githubusercontent.com/48304377/205500236-b96e8717-03eb-43b6-82a3-136a23009937.png)

**Comment by JosefNemec** [comment]
It's a network issue on your side: `System.Net.WebException: Unable to connect to the remote server` (server is definitely up and running).

https://github.com/JosefNemec/Playnite/wiki/Known-Issues#connectivity-issues
