### ISSUE TITLE
Software Tools window clears fields after creating new entry without existing entries

### ISSUE THREAD

**Issue by CanRanBan** [JosefNemec/Playnite#3195]
### Bug Description

Software tools window clears input fields if no entry on the left exists and the user creates one with the `Add` button.

If no entries exist either the input fields should be disabled until the user creates an entry or the content of the fields should be used for the newly created entry. Otherwise users using the software tools window for the first time will most likely face the issue for losing their input data and having to do it again.

Currently only the `Select Icon` and `Remove` buttons used for Icons are disabled. The text fields are all enabled.

### To Reproduce

1. Open Software Tools
2. Have an empty list on the left
3. Input data into at least one field
4. Click on `Add` and create a new entry
5. Fields on the right will be cleared (all fields except Name) or replaced (Name field)

### Diagnostics ID

-

### Screenshots

Before clicking on `Add`:
![grafik](https://user-images.githubusercontent.com/24878047/205512073-0f09879c-3c9a-4a0f-a96f-dbad6fcf171c.png)
After clicking on `Add` creating a new entry:
![grafik](https://user-images.githubusercontent.com/24878047/205512488-93bad905-e126-4d41-ac9b-988f3dcfd51d.png)

**Comment by JosefNemec** [comment]
Fixed in master
