### ISSUE TITLE
Old games imported using "Scan Automatically".

### ISSUE THREAD

**Issue by tfuGhost** [JosefNemec/Playnite#3196]
### Bug Description

Games added using "Scan Automatically" beginning at atleast September, and going further back, were missing one piece of information. Or atleast they are missing that piece of information now. As new games that are added have it. "{installdir}\\". See photos, Photo number 1 is how an old game looks, Photo number 2 is how a new game looks. 

Some games launched using the lines from Photo 1 do not launch correctly. The ways in which it interacts with games varies wildly. Either failing to launch and crashing, launching but getting stuck, and launching with glitches. I have linked a video showing an example of a game launching with glitches. You can see that the game with the glitches doesn't load dgVooDoo2 or ReShade. Although, if I remove dgVooDoo2, the exact same errors persist. Something stops dgVooDoo from even activating, as well as causing crashes and glitches.

https://youtu.be/rB50iiJkb90

I could find no other game that acts in the same way as my Custom Tomb Raider games. Neither as old or as modern. Everything launches exactly as its supposed to. The games I am testing were added around the same time as the Custom Tomb Raider games and were using the same method (Scan Automatically). 

I can provide logs if necessary, I just can't remember the proper way to do so within Playnite. I am sorry, you'll have to tell me. 

### To Reproduce

Download a Custom Tomb Raider game:
[https://www.trle.net/sc/levelfeatures.php?lid=621](url). Thats the one I was testing in the video.
Add it to Playnite using Scan Automatically. Edit the actions folder to look like Photo 1, by removing {installdir}\\
Launch the game. 

It might present you with a Setup box. Just make sure you set the resolution to a 32bit option. 

### Diagnostics ID

233eb561-951e-456d-a9b6-f4f37e33db29

### Screenshots

![Untitled 1](https://user-images.githubusercontent.com/66293566/205597051-87c20b33-b7aa-4fbb-aeff-9c6292393fad.png)
Photo 1

![Untitled 2](https://user-images.githubusercontent.com/66293566/205597165-374de14d-89d2-4014-8745-e8ba2172ca98.png)
Photo 2

**Comment by JosefNemec** [comment]
I tried it with Disciples 2 and Divine Divinity. dgVoodoo is loaded properly when play action is configured in either way you showed on those screenshots. I'm using Playnite 10.8 and dgVoodoo 2.75

**Comment by tfuGhost** [comment]
I am aware that it is only affecting Custom Tomb Raider games. But I still don't know why. Watch the video. All I did between the game working, and being broken, was add {installdir}\\. Something that no other game seems to care about.

**Comment by JosefNemec** [comment]
I'm afraid you will have to contact game's/mod's developers, it's simply an issue with the game and nothing we can fix.

**Comment by tfuGhost** [comment]
I still don't know how changing a line in the way Playnite executes a game, can completely corrupt a game that works perfectly fine without it, and it not be something wrong with Playnite. Especially because Prior to around 2-3 months ago, the games launched perfectly fine the way they were. 
But its your program. And you're the expert. Consider the ticket closed. Sorry for wasting your time.

**Comment by JosefNemec** [comment]
It means the game doesn't handle properly being started in a specific process environment. The only thing Playnite does in regards to interaction with game's process is starting it in a specific way (the way you configure in play action settings) and then it's up to the game how it runs. Playnite no longer interacts with the game in any way other than checking if it's still running.

Also as I mentioned in the original reddit thread, we haven't changed anything related to game startup in a very long time (if I remember correctly), so it's more likely that something on your system changed or the game itself changed if you are saying that it used to work properly.
