### ISSUE TITLE
Ryujinx Emulator Avalonia

### ISSUE THREAD

**Issue by stryxz1** [JosefNemec/Playnite#3198]
### Bug Description

playnite does not detect ryujinx avalonia build

### Diagnostics ID

761fc464-3bee-458e-932e-a413f31b066d

**Comment by JosefNemec** [comment]
Profile added in master

**Comment by JosefNemec** [comment]
Yes, wait for the release. You can create custom profile for Avalonia build until then.

**Comment by stryxz1** [comment]
i tryed but cant make it work, i created custom profile and add the folder and executable, but when i start game only open emulator and not open with the game loaded
