### ISSUE TITLE
Indonesia Translation for Playnite

### ISSUE THREAD

**Issue by operamaniac** [JosefNemec/Playnite#320]
[indonesia.zip](https://github.com/JosefNemec/Playnite/files/1569486/indonesia.zip)

Sorry for not using the github repo. I don't really know how to sync the fork with master branch for the time being. I will update from repo for next update.

**Comment by JosefNemec** [comment]
Don't worry about it, this is fine. I will integrate it in next update.

**Comment by JosefNemec** [comment]
3.2 update added new string for localization:
https://github.com/JosefNemec/Playnite/commit/ad9500c54713b53cf6e8bab1df4f0ee9fbf0be1a#diff-fc6eaa727d5578c3ac3d59652659d9e2
https://github.com/JosefNemec/Playnite/commit/b122a110cce6735adca31c3a5caadd0ab6451f91#diff-fc6eaa727d5578c3ac3d59652659d9e2

**Comment by operamaniac** [comment]
[indonesia.zip](https://github.com/JosefNemec/Playnite/files/1572734/indonesia.zip)

Updated with the new string and some typo fix.

**Comment by JosefNemec** [comment]
3.3 update added new string for localization:
https://github.com/JosefNemec/Playnite/commit/ec65168e6fb0f6dc207404c78f7647913441e956#diff-fc6eaa727d5578c3ac3d59652659d9e2

**Comment by JosefNemec** [comment]
I won't be posting updates to original English files in every separate localization issue anymore. Please subscribe to new [localization updates](https://github.com/JosefNemec/Playnite/issues/385) issue to be notified when new stuff needs translation. But please keep posting your updated files in appropriate language issues. Thanks

**Comment by operamaniac** [comment]
Updated to 3.3 : 
[indonesia.zip](https://github.com/JosefNemec/Playnite/files/1604986/indonesia.zip)

I also notice that my Battle.Net login is OK even when I don't login with it (I don't even have one). Should I report this as an issue?
![image](https://user-images.githubusercontent.com/21957465/34587971-33b3eb38-f1dd-11e7-8d63-25319dd87327.png)

**Comment by JosefNemec** [comment]
Yes, please open that as separate issue. Thank you

**Comment by operamaniac** [comment]
@JosefNemec Updated to 3.4

[indonesia_3.4.zip](https://github.com/JosefNemec/Playnite/files/1607854/indonesia_3.4.zip)

**Comment by JosefNemec** [comment]
Localization have been completely move to Crowdin: https://crowdin.com/project/playnite

Please join the project there to submit updates.
