### ISSUE TITLE
Itch.IO game installation does nothing

### ISSUE THREAD

**Issue by drnooooo** [JosefNemec/Playnite#3203]
### Bug Description

Using itch.io app 25.5.1, Playnite's installation button does nothing, forcing me to install games manually. I tested with multiple games: Hypnospace Outlaw, Lenna's Inception, Baba Is You, and Micro Mages. The itch.io app pops up but no install pop-up appears. I attempted to install the latest version of Playnite (I was using 9, now I'm using 10) and update all addons, and I also attempted to install with Playnite in safe mode. Regardless, nothing happens when I press the Install button - the "Installing" text appears in Playnite but nothing is installed and the app doesn't do anything but go to itch.io's home screen.

I also made sure my account was authenticated in Playnite, and reauntheticated just in case.

### To Reproduce

- In Playnite 10.8, press install button on uninstalled game from itch.io source.

### Diagnostics ID

43413483-2f69-4305-b8bc-455730b28717

**Comment by drnooooo** [comment]
Safe mode diagnostics package: d33ee2c1-80c4-4862-8438-3918221057ff

**Comment by JosefNemec** [comment]
That's a correct behavior, we can't directly initiate installation in itch client, it's currently technically not possible. We can only open itch client for you, then you have to start the installation manually from that point.

**Comment by drnooooo** [comment]
I see. Thank you for the clarification!
