### ISSUE TITLE
Crash On Start

### ISSUE THREAD

**Issue by Tierney11290** [JosefNemec/Playnite#3209]
### Bug Description

When starting Playnite, the splashscreen appears but I am then shown an error window 

"Whoops! Something went wrong...

An Unrecoverable error has occurred."

Unable to even provide a diagnostics package as it returns an error as seen in the screenshot below. Starting in Safe Mode also does not work and results in the same crash/error.

### To Reproduce

When Playnite starts automatically on Windows 11 boot up.

### Diagnostics ID

N/A

### Screenshots

![Crash Error](https://user-images.githubusercontent.com/32247044/207471909-ae46b717-bc6d-4d12-8099-7871b2de8226.jpg)

![Diagnostics Failure](https://user-images.githubusercontent.com/32247044/207471915-1799cf78-9f26-45d1-b1e3-9896e9dec6c1.png)

**Comment by JosefNemec** [comment]
Please upload `%appdata%\playnite\playnite.log` file (will be in Playnite's install folder if you are using portable version).

**Comment by Tierney11290** [comment]
Today it started up fine. Nothing different this time so not sure what happened but here is the log. 

[playnite.log](https://github.com/JosefNemec/Playnite/files/10231636/playnite.log)

**Comment by JosefNemec** [comment]
It was crashing because something about .NET Framework installation on your system was broken:
`System.BadImageFormatException: [C:\WINDOWS\Microsoft.Net\assembly\GAC_32\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll] The signature is incorrect.`

**Comment by Tierney11290** [comment]
Glad to hear it was local and an easy fix! Thanks for the assistance and your hard work as always
