### ISSUE TITLE
Basic gamepad support in desktop mode

### ISSUE THREAD

**Issue by Shituation** [JosefNemec/Playnite#3210]
### Feature description

Need basic support for desktop mode to select and launch games. There is no point to have to launch playnite, then launch fullscreen mode to be able to use the gamepad.

Also in my case the guide button from my xbox controller has been mapped to other key combination (to solve the lack of GUI / exit hotkeys in modern emulators 🤷‍♂️) so the guide button that is hardcoded to open fullscreen mode, is not working.

**Comment by JosefNemec** [comment]
You can directly launch Fullscreen mode (by launching it's exe), you don't have to go thorough Desktop mode first. 

Controller support in Desktop mode is unlikely to happen, at least not in near future.

**Comment by Shituation** [comment]
Ok, but launching it in fullscreen mode means I cannot make it auto start with the system since I would have to close it everytime. I'm trying to reduce dead time here, having the app open in background, open it fast (bring to front) and be able to use gamepad (use from a distance).

Closing this since you will not add the feature.

**Comment by JosefNemec** [comment]
I didn't say it's never going to happen, I said it's not going to happen in near future.

**Comment by Shituation** [comment]
Which, to me, its the same thing. 
Thanks.
