### ISSUE TITLE
Some kind of Kid "Blocked" Mode

### ISSUE THREAD

**Issue by darksgan** [JosefNemec/Playnite#3213]
### Feature description

I've been testing a little the aplication and I started to add games for kids on it (emulated or PC games), Disney Games, Looney Tunes / Tiny Toons games, old plataformers, some old games, etc... and I'm liking it a lot, specially the Fullscreen Mode as a easy way to access to games... for a kid.

Well, ok, I'm thinking of creating a session for windows (or a machine only with games and Playnite) for a kid (or more kids, I don't know yet), and "autolaunch" Playnite in "fullscreen mode" as soon as the Windows Session Start (and "autostart" that session as default)...

I think it would be fine to hide the keyboard and mouse, and let only the controller **stay** conected to the machine (if the kid is alone with the machine and the games), so ... a kid could switch on the machine, and access to the games directly "without risks" if "nobody is around"... but there is a problem.

If the kid goes to the "Main Menu", he could choose options as "Configuration" and change things that shouldn't be changed.

He/She could enter in the "send feedback" option too, and then the Internet Browser would be launched (and he/she wouldn't have a way to go back to the Playnite launcher without a keybooard or mouse (and, anyway, maybe it wouldn't be good that the kid could access to internet/browser without somebody looking at him/her). The "Patreon Option" shoundn't be accesible in the "kid mode" either, because nothing related with money should be accesible (maybe a "info message" with the link to the "Patreon url" would be fine, but... impossible to access to it only with a controller), and... it would open the Internet Browser too, and... again, it could have some kind of access to internet (and futhermore, without a Keyboard/Mouse, it wouldn't be able to go back to the launcher)...

In a kid mode, I would love to see that they are not able to change to "Desktop Mode" either or "Exit Playnite"... for not letting them see other thing in the PC, even if the session is "more or less empty"... the objective is "to avoid risks".

I mean, It would be fine to have a lot of "config options" or ways to get out of the "Playnite fullscreen mode" blocked for a "kid mode"...

Options that are already accesible in Playnite like "Restart Playnite" (the new one in the Help section) is fine, because maybe the aplication could fail and to not work fine or something; and the "Restart" or "Shutdown" the machine options are marvelous too as a way to not let the kid access to the "Windows Desktop, and even so, to let him/her to Shutdown or Restart the machine "in a right way".

Options like "Choose a Random Game" of "Update Library"... could be there or not, they are maybe not relevant for a kid, but it can't "hurt him/her", I think.

Then, if somebody want to access to the Config Menu, the Patreon link, the "Send Feedback"option, etc, you only need to conect a Keyboard and PRESS F11, or close the "Kid Mode" with Alt+F4, and start the "Desktop Mode" of the "Normal Fullscreen Mode" (even if a Keyboard is conected, the kid could no exit the "kid mode", if he/she don't know that the F11 let you access to the Destop Mode, or the Alt+F4 close the aplication).

Of course, there should be a option or parameters for a CMD/.bat "launcher", that let you start the "kid mode" directly for blocking those options from start.

Thanks, regard, and sorry for disturbing.

**Comment by darklinkpower** [comment]
Duplicate of https://github.com/JosefNemec/Playnite/issues/1102 and https://github.com/JosefNemec/Playnite/issues/1497

The first issue indicates Desktop Mode but should apply to Fullscreen Mode as well.

**Comment by darksgan** [comment]
> Duplicate of #1102 and #1497
> 
> The first issue indicates Desktop Mode but should apply to Fullscreen Mode as well.

Hmmm, nice... they are similar, yes, and they thought about somethink I didin't, like block the "Hide Games" and "Uninstall Games" options.

But it would be fine to block the Patreon and the Send Feedback options too...

And, I don't think that Restart and Shutdown options should be removed.

I see people ask for blocking different things... so, maybe, a good option, would be paremeters for CMD / .bat scripts, to launch Playnite in different modes, blocking some or other things.

Or an editable config file where options could be enabled/disabled

Thanks you for showing the other request The I dind't see.

Regards.

**Comment by JosefNemec** [comment]
Will be done via #1102 and #1497

**Comment by findbmx** [comment]
Fot those who want to disable GameMenu items so kids can remove or uninstall a game through Fullscreen Mode:

1. Open GameMenu.xaml to edit
2. Add the below property to the first style tag targeting ButtomEx

`<Setter Property="IsEnabled" Value="false" />`

It should look like this:

```
<Style x:Key="GameMenuButton" BasedOn="{StaticResource {x:Type ButtonEx}}" TargetType="ButtonEx">
	<Setter Property="Margin" Value="5" />
	<Setter Property="IsEnabled" Value="false" />
</Style>
```

This will gray out and disable all the menu items in game option.

Kids who accidentally opened the game menu in Fullscreen mode can tap the B button on their gamepad to go back to game list.
