### ISSUE TITLE
Authenticate with system browser

### ISSUE THREAD

**Issue by mwisnicki** [JosefNemec/Playnite#3214]
### Feature description

OAuth login prompts should be executed in system browser rather than embedded web view.

I'm already logged into Google/FB/etc so it would make it much easier and also I don't like entering my passwords into 3rd party apps (even if Playnite is open source we should object on principle - it's generally a horrible idea).

**Comment by mwisnicki** [comment]
Well actually, Google is blocking the login for that very reason.
All the more reason to add this.

**Comment by JosefNemec** [comment]
Library authentications are handled by each library plugin individually, it's not something Playnite enforces how it should work.
