### ISSUE TITLE
Ability to see the "library integrated play action" action

### ISSUE THREAD

**Issue by MistaMelon** [JosefNemec/Playnite#3217]
### Feature description

An option that can be enabled in options menu to show the library integration play action in text instead of just a checkbox. This can be handy for people with libraries that use other launchers too but don't rely on them. 

An example are "Ubisoft" games on the "Epic games launcher". These games are also able to launch from the "Ubisoft connect launcher" without launching the "Epic games launcher". But these games show up twice in the library cause they are part of both libraries. So I like to hide them but still like to know I have the option to launch one way or the other. 
What I have to do now to do this is: Go to launcher -> Click make a desktop shortcut -> Look at the properties of the shortcut -> Copy and paste the shortcut path to "Playnite" as an extra option -> delete the shortcut from desktop.

The screenshot I added gives an indication of what I mean if its not really clear. (Screenshot "library integration" is from Epic, I added the option for "Ubisoft connect"). Of course a more advanced way would be to allow to merge games but then they would need to be able to be part of different sources and libraries at the same time, so I don't think that is plausible. I think my idea is a more realistic option for something which probably a minor amount of people would utilize. Its still a "copy and paste" action but everything happens in "Playnite" instead of: launcher/desktop/Playnite.

### Screenshots
How it is now:
![image](https://user-images.githubusercontent.com/44997434/208105193-ead9928e-727f-4615-95f4-885a1d06ed1c.png)
My proposal option (quickly made in paint):
![image](https://user-images.githubusercontent.com/44997434/208107975-6cbd1845-ef99-4916-b237-589d38651185.png)

**Comment by JosefNemec** [comment]
This is not possible because these actions are generated dynamically by integration plugins each time a game is started, to make sure that plugins can update game's startup behavior, add additional actions and other changes to game startup without need to permanently change game's data.
