### ISSUE TITLE
Jump List... Do Not Launch Game... Options

### ISSUE THREAD

**Issue by Phoenix92471** [JosefNemec/Playnite#3221]
### Feature description

Windows 10/11/+ Jump List items don't Launch game.

 Instead, they show the library page of the game you click on within Playnite, then you could hit Play if you wanted to.

Option under More Button to Pin/Unpin to Jump List.

Jump List Link Launches Game or Links to Playnite Library Page.
 Right Click could Have those options.

 Some Jump List items have Playnite icon instead of Game icon.
 This could be set in games Library Properties Page.

Other Jump List Settings Like Font Type, Size, & Bold Fonts, and the number of Jump List items that are shown on the Jump List.

Tasks like Quick Access to Settings via the Jump List. Similar to Steam App. (See attached images)....

### Screenshots

![Jump List (Right click, Taskbar icon) - Screenshot 2022-12-17 103127](https://user-images.githubusercontent.com/120794100/208249550-8a14adb1-4c0a-40b9-8fdf-4bf80ff816b8.png)
Jump List (Right click, Taskbar icon) - Screenshot 2022-12-17 103127

![Library Page - Screenshot 2022-12-17 091941](https://user-images.githubusercontent.com/120794100/208249583-3dd6dafa-c7be-4cb0-ad95-3484c550319e.png)
Library Page - Screenshot 2022-12-17 091941

![Right Click on Jump List Item - Screenshot 2022-12-17 103204](https://user-images.githubusercontent.com/120794100/208249593-4b114cb9-d09b-4f69-9d35-9010dde8b692.png)
Right Click on Jump List Item - Screenshot 2022-12-17 103204

![Steam Tasks Jump List Menu - Screenshot 2022-12-17 104817](https://user-images.githubusercontent.com/120794100/208250146-38b7fb38-6d77-4257-a8b9-6da36b631d9d.png)
Steam Tasks Jump List Menu - Screenshot 2022-12-17 104817

**Comment by JosefNemec** [comment]
> Right Click could Have those options.

It couldn't, we can't add options there, Windows doesn't allow it.

> Some Jump List items have Playnite icon instead of Game icon.

Windows limitation, Windows supports only .ico icons there. If a game has icon in a different format, it will not be displayed.

> Other Jump List Settings Like Font Type, Size, & Bold Fonts, and the number of Jump List items that are shown on the Jump List.

Not possible, we can't change those, it's controlled by Windows.
