### ISSUE TITLE
Ability to ignore certain groups while using 'grouping settings' feature

### ISSUE THREAD

**Issue by cnapolit** [JosefNemec/Playnite#3222]
### Feature description

Often while grouping, especially by tag or category, there are numerous groups that are not the intended target for the filter.
The ability to ignore these groups while filtering would help declutter grouping options with many values already present.

A potential UI implementation could be right clicking on a group title bringing up a context menu with the option to remove the group from the current filter.

Ignored groupings could be displayed and modified for filter presets under the filter editor (accessed via the pencil icon in the filter panel).

A list of ignored groups could also be maintained at the bottom of the view, with a similar context menu offering the ability to revert the ignored status.

A more organic option would be a minus/plus symbol on the far right of the group name. The expand symbols could be changed to carrots (^, v) to avoid confusion.

The groupings should reset only if the grouping field changes. Adding filtering options should not re-introduce ignored groups.

Alternatively, this feature could be implemented instead by a whitelist. This may make more sense, since the number of ignored groupings would usually exceed the number of desired groupings.

### Screenshots

![image](https://user-images.githubusercontent.com/94765074/208252646-3505dbf6-a713-41a1-b090-dde43f82fa76.png)

**Comment by JosefNemec** [comment]
Will be done as part of filtering rework which will also include exclusion filtering #2538

**Comment by cnapolit** [comment]
Is exclusion filtering the same thing? I thought it was specifically adding 'NOT' functionality to exclude games, but it is a bit of a catch-all term. Might help to elaborate the description in that case.

just to ensure clarity, ignoring groups wouldn't necessarily exclude games unless that game was only associated with the group and no other.

For example, say game 'A' has tags [ 'Tag1', 'Tag2' ] and game 'B' has the tag [  'Tag1' ]. 
If I were to group by tags and ignore 'Tag2' from grouping,
then game 'A' would still be listed under the 'Tag2' group, 
and 'B' would not be listed since no other groupings are associated with it.

**Comment by JosefNemec** [comment]
It will work exactly how you describe in your example if you create a filter that excludes Tag1.
