### ISSUE TITLE
Steam title failing to launch in Playnite

### ISSUE THREAD

**Issue by aquarion** [JosefNemec/Playnite#3223]
### Bug Description

This may be a new Steam feature, but when I tried to launch Kentucky Route Zero from Playnite, it launches steam, and then gets stuck on "Preparing to launch". If I launch it directly from Steam, I get an interstitial Steam-UI dialogue box offering me execution options, which I don't get if I launch from Playnite, so maybe that's getting in the way?

There's nothing in playnite logs after `Starting Kentucky Route Zero, 1a83a437-728b-49a2-915f-52c900b92883, 231200, cb91dfc9-b977-43bf-8e70-55f46e410fab`, and steam doesn't produce any output I can see either.

### Diagnostics ID

d3cf6226-5ae7-45f8-afea-c6a9bd869a81

**Comment by Jeshibu** [comment]
This should be in the https://github.com/JosefNemec/PlayniteExtensions repository (where the Steam plugin is hosted).

I've tried to reproduce it, and what the Steam plugin is normally doing is calling steam://rungameid/231200 - which I've just tried and launches the game fine for me. Maybe try verifying your game files in Steam?
There's also a recently added option to use the Steam launch dialog under `main menu > Add-ons > Extension settings > Libraries > Steam > Advanced > Show Steam's game startup selection menu in desktop mode`

**Comment by aquarion** [comment]
Fair. The game launches fine direct from Steam, and verifying files doesn't change this, but if you can't reproduce it, it's probably something local.

**Comment by Jeshibu** [comment]
Try entering that steam url from my last comment into your browser bar and press enter - if it doesn't launch it's on your local Steam install's end. If it does, there's something else going on in Playnite.

**Comment by aquarion** [comment]
That URL works fine

**Comment by Jeshibu** [comment]
Then it's something for Josef Nemec to look at, I'd reopen if I were you.

**Comment by JosefNemec** [comment]
The logs say that Steam plugin is launching the game via `steam://launch/231200/Dialog`, if it doesn't work properly, then it's either Steam plugin issue or Steam issue. Either way, nothing to do with Playnite itself.
