### ISSUE TITLE
Incorrect Hours for Game Not Installed

### ISSUE THREAD

**Issue by DJ-Fox11** [JosefNemec/Playnite#3226]
### Bug Description

Playnite is showing me that I have 99 hours and 59 minutes on Fortnite. I have never had Fortnite installed on my computer, so I have never played it. But I do own it on my account.

### To Reproduce

Cannot find any way to repeat this issue.

### Diagnostics ID

80e14a85-b062-4e2a-bfaa-70eee2e3eab5

### Screenshots

![Screenshot 2022-12-21 105512](https://user-images.githubusercontent.com/114490578/208788839-0cb91196-07a9-4126-af3d-fc930e234c64.png)

**Comment by JosefNemec** [comment]
Some plugins, like Epic in this case, can fetch play time from your account, no matter if a game is installed or not.
