### ISSUE TITLE
rockstar games addon

### ISSUE THREAD

**Issue by DAIIIIIIIIIIIIII** [JosefNemec/Playnite#3230]
### Bug Description

i have correctly installed and logged in the extension, but I just bought red dead redemption 2 and updating the playnite library, it doesn't find anything

### Diagnostics ID

50d94f6b-0c1f-4bc8-8cd8-4ad74a07d6f4

**Comment by JosefNemec** [comment]
1) Wrong repository
2) Rockstar plugin only imports installed games
