### ISSUE TITLE
'Companies' entries may be duplicated when downloading metadata

### ISSUE THREAD

**Issue by chocolatechipcats** [JosefNemec/Playnite#3231]
### Bug Description

When downloading metadata from a provider, if both developer and publisher are identical, it results in duplicate values in Companies.

This occurs with both the Steam and GOG metadata plugins. Unless they share code (though that is not unlikely), this makes me believe it's a Playnite issue rather than an extension one. (I attempted to test with other plugins, but IGDB is hard to find duplicate entries, itch.io doesn't seem to have 'publisher', and Epic is broken.)

This does not seem to occur if the company already exists in the Companies list.

### To Reproduce

Find a game with the same value in both developer and publisher. Remove it from the company list if it already exists there, then download the metadata and save. upon checking the library manager, you should see the duplicate entries in Companies. 

On Steam, I tested with Cattails. Both developer and publisher are Falcon Developments.

On GOG, I tested with The Witcher 3: Wild Hunt. Both developer and publisher are CD PROJEKT RED.

### Diagnostics ID

56ecf6d0-1c3f-4993-ada9-0b7897afdee9

**Comment by chocolatechipcats** [comment]
Can confirm this also happens with IGDB.

I tested with Terroir. Both publisher and developer are General Interactive.

**Comment by chocolatechipcats** [comment]
Another update:

This does _not_ occur when entering the entries manually.

**Comment by chocolatechipcats** [comment]
It _does_ happen when downloading one entry and entering the other manually.

**Comment by JosefNemec** [comment]
Fixed in master via f40422782eeeed312cd279e2383cbfbe2c6ea391
