### ISSUE TITLE
Possible regression: "Open Installation Folder" doesn't respect default file manager

### ISSUE THREAD

**Issue by chocolatechipcats** [JosefNemec/Playnite#3234]
### Bug Description

Playnite 10.9. Related: #2166

This time, 'Open Installation Folder' opens in explorer.exe rather than my default XYplorer. 

As I don't use that option too much, I'm unsure of the last version this worked correctly.

Thanks in advance.

### Diagnostics ID

b3e4fd64-b61c-4773-addb-0df478b07ea7

**Comment by JosefNemec** [comment]
Go to advanced settings and manually configure "folder open command" to use your custom file manager. Current behavior solves multiple issues with folder open action and will stay that way since majority of people use standard file explorer.
