### ISSUE TITLE
Crash While Downloading Metadata

### ISSUE THREAD

**Issue by epeternally** [JosefNemec/Playnite#324]
Playnite seems to consistently crash while attempting to download the IGDB metadata for Beach Spikers on the GameCube.

[Playnite Crash Diag 12-18-2017 455pm.zip](https://github.com/JosefNemec/Playnite/files/1569924/Playnite.Crash.Diag.12-18-2017.455pm.zip)

**Comment by JosefNemec** [comment]
Released in 3.2
