### ISSUE TITLE
(steam) Playtime not updating for games shared from others / Friends

### ISSUE THREAD

**Issue by Cixxar** [JosefNemec/Playnite#3242]
### Bug Description

Playtime from games not owned but borrowed via steams family/friends sharing is not importing into playnite

### To Reproduce

Steam -> Settings -> Family -> authorize library sharing on this computer -> Add any other account that has been logged in on the same PC and repeat on the other account.
*requires 2 steam accounts not on limited features*
Install a game from your friend and play.

API keys added and playtime is not private

### Diagnostics ID

dd1ad87d-287a-44cb-b935-b04873302b7f

**Comment by darklinkpower** [comment]
Should go in this other repository https://github.com/JosefNemec/PlayniteExtensions

This repository is for the core Playnite software only.

Regarding your issue, it's because the Steam API the extension uses only reports playtime for owned games

**Comment by JosefNemec** [comment]
As darklinkpower mentioned, this is not possible because Steam API we use doesn't provide that info.
