### ISSUE TITLE
Support for more launchers?

### ISSUE THREAD

**Issue by TheNametag** [JosefNemec/Playnite#3246]
### Feature description

You've got the most major launchers covered, it seems, but there are a few others out there.  Some may be known to people who've used Twitch/Amazon Prime for a bit, as they've received games there.  Would it be possible to add games from:

Legacy Games Launcher
Rockstar Game Launcher
Wargaming.net Game Center
My.com GameCenter

I'm sure there's plenty of others I missed.  The latter two may not be that critical as they don't have that many games on them, but Legacy at least has a rather significant amount of mostly casual games, and it would be nice to have those added to a collected list like this.

**Comment by Jeshibu** [comment]
The install process only shows you a selection of plugins. Look in `main menu > Add-ons > Browse > Libraries` to find at least the first two of your list, or here:
https://playnite.link/addons.html#LegacyGamesLibrary_34c3178f-6e1d-4e27-8885-99d4f031b168
https://playnite.link/addons.html#Rockstar_Games_Library

**Comment by JosefNemec** [comment]
I don't plan to create any more integrations myself, I already have a lot of them to maintain. They will have to be created by community members, which is already happening as Jeshibu pointed out.
