### ISSUE TITLE
Change metadata download label to skip

### ISSUE THREAD

**Issue by darktorres** [JosefNemec/Playnite#3249]
### Feature description

When downloading icon/cover/background metadata the cancel button doesn't actually cancel, it just skips to the next screen. The usability can be improved by changing the label text to "Skip".

### Screenshots

![Captura de tela 2023-01-05 094446](https://user-images.githubusercontent.com/5768540/210783131-73dbbe38-00de-4316-9b49-ac9e3a23192f.png)

**Comment by JosefNemec** [comment]
That dialog is from a metadata plugin that provides those images, Playnite has no control over it.

**Comment by JosefNemec** [comment]
It needs to be changed on plugin's side.

**Comment by darktorres** [comment]
I changed the label text in ImageSelectionWindow.xaml to make the image above. Could this be changed in Playnite code to avoid needing changing every plugin?

**Comment by JosefNemec** [comment]
That's a generic dialog for image selection, changing it to "skip" would not make sense in other places where that dialog could be used.

The proper change would be making that dialog customizable and allow plugins to change action buttons, which would still require change in plugins that use this dialog.
