### ISSUE TITLE
Theme updates

### ISSUE THREAD

**Issue by JosefNemec** [JosefNemec/Playnite#325]
This is just a notification issue that will be updated when changes are made to built-in Classic and Modern themes. It's for people to subscribe to it and be notified, so they can update their forked themes.

**Comment by JosefNemec** [comment]
Changes in 3.2:

Social links added:
https://github.com/JosefNemec/Playnite/commit/5525d0569ea97e5e46b4312818695cdefe32f5f8#diff-a55d87f8b528d0587c661474447f86aa
https://github.com/JosefNemec/Playnite/commit/5525d0569ea97e5e46b4312818695cdefe32f5f8#diff-e579e2899b4829a8371e7356e7b4e83f

Added missing localization strings:
https://github.com/JosefNemec/Playnite/commit/ad9500c54713b53cf6e8bab1df4f0ee9fbf0be1a#diff-a55d87f8b528d0587c661474447f86aa
https://github.com/JosefNemec/Playnite/commit/ad9500c54713b53cf6e8bab1df4f0ee9fbf0be1a#diff-e579e2899b4829a8371e7356e7b4e83f

**Comment by JosefNemec** [comment]
Changes in 3.3

Added missing localization strings:
https://github.com/JosefNemec/Playnite/commit/ec65168e6fb0f6dc207404c78f7647913441e956#diff-a55d87f8b528d0587c661474447f86aa
https://github.com/JosefNemec/Playnite/commit/ec65168e6fb0f6dc207404c78f7647913441e956#diff-e579e2899b4829a8371e7356e7b4e83f

Prevent accidental double-click from starting the game
https://github.com/JosefNemec/Playnite/commit/601ffe10c0d8590daea3fa793d34752e25d97195#diff-a55d87f8b528d0587c661474447f86aa
https://github.com/JosefNemec/Playnite/commit/601ffe10c0d8590daea3fa793d34752e25d97195#diff-e579e2899b4829a8371e7356e7b4e83f

**Comment by evgdovg1996** [comment]
@JosefNemec What's happened with Modern theme? Now it looks like classic.
It's ok that it lost dark shading and now has only dark text-blocks? Or this is bug?
https://imgur.com/a/79Nst

**Comment by JosefNemec** [comment]
Changes in 3.4

Cover image aspect ratio settable via profile:
https://github.com/JosefNemec/Playnite/commit/1d245815b7e01776a52fa7d5f169d91e4d17484b

Modern theme restored to original 3.0 release look:
https://github.com/JosefNemec/Playnite/commit/d96ee79bf6625a2c1fd34d0262e07761a425a10f
