### ISSUE TITLE
Is there a function to clear data for games that no longer exist?

### ISSUE THREAD

**Issue by shinobiz** [JosefNemec/Playnite#3252]
### Feature description

I am a novice and I can't seem to find this feature.

**Comment by darklinkpower** [comment]
What do you mean that no longer exist? But no, Playnite doesn't remove any games automatically. Games that have been imported to Playnite can only be removed manually by the user with right click -> Remove

**Comment by shinobiz** [comment]
Sorry, it means the game has been uninstalled

**Comment by chocolatechipcats** [comment]
Is there a reason filtering to installed won't work for your purposes?

**Comment by JosefNemec** [comment]
Filter uninstalled games, select all, delete.

**Comment by shinobiz** [comment]
> 过滤已卸载的游戏，全选，删除。

Sorry, the option "Uninstalled" was not found in the filter

**Comment by chocolatechipcats** [comment]
> > 过滤已卸载的游戏，全选，删除。
> 
> Sorry, the option "Uninstalled" was not found in the filter. Can you take a screenshot and let me know? Please.

The first two checkboxes in the filter panel is "installed" and "not installed." Click the second one.

**Comment by shinobiz** [comment]
I mean games that were once installed were uninstalled, not games that were not installed.发自我的手机-------- 原始邮件 --------发件人： chocolatechipcats ***@***.***>日期： 2023年1月7日周六 04:54收件人： JosefNemec/Playnite ***@***.***>抄送： shinobiz ***@***.***>, Author ***@***.***>主    题： Re: [JosefNemec/Playnite] Is there a function to clear data for games that no longer exist? (Issue #3252)





过滤已卸载的游戏，全选，删除。



Sorry, the option "Uninstalled" was not found in the filter. Can you take a screenshot and let me know? Please.



The first two checkboxes in the filter panel is "installed" and "not installed." Click the second one.
