### ISSUE TITLE
Yuzu not launching games directly

### ISSUE THREAD

**Issue by hyoretsu** [JosefNemec/Playnite#3256]
### Bug Description

Title. It used to work.

### To Reproduce

Download a Nintendo Switch game (.nsp) and try to play with Yuzu emulator. (v1299, latest as of 2023/1/7)

### Diagnostics ID

1573799d-a2ee-4175-8210-e78e74ea8f87

**Comment by JosefNemec** [comment]
https://playnite.link/docs/master/manual/emulators.html#game-runs-properly-when-launched-manually-from-an-emulator-but-not-from-playnite

If you are saying that it used to work and stopped, then I'm betting on something being broken in Yuzu, since we haven't made any changes to this in a long time.
