### ISSUE TITLE
Rotating backup files via external config

### ISSUE THREAD

**Issue by Terrance** [JosefNemec/Playnite#3257]
### Feature description

As backups take some time to run, having it trigger at application startup when I'm about to play a game isn't ideal, so I'd like to configure this to run via Task Scheduler or similar instead.

I can see from the docs that I can run `Playnite.DesktopApp.exe --backup <config>`, which describes the following options:

Property | Description
-- | --
OutputFile | Full path to resulting backup file.
RotatingBackups | Number of rotating backup files to be kept. This only works if resulting file name is in `PlayniteBackup-yyyy-MM-dd-HH-mm-ss.zip` format. `0` means only one backup file will be always kept.

As far as I can tell, `OutputFile` must be an actual file path, not a target directory, and there's no mention of any substitution values to put the current date in the filename (I've tried the literal `yyyy-MM-dd-...` as well as a fixed date), so I can only define a static filename.  This means I can't do rotating backups without a secondary script that dynamically generates the config file each time.

**Comment by JosefNemec** [comment]
Done in master, you can now use `OutputDir` to specify only target folder, file names will be set automatically and will work with rotating backups.
