### ISSUE TITLE
Add "Playing" completion status

### ISSUE THREAD

**Issue by jmason86** [JosefNemec/Playnite#3259]
### Feature description

Right now the list of values for Completion Status are: 
* None
* Abandoned
* Completed
* Not Played
* Played

It would be really nice if there was also "Playing". I love Playnite for consolidating my list of games across all platforms. I'm often playing at least one on each console and PC. I've been using "favorites" as effectively my "playing" list but obviously that's a bit of kludge. 
So glad that Playnite exists!

**Comment by XenorPLxx** [comment]
You can edit completion statuses yourself in setting, library manager tab.

**Comment by jmason86** [comment]
Oh nice, I looked through the Settings > Settings and didn't find it before posting this issue. But now I do indeed see it in Settings > Library > Library Manager > Completion Statuses. Thanks!
