### ISSUE TITLE
Need to be able to ignore text in parenthesis, brackets, and braces when adding game

### ISSUE THREAD

**Issue by billybruiser** [JosefNemec/Playnite#326]
When adding emulated games, it would be helpful to be able to ignore those, so that it can correctly pull information from IGDB.

**Comment by JosefNemec** [comment]
This has been added in 3.2 released today. Can you please verify that it works as you would expect?

**Comment by billybruiser** [comment]
That's funny.  The update notification just popped up right after I posted this.  I just tested it out with re-adding some games and it seems to be working correctly.  Thanks
