### ISSUE TITLE
Metadata Download: Differing tittle capitalization always overwritten

### ISSUE THREAD

**Issue by chocolatechipcats** [JosefNemec/Playnite#3261]
### Bug Description

If the current title of a game differs in capitalization from that on the metadata provider, it'll automatically choose the remote information without giving a choice in "select metadata to import."

Confirmed with several different metadata plugins that provide tittes (IGDB, Steam, and PCGamingWiki).

### To Reproduce

1. Take a game and change its title to ALL CAPS.
2. Download metadata from any provider that has it.
3. Click "Select all" on current metadata and import.
The capitalization of the title will change.

This was first discovered when downloading information for a gamed called "Little Racers STREET" from PCGamingWiki.

### Diagnostics ID

bf1361e7-d145-4434-a12f-87127ea391f6

### Screenshots

![2023-01-09 00_51_17-Edit Game Details](https://user-images.githubusercontent.com/47759676/211242977-726efb17-2298-40f6-bad9-0aff37c60ed9.png)

![2023-01-09 00_52_40-Edit Game Details](https://user-images.githubusercontent.com/47759676/211243049-fc584fa5-0a81-46a6-8d36-043c142af43c.png)

**Comment by chocolatechipcats** [comment]
Uh, ignore the typo. Stupid cold fingers.

**Comment by JosefNemec** [comment]
Fixed in master
