### ISSUE TITLE
Request for "Display Name" box in "Edit Game Edit"

### ISSUE THREAD

**Issue by shinobiz** [JosefNemec/Playnite#3262]
### Feature description

Sorry for my bad english, I hope you can understand.

In areas other than English-speaking regions, many players are used to naming and displaying game titles in their local language, which seems intuitive. But the problem is that once the "Name" column is not in English, it is very difficult to find information using a metadata scraper. So I want to add the "Display Name" box separately.

Working logic:
When there is no information in the "Display Name" box, the game name is displayed according to the information in the "Name" box.
![无显示名](https://user-images.githubusercontent.com/31954517/211256697-32e72545-ca30-4018-b542-8ec64be874dc.jpg)

When there is information in the "Display Name" box, the game name is displayed according to the information in the "Display Name" box. Users can customize the game name they want to display.
Metadata scraping is still based on the "Name" box.
![有名字](https://user-images.githubusercontent.com/31954517/211257087-68a04ef9-3ace-4d9c-852f-42b37384d841.jpg)

Whether you search by "Name" or "Display Name" in the game list is fine.
![搜索](https://user-images.githubusercontent.com/31954517/211257141-a1fb4e04-5d0f-47ce-8927-da4d4dc1fe0a.jpg)

If you want to further facilitate the user, the program can also help the user to automatically fill in the game display name corresponding to the local language. Of course, this needs to provide additional switches and language selection, because not every user likes to do that.

**Comment by JosefNemec** [comment]
#3190
