### ISSUE TITLE
How to display the number of filtered games or the number of a certain game platform?

### ISSUE THREAD

**Issue by shinobiz** [JosefNemec/Playnite#3266]
### Feature description

look at the title

![列表](https://user-images.githubusercontent.com/31954517/212027696-29626f14-b281-4909-9f3f-2243fb8eabbd.png)

**Comment by JosefNemec** [comment]
The only option right now is group by that field and numbers will appear for each group (might not be enabled by default, but you can enable group counts in the settings). General game view numbers will be done via #1150

Also please don't use this repository for general questions, we want to use it to track feature requests and bugs only. Please use our reddit or Discord instead for these questions, thank you.
