### ISSUE TITLE
Can't install or download Add-Ons or libraries or Metada

### ISSUE THREAD

**Issue by LoveDeluxeNem** [JosefNemec/Playnite#3268]
### Bug Description

Issue is resolved. This is just so people that encounter the same error know hot to fix it.

The issue (for me) didn't lie in Playnite. Checking the "playnite.log" file I encountered the error `|DEBUG|Downloader:Downloading string content from https://github.com/JosefNemec/PlayniteExtensions/raw/master/manifests/IGDBMetadata_Builtin.yaml using UTF8 encoding.
13-01 16:04:41.433|ERROR|AddonManifest:Failed to get addon installer manifest data.
System.Net.WebException: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel. ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.`

Following the link, I found out that my ISP is blocking links from "raw.githubusercontent.com" as not trustworthy. 

Solution : use another ISP. In my case, I used my phone's hotspot, it's not from the same provider. I guess you could use a VPN. Once the Add-on/library has been downloaded, it should work even if you are in the previous ISP.

### Diagnostics ID

bc8ffa5c-be54-4d04-b8e7-ff367f31cfa3

**Comment by JosefNemec** [comment]
I updated relevant paragraph on wiki https://github.com/JosefNemec/Playnite/wiki/Known-Issues#connectivity-issues

**Comment by chocolatechipcats** [comment]
> I updated relevant paragraph on wiki https://github.com/JosefNemec/Playnite/wiki/Known-Issues#connectivity-issues

If you have access, rebooting the modem may give you a new IP address. This isn't guaranteed to work; some ISPs have carrier-grade NATs for instance.
