### ISSUE TITLE
Toolbox "pack" doesn't remove all project / solution files from theme packages

### ISSUE THREAD

**Issue by CanRanBan** [JosefNemec/Playnite#3269]
### Bug Description

If solution files or project files use a different name than the default ones Toolbox `pack` will include them in the theme package.
It will do the same for `Theme.csproj.user` files which are created when the debugger is attached to Playnite.

### To Reproduce

Additional unused `Theme.csproj.user` included in `[Theme Name].pthm`:
- Create a `StartAction` inside Visual Studio with Playnite's `DesktopApp` or `FullscreenApp` executable as it's target.
- Use `Toolbox pack "Themefolder" "Outputfolder"`.
- Either add the `Theme` using the theme package (`.pthm`) to Playnite or inspect the theme package with an extraction tool: `Theme.csproj.user` will be present.

Same issue if the project (`.csproj`) and/or solution (`.sln`) file use different names.

### Diagnostics ID

-

**Comment by JosefNemec** [comment]
Fixed in master
