### ISSUE TITLE
[Long-Term] Additional options for scheduling updates

### ISSUE THREAD

**Issue by chocolatechipcats** [JosefNemec/Playnite#3273]
### Feature description

Related: #2011

Suggestion: Additional options for scheduling library/scan/addon/program updates. Some ideas, based on Windows' Task Scheduler:

- Trigger update at a specific time (rather than 'every day');
- Choose how often it recurs (daily, weekly, certain days of the week);
- Choosing whether to run as soon as possible after a scheduled update is missed due to Playnite not running.

Thanks.

### Screenshots

Screenshot from Task Scheduler:

![2023-01-17 00_05_03-New Trigger](https://user-images.githubusercontent.com/47759676/212807697-6d09c3a5-9c3a-433b-9eea-260236e20aec.png)

**Comment by JosefNemec** [comment]
I'm not sure this is worth all the effort to implement this for an application like Playnite where missing an update is not critical at all.

**Comment by Destroy666x** [comment]
I was just about to create an issue like that and it's coincidentally the first one listed :P

> where missing an update is not critical at all

It is critical for addons such as "IsThereAnyDeal" at least, I don't know if that can just implement that itself with WIndows libs though or if some Playnite API changes are needed. But having organized API option for plugins to schedule stuff easily would be nice in general.

For the rest, such as library updates, I agree it's not quite important, but more granularity would be nice to avoid running it at a bad time. How do the current "once a week" and "once a day" work?

**Comment by chocolatechipcats** [comment]
> > It is critical for addons such as "IsThereAnyDeal" at least
> 
> This is completely unrelated, ITAD plugin is not a library plugin, so if it has any regular data update, it's fully controlled by that plugin.
> 
> I'm going to close the issue, this is really something I can't see myself doing. The amount of effort needed compared to the value it brings is simply not worth it.

I assumed the poster meant "getting a prompt notification that the plugin has been updated," but maybe I misunderstood.

**Comment by Destroy666x** [comment]
> This is completely unrelated,

It is related as I was talking about a scheduling system as a whole, for various kind of events with API access. The 4 select boxes OP is talking about could be then just using that.
