### ISSUE TITLE
Android companion app to manage Playnite library

### ISSUE THREAD

**Issue by samkitty** [JosefNemec/Playnite#3275]
I have a huge library of games that I manage using Playnite, but whenever I'm away from my PC I have no way of viewing my games library unless I remote into my PC.

A simple companion app which allows you to easily scroll through your games/lists and manage them by either manually importing/exporting your library between devices or having them synced via a local instance would be incredibly useful and would fill a gap in the market. I'm aware of other apps that manage game libraries, but they 1-  are outdated and 2- don't have a PC client that is as powerful as Playnite.

Sorry for resurrecting this feature request, but I wanted to let you know that there's genuine demand for it. Especially now with game streaming dedicated Android handhelds and gadgets like Razer Kishi changing the way we think about accessing our games.

Not to mention Epic Games having 0 way of viewing your owned games on mobile. Not even via the official website. And with the weekly free games, I'm sure many people have games in their Epic library that they've never played/heard of. Not uncommon to purchase the same game you already own from a different store because you forgot you own it. Playnite is our only real hope.

**Comment by samkitty** [comment]
![Screenshot_20230125-003942_Google Play Store](https://user-images.githubusercontent.com/57629730/214445493-9489d536-e198-40d8-be74-11622a586636.jpg)
An app released in 2013 that is similar to Playnite. It's incredibly outdated and is a pain to setup, plus it doesn't automatically keep track of played games. Still managed to attract 500k users because it's simply the only available option.

**Comment by HerrKnarz** [comment]
There's already [Sharenite](https://www.sharenite.link/) to keep track of your playnite library. It's only a website for now and in an early beta, but it already works great - also on mobile.

**Comment by JosefNemec** [comment]
Duplicate #323

**Comment by Adithya-Jayan** [comment]
Below is another app that tries to do this with Playnite. Just adding it here for info: (Similar to Sharenite)
https://github.com/zachvlat/gamelibrary

**Comment by PushpakB3096** [comment]
I built something in this space if the goal is browsing / managing your Playnite library away from the PC (not a full Playnite-on-Android launcher).

PlayLog is a companion: Playnite add-on syncs your library and sessions to an Android app + web, over the internet. No same-network remoting required.

https://www.playlog.online

Disclosure: I'm the solo dev. Happy to answer setup questions here or on the site.
