### ISSUE TITLE
System.OutOfMemoryException

### ISSUE THREAD

**Issue by Harrison-Palmer** [JosefNemec/Playnite#328]
The error message is thrown when downloading steam metadata and importing steam catagories

System.OutOfMemoryException was unhandled
Message: An unhandled exception of type 'System.OutOfMemoryException' occurred in PresentationCore.dll

I imagine it is from having a large steam library. 1940 in my library.

http://steamcommunity.com/id/boomer_sauce/

[diag package.zip](https://github.com/JosefNemec/Playnite/files/1572458/diag.package.zip)

**Comment by JosefNemec** [comment]
Size of your library shouldn't be a problem. I've done tests with 3k size Steam libraries and Playnite memory usage should stay under 500-600MB (which shouldn't be a problem for you with 16GB of RAM).
I'll look into it.

**Comment by JosefNemec** [comment]
Can you please test it with [this build](http://playnite.link/download/memory.exe) and tell me if it fixes the issue?

**Comment by JosefNemec** [comment]
I'm closing this as it was possibly fixed in 3.3 by f2e47f07d262b546349a3a6172713bf8416dc2fa, please feel free to reopen if the issues still occurs.
