### ISSUE TITLE
Proton existing in Steam library causes install size scan error

### ISSUE THREAD

**Issue by NekuSoul** [JosefNemec/Playnite#3280]
**Describe the bug**
After messing around with Steam on Linux and installing Proton into a shared Steam library between both OSs, scanning for Steam games causes an error on Playnite (in Windows) each time: `Proton 7 0: Object reference not set to an instance of an object.`.

I'm guessing this is because there's some special files in there that can't be handled properly by Windows.

**To Reproduce**
* Install Proton into Steam library.
* Scan for new Steam games.

Not sure if there's a simple way to install Proton on Windows, since you can't seem to manage Proton on Windows at all, not even being able to uninstall through Steam or manually due to those special files.

**Screenshots**
![image](https://user-images.githubusercontent.com/1763357/215151697-74e17e74-fcae-4b12-b8d5-b2bdae7f0433.png)
![image](https://user-images.githubusercontent.com/1763357/215154189-9753efff-97b9-4588-92b9-d6f2fdc40188.png)
![image](https://user-images.githubusercontent.com/1763357/215155764-2de3cd98-08f2-4439-a223-a3aaa722e080.png)

**Diagnostics ID**
`f24321a5-2314-4e85-814b-678fa3cfd65b`

**Comment by JosefNemec** [comment]
What file system is it? It's definitely failing on those `c:` like files because those are not allowed under normal circumstances on Windows file systems. So file system APIs we use are probably falling apart on those.

Also I don't have a way to replicate this setup so somebody else will have to look into it.

**Comment by NekuSoul** [comment]
It's a regular NTFS partition.

I figured that this bug might be a pain to replicate. When I have some time I might look into this myself and open a PR, or at the very least try to debug to find out what and how exactly it's failing.

**Comment by JosefNemec** [comment]
Fixed in 10.10
