### ISSUE TITLE
Game description translation

### ISSUE THREAD

**Issue by PeWa48** [JosefNemec/Playnite#3281]
### Feature description

I have also proposed this idea for the metadata-local addon:

there are many games where the description is not in your own language, even when using Metadata local.
So, in such cases, why not implement a Deep-L or Google Translator translation ?
This could be implemented in Edit/F3 - Description
This doesn't seem too complicated (with the APIs available), and so we could get good translations for all games.

**Comment by JosefNemec** [comment]
One of the issues is that these APIs are not free. Google has only paid options and Deep-L has very limited free option. So from my point of view it's very unlikely to be added as a built-in option.

**Comment by PeWa48** [comment]
I didn't know that, I thought the Google Translator was free.
With Deep-L, 1000 characters are free via the website, which is enough for most descriptions.
But even so, it could still be an option and worth considering: Deep-L, for example, can be subscribed to monthly for about 5-7 euros, which would probably be worth it to most people to spend this amount once to translate their game library.

**Comment by PeWa48** [comment]
It seems that Microsoft translator could be an option: 
API:
Free per month: 2 million characters for standard translations in any combination and user-defined training

**Comment by JosefNemec** [comment]
I can't see myself implementing this any time soon. Would be imo better to be done as a separate plugin.

**Comment by JosefNemec** [comment]
Closing, should be done as an extension as this is simply out of scope for this project, especially since it's tied to external paid service.
