### ISSUE TITLE
Is it possible to add google for cover image in metadata settings?

### ISSUE THREAD

**Issue by shinobiz** [JosefNemec/Playnite#3284]
### Feature description

I found that apart from Steam, GOG and other platforms, many ancient emulator games have inaccurate covers, while Google's covers are relatively accurate, but they need to be corrected one by one, which is too inefficient. I hope it can automatically scrape according to the Gaming platform to scrape.

### Screenshots
![封面](https://user-images.githubusercontent.com/31954517/216283304-38ff01f8-d6bd-4772-b38c-9ff45ad6951f.png)

_No response_

**Comment by JosefNemec** [comment]
Not possible, you would be detected as a bot (due to amount of request) and blocked.
