### ISSUE TITLE
Add Google Play Games to Playnite.

### ISSUE THREAD

**Issue by Octavion358** [JosefNemec/Playnite#3285]
### Feature description

I want a new feature in Playnite that adds a addon to Playnite, that will allow you to connect Google Play Games to Playnite. So you can have mobile games from Google play store and from Google Play Games in Playnite. So you can see your progress, achievements, what games you play and other things in Google Play Games. It would be good to have in Playnite and that is because Google Play Games Have millions of mobile games, I hope you add that.

**Comment by JosefNemec** [comment]
I'm no longer have time creating integration plugins for additional services. I already have a lot of them to maintain. Somebody else will have to make it a community plugin.

**Comment by Octavion358** [comment]
Ok
