### ISSUE TITLE
Slovak translation

### ISSUE THREAD

**Issue by sekuka925** [JosefNemec/Playnite#329]
Here you go

[slovak.zip](https://github.com/JosefNemec/Playnite/files/1572578/slovak.zip)

**Comment by JosefNemec** [comment]
3.3 update added new string for localization:
https://github.com/JosefNemec/Playnite/commit/ec65168e6fb0f6dc207404c78f7647913441e956#diff-fc6eaa727d5578c3ac3d59652659d9e2

**Comment by sekuka925** [comment]
[slovak.zip](https://github.com/JosefNemec/Playnite/files/1583360/slovak.zip)
Updated and fixed version

**Comment by JosefNemec** [comment]
I won't be posting updates to original English files in every separate localization issue anymore. Please subscribe to new [localization updates](https://github.com/JosefNemec/Playnite/issues/385) issue to be notified when new stuff needs translation. But please keep posting your updated files in appropriate language issues. Thanks

**Comment by JosefNemec** [comment]
Localization have been completely move to Crowdin: https://crowdin.com/project/playnite

Please join the project there to submit updates.
