### ISSUE TITLE
How to start the switch game directly through playsite and then automatically turn it into full-screen mode.

### ISSUE THREAD

**Issue by GTAIMPK** [JosefNemec/Playnite#3291]
### Feature description

Can you tell me how to start the direct full-screen mode of the switch game? Now starting switch games through playnite is windowed. How to start directly through playnite and then turn it into full-screen automatically. Thank you

**Comment by JosefNemec** [comment]
You will most likely need to add some startup argument to an emulator you are using.

This repository is for tracking of issues and feature requests. Please use reddit or Discord for general questions like this one.
