### ISSUE TITLE
Make Desktop Mode ontop of the Taskbar

### ISSUE THREAD

**Issue by dr757** [JosefNemec/Playnite#3293]
### Feature description

Please add a feature to make Desktop Mode ontop of the Windows Taskbar and also take full screen size. or basically just turning Desktop Mode into Fullscreen Mode. 

As the taskbar just ruins the clean ui of Playnite. Thank you.

**Comment by JosefNemec** [comment]
I don't know if this feature make sense for Desktop mode. Why not just set task bar to auto-hide?

**Comment by dr757** [comment]
Thanks for the response.
The thing is that i always use the taskbar. And the auto-hide taskbar feature from windows is too annoying. So i have to have it always on.

i actually made an ahk script that right clicks the taskbar, goes into taskbar settings and toggle auto-hide taskbar and altF4 the the taskbar settings menu. But it just too cumbersome.

It would so awesome if there was just a checkbox to make Playnite Desktop take the full screen.!

**Comment by domportera** [comment]
I use 7+Taskbar Tweaker to allow me to auto-hide the task bar with a simple middle-click. I don't use this for playnite but it seems like it'd serve the same purpose for you

**Comment by JosefNemec** [comment]
This doesn't make sense for desktop style applications and would actually require us to hack this feature into UI library we are currently using. Closing because of that.
