### ISSUE TITLE
I can't delete some games for my library playnite

### ISSUE THREAD

**Issue by MilesDeka** [JosefNemec/Playnite#3294]
### Bug Description

I try to delete a game or open it but it crashes at the time warning me of a message, please fix this!

### Diagnostics ID

15f6f5a1-a52b-420f-bfe3-5ec0fed56905

### Screenshots

![image](https://user-images.githubusercontent.com/124748429/217403946-e5c88077-5999-4818-95c0-008525752554.png)

**Comment by JosefNemec** [comment]
Library files are corrupted. Go to `%AppData%\Playnite\library` and upload .db files you see there, I'll see if I can fix them.
