### ISSUE TITLE
[Feature Request] Implementation of simple in-built and lightweight Internet browser in Playnite desktop app. 

### ISSUE THREAD

**Issue by callisto-christopher** [JosefNemec/Playnite#3296]
### Feature description

This is just an feature idea/concept, not really useful but I will be very happy if it really happened. It will be very simple and lightweight browser that you can open it with from the button called "Browser" from the Side bar in Playnite desktop mode. It can able to browse the Internet, open few tabs (number of tabs should be capped to like 5 or 10 so it don't become resource heavy for the Playnite since browsers often consume lot of RAM's), save gaming-related pages like IGN, PCgamingwikia etc as favorites so you can access it anytime when you're not gaming. It is useful if we don't always want to open the external browser to check guides, walkthroughs, benchmarks etc since sometimes it will be annoying and also looks cool if we can view it within Playnite user-interface. Best example I can give you is Browser widgets for Xbox game bar where it does exactly what I am saying, but Playnite devs might do better job.

If anyone who're seeing this and agree with my concept, please don't simply scroll past, but instead comment that you agree so this feature gathers demand and Crow and other devs can make it true! Thanks!

**Comment by JosefNemec** [comment]
#138

**Comment by callisto-christopher** [comment]
Do you have any time estimation when this feature get's available?

**Comment by JosefNemec** [comment]
No estimate, it's not a priority right now. Also I'm afraid there's no such thing as "lightweight Internet browser". All browser engines are heavy if you want all modern day web features. We will be using Chromium based engine for it.

**Comment by callisto-christopher** [comment]
Yeah I know browsers are not cheap feature to use at least in terms of RAM usage, but still I have saw few websites having headlines like "Top 10 Lightweight Browsers" or "Browser that use less RAM" which some have like small and open source browsers listed in them, so I said in that way if it makes any sense. 
Also what do you mean by "modern day web features"? It doesn't need to have features like It's own extensions, VPN, themes, adblock etc, it's okay if it's very basic that do the above mentioned tasks during it's release.

**Comment by chocolatechipcats** [comment]
> Also what do you mean by "modern day web features"? It doesn't need to have features like It's own extensions, VPN, themes, adblock etc, it's okay if it's very basic that do the above mentioned tasks during it's release.

Being able to render anything that isn't 1996 Geocities, likely.

**Comment by callisto-christopher** [comment]
I don't know anything about Geocities, but I am not hoping that it should use like 10-20 MB of RAM. As long as this feature uses less than 200 MB of RAM, I am fine with it. Also not strictly anything more that since we're compromised much of the extra features of today's common Internet browsers.

**Comment by TheusReis** [comment]
Hello folks, I'm not sure if this browser project is still ongoing, but it would be good to take a look at how the Heroic Launcher does it, if I'm not mistaken it loads the stores through a "browser" and doesn't impact the launcher's performance.
