### ISSUE TITLE
Added additional language support for the Steam library coverimage

### ISSUE THREAD

**Issue by kwk-36l** [JosefNemec/Playnite#3298]
### Feature description

The problem is that even if you choose another language, the coverimage will still be in English. So I hope the coverimage will also be supported in another language. That means I just need to add the language suffix at the end of the url where you get the coverimage.

For example:
Game:ASTLIBRA ～生きた証～ Revision
Default:    https://cdn.akamai.steamstatic.com/steam/apps/1718570/library_600x900.jpg
Chinese:   https://cdn.akamai.steamstatic.com/steam/apps/1718570/library_600x900_schinese.jpg
Japanese: https://cdn.akamai.steamstatic.com/steam/apps/1718570/library_600x900_japanese.jpg

Of course, many games don't have cover in other languages, so just go with the default.
Thanks.

**Comment by JosefNemec** [comment]
This would have to be handled on Steam plugin's side.
