### ISSUE TITLE
Crash when draging text of "edit game details window" fields

### ISSUE THREAD

**Issue by X4Lo** [JosefNemec/Playnite#3299]
### Bug Description

Playnite crashes once I try to drag text of **Edit Game Desciption Window** text fields.

**Note:** I tried multiple themes (including the default theme) so it's not theme related.

### To Reproduce

- Open the **Edit Game Description Window** of any game.
- Select a part of/all of the text of a textbox.
- Try to drag it with the mouse.

### Diagnostics ID

2632f2d3-de6f-4d90-a4df-7a22115b2cbc

**Comment by JosefNemec** [comment]
I can't reproduce it on my system and crash log doesn't make much sense to me. I suspect it's caused by description editor plugin you have installed, try disabling it to see if it fixes the issue.

**Comment by X4Lo** [comment]
I disabled the **description editor plugin** but I still get the same crash.

**Comment by JosefNemec** [comment]
Does it still occur if you restart Playnite in safe mode from Help menu?

**Comment by X4Lo** [comment]
Yup it does even in safe mode..

![image](https://user-images.githubusercontent.com/58141750/218397805-611e063d-db62-4c0d-b56f-5650660301aa.png)

**Comment by JosefNemec** [comment]
No idea then. The crash doesn't happen in our code, but in core .NET library, I don't think there's anything I can do about it myself, also still unable to reproduce it myself on any of my systems.

```
System.Runtime.InteropServices.COMException (0x80004005): A drag operation is already in progress

A drag operation is already in progress

   at MS.Win32.UnsafeNativeMethods.DoDragDrop(IDataObject dataObject, IOleDropSource dropSource, Int32 allowedEffects, Int32[] finalEffect)
```

**Comment by X4Lo** [comment]
I found out that draging text wasn't working at all, not just in Playnite but all my other apps like ms word, vs code...
I'm no sure where that problem was coming from, but after restarting my pc it is working again and Playnite is not crashing.

Thanks for the assistance!
