### ISSUE TITLE
Brazilian Portuguese Translation for Playnite

### ISSUE THREAD

**Issue by RubeensVinicius** [JosefNemec/Playnite#330]
Really nice to see this amazing program with multiple languages support. So I made one for my language. 😃 

But there's parts of the UI that aren't "responsive" enough, and it's cutting some text. Can you take a look at that?

[brazilian.zip](https://github.com/JosefNemec/Playnite/files/1572797/brazilian.zip)

![playniteui_2017-12-19_16-30-51](https://user-images.githubusercontent.com/15078228/34172958-e179bcd0-e4da-11e7-87e3-8e666d3f4448.png)
![playniteui_2017-12-19_16-31-50](https://user-images.githubusercontent.com/15078228/34172959-e2898380-e4da-11e7-9f90-ae7c944feeb5.png)
![playniteui_2017-12-19_16-33-17](https://user-images.githubusercontent.com/15078228/34172960-e2d17924-e4da-11e7-805f-8ea2e0790997.png)

**Comment by JosefNemec** [comment]
3.3 update added new string for localization:
https://github.com/JosefNemec/Playnite/commit/ec65168e6fb0f6dc207404c78f7647913441e956#diff-fc6eaa727d5578c3ac3d59652659d9e2

**Comment by RubeensVinicius** [comment]
Updated for the version 3.3
[brazilian.zip](https://github.com/JosefNemec/Playnite/files/1579539/brazilian.zip)

**Comment by JosefNemec** [comment]
I won't be posting updates to original English files in every separate localization issue anymore. Please subscribe to new [localization updates](https://github.com/JosefNemec/Playnite/issues/385) issue to be notified when new stuff needs translation. But please keep posting your updated files in appropriate language issues. Thanks

**Comment by RubeensVinicius** [comment]
[brazilian 3.4.zip](https://github.com/JosefNemec/Playnite/files/1607068/brazilian.3.4.zip)

**Comment by RubeensVinicius** [comment]
[brazilian 4.2.zip](https://github.com/JosefNemec/Playnite/files/1988766/brazilian.4.2.zip)

**Comment by RubeensVinicius** [comment]
[brazilian 4.21.zip](https://github.com/JosefNemec/Playnite/files/2023968/brazilian.4.21.zip)

**Comment by RubeensVinicius** [comment]
[brazilian 4.3.zip](https://github.com/JosefNemec/Playnite/files/2073414/brazilian.4.3.zip)

**Comment by JosefNemec** [comment]
Localization have been completely move to Crowdin: https://crowdin.com/project/playnite

Please join the project there to submit updates.
