### ISSUE TITLE
桌面模式下多个库包括本地游戏库playnite里的游戏不显示了，全屏下却正常In desktop mode, the games in multiple libraries including the local game library playnite are not displayed, but it is normal in full screen

### ISSUE THREAD

**Issue by huangjiandead** [JosefNemec/Playnite#3303]
### Bug Description

我添加了steam、epic、GOG、EA APP、ubisoft connect和本地游戏库playnite,但是昨天启动后发现桌面模式下epic、GOG、EA APP、ubisoft connect和本地游戏库playnite都显示“未找到项目”，我添加的游戏都不显示了。steam库里第一次输入的账号里的游戏也不见了，但是额外账号里的游戏却还在。
这些不见了的游戏在桌面模式的搜索框里还能搜索到名字并打开，当然跳转的页面还是显示未找到项目。
这些在桌面模式下不见了的游戏在全屏模式下却一切正常显示
以下是谷歌翻译：
I added steam, epic, GOG, EA APP, ubisoft connect and local game library playnite, but after launching yesterday, I found that epic, GOG, EA APP, ubisoft connect and local game library playnite all displayed "item not found" in desktop mode, None of the games I added are showing up. The games in the account entered for the first time in the steam library are also gone, but the games in the additional account are still there.
These missing games can still be searched for and opened in the search box of the desktop mode. Of course, the redirected page still shows that the item was not found.
Games that are missing in desktop mode show up fine in full screen mode

### To Reproduce

我现在无论是重启还是进入安全模式，都这样，桌面模式下很多游戏都不见了
Whether I restart or enter safe mode, it is the same, many games in desktop mode are gone

### Diagnostics ID

a6b4c5af-ada0-427b-a029-56b1de5299e4

### Screenshots

桌面模式下的情况![本地](https://user-images.githubusercontent.com/45986985/218454068-1dc8f61f-b827-406b-b812-a1d1a117d327.png)
桌面模式下搜索到游戏的情况![黑屏](https://user-images.githubusercontent.com/45986985/218454095-7851c5dd-bff2-4bc8-b278-ba3d721b8424.png)
全屏下那些游戏正常显示
![全屏](https://user-images.githubusercontent.com/45986985/218454324-15fbdcdf-48fe-4bd4-95ac-cef5eb60c788.png)

**Comment by JosefNemec** [comment]
You have additional genre filter enabled. Open filter panel and disable it.

**Comment by huangjiandead** [comment]
@JosefNemec 
you are right，I'm an idiot
