### ISSUE TITLE
Addons update progress bar doesn't increase while downloading multiple updates

### ISSUE THREAD

**Issue by darklinkpower** [JosefNemec/Playnite#3305]
### Bug Description

Addons update progress bar doesn't increase while downloading multiple update, it always remains without progress. Ideally it should indicate the total progress.

### To Reproduce

1. Install multiple extensions
2. Initiate update process when multiple extensions receive an update.

### Diagnostics ID

🐱

### Screenshots

![image](https://user-images.githubusercontent.com/1389286/219214681-47f73433-49fe-4515-923c-37818061a4ef.png)

**Comment by JosefNemec** [comment]
I can't reproduce it, it works properly for me in 10.9 Are you sure this is not a theme issue?

**Comment by JosefNemec** [comment]
https://user-images.githubusercontent.com/3874087/219335612-0a4c5d43-b4d0-4472-8513-d544cd91ae82.mp4

**Comment by chocolatechipcats** [comment]
For what it matters, I'm not getting this issue on the Mythic theme.
