### ISSUE TITLE
Feature Request : Fullscreen resolution or ratio for 21:9 screen

### ISSUE THREAD

**Issue by Alexis67330** [JosefNemec/Playnite#3307]
### Feature description

is it possible add to define the resolution or the ration of the image for the full screen mode?

Let me explain, when you have a 21:9 screen the themes are rarely suitable, it would then be necessary to be able to define the 16:9 ratio or a resolution adapted for the correct display of the theme.

THANKS

**Comment by JosefNemec** [comment]
This has to be done on per theme basis, we can't force themes to any specific layout, that would defeat the whole idea of themes being able to change layout and style of the program. So this request is imo only valid for the default theme and that one already works with 21:9 just fine, as far as I know.

**Comment by JosefNemec** [comment]
If you are using some custom theme that doesn't work properly in 21:9, I recommend contacting its dev to fix/add support for it.

**Comment by Alexis67330** [comment]
Themes with a specific layout that goes out of the standard don't work well... I like the XBOXreborn (for exemple) theme which is problematic in 21:9 and it's not the only one (I have more in mind all this that I have tried)

The goal is not to annoy any theme developer and you for Playnite. But to make it easier for the theme developer who may not have the equipment to test their theme in 21:9 or any other ratio

**Comment by Alexis67330** [comment]
the idea is to add a parameter in playnite so that we users can adjust the fullscreen in either ratio or in definition when we have non-standard screens towards a more standard definition or ratio (16:9)

**Comment by Alexis67330** [comment]
of course if it is possible

**Comment by JosefNemec** [comment]
Theme devs can already make their themes to work in 21:9, I'm not aware of any blockers when ti comes to this. Default theme already support this aspect ratio.
