### ISSUE TITLE
Downoad MetaData from alternativeto

### ISSUE THREAD

**Issue by Alexnoj** [JosefNemec/Playnite#3319]
### Feature description

If its possible can be very useful who use Playnite for Apps too
[alternativeto](https://alternativeto.net)

**Comment by JosefNemec** [comment]
I have no plans creating any more integration or metadata plugins. I already have lot of them to maintain and simply don't have time to do more. This will have to be created as a community plugin (like many existing metadata plugins are already).

**Comment by Jeshibu** [comment]
I've had a look at alternativeto and it seems like a really poor data source for games.
- If a game belongs to a series, only the series is listed
- This means it can't (accurately) list release date, developer, publisher, description, etc
- It also makes it hard to find a game if you don't have the series listed in Playnite already
- There are screenshots but they're tiny

The only use I could maybe see is as a source for genres and logos/icons? What were you hoping to scrape from it?

**Comment by Alexnoj** [comment]
its for Apps not games. the data on apps pretty good.
