### ISSUE TITLE
It doesn't import .nds files if the game is zipped (.zip)

### ISSUE THREAD

**Issue by AlexMini2517** [JosefNemec/Playnite#3320]
**Describe the bug**
If there is a .nds file in the folder, it detects it. If the nds file is inside a zip, it doesn't. The emulator is capable of opening those zips.

**Comment by AlexMini2517** [comment]
I imported MelonDS, so I think it's a built-in profile. Where can I find the supported file format list?

**Comment by AlexMini2517** [comment]
How can I add zip?
![image](https://user-images.githubusercontent.com/76444133/221350593-ab361cdf-3f33-469e-bf45-847659f209af.png)

**Comment by AlexMini2517** [comment]
![image](https://user-images.githubusercontent.com/76444133/221351110-d1316edd-a5a3-42eb-b471-0be4ff7fa03c.png)
Tried this but it doesn't launch the game, it crashes.

**Comment by JosefNemec** [comment]
https://playnite.link/docs/master/manual/emulators.html#game-runs-properly-when-launched-manually-from-an-emulator-but-not-from-playnite

**Comment by AlexMini2517** [comment]
I found a solution:
![image](https://user-images.githubusercontent.com/76444133/221352527-e1979c2b-f992-4ab6-91d3-878e5056a62f.png)

**Comment by JosefNemec** [comment]
zip support for MelonDS built-in profile will be added via #3581
