### ISSUE TITLE
Playnite Crash report

### ISSUE THREAD

**Issue by MilesDeka** [JosefNemec/Playnite#3321]
### Bug Description

Update this please, playnite is crash when i try remove game in library

### Diagnostics ID

10.9.0.16050

### Screenshots

![Screenshot_5](https://user-images.githubusercontent.com/124748429/221332157-f404efc7-3030-4bd7-9c17-32244dbbc000.jpg)

**Comment by JosefNemec** [comment]
10.9.0.16050 is not a crash ID you got from the crash report. Please generate new diag package from About Playnite menu.

**Comment by MilesDeka** [comment]
> 10.9.0.16050 is not a crash ID you got from the crash report. Please generate new diag package from About Playnite menu.

sorry is that my internet was very bad and I couldn't get the id

**Comment by MilesDeka** [comment]
> 10.9.0.16050 is not a crash ID you got from the crash report. Please generate new diag package from About Playnite menu.

I can't generate a ID, always have a problem.

**Comment by JosefNemec** [comment]
What kind of a problem?

**Comment by MilesDeka** [comment]
> What kind of a problem?

![error playnite](https://user-images.githubusercontent.com/124748429/221382365-50adc581-297d-4bde-865f-a517bd90dc76.jpg)

**Comment by JosefNemec** [comment]
See https://github.com/JosefNemec/Playnite/wiki/Known-Issues#connectivity-issues

**Comment by JosefNemec** [comment]
No diag. package to analyze => closing.
