### ISSUE TITLE
Update README with all supported launchers

### ISSUE THREAD

**Issue by Osiris-Team** [JosefNemec/Playnite#3322]
### Feature description

I almost didnt install this because the readme and description of the project didnt include Epic Games.

### Screenshots

![image](https://user-images.githubusercontent.com/59899645/221360406-36d7f6bf-0be7-42dc-a221-5247dd3f8936.png)

**Comment by JosefNemec** [comment]
I don't think this is necessary. They are only as examples in readme, plus those showed on the screenshot are not even all of available ones.

**Comment by JosefNemec** [comment]
The list also changes with how people make additional community integrations.

**Comment by Osiris-Team** [comment]
@JosefNemec I just told you that I almost installed another launcher instead of Playnite because I thought it didnt support Epic Games... And I bet I am not the only one.
You could avoid this simply by adding the names to the description and readme, its not like its hard to do, or a crime, or any other downside to it lol?
