### ISSUE TITLE
Bunch of random letters and number games added to my library

### ISSUE THREAD

**Issue by Blokheck011** [JosefNemec/Playnite#3324]
### Bug Description

basically i recently added yuzu, it worked fine but after restarting my pc and opening playnite all these games were added. I have deleted them as there was nothing special except for the games being added.

### To Reproduce

i dont know how to reproduce, it happened when i opened playnite after  importing 2 games with yuzu emulator, and restarting my pc.

### Diagnostics ID

ee11e0f2-f36c-4185-b6db-54ccef75ba70

### Screenshots

https://user-images.githubusercontent.com/105729942/221515095-2833f063-aad4-4d50-a361-7417a8c436bc.mp4

**Comment by JosefNemec** [comment]
Based on the installation path, they are ROM files imported via Nintendo Switch scanner you are using.
