### ISSUE TITLE
Open the global search through URI

### ISSUE THREAD

**Issue by griseouslight** [JosefNemec/Playnite#3326]
### Feature description

Allow opening the global search menu through a URI call such as `playnite://search`.

My use case is that I already use a global hotkey for a command palette (PowerToys Run), and would like to open it through there instead of having a separate command.

**Comment by griseouslight** [comment]
This was simple enough to make a short plugin for, so I've made my own bare-bones project for it [here](https://github.com/griseouslight/Playnite-URISearch), if this use-case is niche enough for only me to really want it.

**Comment by fl4shback** [comment]
Hi!
Thanks for making that, was just starting research about this today.

Do you have to type the URI manually in powertoys or am I missing something ?

**Comment by JosefNemec** [comment]
Done in master. It will usable as `playnite://playnite/search` or `playnite://playnite/search/quake%203` for specific search query.
