### ISSUE TITLE
$SourceAction does not work in post-scripts unless either of the other 2 scripts have lines in it

### ISSUE THREAD

**Issue by akumenon** [JosefNemec/Playnite#3328]
### Bug Description

Hello,

I mentioned this bug on Discord that I'm posting it here as requested, regarding game scripts that execute before starting a game, after the game is started, and after the game has exited. Going forward I will refer to them as pre-script, mid-script, and post-script for conciseness.

As the title implies, `$SourceAction` does not work in post-scripts. This bug occurs exclusively for games that Playnite runs the exe of i.e. not Steam, or other library games. My test script `$PlayniteApi.Dialogs.ShowMessage("$SourceAction")` shows up blank, but when run through the "Test script" button, it works.

Interestingly, if either the pre-script or mid-script have any lines in them (even something like `echo .`), the post-script works again.

Hope this is descriptive enough, but if it isn't, please let me know.

Thanks for your time and all the hard work you put into Playnite.

P.S. I don't think a diag package is required for this but I'm creating one since the form asks me to.

### To Reproduce

1. Have a game/play action that points to an executable.
2. Edit the game and in the scripts tab, enter `$PlayniteApi.Dialogs.ShowMessage("$SourceAction")` as the post/exit script. Testing the script via the button will work, and show you a popup of the contents of `$SourceAction`.
3. Save and run the game, then exit it.
4. You'll see a blank popup and instead of what you saw when you tested it.

As a workaround to this, add `echo .` to either the pre or mid-script, save, run, and exit the game.
You'll now see that the popup shows the correct info.

### Diagnostics ID

d18634a3-6a36-4d0f-9422-484c7ead275b

**Comment by JosefNemec** [comment]
Fixed in mater
