### ISSUE TITLE
I tried to import my backup but failed

### ISSUE THREAD

**Issue by sunencheng** [JosefNemec/Playnite#3329]
### Bug Description

I backuped my playnite last year,the file is PlayniteBackup-2022-11-28-09-42-32。
When i tried to restore my data after a system crash ,i follow this manual [Data Backup
](https://playnite.link/docs/master/manual/backup.html)
But ,I got the error like this 
![image](https://user-images.githubusercontent.com/8297524/222921589-1a3fa27c-23ea-47b8-a5ce-5f7f95ffa28b.png)
This is my restore.json file
[restore_config.zip](https://github.com/JosefNemec/Playnite/files/10889317/restore_config.zip)
this is my shortcut destination :G:\Application\Playnite\Playnite.DesktopApp.exe --restorebackup "‪C:\Users\admin\Desktop\restore_config.json"
Is there anything wrong with what i did ?

### Diagnostics ID

f09d02fd-9bad-4893-be2f-22fb96006a58

**Comment by JosefNemec** [comment]
Try moving that json file into a different location and running backup from there. It looks like some permission issue, Playnite process can't read that file for some reason.

**Comment by sunencheng** [comment]
Thx,i tried that.No error,but i don't think it worked.
I started playnite with new shortcut,but it dispear after restore, and i start  .exe ,i don't think my data has been restored.

**Comment by JosefNemec** [comment]
Does restore work if you do it manually from library menu? If so, then your json config is broken.

**Comment by sunencheng** [comment]
It works. Thanks.
