### ISSUE TITLE
Make Playnite more portable

### ISSUE THREAD

**Issue by RubeensVinicius** [JosefNemec/Playnite#333]
Would it be possible to add support for the Playnite folder as a variable in the database, working and install directory fields? Something similar to the _{InstallDir}_ we have atm.

So, if the .db file is on the Playnite folder and the games on subfolders, the database path would be something like _"{AppDir}/library.db"_ and the game Install Directory _"{AppDir}/apps/Tetris"_.

It would really help when using Playnite as a launcher for games on an external drive that doesn't have the same driver letter on different computers.

**Comment by JosefNemec** [comment]
Released in 3.4, you can now use `{PlayniteDir}` variable in path strings. The database path doesn't accept it, but leaving the path with just file name will make it to use program's folder (just set it to `library.db`).

**Comment by AFaustini** [comment]
I have some new ideas to improve this portability:
Support for Recursive Path by default
For example:
My Playnite instalation (in a external drive) is in G:\Playnite and my games instalation is in G:\Videogames.
When my Rom Path is "G:\Videogames\SNES\Super Mario World.zip" in the program my path shows "..\Games\SNES\Super Mario World\Super Mario World.zip"
