### ISSUE TITLE
Separate 'Hide this game' and 'Edit...' buttons more in right-click menu

### ISSUE THREAD

**Issue by Ohhhboyyy** [JosefNemec/Playnite#3332]
### Feature description

I've been doing a lot of manual editing on games recently for some uncommon platforms, and I've noticed that I accidentally click "Hide this game" instead of "Edit..." in the right-click menu with some regularity. It's user error and not a bug, but it may be beneficial to some people's workflows to have these buttons further apart. 

### Screenshots

![image](https://user-images.githubusercontent.com/14195586/223138567-d2d2a1ea-63d2-4962-addd-bc6b4b035939.png)

**Comment by JosefNemec** [comment]
Will be done via #1772
