### ISSUE TITLE
Group by Favorite status

### ISSUE THREAD

**Issue by mixels** [JosefNemec/Playnite#3336]
### Feature description

One of nicest quality of life features of Steam when viewing the Steam Library is that the Steam Library view groups games marked as Favorites together at the top of the games list. This is a very nice feature. I don't currently see any way to do this in Playnite. Kindly consider adding this feature. Since you can currently only group by one grouping method at a time, I don't foresee this causing problems.

See the attached screenshot of the Steam Library grouping by favorites feature.

Thank you!

### Screenshots

![image](https://user-images.githubusercontent.com/7928577/224489124-a1b20e6e-1c2b-4e7b-b751-cd27abf9fe07.png)

**Comment by chocolatechipcats** [comment]
In general, I can also see a multisort being useful.

**Comment by JosefNemec** [comment]
#207
