### ISSUE TITLE
Add emulators-like script behaviour for game clients

### ISSUE THREAD

**Issue by ld892012** [JosefNemec/Playnite#3337]
### Feature description

Give possibility to start script before/after a game client (Steam, Epic,...) or just for games without client like it is already possible for emulators.

Some example :
- Launch Antimicro to bind Guide button to correct client's overlay shortcut (and windows overlay for games without client)
- Set a custom closing client time to a specific client (using after script instead auto close parameter)
- Launch client in specific mode before play game (Steam BP for example)
- Create an unique script that mount correct disc image in right letter with appropriate software and load good controller profile with appropriate software (and game script just store files location variables)

It can be already done with global script but it gives an huge script with lots of conditions, it can be more clear.

### Screenshots

![image](https://user-images.githubusercontent.com/17686344/224536861-fda0948d-2b0c-4497-b37a-ef0c0ffcf9ed.png)
![image](https://user-images.githubusercontent.com/17686344/224536938-6014d1ee-6815-4273-ba1c-35ad08362789.png)

**Comment by JosefNemec** [comment]
This is virtually not possible to do because Playnite has no idea if/when 3rd party client is being launched. Even library plugins themselves often don't know this if they are using URI protocols to run games.
