### ISSUE TITLE
Make Playnite only get posters for images.

### ISSUE THREAD

**Issue by eddiestrike** [JosefNemec/Playnite#334]
When downloading metadata, there should be an option to make Playnite only get Posters.

Half my collection has posters, while the other half has the smaller icon images and it ruins the look of playnite.

Here's what i mean: https://imgur.com/a/YiYb7

If I right click one of the small posters and edit them one-by one, IGDB will replace the small icon with a big poster, but it should do this by default imo.

**Comment by JosefNemec** [comment]
It depends on what settings have you selected on metada download dialog and whether Playnite was able to automatically detect correct IGDB game from game name.

To get best results select "IGDB -> Official Store" option as source for cover images. That will try to download image from IGDB and if not available (or detected) it will use the smaller image from Steam.

**Comment by eddiestrike** [comment]
Thanks, it worked.

Shouldn't that be the default option since it's way better and most game detect fine from IGDB?

**Comment by JosefNemec** [comment]
I intentionally made it not default, because we had limit on how many API calls we can make to IGDB. That's not an issue anymore so I'll change it.

**Comment by JosefNemec** [comment]
Released in 3.3

**Comment by By6r9** [comment]
With planned in 4.4 metadata downloading improvements, it would be nice to have option to separate metadata and covers downloading. Now, if you set cover from one source, it will be overwritten anyway after searching for metadata in other source. 

(In Launchbox, old media is not deleted, and new ends with -02/-03/ etc. suffixes which leads to repeating files with same content, but it is better than losing meticulously set data)

**Comment by JosefNemec** [comment]
@By6r9 You can choose to download metadata only for missing fields and covers (any metadata field) should not be overwritten in that case (also this is enabled by default). If your covers are getting overwritten then it's a bug, please open new issue for it.
