### ISSUE TITLE
Adding online backup support (upload to Google Drive, Mega, etc)

### ISSUE THREAD

**Issue by quartzbear** [JosefNemec/Playnite#3342]
### Feature description

Hi

I wanted to suggest a function that would allow the users to connect to a cloud provider and upload their Playnite backup periodically.
It could have an option to upload images (or not).
Something like I this, maybe: https://github.com/sabeechen/hassio-google-drive-backup
Thanks!

**Comment by JosefNemec** [comment]
Duplicate #108

You can technically have it right now using auto backup with target folder on a cloud drive.

**Comment by quartzbear** [comment]
> Duplicate #108
> 
> You can technically have it right now using auto backup with target folder on a cloud drive.

Well, I didn't realize that was a possibility. 
I did go down a rabbit hole into Rclone. It was... interesting. 
I was able to mount clouds as drives on the PC, but couldn't backup to them.

I guess i'll be sticking to local backups. Thanks anyway.
