### ISSUE TITLE
Items not saving when adding through "Edit Game Details" menu

### ISSUE THREAD

**Issue by lucasnake** [JosefNemec/Playnite#3343]
### Bug Description

After the new update i'm experiencing this bug where if i add an item through the "Edit Game Details" menu, like adding an Developer with the "+" button then it is not saved. In order for it to save i now need to add the Developer in Library Management and then select it in the list of Developers. Before i could simply create it through the "+" button and it would save. 

### Diagnostics ID

5fd0d173-b0ba-470b-b61f-aafd30ec8518

### Screenshots

![aaa](https://user-images.githubusercontent.com/31028678/225766769-741043c3-4bd2-40df-ae62-88dabac557b4.gif)

**Comment by yairmohr** [comment]
Now I know it's not just me...
I've been having the same issue - but I think in my case it started in the previous version. I reported it a few hours ago on Discord, and hope there's a solution soon.

https://user-images.githubusercontent.com/109385071/225768692-fa56c3f7-6b6b-41cf-943e-38105a51d09c.mp4

**Comment by Gildum** [comment]
> Now I know it's not just me... I've been having the same issue - but I think in my case it started in the previous version.

I'm still on v10.9 and here it works, so the bug must have been introduced in 10.10.

**Comment by JosefNemec** [comment]
Fixed in master
