### ISSUE TITLE
Auto hidden taskbar won't appear in full screen mode

### ISSUE THREAD

**Issue by MSBuV** [JosefNemec/Playnite#3345]
### Bug Description

I have an OLED TV so I keep the taskbar hidden by default to avoid burn in. When Playnite is in full screen mode, moving the cursor to the bottom of the screen does not make the taskbar appear. Playnite is the only app where that behavior occurs. It happens in safe mode too. Also doesn't change whether I am in the library tab or statistics tab.
Anything else works fine. OS is Windows 10, Playnite is latest version with Howlongtobeat- and Duplicatehider plugins.
If I reduce the window size of Playnite to something smaller than full screen showing the hidden taskbar with the cursor works fine.
Thank you for all your work.

### Diagnostics ID

b8c53ae4-6d5f-4d5b-bd0d-47ca217a438b

**Comment by JosefNemec** [comment]
see #1106
