### ISSUE TITLE
Show platform icons of previously played games in system tray drop down menu

### ISSUE THREAD

**Issue by woutercools** [JosefNemec/Playnite#3346]
### Feature description

Show platform icons of previously played games (who don't have a unique icon assigned) in the system tray drop down menu in stead of the default gamepad icon.

### Screenshots

![2023-03-19 15_54_33-Window](https://user-images.githubusercontent.com/16439116/226184278-09bbddbe-df76-458f-82c0-46f3fc28b55c.png)

**Comment by JosefNemec** [comment]
#1433

**Comment by woutercools** [comment]
I actually made a mistake...

What I was meaning to ask was: Show library icons of previously played games (who don't have a unique icon assigned) in the system tray drop down menu in stead of the default gamepad icon.

As Playnite does for the gameslist in the sidebar.
