### ISSUE TITLE
Show library icons of previously played games in the system tray drop down menu

### ISSUE THREAD

**Issue by woutercools** [JosefNemec/Playnite#3347]
### Feature description

Show library icons of previously played games (who don't have a unique icon assigned) in the system tray drop down menu in stead of the default gamepad icon.

As Playnite does for the gameslist in the sidebar.

### Screenshots

![2023-03-19 15_54_33-Window](https://user-images.githubusercontent.com/16439116/226191159-74d9e5d9-f1b3-4778-b6ad-bec7d46de82b.png)

**Comment by JosefNemec** [comment]
Please do not open multiple issues for the same thing. It will be solved by #1433. The fix in there will use the same icon as game lists.

**Comment by woutercools** [comment]
I'm sorry, but I just can't see how to do it.

How to select an icon per library?

**Comment by JosefNemec** [comment]
You can't fix it right now, that's why #1433 is still open.

**Comment by woutercools** [comment]
ok, that's clear... sorry about that.
