### ISSUE TITLE
metadata not downloaded for .iso.gz ps2 games

### ISSUE THREAD

**Issue by ve1la** [JosefNemec/Playnite#3357]
### Bug Description

PCSX2 can open ISOs compressed to .gz files, which is convenient to save space, so I compressed my entire collection in this format.

So to explain the problem here is an example, a .gz file name will look like this: Dragon Ball Z Budokai Tenkaichi 3 (widescreen).iso.gz
Unfortunately playnite will not be able to download metadata for the game, as it searches for "Dragon Ball Z Budokai Tenkaichi 3 .iso" instead of "Dragon Ball Z Budokai Tenkaichi 3". It thinks " .iso" is part of the file name (note: yes, for some reason it adds a space before .iso, even though there isn't one in the filename)

I'm using playnite 10.12

Could this be fixed? 

### Diagnostics ID

52d0f556-a85e-4925-af8c-368e5a8f19a9

**Comment by JosefNemec** [comment]
Fixed in master
