### ISSUE TITLE
What Playnite Could Be

### ISSUE THREAD

**Issue by JakeStorm-Dev** [JosefNemec/Playnite#3364]
### Feature description

When I first found Playnite, it was in its infancy.  But it failed to meet my requirements and I went a different directions.  Now, years later, I have a new concept in mind.  Running and managing a game library from an NAS for multisuser use and LAN/Local gameplay.  I have revisited Playnite.  It has many features that could be sent in this direction with minimal effort.  For Instance: 

The Install/Play Button:  Some of Playnite's competitors already have a functionally working Install vs Play feature built into their software.  Currently the "Install" button does not functionally install the software, nor programmable to do so.  It logically make sense as quite a large majority of gamers have digital offline copies of their games in a storage and not installed due to sheer size volume of the game.  Certain current generation games exceed 100GB - 150GB installed, leaving far less room for storage.  Likewise, many, such as myself functionally use an NAS storage solution and have multiple systems that have access to the game library.  Software on multiple devices is permitted, as even Steam's TOS states: "You may authorize Family Library Sharing on up to 10 devices at a given time, and for up to 5 accounts that may then use your game library on any of your authorized computers."  Short of fixing the issue myself and recompiling, I am pushing that this function be incorporated into the main build as a fork to correct this alone would be excessive.  Currently the work around is to reprogram the "Play" button to function as the install button via Actions tab PS Scripting (using Robocopy to a temp folder,  Start-Process with wait, and Remove-Item) with a manual change in script in place to redirect for playing.  This is a whole lot of manual input for what could be a simple function incorporated in with rudimentary scripting.  

Multiple User Preferences:  Currently no FrontEnd is utilizing multiuser function, which is a shame.    Quite a large number of households have multiple games in the home.  Access to the same game library is a given andd NAS/ home cloud storage is becoming the norm.  Likewise, Playnite stands a chance of becoming the premier tool of choice by simply beating the other front ends to the punch on this.  Again, not difficult coding and not needed in a fork.  The only item needed is the ability to place individual playlists in the sidebar drawing on the main library for reference in the immediate.  Later development could include user profiles and sign in assignment to controllers that has been already an industry staple in multiple platforms.  There is very little need to offer security protections on these assignments as they're designed for local rather than internet use.  There currently is no viable work around to this and creating multiuser extensions to do this is both creating arbitrary coding and messy at best.

Manual Input Functionality: Most FrontEnds tend to punish manual input of games into a database with broken function and/or missing or forced manual input of Metadata.  There's no particular reason outside of some folks in the distribution side of the industry (Steam and others) disconnecting non-paying customers from readily available prescraped data.  this is frustrating to users and many have complained and always to no avail.  To improve functionality, Metadata sources should be open ended to choice of user.  There are several sources that contain information not captured by the bigger names in sourcing.  A prime example is numerous Indie titles or certain types of games such as Adventure Games, Hidden Object Games or Time Management Games.  While certain sources contain this information such as Big Fish, AdventureGamers, etc.  These sources are missing from Playnite and are crucial to gathering data on such games.

System Requirements: Largely missing functionality from the Metadata within Playnite is the System Requirements field.  While it can be added and a system check implemented by extension, this is a basic functionality that can and would set Playnite apart from competitors.  Most have some non-parsable entry points for system requirements, but none currently support it through verification.  In most homes or locations with multiple systems, they're not all equal spec, and not all are capable of running all games in a library.  Even if it can be flagged and filtered manually though categories, filters, or tags, it can and should be a regular field within Playnite.

Network Support: As mentioned prior, Playnite as a portable platform has great possibility for use on a network.  It is likewise possible to add functionality to that end.  Most of Playnite's functions are useable without issue but additional documentation can and should be considered.  

In the end, all of these concepts can and should be implemented in the main version.  If not, a proposed fork to incorporate these items could overtake the main program.   Playnite could be the premiere Frontend for game libraries both on the cloud and on local machines.  Leaning more heavily into the multiuser environment will win many fans on the fence with which FrontEnd to choose and current user will be getting a much sought after functionality.  In the meantime, I'll continue to review Playnite's coding and keep an eye on other open source platforms as I'm still seeking a solution.   Feel free to comment, or if any are interested in these functions as a fork, let me know.  Thanks.

-Jake Storm

**Comment by JosefNemec** [comment]
> The Install/Play Button

Not planned. Different people have different setups and it would be virtually impossible to make this universal enough to cover most use cases. Or at least it would be a ton of effort for a feature that I imagine most people would not use.

> Multiple User Preferences

The only thing that is planned related to this is some sort of account system based around parental controls.

> Manual Input Functionality

I don't understand how is this proposal any different to current metadata plugin system.

> System Requirements

Extension for this already exists. Built-in support is a no go since there's no reliable database that would provide this info for most games and also had stable API we could use.

> Network Support

No idea what you mean by this. You don't mention any specific use case.

> In the end, all of these concepts can and should be implemented in the main version.

I don't know why are you so sure that these proposals can and should be implemented. There are technical limitations and big implementation/maintenance cost to lot of what you propose.

> If not, a proposed fork to incorporate these items could overtake the main program.

You are free to start your own fork implementing these proposals.

Also, please do not bunch more that one feature request or suggestion into a single GitHub issue, it makes it impossible to manage. Thank you
