### ISSUE TITLE
Sort by Steam rating

### ISSUE THREAD

**Issue by putovoador** [JosefNemec/Playnite#3366]
### Feature description

Pretty much the title.
The sorting system by user score is bad. On "community score", I can see some random "mostly positive" games alongside actually good games, like Portal 2 or Hades. And of course, hunders of games are on the "None" tab.
"Critic score" is somewhat better, but I got even more games on "none" tab.
"User score" is not working ):

My suggestion would be to add a "Steam Score" and rate all games by how steam users rated them: Overwhelmingly Positive to Negative.

Love this software. Mainly downloaded it to find hiddem gems along all these launchers. The integrations are great too!

### Screenshots

![Screenshot_1](https://user-images.githubusercontent.com/28831588/229315777-62a25216-9346-46c9-8a18-adf56a53e26a.png)
![Screenshot_2](https://user-images.githubusercontent.com/28831588/229315778-a2a00c84-dfe9-4c60-91ae-dee3b1a4b9ee.png)
![Screenshot_3](https://user-images.githubusercontent.com/28831588/229315780-f0152cac-f15e-4c40-b1b5-3cdb0d8c39a3.png)

**Comment by HerrKnarz** [comment]
The critic and community score fields are populated by the metadata addons. If you set the steam store as the first (or only) source for community score and redownload metadata, you get basically what you want. If you have games from other stores, that also have a steam page, download the "Universal Steam Metadata" addon and set that one as the source for community score. That addon also gets the steam ratings for games, you have on other libraries than steam (if they're also available on steam).

The user score is meant for your own score, by the way. If you don't rate games yourself in Playnite, the field remains empty of course.

**Comment by JosefNemec** [comment]
As HerrKnarz said, this is already supported if you fetch metadata from Steam, closing.
