### ISSUE TITLE
PCSX2 Nightly latest executable name not supported

### ISSUE THREAD

**Issue by alessandrobaldazzi** [JosefNemec/Playnite#3367]
### Feature description

As in the issue #2871, one of the current executable names for the pcsx2 nightly is not supported by any profile.
The latest executable downloaded from the official site has the name "pcsx2-qt.exe".

**Comment by JosefNemec** [comment]
They really need to stop constantly renaming executables.

**Comment by JosefNemec** [comment]
Fixed in 10.13
