### ISSUE TITLE
Update Bizhawk

### ISSUE THREAD

**Issue by Coloradohusky** [JosefNemec/Playnite#3374]
### Feature description

Bizhawk 2.9 just released, and I just found out about this project, so figured I'd open a request to update Bizhawk's YAML. 
Add to Bizhawk:
-Nintendo DS/DSi
-Atari Jaguar
-TI-83
-TIC-80
-Magnavox Odyssey 2
-Uzebox
-Vectrex
-MSX

New platforms needed:
-Nintendo DSi
-TI-83
-TIC-80
-Magnavox Odyssey 2
-Uzebox

I can submit a pull request for these, just let me know if about specifics (ie, if you want DS and DSi to be the same)

**Comment by JosefNemec** [comment]
We currently don't have separate platforms for DS and DSi. Not sure it's worth differentiating between them in this case.

https://github.com/JosefNemec/Playnite/tree/master/source/Playnite/Emulation

**Comment by Coloradohusky** [comment]
Some emulators (Desmume) don't support DSi, while MelonDS (and by extension, Bizhawk and RetroArch) does support DSi

**Comment by Coloradohusky** [comment]
Fixed in #3378
