### ISSUE TITLE
'Xinput Device Support' setting reverts to its default behaviour upon losing and regaining window focus

### ISSUE THREAD

**Issue by Michael-Ingraldi** [JosefNemec/Playnite#3375]
### Bug Description

Even with 'Xinput Device Support' disabled, Playnite (fullscreen) will start responding to Xbox controller inputs upon losing and regaining window focus. This will also happen upon launching and exiting a game. This setting must be enabled and re-disabled every time thereafter.

### To Reproduce

1. Launch Playnite in fullscreen mode
2. Go to Settings > Input and disable 'Xinput Device Support' to block inputs from Xinput devices (requires relaunch)
3. After Playnite relaunches, switch focus from Playnite to another window
4. Switch focus back to Playnite

Upon returning to Playnite, 'Xinput Device Support' reverts to its default behaviour and starts responding to controller inputs again. Although, it still _appears_ to be disabled in the settings.

### Diagnostics ID

364ee81e-4ac4-4daf-9f71-4e561568a2be

### Screenshots

![xdev](https://user-images.githubusercontent.com/72154645/230783911-33fa1285-1a7e-4dd7-9706-4876995a8182.png)

**Comment by JosefNemec** [comment]
Fixed in master
