### ISSUE TITLE
Unresponssive game list

### ISSUE THREAD

**Issue by AestheticPixels** [JosefNemec/Playnite#338]
Sometimes when you search something using the search bar or select a filter the game list doesn't updates requiring you to restart Playnite

**Comment by JosefNemec** [comment]
Can you possibly make a video of this behavior? Otherwise it's hard for me to pinpoint the cause of it. Also please go to "About" menu and attach diagnostics package. created from there Thanks you

**Comment by JosefNemec** [comment]
Fixed in 3.3 by f2fe3b36e6343d689ff108fe602000d04aad9e58
