### ISSUE TITLE
Playnite prevents PC from turning off display and sleeping

### ISSUE THREAD

**Issue by rumblerosesxx** [JosefNemec/Playnite#3380]
### Bug Description

Since updating to 10.14 my PC stopped turning off the display and going to sleep mode automatically. It seems this only happens when playnite is running (including in minimized to tray mode). I'm running Windows 11. Please let me know if I can provide any additional info.

### To Reproduce

Just having playnite running seems enough, 

### Diagnostics ID

fd7e7837-f605-4471-b34c-ca3b16c1a679

**Comment by rumblerosesxx** [comment]
I should have done more testing before posting, running playnite turned out to be a red herring. After reseating all my usb devices the issue is fixed and PC sleeps with playnite running.

**Comment by JosefNemec** [comment]
#2932
