### ISSUE TITLE
Library Tag Merge

### ISSUE THREAD

**Issue by Caraamon** [JosefNemec/Playnite#3382]
### Feature description

It would be nice if when in the Library Manager screen, if you renamed something like a Genre to match that of an existing one, it would ask if you'd like to merge the two terms.

When downloading from multiple metadata sources, they often use similar but different phrases for genres, features, tags, etc., and it would be nice for smooth merging. Otherwise, I have to manually select them with filters, edit, remove one term, and add the second.

Thanks for your time.

**Comment by chocolatechipcats** [comment]
See #1270

**Comment by Caraamon** [comment]
My google-fu failed me.
