### ISSUE TITLE
Fresh install "Failed to open library database"

### ISSUE THREAD

**Issue by RandallCurtis** [JosefNemec/Playnite#3388]
### Bug Description

Win 11 fresh install of 10.4 (tried portable and non) in the default location. Error appears on first startup with "Failed to open library database". I can continue to the main UI but I'm unable to add games and trying to open settings results in a full crash. I thought maybe I had a lingering library from a previous install so I uninstalled, deleted all Playnite folders and re-installed. Still opens with the same error and I'm unable to generate a diagnostics package. No conflicting AV or utilities are running as far as I can tell.

[playnite.log](https://github.com/JosefNemec/Playnite/files/11328167/playnite.log)

### Diagnostics ID

N/A

### Screenshots

![image](https://user-images.githubusercontent.com/114831222/234444622-5f0d7431-7aba-4dad-aaaa-8f9ab39ff28f.png)

**Comment by JosefNemec** [comment]
Are you using Atlas OS, Tiny 11 or some other similar custom Windows edition?

**Comment by JosefNemec** [comment]
I'm asking because this looks like broken .NET Framework installation and I've seen that only on these customized Windows editions.

**Comment by JosefNemec** [comment]
4.8 is correct

**Comment by RandallCurtis** [comment]
Installed .NET Framework 4.8.1: [https://dotnet.microsoft.com/en-us/download/dotnet-framework/net481](url), ran Windows update and restarted. Playnite runs correctly now. Not sure what happened with my 4.8 install but forcing an update/repair with the latest version seems to have fixed it.
