### ISSUE TITLE
Option to unload all views when closed to tray

### ISSUE THREAD

**Issue by AestheticPixels** [JosefNemec/Playnite#339]
Playnite uses ~150Mb RAM when using it and even when not using it.

[Diagnose.zip](https://github.com/JosefNemec/Playnite/files/1575873/Diagnose.zip)

**Comment by JosefNemec** [comment]
I think 150MB is perfectly reasonable in normal scenarios (at least compared to apps similar to Playntie). We might do some improvements like unloading all data when application is closed to tray.

**Comment by JosefNemec** [comment]
Will be implemented as part of #60
