### ISSUE TITLE
Corrupted Library

### ISSUE THREAD

**Issue by EleventhEric** [JosefNemec/Playnite#3394]
### Bug Description

I can launch into Playnite fine and use it like normal with two exceptions.

When I try to manually add a game it tells me that my library is corrupt and shuts down.
I generated the diagnostics files. The id is: b6ad5e37-14ce-41f7-8f40-74a6c4afe9fb

I also noticed that the xCloud extension shows an error on launch that says "Failed to import games from XCloud. Unable to cast object of type 'LiteDB.EmptyPage' to type 'LiteDB.HeaderPage'." I'm assuming it has to do with the database corruption that my library is facing though I suppose it could be unrelated.

Let me know if you need any other info.

### Diagnostics ID

b6ad5e37-14ce-41f7-8f40-74a6c4afe9fb

**Comment by JosefNemec** [comment]
Go to `%AppData%\Playnite\library` and send me all `.db` files you find there, I'll try to fix them.

**Comment by EleventhEric** [comment]
I have attached the db files.
[library.zip](https://github.com/JosefNemec/Playnite/files/11398630/library.zip)

**Comment by JosefNemec** [comment]
The zip you attached has only one .json file inside.

**Comment by EleventhEric** [comment]
Ah, it looks like 7zip couldn't access the files since I still had Playnite open. My apologies. I have attached the corrected zip.
[library.zip](https://github.com/JosefNemec/Playnite/files/11409391/library.zip)

**Comment by JosefNemec** [comment]
Here's fixed file: [games.zip](https://github.com/JosefNemec/Playnite/files/11412070/games.zip)

**Comment by EleventhEric** [comment]
That fixed it! Thank you very much for your help. Also, thank you for this amazing program. It has been exactly what I needed to wrangle all of the various game stores in one place.
