### ISSUE TITLE
Corrupt icons when importing games

### ISSUE THREAD

**Issue by flepperdeplep** [JosefNemec/Playnite#3395]
### Bug Description

When adding some older games (it especially seems to happen with older GameMaker games in my case) the icon is imported incorrectly, as shown in the screenshot.

### To Reproduce

I've uploaded some example games to [here (MediaFire)](https://www.mediafire.com/file/c45egr84i00zxol/broken_icons.7z/file) (50mb download).

### Diagnostics ID

bfffa34e-c2ec-4795-9ca1-311e4edbe8a4

### Screenshots

![Clipboard01](https://user-images.githubusercontent.com/132608941/236297866-361b514c-162b-4992-a995-46492de52f91.png)

**Comment by Jeshibu** [comment]
Do you know what metadata provider supplied the icons?

**Comment by flepperdeplep** [comment]
These are the icons from the executable files, which is why I provided some examples. They show up fine for me in Windows explorer etc but not in Playnite.

**Comment by JosefNemec** [comment]
It's an issue in UI toolkit we use. I'm guessing this icon format from old GameMaker is not fully standard complainant and our UI library can't render them properly. We would have to implement our own ico format drawing solution, which is not worth it just to fix this specific issue.
