### ISSUE TITLE
Wasted space in the game info box

### ISSUE THREAD

**Issue by CorruptComputer** [JosefNemec/Playnite#340]
I looked and didn't find anything open about this, but all that space is wasted and it causes some descriptions to have to be scrolled to fully read.

![image](https://user-images.githubusercontent.com/5573038/34225502-531554f6-e58c-11e7-9399-0ce47a3f3bf5.png)

**Comment by JosefNemec** [comment]
The idea was to show off the background artwork, but I might change it.

**Comment by CorruptComputer** [comment]
I really like the way Steam does it, it doesn't have that space, but rather makes everything else transparent (looks like Playnite already is). So you'll still be able to see the picture, the only other suggestion would be to make the image show up a bit better, as right now they are barely visible.

**Comment by JosefNemec** [comment]
Released in 3.3
