### ISSUE TITLE
Unable to Create New Category/Categories from right-clicking

### ISSUE THREAD

**Issue by Firethorn43** [JosefNemec/Playnite#3400]
### Bug Description

Currently, I have 3 categories, and wanted to make a 4th one, but the 'Add Category' button is unresponsive. I can still add a game to an existing category, but not create a new one via right-clicking the game and selecting "Set Category". I can still add or remove categories from Library Manager.

### Diagnostics ID

0abf1b49-e973-4866-ba90-9dfbb3a42a8f

**Comment by JosefNemec** [comment]
Can't reproduce. Are you actually writing down new category name into the text box next to add category button?

**Comment by Firethorn43** [comment]
Ah, I see. I didn't realize I needed to type there first because of my theme.
