### ISSUE TITLE
Achievement don't pop when playing steam games

### ISSUE THREAD

**Issue by Vaportone** [JosefNemec/Playnite#3403]
### Bug Description

Achievements don't activate while launching steam games, so if I click play in Playnite I won't get achievements while playing

### To Reproduce

starting and playing a steam game by hitting play in Playnite

### Diagnostics ID

f5687a60-35b7-4b57-bab2-a554dd9a0257

**Comment by JosefNemec** [comment]
You need to let Steam games to be imported and launched via Steam integration plugin.

**Comment by JosefNemec** [comment]
If you are already doing that, then it's a Steam issue. Steam plugin uses `steam://` URI to launch games (like Steam's desktop shortcuts) and then it's up to Steam how a game launches and runs.
