### ISSUE TITLE
consolidate duplicate game entries

### ISSUE THREAD

**Issue by PeWa48** [JosefNemec/Playnite#3404]
### Feature description

It happens more often that you own a game more than once, for example on GOG and Steam.
This happens more and more often, especially with game collections like Humble.
In most cases, the double entry in the game list makes no sense and only disturbs or makes the list unnecessarily large.
I would like to see a scan option that detects the duplicate entries and makes only one entry from it with listing of the sources (so e.g. Steam, GOG).
That is completely sufficient. Perhaps also additionally with a visual display at the icon that games are duplicated here.

**Comment by JosefNemec** [comment]
duplicate

**Comment by Jeshibu** [comment]
Use [the DuplicateHider plugin](https://playnite.link/addons.html#felixkmh_DuplicateHider_Plugin)

**Comment by chocolatechipcats** [comment]
> duplicate

I love the irony

**Comment by JosefNemec** [comment]
It is planned for P11, but there's been multiple issues for this opened already.
