### ISSUE TITLE
Latest version (10.16) doesn't show steam launch options when starting a game

### ISSUE THREAD

**Issue by maurinhozonasul** [JosefNemec/Playnite#3406]
### Bug Description

As the title says. When you launch a steam game from playnite, if the game has multiple launch options, playnite just launch the first option without asking which to choose.

For example: GTA V has two options after you click play: Grand Theft Auto, or Online: 

![gta](https://github.com/JosefNemec/Playnite/assets/133628011/8b245d7c-aa34-454b-9c84-320b285a0a45)

When lauching the game via the latest playnite version, it just plays Grand Theft Auto by default and won't ask me which one I want to play.

Downloaded version 10.12 and the problem doesn't happen. It asks me which option to choose, like it should be.
Steam is configured to ask me which option to choose when launching the game. I did not accidentally configured it to launch Grand Theft Auto automatically.
Doesn't matter if it's user made launch configurations or if it's the default steam options: playnite always launches the first one.

### Diagnostics ID

ac96238e-2df1-4b80-a6a4-5d0911b8bf2f

**Comment by JosefNemec** [comment]
1) wrong repository, this is all handled by Steam plugin
2) This needs to be enabled in Steam plugin's settings:
![image](https://github.com/JosefNemec/Playnite/assets/3874087/d99c1632-700f-43e5-b93d-9982c4b14c28)
