### ISSUE TITLE
EPIC and EA There are no icons

### ISSUE THREAD

**Issue by yzw20020919** [JosefNemec/Playnite#3407]
### Bug Description

![image](https://github.com/JosefNemec/Playnite/assets/86851790/d0d0c331-1f43-42c4-9b1f-e264fe957e1e)

### Diagnostics ID

bug

**Comment by Jeshibu** [comment]
Not every service provides icons. You can check which libraries do here: https://github.com/Jeshibu/PlayniteExtensionsFeatures/blob/main/librarymetadata.md
Note that several of them only provide icons for installed games.

If you want to download icons for games from services that do not provide icons themselves, have a look here: https://github.com/Jeshibu/PlayniteExtensionsFeatures/blob/main/faq.md#my-games-are-missing-covers-or-other-data-or-what-is-metadata
