### ISSUE TITLE
Force game added manually to get listed under Uplay , GOG etc.

### ISSUE THREAD

**Issue by davepatt** [JosefNemec/Playnite#341]
When adding game manually get option to get it listed under Uplay , Steam , Origin , Battlenet , GOG . It fix inability to get all games from Uplay and it dont add again software from Steam when you automaticly refresh client.

**Comment by JosefNemec** [comment]
This is no longer possible since support for individual libraries is implemented via plugins. However you can use `Source` filed for this purpose.
