### ISSUE TITLE
Have Game Variables like {PlayniteDir} work for ROM entries in the installation tab

### ISSUE THREAD

**Issue by Low-IQ-Dude** [JosefNemec/Playnite#3411]
### Feature description

I have a standalone HDD with Playnite and games on it. Mostly games that are not installed yet to save space on the drive, but the install files are present.

Using the Install Button add-on, adding a ROM entry for the install exe file in the game's details under the installation tab allows this to function properly. The "Play" is replaced with "Install" until after the attached installer is run for that game, with a window popping up after the installer is closed asking for the newly installed file location to link to the Play button. 

For games not installed yet the "installation folder" path in the installation tab is left blank, and the "Installed" box left unchecked. This field is automatically filled and box checked upon selecting the game's exe with Playnite's prompt after running and closing the installer for the game via Playnite's interface.

The "Actions" tab for these games is frequently left blank. Some of the games have actions connected to the Play button for installing separate DLC for the game, or other related files. Upon selecting the game's exe after installation through Playnite's prompting as mentioned before, an appropriate Play action is also automatically generated for the game.

I want to edit the paths of the exes listed under the ROMs of the games that aren't installed yet so that they reference the Playnite directory. That way the paths are always correct no matter what computer I plug the HDD into and whatever letter the drive becomes. Using the Path Replacer add-on would make this pretty simple to add in, but {PlayniteDir} does not seem to work when used for ROM paths this way.

There are alternative ways for me to enact this using Actions and messing with the add-ons. It's just more time consuming, tedious, and unintuitive. I might have to do just that, but I can picture other scenarios where being able to use {PlayniteDir} and other game variables in the ROM field would be helpful for users.

**Comment by JosefNemec** [comment]
This sounds to me like an issue with "Install button" addon. Addons fetching arbitrary data from games (like install paths or ROM paths) need to expand variables on their own. So this needs to be looked at by "Install Button" dev.

**Comment by Low-IQ-Dude** [comment]
Oh. So if I didn't have the Install Button add-on, Game Variables like {PlayniteDir} would work when used in the ROM field?

**Comment by JosefNemec** [comment]
It depends on what and where is using those paths. If you are reading them via an extension or a script you need to expand them on your own.

**Comment by Low-IQ-Dude** [comment]
Alright, thanks.
