### ISSUE TITLE
Add buttons for nintendo switch pls.

### ISSUE THREAD

**Issue by safarirat** [JosefNemec/Playnite#3412]
### Feature description

source/Playnite.FullscreenApp/Themes/Fullscreen/Default/Images/ButtonPrompts

**Comment by Shywizz** [comment]
Perhaps this could be used either in a theme or in the default layout, with something like this 
https://thoseawesomeguys.com/prompts/

**Comment by safarirat** [comment]
> Perhaps this could be used either in a theme or in the default layout, with something like this https://thoseawesomeguys.com/prompts/

Sounds too complicated. It is much easier to replace a-b and y-x in the profile for the xbox layout.

**Comment by safarirat** [comment]
Very lazy, but i don't know where get switch font.
https://github.com/JosefNemec/Playnite/pull/3417
Something lilke that. (i did not test FullscreenSettings.cs)

**Comment by safarirat** [comment]
Very lazy, but i don't know where get switch font.
https://github.com/JosefNemec/Playnite/pull/3417
Something lilke that. (i did not test FullscreenSettings.cs)
