### ISSUE TITLE
[P11] 'Install' process for non-library games.

### ISSUE THREAD

**Issue by chocolatechipcats** [JosefNemec/Playnite#3414]
### Feature description

If the game is in the default Playnite library (retail, freeware stuff, etc) the 'install' button isn't very helpful. It just changes to 'installing' and then cancelling monitoring returns it to the uninstalled state. Here's an idea for how an 'install' option could work for these.  

This is mostly centric to PC games installed from an ISO file or downloaded executable installer. 

When the install button is clicked:

- Have a field to let the user define the path to an installation executable or an ISO or something. If this path is set, launch the installer/ISO.
- If the installation folder is unset, prompt the user to set it. 
- If there is no 'Play' action set, prompt the user to create one.
- Ask if installation was successful. 'Yes' option sets the game to installed state.

**Comment by JosefNemec** [comment]
#478
