### ISSUE TITLE
.gg file support for Game Gear

### ISSUE THREAD

**Issue by JelloEmperor** [JosefNemec/Playnite#3415]
### Feature description

Please add support for .gg files for PicoDrive emulator.

**Comment by jedinjapan** [comment]
Is this for PiceDrive standalone, or as a libretro core?

In either case, you can define the supported filetypes for all emulators in Playnite from Configure Emulators. Choose the system on the left, and fill in the supported file types at the bottom.

If using an emulator such as Retroarch with multiples cores, these are loaded as profiles. Select Retroarch, then select the PicoDrive profile, followed by adding .gg to the supported file types for that profile before pressing save.

**Comment by JosefNemec** [comment]
Done in master
