### ISSUE TITLE
Corrupted library files

### ISSUE THREAD

**Issue by Manta70** [JosefNemec/Playnite#3422]
### Bug Description

When i try to manually add a game i get the library files are corrupt error and to come here to get my files fixed. Any help would be appreciated. I would like to continue using this fantastic software it has madse keeping my games in order a lot easier

### To Reproduce

All i hve to do is try to add a game

### Diagnostics ID

46376f34-eea2-4a83-9eac-2798777e855b

**Comment by JosefNemec** [comment]
Go to `%AppData%\Playnite\library` (put that path exactly as is into file explorer) and send me `.db` files you find there.

**Comment by Manta70** [comment]
Here are the files you requested

**Comment by JosefNemec** [comment]
I don't see any attached files.

**Comment by Manta70** [comment]
I Have attached a 7zip file called New folder.7z hope you receive it

**Comment by JosefNemec** [comment]
There's no file attached. You can't attach files via email response, as far as I know, you need to do it on GitHub.

**Comment by Manta70** [comment]
[New folder.zip](https://github.com/JosefNemec/Playnite/files/11593168/New.folder.zip)
Ok i have uploaded the file here on github hopefully you will recieve them

**Comment by Manta70** [comment]
Thankyou most appreciateed
