### ISSUE TITLE
It would be nice if users could add imported games to different filters 

### ISSUE THREAD

**Issue by MohsenGamer11** [JosefNemec/Playnite#3423]
### Feature description

This software is excellent for having every game from different libraries in one extensive Library is excellent I have always looked for a game library like this but I could not find one that was as good as this one.
though I do have a problem with it the filters in this program do not work the way other filters work in other Libraries work. for example, in Steam you can add a filter like a completed filter and you can add a game that you completed in that filter so it's gone from your library and is added to that filter. It's also like this in other libraries like in Epic Games it's exactly the same here. but that's not exactly how the filtering system in this program work, to be honest, I have no idea how it works its a bit of a complicated mess and it's not explained either so I'm really confused. I also tried to replicate my filters from my Epic Games Library but I couldn't It made me really mad.  
so it would be nice to add your games to the filters you create just like the way it's in Steam or in Epic Games.      

### Screenshots

![Screenshot 2023-05-29 175859](https://github.com/JosefNemec/Playnite/assets/112362001/35cb244e-c988-4032-aa52-12d07a628033)

For example in Epic Games library, you see different filters with different names on them 
in the Never Play filter, I added games that I don't want to play, and in the will play filter I added games that I want to play so that's the idea.

**Comment by JosefNemec** [comment]
This is already available.

Filters filter games based on game fields. If you want never play filter, then you have to assign "never play" to some game field, most likely tag, category or whatever. Then you create filter that filters this field (tag, category or whatever else) by "never play" value.

**Comment by MohsenGamer11** [comment]
Oh ok thanks for the response i didn't know that it already exists 
but what do you mean by gamefields

**Comment by JosefNemec** [comment]
Game fields are fields you can assign to games. Tags, categories, platforms, developers etc.

**Comment by MohsenGamer11** [comment]
oh ok but can I assign a filter for one game or multiple games I keep trying but it is still not working

**Comment by JosefNemec** [comment]
You don't assign games to filters. You assign game fields to games and then create filters that filters by those fields. Games then  automatically shown under that filter as you add or remove game fields on games.

You can edit fields on multiple games at the same time by selecting multiple games in the list and using "edit" from right-click menu.

**Comment by MohsenGamer11** [comment]
ok I think understand how it works now thanks a lot though it would be nice to make a guide on how it works because it could be confusing for first-time users

**Comment by JosefNemec** [comment]
There is long term plan to make user manual/documentation better.

**Comment by MohsenGamer11** [comment]
ok thank you
