### ISSUE TITLE
Battle.net authentication not working

### ISSUE THREAD

**Issue by Kinc4id** [JosefNemec/Playnite#3427]
### Bug Description

Playnite can't connect to battle.net because the user is not authenticated. Authenticating removes the message until the next time playnite is started.

### Diagnostics ID

262a664e-dc83-4656-928a-ae03d5dfa136

**Comment by JosefNemec** [comment]
1) wrong repository, this is handled by battle.net plugin
2) https://github.com/JosefNemec/PlayniteExtensions/wiki/Battle.net-troubleshooting#authentication-being-lost-after-some-time
