### ISSUE TITLE
French Translation for Playnite

### ISSUE THREAD

**Issue by ArtexJay** [JosefNemec/Playnite#343]
Working on, will be finished in the next few days

**Comment by JosefNemec** [comment]
3.3 update added new string for localization:
https://github.com/JosefNemec/Playnite/commit/ec65168e6fb0f6dc207404c78f7647913441e956#diff-fc6eaa727d5578c3ac3d59652659d9e2

**Comment by ArtexJay** [comment]
French translations finished
[french.zip](https://github.com/JosefNemec/Playnite/files/1595622/french.zip)

**Comment by ArtexJay** [comment]
French translations finished. I have an issue when adding the french file to the folder playnite stops showing the available languages, I cant figure out why
[french.zip](https://github.com/JosefNemec/Playnite/files/1595645/french.zip)

**Comment by JosefNemec** [comment]
I won't be posting updates to original English files in every separate localization issue anymore. Please subscribe to new [localization updates](https://github.com/JosefNemec/Playnite/issues/385) issue to be notified when new stuff needs translation. But please keep posting your updated files in appropriate language issues. Thanks

**Comment by ArtexJay** [comment]
French localization updated to newest version

[french.zip](https://github.com/JosefNemec/Playnite/files/1620250/french.zip)

**Comment by ClearStrelok** [comment]
Not sure how to properly do this but here goes. Here's the _french.xaml_ file from version 4.0 with the missing strings added and translated. I've also corrected some errors and reformulated a few existing strings.

[french.zip](https://github.com/JosefNemec/Playnite/files/1958927/french.zip)

**Comment by ClearStrelok** [comment]
New update. 

[french.zip](https://github.com/JosefNemec/Playnite/files/1985834/french.zip)

**Comment by ClearStrelok** [comment]
New update. 

[french.zip](https://github.com/JosefNemec/Playnite/files/1985834/french.zip)

**Comment by ClearStrelok** [comment]
New strings added.

[french.zip](https://github.com/JosefNemec/Playnite/files/1989864/french.zip)

**Comment by JosefNemec** [comment]
Localization have been completely move to Crowdin: https://crowdin.com/project/playnite

Please join the project there to submit updates.
