### ISSUE TITLE
Add support for BigPEmu

### ISSUE THREAD

**Issue by geoneil** [JosefNemec/Playnite#3430]
### Feature description

I know it may have only just come out, but BIGPEmu runs a lot better than Virtual Jaguar and I'd like to be able to import games from that emulator.  

If there is a way to do this manually, I'd need someone to hold my hand for that as well as a way to share what I did.

**Comment by geoneil** [comment]
OK, I have managed to make a start at a profile for BigPEmu, but the game isn't launching automatically.  

Name: BigPEmu
Installation Folder: D:\Emulators\BigP
Emulator Specification: Virtual Jaguar

Profile Name: BigP
Supported Platforms: Atari Jaguar
Executable: {EmulatorDir}\BigPEmu.exe
Arguments: {ImagePath}
Working Directory: {EmulatorDir}
Tracking Mode: Defualt
Supported File Types: j64,cof,rom,jag,abs,zip,cue,cdi

What should happen: The emulator starts and automatically launches the chosen game.

What actually happens: The emulator starts, skips the intro, but does NOT automatically launch the game.  

I don't know if I'm doing something wrong or if there's a bug in the emulator.  I'll have to do some further work.

**Comment by JosefNemec** [comment]
Try: `Arguments: "{ImagePath}"`

The path should be in quotes in case there's a space in the path, I tried it, it works.

**Comment by JosefNemec** [comment]
Built-in profile added in master

**Comment by geoneil** [comment]
And pushed it out to 10.17, thanks!
