### ISSUE TITLE
StackOverflowException using $PlayniteAPI.InstallGame from Interactive SDK Powershell script

### ISSUE THREAD

**Issue by jbmccune** [JosefNemec/Playnite#3432]
### Bug Description

I am working on a custom PS script to trigger the install action on Steam games that are already installed in the Steam client (explanation below). As soon as I issue the InstallGame call, Playnite freezes up and crashes.

Sample code:
```
try {
    $filterSettings = New-Object "Playnite.SDK.Models.FilterPresetSettings"
    $filterSettings.Favorite = $true
    $filterSettings.IsUnInstalled = $true

    foreach ($game in $PlayniteApi.Database.GetFilteredGames($filterSettings)) {
        $game.Name
        $game.Id
        $PlayniteApi.InstallGame($game.Id)
    }
}
catch {
    "Failed: " + $_ + "`n" + $_.ScriptStackTrace
}
```

The catch block isn't getting hit, I see the first correct game name and Id output in the console, and then Playnite just blows up and I get an unhelpful Windows error dialog w/ Debug or Close, and I'm not setup to debug. I do see the error in the Event Log, and a reference to this crash report:
[Report.wer.txt](https://github.com/JosefNemec/Playnite/files/11681762/Report.wer.txt)

Long background story: I have an extremely large library (20K+). Since I can't bulk install games from Playnite, but I can with the Steam client, I am using Steam to install large batches of games and then doing a library update in Playnite to sync the install status and details. That works fine most of the time, but there are a significant number of games that are in my Steam client, but not being imported into Playnite - maybe 5%. Installing them in Steam and them updating doesn't bring them in, so I have a script to create stubs in Playnite with just the PluginId and GameId set, and then I do a metadata update to grab the rest. That works fine, except that those games that I manually add and then connect that way somehow aren't hooked up with Steam quite right and don't get their install status updated when I install them from the Steam client and then do a library update. However, if I manually hit Install for each game in Playnite, after they are already installed in Steam, there's no pop-up or anything, they just get marked installed in Playnite and all seems to be well. It's just very cumbersome to click Install on each of 100s of games individually, hence the script idea.

### To Reproduce

Minimal repro steps:

1) Restart Playnite in safe mode.

2) Copy the Library GUID for any Steam game in your library, regardless of install status or whether it was manually or automatically added to Playnite.

3) Open the Interactive SDK Powershell and hit Ctrl-V.

4) Issue this command:
```
$PlayniteApi.InstallGame([guid]"{any valid Steam game guid}")
```

### Diagnostics ID

6442484e-4b30-4988-91c2-121d356ca441

**Comment by JosefNemec** [comment]
Can reproduce, will look into it.

> Installing them in Steam and them updating doesn't bring them in

This should definitely work, Steam plugin will import any game it detect as installed no matter if it's found on your account or not. The only exception being if you have "ignore installed games from other accounts" option enabled. So try disabling that, even if you don't have extra accounts connected.

**Comment by JosefNemec** [comment]
Fixed in master
