### ISSUE TITLE
movies, books, etc.

### ISSUE THREAD

**Issue by TylerJBraun** [JosefNemec/Playnite#3437]
### Feature description

I love this system so much that I want to use it to track my use of even more stuff like movies and stuff! I've been just adding stuff manually but would love integration for IMDB.

**Comment by chocolatechipcats** [comment]
See #3398

**Comment by JosefNemec** [comment]
Out of scope for Playnite (as stated in #3398 that chocolatechipcats linked). Should be doable via plugins more easily in P11.

**Comment by TylerJBraun** [comment]
Thanks. I look forward to P11. :)
