### ISSUE TITLE
Library file corruption has been detected, Playnite will shutdown now

### ISSUE THREAD

**Issue by mrbruh1** [JosefNemec/Playnite#3438]
### Bug Description

Error occurs when adding a game manually, then closes.

### To Reproduce

Try to add a game

### Diagnostics ID

"Failed to automatically upload diag package"

### Screenshots

![image](https://github.com/JosefNemec/Playnite/assets/91948270/29e2ed2c-85ee-4b3a-9891-aaf3ee28b84f)

**Comment by mrbruh1** [comment]
[diag.zip](https://github.com/JosefNemec/Playnite/files/11758165/diag.zip)

**Comment by JosefNemec** [comment]
Go to `%AppData%\Playnite\library` (put the path as is into file explorer) and attach `.db` files you find there.

**Comment by mrbruh1** [comment]
[db.zip](https://github.com/JosefNemec/Playnite/files/11768339/db.zip)


> Go to `%AppData%\Playnite\library` (put the path as is into file explorer) and attach `.db` files you find there.

**Comment by JosefNemec** [comment]
[Here's fixed file](https://github.com/JosefNemec/Playnite/files/11768628/games.zip)
