### ISSUE TITLE
Game Play action paths

### ISSUE THREAD

**Issue by N0keya** [JosefNemec/Playnite#344]
Hey Ive noticed the path in the Play Action does not stay as what I have changed it to, they stay on the new path until I restart and then the path resets to the original. This causes problems when I plan on loading a Modded game, as I would have changed the path to the modded exe rather than the original game

**Comment by JosefNemec** [comment]
Play Action is updated when automatically imported games are refreshed (at every start or when called manually via F5), this is to make sure that the paths are always correct when the installation folder changes for some reason. But you are right that it doesn't make sense to let user change it and then overwrite it automatically during next startup. I'll change play actions to use relative paths by default and stop overwriting it.

**Comment by JosefNemec** [comment]
Released in 3.3
