### ISSUE TITLE
Playnite tries to access the webcam

### ISSUE THREAD

**Issue by Neurone** [JosefNemec/Playnite#3442]
### Bug Description

I installed Playnite 10.17 (I used the PlayniteInstaller.exe from your website https://playnite.link/).
I configured the Steam add-on, and the Epic add-on. While configuring the Epic add-on, just after showing the Epic web login page, Avast blocked the CefSharp.BrowserSubprocess.exe process, installed with Playnite, because it was trying to access my webcam.
I uninstalled Playnite, please verify your code or your add-ons.

### Diagnostics ID

I uninstalled Playnite.

**Comment by JosefNemec** [comment]
Playnite doesn't access web cam. If it happened during Epic login, then it means that Epic's login page was trying to access it. It's also possible that it is a false positive from Avast which has flagged CefSharp incorrectly in the past already.

**Comment by JosefNemec** [comment]
> please verify your code or your add-ons

You can check both Playnite's code and Epic plugin's code, you won't find anything trying to access web cam or other device on your PC.

**Comment by Neurone** [comment]
Hi Josef, I'm not saying Playnite access camera on purpose; that is why I flagged it as a bug.

In my personal experience, checking the camera access is something Avast never reported a false positive for; it would be the first time I get a false positive about that in years, and in general, it seems pretty an easy check that is difficult to fail (it's not like a heuristic approach to malware or viruses).

The odds of false positives in checking for webcam access are very low, so I suggest more verifications on this topic.

For example, CefSharp.BrowserSubprocess.exe is included in the installer by your build process, but it is not something you have the source code for, right? If so, is it possible the build process of the PlayniteInstaller.exe or Playnite1017.exe is somehow compromised? Where that exe comes from? Did Microsoft sign it? Is there a mechanism in Playnite that automatically updates that file that may bring to download compromised exes? Etc.

**Comment by JosefNemec** [comment]
Builds are done transparently via [appveyor](https://ci.appveyor.com/project/JosefNemec/playnite) and signed using [SignPath](https://about.signpath.io) which actually requires this transparency for OSS projects. CefSharp.BrowserSubprocess.exe comes from official [CefSharp](https://github.com/cefsharp/CefSharp) Nuget packages (I can't find any reports of those being compromised).
