### ISSUE TITLE
Ability to change game library

### ISSUE THREAD

**Issue by ForAnAngel731** [JosefNemec/Playnite#3443]
### Feature description

I manually added a game that I downloaded from itch.io. For some reason it didn't find the game when I tried the automatic Update Game Library. The game was added with "Playnite" as the library. I would like to be able to change it to "itch.io" to be able to group it together with the other games I've gotten from there. But in Edit Game Details/Advanced, the library is shown but there is no option to change it.

### Screenshots

![image](https://github.com/JosefNemec/Playnite/assets/101476189/0b5b38f3-ad72-4a96-882a-bbaf3a938c65)

**Comment by JosefNemec** [comment]
Not possible. Library field specifies what library integration plugin imported a game. If you would just add arbitrary game to a plugin, the plugin would have no idea what to do with the game and how to handle it (for example how to start it). You can use other fields, like Source, if you want to categorize manually added games with automatically imported ones.

> For some reason it didn't find the game when I tried the automatic Update Game Library

You need to claim the game to your itch account. Itch doesn't do it automatically with every game to not clog up your library.

**Comment by ForAnAngel731** [comment]
The problem is there is no "claim" button. There is just a download button because it is a free game.

**Comment by JosefNemec** [comment]
Then add the game to a collection and enable "import free games from collection" option.

**Comment by ForAnAngel731** [comment]
I added the game to a collection and enabled the "import free games from collections" option then updated all my game libraries and nothing happened.
