### ISSUE TITLE
Playtime backup merge

### ISSUE THREAD

**Issue by hyoretsu** [JosefNemec/Playnite#3447]
### Feature description

This is related to #3239. I recently bought a gaming PC to play games along with my notebook. While I can't use some sort of auto cloud sync, I can backup and import one or the other when switching. But then I found out that everything gets transferred, without any sort of filter.

It could do a sort of merge of game data, at least for playtime. Use the one that has the latest "Last Played", and if they're the same, use the highest time played.

**Comment by JosefNemec** [comment]
There already exists multiple issues for this #108 #1975  #3239

**Comment by hyoretsu** [comment]
I know, as I found all 3. I'm not asking for a fully fledged cloud backup solution. I specifically created a new issue to ask for just playtime handling between backup/import. That doesn't involve cloud on your part, and it's way simpler to do.

**Comment by hyoretsu** [comment]
One last comment to say this again, I'm not asking for the same thing as the issues you linked.
