### ISSUE TITLE
Wallpaper Engine produces error in initial size scan

### ISSUE THREAD

**Issue by comiluv** [JosefNemec/Playnite#3448]
### Bug Description

With [Wallpaper Engine](https://store.steampowered.com/app/431960/Wallpaper_Engine/) installed, Playnite produces an error message "There were 1 errors during install size scan"

Upon clicking on the message, a window shows a message: "Wallpaper Engine: installation dir/ui/uicache/welcome/user/WidevineCdm/4.10.2557.0 access to path denied"

### To Reproduce

1. Install wallpaper engine
2. Update game library

### Diagnostics ID

5ddf9662-4d94-4ed8-874d-2cfcaafa7ca4

### Screenshots

<img width="1009" alt="스크린샷 2023-06-19 222152" src="https://github.com/JosefNemec/Playnite/assets/19642705/18da097a-be11-4c85-845a-c4e068f744ec">

**Comment by JosefNemec** [comment]
If wallpaper engine creates folders that have such restrictive permissions on them that doesn't allow normal users to read files and their sizes, then there's nothing we can do about it.
