### ISSUE TITLE
Missing localization strings

### ISSUE THREAD

**Issue by PhrozenByte** [JosefNemec/Playnite#346]
https://github.com/JosefNemec/Playnite/blob/ad9500c54713b53cf6e8bab1df4f0ee9fbf0be1a/source/PlayniteUI/Skins/Modern/Modern.xaml#L2373-L2380

I'll comment on this Issue if I encounter more missing localization strings in the implementation of #345.

**Comment by JosefNemec** [comment]
Released in 3.3

**Comment by PhrozenByte** [comment]
https://github.com/JosefNemec/Playnite/blob/601ffe10c0d8590daea3fa793d34752e25d97195/source/PlayniteUI/Localization/english.xaml#L396

Doesn't seem to be used anywhere

**Comment by PhrozenByte** [comment]
https://github.com/JosefNemec/Playnite/blob/601ffe10c0d8590daea3fa793d34752e25d97195/source/PlayniteUI/Localization/english.xaml#L297

The same seems to be true for this one

**Comment by PhrozenByte** [comment]
https://github.com/JosefNemec/Playnite/blob/d41ffd6a1b6dd87a03cd3e27da56b936aeeb264d/source/PlayniteUI/ViewModels/PlatformsViewModel.cs#L582

Small typo
