### ISSUE TITLE
bug metadata

### ISSUE THREAD

**Issue by TheNicceGuy** [JosefNemec/Playnite#3461]
### Bug Description

crash when try download metadata for vr games that imported.

### To Reproduce

crash when try download metadata for vr games that imported.

### Diagnostics ID

98858724-e9b5-4512-b670-3dee2ebd9072

### Screenshots

26-06 09:40:46.769|DEBUG|BaseCollectionView:Refreshing collection view filter.
26-06 09:40:48.663|DEBUG|BaseCollectionView:Refreshing collection view filter.
26-06 09:40:55.005|DEBUG|BaseCollectionView:Updating collection view settings.
26-06 09:41:02.792|DEBUG|WindowFactory:Show dialog window Playnite.DesktopApp.Windows.SettingsWindowFactory: 7f329492-f4ba-4b81-a2f4-e1baa604f961
26-06 09:41:05.890|INFO |PlayniteApplication:Shutting down Playnite and starting an app.
26-06 09:41:05.995|DEBUG|PlayniteApplication:Releasing Playnite resources...
26-06 09:41:06.014|DEBUG|WindowFactory:Show dialog window Playnite.Windows.ProgressWindowFactory: 8fc9b8a8-c5af-4ba2-9da1-5c3bcbf72aab
26-06 09:41:06.014|DEBUG|WindowFactory:Closing window Playnite.Windows.ProgressWindowFactory: 8fc9b8a8-c5af-4ba2-9da1-5c3bcbf72aab, True
26-06 09:41:06.137|DEBUG|ProcessStarter:Starting process: D:\Playnite\Playnite.DesktopApp.exe, --clearwebcache --masterinstance --nolibupdate, , False
26-06 09:41:06.315|INFO |ProgramEntry:App arguments: '--clearwebcache,--masterinstance,--nolibupdate'
26-06 09:41:07.028|INFO |PlayniteApplication:Application started from 'D:\Playnite'
26-06 09:41:07.367|INFO |ExtensionFactory:Loaded plugin: Epic Store library integration, version 2.16
26-06 09:41:07.386|INFO |ExtensionFactory:Loaded plugin: IGDB metadata provider, version 2.7
26-06 09:41:07.392|INFO |ExtensionFactory:Loaded plugin: Oculus Library Importer, version 2.3.2
26-06 09:41:07.392|INFO |ExtensionFactory:Loaded plugin: Rockstar Games library integration, version 2.7
26-06 09:41:07.392|INFO |ExtensionFactory:Loaded plugin: Simple Game Import, version 2.0
26-06 09:41:07.450|INFO |ExtensionFactory:Loaded plugin: Steam library integration, version 2.16
26-06 09:41:07.462|INFO |ExtensionFactory:Loaded plugin: Ubisoft Connect library integration, version 2.5
26-06 09:41:07.566|DEBUG|WindowFactory:Show window Playnite.DesktopApp.Windows.MainWindowFactory: a842a5a5-16f4-4e98-85a8-7c8a3c66cdd6
26-06 09:41:07.772|DEBUG|GamesCollectionViewEntry:Reloading collection item view properties.
26-06 09:41:07.793|INFO |GameDatabase:Opening db D:\Playnite\library
26-06 09:41:07.793|DEBUG|WindowFactory:Show dialog window Playnite.Windows.ProgressWindowFactory: debe5f5c-1491-4077-b33f-daa21d9f1df2
26-06 09:41:08.297|DEBUG|ExecutionTimer:--- Timer 'DatabaseLoadCollections', 502 ms to complete.
26-06 09:41:08.316|INFO |DatabaseStats:Completely recalculating database statistics...
26-06 09:41:08.352|DEBUG|WindowFactory:Closing window Playnite.Windows.ProgressWindowFactory: debe5f5c-1491-4077-b33f-daa21d9f1df2, True
26-06 09:41:08.472|WARN |MainViewModelBase:Startup library update disabled via cmdline.
26-06 09:41:08.497|INFO |PlayniteApplication:Application 10.18.0.17924 started
26-06 09:41:11.236|DEBUG|WindowFactory:Show dialog window Playnite.DesktopApp.Windows.SettingsWindowFactory: 87bcaddc-a59b-43ef-bd3c-d63cc51c07d8
26-06 09:41:13.500|DEBUG|Downloader:Downloading string content from https://www.playnite.link/update/stable/10.18/update.json using System.Text.UTF8Encoding encoding.
26-06 09:41:14.274|DEBUG|Downloader:Downloading string content from https://github.com/JosefNemec/PlayniteExtensions/raw/master/manifests/IGDBMetadata_Builtin.yaml using UTF8 encoding.
26-06 09:41:15.088|DEBUG|Downloader:Downloading string content from https://github.com/JosefNemec/PlayniteExtensions/raw/master/manifests/EpicGamesLibrary_Builtin.yaml using UTF8 encoding.
26-06 09:41:15.335|DEBUG|Downloader:Downloading string content from https://github.com/Jeshibu/Playnite-OculusLibrary/raw/master/OculusLibraryInstaller.yaml using UTF8 encoding.
26-06 09:41:15.738|DEBUG|Downloader:Downloading string content from https://github.com/JosefNemec/PlayniteExtensions/raw/master/manifests/Rockstar_Games_Library.yaml using UTF8 encoding.
26-06 09:41:16.138|DEBUG|Downloader:Downloading string content from https://github.com/JosefNemec/PlayniteExtensions/raw/master/manifests/SteamLibrary_Builtin.yaml using UTF8 encoding.
26-06 09:41:16.408|DEBUG|Downloader:Downloading string content from https://github.com/JosefNemec/PlayniteExtensions/raw/master/manifests/UplayLibrary_Builtin.yaml using UTF8 encoding.
26-06 09:41:16.648|DEBUG|Downloader:Downloading string content from https://raw.githubusercontent.com/joyrider3774/Playnite_Simple_Game_Importer/main/SimpleGameImport.yaml using UTF8 encoding.
26-06 09:41:16.819|DEBUG|Downloader:Downloading string content from https://raw.githubusercontent.com/felixkmh/DH_Themes/main/InstallerManifest/felixkmh_DesktopTheme_DH_Dawn.yaml using UTF8 encoding.
26-06 09:41:50.566|DEBUG|WindowFactory:Closing window Playnite.DesktopApp.Windows.SettingsWindowFactory: 87bcaddc-a59b-43ef-bd3c-d63cc51c07d8, True
26-06 09:41:54.971|DEBUG|WindowFactory:Show dialog window Playnite.DesktopApp.Windows.GameEditWindowFactory: 92389bad-5cea-43ed-b2f5-46e9aae94d36
26-06 09:41:56.367|DEBUG|WindowFactory:Show dialog window Playnite.Windows.ProgressWindowFactory: 115a4f56-95de-44c4-af4e-36222e6021c9
26-06 09:41:56.403|DEBUG|WindowFactory:Show dialog window Playnite.DesktopApp.Windows.ItemSelectionWithSearchWindowFactory: fa2f3b07-b93b-4a22-854f-1bcb5edb4a0b
26-06 09:41:56.418|DEBUG|WindowFactory:Show dialog window Playnite.Windows.ProgressWindowFactory: 2a0d405a-ce5d-44cf-a313-48e3641292da
26-06 09:41:56.840|DEBUG|WindowFactory:Closing window Playnite.Windows.ProgressWindowFactory: 2a0d405a-ce5d-44cf-a313-48e3641292da, True
26-06 09:42:00.727|DEBUG|WindowFactory:Closing window Playnite.DesktopApp.Windows.ItemSelectionWithSearchWindowFactory: fa2f3b07-b93b-4a22-854f-1bcb5edb4a0b, True
26-06 09:42:00.867|DEBUG|WindowFactory:Show dialog window Playnite.DesktopApp.Windows.ImageSelectionWindowFactory: 6b15b5d1-5484-483c-aadf-1f6c5f79fe29
26-06 09:42:03.590|DEBUG|WindowFactory:Closing window Playnite.DesktopApp.Windows.ImageSelectionWindowFactory: 6b15b5d1-5484-483c-aadf-1f6c5f79fe29, True
26-06 09:42:03.607|DEBUG|Downloader:Downloading data from https://images.igdb.com/igdb/image/upload/t_1080p/co1m3a.jpg to C:\Users\psych\AppData\Local\Temp\Playnite\6e1adeef-43e6-4f7e-9699-c99b166aa4a2.jpg.
26-06 09:42:03.607|DEBUG|WindowFactory:Show dialog window Playnite.Windows.ProgressWindowFactory: 77019e51-c296-4618-8919-13f2350fbe1d
26-06 09:42:03.644|DEBUG|WindowFactory:Closing window Playnite.Windows.ProgressWindowFactory: 77019e51-c296-4618-8919-13f2350fbe1d, True
26-06 09:42:03.644|DEBUG|Downloader:Downloading data from https://images.igdb.com/igdb/image/upload/t_1080p/ar5t8.jpg to C:\Users\psych\AppData\Local\Temp\Playnite\d6a698a3-3d78-4335-98b2-5919128e3eae.jpg.
26-06 09:42:03.644|DEBUG|WindowFactory:Show dialog window Playnite.Windows.ProgressWindowFactory: bcfba490-eae9-425c-b84f-460a5de15a0e
26-06 09:42:03.683|DEBUG|WindowFactory:Closing window Playnite.Windows.ProgressWindowFactory: bcfba490-eae9-425c-b84f-460a5de15a0e, True
26-06 09:42:03.712|DEBUG|WindowFactory:Show dialog window Playnite.DesktopApp.Windows.MetadataComparisonWindowFactory: d45f06f6-c69b-4bb1-af53-b4dff0c5e3d8
26-06 09:42:04.727|DEBUG|WindowFactory:Closing window Playnite.DesktopApp.Windows.MetadataComparisonWindowFactory: d45f06f6-c69b-4bb1-af53-b4dff0c5e3d8, True
26-06 09:42:04.746|DEBUG|WindowFactory:Show dialog window Playnite.Windows.ProgressWindowFactory: cec68284-435f-48bc-89f3-e8bcd517c963
26-06 09:42:04.762|DEBUG|WindowFactory:Closing window Playnite.Windows.ProgressWindowFactory: cec68284-435f-48bc-89f3-e8bcd517c963, True
26-06 09:42:04.817|DEBUG|WindowFactory:Show dialog window Playnite.Windows.ProgressWindowFactory: d825ff05-04aa-42bd-aeb2-e55acffa5296
26-06 09:42:04.817|DEBUG|WindowFactory:Closing window Playnite.Windows.ProgressWindowFactory: d825ff05-04aa-42bd-aeb2-e55acffa5296, True
26-06 09:42:04.896|DEBUG|WindowFactory:Closing window Playnite.Windows.ProgressWindowFactory: 115a4f56-95de-44c4-af4e-36222e6021c9, True
26-06 09:42:05.397|DEBUG|FileSystem:Copying file C:\Users\psych\AppData\Local\Temp\Playnite\temp_edit_preview_cover.jpg to D:\Playnite\library\files\76ea8e02-c325-4441-a661-65975b50ab87\76d41ab0-3823-4b98-a52e-d61e4d290fd8.jpg
26-06 09:42:05.397|DEBUG|FileSystem:Copying file C:\Users\psych\AppData\Local\Temp\Playnite\temp_edit_preview_background.jpg to D:\Playnite\library\files\76ea8e02-c325-4441-a661-65975b50ab87\d006d302-327b-4a7c-8469-68e4977eeb05.jpg
26-06 09:42:05.438|ERROR|PlayniteApplication:Unhandled exception occured.
LiteDB.LiteException: Datafile is not a LiteDB database.
   ב-  LiteDB.HeaderPage.ReadContent(ByteReader reader)
   ב-  LiteDB.BasePage.ReadPage(Byte[] buffer)
   ב-  LiteDB.PageService.GetPage[T](UInt32 pageID)
   ב-  LiteDB.PageService.RemoveToFreeList(BasePage page, BasePage startPage, UInt32& fieldPageID)
   ב-  LiteDB.PageService.AddOrRemoveToFreeList(Boolean add, BasePage page, BasePage startPage, UInt32& fieldPageID)
   ב-  LiteDB.PageService.NewPage[T](BasePage prevPage)
   ב-  LiteDB.DataService.Update(CollectionPage col, PageAddress blockAddress, Byte[] data)
   ב-  LiteDB.LiteEngine.UpdateDocument(CollectionPage col, BsonDocument doc)
   ב-  LiteDB.LiteEngine.<>c__DisplayClass33_0.<Upsert>b__0(CollectionPage col)
   ב-  LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func`2 action)
   ב-  LiteDB.LiteEngine.Upsert(String collection, IEnumerable`1 docs, BsonType autoId)
   ב-  LiteDB.LiteCollection`1.Upsert(IEnumerable`1 documents)
   ב-  LiteDB.LiteCollection`1.Upsert(T document)
   ב-  Playnite.Database.ItemCollection`1.Update(TItem itemToUpdate) ב- C:\projects\playnite\source\Playnite\Database\Collections\ItemCollection.cs:שורה 506
   ב-  Playnite.Database.GamesCollection.Update(Game itemToUpdate) ב- C:\projects\playnite\source\Playnite\Database\Collections\GamesCollection.cs:שורה 167
   ב-  Playnite.DesktopApp.ViewModels.GameEditViewModel.ConfirmDialog() ב- C:\projects\playnite\source\Playnite.DesktopApp\ViewModels\GameEditViewModel.cs:שורה 867
   ב-  Playnite.DesktopApp.ViewModels.GameEditViewModel.<get_ConfirmCommand>b__223_0(Object a) ב- C:\projects\playnite\source\Playnite.DesktopApp\ViewModels\GameEditViewModelCommands.cs:שורה 114
   ב-  Playnite.SDK.RelayCommand`1.Execute(Object parameter) ב- C:\projects\playnite\source\PlayniteSDK\RelayCommand.cs:שורה 205
   ב-  MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   ב-  System.Windows.Controls.Primitives.ButtonBase.OnClick()
   ב-  System.Windows.Controls.Button.OnClick()
   ב-  System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   ב-  System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   ב-  System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   ב-  System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   ב-  System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   ב-  System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   ב-  System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   ב-  System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   ב-  System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   ב-  System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   ב-  System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   ב-  System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   ב-  System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   ב-  System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   ב-  System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   ב-  System.Windows.Input.InputManager.ProcessStagingArea()
   ב-  System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   ב-  System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   ב-  System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   ב-  System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   ב-  System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   ב-  MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   ב-  MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   ב-  System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   ב-  System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   ב-  System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   ב-  MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   ב-  MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   ב-  System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   ב-  System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   ב-  System.Windows.Window.ShowHelper(Object booleanBox)
   ב-  System.Windows.Window.Show()
   ב-  System.Windows.Window.ShowDialog()
   ב-  Playnite.Windows.WindowFactory.<>c__DisplayClass16_0.<CreateAndOpenDialog>b__0(Object a) ב- C:\projects\playnite\source\Playnite\Windows\WindowFactory.cs:שורה 82
   ב-  System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   ב-  System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   ב-  System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   ב-  System.Windows.Threading.DispatcherSynchronizationContext.Send(SendOrPostCallback d, Object state)
   ב-  Playnite.Windows.WindowFactory.CreateAndOpenDialog(Object dataContext) ב- C:\projects\playnite\source\Playnite\Windows\WindowFactory.cs:שורה 57
   ב-  Playnite.DesktopApp.DesktopGamesEditor.EditGame(Game game) ב- C:\projects\playnite\source\Playnite.DesktopApp\DesktopGamesEditor.cs:שורה 52
   ב-  Playnite.DesktopApp.ViewModels.DesktopAppViewModel.EditGame(Game game) ב- C:\projects\playnite\source\Playnite.DesktopApp\ViewModels\DesktopAppViewModel.cs:שורה 1274
   ב-  Playnite.DesktopApp.ViewModels.DesktopAppViewModel.<InitializeCommands>b__319_59(Game a) ב- C:\projects\playnite\source\Playnite.DesktopApp\ViewModels\DesktopAppViewModel_Commands.cs:שורה 444
   ב-  Playnite.SDK.RelayCommand`1.Execute(Object parameter) ב- C:\projects\playnite\source\PlayniteSDK\RelayCommand.cs:שורה 201
   ב-  MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   ב-  System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   ב-  System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   ב-  System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   ב-  System.Windows.Threading.DispatcherOperation.InvokeImpl()
   ב-  System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   ב-  MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   ב-  System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   ב-  System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   ב-  System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   ב-  MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   ב-  System.Windows.Threading.DispatcherOperation.Invoke()
   ב-  System.Windows.Threading.Dispatcher.ProcessQueue()
   ב-  System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   ב-  MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   ב-  MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   ב-  System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   ב-  System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   ב-  System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   ב-  MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   ב-  MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   ב-  System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   ב-  System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   ב-  System.Windows.Application.RunDispatcher(Object ignore)
   ב-  System.Windows.Application.RunInternal(Window window)
   ב-  System.Windows.Application.Run(Window window)
   ב-  Playnite.DesktopApp.ProgramEntry.Main(String[] args) ב- C:\projects\playnite\source\Playnite.DesktopApp\ProgramEntry.cs:שורה 61
26-06 09:42:05.478|DEBUG|WindowFactory:Show dialog window Playnite.Windows.CrashHandlerWindowFactory: 211bba0c-2090-48d8-8a69-4243a6de02e0
26-06 09:42:07.796|DEBUG|ProcessStarter:Opening URL: https://github.com/JosefNemec/Playnite/issues/new/choose
26-06 09:43:42.648|DEBUG|ProcessStarter:Opening URL: https://github.com/JosefNemec/Playnite/issues/new/choose
26-06 09:44:43.806|DEBUG|WindowFactory:Show dialog window Playnite.Windows.ProgressWindowFactory: 9867c31d-f902-4658-a4c6-f73e2a4d7b58
26-06 09:44:45.529|DEBUG|WindowFactory:Closing window Playnite.Windows.ProgressWindowFactory: 9867c31d-f902-4658-a4c6-f73e2a4d7b58, True
26-06 09:44:45.538|DEBUG|WindowFactory:Show dialog window Playnite.Windows.ProgressWindowFactory: 3e521709-1ef7-421d-9fc1-882c5248bda8
26-06 09:44:51.061|DEBUG|WindowFactory:Closing window Playnite.Windows.ProgressWindowFactory: 3e521709-1ef7-421d-9fc1-882c5248bda8, True

**Comment by JosefNemec** [comment]
Your game library files are damaged somehow. Go to `D:\Playnite\library` and attach `.db` files you find there.

**Comment by TheNicceGuy** [comment]
all files .db there , can you be more specific

**Comment by JosefNemec** [comment]
I can't be more specific, all .db files means all files with .db extension.

**Comment by TheNicceGuy** [comment]
> I can't be more specific, all .db files means all files with .db extension.

all the files there in library folder  in .db format ...
what to do with them ?
![ללא שם](https://github.com/JosefNemec/Playnite/assets/137758990/fd9dcac4-431b-4a37-8b37-8159dd61578b)

**Comment by JosefNemec** [comment]
Upload them here so I can try repair them.

**Comment by TheNicceGuy** [comment]
here

**Comment by TheNicceGuy** [comment]
[library.zip](https://github.com/JosefNemec/Playnite/files/11867443/library.zip)

**Comment by JosefNemec** [comment]
Here's fixed file [games.zip](https://github.com/JosefNemec/Playnite/files/11867511/games.zip)

**Comment by TheNicceGuy** [comment]
it fix this , thank a lot !!
