### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by TheNicceGuy** [JosefNemec/Playnite#3462]
### Bug Description

the new games i imported dosent apper aftter metadata auto updata so i do it manually 1 by one /
in all rest of games that alredy there i can freely change and download new metadata /
but the new ones failed and playnite crash 

### To Reproduce

import new games from other hdd 
try to download manually metadata 
playnite crashes 

### Diagnostics ID

48f4acd8-f9db-4141-b80a-301d9c77115d

### Screenshots

   ב-  LiteDB.HeaderPage.ReadContent(ByteReader reader)
   ב-  LiteDB.BasePage.ReadPage(Byte[] buffer)
   ב-  LiteDB.PageService.GetPage[T](UInt32 pageID)
   ב-  LiteDB.PageService.RemoveToFreeList(BasePage page, BasePage startPage, UInt32& fieldPageID)
   ב-  LiteDB.PageService.AddOrRemoveToFreeList(Boolean add, BasePage page, BasePage startPage, UInt32& fieldPageID)
   ב-  LiteDB.PageService.NewPage[T](BasePage prevPage)
   ב-  LiteDB.DataService.Update(CollectionPage col, PageAddress blockAddress, Byte[] data)
   ב-  LiteDB.LiteEngine.UpdateDocument(CollectionPage col, BsonDocument doc)
   ב-  LiteDB.LiteEngine.<>c__DisplayClass33_0.<Upsert>b__0(CollectionPage col)
   ב-  LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func`2 action)
   ב-  LiteDB.LiteEngine.Upsert(String collection, IEnumerable`1 docs, BsonType autoId)
   ב-  LiteDB.LiteCollection`1.Upsert(IEnumerable`1 documents)
   ב-  LiteDB.LiteCollection`1.Upsert(T document)
   ב-  Playnite.Database.ItemCollection`1.Update(TItem itemToUpdate) ב- C:\projects\playnite\source\Playnite\Database\Collections\ItemCollection.cs:שורה 506
   ב-  Playnite.Database.GamesCollection.Update(Game itemToUpdate) ב- C:\projects\playnite\source\Playnite\Database\Collections\GamesCollection.cs:שורה 167
   ב-  Playnite.Metadata.MetadataDownloader.<>c__DisplayClass11_0.<DownloadMetadataAsync>b__0() ב- C:\projects\playnite\source\Playnite\Metadata\MetadataDownloader.cs:שורה 614
26-06 12:17:39.707|DEBUG|MetadataDownloader:Downloading metadata for Sairento VR, 10dcca8da4542ece5701c1a210328b7f, 00000000-0000-0000-0000-000000000000
26-06 12:17:39.930|DEBUG|Downloader:Downloading data from https://images.igdb.com/igdb/image/upload/t_original/arj4d.jpg to C:\Users\psych\AppData\Local\Temp\Playnite\d138b27a-3022-4866-8a95-a631cbc99095.jpg.
26-06 12:17:40.185|DEBUG|FileSystem:Copying file C:\Users\psych\AppData\Local\Temp\Playnite\d138b27a-3022-4866-8a95-a631cbc99095.jpg to D:\Playnite\library\files\2cd5e83b-8a99-482f-ba0b-9a6d7197971d\5c3ef6f4-7891-4a91-aff3-af79e836db1b.jpg
26-06 12:17:40.195|DEBUG|Downloader:Downloading data from https://images.igdb.com/igdb/image/upload/t_original/co3anp.jpg to C:\Users\psych\AppData\Local\Temp\Playnite\dbed823f-d85c-4c4e-bd37-0fb8a9393b72.jpg.
26-06 12:17:40.694|DEBUG|FileSystem:Copying file C:\Users\psych\AppData\Local\Temp\Playnite\dbed823f-d85c-4c4e-bd37-0fb8a9393b72.jpg to D:\Playnite\library\files\2cd5e83b-8a99-482f-ba0b-9a6d7197971d\d21c47b7-9ab0-4069-ba3e-1c77f6f21474.jpg
26-06 12:17:40.727|ERROR|MetadataDownloader:Failed to download metadata for game Sairento VR, 2cd5e83b-8a99-482f-ba0b-9a6d7197971d
LiteDB.LiteException: Datafile is not a LiteDB database.
   ב-  LiteDB.HeaderPage.ReadContent(ByteReader reader)
   ב-  LiteDB.BasePage.ReadPage(Byte[] buffer)
   ב-  LiteDB.PageService.GetPage[T](UInt32 pageID)
   ב-  LiteDB.PageService.RemoveToFreeList(BasePage page, BasePage startPage, UInt32& fieldPageID)
   ב-  LiteDB.PageService.AddOrRemoveToFreeList(Boolean add, BasePage page, BasePage startPage, UInt32& fieldPageID)
   ב-  LiteDB.PageService.NewPage[T](BasePage prevPage)
   ב-  LiteDB.DataService.Update(CollectionPage col, PageAddress blockAddress, Byte[] data)
   ב-  LiteDB.LiteEngine.UpdateDocument(CollectionPage col, BsonDocument doc)
   ב-  LiteDB.LiteEngine.<>c__DisplayClass33_0.<Upsert>b__0(CollectionPage col)
   ב-  LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func`2 action)
   ב-  LiteDB.LiteEngine.Upsert(String collection, IEnumerable`1 docs, BsonType autoId)
   ב-  LiteDB.LiteCollection`1.Upsert(IEnumerable`1 documents)
   ב-  LiteDB.LiteCollection`1.Upsert(T document)
   ב-  Playnite.Database.ItemCollection`1.Update(TItem itemToUpdate) ב- C:\projects\playnite\source\Playnite\Database\Collections\ItemCollection.cs:שורה 506
   ב-  Playnite.Database.GamesCollection.Update(Game itemToUpdate) ב- C:\projects\playnite\source\Playnite\Database\Collections\GamesCollection.cs:שורה 167
   ב-  Playnite.Metadata.MetadataDownloader.<>c__DisplayClass11_0.<DownloadMetadataAsync>b__0() ב- C:\projects\playnite\source\Playnite\Metadata\MetadataDownloader.cs:שורה 614
26-06 12:17:40.727|DEBUG|MetadataDownloader:Downloading metadata for Surgeon Simulator - Experience Reality, 44d7dbff05cccda747c00083d2879c59, 00000000-0000-0000-0000-000000000000
26-06 12:17:40.972|DEBUG|Downloader:Downloading data from https://images.igdb.com/igdb/image/upload/t_original/ars0r.jpg to C:\Users\psych\AppData\Local\Temp\Playnite\d612b995-9bfc-4ee9-bfa9-a2e6ab62e129.jpg.
26-06 12:17:41.003|DEBUG|FileSystem:Copying file C:\Users\psych\AppData\Local\Temp\Playnite\d612b995-9bfc-4ee9-bfa9-a2e6ab62e129.jpg to D:\Playnite\library\files\1316358c-3a51-4ef3-8d6e-3b6454a505b4\b7d9a154-b1ef-4385-8c4f-f842170ef516.jpg
26-06 12:17:41.003|DEBUG|Downloader:Downloading data from https://images.igdb.com/igdb/image/upload/t_1080p/co1v3m.jpg to C:\Users\psych\AppData\Local\Temp\Playnite\6a161692-0045-4857-8ecf-7cc79cf2a17b.jpg.
26-06 12:17:41.035|DEBUG|FileSystem:Copying file C:\Users\psych\AppData\Local\Temp\Playnite\6a161692-0045-4857-8ecf-7cc79cf2a17b.jpg to D:\Playnite\library\files\1316358c-3a51-4ef3-8d6e-3b6454a505b4\491d466b-8a35-4747-a416-eab1ca3627df.jpg
26-06 12:17:41.035|ERROR|MetadataDownloader:Failed to download metadata for game Surgeon Simulator - Experience Reality, 1316358c-3a51-4ef3-8d6e-3b6454a505b4
LiteDB.LiteException: Datafile is not a LiteDB database.
   ב-  LiteDB.HeaderPage.ReadContent(ByteReader reader)
   ב-  LiteDB.BasePage.ReadPage(Byte[] buffer)
   ב-  LiteDB.PageService.GetPage[T](UInt32 pageID)
   ב-  LiteDB.PageService.RemoveToFreeList(BasePage page, BasePage startPage, UInt32& fieldPageID)
   ב-  LiteDB.PageService.AddOrRemoveToFreeList(Boolean add, BasePage page, BasePage startPage, UInt32& fieldPageID)
   ב-  LiteDB.PageService.NewPage[T](BasePage prevPage)
   ב-  LiteDB.DataService.Update(CollectionPage col, PageAddress blockAddress, Byte[] data)
   ב-  LiteDB.LiteEngine.UpdateDocument(CollectionPage col, BsonDocument doc)
   ב-  LiteDB.LiteEngine.<>c__DisplayClass33_0.<Upsert>b__0(CollectionPage col)
   ב-  LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func`2 action)
   ב-  LiteDB.LiteEngine.Upsert(String collection, IEnumerable`1 docs, BsonType autoId)
   ב-  LiteDB.LiteCollection`1.Upsert(IEnumerable`1 documents)
   ב-  LiteDB.LiteCollection`1.Upsert(T document)
   ב-  Playnite.Database.ItemCollection`1.Update(TItem itemToUpdate) ב- C:\projects\playnite\source\Playnite\Database\Collections\ItemCollection.cs:שורה 506
   ב-  Playnite.Database.GamesCollection.Update(Game itemToUpdate) ב- C:\projects\playnite\source\Playnite\Database\Collections\GamesCollection.cs:שורה 167
   ב-  Playnite.Metadata.MetadataDownloader.<>c__DisplayClass11_0.<DownloadMetadataAsync>b__0() ב- C:\projects\playnite\source\Playnite\Metadata\MetadataDownloader.cs:שורה 614
26-06 12:17:41.035|DEBUG|MetadataDownloader:Downloading metadata for TESV: Skyrim VR, b32b1e6625310937fd7397286be8f7e9, 00000000-0000-0000-0000-000000000000
26-06 12:17:41.270|DEBUG|MetadataDownloader:Downloading metadata for The Walking Dead Saints and Sinners Aftershocks, 6f36a241b205cac2c61ae913806c0ab4, 00000000-0000-0000-0000-000000000000
26-06 12:17:41.493|DEBUG|MetadataDownloader:Downloading metadata for TribeXR DJ School [Build 6690138], 21c0bd80247d9521acb5b28ece3d721e, 00000000-0000-0000-0000-000000000000
26-06 12:17:41.683|DEBUG|MetadataDownloader:Downloading metadata for Warhammer 40,000 Battle Sister, 31cc8be2f9a92e853d3332b2fe43b89a, 00000000-0000-0000-0000-000000000000
26-06 12:17:41.922|DEBUG|Downloader:Downloading data from https://images.igdb.com/igdb/image/upload/t_original/ar1h0r.jpg to C:\Users\psych\AppData\Local\Temp\Playnite\466eab8b-f0e6-4076-8437-67052f431740.jpg.
26-06 12:17:42.328|DEBUG|FileSystem:Copying file C:\Users\psych\AppData\Local\Temp\Playnite\466eab8b-f0e6-4076-8437-67052f431740.jpg to D:\Playnite\library\files\072d3170-8c3d-4c30-b7bb-14e063e785d4\d82ad332-5d0b-49ce-a30b-67b65bc3119a.jpg
26-06 12:17:42.328|DEBUG|Downloader:Downloading data from https://images.igdb.com/igdb/image/upload/t_original/co2z7o.jpg to C:\Users\psych\AppData\Local\Temp\Playnite\168dbd99-293c-434e-b65c-4137642bc3f6.jpg.
26-06 12:17:42.893|DEBUG|FileSystem:Copying file C:\Users\psych\AppData\Local\Temp\Playnite\168dbd99-293c-434e-b65c-4137642bc3f6.jpg to D:\Playnite\library\files\072d3170-8c3d-4c30-b7bb-14e063e785d4\e0edcc04-eafe-4d10-8587-ad840c21e417.jpg
26-06 12:17:42.905|ERROR|MetadataDownloader:Failed to download metadata for game Warhammer 40,000 Battle Sister, 072d3170-8c3d-4c30-b7bb-14e063e785d4
LiteDB.LiteException: Datafile is not a LiteDB database.
   ב-  LiteDB.HeaderPage.ReadContent(ByteReader reader)
   ב-  LiteDB.BasePage.ReadPage(Byte[] buffer)
   ב-  LiteDB.PageService.GetPage[T](UInt32 pageID)
   ב-  LiteDB.PageService.RemoveToFreeList(BasePage page, BasePage startPage, UInt32& fieldPageID)
   ב-  LiteDB.PageService.AddOrRemoveToFreeList(Boolean add, BasePage page, BasePage startPage, UInt32& fieldPageID)
   ב-  LiteDB.PageService.NewPage[T](BasePage prevPage)
   ב-  LiteDB.DataService.Update(CollectionPage col, PageAddress blockAddress, Byte[] data)
   ב-  LiteDB.LiteEngine.UpdateDocument(CollectionPage col, BsonDocument doc)
   ב-  LiteDB.LiteEngine.<>c__DisplayClass33_0.<Upsert>b__0(CollectionPage col)
   ב-  LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func`2 action)
   ב-  LiteDB.LiteEngine.Upsert(String collection, IEnumerable`1 docs, BsonType autoId)
   ב-  LiteDB.LiteCollection`1.Upsert(IEnumerable`1 documents)
   ב-  LiteDB.LiteCollection`1.Upsert(T document)
   ב-  Playnite.Database.ItemCollection`1.Update(TItem itemToUpdate) ב- C:\projects\playnite\source\Playnite\Database\Collections\ItemCollection.cs:שורה 506
   ב-  Playnite.Database.GamesCollection.Update(Game itemToUpdate) ב- C:\projects\playnite\source\Playnite\Database\Collections\GamesCollection.cs:שורה 167
   ב-  Playnite.Metadata.MetadataDownloader.<>c__DisplayClass11_0.<DownloadMetadataAsync>b__0() ב- C:\projects\playnite\source\Playnite\Metadata\MetadataDownloader.cs:שורה 614
26-06 12:17:42.923|INFO |MainViewModelBase:Starting Library Install Size scan
26-06 12:17:48.900|INFO |MainViewModelBase:Finished Library Install Size scan
26-06 12:18:00.808|DEBUG|WindowFactory:Show dialog window Playnite.DesktopApp.Windows.CategoryConfigWindowFactory: 6a0e77ac-81b6-4e8e-b979-aa502d143fe6
26-06 12:18:02.593|DEBUG|WindowFactory:Closing window Playnite.DesktopApp.Windows.CategoryConfigWindowFactory: 6a0e77ac-81b6-4e8e-b979-aa502d143fe6, True
26-06 12:18:03.961|DEBUG|WindowFactory:Show dialog window Playnite.DesktopApp.Windows.GameEditWindowFactory: c3b001dc-5813-4e13-80cb-247646c906e8
26-06 12:18:06.180|DEBUG|WindowFactory:Show dialog window Playnite.Windows.ProgressWindowFactory: 118759e1-5473-4096-a911-3450dbcd8e7d
26-06 12:18:06.205|DEBUG|WindowFactory:Show dialog window Playnite.DesktopApp.Windows.ItemSelectionWithSearchWindowFactory: e59b0038-4afa-4630-9038-eafcefbc4383
26-06 12:18:06.219|DEBUG|WindowFactory:Show dialog window Playnite.Windows.ProgressWindowFactory: d6da9276-dfbd-4e70-a585-e8f2487b2921
26-06 12:18:06.423|DEBUG|WindowFactory:Closing window Playnite.Windows.ProgressWindowFactory: d6da9276-dfbd-4e70-a585-e8f2487b2921, True
26-06 12:18:08.096|DEBUG|WindowFactory:Closing window Playnite.DesktopApp.Windows.ItemSelectionWithSearchWindowFactory: e59b0038-4afa-4630-9038-eafcefbc4383, True
26-06 12:18:08.200|DEBUG|WindowFactory:Show dialog window Playnite.DesktopApp.Windows.ImageSelectionWindowFactory: 50fdd58e-add6-4a2c-876a-4a9cf4a87550
26-06 12:18:09.281|DEBUG|WindowFactory:Closing window Playnite.DesktopApp.Windows.ImageSelectionWindowFactory: 50fdd58e-add6-4a2c-876a-4a9cf4a87550, True
26-06 12:18:09.342|DEBUG|Downloader:Downloading data from https://images.igdb.com/igdb/image/upload/t_1080p/co1m3a.jpg to C:\Users\psych\AppData\Local\Temp\Playnite\b9a441c8-3c56-4d15-b819-dd8916687626.jpg.
26-06 12:18:09.343|DEBUG|WindowFactory:Show dialog window Playnite.Windows.ProgressWindowFactory: e246ffe1-2d58-41c4-8095-2fc16577f8d2
26-06 12:18:09.367|DEBUG|WindowFactory:Closing window Playnite.Windows.ProgressWindowFactory: e246ffe1-2d58-41c4-8095-2fc16577f8d2, True
26-06 12:18:09.367|DEBUG|Downloader:Downloading data from https://images.igdb.com/igdb/image/upload/t_1080p/ar5t8.jpg to C:\Users\psych\AppData\Local\Temp\Playnite\77dc77eb-8aa8-4592-b204-ac2cb005d378.jpg.
26-06 12:18:09.367|DEBUG|WindowFactory:Show dialog window Playnite.Windows.ProgressWindowFactory: 8d22a870-1b44-46fc-a846-c324ae06d0ca
26-06 12:18:09.402|DEBUG|WindowFactory:Closing window Playnite.Windows.ProgressWindowFactory: 8d22a870-1b44-46fc-a846-c324ae06d0ca, True
26-06 12:18:09.420|DEBUG|WindowFactory:Show dialog window Playnite.DesktopApp.Windows.MetadataComparisonWindowFactory: bf7399a8-187e-4295-969b-b39718e75c1a
26-06 12:18:10.369|DEBUG|WindowFactory:Closing window Playnite.DesktopApp.Windows.MetadataComparisonWindowFactory: bf7399a8-187e-4295-969b-b39718e75c1a, True
26-06 12:18:10.377|DEBUG|WindowFactory:Show dialog window Playnite.Windows.ProgressWindowFactory: 74c8d6e8-75a1-4fdb-bdad-8b862921a1b3
26-06 12:18:10.393|DEBUG|WindowFactory:Closing window Playnite.Windows.ProgressWindowFactory: 74c8d6e8-75a1-4fdb-bdad-8b862921a1b3, True
26-06 12:18:10.443|DEBUG|WindowFactory:Show dialog window Playnite.Windows.ProgressWindowFactory: 53418003-e3bc-4759-af38-f84d52ff4894
26-06 12:18:10.443|DEBUG|WindowFactory:Closing window Playnite.Windows.ProgressWindowFactory: 53418003-e3bc-4759-af38-f84d52ff4894, True
26-06 12:18:10.516|DEBUG|WindowFactory:Closing window Playnite.Windows.ProgressWindowFactory: 118759e1-5473-4096-a911-3450dbcd8e7d, True
26-06 12:18:12.486|DEBUG|FileSystem:Copying file C:\Users\psych\AppData\Local\Temp\Playnite\temp_edit_preview_cover.jpg to D:\Playnite\library\files\f78a0266-3b1b-4ba2-9467-d4e24818cc24\e4ca3daf-3751-4227-83f3-9b52cecac414.jpg
26-06 12:18:12.486|DEBUG|FileSystem:Copying file C:\Users\psych\AppData\Local\Temp\Playnite\temp_edit_preview_background.jpg to D:\Playnite\library\files\f78a0266-3b1b-4ba2-9467-d4e24818cc24\d975eeba-9d75-409f-8080-79c914ea7795.jpg
26-06 12:18:12.513|ERROR|PlayniteApplication:Unhandled exception occured.
LiteDB.LiteException: Datafile is not a LiteDB database.
   ב-  LiteDB.HeaderPage.ReadContent(ByteReader reader)
   ב-  LiteDB.BasePage.ReadPage(Byte[] buffer)
   ב-  LiteDB.PageService.GetPage[T](UInt32 pageID)
   ב-  LiteDB.PageService.RemoveToFreeList(BasePage page, BasePage startPage, UInt32& fieldPageID)
   ב-  LiteDB.PageService.AddOrRemoveToFreeList(Boolean add, BasePage page, BasePage startPage, UInt32& fieldPageID)
   ב-  LiteDB.PageService.NewPage[T](BasePage prevPage)
   ב-  LiteDB.DataService.Update(CollectionPage col, PageAddress blockAddress, Byte[] data)
   ב-  LiteDB.LiteEngine.UpdateDocument(CollectionPage col, BsonDocument doc)
   ב-  LiteDB.LiteEngine.<>c__DisplayClass33_0.<Upsert>b__0(CollectionPage col)
   ב-  LiteDB.LiteEngine.Transaction[T](String collection, Boolean addIfNotExists, Func`2 action)
   ב-  LiteDB.LiteEngine.Upsert(String collection, IEnumerable`1 docs, BsonType autoId)
   ב-  LiteDB.LiteCollection`1.Upsert(IEnumerable`1 documents)
   ב-  LiteDB.LiteCollection`1.Upsert(T document)
   ב-  Playnite.Database.ItemCollection`1.Update(TItem itemToUpdate) ב- C:\projects\playnite\source\Playnite\Database\Collections\ItemCollection.cs:שורה 506
   ב-  Playnite.Database.GamesCollection.Update(Game itemToUpdate) ב- C:\projects\playnite\source\Playnite\Database\Collections\GamesCollection.cs:שורה 167
   ב-  Playnite.DesktopApp.ViewModels.GameEditViewModel.ConfirmDialog() ב- C:\projects\playnite\source\Playnite.DesktopApp\ViewModels\GameEditViewModel.cs:שורה 867
   ב-  Playnite.DesktopApp.ViewModels.GameEditViewModel.<get_ConfirmCommand>b__223_0(Object a) ב- C:\projects\playnite\source\Playnite.DesktopApp\ViewModels\GameEditViewModelCommands.cs:שורה 114
   ב-  Playnite.SDK.RelayCommand`1.Execute(Object parameter) ב- C:\projects\playnite\source\PlayniteSDK\RelayCommand.cs:שורה 205
   ב-  MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   ב-  System.Windows.Controls.Primitives.ButtonBase.OnClick()
   ב-  System.Windows.Controls.Button.OnClick()
   ב-  System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   ב-  System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   ב-  System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   ב-  System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   ב-  System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   ב-  System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   ב-  System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   ב-  System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   ב-  System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   ב-  System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   ב-  System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   ב-  System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   ב-  System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   ב-  System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   ב-  System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   ב-  System.Windows.Input.InputManager.ProcessStagingArea()
   ב-  System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   ב-  System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   ב-  System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   ב-  System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   ב-  System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   ב-  MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   ב-  MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   ב-  System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   ב-  System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   ב-  System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   ב-  MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   ב-  MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   ב-  System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   ב-  System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   ב-  System.Windows.Window.ShowHelper(Object booleanBox)
   ב-  System.Windows.Window.Show()
   ב-  System.Windows.Window.ShowDialog()
   ב-  Playnite.Windows.WindowFactory.<>c__DisplayClass16_0.<CreateAndOpenDialog>b__0(Object a) ב- C:\projects\playnite\source\Playnite\Windows\WindowFactory.cs:שורה 82
   ב-  System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   ב-  System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   ב-  System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   ב-  System.Windows.Threading.DispatcherSynchronizationContext.Send(SendOrPostCallback d, Object state)
   ב-  Playnite.Windows.WindowFactory.CreateAndOpenDialog(Object dataContext) ב- C:\projects\playnite\source\Playnite\Windows\WindowFactory.cs:שורה 57
   ב-  Playnite.DesktopApp.DesktopGamesEditor.EditGame(Game game) ב- C:\projects\playnite\source\Playnite.DesktopApp\DesktopGamesEditor.cs:שורה 52
   ב-  Playnite.DesktopApp.ViewModels.DesktopAppViewModel.EditGame(Game game) ב- C:\projects\playnite\source\Playnite.DesktopApp\ViewModels\DesktopAppViewModel.cs:שורה 1274
   ב-  Playnite.DesktopApp.ViewModels.DesktopAppViewModel.<InitializeCommands>b__319_59(Game a) ב- C:\projects\playnite\source\Playnite.DesktopApp\ViewModels\DesktopAppViewModel_Commands.cs:שורה 444
   ב-  Playnite.SDK.RelayCommand`1.Execute(Object parameter) ב- C:\projects\playnite\source\PlayniteSDK\RelayCommand.cs:שורה 201
   ב-  MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   ב-  System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   ב-  System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   ב-  System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   ב-  System.Windows.Threading.DispatcherOperation.InvokeImpl()
   ב-  System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   ב-  MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   ב-  System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   ב-  System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   ב-  System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   ב-  MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   ב-  System.Windows.Threading.DispatcherOperation.Invoke()
   ב-  System.Windows.Threading.Dispatcher.ProcessQueue()
   ב-  System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   ב-  MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   ב-  MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   ב-  System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   ב-  System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   ב-  System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   ב-  MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   ב-  MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   ב-  System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   ב-  System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   ב-  System.Windows.Application.RunDispatcher(Object ignore)
   ב-  System.Windows.Application.RunInternal(Window window)
   ב-  System.Windows.Application.Run(Window window)
   ב-  Playnite.DesktopApp.ProgramEntry.Main(String[] args) ב- C:\projects\playnite\source\Playnite.DesktopApp\ProgramEntry.cs:שורה 61
26-06 12:18:12.546|DEBUG|WindowFactory:Show dialog window Playnite.Windows.CrashHandlerWindowFactory: e5f2ef6b-047f-48fc-9ba1-123c7a441635
26-06 12:18:30.764|DEBUG|WindowFactory:Show dialog window Playnite.Windows.ProgressWindowFactory: 460ee617-8233-453c-b08d-7bb10f163175
26-06 12:18:32.367|DEBUG|WindowFactory:Closing window Playnite.Windows.ProgressWindowFactory: 460ee617-8233-453c-b08d-7bb10f163175, True
26-06 12:18:32.374|DEBUG|WindowFactory:Show dialog window Playnite.Windows.ProgressWindowFactory: b51e2ca6-b668-4260-a589-eb35dc60c89d
26-06 12:18:37.235|DEBUG|WindowFactory:Closing window Playnite.Windows.ProgressWindowFactory: b51e2ca6-b668-4260-a589-eb35dc60c89d, True
26-06 12:18:39.020|DEBUG|ProcessStarter:Opening URL: https://github.com/JosefNemec/Playnite/issues/new/choose
26-06 12:18:50.751|DEBUG|WindowFactory:Show dialog window Playnite.Windows.ProgressWindowFactory: 56dc8c2e-cb99-4bfe-b322-ae03c58ed432
26-06 12:18:52.244|DEBUG|WindowFactory:Closing window Playnite.Windows.ProgressWindowFactory: 56dc8c2e-cb99-4bfe-b322-ae03c58ed432, True
26-06 12:18:52.254|DEBUG|WindowFactory:Show dialog window Playnite.Windows.ProgressWindowFactory: fe503df2-7df4-4619-a6e3-1b3b57c4686a
26-06 12:18:58.173|DEBUG|WindowFactory:Closing window Playnite.Windows.ProgressWindowFactory: fe503df2-7df4-4619-a6e3-1b3b57c4686a, True

**Comment by JosefNemec** [comment]
Please do not open multiple issues for the same bug.

**Comment by TheNicceGuy** [comment]
> Please do not open multiple issues for the same bug.

sorry, i want to be more specific and organize
