### ISSUE TITLE
Unable to search for media images

### ISSUE THREAD

**Issue by yuemeng123456** [JosefNemec/Playnite#3464]
### Bug Description

Suddenly, IGDB media function cannot be used. All searches are invalid.

### To Reproduce

Suddenly, IGDB media function cannot be used. All searches are invalid.

### Diagnostics ID

Suddenly, IGDB media function cannot be used. All searches are invalid.

### Screenshots

Suddenly, IGDB media function cannot be used. All searches are invalid.

**Comment by Jeshibu** [comment]
Update your IGDB plugin via `main menu > Add-ons > Updates`
