### ISSUE TITLE
More filter options for Date Added, Date Modified Fields, last played fields

### ISSUE THREAD

**Issue by ZLoth** [JosefNemec/Playnite#3466]
### Feature description

As currently designed, the following fields are available for filtering for Date Added, Date Modified, and Last Played fields. These currently have the values of:

- Today
- Yesterday
- In The Past 7 Days
- In The Past 31 Days
- In The Past 365 Days
- More Than 365 Days Ago
- Never

It would be nice to have some additional values like:

- In The Past 60 Days
- In The Past 90 Days
- Specific date range
- By year

One example is that I had to rebuild my PlayNite library, and was resetting the Date Added to the actual purchase date. I could not filter to just May 5th, 2023, and it was more than 31 days ago.

**Comment by JosefNemec** [comment]
#1614
