### ISSUE TITLE
Playnite scanning size of games in library then crashing

### ISSUE THREAD

**Issue by shinjorai** [JosefNemec/Playnite#3470]
### Bug Description

When i start up playnite, no other extensions added it crashes when it gets to the part where it says "scanning size of games in library"  

The following is my playnite.log file if this helps. 
[playnite.log](https://github.com/JosefNemec/Playnite/files/11927076/playnite.log)

I do have a large library across platforms  7821 games in total, so it may have to do with that. 

Also after the crash when i start up playnite i get the following dialogue. 

Playnite closed unexpectedly while starting. This is usually caused by 3rd party theme or extension. Do you want to start in safe mode with all 3rd party add-ons disabled?

I dont have any 3rd party addons installed that im aware of. 

### To Reproduce

Not sure other than starting playnite letting it add all games to database, then scan  size of games in library where it crashes everytime.

### Diagnostics ID

e83db7e7-658a-4c7c-8401-2620efb25588

**Comment by JosefNemec** [comment]
There's no crash info in logs so this is not crashing in our code. Most likely caused by some 3rd party app doing something with Playnite process or something broken system wise. I recommend reinstalling Playnite and repairing .NET Framework install (Google how to do that, there's multiple ways including sfc utility).

**Comment by shinjorai** [comment]
Ive repaired .NET framework tried running it again, i shutdown EVGA precision and MSI dragon center in case either of those were interfering with it as i read something about that could be a possibility. These are results from windows event viewer.  How would i go about finding out what 3rd party app is interfering with it? Or is there a way to turn off the 
" scanning size of games in library" ?

Faulting application name: Playnite.DesktopApp.exe, version: 1.0.0.0, time stamp: 0xc5565ee0
Faulting module name: ntdll.dll, version: 10.0.19041.3086, time stamp: 0xfab6a536
Exception code: 0xc00000fd
Fault offset: 0x00048e43
Faulting process id: 0x52c8
Faulting application start time: 0x01d9ac67e2ed62e4
Faulting application path: C:\Users\kornbred\AppData\Local\Playnite\Playnite.DesktopApp.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report Id: 80bbc156-3894-44fd-9986-32ee840bc74c
Faulting package full name: 
Faulting package-relative application ID:

**Comment by JosefNemec** [comment]
You can disable it in general settings.

**Comment by shinjorai** [comment]
> You can disable it in general settings.

Ok tyvm for your help ill look for it
