### ISSUE TITLE
Add exclusions to the filtering feature

### ISSUE THREAD

**Issue by philou-felin** [JosefNemec/Playnite#3475]
### Feature description

I would love to use filters in the following way:

- To temporarily hide every games which have "simulator" as a genre.

This could be achieved by allowing us to use the filtering feature to ALSO exclude stuff.

That being said, users should be able to force the exclusion to also hide games which share more than one genre, i.e. if the game is both a "simulator" and "adventure" game, it would also be hidden because it contains the "simulator" genre,

**Comment by philou-felin** [comment]
Seems like this is similar to #2538.

**Comment by JosefNemec** [comment]
Planned as part of #2538
