### ISSUE TITLE
I love this program

### ISSUE THREAD

**Issue by lkhnkhlm** [JosefNemec/Playnite#3476]
### Bug Description

when I open Playnite I find a proplem when I choose scan automatically

### Diagnostics ID

41743b46-3cba-48a8-b592-bf484d1d3e41

### Screenshots

![screenshot_20230707_223943](https://github.com/JosefNemec/Playnite/assets/138930444/74297d5e-ed20-4846-90c4-0cb44efc1480)

**Comment by lkhnkhlm** [comment]
this program is amazing

**Comment by JosefNemec** [comment]
Something broken with your system, Playnite can't create folder selection dialog, try repairing your system (using sfc utility, full reinstall etc.).

```
Creating an instance of the COM component with CLSID {DC1C5A9C-E88A-4DDE-A5A1-60F82A20AEF7} from the IClassFactory failed due to the following error: 80040111 ClassFactory cannot supply requested class (Exception from HRESULT: 0x80040111 (CLASS_E_CLASSNOTAVAILABLE)).
```
