### ISSUE TITLE
I love this program

### ISSUE THREAD

**Issue by lkhnkhlm** [JosefNemec/Playnite#3477]
### Bug Description

when I open Playnite I find a proplem when I choose scan automatically

### Diagnostics ID

a26a99b7-7438-47c2-bb0e-47c7379c5d6d

### Screenshots

![screenshot_20230707_225407](https://github.com/JosefNemec/Playnite/assets/138930444/0e10d501-feb2-4330-83f6-8b08a35ef925)

**Comment by JosefNemec** [comment]
#3476
