### ISSUE TITLE
Too high

### ISSUE THREAD

**Issue by ArtexJay** [JosefNemec/Playnite#348]
I think it would much better if game description, cover and Genre box would be brought down, they are currently too high up and there is a lot of empty space underneath.
![capture](https://user-images.githubusercontent.com/32932497/34258379-b92245e8-e62b-11e7-8520-18ee77fcdbf3.PNG)

**Comment by JosefNemec** [comment]
One of the commits got into release by mistake, I'll fix it.

**Comment by JosefNemec** [comment]
Fixed in 3.3.1 repack
