### ISSUE TITLE
Playnite Does Not Support Games In Winapps Folder?

### ISSUE THREAD

**Issue by jcurbaniak** [JosefNemec/Playnite#3480]
### Bug Description

Apparently any game added to Playnite from the WinApps folder will not run.  They all get messages that two required DLLs are missing when the game is started.  The DLLs are SharedLibrary.dll and mrt100_app.dll.

Interestingly when the games are launched using a Windows created shortcut they run fine.

### To Reproduce

Do a Playnite automatic scan of the WinApps folder under Program Files and add any game to Playnite.  Then try to start the game.

### Diagnostics ID

91d2036c-7e6a-4516-ac34-99338badc01f

### Screenshots

![image](https://github.com/JosefNemec/Playnite/assets/134623850/f933d35b-d46a-43ee-8c25-9e856e73ff36)

**Comment by JosefNemec** [comment]
MS Store games and apps have to be imported via `main menu -> add game -> MS Store application` because they have to be started in a special way.

**Comment by jcurbaniak** [comment]
Thanks!!  Works great.  Playnite is a remarkable and very useful tool.

 

Jerry Urbaniak
