### ISSUE TITLE
Creating Backup in Parallel

### ISSUE THREAD

**Issue by EdwinRodger** [JosefNemec/Playnite#3481]
### Feature description

Currently backups are done before them main window shows. This may consume more time if the library is large. Instead of creating backup before opening playnite, it would be better to create backup in parallel thread as it would greatly decrease startup time of playnite. This issue may be related to #2026.

**Comment by Jeshibu** [comment]
The reason this currently isn't done is that any number of things could affect (and write to) the library that is being backed up, which could lead to read errors or corruption for the backup process. At most you could separate step 2 in this process:
- Copy library files somewhere
- Put those files in a single archive (.zip) and place that in the backup directory

Not sure how much time gain that would be, and it complicates the whole thing significantly.

**Comment by JosefNemec** [comment]
Current way is the safest one because we know 100% that nothing related to Playnite (built-in functionality or a plugin) is not accessing/changing data we are trying to back up. I'm closing this because of that. Trying to do backups while Playnite is fully initialized and running is just not safe.
