### ISSUE TITLE
Playnite Fullscreen compatibility issues with 4K streaming using Sunshine

### ISSUE THREAD

**Issue by draikor** [JosefNemec/Playnite#3482]
### Bug Description

This was most probably introduced with the latest release, as it was not happening before. For some reason, Playnite has stopped working with my current setup, whereas Steam Big Picture still works. I've tried safe mode without success.

Setup: PC with Sunshine installed, 4k HDMI dummy plug and software (MonitorSwitcher) that automatically switches the PC's main screen to the dummy output before running Playnite Fullscreen.

Previous behavior: When connecting to the PC via Sunshine/Moonlight, Sunshine would first make the proper switching using a call to the MonitorSwitcher app, then Playnite you start in Fullscreen mode on the 4k dummy output.

Current behavior: For some reason, Playnite prevents the switch from happening in the first place, then starts in Fullscreen mode using the wrong output (1080p monitor). Sometimes, Playnite will first complain that some 3rd party apps may be prevent it from properly running, and asks whether to restart in safe mode.

### Diagnostics ID

c31f8b53-de3c-47df-ba1c-058dc5bcb638

**Comment by Jeshibu** [comment]
What was the last version you used where it still worked for you?

**Comment by JosefNemec** [comment]
There were no changes to the app that could cause this for a long time now, so unless you were on very old build before (Playnite 9), something else must have update that started causing the issue, most likely Sunshine.

**Comment by draikor** [comment]
Hi, sorry for the late response. Thank you both for your messages.

> What was the last version you used where it still worked for you?

I'm currently on 10.18.

> There were no changes to the app that could cause this for a long time now, so unless you were on very old build before (Playnite 9), something else must have updated that started causing the issue, most likely Sunshine.

Okay, I thought it might have been Playnite since Steam Big Picture works. I'll reach out to the Sunshine devs instead.

**Comment by JosefNemec** [comment]
Closing since there's nothing we can do about streaming issues since we have no control over how graphics rendering is done.

https://github.com/JosefNemec/Playnite/wiki/Known-Issues#rendering-issues-while-streaming-playnite
