### ISSUE TITLE
Rom Scanner Returns No Results

### ISSUE THREAD

**Issue by jcurbaniak** [JosefNemec/Playnite#3484]
### Bug Description

I run a ROM scanner for Atari 7800 ROMs and get no results.  As I am new to this process it is entirely possible I am causing the problem.  At one point this WAS working but no longer for some reason.  I recycled Playnite but still not working.

### Diagnostics ID

b0ebe625-bb87-4318-9bf5-2582f648f9dc

### Screenshots

My Retroarch emulator is set up as follows:

![image](https://github.com/JosefNemec/Playnite/assets/134623850/2d50daee-7268-46c9-9604-b7e12a2a7f82)

My scanner run is set up as follows:

![image](https://github.com/JosefNemec/Playnite/assets/134623850/5e041c07-9c33-4e0d-9361-eb96a486f10b)

The scanner results are blank:

![image](https://github.com/JosefNemec/Playnite/assets/134623850/14ae58c5-096a-4686-90e4-53a5d954af59)

I do have ROMs in my target file.

![image](https://github.com/JosefNemec/Playnite/assets/134623850/6c452e1a-2d0a-4fb7-ab18-3b9980417e4e)

**Comment by JosefNemec** [comment]
You have no supported file types defined, see: https://api.playnite.link/docs/master/manual/emulators.html

**Comment by jcurbaniak** [comment]
Thanks!  That was very helpful.  I had no idea what was wrong.

 

Now I have encountered a new emulator based issue. 

 

I will open another item.

 

Jerry Urbaniak
