### ISSUE TITLE
Retroarch Error Message When Running Atari 7800 Game With Playnite

### ISSUE THREAD

**Issue by jcurbaniak** [JosefNemec/Playnite#3486]
### Bug Description

Game launch fails with this error message:

![image](https://github.com/JosefNemec/Playnite/assets/134623850/27d9104d-6fc2-4282-9405-954977d6bde2)

Retroarch configuration:

![image](https://github.com/JosefNemec/Playnite/assets/134623850/dbb46dab-f6f3-42ed-8143-d19dbe33dc9d)

Atari 7800 Scanner definition:

![image](https://github.com/JosefNemec/Playnite/assets/134623850/5902f4b9-fe65-436c-866a-11f9c292a9cb)

Any idea what it is looking for?

### Diagnostics ID

09392969-448a-499a-b181-dc0d52cf5910

**Comment by JosefNemec** [comment]
You don't have any executable or arguments specified. Please read [doc page](https://api.playnite.link/docs/master/manual/emulators.html) I already linked in that other issues to see how to properly configure emulation, ideally import emulators to have them configured automatically.

**Comment by jcurbaniak** [comment]
I am sorry.  I am confused.  I do not see any place to specify an executable name.  I take it in this case the executable is retroarch.exe.

 

I tried to Import the Emulator from the directory shown below C:/RetroArch-C64 where the emulator is stored and got nothing.   So I added the Emulator manually.

 

Here is my Retroarch directory.

 



 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

Thanks for all of your help.

 

Jerry Urbaniak

**Comment by jcurbaniak** [comment]
OK.  I found the executable name in the profile.  I used retroarch.exe.  I then loaded the core for Atari 7800.

 

But how do I get the game to start?

 

Jerry Urbaniak

 

From: ***@***.*** ***@***.***> 
Sent: Monday, July 10, 2023 11:27 AM
To: 'JosefNemec/Playnite' ***@***.***>
Subject: RE: [JosefNemec/Playnite] Retroarch Error Message When Running Atari 7800 Game With Playnite (Issue #3486)

 

I am sorry.  I am confused.  I do not see any place to specify an executable name.  I take it in this case the executable is retroarch.exe.

 

I tried to Import the Emulator from the directory shown below C:/RetroArch-C64 where the emulator is stored and got nothing.   So I added the Emulator manually.

 

Here is my Retroarch directory.

 



 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

Thanks for all of your help.

 

Jerry Urbaniak
