### ISSUE TITLE
Quirks with the UX and some requests

### ISSUE THREAD

**Issue by RubeensVinicius** [JosefNemec/Playnite#349]
So, after using Playnite for a couple weeks, these are the problems I found and some features requests related to the user experience.

### Games list
- Sort genres, developers, publishers, categories and tags alphabetically.

### Game details editor
- An option to import/export the game metadata. Maybe a zip file with images (icon, cover and background) and an xml file (info, links and actions).

**General tab**
- You can't insert spaces in the genre, developer, publisher, categories and tags fields if it's the last character, so you need to write "PixelArt" and then add the space after "Pixel".
- Maybe you should add a warning somewhere that the Description field is HTML sensitive, took me a while to figure out why it wasn't respecting my line breaks and that I should involve each one with a paragraph tag.

**Media tab**
- Show the image's dimensions, size and format.
- A button to save the images in the computer.

**Links tab**
- Buttons to reorder the links, as the ones on the actions tab.

### Appearance
- A profile for the Modern theme with the info box of the 3.2 version. Seems like you changed it because of the issue #340, but it had space enough for all the info and looked way better when you have a background image.
- ~~A slider to make all the background images blurry and/or darker. If the image is too detailed, it can be hard to read the text sometimes.~~ Well, I just figured out that you can do this just editing the theme. 🙄

**Comment by JosefNemec** [comment]
Just for #340, I had merged the wrong change originally, you can re-download 3.3 and it looks more as it did in 3.2, showing more of the background art.

**Comment by RubeensVinicius** [comment]
Hmm, I just updated it again and it's still not quite the old one. I liked the shadow on the bottom better than the square text boxes. But I just downloaded 3.2 again and copied it as a new theme. I should have thought of that before. 🙄

**Comment by evgdovg1996** [comment]
@RubeensVinicius Totally agree with you!
After the update 3.3, the modern theme lost its appeal and became another classic theme.
I hope Josef come back old variant in the future

**Comment by evgdovg1996** [comment]
For those who like the Modern theme of version 3.2 (like me, for example) - i updated it with fixes for strings and bug fixex from 3.3.
[Modern3.2.zip](https://github.com/JosefNemec/Playnite/files/1582510/Modern3.2.zip)

**Comment by JosefNemec** [comment]
> Sort genres, developers, publishers, categories and tags alphabetically.

Created #349

> An option to import/export the game metadata. Maybe a zip file with images (icon, cover and background) and an xml file (info, links and actions).

Already requested in #212

> General tab

Both added/fixed in 3.4

> Media tab

Created #393 and #395

> Buttons to reorder the links, as the ones on the actions tab.

Created #392 

> Appearance

I have reverted changes to 3.0 state (in version 3.4), since that's what most people liked.

I'm going to close this since I want to track every point separately, thanks for the feedback.
