### ISSUE TITLE
Error when opening install location on windows 11

### ISSUE THREAD

**Issue by Gu57avo** [JosefNemec/Playnite#3497]
### Bug Description

Upon clicking the "Open Install Location" button, I get an explorer.exe error saying: "The application was unable to start correctly (Oxc0000142). Click OK to close the application."
It doesn't matter if the game is a local game, or if it's from a digital store, the result is the same
![image](https://github.com/JosefNemec/Playnite/assets/109315036/458e5554-60c9-4eb2-b523-6d6bbc7ae900)

### Diagnostics ID

6ee0ac2d-50d7-4e17-8b5a-f315884d868f

**Comment by JosefNemec** [comment]
Something broken with your system. Try running sfc utility or reinstall Windows.
