### ISSUE TITLE
Everytime i start Playnite, I have to ligin again into BattleNet

### ISSUE THREAD

**Issue by Fusselchen87** [JosefNemec/Playnite#3499]
### Bug Description

Hi.
The headline says all.
Playnite tell me, it can't scan for games in Battle Net, coz I'm not logged in. I have to just click on it, type the password and it works then. No big deal. But maybe a bug!?
If you need more information, I want to give it to you. But atm idk what you could need. ^^' 

greetings
Dario

### Diagnostics ID

5b15837e-289f-4d9d-b5fc-49ea819ebfec

**Comment by JosefNemec** [comment]
https://github.com/JosefNemec/PlayniteExtensions/wiki/Battle.net-troubleshooting#authentication-being-lost-after-some-time

Also library plugin issues go to a different repository as mentioned in the issue template.
