### ISSUE TITLE
Uplay game import

### ISSUE THREAD

**Issue by JosefNemec** [JosefNemec/Playnite#35]
Full Uplay account sync is too complicated, but we could at least add support to automatically import installed games.

**Comment by ziplock9000** [comment]
Another vote for uPlay support.

**Comment by hdkiller** [comment]
Please do

**Comment by JosefNemec** [comment]
Ability to import installed games is now available in 1.0 release. Sadly I was unable to add support for all games including not installed ones, because I haven't found a way how to get necessary information about users account. So until Ubisoft opens their API more to public, this is what we get.
