### ISSUE TITLE
Add minimization function to large screen mode

### ISSUE THREAD

**Issue by henuoxi** [JosefNemec/Playnite#3500]
### Feature description

Add minimization function in the settings of large screen mode

### Screenshots

![屏幕截图(6)](https://github.com/JosefNemec/Playnite/assets/96648714/500334ae-16c7-44dd-89bf-2f81b599f654)

**Comment by JosefNemec** [comment]
Minimize is already there at the bottom of that menu, you are just using either too large font or a theme that prevents it from showing.
![image](https://github.com/JosefNemec/Playnite/assets/3874087/343a3eca-6f2b-4034-849e-629cae9d6fc9)
