### ISSUE TITLE
itchio not updated on the last version

### ISSUE THREAD

**Issue by x0rld** [JosefNemec/Playnite#3504]
### Bug Description

I have freshly installed playnite

When I try to import my game from itch.io I have an error saying "the itch.io client is not up to date, it requires the 25 version to synchronize"

### To Reproduce

install playnite and try to synchronize itch.io game

### Diagnostics ID

04336a86-b810-4007-a5ea-f53b4d9cb563

### Screenshots

![image](https://github.com/JosefNemec/Playnite/assets/45242856/cb32913b-9690-40b6-a785-3cdf3e09358f)

**Comment by JosefNemec** [comment]
And do you have itch app installed? If so, try reinstalling it.
