### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by TheNicceGuy** [JosefNemec/Playnite#3506]
### Bug Description

its crash with no reason

### To Reproduce

i play for some time and its crashes and sometimes even disconect all my usb and restart without some of windows futures include my controller and sound bar

### Diagnostics ID

79e0d5c1-0c0d-4538-a711-60c0286e9202

**Comment by JosefNemec** [comment]
File system issue or connection to a drive issue. When Playnite is trying to save data to where you have library folder set (D:\Playnite\), it fails with device not being accessible error. Nothing we can do about it.

> sometimes even disconect all my usb and restart without some of windows futures include my controller and sound bar

Sounds like hardware issue to me, USB port/hub issue most likely.
