### ISSUE TITLE
Playnite doesn't detect ROMs

### ISSUE THREAD

**Issue by 0zzyO** [JosefNemec/Playnite#3508]
### Bug Description

When one of my emulators(Ryujinx) updated, from then on playnite couldn't detect any roms including all the other emulators. I have checked and reset the path to my emulators and there seems to be nothing wrong yet the tool can't find my roms. 

### To Reproduce

I couldn't quite put my finger on why this happened but my guess is updating ryujinx was what caused it. Although I don't know if it's ryujinx spesific.

### Diagnostics ID

dd760093-3a25-4093-9ef3-b2d842b05d4f

### Screenshots

![image](https://github.com/JosefNemec/Playnite/assets/140543619/37885bca-d235-4aa2-86fc-2c97d83b7e9c)

**Comment by JosefNemec** [comment]
There's an error in the logs saying that emulator scanner you are using is pointing to non-existent emulator entry. If you've removed and then re-imported Ryujinx emulator, you need to fix its reference in emulator scanner's settings.

**Comment by 0zzyO** [comment]
Thanks for the reply.I did fix it's reference after I updated, at least I thought I did. In any case even if  I did something wrong on that part I still don't understand why other emulators broke as well. There should have been something wrong with just ryujinx, no ?

**Comment by JosefNemec** [comment]
An emulator updating outside of Playnite could not have affected how ROM scanning works inside Playnite, something else must have changed as well. Are you sure the files you are scanning are not imported already? Emulation scanner will skip already imported ROM files.

**Comment by 0zzyO** [comment]
I had thought about that but it seems I forgot I put the copy of the same game on the hidden list thus playnite though it had already imported the game.
