### ISSUE TITLE
"After I compiled the source code of playnite1018 and installed the generated exe, the bottom menu appears like this in fullscreen mode, and the controller is not working. Can you please tell me the reason for this?"

### ISSUE THREAD

**Issue by taobingqing** [JosefNemec/Playnite#3510]
### Bug Description

"After I compiled the source code of playnite1018 and installed the generated exe, the bottom menu appears like this in fullscreen mode, and the controller is not working. Can you please tell me the reason for this?"

### To Reproduce

"After I compiled the source code of playnite1018 and installed the generated exe, the bottom menu appears like this in fullscreen mode, and the controller is not working. Can you please tell me the reason for this?"

### Diagnostics ID

Please take a look at the screenshot.

### Screenshots

![image](https://github.com/JosefNemec/Playnite/assets/44764572/3bb1d651-9598-439c-9e78-f0a0887d18bc)

**Comment by JosefNemec** [comment]
https://github.com/JosefNemec/Playnite/wiki/Gamepad-Controller-support
https://github.com/JosefNemec/Playnite/wiki/Building#fullscreen-mode-development

**Comment by taobingqing** [comment]
How can I obtain a license? I want to modify some buttons in the fullscreen mode.

> https://github.com/JosefNemec/Playnite/wiki/Gamepad-Controller-support https://github.com/JosefNemec/Playnite/wiki/Building#fullscreen-mode-development

**Comment by JosefNemec** [comment]
Modify in what way?

**Comment by taobingqing** [comment]
> Modify in what way?

![image](https://github.com/JosefNemec/Playnite/assets/44764572/fd88dea0-8063-4684-9661-cf99931ada47)
Here's the thing, I want to let the kids at home play with it, but these two features have too much authority. Actually, I want to remove these two features so that the kids won't accidentally cause trouble for me.

**Comment by JosefNemec** [comment]
Just removing those buttons won't prevent related actions to be invoked on button press, you need to remove underlining button bindings in code behind as well.

As far as font license, the font is not available anymore so you'll have to get it some other way.

**Comment by taobingqing** [comment]
I'm sorry, I didn't quite understand. However, I did make changes at the code level. I compiled the source code, located the actions triggered when pressing the buttons, and commented them out before recompiling. But after compiling, the controller doesn't work in full-screen mode. Also, I'm not very familiar with the font license, so I'm not sure about that. Can you please help me?

> Just removing those buttons won't prevent related actions to be invoked on button press, you need to remove underlining button bindings in code behind as well.
> 
> As far as font license, the font is not available anymore so you'll have to get it some other way.
