### ISSUE TITLE
Ability to customize Discord Rich Presence with user's Discord Application API and possibly Imgur API.

### ISSUE THREAD

**Issue by shoraaa** [JosefNemec/Playnite#3514]
### Feature description

As title said, it would be nice if the Discord Rich Presence feature was actually have "advanced settings", which allow user to use their own Application API and possibly image hosting service API (such as Imgur), to customize their Rich Presence. 

The idea was taken from [DiscordBee](https://github.com/sll552/DiscordBee), which is the same but with MusicBee.
Example image:
![image](https://github.com/JosefNemec/Playnite/assets/24241275/987c2c5b-4dba-4128-9e4c-d9000676af1f)
![image](https://github.com/JosefNemec/Playnite/assets/24241275/f42faf5c-1f98-4bcb-ab4f-abc1d3f3a383)

**Comment by JosefNemec** [comment]
Discord rich presence support is actually being completely removed in next major release due to API limitations on Discord's side. So this would have to be made as a community plugin.
