### ISSUE TITLE
Option: Uncensor Image Search Images

### ISSUE THREAD

**Issue by sapioit** [JosefNemec/Playnite#3516]
### Feature description

Hi!

**Problem:** Images, like covers and backgrounds, show fine in the main screen and the media tab of the edit game details pane, but when I do a search for covers or backgrounds it shows a very blurred version of the images containing too much blood or gore (and now that I think of checking it, it blurs all images tagged as adult content, which could be images for/about adult games). If I select one I can then see it in the media tab so the search is working, only it is showing blur-censored the results in the Google image search pane.

**Current workaround:** Select each image one by one to see their contents, which takes a lot more time.

**Solution:** A checkbox (off by default) in the Settings > Metadata > Web Image Search, with the text "Uncensored Images". 

### Screenshots

![image](https://github.com/JosefNemec/Playnite/assets/3173159/79113f63-c97c-413d-a8d4-cb426b254693)

Edit: I'm only showing part of the image, because I don't want to show gore here. The rest of the image has a creature splattered on the ground.

**Comment by sapioit** [comment]
I found that one needs to access [this page](https://www.google.com/safesearch) and choose the third option to deactivate the censoring, the second option to have them blurred, or the first option to have them missing (filtered out). Would it be possible to add a web-view (i.e. an iframe) with [the page](https://www.google.com/safesearch), so we can choose the leveling of filtering we want? It could even be it's own dedicated page in the settings, if needed.

https://www.google.com/safesearch

**Comment by sapioit** [comment]
Apparently, in the [`source/Playnite/GoogleImageDownloader.cs`](https://github.com/JosefNemec/Playnite/blob/master/source/Playnite/GoogleImageDownloader.cs) file, there is a `getImages` function in which there is functionality used to reject the consent for google image searches, so we could have a similar function made which to be used to choose the setting we want for google searches.

**Comment by darklinkpower** [comment]
It's nothing that complicated, it just requires adding a `safe` parameter set to `off` e.g.: https://www.google.com/search?q=explicit+images&tbm=isch&safe=off

**Comment by sapioit** [comment]
Awesome! Now the remaining problem is adding that option. I tried doing a Pull Request, namely #3541 , but it says no more accepting Pull Requests until v11 is at least in Beta. Any idea how I could compile the project myself?

**Comment by sapioit** [comment]
Thank you very much! I appreciate it!
