### ISSUE TITLE
Why does Playnite crop some box art images when displayed?

### ISSUE THREAD

**Issue by jcurbaniak** [JosefNemec/Playnite#3520]
### Bug Description

Some box art images are cropped at the top.

For example:

![image](https://github.com/JosefNemec/Playnite/assets/134623850/4333ea0f-21ff-4761-a6f7-5cdb7de1b3fa)

The source image looks like this:

![image](https://github.com/JosefNemec/Playnite/assets/134623850/5c35dd6c-4d17-48dd-a7a8-e386966d00e2)

The source image is 214 X 306 pixels.
Kind of a nit to be sure, but slightly annoying.

Thanks,   Jerry Urbaniak

### To Reproduce

Not sure what triggers this behavior.

### Diagnostics ID

106b563a-d99d-456d-8512-509a125e2302

**Comment by Jeshibu** [comment]
That's done to make the image fit the box. If you want to leave blank space around the image if it's not the exact same aspect ratio, change `Settings > Appearance > Grid view > Stretch mode` to `Uniform` (or `Fill` if you want them to be stretched out of their aspect ratio)

**Comment by JosefNemec** [comment]
Closing, see Jeshibu's comment.

**Comment by jcurbaniak** [comment]
Yes, that worked great.  Set to Uniform.   Thanks very much.

 

Jerry Urbaniak

**Comment by jcurbaniak** [comment]
Yes, that worked great.  Set to Uniform.   Thanks very much.

 

Jerry Urbaniak
