### ISSUE TITLE
Allow passing the words "game" and the release year when doing a image or metadata search

### ISSUE THREAD

**Issue by ZLoth** [JosefNemec/Playnite#3526]
### Feature description

Sometimes, it's a good idea to add some additional words or phrases when doing a search. For the metadata search, it may be helpfull (when available) to provide the release year of the game. For image search, adding the keyword "game" will provide better results. As an example, searching for the word "Tacoma wallpaper" will bring up images of the Toyota Tacoma, while searching for "Tacoma game wallpaper" will bring up the expected game images. 

### Screenshots

![Search for just "Tacoma wallpaper"](https://github.com/JosefNemec/Playnite/assets/6700159/7e7c60b1-8067-408d-88a2-716cc36cd8f9)

![Search for "Tacoma game wallpaper"](https://github.com/JosefNemec/Playnite/assets/6700159/95549c7c-37e0-4f6f-91b0-c682996b0f84)

**Comment by Jeshibu** [comment]
No release date option, but you can change what the search strings are by default:
![image](https://github.com/JosefNemec/Playnite/assets/37979717/c87df1af-acef-4bc1-882d-b058e09b8829)
The available variable templates are {Name} and {Platform}

**Comment by chocolatechipcats** [comment]
Related: #3490

**Comment by JosefNemec** [comment]
Done in 10.30
