### ISSUE TITLE
Failed to Import Games Due to Lack of Disk Space

### ISSUE THREAD

**Issue by MasterZoen** [JosefNemec/Playnite#3529]
### Bug Description

While trying to import my game libraries from various platforms I received the following error:

Failed to Import games from Steam.
There is not enough disk space.

Checking the drive I installed Playnite to, I found that it had chewed through over 100GB of free space trying to import the libraries. Why is it using disk space at all? The games that are installed are already on a disk, and the games that are uninstalled don't need to use any space.

### To Reproduce

No clue.

### Diagnostics ID

3e8ba8e8-c40c-493c-90cb-e1f759edceb3

**Comment by JosefNemec** [comment]
I don't see how Playnite could take 100GB of disk space. Majority of needed space is for metadata (primarily background and cover images) and you would have to have 10s of thousands of games imported each with populated metadata to get even close to that size. And even in that case it mainly depends on what metadata providers you are using.

So you you either have some plugin installed that's saving additional data to Playnite folder or some other app is adding data to our folders.

So please double check if it's really Playnite taking up that space.

**Comment by orkeilius** [comment]
Maybe playnite don't have access to write/read to some folder
