### ISSUE TITLE
Filter panel not responding

### ISSUE THREAD

**Issue by sekuka925** [JosefNemec/Playnite#353]
When i click on filter symbol and write something to filter by, then i click on main menu button and then i want to open filter bar again, its not responding, it just doesnt show up anymore until restart, im attaching my theme file in case its something wrong with it, however its just edited color codes and some spacing numbers are changed in description layout. Theme is updated with new lines if the new update contains new/edited lines by this https://github.com/JosefNemec/Playnite/issues/325
![1](https://user-images.githubusercontent.com/4690548/34307212-3fdb17f6-e747-11e7-83b4-592ce328381f.jpg)

[Infinite.zip](https://github.com/JosefNemec/Playnite/files/1583124/Infinite.zip)

**Comment by JosefNemec** [comment]
Does it happen only with your custom theme or with the built-in ones as well?

**Comment by JosefNemec** [comment]
I'm unable to reproduce this, at least not with built-in themes. If you find a way how to reproduce it on demand (or provide theme that causes this), then please feel free to reopen.
