### ISSUE TITLE
Time Played Tracking Failure with Launcher-only Game (BG3)

### ISSUE THREAD

**Issue by matt-buckley** [JosefNemec/Playnite#3530]
### Bug Description

Intermittent issue with playtime tracking appears when launching a game that uses a game-specific launcher (in this case Baldur's Gate 3 when downloaded from GOG). Sometimes playtime will be tracking fine, other times it will only track the game as long as the launcher is open (aka for a few seconds at most). It's possible this issue was introduced with Hotfix 3 for BG3 but this is unclear.

### To Reproduce

Launch game launcher EXE directly using Playnite (rather than via Steam or GOG), playtime will occassionally not track.

### Diagnostics ID

15ddb7b3-779c-4c89-962e-41f2a97e38e4

**Comment by matt-buckley** [comment]
Apologies, seems I opened an issue too soon and solved it as soon as posted (as is inevitable). Issue can be resolved by launching directly from EXE in bin folder, no-one else seems to be facing an issue with the launcher so believe it may be specific to my installation.

**Comment by JosefNemec** [comment]
If the default tracking doesn't work with games using separate launcher process, then switching to folder tracking usually fixes it.
