### ISSUE TITLE
When I'm selecting multiple games, Media should display what I have locally before going to Internet

### ISSUE THREAD

**Issue by ZLoth** [JosefNemec/Playnite#3532]
### Feature description

I have a game (e.,g. GoNNER) that I obtained from three different sources (Steam in May 2017, Amazon Games in July 2018, Epic in March 2020). It would be nice if I can select all three games, go to Media, and have an button to allow me to select which of the images I have saved locally for those games, and have it populate across all of those selected games. This is especially important since we are unable to import icons for either Amazon Games or Epic Games.

**Comment by JosefNemec** [comment]
This is already supported, if you assign local image while bulk editing multiple games, the image will be assigned to all selected games.
