### ISSUE TITLE
Auth window only shows URL (when run in Wine)

### ISSUE THREAD

**Issue by tarasis** [JosefNemec/Playnite#3533]
### Bug Description

In 10.18 the auth dialogs appear empty, except for the URL.

<img width="526" alt="Screenshot 2023-08-20 at 03 07 30" src="https://github.com/JosefNemec/Playnite/assets/3006/188ae386-0cc9-419d-8956-0450ca779db7">

9.16 worked fine (installed via Lutris https://lutris.net/games/install/28929/view ), as does 10.1 (just tested)

Is there a package, font, dll that needs to be additionally installed?

### Diagnostics ID

724930f6-d467-4d6e-b590-fc2920da2ab5

**Comment by tarasis** [comment]
Just been trying older 10.x versions. Last working auth dialog was 10.3. 

I see in the release notes for 10.4 it says "Updated web view component".

So I guess I need to install something into that Wine that provides whatever you are using.

For now I am going to sign in on 10.3 to accounts, and then reinstall 10.18

**Comment by JosefNemec** [comment]
We don't support Playnite running under Wine. Also web views are handled by 3rd party package and I have no idea how it handles rendering under the hood.

**Comment by JosefNemec** [comment]
Native Linux port is being [considered](https://github.com/JosefNemec/Playnite/issues/59) in long term, but there's no ETA.

**Comment by tarasis** [comment]
I understand you don't offer support for it, thats entirely reasonable. Could you at least tell me what 3rd party package is used for the web views. It would give me a starting off point to see if there is anything I could install that would help it.

**Comment by JosefNemec** [comment]
https://github.com/cefsharp/CefSharp

**Comment by tarasis** [comment]
Thank you
