### ISSUE TITLE
Add option for game covers height position in horizontal layout 

### ISSUE THREAD

**Issue by EddyHg80** [JosefNemec/Playnite#3534]
### Feature description

Similar to the Playstation homescreen, I would love an option to place the game covers on the top side, in order to better display the background image below.

While you are at it, add an option to place them below too, some people may want that instead.

Thank you for your work!

**Comment by JosefNemec** [comment]
This should be handled via custom theme as we are not trying to emulate PlayStation as our UX. There are already themes that do this, you can see and download them via addons menu in Desktop mode.

**Comment by EddyHg80** [comment]
Okay thank you.
I thought it would be still a nice little option. I like the default theme and I just had this nitpick. :)
