### ISSUE TITLE
Playnite installation command line 

### ISSUE THREAD

**Issue by Koriebonx98** [JosefNemec/Playnite#3536]
### Feature description

When first installing playnite, is there away to to install silent via command line? 

Only asking as I’ve been using ntlite to make a custom version of windows 10 for my pc.

or is there away to zip a portable version of playnite and change into a custom installer?

**Comment by JosefNemec** [comment]
Playnite uses Inno Setup for the installed so their arguments apply to Playnite as well: https://jrsoftware.org/ishelp/index.php?topic=setupcmdline

**Comment by Koriebonx98** [comment]
Okay thank you
