### ISSUE TITLE
Guide button// focus menu 

### ISSUE THREAD

**Issue by Koriebonx98** [JosefNemec/Playnite#3538]
### Feature description

Possible feature or add-on for playnite.

where playnite has set to focus on guide button press (as long as game bar and steam are disabled)  

is there a way to to have settings for per game? 
for example the addon playstate allows minimal controller configuration such as alt tab, alt f4 ect.

this would be good so epic games guide press activates “shift + f3” or gog,Ubisoft ect to activate there gui 

it would be good to have guide button while in playnite loads the menu instead of the “back button” or as an option.

Or a possible gui for when “playnite is in or out of focus” 
E.g if playnite is open in fullscreen mode, guide button opens menu button instead of “back”

while playnite in background after launching a game, playnite displays a minimal gui to the left with controller navigation on guide press. While displaying game info on the right 

Such as 

“Home” - opens playnite again (if click same game it resumes game)

“Friends” - display friends tab (if addons for epic, gog ect they’ll display too) 

“Achievements” - activates either success story with info of achievements or opens “Achievement Watcher” via command line to the correct game with achievement data

close game: on click ask to confirm if clicks yes activates alt, f4 or close app script 

“Restart console” - ask for confirm before restarts pc 

“power of” - ask to confirm before continuing to lock/sleep or power of pc <user sets up at start or has a small menu with all 3 to choose from> 

Only put in request addon as if doesn’t get added as a feature possibly will as an addon

**Comment by JosefNemec** [comment]
You are basically describing in game overlay which we already have different issue for.
