### ISSUE TITLE
Playnite crashes saying library file corruption has been detected

### ISSUE THREAD

**Issue by ddeignan** [JosefNemec/Playnite#3539]
### Bug Description

Whenever I try to update the metadata for a game, playnite crashes and shows me the error above
[library.zip](https://github.com/JosefNemec/Playnite/files/12491609/library.zip)

### Diagnostics ID

4f58dd25-082b-4d5f-b49f-b51febcf1c72

**Comment by JosefNemec** [comment]
Here's fixed file: [games.zip](https://github.com/JosefNemec/Playnite/files/12495703/games.zip)
