### ISSUE TITLE
Not able to import games from Battle.net

### ISSUE THREAD

**Issue by jcurbaniak** [JosefNemec/Playnite#3540]
### Bug Description

I keep getting this message whenever Playnite starts.   I am however logged in to battle.net.

![image](https://github.com/JosefNemec/Playnite/assets/134623850/96d9abf8-7f92-4699-b8ac-7b39aea7bffb)

What am I doing wrong?   Five other extensions all work correctly.

Thanks,

Jerry Urbaniak

### Diagnostics ID

3c20190a-c96f-4c1b-926f-68c8d7a9a678

**Comment by JosefNemec** [comment]
https://github.com/JosefNemec/PlayniteExtensions/wiki/Battle.net-troubleshooting#authentication-being-lost-after-some-time

**Comment by jcurbaniak** [comment]
Thanks.  Lost authentication as documented.  Re-authenticating fixed problem.

 

Jerry Urbaniak
