### ISSUE TITLE
Shared access to database

### ISSUE THREAD

**Issue by KrystianLesniak** [JosefNemec/Playnite#3547]
### Feature description

Hello all

Lately I've been diving into the Playnite project and working on a plugin called GamesLauncher (https://github.com/KrystianLesniak/Flow.Launcher.Plugin.GamesLauncher).

In my quest to improve the plugin, I've been looking for ways to integrate the Playnite library into it.

However, I've encountered a hurdle in my exploration. When trying to access the Playnite database located at "%appdata%/Playnite/library/games.db", I've noticed that the file is constantly being locked by the Playnite process. As a result, I can't access it, which prevents me from effectively integrating my plugin.

Given these challenges, I'd like to ask if you might consider adding a shared database connection feature in the future. As mentioned in
https://www.litedb.org/docs/connection-string/
"Connection=shared"
"Shared: The engine will be close the datafile after each operation. Locks are made using Mutex. This is more expensive but you can open same file from multiple processes."

This would give me and other external tool developers access to the Playnite database and library. It has the potential to open up exciting possibilities for the Playnite community.

Thank you for your time and I'm looking forward to any feedback, be it yes or no.

Best regards

**Comment by JosefNemec** [comment]
There are no plans making database files directly shareable, mainly due to issues in the past with various apps doing weird things with them and causing random issues.

If you want to access game library data, you need to make a plugin for Playnite which would then communicate with the other app.
