### ISSUE TITLE
Corrupted Library crash

### ISSUE THREAD

**Issue by Musubhai** [JosefNemec/Playnite#3548]
### Bug Description

I can launch into Playnite fine and use it like normal except when I try to manually add a game it tells me that my library is corrupt and shuts down.

[library.zip](https://github.com/JosefNemec/Playnite/files/12566345/library.zip)

I have attached the .db files in AppData%\Playnite\library

### Diagnostics ID

3982ba92-5858-491f-bbf5-ea6922639dc6

**Comment by JosefNemec** [comment]
Here's fixed file: [games.zip](https://github.com/JosefNemec/Playnite/files/12566378/games.zip)
