### ISSUE TITLE
Download images from Microsoft / Xbox server in larger resolution in Google Images downloader

### ISSUE THREAD

**Issue by darklinkpower** [JosefNemec/Playnite#3549]
### Feature description

Currently the Google downloader commonly obtains images available in Microsoft's server in very low resolution `480x270`. These same images are downscaled from their original, larger resolution versions and can be obtained by changing a parameter.

Example of URL obtained during search: https://store-images.s-microsoft.com/image/apps.5684.14461820086048132.cb5b0df9-a838-4ec8-9af1-55effba7c55a.aa900afb-ca53-4013-a1d3-921f996d98b4?q=97&w=480&h=270

It's possible to change the `w` and `h` parameter to indicate the `width` and `height` respectively of the image to be obtained. For example, this would be the url to obtain the image in 1080p resolution: https://store-images.s-microsoft.com/image/apps.5684.14461820086048132.cb5b0df9-a838-4ec8-9af1-55effba7c55a.aa900afb-ca53-4013-a1d3-921f996d98b4?q=97&w=1920&h=1080

### Screenshots

Example of search using Google images:

![image](https://github.com/JosefNemec/Playnite/assets/1389286/84b323d6-b527-46c2-89a6-6f41ee52e3a4)

**Comment by darklinkpower** [comment]
A draft for the implementation is available here: https://github.com/darklinkpower/Playnite/commit/465c926bce8092fe16dc93c412e242a464787952

![image](https://github.com/JosefNemec/Playnite/assets/1389286/8cbb597d-cfd0-4513-b768-c3ef576c9dce)

With the changes in that commit, the parameters are being increased when the resolution is `480x270` and decreased when `3840x2180` to `1920x1080` but there's still one issue, the response code obtained here is not successful when changing the parameters, resulting in a fallback to the thumb url:

https://github.com/JosefNemec/Playnite/blob/d1634e849bd80c148374623d3a1b6582c3989674/source/Playnite.DesktopApp/ViewModels/GameEditViewModelMetadata.cs#L731-L736

It specifically obtains a `405` `Method not allowed` response

![image](https://github.com/JosefNemec/Playnite/assets/1389286/2b8f7b76-bffc-41b8-9da9-82a6f538c9c8)

For some reason, when changing this parameter this error happens with a `HEAD` request. Making a `GET` downloads it without issues but here's the weird thing, after making this request from anywhere, like a browser, Postman, whatever, the same `HEAD` request that was previously failing will be successful now, making it possible to download the image in Playnite. I'm not sure why this happens, perhaps Microsoft creates the image resource on first GET request, I don't know and I'm also not sure how this should be handled in Playnite itself.

**Comment by JosefNemec** [comment]
I'm not a fan of introducing special case download handling based on domain. Web image search is already pretty fragile because of the way it has to be implemented and adding more complexity to it is imo not a good idea.
