### ISSUE TITLE
Some advice on the appearance of the program

### ISSUE THREAD

**Issue by fighuass** [JosefNemec/Playnite#355]
Here's some ideas on how I'd improve the appearance of the program:

1. Add some animations. When you press the top left button (with the 3 stripes) for example, the menu just pops up out of nowhere, which doesn't look smooth. Also, when you click something, like a game, maybe make that look more smooth, too.
2. Also, at that menu, change the font. Right now it looks like comic sans.
3. Make the interface look more like a material design app ([example](https://cdn57.androidauthority.net/wp-content/uploads/2016/05/BH-Photo-screenshot-2017-840x472.jpg)), Phoenix ([example](https://raw.githubusercontent.com/team-phoenix/Designs/gh-pages/Screenshots/screen.png)) or OpenEmu ([example](http://openemu.org/img/intro-list.png)). Right now it doesn't look all that professional.
4. Maybe add more themes, or custom theme support. Latter would be best, I think.

Anyways, great program.

**Comment by fighuass** [comment]
> Also im pretty sure there is custom theme support already.

Source?

**Comment by CorruptComputer** [comment]
This guy has his own custom theme, afaik you can make it yourself of you want one: https://github.com/JosefNemec/Playnite/issues/353

**Comment by L1cardo** [comment]
@fighuass  can you give me the link of the Phoenix and the OpenEmu?   I want to test them

**Comment by JosefNemec** [comment]
https://github.com/JosefNemec/Playnite/wiki/How-to:-Themes

**Comment by fighuass** [comment]
Phoenix: https://github.com/team-phoenix/Phoenix
OpenEmu: http://openemu.org

Note that OpenEmu is only for Mac.

**Comment by L1cardo** [comment]
ok， got it.  thanks!

**Comment by JosefNemec** [comment]
Closing this since there has been a number suggestion improvements already implemented, plus new theming system is coming in 5.0.
