### ISSUE TITLE
Can't run a script with file name with bracket 

### ISSUE THREAD

**Issue by kent79** [JosefNemec/Playnite#3551]
### Bug Description

I would like to add a script as below to mount a ISO file, but it fail to run. I need to change the file name to "Disney-E.iso". Playnite seems not allow the name with bracket (E).  Please fix it. Thanks. 

Scripts execute before starting a game 
C:\progra~2\WinCDEmu\batchmnt.exe E:\Disney(E).iso Z: /wait

### Diagnostics ID

1

**Comment by JosefNemec** [comment]
Not a Playnite issue. You need to use `Start-Process` cmdlet and pass arguments properly:

https://api.playnite.link/docs/master/manual/gameScripts.html#examples
