### ISSUE TITLE
Add "Save as" in edit mode

### ISSUE THREAD

**Issue by herrenP** [JosefNemec/Playnite#3555]
### Feature description

I have a game that was detected automatically. I now realize I need two separate entries for this game since I have a need of two specific scripts that should run prior to launching the game. Which script depends on my PC setup at a given time. Instead of having to add a game manually I would like to open the original entry and do my edits and click "Save as" so that this new modified version becomes a separate entry.

**Comment by JosefNemec** [comment]
You can just add new play action to a game and then adjust your script based on what game action was used to start the game. 

Duplicating automatically added game entries like you propose is not safe because it could cause issues on plugin's side which imported the original entry.
