### ISSUE TITLE
What is the correct way to invoke Altirra for a game in Playnite?

### ISSUE THREAD

**Issue by jcurbaniak** [JosefNemec/Playnite#3557]
### Feature description

I would like to invoke an Atari 5200 game directly from Playnite.  What is the correct way to invoke Altirra on the Actions tab?

**Comment by JosefNemec** [comment]
https://forums.atariage.com/topic/327629-command-line-parameters-with-altirra/

**Comment by JosefNemec** [comment]
Also found this https://atarionline.pl/forum/?PostBackAction=Download&AttachmentID=10849
