### ISSUE TITLE
Is it possible using image insead of text of filters name in Full screen mode?

### ISSUE THREAD

**Issue by kent79** [JosefNemec/Playnite#3558]
### Feature description

as title

**Comment by JosefNemec** [comment]
If you use a theme that supports it.

**Comment by kent79** [comment]
I am using default theme. But didn't seen how to setup. Could you teach me how to do? Thanks.

**Comment by JosefNemec** [comment]
Default theme doesn't support it, might be added in future.

**Comment by kent79** [comment]
Playnite is the best frontend Ever that I seen. Please keep going :)

**Comment by JosefNemec** [comment]
Built in support will be added most likely via #2510
