### ISSUE TITLE
CompactModern Theme

### ISSUE THREAD

**Issue by Evene174** [JosefNemec/Playnite#356]
This is rework of modern theme of 3.2. version, with more compact elements.
-Сover and game information has been moved to the bottom since most images focus on the top / center.
-Removed top border
-Reduced list block
-7 colors for theme (Blue/White/Red/Yellow/Purple/Green/Orange)
![default](https://user-images.githubusercontent.com/26068083/34632027-0bf34112-f295-11e7-8aec-06cf555a17ed.png)

-updated 06.01 ver.1.4
[CompactModern1.4.zip](https://github.com/JosefNemec/Playnite/files/1608580/CompactModern1.4.zip)

examples at different resolutions:
720р - https://imgur.com/a/QXfSR
900р - https://imgur.com/a/0Ufq6
1080р - https://imgur.com/a/2UeNc

**Comment by ArtexJay** [comment]
This is honestly the best skin and the way i wanted playnite to look

**Comment by evgdovg1996** [comment]
@ArtexJay Thanks for the feedback!
I looked into your problem. It's a very strange, because i also use 1080p resolution. I don't change size of cover image - i change only the position of elements. For some reason, your interface in playnite does not scale and all the more mine if compared to the screenshots (Maybe do you use virtual resolution from drivers?)
Try to re-download archive( i updated this today) or open compactmodern.xaml and change all four value on -50/-75 (it's "y" ordinate and it should up proportionally elements)
![default](https://user-images.githubusercontent.com/26068083/34555697-eaf862f8-f154-11e7-8828-929b3af2317c.png)

**Comment by JosefNemec** [comment]
I've added this to [reddit theme list](https://www.reddit.com/r/playnite/comments/7o2bd2/custom_themes_database/) for people to find easily. Also new update will link to that thread from application itself.

**Comment by ArtexJay** [comment]
Alright I'll be giving it a try and yes its 1080p but the scaling is by default on my laptop 125%

**Comment by JosefNemec** [comment]
@Evene174 Don't use margins to offset the whole layout like you do. It will break in case of different DPI scaling, exactly like ArtexJay posted. If you need to offset the panel more to bottom just change the row scaling of parent grid. For example this specifies that two rows in grid will scale dynamically to fit 40% and 60% percent of the space respectively:

```
<Grid.RowDefinitions>
   <RowDefinition Height="4*"/>
   <RowDefinition Height="6*"/>
</Grid.RowDefinitions>
```

**Comment by DSPAUL** [comment]
Great theme! The problem i have apart from the scaling problem is that the "install" button is partially under the "more" button. The "play" button however is just fine as shown in the screenshot.

**Comment by L1cardo** [comment]
It is really a great theme, but it doesn't working well as it should be =(  
The steam games all look terrible , but battle net is nice !  The background of steam games seem vague unlike the battle net , You will know what I mean .....

And the button doesn't work on PC, I clicked it but nothing happened 

![1](https://user-images.githubusercontent.com/33802186/34620102-43942d9a-f27f-11e7-8544-afab0aa49bb0.png)
![2](https://user-images.githubusercontent.com/33802186/34620118-4d4c3e36-f27f-11e7-9e0e-246fa04e2a97.png)
![3](https://user-images.githubusercontent.com/33802186/34620124-534b2ffe-f27f-11e7-863d-84bc471f3b9b.png)

**Comment by Evene174** [comment]
@DSPAUL Fixed in 1.3,thanks for feedback.
Problem with scaling:  I'll try to fix it soon

**Comment by Evene174** [comment]
@ArtexJay @L1cardo 
Completely rewrote the code in 1.4, i checked - it works on most resolutions now.

**Comment by ArtexJay** [comment]
Now it's the best Theme! Yay

**Comment by bocest1986** [comment]
Love the theme, I get why everything is aligned to the bottom of the screen but the now open space would be perfect for a video window playing the game trailer or a gameplay video

**Comment by ArtexJay** [comment]
YES! This would be an awesome suggestion!

**Comment by JosefNemec** [comment]
Forgot to mention this before 4.0 release, but custom themes will be broken in Playnite 4. There has been some changes to localization strings and other stuff that will break your theme. It's one of the reasons why themming is being completely rewritten in #510. I'm sorry for the issues and not notifying you earlier.

**Comment by ArtexJay** [comment]
I will patiently wait, for your theme to support the upcoming version!

**Comment by Pikelot** [comment]
The theme doesn't work to me ;-; plz help
![image](https://user-images.githubusercontent.com/48073507/53532053-174e5c80-3ad4-11e9-851e-55dc3d9eb98a.png)

**Comment by JosefNemec** [comment]
@Pikelot As I said in my previous post. Existing theme are borken with 4.0 release and new proper theming is comming with #510 If you need to revert back then you can use `F4` hotkey to get back to settings.

**Comment by Pikelot** [comment]
@JosefNemec Oh, thank you

**Comment by JosefNemec** [comment]
I'm closing this since it won't be compatible with 5.0 theming changes, plus we should use different place to manage 3rd party themes.
