### ISSUE TITLE
Allow Users to Lock the PC from the Fullscreen Theme

### ISSUE THREAD

**Issue by TariqMK** [JosefNemec/Playnite#3563]
### Feature description

For those of us who have a console-like setup, being able to lock the PC after a gaming session would be very helpful.

The benefits include:

1. Being able to prevent the PC from unauthorised access or controller/keyboard input
2. Being able to secure the PC without shutting it down or putting it to sleep. This will allow the PC to continue acting as a Server for other devices on the LAN

**Comment by JosefNemec** [comment]
done
