### ISSUE TITLE
Native english Localization Variable insteaed of text aare displayed

### ISSUE THREAD

**Issue by AdrianMuszik** [JosefNemec/Playnite#3565]
### Bug Description

On a Freshly Installed Playnite version 10.19 there are some text that are not displayed.
English Language and it shows: 
`LOCSettingsRestartTitle` or `LOCSettingsTextRenderingModeOptionAuto`

### To Reproduce

I found these ina fresh install of Playnite 10.19

### Diagnostics ID

9f5fe71b-0a5b-499d-b37d-7f1b99cebc03

### Screenshots

![Playnite DesktopApp_26JpXn4xE6](https://github.com/JosefNemec/Playnite/assets/144274167/b625d013-945f-44d7-9657-97f64083e79e)
![Playnite DesktopApp_LYG1q9Ht21](https://github.com/JosefNemec/Playnite/assets/144274167/62dd95f0-235a-490d-bd8e-4b187906d6f1)
![Playnite DesktopApp_ooYl5Tlqs0](https://github.com/JosefNemec/Playnite/assets/144274167/3bdd8806-8c22-4aa9-bedf-aeafd04076b6)
![Playnite DesktopApp_minXgysC38](https://github.com/JosefNemec/Playnite/assets/144274167/fc2d9eaf-6777-494f-b0a3-7cc64e202cb6)
![tJDl4W4sLX](https://github.com/JosefNemec/Playnite/assets/144274167/93cea843-3833-435f-9511-79b278bb8b65)
![ewi8333FEW](https://github.com/JosefNemec/Playnite/assets/144274167/ae50a338-ca15-4cb1-9feb-77b32c209a48)
![u6d7Z2tsAd](https://github.com/JosefNemec/Playnite/assets/144274167/73cadcc0-bfc3-444a-accd-fb1ac1a09ce1)

**Comment by JosefNemec** [comment]
Can't reproduce with new or updated installation, these strings are properly displayed. No idea what's going on with you installation, I recommend reinstalling.

**Comment by AdrianMuszik** [comment]
> Can't reproduce with new or updated installation, these strings are properly displayed. No idea what's going on with you installation, I recommend reinstalling.

the funny thing is: I have 2 installs.
1 installed and 1 portable.
and both have the same issue. 
the portablée one is the one in the zip file downloadable from the releases.

**Comment by JosefNemec** [comment]
Can you upload `Localization` folder from one those installs? Or ideally the entire portable instance?

**Comment by AdrianMuszik** [comment]
Yesh sure here is the whole thing:

https://drive.google.com/file/d/1SOCgF83ekIpwMpgDaCp2Tj9w4vgxujn1/view?usp=drive_link

**Comment by JosefNemec** [comment]
Thank you. I launched your portable version and everything seems fine:
![image](https://github.com/JosefNemec/Playnite/assets/3874087/80d65088-155d-4b00-8f48-5d9db8801db8)

**Comment by JosefNemec** [comment]
What are your Windows regional settings? These:
![image](https://github.com/JosefNemec/Playnite/assets/3874087/da942ae7-4dc9-4304-98a4-de7ff805dd2f)

**Comment by AdrianMuszik** [comment]
Its Hungarian

![image](https://github.com/JosefNemec/Playnite/assets/144274167/d6ad92e7-dd8d-4e0d-a3ef-de70ff669ec6)

If i switch it to UK would that fix it?

**Comment by JosefNemec** [comment]
No idea, you can try. I'll try to reproduce it with HU settings later, can't do it now.

**Comment by AdrianMuszik** [comment]
tried it .
![image](https://github.com/JosefNemec/Playnite/assets/144274167/3ffeb8ae-d9a9-4450-8b7f-3f8aa91a1f4e)
sadly didntz solve it.

**Comment by JosefNemec** [comment]
Managed to reproduce it after switching Windows language and locale to Magyar. Will look into it.
