### ISSUE TITLE
Fuerboos Trojan alert in installer exe with Windows Defender

### ISSUE THREAD

**Issue by billybruiser** [JosefNemec/Playnite#357]
This popped up in Windows Defender today.  It was the latest installer.
<img width="960" alt="2017-12-22 1" src="https://user-images.githubusercontent.com/32617077/34314812-56853126-e73d-11e7-8471-eb4af5a5466b.png">

**Comment by JosefNemec** [comment]
False positive, I've done some googling and this is not the first time Defender reports app as this type of malware. I've submitted the file for review, but that's all I can do about it.

Anyway: https://www.virustotal.com/#/file/f60a0352c219f8e1aca2ef36a6b5342d36e55d64fb7608363d09a8b64e6fac3f/detection

**Comment by JosefNemec** [comment]
https://www.microsoft.com/en-us/wdsi/submission/8e7dab54-9065-4213-a397-185dbf4a326f

**Comment by JosefNemec** [comment]
I'm going to leave this open until MS get it's shit together and stops reporting this false positive.

**Comment by JosefNemec** [comment]
I closing this, new versions are not being reported anymore.
