### ISSUE TITLE
Icon missing for some games in Recently Played

### ISSUE THREAD

**Issue by ketchupfriend** [JosefNemec/Playnite#3572]
### Bug Description

Icons missing for some games in Recently Played, the right click menu for Playnite. The games in question have a icon downloaded and available in the metadata. This only seems to affect the games in my library that are not in Steam.

### To Reproduce

Here's what I did for Witcher 3:
1. Install game from GOG
2. Download the metadata for the game, including Steam as a metadata source
3. Launch game
4. Observe game showing in recently played, but without the game launch icon

### Diagnostics ID

20bbb1a9-89ce-4d89-8fdf-f42a9cc0e2ac

### Screenshots

Here ya go
![image](https://github.com/JosefNemec/Playnite/assets/146660173/b5628206-0df5-47cc-ab1a-65b3db6cba4e)
And screenshots of the affected games to prove that they have icons:
![image](https://github.com/JosefNemec/Playnite/assets/146660173/eabf5b87-7b80-4415-9c86-79115eea1f37)
![image](https://github.com/JosefNemec/Playnite/assets/146660173/8e004d79-2133-48fd-87b8-2d82a63f1ccf)
![image](https://github.com/JosefNemec/Playnite/assets/146660173/c7bbe43d-0129-4770-a5ac-9f03abff47f8)

Witcher 3 from GOG, Loop Hero from Epic Games, Titanfall 2 from EA Games. Interestingly, MTGA and 911 Operator are installed in Epic but does have an icon showing in the list.

**Comment by JosefNemec** [comment]
Nothing we can do about it because Windows only supports .ico images there.

**Comment by JosefNemec** [comment]
Also duplicate #3047
