### ISSUE TITLE
Unrecoverable error when adding new games

### ISSUE THREAD

**Issue by inCrooo** [JosefNemec/Playnite#3575]
### Bug Description

It's the same issue as #2895 and #3119. From what I have read, the only way to fix it is to manually fix the corrupted library file.

Here's my file
[games.zip](https://github.com/JosefNemec/Playnite/files/12813957/games.zip)

Thank you very much.

### Diagnostics ID

00000000-0000-0000-0000-000000000000

**Comment by JosefNemec** [comment]
Please attach diagnostics ID.

**Comment by inCrooo** [comment]
Diagnostics ID only shows up as 00000000-0000-0000-0000-000000000000. I'm not sure why.

![image](https://github.com/JosefNemec/Playnite/assets/56158640/c56a7a87-8e56-4652-8bd0-ab8ca60a8fa6)

**Comment by JosefNemec** [comment]
Then it means you are on old Playnite version, update to the latest one.

**Comment by inCrooo** [comment]
Yeah indeed I was. I updated and now I get this error

![image](https://github.com/JosefNemec/Playnite/assets/56158640/90d7b360-87f4-4195-8c25-0061313556d9)

Here's the diagnostics ID
5e8a0585-3c84-4578-9f07-4aa72fed2d35

Thank again.

**Comment by JosefNemec** [comment]
Fixed file: [games.zip](https://github.com/JosefNemec/Playnite/files/12817918/games.zip)
