### ISSUE TITLE
Restore native shadow beneath playnite window

### ISSUE THREAD

**Issue by RichardLuo0** [JosefNemec/Playnite#3580]
### Feature description

Windows 11 has a conspicuous shadow beneath every window. But Playnite somehow lacks the shadow. It makes Playnite unfit with the system UI.

### Screenshots

![image](https://github.com/JosefNemec/Playnite/assets/22096448/1cb65af3-03e6-4f42-9ed5-9f38d98dcda5)
Playnite window
![image](https://github.com/JosefNemec/Playnite/assets/22096448/1b64cfc7-f6db-4be5-a2f5-3e18cb43869c) 
Chrome shadow for comparison

**Comment by JosefNemec** [comment]
Not possible with current UI framework because it doesn't properly support Mica borders. Will be fixed with move to different UI framework in #1141
