### ISSUE TITLE
Some emulator profiles are misssing their .zip/.7z compatibility, alongside other extensions.

### ISSUE THREAD

**Issue by OmegaOmega** [JosefNemec/Playnite#3581]
### Bug Description

I tested these emulators by dragging and dropping the ROMs into the emulators. 

**.zip support:**

Ares: Sega SG-1000
OpenMSX

**.zip and .7z support:**

BizHawk: GCE Vectrex, Magnavox Odyssey 2, Nintendo DS/DSi, Uzebox
MelonDS
Mesen: All of them except the default profile

**Other extensions:**
jzIntvImGui - .int

### Diagnostics ID

c653dc2e-ee66-428f-a0d2-20fc9fdb6df7

**Comment by OmegaOmega** [comment]
An addendum: FS-UAE can also open .zip files now

**Comment by JosefNemec** [comment]
Done in 10.30

**Comment by KartikKurt** [comment]
Emulator gets stuck or crashes when launching game after adding Melon ds emulator profile and importing nintendo Ds games which are in zip format.
Melon DS plays zip format games when launched in standalone, but doesn't work with playnite
