### ISSUE TITLE
Playnite v10.20 will not import Retroarch from an external drive; however simply copying the Retroarch folder from the external drive to the C: drive will allow Playnite to import Retroarch correctly.

### ISSUE THREAD

**Issue by JunglePredator** [JosefNemec/Playnite#3583]
### Bug Description

Playnite v10.20 will not import Retroarch from an external drive; however simply copying the Retroarch folder from the external drive to the C: drive will allow Playnite to import Retroarch correctly.

### To Reproduce

Steps to reproduce the bug:
Install Retroarch in G:\Retroarch
Try to get Playnite v10.20 to import; will not import.
Copy G:\Retroarch to C:\Retroarch (or do a fresh install of Retroarch; copying is just to verify it doesn't depend on registry).
Attempt another import after restarting Playnite
Playnite will detected all installed Retroarch cores in C:\Retroarch\cores.

### Diagnostics ID

Not Submitted

**Comment by JosefNemec** [comment]
Attach requested diagnostics ID
