### ISSUE TITLE
Create custom fields (numeric or date)

### ISSUE THREAD

**Issue by kostasmarkakis** [JosefNemec/Playnite#3586]
### Feature description

I am not sure if my use of playnite is out of scope but it would be particularly interested for people to be able to add custom fields like numeric fields or date fields.
I am a collector and i am using playnite (also) to categorize my collection.
But something that is lacking is to be able to catalog a game's price or date of purchase.
Right now i am using tag field for price but since it is a string field it does not short values correctly. 
thanks

**Comment by JosefNemec** [comment]
Will be done via #801
