### ISSUE TITLE
Aurora Skin

### ISSUE THREAD

**Issue by sekuka925** [JosefNemec/Playnite#359]
Ive been working on my personal custom skin for Playnite and i want to share it with you, in readme file is everything important to achieve the same result as in screenshots, unfortunaely, the covers and bg images you have to create yourself, the background images (wallpaper or screenshot) are just blured and covers are rounded
[Aurora.zip](https://github.com/JosefNemec/Playnite/files/1584022/Aurora.zip)

![cover](https://user-images.githubusercontent.com/4690548/34318787-81bc857c-e7d0-11e7-9bbf-6691aebc864e.jpg)
![a](https://user-images.githubusercontent.com/4690548/34318797-a9d95788-e7d0-11e7-8c32-9163b238e22f.jpg)

**Comment by RubeensVinicius** [comment]
Duuude, this looks really nice. Really smart workaround to get the screenshots. I already made a request for a slider to blur the background images, if Josef adds it, your skin would be even easier to use. :eyes:

Thanks for sharing. 👍

**Comment by sekuka925** [comment]
@RubeensVinicius thanks, enjoy

**Comment by Lithium1988** [comment]
@sekuka925 It would be verry nice if you could add a Coverview. I tryed to do it but I'm kinda too stupid to open the sourcecode in VisualStudios...
+ I really like the color style and the theme itself =)

**Comment by sekuka925** [comment]
you man replace the circle image by game cover?

**Comment by Lithium1988** [comment]
@sekuka925 Nope :P the circle image isn't even showing up on me, i mean a full new tab wich will change the view itself to a cover view. Like in the Classic Cover view

**Comment by sekuka925** [comment]
@Lithium1988 oh, i have no skills to do that, all what i did is based on work with notepad

**Comment by Lithium1988** [comment]
@sekuka925 i see =) so like me xD but thx anyway!

**Comment by RubeensVinicius** [comment]
So, I'm trying to make a theme and I just figured something out that might be handy for you. You don't need to blur the backgrounds manually, you can add some lines to the theme .xaml to do this automatically.

![x300_clipboard image](https://user-images.githubusercontent.com/15078228/34382341-4bd2fd56-eaf5-11e7-9016-61dae4ae80e5.png)
![clipboard image 1](https://user-images.githubusercontent.com/15078228/34382346-50d69600-eaf5-11e7-9972-dbbb7b304a98.png)

You just have to add this line inside your Image tag:
`<Image.Effect><BlurEffect Radius="50"/></Image.Effect>`

**Comment by sekuka925** [comment]
Thanks, very useful, my PC is broken atm but will add it asap

**Comment by JosefNemec** [comment]
I've added this to [reddit theme list](https://www.reddit.com/r/playnite/comments/7o2bd2/custom_themes_database/) for people to find easily. Also new update will link to that thread from application itself.

**Comment by JosefNemec** [comment]
Maybe in future, I'm currently more focused on idea of #298. Making it easier for people to find and install 3rd party themes.

Making 3rd party themes part of default installation would mean that I would have to maintain them and make sure that they 100% work with each update, which I don't have a time for right now. But I'm not against an idea of switching some of the default themes for user made one if it's really good and preferred by users.

**Comment by sekuka925** [comment]
@RubeensVinicius hey brother, im back with developing this skin and i would like to apply your blur effect suggest, however im not sure what do you mean by "add this line inside your Image tag" , can you point me out? thanks

**Comment by JosefNemec** [comment]
There's no easy way to blur image at the moment. Also I would probably wait making any major changes to your theme because one of 4.x version will come with reworked themming framework, see #510

**Comment by sekuka925** [comment]
@JosefNemec thanks for letting me know, i will wait than

**Comment by RubeensVinicius** [comment]
@sekuka925  If you still want to try it, just search for a image tag with `BackgroundImage` on the Source value. If it ends with `/>` you'll have to change it to `> </image>`. Then you just need to place the image effect tag between the brackets.

**Comment by JosefNemec** [comment]
Forgot to mention this before 4.0 release, but custom themes will be broken in Playnite 4. There has been some changes to localization strings and other stuff that will break your theme. It's one of the reasons why themming is being completely rewritten in #510. I'm sorry for the issues and not notifying you earlier.

**Comment by JosefNemec** [comment]
I'm closing this since it won't be compatible with 5.0 theming changes, plus we should use different place to manage 3rd party themes (probably new forums in near future).
