### ISSUE TITLE
The description box of the PS5ish theme cannot be slid

### ISSUE THREAD

**Issue by Itachi0833** [JosefNemec/Playnite#3590]
### Bug Description

When I updated from 10.09 to 10.10, the description box of the PS5ish theme couldn't slide, while 10.09 can. I don't know where the problem is, please help. Thank you.

### Diagnostics ID

no

### Screenshots

![e050638f7b885f95b0eb9247018117f](https://github.com/JosefNemec/Playnite/assets/149048209/fc881c46-ce94-4a99-b65d-a9a80ab2c2c6)

**Comment by JosefNemec** [comment]
This repository is for issues related to Playnite itself. You need to report this to theme's developer.
