### ISSUE TITLE
Filter Presets

### ISSUE THREAD

**Issue by Itachi0833** [JosefNemec/Playnite#3591]
### Feature description

Can you add the Filter Presets feature for version 10.09? I really need it, please

**Comment by JosefNemec** [comment]
No, update Playnite to newer version. Why are you still on 10.09?

**Comment by Itachi0833** [comment]
I don't want to, but the theme producer hasn't updated yet, and 10.09 is the perfect fit, but I want this new feature

**Comment by Itachi0833** [comment]
Hello, I really need a version 10.09 with FilterPresets added. Can you hide it and help me? I can pay for it




---Original---
From: "Josef ***@***.***&gt;
Date: Thu, Oct 26, 2023 18:58 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [JosefNemec/Playnite] Filter Presets (Issue #3591)




 
No, update Playnite to newer version. Why are you still on 10.09?

**Comment by JosefNemec** [comment]
I'm not backporting any features to old versions, you'll have to find somebody else to do it.

Just update to the latest version, themes made for earlier P10 versions will work in the latest 10.20 unless the theme is doing something unsupported.

**Comment by Itachi0833** [comment]
I know this request is unreasonable, but I really can't help it. I have found many people in China who don't know how to handle it. Could you please take a look at which statement in the description box of PS5ish cannot be dropped down? I'm going crazy! The theme author has also lost contact


---Original---
From: "Josef ***@***.***&gt;
Date: Fri, Oct 27, 2023 16:04 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [JosefNemec/Playnite] Filter Presets (Issue #3591)




 
I'm not backporting any features to old versions, you'll have to find somebody else to do it.
 
Just update to the latest version, themes made for earlier P10 versions will work in the latest 10.20 unless the theme is doing something unsupported.
