### ISSUE TITLE
"Time Played" Never Updates

### ISSUE THREAD

**Issue by Snipe3000** [JosefNemec/Playnite#3594]
### Bug Description

I noticed "Time Played" for steam games never gets updated. Mine seems to be sitting at the same time played amount from when I initially setup Playnite, and as far as I can tell, there is no way to force an update.

### To Reproduce

Setup Playnite, note the time played for steam games. Play the games, months later the time played will be the same.

### Diagnostics ID

3ffbc473-7653-4ace-a96b-78c145c8a1bf

### Screenshots

![Playnite DesktopApp_E5WerjwIrA](https://github.com/JosefNemec/Playnite/assets/1177321/ae4fe91f-2c1a-4545-a8ec-fb6479ca6c08)
![Playnite DesktopApp_RixliLAqve](https://github.com/JosefNemec/Playnite/assets/1177321/2087b744-bb41-4ff7-99e9-d27339d98846)
![Playnite DesktopApp_xx0w8uR7H8](https://github.com/JosefNemec/Playnite/assets/1177321/76e704d8-b981-4032-959a-0ab5b52dfd85)
![steamwebhelper_SqWhPGyA2S](https://github.com/JosefNemec/Playnite/assets/1177321/eb9510cf-a94a-4cb0-b175-dcbcb8a75c88)

**Comment by Jeshibu** [comment]
Have a look at this: https://api.playnite.link/docs/manual/gettingStarted/configuringPlaynite.html#importing-playtime-from-third-party-libraries-and-services

If that still doesn't work: https://github.com/Jeshibu/PlayniteExtensionsFeatures/blob/main/faq.md#steam-specific-playtime-troubleshooting

**Comment by Snipe3000** [comment]
> Have a look at this: https://api.playnite.link/docs/manual/gettingStarted/configuringPlaynite.html#importing-playtime-from-third-party-libraries-and-services
> 
> If that still doesn't work: https://github.com/Jeshibu/PlayniteExtensionsFeatures/blob/main/faq.md#steam-specific-playtime-troubleshooting

Looks like that fixed it, Thanks. I guess it defaults to "off"

**Comment by JosefNemec** [comment]
The default state is "Only for newly imported games" not "Never", you had to change it at some point.

**Comment by Snipe3000** [comment]
"Only for newly imported games" is an off state. It pulls play time when first imported, then never again.
