### ISSUE TITLE
In grid mode, the game information on the right is missing

### ISSUE THREAD

**Issue by huangjiandead** [JosefNemec/Playnite#3598]
### Bug Description

It turns out that the interface in grid mode is similar to this ， 
![thumb-2](https://github.com/JosefNemec/Playnite/assets/45986985/1c87bbb9-cefc-4085-a110-5975f2b831b9)
After selecting a game, basic information about the game will be displayed on the right。
now The page looks like this in grid mode,
![2](https://github.com/JosefNemec/Playnite/assets/45986985/c094a009-dd93-4937-98ca-275d0ac9714f)
i can‘t find basic information about the game display on the right，How can I set it up to restore the original appearance?

### Diagnostics ID

514f5be9-021a-4839-a33c-269cc8e4989d

### Screenshots

![2](https://github.com/JosefNemec/Playnite/assets/45986985/4f7eefd5-801b-4ac7-9759-7efa21894856)

**Comment by JosefNemec** [comment]
Click the "i" button displayed over game cover.
