### ISSUE TITLE
Bug: Data saving warning pops up when no data edited, when editing multiple items

### ISSUE THREAD

**Issue by Acru** [JosefNemec/Playnite#3599]
### Bug Description

The new save data warning dialog always pops up when multiple items are selected to view/edit, then canceling, even when nothing is actually edited.  The dialog should not trigger in the case where the data is viewed for multiple items but not changed.

### Diagnostics ID

335e475f-3ec6-4810-9686-22c9bffdbd25

**Comment by JosefNemec** [comment]
Fixed
