### ISSUE TITLE
Can not auto import  the Origin games

### ISSUE THREAD

**Issue by L1cardo** [JosefNemec/Playnite#360]
Playnite can import the Origin game at the first time it is installed , but after I removed the Origin game manually , it can not auto import the game at the next startup 
The reload game list button didn't work either .

here is the log
[1.zip](https://github.com/JosefNemec/Playnite/files/1584155/1.zip)

**Comment by JosefNemec** [comment]
You don't have any Origin games installed according to diag. package. I don't see why you would expect them to be imported, there's nothing to import.

**Comment by L1cardo** [comment]
No no . I have installed Battlefield 1.
What I mean is that after I first installed Playnite, it could import Battlefield 1 successfully . Then I removed Battlefield accidentally , and Playnite didn't auto import it at the next startup. 
I tried to remove Steam games and Battle Net games, Playnite can re-import them. Only Origin fails.

![1](https://user-images.githubusercontent.com/33802186/34323923-134aeaf2-e898-11e7-8ad6-c872ca4e5398.png)

**Comment by JosefNemec** [comment]
But the diag. package doesn't show BF1 as installed, at least not according to files Playnite uses to detect installed Origin games. I'm not sure what to do about it, you will probably need to reinstall BF1.

**Comment by L1cardo** [comment]
Well , ok then . Re-downloading the 70 GB files will be killing me ,  haha .
Anyway , thanks!

**Comment by JosefNemec** [comment]
You don't need to re-download it, rename folder with BF1, uninstall it, rename it back and install it back. Origin won't re-download the whole game if it finds the files being there already.

**Comment by L1cardo** [comment]
OK， I will do as you said， thanks

**Comment by JosefNemec** [comment]
Let me know if it fixed the issue so I can close this. Thanks

**Comment by L1cardo** [comment]
I did as you said, the rename-and-rename thing, and the BF1 appeared in Playnite.  You can close the issue now .  It is solved .Thanks!
