### ISSUE TITLE
System tray and Recent Activity

### ISSUE THREAD

**Issue by ThomasWeber** [JosefNemec/Playnite#3600]
### Bug Description

If you display games by Recent Activity and and launch a game from the system tray, the game order is not updated to reflect the launch. The Recent Activity field is updated correctly.

### To Reproduce

- Sort games by Recent Activity (I am using Descending order and grid view)
- Launch a game
- Check the order

### Diagnostics ID

1911f63c-fd7c-4662-918c-b8dbfcc98b52

**Comment by JosefNemec** [comment]
#1995
