### ISSUE TITLE
Can't search for web images on game backgrounds

### ISSUE THREAD

**Issue by LandoLakes011** [JosefNemec/Playnite#3605]
### Bug Description

Basically the title, when trying to edit a game's background or cover image by web search there is just absolutely nothing there. Even tried uninstall playnite and reinstalling.

### To Reproduce

I just try to search for an image, its always like this now

### Diagnostics ID

38d7aed1-72ca-42c5-b76f-14d85bd8ee54

### Screenshots

![image](https://github.com/JosefNemec/Playnite/assets/26018675/279707c4-35ed-4e9f-8cdc-49d4b6b23a82)

**Comment by JosefNemec** [comment]
Try deleting web cache via advanced settings.
