### ISSUE TITLE
Sorting by age rating sorts the games in respect to the first digit instead of the whole number

### ISSUE THREAD

**Issue by mMajestro** [JosefNemec/Playnite#3607]
### Bug Description

Hi there you beautiful people behind such an ultra useful tool. Thanks a lot for the development!!

I recognized that, when you sort titles by age rating, the list starts with PEGI 12, then 16, 18, and then starts with 3, then 7, then 'none'. The 'none' is in the right place in my opinion, but would it be nicer to have the titles sorted by whole numbers, starting with 3 (or 0, if added manually) and ending with 18. Hope this isn't too much work for this small improvement.

All the best to you!

### To Reproduce

Just click on the title of the age rating column to sort.

### Diagnostics ID

f8d429dd-d406-461a-9699-f416e5567624

### Screenshots

![age rating](https://github.com/JosefNemec/Playnite/assets/136154521/e2c3dc9c-9be8-4255-ae50-92c7383f2285)

**Comment by JosefNemec** [comment]
Will be fixed with #671
