### ISSUE TITLE
Filter menu not overlaying over art

### ISSUE THREAD

**Issue by NastyFlytrap** [JosefNemec/Playnite#3608]
### Feature description

Basically, right now if i open the filter tab in my library, it exists on the same level as the background and the cover for the game and pushes it to the side, (obscuring the edit button if the cover is wide enough, which is probably not an intended feature..), and im saying that when we open the filter tab, it should appear over the background, and the cover art.

The layering should be background, cover above it, and if open, filter menu above the cover, so its not pushing anything anywhere, and it stays nice and fixed.
Also, keep the mild blur of the filtering menu, and just blur the things under it, like the cover art it'd be layered over

**Comment by JosefNemec** [comment]
Screenshot please of what exactly you are talking about.

**Comment by NastyFlytrap** [comment]
![image](https://github.com/JosefNemec/Playnite/assets/43176063/30085431-535a-4b25-8678-942e9f4b97ae)
The cover art and wallpaper exists on the same layer as the filter menu, and to make space for it you're pushing it to the left.

Im suggesting that you move the wallpaper down two layers, the cover down one layer, so its above the wallpaper, and the filter menu would be on top of both the cover and the wallpaper, and you'd blur them with the same blur its already using

**Comment by JosefNemec** [comment]
These are completely separate panels and it would imo not make sense from UX point view. Can be done by making custom theme if you really want to have it that way.
