### ISSUE TITLE
Corrupted library.

### ISSUE THREAD

**Issue by TheCrowSpain** [JosefNemec/Playnite#3609]
### Bug Description

Hello!

I'm having a problem every time I try to add a game manually to my library. It's saying that my library is corrupted.

It happened after I created a portable version of Playnite and installed in OneDrive, with the intention to share use the program in two different computers. 

Thank you for your help!

### Diagnostics ID

f4c7a05c-a636-4c8c-a962-11da01482e90

**Comment by JosefNemec** [comment]
Go to [game library folder](https://api.playnite.link/docs/manual/gettingStarted/helpAndTroubleshooting/faq.html#where-can-i-find-the-library-folder-with-all-games) and attach all .db files you find there.

**Comment by CleanToris** [comment]
Hi, I have the same problem and I don't understand the issue of attaching the .db files, could you explain in more detail?

**Comment by JosefNemec** [comment]
Go to [game library folder](https://api.playnite.link/docs/manual/gettingStarted/helpAndTroubleshooting/faq.html#where-can-i-find-the-library-folder-with-all-games), zip .db files you find there and upload them here.

**Comment by CleanToris** [comment]
Hi, I managed to solve the problem, in the Playnite library folder, I deleted the games.db file and opened Playnite again, so the app pulled all my games again, the downside is that I had to manually add each game again.
