### ISSUE TITLE
3.3 Reported as a Trojan

### ISSUE THREAD

**Issue by NathanJPlummer** [JosefNemec/Playnite#361]
Attempting to update to Playnite 3.3 from 3.2 within the program results in Windows Defender reporting a Trojan and blocking installation.  I tried to take a screenshot of this but after two attempts Playnite is not even offering the update anymore.

Meanwhile, try to update manually from the install file results in this message:

> This app can't run on your PC.
> To find a version for your PC, check with the software publisher.

**Comment by JosefNemec** [comment]
See #357

**Comment by NathanJPlummer** [comment]
@JosefNemec 

Ah, sorry about that.  Did a search and poked around a bit, but didn't find anything.  Thanks for the link.
