### ISSUE TITLE
Unable to start full screen theme

### ISSUE THREAD

**Issue by 104979058** [JosefNemec/Playnite#3611]
### Bug Description

The full screen theme has been downloaded, but after restarting, it still remains the default full screen theme

### Diagnostics ID

1111222

### Screenshots

![QQ截图20231130091333](https://github.com/JosefNemec/Playnite/assets/28974521/fccd0796-77c3-4f00-bb81-1249f1d3a5e3)

**Comment by JosefNemec** [comment]
You need to activate it via settings -> appearance -> theme
