### ISSUE TITLE
Xbox Library Authentication failing

### ISSUE THREAD

**Issue by cfsantiago** [JosefNemec/Playnite#3612]
### Bug Description

Since yesterday, authentication with the Xbox library has stopped working. I tried uninstalling and installing again, but when trying to authenticate nothing happens. I looked in the log and found this:

01-12 08:06:18.289|ERROR|XboxLibrary#XboxLibrarySettingsViewModel:Failed to authenticate user.
System.NullReferenceException: Referência de objeto não definida para uma instância de um objeto.
   em XboxLibrary.Services.XboxAccountClient.<Authenticate>d__8.MoveNext() na C:\Devel\PlayniteExtensions\source\Libraries\XboxLibrary\Services\XboxAccountClient.cs:linha 159
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em XboxLibrary.Services.XboxAccountClient.<Login>d__6.MoveNext() na C:\Devel\PlayniteExtensions\source\Libraries\XboxLibrary\Services\XboxAccountClient.cs:linha 90
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em XboxLibrary.XboxLibrarySettingsViewModel.<Login>d__9.MoveNext() na C:\Devel\PlayniteExtensions\source\Libraries\XboxLibrary\XboxLibrarySettingsViewModel.cs:linha 59

Any idea what happened? 

Thanks.

### Diagnostics ID

fd900503-6e3e-4049-b294-9f29aad1a470

**Comment by JosefNemec** [comment]
Wrong repository, also already reported in correct one.

https://github.com/JosefNemec/PlayniteExtensions/issues/338
