### ISSUE TITLE
Playnite Blocking Advanced Optimus Auto-switch

### ISSUE THREAD

**Issue by GodSponge** [JosefNemec/Playnite#3616]
### Bug Description

Whenever Playnite is running, it blocks Advanced Optimus from switching to the discreet video card. I have Playnite set to run on the DGPU in Nvidia's settings and in windows settings just to be sure and that doesn't work either.

I've also tried disabling HW accel in Playnite and this doesn't change anything.

As long as Playnite is running, it can't auto switch. No other app on my computer prevents switching. 

I saw one article that mentioned that you can force an app to switch, even if it's not compatible, but there was no mention of how. Other than that one article I've found no other mention of this.

To be clear, this is the Advanced Optimus auto switch. I can manually change GPU in NV control panel and Playnite and the game work as expected.

### To Reproduce

Have Advanced Optimus enabled.
Run playnite.
Start a game.
Get error saying that Playnite is blocking display mode switch.

### Diagnostics ID

02980f15-e0a3-4448-8673-447f71f02f4e

### Screenshots

<img width="738" alt="Screenshot 2023-12-04 232344" src="https://github.com/JosefNemec/Playnite/assets/20741982/1bf7cada-dabe-4551-b545-d3379c633355">

**Comment by JosefNemec** [comment]
I'm afraid there's nothing we can do about this. We have basically zero control over how GPU is used because it's completely obfuscated from us by UI library we are currently using.

**Comment by mbushnaq00** [comment]
I am also having the same issue. Steam beta was also causing a problem in switching display mode, however after reverting back to a non-beta steam the app no longer block display switch. However I cant figure out how to prevent playnite from block display switching

**Comment by GodSponge** [comment]
> I am also having the same issue. Steam beta was also causing a problem in switching display mode, however after reverting back to a non-beta steam, the app no longer blocks display switching. However, I can't figure out how to prevent playnite from block display switching

I've just had to turn off Advanced Optimus. Playnite just doesn't play nice with it. You can turn off Advanced Optimus and just use the standard version by going into the nvidia control panel. Under "Manage Display mode" Select "Automatic Select" instead of "Optimus" Switching will be handled the old way and be controlled by Windows instead of the nvidia control panel.

**Comment by JosefNemec** [comment]
Closing per my last comment, nothing we can do about it.

**Comment by Rohan1857** [comment]
<img width="1504" height="862" alt="Image" src="https://github.com/user-attachments/assets/bb358721-79ad-44a7-a535-5a1f4269ef09" /> firstly install a add-on named lauchmate then create a group, set launch conditions to All Games and Action type to run script and set action delay to 10ms. Now Create a text file paste this text
"@echo off
taskkill /f /im Playnite.FullscreenApp.exe
exit"
and then change the extension of the file to .bat using save as now add this file location in launchmate.This is for fullscreen mode for  desktop mode just replace its fille name in the .bat file and it should work keep in mind action delay should be 10ms or it wont work.

**Comment by JosefNemec** [comment]
> taskkill /f /im Playnite.FullscreenApp.exe

DO NOT USE THIS! It can lead to library data corruption depending on what the app doing. Call Playnite exe with `--shutdown` argument which will close any running instance gracefully.
