### ISSUE TITLE
Excluding Emulated Subfolder with Relative Path

### ISSUE THREAD

**Issue by Burner911** [JosefNemec/Playnite#3618]
### Bug Description

When excluding subfolders for an emulated folder, in this case `Games`, I would expect the following paths to be excluded using the folders following:

**Paths**
```
Games/Doom/Updates
Games/Doom/DLC
Games/Doom/Other
```

**Excluded folders**
```
..\Updates
..\DLC
..\Other
```

This is not the case however and contents of `Updates`, `DLC`, and `Other` are still scanned. Am I using this feature incorrectly?

### Diagnostics ID

84a156d5-b382-4156-baba-765bb49aa47b

**Comment by JosefNemec** [comment]
Also not sure if this is even doable. `..` is for parent folder relative to a path. So in your specific case it would be `Updates` folder on the same level as `Games` folder. It will require some custom syntax or support for excluding folder names from any subfolder, not just root to a scan folder.

**Comment by CraniumFarmer** [comment]
Interesting, ok thank you for the feedback. In this case, would you recommend storing the base game file in one directory and any additional files in another directory I guess? This would work, but excluding subfolders like I mentioned would be a little cleaner to keep related files all in one place.

**Comment by JosefNemec** [comment]
I'll add some option to exclude folders and files by name no matter how nested they are.

**Comment by JosefNemec** [comment]
Done in 10.30

documentation here: https://api.playnite.link/docs/manual/features/emulationSupport/addingEmulatedGames.html#excluding-files-and-folders-from-import-completely
