### ISSUE TITLE
Search shortcut

### ISSUE THREAD

**Issue by PhrozenByte** [JosefNemec/Playnite#362]
When typing in the main window, Playnite should immediately start searching/filtering games without the need to actually click into the search box.

**Comment by JosefNemec** [comment]
I disagree, adding something like CTRL-F (or F1) to focus the search is more acceptable. Functionality like this shouldn't be automatically enabled by just typing, that's bad UI design.

**Comment by PhrozenByte** [comment]
Whether this is good or bad UI design depends on whether there might be another reason why a user started typing. I don't think that there is a single other action a user might want to take when typing in the main window - or do I miss something? Thus it's IMO very reasonable to assume that the user wants to take this action, rather than requiring the user to explicitly initiate a search, something that might rather disturb the UX. Things like <kbd>Ctrl</kbd> <kbd>F</kbd> are a good idea nevertheless. However, instant search is a pretty common functionality (like in Windows 10's start menu) and a consistent further development of search boxes focused by default (like on Google).

**Comment by ghostwheel** [comment]
I also like instant search. Especially for an interface to be used with small handhelds, like the GPD win, requiring ctrl-f or F1 is just too hard.

**Comment by JosefNemec** [comment]
I've added `CTRL-F` shortcut in 4.2 which focuses main search bar and `ENTER` or `ESC` then exits from it. "Just typing" search could work for Fullscreen mode in future, but I don't see getting in Desktop mode. There's too many possible issues with focus from different control, not even counting in custom themes that could possible break it.

**Comment by JosefNemec** [comment]
I'm closing this since it would be nearly impossible to implement reliably with how WPF handles input. You can use `CTRL-F` shortcut to initiate search.
