### ISSUE TITLE
Playnite not responding when launching a Steam game

### ISSUE THREAD

**Issue by RobLR** [JosefNemec/Playnite#3620]
### Bug Description

When I try and launch steam games the app becomes unresponsive for about 20 seconds, then the game launches.

Other launchers don't have this problem. 

I uninstalled and deleted all my user data from local and roaming, then reinstalled and synced the library again, but it is still happening

### To Reproduce

Launch a game from the Steam library

### Diagnostics ID

d2beb11a-3b13-43ac-ab7a-84cd0169d9d0

### Screenshots

![image](https://github.com/JosefNemec/Playnite/assets/94964242/e392f900-742b-463d-938b-6e990ce4bdcc)

**Comment by JosefNemec** [comment]
Game startup is handled by Steam plugin, not by Playnite itself so this would be Steam plugin issue.

This specific case is probably this Steam bug: https://github.com/JosefNemec/PlayniteExtensions/wiki/Steam-troubleshooting#long-delay-after-launching-a-game-before-it-actually-starts

**Comment by RobLR** [comment]
Didn't see that page sorry. Disabling the igpu has fixed it. Thank you
