### ISSUE TITLE
Library File Corrupted

### ISSUE THREAD

**Issue by CalciB** [JosefNemec/Playnite#3621]
### Bug Description

This happened after trying to add windows games which were already in library after they were marked as uninstalled by installation status updater. Library db files attached below

### To Reproduce

Trying to delete those apps from the library

### Diagnostics ID

ac64c6fb-ba8f-4f13-acd3-3afba9be86be

### Screenshots

[
[library.zip](https://github.com/JosefNemec/Playnite/files/13650052/library.zip)
](url)

**Comment by JosefNemec** [comment]
Fixed: [games.zip](https://github.com/JosefNemec/Playnite/files/13650151/games.zip)

**Comment by CalciB** [comment]
Thank you so much!
