### ISSUE TITLE
Crash on switch from fullscreen to desktop mode

### ISSUE THREAD

**Issue by benspray** [JosefNemec/Playnite#3622]
### Bug Description

Just switching from full screen to desktop, not sure what went wrong though, I've tried a few times and it crashes each time even in safe mode

### Diagnostics ID

48c9ef9d-28fb-47ee-bb63-1212c10c688c

**Comment by benspray** [comment]
I've fixed this - the config.json file had a filter defined that had no matches (I had uninstalled a game since last using desktop mode) so when the desktop mode loaded it had no matches and seemed to cause a crash.
Manually changed the filter in the config file so that it had a match and it loads fine now - maybe just needs some logic to ignore this type of error? cheers

**Comment by JosefNemec** [comment]
I'm uploading 10.31 hotfix which fixes the issues.
