### ISSUE TITLE
SDL/XInput selectable for controller inputs.

### ISSUE THREAD

**Issue by ersan** [JosefNemec/Playnite#3624]
### Feature description

Since the 10.30 release yesterday I've had multiple issues with simultaneous controllers being detected properly and Playnite not responding to controller inputs.

XInput worked perfectly for me, the switch to SDL has caused my issues.  I've rolled back to 10.20 which works fine and will likely have to stay on that version if I can't work around these problems.

I was hoping to be able to select between XInput and SDL as options, like how you can for audio options.

**Comment by JosefNemec** [comment]
SDL supports XInput controllers no problem according to my tests. What issues exactly are you having? What controllers show up in Fullsreen mode's input settings? If you are using some DirectInput -> XInput emulator then make sure it's not duplicating or hiding devices to Playnite.

We are not going to the back old solution which was problematic in other ways. SDL is de facto industry standard library used by ton of games and even by Steam for Steam input handling.

**Comment by JosefNemec** [comment]
Btw when I tested, I tested it with Xbox 360 controller, Xbox Series controller (wired and wireless) and DualShock 3 (both XInput emulated and DirectInput "native" modes), all worked properly.

**Comment by JosefNemec** [comment]
Also please go to "About Playnite" menu in Desktop mode and generate diag. package for me.

**Comment by JosefNemec** [comment]
Then it sounds like some incompatibility between Sandboxie and SDL. Nothing I can do about it and definitely not worth downgrading to previous input handling system which only supported XInput devices.
