### ISSUE TITLE
Humble library sync keeps requiring authentication

### ISSUE THREAD

**Issue by as232** [JosefNemec/Playnite#3625]
### Bug Description

Ever since the 10.31 update, every time I launch PN, I am told that the Humble library cannot sync because it requires authentication. I authenticate, and then it works. Then the next time I launch, I have the same problem.

### To Reproduce

Update 10 10.31.
Launch PlayNite.
Authenticate to Humble.
Reboot computer.
Repeat.

### Diagnostics ID

2216fb5c-9c67-49a9-9130-0a57614ff6c1

**Comment by JosefNemec** [comment]
https://github.com/JosefNemec/PlayniteExtensions/issues/345

**Comment by as232** [comment]
Hello,

Why do you reference someone else reporting the same issue 3 days after I did, then close the ticket with no comment?  What is this supposed to mean?

Why do I donate money towards this project when I don't get a coherent response to issues?

**Comment by JosefNemec** [comment]
You reported the issue in wrong repository. The issue template clearly states:

> If an issue is related to library integrations, use separate [extensions repository](https://github.com/JosefNemec/PlayniteExtensions) to file a report.

So I linked you an existing report of the same issue from the correct repository.

**Comment by JosefNemec** [comment]
The other one is not closed.
