### ISSUE TITLE
selection sounds

### ISSUE THREAD

**Issue by Itachi0833** [JosefNemec/Playnite#3626]
### Bug Description

Hello, may I ask why there are two game selection sounds when starting from full screen mode on 10.31? Previously, there was one sound

### Diagnostics ID

无

**Comment by Itachi0833** [comment]
It seems that the operation mode of sound has changed. Sometimes, when activating full screen mode, the background sound will be played in advance. Moreover, when playing game preview videos in full screen mode, if you click to turn off the video sound, the background sound will be played from scratch, while the background music in 10.20 will be played at a breakpoint

**Comment by JosefNemec** [comment]
> if you click to turn off the video sound

Not sure what that means, Playnite has no support for video playback. If you are using some extensions for it, it's probably an issue with the extension.

**Comment by Itachi0833** [comment]
But now when starting full screen mode, there are indeed two times to choose the sound of the game, that is, navigation.wav will play twice

**Comment by JosefNemec** [comment]
Fixed in 10.32
