### ISSUE TITLE
A button unfunctional after hibernate

### ISSUE THREAD

**Issue by lukeskope** [JosefNemec/Playnite#3630]
### Bug Description

After putting device to hibernate, for longer than 30 minutes, A button no longer works in Fullscreen mode 

### To Reproduce

Reported on ROG Ally and Legion Go.  Put device into hibernate.  Wait 30 minutes.  Wake device.  A button does nothing

### Diagnostics ID

5b6857c4-f536-4077-8cd9-4b816b47170b

**Comment by absolution1** [comment]
I just came to report a similar bug.  For this is happening on a Windows PC and an xbox series x controller.  I can confirm that it seems related to playnite as the a button still works in game.
If it helps, my joy2key shortcuts also stop working (but only while playnite is in focus, and after hibernating)

**Comment by JosefNemec** [comment]
Fixed in 10.32
