### ISSUE TITLE
Playnite Close!

### ISSUE THREAD

**Issue by MarkyCY** [JosefNemec/Playnite#3639]
### Bug Description

When I want to add a game or in edit I push Installation the app just close.

### Diagnostics ID

5b144db8-88cc-467c-9f5b-3157733aeca5

**Comment by JosefNemec** [comment]
Some issue with your system. UI library we are using can't write temp files:

> Acceso denegado a la ruta de acceso 'C:\Windows\TEMP\WPF'

**Comment by MarkyCY** [comment]
Thank u, I have found the solution, I just opened playnite in Administrator mode
