### ISSUE TITLE
Game screenshots support

### ISSUE THREAD

**Issue by Lithium1988** [JosefNemec/Playnite#364]
Do you think it's possible to scrap the game infos (description) in the language you select in Playnite itself?
I don't know how the scrap service is working, but it would be nice if we could choos in wich language we want to scrap :)
It would be also nice if we could select one or may be two screenshots we can drop in the description, there are screenshots on IGDB.com. So maybe we could get an option to choose some of these.

**Comment by L1cardo** [comment]
IGDB database is an English database , so I think it's hard to scrap the game infos (description) in the language you select.
Anyway , it would be nice !

**Comment by Lithium1988** [comment]
Yea your right, but the games we can import from steam aren't ;) 
so that would be a step to that enchantment

**Comment by JosefNemec** [comment]
Yeah the store API for steam uses geo ip and localize the results for some reason, I may need to force to English for consistency.

I'll leave this open for the screenshots idea.

**Comment by JosefNemec** [comment]
Will be covered by #242 and #358
