### ISSUE TITLE
Playnite not displaying platform icon as assigned in the library manager

### ISSUE THREAD

**Issue by woutercools** [JosefNemec/Playnite#3644]
### Bug Description

I assigned an icon to the DOS platform in the library manager, yet it isn't displayed.

### Diagnostics ID

571ebd35-39dc-4de1-9cee-05d5445672c9

### Screenshots

![2024-01-02 23_46_19-Playnite](https://github.com/JosefNemec/Playnite/assets/16439116/ac9b8fb7-3502-4e5b-89b2-e9c53c496af1)

**Comment by Jeshibu** [comment]
What about your `main menu > Settings > Appearance > Advanced > Missing game icon source` setting?

**Comment by woutercools** [comment]
> What about your `main menu > Settings > Appearance > Advanced > Missing game icon source` setting?

Yes, that does it!

But now all the other missing icons take the platform icon too and I don't want that.
I want the library games to have the library icon and the non-library games to have the platform icon.

**Comment by Jeshibu** [comment]
Not possible right now.
