### ISSUE TITLE
1020-1032 .net runtime

### ISSUE THREAD

**Issue by Misauzer** [JosefNemec/Playnite#3645]
### Bug Description

应用程序: Playnite.DesktopApp.exe
Framework ver: v4.0.30319
Description: The process was terminated due to an unhandled exception
异常信息: System.TypeLoadException
   在 System.Windows.Automation.Peers.AutomationPeer.Initialize()
   在 System.Windows.Automation.Peers.AutomationPeer..cctor()

异常信息: System.TypeInitializationException
   在 System.Windows.Automation.Peers.UIElementAutomationPeer..ctor(System.Windows.UIElement)
   在 Playnite.Controls.WindowBase..ctor()
   在 Playnite.DesktopApp.Windows.CrashHandlerWindow..ctor()

### To Reproduce

Flashback after startup

### Diagnostics ID

0

**Comment by JosefNemec** [comment]
There's literately no useful information in your bug report, no info about what is happening or when. No diag. ID either. Closing

**Comment by JosefNemec** [comment]
Also that tiny bit of stack trace says that it's failing in .NET itself. So either broken .NET Framework installation or broken system.
