### ISSUE TITLE
Return Import Steam Categorires

### ISSUE THREAD

**Issue by Herofthyme** [JosefNemec/Playnite#3648]
### Feature description

The biggest reason I downloaded playnite is because I am very OCD about how my steam library is downloaded, and playnite was the easiest way to download steam games with categories imported so that I could easily add other game libraries to my organization system. However, this feature being removed made playnite completely useless for me. Is there any way this feature can be re-added?

**Comment by JosefNemec** [comment]
1) This is handled by Steam plugin, not by Playnite, so wrong repository
2) It was not working properly anymore after Steam UI redesign and there's currently no reliable way how to get that info as far as we know

**Comment by SgtSweetieBelle** [comment]
hi there! has there been any update to this functionality?
