### ISSUE TITLE
Corrupted Library 

### ISSUE THREAD

**Issue by DeliriumBlades** [JosefNemec/Playnite#3649]
### Bug Description

I have a corrupted library that leads to a force close of Playnite with a message saying to post here for a fix
[library.zip](https://github.com/JosefNemec/Playnite/files/13853645/library.zip)

### To Reproduce

when starting playnite it does a library check then crashes with a message to post here

### Diagnostics ID

212a6541-3dfa-4a91-b733-04a50d61a74a

### Screenshots

<img width="457" alt="Screenshot 2024-01-07 082846" src="https://github.com/JosefNemec/Playnite/assets/155894601/627e70b7-bd9b-4bda-b6c7-077edd6a122a">

**Comment by DeliriumBlades** [comment]
<img width="182" alt="Screenshot 2024-01-07 085154" src="https://github.com/JosefNemec/Playnite/assets/155894601/d80963d1-f670-4b40-9c68-7c198113df30">
<img width="470" alt="Screenshot 2024-01-07 085214" src="https://github.com/JosefNemec/Playnite/assets/155894601/28ce876f-47a3-4483-a009-9614e452145e">

**Comment by DeliriumBlades** [comment]
Appears 3 games in steam library cause the Crash.. The Witcher 3, Martha is Dead and Metal Gear Solid V:The Phantom Pain

**Comment by JosefNemec** [comment]
Fixed file: [games.zip](https://github.com/JosefNemec/Playnite/files/13857658/games.zip)
