### ISSUE TITLE
use igdb game id to refresh metadata instead of game title

### ISSUE THREAD

**Issue by KrivenRaven** [JosefNemec/Playnite#3652]
### Feature description

I performed a refresh of the metadata in my library recently to correct some issues and discovered that Playnite had downloaded the incorrect metadata when there were title collisions (Sonic the Hedgehog genesis vs game gear). Can you make it so that playnite remembers the IGDB id after downloaded metadata and defaults to that instead of game title when attempting to refresh metadata?

**Comment by JosefNemec** [comment]
This is up to IGDB plugin to handle, not specific to Playnite.
