### ISSUE TITLE
Linux/bsd/arch support?

### ISSUE THREAD

**Issue by TroubledThinker** [JosefNemec/Playnite#3653]
### Feature description

I was looking to thais as a solution to my game library but I found that this unfortunately is not available for linux distributions. If at all possible, I would like to request such versions as I know a large linux community would love to use your software over other options. As far as compatibility is concerned I would suggest a .Deb format, a snap package, and a flatpak option. Thank you so much for your time and I hope you have a wonderful new year!

**Comment by JosefNemec** [comment]
#59
