### ISSUE TITLE
Fullscreen controls broken

### ISSUE THREAD

**Issue by DoganM95** [JosefNemec/Playnite#3656]
### Bug Description

Just updated playnite after a while and fullscreen controls don't work as intended, e.g.:

- Going to the menu button and pressing it picks a random game, instead of opening the menu
- Filter does not open anymore when pressing R3

Tested this with ReskinPS5 and Default theme, persists in both so not a theme fault i guess.

### Diagnostics ID

Fullscreen app, only used with controller. no diag possible

**Comment by JosefNemec** [comment]
Latest version switched to SDL for controller input handling. Your controller either has wrong game controller mapping in SDL database or you have some 3rd party input handling app/wrapper running that's breaking it:

https://api.playnite.link/docs/manual/gettingStarted/playniteFullscreenMode.html#controller-support

**Comment by DoganM95** [comment]
I think i found the issue. An update of DS4W unchecked the "disable virtual controller" in my default profile, causing my dualshock 4 to be recognized as 2 cntrollers simultaneously, one dualshock 4 and one xbox 360 controller. This caused double input as well as wrong mappings.

To resolve this, i rechecked the disable virtual controller in the profile settings, as well as setting the controller type to dualshock 4 again. Also (if necessary) i checked the disable dualshock 4 in the main settings of DS4W, which however probably hat no effect. Hope this helps anyone having the same issue.

Playnite works fine now and was not the cause of this, so this issue can be closed. Thanks for your support!
