### ISSUE TITLE
Battery indicator gets disabled after restarting Lenovo Legion Go

### ISSUE THREAD

**Issue by LordAlucardXi** [JosefNemec/Playnite#3657]
### Bug Description

Every time my Lenovo Legion Go reboots, the battery indicator option always gets disabled.

### To Reproduce

- Enabled battery indicator on Fullscreen mode.
- Restart Lenovo Legion Go.
- Battery indicator is disabled again.

### Diagnostics ID

N/A

**Comment by JosefNemec** [comment]
This means that something is preventing Playnite from saving settings on exit (during restart). Can't say more because you didn't attach diagnostics ID requested in issue template...
