### ISSUE TITLE
mes raccourcies sont effacés depuis la mise à jour...

### ISSUE THREAD

**Issue by alberic13220** [JosefNemec/Playnite#3659]
### Bug Description

bonjour, depuis la dernière mise à jour, le programme m'a supprimé 80% des raccourcis de jeux.... ils ne les reconnaient plus, même si je sélectionne manuellement. du coup playnite ne me sert plus a rien. j'ai deja tenté de désinstaller et réinstaller mais en vain. finit playnite... ps : ce n'est pas un pb de disque dur ni lettre.

### Diagnostics ID

00b09bbc-242b-4f00-ad58-a6192422f372

**Comment by JosefNemec** [comment]
English please, I don't speak this language.
