### ISSUE TITLE
Allow importing from a folder without doing a full scan first

### ISSUE THREAD

**Issue by JanPokorny** [JosefNemec/Playnite#366]
Currently, if I want to import a newly manually installed game, I have to wait through the initial scan before I can import from a folder (takes about a minute on my system, so it's slightly annoying).

![obrazek](https://user-images.githubusercontent.com/4580066/34341266-17725c1c-e994-11e7-94e3-b1b4d7a04357.png)

I propose to separate the "Import installed" and "Import from folder" in this menu: 
![obrazek](https://user-images.githubusercontent.com/4580066/34341273-555d59fa-e994-11e7-8d4e-6b22b765331a.png)

**Comment by JanPokorny** [comment]
#187 would be a nice solution, too.

**Comment by JosefNemec** [comment]
Done in 4.0
