### ISSUE TITLE
My library got corrupted, and I can't fix it on my own

### ISSUE THREAD

**Issue by Flogflogf** [JosefNemec/Playnite#3661]
### Bug Description

[library.zip](https://github.com/JosefNemec/Playnite/files/13937504/library.zip)
here is my corrupted database, please fix it

### Diagnostics ID

f698c8a0-7640-435f-9393-eb3c6aa09345

**Comment by JosefNemec** [comment]
Fixed file: [games.zip](https://github.com/JosefNemec/Playnite/files/13939302/games.zip)
