### ISSUE TITLE
Playnite crashes on first launch, then prompts to use safe mode.

### ISSUE THREAD

**Issue by Mapty231** [JosefNemec/Playnite#3665]
### Bug Description

I downloaded Playnite version 10.32.0 via Chocolatey & it immediately crashes upon first launch. Then prompts you to launch it in safe mode. It will launch if you accept or decline. Future opening of Playnite has no discernable issues.
I am running Windows 10.

### Diagnostics ID

a66a34b6-6633-4eb1-8057-9b3be157eaca

### Screenshots

[Video of error](https://github.com/JosefNemec/Playnite/assets/131195812/2ee586c7-f225-4053-892e-752ee4e4e364) (Any video editing is me removing AFK time.)

**Comment by JosefNemec** [comment]
There's no crash info in logs. Also Chocolatey is not officially supported installation method. Use official installer from the website or releases page here on GitHub.

**Comment by Mapty231** [comment]
Okay, thank you for the quick response!
