### ISSUE TITLE
Steam/GoG/Epic Verify Game Data Option

### ISSUE THREAD

**Issue by jarrard** [JosefNemec/Playnite#3667]
### Feature description

As title says, it be nice if there was a option to verify game data. 

I know this is possible as all these stores have the CLI/API to do it and have seen it done in several other launchers so it much be possible. The only exception is Steam does require their app to be open for it to work whereas the others I believe have CLI tools to do it. (I.e like Legendary used by Heroic Launcher)

**Comment by JosefNemec** [comment]
This is nothing for Playnite itself, has to be done on integration's side.
