### ISSUE TITLE
Add Profile Data for connected controller.

### ISSUE THREAD

**Issue by TrafalgarSP** [JosefNemec/Playnite#3668]
### Feature description

By adding this, you can either enable and disable what controller can use in Fullscreen Mode because some games like Yakuza only support XBOX Joystick and by opening x360ce, playnite will recognize DualShock and Xbox Joystick at the same time and will make Full Screen double click. Add profile so playnite can will detect which controller enable and disable during Full Screen Mode.

**Comment by JosefNemec** [comment]
You can already disable individual controllers in input settings.

**Comment by TrafalgarSP** [comment]
> You can already disable individual controllers in input settings.

i know that, make that like a save data so whenever you open and close playnite, the same controller keep disable.

**Comment by JosefNemec** [comment]
It is already being saved. If not then you are probably getting this issue #3660 because you are using some input wrapper.

**Comment by JosefNemec** [comment]
Fixed in 10.33
