### ISSUE TITLE
Adding Mod/DLC list

### ISSUE THREAD

**Issue by AestheticPixels** [JosefNemec/Playnite#367]
It would be useful to have a way to add DLC and Mods to lists in to your game.

Since there is no API to get those you could manually add the desired DLC or Mods to a list in your game page.

**Comment by epeternally** [comment]
I'd like this. Such information can easily be added to the main description field, but I think having a dedicated field for DLC would be helpful. Only question becomes how to format that information.

**Comment by Bluscream** [comment]
```
steam://openurl/https://store.steampowered.com/dlc/<ID>/
```

**Comment by gjgfuj** [comment]
Preferably, DLC/mods should work as proper games effectively, but as children of the existing ones. They should be able to be automatically installed/uninstalled by extensions, and have full metadata like existing games. It would be very good to be able to manage mods via playnite too (assuming extensions are built to allow for such things, e.g. integration with nexus mod manager. Steam has checkboxes for DLCs you own and presumably there's a way to access and install/uninstall them via an integration?

**Comment by JosefNemec** [comment]
Out of scope. Should be done in each library plugin on an individual level. Most client make this really hard to access so it's unlikely to happen anyways.
