### ISSUE TITLE
Corrupted Library

### ISSUE THREAD

**Issue by HacktorXP** [JosefNemec/Playnite#3671]
### Bug Description

Hi, I cannot add manually new games to the library.
Please fix the files, thx :D
[library.zip](https://github.com/JosefNemec/Playnite/files/14043113/library.zip)

### Diagnostics ID

d5b1142f-c3b7-4196-abd9-6ebd25d20f5c

**Comment by JosefNemec** [comment]
`companies.db` is broken in a state that's not fixable. You have to delete the file and let Playnite recreate it. You'll loose all information about developers and publishers, unfortunately.
