### ISSUE TITLE
Wrong game assigned

### ISSUE THREAD

**Issue by sp33dyS** [JosefNemec/Playnite#3674]
### Bug Description

Hi,
there is a game called "Beyond Blue" (https://store.epicgames.com/en-US/p/beyond-blue), but Playnite shows "Far Cry 3" under this title.
There is also another game with bug - "The Witness" (https://store.epicgames.com/en-US/p/the-witness), but Playnite metadata shows much older game with the same title - https://www.mobygames.com/game/61/the-witness/

### Diagnostics ID

ce4ca755-a9f6-4c9a-8a09-e643238c97fd

### Screenshots
"Far Cry 3" instead of "Beyond Blue"
![image](https://github.com/JosefNemec/Playnite/assets/21987201/a18f045a-d46d-4a80-b388-a9cb2a3fba2d)<br>
"The Witness"
![image](https://github.com/JosefNemec/Playnite/assets/21987201/f407ee0d-5dd0-468f-b224-a7ad97830194)

**Comment by JosefNemec** [comment]
Playnite itself doesn't assign specific metadata, this was some metadata plugin wrongly matching the game.
