### ISSUE TITLE
Playnite not detecting Baldur's Gate closing after the latest update

### ISSUE THREAD

**Issue by xCeeTee** [JosefNemec/Playnite#3675]
### Bug Description

The game still reports as running even though Steam shows it's closed. The process isn't running in the background. Not sure if this is also as intended, but my post-game scripts don't run when I manually cancel the game execution monitoring. 

### To Reproduce

I open and ghen close my game to desktop. 

### Diagnostics ID

b351897f-3492-46e7-ad16-b180db15e1ac

**Comment by JosefNemec** [comment]
Unless you import a game manually, then tracking is handled by library integration plugin that imported the game, which in your case would be Steam plugin.

Therefore this needs to be reported to its dev to fix it [there](https://github.com/JosefNemec/PlayniteExtensions).
