### ISSUE TITLE
Game install path with brackets not launching when using global scripts

### ISSUE THREAD

**Issue by codecrafting-io** [JosefNemec/Playnite#3676]
### Bug Description

If the game installation path has brackets in it, Global Scripts fails to launch the game when using any script that uses a path. This is **very strange**. For example, this `Start-Process "C:\Windows\sysnative\ie4uinit.exe" -ArgumentList "-show"` global script runs, but generates a "Global Script execution failed" only if the game's installation path has parentheses, which seems unrelated. Remove the brackets from the installation path, no errors occur.

### To Reproduce

- Create the following global script before starting the game `Start-Process "C:\Windows\sysnative\ie4uinit.exe" -ArgumentList "-show"`.
- Have a game with an installation folder with brackets ([]) in the path
- Launch the game

### Diagnostics ID

cfccf7cc-3aaf-414d-9589-21ccc2ab2f99

### Screenshots

![image](https://github.com/JosefNemec/Playnite/assets/2507127/a2699b79-8345-47dd-a938-81ee122a8f8c)

**Comment by JosefNemec** [comment]
Known issue with current scripting runtime we are using, see: https://api.playnite.link/docs/manual/features/scriptingSupport/helpAndTroubleshooting.html#exceptions-related-to-directory-not-being-found

Can't do anything about it from our side until P11 which will have different runtime.
