### ISSUE TITLE
Unable to add a game and game record not being recorded

### ISSUE THREAD

**Issue by ElieRP3121** [JosefNemec/Playnite#3678]
### Bug Description

When I try to add a game a crash appears
![image](https://github.com/JosefNemec/Playnite/assets/99256287/b879185f-6b9a-423c-8316-45b2aee5dfb8)

 and so when I play a game, the game starts but it is not being recorded.

![image](https://github.com/JosefNemec/Playnite/assets/99256287/d21feb30-58c1-4e30-bd42-bf403d1184b2)

I have the last version of Playnite 10.32

The issue starts when I put Playnite as portable, I'm gonna send all my db files from library, it should fix both problems.

[library_2.zip](https://github.com/JosefNemec/Playnite/files/14088687/library_2.zip)

### Diagnostics ID

cb1a35c4-f68b-4ad0-8c1e-0d2ad7dff5ce

**Comment by JosefNemec** [comment]
`completionstatuses.db` file is damaged beyond repair, you have to delete it and let Playnite recreate it from scratch.

**Comment by ElieRP3121** [comment]
Alright, thanks
