### ISSUE TITLE
Bulk import offline game collection

### ISSUE THREAD

**Issue by hngsggbr88** [JosefNemec/Playnite#368]
As an older gamer, I still have a lot of games on DVDs and CDs. Would it be possible to implement a function to manually bulk import titles into Playnite by e.g. using an Excel file? The Excel file would then contain the title and other neccesary information. By doing this you can avoid buying the same game twice.

As a sidenote: i really like Playnite, have been looking for an application like it for a long time and find it very easy to work with. Keep up the good work.

**Comment by JosefNemec** [comment]
I'm not sure we can do this general enough to be added as standard feature (input data can be very different depending on what user used to export). However when #414 is added you could write a simple script that would import your collection.

**Comment by JosefNemec** [comment]
Scripting support is done since 4.0. The documentation can be found [here](https://playnite.link/docs/). You should be able to import games from basically any source if you write appropriate script for it.
