### ISSUE TITLE
Games in Epic library don't run after Playnite is started via cli/task scheduler. Steam does though.

### ISSUE THREAD

**Issue by ykiran** [JosefNemec/Playnite#3680]
### **Background:**
I've a backup app that is scheduled to run at 4 AM everyday. It backups the drive Playnite is located in.
To prevent file locks/conflicts, Playnite is shutdown via cli, before the backup starts.
Later on, a scheduled task will run, which starts up Playnite.

**Kill and Start Scripts:**
Close Playnite: E:\Playnite811\Playnite.DesktopApp.exe --shutdown
Start Playnite: start E:\Playnite811\Playnite.DesktopApp.exe
The Start command is part of a batch file, which will be triggered by the Task Scheduler.
![image](https://github.com/JosefNemec/Playnite/assets/5526410/e54e18be-13df-4821-82bd-1da3a7b68dba)

Playnite starts normally, no issues.

But, when I try to launch Fortnite/RDR 2 which are in my Epic library, the Epic launcher does not run.
The launch button just stays in the "Launching" status and nothing ever happens, no matter how many times I try.

I tried to run the Playnite start command normally with the "--startdesktop" argument. Even that had the same result.

Whereas, Steam launcher would run normally and start a game.
I verified this.

Can you please help.

Playnite details:
![image](https://github.com/JosefNemec/Playnite/assets/5526410/90150e3d-7680-4e83-a3b0-d91f0d822617)

Thanks in advance.

### To Reproduce

Try starting Playnite from the Task scheduler.
After Playnite is ready, launch a game which is in your Epic library.

### Diagnostics ID

ee0c7226-f6df-4a20-9a85-662e070f6cfe

**Comment by JosefNemec** [comment]
This is all handled by Epic plugin, Playnite itself is not running the game. 

Checking from logs, `com.epicgames.launcher://apps/Fortnite?action=launch&silent=true` URI was launched. If the game doesn't start after that, it's Epic launcher issue. Epic plugin just starts that URI and what happens next is out of plugin's control.

**Comment by ykiran** [comment]
Thanks for the quick reply.
I know this issue is closed, but just want to clarify that when I close Playnite and open normally from the Taskbar or Start launcher, Epic launcher starts normally.

Thank you again.
