### ISSUE TITLE
Xenia now support Zarchive please add .zar extension to default profile for Xenia Emulator

### ISSUE THREAD

**Issue by digitalassassins** [JosefNemec/Playnite#3683]
### Feature description

Xenia now supports Zarchive please add ".zar" extension to the default profile for Xenia Emulator.

Zarchive support was added to the Carnary build in September 2023 and has just been merged into the main build in January 2024

The Xenia emulator now supports loading ISO and XEX formats directly from compressed .zar files 

https://github.com/xenia-canary/xenia-canary/pull/165

Anybody wanting to compress their games can just drag and drop the xex folder or ISO to zarchive.exe to compress the library

https://github.com/Exzap/ZArchive/releases/

This change for ZAR format has already been added to Steam ROM Manager

https://github.com/SteamGridDB/steam-rom-manager/pull/610

**Comment by JosefNemec** [comment]
Fixed in 10.33
