### ISSUE TITLE
Multiple Addon Errors

### ISSUE THREAD

**Issue by finkleroy** [JosefNemec/Playnite#3684]
### Bug Description

Everything's worked very will for months without issue, but now I'm getting errors from three different addons at the same time when launching Playnite.

The Epic addon says "Failed to import games from Epic. errors.com.epicgames.common.missing_permission". It originally told me I wasn't authenticated, so I logged back in, at which point I started receiving this error.

The GOG addon says "Failed to authenticate games from GOG. User is not logged into GOG account." When I click the authenticate button, nothing happens, so I'm unable to get to the login screen.

The PSN addon says "PSN: Authentication check failed." When I click the link to copy the value to paste into Playnite, it says "HTTP Status 429 – Too Many Requests. Type Status Report. Description The user has sent too many requests in a given amount of time ("rate limiting"). Apache Tomcat/9.0.34" This happens when I'm connected to my VPN and also when I'm not connected to it. The first time I clicked that link, it had been months since I'd last clicked it, so the error message is incorrect. This appears to be an issue on Sony's end, not Playnite's. I'm not sure if there's a way around the issue, or if I'll just have to wait until they fix it.

### Diagnostics ID

2ce86a19-c74b-4b6c-8d2c-1f16792c05b7

**Comment by JosefNemec** [comment]
This repository for Playnite only. As issue template says, issues related to specific extensions have to be reported to their devs in their repositories.

As far as GOG: https://support.gog.com/hc/en-us/articles/16623319335197-We-are-undergoing-a-planned-maintenance-services-will-be-back-at-10-PM-UTC?product=gog
