### ISSUE TITLE
No se actualizan los metadatos automáticamente solo de forma manual 

### ISSUE THREAD

**Issue by Memnoch79** [JosefNemec/Playnite#3685]
### Bug Description

Desde hace varios meses la biblioteca no actualiza sus metadatos, he desinstalado y reinstalado varias veces la app y el problema persiste, solo me deja actualizar los metadatos de los juegos, de forma manual y uno por uno. 

### Diagnostics ID

7900d4de-9fd6-416d-8b49-64c673dfec5f

**Comment by JosefNemec** [comment]
english please

**Comment by Memnoch79** [comment]
For several months the library has not updated its metadata, I have uninstalled and reinstalled the app several times and the problem persists, it only lets me update the metadata of the games, manually and one by one.

**Comment by JosefNemec** [comment]
https://api.playnite.link/docs/manual/library/games/metadata.html#updating-game-metadata
