### ISSUE TITLE
Xbox games installed on Windows no longer detected as installed

### ISSUE THREAD

**Issue by jaspotn** [JosefNemec/Playnite#3686]
### Bug Description

I am using Playnite v10.32, SDK 6.11.0 and Xbox Library Integration v2.14
This used to work fine however now, while the games are listed in the client, they only give the option to install. When this is clicked the Windows Store opens and it shows the game is installed as the only option is "Play". I can launch the game fine from the Windows menu. I have removed the add-in and reinstalled and the games disappear and reappear as they should but the only option is to install. Looking at the game details the installation location is blank.
If I try to manually add a game they do not show, and i've checked I've got "hide installed" disabled.

### Diagnostics ID

f3deaf71-315d-4308-9b1b-e403325d27e9

### Screenshots

![image](https://github.com/JosefNemec/Playnite/assets/39434813/9ca9a6b9-4b17-47d2-bc8a-53861e293836)
![image](https://github.com/JosefNemec/Playnite/assets/39434813/0afc7d17-70f5-4885-ac84-69905157f2a5)

**Comment by JosefNemec** [comment]
API for getting list of installed MS Store apps is failing on your system with generic `Element not found.` message. There was no change on our end so if you are saying that it used to work and stopped then something broken in your system, most likely. No idea what though.

**Comment by jaspotn** [comment]
I think you're correct, there was some other issues that eventually cropped up on my system that was unrelated so in the end, after many attempts at fixing, I did a system reset. I haven't yet restored Playnite, however this issue can be closed off
