### ISSUE TITLE
Game state within Playnite is stuck in "installing" status after install was cancelled.

### ISSUE THREAD

**Issue by Punctual-Donkey** [JosefNemec/Playnite#3689]
### Bug Description

Playnite 10.32 on Windows 11. In the Playnite library view, I clicked "Install" for a game. In this case, it was a game in Ubisoft Connect. Ubisoft Connect launched, and before it could install, I shut down the Ubisoft Connect app, because I changed my mind about the install.

Now Playnite still shows the game as "installing", even though it is not. There is no obvious way to reset this state. I thought perhaps I could delete the game from Playnite and re-add it to fix the issue, but Playnite doesn't allow me to remove the game from it's database - when I choose the "remove" option for the game, it gives an error "Cannot remove - game or installer is currently running". Which of course is not correct.

So Playnite's internal state is fucked because I cancelled the install outside of Playnite, and if there is some easy way to correct this, it is not obvious.

### To Reproduce

I think I provided repro steps above.

### Diagnostics ID

25ae280d-3f77-4550-9f69-38c342fcadd0

**Comment by Jeshibu** [comment]
Click the "Installing" button, and it will prompt you to revert to uninstalled status.

**Comment by Punctual-Donkey** [comment]
That easy? Ha. Thank you.
