### ISSUE TITLE
Crash when trying to open About Playnite > About Playnite

### ISSUE THREAD

**Issue by CorruptComputer** [JosefNemec/Playnite#369]
If it is any help it was also after https://github.com/JosefNemec/Playnite/issues/327 happened to me and I was trying to see what version had just installed. Also that is not fixed as I was up to date, ended up deleting and rebuilding the DB. [crash.zip](https://github.com/JosefNemec/Playnite/files/1588219/crash.zip)

**Comment by JosefNemec** [comment]
Released in 3.4
