### ISSUE TITLE
Startup Library/Emulated Folder Updates Not Occurring

### ISSUE THREAD

**Issue by SkyNinja** [JosefNemec/Playnite#3691]
### Bug Description

Recently, when booting Playnite, library updates simply do not occur. I set updates to occur on every startup as a test, but still, nothing happens. I've tried booting in safe mode, but it still does not update libraries. Manual updating is functional, however.

I am unsure of exactly when this started, but I know it's been at least the past five days, as that's when I first noticed the issue. It's possible that all startup jobs aren't happening, but I've yet to see an extension update to confirm.

### To Reproduce

Issue occurs upon launching the software.

### Diagnostics ID

72451656-1cb2-45cd-82a8-9fea3019a20f

**Comment by JosefNemec** [comment]
Updates are not occurring because Playnite is detecting no internet connection. Which is being tested by trying to reach Cloudflare's DNS server 1.1.1.1. So this is some network issue on your system/network.
