### ISSUE TITLE
Forced to turn the controller off and then on again

### ISSUE THREAD

**Issue by Julinkk** [JosefNemec/Playnite#3693]
### Bug Description

Since the last update of playnite when I launch the pcsx2 or ryujinx emulator from playnite I have to turn my controller off then on again when the game is launched so that the controller is recognized. I have no problem going directly through the emulator.

### Diagnostics ID

58c3ee04-b4f9-49e9-8b5a-73ed12136bef

**Comment by JosefNemec** [comment]
I can't see anything on our side that could cause this issue. We just pull controller state via SDL library, nothing special. So this is either some issue with SDL or those emulators.

Also I tried it with PCSX2 (Xbox Series controller) and I can't reproduce it.

**Comment by Julinkk** [comment]
it was a problem between playnite, hidhide and ds4windows, I solved the problem, thanks for the answer.
