### ISSUE TITLE
Achivements watcher

### ISSUE THREAD

**Issue by KAZUTO2025** [JosefNemec/Playnite#3698]
### Feature description

the success story generic plugin sometimes not fully work with  pairated games.so with changing crack manually to ali 312 or goldberg crack i can get notif of unlocking achievement from achievement watcher.i dont wants somthing so hard all i want is to get unlocked or locked achievements data from Achievement watcher app that installed in my pc. if you dear programmers think you can do much better why not make the full achievement tracker by combining achievement watcher app and success story. anyway thanks for your hard works.
if have any questions about not showing achievements in achievement watcher ask me i try my best to answer.
here the achivement watcher app: https://github.com/xan105/Achievement-Watcher

**Comment by JosefNemec** [comment]
We do not support pirated games.
