### ISSUE TITLE
Any way to import games from a second hard drive?

### ISSUE THREAD

**Issue by pomkos** [JosefNemec/Playnite#37]
Hey there!

Great software, it was love at first sight. Love the UI, the auto labeling and import. Speaking of import though, it looks like Playnite only recognized games that were either on my C drive or (probably) that were listed in Windows' Add/Remove Programs. Most of my games are on a second E drive, and almost all non-GOG games are not listed in the Add/Remove Programs. For example: Rimworld (steam) is on my C, by not in Add/Remove so it didn't get imported into Playnite. 

Is there something I'm missing? Or do installed games from Steam/Origin need to be added manually?

**Comment by JosefNemec** [comment]
If you installed game via official client (Steam, Origin or GOG Galaxy) and it shows as installed it that client, then it shouldn't matter on what drive it is, it should be detected and imported automatically (no matter if it is in Add/Remove programs list). If that's not the case then it's a bug.

For manually installed games, Playnite looks at Start Menu entries and Add/Remove program entries to find installed apps. So if your game doesn't show up in those, then you will have to add it manually (or use Scan Folder option).

You example with Rimworld however sound definitely like a bug. Could you please attach diagnostics package, which you can create from "About Playnite..." dialog? Thank you

**Comment by pomkos** [comment]
Ah, thanks for clear up! It must be a bug then, as so far only games in GOG (which also appear in Add/Remove) are showing up as installed.

On opening playnite I did get a notification: "object reference not set to an instant of an object".

Here's the debug:
[debug.zip](https://github.com/JosefNemec/Playnite/files/1015068/debug.zip)

**Comment by JosefNemec** [comment]
Thank's for additional debug info, fix will be released in next version.

**Comment by JosefNemec** [comment]
Released in 0.90
