### ISSUE TITLE
Automatic input focus

### ISSUE THREAD

**Issue by Damntry** [JosefNemec/Playnite#3701]
### Feature description

This is more of a discussion about a possible feature request.

To put things in perspective, I have a category that I use as a wishlist of games I want in the future, which means I regularly add games to it.
When adding a new game manually and after opening the window to download metadata, the focus is on the window itself. This means you have to tab a few times to reach the search box, select the "New game" text, and then you can start typing to search. Its worse for users that dont know you can tab to change focus.

![SearchFocus](https://github.com/JosefNemec/Playnite/assets/25682817/766895ec-9a62-4961-8ed0-36f18de76afa)

It would be helpful for the cursor to automatically focus on the search input box, with the "new game" text selected, so you can start typing right away. But ideally this would only happen if you havent touched the "New game" text in the game details, otherwise its understood that its an edit of an existing entry, or that the user wrote something in it already, in which case preselecting the first entry might be more useful¿?

The problem with this is that it would make the focus behave differently depending on input, which tends to be avoided.

Thoughs?

**Comment by Jeshibu** [comment]
I'm definitely in favor of focusing the text field by default - you can shift-tab to the results view, and it's still better than focusing the window.

**Comment by JosefNemec** [comment]
Fixed in 10.33
