### ISSUE TITLE
Play time is tracked when system is hibernated

### ISSUE THREAD

**Issue by xdpirate** [JosefNemec/Playnite#3702]
### Bug Description

Playnite will erroneously count time in hibernation as playing time, presumably because it counts by start and end timestamps for process start and exit, without accounting for time when the system is hibernated. 

Observed on ASUS ROG Ally (Windows 11 Home, x64). I played a game for about 5 hours, put the system into hibernation, returned about 18 hours later, exited the game and the timer read 23 hours. The timer now sits at 51 hours played, although the actual play time is about 15 hours across several sessions.

### To Reproduce

1. Launch a game
2. Hibernate the system
3. Wait an arbitrary amount of time
4. Wake system from hibernation
5. Quit game
6. Observe that time spent in hibernation is added to play time

### Diagnostics ID

41594f70-e239-4e0e-bccc-2e536886e793

**Comment by JosefNemec** [comment]
#1389
