### ISSUE TITLE
Add Sega - Mega Drive as a Default Profile in Ares

### ISSUE THREAD

**Issue by jasonfails** [JosefNemec/Playnite#3707]
### Feature description

For whatever reason the Mega Drive core from Ares isn't a default profile in Playnite. The arguments to make it work are identical as any other profile for the emulator meaning all you need is "--system "Mega Drive" "{ImagePath}" --fullscreen" to get it running with supported file types being "zip,md" I'm sure it would be appreciated by others if this was added to the defaults list.

**Comment by JosefNemec** [comment]
Fixed in 10.33
