### ISSUE TITLE
"Select Games to Import" GUI ignores already imported games, but the select all checkbox still imports everything

### ISSUE THREAD

**Issue by t3hsuppli3r** [JosefNemec/Playnite#3708]
### Bug Description and Reproduction 

"Playnite > Add Game > Scan Automatically" and then select a folder.
It will iterate over this folder and show you only the games that are not already present on the Playnite library (from the same folder) *

* This is with the [*] Hide imported feature enabled

However, if you press the Select All checkbox at the upper left part, it will still add all games (creating duplicate names) inside your library.

I suspect that the "Select Games to Import" GUI use something like a HashSet that ignores any duplicates, but the good old "Select All" check box gets the original list before removing the duplicates (the games that are already imported).

### Diagnostics ID

82ffe61f-bedf-4d00-91c4-761aae9bde71

### Screenshots

Those are the already imported games
![image](https://github.com/JosefNemec/Playnite/assets/161611271/72209ac7-d656-425d-98ad-dc2be3defdc3)
Then i scan the same folder, that also contains three more games (having the Hide Imported feature enabled)
![image](https://github.com/JosefNemec/Playnite/assets/161611271/6e15d3b2-67a1-4fc3-82c6-6edf7784ff23)
And now if i press the Select All checkbox
![image](https://github.com/JosefNemec/Playnite/assets/161611271/e12e3706-5bfa-4c0b-8d8e-1043b37a5437)
Instead of those new three games i will get all 7 games from this folder
After metadata scan i have two versions of the old (already imported from before) games
![image](https://github.com/JosefNemec/Playnite/assets/161611271/945c8336-9c39-404c-bd2d-9c702be9b943)

**Comment by JosefNemec** [comment]
Fixed in 10.33
