### ISSUE TITLE
Switching Target display leaves Settings overlay on previous monitor

### ISSUE THREAD

**Issue by Gammler** [JosefNemec/Playnite#3709]
### Bug Description

Hi,

if you switch the target display in fullscreen mode it leaves the settings overlay on the previous monitor until you completely close the overlay.

To be honest i'm quite disappointed that these easy to reproduce bugs still happen. It was the reason i didn't use playnite anymore for quite some time now and those things still occur and are not like hard to reproduce. It took me like one minute to remind me why i stopped using it.

### To Reproduce

change taget display in fullscreen mode

### Diagnostics ID

715cb2c1-6159-47c6-9888-da7880d1c24e

### Screenshots

![playnite_target_display_bug](https://github.com/JosefNemec/Playnite/assets/7454243/d7441e1e-5321-43cd-9983-46b16d29ad12)

**Comment by JosefNemec** [comment]
This is intentional behavior in case you change to incorrect display, we make sure that the settings view stays "visible" until you confirm by exiting settings.

**Comment by Gammler** [comment]
To be honest, that makes no sense if it doesn't tell you that since i had no itention to close the settings because i was not finished. Also it is not confirming by closing the overlay once, this behaviour forces you to also close the underlaying menu.
Not intuitive.
