### ISSUE TITLE
Sorting by name, games starting with article (the, a, an)

### ISSUE THREAD

**Issue by Ianuarius** [JosefNemec/Playnite#371]
Please use search first to see if the issue is already opened. Thank you
Steam ignores an article (the, a, an) in front of the game name when sorting by name and I wish Playnite did it the same way. To me, it's harder to remember which games start with "The" and then finding them can be a hassle. Maybe an option for this?

**Comment by JosefNemec** [comment]
Duplicate to #154

Btw the text `Please use search first to see if the issue is already opened. Thank you` you left in your issue text is there for a reason :)

**Comment by JosefNemec** [comment]
Also forgot to mention that since #84 you can set custom sorting name that will ignore "the" and other strings. However I understand that Playinte doing that automatically would be better.
