### ISSUE TITLE
Folder Problem.

### ISSUE THREAD

**Issue by zzh2270** [JosefNemec/Playnite#3711]
### Bug Description

I just need to add a game in the software, scan or browse the folder,  and the software will report an error in the end.

### To Reproduce

 I just need to add a game in the software, scan or browse the folder,and the software will report an error in the end. I think about it carefully, and I don't have any other operations before that.It also have problem when modifying the picture cover.In short there will be problems as long as I want to open the folder.

### Diagnostics ID

2b161b1f-1d00-4832-94fb-b73f4cc66acf

### Screenshots

<img width="1280" alt="屏幕截图 2024-03-20 135609" src="https://github.com/JosefNemec/Playnite/assets/159754732/c8f788b3-78a8-49d5-9d28-dc328aa33ef3">
<img width="1280" alt="屏幕截图 2024-03-20 135616" src="https://github.com/JosefNemec/Playnite/assets/159754732/3caecf37-08ef-4103-a37a-e003a74b8e60">

**Comment by zzh2270** [comment]
My tone may not be polite enough.Please forgive me,my English is rusty.

**Comment by JosefNemec** [comment]
Crashes because of some missing system COM component:

>System.Runtime.InteropServices.COMException (0x80040111): 从 IClassFactory 为 CLSID 为 {DC1C5A9C-E88A-4DDE-A5A1-60F82A20AEF7} 的 COM 组件创建实例失败，原因是出现以下错误: 80040111 ClassFactory 无法供应请求的类 (异常来自 HRESULT:0x80040111 (CLASS_E_CLASSNOTAVAILABLE))。

Some googling says that it's either caused by high contrast mode begin turned on (apparently it's a Win API bug introduced some time ago) or broken system installation.

**Comment by zzh2270** [comment]
Thank you very much!

**Comment by zzh2270** [comment]
Some of the missing system COM components were originally caused by compatibility adjustments I made before, resulting in their incompatibility. Now it has run perfectly. I apologize for my carelessness
<img width="386" alt="屏幕截图 2024-03-22 151512" src="https://github.com/JosefNemec/Playnite/assets/159754732/69053571-4826-46d0-a262-1dd487f632bc">
