### ISSUE TITLE
A variety of weird problems.

### ISSUE THREAD

**Issue by wensleyoliv** [JosefNemec/Playnite#3712]
### Bug Description

I used Playnite for months, suddenly it started to have a lot of weird problems, when i open a game and i close it, if i open playnite the window it gets bugged like in the screenshot below, also sometimes when this happens my computer get slow and if i look at task manager the usage of ram is at 99% if i force close playnite on task manager everything gets normal. Most importantly the software is so hard to open now, it opens and crashes without any dialog, sometimes after a few tries it opens. I already deleted everything and tried a reinstall i don't understand what is happening. If i need to upload any other file please tell me.

### To Reproduce

Try to open the software it will crash without any dialog, if it opens try to open a game then close the game and open the program it will be just like the screenshot.

### Diagnostics ID

98b4963d-e776-4866-9cf4-58a7c2142477

### Screenshots

![after game](https://github.com/JosefNemec/Playnite/assets/14226926/560115a0-bbfc-4904-b777-6ab862919567)

https://github.com/JosefNemec/Playnite/assets/14226926/6301dacc-12be-4631-9656-90af561fd583

**Comment by JosefNemec** [comment]
Try it in safe mode (main menu -> help -> restart in safe mode). There was no update to Playnite for some time now, so if you are saying that it started happening out of nowhere, something else must have changed on your system. Either some extension/theme in Playnite or app/driver on your system.

**Comment by wensleyoliv** [comment]
It opens in safe mode, but in the same way it does open normally sometimes too, but with the weird interface bugs in the screenshot after playing any game. is there some way to see what is causing the crashes?

**Comment by JosefNemec** [comment]
There are no crashes in the logs from diag package you attached so it's a crash most likely caused by issue with the system or 3rd party app/driver.

**Comment by wensleyoliv** [comment]
Thank you i found the problem, the crash is caused by Howlongtobeat extension, and the interface bug is caused by Special K Helper.
