### ISSUE TITLE
Import "Community Rating Count" from LaunchBox Database

### ISSUE THREAD

**Issue by MotherSoraka** [JosefNemec/Playnite#3714]
### Feature description

Currently Playnite doesn't seem to have any attribute/fields for games to hold and display "Community Rating Count"
 (Number of users who've rated a game).

That would be a very useful when filtering or sorting games based on User Rating. 
 (By filtering out very low user counts)

**Comment by JosefNemec** [comment]
This repository is for built-in Playnite features only. If you to pull specific data from LaunchBox database, ask developer of LaunchBox plugin.

**Comment by Jeshibu** [comment]
Yes, but such a field would need to be created to hold this data. Custom fields are planned for Playnite 11, until then I can't see a field that would usefully hold this data.
