### ISSUE TITLE
Fullscreen mode waking screen every few seconds

### ISSUE THREAD

**Issue by zomgugoff** [JosefNemec/Playnite#3715]
### Bug Description

Turning the screen off in Windows while in fullscreen mode results in the screen waking after 3-5 seconds. This does not occur in desktop mode. I have tried adding an override with powercfg for the sound driver and Playnite application, but it did not change the behavior.

### To Reproduce

Set screen to turn off (Control Panel ->Power Options -> Choose what the power buttons do -> Turn off the display)
While in fullscreen mode, press the power button

### Diagnostics ID

d158ea30-2d55-485d-a0b6-11ee8dd6e2f6

**Comment by JosefNemec** [comment]
#2932
