### ISSUE TITLE
Missing tooltip when hovering mouse over Playnite icon in the Windows Notification Area (System Tray)

### ISSUE THREAD

**Issue by gselis** [JosefNemec/Playnite#3718]
### Bug Description

When hovering the mouse pointer over the Playnite icon in the Windows notification area, a blank (or no) tooltip is displayed. Instead, the tooltip should display the application's name ("Playnite").

Background: most applications display the name of the application in their tooltip when hovering the mouse pointer over their icon in the notification area. Some applications may also display a short status or other detail that may be helpful to the user, but this is less common.

### To Reproduce

Environment details:

Playnite version: 10.32
Windows edition: Windows 11 Pro, version 23H2, OS Build 22631.3374

Steps to reproduce:

1. Start Playnite.
2. In Settings > General, make sure that "Show system tray icon" is checked. Restart Playnite if prompted to do so.
3. Hover over the Playnite icon in the notification area. 
4. Note that no tooltip, or an empty tooltip, is displayed.

### Diagnostics ID

N/A

**Comment by JosefNemec** [comment]
This is intentional because tray icon component we are using has buggy tooltip and it would occasionally get stuck on the screen without a way to get rid of it.
