### ISSUE TITLE
Less clicks

### ISSUE THREAD

**Issue by ghostwheel** [JosefNemec/Playnite#372]
Hi, great project!

Maybe this is already possible with a skin/theme.
I'd really like to be able to do things with less clicks. I'd like to be able to launch a game with just one click, and I'd like to be able to see game manual and others with just two - and just left button.
I'm using it on a GPD win, and doing things just by using the touchscreen is nice.
I'm not sure how one button launch would work. Maybe another cover mode where a click launches?
I would also like to have buttons to actions on the game page, instead of just in the menu. Especially the "Manual" button. It is nice, because it also tells you if a Manual is available without having to check the menu. I guess there's a problem with how Manuals are currently handled - as actions (which I guess also makes it hard to translate the button to different locales).
Is it possible to do these with skins?

**Comment by JosefNemec** [comment]
Please open `manual` stuff as separate issue, I think ti's a good idea to have manuals as separate game property rather then having it as "Action", as you propose. That would allow us to integrate it into UI better.

As for other stuff, almost all can be done via custom theme. For example adding "Play" button to all lists to be able to launch game without opening its details. I'll do pass on default themes to see where we can optimize things to require less clicks. However in general it would make a sense to create separate theme fully optimized for devices like GPD win or touch based devices. I think a lot of that will be achieved via fullscreen mode and fullscreen themes (#56), which in general will not rely on mouse but other modes of input.

**Comment by Ianuarius** [comment]
Speaking of less clicks, changing a game cover takes 7 clicks and I have to do this a lot. I'd suggest that the "Covers" view had a RMB menu item "Change Cover Image" that immediately just opens the browse dialogue. This could probably be done with custom themes, but I think it'd just be nice default functionality.

Similarly, the "List" view could have a RMB menu item "Change Icon".

**Comment by rix1337** [comment]
+1, just start a game on clicking the cover anywhere... maybe move the Info button to the top right?

**Comment by trick72** [comment]
+1 for me too. It would be great if I could use Playnite on my Touchscreen game console. So i ONLY have the touchscreen to interact. So it would be great to "swipe" through the game list and launch a game by simple 1-click on the game cover.

**Comment by JosefNemec** [comment]
There has been a lot changes to UX related to this since this issue was created. I'm closing this for now. If there are other/unsolved issues present, open new issue please.
