### ISSUE TITLE
Smooth Scrolling by clicking the mouse wheel (different from the present smooth scrolling implementation)

### ISSUE THREAD

**Issue by AndreF111** [JosefNemec/Playnite#3720]
### Feature description

I would like to request the addition of a type of smooth scrolling which is completely different from the smooth scroll feature presently implemented.

In all browsers and many apps, such as GOG Galaxy and Steam, if you click on the middle mouse button, the pointer is replaced with an elevator icon, and moving the mouse up or down will make the page scroll automatically in that direction, with the speed being directly proportional to how far the mouse has been moved from the starting point. This type of scrolling is extremely pleasant to use, as it allows for completely automatic scrolling at a constant speed. It's perfect for leisurely browsing the game collection, appreciating the artwork.

Please consider implementing this type of scrolling in Playnite, as it is the only feature from GOG Galaxy or Steam which I miss.

This feature request is related to #2743

**Comment by JosefNemec** [comment]
Why did you open duplicate issue if you already knew this is already requested in #2743?

**Comment by AndreF111** [comment]
I don't usually use this platform, so I'm sorry if I did something wrong.
