### ISSUE TITLE
Overlay to close the currently game and open the game library

### ISSUE THREAD

**Issue by rybandz** [JosefNemec/Playnite#3721]
### Feature description

Currently I use the OGL through game bar widget, but I think that be nice open a overlay to the playnite library through the main button of the gamepad or create a widget to him in the gamebar
![imagem_2024-03-30_204901524](https://github.com/JosefNemec/Playnite/assets/165525397/f03fa546-be5e-4d72-8b5b-f9d1a2969303)

I believe that opening the game library using the button and being able to close any game with an overlay would be very useful to who can likes to play using only the gamepad

**Comment by JosefNemec** [comment]
#1390
