### ISSUE TITLE
Add support for the suyu emulator

### ISSUE THREAD

**Issue by cromefire** [JosefNemec/Playnite#3723]
### Feature description

Basically [Suyu](https://suyu.dev/) is resuming development on yuzu (in a more sterile environment...) and should work basically the same except for some renaming. If you try to add it as yuzu, it won't find the launch binary.

### Screenshots

<details>

![image](https://github.com/JosefNemec/Playnite/assets/26320625/36314fe9-6aa3-4471-9513-4d9f46dbbf85)
![image](https://github.com/JosefNemec/Playnite/assets/26320625/b7d2c889-d80d-4c4a-8ee7-a4861c19c029)

</details>

**Comment by JosefNemec** [comment]
You can make custom profile for emulators that don't have built-in support, including Suyu. I'll probably wait a bit before adding built-in support for it given its history.

**Comment by cromefire** [comment]
Understandable. But now there's at least an issue to keep track of it

**Comment by DmitriyPekar** [comment]
https://github.com/sudachi-emu/sudachi

**Comment by JosefNemec** [comment]
Closing. You can configure it manually: https://api.playnite.link/docs/manual/features/emulationSupport/addingNewEmulators.html

It's unlikely we are going to add built-in support due to the entire shit show around Yuzu forks.

**Comment by cromefire** [comment]
Yeah that got far more convoluted than expected...
