### ISSUE TITLE
Updating OBS Studio conflicts with Playnite running

### ISSUE THREAD

**Issue by lightningHoneypot** [JosefNemec/Playnite#3727]
### Bug Description

If one to have Playnite running in the background, it conflicts with OBS Studio trying to update itself.

### To Reproduce

1. Have Playnite running in the background
2. Try to update OBS Studio

The only way to get around this bug is to close Playnite first, then continue with the update. This also affects the `winget` command too.
### Diagnostics ID

f4efbbfb-2a9a-4a7c-8a9d-7ee7203499cf

### Screenshots

![image](https://github.com/JosefNemec/Playnite/assets/88814097/4470796d-6db6-4fd5-b24c-3af244521b40)

**Comment by lightningHoneypot** [comment]
Huh, there is an issue reported in the obs-studio repository:

[Installer is blocked by Playnite processes (CefSharp.BrowserSubprocess) #8883](https://github.com/obsproject/obs-studio/issues/8883)

I guess it is up to you guys if you want to fix it.

**Comment by JosefNemec** [comment]
We are not locking other apps files and we have virtually no control over what CefSharp does under the hood. So this is CefSharp issue touching other apps files (no idea what that would happen, there's no good reason for it) or NSIS issue wrongly detecting that the files are locked by CefSharp process. Either way, not an issue on our side as far as I can tell.

This was actually reported in the past with another app also using NSIS if I remember correctly. I did some digging back then and I couldn't find anything on our side that could be causing this.

**Comment by JosefNemec** [comment]
Forgot to mentioned 3rd possible culprit and that's some plugin causing this by using web view in a weird way (no idea what that would be). You can test it by running Playnite in safe mode (from help menu).

**Comment by Jeshibu** [comment]
I updated OBS with no issue this weekend and I'm pretty sure I had Playnite running. This might be a plugin issue, or at least not something universal.
