### ISSUE TITLE
Playnite Crashes at Startup on Windows 11

### ISSUE THREAD

**Issue by Socxenophone** [JosefNemec/Playnite#3729]
### Bug Description

After upgrading from Windows 10 to Windows 11, Playnite (versions 9 and 10) fails to start up, rendering it entirely unusable. 

No antivirus software, apart from Windows Defender, is installed, and Defender is turned off. Also, when attempting to launch Playnite, a "Startup Error" window appears, stating "Playnite closed unexpectedly while starting," with only the options to start with 3rd party extensions disabled. Clicking either "Yes" or "No" does not initiate any action. Even running safemode.bat does not resolve the issue. Pls help :( 

The log :

```
07-04 18:39:08.784 INFO (ProgramEntry App arguments:
07-04 18:39:10.067 ERROR PlayniteApplication:Failed to start pipe service.
System ArgumentNullExceptior: Value cannot be null.
Parameter name: uriString
at System.Uri.ctor(String uriString)
at Playnite. PipeServer StartServer(IPipeService service) in C:\projects\playnite\source\Playnite/PipeServer.cs:line 82
at Playnite PlayniteApplication.ctor(Func'1 appinitializer, ApplicationMode mode, CmdLineOptions cmdLine) in C:\projects\/playnite\source\Playnite\App PlayniteApplication.cs:line

07-04 18:39:10.283/WARN |PlayniteSettings:No existing settings found.

07-04 18:39:10.283 WARN |PlayniteSettings:No settings backup found, creating default ones.

08-04 19:59:48.208 INFO |ProgramEntry:App arguments:
08-04 20:00:03.363 ERROR PlayniteApplication:Failed to start pipe service.
System ArgumentNullException: Value cannot be null.
Parameter name: uriString
at System.Uri..ctor(String uriString)
at Playnite PipeServer.StartServer(IPipeService service) in C:\projects\playnite\source\Playnite PipeServer.cs:line 82
at Playnite PlayniteApplication.ctor(Func'1 appInitializer, ApplicationMode mode, CmdLineOptions cmdLine) in C:\projects\playnite\source\Playnite App PlayniteApplication.cs:ling

08-04 20:00:03.504 WARN [PlayniteSettings.No existing settings found.

08-04 20:00:03.504 WARN |PlayniteSettings:No settings backup found, creating default ones
```

### To Reproduce

- Upon attempting to launch Playnite, it crashes immediately. (Version 9 or 10)

### Diagnostics ID

Unable to Generate ID without accessing Playnite

**Comment by JosefNemec** [comment]
This looks like broken installation, try reinstalling or using fresh portable install.

**Comment by Socxenophone** [comment]
Hi @JosefNemec thanks for replying, I appreciate it :)

> This looks like broken installation, try reinstalling or using fresh portable install.

Unfortunately, I have already attempted to reinstall Playnite three times, as well as trying the latest portable install, but unfortunately, the issue persists.

**Comment by JosefNemec** [comment]
Please attach `Common.config` from an installation that's failing to start.

**Comment by Socxenophone** [comment]
```
<appSettings>

<add key="UpdateUrl" value="https://www.playnite.link/update/" />

<add key="UpdateUrl2" value="https://api.playnite.link/update/" />

<add key="ServicesUrl" value="https://api.playnite.link/api"/>

<add key="UpdateBranch" value="stable" />

<add key="ThrowAllErrors" value="False" />

<add key="OfflineMode" value="False" />

<add key="PipeEndpoint" value="net.pipe://localhost/PlaynitePipe" />

<add key="AppBranch" value="master" />

</appSettings>
```

**Comment by JosefNemec** [comment]
That looks file, please upload the entire Playnite for me.

**Comment by Socxenophone** [comment]
Apologies @JosefNemec, I'm not very good at english, do you mean the entire Playnite folder? Or all the files from AppData\Local\Playnite : https://send.cm/d/12Ywo
(Unable to upload to github due to size limit)

**Comment by JosefNemec** [comment]
Thanks. Those files look ok and I can't replicate it (Playnite starts properly for me using those files). Probably some system issue, not much I can do about it I'm afraid and I have no idea what could be causing it.

**Comment by JosefNemec** [comment]
Btw is it normal Windows 11 install or one of those "lightweight" ones like Atlas or Tiny?

**Comment by Socxenophone** [comment]
> Btw is it normal Windows 11 install or one of those "lightweight" ones like Atlas or Tiny?

No, It's Win11 Pro, version 21H2 :/

> Probably some system issue, not much I can do about it I'm afraid and I have no idea what could be causing it.

Yeah, gotta live with it ig? The issue seems to affect Playnite only for me, Heroic runs fine but it's far behind Playnite and pretty mid. 
 
Running `DISM /Online /Cleanup-Image /RestoreHealth ` or `sfc /scannow` doesn't return any issues, and I'm no windows expert either. Doing a clean installation seems a bit of a stretch. 

Thanks for trying ig. Have a good day.

**Comment by JosefNemec** [comment]
The log you attached would point to something being messed up with Playnite files. That one error from the log you attach means that `PipeEndpoint` value is missing from common.config file, which is not the case based on files you attached, so it makes no sense to me. Looks like something is maybe preventing Playnite from reading its files properly. Try installing Playnite into different location maybe.
