### ISSUE TITLE
Playnite Crashing When Viewing Youtube Videos

### ISSUE THREAD

**Issue by BiggSlime** [JosefNemec/Playnite#3730]
### Bug Description

I have came across a bug when where searching youtube videos through the extra metadata loader add-on will crash playnite to desktop. I have brought up this issue to the creator of the add-on but redirected me to Playnite git hub to bring attention to the bug. 

Here is a link to the mentioned Extra metadata loader thread: https://github.com/darklinkpower/PlayniteExtensionsCollection/issues/524#event-12414044949

Here are videos of the issue I am experiencing: https://www.youtube.com/watch?v=zDQ0swbJZ9Q ,  https://youtu.be/gA1gailXYdY

The Owner of the add-on mentioned to copy and paste this when creating this new bug report: 
`[using]() (var webView = PlayniteApi.WebViews.CreateView(1280, 750))
{
    webView.Navigate("https://www.youtube.com/watch?v=dx-oLsap7P0");
    webView.OpenDialog();
}`

### Diagnostics ID

ba0b8df8-d9a3-446d-bc10-c4ad25cd037d

**Comment by JosefNemec** [comment]
I'll update web view component in next update but that's pretty much all I can do. It doesn't crash in our code according to logs.

**Comment by JosefNemec** [comment]
Web view was updated in 10.33. If the issue still persists, then it will need to be fixed in CefSharp.

**Comment by darklinkpower** [comment]
Can confirm it's fixed on the latest update with the CefSharp upgrade. Just for reference, it looks like it was this issue: https://github.com/chromiumembedded/cef/issues/3643
