### ISSUE TITLE
Library Corruption

### ISSUE THREAD

**Issue by flazzarin** [JosefNemec/Playnite#3732]
### Bug Description

When trying to save new metadata to a recently imported title a dialog appears saying my library data is corrupted and to seek help here.
"Library file corruption has been detected, Playnite will now shutdown.
Open new issue..."

### To Reproduce

Simply edit metadata on a title, download from any source, click save, then the error pops up.

### Diagnostics ID

ff9a223a-4247-4eef-9cfa-31f744447686

**Comment by JosefNemec** [comment]
Go to `%AppData%\Playnite\library` folder (put it into file explorer exactly as is) and upload .db files you see there.

**Comment by flazzarin** [comment]
[library.zip](https://github.com/JosefNemec/Playnite/files/14968979/library.zip)

**Comment by JosefNemec** [comment]
Unfortunately `companies.db` file is corrupted in unrecoverable way (at least not without major effort). You will need to delete the file and let Playnite recreate it.

**Comment by flazzarin** [comment]
Ok, thanks for trying to fix it! Sorry for my noob question, but do you mean I should delete `companies.db` or all the .db files?
Because I tried deleting only that file and Playnite did not recreate it automatically.

**Comment by JosefNemec** [comment]
Only that one file.
