### ISSUE TITLE
Support importing games that are shared through the new Steam Families feature

### ISSUE THREAD

**Issue by mmlac** [JosefNemec/Playnite#3733]
### Feature description

Steam has a new library sharing feature, [Steam Families](https://help.steampowered.com/en/faqs/view/054C-3167-DD7F-49D4). Currently those games shared don't seem to be imported through the Steam library integration.

This is in the beta stage, so I don't know if this is even exposed in any APIs yet. I think this should be something to keep track.
Additionally, thinking about how these could be tracked in the library, so one can easily search for or exclude games from the shared library.

**Comment by JosefNemec** [comment]
https://github.com/JosefNemec/PlayniteExtensions/issues/377
