### ISSUE TITLE
background are moving to the filter and details  panal

### ISSUE THREAD

**Issue by Cosmp** [JosefNemec/Playnite#3735]
### Bug Description

background are showing under the filter and details panal 
![Screenshot 2024-04-15 225838](https://github.com/JosefNemec/Playnite/assets/156788975/338420ad-85ad-48a4-95be-a3f56491390d)

### Diagnostics ID

f3543ca8-ff04-45c0-b4f9-f37fb71f3ffa

### Screenshots

![Screenshot 2024-04-15 225838](https://github.com/JosefNemec/Playnite/assets/156788975/2c8df93c-9f62-41b2-b077-6b504069a37a)

**Comment by JosefNemec** [comment]
Please report theme specific issues to its dev, we don't provide support for community made addons here.
