### ISSUE TITLE
Buzzing Sound Caused by Animated Background Image Transitions

### ISSUE THREAD

**Issue by kasonmane** [JosefNemec/Playnite#3742]
### Bug Description

With the option "Animate background image transitions" turned on, a buzzing sound (most likely coil whine) can be heard coming from the computer when switching from one game to another in the library. After disabling this option, the noise goes away. Corroboration of this report can be found in the following Reddit thread:
https://www.reddit.com/r/playnite/comments/191bbac/extremely_weird_buzzing_sound_from_pc_only_when/
I'm unsure if this problem is hardware specific. I'm using a 6750XT, two others in the thread stated they also experienced this same problem on their computers with a 6700XT and 6950XT, so it may be an issue exclusive to AMD GPUs.
Apologies if this bug has already been reported.

### Diagnostics ID

0540ba91-7ca8-4702-9770-ee703946043f

**Comment by JosefNemec** [comment]
We have virtually no control over how GPU is utilized by UI library we use. Nothing we can do about it.

**Comment by ArcticFox037** [comment]
In case this is ever possibly looked into for future (or for anyone searching the issue), I'm also having this specifically in a 6900XT even now.

Might have something to do with brief, intensive GPU usage causing the buzzing; it instantly makes my fans go from 0 to 900 RPM for a moment
