### ISSUE TITLE
Windows Startup

### ISSUE THREAD

**Issue by juturna01** [JosefNemec/Playnite#3743]
### Bug Description

Playnite no longer starts with windows. Ive checked to make sure start with windows is still enabled, it is, and its also no longer in the startup list in task manager. 

### Diagnostics ID

5e723f1f-0fa9-45d2-9bff-03e30b32e67c

**Comment by JosefNemec** [comment]
I don't see anything wrong in the logs. Try disabling start on boot, restarting Playnite, reenabling start on boot.
