### ISSUE TITLE
Modifying Sorting Name on games only sometimes refreshes the display/re-sorts

### ISSUE THREAD

**Issue by SAH7777** [JosefNemec/Playnite#3744]
### Bug Description

Firstly, thank so much for the great Playnite software, and you deserve much credit for it (will donate later hopefully). 

My problem:
I'm currently setting up/building my personal Playnite DB and the following problem keeps coming up... When I edit the **Sorting Name** for a game entry and click Save (save the Edit Game Details menu), only **sometimes** does Playnite refresh the display (i.e. re-sort the games displayed). If I restart Playnite it will re-sort fully OK. Please can you look into this and better force Playnite to refresh display/re-sort when one saves a game entry with edited Sorting Name.

Here is my display options where this bug comes up:
Grid view
No filter applied
Sort by Name Ascending 
Group by Categories

Thank you! 

### Diagnostics ID

000

**Comment by JosefNemec** [comment]
Same as this issue: #1995, will be fixed in that one. It's an issue with UI library we are using.

Btw. attach diagnostics ID in future, we ask for it for good reason, it's not there just for fun of it.

**Comment by SAH7777** [comment]
Great!
