### ISSUE TITLE
Encountered a strange bug where Playnite was unable to launch a game due to name of the executable file had no spaces.

### ISSUE THREAD

**Issue by StellarBeing25** [JosefNemec/Playnite#3745]
### Bug Description

I added Forza Horizon 5 containing the executable "ForzaHorizon5.exe" to Playnite, and I was not able to launch as it was throwing missing DLL errors. However, when I renamed the exe file to "Forza Horizon 5.exe," it launched properly. I have several games with text and numbers without any spaces in the exe file, but I have never encountered this issue which is weird.

### Diagnostics ID

4f889b8d-58c0-47f4-823e-a190297a9cf0

**Comment by JosefNemec** [comment]
> it was throwing missing DLL errors

Game issue. Playnite definitely can with no issue execute games with spaces or no spaces in the path. The only thing is that you sometimes may need to define working directory because some games do not work properly without it, also game issue, not Playnite issue.
