### ISSUE TITLE
Plugin OpenSettingsView method opens the window uncentered and offscreen

### ISSUE THREAD

**Issue by darklinkpower** [JosefNemec/Playnite#3746]
### Bug Description

Using the plugin [OpenSettingsView](https://api.playnite.link/docs/api/Playnite.SDK.Plugins.Plugin.html#Playnite_SDK_Plugins_Plugin_OpenSettingsView) method opens the window uncentered and offscreen. I don't know why this is happening, if I'm not wrong I don't recall this issue happening before.

I don't see the plugin settings window position being saved on `windowPositions.json` but I deleted it anyway to let Playnite recreate it and the issue remains.

### To Reproduce

1. Use [OpenSettingsView](https://api.playnite.link/docs/api/Playnite.SDK.Plugins.Plugin.html#Playnite_SDK_Plugins_Plugin_OpenSettingsView) method.

### Diagnostics ID

0ad534ce-bb4b-4622-8506-bb72a30c8921

### Screenshots

https://github.com/JosefNemec/Playnite/assets/1389286/168c600b-3b5f-4aa9-816e-3a2b5307efe0

**Comment by JosefNemec** [comment]
I can't reproduce it, might be theme issue. Also the window has startup location set to be center of owner window so no idea why it would show like on your video.

> I don't see the plugin settings window position being saved on windowPositions.json but I deleted it anyway to let Playnite recreate it and the issue remains.

This window doesn't save its position.

**Comment by darklinkpower** [comment]
I just checked and the issue is no longer occurring and no changes to the theme have been made. I use a dual monitor setup and it might just be a Windows bug probably where it's giving incorrect information to the methods that are used in Playnite, it's not the first time I've had display bugs like that since I started using Windows 11.
