### ISSUE TITLE
Could we get a global variable for game tags?

### ISSUE THREAD

**Issue by xCeeTee** [JosefNemec/Playnite#3747]
### Feature description

So I'd like to have a global script for all games marked as Competitive or CPU intense in the tags. And another for games I play listening to music.

**Comment by JosefNemec** [comment]
Add condition to global script based on assigned data to a game:

https://api.playnite.link/docs/manual/features/scriptingSupport/exampleScripts.html#executing-actions-depending-of-game-characteristics
