### ISSUE TITLE
Images not loading when searching

### ISSUE THREAD

**Issue by knittycatkitty** [JosefNemec/Playnite#3748]
### Bug Description

Images don't load when searching for artwork online

https://ufile.io/eewa5vvh

video file is too large to upload through github 

### Diagnostics ID

3eb0e815-8e0e-4584-a786-b94cb39757fc

### Screenshots

https://ufile.io/eewa5vvh

**Comment by JosefNemec** [comment]
Go to advanced settings and clear web cache. If it doesn't, help then see [this link](https://api.playnite.link/docs/manual/gettingStarted/helpAndTroubleshooting/troubleshooting.html#general-network-issues).
