### ISSUE TITLE
Library file corruption has been detected 

### ISSUE THREAD

**Issue by andercard0** [JosefNemec/Playnite#3749]
### Bug Description

When I try to delete a game that is no longer available in my list, the title error occurs.

### To Reproduce

- Uninstall a game (via steam, gog whatever)
- Open playnite > right click > delete

### Diagnostics ID

Library file corruption has been detected, playnite ll now shutdown

### Screenshots

![image](https://github.com/JosefNemec/Playnite/assets/43047877/3be10f2c-4741-4556-9a7b-3a34876c12ef)
[library.zip](https://github.com/JosefNemec/Playnite/files/15369869/library.zip)

**Comment by JosefNemec** [comment]
Here's fixed file: [games.zip](https://github.com/JosefNemec/Playnite/files/15369888/games.zip)

**Comment by andercard0** [comment]
> Here's fixed file: [games.zip](https://github.com/JosefNemec/Playnite/files/15369888/games.zip)

Thank you!
