### ISSUE TITLE
Library file corruption has been detected 

### ISSUE THREAD

**Issue by harikrishnav5** [JosefNemec/Playnite#3758]
### Bug Description

App crashing whenever trying to add a game  

[library.zip](https://github.com/user-attachments/files/15525443/library.zip)

### To Reproduce

when trying to add a game through manual or automatic options

### Diagnostics ID

b335d027-bafc-4858-822a-70da182d53fd

### Screenshots

![playnite_library](https://github.com/JosefNemec/Playnite/assets/114297614/5468bf25-f452-41d0-a2a8-0937a4b8f990)

**Comment by JosefNemec** [comment]
Here's fixed file: [games.zip](https://github.com/user-attachments/files/15525879/games.zip)

**Comment by harikrishnav5** [comment]
Thank you very much, it works perfectly now!
