### ISSUE TITLE
Google Image

### ISSUE THREAD

**Issue by lioyiojun** [JosefNemec/Playnite#3763]
### Bug Description

Google Image search doesn't work,and I have already tried Clear web cache.

### Diagnostics ID

4583d480-1cca-406d-87ff-56a9b9d7b0b2

**Comment by JosefNemec** [comment]
- try reinstalling Playnite
- make sure that AV or FW is not blocking any Playnite processes
- check that your network is [working properly](https://api.playnite.link/docs/manual/gettingStarted/helpAndTroubleshooting/troubleshooting.html#general-network-issues)

I don't see any errors in the logs related to image search and can't replicate this myself.
