### ISSUE TITLE
Obsidian and Playnite Integration

### ISSUE THREAD

**Issue by Barmaid1076** [JosefNemec/Playnite#3764]
### Feature description

Obsidian (note-taking) and Playnite integration: The idea is to take notes for games in Obsidian and view them in Playnite. Alternatively, simply implementing a note-taking feature in Playnite would also be great.

**Comment by JosefNemec** [comment]
Things like specific integrations with 3rd party services are usually done via a plugin, which would be more appropriate in this case as well.

> Alternatively, simply implementing a note-taking feature in Playnite would also be great.

There already is a notes field you can use. Currently only supporting plain text but it will support markdown in Playnite 11.

**Comment by Barmaid1076** [comment]
Could you tell me where I can asking for a plugin to be developed?

and just out of curiosity, does the note-taking in playnite11 support adding images? and would it support multiple notes for one game?

Thank you!

**Comment by JosefNemec** [comment]
> Could you tell me where I can asking for a plugin to be developed?

Reddit or Discord

> does the note-taking in playnite11 support adding images? and would it support multiple notes for one game?

No and no

**Comment by Jeshibu** [comment]
This already seems to do most of what you want: https://playnite.link/addons.html#PlayNotes_4208657d-4f78-42d2-968f-39f24de275e1

**Comment by Barmaid1076** [comment]
> This already seems to do most of what you want: https://playnite.link/addons.html#PlayNotes_4208657d-4f78-42d2-968f-39f24de275e1

Yes! I installed this plugin before but failed to make it work. I gave up because I thought it was no longer maintained, had compatibility issues, and I could find very few tutorials about it. I will try it again. Thank you!
