### ISSUE TITLE
System Checker keeps producing error after launching Playnite: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by woutercools** [JosefNemec/Playnite#3765]
### Bug Description

System Checker keeps producing error after launching Playnite: Object reference not set to an instance of an object

![image](https://github.com/JosefNemec/Playnite/assets/16439116/95b90e6d-f6f6-4d5f-8031-76481fbc750f)

3 log files:
[SystemChecker_2024-05-26.zip](https://github.com/user-attachments/files/15904609/SystemChecker_2024-05-26.zip)
[SystemChecker_2024-06-15.zip](https://github.com/user-attachments/files/15904611/SystemChecker_2024-06-15.zip)
[SystemChecker_2024-06-19.zip](https://github.com/user-attachments/files/15904616/SystemChecker_2024-06-19.zip)

### Diagnostics ID

c419c691-2525-4404-a0be-e03ab3aa7e33

**Comment by Jeshibu** [comment]
Plugin issues should be reported to the plugin author, in this case here: https://github.com/Lacro59/playnite-systemchecker-plugin
