### ISSUE TITLE
Library Corruption

### ISSUE THREAD

**Issue by brickcatena** [JosefNemec/Playnite#3769]
### Bug Description

Might not be a bug. Added a user rating to 3 games. Library update was happening. PC crashed (some other reason I assume). 

### To Reproduce

Run a library update.
Add user rating to game
Pull the power on pc shortly after

### Diagnostics ID

b48e2066-22d6-4906-b378-977a58e6f580

### Screenshots

[games.zip](https://github.com/user-attachments/files/16041594/games.zip)
The games I added a rating too:
140
2000:1 A Space Felony
10 Second Ninja X

**Comment by brickcatena** [comment]
I only added the games.db to the games.zip. Here is all of the db files: 
[library.zip](https://github.com/user-attachments/files/16041624/library.zip)

**Comment by JosefNemec** [comment]
Here's fixed file: [games.zip](https://github.com/user-attachments/files/16041646/games.zip)

**Comment by brickcatena** [comment]
I replaced the games.db with the fixed file. Did a backup via Playnite.
If I try to edit the user score for, or simply attempt to remove either of these, I get the corruption message again and Playnite closes.
2000:1 A Space Felony
10 Second Ninja X

**Comment by brickcatena** [comment]
@JosefNemec , do any of the databases I uploaded contain access info for sources? user/pw etc?

**Comment by JosefNemec** [comment]
I can't do any more fixes to that file than what I already did. Some corruptions are just unfixable without considerable amount of effort. This is best I can do for you.

> do any of the databases I uploaded contain access info for sources? user/pw etc?

They don't unless you manually put some of that info into a game field (like description or note fields).

**Comment by brickcatena** [comment]
Thank you for trying
