### ISSUE TITLE
Blank fields in store metadata overwrite existing data

### ISSUE THREAD

**Issue by HunterZ** [JosefNemec/Playnite#377]
Encountered in version 3.3:

I randomly own _The Sims 2 Ultimate Collection_ on Origin, and Playnite found no Developer or Publisher from Origin, so I scraped it from a Wiki. I then re-downloaded the Origin metadata to make sure that what it provided was authoritative, and it cleared the Developer and Publisher without giving me an option to avoid the clear (other than to cancel the metadata save).

A empty/blank field received via a metadata scrape should never overwrite a filled-in field, even if the empty/blank field is explicitly provided by the source. Alternatively, it should be possible for the user to reject the clear by un-checking the box next to the field.

**Comment by HunterZ** [comment]
This also happens for Publisher with Rochard and Super Meat Boy on Steam.

**Comment by JosefNemec** [comment]
Released in 3.4
