### ISSUE TITLE
playnite not recognize sudachi switch emulator

### ISSUE THREAD

**Issue by Andrea18K** [JosefNemec/Playnite#3770]
### Feature description

i hope thi is the right place for my request, can you place add sudachi to the switch emulator knlw to playnite? thank you very much

**Comment by JosefNemec** [comment]
You can configure it manually: https://api.playnite.link/docs/manual/features/emulationSupport/addingNewEmulators.html

It's unlikely we are going to add built-in support due to the entire shit show around Yuzu forks.

**Comment by Andrea18K** [comment]
oh ok, thank you very much and sorry for the mistake
