### ISSUE TITLE
Unable to add/edit game and open the appearance tab in Playnite

### ISSUE THREAD

**Issue by BerbtheHero** [JosefNemec/Playnite#3772]
### Bug Description

This happened very recently, I can't add any game into playnite without it crashing. Here is what I've tried so far,
edited games.db
deleted games.db
safe mode
reinstalled
uninstalled and reinstalled
deleted every single file and reinstalled

### To Reproduce

add a game, also going to the appearance tab causes a hard crash

### Diagnostics ID

ec68fa7d-3768-44e3-85a8-42c6307dd261

**Comment by JosefNemec** [comment]
It's crashing on some low level function related to loading fonts. Looks like something corrupted with the system probably. Nothing I can do about this.

See sections here about broken .NET and Windows installations: https://api.playnite.link/docs/manual/gettingStarted/helpAndTroubleshooting/troubleshooting.html#playnite-is-crashing
