### ISSUE TITLE
Failed to import games from steam

### ISSUE THREAD

**Issue by gabrcare** [JosefNemec/Playnite#3777]
### Bug Description

The bug I am having is when Playnite tries to get not-installed games from my steam library, it says "Failed to import games from steam" and failed to import games from my steam API account. I have tried both using the private API method and the public library method. I have clicked on the diagnostic package 
Please get back to me ASAP
Thank You

### Diagnostics ID

043f6dbb-d87b-4711-bfcb-3b0915e47d41

### Screenshots

![Screenshot 2024-07-16 201740](https://github.com/user-attachments/assets/76e71e0a-35be-4c6e-88fc-896cc5d1eb05)

**Comment by gabrcare** [comment]
Note: don't worry about that first error message

**Comment by JosefNemec** [comment]
1) Wrong repository. Issue template clearly state that issues related to integration plugins should be reported somewhere else.
2) The error is from an extra account you have configured without setting up any API key for it (additional accounts tab). That tab is only for non-primary accounts. So delete that entry, login and configure an API key on general page.
