### ISSUE TITLE
Game not showing up on horizontal scrolling

### ISSUE THREAD

**Issue by Yoned-Mikay** [JosefNemec/Playnite#3778]
### Bug Description

I added Pokemon Unbound to my Library, but it only shows up on vertical scrolling. How do I solve this? The theme I'm using is Ubiquity.

### Diagnostics ID

5a2e3362-be58-4073-9a49-1e7ad5f59813

### Screenshots

![horizontal](https://github.com/user-attachments/assets/b09857c0-8194-45a4-adf1-2bb6294871e5)
![vertical](https://github.com/user-attachments/assets/60fdc740-d528-4dc1-9197-22646efbd988)

**Comment by JosefNemec** [comment]
Probably theme issue, test with the default one and if it works, report issue to theme developer.
