### ISSUE TITLE
More aliases needed

### ISSUE THREAD

**Issue by X012C** [JosefNemec/Playnite#3781]
### Feature description

When we play games from more than one country, they have multiple names when they are not officially translated. They include the names of the translation teams and the names used in the original place. Hopefully, games can support multiple aliases as subtitles to facilitate scraping and sorting.

**Comment by JosefNemec** [comment]
#3190

**Comment by Jeshibu** [comment]
How would aliases facilitate sorting?

**Comment by X012C** [comment]
> How would aliases facilitate sorting?

This may be a problem with Google Translate. I don't know this word either. In my original language, it is X to strengthen the meaning of scraping certain actions, not sorting.
