### ISSUE TITLE
game alternative name (alias)

### ISSUE THREAD

**Issue by g2mXagent** [JosefNemec/Playnite#3783]
### Feature description

A game may have many different names in different regions. As a game library, I hope Playnite can record these names (as aliases), specify which name to display, and find the corresponding game when searching. Just like in LaunchBox.

### Screenshots

![LaunchBox_6lQ9Jb8P3X](https://github.com/user-attachments/assets/6288ef62-099b-4935-83bd-f13b4b946332)

**Comment by JosefNemec** [comment]
#3190

**Comment by g2mXagent** [comment]
@JosefNemec 
Where is the alias? Is it "Soring Name"? However, this is not what I want. LaunchBox can support multiple names at the same time, but Playnite only supports one alias?

Alias ​​should work similarly to the existing feature "Links", where users can customize as many links as they like and name them.

![Playnite DesktopApp_SK6cGyttoi](https://github.com/user-attachments/assets/4cd7b6e2-b2d9-45c0-9c40-2a12d0603304)

**Comment by JosefNemec** [comment]
There is no alias support. I closed this because alternatives names are being tracked in different existing issue which this is duplicate to.
