### ISSUE TITLE
Fullscreen mode tends to hang when controller disconnects and reconnects

### ISSUE THREAD

**Issue by Mythrix** [JosefNemec/Playnite#3785]
### Bug Description

I quite consistently have an issue with the Fullscreen mode hanging for around a minute if my Xbox 360 wireless controller disconnects and then reconnects again.

Additionally, when using Sunshine/Moonlight to stream to a mobile device, Fullscreen mode also hangs for about a minute, and I suspect this is also caused by the virtual controller that Sunshine uses.

After about a minute of hanging, Playnite works fine with the controller (both the X360 controller and Moonlight controller), so it's not a super big problem, but it is slightly annoying.

Is this is some kind of known issue with Xinput or something?

Notes:
- I'm using Windows 11 23H2
- My installed Playnite version is currently 10.33
- I have tried googling, searching the issues in this repo, searching on the Playnite subreddit and in the Playnite Discord, but I could not find anyone describing the same issue anywhere
- I tried changing the Fullscreen theme back to the default one
- I also tried starting Playnite Fullscreen in safe mode
- None of those steps seemed to help

### To Reproduce

1. Turn on the Xbox 360 controller
2. Start Playnite Fullscreen mode
3. The controller works fine
4. Turn off the Xbox 360 controller (take out the batteries)
5. Turn the Xbox 360 controller on again
6. Playnite hangs for about a minute before I can use it again

Sunshine/Moonlight:
1. I'm using a Razr Kishi controller on an Android phone (Galaxy Note8)
2. Start Playnite from the Moonlight app on mobile
3. Sunshine is configured to start Playnite Fullscreen mode as a detached app
4. Once Playnite is started, it then immediately hangs for about a minute before I can use it
(As a sidenote, if I don't connect the Razr Kishi, then Playnite starts up without hanging, but then I am unable to play anything.)

### Diagnostics ID

f4b7a50b-aadf-4257-b3c8-ad336339af16

**Comment by JosefNemec** [comment]
This sounds like some issue related to streaming. I can't reproduce this under normal non-streaming circumstances so most likely some compatibility issue in/with Moonlight/Sunshine. Not much I will be able to do here, we don't do anything different when Playnite is being streamed (there is no direct support for it).

**Comment by JosefNemec** [comment]
You can try extracting this to Playnite install folder to see if it fixes the issue: https://github.com/libsdl-org/SDL/releases/download/release-2.30.6/SDL2-2.30.6-win32-x86.zip

It's the latest version of SDL2, library we use to handle controller input.

**Comment by Mythrix** [comment]
> This sounds like some issue related to streaming.

Just to clarify, the issue also occurs when I am playing with an Xbox 360 controller locally on the PC, so it is not only when streaming.

But thanks for the new SDL file, I will test this when I am home!

**Comment by Mythrix** [comment]
The new SDL2.dll driver did not seem to help.

However, I finally wisened up and searched for the same issue without specifying "Playnite", and found [this thread about the same issue on Steam](https://steamcommunity.com/discussions/forum/1/541907867751931687/). The final suggestion was to just try uninstalling the controller and the wireless dongle from Windows Device Manager, and then restart.

Doing this seemed to have solved the issue for now!

As a bonus, booting up fullscreen mode is a lot faster now, so I think this issue actually caused a long delay when switching to fullscreen mode. I just thought it was because of my huge gaming library, so I didn't realize the long delay in starting up fullscreen mode was the same issue.

Sorry for troubling you with this issue! I'll just close it as resolved then.

**Comment by Mythrix** [comment]
Man, that solution did *not* last long, today the same issue occured again. *sigh*

But in any case, I am suspecting that it is not an issue with Playnite itself, but rather with the Xinput or SDL drivers. (That's why in my bug report I was asking if this was some kind of known issue with Xinput.) I'll just keep trying to google for similar issues not related for Playnite and see if I find any solutions, can just keep this issue closed.
