### ISSUE TITLE
Silent install has no way to prevent launching Playnite once complete

### ISSUE THREAD

**Issue by the0neWhoKnocks** [JosefNemec/Playnite#3786]
### Bug Description

I'm installing Playnite silently via `.\Playnite_v10.33.exe /SILENT /DIR="<PATH>"` inside a script, and it launches Playnite once it's done which then prevents the script from proceeding without me manually killing Playnite.

I recorded a manual install via `.\Playnite_v10.33.exe /SAVEINF=".\temp"`, unchecked the launch option at the end, and the only `TASKS` listed were for the creation of the desktop and startmenu items. I tried keeping the launch item checked, but there was nothing new listed for `TASKS`.

It seems the ability to prevent launch after install was missed when switching to Inno.

### Diagnostics ID

N/A

**Comment by JosefNemec** [comment]
Use `/NORUN` argument.
