### ISSUE TITLE
Add support for Visual Studio 2022 for theme editing

### ISSUE THREAD

**Issue by SHiLLySiT** [JosefNemec/Playnite#3787]
### Feature description

# Summary
Visual Studio 2019 is no longer available for free from Microsoft, making _free_ theme editing not possible with Blend. Please add support for editing themes in Visual Studio 2022.

# Details
[The Playnite documentation](https://api.playnite.link/docs/tutorials/themes/usingBlend.html) directs users to install VS 2019 via [this link](https://visualstudio.microsoft.com/vs/older-downloads/). However there's a banner at the top of the page that reads "Older versions require an active Visual Studio Subscription":

![download](https://github.com/user-attachments/assets/6d96fde0-27f7-4be8-b20d-0c6cd16400c9)

Ignoring the banner and navigating to the VS 2019 downloads, only the 2019 redistributable is available:
![list1](https://github.com/user-attachments/assets/2ba98ace-bb67-40e3-ae45-07b176d7db16)

Fiddling with the filters however, reveals a more explicit unavailability:
![list2](https://github.com/user-attachments/assets/8a93e7ca-f712-41ce-bea9-253301436b1c)

**Comment by JosefNemec** [comment]
Will be done automatically after #1199 is completed.
