### ISSUE TITLE
Missing metadata for individual entries from GOG multi-game packs

### ISSUE THREAD

**Issue by HunterZ** [JosefNemec/Playnite#379]
GOG sells games in packs, such as King's Quest 1+2+3: https://www.gog.com/game/kings_quest_1_2_3

These show up in the user's GOG library as individual entries for each game.

Playnite seems unable to scrape developer, publisher, and genre for these library entries. I wonder if it's possible for the scraper to find them by going one level deeper, as the data is present on the store page?

**Comment by JosefNemec** [comment]
I had a look at this and sadly it doesn't seem to be possible because of how GOG bundles the metadata.
