### ISSUE TITLE
Library corruption

### ISSUE THREAD

**Issue by bukkaroo** [JosefNemec/Playnite#3790]
### Bug Description

When attempting to remove a game I get the following error:
**Library file corruption has been detected. Playnite will now shutdown**

[Ares library - no media.zip](https://github.com/user-attachments/files/16460729/Ares.library.-.no.media.zip)

### Diagnostics ID

6ab6ac9f-8a3b-4840-9a80-37d10f26af3b

**Comment by JosefNemec** [comment]
Fixed file: [games.zip](https://github.com/user-attachments/files/16461131/games.zip)
