### ISSUE TITLE
Controller detected but only triggers work

### ISSUE THREAD

**Issue by the0neWhoKnocks** [JosefNemec/Playnite#3794]
### Bug Description

My old official Bluetooth XBox controller worked in Playnite, but a joystick died and I decided to upgrade to the 8bitdo 3-mode controller.

I have the controller set to 2.4 wireless (X-Input), and it works everywhere except Playnite aside for the triggers scrolling the UI vertically.

I used [sdl2-gamepad-mapper](https://gitlab.com/ryochan7/sdl2-gamepad-mapper/-/releases) and it detected my controller, I copied the resulting string over to `gamecontrollerdb.txt`, still the same result.

There's a [similar report on reddit](https://www.reddit.com/r/playnite/comments/1cn5ryt) as well.

### Diagnostics ID

1c5df34a-9fe2-455f-a94a-6f93017fc917

**Comment by JosefNemec** [comment]
Try replacing this file in Playnite's install folder: https://github.com/libsdl-org/SDL/releases/download/release-2.30.6/SDL2-2.30.6-win32-x86.zip

Other than that, no idea. I do see some open issues in SDL2's repo related to 8bitdo controllers, but it looks like most of them are caused by bad mappings. Make sure that your custom mapping in `gamecontrollerdb.txt` is the only one for that controller ID (maybe there's broken duplicate one as well).

**Comment by the0neWhoKnocks** [comment]
Replacing the `.dll` worked. Perhaps adding that to the controller support documentation as a possible fix, may help others.

I commented out my addition to `gamecontrollerdb.txt`, restarted Playnite and it still worked.

How does `gamecontrollerdb.txt` work? I was assuming that I'd just have to add my contoller's mapping string and Playnite would just pick it up from there. Are the definitions baked into that `.dll`?

**Comment by JosefNemec** [comment]
> Replacing the .dll worked. Perhaps adding that to the controller support documentation as a possible fix, may help others.

That means the issue was somewhere in SDL2 and was fixed in some recent update. Playnite doesn't use the most up to date version since there wasn't Playnite update for some time now, I will have to push new Playnite update with update SDL2 dependency.

**Comment by JosefNemec** [comment]
SDL2 was updated to the latest version in 10.34 update.

**Comment by xenophobentx** [comment]
Interestingly i have repro here with windows 11wirh series x controller. It happens randomly maybe after waking from sleep. Will test it and come back.

**Comment by blitz2kx** [comment]
Having the same issue with an Xbox Wireless Adapter and an official controller. Randomly, playnite full screen doesn't respect any inputs besides triggers.

A full reboot of my system fixed it. Windows 11. Hope this helps

**Comment by ScolderCreations** [comment]
Having this same issue today in various apps including Cemu, where the SDL controller only allows trigger input and DirectInput works.

**Comment by cherryontopknife** [comment]
Same, this issue randomly started this morning. My controller works in full screen until the libraries start refreshing, then only the triggers work. I tried replacing the DLL file, no effect. I'm on W11 24H2.

**Comment by JosefNemec** [comment]
You can try the latest SDL dll from here, other than I have no solution for you:
https://github.com/libsdl-org/SDL/releases/download/release-2.32.6/SDL2-2.32.6-win32-x86.zip

**Comment by JosefNemec** [comment]
Also please let me know if it actually fixes the issue in which case I'll release new Playnite update with updated SDL library.

**Comment by JosefNemec** [comment]
Also linking this https://github.com/libsdl-org/SDL/issues/13047 in case it's in fact issue in SDL.

**Comment by cherryontopknife** [comment]
OK so I think this is an issue with a plugin. I replaced the DLL as recommended and rebooted. Playnite said it failed to close properly and asked if I wanted to run in safe mode. The controller worked as expected. I closed Playnite, restarted it not in safe mode, and again my controller doesn't work.

**Comment by cherryontopknife** [comment]
I went into DKG Theme editor, just messed with some settings of my full screen theme, removed entries and turned off settings in the SuccessStory plugin, and now my controller works in full screen. I did mess with some plugins yesterday, but I only uninstalled things. Weird.

**Comment by JosefNemec** [comment]
I don't think it's plugin related since another person mentioned the issue also affects other apps using SDL and there's now also report from somebody else in SDL repo.

Plus looking at extensions change history, there was no extension updated that would directly mess around with controller input, as far as I tell.

**Comment by JosefNemec** [comment]
Might be possibly related to SuccessStory plugin if this report is accurate: https://github.com/Lacro59/playnite-successstory-plugin/issues/612

**Comment by deskora** [comment]
I'm not using SuccessStory plugin and I will constantly have Playnite (even after manually updating the SDL2.dll file from github to something newer) stop working with my Xbox-related controllers.  I don't understand it.  

Even tried download the AntiMicroX App (which uses SDL2) and I'll notice the exact same issue where it can't see any other button presses except for the triggers.

is there some Win11 service that I should restart that interfaces with the SDL2.dll? It's such an annoying issue - I just don't understand it. I hate rebooting my PC just so my controllers will work in Playnite (and other apps that use SDL2) - I'd be open to running a script that restarts services that interface with SDL2.dll as some sort of hacky workaround.

using 8bitdo Ultimate 3-way Xbox controllers as well as Xbox Series controllers

**Comment by henryfa2** [comment]
@JosefNemec 
Hey,
I had the issue as well.
After deactivating SuccessStory, as you pointed out, it fixed the issue. XBOX 360 controller working as expected.

**Comment by JosefNemec** [comment]
10.36 update released today includes SDL_HINT_JOYSTICK_RAWINPUT based workaround mentioned in SDL's repo. I also updated SDL2 to the latest version. If this doesn't fix the issue for you, it's probably somehow SuccessStory related issue (although I still don't understand how SS can be breaking this). That's all I can do for this.

**Comment by henryfa2** [comment]
> 10.36 update released today includes SDL_HINT_JOYSTICK_RAWINPUT based workaround mentioned in SDL's repo. I also updated SDL2 to the latest version. If this doesn't fix the issue for you, it's probably somehow SuccessStory related issue (although I still don't understand how SS can be breaking this). That's all I can do for this.

Updating to 10.36 fixed the issue for me.
Thanks

**Comment by Charade28** [comment]
Success Story 3.5 is the issue for me after updating to 10.37

**Comment by filipemendespi** [comment]
> Success Story 3.5 is the issue for me after updating to 10.37

for me too...

**Comment by CrumpThePenguin** [comment]
> > Success Story 3.5 is the issue for me after updating to 10.37
> 
> for me too...

Same here. Just started having this, found this thread. Disabling Playstory immediately fixed it. Weirdly enough if I use the same controller (8BitDo Ultimate 2) but booted into Switch Pro mode (Power on while holding Y) it works even with Success Story.

**Comment by HusbandOfBomi** [comment]
I am having a similar issue. Playnite recognises my 8BitDo Ultimate 2 controller however when I try to press any buttons or the stick etc it does nothing. The controller works in all other applications. How can I fix this?

**Comment by JosefNemec** [comment]
https://api.playnite.link/docs/manual/gettingStarted/helpAndTroubleshooting/troubleshooting.html#my-controller-is-not-working

**Comment by HusbandOfBomi** [comment]
> https://api.playnite.link/docs/manual/gettingStarted/helpAndTroubleshooting/troubleshooting.html#my-controller-is-not-working

So I didn't even need to do this. So my 8BitDo Ultimate 2 controller has 2 connectivity methods 2.4GHz and Bluetooth. With my PC I normally use 2.4 since it is much faster than bluetooth. I thought I'd try connecting with bluetooth and see if it works and yeah instantly worked with playnite fullscreen no need for work arounds. Not sure why it doesn't work with 2.4GHz or when plugged into the PC bia USB-C but it works with bluetooth no issues.

**Comment by lyndonguitar** [comment]
> Success Story 3.5 is the issue for me after updating to 10.37

thank you for this. uninstalling success story immediately fixed my xbox elite series 2 controller not working on playnite (but working everywhere else)

**Comment by larryventura** [comment]
Looks like fix may have been backported to SDL2?
https://github.com/libsdl-org/SDL/issues/13047#issuecomment-3382766626

*Edit - per https://github.com/Nonary/PlayNiteWatcher/issues/25#issuecomment-3399515532, I was able to get it working with latest version of sdl2-compat / SDL3

**Comment by JosefNemec** [comment]
As as said in this comment: https://github.com/JosefNemec/Playnite/issues/3794#issuecomment-2969620782 we already have that SDL fix in Playnite

**Comment by JosefNemec** [comment]
Also current version of Playnite is already using the latest version of SDL2 available, 2.32.10. If you have controller issues still, it's most likely due to SuccessStory plugin.

**Comment by larryventura** [comment]
Sorry I wasn't clearer. The problem persisted after removal of SuccessStory, so I explored further. Issue for me was resolved with `sdl2-compat 2.32.58` working with `SDL3-3.2.26`. I compiled latest `sdl2-compat 2.32.58` and replaced SDL2.dll with it.

@deskora set me on the path here https://github.com/JosefNemec/Playnite/issues/3794#issuecomment-2969620782 (Comment is from October 14th), and I was able to find related comment from @AL2009man on https://github.com/libsdl-org/SDL/issues/13047#issuecomment-3382766626 and compile the newest `sdl2-compat 2.32.58` branch myself and point to newest SDL3. Issue has been resolved for me by doing this, just trying to help others who may find this thread.

I did think this was caused by SuccessStory initially, but was able to eliminate it as a suspect since the problem persisted after removal. After above SDL update controller is working in fullscreen with Successstory reinstalled.

**Comment by syaifulnizamyahya** [comment]
> Sorry I wasn't clearer. The problem persisted after removal of SuccessStory, so I explored further. Issue for me was resolved with `sdl2-compat 2.32.58` working with `SDL3-3.2.26`. I compiled latest `sdl2-compat 2.32.58` and replaced SDL2.dll with it.
> 
> [@deskora](https://github.com/deskora) set me on the path here [#3794 (comment)](https://github.com/JosefNemec/Playnite/issues/3794#issuecomment-2969620782) (Comment is from October 14th), and I was able to find related comment from [@AL2009man](https://github.com/AL2009man) on [libsdl-org/SDL#13047 (comment)](https://github.com/libsdl-org/SDL/issues/13047#issuecomment-3382766626) and compile the newest `sdl2-compat 2.32.58` branch myself and point to newest SDL3. Issue has been resolved for me by doing this, just trying to help others who may find this thread.
> 
> I did think this was caused by SuccessStory initially, but was able to eliminate it as a suspect since the problem persisted after removal. After above SDL update controller is working in fullscreen with Successstory reinstalled.

Can confirm this works. All i did was replace the SDL with https://github.com/libsdl-org/sdl2-compat/releases. I think after new version of playnite, I might need to do this again as playnite might replace the sdl.

Hopefully, playnite will update its sdl.

**Comment by larryventura** [comment]
@syaifulnizamyahya Can confirm the fixed DLL persisted through last Playnite update.

**Comment by syaifulnizamyahya** [comment]
Hi. Shouldn't this bug be marked as open?

**Comment by JosefNemec** [comment]
The next update will switch to that sdl2-compat project to see if this fixes it the issue. I can't really switch P10 to SDL3 because of some issues related to P10 still running on old .NET, it's just giving me headaches.

Thank @larryventura for mentioning sdl2-compat, I had no idea that project existed.

**Comment by JosefNemec** [comment]
10.49 update is not using sdl2-compat, please let me know if it fixed the issue.
