### ISSUE TITLE
Playnite Google Web Image Search keeps failing

### ISSUE THREAD

**Issue by Zemoco101** [JosefNemec/Playnite#3796]
### Bug Description

The Web Image Search keeps failing for me. I've used the fix for this by removing resetting my web cache in the settings and it works for a little while but the issue always comes back.  I've tried making sure my firewall accepts Playnite but I have no issues with that since all other aspects of playnites such as using addons, IDGB, Steamgrid all work fine.

Same issue even in safe mode. Again like I mentioned previously, clearing the web cache fixes it, but usually a few days later it's back to not working. 

### Diagnostics ID

20400cc6-02a5-4164-aff9-f8d77c701d7d

### Screenshots

![Playnite DesktopApp_repDmcD44Z](https://github.com/user-attachments/assets/61e1ef9a-a3d7-4ed4-9c12-79b3b4086a57)
![Playnite DesktopApp_nqLKpHx12i](https://github.com/user-attachments/assets/ac928daa-ca65-4df1-88a9-d1c60a5dec4d)

**Comment by JosefNemec** [comment]
Your network is getting flagged by Google via anti-bot measures, more info here:

https://api.playnite.link/docs/manual/gettingStarted/helpAndTroubleshooting/troubleshooting.html#web-image-search-doesnt-work

**Comment by JosefNemec** [comment]
Btw there's basically nothing we can do about this. The search works by using hidden Google image search page because Google deprecated free search API and once you are blocked search starts requiring solving captcha.

The only solution would be switching to different image search provider, but as far as I know, there's no provider that would offer free API and also good results.

**Comment by JosefNemec** [comment]
Just to confirm that this is in fact network block issue:
- download and extract this to install folder: https://playnite.link/download/web_image_issue_test.zip
- reproduce the issue
- generate new diag. package

Thank you

**Comment by Zemoco101** [comment]
All right thank you for explaining. So it's my VPN (something I already used to begin with.) Switched servers and it's working. 

At least that's solved since this issue was driving me crazy.
