### ISSUE TITLE
Games config and save files under the Playnite folder using the Sandboxie compartment mode approach.

### ISSUE THREAD

**Issue by StellarBeing25** [JosefNemec/Playnite#3798]
### Feature description

I tried running games using Sandboxie compartment mode, and all the game config and saves were being created in a custom folder without any performance loss or compatibility problems. It would be nice to have something similar in Playnite for easy backup, sync, and portability.

![CM](https://github.com/user-attachments/assets/72132da3-15d6-43ec-a431-d8023c7b6168)

**Comment by JosefNemec** [comment]
This is out of scope for this project (it's single person project). Would be more fit to be done as a plugin.
