### ISSUE TITLE
retroarch from playnite launch problems

### ISSUE THREAD

**Issue by Darkloke** [JosefNemec/Playnite#3799]
### Feature description

Greetings. I have two problems regarding launching retroarch from playnite.

First of all let me describe my setup. I am using a portable playnite installation, which (along with retroarch and roms) i placed in cloud drive (local folder, which synchronizes with cloud) to be able to play both at home and work. This folder located at separate drive (at the same path at home/work) and the path doesnt contain non-english letters. Configuration is provided at screenshots. Cloud drive used - Yandex disk.

Another thing i did - i sylinked playnite browsercache folder to the system temp directory to exclude this files from synchronization (i suppose they are kind of temp anyway).

1. The first problem is with arcade/mame games. Some of them require bios files, which *ideally* should be placed at retroarch/system(/fbneo) directory. If i place them at that system directory, then the games launched from retroarch itself are working normally, but they dont work when i launch them from playnite ("one of your romsets is missing files for this version of fbneo" error).
I suppose this happening may be because when launching with arguments:
-L ".\cores\fbneo_libretro.dll" "{ImagePath}"
retroarch searches needed files only in roms directory and ignore that system folder. If i move this bios files to the roms folder, then its working ok.

So far i am using workaround by storing bios files along with roms, but adding them as exclusions in auto-scan configuration so they wont appear every times i import a new game.

3. Another problem with retroachievements. They are working ok at home, but failing at the work when i launch retroarch from playnite, but they still work if i launch the game from retroarch directly. Since config is the same i dont understand what could be a reason. I could only suppose the following...
- Internet at the work organized via proxy - i am using Proxifier tool to pass all the traffic through it. When i launch directly from retroarch i could see there connections to retroachievements.org, but while launching from playnite - there are no such connections.
- Default Windows 10 language is different: English at home, Russian at work, but i am not sure if its affect something unless is messes somehow folders or paths.

4. Another thing not related to the problems above - while playinite is launched cloud drive synchronization tool constantly shows me error regarding games.db that cannot be synchronized. I suppose this is because the file is in use, locked or some kind of. Just informing. Btw it would be nice in general to minimize updates to playnite files to decrease synchronization requests (file like for logs for example etc.).

### Screenshots

![image](https://github.com/user-attachments/assets/08463b90-ad89-41e6-970d-2a6528dd8ffc)
![image](https://github.com/user-attachments/assets/4f729c34-1705-4f65-bdf2-332a70340d13)
![image](https://github.com/user-attachments/assets/a95258f2-0d05-4e4c-a744-0589841354ff)
![Screenshot_1](https://github.com/user-attachments/assets/890734cc-cfb3-4949-9179-f9d5845f32c3)

**Comment by JosefNemec** [comment]
As I explained this to you on Discord, this is either RetroArch issue (issues with different behavior when games are launched via command line as compared to launched directly from the emulator) or issue with used command line arguments. [As described here](https://api.playnite.link/docs/manual/features/emulationSupport/troubleshooting.html#game-runs-properly-when-launched-manually-from-an-emulator-but-not-from-playnite).

There is nothing we can change in Playnite other than modifying default command line arguments in built-in profiles to ones that will fix this, if it is in fact an issue with what arguments we are using. We can't do anything else about this since passing around command line arguments is the only way we can interact with the emulator during game startup. So this would be probably better support question for RetroArch team, imo.

> Another thing not related to the problems above - while playinite is launched cloud drive synchronization tool constantly shows me error regarding games.db that cannot be synchronized.

This is intentional and not going to change. We've had issues in the past with cloud tool corrupting files and therefore library files are being locked.

> Btw it would be nice in general to minimize updates to playnite files to decrease synchronization requests (file like for logs for example etc.).

You should not be syncing those files, I don't know why you would sync log files or other program files. Adding extra complexity to the app to just to cater to cloud sync tools in this way is not worth it and I don't want to maintain that.

There is long term plan to have proper built-in device sync support but there's no ETA.

**Comment by Darkloke** [comment]
Ah, it was you in discord. Sorry, i was simply unaware. :)

Well, i see then. I will try contact retroarch developers, but i suppose they would say "if its for working for you directly from retroarch, then it isnt an our problem". xD Well, anyway i should try at least.

As for syncing - i meant that all folders lie in sync folder, which syncs as a whole, i.e. i dont choose what to sync - i just see that when i close retroarch a bunch of files changed/updated and posted in sync queue.

**Comment by JosefNemec** [comment]
> Well, i see then. I will try contact retroarch developers, but i suppose they would say "if its for working for you directly from retroarch, then it isnt an our problem". xD Well, anyway i should try at least.

Well they are supporting game startup from command line so that should work, it is supported scenario from their point of view, if it wasn't, then I don't know why they would have those arguments implemented.

**Comment by Darkloke** [comment]
> Well they are supporting game startup from command line so that should work, it is supported scenario from their point of view, if it wasn't, then I don't know why they would have those arguments implemented.

Well, you see running from windows cmd is working for me - it just doesnt work from playnite. Basically i do the same, just changing {ImagePath} to actual path...
![image](https://github.com/user-attachments/assets/a7903de5-36f7-4ae2-9846-7644c4aeffb8)
![image](https://github.com/user-attachments/assets/078c06d0-a79d-445a-ba9c-882891250104)

**Comment by JosefNemec** [comment]
If it works from cmd, then it has to work from Playnite as well. The only difference would be working directory. Try setting working directory in Playnite to whatever you are using in cmd.

**Comment by Darkloke** [comment]
Some info. I was able to solve the problem with r-achievements by reentering the password to RA account manually in retroarch.cfg. The password later disappears anyway from config - i suppose it "converts" into authorization token. May be it was necessary to recreate token on 2nd machine (work), but it works normally now at both machines. May be this could help someone.
