### ISSUE TITLE
Game list not updating with category changes

### ISSUE THREAD

**Issue by robbely** [JosefNemec/Playnite#3800]
### Bug Description

Since the last update 10.34, if I add a new game or chnge the category for an existing game, the game list doesn't update. The only way to see the changes is to turn grouping off and on again or restart the app.

### To Reproduce

Add a new game - game doesn't show in list
Add a category to an existing game - game does not show in new category

### Diagnostics ID

n/a

**Comment by JosefNemec** [comment]
It's caused by the latest SuccessStory update: https://github.com/Lacro59/playnite-successstory-plugin/issues/509

**Comment by JosefNemec** [comment]
If you can, please attach logs to [the issue](https://github.com/Lacro59/playnite-successstory-plugin/issues/509) I linked in SS repository, thank you.

> Attach Playnite's `Extensions.log` file. It is located in Playnite's installation directory in the portable version or in `%AppData%\Playnite` (Can be pasted in Explorer) in the installed version

**Comment by robbely** [comment]
Unfortunately I have downgraded the plugin now, I can confirm that it fixed the issue though.
