### ISSUE TITLE
Crash on Game Edit or Settings / Appearance / General

### ISSUE THREAD

**Issue by LeeThompson** [JosefNemec/Playnite#3802]
### Bug Description

I am not sure why this is happening; I haven't changed any fonts or Playnite settings but suddenly it's crashing.

I did update to 10.34 a few days ago but it's been fine?

This is similar in behavior to #2623

### To Reproduce

For me, edit any game entry or go into Playnite's appearance settings.

I've generated a diagnostic report in the hopes that if not a bug someone can at least tell me where to look.
The exception seems related to fonts.

### Diagnostics ID

bcbe5fa2-41fe-43d2-8e50-ab03ecbacda7

**Comment by LeeThompson** [comment]
I edited the config.json in notepad++ and saw that the mono font had changed back to Cascadia Mono (which was part of the prior issue), I changed it back to Consolas and now it works again.

I'm going to leave this open in case it's something that should be fixed.   

I don't remember changing the font to Cascadia Mono.

**Comment by LeeThompson** [comment]
I just checked the backup when I updated to Playnite 10.34 and in the backup's config, the font is set to Consolas

```
  "FontFamilyName": "Calibri",
  "MonospaceFontFamilyName": "Consolas",
```

So this somehow happened when I updated (I used the zip since I have it installed to a non-standard folder).

**Comment by JosefNemec** [comment]
The crash happens because Playnite fails to load that font. Which is standard font included with Windows, so most likely your Windows/Fonts files got corrupted somehow. Nothing I can do about that.

Also, there was no change to anything settings or config related in 10.34 update, you must have had that font set there even before the update.

**Comment by LeeThompson** [comment]
The fonts aren't corrupted.  That's the part I have a problem with.
