### ISSUE TITLE
Allow OpenGoal addition

### ISSUE THREAD

**Issue by DannyDarth** [JosefNemec/Playnite#3804]
### Feature description

Allow to add the OpenGoal Launcher. OpenGoal is a recompilation launcher for certain games.

**Comment by DannyDarth** [comment]
![Uploading 2024-08-23-19-35-52-Parsec.png…]()

**Comment by JosefNemec** [comment]
Any library integrations of launchers have to be done as separate plugins, not as built-in feature. I don't have time to personally implement and maintain any more library integrations, I have plenty to maintain already. Somebody else from the community will have to do make it as "3rd party" plugin.
