### ISSUE TITLE
Video Trailer in Media Section when editing a game

### ISSUE THREAD

**Issue by B-Radz** [JosefNemec/Playnite#3808]
### Feature description

Since the issue with YT metadata, I've learned how to add a pre downloaded trailer to the game by opening the Extra Metadata folder & naming it VideoTrailer.mp4 or VideoMicrotrailer.mp4. 

The issue is the trailer will play video for 10 seconds, then show the games photo background while the trailer sound is playing until it shows it again, all while the trailer continues.

The solution to this could be adding a dedicated "Trailer" spot to the Edit Game Details < Media section, and letting us choose a time frame for the trailer to play for. 

Absolutely love Playnite, and this is the only problem I've come across. This would make a world of a differene, saving so much time and troubleshooting. Thank you for your consideration and I hope you have a good day/night.

### Screenshots

![d4084c78-5894-4499-b6fa-0d4530eef16a 8_28_2024 2_50_28 AM](https://github.com/user-attachments/assets/71301bec-c2da-437c-a37f-c65574a2de05)

![Edit Game Details 8_28_2024 2_52_38 AM](https://github.com/user-attachments/assets/c14de433-4609-44f7-aa89-b890932ba007)

![Playnite 8_28_2024 2_54_24 AM](https://github.com/user-attachments/assets/3bba0761-2ef6-485c-88ab-d1b8745e38cd)

![Playnite 8_28_2024 2_54_55 AM](https://github.com/user-attachments/assets/1a342e41-32fd-4e68-b8e4-e59277deca15)

![Playnite 8_28_2024 2_55_00 AM](https://github.com/user-attachments/assets/7b110c89-29c5-4dc1-b380-4f96ad36618c)

**Comment by JosefNemec** [comment]
This is up to the plugin to handle. Playnite doesn't support this as built-in media type and therefore we can't add any editing options for it.
