### ISSUE TITLE
Random color mode

### ISSUE THREAD

**Issue by Evene174** [JosefNemec/Playnite#381]
It would be cool if Playnite will be has a random color mode, and after every launch of program (or after launch of game) the color of the theme would change.
It's not difficult for theme's makers to make more colors, but it will add variety.

**Comment by ArtexJay** [comment]
I have a similar suggestion, that playnite's color changes based on the default computer's accent color theme

**Comment by JosefNemec** [comment]
Theme color profiles will not longer be possible in 5.0 and changing theme does require restart of application. For those reasons I'm closing this.
