### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by Ronsolo77** [JosefNemec/Playnite#3811]
### Bug Description

The games immediately crash when I try to use them. It sends me to the "Whoops! Something went wrong" window. 

### Diagnostics ID

c99e7ef0-2511-4eb6-8881-fdc763107a11

### Screenshots

![image](https://github.com/user-attachments/assets/0fb6830c-8b72-4d7b-b52c-0dedd7becb10)
![Playnite](https://github.com/user-attachments/assets/34e87f15-979a-43c2-8027-369ba8ce1eec)
![Screenshot 2024-08-30 182157](https://github.com/user-attachments/assets/104a5a0f-c51d-4f59-b3b0-7404bd6b11ee)

**Comment by JosefNemec** [comment]
Your library files are corrupted.

Please attach `library\games.db` from Playnite's install folder.

**Comment by Ronsolo77** [comment]
Thank you. I'm very new at this. How do I perform such a task?

**Comment by JosefNemec** [comment]
- go to `library` folder
- find games.db file there
- upload it here (just drag and drop it to new comment)

You might need to zip it first if GitHub won't let you upload it as .db

**Comment by Ronsolo77** [comment]
the library folder is located where? on the Playnite site or the drive.

**Comment by JosefNemec** [comment]
In Playnite's install folder.

**Comment by Ronsolo77** [comment]
I found the library folder, but I don't see the games.db file. I can see a game folder if this is what you are referring to.

**Comment by JosefNemec** [comment]
No, it's `games.db` file, it's 100% in Playnite's install folder, under `library` folder.

`E:\Playnite\library\games.db`

**Comment by Ronsolo77** [comment]
I found it and you are right github is not liking that file format.  Can I use filezilla for the zip or what type of zip do you recommend?

**Comment by Ronsolo77** [comment]
Sorry 7Zip not filezilla.

**Comment by Ronsolo77** [comment]
[games.zip](https://github.com/user-attachments/files/16825836/games.zip)

**Comment by JosefNemec** [comment]
Here's fixed file: [games.zip](https://github.com/user-attachments/files/16825862/games.zip)

**Comment by Ronsolo77** [comment]
Cool. Thanks. What do I do from here?
Should I drag those to the same game folder and unzip them?

**Comment by JosefNemec** [comment]
You replace the original file you sent me with the one I attached.

**Comment by Ronsolo77** [comment]
Done. Most of the games play, but TMNT shredder revenge is giving an error. It was working, but now it crashes.

**Comment by Ronsolo77** [comment]
![image](https://github.com/user-attachments/assets/02274f3d-996c-4967-b5b1-e7c113008cd1)

**Comment by JosefNemec** [comment]
Game issue, nothing to do with Playnite.

**Comment by Ronsolo77** [comment]
Got it. Thank you.
