### ISSUE TITLE
Playnite not auto-updating libraries at startup anymore

### ISSUE THREAD

**Issue by ok-andy** [JosefNemec/Playnite#3815]
### Bug Description

It used to work fine. I have the "Update libraries" set to "on every startup" but Playnite no longer updates my libraries at startup

### Diagnostics ID

cee9aa0e-5890-4376-83ed-675c796e7a5a

### Screenshots

![image](https://github.com/user-attachments/assets/71c7e834-4c09-48fc-a5ef-26c162872897)

**Comment by JosefNemec** [comment]
It's because Playnite didn't detect any internet connection. Library update won't be executed in that case to prevent running update and just failing and throwing errors. Make sure your network works fine and that Playnite is not blocked by AV or FW.

> 03-09 20:43:12.804|WARN |MainViewModelBase:Startup library update disabled because of no internet connection.

**Comment by ok-andy** [comment]
I have internet though, I can manually update my library just fine.
