### ISSUE TITLE
Unspecified Error when importing games from Amazon Games

### ISSUE THREAD

**Issue by w-peter-schmidt** [JosefNemec/Playnite#3818]
### Bug Description

I recently added a few new games to my Amazon Games (AG) library (Titles below). Apparently the API is responding with a not further specified error message that the Playnite plugin cannot interpret (see log excerpt in attachments). I tried updating the library contents twice back to back so you can see that there's nothing further to it in the log file.
I checked my local installation of the AG launcher and it is up to date.
The last time the update seems to have worked (according to the log file) is at timestamp 05-09 15:06:49.274 (that seems to be dd-MM rather than MM-dd).
I also tried re-authenticating the library plugin.
Not sure if the issue is with my specific account / library is the cause or if this is something that happens to everybody. I couldn't find an existing issue on here regarding this problem. Sorry if it's there after all and I just missed it.

Games:
"Whispered Secrets: Everburning Candle - CE"
"Minabo – A Walk Through Life"
and "LEGO Indiana Jones: The Original Adventures"

[playnite application log excerpt 2024-09-07.log](https://github.com/user-attachments/files/16919458/playnite.application.log.excerpt.2024-09-07.log)

### To Reproduce

Run Update Amazon Games Library in Desktop client.

### Diagnostics ID

d3d318f3-7bfd-4bd6-b99b-5709357e53df

**Comment by CianH** [comment]
Looks like https://github.com/JosefNemec/PlayniteExtensions/issues/401

**Comment by w-peter-schmidt** [comment]
yes that seems to be the same issue. sorry. idk why i didn't find that.
