### ISSUE TITLE
Unique Classes for Child Windows

### ISSUE THREAD

**Issue by GhoulBoii** [JosefNemec/Playnite#3819]
### Bug Description

I utilise a tiling window manager called komorebi on windows. The issue I face is that the dialog boxes of playnite always get tiled and to stop this, I want to setup float rules to prevent just the dialog boxes from being tiled. However, when I open a dialog box, the windows don't have an unique class/exe id which I can match. Here is the output from ```komorebic state``` which shows the issue:

```
 "elements": [
  {
    "name": "",
    "containers": {
      "elements": [
        {
          "id": "W12ORcpQ4pGh1A8NMEADh",
          "windows": {
            "elements": [
              {
                "hwnd": 3408778,
                "title": "SystemChecker - Downloading data...",
                "exe": "Playnite.DesktopApp.exe",
                "class": "HwndWrapper[Playnite.DesktopApp.exe;;af4dce75-1489-4408-949e-ec76a758cd11]",
                "rect": {
                  "left": 6,
                  "top": 50,
                  "right": 400,
                  "bottom": 138
                }
              }
            ],
            "focused": 0
          }
        },
        {
          "id": "mvxWk0vrIhNO0sYPWLzyJ",
          "windows": {
            "elements": [
              {
                "hwnd": 328930,
                "title": "Playnite",
                "exe": "Playnite.DesktopApp.exe",
                "class": "HwndWrapper[Playnite.DesktopApp.exe;;61c3de0a-6f4e-4c75-906d-84ec1101f6a2]",
                "rect": {
                  "left": 724,
                  "top": 50,
                  "right": 710,
                  "bottom": 844
                }
              }
            ],
            "focused": 0
          }
        }
      ],
      "focused": 0
    },
    "monocle_container": null,
    "maximized_window": null,
    "floating_windows": [],
    "layout": {
      "Default": "VerticalStack"
    },
    "layout_rules": [],
    "layout_flip": null,
    "workspace_padding": 2,
```

The main window class is: ```"class": "HwndWrapper[Playnite.DesktopApp.exe;;61c3de0a-6f4e-4c75-906d-84ec1101f6a2]",```
while the dialog window class is: ```"class":"HwndWrapper[Playnite.DesktopApp.exe;;af4dce75-1489-4408-949e-ec76a758cd11]",```

### To Reproduce

1. Start komorebi
2. Open playnite
3.  use ```komorebic state``` to print the window class/exe
4.  See no differentiate the dialog boxes and main window

Note: komorebi is not required to see the window class/exe. You can use any app which can see these fields.

### Diagnostics ID

6753aa5d-ef7c-472a-869d-32d859cac85e

**Comment by JosefNemec** [comment]
Looks like this is not possible because of WPF (UI library we use) constructs native window container. We would have to use hacks to do it which would break theming from quickly looking into it.

https://stackoverflow.com/questions/18103738/wpf-and-hwnd-unique-name
