### ISSUE TITLE
Amazon Games Import Failing 

### ISSUE THREAD

**Issue by kckramer** [JosefNemec/Playnite#3820]
### Bug Description

1. On Launch or by demand (Update Game Library -> Amazon Games), try importing Amazon Games existing account library.
2. Receive notification of error importing games.

### To Reproduce

- Tried reconnecting account, re-authenticating.
- All other existing account integrations work fine and continue to work.
- No difference when launching in safe mode.
- Noticed new games needing to be imported aren't importing as well anymore via Amazon Games connection.

### Diagnostics ID

e1a5bc8d-80a1-4a7a-9635-46c043b0565b

### Screenshots

![image](https://github.com/user-attachments/assets/694c4bf7-5908-4d04-8010-bc87b817ffe0)

**Comment by CianH** [comment]
https://github.com/JosefNemec/PlayniteExtensions/issues/401
