### ISSUE TITLE
Not able to add .exe

### ISSUE THREAD

**Issue by Laurenz07** [JosefNemec/Playnite#3823]
### Bug Description

When i try to add an exe it says that something went wrong. if i try on a new install it works but as soon as i load my backup data even when i just select games and game media it doesnt work anymore. also isnt an issue with the theme

### To Reproduce

i have no clue how this happens but i can provide any necessary information

### Diagnostics ID

6e293519-4026-4bdc-be5e-24f6b14b1342

### Screenshots

![image](https://github.com/user-attachments/assets/04101618-f960-4558-bdfb-5831ad0ae252)

**Comment by JosefNemec** [comment]
Your library files are corrupted, please attach `library\games.db` from Playnite's install folder.

**Comment by Laurenz07** [comment]
[games.zip](https://github.com/user-attachments/files/17045748/games.zip)
couldnt upload without compressing

> Your library files are corrupted, please attach `library\games.db` from Playnite's install folder.

**Comment by JosefNemec** [comment]
Here's fixed file: [games.zip](https://github.com/user-attachments/files/17053919/games.zip)
