### ISSUE TITLE
Please add suyu emulator

### ISSUE THREAD

**Issue by henuoxi** [JosefNemec/Playnite#3824]
### Feature description

Hello, first of all, I am sorry, because the next feedback is translated by a translator, there may be some errors, first of all, why I want to add suyu emulator because the yuzu emulator has been closed by Nintendo, but now there may be people still using it.

**Comment by henuoxi** [comment]
So I hope to detect the Yuzu do not delete, and then the Suyu simulator is the descendant of Yuzu, so I hope that the future version of the update can add detection Suyu simulator to fix this bug, above is my feedback to you.

**Comment by henuoxi** [comment]
So I hope to detect Yuzu do not delete, and then the suyu simulator is the descendant of Yuzu, so I hope that the future version of the update can add detection of Suyu simulator, above is my feedback to you

**Comment by JosefNemec** [comment]
I'm not planning to add profiles for any Yuzu fork because of scuffed the entire ecosystem around Yuzu forks is. You can always make custom profile.
