### ISSUE TITLE
Video links under video tab in the theme

### ISSUE THREAD

**Issue by PeWa48** [JosefNemec/Playnite#3825]
### Feature description

I dont know if this must be a feature from playnite itself or a feature that must be implemented in the theme:
when the collection over the time grows and we download video files locally, the amount of used harddrive space grows also, currently by my own collection about ~14 GB.
As an alternative we can use the options under the addon videos to view the steam trailer, but we must go everytime in the addon for every game to view the trailers instead of the use of the tab video in the theme.
So, why not implement both in the videotab in the theme: an option to choose the local video file if i have it downloaded or i can choose a link to view the video ? 
In my opinion, in most cases it makes it unnessasary to download videofiles if i can use links instead under the tab video in the theme.
(By the way: why is it not possible to make the video bigger under the videotab ? This must also be implemented )
So, conclusion in one sentence :-)  : Implementation of the Addon Video with videolinks under the videotab  of the theme as a choice (idealically with one click) to avoid spacy local downloads of videofiles

**Comment by JosefNemec** [comment]
This is up to a theme and plugins you are using. Not relevant to built-in functionality.
