### ISSUE TITLE
Download media button stops showing images

### ISSUE THREAD

**Issue by Vezelltje** [JosefNemec/Playnite#3828]
### Bug Description

When i want to download media for my game i can download some pictures and then it stops downloading from Google

I can clear the cache, but that works for a couple of images and then the same issue reappears. When i wait more than a few hours, i can download a couple pictures again.

https://github.com/user-attachments/assets/46faefbb-58cb-4785-bfe2-9f125b42f29e

I have noticed, since i have installed Extra Metadata Downloader, that it's the same. Download some logo's and then, nothing...

### Diagnostics ID

7bc8f8e0-1d91-4922-9c6e-f2663dde951a

### Screenshots

![Scherm­afbeelding 2024-09-19 om 08 22 02](https://github.com/user-attachments/assets/7ad953e9-891e-486c-8362-ee7e7008058f)

**Comment by JosefNemec** [comment]
https://api.playnite.link/docs/manual/gettingStarted/helpAndTroubleshooting/troubleshooting.html#web-image-search-doesnt-work

You (your network) are being flagged as a bot, nothing we can do about it.
