### ISSUE TITLE
Better handling of game duplicates

### ISSUE THREAD

**Issue by stibbons01** [JosefNemec/Playnite#383]
Hi,

as I couldn't find a similiar request I would like to ask for a new filter that makes it possible to filter for duplicate games over all game libraries (GOG/STEAM/etc.).

Greetings
Marc

**Comment by JosefNemec** [comment]
Two things we should add to handle duplication better:
- view/filter to show current duplicates
- option to automatically hide newly imported games if they are already imported from different library

Ideally we would also have a system in place that would allow grouping of duplicate games from different libraries together, but that's currently not possible without major rework of the whole game library system, which would be done via #408.

**Comment by Scaledish** [comment]
@JosefNemec I think a good approach to this  like gog 2.0s.
https://imgur.com/a/1eckPfJ

**Comment by Xicloing** [comment]
Probably would be useful to let users set a preferred client for automated handling of duplicate games, e.g. :
- if available, always use Steam as main entry
- if available, always use DRM-free GOG games as main entry.

**Comment by shakeyourbunny** [comment]
Any plans to implement this? 

It does not need to be automated (as a first step), but I second that you may select a "main" library with priorities.

This would really condense my library (I usually buy games on Steam for playing and GOG for my legal backup copy).

Some sort of "Libraries - Main and priority ordering" dialog would be neat, where you could switch around your library priorities, like the meta source data selection dialog.

**Comment by JosefNemec** [comment]
Current plan is:
1) add option to automatically hide/ignore duplicates when importing new games (with library priorities)
2) some overview/management of current duplicates
3) option to completely ignore games during import to prevent duplicates from coming back if you don't want to just hide them but completely remove them+ (this will be in Playnite 8)

No ETA on 1) and 2).

**Comment by shakeyourbunny** [comment]
I didn't meant to ignore duplicates, but to merge the duplicates. What if I'd like to launch not the main library version, but the duplicate version?

**Comment by JosefNemec** [comment]
Merging won't be implemented any time soon because I would have to completely rework how the library is implemented. I may add it in far future, but it will be done via #408.

I also think that merging is not a priority right now, because I can't imagine situation where you would want to start game via Steam one time and via GOG another time anyway (like actually have them both installed and switch between them). There might be some edge cases where this would be useful, but the effort to implement merging is currently not worth it.

**Comment by HunterZ** [comment]
This is one of the features I've always felt was really missing from Playnite.

I have FTL on Epic, GOG, and Steam, and they all show up as completely separate entries in Playnite ("Faster Than Light" on Epic, "FTL: Advanced Edition" on GOG, "FTL: Faster Than Light" on Steam). In GOG Galaxy 2.0 they are consolidated into a single entry.

The point of merging is to slim down the list so that you're not having to mentally filter out duplicates, and to make it easier to find a game when you own it on multiple storefronts.

**Comment by gjgfuj** [comment]
the easiest way I can think of to make this as soon as possible is to just add the ability to link to another playnite game inside the links section. That is a very simple way to resolve it and I'm surprised that is entirely non-possible.

**Comment by shakeyourbunny** [comment]
If you do this linking, it would be neat, if there is an entry with the linked games in Detail view and Gallery View. This should be togglable.

**Comment by Flare576** [comment]
I'm excited to see this feature. I just spent a few hours with a game export from Playnite trying different techniques of "categorizing" games (e.g., "Avadon: The Black Fortress", "Avadon 2: The Corruption" and "Avadon 3: The Warborn" would all be categorized as *Avadon* games) and "Source" grouping (e.g., my output shows that I have "Avadon: The Black Fortress" on both Steam and Humble). It's far, far from perfect, though; things like "Assassin's Creed Brotherhood" and "Assassin's Creed Revelations" don't have a delimiter-driven way to determine a "base name". Likewise, games with slight variances in formatting don't match for Source combination.

I think if I invested the time to do some word-by-word comparisons, it could get better, but it'd likely end up messier ( like ending up with "Dungeon Defenders" and "Dungeon Souls" as *Dungeon* games).

But after playing with data for a bit, I got to thinking about starting at the UI/UX end instead. One thought was that the [Install] button could have a dropdown-style arrow for games with multiple sources (i.e., https://user-images.githubusercontent.com/851745/39771116-572d7bf4-52f1-11e8-85ee-cb44ddc8766b.png).

This could get messy when the game is already installed and is changed to a _Play_ button, but the "More" button could be leveraged with a "Sources" entry that would allow installing from a second location? Doing so would cause the "Play" button to have a dropdown as well. This gives some parity between the Play/Install buttons and keeps it simple for folks who only want to install from one place.

If you also added an item to the `Appearance -> Details View` to set a "Preferred Sources" (a sortable list?), MOST users wouldn't even need to worry about the drop-down.

The "More" -> "Sources" entry could be leveraged to "Remove" a game from a source, where the main-level "Remove (Delete)" would remove it from _all_ sources.

Sorry for the brain dump; ya'll are probably already way past the "suggestions" phase, but if I didn't get it out of my head I wouldn't stop thinking about it :) Thank you for such an amazing tool.

**Comment by Bluscream** [comment]
I like how GOG handles duplicates

**Comment by ehawman** [comment]
![image](https://user-images.githubusercontent.com/52979227/94452839-9951ac00-0175-11eb-8102-67c2afb4f80f.png)

This is the first page of my Playnite library. There are 5 duplicates (one of which is a triple). Just the first page. When a game is released for free on one service, the same usually happens for other services as well in short order.

I know you've said that this is a difficult thing to implement for little payoff, but even if the option had no automation, was 100% manually done, it would be worth it.

As others have said, GOG does their grouping/swapping well, but you could also do something in the general options menu where the linked services are ordered, and if you have duplicates the higher priority one becomes the default for that grouped game.

**Comment by darklinkpower** [comment]
You can use this extension to hide duplicates automatically.
[DuplicateHider - Hide Duplicate Game Copies](https://playnite.link/forum/thread-308.html)

**Comment by TehJumpingJawa** [comment]
Just want to highlight my use case, as it hasn't been explicitly mentioned so far.

I desire the ability to find titles for which I have multiple licenses, so I can play them co-op/MP with family members with whom I share my accounts.

There's also a complication that I don't think has been mentioned; the issue of differing versions of the same game.
e.g. 
vanilla, Enhanced, Gold, GotY, GotY Enhanced, Overkill, Complete Collection, etc etc.

No idea how you'd go about consolidating these, or if it's even a good idea to do so.
Still, even if they're not consolidated, an "include different versions" filter would be desirable in the use case outlined above.

**Comment by JosefNemec** [comment]
Do we still need this as built-in feature when there's this extension? https://playnite.link/forum/thread-308.html

**Comment by P3t3rU5** [comment]
Not sure if its related to this particular issue, but I got copies of the same game from the same platform in Playnite

![image](https://user-images.githubusercontent.com/1653159/108199371-d282bc80-7114-11eb-8b5c-08648a9b912a.png)

**Comment by JosefNemec** [comment]
> Not sure if its related to this particular issue, but I got copies of the same game from the same platform in Playnite

Nothing to do with this issue. It's #2204, fixed by #170.

**Comment by HunterZ** [comment]
> Do we still need this as built-in feature when there's this extension? https://playnite.link/forum/thread-308.html

Yes, because it just hides alternate versions based on user-specified priority. Would be much more ideal if the idea of owning the same game on multiple platforms was a first-class concept modeled by the program.

Here's an example of how GOG Galaxy presents this (note the icons on the right):
![image](https://user-images.githubusercontent.com/108939/108571918-0bae5e80-72c6-11eb-8373-52ecaf8ab516.png)

**Comment by darklinkpower** [comment]
@HunterZ as mentioned in this comment https://github.com/JosefNemec/Playnite/issues/383#issuecomment-577155707, linking that way can't be done without a heavy rework of how the Playnite library works. The solution mentioned in that comment would be to do the same the extension already does.

**Comment by GoverLabs** [comment]
How about to add a library icon to the game list? Just like at the additional game info in the full-screen mode. It doesn't solves the problem, but at least user will be able to differentiate versions without opening any additional windows.
Visibility of the icon can be optional, not to bother users who don't have duplicate games, or use the a plugin, mentioned above.

P.S. don't look at weirdly stretches images, looks like some issues with debug build.

![image](https://user-images.githubusercontent.com/37362815/108709872-f7fc3580-751b-11eb-8b5e-3bc60f6c309b.png)

**Comment by JosefNemec** [comment]
I'm closing this since this issue would basically implement the same functionality available in [this plugin](https://playnite.link/forum/thread-308.html).

Linking multiple game duplicates under one entry (like Galaxy does it) was never part of this issue and will be done separately via #408.

**Comment by monokrome** [comment]
@JosefNemec That plugin is buggy and doesn't work half the time

**Comment by Akryum** [comment]
I confirm that the plugin doesn't really work for part of the library

**Comment by a7x492** [comment]
Requesting this to be re-opened because the link above to "this plugin" is broken

**Comment by JosefNemec** [comment]
There's nothing to reopen, we already have open tracking issue for this #408
