### ISSUE TITLE
Add support for Sinclair ZX Spectrum games

### ISSUE THREAD

**Issue by Korb** [JosefNemec/Playnite#3836]
### Feature description

> Includes game **emulation** support

I read the quoted phrase above, and not finding a list of emulated platforms, I tried scanning local folders [1] with games in the following formats:

1. `.air` (RealSpec)
2. `.dck` (Warajevo)
3. `.dsk`
4. `.fdi`
5. `.hdf` (RealSpec and Fuse)
6. `.img`
7. `.mdr`
8. `.mgt`
9. `.pok` (SGD)
10. `.rzx`
11. `.slt`
12. `.sna`
13. `.szx` (Spectaculator)
14. `.tap`
15. `.trd`
16. `.tzx`
17. `.z80`

As far as I understand, Playnite does not provide built-in support for them. Perhaps it makes sense to directly indicate in README.md that emulation of platforms other than Windows is not available "out of the box", and is implemented in some other way. At least, in the application settings I did not see a tab called "Emulators" or something like that.

_Metadata for Speccy games can be obtained from [the World of Spectrum website](https://worldofspectrum.org/)._

[1] `Scan Automatically...` → `Select Games to Import` → `Scan Folders...`

**Comment by JosefNemec** [comment]
https://api.playnite.link/docs/manual/features/emulationSupport/emulationSupportOverview.html
