### ISSUE TITLE
Detecting duplicate copies of games (from different platforms)

### ISSUE THREAD

**Issue by Krzysztof23** [JosefNemec/Playnite#3839]
### Feature description

If technically possible, I would like to ask you to add the ability to scan games from libraries connected to applications and mark duplicate copies based on the title as duplicates and not include them in the summary of your games in the filtered section

**Comment by JosefNemec** [comment]
#408

**Comment by Jeshibu** [comment]
Until Playnite 11 releases, this plugin is very good and allows you to set priority criteria yourself: https://playnite.link/addons.html#felixkmh_DuplicateHider_Plugin
There's also this one which I haven't tried yet: https://playnite.link/addons.html#DuplicateFinder_d85c1809-6ab7-40c2-9434-af74feeae2d3
