### ISSUE TITLE
Issues switching themes

### ISSUE THREAD

**Issue by janforster** [JosefNemec/Playnite#384]
Hi Crow,

I am getting some strange behaviour when changing between themes:
- I cannot change the theme using the usual settings > appearance dialogue
- When I change the theme using the F8 window I get it "disabled", until I click somewhere outside of playnite

Demonstration: http://recordit.co/5QdKxBTiJ4

What do you think?

Cheers

**Comment by janforster** [comment]
On a second look I am not sure this is actually an issue, when restarting the app the theme switches OK and defaults back to the "settings > appearance" choice.

**Comment by JosefNemec** [comment]
The theme switching without app restart is kind of buggy (just switching profiles should work just fine), I'll look into it.

**Comment by JosefNemec** [comment]
Upon further investigation it seems there's nothing I can do about this. It looks to be WPF issue, specifically it highly depends on how that theme is implemented (what views must be reloaded).
