### ISSUE TITLE
Playnite Misdetects Install Status After Moving GoG Galaxy Content

### ISSUE THREAD

**Issue by LeeThompson** [JosefNemec/Playnite#3840]
### Bug Description

First, I'm going to say this doesn't happen 100% of the time, more about 80% of the time.

I got a new external SSD drive recently so I've been moving the more demanding games from my hard drive to the external SSD.  With Steam this is no problem for Playnite.    
   
With GoG Galaxy games Playnite no longer sees that they are installed.   The Galaxy client sees it just fine and can launch the game.   I've been working around it by overriding the install (and action) settings within Playnite but it would be better if Playnite was able to handle this better.    

The weird thing is out of the 10 games I moved yesterday, two did not have this issue.

I have noticed, that the shortcuts in the game's folder do *not* get updated by Galaxy.  However, as a test, I manually edited the shortcuts be the correct locations and Playnite still saw the game as not installed any longer.

### To Reproduce

1. Exit GoG Galaxy entirely
2. Move the games to the new drive
3. Launch GoG Galaxy 
4. For each game, use "Import Folder" to add them back, in a few seconds the "Play" button in Galaxy becomes available
5. In Playnite, run the update GoG Library

### Diagnostics ID

ef62d1ad-78c2-4a54-876c-c5d1364b7be2

**Comment by JosefNemec** [comment]
1) This is not handled by Playnite but by GOG plugin.
2) The install state is detected from registry keys that might not be correctly set depending on how a game was installed or imported to Galaxy. Using "Import Folder" is not enough, Galaxy sometimes doesn't create correct registry keys on folder import and repairing game install in Galaxy is needed to fix the issue. [This has been well known issue for long time now](https://github.com/JosefNemec/PlayniteExtensions/wiki/GOG-troubleshooting).

**Comment by LeeThompson** [comment]
Thanks for the info!
