### ISSUE TITLE
Playnite Window tiling feature

### ISSUE THREAD

**Issue by dearpowa** [JosefNemec/Playnite#3847]
### Bug Description

Playnite maximize button does not trigger Windows 11 tiling preset feature

### Diagnostics ID

37e133ca-0b4a-43b3-9bf1-1580f37b06d6

### Screenshots

https://github.com/user-attachments/assets/f8f84e6f-3e41-4e6d-8411-9d938ce2a07f

**Comment by JosefNemec** [comment]
#2629
