### ISSUE TITLE
Full Screen Mode Issues

### ISSUE THREAD

**Issue by chasimus** [JosefNemec/Playnite#3851]
### Bug Description

Hey guys, I'm running into issues with button press actions in the full screen mode. I use a DualShock 4 via Bluetooth running on DS4Windows v3.3.3. The two main issues I'm running into are: 1) When pressing X(A) on a game icon it doesn't open up the Details screen. It just doesn't do anything; and 2) when clicking on the menu button in the upper right, it does a rapid double click and selects the Random Game option, with no success in getting it to not do this. It prevents me from accessing the main menu completely.

### Diagnostics ID

3bdc2643-adf0-44bc-9910-2db2492f8c72

**Comment by JosefNemec** [comment]
https://api.playnite.link/docs/manual/gettingStarted/helpAndTroubleshooting/troubleshooting.html#controller-is-acting-weird
