### ISSUE TITLE
Library file corruption has been detected, Playnite will now shutdown.

### ISSUE THREAD

**Issue by SnipeAT** [JosefNemec/Playnite#3852]
### Bug Description

gives this error and then closes.  attached is a zip of all dbs as I've seen that be the first step in similar previous issues.
[dbs.zip](https://github.com/user-attachments/files/17368596/dbs.zip)

### Diagnostics ID

dac4a575-28a4-4d0d-a129-8add7a1b4862

### Screenshots

![image](https://github.com/user-attachments/assets/5c08fd48-fb32-4359-80b0-9456d56f5742)

**Comment by JosefNemec** [comment]
Where's diag. id?

**Comment by SnipeAT** [comment]
> Where's diag. id?

I didn't realize I could do this without having access to the about menu.  Let me try to generate one via the "crash dialog".

**Comment by SnipeAT** [comment]
i launched in safe mode and created a diagnostics pacakge: 

dac4a575-28a4-4d0d-a129-8add7a1b4862

**Comment by JosefNemec** [comment]
Fixed file: [games.zip](https://github.com/user-attachments/files/17369490/games.zip)

**Comment by SnipeAT** [comment]
thank you so much!  it works!
