### ISSUE TITLE
Conhost is not recognized as a command when scripting

### ISSUE THREAD

**Issue by Alfamari** [JosefNemec/Playnite#3856]
### Bug Description

When attempting to call conhost as a command in the scripts section it is not recognized as a command. Even when providing the full path `C:\WINDOWS\system32\conhost.exe`. Of course, I have it, not sure if it's even possible for windows to run without it. Running Get-Command outside of playnite shows it's there. Running the command `conhost sleep 2` outside of playnite works just fine. Just not when I try to test the script from within playnite. I also tried various methods of invocation `&`, `start-process`, and even `powershell -NoProfile -Command conhost sleep 2`. All of which work outside of playnite but fail inside of it.
Interestingly if I call it through powershell core: `pwsh -NoProfile -Command conhost sleep 2` it DOES work, and so far is the only solution outside of replacing conhost entirely with wt (windows terminal).

Other failed methods that work outside of playnite:
`cmd /c conhost sleep 2`
`& test.ps1` (Where test.ps1 contains `conhost sleep 2`)

Problem persists in safe mode.
I searched the docs, faqs, and issues for this but found no results.

### To Reproduce

1. Try to setup a script for a game that tries to call or invoke conhost without using pwsh core.
For example: `conhost sleep 2`
2. Click `Test script`.

### Diagnostics ID

d4724d3a-c2cd-47cf-91a4-4753a46fe27f

### Screenshots

Attempt (without specifying fullpath):
![Playnite DesktopApp_yNvrQba1oY](https://github.com/user-attachments/assets/8042e2d5-7635-422f-a8fa-a6281a22623f)

Error message (when specifying fullpath):
![Playnite DesktopApp_dCdyob0ADz](https://github.com/user-attachments/assets/74514fbc-416e-416c-922c-271e5237253f)

Error when attempting `Start-Process -FilePath C:\WINDOWS\system32\conhost.exe`:
`Can't find the file specified`
![Playnite DesktopApp_5tLWqT9vls](https://github.com/user-attachments/assets/5986da2c-c5b3-4358-bd48-10617b5c4569)

Error when attempting `cmd /c C:\WINDOWS\system32\conhost.exe sleep 2`:
![Playnite DesktopApp_t8rODVjBaq](https://github.com/user-attachments/assets/aa075216-d806-4d34-833c-3654362446f2)

Error when attempting `powershell -noprofile -command C:\WINDOWS\system32\conhost.exe sleep 2`:
![Playnite DesktopApp_hpuPxQQONs](https://github.com/user-attachments/assets/59707d54-069b-4898-bf75-2eb44e94998b)

Error when executing the command as a .ps1 script `& test.ps1`:
![Playnite DesktopApp_zaYy1rrJ0M](https://github.com/user-attachments/assets/60a8a862-0779-4dab-85a8-2521215069ba)

**Comment by JosefNemec** [comment]
Playnite is 32-bit process so it can't natively access 64 bit paths. Use `C:\WINDOWS\sysnative` instead of `C:\WINDOWS\system32`.

**Comment by JosefNemec** [comment]
Btw you'll get similar issue when trying to access 64 bit Program Files folder. I added troubleshooting paragraph about it to [scripting docs](https://api.playnite.link/docs/manual/features/scriptingSupport/helpAndTroubleshooting.html), for future reference.

**Comment by Alfamari** [comment]
Wow thanks, never knew about sysnative. Learning about it also taught me about syswow64 which I was previously curious about. Also explains why pwsh worked, cuz I have it in an (x86) folder, which I also didn't previously understand the difference. My god does Microsoft's naming convention for 32-bit/64-bit get confusing.
