### ISSUE TITLE
Open fullscreen mode on another monitor

### ISSUE THREAD

**Issue by gtrus21** [JosefNemec/Playnite#3858]
### Feature description

Add parameter "open fullscreen mode on another monitor" (and switch sound out device)

**Comment by JosefNemec** [comment]
We already have an option in the settings to change target display, so I'm not sure what this is about.

**Comment by gtrus21** [comment]
Please tell me where

**Comment by JosefNemec** [comment]
In the settings -> general -> target display

**Comment by gtrus21** [comment]
nothing
![image](https://github.com/user-attachments/assets/7cc87845-5f1f-4388-8172-babfd32d4d68)
