### ISSUE TITLE
Multiple Games a alot

### ISSUE THREAD

**Issue by Beninja1987** [JosefNemec/Playnite#3859]
### Feature description

When you open certain games on Steam, it gives you multiple choices to open it with DLC or in another Update, or just sometimes whole other games. a Function like this with customizability would be really great.

Lets say you have a game, and then you have its remake; you could put both games in one slot, and anytime you open the game, you can choose which you wanna play. insanely useful and helps clean up libraries 

### Screenshots

![image](https://github.com/user-attachments/assets/ba4d15a7-1ccd-4ddd-875f-4d7fc8a71e03)

**Comment by JosefNemec** [comment]
This is already support. Assign additional play actions to a game to get similar dialog in Playnite after starting a game.
