### ISSUE TITLE
Cannot enter spaces into game details that aren't the game description

### ISSUE THREAD

**Issue by DotsSalchow** [JosefNemec/Playnite#386]
This is my first time using Playnite, and I'm hoping that this is just a bug that snuck in with the latest update or something.
EDIT: I just noticed that it only lets me enter spaces after commas.
EDIT2: I found that entering a space in-between letters and strings works fine, but it won't let me enter spaces at the very end of a string if there's no comma present there.

**Comment by JosefNemec** [comment]
Released in 3.4
