### ISSUE TITLE
Automatic Metadata Import Issues

### ISSUE THREAD

**Issue by GoldenHindXXX** [JosefNemec/Playnite#3863]
### Bug Description

When I download the Metadata for an Individual Game, my sources are usually able to find the game and information for it. 

https://github.com/user-attachments/assets/ba49515c-eb8e-41b9-a05a-5675cb59772b

However when metadata is downloading automatically, some don't get recognized at all. Even though it will be recognized just fine if I was to do it on its own.

https://github.com/user-attachments/assets/d7b6c784-7ec1-430b-944d-25b12ee2d7d5

By extension of this issue I find is that at least for the Title, it doesn't change or get corrected to my Metadata Sources title, again, only if I use Metadata Automatic Import, even when the title is normalized for easier reading. Otherwise Importing Data Manually works fine.

![image](https://github.com/user-attachments/assets/3f55906f-297d-41db-a0f2-061231ed3f5a)
![image](https://github.com/user-attachments/assets/e6edb6bb-2993-4151-a1a2-908c9795d69f)

https://github.com/user-attachments/assets/be32e9e2-e29a-44c3-ac17-bf14a21b74b3

Both of these issues lead to information not being able to get pulled. 

It would make sense if the default title doesn't lead to anything being found, but multiple sources are able to tell which game it is. So I'm confused on how it's not able to get the complete metadata.
I don't know how Playnite downloads metadata automatically, but I would assume that the title and release date would be the priority to be able to determine which game (or version of a game) it is. And have those results kind of trickle down for the rest of the information pulled.

### To Reproduce

Import any game, the title doesn't change and automatic imports will not change the information of the game unless the title is pretty precise. Manual Imports work no problem.

### Diagnostics ID

32c8dedd-32ff-4090-9477-7fd49d39342a

**Comment by Jeshibu** [comment]
The top example is using MobyGames metadata plugin, which I make. The reason it's not automatically matching is that the names do not match. Disney epic mic vs Disney epic Mickey. It does account for things like : instead of - in a title and different editions, but I have explicitly only required it to match mostly exactly.

**Comment by JosefNemec** [comment]
Actual metadata fetching is done by individual metadata plugins, so any issues with metadata not being pulled are coming from these plugins, not from Playnite. You need to report this to devs of metadata plugins you are using.
