### ISSUE TITLE
Games in wrong order when using "last played" and "decending" 

### ISSUE THREAD

**Issue by dostillevi** [JosefNemec/Playnite#3866]
### Bug Description

I have my game list set to tiles, and I have the tiles ordered so that the most recently played games should appear first in the upper left. Instead, sometimes Playnite gets confused and moves recently played games further down the game list. This behavior isn't consistent. Usually restarting Playnite causes it to work correctly.

I have several game services connected to playnite, including Steam, Epic, EA, and Ubisoft.

### To Reproduce

Set games to tiles, and then set the order to "descending" and "last played". When clicking on a game to play it, the game will move into the middle of the game list instead of to the front.

### Diagnostics ID

f94bef44-6c5d-49e7-80d8-7632a667e2b9

### Screenshots

![image](https://github.com/user-attachments/assets/c34ad464-1d71-484b-86a6-9026011af292)

**Comment by JosefNemec** [comment]
Duplicate to #1995
