### ISSUE TITLE
Game title not match with pic

### ISSUE THREAD

**Issue by sictea** [JosefNemec/Playnite#3868]
### Bug Description

some games have different pic with a title of the game and t makes me  confused because it's different at all

### Diagnostics ID

7a316823-881e-4cb9-9156-9a056f88371e

**Comment by JosefNemec** [comment]
This depends on what metadata sources you are using, Playnite itself doesn't do any metadata download or matching. So you need to figure out which metadata source/plugin matched bad data and report it to its developer.
