### ISSUE TITLE
Controller menu issue

### ISSUE THREAD

**Issue by Siranooscome** [JosefNemec/Playnite#3869]
### Bug Description

When using the directional buttons or even the analog stick to cycle through the menu's on the main Playnite screen, it skips through two or three options making it almost impossible to use the controller on the home page.

-Using Dualsense PS5 controller

### To Reproduce

Simply use a controller to cycle through the options on the main screen.

### Diagnostics ID

00001

**Comment by JosefNemec** [comment]
https://api.playnite.link/docs/manual/gettingStarted/helpAndTroubleshooting/troubleshooting.html#controller-is-acting-weird
