### ISSUE TITLE
Unused localization strings

### ISSUE THREAD

**Issue by PhrozenByte** [JosefNemec/Playnite#387]
The following localization strings don't seem to be used anywhere:

https://github.com/JosefNemec/Playnite/blob/601ffe10c0d8590daea3fa793d34752e25d97195/source/PlayniteUI/Localization/english.xaml#L396

https://github.com/JosefNemec/Playnite/blob/601ffe10c0d8590daea3fa793d34752e25d97195/source/PlayniteUI/Localization/english.xaml#L297

And here's a small typo:

https://github.com/JosefNemec/Playnite/blob/d41ffd6a1b6dd87a03cd3e27da56b936aeeb264d/source/PlayniteUI/ViewModels/PlatformsViewModel.cs#L582

ref #346

**Comment by JosefNemec** [comment]
I'll leave `EmuLoadArgsPresetTooltip` there, because it will be used for feature that was temporarily removed.
