### ISSUE TITLE
Controller simulation keyboard

### ISSUE THREAD

**Issue by Itachi0833** [JosefNemec/Playnite#3870]
### Feature description

Hello, I hope to add a custom shortcut key for setting up a controller to simulate keyboard keys, so that I can exit the game because not all games have an exit button. Thank you

**Comment by JosefNemec** [comment]
https://api.playnite.link/docs/manual/gettingStarted/helpAndTroubleshooting/faq.html#how-can-i-close-a-game-or-emulator-with-a-controller

**Comment by JosefNemec** [comment]
#2715
