### ISSUE TITLE
Supported control types

### ISSUE THREAD

**Issue by MrDougCover** [JosefNemec/Playnite#3871]
### Feature description

First of all, excellent project, really very useful. But if there is something that would be interesting to add, it is the type of controller that the game is compatible with. For example, Spider-Man Remastered is compatible with Dualshock 4. It could have a section where it illustrates with the controller icon that it is compatible. Or even GTA V which is only compatible with Xbox controller... It would be a very useful tool!

**Comment by JosefNemec** [comment]
Problem with this is being able to source that information reliably for most of the games. My current stance on adding new game fields is that if we can't reliably populate it with the default metadata provider, IGDB, then the field most likely won't be added.

This would fall right under that condition, it's imo more fit to be added as an extension. Therefore closing.
