### ISSUE TITLE
EA game on Epic Games doesn't import

### ISSUE THREAD

**Issue by objecttothis** [JosefNemec/Playnite#3874]
### Bug Description

I purchased Mass Effect Legendary Edition which is an EA App required game. Then I opened Playnite and updated the Epic library, but the game was not imported.  I was not aware at the time there was a separate checkbox to include EA App Games, so I checked that box, then restarted playnite, epic games app and my computer and sync'd Epic again, but nothing I do is bringing Mass Effect Legendary Edition into Playnite. Just in case this was a user authentication, I reauthenticated Epic in playnite. The game is not installed and the EA App is not installed.  AFAIK playnite should be able to pull it in through the Epic API without having to install it.

### To Reproduce

Should be clear from the description

### Diagnostics ID

363520d5-9b45-45b5-a480-0f80d4b04b21

### Screenshots

![image](https://github.com/user-attachments/assets/c67fee83-37d2-468a-a3f6-dec9efb03012)
![image](https://github.com/user-attachments/assets/d8f4cc08-fbe9-4122-9305-155431a81d53)

**Comment by DRG2Boss** [comment]
Considering that the standalone EA integration is broken with no plans to fix, this should be reopened imo.
