### ISSUE TITLE
安装Playntie发生错误

### ISSUE THREAD

**Issue by Mist5673** [JosefNemec/Playnite#3878]
### Bug Description

 安装Playnite发生错误

### Diagnostics ID

无

### Screenshots

![屏幕截图 2024-12-02 192738](https://github.com/user-attachments/assets/b3796dcf-b14b-4b6a-8ba9-4562b5b30826)
![屏幕截图 2024-12-02 213639](https://github.com/user-attachments/assets/d7f49921-fa66-46ed-89b9-acbd0bc5b24a)

**Comment by JosefNemec** [comment]
https://api.playnite.link/docs/manual/gettingStarted/helpAndTroubleshooting/troubleshooting.html#general-network-issues
