### ISSUE TITLE
Uninstalled ITSELF.......!!!???

### ISSUE THREAD

**Issue by MrFIVEfourONE** [JosefNemec/Playnite#3885]
### Bug Description

windows 11 on Legion GO handheld brand new
Installed it.    .https://playnite.link/download/PlayniteInstaller.exe  
Updated it and installed some Libraries
Took it off the list to open during start up
Shut down pc
Next day its completely gone off pc as if I never hit the Install button on the playniteinstaller.exe the day prior and spent 4 hours using.......
I have little coding experience... Basically been under a rock for 3years

### Diagnostics ID

000

**Comment by JosefNemec** [comment]
There is no way Playnite could have uninstalled itself, there is no code in Playnite that could possibly do that. If Playnite really disappear from your PC, some other app had to do it.
