### ISSUE TITLE
Crashed while trying to update Metadata

### ISSUE THREAD

**Issue by Belgost** [JosefNemec/Playnite#3886]
### Bug Description

I was attempting to update metadata for some of my games, and now everytime I try to access the metadata editor, the app crashes.

### Diagnostics ID

c0575012-0a6f-4120-9635-39ac5d3eb2d8

**Comment by JosefNemec** [comment]
It's crashing in .NET framework on something related to text parsing/formatting. So probably some system or .NET corruption. Definitely not an issue on our side. Try these steps: <https://api.playnite.link/docs/manual/gettingStarted/helpAndTroubleshooting/troubleshooting.html#playnite-is-crashing>
