### ISSUE TITLE
Ignore UnityCrashHandler64.exe when launching a game

### ISSUE THREAD

**Issue by Eloren1** [JosefNemec/Playnite#3889]
### Feature description

Is there a way to ignore UnityCrashHandler64.exe when launching a game? 

I know that I can do [Edit - Actions - Remove UnityCrashHandler64.exe], but this is done individually for each game. 

I have 80% games in the library that have this crash handler, can you create a solution that ignores this exe file?

### Screenshots

![{F12CF568-8BF2-4A18-83DA-3C56A52F913E}](https://github.com/user-attachments/assets/7e0e61f1-afcc-41df-932b-ec0f24492890)

**Comment by JosefNemec** [comment]
How did you import this game? I don't think there a feature in Playnite that would import a game like this.

**Comment by Eloren1** [comment]
> How did you import this game? I don't think there a feature in Playnite that would import a game like this.

Using this method, I have all my games in D:\Games folder 

https://www.reddit.com/r/playnite/comments/1d895y0/comment/l7i9rrn/

**Comment by JosefNemec** [comment]
It's an issue with the extension, it needs to ignore that file on import.
