### ISSUE TITLE
Time tracking for games start via Lunchers 

### ISSUE THREAD

**Issue by GhostVPN1** [JosefNemec/Playnite#3893]
### Feature description

I have recent a problem to track flowing games from HoVerse and another gacha games.
I use all tracking method and no one works when i add the game directly to playnite - the solution for me was to do it via Epic Luncher.

**Comment by JosefNemec** [comment]
I'm 99% positive that folder tracking works with this. Make sure you have tracking folder set correctly to a folder where actual game exe is. Also try increasing initial tracking delay.

https://api.playnite.link/docs/manual/library/games/gameActions.html#tracking-mode

**Comment by GhostVPN1** [comment]
Ty for fast response, indeed, I reinstall the games and that all start works with the folder track
