### ISSUE TITLE
Exclude files/folders from regular auto-scan using the same system as emulator auto-scan

### ISSUE THREAD

**Issue by NoxNecro** [JosefNemec/Playnite#3894]
### Feature description

The emulator auto-scan has a feature where you can [exclude certain files/folders](https://api.playnite.link/docs/manual/features/emulationSupport/addingEmulatedGames.html#excluding-files-and-folders-from-import-completely) from being added by adding them to the exclusion list. The best part of this feature is the ability to match names using regex. I feel like adding a feature like this to the regular auto-scan would be incredibly useful.

**Comment by JosefNemec** [comment]
#1044
