### ISSUE TITLE
DRM-free metadata plugin/extension

### ISSUE THREAD

**Issue by 2018robert** [JosefNemec/Playnite#3895]
### Feature description

This plugin can use metadata to tag games as DRM free. 
Maintained lists for various stores can be found here: https://www.pcgamingwiki.com/wiki/List_of_DRM-free_games 
also https://www.pcgamingwiki.com/wiki/The_big_list_of_DRM-free_games_on_Steam

**Comment by JosefNemec** [comment]
This repository is for things related to Playnite itself only, not for any extension proposals, if this is what you are asking for. I recommend asking on reddit or Discord if you want somebody to make custom extension for you.
