### ISSUE TITLE
New categories to differentiate games procured via a subscription service

### ISSUE THREAD

**Issue by loficat** [JosefNemec/Playnite#3898]
### Feature description

Feature request:  It would be helpful (and a core function) to add new library options to differentiate games procured via a subscription service (e.g., Xbox Gamepass, Playstation Plus).  Games obtained in this manner would have their own "library" entry.  The new categories would allow users to identify which games are "owned"* when shopping or reviewing their libraries.

* which is sadly a nebulous concept today

**Comment by JosefNemec** [comment]
#2123
