### ISSUE TITLE
SuccessStory and Played time not sync

### ISSUE THREAD

**Issue by VGGaming1** [JosefNemec/Playnite#3899]
### Bug Description

So i'm new to this app, and did find every solution for this problems but it not working for me. English is not my main language so sorry for it. 
1. Played time not sync. (I'll put images too)

- For some reason, Playnite don't sync my played time on steam, but the other games from steam (example: DMC 5) had it but not install. I checked some game that doesn't install and it does show the time I played, but not the game I cureently install. Is this a bug or it suppose to be like it? And how do I fix it, do I need any plug-ins for it? (Images 1 and 2)

2. SuccessStory not working for installed games
- I tried everything like Download Data, Connect Steam and Epic account as Private and non-Private. Connect to Exophase.

- It's seem like it work for the games that is not install, but I have to click one by one to refresh the data. I'll put images of both launcher with some games I got fixed. 

- Image 3 and 4 is from Epic, that I just refresh the data for it, Vampire time played is sync, but not the achievements. And this is same with steam but the games is installed is not updating, except Wallpaper Engine. 

### Diagnostics ID

eadf3f35-2a6e-4f70-bfca-453de3c8c96c

### Screenshots

![Screenshot (69)](https://github.com/user-attachments/assets/d2b8253a-a92a-4e6a-aa3d-13ae2748967b)
![Screenshot (70)](https://github.com/user-attachments/assets/78adda0c-70cf-4cdc-baa2-744dad2e1410)
![Screenshot (71)](https://github.com/user-attachments/assets/af7918cc-aa16-484c-a53e-b166443d80cd)
![Screenshot (72)](https://github.com/user-attachments/assets/ac4cf39d-2b85-4d68-a929-e392a33c43c2)

**Comment by JosefNemec** [comment]
1) As issue template says, issues related to specific extensions should be reported in their repository.

2) For play time see https://api.playnite.link/docs/manual/gettingStarted/configuringPlaynite.html#importing-playtime-from-third-party-libraries-and-services You may also need to provide your own API key depending on privacy settings set on your account.

3) For SuccessStory, report it to its dev, this repository has nothing to do with that project.
