### ISSUE TITLE
Import steam categories

### ISSUE THREAD

**Issue by janforster** [JosefNemec/Playnite#39]
Hi,

Firstly, thanks a lot for this software, I was looking for something like this for years now :) .

**For the feature itself:**
It would be really useful if the import from steam took into consideration also categories which the user created there. I have a library of 500 categorised games on steam and it took me good 5 hours to recreate the same structure in Playnite, therefore I think other users might find this useful.

Cheers,
Jan

**Comment by JosefNemec** [comment]
Good idea, sadly there's no official API, which would provide information about categories on your Steam account. However that didn't stop me in past... :)

**Comment by JosefNemec** [comment]
Released in 0.94

**Comment by Korb** [comment]
@janforster, @JosefNemec, what do you mean by `Categories`? Is that what the Steam client calls `Collections`?

![2024-09-26_09-26-48](https://github.com/user-attachments/assets/17ed2ded-8aac-45aa-b35b-9818e0576323)
