### ISSUE TITLE
This NEEDS to be available on other platforms.

### ISSUE THREAD

**Issue by BlastBlaster17** [JosefNemec/Playnite#3901]
### Feature description

It's simple, really. This should be available on platforms such as Linux and macOS with Wine integration if we want to stay true to the application's name. The one barrier to this is that it's written in .NET. However, .NET is supposed to be cross-platform, so it shouldn't be that much of an issue to rewrite the parts of the code reliant on Windows to work with Unix dependencies as well.

**Comment by Jeshibu** [comment]
The barrier isn't .NET, it's that WPF (the UI library Playnite uses) isn't compatible outside of Windows. Rest assured that porting that, or switching to a comparable library, is not as simple as you think it is.

It is planned in the long term, though. If you want to keep track of this, subscribe to this issue: #59

**Comment by JosefNemec** [comment]
#59

**Comment by JosefNemec** [comment]
> so it shouldn't be that much of an issue to rewrite the parts of the code reliant on Windows to work with Unix dependencies as well

People need to stop confidently commenting on stuff they know nothing about. Modern .NET is open source and cross platform but not all parts of old (Windows only) .NET Framework have been ported to new .NET and made cross platform, critically the UI framework we are using. See #59
