### ISSUE TITLE
MessageBox buttons localization

### ISSUE THREAD

**Issue by FrantisekNemec** [JosefNemec/Playnite#4]
MessageBox buttons are localized for system language despite english title and message.

![messagebox_buttons](https://cloud.githubusercontent.com/assets/18503961/24427929/01508934-140d-11e7-835d-fcece79abb09.png)

**Comment by JosefNemec** [comment]
I'm not sure this is worth fixing. There are translations planned for future, which should fix language inconsistency in these dialogs.
