### ISSUE TITLE
Persistence of collapsed categories

### ISSUE THREAD

**Issue by janforster** [JosefNemec/Playnite#40]
Hi,

Right now it is possible to collapse categories, but if the user changes a view the categories expand back. Specifically, the categories expand when:

- The filters are switched
- The application restarts
- A search is performed

I would find it more convenient if the application would be able to remember the state of collapse/expand and always return to it (unless the user makes a change).

Cheers,
Jan

**Comment by JosefNemec** [comment]
Released in 0.93
