### ISSUE TITLE
Battle.Net sometimes had an OK states even when not logged in.

### ISSUE THREAD

**Issue by operamaniac** [JosefNemec/Playnite#400]
When I'm checking the 3.3 updates with some localization, I noticed that the Battle.Net authenticate state is  in "OK" state even though I don't have any Battle.Net account logged up / authenticated with Playnite. This is still persist in other language (tested with English and Indonesia) and it still there in 3.4 update.

Now I recently found out that it sometimes revert back to "Authentication Required" and vice versa.
![image](https://user-images.githubusercontent.com/21957465/34626433-31f6f72e-f28f-11e7-9f84-b65b48e43ea0.png)

**Comment by JosefNemec** [comment]
Fixed in 3.6
