### ISSUE TITLE
Add Changelog Tab in "About Playnite" Window

### ISSUE THREAD

**Issue by operamaniac** [JosefNemec/Playnite#401]
I noticed that I can't read the changelog between updates (except when updating). It would be nice to have a changelog tab to keep track the updates with fixed issue and the contributor for that fix.

**Comment by JosefNemec** [comment]
What do you mean by "can't read the changelog between updates"? The change log doesn't appear on update dialog?

**Comment by operamaniac** [comment]
@JosefNemec No, It appear just fine. I mean we can add a changelog tab to "About Playnite Window" to see the changelog, not just when updating. Sorry if it's confuse you.

**Comment by JosefNemec** [comment]
No problem, for now you can view changelog [here](https://github.com/JosefNemec/Playnite/releases). Adding it into app itself shouldn't be a problem.

**Comment by JosefNemec** [comment]
I'm closing this since we won't be able to include the whole changelog directly because of how I plan to present them in future. I will probably add a button that will open web page linking to changelog page.
