### ISSUE TITLE
Reboots have cover art from original game

### ISSUE THREAD

**Issue by DSPAUL** [JosefNemec/Playnite#404]
Some games display the wrong cover art of a game with the same name, this is mostly a problem with rebooted games because they often have the same name as the very first game in the franchise. I my case, the 2013 Tomb Raider reboot has all the right metadata including the 2013 releasedate except for the cover, which is from the 1996 Tomb Raider. The same happend with the 2013 Shadow Warrior, who got the cover from the 1997 Shadow Warrior.

**Comment by JosefNemec** [comment]
Fixed in 4.40
