### ISSUE TITLE
Selecting multiple games in Covers view

### ISSUE THREAD

**Issue by Ianuarius** [JosefNemec/Playnite#406]
I believe there's currently no way to select multiple games in the Covers view. This relates to my problem with switching cover images with Download Metadata tool.

If I want to see all the games that have a wrong cover image, I need to use the Covers view, since the cover images are not displayed in the info of the games (and this would require me clicking on every game anyway).

As a sidenote, maybe the game info page could have the cover image anyway somewhere, such as underneath the infobox with genre, develper, etc. It's not super important, but the cover image gives you a sense of what game you're currently viewing faster than just reading the title. Nice to have.

**Comment by Continous** [comment]
The Aurora skin displays the Cover Art in the manner you're asking.

**Comment by JosefNemec** [comment]
Oops we did it in #553
