### ISSUE TITLE
Different quick-launch modes

### ISSUE THREAD

**Issue by Evene174** [JosefNemec/Playnite#410]
I think it would be cool to have different modes for running games
For example:
**Quick Resume Mode**(I think it's better to make it available for shutdown in the settings):
Notification when you start Playnite with a suggestion to continue the last game (everything else is blured and the user can continue the game by pressing one button or close it and go to the program) 
![last game](https://user-images.githubusercontent.com/26068083/34639338-0b72447a-f300-11e7-959f-3df9a8de8ea8.jpg)
(Yes, I know, I'm not an designer :D, but something like this)
Also remembering the last game may be as part https://github.com/JosefNemec/Playnite/issues/147
If you decide to save the last state of program before it will be close

There may be something like a littles 'wheel of fortune' buttons in top of program with two modes:
![-1](https://user-images.githubusercontent.com/26068083/34639354-6791a278-f300-11e7-9978-7ea80e24d0f5.jpg)

**Three-Games Mode**:
Also notification with blured where the user is offered three random games, and he _must_ choose and play any of them to continue

**Random Game Mode**: same https://github.com/JosefNemec/Playnite/issues/121
It starts one random game from list.

I think this modes should greatly helps when the user does not know what to play, or wants to quickly launch the game in which he played last

**Comment by Continous** [comment]
I don't think forcing a user into doing something is appropriate for your proposed 'Three-Games Mode'. Maybe have it work like #121 but instead of launching, it prompts players with 3 games to choose.

**Comment by JosefNemec** [comment]
Yeah, I don't think this makes much sense to add. We will display options if users sets multiple Play action for game (like Steam does) via different issue.
