### ISSUE TITLE
"Steam Friends" button is delayed

### ISSUE THREAD

**Issue by pen-mb** [JosefNemec/Playnite#416]
Steam Friends button takes quite a long time (about 20 seconds) to react after being clicked on, which makes it practically useless. I've tried this with Steam minimized, maximized, friends panel being closed and open.

This is on Windows 10, 1709 (16299.192) with latest, non-beta Steam and Playnite clients.

Happy to provide any other information as well.

**Comment by JosefNemec** [comment]
Does it take 20 seconds when you use `WinKey-R` shortcut and run `steam://open/friends` url? The only thing Playnite does to open the list is opening that URL, so I have no idea why it would take so long to open.

**Comment by pen-mb** [comment]
Yes, it does. So is it not a Playnite issue?

**Comment by JosefNemec** [comment]
No it's not Playnite issue then. Not sure what might be causing it, try googling it out. It's a first time I hear about problem like this.
