### ISSUE TITLE
Plugins - custom metadata providers

### ISSUE THREAD

**Issue by JosefNemec** [JosefNemec/Playnite#417]
Ability to add custom metadata providers. Needed for #255 #224 #214 #183 #160

**Comment by ArtexJay** [comment]
can't wait for this plugin to come in XD

**Comment by janforster** [comment]
@JosefNemec: what is the relation of this issue and #523? It seems quite similar. I am asking mostly because I would really love to see #112 implemented and this issue (#417) is listed as a blocker for it.

**Comment by JosefNemec** [comment]
They are not related anymore, library plugins can provide their own way of providing metadata, but that's just for games coming from that plugin. This issue is to add support for metadata plugins that could be used on any game. This no longer blocks #112

**Comment by JosefNemec** [comment]
Done in 6.0
