### ISSUE TITLE
Playnite doesn't resolve {InstallDir} when creating desktop shortcuts

### ISSUE THREAD

**Issue by PhrozenByte** [JosefNemec/Playnite#419]
This is likely the reason why Playnite creates desktop shortcuts with Windows' "empty file" icon (because `{InstallDir}\SomeGame.exe` is no valid path for Windows) rather than using the actually configured icon. Playnite should resolve placeholders when creating desktop shortcuts.

Also see #354

**Comment by JosefNemec** [comment]
Fixed in 3.6
