### ISSUE TITLE
Announce Played Game Over Social Media

### ISSUE THREAD

**Issue by Warrender** [JosefNemec/Playnite#420]
One of the neater features of Raptr (RIP) that I used extensively was linking my account to social media so that it would send an announcement what game I was currently playing.  Just wondering how hard it would be to implement such a feature to announce to twitter, facebook, etc. for Playnite.

**Comment by JosefNemec** [comment]
You can now write a [custom extension](https://playnite.link/docs/) to do that, not sure if this will get into Playnite as standard feature any time soon.

**Comment by JosefNemec** [comment]
I'm closing this since I don't like this being built-in feature (because of how many social networks there are) and extensions API is mature enough to allow implementation of plugins for specific networks.
