### ISSUE TITLE
Emulation Import Wizard: improvements

### ISSUE THREAD

**Issue by By6r9** [JosefNemec/Playnite#423]
* selecting more than one entry (or range) with control and shift
* changing platform for that selection 
* sorting by clicking column headers
* extension column 
* maybe select/unselect all button?
* there is one unused (?) column visible after maximizing window

**Comment by epeternally** [comment]
Some form of mass select is definitely needed. MAME sets can be thousands of games long, dealing with them is pretty unwieldy right now.

**Comment by By6r9** [comment]
I don't think it's worth a separate issue, so i'll note that:
* selecting more than one entry (or range) with control and shift
* sorting by clicking column headers
also applies to "Import Installed or from Folder"

**Comment by kernaldave** [comment]
Would be nice to have a drop box to select a platform and apply it to all games being imported.  Right now if I want to change my Game boy Advanced, from Game Boy, I would have to do every one individually.

**Comment by JosefNemec** [comment]
Should be done after/with #653

**Comment by JosefNemec** [comment]
Done in devel9.
