### ISSUE TITLE
Release year

### ISSUE THREAD

**Issue by Tarmo-R** [JosefNemec/Playnite#427]
Is it possible to add feature that i can choose between release date (dd/mm/yy) and release year? Because there are many games that have no known release date and only a known release year.

**Comment by Lithium1988** [comment]
How about a workourund? give games with a releas yea just the 01.01.xxxx and you'r good to go ;)

**Comment by doublah** [comment]
Assuming 01/01/YYYY would be a useful option.

**Comment by JosefNemec** [comment]
I'm not sure about this. Having separate fields for release date and release year seems redundant to me and you can already filter games by just specifying the year.

**Comment by Tarmo-R** [comment]
Why separate fields? Example if checkbox checked, you can use datepicker and if not checked, you can enter date or year manually using  your own date formats (yyyy, yyyy-mm-dd, mm-dd-yy or whatever).

**Comment by JosefNemec** [comment]
Had a look at this and we can easily add option to filter/group/sort by release year based on the release date just by using the year data, we would not need to add any new fields or game settings.

**Comment by JosefNemec** [comment]
Done in 5.0
