### ISSUE TITLE
Dutch Translation

### ISSUE THREAD

**Issue by wilco375** [JosefNemec/Playnite#429]
Translated the application to Dutch: 

[Playnite Dutch Translation.zip](https://github.com/JosefNemec/Playnite/files/1636939/Playnite.Dutch.Translation.zip)

**Comment by JosefNemec** [comment]
Added in 3.6

**Comment by wilco375** [comment]
Here's the updated Dutch translation. I also added the LOC prefix to all the keys.
[Playnite Dutch Translation 20180426.zip](https://github.com/JosefNemec/Playnite/files/1952146/Playnite.Dutch.Translation.20180426.zip)

**Comment by wilco375** [comment]
Updated for 4.2
[Playnite.Dutch.Translation.20180512.zip](https://github.com/JosefNemec/Playnite/files/1997390/Playnite.Dutch.Translation.20180512.zip)

**Comment by JosefNemec** [comment]
Localization have been completely move to Crowdin: https://crowdin.com/project/playnite

Please join the project there to submit updates.
