### ISSUE TITLE
Add thegamesdb.net metadata provider

### ISSUE THREAD

**Issue by JosefNemec** [JosefNemec/Playnite#43]
http://wiki.thegamesdb.net/index.php/API_Introduction

**Comment by JanPokorny** [comment]
I second this. They seem to have a rather large collection of game artwork (mainly banners). At the moment, most of the games in my library are missing the background artwork, so this would be a nice addition.

Also, I believe that displaying the wide banners in a top-to-bottom list view would create a very visually appealing library view.

**Comment by JosefNemec** [comment]
I'm closing this because the API seems to be no longer available. Playnite 6 added an option to add custom metadata sources via plugins so if anybody wants to add this via some scrapper then feel free to create a plugin for it.

**Comment by doublah** [comment]
Legacy API is down, but appears to be a new API at https://api.thegamesdb.net/
