### ISSUE TITLE
Playnite forums

### ISSUE THREAD

**Issue by JosefNemec** [JosefNemec/Playnite#430]
Currently we only have reddit as sort of permanent discussion place, which we cannot really customize and tailor more to Playnite needs. 

Requirements:
- Can be self deployed.
- Supports sub-forums or categories.
- Can integrate with #593. We must be able to use the same user accounts.
- Supports mobile devices, forum must be usable on mobile screens.
- Is actively being developed and supported.

Nice to have:
- Single sign on using Google, Facebook etc.
- Ideally PHP+MySQL so I can use current hosting, but this is not requirement.

Super nice to have
- Has a wiki or can integrate with a separate wiki instance (use the same accounts). I would ideally like to use it to replace GitHub wiki so people can contribute more easily to it.

It doesn't have to be free or open source, the quality and support for our requirements are more important.

**Comment by Continous** [comment]
If we do, would you mind allowing users to sign in using something like Google or Facebook?

**Comment by JosefNemec** [comment]
I hope so, I personally don't like creating new accounts for every forum.

**Comment by Continous** [comment]
I agree, and many platforms absolutely do not need to know my password.

**Comment by JosefNemec** [comment]
After some research I will probably use [MyBB](https://mybb.com/).

**Comment by Magi1053** [comment]
I highly recommend using Discourse on Docker

**Comment by PopeRigby** [comment]
I would also recommend Discourse. The UI is great on both desktop and mobile. It's also open source, like Playnite.

**Comment by JosefNemec** [comment]
Done
