### ISSUE TITLE
Game update notifications

### ISSUE THREAD

**Issue by stefhol** [JosefNemec/Playnite#432]
With many Game launcher its really a mess to keep the stuff updated
I researched a bit
The simplest solution would be a RSS feed grabber for patchnote sites like Factorio Cs or Dota.

Furthermore u could use SteamDB.info and Blizztrack.com to get Updates for all Steam and Blizzard games.
SteamDb supports a RSS feed to get the info and Blizztrack provides a TwitterBot and discordBot or contact them, about a direct solution

**Comment by JosefNemec** [comment]
Probably the same as #227, the implementation would also use RSS to get the data. I'm currently for just providing general ability to set RSS feeds for a game, no matter if it's a news or update source.

**Comment by JosefNemec** [comment]
This is practically impossible to implement for most libraries we have plugins for right now. At least not without a lot of reverse engendering effort that could go towards more usable features.
