### ISSUE TITLE
Handle merging of existing and newly added metadata better

### ISSUE THREAD

**Issue by DennoCoil** [JosefNemec/Playnite#435]
I originally wrote something about adding Store availability and seeing if DRM-Free versions of games were available from the PC Gaming Wiki's Availability section of a game's article, then I thought adding PC Gaming Wiki to Links would be more beneficial in the short term.

I noticed this because it didn't seem to add certain Links inconsistently.  I then noticed that Links weren't getting added, they were getting overwritten.  They should be appended to populate the Links list properly.

I also think there's a larger issue with how the UI is designed. Like you can't see the metadata before and possibly after at the same time. Where if you uncheck the box, it shows the original data, and with the check, shows the new data.

**Comment by DennoCoil** [comment]
I think I found the problem.

The metadata from one scrape overrides the other in the Links section instead of appending.  This is true for the other pieces of metadata where stuff is overwritten instead of appended.

I think there's a larger issue with how the UI is designed.  Like you can't see the metadata before and possibly after at the same time.  Where if you uncheck the box, it shows the original data, and with the check, shows the new data.

**Comment by JosefNemec** [comment]
There's a checkbox as an option to replace or keep links when downloading metadata, but I agree that it's not ideal. Also you are right that option to compare old and new data is needed.

**Comment by DennoCoil** [comment]
I know that's there, but using it now I noticed 2 other problems.

- It doesn't save what was selected the last time it was used.
- It doesn't have Wikipedia as an optional place to scrape data from.  (It has IGDB and "Official Store" which doesn't work except for modernish PC titles.)

To correct this might need a slight overhaul of that specific menu in addition to the scraping problem.  Because once you start adding in more than 1 site from some plugin or a future update adds in more places, it'll exponentially explode with all the combinations and become incredibly unwieldy to you and the users.

I think the solution is that instead of having "(Place)>(Place)" for each source menu, each of the Import locations can have Sources that allow the possibility to add\remove multiple (Place) switches in decreasing order of importance and save that to memory\database.

Not sure how complicated that can be, but it's mostly a UI redesign and can be easy if the scraping and UI were abstract from each other.  I tried reading the code, but I'm only familiar with mostly Python and some C++.

**Comment by DennoCoil** [comment]
The Wikipedia thing really should be added.  I looked up the Warhawk entry on IGDB and Wikipedia.  There was only a tiny stub on the IGDB that doesn't even give a year.  The Wikipedia one is actually decent and has plenty of information.  Gah!!  That game was one of the best early PS1 games and one of the few flight sims for a mainstream audience, and there was no entry?!  Yeah, diversifying the list, redesigning the UI, and tweaking how it handles metadata should be important.

**Comment by JosefNemec** [comment]
Scrapping more data from Wikipedia is completely different issue, lets keep this focused on original issue. Please open new one if you want to see more data to be scrapped from wiki.

Also I highly recommend contributing to IGDB if you find game that lacks some information. Getting info from IGDB is way easier then scrapping data from Wikipedia. IGDB provides API that's purpose built for gaming related usage and apps like Playnite.

**Comment by DennoCoil** [comment]
Gotcha.

**Comment by JosefNemec** [comment]
I renamed the issue because exactly the same UX problem affects other fields as well, not just links.

**Comment by JosefNemec** [comment]
Will be done via #1668
