### ISSUE TITLE
Swedish Translation 

### ISSUE THREAD

**Issue by MrCraigen** [JosefNemec/Playnite#436]
Translated the application to Swedish:

[Playnite Swedish Translation.zip](https://github.com/JosefNemec/Playnite/files/1646492/Playnite.Swedish.Translation.zip)

**Comment by JosefNemec** [comment]
Added in 3.6

**Comment by JosefNemec** [comment]
Localization have been completely move to Crowdin: https://crowdin.com/project/playnite

Please join the project there to submit updates.
