### ISSUE TITLE
Non-games imported from Steam: "appid 218" and "SteamVR"

### ISSUE THREAD

**Issue by JanPokorny** [JosefNemec/Playnite#438]
The Steam import automatically imports two "games": "appid 218" (some sort of Source engine demo) and "SteamVR" (isn't actually installed, prompts to install when clicked, steam app id 250820). I think that these should not be imported, as they are just some default Steam junk.

**Comment by JosefNemec** [comment]
Nothing I can do about it. There's no way how to automatically differentiate between these tools and regular games (currently used API doesn't provide that information). You have to simply hide those in your library.

**Comment by JanPokorny** [comment]
If those "games" are present for everyone (and I suspect that at least SteamVR is), it might be worth it adding exceptions for the app ids.
