### ISSUE TITLE
Outdated Paypal link?

### ISSUE THREAD

**Issue by Akmanar** [JosefNemec/Playnite#441]
Hi,

I have loved Playnite and I would like to make a Paypal donation but the link seems to be outdated/not working at the moment.

https://playnite.link/paypal.me/playnite

Had you notice this? Isn´t there a way to donate through Paypal anymore?

Regards,

Akmanar

**Comment by JosefNemec** [comment]
The link was broken on the website, I fixed it. The correct one is https://www.paypal.me/playnite

Thanks for considering contributing to the project!
