### ISSUE TITLE
Allow and implement usage of variables in metadata and editing/theming.

### ISSUE THREAD

**Issue by Continous** [JosefNemec/Playnite#442]
Currently all information must be added in _manually_. This is fine for a baseline, but for large libraries it becomes tedious, and thus it would be sensible for Playnite to implement a metadata-driven variable system like Foobar2000 has, and you can see [here](http://wiki.hydrogenaud.io/index.php?title=Foobar2000:Title_Formatting_Reference#Track_info_fields_and_functions).

**Comment by JosefNemec** [comment]
Kind of related to #358

**Comment by JosefNemec** [comment]
I don't think this is needed anymore. You can access any game field via standard XAML binding in themes. This would add the same functionality just with different syntax, which is unnecessary work.
