### ISSUE TITLE
PCGamingWiki (PCGW) Integration

### ISSUE THREAD

**Issue by doublah** [JosefNemec/Playnite#444]
https://github.com/PCGamingWiki/api

https://pcgamingwiki.com/wiki/Home

**Comment by JosefNemec** [comment]
What would the integration do? We already add PC Gaming Wiki URL to every automatically imported game. What else should this integration do?

**Comment by JosefNemec** [comment]
I'm closing this for now since there's no additional info about how the integration would work. If you can provide additional information then feel free to reopen this.

**Comment by Bluscream** [comment]
it can provide things like the used engine, what kinds of controllers are supported, and so much more!
