### ISSUE TITLE
ModDB integration

### ISSUE THREAD

**Issue by Continous** [JosefNemec/Playnite#445]
Having at least links to these platforms would be very nice. Even better would be having in-app browsers for them.

**Comment by JosefNemec** [comment]
Workshop link is already added if the game supports it.

**Comment by JosefNemec** [comment]
Can you provide some use cases of how would the ModDB integration work?

**Comment by JosefNemec** [comment]
I'm closing this since there's was no additional information provided by original reporter. General modding support will be considered in #367 and #458.
