### ISSUE TITLE
Italian localization for Playnite

### ISSUE THREAD

**Issue by StarFang208** [JosefNemec/Playnite#446]
Working on italian transaltion, I'll finish it within a week.

**Comment by StarFang208** [comment]
Sorry for my delay, here the localization file;
[Playnite Italian Translation.zip](https://github.com/JosefNemec/Playnite/files/1705634/Playnite.Italian.Translation.zip)

**Comment by StarFang208** [comment]
I have updated the translation for Playnite 4.30 .
[Playnite.Italian.Translation.zip](https://github.com/JosefNemec/Playnite/files/2121885/Playnite.Italian.Translation.zip)

**Comment by StarFang208** [comment]
Updated the translation for PLaynite 4.4:
[Playnite.Italian.Translation.4.4.zip](https://github.com/JosefNemec/Playnite/files/2193141/Playnite.Italian.Translation.4.4.zip)

**Comment by Askancy** [comment]
Change Estenzioni with Estensioni

**Comment by StarFang208** [comment]
Thanks for the info.
Now it should be fixed.
[Playnite.Italian.Translation.4.4.zip](https://github.com/JosefNemec/Playnite/files/2279810/Playnite.Italian.Translation.4.4.zip)

**Comment by StarFang208** [comment]
Updated the translation for Playnite 4.5 #385
[Playnite.Italian.Translation.4.5.zip](https://github.com/JosefNemec/Playnite/files/2359032/Playnite.Italian.Translation.4.5.zip)


Add this into the program this time, please.

**Comment by Axaf** [comment]
@StarFang208 Please update to latest version (4.7) and thanks for the Translation!

**Comment by StarFang208** [comment]
I did at #794

**Comment by mirh** [comment]
Can be closed I guess?
726686323319fc1c9ac8d8ed4673208df860eca1

**Comment by StarFang208** [comment]
@mirh Yes, I translated the new lines.

**Comment by StarFang208** [comment]
ref #385 (comment)
[italian.zip](https://github.com/JosefNemec/Playnite/files/2655826/italian.zip)

**Comment by StarFang208** [comment]
Update italian translation for version 4.70 #385 
[PlayniteItalian.zip](https://github.com/JosefNemec/Playnite/files/2819916/PlayniteItalian.zip)

**Comment by StarFang208** [comment]
Update for version 4.73   #385 
[PlayniteItalian.zip](https://github.com/JosefNemec/Playnite/files/2869978/PlayniteItalian.zip)

**Comment by JosefNemec** [comment]
Localization have been completely move to Crowdin: https://crowdin.com/project/playnite

Please join the project there to submit updates.
