### ISSUE TITLE
Is there a way to access the database without the Playnite GUI?

### ISSUE THREAD

**Issue by Akmanar** [JosefNemec/Playnite#447]
Hi,

This is not really an issue but I have been creating a nice Playnite database of local/split screen games and I ran into a small problem.

I have been reading and searching a lot to find all the local/couch/split screen games and been adding them to my Playnite database and my numbers don´t add up.
According to my notes I should have 122 games and it seems I only added 120 to my database. Now its really hard to check wich ones are missing and I was wondering if there is a way to print out the list of games that I have added to the databse?

Maybe opening the file in a database engine or any other way to see or query the contents to be able to list my games?

Thanks in advance for reading! :)

Regards,

Akmanar

**Comment by JosefNemec** [comment]
First make sure that you don't have some filter enabled, that could be why some games are not being displayed. If the filter panel is not visible then you can open it via `V` button next to the `...` button.

Right now there's no option in Playnite that would allow you to export raw data (4.0 will add it), but you can sort of do it via one of these tools:

* [LiteDbExplorer](https://github.com/JosefNemec/LiteDbExplorer) and check `games` collection
* [LiteDB's shell](https://github.com/mbdavid/LiteDB/releases) and query all games via commands:
```
open <path_to_db_file>
db.games.select Name
```

Database location can be found in `Settings` menu.

**Comment by Akmanar** [comment]
Thank you so much! This was just what I was looking for :)
