### ISSUE TITLE
Support for RTL Languages 

### ISSUE THREAD

**Issue by boudrar** [JosefNemec/Playnite#448]
Is it possible to add support for Right-To-Left languages (Persian, Hebrew and Arabic).

Using RTL localizations without changing the layout of the UI is as very bad UX.

**Comment by JosefNemec** [comment]
Adding high complexity tag. We can currently simply switch application flow to RTL, but not all controls work with it properly, for example game description is upside down:

![image](https://user-images.githubusercontent.com/3874087/35432615-e66b5fc8-0280-11e8-930f-142fb975fc76.png)

**Comment by Continous** [comment]
> game description is upside.

What? Why and how did that happen. Maybe if issue #397 is fixed, the game description will be fixed.

**Comment by JosefNemec** [comment]
Closing, was done via #1523
