### ISSUE TITLE
App crashes when "Integrate with GOG Galaxy" is checked

### ISSUE THREAD

**Issue by schouffy** [JosefNemec/Playnite#449]
Hi,
This is what i did :
- Start the app, importing from Steam only
- Once library is loaded, go to Tools > Settings
- Add GOG, leave galaxy checked, authenticate, click Save
- App crashes
- When it reloads, go to the settings, uncheck galaxy, Save
- Reload list, it works
- Go to settings, check galaxy, save
- App crashes again.

**Comment by JosefNemec** [comment]
Can you go to `About` menu and create diagnostics package for me? Thank you

**Comment by schouffy** [comment]
Here you go.
Please note that i tried again right now and don't seem to have the issue anymore.
Great app BTW, thanks a ton.
[playnite-issue449.zip](https://github.com/JosefNemec/Playnite/files/1668735/playnite-issue449.zip)

**Comment by JosefNemec** [comment]
The logs from diag. package doesn't show any crash related to GOG. Do you use portable version by any chance? And if so, did you install this https://www.microsoft.com/en-us/download/details.aspx?id=40784

**Comment by schouffy** [comment]
I first tried the portable version and had crashes after the wizards. This issue was with the installer version.
Sorry i can't help more, i don't have the issue anymore :/
I will try again the portable version, just to be sure.

**Comment by JosefNemec** [comment]
Thanks for the info, I will close this for now. If you find a way how to reproduce this on demand then feel free to reopen this issue.
