### ISSUE TITLE
Change emulator for many of roms with one click

### ISSUE THREAD

**Issue by Lithium1988** [JosefNemec/Playnite#452]
Is there a way to change the emulator for many roms at once?
I mean, i want to change for example the emulator from retroarch to epsxe... Now i have 100 PSX Isos, is there a way to mark all games and put a new emulator to tham?
Cause i deleted a Emulator and now i must change the emulator to a hundret of roms/isos... so it would be nice if we could change the emulator with "one click".

Thx for any advice

**Comment by JosefNemec** [comment]
No it's currently not possible, it will be implemented via issue #274
