### ISSUE TITLE
Image caching option

### ISSUE THREAD

**Issue by JosefNemec** [JosefNemec/Playnite#454]
Scrolling down large list of games can be slow in case user has slow hard drive or generally access to game database file is slow. It's due to game image files (icons and covers) being loaded as they are scrolled into view and released when they leave the view (to decrease memory usage). The problem is that the data are not cached and scrolling to same game/image causes another request to database.

This would introduce cache that would reuse already loaded resources and should make scrolling more smooth (together with already available async loading option). Cache should be configurable since it will increase memory usage, both option to enable/disable and the size of cache.

**Comment by Continous** [comment]
Would it be possible to change what is cached as well? For example, if I want to cache all images except cover images, would that be possible?

**Comment by shakeyourbunny** [comment]
It would be cool if the database directory not only contains the database itself, but in subfolders cached images for background / cover / icons etc for easy access.

Perhaps as a configuration option enable / disable?

**Comment by JosefNemec** [comment]
@shakeyourbunny I think that's completely different issue. If you want to have game media stored in separate folders and not in database file then please open new issue for it.

**Comment by JosefNemec** [comment]
Closing since caching has been added in one of the 4.x versions (can't remember which one).
