### ISSUE TITLE
Change default installation location to %localappdata%

### ISSUE THREAD

**Issue by JosefNemec** [JosefNemec/Playnite#455]
%localappdata% doesn't require elevated rights to write to, which should solve some rare access issues (since Playnite itself doesn't require elevated rights).

**Comment by Continous** [comment]
Any reason you weren't before?

**Comment by JosefNemec** [comment]
Released in 4.0

**Comment by Anutrix** [comment]
What about adding opposite support for those who need it?
The default localappdata installation means all users won't be able to run it. Each user on a machine would need install separately.
Maybe we can add option for user to choose System-Wide(with admin access) or Single User installation?
