### ISSUE TITLE
Problems with Uplay and Battle.net

### ISSUE THREAD

**Issue by cristi1990an** [JosefNemec/Playnite#456]
Please use search first to see if the issue is already opened. Thank you
1. Even though I have Uplay installed and have games purchased on it, they won't show up in my Playnite library
2. I keep getting a "Failed to download library, user not logged in" message. I've tried to log in and it works fine, but then it instantly logs me out again.

**Comment by JosefNemec** [comment]
Only **installed** Uplay games are currently being imported, if the game is not installed it won't be imported automatically. Support for uninstalled games is being tracked in #196

Battle.net login issue is tracked via #234
