### ISSUE TITLE
Playnite 3.6 doesn't start

### ISSUE THREAD

**Issue by carlosuh91** [JosefNemec/Playnite#457]
The playnite application shows an error at startup. It used to work fine days ago but now this is happening.
I attached the diag package..
[playnite_diag.zip](https://github.com/JosefNemec/Playnite/files/1678644/playnite_diag.zip)

**Comment by JosefNemec** [comment]
Looks like some files are damaged and cannot be loaded. Can you try manual reinstall to see if it helps?

**Comment by carlosuh91** [comment]
No problem.. it was a corrupted file from windows. (Never trust chkdsk).
Thanks anyways and keep the work!
