### ISSUE TITLE
Native recognition of popular community modding tools maybe?

### ISSUE THREAD

**Issue by cristi1990an** [JosefNemec/Playnite#458]
I'm using things like Nexus Mod Manager, Skyrim LOOT, Skyrim Mod Combiner, Mass Effect Mod Manager, ME ALOT Installer, GTA 5 Mod Manager etc all the time since they're the kind of modding tools that you usually keep around even after you're done modding but none of them have been recognized automatically. Since Playnite also supports emulators I was wondering if you're playing on supporting these kind of tools too.

**Comment by JosefNemec** [comment]
We can probably do it once #197 is implemented.

**Comment by JosefNemec** [comment]
Closing is #197 is done already.
