### ISSUE TITLE
Ability to import UWP games

### ISSUE THREAD

**Issue by JosefNemec** [JosefNemec/Playnite#46]
list of installed packages: Get-AppxPackage
package info: Get-AppxPackageManifest
starting app:  start shell:AppsFolder\{FamillyId}!{ApplicationId}

**Comment by qtv** [comment]
My current solution - use https://github.com/BrianLima/UWPHook to add UWP games to steam, create shortcut for that game, go into properties of shortcut, copy steam:// link, add as Installed Game to Playnite.

**Comment by JosefNemec** [comment]
Released in 1.0

**Comment by XJIOP** [comment]
not working

![Аннотация 2019-09-30 162432](https://user-images.githubusercontent.com/1385503/65887850-e81c0880-e39e-11e9-822c-96728f9bfc7b.png)
![Аннотация 2019-09-30 162504](https://user-images.githubusercontent.com/1385503/65887849-e81c0880-e39e-11e9-94fd-8b3cc34b4953.png)
