### ISSUE TITLE
The portable version crashes when it tries to access the games.db

### ISSUE THREAD

**Issue by GuyXY** [JosefNemec/Playnite#461]
The Portable version of Playnite crashes when it tries to access the %appdata%\Playnite\games.db file.
Neither the games.db file nor the Playnite folder under %appdata% existed.

After I created the Playnite folder manually, it worked fine.

It seems like the installer would create the Playnite folder and the portable version just assumes that the folder therefore has to exist, when it in fact doesn't.

**Comment by JosefNemec** [comment]
Installer doesn't create %appdata%\Playnite folder, that's always created by Playnite itself. There might be some access rights issues depending on what user starts it. I'll check it out.

**Comment by JosefNemec** [comment]
Released in 4.0
