### ISSUE TITLE
Getting "Failed to download GOG library" message even though in settings it says that I'm logged in.

### ISSUE THREAD

**Issue by cristi1990an** [JosefNemec/Playnite#462]
Please use search first to see if the issue is already opened. Thank you

**Comment by JosefNemec** [comment]
Can you go to "About" menu and create diagnostics package for me? Thanks

**Comment by cristi1990an** [comment]
[Diag. pack.zip](https://github.com/JosefNemec/Playnite/files/1698569/Diag.pack.zip)

**Comment by cristi1990an** [comment]
Though when I created this I wasn't getting the message. Should I send another one when I'm also getting the message? Sometimes I get it, sometimes I don't.

**Comment by JosefNemec** [comment]
No you don't have to send another one. It's really weird that settings says that you are logged in, can you try to relog via settings menu to see if it fixes the issue?

**Comment by cristi1990an** [comment]
I already tried. Re-logged in GOG but it didn't fix the issue. I'll try one more time now though.

**Comment by cristi1990an** [comment]
I haven't been getting the message lately. I assume it's fixed? Or it was just one of those bugs that go away on their own?

**Comment by JosefNemec** [comment]
No idea, maybe some temporary issue on GOG's side.

**Comment by JosefNemec** [comment]
Closing, if you encounter this again then feel free to reopen this with diag package.
