### ISSUE TITLE
Automatic background image download

### ISSUE THREAD

**Issue by Ccry11** [JosefNemec/Playnite#463]
Hi,
using the modern theme I can't see the background image when I select a game.
I have tried to download metadata multiple times but the background image for all my games is not shown.
Is the background image downloaded automatically or the user must provide the url/path for the image?
Thank you.

**UPDATE**: I have imported games from my Steam account instead of  selecting the path. Now the background is visible but it would be awesome to be able to select a background image from IGDB

**Comment by JosefNemec** [comment]
IGDB doesn't provide background images (I don't count the blurry header image), and since IGDB is the only 3rd part metadata provider, there's nothing I can do about it.
