### ISSUE TITLE
[GUI] Collapsed categories expand back after setting a game's category

### ISSUE THREAD

**Issue by Auliyaa** [JosefNemec/Playnite#464]
Preconditions:
- Have at least 2 game categories configured
- Group your games by category

Steps to reproduce:
1- Collapse a category in the UI.
2- Right click a game and set its category.

All categories, even the collapsed ones, are expanded back. This gets especially frustrating when having to categorize multiple games in a row if those are way down the category list.

**Comment by JosefNemec** [comment]
Duplicate to #319
