### ISSUE TITLE
[GUI] Add play time to a game's details panel.

### ISSUE THREAD

**Issue by Auliyaa** [JosefNemec/Playnite#465]
It would be nice to have the **played time** indicator when the original game platform (Steam/UPlay) can provide it.

Such an information could be added to the details panel of the currently selected game:

![playtime](https://user-images.githubusercontent.com/6253590/35782718-c2f88e0c-09fc-11e8-8469-0c7c7cd43759.png)

**Comment by MattyJacques** [comment]
This is the same as #120 which is currently planned for 4.0

**Comment by JosefNemec** [comment]
Duplicate to #120
