### ISSUE TITLE
Crash when opening link without http

### ISSUE THREAD

**Issue by cristi1990an** [JosefNemec/Playnite#468]
The link is this: www.nexusmods.com/masseffect3/mods/373/?

I've added this modding tool to my Playnite as a custom game but when I click the link it gives me this crash error:

[log.txt](https://github.com/JosefNemec/Playnite/files/1707823/log.txt)

Also the diag. pack: 

[Diag pack.zip](https://github.com/JosefNemec/Playnite/files/1707832/Diag.pack.zip)

**Comment by JosefNemec** [comment]
You must currently also specify `http` part of the url.

**Comment by cristi1990an** [comment]
Thank you!

**Comment by JosefNemec** [comment]
Released in 4.0
