### ISSUE TITLE
Deduplicate games in games list

### ISSUE THREAD

**Issue by shakeyourbunny** [JosefNemec/Playnite#471]
I own some (erh, many) games both on Steam and GOG. Would it be possible to merge the duplicate entries into one?

It would also be neat for games on multiple (emulated) platforms to be merged into one single entry. On launch it should be asked which version will be started, perhaps with a default setting and timeout.

![duplicated_games](https://user-images.githubusercontent.com/5352403/36065379-25081d32-0e9a-11e8-8bff-0bf71e45c3d0.PNG)

**Comment by JosefNemec** [comment]
Duplicate to #408
