### ISSUE TITLE
Support for Humble Bundle games library

### ISSUE THREAD

**Issue by shakeyourbunny** [JosefNemec/Playnite#472]
It would be neat if you can support for the Humble Bundle Games Library.

Though there is not an official api, but the online library is built atop some json based one. After authentication, you can easily sift all purchases from the account and build a games list.

Perhaps it is easier to implement this, if you examine the python-based downloader from https://github.com/talonius/hb-downloader :)

**Comment by JosefNemec** [comment]
Duplicate to #112
