### ISSUE TITLE
Add seperators when Category is selected while browsing the Covers viewport

### ISSUE THREAD

**Issue by DennoCoil** [JosefNemec/Playnite#475]
Not a big problem, but it would be nice to have a generic separator\horizontal line like there is in the List and Details viewports for the Cover viewport when Category is selected.  As it is now, games are still separated by Category in the Covers view like it should, but they flow into each other as if there was nothing there.  For example, South Park: The Stick of Truth from the Action RPG Category is right next The 7th Guest from the Adventure Category with no delineation.

**Comment by JosefNemec** [comment]
Same as #170
