### ISSUE TITLE
Make grouping case insensitive

### ISSUE THREAD

**Issue by DennoCoil** [JosefNemec/Playnite#476]
There's a thing where you can have multiple Categories that are spelled the same, but based around capitalization, they count as different or the same category due to a bug in the logic.

For example, I had the game BulletStorm in the "First Person Shooter" category... I also had it set to the "First person Shooter" category too.  Notice the capitalization in the word "person".  This resulted in BulletStorm being listed twice in the First Person Shooter category.

**Comment by JosefNemec** [comment]
Done in 5.0
