### ISSUE TITLE
Security: Values used for Process.Launch() in Game.cs should be checked before use

### ISSUE THREAD

**Issue by ShaneZlaros** [JosefNemec/Playnite#479]
See https://dotnet-security-guard.github.io/SG0001.htm

There are some values, that are used for Process.Launch() in Games.cs without being checked first.

This creates a possible target for code injection.

E.g. for Steam the variable ProviderId is used in ```Process.Start(@"steam://install/" + ProviderId)```.
The value of ProviderId has been fetched over an unsecure http connection from PlayniteServices. An attacker hijacking this connection can alter the value of ProviderId and inject harmful code to be executed by Process.Launch(). 
Another possible attack is a compromised or purposefully malicious PlayniteServices endpoint distributing harmful code injections to all connected clients.

This should be fixed by checking the variables before using them in Process.Launch(), see link above.

**Comment by JosefNemec** [comment]
I don't just take arguments from cmdline, only game id record from DB is taken. So the attacker would have to modify the database first. And if he has access that's give him ability to modify database file then what's the point of running executable via Playnite anyway.

**Comment by JosefNemec** [comment]
Closing for now per my previous comment. If you find some other possible security issues related to shortcut execution then feel free to reopen this.
