### ISSUE TITLE
GOG login window does not automatically have focus

### ISSUE THREAD

**Issue by ShaneZlaros** [JosefNemec/Playnite#484]
The GOG login window does not automatically have focus, which can be confusing as the text cursor is blinking in the input field but keyboard input won't go to it.

See https://github.com/Shanezlar/Playnite/commit/d0f6ee837d16586072b982d4930f17c82d387e13 for a potential fix.

**Comment by JosefNemec** [comment]
This is not just GOG login, it affects all views using CEFSharp control.

**Comment by JosefNemec** [comment]
Fixed in 4.0
