### ISSUE TITLE
Playnite Backup

### ISSUE THREAD

**Issue by MattGTX** [JosefNemec/Playnite#485]
Hello guys, Im kinda of a noob in some aspects 😄 I am creating this issue to ask how can I backup all the modifications I made? Because adding custom descriptions, backgrounds, covers for each game took me some time and I dont want to lose it. Thanks!

**Comment by JosefNemec** [comment]
By default all library information is stored in `%appdata%\playnite\games.db` file. Specific path is visible in settings menu.

**Comment by MattGTX** [comment]
Thanks JosefNemec
