### ISSUE TITLE
View Import Results

### ISSUE THREAD

**Issue by Continous** [JosefNemec/Playnite#486]
Being able to review import results before applying changes could prevent issues like file corruption/errors to other third party programs or sources (IE, if my Steam files are corrupted) from indirectly infecting Playnite. It would also easily allow duplicates to be filtered out, (IE, I have a non-origin and origin version of a game).

Furthermore, if I use certain genres in one third-party app, but not in Playnite, it would allow me to notice this ahead of time. (For example, in Steam I use the format (Genre/Year) Adventure/1997)

**Comment by JosefNemec** [comment]
Are you talking about automatic import when Playnite adds games from supported providers or manual import from "Add installed games" menu? Because I'm not sure what you mean by "indirectly infecting Playnite" if we talk about 3rd party sources.

**Comment by Continous** [comment]
For 3rd party services such as Steam, some people will use Steam's genres as categories, instead of genres, and this can cause issues when importing into Playnite.

**Comment by JosefNemec** [comment]
We might need some mockups of how this would work, I'm having issues visualizing this in practice.

**Comment by JosefNemec** [comment]
I'm closing this since there was no response to my request.
