### ISSUE TITLE
Force quit 3rd party client upon game quit

### ISSUE THREAD

**Issue by molnizzle** [JosefNemec/Playnite#487]
This would be useful for clients that don't offer the option, like the Epic Games client. When I finish a session of Fortnite, it would be great if the Epic Games client could automatically force quit  (instead of just minimize to the system tray). Origin gives you this option, but I believe that is the only one.

**Comment by Continous** [comment]
I don't know if this is necessary, possible (would likely require elevated privileges), or something that should be done through anything but a plugin.

**Comment by JosefNemec** [comment]
I'm not sure about this, we would have to find a way how to gracefully close the client (simply shutting down the client's process might cause issues).

**Comment by JosefNemec** [comment]
I think this could be solved by #113, you would have to set it on per game basis, but we would not have to hardcode it for every provider as separate option. Let me know if your agree.

**Comment by molnizzle** [comment]
Per game would be perfectly fine, but would #113 be able to perform actions upon _close_ as well? That would be optimal.

**Comment by JosefNemec** [comment]
Yes, you'll be able to set actions before the game starts and when it stops running. I'm closing this and the support will be done via #113.
