### ISSUE TITLE
Config background image blurriness on a per-game basis

### ISSUE THREAD

**Issue by PhrozenByte** [JosefNemec/Playnite#488]
See @RubeensVinicius suggestion he cancelled later:

> A slider to make all the background images blurry and/or darker. If the image is too detailed, it can be hard to read the text sometimes.

It's IMO very reasonable to allow users to blurry/darken images *on a per-game basis*, because you usually don't use images from a single source (e.g. Steam background images are already blurry, "normal" screenshots are not). However, the user should be able to change the transparency of a theme-controlled overlay only (to limit complexity), making the image more or less blurry and more or less dark by fading to a theme-specific color (might be black or a usually dark color).

ref #393 #349

**Comment by JosefNemec** [comment]
I'm not sure about this, at least if we talk about per game setting. IMHO it would be better to do this via something like #358 and handle it on the theme level.

**Comment by PhrozenByte** [comment]
The problem is that the desired bluriness of a background image *primarily* depends on the background image itself, and just secondary on the theme. Just compare the following two background images, the first one taken from the Steam database (i.e. it was processed by Steam already), the other one was taken manually (i.e. the "raw" screenshot):

![page_bg_generated_v6b](https://user-images.githubusercontent.com/920356/37355256-9d910078-26e3-11e8-80b8-2ac34dc34ff6.jpg)

![ss_5723ddcec6da4d9697f73882fab90e6cec99a8ad](https://user-images.githubusercontent.com/920356/37355264-a0362ace-26e3-11e8-919b-c391dbdd9be6.jpg)

Sure, this is a extreme example, but consider the following: Some games are usually pretty bright (like Age of Empires), some are usually pretty dark (like Doom 3).

![ss_4ef531d962d08f1c60746cac733d6ff8415e6778](https://user-images.githubusercontent.com/920356/37355937-2d93e02c-26e5-11e8-937e-972e551a020a.jpg)

How could a theme possibly know how much it has to darken the image, and how blurry it should become? This information must be stored together with the image (i.e. it must be part of the image's meta data).

Naturally the theme still must have at least *some* (but not exclusive) control over the bluriness. That's the reason why I've suggested a theme-controlled overlay. The then user just decides how transparent this overlay should be. For Age of Empires II one would choose a high opacity, making the image more blurry and darker. For Doom 3 one would use a low opacity, because the image already is pretty dark. For a background image directly taken from the Steam database one would set the opacity to `0` (i.e. no alteration at all).

**Comment by JosefNemec** [comment]
If we add the option you propose then we are solving this problem on wrong place. Adding option to blur original image on per game basis not depending on theme or other stuff adds too much complexity for something that only affects backgrounds. You should make sure that the original image is already blurred, that's the most efficient and IMHO the right way to do it. There are apps that will add image effect in bulk for multiple files and you are doing it only once.

It just doesn't make sense to me why we should add some image manipulation for backgrounds other then the stuff what themes can do globally.

**Comment by PhrozenByte** [comment]
If the final decision is that Playnite doesn't alter a background image's appearance on a per-image basis, I'd rather say that all images shouldn't be altered *at all* (we're now talking about "best practices for background images", right?) - because this would require you to alter background images in a theme-specific way, and if you wish to use a different theme, you might have to alter all images again. Steam e.g. darkens background images using a dark blue - but what if a theme's main color is not blue, but green? The background images won't match the theme's color scheme.

Thus Playnite's "best practice for background images" should IMHO rather be to always use "raw" background images and leave the whole image manipulation up to the theme. You won't get a perfect result, but at least it doesn't place the burden of image manipulation on the user.

**Comment by JosefNemec** [comment]
That's what Playnite does now and what it should do in future. Don't alter the image and leave any "changes" to themes (darkening or blurring for example).

I haven't look, but I think that Steam store API only provides altered background. Where did you get that original image? I have no problem using the original ones for more consistency with other providers.

**Comment by PhrozenByte** [comment]
The original image was part of the game's screenshot gallery in the Steam Store. I guess Playnite could simply use the first image in the `screenshots` array as default background image. See http://store.steampowered.com/api/appdetails/?appids=221380

**Comment by JosefNemec** [comment]
I've added option in 4.0 to use screenshots instead of store backgrounds (for Steam games). As I said in previous comments, any additional blurring, darkening or any image alteration has to be done to source image manually.
