### ISSUE TITLE
Ability to download/install games from cloud

### ISSUE THREAD

**Issue by outsider7a** [JosefNemec/Playnite#489]
For example, suppose i backup my games installers to a cloud service (e.g. gdrive, dropbox, etc). Then i could link Playnite with my cloud service and set the game installer path url in the game settings. Then in the game view, instead of showing "Play" it would say "Download". Clicking on this will download the game from the cloud service and install it. It could also have an option when the installer is a zipped file instead of an executable, decompress it instead of installing it and prompt the user to select the exe file to run the game.

**Comment by JosefNemec** [comment]
Duplicate to #478
