### ISSUE TITLE
Twitch.tv client integration

### ISSUE THREAD

**Issue by JosefNemec** [JosefNemec/Playnite#496]

**Comment by samirm** [comment]
would love to help out with this

**Comment by JosefNemec** [comment]
@samirm You can start by documenting how to detect installed/uninstalled games and how to start/install them properly. Implementation itself should be done after #523 is completed (unless overwhelming amount of people want this really bad), because I don't want to hard code other library provider.

**Comment by samirm** [comment]
@JosefNemec no you're right, hard coding is not the proper way of doing things and won't be sustainable. I'll start looking into those issues, will post my progress here. If you want help with #523 let me know :)

**Comment by JosefNemec** [comment]
Released in 4.5
