### ISSUE TITLE
Custom game properties

### ISSUE THREAD

**Issue by JosefNemec** [JosefNemec/Playnite#502]
Ability to add any custom (string based) key/value data pair to each game.

**Comment by jpflanegan** [comment]
If I'm to understand this one correctly it is to add custom fields like there is a Genre(s) field but I could add a Sub-Genre(s) field or a Mode(s) field or a Perspective(s) field or any other field I might like or think of?

I really like to sort and categorize my collections and tag relevant information as much as possible, ultimately I am looking for a way to do filtering something like this.

1. Filter by Genre(s) - Action
2. Filter by Sub-Genre(s) - Shooter
3. Filter by Perspective(s) - Third-Person
4. Filter by Mode(s) - LAN Multi-Player

If that is what would be possible with this then that is awesome and I can't wait for this. Would they also be editable like the Category(s) field?

**Comment by JosefNemec** [comment]
This doesn't mean global customizable fields. It means that you would be able to add any key/value pair per game. You can think of them as you custom "notes", but they will be passable to launch arguments or usable by extensions or other places like game properties.

**Comment by Lacro59** [comment]
Likewise, it would be good if the plugin could also add editable fields of its own.

**Comment by JosefNemec** [comment]
That's being tracked under #801

**Comment by chocolatechipcats** [comment]
Would it be possible to have a field-type similar to 'manual' that stores a hyperlink and then allows the user to access it via the 'More' menu? 

One use-case would be having a link (file://, https://, or custom protocols like [calibre://](https://manual.calibre-ebook.com/url_scheme.html)) to a strategy guide alongside Manual. (Currently, I stick them in the Play actions.)

**Comment by lucasmarotta** [comment]
@JosefNemec  Will this issue provide a more simple way to add custom launch arguments for a game? Why I am saying this. I am not talking about emulators, just normal store games. Currently, as far as I know, this could be done by actions or in the installation tabs. Using actions imply having two Play actions, which I don't like for a simple game launch argument. Using the installation folder requires adding a Game ROM which implies to specifically select the executable file of the game. Sometimes this is easy to check, but others not so much. If the system already knows internally what should be the executable file, why not just have argument fields like present in many game stores? Would be way simpler and easier.

**Comment by JosefNemec** [comment]
This is completely unrelated to anything game startup related. If you want custom cmdline arguments, you need to add custom play action. If you don't want original store play action to be displayed on startup, there's a checkbox to disable it.

What you describe with ROM files also has nothing to do with argument or game executable, that's handled on emulator level, you are not launching ROM file, you are starting emulator exe.

**Comment by JosefNemec** [comment]
Will be done in P11 via plugin fields as #801. It doesn't make sense to have two separate systems for this, especially when one of them (this issue) would be very limited compared to the other (for example no metadata download support).
