### ISSUE TITLE
Flat Skin

### ISSUE THREAD

**Issue by LiNCHx** [JosefNemec/Playnite#505]
# Flat Skin
Flat Skin is my first Theme for Playnite. Its a simple modern/material looking Theme that I've created because I don't like the standard colors and borders.
_You have to blur the background images yourself! I recommend using Photoscape or Gimp for that._

**The font I've used is Century Gothic. If you want this font too you have to download it yourself.**

**DOWNLOAD** _[v1.2]_ [Flat-Theme.zip](https://github.com/JosefNemec/Playnite/files/1877325/Flat-Theme.zip)

**SCREENSHOT:**
![Screenshot](https://user-images.githubusercontent.com/34384416/38173583-bcdf6618-35c0-11e8-8c0e-8688aa768093.png)

**Comment by ArtexJay** [comment]
Oh wow, that looks good, ll give it a try

**Comment by LiNCHx** [comment]
1. Ok, I will update the Theme so you can select the Theme with and without Borders.
2. I don't have much experience with theming in playnite so I don't know how I could prevent the background wallpaper from extending under the sidebar :/

**Comment by Continous** [comment]
> I don't have much experience with theming in playnite so I don't know how I could prevent the background wallpaper from extending under the sidebar :/

Currently you can't, to my understanding.

**Comment by JosefNemec** [comment]
You can prevent background from being under sidebar by moving background Image element to GameDetailsView view.

**Comment by LiNCHx** [comment]
> You can prevent background from being under sidebar by moving background Image element to GameDetailsView view.

I've tried that but now the background image isn't visible anymore.
Screenshot: http://prntscr.com/j0v6f3
What did I do wrong?

**Comment by JosefNemec** [comment]
Set Source binding to `{Binding Game.` not `{Binding SelectedGameDetails.Game.`

I know that making these changes sux currently because you need to modify data binding, that's why I'm going to rewrite theming in one of the 4.x versions.

**Comment by ArtexJay** [comment]
Nice update! I'll wait for that binding thingy, and try to skin more then. So far great job! Really like it

**Comment by JosefNemec** [comment]
Forgot to mention this before 4.0 release, but custom themes will be broken in Playnite 4. There has been some changes to localization strings and other stuff that will break your theme. It's one of the reasons why themming is being completely rewritten in #510. I'm sorry for the issues and not notifying you earlier.

**Comment by JosefNemec** [comment]
I'm closing this since it won't be compatible with 5.0 theming changes, plus we should use different place to manage 3rd party themes (probably new forums in near future).
