### ISSUE TITLE
Filter options for all new game fields from 4.0

### ISSUE THREAD

**Issue by JosefNemec** [JosefNemec/Playnite#512]
There's a lot of new game fields in 4.0 and not all of them can be currently used to filter game lists. This is because current filtering system only allows filtering of simple string based fields (and some date time values). Issue #135 will add ability to filter all field types and we should add option to filter by all 4.0 fields once it's implemented.

**Comment by MattGTX** [comment]
Thats good, but how can I install the 4.0 Update? I know that you already released the Update but only the source code. What do I need to do?

**Comment by JosefNemec** [comment]
4.0 binaries are temporarily available to [patrons](https://www.patreon.com/playnite) only until end of this month.

**Comment by MattGTX** [comment]
Ok! So the new update will be available in about 2 weeks ?

**Comment by JosefNemec** [comment]
Yes

**Comment by mike-potter** [comment]
Using v4.74 and I'm not seeing any way to filter by completion status.  I'd like to filter out the games I've already completed or beaten.  Any plans to add that?

**Comment by JosefNemec** [comment]
Done in 5.0
