### ISSUE TITLE
Crash at startup, after several hard crashes

### ISSUE THREAD

**Issue by Ripper935** [JosefNemec/Playnite#515]
[Startup after several crashes.zip](https://github.com/JosefNemec/Playnite/files/1912370/Startup.after.several.crashes.zip)

Error message keeps popping and won't run Playnite.

**Comment by JosefNemec** [comment]
This is really weird, your config file is all messed up.

To fix this first delete `%appdata%\playnite\config.json` file and then check Steam's installation folder and delete `\config\loginusers.vdf` file. Restart Steam and check if you still get crashes.

**Comment by Ripper935** [comment]
Wanted to ask what's the difference between importing all games by: name or local user

**Comment by JosefNemec** [comment]
No difference other than you don't have to fill out account name (if don't have public account for example) if you choose local user.

**Comment by JosefNemec** [comment]
Released in 4.0
