### ISSUE TITLE
Fullscreen mode enhacements

### ISSUE THREAD

**Issue by JosefNemec** [JosefNemec/Playnite#520]
Current implementation is very limited and lacks a lot of features. Once themming support #510 is implemented we should rework fullscreen mode and add these features (also split this to separate issues).

- Advanced search and filters
- Grouped views
- Game editing (mainly assigning groups, tags etc.)
- Display additional game details (configurable)
- Fullscreen related settings changeable without switching to desktop mode
- Fullscreen customized dialogs (like update dialog)

**Comment by berserkwarwolf** [comment]
- Zoom slider for fitting more games in 1 view

**Comment by xBitsoft** [comment]
In fullscreen mode, can the space between rows be automatically adjusted based on the proportions of the game covers in each row? I use 2x Steam grid covers for all my games and there's a big space between my rows.

**Comment by ThePaul51** [comment]
Group by genre should also be done.

**Comment by JosefNemec** [comment]
Done in 5.0, grouped view will be done as part of  #1278
