### ISSUE TITLE
not installing with windows shell 4.0

### ISSUE THREAD

**Issue by marlon99rocks** [JosefNemec/Playnite#529]
not installing with windows shell 4.0

**Comment by JosefNemec** [comment]
If you mean PowerShell 4.0 then 5.0 is currently required for PS scripts to work. And I have no idea what's not installing, missing PowerShell should not prevent Playnite from being installed.

**Comment by marlon99rocks** [comment]
micro visual studio not working

**Comment by marlon99rocks** [comment]
its giving me 2 errors codes CS0246 and CS0006
