### ISSUE TITLE
Add installer to 4.0 release

### ISSUE THREAD

**Issue by madsnedergaard** [JosefNemec/Playnite#530]
Installer is missing from the 4.0 release. Since this release seems done, is there any reason why the installer isn't added (currently only source code is available)?

Would love to try the new version :)

**Comment by JosefNemec** [comment]
Binaries are currently exclusively released to [patrons](https://www.patreon.com/playnite) only. Public release is on this Friday 27th.

**Comment by madsnedergaard** [comment]
Oh okay, didn’t realise that - and seems like a great way to do it actually :)
