### ISSUE TITLE
Auto-hide mouse cursor when starting full-screen mode

### ISSUE THREAD

**Issue by Evene174** [JosefNemec/Playnite#533]
At this moment, the cursor remains in the position it was before launching. It's really uncomfortable.

**Comment by DagNasty** [comment]
Any ETA when this might be added?

**Comment by wwwizzarrdry** [comment]
In C# it's as easy as:
`private void gridArea_MouseEnter(object sender, System.EventArgs e)
{
   // Hide the cursor when the mouse pointer enters the grid area.
   Cursor.Hide();
}

private void gridArea_MouseLeave(object sender, System.EventArgs e)
{
   // Show the cursor when the mouse pointer leaves the grid area.
   Cursor.Show();
}`

**Comment by JosefNemec** [comment]
Already done in devel9, just forgot to close this.
