### ISSUE TITLE
Alternative play time display

### ISSUE THREAD

**Issue by PhrozenByte** [JosefNemec/Playnite#536]
A game's play count should be displayed using `HH:MM:SS` (two digits each, possibly more digits for hours), e.g. `01:02:03` for 1 hour, 2 minutes and 3 seconds. The current solution using 3 separate language variables IMO looks a bit "patchy" and can't be used in a meaningful way for some languages.

Btw: The "Not played" string when entering `0` isn't translatable (I'd assume it uses the `LOCNotPlayed` variable, but that's not the case, `LOCNotPlayed` is used for the play status dropdown, only).

**Comment by JosefNemec** [comment]
Why is "Not played" not translatable?

**Comment by PhrozenByte** [comment]
![playnite-notplayed](https://user-images.githubusercontent.com/920356/39395790-4f37949a-4ae3-11e8-9c59-abf7342ef1ed.png)

"Nicht gespielt" (not played) in the "Spielfortschritt" (game progress) dropdown is `LOCNotPlayed`, but the "Not played" string from "Spielzeit" (play count) seems to be hardcoded, there's no language variable for it.

**Comment by PhrozenByte** [comment]
Amendment: I guess Playnite should ignore seconds, a play time below 60 seconds doesn't make much sense. So the play time should be displayed using `HH:MM` only, with e.g. `01:02` for 1 hour and 2 minutes. Everything below 60 seconds should be displayed as "Not played".

**Comment by JosefNemec** [comment]
I guess that goes down to personal preference, I personally would rather have the current style compared to HH:MM one. This should be added as switchable option.

The and Not Played text should be using `LOCNotPlayed`, I'll look into it.

**Comment by JosefNemec** [comment]
The localization string for the `Not Played` text is `LOCPlayedNone`.

**Comment by JosefNemec** [comment]
Done for P11 already with move to Project Fluent style translations.
