### ISSUE TITLE
Add option to collapse/expand all categories

### ISSUE THREAD

**Issue by JosefNemec** [JosefNemec/Playnite#54]
Probably via context menu on group header.

**Comment by jvarnes** [comment]
Adding a request for this feature as well. Steam has right click context popup that operates in this manner and I have found it to be a Godsend when dealing with large amounts of categories (which I have for organizational purposes).

**Comment by elrandir** [comment]
I would like to request this feature as well, or if I'm not understanding this request correctly: a dropdown list in the Category filter for all categories so I don't have to type them instead.
I would happily donate for this to be added. Thank you! I love Playnite!

**Comment by shinmai** [comment]
> Adding a request for this feature as well. Steam has right click context popup that operates in this manner

Steam _used_ to have a context menu item that did this, which was nixed in the latest update to the Library tab of the client.

**Comment by JosefNemec** [comment]
Done in `devel8`.
