### ISSUE TITLE
Importing games from D-Fend Reloaded (DOSBOX frontend) doesn't work

### ISSUE THREAD

**Issue by spiral6** [JosefNemec/Playnite#540]
The issue is due to typical DOSBOX .conf files being renamed .prof files in D-Fend. If there's an option to import them as .prof files, it would work.

**Comment by JosefNemec** [comment]
You need to create new [emulator profile](https://github.com/JosefNemec/Playnite/wiki/Emulator-Settings) for it then.

And possible if you can also add it into [this list](https://github.com/JosefNemec/Playnite/blob/master/source/Playnite/Emulators/Definitions.yaml) and send pull request for it. That will make supported by default in Playnite.

**Comment by spiral6** [comment]
Actually, the commit I added isn't going to work. When launching a game from D-Fend Reloaded from the command line, it needs the "proper name", aka the name of the game in Playnite (i.e. "Jazz Jackrabbit" as opposed to "jazzjackrabbit.prof" or "jazzjackrabbit") to launch. Perhaps add a {Name} option?

**Comment by JosefNemec** [comment]
I'll add `{Name}` option in next update.

**Comment by JosefNemec** [comment]
There's now new variable called `{Name}` you can use in 4.2.
