### ISSUE TITLE
MAME games look like always installed no matter the action

### ISSUE THREAD

**Issue by diegoesp** [JosefNemec/Playnite#541]
Hey!

MAME games come in the "installed" search even if they're not playable.

![image](https://user-images.githubusercontent.com/1253206/39404211-117b539c-4b8f-11e8-882a-c41b7e90846c.png)

![image](https://user-images.githubusercontent.com/1253206/39404215-21d69328-4b8f-11e8-905d-e3eb611765dc.png)

![image](https://user-images.githubusercontent.com/1253206/39404216-29ff824e-4b8f-11e8-9114-95683b638767.png)

**Comment by JosefNemec** [comment]
Installation state for emulated games is based on wheter the game has valid ROM/ISO set.

**Comment by diegoesp** [comment]
OK! I'm not sure what is the best possible outcome because I'm probably doing a very custom thing here. I just don't want my emulators games to look like "installed", I typically filter by a custom tag when I want to find them.

So I'll just go ahead and take out the path from the ISO whenever I don't want to look them like they're installed. I'll leave the path in another field and put it back in when I want the game to be displayed in the "installed" filter.

**Comment by JosefNemec** [comment]
I will be adding option to specifically set if the game is installed or not as part of #546 

If you have additional comments or requests regarding this issue please post them in #546 since it's basically the same issue.

**Comment by diegoesp** [comment]
That is great :) Thanks Josef!

**Comment by Jacl1982** [comment]
Hi guy looking for help to set up mame on playnite. step by step guide would be great have mame emulator and roms really to go just can't  seem to set it on on playnite I'm using latest version 9.19 thanks again...
