### ISSUE TITLE
Banner/Tile View

### ISSUE THREAD

**Issue by spiral6** [JosefNemec/Playnite#543]
The Cover View is great but all the covers are not of a standard size and it would be nice to have a standard size view like the cover view without losing the cover metadata. This is why I propose an additional view similar (or exactly like) Steam's Banner view. Adding a place for banner metadata would be nice. 

Something akin to ![this](https://i.imgur.com/sRZW6MM.jpg) would be very nice. Mainly because there is a website already for banners like these such as the [Steambanners booru](http://steambanners.booru.org/index.php?page=post&s=list), among others, which support all kinds of banners including custom banners for non-Steam games and even programs like emulators.

The standard size of the banners are all consistently 460x215 px.

**Comment by JosefNemec** [comment]
There will be an option with new theming support to chose what aspect ration covers should render at.

**Comment by kblamann** [comment]
Hi,
as a workaround i use the free image viewer/editor irfanview to batch adjust the size of all imags in one step to the same size. This should also be possiblle with other apps too.

Short HowTo (i use no background pics, maybe this could change the procedure) 
After adding the games with covers to playnite, it will be cached in the playnite directory.
In example: pathtoplaynite\Playnite474\library\files
Make a backup of your "files" folder first.

1. Open up irfanview, go to "File -> Batch Processing/Renaming"
2. Choose "Batch Conversion"
3. Output format, take your format, i.e. jpg
4. Check "use advances options (for bulk resize)
5. Click "Advanced" button
6. Check "Resize" and add the size you will use for all covers
7. Uncheck option "Preserve aspect ration"
8. Under Miscellaneous, check "create subfolders in destination folder"
9. Click "OK" th exit advanced settings.
10. Change output drectory to any path and check "include subdirectories"
11 on the top right go to your playnite dir pathtoplaynite\Playnite474\library\files
12 Select jpg to get only covers and no icons and select "Add all"
12 "Start batch" now. Before you close check your output dir if you're happy with the result.
13. After this replace playnite\library\files dir with the newly created output dir.

Hope that helps

**Comment by JosefNemec** [comment]
Done in 5.0
