### ISSUE TITLE
Games with 2 or more discs get duplicated when using the Emulation Import Wizard

### ISSUE THREAD

**Issue by drakenation** [JosefNemec/Playnite#545]
It is as the title says. I've included a screenshot to better illustrate the situation.
![duplicate_import](https://user-images.githubusercontent.com/395853/39411204-b50454a4-4bdb-11e8-8e7c-4e2095431994.png)

**Comment by JosefNemec** [comment]
Support for multiple disc games is not implemented yet, it will done as part of #159

**Comment by MAC293** [comment]
When I added a specific game (PSX), I had to select the 3 discs of it, and 3 copies of the same game were included to the menu. How can I make one cover of it? It confuses me everytime I want to play the game, I don't know if I chose the 1st disc or not.
