### ISSUE TITLE
Manually Added Games Are Not Considered Installed

### ISSUE THREAD

**Issue by BAPACop** [JosefNemec/Playnite#546]
After updating to 4.1, all manually-added games lost their Play buttons in List view. The Play Action for each game is still set. Attempting to hit Play from the Covers view prompts the error message "Cannot install game: The method or operation is not implemented." List view then shows a button labeled "Setup in progress" which can be cancelled. It seems that Playnite believes manually-added games need to be installed. No game has anything set in the Installation tab; both Installation Directory and Image/ISO Path are both blank.

This issue exists with games added before the update as well as game added after the update.

**Comment by BAPACop** [comment]
That did work and allow me to run manually-added games via Playnite again. I assume this is unintended behavior though, since it's rather unintuitive and also applies to games using URL Play Actions.

**Comment by MattGTX** [comment]
Yes, that's a pretty strange behavior.

**Comment by JosefNemec** [comment]
Custom games are considered installed if they have Installation Directory or ROM path set. There's one exception for Windows Store games, where the detection works different.

I'm not sure what would be better way to do it, I'm open to suggestions.

**Comment by MattGTX** [comment]
I think that a better way to solve this is automatically input the installation path when you inform where the exe is

**Comment by JosefNemec** [comment]
Installation path is automatically populated if you add game via drag'n'drop or from `Add game -> Installed games` menu. If you create completely custom one then I'm not sure if Playnite should be responsible to fill that value in.

**Comment by BAPACop** [comment]
I would suggest one of the following:

- If no installation directory is specified, assume the game is installed 
- If no installation directory is specified, assume the game is installed if the Play Action points to a valid location
- Auto-populate the installation directory (if it is not already set) with the directory of the Play Action, since the user is likely not selecting a non-existent file when manually setting this option
- Display a button in place of "Play" that is labelled "Install" or "Locate" on these games in List mode and have this function and the existing function in Cover mode prompt the user for the installation directory instead of throwing an error due to a non-existent installer

Even if you prefer to keep the current behavior, I strongly suggest ignoring the installation directory and always assuming the game is installed if the Play Action is a URL.

**Comment by JosefNemec** [comment]
Released in 4.2
