### ISSUE TITLE
Enable bulk editing for all game fields

### ISSUE THREAD

**Issue by JosefNemec** [JosefNemec/Playnite#547]
Currently only fields from general tab can be changed while editing multiple games at once. We should extend to other tabs as well.

**Comment by CorporalQuesadilla** [comment]
For example. being able to change platform-specific emulator would be useful. This could even be abstracted to a separate setting (default emulator for system) than just the Edit menu of selected titles.

**Comment by Revolt64** [comment]
Hello @JosefNemec - Hope you are keeping well during the pandemic. 

Is there any timeline for being able to bulk edit the emulator used by games of said system? For instance, I recently changed from a standalone emulator for the sega genesis to using retroarch, and I have about 400 games. So doing them one by one was out of the question, so I was forced to just delete all the games from playnite and re-import them all.

It's sub-optimal.

Thanks for all your great work on this project.

**Comment by JosefNemec** [comment]
It's going to be added in Playnite 8, I just forgot to add milestone, sorry about that.

**Comment by JosefNemec** [comment]
Done in `devel8`.
