### ISSUE TITLE
Lithuanian translation

### ISSUE THREAD

**Issue by Wargzax** [JosefNemec/Playnite#550]
Just finished lithuanian translation. Here's the fille:
[lithuanian.zip](https://github.com/JosefNemec/Playnite/files/1965900/lithuanian.zip)

**Comment by Wargzax** [comment]
Also there are few bits aren't translated. Just double checked lokalization file - all strings are translated, but error still return english text :
![screenshot_1](https://user-images.githubusercontent.com/24790236/39519719-a0950e96-4e10-11e8-969d-0ba57796073f.png)

**Comment by JosefNemec** [comment]
Some error messages are currently not translatable, I'll open separate issue to make them translatable.

**Comment by JosefNemec** [comment]
Localization have been completely move to Crowdin: https://crowdin.com/project/playnite

Please join the project there to submit updates.
