### ISSUE TITLE
Multiple Selections in Cover View

### ISSUE THREAD

**Issue by By6r9** [JosefNemec/Playnite#553]
List and Details Views allows selection of multiple items but not Cover view, breaking for example mass editing.

**Comment by JosefNemec** [comment]
Please leave issues open if implementation is not in any released build yet. Thanks

**Comment by By6r9** [comment]
Tested this change today and: I can select few covers, but only first selected is active, PlayniteApi.MainView.SelectedGames returns only one/first game, also edit/F3 opens detail view of a single position.

**Comment by JosefNemec** [comment]
I can't reproduce it, it works properly for me when selecting multiple games via CTRL-A, CTRL-CLICK and SHIFT-CLICK.

**Comment by JosefNemec** [comment]
Nevermind, it looks like it only works properly if the application is started on Convers view, it doesn't work if you switch to it.

**Comment by JosefNemec** [comment]
Released in 4.2
