### ISSUE TITLE
Game Jolt support

### ISSUE THREAD

**Issue by IroN1Mod** [JosefNemec/Playnite#555]
I love playnite but i think something is missing. Other game client are available like gamejolt. If you can add it to playnite, this software can be perfect, so, please add gamejolt client to playnite !!!

**Comment by ArtexJay** [comment]
Yes this needs to be a thing especially if we have itch there too.

**Comment by ArtexJay** [comment]
https://gamejolt.com/game-api/doc

here is the api one would need for Gamejolt implementation I think.

**Comment by JosefNemec** [comment]
I'm going to have to close this. I'm already maintaining a lot of other integrations already and it's just not possible for me to add another one to the list. Maybe somebody else will make this as a 3rd party integration.

**Comment by JosefNemec** [comment]
Also forgot to mention that mrxx99 on Discord already started making GameJolt integration plugin some time ago, but I have no idea what state it's in.

**Comment by ayunami2000** [comment]
Is this possible now that quite a bit of time has passed?

**Comment by Mrxx99** [comment]
@IroN1Mod @ArtexJay @ayunami2000 Game Jolt integration library is now available: https://playnite.link/addons.html#GameJoltLibrary_555d58fd-a000-401b-972c-9230bed81aed
If you find issues please report them here: https://github.com/Mrxx99/Playnite.GameJoltLibrary

**Comment by Nedjouamario** [comment]
LETS FUCKING GO
