### ISSUE TITLE
ScummVM support

### ISSUE THREAD

**Issue by shoku4649** [JosefNemec/Playnite#556]
Please use search first to see if the issue is already opened. Thank you
Ability to import and play ScummVM games.
- add folder of ScummVM games
- get all the folders imported as ScummVM games (folder name only is fine, but mapping the names to the game short names in https://www.scummvm.org/compatibility/ would be even better)
- launch scummvm with the folder name as argument

**Comment by JosefNemec** [comment]
I will add profile to automatically detect ScummVM installation but there's no way how to automatically detect and import games (without managing list of supported titles). The execution also requires game id to be supplied to emulator to run games properly.

**Comment by JosefNemec** [comment]
It's used in regular expressions for end of string.

**Comment by JosefNemec** [comment]
Released in 4.2, there's also new variable called `{InstallDirName}` you can use.
