### ISSUE TITLE
Download Metadata from IGDB: can't search for XIII

### ISSUE THREAD

**Issue by TroudhuK** [JosefNemec/Playnite#558]
I added XIII game manually, but I'm unable to get metadata from IGDB, which exists: https://www.igdb.com/games/xiii

I think it is a search engine bug.

![image](https://user-images.githubusercontent.com/11449740/39664181-c9d5faf6-507f-11e8-9d1e-ae4792564442.png)

**Comment by JosefNemec** [comment]
Looks like some IGDB API issue, for now you can use `Thirteen` to find it.

**Comment by TroudhuK** [comment]
Nice, thank you for the analysis and solution 👍

**Comment by JosefNemec** [comment]
I'm closing this since there's nothing to fix on our side, it has to be fixed in IGDB API. I've created [issue](https://github.com/igdb/api/issues/40) for it in their repository.
