### ISSUE TITLE
Allow sorting by playform

### ISSUE THREAD

**Issue by EatSleepSlay** [JosefNemec/Playnite#561]
Right now there seems to be no windows allowing us to sort games into platforms. I use this program for running my steam library and my emulator library and right now it's an eyesore to have all the games on one giant window.

Would it be possible to add in some form of sections for each platform we import (like one section for PC, N64, Dolphin etc)?

**Comment by JosefNemec** [comment]
Could you elaborate more on how the platform grouping should be handled? Or is this just about grouping not working on Covers view (will be added in #170)?

**Comment by sduensin** [comment]
I've been using filters for this but there doesn't seem to be a way to filter something like "PlayStation" since that also gets me "PlayStation 2" and "PlayStation Portable" games.

**Comment by JosefNemec** [comment]
Done in 5.0
