### ISSUE TITLE
Check updater integrity before updating

### ISSUE THREAD

**Issue by noraj** [JosefNemec/Playnite#563]
Hi,

I'm running **Playnite 3.6.** 

I can't upgrade Playnite via the *Install update* button, I get the following error:

![](https://i.imgur.com/cuWU8kS.jpg)

But I sucessfully installed it via the exe installer.

I'm running Windows Server 2016.

**Comment by JosefNemec** [comment]
Updater package was probably not downloaded properly and there's currently not checksum check before starting the update.

**Comment by noraj** [comment]
@JosefNemec I tried several time so I don't think it is a corruption during the HTTP download.

It's maybe a problem from Windows Server itself because I had pending windows updates that required a Windows reboot.

So I wouldn't spend to much time to test this but rather improve the error handling and message.

**Comment by JosefNemec** [comment]
The message comes from NSIS framework used to package the installer, I'm not sure I can change it.

**Comment by noraj** [comment]
Can you detect / catch the update error/fail in Playnite code ?

**Comment by noraj** [comment]
I installed 4.3, I'll tell you at the next update if it fixed the update issue.
