### ISSUE TITLE
Hungarian localization

### ISSUE THREAD

**Issue by Ratox00** [JosefNemec/Playnite#564]
Finished making the hungarian translation
[hungarian translation.zip](https://github.com/JosefNemec/Playnite/files/1981798/hungarian.translation.zip)

**Comment by Ratox00** [comment]
Updated the file, fixed typos, some missing text translation, and changed some text to make it more grammatically correct, and easier to understand.
[Hungarian translation update 1.zip](https://github.com/JosefNemec/Playnite/files/1987715/Hungarian.translation.update.1.zip)

**Comment by JosefNemec** [comment]
Localization have been completely move to Crowdin: https://crowdin.com/project/playnite

Please join the project there to submit updates.
