### ISSUE TITLE
Add import ignore list

### ISSUE THREAD

**Issue by ClearStrelok** [JosefNemec/Playnite#565]
Not quite an issue in itself, but installing the early access game "Deep Rock Galactic" had Steam add a new folder containing common Redist such as DirectX in the "steamapps" section, which Playnite has identified as a standard game. 

![sans titre-2](https://user-images.githubusercontent.com/38838369/39784003-3ebf614c-5317-11e8-9b6b-7c1a55dfe1fb.jpg)

The automatic scan should probably ignore this entry entirely. (This appears to be the AppID: https://steamdb.info/app/228980/)

**Comment by JosefNemec** [comment]
We'll have to setup some ignore list, I think somebody else also reported one or more of these on discord. For now you can hide them via context menu.

**Comment by JosefNemec** [comment]
I changed the title to cover this functionality for any library plugin (can be used to ignore game trials from Origin for example).

**Comment by JosefNemec** [comment]
Done in `devel8`.
