### ISSUE TITLE
Unable to track "Time Played" when launching a Windows Store game

### ISSUE THREAD

**Issue by ClearStrelok** [JosefNemec/Playnite#567]
I suppose this issue is entirely related to UWP applications being a complete mess, but Playnite can't monitor the session for more than a few seconds when playing a Windows Store game. (Tested with ReCore and Sea of Thieves)

**Comment by JosefNemec** [comment]
To be honest I totally forgot about UWP apps when implementing time tracking :)

**Comment by JosefNemec** [comment]
Released in 4.2, you need to re-import UWP applications for it to work properly.
