### ISSUE TITLE
Can't start Playnite minimized anymore

### ISSUE THREAD

**Issue by PhrozenByte** [JosefNemec/Playnite#568]
As described in https://github.com/JosefNemec/Playnite/issues/64#issuecomment-353715407 it was possible to start Playnite minimized by using Windows' "Run minimized" feature for shortcuts. This doesn't work anymore. I'm not sure whether it stopped working with Playnite 3.6 or 4.0/4.1, it always starts maximized now.

**Comment by JosefNemec** [comment]
Looks like this is Windows 7 only issue according to my tests.

**Comment by PhrozenByte** [comment]
I'm using Windows 10 1710 :confused:

**Comment by JosefNemec** [comment]
That's odd, it works for me properly on 1709 and 1803. Can you try to update to the big "April" update (1803) to see if it fixes it.

**Comment by PhrozenByte** [comment]
I've updated to 1803 now. Anyway, the issues isn't related to Windows 10.

The issue only occurs when Playnite's window is maximized when closing Playnite. If Playnite's window is not maximized when closing Playnite, it later respects the "Run Minimized" shortcut option. If Playnite's window is maximized, it later ignores the shortcut option. 

The weird thing is: This only happens if one uses the "Exit" button in Playnite's menu. If you rather just restart Windows (i.e. letting Windows terminate Playnite's process), it has no effect whether Playnite's window is maximized or not.

**Comment by JosefNemec** [comment]
Released in 4.55
