### ISSUE TITLE
Put games into categories based on metadata

### ISSUE THREAD

**Issue by terrainer** [JosefNemec/Playnite#569]
We have metadata to know what genre a game is, is there any way we could have it automatically categorise your game library based on the metadata genres?

**Comment by JosefNemec** [comment]
Databases we download data from currently don't have specific Category field. I'm not sure what would we base categories on. This is currently not possible.

**Comment by JosefNemec** [comment]
Closing per my last comment, metadata providers we support don't offer data that we could use to apply categories.
