### ISSUE TITLE
Allow wide game covers to occupy two spaces in the grid view

### ISSUE THREAD

**Issue by JanPokorny** [JosefNemec/Playnite#579]
Some game covers are wide -- like the Steam ones. Because of different cover sizes, the "covers" view has a lot of wasted space:

![obrazek](https://user-images.githubusercontent.com/4580066/39878684-3da60d70-5479-11e8-8084-734d41b53e5b.png)

It may help if Playnite allows the wide cover to occupy two spaces in the grid: _(MSPaint warning)_

![obrazek](https://user-images.githubusercontent.com/4580066/39878927-d4bacc14-5479-11e8-8a21-80f854d01c94.png)

What do you think about this idea? I believe this would help wide covers become first-class in Playnite, which is important because both Steam and GOG use wide covers by default.

**Comment by JosefNemec** [comment]
I had something similar in past (in 2.0 I think) where height of the items was unified and it was nightmare to get it working properly. I may revisit this some day, but any non-uniform grids are difficult to implement (specifically to make them efficient memory wise with virtualization).

I currently put more focus on getting all external covers downloaded correctly to mitigate these discrepancies in sizes.

**Comment by JanPokorny** [comment]
@JosefNemec I'm actually quite surprised that you chose tall covers, as wide covers seem to be the standard now, in the post-DVD era.

**Comment by JanPokorny** [comment]
@JosefNemec Yeah, the size isn't standardized, but both Steam:

![obrazek](https://user-images.githubusercontent.com/4580066/39880926-771ac298-547f-11e8-9199-a65b2519f164.png)

...and GOG:

![obrazek](https://user-images.githubusercontent.com/4580066/39880900-655e4174-547f-11e8-8ed2-9ca8f58fcb2d.png)

...seem to be using wide covers, as opposed to tall (DVD) ones.

**Comment by spektor56** [comment]
DVD size box art is pretty standard, any retail game in stores will have this type of art available.  Steam and GOG are not standard.

**Comment by JanPokorny** [comment]
Almost all retail games are on Steam, GOG or other platforms (UPlay has
wide covers too, I don't use Origin and battle.net so can't tell.) But
there are many games that aren't in retail (digital only), and these don't
have DVD covers. So wide covers should be more universal, right?

>

**Comment by JanPokorny** [comment]
@spektor56 

Origin uses primarily box art, but uses wide art sometimes (used in search results, for example):

![obrazek](https://user-images.githubusercontent.com/4580066/40612849-6e13d12a-627c-11e8-82b1-d8767c06719d.png)

Same goes for UPlay, it uses portrait covers (not really DVD covers, a little less tall), but uses wide art too:

![obrazek](https://user-images.githubusercontent.com/4580066/40612971-f0c25100-627c-11e8-98b5-f03ea56b8c6b.png)

But most importantly: **most games from non-Steam platforms are also on Steam**, so they have Steam-sized covers available. There is a much higher chance for a game to have a wide cover art than DVD cover art.

**Comment by JanPokorny** [comment]
But overall, I think that wide covers look better on screen. Look:

![image](https://user-images.githubusercontent.com/26068083/40082229-ce973708-58a9-11e8-89fc-9a0c12f054c7.png)

(Screen from @Evene174 -- I think they used some custom source for covers, right?)

**Comment by grey-lovelace** [comment]
Any opinion on using the SteamGridDB API to grab images from there so they are all uniform? I believe that is one of the main providers that the Steam-Rom-Manager uses and it works pretty well. Here are the docs for it. http://www.steamgriddb.com/api/

**Comment by JanPokorny** [comment]
@grey-lovelace That's a good idea, I'll create an issue

**Comment by JosefNemec** [comment]
@grey-lovelace Completely doable after we implement plugin API for custom metadata provides (#417).

**Comment by JosefNemec** [comment]
I'm closing this since original request is not doable. All items in the grid view have to occupy the same space for performance reasons. However 5.0 update will add several customization options to make rendering of cover images look more uniform.
