### ISSUE TITLE
Actions are not saved

### ISSUE THREAD

**Issue by Dragonink** [JosefNemec/Playnite#58]
The list of Actions we can set in the options of a game are not saved, especially with GOG games.
They rollback to the default actions of GOG after Playnite restart.

**Comment by JosefNemec** [comment]
This only applies to actions, which are imported from GOG, Steam or Origin, not manually added ones. I will change it so that changed built-in actions are not being overwritten to default state.

**Comment by JosefNemec** [comment]
Released in 0.94
