### ISSUE TITLE
Don't import non-games from Steam

### ISSUE THREAD

**Issue by JanPokorny** [JosefNemec/Playnite#583]
As Playnite is a tool to organize games, it doesn't make sense to import non-game items from Steam.

Like movies: https://store.steampowered.com/app/804320/Papers_Please__The_Short_Film/

...or tools: https://store.steampowered.com/app/719950/Windows_Mixed_Reality_for_SteamVR/

It would be great if Playnite automatically filtered those out, and imported only "real" games.

**Comment by JosefNemec** [comment]
There's no way how to do it, Steam API doesn't report what type of item is it.

**Comment by JanPokorny** [comment]
@JosefNemec It sort of does:

![obrazek](https://user-images.githubusercontent.com/4580066/39882741-f97d60e2-5484-11e8-82c6-dbe0340f5476.png)

![obrazek](https://user-images.githubusercontent.com/4580066/39882811-2d2570a6-5485-11e8-9e37-2dbf904af751.png)
