### ISSUE TITLE
"Modern" Fullscreen background

### ISSUE THREAD

**Issue by ClearStrelok** [JosefNemec/Playnite#584]
I wanted the fullscreen mode background to match the theme used in desktop mode so I made a new one. The second background is dithered but it's also 1080p because the dithering looked terrible with these colors at the default resolution. 

![background](https://user-images.githubusercontent.com/38838369/39887768-550e0ed0-5493-11e8-8e18-447af5192935.png)
![background](https://user-images.githubusercontent.com/38838369/39888252-8ceaa952-5494-11e8-8ff9-d106e244399b.png)

**Comment by JosefNemec** [comment]
Very nice! I'll be sure to include it in next version.

**Comment by JosefNemec** [comment]
Thanks, I'll include the Steam like one in next update and replace the current one since it's in pretty crappy quality. I just had to convert it to jpeg (best possible quality) since 6 MBs is quite heavy.

**Comment by JosefNemec** [comment]
Released in 4.71
