### ISSUE TITLE
Custom aspect ratio support for fullscreen mode

### ISSUE THREAD

**Issue by JosefNemec** [JosefNemec/Playnite#589]
Fullscreen mode is currently hard coded at 16:9 aspect ratio.

**Comment by joseluisametller** [comment]
Now that 4.6 has been released, any updates on this? Specially for ultrawide monitors. Thanks.

**Comment by JosefNemec** [comment]
It's been postponed to 5.0

**Comment by JosefNemec** [comment]
Done in 5.0
