### ISSUE TITLE
Save filter presets / Bookmarks

### ISSUE THREAD

**Issue by JosefNemec** [JosefNemec/Playnite#590]
Add option to save/load filter settings. Includes functionality for Fullscreen mode.

**Comment by Belgabor** [comment]
This is pretty much the first thing I missed when I started playnite the first time XD
My suggestion would be to implement them as tabs across the top as kind of quick-filter access.

**Comment by pulse4J** [comment]
I'm looking into this.  I'll let you know.

**Comment by pulse4J** [comment]
Unfortunately, I was not able to do the requested work due to some medical issues, so I apologize.  Maybe someone else can look into this.

**Comment by rnd256** [comment]
I agree with @Belgabor about tabs across the top, or possibly a dropdown field to support a large number of saved filter configs.

**Comment by bverkron** [comment]
For those interested in this features it's included in the poll for v9. I encourage users to vote for your desired features.
https://www.patreon.com/posts/playnite-9-42658568

**Comment by JosefNemec** [comment]
Done in devel9.
