### ISSUE TITLE
There's something wrong with embedding images in game description

### ISSUE THREAD

**Issue by DotsSalchow** [JosefNemec/Playnite#591]
This bug seems hard to describe, but I'm gonna try describing anyway.

Since the game description can be spruced up through HTML, I've been using it to add images in the game description. More specifically, I've been using it to make a game's age ratings easy to identify. Unfortunately, there seems to be a bug with HTML image embedding that messes with this.

From a certain point, any new image I tried to embed showed up as broken. I know this problem is not caused by the image or URL itself being broken, because I've replaced the image source URL in the description's HTML code with a completely different image that I hadn't embedded before (whether it came from online or from my hard drive), and it still shows up as broken. Now it seems like, in any game description, I can only embed the exact same images I've embedded already before this bug came to pass.

(In the image below, where it's circled and pointed out, there's supposed to be the ESRB Teen rating image.)
![playnite](https://user-images.githubusercontent.com/35101055/39966131-0dd941d6-56a7-11e8-85ab-ccafacb7ae63.jpg)
[playnite.log](https://github.com/JosefNemec/Playnite/files/1998324/playnite.log)

**Comment by DotsSalchow** [comment]
Update: I was being dumb. Turns out I made a misspelling in my HTML. The fault was entirely with me. You're free to reject this bug report.

Still, I look forward to the implementation of Markdown. That'll be a lot less of a hassle to work with in the end.

**Comment by JosefNemec** [comment]
Thanks for the info, closing...
