### ISSUE TITLE
Super Nintendo and Wii U/Switch Pro Controller fullscreen buttons

### ISSUE THREAD

**Issue by ClearStrelok** [JosefNemec/Playnite#592]
Steam now has official support for the Switch Pro and 8bitdo's lineup of retro gamepads has been quite popular recently, so I expect more and more users will have some sort of Nintendo device as their main controller.

[Nintendo.zip](https://github.com/JosefNemec/Playnite/files/1998651/Nintendo.zip)

![2](https://user-images.githubusercontent.com/38838369/39969073-2eca0094-56d7-11e8-8aee-163fdebf71df.jpg)
![1](https://user-images.githubusercontent.com/38838369/39969074-2eed7b50-56d7-11e8-8326-f91b82a20405.jpg)

**Comment by JosefNemec** [comment]
Released in 4.21
