### ISSUE TITLE
Uninstalling a game

### ISSUE THREAD

**Issue by FrantisekNemec** [JosefNemec/Playnite#6]
After uninstalling a game (tested on GOG game) uninstalled game is still present in Playnite. Attempt to launch the game results in error message.
![bez nazvu](https://cloud.githubusercontent.com/assets/18503961/24428489/f0cfbf74-140e-11e7-9725-3ee44e5c5b73.png)

**Comment by JosefNemec** [comment]
Fix released in 0.71
