### ISSUE TITLE
Making RetroArch import menu less cluttered.

### ISSUE THREAD

**Issue by By6r9** [JosefNemec/Playnite#607]
![r2](https://user-images.githubusercontent.com/32620314/40076412-1cd526c6-587f-11e8-8b03-55cccea4543c.png)

Script generating those entries uses `display_name` entry from RA info files, which results in some mess - cores are still listed in alphabetical order, but they are displayed in `platform (core name)` format.
Using `corename` field makes that menu much more readable.

![r1](https://user-images.githubusercontent.com/32620314/40076878-606880e4-5880-11e8-94be-545434096eb2.png)

Other good solution would be switching order of `display_name` to `core name (platform)` :
`Nintendo - Game Boy / Color (Gambatte)` to `Gambatte (Nintendo - Game Boy / Color)`

**Comment by JosefNemec** [comment]
Released in 4.21
