### ISSUE TITLE
Missing Strings (Translation)

### ISSUE THREAD

**Issue by ClearStrelok** [JosefNemec/Playnite#618]
Here's everything I could find that couldn't be translated due to the absence of related strings. This should concern other translations as well.

**When importing categories from Steam:**

  _Import Successful
  Import Finished._

**When using the virtual keyboard in fullscreen mode:**

  _Clear
  Back
  Done_

**In Desktop mode:**

  _No Category
  Export Library_  **(See #570)**

**Comment by JosefNemec** [comment]
*Export Library* comes from script extension which are not translatable.

**Comment by JosefNemec** [comment]
No Category will be fixed in #570

**Comment by JosefNemec** [comment]
Released in 4.30
