### ISSUE TITLE
Automatically download background pictures for Origin games using online store

### ISSUE THREAD

**Issue by ClearStrelok** [JosefNemec/Playnite#620]
Origin games currently don't have backgrounds automatically associated to them but they could. The backgrounds on the store pages of each game are pretty much the same size as the ones found on GOG (Around 200kb) and they look really good.

https://www.origin.com/fra/fr-fr/store/mirrors-edge/mirrors-edge-catalyst/standard-edition

![sans titre-9](https://user-images.githubusercontent.com/38838369/40283209-d76ce40c-5c7a-11e8-9fd0-b91d5183a4c1.jpg)

I was able to find matching backgrounds for pretty much all games except for the ones that don't exist on the store, either because they were given for free (Battlefield 1942, Populous...) or because they have been deleted in favor of a new edition (Titanfall and Bulletstorm in my case, but in [both](https://www.origin.com/fra/fr-fr/store/titanfall/titanfall/deluxe-edition) cases I just had to look for the [new versions](https://www.origin.com/fra/fr-fr/store/bulletstorm/bulletstorm-lite/standard-edition), maybe see #619 on that subject)

**Comment by JosefNemec** [comment]
Released in 4.59
