### ISSUE TITLE
Minimize 3rd party clients in system tray (When launching from Playnite)

### ISSUE THREAD

**Issue by ClearStrelok** [JosefNemec/Playnite#621]
It's nice that Playnite can act as a frontend to launch the game clients quickly, but having to wait for the client's window to load and then close it every time you want to launch a game gets old pretty fast. 

Having this as an option may help lower-end systems that can't afford to have 5+ game clients always running in the background, and also streamline the experience for those that can afford it but don't wish to have them running unless they are absolutely needed. (Starting the game and letting it load the client already kind of does that, but in my experience it often leads to weird behaviour with the system or cloud saves)

**Comment by JosefNemec** [comment]
The problem with this is detecting actual state of 3rd party application. I would have to detect different states and minimize it after the application is fully initialized (logged in and actually starting desired game).

**Comment by JosefNemec** [comment]
Closing based on my previous comment. It would too much effort to properly support all clients and keep maintaining this based on updates of those clients.
