### ISSUE TITLE
Add option to auto-close 3rd party client after a game is closed

### ISSUE THREAD

**Issue by ClearStrelok** [JosefNemec/Playnite#622]
This may be extremely difficult to implement with the already barely working Cloud Sync features of each game client updating at wildly different rates each times. (Unless the API can detect if a client is currently syncing data)

**Comment by JosefNemec** [comment]
This will be possible once #113 is implemented.

**Comment by JosefNemec** [comment]
Done in `devel7` branch (future Playnite 7).
