### ISSUE TITLE
Freeze then Crash while trying to import Steam categories

### ISSUE THREAD

**Issue by zh2eou** [JosefNemec/Playnite#623]
I'm trying to import my categories into Playnite, but both times I've tried it the client freezes for while before eventually crashing. I only have about a half dozen or so categories, though I do have a lot of games on Steam (1764 according to Playnite). 

This is for version 4.2 running on Windows 10 1803.

**Comment by JosefNemec** [comment]
Can you please attach diagnostics package that can be created from crash dialog? Thanks

**Comment by zh2eou** [comment]
Where do I get that from?

**Comment by JosefNemec** [comment]
There's a button on crash dialog for that, or go to `About Playnite` menu and create one from there.

**Comment by zh2eou** [comment]
[diag.zip](https://github.com/JosefNemec/Playnite/files/2031427/diag.zip)

On the crash dialog it just says PlayniteUI has stopped working with a Close program button, nothing else. However, I was able to get generate one from the About menu afterwards.

**Comment by JosefNemec** [comment]
I see, so it's not the standard Playnite crash, you would get different dialog then. Thanks for the package.

**Comment by JosefNemec** [comment]
Fixed in 4.5
