### ISSUE TITLE
Steam as a metadata source

### ISSUE THREAD

**Issue by JanPokorny** [JosefNemec/Playnite#638]
Many games are on Steam, even those bought on other platforms. Steam also provides a wide cover for all games, which is preferred by some users over DVD-sized covers. It would make sense to allow a setting to primarily use the Steam data.

Metadata API endpoint: https://store.steampowered.com/api/appdetails?appids=620

It also seems like the cover and background URLs are pretty constant (although they may change in the future):
https://steamcdn-a.akamaihd.net/steam/apps/620/header.jpg
https://steamcdn-a.akamaihd.net/steam/apps/620/page_bg_generated_v6b.jpg

Probably depends on #417

**Comment by JosefNemec** [comment]
Duplicate to #538
