### ISSUE TITLE
Removed & beta Steam games not showing up in library

### ISSUE THREAD

**Issue by azumukupoe** [JosefNemec/Playnite#639]
Please use search first to see if the issue is already opened. Thank you

**Comment by JosefNemec** [comment]
That's correct behavior, Playnite can no longer detect game on your account so it won't show up. What would expect to happen differently?

**Comment by azumukupoe** [comment]
ASF actually detects removed game on my account though...

**Comment by JosefNemec** [comment]
I thought you meant game that you removed from your library, not game that was removed from store, but it's still part of your library. What game is it?

**Comment by azumukupoe** [comment]
There are countless but one example is Absconding Zatwor.

**Comment by JosefNemec** [comment]
Can you go to "About Playnite" menu and create diagnostics package for me? Thanks

**Comment by azumukupoe** [comment]
[Playnite Diagnostics.zip](https://github.com/JosefNemec/Playnite/files/2049114/Playnite.Diagnostics.zip)

**Comment by JosefNemec** [comment]
Can you try it again? I pushed fix to the API server that should fixed it.

**Comment by azumukupoe** [comment]
It isn't fixed

**Comment by epeternally** [comment]
Same bug is happening on my end as well. Neither 'Absconding Zatwor' nor 'Breaking Into Zatwor' import into Playnite, despite owning both of them on Steam. 'GooCubelets' and all of its sequels are also affected. A number of removed games do import correctly, such as 'Ion Assault' and 'Indigo Prophecy', so I'm curious what is going on with these ones in particular.

It seems to only affect games that got pulled from the store by Valve, not ones that were removed by the developer/publisher, but I haven't been able to confirm that yet.

**Comment by epeternally** [comment]
> They probably made it so they don't report them via any API as well and that's why they don't get imported.

That's exactly what's going on. Apparently Steam distinguishes between games which have been delisted and games which have been banned. The latter aren't accessible through the API at all. There's a list of banned games [over here](https://steam-tracker.com/apps/banned). Other than Transformers Devastation there is nothing much of value in that list, so I doubt that many users will even notice.

**Comment by psychonic** [comment]
I can only see this working one of a few ways, all requiring Playnite to somehow get the "AppInfo" data for applications a user owns. Neither method is great.
* Parse Steam's AppInfo.vdf - The format is custom, but does not change too often. After the header, it's essentially a bunch of concatenated binary KVs.
* Logging in with SteamKit - This would requiring asking the user for credentials, and making a token request for each app's data, and then downloading it via HTTP(S).

Both ways get you data that could be useful for other purposes as well, such as reading Steam's launch options for games. For unreleased or removed games, it gets you the name, icon hash, etc.

**Comment by JosefNemec** [comment]
* AppInfo.vdf - I actually used to get user's library from that file in one of the very first versions of Playnite, but it caused way too many issues then what it was worth (the weird binary format, file randomly locking up etc.).

* How reliable is logging via SteamKit? Does it support Steam Guard? Wouldn't it be too slow if we had to make a special request for every single game?

In general I'm not sure if this is worth the effort to import couple of games that were removed from the Store, probably for breaking Steam's TOS anyways. I mean it doesn't effect legitimate games that were just hidden and are not sold anymore (like Dirt 3 for example). Those import properly.

Also we do download appinfo when downloading metadata for Steam games and use them to populate launch options for custom actions.

**Comment by psychonic** [comment]
> How reliable is logging via SteamKit? Does it support Steam Guard? Wouldn't it be too slow if we had to make a special request for every single game?

When I had originally mentioned it, I hadn't realized that Playnite does already do this, just with the anonymous user. Functionality would be identical other than calling Logon instead of LogonAnonymous, supplying username and password, with handling of possible Steam Guard code. The appinfo requests would come back for non-public games as well.

**Comment by JosefNemec** [comment]
Will be fixed via #910
