### ISSUE TITLE
Add option to start Playnite automatically during Windows boot

### ISSUE THREAD

**Issue by JosefNemec** [JosefNemec/Playnite#64]

**Comment by tegenton** [comment]
You can do this manually by adding a shortcut to the executable in the startup folder, although i would like to see this as an implemented feature

**Comment by PhrozenByte** [comment]
How about adding a command line option to start Playnite minimized? Even though there's no built-in "Start on boot" setting it would allow one to add a shortcut to the Autostart folder of the start menu to achieve virtually the same.

**Comment by doublah** [comment]
I'd like an additional option to start in the task bar as well.

**Comment by JosefNemec** [comment]
You can do it without any support from Playnite. Create shortuct to `PlayniteUI.exe`, copy that shortcut to `%appdata%\Microsoft\Windows\Start Menu\Programs\Startup\` and set it to start minimized:

![image](https://user-images.githubusercontent.com/3874087/34318469-c68e5368-e7c8-11e7-966a-e4e0daeb3444.png)

**Comment by PhrozenByte** [comment]
Oh, great, didn't knew that this is possible, thanks @JosefNemec! 👍

**Comment by JosefNemec** [comment]
Released in 4.55
