### ISSUE TITLE
A game I never owned showing up in Game Library

### ISSUE THREAD

**Issue by azumukupoe** [JosefNemec/Playnite#641]
I've never owned [Tyranny](https://store.steampowered.com/app/362960/Tyranny/), but it's shown in the Game Library. You can check my [Steam profile](http://steamcommunity.com/profiles/76561198435487131).

**Comment by JosefNemec** [comment]
Playnite will import all games that are reported by Steam API. This could include games that you don't see in your library in these cases:

- it's a F2P game you installed at some point in past
- it's a game that was part of free weekend deal and you installed it

Is this your case with Tyranny?

**Comment by azumukupoe** [comment]
Oh it was probably the free weekends.

**Comment by JosefNemec** [comment]
Thanks for clarification, closing this then.

**Comment by azumukupoe** [comment]
Is it possible for Playnite to ignore free weekend games? do I have to manually delete them after they expire?

**Comment by JosefNemec** [comment]
You have to manually hide then. Deleting them will bring them back if they are still reported by Steam API as part of your library. Proper support for game import ignore list will be done in future via #565.
