### ISSUE TITLE
Add provider labels

### ISSUE THREAD

**Issue by azumukupoe** [JosefNemec/Playnite#643]
It will allow you to distinguish duplicate games' providers without using filters.

**Comment by JosefNemec** [comment]
How exactly? There's already `Source` field that also contains where the game come from?

**Comment by azumukupoe** [comment]
I didn't see that bit how do I see it in the List mode?

**Comment by JosefNemec** [comment]
It currently only shows on grid view (if you enable it by right-clicking on the header), there's an issue #511 that will add option to display it elsewhere.

**Comment by JosefNemec** [comment]
Done in 5.0
