### ISSUE TITLE
Metadata download not completing

### ISSUE THREAD

**Issue by azumukupoe** [JosefNemec/Playnite#644]
Download sometimes get stuck resulting manually closing Playnite from task manager.

**Comment by azumukupoe** [comment]
Doesn't the diagnostics package I sent you previously give some information about this? Could you check?

**Comment by JosefNemec** [comment]
I don't want to have information about one bug spread in other issues, if you could please post it here as well. Otherwise it's impossible for me to keep track of everything.

**Comment by azumukupoe** [comment]
[diagnostics.zip](https://github.com/JosefNemec/Playnite/files/2059246/diagnostics.zip)

**Comment by JosefNemec** [comment]
Fixed in 4.40

**Comment by azumukupoe** [comment]
I'm experiencing the issue on 6.4
[diag.zip](https://github.com/JosefNemec/Playnite/files/4021350/diag.zip)

**Comment by JosefNemec** [comment]
Do you have a specific way of reproducing this? What's the metadata sources that you are using? Is it stuck when doing mass download or when downloading for a single from game edit dialog?

**Comment by azumukupoe** [comment]
![image](https://user-images.githubusercontent.com/31339007/71767366-e8541300-2f4e-11ea-807b-a92f2ce1e074.png)

**Comment by JosefNemec** [comment]
That doesn't really answer all my questions...

**Comment by azumukupoe** [comment]
Why? Doesn't this dialog only come up when you are trying to import metadata for more than one game at once?
