### ISSUE TITLE
Label VR games as VR

### ISSUE THREAD

**Issue by azumukupoe** [JosefNemec/Playnite#645]

**Comment by JosefNemec** [comment]
You can add your own tags and VR games should be already tagged if they come from Steam if I'm not mistaken. What else should we do?

**Comment by azumukupoe** [comment]
VR games are not tagged in my library somehow...

**Comment by JosefNemec** [comment]
Once again, I could do with more information... Are we talking about Steam games? What tags do they have assigned right now? If you try to re-download metadata will the VR tag show up?

**Comment by azumukupoe** [comment]
Yes, Steam games that are marked as VR games on the official client. They are currently marked PC on Playnite.

**Comment by JosefNemec** [comment]
Ou you mean VR `Platform`, I was talking about `Tags` field.

**Comment by Continous** [comment]
How hard would it theoretically be to allow Platform to be user enterable?

**Comment by JosefNemec** [comment]
You can already add your own VR platform and assign games to it.

**Comment by Continous** [comment]
That'd be a not hard at all. Maybe it should be a default then?

**Comment by ChildishGiant** [comment]
For some more info, this is how VR games are distinguished in Steam
![image](https://user-images.githubusercontent.com/13716824/58766543-e3be1b00-8577-11e9-8d1f-7aabd27ec5b7.png)
 They are separated in the same way software is but also appear under games. I guess on importing, add a VR platform to it. But I guess you'd need to have support for multiple platforms for that

**Comment by JosefNemec** [comment]
Done in `devel7`.
