### ISSUE TITLE
Display system requirements

### ISSUE THREAD

**Issue by azumukupoe** [JosefNemec/Playnite#647]

**Comment by JosefNemec** [comment]
IMHO this doesn't doesn't bring that much value after your already bought the game, so I don't think we are going to include it.

**Comment by azumukupoe** [comment]
I have to decide whether to install the game or not by looking at system requirements...
I mean, what about F2P games and games you got for free?
Also, I can't view system requirements for region-locked Steam games redeemed with CD keys.
