### ISSUE TITLE
Full screen user interface only responds to player 1 controller

### ISSUE THREAD

**Issue by SausageDog** [JosefNemec/Playnite#650]
This is an enhancement request.

A lot of games are friendly to multiple controllers. However in order to navigate the PlayNite UI in full screen mode you need to be using player 1 controller. This means if I'm not using the primary controller I need to switch devices to launch the game. It would be nice if any connected XInput device could navigate the UI and launch games, rather than just the first enumerated controller.

**Comment by JosefNemec** [comment]
Released in 4.30
