### ISSUE TITLE
Emulator profiles do not update

### ISSUE THREAD

**Issue by Nilot352** [JosefNemec/Playnite#651]
If a new core is added Retroarch is not updating its emulator profiles and has to be re-imported.

**Comment by JosefNemec** [comment]
This applies to all emulators, not just Retroarch. Emulator import is currently one time thing and settings are not updated if definitions change. We should take this into consideration when implementing #653

**Comment by JosefNemec** [comment]
I'm going to close this because it will be fully covered by the implementation in #653.
