### ISSUE TITLE
Community Support

### ISSUE THREAD

**Issue by sabi1** [JosefNemec/Playnite#66]
Enable community support for Steam at least, create a unified in-game overlay, running as well.

**Comment by JosefNemec** [comment]
I'm not sure I understand what you actually want, can you elaborate more on this?

**Comment by JosefNemec** [comment]
I'm going to close this for now since there's no additional information. Feel free to reopen this, if you can provide more detailed info.

**Comment by sabi1** [comment]
Well I thought if being able to access the steam chat while being in a origin uplay game etc. As well as steam showing which games you play.
________________________________

**Comment by JosefNemec** [comment]
I see, well those features are pretty much impossible I'm afraid.
