### ISSUE TITLE
Creation of themes

### ISSUE THREAD

**Issue by PlayerrLeo** [JosefNemec/Playnite#662]
I do not know if this is the most appropriate place to post this, if it is not, please let me know so it does not repeat itself.

I'm developing a theme for version 4.3 and needed to know how I can change the opacity of the windows bar (where the buttons are close, minimize and maximize).
I'm modifying the Modern skin.

Thanks and congratulations for the great work of updates you have done with playnite.

**Comment by JosefNemec** [comment]
Please wait with theme creation for version 4.5, it's going to include completely [rewritten](https://github.com/JosefNemec/Playnite/issues/510) theming support with more features. If you write it now you would have to completely redo it after 4.5 releases (there won't be any backwards compatibility).

**Comment by JosefNemec** [comment]
New documentation and additional resources will be posted to #510 once implemented.
