### ISSUE TITLE
Installation doesn't work as it is intended

### ISSUE THREAD

**Issue by Shashahan** [JosefNemec/Playnite#664]
For better understanding:
I set up my system with a strict seperation between a user and admin account. 
The Playnite installation requests admin priviliges which is fine as i want to install it.

But the installer only copy the required files to the appdata folder of the admin, not the appdata folder of the user. The created shortcuts point to the user appdata folder but there are no files there.

**Comment by JosefNemec** [comment]
Released in 4.55, setup not longer requires admin privileges.
