### ISSUE TITLE
Crash on setting multiple games to Hidden

### ISSUE THREAD

**Issue by DennoCoil** [JosefNemec/Playnite#665]
Got some "games" that are just DLC entries.  Modified the description to the main game, and set the DLC to Hidden by checking the two Hidden boxes.  Playnite crashed.
[crash.zip](https://github.com/JosefNemec/Playnite/files/2090557/crash.zip)

Edit:  Did a restart and one DLC entry is hidden now.  Hiding the other went fine.  I think it has something to with how multi-select works and the checkboxes caused a bit of a logic error.

**Comment by JosefNemec** [comment]
The same issue as #661
