### ISSUE TITLE
Game Ratings

### ISSUE THREAD

**Issue by ivanmayes** [JosefNemec/Playnite#666]
Please use search first to see if the issue is already opened. Thank you
Love the ease of use in Playnite so far, but it would be great to be able to rate games and sort by ratings.

**Comment by JosefNemec** [comment]
You can already rate games, there are 3 score fields (user, community and critic) when you edit game. And you can also sort by them via `..` button or by clicking on the header if you are using `Details` view.

**Comment by ivanmayes** [comment]
Sorry about that @JosefNemec, I didn't even notice that, was looking around for a star system of some sort.  Thanks!

**Comment by JosefNemec** [comment]
No problem, the star system might be a good idea. I'll look into it in future.

**Comment by JamesFrankel** [comment]
It would be great to be able to quickly rate games, and a star rating system would be great for that, i.e. something where you just hover over the star rating area and can directly set the amount of stars, similar to how Windows Media Player or LaunchBox does it. The lack of a quick and easy-to-use rating system is the only thing missing from Playnite right now, imho.
