### ISSUE TITLE
Last Played Today

### ISSUE THREAD

**Issue by bocest1986** [JosefNemec/Playnite#672]
The last played indicator always reads today. I constantly have Playnite open and only put my gaming pc in sleep mode. This causes the last played indicator to always display today. I have to close Playnite completely and reopen for the indicator to refresh

**Comment by JosefNemec** [comment]
This should be working, at least when you change the game the last played data will definitely update. Can you verify it?

**Comment by JosefNemec** [comment]
Closing, no response from original reporter.
