### ISSUE TITLE
UPlay store metadata support

### ISSUE THREAD

**Issue by cristi1990an** [JosefNemec/Playnite#674]
SC Conviction for example isn't recognized and it won't automatically download its metadata. I can download its IGDB or Wikipedia metadata manually but not its store data.

**Comment by JosefNemec** [comment]
There's no support for store metadata for Uplay yet:
https://github.com/JosefNemec/Playnite/wiki/Feature-table-based-on-library-provider

**Comment by JosefNemec** [comment]
Will be done in #679
