### ISSUE TITLE
Scrolling my games takes Playnite CPU and GPU usage to high values

### ISSUE THREAD

**Issue by fabiotp91** [JosefNemec/Playnite#677]
I have 150 games on Playnite, all with cover images and when I'm scrolling not only the scrolling isn't smooth but Playnite starts using 40%/60% of my CPU and 30%/40% of my GPU making the scrolling experience in the launcher not only bad but also pretty heavy, can't even imagine with weaker PC's how it holds itself.

My Specs:
i5 2500k 
8GB RAM
GTX 970

**Comment by JosefNemec** [comment]
In regards to CPU performance, there are currently caching issues when you scroll related to how images are being loaded, it should be solved by #454.

As far as GPU performance, I'm unable to reproduce the problem. Both my PCs (Win10 with 970 and Win8 with 1080) show basically 0% usage when scrolling (according to GPU-Z).

**Comment by JosefNemec** [comment]
This should be greatly improved since 4.59 release.

**Comment by blueberrys** [comment]
Reproducible in 4.74
Scrolling causes CPU usage to spike.

GPU Acceleration is enabled.
Asynchronous image loading is enabled.

This occurs even if the icon column is hidden.

**Comment by JosefNemec** [comment]
What is your system configuration and OS?

**Comment by blueberrys** [comment]
CPU: AMD FX-6300 Six-Core, 3500 Mhz
GPU: NVIDIA GeForce GTX 1060 3GB
RAM: 8GB DDR3-1600
OS: Microsoft Windows 10 Enterprise LTSC

**Comment by blueberrys** [comment]
Got some more info on this.

"spike" below refers to the CPU usage spike that occurs when scrolling.

- The spike is much larger if the "Genre(s)" column is enabled.
- If the "Genre(s)" column is enabled and then disabled, the spike is just as large as if the column was kept enabled.
- If the "Genre(s)" column is enabled and then disabled, and then the application is restarted, the spike is lower (but still occurs).

Hope that helps in narrowing down the cause!
