### ISSUE TITLE
Failed to open library database

### ISSUE THREAD

**Issue by alpal0** [JosefNemec/Playnite#681]
Hey guys, 
Having an issue with my library being loaded. This pops up every time I open the application. I don't believe I've changed anything lately. I'm new to github/playnite, so sorry if this is an obvious error. 
Thanks!
Allan
![playnite error](https://user-images.githubusercontent.com/40407909/41624416-98d84cd8-73e3-11e8-81d6-3764bc82d6fa.png)

**Comment by alpal0** [comment]
[diag1.zip](https://github.com/JosefNemec/Playnite/files/2116997/diag1.zip)
Attached diag

**Comment by JosefNemec** [comment]
Already tracked as #675. Sadly you'll have to delete your DB file to fix this (the path to a file can be found in settings menu).

I was unable to 100% pinpoint the cause for this, but it looks like it should only happen with version 4.20 and older, which doesn't close database properly when Windows is shutting down (your log files confirm this, sadly Playnite updated to 4.30 after the corruption already occurred).

**Comment by JosefNemec** [comment]
I found a way how to repair corrupted DB. Give me a day or two and I'll make a utility to fix your db if you don't want to delete and recreate your library.

**Comment by JosefNemec** [comment]
Fix tool is ready, see [wiki](https://github.com/JosefNemec/Playnite/wiki/Known-Issues#error-opening-database-unable-to-cast-object-of-type-litedbemptypage-to-type-litedbdatapage) for more information.

**Comment by alpal0** [comment]
Thank you for your prompt response and solutions! Worked for me! I love playnite by the way - great work
