### ISSUE TITLE
Fullscreen + "Exit on launch" option doesn't work

### ISSUE THREAD

**Issue by vrokolos** [JosefNemec/Playnite#682]
Can you please fix this? I'm trying to use playnite as a replacement to steam VR home and it messes up with my gamepad if I leave it open on fullscreen mode. On desktop mode it works fine and whenever I launch a game it closes playnite but on fullscreen mode it doesn't work.

**Comment by JosefNemec** [comment]
How is it messing up with your gamepad? Playnite should completely ignore gamepad inputs if the window is not used.

**Comment by vrokolos** [comment]
Well I'm not sure if it's playnite's fault or steam vr. Whenever I launch a game from playnite (haven't tested from somewhere else yet) I get both steam controller emulated keyb/mouse + gamepad motion from every button on the gamepad. That means when I press A it presses both A + Enter. If I launch the game directly through steam it works fine.

As I said I don't know if it's really playnite's fault but I don't want to keep playnite open anyway when I launch a game.

**Comment by JosefNemec** [comment]
Fixed in 4.5
