### ISSUE TITLE
DirectInput support in Fullscreen Mode

### ISSUE THREAD

**Issue by ClearStrelok** [JosefNemec/Playnite#684]
This would also mean Switch Pro Controller support since they both use DirectInput.

**Comment by DoganM95** [comment]
Any news on this? I am unable to navigate in fullscreen mode with a dualshock 4, which is frustrating..

**Comment by JosefNemec** [comment]
No news, you have to use some DirectInput to XInput wrapper until this is implemented.

**Comment by Ansem93** [comment]
Any hope to have this implemented? I have a ps4 controller and wanted to use Playnite as a launcher :(

**Comment by firinael** [comment]
checking in to say this is still sorely needed.

**Comment by jh0nny2k** [comment]
Just bumping this one up. I use DS4 when playing fighters. Thank you

**Comment by bukkaroo** [comment]
Adding support for this feature - DS4Win is ok, but leaves you with XBox prompts in games, when more and more support native PS prompts.

**Comment by BoxBoy7999** [comment]
bumping this cause ps5 controller no work.

**Comment by ChillyEmber** [comment]
bump, Switch controller doesn't work.

**Comment by JollyJive** [comment]
PS4 controllers don't work for me, even if i map it to a generic input controller with Steam Big Picture's Desktop Configuration.
I don't want to download extra firmware for this, almost every single game these days support PS4 controllers natively and perfectly, I don't want to potentially mess with everything that already works with extra firmware.

Why has this not been implemented yet? After 4 years of this issue no developer has even commented on it
Is it just impossible to implement?

**Comment by cnapolit** [comment]
For the sake of preserving relevant thoughts from discord, I'm posting this here as well.
It could be worth passing off the controller state (both DirectInput & XInput) to plugins so they don't have to poll themselves.

**Comment by S34NN** [comment]
> Adding support for this feature - DS4Win is ok, but leaves you with XBox prompts in games, when more and more support native PS prompts.

I recently came up with my own solution to this by using Special Actions within DS4Windows to switch between profiles on the fly with button combinations. I have mine set up with the default Xinput profile (emulated Xbox 360) and profile emulating a Dualshock 4. When using fullscreen Playnite I can switch to the Xinput profile to navigate it and launch a game, and then quickly switch to the Dualshock 4 profile before the game loads. 

For example I have my profile switching set to PS Button + R1 + X (Cross) to switch to Default Xinput. And PS Button + R1 + Square to switch to the Dualshock 4 profile. 

Profile switching this way has been working impressively well for me and switched back and forth immediately without any issues so far. Granted, my use case is slightly different as I have been using my Dualshock 3 with DS4Windows to emulate a Dualshock 4. I don't have a DS4 to test, but I'm confident there's a way to create a profile that reverts the controller back to its standard DS4 input, or perhaps a way to map just disabling the Xinput emulation profile to accomplish the same thing.

I know this is off-topic in relation to Playnite development, but just wanted to share what recently worked for me to overcome this limitation using other tools.

**Comment by Tyestor** [comment]
4 years later...imagine not having dinput support in your program in 2022 lmao. every emulator does. every modern game does. this is genuine cringe.

**Comment by fidelix** [comment]
@Tyestor I think they are open to pull requests...

**Comment by jh0nny2k** [comment]
It's targeted for the next major patch

**Comment by cnapolit** [comment]
> 4 years later...imagine not having dinput support in your program in 2022 lmao. every emulator does. every modern game does. this is genuine cringe.

Misattributing the goals of a one(ish)-man open-source project to what you specifically want out of it. Genuine cringe.

**Comment by beautyfree** [comment]
I'm new user of playnite and I join this thread to bump it. I use DualShock 4 and want support of it in playnite

**Comment by IliasWhoElse** [comment]
Bumper the bumpie bump

**Comment by JosefNemec** [comment]
Done in 10.30
