### ISSUE TITLE
Unable to edit game details

### ISSUE THREAD

**Issue by Gheb** [JosefNemec/Playnite#686]
When pressing F3 while highlighting a game, the screen for editing game details no longer is popping up. 

![playnite issue](https://user-images.githubusercontent.com/40475244/41745130-f8dc593a-7573-11e8-9924-d29dbb516c43.png)

**Comment by JosefNemec** [comment]
Hmm maybe it's popping up on different screen for some reason. Can you try to use `WinKey` + Arrows key combo to move it around?

**Comment by Gheb** [comment]
Tried using the WinKey + Arrows key combo method, but it looks to have made no difference.

**Comment by JosefNemec** [comment]
Can you post content of your [config file](https://github.com/JosefNemec/Playnite/wiki/Frequently-Asked-Questions#where-are-playnite-settings-located) please?

**Comment by JosefNemec** [comment]
Closing this for now since there's no response from original reporter. Feel free to reopen if more information is available.
