### ISSUE TITLE
Overwattch lancement issue

### ISSUE THREAD

**Issue by D3monya** [JosefNemec/Playnite#687]
error launch overwatch
[rapport bug overwatch.zip](https://github.com/JosefNemec/Playnite/files/2127652/rapport.bug.overwatch.zip)

**Comment by JosefNemec** [comment]
I think it is probably connected to #685. According to logs Playnite is trying to use PTR installation of Overwatch. Do you have PTR version installed?

**Comment by D3monya** [comment]
Non le ptr n'est pas installé

**Comment by JosefNemec** [comment]
Fixed in 4.40
