### ISSUE TITLE
folder scanning

### ISSUE THREAD

**Issue by lamedoo** [JosefNemec/Playnite#69]
add scanning the disk drive too. otherwise when i try to scan one disk it just gives all the executable on my pc

**Comment by JosefNemec** [comment]
I'm not sure I understand, if you select disk drive during folder scan, it will return all executables on that drive (that's how folder scan currently works, searching for all executables). What should be the difference between selecting folder or whole drive?

**Comment by JosefNemec** [comment]
I'm going to close this since I'm unable to do anything about it without more information. Feel free to reopen this if you have something more to add.
