### ISSUE TITLE
Voice control through Google Assistant/Google Home

### ISSUE THREAD

**Issue by themerchant** [JosefNemec/Playnite#691]
Please use search first to see if the issue is already opened. Thank you
I know this'll likely be very low on the list of priorities, but it would be great to have some kind of Google Home integration. Maybe through an IFTTT webhook?

Thanks

**Comment by JosefNemec** [comment]
How would this work actually? I can't think of some feature that would benefit this integration.

**Comment by themerchant** [comment]
It could work for voice control navigation. So you could say something like "Filter all Sony Playstation games". Or "Play the game Crash Bandicoot" to launch straight into the game. I'm already using voice control through an IFTTT webhook and Google Home at the moment. It sends an event to an Event ghost web server to launch specific things. So I can say, for example, "Hey Google, I want to play games" and it'll launch Playnite.

**Comment by Teutonic84** [comment]
What's this event ghost web server you use? I currently have IFTTT setup with google assistant to take a specific phrase with a text ingredient and then it creates a text file in dropbox with the text ingredient input. I then have a batch file on my PC that monitors the dropbox folder for the text file and reads its contents. Then loads other batch files based off of the contents. If there's a way to do this without using a text file and cloud storage that would make it easier i'd love to know!

**Comment by themerchant** [comment]
Eventghost is a free piece of automation software for Windows. It hasn't
been updated for a while, but it still works quite well and is pretty easy
to use. I'm using the Eventghost webserver plugin to run a web server. I
then created a very simple web page that runs on the web server with
hyperlinks that trigger actions in Eventghost. So with IFTTT, Google
Assistant is the "this" with webhook being the "that". The result is that
an event is generated in Eventghost (depending on the url I set in the
webhook), which then runs specific macros I've programmed. Some examples of
how I use this is to switch audio inputs by voice, launch youtube.com/tv in
a full screen chrome browser and switch the buttons on my remote to a
YouTube profile I created. And then of course, I also use it to launch
Playnite by either saying "I want to play games" or "it's game time".

**Comment by ArtexJay** [comment]
@JosefNemec I think it would make more sense to integrate Cortana as Playnite is available via all Windows PC, and Cortana is built into all Windows 10. It may also be easier to do as well. Voice control might make sense sometimes if you are away from the controller or setting it up.

**Comment by JosefNemec** [comment]
I'm closing this since I can say for sure that this is currently out of scope for project like Playnite. The extensions API should have everything available already if somebody wants to add this functionality via an extension.
