### ISSUE TITLE
Battle.net games not launching

### ISSUE THREAD

**Issue by JerBearMeadows** [JosefNemec/Playnite#692]
After the Battle.net app update, Playnite is no longer able to launch the games correctly. After clicking "play", it just says "launching..." until the game is either launched from battle.net or you cancel the launch. While the game is running, however, Playnite accurately tracks playtime and knows when the app is quit.
There is no error message that gets presented, so sorry I can't provide that, but I figured I should still mention that none of the games from the launcher function properly.

**Comment by JosefNemec** [comment]
Blizzard broke it: https://us.battle.net/forums/en/bnet/topic/20765466602

**Comment by JosefNemec** [comment]
Fixed in 4.31
