### ISSUE TITLE
Standardization or Cover Art sizes

### ISSUE THREAD

**Issue by priestofpsi** [JosefNemec/Playnite#697]
I have noticed that even though the majority of cover art downloaded is of same dimensions/ratio, there are a few games (primarily from steam) that do not have similar dimension ratios. I manually resolve this by editing the game, and downloading the metadata from IGDB, but I propose in downloading the metadata from both Steam and IGDB, and finding the nearest ratio'd cover art image  for consistancy, instead of just defaulting to the one.

Possibly having it as a default option, with the ability for users to 'disallow' this as it could take longer when downloading meta data.

**Comment by JosefNemec** [comment]
There are multiple issues on this matter already, if you have some ideas please post them there. Thank you
https://github.com/JosefNemec/Playnite/issues/580
https://github.com/JosefNemec/Playnite/issues/579
