### ISSUE TITLE
Database error

### ISSUE THREAD

**Issue by Dezknight** [JosefNemec/Playnite#700]
Started getting this error as of yesterday. There was no update to cause this unless it was a background install or something.

[Database Error](https://imgur.com/a/20GKfQF)

**Comment by JosefNemec** [comment]
Please see [this](https://github.com/JosefNemec/Playnite/wiki/Known-Issues#error-opening-database-unable-to-cast-object-of-type-litedbemptypage-to-type-litedbdatapage) for a solution.
