### ISSUE TITLE
Game import dialog improvements

### ISSUE THREAD

**Issue by xPandaemonium** [JosefNemec/Playnite#707]
First, why am I unable to import .zip files for emulated games?

When importing a number of .exe files there's a large portion of launcher, configuration and uninstall executables and it would be nice to scan for .lnk or shortcut files, that would save me time personally because I have already separated my non-client games using shortcuts. Navigate using the arrow keys and use "enter" or "spacebar" to toggle selection would also allow for quicker importing.

**Comment by JosefNemec** [comment]
Emulated games have to be imported from `Import emulated games` menu. You select emulator profile there and if it supports zip files then it should import zipped games.

I'll leave this open for your two other improvements (lnk stuff and shortcuts).

**Comment by DaemonPhoenix42** [comment]
Much appreciated,
Though regarding zip files, it doesn't seem that any emulator profiles is registering .zip's. 
![asdfghjkaa](https://user-images.githubusercontent.com/36192863/42683554-79bfd8a4-8642-11e8-851d-4c16ffd86970.gif)

I'v tried it with many different emulator Profiles and I have to unzip the files in order to get any reaction from the Import wizard. Any Ideas? I'd rather not unzip everything knowing that Applications such as RetroArch can handle .zip files.

**Comment by JosefNemec** [comment]
Looks like some RetroAarch profiles don't have zip in list of supported extensions. For now you can manually add them if you go to emulator settings dialog (from `Tools` menu). I'll update RetroArch profiles in next version.

**Comment by JosefNemec** [comment]
I had a look at updating RetroArch profiles but lot of them don't list zip files as supported file type even if the core supports it. I don't really know how to solve this, we generate Playnite profiles automatically from RetroArch .info files and they simply don't list zip files for lot of cores. I guess that we will have to start updating RA profiles manually and don't depend on .info files.

Would you be able to tell me what cores should support zip files, by looking at [this list](https://github.com/JosefNemec/Playnite/blob/master/source/Playnite/Emulators/Definitions.yaml#L592)?

**Comment by By6r9** [comment]
Retroarch supports zip/7z natively, will try to unpack data for every core, I think. It works most of the time, and when it doesn't you should blame upstream.

**Comment by JosefNemec** [comment]
I see, thanks for clarification. I will add zip and 7z to all RA profiles then.

**Comment by JosefNemec** [comment]
Will be done as part of #423

**Comment by Korb** [comment]
> "spacebar" to toggle selection would also allow for quicker importing.

I agree. Using the `space bar` to ✅ check and 🔳 uncheck a box is intuitive and productive.

@JosefNemec, did you decide not to implement this part of the issue of @daephx, or is it just not working for me in Playnite 10.34?
