### ISSUE TITLE
Themes - advanced support

### ISSUE THREAD

**Issue by JosefNemec** [JosefNemec/Playnite#71]
Second stage for UI customization - ability to change control style + UI layout.

**Comment by berserkwarwolf** [comment]
Will I be able to make something like [this mockup of Playnite Theme with Fluent design](https://i.imgur.com/cNL1R9M.jpg)?

**Comment by JosefNemec** [comment]
That looks pretty cool! And yes, you should be able to do it once theme support is in.

**Comment by evgdovg1996** [comment]
@JosefNemec Do you have plans in V.3 for adding integration with metacritic/ openccritic/gamerankings  as suggested by @berserkwarwolf ?

**Comment by JosefNemec** [comment]
No, not for 3.0, there's too much stuff in 3.0 already :)

**Comment by JosefNemec** [comment]
Released in 3.0
