### ISSUE TITLE
Start button cut off in fullscreen mode

### ISSUE THREAD

**Issue by ClearStrelok** [JosefNemec/Playnite#711]
The start button can be cut off on the left depending on what filter option is currently used. This is not a problem with the english localisation, but french and german are affected due to the text being longer. Moving the filter installed games button to the left could prevent this issue, if you don't plan on using that space for something else.

![sans titre-1](https://user-images.githubusercontent.com/38838369/42814056-4f143e5e-89c3-11e8-902c-fa518a9d480c.png)

**Comment by JosefNemec** [comment]
Done in 5.0
