### ISSUE TITLE
Implement support for game nesting.

### ISSUE THREAD

**Issue by Continous** [JosefNemec/Playnite#715]
Currently, all games are isolated from one another, and there is absolutely no way or method for Playnite to reasonably discriminate between a game that uses the same application but different arguments (such as Doom 3, which uses launch arguments to launch expansions) and an entirely different game. Similarly, Playnite has no reasonable method by which to deal with mods.

As examples I will be using Command and Conquer Generals: Zero Hour and Doom 3 Resurrection of Evil. These games are ideal examples as the perfectly represent how each extreme affects and manifests itself on and in Playnite.

First, and I believe most importantly, we should take a look at Doom 3 Resurrection of Evil. Doom 3 runs perfectly, and has no issues, with Playnite. But Resurrection of Evil has a few problems. As a comparison, here's a list of things you ideally want to happen:

- Playnite detects the game properly
- Playnite launches the game properly
- Playnite associates the game properly (IE, this is a Steam game)

However, currently Doom 3 Resurrection of Evil:

- Is not detected at all.
- Only launched correctly through user intervention.
- Will inherit any and all associations from Doom 3, accurate or otherwise.

So the problems should be somewhat obvious, but for those of you who don't notice them: Playnite cannot detect Doom 3 Resurrection of Evil, and cannot easily launch it without modifications to the launch procedure (launch arguments). Similarly, Playnite sees it no differently than the main Doom 3 game. This creates issues in that the game "profile" must be based on the original game's profile, and the user must, themself, discriminate between the base game and the expansion.

Indeed, the issue is minimal, but Playnite can minimize this fairly easily, and in doing so, not too far from being able to implement rudimentary modding support. My proposal is simple, and could also be used to improve sorting/grouping of Playnite. Playnite should, in my opinion, implement a "series/trilogy" system in which users are able to group games together under the same "profile", and the games are kept under a tree. The root of the tree will by default be the base game. The user can change what this root will be, but the other games will thus be children of this.

Here is an illustration of what I mean:

![Example](https://i.imgur.com/F1TcdgE.png)

**Comment by Continous** [comment]
For Doom 3 I was specifically talking about the non-Steam version (as the Steam version is, as you said, properly handled). And yes, ideally this issue should make #408 and #367 obsolete in that it addresses the issue, and I believe this can do it in a far more elegant manner. My idea is mostly to allow Playnite to properly handle nesting. If we could nest "games" it'd be far easier to properly integrate things such as Mod/DLC listings as well as "duplicate" copies. This could also enable better integration of non-standard games such as OpenMW or OpenRA, where the game is both different and identical to another.

Think of it as a long-term solution to #408 and #367

**Comment by JosefNemec** [comment]
I'm closing this since realistically this is not possible to implement in the way that's being proposed. We can't have nesting in game lists (for technical reasons) or link multiple games under one "master" game. Some general support for adding DLC/Expansion records to a game will be considered in #367.
