### ISSUE TITLE
Game description looks weird for certain text

### ISSUE THREAD

**Issue by cristi1990an** [JosefNemec/Playnite#717]
See how the text looks in the screenshot: 

![2018-07-21_15h46_03](https://user-images.githubusercontent.com/23399600/43035712-454af7cc-8cfd-11e8-9275-ba1a515d4e7c.png)

**Comment by JosefNemec** [comment]
This is not Uplay game issue, but it affects all games when description text has certain length.

**Comment by JosefNemec** [comment]
Released in 4.55
