### ISSUE TITLE
No more texts in menus after updating to v4.40

### ISSUE THREAD

**Issue by bettafo** [JosefNemec/Playnite#721]
Good day. First: great job and thank you a lot for Playnite. It has now replaced my previous favourite launcher (Cortex).
As the title says, menus, buttons, etc. do not display any text anymore after I updated Playnite to v4.40 via the update menu.
Screenshots attached.
If you need further logs/debugging info please let me know.
Cheers

![playnite1](https://user-images.githubusercontent.com/41757288/43281082-5fe43252-911b-11e8-9929-048d439d58e0.jpg)
![playnite2](https://user-images.githubusercontent.com/41757288/43281083-600226f4-911b-11e8-9f69-c6f475ff575e.jpg)
![playnite3](https://user-images.githubusercontent.com/41757288/43281084-6022cc60-911b-11e8-89c9-bd634977c1d2.jpg)

**Comment by JosefNemec** [comment]
This looks like you are using custom theme, they are not supported since 4.0 update. Use `F4` to open settings menu and switch back to one of built-in themes. Custom themes will be supported again after #510 rework in 4.6
