### ISSUE TITLE
Fullscreen mode still responds to button presses.

### ISSUE THREAD

**Issue by Nilot352** [JosefNemec/Playnite#723]
If a game is launched via controller on the fullscreen mode then during in-game presses another game will be launched.

**Comment by JosefNemec** [comment]
Does it happen with specific games or all of them? Because I'm not able to reproduce this with any of my games. I'm guessing this must happen with some specific game/emulator not removing focus from Playnite properly.

**Comment by Nilot352** [comment]
It happens with Mugen, try to test that.

**Comment by JosefNemec** [comment]
I'm still unable to reproduce it sadly :( But you can now let Playnite minimize its window when game is started (and restore it when game closes), which should fix it.

**Comment by JosefNemec** [comment]
Done in 5.0
