### ISSUE TITLE
Application crashed after clicking Finish on setup wizard

### ISSUE THREAD

**Issue by Amaya-hime** [JosefNemec/Playnite#724]
I ran through the set up wizard. After hitting Finish, it crashed with an error window. I don't see this issue already reported. 
[PlayniteError.zip](https://github.com/JosefNemec/Playnite/files/2242185/PlayniteError.zip)

**Comment by Amaya-hime** [comment]
Restarting Playnite results in the same error. I am unable to run it.

**Comment by JosefNemec** [comment]
Try installing update linked [here](https://github.com/JosefNemec/Playnite/wiki/Known-Issues#crash-on-startup---windows-7-only).

**Comment by JosefNemec** [comment]
Closing this since there's no response from original reporter. Feel free to reopen this if you encounter the issue again.
