### ISSUE TITLE
Close Steam/Origin/Epic, etc. launcher on close of game 

### ISSUE THREAD

**Issue by johnmarshall515** [JosefNemec/Playnite#726]
I would love to have a feature where playnite closes the launcher of the game played when you exit the game. It gets really annoying to have to manually close or have all these game launchers running in the background even after you have closed those games and unfortunately these launchers do not give you this option. I feel like playnite is the perfect program to do this since I already run it in the background to record play time.

Please consider,
Thanks!

**Comment by JosefNemec** [comment]
Duplicate to #622
