### ISSUE TITLE
Support for categories/consoles in full-screen mode

### ISSUE THREAD

**Issue by DannyGlover** [JosefNemec/Playnite#729]
Hello there.

Apologies if this has already been implemented or the request exists already. I wasn't able to find one.

The last time I tried Playnite, the full screen mode (that offers controller support) just displayed every single game in one list, whether it be a steam game, or an emulated game (say Nintendo 64).

Are there any plans to make the full screen mode flow like so?

- Full screen mode launched
- Category/Console browser (PC, Steam, Nintendo 64, Sega Genesis) etc
- Pick category/console
- Games from that category/console are then displayed

Thanks for all the great work.

**Comment by JosefNemec** [comment]
Yes, this is already planned in #520
