### ISSUE TITLE
Using touchscreen to swipe in fullscreen hides top visible row

### ISSUE THREAD

**Issue by rezorrand** [JosefNemec/Playnite#731]
When slowly wiping through the list in fullscreen, the top row of the list disappears after it crosses a certain threshold nearly immediately. This results in partially empty screen, where one would expect them to gracefully scroll out of view.

**Comment by rezorrand** [comment]
![screenok](https://user-images.githubusercontent.com/7170353/44114887-1992f56e-a015-11e8-97f1-b01b57e55350.jpg)
![screenbroke](https://user-images.githubusercontent.com/7170353/44114894-1d519b92-a015-11e8-8ba2-f5ab6e97106e.png)

**Comment by JosefNemec** [comment]
Why did you close this? This looks to me like legitimate issue.

**Comment by rezorrand** [comment]
Whoops, I'll put it to my sleepiness. Meant to just comment, but accidentally closed and commented. 🤦‍♂️

**Comment by JosefNemec** [comment]
Fixed in 5.0
