### ISSUE TITLE
InstallDir not working properly with relative paths

### ISSUE THREAD

**Issue by curdh** [JosefNemec/Playnite#735]
If i set the installation path of a game using relative path, then pressing the play button gives an error saying that the file (exe) couldn't be found.

With some games it works. I think it has to do with child folders. For example:

When a game InstallDir is: "..\GameFolder", then the play button works ( {InstallDir}\Game.exe ).
But when path is: "..\Folder\GameFolder" Playnite cant find the full path ( {InstallDir}\Game.exe ).

**Comment by JosefNemec** [comment]
Released in 4.5
