### ISSUE TITLE
Use exe's icon and platform icon with desktop shortcut

### ISSUE THREAD

**Issue by curdh** [JosefNemec/Playnite#736]
When creating a desktop shortcut for a game using the .exe's icon, the shortcut shows a default windows file icon (no icon). It would be great if it uses the icon from the exe file.

Something similar happens when there's no icon chosen in Playnite game profile but there's one for the game platform. Let's say i set an icon for N64 platform so every game in this platform shows this icon, but when i create a desktop shortcut it shows the default Playnite icon. 
Could this be changed to display these icons in a desktop shortcut?

**Comment by Webysther** [comment]
I needed to install an extractor to put some icons in the games.

**Comment by JosefNemec** [comment]
I don't think this will be possible unless Microsoft allows shortcuts to use png icons and not just ico files.

**Comment by JosefNemec** [comment]
I'm going to close this since this is a Windows limitation of not supporting other image formats for desktop shortcuts.
