### ISSUE TITLE
Clear & Close filter menu after Starting a game

### ISSUE THREAD

**Issue by rix1337** [JosefNemec/Playnite#738]
Use Case:
-With a huge library, I want to find a specific title
-I enter a few letters in the search box
-The filter menu opens
-I play the game and close it
-To return to the default view I have to press the "remove text from search box" and the "filter menu" button

Those are two clicks to much,... why not clear & close the filter after a title is started?

Please make this an option!

**Comment by JosefNemec** [comment]
Filter menu opening if you use main search box is a bug, I'll fix that.

**Comment by rix1337** [comment]
Oh, thank you for the quick fix. :+1:

**Comment by JosefNemec** [comment]
Released in 4.5
