### ISSUE TITLE
Adding c# code to skin element

### ISSUE THREAD

**Issue by menoro92** [JosefNemec/Playnite#742]
Hi
I added web browser to a skin xaml but i have a problem with bind some behind code to element. Tried some files in playniteui/windows but every time couldn't find it by name while compiling. Is it possible to add code in actual version even if i need to add wpf web browser into all skins? Also i have a question about updates there is support for reading custom config from my website/server? becouse I want to make some auto update for custom games.

**Comment by JosefNemec** [comment]
As it's stated on the wiki, theming is being [completely rewritten](https://github.com/JosefNemec/Playnite/issues/510) and I don't provide any support for it until that's done. Old themes won't be compatible with new system, so you would have to completely redo everything.

As far as the update stuff, you'll have to be more specific about what are you trying to do.

**Comment by menoro92** [comment]
Yes i saw that thread and I hoped there is a easy way to just bind it to some file just for testing till that will bu updated, im not good with c# file/class system, anyway i thout about it and new window would be even better for online chat. About new theme would be nice if there will be some stable(behind)/changable(playnite) wpf file possibility for one skin not only to make some importants elements unbreakable but to protection of some future api commands access from user side

I know there is a service for playnite but i mean more like there is already a way to read a multiple game configs or few tables from one config file without making modyfications beside the bool variable to app quit or not on install? Also how about multi-thread downloading if i would want to make wpf skin tab in future with update system like on steam it would be support 2 started downloaders in same window?

**Comment by JosefNemec** [comment]
What you want sounds more like an extension/plugin to me rather then what themes/skins should do. Themes should only affect application look and feel, not add new functionality.

**Comment by menoro92** [comment]
Yeah you right plugins would be much better to future playnite updating than source editing, but i want to learn some file structure. I dont know what end point will look like, but any protection of bindings and parametres from theme will be nice. Awasome job you are doing on this project, keep it up and thanks for answers.
