### ISSUE TITLE
Some games not imports from GOG

### ISSUE THREAD

**Issue by DrWowa** [JosefNemec/Playnite#743]
Playnite not import from GOG two specific games for me:
A.D. 2044
S.T.A.L.K.E.R.: Shadow of Chernobyl

No errors, no crashes, just that games not appear in library.
Syncing work, newly purchased games added successfully.

Looks like problem with naming pattern (C.A.P.I.T.A.L. with dots) for me.
Maybe another sources also affected, i not have similar games on anywhere.
I can enable debug somehow, without development env?

**Comment by JosefNemec** [comment]
Are those games installed? If not, can you try installing one of them and see if it imports them? The name shouldn't be a problem because games are imported by the internal GOG id, and names are not taken into consideration when importing games.

**Comment by DrWowa** [comment]
Deponia 2: Chaos on Deponia

**Comment by DrWowa** [comment]
I think, i found answer: this games not available for purchase anymore, they not have accessible store pages at the moment.

Sorry for unnecessary distraction =)

**Comment by JosefNemec** [comment]
Can you login on gog web and then open this link, and send me the content please?
`https://www.gog.com/u/<user>/games/stats?sort=recent_playtime&order=desc&page=1`

Don't forget to replace `<user>` part of the link with your [account name](https://github.com/JosefNemec/Playnite/wiki/How-to-get-GOG-account-name).

**Comment by DrWowa** [comment]
[stats.txt](https://github.com/JosefNemec/Playnite/files/2391242/stats.txt)

**Comment by Astuceman** [comment]
Same problem 
I have made a fresh install of my computer
I have last update of gog galaxy, windows and playnite as today

In gog galaxy I have 17 games and in playnite 9 only
I have refresh my database but nothing happened

What I know, it's that some games were patched after I have install gog galaxy and ask to to find my games inside a folder untouch on my second drive
Maybe that have change something ?

**Comment by JosefNemec** [comment]
@Astuceman If you don't see all installed games imported in Playnite then you need to go to Galaxy and repair installation from there. Galaxy sometimes doesn't properly register game as installed if you import games from folder rather then do fresh install.

**Comment by Astuceman** [comment]
You right
My problem is resolved

**Comment by Astuceman** [comment]
For me it's resolved

**Comment by JosefNemec** [comment]
Closing this since there's response from original reporter and it works now for Astuceman.
