### ISSUE TITLE
Feature Request: Battery indicator in full-screen mode

### ISSUE THREAD

**Issue by medallish** [JosefNemec/Playnite#744]
I'm thinking for specifically computer handhelds like the GPD Win 2, and future devices, although I'm sure some would like it on gaming laptops as well.

**Comment by teconmoon** [comment]
I second this! I google'd looking if this was a feature and the first thing I saw.

I have a GPD WIN 2 that auto-boots to an account that's set to run Playnite as a shell in fullscreen mode, and not having to switch back to the explorer.exe shell to check the battery would be great! Just in the upper-right corner by the time would be cool.

**Comment by JosefNemec** [comment]
Done in 5.0
