### ISSUE TITLE
Launch options.

### ISSUE THREAD

**Issue by Continous** [JosefNemec/Playnite#745]
Allow the possibility to add certain extra options to the "Play" button, or launch options.

One such possibility is to follow suite with Steam which gives you a pop-up prompt asking how you'd like to launch.

Another is to just add it to the "more" button.

**Comment by unrealed** [comment]
Even just having Playnite opening the Steam window with that launch option window opened would be nice. Ideally, whether that we get taken to that launch option window or not should be a toggle in the options.

**Comment by JosefNemec** [comment]
Will be done as part of #272
