### ISSUE TITLE
Missing Strings (4.5 Beta)

### ISSUE THREAD

**Issue by ClearStrelok** [JosefNemec/Playnite#754]
These can't be translated at the moment:

_Settings_ 
_Enabled_

(<sys:String x:Key="LOCMenuPlayniteSettingsTitle"> could probably be used for the first one) 

![sans titre-2](https://user-images.githubusercontent.com/38838369/45437282-d0e77b80-b6b4-11e8-9ab3-d6a6776b6c0e.png)

Also, this is pretty secondary and I'm not even sure this would be of use for other languages, but could you add a duplicate of  <sys:String x:Key="LOCGameIsInstalledTitle">Installed</sys:String> specifically for the game details window ?

![sans titre-4](https://user-images.githubusercontent.com/38838369/45437999-4142cc80-b6b6-11e8-9531-8b014052a4d1.png)

**Comment by JosefNemec** [comment]
Released in 4.5
