### ISSUE TITLE
Option to keep filter menu off.

### ISSUE THREAD

**Issue by iiviigames** [JosefNemec/Playnite#757]
When searching for a title to update (usually for artwork, in my case), I really don't need the filter window to pop up every time I do a search. Of course, I do like having the filter option for some cases, it's just most of the time, when it pops up on the left side, I instantly close it. I have my library sorted by console, so the search bar is usually enough on its own. So, this is just a request to turn the filter menu off and on when using the search bar.

**Comment by iiviigames** [comment]
This is why I tell everyone about Playnite. @JosefNemec , You're a great developer - in case no one has told you that lately.I know, I shouldn't post this here, but oh well. You're very good at what you do.

**Comment by JosefNemec** [comment]
Released in 4.5
