### ISSUE TITLE
Possibility to merge several games

### ISSUE THREAD

**Issue by janforster** [JosefNemec/Playnite#76]
Hi,

I was thinking that it would be nice to be able to merge several game records into one in case they are a duplicate. The use case where I find this useful is following: I have several games that I own across different platforms (mostly Steam and GOG) and I would like to see them as a single game instead of two.

I would imagine it would also be needed for the user to be able to define which of the different records of that game do they want to launch by default.

Hope you find this interesting.

Cheers

**Comment by JosefNemec** [comment]
Not a bad idea, I currently hide one of the duplicates so they don't appear in game list.

**Comment by janforster** [comment]
True, that's probably a good-enough solution when looking at it pragmatically :) . I will close the issue.
