### ISSUE TITLE
Time not recorded for Origin games if Origin is not running when you start the game

### ISSUE THREAD

**Issue by Donkeyfumbler** [JosefNemec/Playnite#761]
I've noticed that time played is not recorded for Origin games when you start the game from Playnite without Origin running first. The game launches OK, but not before Playnite has come back into focus (similar to what would happen normally when a game ends). 

If Origin is already running, the game starts, playnite stays minimised and playtime is recorded correctly.

**Comment by JosefNemec** [comment]
I've encountered this with some games as well, can you please post names of games that cause this for your (at least two or three examples)? Thanks

**Comment by Donkeyfumbler** [comment]
OK, so far I've had it with Fifa 19 demo and Battlefield 1. It seems to be fairly consistent in doing it when you launch the game without Origin runnning. It's only done it once (with BF1) when Origin was already running - all other times it has been OK for both games. I've only got a couple of other Origin games installed but I'll try those too and report back.

How does the detection work by the way? I have one program running (Cyborg Auto-profiler) that changes the mapping for my mouse buttons automatically on a per-game basis. It watches for the process running as well as it having focus before it activates the profile for a game (and it seems to work well) but you do have to tell it which process to watch for. Yours is obviously working a bit differently.

**Comment by Donkeyfumbler** [comment]
In that it's fully automatic I mean.

**Comment by Donkeyfumbler** [comment]
That makes sense. 

That said though, thinking about it further I do wonder whether it's really worth Playnite trying to track time for any of the clients that already track time themselves. 

For Steam and GOG I presume it syncs the time played with the Steam client anyway and overwrites whatever Playnite might have recorded. 

Origin, Uplay and Battlenet all track time themselves and while it is a real shame that data isn't available to sync, it's always going to be more accurate on those clients than on Playnite - is it really worth having a total time played on Playnite that doesn't compare to the time recorded by those game clients? 

Maybe it's just easier to keep the 'Last Played' date for those games, sync the time played with Steam and GOG and only work on monitoring time for other games (and other Playnite functionality? 

Just a thought anyway.

**Comment by JosefNemec** [comment]
Forgot to mark this as fixed with 4.59 release. Let me know if there are still some Origin games where it doesn't work properly.

**Comment by JosefNemec** [comment]
Reopen since I got reports that it still doesn't work properly with Battlefield V.

**Comment by Donkeyfumbler** [comment]
As discussed on Discord, this may have been because the games had been moved using symlinks.  I have opened a new issue for this as requested, so you may want to close this one now.
