### ISSUE TITLE
Comment/Notes Text Block game field

### ISSUE THREAD

**Issue by billybruiser** [JosefNemec/Playnite#766]
I would really love a simple text block when editing a game details, much like the Description box, where I can put my comments about a game and save that for later.  

Like, if I'm using Playnite years from now, I would like an easy way to view my thoughts about a game I might be wanting to replay.

**Comment by XN1TE** [comment]
Have to say this would be my number one request. To the point that I've even considered learning to make an extension to do this.

I feel like this is the one major feature I need before I start really using Playnite to organise my games library.

**Comment by unrealed** [comment]
I would also quite like this. I'd also like it to appear above the game's description in the Game Details and maybe even as a tooltip when mousing over the game's name/image in any of the 3 Views

**Comment by dusterherz** [comment]
+1 for that ! I'm using backloggery for the moment and I would love to replace it with playnite for notes

**Comment by JosefNemec** [comment]
Done in `devel8`.
