### ISSUE TITLE
Add abillity to remove categories

### ISSUE THREAD

**Issue by Halllker** [JosefNemec/Playnite#77]
Currently I can only add categories but can't really remove them, so any typo, test category, or not used one will remain there forever.

Or I didn't found how to do it, in which case, make it more visible.

**Comment by Binkie88** [comment]
If you click rightmouse on the game and then use set category you can select which category it should be in. Once an category is empty it will disappear.

**Comment by Halllker** [comment]
Yes, I have heard something like that. My mistake, wasn't really clear to me before. Thanks anyway.

**Comment by JosefNemec** [comment]
Released in 1.1, I've added tooltip describing behavior when settings categories.
