### ISSUE TITLE
Failed to import games from GOG: "an item with the same key has already been added"

### ISSUE THREAD

**Issue by DotsSalchow** [JosefNemec/Playnite#771]
I just updated to 4.5, and I got this incredibly puzzling notification whenever the GOG plugin is enabled. A clean reinstall (complete with deleting the database file as well as the folder in Appdata/Roaming) did nothing. It didn't matter if my GOG account was authorized or not.

**Comment by JosefNemec** [comment]
Can you to "About" menu and create diagnostics package for me please?

**Comment by DotsSalchow** [comment]
[diagnostics.zip](https://github.com/JosefNemec/Playnite/files/2423998/diagnostics.zip)
Done.

**Comment by JosefNemec** [comment]
This is weird, all your gog games have two installation records, one standard and one that begins with `GOGPACK`. This is the first time I'm seeing something like this. Did it work properly with 4.4?

**Comment by DotsSalchow** [comment]
Yes. Everything worked completely fine until the update.

**Comment by JosefNemec** [comment]
Can you please test it with this build? https://playnite.link/download/Playnite450gogfix.exe

**Comment by DotsSalchow** [comment]
This build works. It immediately imported every GOG game installed.

**Comment by JosefNemec** [comment]
Thanks for testing, I just pushed the fix as official 4.51 update.
