### ISSUE TITLE
Can't seem to receive metadata from IGDB

### ISSUE THREAD

**Issue by DotsSalchow** [JosefNemec/Playnite#774]
I'm really sorry to make another bug report this quickly after the last, but this is something I noticed only now. None of the games imported had their info auto-filled, so I tried to do it manually, only to discover that it somehow showed no results when searching IGDB for ANY game's metadata, whereas Wikipedia and Official Store metadata searches work completely fine.

[diagnostics.zip](https://github.com/JosefNemec/Playnite/files/2424321/diagnostics.zip)

**Comment by JosefNemec** [comment]
Can you go to Playnite's install folder and post content of `PlayniteUI.exe.config` file here?

**Comment by JosefNemec** [comment]
One more thing, are you using the custom build I gave you in other issue? I just notices that it has wrong config file, go to main menu and use `Check for Updates` to update to official 4.51. It should fix the issue.

**Comment by DotsSalchow** [comment]
Oh yeah, I was still using the test build. Will change the build and update it asap.
