### ISSUE TITLE
launch mechanism suggestion

### ISSUE THREAD

**Issue by xonk** [JosefNemec/Playnite#775]
Hi Josef,
I'm new here, so first, thanks for the great job you achieved on this launcher, congratulations.
I was wondering is there any way to seamlessly launch a game with a crossfade effect between playniteUI and the game itself ( in a first time just in the case where there is no 3rd party client inbetween ) ?
I explain:
I wish that when I launch my game,  playnite waits a certain amount of time before crossfading to the game ( lets say 10sec , but it could be a user defined option ) with a hourglass turning in the center of the screen just to say "Game is Loading".
The best would have been that playnite detect "automagicaly" that the game is running fullscreen before dropping to tray, just to help this small loading gap being more appealing .
Game loading would have a better look & feel than currently ( launch, playnite goes off ( minimized or something ) then windows desktop appears, then game goes fullscreen )

thanx

**Comment by JosefNemec** [comment]
The `detect "automagicaly"` part is the problem. It's very hard to find out what the game is actually doing or whether it is launched completely. But adding some configurable static delay shouldn't be a problem.

**Comment by xonk** [comment]
Yes.. I knew that will be the tricky part... :)  that's why I wrote "would have been" :)
but if implementing my suggestion is not that hard, them I hope it could do the trick
let me know

thx :)

**Comment by xonk** [comment]
the delay could also be a per game variable..   just to say : )

**Comment by xonk** [comment]
Guess you have time to have a look on that ?
[https://stackoverflow.com/questions/32244415/how-to-check-whether-application-is-running-fullscreen-mode-on-any-screen](url)

..or this function ?
[https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-monitorfromwindow](url)

what do you think? is this could help?

**Comment by JosefNemec** [comment]
Closing. The delay will be addable once #113 is done. The automatic detection for game's fullscreen state is something we just can't reliably implement.
