### ISSUE TITLE
Allow users to sort their games in specific ways

### ISSUE THREAD

**Issue by Halllker** [JosefNemec/Playnite#78]
Currently, you can filter out some games, categories etc, which is great.
But as a user I don't really want to have installed games hidden at any point,
so adding a feature that would allow me to order my games alphabetically, by number of played hours, or by platform would be great.

**Comment by drewbitt** [comment]
Wow, I just made this issue too then realized you beat me by a couple hours. Weird. Adding my comments

"Currently have sort by name and sort by last activity for category / store groupings. Should be able to put category/store in any order, not alphabetically or activity dependent."

A bit different than just adding new sorting options but under the same idea

**Comment by DDMythical** [comment]
You should be able to add your own tags and categories to games in my opinion; for easy searching.

**Comment by JosefNemec** [comment]
@DDMythical you can already set categories. I'm not sure about tags, too me they seem to have the same role as categories. But I will think about adding tags in future.

**Comment by JosefNemec** [comment]
Released in 1.1
