### ISSUE TITLE
Copied emulator profiles cannot be used

### ISSUE THREAD

**Issue by romano** [JosefNemec/Playnite#781]
This is the issue I have on a freshly unpacked Playnite, right after config wizard.

Steps to replicate the issue (my use case):
1. Have a Retroarch with gambatte core and two separate config files, one for Gameboy and one for Gameboy Color.
2. Import Retroarch emulator.
3. Duplicate the gambatte profile.
4. Configure both profiles appropriately.
3. Import some GB and GBC roms.

What happens:
Roms of the copied profile are still using the original profile. After editing the game's properties and manually setting it to use the copy, it switches back to original.

What is expected:
The profile should remain the way it was imported as, and/or the way it was set manually.

Affected versions 4.53 and 4.54

**Comment by JosefNemec** [comment]
Released in 4.55
