### ISSUE TITLE
New Features Request.

### ISSUE THREAD

**Issue by haseebxhekh** [JosefNemec/Playnite#783]
Please use search first to see if the issue is already opened. Thank you
First off, I just want to say that this is, by far, the best launcher that I've come across in terms of games. Exactly what I was looking for. However, according to me, there are a few additions/changes, that need to be made.

1) Adding a drop down menu for custom categories in filter search.

2) The ability to edit and/or remove custom made categories because I accidentally made a few typo's while making categories and now, there's no way to edit or remove them and seeing them is just annoying.

3) Playnite already applies filter accordingly if a user clicks on tags, genre, category(s) etc but no more than one using this method. For example, if a game has a tags which are "Adventure, Indie, Survival, Horror", I should have the ability to just click on 'Survival' and 'Horror' and have two (multiple) tag (Or any other) filters applied instead of one.

4) Playnite sometimes misses to detect if I stop playing a game and still shows the status as 'Running' which I have to cancel so that it says 'Play' instead.

5) I believe it should show stats like, total time played, last played on (Date and Time), Avg. FPS etc.

Keep up the good work!

**Comment by haseebxhekh** [comment]
****Update****

5) I wasn't using the latest version before as now I'm able to see the last played and duration so all that's left is the avg. FPS.

**Comment by RealityExit** [comment]
2.  Custom categories are auto-removed when there's no more games assigned to it. At least that's how it seems to function on my end. A time consuming and tedious workaround depending on how large your categories are.

**Comment by JosefNemec** [comment]
1. Already planned for next major version.

2. Works as RealityExit says. I agree that it's not very user friendly solution and it will be actually reworked together with 1.

3. I'll think about it. It already isn't very transparent what is happening if user clicks on those, so we have to carefully consider doing changes to it.

4. What games specifically? Some custom, emulated or games from Steam, Origin etc.? There will be some improvements for Battle.net and Origin games in next update. Other then that I will need more information.

5. Logging average FPS would be way to difficult to implement to make it reliable with all games. Plus I'm not sure that many people would actually use this. To me this sounds better to be implemented as a plugin.

**Comment by JosefNemec** [comment]
Closing this. 
- 1 and 2 will be done in 5.0
- 3 probably soon after that
- 4 I don't have enough information to do anything about it
- 5 way too technically difficult compared to what value it would bring
