### ISSUE TITLE
Allow to choose between multiple emulators of the same console

### ISSUE THREAD

**Issue by Pralom** [JosefNemec/Playnite#784]
Like choose between RetroArch, ePSXe, or XEBRA for example.

**Comment by JosefNemec** [comment]
Do you mean something like #288

**Comment by Pralom** [comment]
If you meant the "Launch with" part, then yes, similar to that. Maybe a window that lets you choose between them too. It's an open-minded idea that can be done freely when you add your touch into it.

**Comment by JosefNemec** [comment]
Duplicate to #288
