### ISSUE TITLE
Some descriptions are broken

### ISSUE THREAD

**Issue by ClearStrelok** [JosefNemec/Playnite#795]
This only seems to affect some descriptions which are using  _<ul/ul><lil/lil>_

![sans titre](https://user-images.githubusercontent.com/38838369/47207200-e7a38100-d38a-11e8-8e64-172e10f1ebfb.jpg)

**Comment by ClearStrelok** [comment]
Sure ! 

[Myth 2.txt](https://github.com/JosefNemec/Playnite/files/2495674/Myth.2.txt)

Oddly enough, other descriptions with similar formatting don't exhibit the same issues:

[Myth 3.txt](https://github.com/JosefNemec/Playnite/files/2495675/Myth.3.txt)

These are custom by the way, but Steam games are affected as well:

[Remember Me.txt](https://github.com/JosefNemec/Playnite/files/2495680/Remember.Me.txt)

**Comment by JosefNemec** [comment]
Fixed in 4.58
