### ISSUE TITLE
cant add no$gba via import or manually.

### ISSUE THREAD

**Issue by goldenpipes** [JosefNemec/Playnite#799]
Please use search first to see if the issue is already opened. Thank you

not sure if im doing it wrong but here is my config. when I hit save the window closes but its not available in the list of emulators:

![image](https://user-images.githubusercontent.com/6140137/47269525-b959a900-d524-11e8-929c-2b6d17d2af34.png)

**Comment by goldenpipes** [comment]
this is what I get after I hit save and go back to the emulators window: 

![image](https://user-images.githubusercontent.com/6140137/47269534-d8f0d180-d524-11e8-8d34-acd1796be2e3.png)

**Comment by JosefNemec** [comment]
Fixed in 4.58
