### ISSUE TITLE
Problems with first import of full libraries 

### ISSUE THREAD

**Issue by kwokykwoky** [JosefNemec/Playnite#8]
I installed Playnite and tried to import all my games. When import started, several problems occured.

1) GOG did not download anything - an error emerged (which I could not copy, so I rewrote it here):

Failed to download GOG library updates: Error converting value {null} to type 'System.Int32'. Path 'products[42].updates', line 1, position 29227.

2) Steam did download some games, but not all of them. I have more than 600 and number in Playnite says 57. I didn't notice any error message. For info: I have only 14 games installed.
![playnite](https://cloud.githubusercontent.com/assets/26931296/24714441/d0d5de4a-1a28-11e7-9ac5-fab377394292.jpg)

Origin seems to be ok.

**Comment by kwokykwoky** [comment]
Part 2 is ok. I put there my nickname, but profile with that custom ID was someone else's. I changed my custom ID in Steam profile and tried again. And it worked.
Make sure you really download your profile :)

**Comment by JosefNemec** [comment]
Fix released in 0.72
