### ISSUE TITLE
Fixing Game Description HTML button

### ISSUE THREAD

**Issue by DennoCoil** [JosefNemec/Playnite#800]
A feature request, but I've had to deal with some bad HTML code with one of the game descriptions I downloaded.

A work around was sending it to Calibre, the ebook manager, opening up a editor for EPUB's, paste in the code, and click Beautify Current File.  It made a pass through the whole HTML code and properly formatted the code, which allowed it to render properly and the code itself readable.

https://www.flickr.com/photos/33595961@N05/44587852365/in/dateposted-public/
https://www.flickr.com/photos/33595961@N05/45501449391/in/dateposted-public/

**Comment by JosefNemec** [comment]
I'm not sure this is worth implementing since in a long term I want to move away from HTML description to Markdown instead #397. I'll leave this open since I don't know when we get to it and adding some "beautify" button to game edit window might be easy to implement.

**Comment by JosefNemec** [comment]
Duplicate to #632
