### ISSUE TITLE
Overwatch don't start!

### ISSUE THREAD

**Issue by tesivo** [JosefNemec/Playnite#802]
ID CODE: 6011cd23-8d37-46b0-b170-4ebd033fbc00

**Comment by JosefNemec** [comment]
It crashes because Playnite is unable to find Battle.net installation. Can you try to reinstall Battle.net client to see if it fixes the issue?

**Comment by tesivo** [comment]
I tried reinstalling over the previous one, the Battle.net client but it does not seem to work

So I tried to remove Blizzard Launcher and then reinstall. Now work!!!

Thank you!
