### ISSUE TITLE
Add SteamGridDB metadata provider

### ISSUE THREAD

**Issue by JanPokorny** [JosefNemec/Playnite#805]
For uniformly sized game covers. API: http://www.steamgriddb.com/api/

Suggested by @grey-lovelace at https://github.com/JosefNemec/Playnite/issues/579#issuecomment-433185974

**Comment by JosefNemec** [comment]
Depends on #417

**Comment by JosefNemec** [comment]
Support for custom metadata providers was added in Playnite 6. You should be able to create custom plugin for this now, without any addition support from Playnite required.

**Comment by JanPokorny** [comment]
@JosefNemec I'm not currently going to work on it, you can add the "up for grabs" label

**Comment by cooperate** [comment]
I have an in-progress metadata plugin here
https://github.com/cooperate/SteamGridDBMetadata

Enjoy!

**Comment by JosefNemec** [comment]
I'm closing this since the extension is now available. Thanks @cooperate
