### ISSUE TITLE
Unable to download metadata for the game ">observer_"

### ISSUE THREAD

**Issue by azumukupoe** [JosefNemec/Playnite#806]
the Twitch version

**Comment by epeternally** [comment]
That's odd, it's working on my end in 4.58. Which metadata source are you trying to download from?

**Comment by azumukupoe** [comment]
![default](https://user-images.githubusercontent.com/31339007/47627962-614f2200-db76-11e8-9d98-ffe0cb2788ef.png)

**Comment by JosefNemec** [comment]
@azumukupoe  Why did you close this? Is it working now?

**Comment by azumukupoe** [comment]
Metadata download from IGDB can't be done automatically

**Comment by JosefNemec** [comment]
Fixed by changes on the backend.
