### ISSUE TITLE
Option to always sync play time

### ISSUE THREAD

**Issue by JosefNemec** [JosefNemec/Playnite#810]
Playnite currently only syncs play time from external library if current time is 0, otherwise it handles time tracking internally. This option would force Playnite to sync time always during library update.

**Comment by JosefNemec** [comment]
Done in 4.64

**Comment by MatuITA** [comment]
It does not synchronize the playing time yet (ex.: on steam I have 57 hours at gta v, but on Playnite it always starts from 0)

**Comment by JMD13** [comment]
Also an option to reset the time would be cool, for us that play RPG's and want to monitor our playthrough time.

**Comment by JosefNemec** [comment]
You can already reset playtime by editing game (from right-click menu) and changing it in `Advanced` tab

**Comment by Flupster** [comment]
Sometimes playnite doesn't get the time correct, A game I've been bingeing has 37hours on steam but only 18 hours on playnite, setting the game to not played in playnite and resyncing updates the time, wouldn't a simple 

``` 
if (reported_time > internal_playtime) {
  internal_playtime = reported_time
} 
```

be enough? I've not looked through the source myself but this should probably be changed

**Comment by JosefNemec** [comment]
Just enable `Prioritize play time for supported libraries` option and Playnite will use time recorded by Steam instead.

**Comment by lapo-luchini** [comment]
I too would prefer an option to use `max(local, remote)` too… as _most_ of the times Steam time is more correct but sometimes local playtime is more correct than remote one (e.g. playing offline Steam time can get not updated).

**Comment by VirgileVILE** [comment]
> Just enable `Prioritize play time for supported libraries` option and Playnite will use time recorded by Steam instead.

Hi. I'm looking for this option in the days menu, no way to find it...

**Comment by JosefNemec** [comment]
@VirgileVILE  First screen in application settings.

**Comment by wrilliam** [comment]
> @VirgileVILE First screen in application settings.

Hello. I'm using the 10.19 version, and I can't find this option here. Was it taken off?

**Comment by JosefNemec** [comment]
![image](https://github.com/JosefNemec/Playnite/assets/3874087/2d095167-e9e0-4c87-9028-42216b5f1298)
