### ISSUE TITLE
Selector on game covers at start-up

### ISSUE THREAD

**Issue by iolivier87** [JosefNemec/Playnite#812]
Hello,

I suggest a little adjustment : 
When the app starts in desktop mode, the selector (for keyboard or gamepad) is focused on list/cover/details. I think it would be more convenient to have it on the game covers.

On keyboard, it can be changed with Tab, but with a gamepad you are stucked on list/cover/detail...
Otherwise, adding an equivalent to Tab button on gamepads in desktop mode could be useful.
 
Thanks a lot for this awesome app !

**Comment by JosefNemec** [comment]
Desktop mode doesn't officially support controller and there are no plans to support it. The UI structure is just way too complicated to make it reliable support control scheme with game pad.
