### ISSUE TITLE
Planyite uses a shortcut's icon as window icon

### ISSUE THREAD

**Issue by PhrozenByte** [JosefNemec/Playnite#813]
I've looked into #354 again and it seems like the actual problem is that Playnite uses the icon of the shortcut as window icon that is used to start Playnite.

For example, I've a desktop shortcut for GTA V on my desktop. If Playnite isn't running yet, clicking on that desktop shortcut starts Playnite (and Playnite will then start GTA V, but this isn't relevant here). Playnite now uses the icon of the desktop shortcut as window icon, i.e. the logo of GTA V.

You can reproduce this with any shortcut: If Playnite isn't runnig, Playnite uses the icon of the clicked shortcut as window icon. Just copy a random Playnite shortcut (for Playnite itself, not for a game), change the shortcut's icon and start Playnite with it - Playnite's window icon will be the one of that shortcut.

![](https://user-images.githubusercontent.com/920356/34319561-c78bd9d0-e7e5-11e7-9da8-29e259b694f3.png)

**Comment by JosefNemec** [comment]
Please don't open duplicate issues, better to comment in existing one and reopen it. As I said in #354, this is a Windows feature/bug and I can't do anything about it without completely reworking how game startup is handled.

I've opened #814 to look at better ways how to handle shortcuts, but I'm not sure if it will fix this specific issue.

**Comment by PhrozenByte** [comment]
I've opened a new issue because it is a different issue: #354 (and #814) are specifically about starting games, however, as I've found out, the problem is **not** related to starting games.

The issue is not about game startup at all, that's the reason why I've openend a new issue. Just take Playnite's normal shortcut (first shortcut in the *third* row from below on my screenshot): Change the shortcut's icon to e.g. the one of Firefox and Playnite will use Firefox's icon as window icon. No game starting involved. It seems like Playnite doesn't explicitly set the window icon to use, so the application/Windows falls back to the shortut's icon.

btw: non-contributors can't re-open issues :wink:

**Comment by JosefNemec** [comment]
Are you sure this is not how all applications work, have you tested this with other apps? To me this looks like a Windows feature, because Playnite does explicitly set application icon in its manifest.

Also it doesn't matter if it's game shortcut or application shortcut, both currently start Playnite executable in the same way.

**Comment by PhrozenByte** [comment]
> Are you sure this is not how all applications work, have you tested this with other apps?

Yes, I'm sure. Just try it yourself: Neither Steam, nor GOG Galaxy, nor Firefox, nor LibreOffice show this behavior. They all use their own window icon, no matter of the shortcut's icon that was used to start the application. I'm no .NET developer, so no idea how this is done with .NET, but there obviosuly must be a way to do it, otherwise other applications would show the same behavior.

> Also it doesn't matter if it's game shortcut or application shortcut, both currently start Playnite executable in the same way.

Exactly. That's why this issue isn't related to game startup, but Playnite's startup process itself.

**Comment by JosefNemec** [comment]
I have tried it myself, the problem is that I can't reproduce it. No matter what icon is set to .lnk shortcut, Playnite always shows its own icon. I googled a bit and I haven't found any mention of this behavior anywhere. I really don't know what to do with this.

#814 should in theory fix this when launching the game, because we won't be starting it via Playnite executable directly (there won't be any link between .lnk shortcut and Playnite's executable).

**Comment by PhrozenByte** [comment]
Did you make sure that Playnite isn't running when you click the shortcut? This only happens if Playnite isn't running and the shortcut actually starts Playnite. I'm using Windows 10 Pro x64 1803.

**Comment by JosefNemec** [comment]
Yes, I'm aware that it wouldn't occur if it's already running.

**Comment by PhrozenByte** [comment]
I just reproduced this on both another Laptop and a VirtualBox VM, both running Windows 10. Playnite will always use the shortcut's icon as window icon. #814 won't fix the issue, it will just "hide" it by adding more complexity. Since Playnite is the only application I know having this issue, it's standing to reason that it must be a bug in Playnite.
