### ISSUE TITLE
Use URL browser protocol to create desktop shortucts

### ISSUE THREAD

**Issue by JosefNemec** [JosefNemec/Playnite#814]
Desktop shortcuts created from Playnite currently start game by starting Playnite executable directly, which has a side effect described in #354. Using browser protocol to start the game (support for something like `playnite://start/12321`) would probably fix this (but it needs to be tested).

More investigation is needed if it's really worth the effort. Also I'm not sure if registering `playnite://` requires elevated rights, which would be a problem.

**Comment by JosefNemec** [comment]
Update, it should [be doable](https://stackoverflow.com/questions/29509624/can-i-register-a-custom-url-scheme-without-administrator-elevation) without elevated rights.

**Comment by bburky** [comment]
If this gets implemented, you could add install and uninstall actions too: `playnite://install/12321/` `playnite://uninstall/12321`. And maybe a way to trigger each of the game's play actions playnite://start/12321?playaction=1` or whatever.

Currently my non-Steam shortcuts plugin is too much of a hack to do this, but someone asked if it could run installers too: https://github.com/bburky/playnite-non-steam-shortcuts/issues/1. A URL scheme for installation would help I think.

**Comment by JosefNemec** [comment]
Should be done after #1133 is finished.

**Comment by JosefNemec** [comment]
Done in devel7 branch (future Playnite 7).
