### ISSUE TITLE
Include .lnk files when scanning for game executables

### ISSUE THREAD

**Issue by akose1975** [JosefNemec/Playnite#815]
I want to add a folder with game shortcuts as a group, is it possible ?

**Comment by JosefNemec** [comment]
It's not possible currently, Playnite only scans executables, not .lnk files. It should be fairly easy to add this.

**Comment by rubin55** [comment]
@JosefNemec This might be a cool issue to start on for myself; Can you point me in the right direction as to where the scanning feature lives? Which sln should I open (I'm using Rider)?

**Comment by JosefNemec** [comment]
There's only one solution for Playnite: `Playnite.sln`. Scanning is done in `InstalledGamesViewModel`, lnk parsing is already implemented and used for example when dropping .lnk files to main window in `DesktopAppViewModel`.

BTW I don't know if the solution/build will work in Rider. I have no idea if it properly supports projects that use WPF.

**Comment by JosefNemec** [comment]
Done in Playnite 8.
