### ISSUE TITLE
After update, Playnite can't access database

### ISSUE THREAD

**Issue by Ultracoolguy** [JosefNemec/Playnite#825]
Here's the screenshot:
![bug](https://user-images.githubusercontent.com/19539392/48452134-ff9cd380-e783-11e8-927a-9e8bd8833b25.png)

And here's the diagnostic package ID: 12e7e894-8eeb-4e67-834c-ca09a8bff048

If you need anything else lemme know :)

**Comment by JosefNemec** [comment]
This is sadly caused by issues in old database format that new update is trying to replace. Try using [DbTools](https://github.com/JosefNemec/Playnite/wiki/Known-Issues#error-opening-database-unable-to-cast-object-of-type-litedbemptypage-to-type-litedbdatapage) utility to fix the issue.

**Comment by JosefNemec** [comment]
Then I'm afraid the only solution is to delete the library file (location is in Settings -> Advanced) and let Playnite recreate it.

**Comment by Ultracoolguy** [comment]
Ok. Thanks for the help!
