### ISSUE TITLE
Unable to launch battle.net games on spanish deployment

### ISSUE THREAD

**Issue by Korjam** [JosefNemec/Playnite#829]
This message is displayed on notifications trying to run a battle.net game:

> Cannot start game, Battle.net launcher is not installed properly.

Indeed the battle.net launcher is working properly and installed on *C:\Program Files (x86)\Blizzard App*, but the spanish display name is *Aplicación de Blizzard* instead of *Blizzard App*.

**Comment by JosefNemec** [comment]
Can you go to "About" menu and create diagnostics package for me please?

**Comment by JosefNemec** [comment]
Fixed in 4.61

**Comment by Retr0Pixel** [comment]
Hi, even if closed, i have the exact same problem using a german installation where the path to battle.net is called "C:\Program Files (x86)\Battle.net"
It works fine on its own and Games get detected.
This is the diagnostics package code: C:\Program Files (x86)\Battle.net
