### ISSUE TITLE
Missing LOC strings

### ISSUE THREAD

**Issue by PhrozenByte** [JosefNemec/Playnite#830]
There are some missing LOC strings in the extensions page of Playnite's settings:

https://github.com/JosefNemec/Playnite/blob/2a14e70acd956066574e98e34fafa1adb4e5de3f/source/PlayniteUI/Windows/SettingsWindow.xaml#L420
https://github.com/JosefNemec/Playnite/blob/2a14e70acd956066574e98e34fafa1adb4e5de3f/source/PlayniteUI/Windows/SettingsWindow.xaml#L424
https://github.com/JosefNemec/Playnite/blob/2a14e70acd956066574e98e34fafa1adb4e5de3f/source/PlayniteUI/Windows/SettingsWindow.xaml#L428

**Comment by JosefNemec** [comment]
Fixed in 4.62
