### ISSUE TITLE
Playnite fullscreen with customed DPI

### ISSUE THREAD

**Issue by iolivier87** [JosefNemec/Playnite#831]
Hi, I use Playnite with a 1080p TV and the Windows UI is at 150%.

By default, the Playnite Fullscreen image is a bit larger than my screen. Then, the bottom right is cropped :
 ![playnite-default](https://user-images.githubusercontent.com/21123707/48968728-c9691a80-eff3-11e8-857a-d5470c3e5e0d.JPG)

I could change the program properties in order to correct the fullscreen DPI by Windows, but the image is now blurred : 
![playnite-windows ppp correction](https://user-images.githubusercontent.com/21123707/48968729-c9691a80-eff3-11e8-8eaf-932aa2d47852.JPG)

Not a big issue, but it's still better to report.

**Comment by JosefNemec** [comment]
New version 4.62 added option to disable DPI scaling, which fixes this issue. Just note that it will disable scaling in Desktop mode as well. Currently Desktop and Fullscreen modes run from the same process, which means there's no way to just disable it for Fullscreen mode. I will be separating them in next major version.

**Comment by iolivier87** [comment]
I confirm that the fullscreen works fine now. Thank you very much !
