### ISSUE TITLE
Importing Library from another PC does not retain categories.

### ISSUE THREAD

**Issue by DiogoAndreBotas** [JosefNemec/Playnite#832]
I want to export my Playnite library from my desktop PC to my laptop PC. It works just fine, but the categories are not transferred. Am I doing something wrong? Or are they not supposed to be exported? I don't really want to be manually categorizing over a thousand games again...

Appreciate all your amazing work though! Loving the program.

**Comment by JosefNemec** [comment]
Categories are stored in the same [library folder](https://github.com/JosefNemec/Playnite/wiki/Frequently-Asked-Questions#where-can-i-find-library-file-with-all-games) as other library data, if you transfer the whole folder then everything should stay the same (only application settings won't be transferred). Are you sure you just didn't switch to grouping view that groups by categories?

**Comment by DiogoAndreBotas** [comment]
So, I moved everything located in %AppData%/Playnite to my laptop and the categories appeared just fine. Only moving the "games" folder did not work though.

Thanks a lot for the quick response! Closing the issue. Have a good one!
