### ISSUE TITLE
Close Uplay window when game exits

### ISSUE THREAD

**Issue by JosefNemec** [JosefNemec/Playnite#833]
Uplay has unfortunate "feature" which causes Uplay window to always open once you exit the game. This causes issues when using fullscreen mode with controller, because there's no standard way how to close Uplay with just controller, making it impossible to get back to Playnite window.

**Comment by thomaschampagne** [comment]
Yes! Or from another point of view,  It can be handled at opening:

If you start a **steam** game then kill others instance of origin, battle.net, uplay, ... (if they are running).

(I landed here from #1073)

**Comment by JosefNemec** [comment]
Duplicate to  #1073
