### ISSUE TITLE
Indicate if a game in an external drive is unplayable because the drive is not connected.

### ISSUE THREAD

**Issue by Pralom** [JosefNemec/Playnite#834]
When an external drive is not connected, show the game as unplayable (Can't click play, show a message or make it just like the play time when you click the game's info). When it's connected, just say it is connected (That means it detected the game from an external source).

**Comment by JosefNemec** [comment]
Easiest way would probably be to check if installation path of game exists and set installation state based on that on application startup (and when updating library).

**Comment by Continous** [comment]
That wouldn't be a good solution for people using hot-swap storage, or FTP-style storage.

**Comment by JosefNemec** [comment]
Will be done as part of #1065
