### ISSUE TITLE
Add smooth scrolling option

### ISSUE THREAD

**Issue by JosefNemec** [JosefNemec/Playnite#835]

**Comment by lionnesquaer** [comment]
@JosefNemec Please, add smooth scrolling if it possible! Will be much better usability exp!

**Comment by fehbari** [comment]
> Please, add smooth scrolling if it possible! Will be much better usability exp!

Second that. Would _love_ to see smooth scrolling added

**Comment by OsoaGitHub** [comment]
Any updates on this? This would be a really good feature imo

**Comment by JosefNemec** [comment]
Done in devel.
