### ISSUE TITLE
Cut windows back

### ISSUE THREAD

**Issue by SimN7** [JosefNemec/Playnite#836]
Hello,

First of all, congratulations for this great software. However, I have a rather awkward problem. After 1 hour and a few minutes of play (Forza Horizon 4 with Windows Store or Just Cause 3 with Steam) freeze games and then cut windows back.
I played Just Cause throwing it directly by Steam and no cut.

Otherwise continue like this the software is really good;)

**Comment by JosefNemec** [comment]
Please edit the issue to be in English.

**Comment by SimN7** [comment]
(Sorry if there are faults I used Google translation)

Hello,

First of all, congratulations for this great software. However, I have a rather awkward problem. After 1 hour and a few minutes of play (Forza Horizon 4 with Windows Store or Just Cause 3 with Steam) freeze games and then cut windows.
I played Just Cause throwing it directly by Steam and no cut.

Otherwise continue like this the software is really good;)

**Comment by JosefNemec** [comment]
I don't understand what are you saying. Are you saying that Playnite makes games freeze and than crash to desktop? Playnite doesn't interact with games in any way after they are started, so I doubt that Playnite is responsible for any crashes you are experiencing.

**Comment by JosefNemec** [comment]
Closing this since there's was no additional information provided.
