### ISSUE TITLE
Web based games link

### ISSUE THREAD

**Issue by ArtexJay** [JosefNemec/Playnite#838]
Add the option for Playnite to link to a web-based game to play. eg. Mario Crossover. Pressing the play button would attempt to open the link thus opening the browser to the link.
http://supermariobroscrossover.com/resources/super-mario-bros-crossover.84/

**Comment by JosefNemec** [comment]
This is already supported, set play action to `URL` type and `Path` to desired URL.

**Comment by ArtexJay** [comment]
My apologies then 😅 I missed that
