### ISSUE TITLE
Allow users to set a custom sorting title in Edit Game Details

### ISSUE THREAD

**Issue by EitchKeii** [JosefNemec/Playnite#84]
Some game franchises have weird naming schemes and don't really sort chronologically.

Basically what I'm saying is, instead of sorting by the visible name like this:
FINAL FANTASY IV
FINAL FANTASY IX
FINAL FANTASY V

We would have the option to change it to sort like this:
final fantasy 4
final fantasy 5
final fantasy 9

**Comment by drewbitt** [comment]
Why not rename them with Playnite to have actual numbers? Also could be solved with a more customized sort, see #78. I don't see why Playnite should include an option for such a specific thing imo

**Comment by EitchKeii** [comment]
That doesn't work that well in say in some franchises I'd say. Tomb Raider is a decent example where the previous game was called Rise of the Tomb Raider. I'd like the name to stay Rise of the Tomb Raider but still be sorted right next to the first game which is just called Tomb Raider.

I would also argue that just renaming it with numbers or whatever simple doesn't look very good, and that's something I personally care about.

**Comment by JosefNemec** [comment]
This is very specific and would require a lot of changes to sorting code, but I may loot into this in future. No promises tho :)

**Comment by JosefNemec** [comment]
Scratch my last comment, appears to be easy to add this functionality. I might squeeze this into 3.0 release.

**Comment by elouataoui** [comment]
> I'd like the name to stay Rise of the Tomb Raider but still be sorted right next to the first game which is just called Tomb Raider.

I think one way to do this is to add information about the franchise to the game. IGDB already provides a "series" field so that can be used, then you can simply sort by franchise and then by release date for every game in the franchise. It would solve both the Final Fantasy case and the Tomb Raider one.

**Comment by JosefNemec** [comment]
Released in 3.0

**Comment by evgdovg1996** [comment]
Playnite has bug in list mode - the name changes to sorting name
https://imgur.com/kHkTclH

**Comment by JosefNemec** [comment]
@evgdovg1996 Thanks for the report, I'll fix it in next update.

**Comment by JosefNemec** [comment]
@evgdovg1996 Until update is released just edit line `2435` in `Modern.xaml` file and change `Binding Name` to `Binding DisplayName`
