### ISSUE TITLE
Didn't copy file d3dcompiler_47.dll

### ISSUE THREAD

**Issue by Cossack13** [JosefNemec/Playnite#85]
Installer is broken:
![default](https://user-images.githubusercontent.com/16056285/29492867-2eb13c48-85b4-11e7-9653-2eab8db4629d.PNG)

**Comment by JosefNemec** [comment]
I'm unable to reproduce it, even when trying exactly the same installation path. Does it at least install to default path?

**Comment by JosefNemec** [comment]
Closing as there's no additional information from reported, also might be solved once we switch to Inno setup in #96
