### ISSUE TITLE
Pull up exit family view in Steam instead of showing error message.

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [JosefNemec/Playnite#851]
When I try an launch a game that is not in the Steam Family View whitelist, Steam pops up a message that says the game is restricted by Windows Parental Controls.
![blocked by parental controls](https://user-images.githubusercontent.com/38865330/49613599-91f05b80-f96d-11e8-9cad-a28d66052bd6.PNG)

Games in the whitelist work normally, and all games work normally when family view has been exited with a pin.

Preferably, Playnite would detect that the game cannot be run due to family mode, then open the Steam exit family view window where the user can enter the pin to exit Family mode, then try relaunching the game.

Additionally, Playnite shows a different message when trying to install on non-whitelisted game when Steam is in family mode. Oddly enough, this does not affect uninstalling.
![unavailable in family mode](https://user-images.githubusercontent.com/38865330/49614155-0c6dab00-f96f-11e8-890b-b47b445cff43.PNG)

**Comment by TheCakeIsNaOH** [comment]
I found out that this affects not only steam://rungameid/<gameid> that Playnite uses but also trying to run the .exe manually. So I contacted Steam support, and ask about the message and they forwarded the info to the development team. 

So this might be fixed on Steam's end in the not too distant future.

**Comment by JosefNemec** [comment]
According to your description this is a Steam issue not a Playnite one => Closing.
