### ISSUE TITLE
Setting for periodic update times

### ISSUE THREAD

**Issue by chr0max** [JosefNemec/Playnite#853]
Hi,

it´s wonderful that this free application is updated to often, but I would like to have a option to set the update period to a week or month. Because everytime I start it, I get this update screen. But the app works perfectly for me, I just want to start a game. Another possible solution would be a silent update system in the background, like browsers do. I would use it.

Thanks for the work.

**Comment by JosefNemec** [comment]
We are completely changing how update notifications are being delivered in 5.0, making them less obstructive. I don't want to add an option to delay update notifications because updates are important. They can contain important security fixes that you shouldn't miss.
