### ISSUE TITLE
Creating multiple (desktop) shortcuts at the same time

### ISSUE THREAD

**Issue by NilsBergmann** [JosefNemec/Playnite#856]
You can create a desktop shortcut for a game via `Right click` -> `Create Desktop Shortcut`.
Sadly, this option is missing when multiple entries are selected.

Especially after adding emulated games, which dont create shortcuts like steam games do, being able to create a shortcut for all of them at the same time would be really handy for later launching them via other means (e.g the windows start menu, wox, launchy, etc).

**Comment by samusaran** [comment]
Regarding Wox launcher specifically, it's possibile to develop an addon that lets you open Playnite games. There are already a couple for Steam.

**Comment by darklinkpower** [comment]
I've made this as an extension while this is natively added. You can create shortcuts for your selected games in any directory https://playnite.link/forum/thread-251.html

**Comment by JosefNemec** [comment]
Done in `devel`.
