### ISSUE TITLE
Import from Steam fails

### ISSUE THREAD

**Issue by bastafidli** [JosefNemec/Playnite#857]
Please use search first to see if the issue is already opened. Thank you
First time Playnite user. Went through first time setup after installing Playnite for the first time. Created Steam API key and entered domain name (it wasn't clear if I should or not). 
After completing setup and downloading metadata I see red exclamation point in the corner of the window. 
When I click on it I see error
"Failed to import games from Steam.
Value cannot be null.
Parameter name: String"
The same happens if I go to Menu -> Update game library -> Steam

**Comment by JosefNemec** [comment]
Can you post screenshot of your steam settings?

**Comment by bastafidli** [comment]
> Can you post screenshot of your Steam configuration settings?

![image](https://user-images.githubusercontent.com/2342273/49709704-acdbfd80-fc03-11e8-99d8-40cbb31eb221.png)

**Comment by JosefNemec** [comment]
Please go to `About` menu and create diagnostics package for me, thanks.

**Comment by Romarain** [comment]
What domain name should we put in the Steam API Key form ?
Our domain name (our website ? Our ddns address pointing to our home ?), or yours ?

**Comment by JosefNemec** [comment]
@Romarain It doesn't matter, put anything you want there. It only matters if you would plan to build web based app with that API.

**Comment by SirBirdius** [comment]
HI @JosefNemec I am also getting this issue. Just got playnite last night, love it so much thanks to you and all others that have made this (Y)

**Comment by JosefNemec** [comment]
@SirBirdius Make sure that you are setting up [proper user name](https://github.com/JosefNemec/Playnite/wiki/How-to-get-Steam-account-name), it's not the same as your login name. Overall I recommend using `Local User` option, that should link your account properly every time.

**Comment by bastafidli** [comment]
> I also experienced this error when syncing Steam: "Failed to import games from Steam. Value cannot be null. Parameter name: String"
> 
> This was caused by having an incorrect Steam account name. (I also had an API key listed, even though my Steam account is Public - I'm not sure if this made a difference.)
> 
> When I corrected the account name, I no longer saw the error when syncing Steam.
> 
> The term "account name" is a little confusing in this context. I assumed it was the account name I use for signing in to the Steam client. But actually Playnite is asking for the "Custom URL" value, not the Steam account name. This is only obvious when the user clicks the link "What's my account name?"
> 
> Please may I suggest that this dialog is reworked so it's less ambiguous. I'd suggest not using the term "account name".
> 
> P.S. Playnite is awesome. Thank you so much!

After I used the correct account name, the problem was fixed. I do recommend improving the dialog to make this clearer. Thanks for the Playnite.

**Comment by JosefNemec** [comment]
Thanks, I improved the settings dialog for next version.
