### ISSUE TITLE
Application can be stuck on exit

### ISSUE THREAD

**Issue by JosefNemec** [JosefNemec/Playnite#859]
Playnite tries to cancel background operations (account sync, metadata download etc.) first before exiting and then closes afterwards. This cases issue if the background operation gets stuck and is unable to be canceled. We should add some timeout to exit operation and forcefully close if we reach it.

**Comment by Syzygy2048** [comment]
Since this issue is super annoying. When can we expect this to be released?

**Comment by JosefNemec** [comment]
Fix will be in 5.0 release.

**Comment by Syzygy2048** [comment]
I'm more interested in a rough date or timeline. This is a big issue for me and if the fix is far off, I would rather stop using Playnite than continue dealing with this issue.

**Comment by JosefNemec** [comment]
Couple weeks.

**Comment by JosefNemec** [comment]
Done in 5.0
