### ISSUE TITLE
Spaces added when using comma in filters

### ISSUE THREAD

**Issue by supergeorg** [JosefNemec/Playnite#861]
If you enter a comma into most filter box, it gets automatically deleted.
If you enter a comma after a word into most filter boxes, for every letter you write, a space will appear behind the comma. This can be related to the issue #779, which I also encountered. (using 4.63)

The affected filter boxes are:

- Genre
- Platform
- Developer
- Publisher
- Category
- Tag

Is multiple filters supported, i.e. showing Wii and GCN games? I tried this by seperating the categories with a comma and thus found this bug.

**Comment by Mates1500** [comment]
I could take a look at this issue if nobody else is working on it.

**Comment by JosefNemec** [comment]
I'm already fixing this for next update, together with #779.

**Comment by JosefNemec** [comment]
Fixed in 4.64
