### ISSUE TITLE
Steam not importing unistalled game

### ISSUE THREAD

**Issue by Ithoh** [JosefNemec/Playnite#862]
Please use search first to see if the issue is already opened. Thank you

Hello josef, I'm a new Playnite user, I've installed everything properly, after setting everything up, It seems that Playnite can't import my unistalled game from steam whereas i checked the box to, I tried both method, Username and local none of them seems to work.
Thanks in advance if you have a solution for me ;)

(Sees the screenshot attached with Playnite open and my steam library)

![playnite cannot import unistalled games](https://user-images.githubusercontent.com/21315692/49703421-34763c00-fc05-11e8-90d0-2939a25fec3b.png)

**Comment by JosefNemec** [comment]
Make sure that either your profile is set to public (including `Game Details` setting) or provide your own API key if you want to use private one: https://github.com/JosefNemec/Playnite/wiki/How-to-get-Steam-account-name

**Comment by Ithoh** [comment]
Thanks Josef worked fine I didn't notice i set my game details to friends only ! :)
