### ISSUE TITLE
Support Rockstar Games/Social Club

### ISSUE THREAD

**Issue by Filipe3xF** [JosefNemec/Playnite#863]
I have Grand Theft Auto V on Rockstar's Client and I found that it would be cool if Playnite supports it, if possible. Thank you for your work btw!

**Comment by JosefNemec** [comment]
I'm closing this since adding support for service that has basically one game on it doesn't make sense to me. You can that game manually.

**Comment by janforster** [comment]
I would propose to reopen this issue since Rockstar has changed the service to actual launcher now:
https://www.eurogamer.net/articles/2019-09-18-rockstar-has-announced-its-very-own-games-launcher

**Comment by MaximusX800** [comment]
While I can agree that the library is limited via R* Launcher at this time, there is an issue with using its games via manual mapping.

I have both RDR2 and GTAV via R*, and Playnite can use then, since R* fixed an with .exe launching with RDR2.  However it requires an Alt-Tab to see the game, for fullscreen mode.

**Comment by cooperate** [comment]
GOG Galaxy has a working plugin for R* Launcher, might be worth it to take a look at that to see if any finagling had to be done to get the game launched correctly.

**Comment by lordsilver-zz** [comment]
The GOG Galaxy plugion mentioned above can be found in here: https://github.com/tylerbrawl/Galaxy-Plugin-Rockstar

As previosly said, it would be great to be able to have the Rockstar Launcher integrated in Playnite, to be able to import those games and most import, to be able to open them with no problems and automatically close the launcher when you quit the game.

In this moment, on Rockstar Launcher there are 9 games:
- Bully: Scholarship Edition
- Grand Theft Auto 3
- Grand Theft Auto: Vice City
- Grand Theft Auto: San Andreas
- Grand Theft Auto IV
- Grand Theft Auto V
- L.A. Noire
- Max Payne 3
- Red Dead Redemption 2

**Comment by JosefNemec** [comment]
Done as a separate plugin:
https://github.com/JosefNemec/PlaynitePlugin-RockstarLibrary
