### ISSUE TITLE
Can't start GOG Witcher 3 GOTY

### ISSUE THREAD

**Issue by N-Madsen** [JosefNemec/Playnite#867]
Hi!
There is problem with GOG Witcher 3 GOTY. Can't start it :(

I Get message as in the uploaded picture. It means "Cant find file specified"

Other GOG Games are fine

Regards,

**Comment by N-Madsen** [comment]
![w3-err](https://user-images.githubusercontent.com/45794875/49810852-5933f600-fd62-11e8-8ff4-978569e80d66.JPG)

**Comment by JosefNemec** [comment]
Fixed in 4.64. You will need to update your library (from main menu) or completely re-import Witcher 3 (depending on your setup) to apply the fix properly.

**Comment by N-Madsen** [comment]
After update works like a charm.

Thank you and best regards :)
