### ISSUE TITLE
Amazon Software Library support

### ISSUE THREAD

**Issue by oshaboy** [JosefNemec/Playnite#871]
Microsoft Store Games and Amazon Software Library Games. Both of them are Software distributors not game distributors but I still feel like they should at least be considered. 

Also I would like to second the previous requests for Itch.io Downloads (Although it doesn't have a real game library AFAIK) and Humble Bundle.

**Comment by JosefNemec** [comment]
You can already import [installed Windows Store apps](https://github.com/JosefNemec/Playnite/wiki/Importing-Windows-Store-games). Support for uninstalled ones will probably not happen because of how closed the whole Windows Store ecosystem is. I' haven had a change to look at Amazons solution yet.

**Comment by JosefNemec** [comment]
Done in Playnite 7.
