### ISSUE TITLE
Playnite is slow in cover mode

### ISSUE THREAD

**Issue by Nilot352** [JosefNemec/Playnite#873]
loads covers slow as well as closes in a lot more time.

**Comment by JosefNemec** [comment]
Please go to `About` menu and create diag package for me. By "closes" do you mean crashes?

**Comment by WhiskeyOmega** [comment]
Depends on how many you have. Ive stopped adding alot of random old school games from some emulators as it can really bog down the database loading in cover mode. I think trying to detect 1 game in a folder if the files labelled Disk 1 and Disk 2 would cut down on the amount of loading needed so you dont get dupes also.

**Comment by spektor56** [comment]
I was looking into this before and used the profiler to find the spot where it was slow but never had the free time to go fix it.  So busy these days :(

**Comment by JosefNemec** [comment]
This should haven been fixed by 4.59 update. If it's still an issue then I need more information then "it's slow". Ideally diag. package and copy of the game library.

**Comment by JosefNemec** [comment]
Closing this since there's was additional information provided.
