### ISSUE TITLE
Cover view - It would be nice if all covers were the same size

### ISSUE THREAD

**Issue by Mrhgb** [JosefNemec/Playnite#874]
Is there any chance we could get an option for uniform cover sizes? It's really annoying me how some are bigger than others, I've tried manually add 4K versions of all but they still aren't all the same size.

**Comment by JosefNemec** [comment]
See #579, #580 and #543. There's no way how to reliably have all covers have the same size, unless we want to stretch the image. There will be options to customize covers view to mitigate nonuniform sizes, which will be solved in issues I linked.

**Comment by kblamann** [comment]
Hi,
as a workaround i use the free image viewer/editor irfanview to batch adjust the size of all imags in one step to the same size. This should also be possiblle with other apps too.

Short HowTo (i use nobackground pics, maybe this could change the procedure) 
After adding the games with covers to playnite, it will be cached in the playnite directory.
In example: pathtoplaynite\Playnite474\library\files
Make a backup of your "files" folder first.

1. Open up irfanview, go to "File -> Batch Processing/Renaming"
2. Choose "Batch Conversion"
3. Output format, take your format, i.e. jpg
4. Check "use advances options (for bulk resize)
5. Click "Advanced" button
6. Check "Resize" and add the size you will use for all covers
7. Uncheck option "Preserve aspect ration"
8. Under Miscellaneous, check "create subfolders in destination folder"
9. Click "OK" th exit advanced settings.
10. Change output drectory to any path and check "include subdirectories"
11 on the top right go to your playnite dir pathtoplaynite\Playnite474\library\files
12 Select jpg to get only covers and no icons and select "Add all"
12 "Start batch" now. Before you close check your output dir if you're happy with the result.
13. After this replace playnite\library\files dir with the newly created output dir.

Hope that helps
