### ISSUE TITLE
Startup and shutdown script support

### ISSUE THREAD

**Issue by sixsixfive** [JosefNemec/Playnite#878]
Hi, I configured Playnite to run in fullscreen and I have replaced the explorer shell with it. However It would be nice if I could launch some applications if playnite starts because the normal windows startup does not work anymore without the shell.

Things I would like to launch:

* DS4Windows
* cleanmgr.exe /sagerun:1
* GOG Galaxy minimized(to update the games)
* Steam minimized(to update games)

Would this be possible?

**Comment by JosefNemec** [comment]
Kind of a good idea, but can't you just add those applications manually to start automatically with Windows? See [this post](https://github.com/JosefNemec/Playnite/issues/64#issuecomment-353715407) about how to do it basically for any application.

**Comment by JosefNemec** [comment]
Closing as this was implemented some time ago.
