### ISSUE TITLE
Add emulator option to open in fullscreen

### ISSUE THREAD

**Issue by Roukira** [JosefNemec/Playnite#879]
Allow each emulator to specify options at startup (when launching a game), more specifically fullscreen option. Some emulators allow that by simply passing -fullscreen argument, so it can already be done manually for now, but for others it might a bit tricky.

**Comment by JosefNemec** [comment]
Why would you want to have that as an option when starting the game? Is that a real use case where you would launch one emulated game in fullscreen and other in windowed?

**Comment by JosefNemec** [comment]
Closing due to no answer from original reporter.
