### ISSUE TITLE
Cannot load "Albion" from GOG

### ISSUE THREAD

**Issue by cycyx** [JosefNemec/Playnite#882]
If the game is already installed, or even with a new installation launched from inside Playnite, it's impossible to launch Albion with the message "Cannot start game: specified file cannot be found" (the last part is translated from french because the message is actually "Cannot start game: Le fichier spécifié est introuvable").

Same thing happens with "Amnesia The Dark Descent", "Amnesia: a machine for pigs", "Penumbra - Overture", "Penumbra - Black Plague" (all 4 by the same developper) and "Shovel Knight".

Playnite doesn't find those games while scanning directory during setup.

**Comment by JosefNemec** [comment]
Can you post a screenshot of Albion's "Play" action settings (edit game and navigate to "Actions" tab)? My Albion from GOG imports and starts properly so I have no idea what might be wrong.

**Comment by cycyx** [comment]
I just got the message about the latest update. With it, Albion launch fine.

But still the same error with Amnesia, Penumbra and Shovel knight.

![error](https://user-images.githubusercontent.com/3910864/50243536-b9174600-03cd-11e9-9e8d-45fd9d0ec2fb.png)

To be complete, those 5 games doesn't import, and if I try to import them by scanning or browsing, the import results in a badly named exectable (redist intead of Amnesia for example) and no metadata...

**Comment by cycyx** [comment]
I tried to attach the info file, but it's not supported. Just copying it here:

{
    "buildId": "51194033869387641", 
    "clientId": "49938185473192608", 
    "gameId": "1207659443", 
    "language": "English", 
    "languages": [
        "en-US"
    ], 
    "name": "Amnesia - A Machine For Pigs", 
    "playTasks": [
        {
            "category": "launcher", 
            "isPrimary": true, 
            "languages": [
                "*"
            ], 
            "name": "Amnesia - A Machine For Pigs", 
            "path": "redist/Launcher.exe", 
            "type": "FileTask", 
            "workingDir": "redist"
        }, 
        {
            "category": "game", 
            "isHidden": true, 
            "languages": [
                "*"
            ], 
            "name": "Amnesia - A Machine For Pigs", 
            "path": "redist/aamfp.exe", 
            "type": "FileTask", 
            "workingDir": "redist"
        }, 
        {
            "category": "document", 
            "languages": [
                "*"
            ], 
            "link": "http://www.gog.com/support/amnesia_a_machine_for_pigs", 
            "name": "Support", 
            "type": "URLTask"
        }, 
        {
            "category": "document", 
            "languages": [
                "*"
            ], 
            "name": "Manual [BR]", 
            "path": "manual//Amnesia amfp - Manual br.pdf", 
            "type": "FileTask", 
            "workingDir": "manual"
        }, 
        {
            "category": "document", 
            "languages": [
                "*"
            ], 
            "name": "Manual [CZ]", 
            "path": "manual//Amnesia amfp - Manual cz.pdf", 
            "type": "FileTask", 
            "workingDir": "manual"
        }, 
        {
            "category": "document", 
            "languages": [
                "*"
            ], 
            "name": "Manual [DE]", 
            "path": "manual//Amnesia amfp - Manual de.pdf", 
            "type": "FileTask", 
            "workingDir": "manual"
        }, 
        {
            "category": "document", 
            "languages": [
                "*"
            ], 
            "name": "Manual [EN]", 
            "path": "manual//Amnesia amfp - Manual en.pdf", 
            "type": "FileTask", 
            "workingDir": "manual"
        }, 
        {
            "category": "document", 
            "languages": [
                "*"
            ], 
            "name": "Manual [ES]", 
            "path": "manual//Amnesia amfp - Manual es.pdf", 
            "type": "FileTask", 
            "workingDir": "manual"
        }, 
        {
            "category": "document", 
            "languages": [
                "*"
            ], 
            "name": "Manual [FR]", 
            "path": "manual//Amnesia amfp - Manual fr.pdf", 
            "type": "FileTask", 
            "workingDir": "manual"
        }, 
        {
            "category": "document", 
            "languages": [
                "*"
            ], 
            "name": "Manual [HU]", 
            "path": "manual//Amnesia amfp - Manual hu.pdf", 
            "type": "FileTask", 
            "workingDir": "manual"
        }, 
        {
            "category": "document", 
            "languages": [
                "*"
            ], 
            "name": "Manual [IT]", 
            "path": "manual//Amnesia amfp - Manual it.pdf", 
            "type": "FileTask", 
            "workingDir": "manual"
        }, 
        {
            "category": "document", 
            "languages": [
                "*"
            ], 
            "name": "Manual [PL]", 
            "path": "manual//Amnesia amfp - Manual pl.pdf", 
            "type": "FileTask", 
            "workingDir": "manual"
        }, 
        {
            "category": "document", 
            "languages": [
                "*"
            ], 
            "name": "Manual [RU]", 
            "path": "manual//Amnesia amfp - Manual ru.pdf", 
            "type": "FileTask", 
            "workingDir": "manual"
        }, 
        {
            "category": "document", 
            "languages": [
                "*"
            ], 
            "link": "http://www.frictionalgames.com/", 
            "name": "Frictional Games", 
            "type": "URLTask"
        }, 
        {
            "category": "document", 
            "languages": [
                "*"
            ], 
            "link": "http://support.frictionalgames.com/", 
            "name": "Frictional Games - Support", 
            "type": "URLTask"
        }, 
        {
            "category": "document", 
            "languages": [
                "*"
            ], 
            "link": "http://www.thechineseroom.co.uk/", 
            "name": "The Chinese Room", 
            "type": "URLTask"
        }
    ], 
    "rootGameId": "1207659443", 
    "version": 1
}

**Comment by JosefNemec** [comment]
If they were not imported automatically then you need to reinstall them. If you use Galaxy then you need to use "Manage Installation" and "Verify / Repair..." options. Galaxy sometimes doesn't import games properly when you use "Scan and import folders". After that Playnite should find them automatically.

**Comment by cycyx** [comment]
Saw the FAQ afterwards, sorry for the inconvenience (even if Albion was actually a bug for the previous version).
Thanks for your time.
