### ISSUE TITLE
Add a game streaming server and client apps

### ISSUE THREAD

**Issue by berserkwarwolf** [JosefNemec/Playnite#883]
Playnite is already the best launcher for PC games, and a great alternative to adding games to Steam, Launchbox, or others.

But one reason why adding games to Steam keeps being convenient is to stream games. Nvidia and AMD also offer their alternatives but at the cost of the user's privacy: GeForce Experience is very invasive with telemetry.

This is why I think an open source standard should exist, and the people at Rainway are open sourcing their tech. This is a unique opportunity for Playnite, and one that should be evaluated in depth.

More information at:
https://blog.rainway.io/introducing-rainway-home-bc91172303a0

**Comment by JosefNemec** [comment]
Sadly there's currently no info that would be really interesting to developers. Like what will their SDK actually contain, so I can estimate how much effort this is going to be. Please keep me updated when they actually release it for testing, I'm really interested in this.

**Comment by genova447** [comment]
Not being a programmer in the least - this might not be related: but from my meager understanding, it might be something you can use and 'shape' to work in Playnite as fully independent playnite-thing(?):
https://github.com/chunying/gaminganywhere

https://github.com/chunying/gaminganywhere/blob/master/LICENSE

**Comment by berserkwarwolf** [comment]
How about  tight integration with moonlight and sunshine?
