### ISSUE TITLE
(Not an issue) Possible support for Mac computers

### ISSUE THREAD

**Issue by Tastrager** [JosefNemec/Playnite#891]
I am currently in the process of organising, ordering and building a gaming PC for personal use, but I would still like to play a couple of games on my Macbook while I'm waiting for the parts (yes I know Macbooks are terrible for gaming, but it's all I have and I can still run certain games on there) do you reckon it's possible to add support for Mac computers just so I'm not having to remember which games are on where. Thank you!

**Comment by JosefNemec** [comment]
See #59
