### ISSUE TITLE
Ukrainian translation

### ISSUE THREAD

**Issue by Yamaha373** [JosefNemec/Playnite#892]
[ukrainian.zip](https://github.com/JosefNemec/Playnite/files/2704454/ukrainian.zip)

**Comment by Yamaha373** [comment]
Am I did something wrong? Why you not use it? Or not even reply?

**Comment by JosefNemec** [comment]
Hi, I usually don't do updates to just add new localization. I will include this with other changes for next update.

**Comment by JosefNemec** [comment]
I forgot about it since it was not submitted as standard pull request. I'll add it in next update.

**Comment by JosefNemec** [comment]
Localization have been completely move to Crowdin: https://crowdin.com/project/playnite

Please join the project there to submit updates.
