### ISSUE TITLE
Loading images (in descriptions) may freeze everything else

### ISSUE THREAD

**Issue by ClearStrelok** [JosefNemec/Playnite#894]
Possibly linked to #454

I added Subnautica from the Epic Store and Copy-pasted [the description from Steam](https://store.steampowered.com/app/264710/Subnautica/), which highlighted an issue that can occur in  Cover view : upon clicking on another game cover, Playnite will sometimes freeze completely for a few seconds. If I try to exit Playnite just after clicking on a game with enough images in its description, the "Closing Playnite" prompt will appear and seemingly prevent the app from closing until everything is loaded.

**Comment by JosefNemec** [comment]
Can you post a specific description text that's causing an issue for your? Thanks

**Comment by ClearStrelok** [comment]
Sure ! 

[Subnautica.txt](https://github.com/JosefNemec/Playnite/files/2721402/Subnautica.txt)
