### ISSUE TITLE
IGDB is broken

### ISSUE THREAD

**Issue by DaBear78** [JosefNemec/Playnite#896]
For me looking for metadata with IGDB always returns 0 results. Already reinstalled playnite and tried on another PC, still the same issue.

**Comment by DaBear78** [comment]
I tried all my games, none of them returned any result when searching with IGDB (Wiki and official store work both). Some of the terms I tried: "Warframe", "Star Wars: The Old Republic", "Diablo III". I also tried to disable the firewall, but it changed nothing...

The created diag.zip could not be uploaded, so I'm posting it here.
[diag.zip](https://github.com/JosefNemec/Playnite/files/2708982/diag.zip)

Is that everything you need?

**Comment by JosefNemec** [comment]
If Playnite failed to upload diag. package that means that you are unable to contact API server, which is also reason why the IGDB stuff is not working. Please make sure that Firewall or AV is not blocking Playnite.

**Comment by DaBear78** [comment]
Disabled both, still no success... Will try a few other things, maybe I can make it work ^^

**Comment by JosefNemec** [comment]
Is this still an issue? I've made several improvements to IGDB integration since December that could fix it.

**Comment by DaBear78** [comment]
Checked it, it now works. Thx!

**Comment by sharazy** [comment]
Had same problem as well, somehow restarting the Windows solve it.
