### ISSUE TITLE
Some Bethesda Launcher games aren't importing

### ISSUE THREAD

**Issue by ClearStrelok** [JosefNemec/Playnite#897]
I noticed the issue after installing Quake 2 on there. I then tried with Fallout Shelter and it failed to import as well.

**Comment by JosefNemec** [comment]
You need to launch the game at least once for Playnite to pick it up. For some reason they don't properly add all necessary system entries unless you start the game. Can you confirm that that's your case with this issue?

**Comment by ClearStrelok** [comment]
Yep, nevermind. I never played the game using the launcher button before and now it works.
