### ISSUE TITLE
Bethesda Launcher metadata support

### ISSUE THREAD

**Issue by ClearStrelok** [JosefNemec/Playnite#898]
Same thing as #620 but for the Bethesda Launcher ! Not sure if doable though. Background pictures seen in the launcher are available at https://bethesda.net/fr/games/ 

Ex: https://bethesda.net/fr/games/QU2CSTPCBG01

http://drh2.img.digitalriver.com/DRHM/Storefront/Company/zenimax/images/background/Quake/Quake2_bnet-ProductBackground-1920x1080-01.jpg

**Comment by JosefNemec** [comment]
The whole integration of Bethesda's stuff is a huge PIA (because they don't have a public API) and I don't think it makes sense to integrate their metadata when there's a lot of other metadata alternatives available already.
