### ISSUE TITLE
Show exact zoom value on top of the Zoom slider

### ISSUE THREAD

**Issue by ClearStrelok** [JosefNemec/Playnite#899]
Maybe something like this ? 

![slider](https://user-images.githubusercontent.com/38838369/50423158-21dd4300-0852-11e9-98e7-81f598fcb89f.png)

**Comment by Mates1500** [comment]
is this being worked on? seems simple enough

**Comment by ClearStrelok** [comment]
That was more of a suggestion, as I'm not sure how much interest there is in it, but I could try and propose it in a commit (once I semi-know what I'm doing that is).

**Comment by JosefNemec** [comment]
I'm not sure how useful this information would be. The only value we can currently display is target pixel width of cover image (which is what the slider changes) and even that will not be accurate when non-100% DPI scaling is used.

**Comment by JosefNemec** [comment]
I guess we could treat some specific value as being 100% zoom and then offer values that would represent zoom" from 50% to 200%, and only display calculated percentage while still handling pixel width in background.

**Comment by Mates1500** [comment]
Yeah, that's what I meant. I could get to work on this by the end of the next week if you're not already working on it.

**Comment by JosefNemec** [comment]
I don't plan to work on this any time soon so it's up for the grabs.

**Comment by JosefNemec** [comment]
Released in 4.71
