### ISSUE TITLE
Origin games don't show up as installed 

### ISSUE THREAD

**Issue by cristi1990an** [JosefNemec/Playnite#901]
![2018-12-27_18h37_55](https://user-images.githubusercontent.com/23399600/50487375-cc966280-0a06-11e9-9619-c4f1e77dcf0f.png)

**Comment by cristi1990an** [comment]
That worked! Thank you!

În sâm., 29 dec. 2018 la 20:23, Josef Nemec <notifications@github.com> a
scris:

**Comment by cristi1990an** [comment]
Actually, no. It didn't. Restarted Playnite and it shows as uninstalled
again.

În dum., 30 dec. 2018 la 18:15, Cristian Cornea <
cristi.1990.cristi@gmail.com> a scris:

**Comment by seanscot** [comment]
I'm also having this issue.  I wonder if it is as simple as Playnite having a hard-coded location for the installed Origin games folder.  I have the error "Failed to import games from Origin.  Access to the path 'C:\ProgramData\Origin\LocalContent' is denied." in the notifications of Playnite.  This makes sense given that I don't have anything at that location - my Origin games are installed at on my D: drive in the Program Files folder.  Is there a config file to change where Playnite looks for installed Origin games?  Is this something that could be added to the UI?

**Comment by JosefNemec** [comment]
`C:\ProgramData\Origin\` should exists no matter where you have games installed. Origin uses that path to store application settings, logs and other stuff there (including information about what games are currently installed).

**Comment by JosefNemec** [comment]
Is this still an issue with Playnite 5?

**Comment by cristi1990an** [comment]
No, no. Hasn't been an issue for a while now.

**Comment by cymen** [comment]
I ran into this problem on version 8.12. I opened up File Explorer and navigated to the folder and tried to open it and got an error about permissions. There was an option to fix/grant permissions and that worked and I was able to open the folder. Then I restart Playnite and the error was gone.

Only replying here for the googles results. Not a problem.
