### ISSUE TITLE
Jump list (right click taskbar icon) limited to ten games

### ISSUE THREAD

**Issue by PoliteTimesplitter** [JosefNemec/Playnite#902]
I brought this up on the discord and was asked to put a ticket here; essentially, even though I've edited my registry to allow for for jumplists to hold many more than 10 entries, Playnite is, I'm told, hard coded to ten because its list comes from the list provided by the tray icon and can be fixed.

Though I'm grateful for having 10 jumplist entries again since steam dropped down to 5 (even on beta branch), the more the better, especially for people who game-hop or are dilligent with login bonuses. The jumplist is fantastic for launching things with two clicks!

**Comment by JosefNemec** [comment]
Done in Playnite 8, number of items in tray menu and jump list is now configurable.
