### ISSUE TITLE
All imported Steam games Last Played: Never

### ISSUE THREAD

**Issue by Leiludallas** [JosefNemec/Playnite#903]
Hi,

All imported Steam games have the "Never" last played status.

![playnitebug](https://user-images.githubusercontent.com/39462014/50502175-828c9b80-0a5d-11e9-82ac-9d310829b48d.jpg)

Thank you

**Comment by JosefNemec** [comment]
That's correct behavior. Playnite has no way of knowing when you launched the game last time unless the game was started via Playnite.
