### ISSUE TITLE
Polish translation

### ISSUE THREAD

**Issue by Falsen123** [JosefNemec/Playnite#905]
[polish.zip](https://github.com/JosefNemec/Playnite/files/2716366/polish.zip)

**Comment by Falsen123** [comment]
[polish.zip](https://github.com/JosefNemec/Playnite/files/2741849/polish.zip)
Update translation. Repair typos.

**Comment by Falsen123** [comment]
[polish.zip](https://github.com/JosefNemec/Playnite/files/2847783/polish.zip)
Update to playnite 4.7

**Comment by JosefNemec** [comment]
Localization have been completely move to Crowdin: https://crowdin.com/project/playnite

Please join the project there to submit updates.
