### ISSUE TITLE
Possible upgrade if not exists

### ISSUE THREAD

**Issue by L-anonyme** [JosefNemec/Playnite#914]
Hello

I have some ideas for you if it's not yet implemented or if I'm too bad to find out how to do it.

 - when you click on the awning of a game, the launcher of the game opens with the right page ( can be activated in the options);
 - rename categories;

For the moment, nothing comes to mind but in case I answer on this post

**Comment by JosefNemec** [comment]
What's "awning of a game"? Renaming categories (and global management for that matter) will be available in next major version).

**Comment by L-anonyme** [comment]
Sorry my english is not perfect and I used a traductor (deepl). I mean the store button

**Comment by JosefNemec** [comment]
Option to rename categories is coming in 5.0 update and store link is available for games that support [official metadata download](https://github.com/JosefNemec/Playnite/wiki/Feature-table-based-on-library-provider).
