### ISSUE TITLE
Add directory containing IronPython scripts to SearchPaths

### ISSUE THREAD

**Issue by bburky** [JosefNemec/Playnite#916]
Please clone this simple test extension to test IronPython imports:
https://gist.github.com/bburky/a213d97b81c1431ee9791e5831890af7

Currently importing a module in IronPython fails:

```
ImportError: No module named b.
```

After some debugging and reading StackOverflow, I discovered you need to manually add the directory containing the script to the ScriptEngine's SearchPaths. I almost wrote you a pull request but, `engine` is private to IronPythonRuntime and I didn't know how you wanted to expose configuring SearchPaths. I think where you _want_ to configure it is IronPythonScript's constructor.

As a quick hack I tested by modifying IronPythonRuntime like this and the test extension above correctly runs:

```
public void ExecuteFile(string path)
{
    var paths = engine.GetSearchPaths();
    paths.Add(Path.GetDirectoryName(path));
    engine.SetSearchPaths(paths);
    engine.ExecuteFile(path, scope);
}
```

**Comment by JosefNemec** [comment]
Closing, IronPython support has been removed in P9.
