### ISSUE TITLE
Allow optionally configuring the IronPython engine in debug mode

### ISSUE THREAD

**Issue by bburky** [JosefNemec/Playnite#917]
It is useful to run IronPython in debug mode while developing extensions. Running IronPython in debug mode allows setting breakpoints, single stepping and viewing Python local variables. (Sadly, no repl though.)

Running in debug mode does slow down IronPython significantly. And as far as I can tell it requires Visual Studio to do anything with, so this isn't anything most users need. Maybe only enable it when `Debugger.IsAttached` or something like only in debug builds?

You can enable debug mode like this:

```
public IronPythonRuntime()
{
    Dictionary<string, object> options = new Dictionary<string, object>();
    options["Debug"] = true;
    engine = Python.CreateEngine(options);
[...]
```

It may be worth documenting this too for people developing extensions.

**Comment by JosefNemec** [comment]
Yeah the current environment for debugging script extensions is not really that good. We should add general support for script debuggers to be able to attach to Playnite runtime (even for PowerShell) and make it easier for people to experiment with Playnite's API.

**Comment by JosefNemec** [comment]
Should be done together with or after #1206

**Comment by JosefNemec** [comment]
Closing, IronPython support has been removed in P9.
