### ISSUE TITLE
Set inital location of game executable file dialog to InstallDir

### ISSUE THREAD

**Issue by bburky** [JosefNemec/Playnite#918]
When choosing the executable path of a game please set the default location of the file dialog to the game's installation directory.

This would be really useful when reconfiguring Twitch games to skip the launcher. I end up manually reconfiguring each game to launch the exe instead of the twitch:// url. Twitch does provide the installation directory, so please default the dialog to it so I don't have to guess which GUID is the game.

**Comment by JosefNemec** [comment]
Done in `devel7` branch (future Playnite 7).
