### ISSUE TITLE
Emulation Import Wizard - Add Real File Name

### ISSUE THREAD

**Issue by teorex3** [JosefNemec/Playnite#921]
![002_playnite](https://user-images.githubusercontent.com/35883258/50905243-6b718480-1433-11e9-82a3-0de5eab8556b.jpg)
![emulation import wizard](https://user-images.githubusercontent.com/35883258/50905810-af18be00-1434-11e9-9ce6-1ae45bc17cef.jpg)

Emulation Import Wizard Scaner deleted info from games version, region, beta, proto other info.
Maybe you need to add another alternate name for real file names: scan file name and save all name+region\other without extensions to db. as an option Title Name - Scan Metadata, Alt Name - Show in List

**Comment by JosefNemec** [comment]
Requires #653 first.
