### ISSUE TITLE
Can't Get Background Image from URL

### ISSUE THREAD

**Issue by MohandL3G** [JosefNemec/Playnite#928]
b6114240-75a9-45a4-a455-0f42358828e1

Can't Get Background Image from URL for Titan Souls Game, [This is the Pic](https://wallpapercave.com/wp/wp3082849.jpg).
When I click Save, Playnite Crash, So I've Download the Pic, and applied it.

**Comment by JosefNemec** [comment]
Is this still an issue in Playnite 5?
