### ISSUE TITLE
Option to disable XInput handling

### ISSUE THREAD

**Issue by JosefNemec** [JosefNemec/Playnite#932]
For people that use apps like [Controller Companion](https://store.steampowered.com/app/367670/Controller_Companion/), because it causes duplication of inputs.

**Comment by molnizzle** [comment]
Oh god so I'm not crazy, this just isn't an option?
What in the world......

**Comment by phoenixanimations** [comment]
Just wanted to +1 this. Would be nice if there was some way to stop apps from reading the controller in general but I suppose there isn't.

**Comment by JosefNemec** [comment]
Done in 5.0
