### ISSUE TITLE
Crash in fullscreen mode

### ISSUE THREAD

**Issue by theWill** [JosefNemec/Playnite#935]
Please use search first to see if the issue is already opened. Thank you

**Comment by theWill** [comment]
I have 1 GOG galaxy game and 3 steam games added to playnite. They work and launch correctly. When I enter Full Screen Mode they work fine with mouse and keyboard. The entire app crashes when pushing a few buttons on the xbox 360 controller in Full Screen Mode.

easy to reproduce. I saw a diag file can be generated but not sure where it is saved.

**Comment by JosefNemec** [comment]
You need to attach the ID you get when generating diag. package.

**Comment by theWill** [comment]
I am not sure I even created any diag file... it crashes so fast... see gif attached
![crash](https://user-images.githubusercontent.com/1052378/51431497-67d1c080-1bde-11e9-96c2-bbfd15f194b5.gif)

**Comment by JosefNemec** [comment]
Start in desktop mode, go to main menu -> `About Playnite` and create diag. package from there.

**Comment by theWill** [comment]
got it. thanks!
f2989527-582f-4e26-a93d-0210fdde8073

**Comment by JosefNemec** [comment]
Done in 5.0
