### ISSUE TITLE
Add Or Change Emulator Games Directory

### ISSUE THREAD

**Issue by trymeouteh** [JosefNemec/Playnite#938]
How do you add or change the directory where your games are for a specific emulator? I cannot find this anywhere in the settings or in emulation tools.

And when I do add or change a directory how do I update Playnite so it will list new games.

Thank You!

**Comment by JosefNemec** [comment]
Emulators don't know where the games are stored. The ROM path is passed to emulator when the game is started and all paths are stored with the game itself. You can change it by editing the game (`Installation` tab).
