### ISSUE TITLE
[Feature Request] Option To Disable Playtime

### ISSUE THREAD

**Issue by trymeouteh** [JosefNemec/Playnite#939]
Playtime is a cool feature but I would prefer to disable it if possible.

**Comment by JosefNemec** [comment]
Why? What's the issue with Playnite counting your play time?

**Comment by trymeouteh** [comment]
Sorry for the late response but the reason why I would like to disable play time is because I like using Gameplay Time Tracker for keeping track of my game time.

**Comment by JosefNemec** [comment]
I'm closing this. I don't see a point of disabling internal tracking, there's no downside of having it enabled and you can still use any other 3rd party software to track it as well. 5.0 updates will add an option to hide play time information from the details view.
