### ISSUE TITLE
ePSXe Games Do Not Show Up In Library

### ISSUE THREAD

**Issue by trymeouteh** [JosefNemec/Playnite#940]
When I add my ePSXe emulator to playnite the ps1 games do not appear in my library. All of my other emulators games do appear. All of my ePSXe games are saved as a .PBP file and I tried adding that file type in the emulator settings and after the ps1 games still do not appear.

Thank You.

**Comment by trymeouteh** [comment]
When I import Project 64, Dolphin, DeSmuMe and PCSX2 during the startup wizard the games do get imported into playnite. They get imported by completing the last step in the emulation wizard which asks you to click on the "Scan folder using Emulator" and then I select the directory where my games are saved for that emulator and after when I click finish my games do appear in Playnite.

**Comment by JosefNemec** [comment]
Thank's for clarification.

**Comment by JosefNemec** [comment]
I will add PBP to list of supported extensions for ePSXe. You can also add it manually by editing emulators profile from `Tools -> Platforms and emulators` menu. It should then import your .pbp games properly even without Playnite update.

**Comment by JosefNemec** [comment]
Fixed in 4.71
