### ISSUE TITLE
Importing Google Play (android) library

### ISSUE THREAD

**Issue by janforster** [JosefNemec/Playnite#943]
Along the lines of #549: managing library of games that are not playable on windows, but I would still love to be able to retrieve automatically and categorise.

Similar reasoning and mentioned in the other ticket:

- Cataloging the games I own.
- Organizing them into categories, for the purpose of knowing which ones I have played, beaten, or want to play next.

Also could be linked with #733, for actual launching of the games inside an emulator.

**Comment by JosefNemec** [comment]
I'm going to close this, since I can say for sure I won't be doing this as built-in plugin (there's no demand for this and I'm not interested in mobile platforms at the moment). SDK has support for everything needed for this to be done as 3rd party plugin.
