### ISSUE TITLE
Crash When Launching Origin.OFR.50.0002756

### ISSUE THREAD

**Issue by epeternally** [JosefNemec/Playnite#946]
Playnite imported an entry from Origin called "Origin.OFR.50.0002756" and out of silly curiosity I tried to open it just to see what would happen, which was an immediate crash. 3fc75651-6ad7-4ae9-9415-0c9d2f1cc164

**Comment by JosefNemec** [comment]
Did Origin actually open and started installing something? I will fix the crash, but Origin API says that `Origin.OFR.50.0002756` is unknown product, so I'm wondering why it was reported as part of your library.

**Comment by JosefNemec** [comment]
Fixed in 4.71
