### ISSUE TITLE
"Account name cannot be empty" has no translation string

### ISSUE THREAD

**Issue by ClearStrelok** [JosefNemec/Playnite#955]
Stumbled on this while testing 4.70

![sans titre-2](https://user-images.githubusercontent.com/38838369/52080869-1e4b8300-2599-11e9-9840-2a0463e4f552.png)

**Comment by ClearStrelok** [comment]
Also this : ("Startup error" + "Playnite failed to start. Please close all runing instances and try again.")

![sans titre-2](https://user-images.githubusercontent.com/38838369/52087997-198fca80-25ab-11e9-8e4b-aa372513820a.jpg)

**Comment by JosefNemec** [comment]
Both strings are translatable, first one is `LOCSettingsInvalidAccountName` and second `LOCStartGenericError`. Can you check if your localization file contains these?

**Comment by ClearStrelok** [comment]
I found LOCSettingsInvalidAccountName in the latest English.xaml but it was still LOCSettingsInvalidSteamAccountName in my case. I've probably missed it at some point but now it works. Other translation files had the same mistake so I'll fix them too.

I found LOCStartGenericError in the current French.xaml however, so it appears that the string is not used at least in that case (Attempting to launch Playnite while a session is already running).

**Comment by JosefNemec** [comment]
LOCStartGenericError is used and I couldn't find the raw English text in any source files, I'm not sure what's happening in your case.

As far as your PRs, please bulk them together. There's no reason to open PR for every single file if you are fixing one issue affecting multiple files. Second, are your sure that your changes to those languages still make sense? I don't think that simply removing word "Steam" from sentence doesn't break the meaning of it.

**Comment by ClearStrelok** [comment]
Sorry, I didn't know these could be bulk together. I'll try to change it and will remove the duplicate PRs in the meantime. As for the changes themselves, I can't be sure that it's correct for all languages but I tried to remove the preposition when there seemed to be one, so it should be relatively safe. 

For LOCStartGenericError, I just tried to reproduce the same error by double clicking on the application shortcut with other translations enabled and they display the english text as well. I also tried a portable installation with the same results. It's unlikely for this error to show up for most people, though, so it's hardly a problem if it can't use the translation string.

**Comment by JosefNemec** [comment]
I think the error stays in English because it happens before we actually load localization from application settings. I'll fix that.

**Comment by ClearStrelok** [comment]
I though I'll only update French.xaml after all for now : LOCSettingsInvalidAccountName not being named correctly in other translations files isn't because of an oversight but rather because of them not being updated in a while so future contributors will probably take care of that along with the rest.

**Comment by JosefNemec** [comment]
Done in 5.0
