### ISSUE TITLE
Localization tool

### ISSUE THREAD

**Issue by JosefNemec** [JosefNemec/Playnite#958]
Create tool to help people creating/updating localization files. Primarily highlight what strings are missing or are not translated compared to English version.

**Comment by L1cardo** [comment]
It would be nice if this is real !

**Comment by southrop** [comment]
Have you considered using a platform like Transifex?

**Comment by JosefNemec** [comment]
I haven't and looking and their pricing I probably won't :)

**Comment by southrop** [comment]
Ah, apologies. I should've been a bit more specific. Transifex is free for open source projects.

> **What are the basic requirements to qualify as an Open Source account?**
We are proud and humbled to be hosting the largest Open Source translation community in the world. We offer Transifex for free to Open Source projects that have no funding, revenue, and/or commercialization model. If you have a question whether your organization qualifies for our Open Source program, please contact us.

https://www.transifex.com/pricing/
https://docs.transifex.com/projects/open-source-project

**Comment by JosefNemec** [comment]
I see, in that case I'll check it out. Also thanks for tip about Weblate.

**Comment by JosefNemec** [comment]
Note to myself: also check out https://crowdin.com/

**Comment by JosefNemec** [comment]
Status update. I checked Transifex and Crowdin and decided to go with Crowdin (if we get OSS license). They have really great integration with GitHub and I would not have write any custom tool since they seem to support all scenarios I plan to deploy in near future (like separate localization files for library plugins).

**Comment by JosefNemec** [comment]
Crowdin: https://crowdin.com/project/playnite
