### ISSUE TITLE
Unable to track Play Time (Apex Legends)

### ISSUE THREAD

**Issue by ClearStrelok** [JosefNemec/Playnite#965]
I'm creating a new issue as it seems to differ from #703. Apex Legends just released on Origin and it seems that Play Time with this specific game cannot be tracked at all. There are two .exe ("EasyAntiCheat_launcher" + "r5apex") but neither of them are recognized properly when setting them up as the launch action.

**Comment by JosefNemec** [comment]
Fixed in 4.71
