### ISSUE TITLE
Group by category doesn't get remembered

### ISSUE THREAD

**Issue by AntoinevdHorst** [JosefNemec/Playnite#97]
Hi,

I changed the application to group by categories but everytime I restart the application that setting gets forgotten. Any ideas?

**Comment by JosefNemec** [comment]
That's weird, is grouping the only setting that's not saved? What about sorting options? In general if you close Playnite properly (not by killing the process), the setting should be saved.

**Comment by AntoinevdHorst** [comment]
Nope sorting is also not saved, could it have to do with me reloading the game list to add more game info(takes me like 10 times reloading before everything is loaded in which takes a lot of time but that's beside the point) because that's the only "abnormal" thing I do.

I close the app by shutting down my pc. Love the app apart from that :)

**Comment by JosefNemec** [comment]
Yeah that's a bug, when shutting down, Windows basically kills the process so settings are not saved. I will make it so the settings are saved right after you change them, to prevent this from happening.

**Comment by AntoinevdHorst** [comment]
Okay, I'll close the application normally once to make it stop from happening. Thanks!

**Comment by JosefNemec** [comment]
Fix released in 1.4
