### ISSUE TITLE
Download age ratings from IGDB

### ISSUE THREAD

**Issue by giuliocatte** [JosefNemec/Playnite#975]
I've tried various inputs for that filter, nothing seems to give results. Possibly I've not tried the right input, but it is not easy to understand what I should put inside this field. 
Probably a good solution would be to use a picklist of values, or a range. I think I'm in the most common use case for this: I've children and I'm wondering which games of my libraries they can play.

**Comment by JosefNemec** [comment]
Just enter part of the rating's string and it should filter them. For example games with age rating "18+" will show up if you set filter to "18" or "18+".

Next major version will add list of all available age ratings to filter field.

**Comment by giuliocatte** [comment]
it's not working, not "18" neither "18+"
but if the next version changes the input field to a picklist, that's ok i guess

**Comment by JosefNemec** [comment]
Do you actually have age ratings set for game? They are not imported automatically and you have to set them up manually. I'm asking because I'm unable to reproduce the issue.

**Comment by giuliocatte** [comment]
oh I'm sorry, I thought they were imported from IGDB (if I remember the API correctly, they have ratings from several rating systems). So, of course I wasn't seeing anything, I had anything to see.
Sorry for the waste of time, keep up the good work. (probably patreoning you soon)

**Comment by JosefNemec** [comment]
No problem, I'll rename this issue to add age rating download from IGDB.

**Comment by teihoo** [comment]
I have something else to add regarding - ratings. Would it be possible to add to the info page of a game (when you select it from the left and info appears on the right) to have let's say different ratings (or just one or none, if there isn't more) displayed near top? Like steams ratings does it? That'd be very nice in my opinion.

**Comment by splinke** [comment]
This program is fantastic to catalog my large collection of games! It would be great if you could implement the "age rating" download from IGDB.com. That would be very helpful, along with the existing filters for available multiplayer modes, critical ratings, and genres, in order to help identify the best games to introduce to my younger son.

**Comment by JosefNemec** [comment]
Done in `devel8`.
