### ISSUE TITLE
Save columns size on List view

### ISSUE THREAD

**Issue by TheDreka** [JosefNemec/Playnite#976]
When I first open the Playnite client, the Details view is shown by default (desired behavior) but all of the columns are reset to "default" widths. The default widths are too short for the content inside of the Details view, so nearly every single column has truncated/cut-off contents, including the icon column. When I manually change the column widths they do not revert, even if I hide and re-open the window. They remain correct until I restart the application.
![example](https://user-images.githubusercontent.com/227006/52376095-3a36a500-2a2f-11e9-9276-dd4ac27b0cd5.png)

**Comment by JosefNemec** [comment]
Should be done together with #688

**Comment by thedreka** [comment]
D'oh. Sorry for the dupe; looked over titles for similar issues, didn't read comments inside each.

Thanks for your efforts, by the way, the program is awesome.

**Comment by JosefNemec** [comment]
I don't consider it to be duplicate, they are clearly two different issues. I just wanted to link them since it would be probably good to implement those two issues together

**Comment by Stuntaneous** [comment]
This is (strangely) still an issue.

**Comment by JosefNemec** [comment]
Done in `devel`.
