### ISSUE TITLE
Background only shows up with the infobox in Grid view

### ISSUE THREAD

**Issue by ClearStrelok** [JosefNemec/Playnite#977]
Not sure if this the intended behavior or not, but I thought this was worth mentioning. The downloaded background pictures won't show up in Grid view if you just (either left or right) click on the game cover, like this : 

![1](https://user-images.githubusercontent.com/38838369/52403282-a7494980-2ac6-11e9-9425-7fded452d539.jpg)

You always have to click on the Infobox icon first, and the background pictures also stop showing once the infobox gets closed : 

![2](https://user-images.githubusercontent.com/38838369/52403455-0c04a400-2ac7-11e9-90c4-4f3d5c55d134.jpg)

**Comment by JosefNemec** [comment]
Probably makes sense to show background even if the details panel is hidden.

**Comment by JosefNemec** [comment]
Fixed in 4.73
