### ISSUE TITLE
[Feature request] Add the platform name in grid view

### ISSUE THREAD

**Issue by Kvaell** [JosefNemec/Playnite#979]
Hello, 

Would it be possible to display in grid view the plateform's name between the end of the first one and the beginning of the next one?

Currently in grid view games just continue as if they are all from the same plateform, it would be nice to have a space between tiles when reaching a new plateform, with the name of the new plateform.

**Comment by JosefNemec** [comment]
You can achieve that by grouping games by platform via `...` button. Let me know if that's what you are looking for.

**Comment by Kvaell** [comment]
Games are grouped by plateform, but the only way to know what plateform the game is for is the game cover

![dsc_0299](https://user-images.githubusercontent.com/27021339/52484191-06d25280-2bb6-11e9-81b7-4cbc233b0944.JPG)

**Comment by JosefNemec** [comment]
I see, it will be done as part of #170
