### ISSUE TITLE
Resize window if original size doesn't fit the screen

### ISSUE THREAD

**Issue by Kvaell** [JosefNemec/Playnite#980]
Hello, 

I noticed that we can modify the script that is applied by default on emulator's game, I would like to change the script that is applied on all my psp games (under ppsspp) by applying is to the plateform directly instead of changing it per game that is too long. 

The problem with the script applied by Playnite is that when you launch a a game for ppsspp, if you press the button to go to setting, it closes the emulator to go back to Playnite.

**Comment by JosefNemec** [comment]
Can you specify what do you mean by "I noticed that we can modify the script that is applied by default on emulator's game"? Playnite doesn't apply any "scripts" to emulated games. It only starts emulator process with necessary arguments and then waits for process to close. No other interaction between emulator and Playnite is currently implemented and there's no option to specify emulator scripts.

**Comment by Kvaell** [comment]
My bad, I thought the argument was a script.

The argument escape exit-- make the emulator close to go back to Playnite

**Comment by JosefNemec** [comment]
You can change emulator arguments from `Tools -> Platforms and emulators` menu.

**Comment by Kvaell** [comment]
Thanks I found it, and fixed my problem! However there is a problem with the UI because nothing is written, it is an empty space, that's why I didn't find it by myself. 
![dsc_0313](https://user-images.githubusercontent.com/27021339/52507976-69960f00-2bf3-11e9-895e-4dcb0c2d05a3.JPG)

**Comment by JosefNemec** [comment]
What desktop resolution do you have? The window has 830x700 pixels dimensions so I find it weird that it doesn't fit completely on your screen.

**Comment by Kvaell** [comment]
> What desktop resolution do you have? The window has 830x700 pixels dimensions so I find it weird that it doesn't fit completely on your screen.

You right, my desktop (handheld computer) resolution is 1024x600

**Comment by JosefNemec** [comment]
I've made multiple changes to this and minimum window height is now 480.
