### ISSUE TITLE
Playnite is unable to import uninstalled games from Itch.io

### ISSUE THREAD

**Issue by ClearStrelok** [JosefNemec/Playnite#984]
Using the latest version (25.4.0) so the issue should be elsewhere. I'll try to reinstall both applications to see if this solves anything. 

![itch](https://user-images.githubusercontent.com/38838369/52496087-ba494000-2bd2-11e9-932f-81b281d7074b.png)

This reads as : "Object reference not set to an instance of an object"

**Comment by JosefNemec** [comment]
Can you go to `About` menu and create diagnostics package for me please? Thank you

**Comment by ClearStrelok** [comment]
Here it is : 

c8184d17-cda6-4faa-a469-9bc96d243b7d

**Comment by JosefNemec** [comment]
Can you please test it with [this build](https://playnite.link/download/ItchioDebug.zip) and generate new diag. package for me? Thank you

Please do not override your main installation with it, but rather extract it to a different folder.

**Comment by JosefNemec** [comment]
Fixed in 4.72
