### ISSUE TITLE
Better horizontal resizing for game descriptions

### ISSUE THREAD

**Issue by FireFtw** [JosefNemec/Playnite#990]
While game descriptions do resize respective to the horizontal width and even eventually disappear there is [a weird in between where it is completely unreadable but still there](https://user-images.githubusercontent.com/6172118/52524184-fa0a3900-2c5f-11e9-9d42-fddf3ce6e3ff.PNG). At some point before the text box is completely hidden but the text is unreadable the text should either disappear or be moved to below the game information.

**Comment by JosefNemec** [comment]
This shouldn't an issue anymore since the layout has completely changed in Playnite 5.
