### ISSUE TITLE
Itch.io Games are not imported.

### ISSUE THREAD

**Issue by Nytuo** [JosefNemec/Playnite#994]
Hello,
I can't import games from itch.io to playnite (whether installed or not), I'm told that itch.io is not installed in the last version when it is.
![capture d ecran 27](https://user-images.githubusercontent.com/34894524/52532339-9ba68e80-2d23-11e9-9612-a7af911ac4a9.png)
Thanks for answering.
(Sorry for my bad english).
-Nytuo

**Comment by JosefNemec** [comment]
It says in the error message you get in Playnite's popup. You need to have Itch client version 25 and newer installed. Apparently [there's some issue](https://github.com/JosefNemec/Playnite/issues/107#issuecomment-461964182) with Itch client not auto-updating to 25,you will need to re-install it manually.

**Comment by Nytuo** [comment]
Yes but Itch.io is in the last version (25.4.0) and i have already re-install Itch.io yesterday.
![itch](https://user-images.githubusercontent.com/34894524/52532439-69962c00-2d25-11e9-804e-7a1630fdcab1.PNG)
-Nytuo

**Comment by JosefNemec** [comment]
Can you attach `%localappdata%\itch\state.json` file here please? Also please go to `About` menu and create diagnostics package. Thank you

**Comment by Nytuo** [comment]
Sorry for late.
I disable MalwareByte and Playnite now detect the itch.io games.
-Nytuo
